### ISSUE TITLE
side bar workspace can't be closed if no one is open

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#1000]
Currently : 

- if only one workspace is open, then clicking on it closes it and reopen it as soon as it is closed
- this is the case if one workspace only, but also if several workspaces and all are closed

Expected :

- do have the standard behavior : if clicked when open, then close it (and stay closed)

**Comment by PhilippeAccorsi** [comment]
Fixed with this issue https://github.com/tracim/tracim/issues/1016

**Comment by PhilippeAccorsi** [comment]
Verified.
