### ISSUE TITLE
Add API endpoint returning all error code.

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1006]
## Current situation

Currently error code are not visible in rest API, only in error.py file.

## Expected

Create an API endpoint publishing list of error code.

**Comment by inkhey** [comment]
Many way to deal with  "how to obtain error list" issue :
- Get list of error from exceptions, need to find a way to get all exceptions from exceptions.py with error_code..
- Introspect error.py in order to get constant name.
- Convert error.py into enum (probably the easiest).

**Comment by inkhey** [comment]
https://github.com/tracim/tracim/pull/1461 fix the issue using Enum.

**Comment by PhilippeAccorsi** [comment]
Verified.
