### ISSUE TITLE
LibreOfficeOnline Support

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1007]
**Is your feature request related to a problem? Please describe.**
There actually no such thing as online office file editor in Tracim.

**Describe the solution you'd like**
Make Tracim compatible with LibreOfficeOnline. This means a specific app in Tracim and be able to run LibreofficeOnline.

**Comment by inkhey** [comment]
## Setting up LibreOfficeOnline, somes infos

run docker image of LOO:

> docker run -it --name lool -p  127.0.0.1:9980:9980 -e "domain=127\.0\.0\.1" -e "username=admin" -e "password=admin" libreoffice/online:master

 ("-p  127.0.0.1:9980:9980 -e "domain=127\.0\.0\.1" need to be change according to server)

run bash inside docker image:

> docker exec -it lool bash

### go to file
`https://localhost:9980/loleaflet/7b90179/loleaflet.html?path=https://url_of_the_file.odt`

for local file:
`https://localhost:9980/loleaflet/7b90179/loleaflet.html?file_path=file:///path/of/the/file.odt`

## Config

conf file path is `  /etc/loolwsd/loolwsd.xml`

### logging

Logging on file can be setup in `<logging>`  with ` <file enable="true">` , logging level can also be changed.

check log:

`docker exec -it lool tail -f /var/log/loolwsd.log`

### Admin console

setup `<username>` and `<password>` in `<admin_console>`.

go to admin console : 
`https://[ip_address]:9980/loleaflet/dist/admin/admin.html`

**Comment by inkhey** [comment]
## About file limitation (number of file, number of connexion simultaneously) 

If we want to modify file limitation , this need to recompile loolwsd websocket server of libreofficeOnline with --with-max-connections and --with-max-documents options.

and easiest way to do the same is to use https://github.com/husisusi/officeonlin-install.sh
like this : 

`./officeonline-install.sh -c lool_maxdoc=100000 -c lool_maxcon=1000000`

**Comment by lebouquetin** [comment]
@inkhey pense aussi à mettre le contenu du mail qui explique comment modifier les limitations du nombre de user

**Comment by lebouquetin** [comment]
This work has started through a contribution from @kmarilleau

**Comment by inkhey** [comment]
this "big" feature is provided in #2139 PR.

**Comment by PhilippeAccorsi** [comment]
@inkhey do you have tested with libreofficeonline or just with collaboraonline?

**Comment by PhilippeAccorsi** [comment]
to start libreoffice on local:

`sudo docker run -d -t -p PORT:PORT -e "domain=IP_OF_TRACIM_API" -e "username=admin" -e "password=S3cRet" -e "SLEEPFORDEBUGGER=0" -e "extra_params=--o:ssl.enable=false" --cap-add MKNOD --restart always libreoffice/online:master`

**Comment by PhilippeAccorsi** [comment]
Its working with tracim (like collabora. Need more test to make sure everything working good.

**Comment by PhilippeAccorsi** [comment]
this parameter `collaborative_document_edition.software` in development.ini need to accept libreoffice when we use libreoffice online.

At present we need to use this config `collaborative_document_edition.software = collabora`.

**Comment by PhilippeAccorsi** [comment]
Also this parameter is not clear `collaborative_document_edition.collabora.base_url = http://192.168.1.150:9980`. This is not just for collabora but for each office tool.

**Comment by PhilippeAccorsi** [comment]
Some information to know how to use libreofficeonline docker image https://hub.docker.com/r/libreoffice/online

**Comment by PhilippeAccorsi** [comment]
verified.
