### ISSUE TITLE
Show workspace name in calendars instead of id 

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#101]
Currently, caldavzap show 30.ics or 230.ics or similar calendar names.
We need to show associated workspace names.

@buxx : add an api endpoint that will return workspaces in json.

```
GET /api/workspaces
{
    "value_list": [
        { "id": 30, "label": "my calendar", "description": "blablabla", "has_calendar": "true", },
        { "id": 230, "label": "my calendar other", "description": "blablabla 230", "has_calendar": "true", },
    ]
}
```

Code de retour 200 si OK, ou 400/500, etc.
En cas d'erreur, on retournera un structure

```
{
    "code": 400
    "msg": "invalid parameter"
    "detail": {}
}
```

Ajouter un endpoint plus spécifique aux calendriers qui ne renvoie que les workspaces pour lesquels les calendriers sont activés :

```
GET /api/calendars
{
    "value_list": [
        { "id": 30, "label": "my calendar", "description": "blablabla 230",},
        { "id": 230, "label": "my other calendar", "description": "blablabla 230",},
        { "id": 20, "label": "Name of the user", "description": "my personnal calendar",},
    ]
}
```

Endpoint à tester en auto (cas de tests unitaires à implémenter)

On utilisera avantageusement le concept de routing et/ou EasyRestCrudControlleur (si c'est utile... à discuter)
- http://turbogears.readthedocs.io/en/rtfd2.2.2/main/Config/Routes.html
- http://turbogears.readthedocs.io/en/latest/cookbook/Crud/restapi.html

Transférer ensuite à Come pour qu'il intègre en JS le renommage des calendriers à partir de l'API

**Comment by buxx** [comment]
And about the personal calendar actually displayed as "<user_id>.ics ?

**Comment by buxx** [comment]
@Skylsmoi L'api est dispo, cf. https://github.com/tracim/tracim/blob/master/API.md
