### ISSUE TITLE
add persistance of language config in a cookie

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1012]
for 2.0, we only set default language from navigator.language

after that, we need

- [x] a cookie that save the default language.
- [x] the frontend must update the backend with language used in the user interface. I mean, if the UI is in french and the backend is not aware of french for current user, then frontend must update backend.

**Comment by Skylsmoi** [comment]
see https://github.com/tracim/tracim/issues/747

**Comment by Skylsmoi** [comment]
cookie for default language has been added
cookies usage has been refactored with constants

**Comment by PhilippeAccorsi** [comment]
Verified.
