### ISSUE TITLE
member list: its possible for one member to remove is own name from this list

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1013]
At present

Its possible for one member to remove is own name from list. After that tracim not working: dashboard stay open, admin page is not accessible.

expected

Its not possible to remove is own name from list of member.
Backend need to make unit test for that

**Comment by PhilippeAccorsi** [comment]
@inkhey MR #92 is about what damien have done yesterday evening?

For you, backend it ready?

If yes, can you change label to frontent and assigne skylsmoi.

**Comment by inkhey** [comment]
@PhilippeAccorsi Your link was uncorrect. MR is almost ready no and fix thoses issues.

**Comment by PhilippeAccorsi** [comment]
Verified.
