### ISSUE TITLE
check that all the rules of law are respected in api

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1015]
At present

Some controls is make directly in frontend. ex: admin can't deactivate is own account.

Expected

Verify if all unit test is make in backend to prevent the security breach if one request is send directly to backend.

- [ ] User profile and member role need to be verified directly in backend.
- [ ] User can't deactivate is own account
- [ ] member can't remove himself from member list

**Comment by inkhey** [comment]
Not sure to understand what to do with this issue, lack of control have #1013 and #1014 issue, other endpoint have many functional tests for profile and roles. Their may be error somehow but i do not see easy way to verify this.

"All unit test look really unclear" to me.
The only lacking thing is this:  https://github.com/tracim/tracim/issues/709 . This prevent decorator to work correctly but this do not prevent endpoint X to have uncorrect decorator.

**Comment by PhilippeAccorsi** [comment]
@inkhey If you think all case is done with the MR, its ok.
This issue is to verify if all security is done directly in api.

We have find some case (with specific issue) but if you now more case, you can fix here. Maybe all is in your MR.

**Comment by PhilippeAccorsi** [comment]
@inkhey I have find something for this issue:

For all content: if I change status to "deprecated" for exemple, its not possible to change something in this content.
For the moment its possible to modify content with some different status.

**Comment by PhilippeAccorsi** [comment]
@lebouquetin 

Par défaut le backend empêche la modification d'un document html par exemple, avec le statut obsolete, mais il est toujours possible d'ajouter un commentaire (ce qui peut-être très pratique).

Par contre une discussion est composé seulement de commentaire, et donc changer le status de la discussion n'emêche pas de rajouter des commentaire.

Faut-il un comportement particulier pour les discussion ou alors revoir le comportement des commentaire de chaque application?

**Comment by lebouquetin** [comment]
For now, comment must be allowed only on éditable contents.

@inkhey for authentication/authorization checks, its your responsibility of developer to check that all routes have checks and associated unit tests.

**Comment by lebouquetin** [comment]
If you want @PhilippeAccorsi to tell you what to fix, then give him a list of endpoints and associated authentication and authorization check you implemented

**Comment by PhilippeAccorsi** [comment]
Verified.
