### ISSUE TITLE
workspace advanced: sidebar is closed after modification in description (access from admin workspace)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1016]
At present

If you open advanced workspace from admin workspace and if you edit description, after validation the sidebar is close. If you open advanced workspace from dashboard, after edit description and validation the sidebar stay in last state.

Expected

If description is edit, the sidebar stay open if its last state.

**Comment by Skylsmoi** [comment]
related: https://github.com/tracim/tracim/issues/755

**Comment by PhilippeAccorsi** [comment]
Verified.
