### ISSUE TITLE
Add member: do not show users that are already in the workspace

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1018]
At present:

When you want to add a member to a workspace, you can type few letters in order to get an auto-complete of available users.

Currently, this auto-complete listing also show users that are already in the workspace.

Expected:

- [x] Frontend: do not show users already member of the current workspace
- [X] Backend add two optionnal query filters in the `/api/v2/users/{user_id}/known_members` endpoint : 
    - [X] exclude_space_ids : if set, then exclude users already member of a given workspace : parameter is a comma-separated list of ids. Example: `3,4` will exlude from returned list all users being member of 3 and also exclude all users being member of 4
    - [X] exclude_user_ids : same behavior but with user id (optionnal)

Idea: when you want to add some member, the searchlist  decrease when you add member.

- [ ] assign to @Skylsmoi when backend is ready and remove label backend.

**Comment by PhilippeAccorsi** [comment]
@lebouquetin thats ok for you?

**Comment by PhilippeAccorsi** [comment]
@inkhey the result of research not working.
I'm an admin with role workspace manager

I have 3 account wtih test in name or email

If I type test => result is testtest
If I type test1 => result is test1
If I type test2 => result is test2

Expected: If I type test I can see this result:
testtest
test1
test2

**Comment by Skylsmoi** [comment]
frontend now filter users that are already in the current workspace

**Comment by Skylsmoi** [comment]
@lebouquetin will I have to remove my filter and use the query parameters when it is ready ?

**Comment by lebouquetin** [comment]
@Skylsmoi My feeling is : "it would be better to use query parameters", do you agree?

**Comment by Skylsmoi** [comment]
Yes. I was just hopping you had a good reason to not using it. That would have implied less work for me : >

**Comment by Skylsmoi** [comment]
to test: check that the autocomplete when adding members to a workspace doesn't display members that already are in the workspace

**Comment by PhilippeAccorsi** [comment]
Verified.
