### ISSUE TITLE
Dashboard and advanced workspace: Add member => add different Icon

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1020]
At present

We can see warning icon all the time 

Expected

- [ ] replace the light-bulb by a warning for when email notif are deactivated

**Comment by Skylsmoi** [comment]
I dont understand what icon you are talking about, please add screenshots

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi I have put an exemple.

**Comment by Skylsmoi** [comment]
todo:  
replace the light-bulb by a warning for when email notif are deactivated

**Comment by PhilippeAccorsi** [comment]
Verified.
