### ISSUE TITLE
Add member: button to add member is not really accessible if you have a big list of member

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1025]
At present

The button to add member is at the end of member list but if you have lot of member the button is not accessible without scrolling a long time.

Expected

- [ ] The position of this button is before the list

- [ ] make a see more button like we have in recent activity.

**Comment by lebouquetin** [comment]
@gbonaspetti we talked about this issue... but in another MR / issue... do you remember where?

**Comment by gbonaspetti** [comment]
@lebouquetin it was at https://github.com/tracim/tracim/issues/1513

**Comment by PhilippeAccorsi** [comment]
I close this issue. all necessary information are in related issue.
