### ISSUE TITLE
sidebar entry routes seems not to be used from API

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#1027]
The endpoint returning /api/v2/workspaces and /api/v2/users/:id/workspaces returns the list of sidebar_entries : 

```
"sidebar_entries": [
      {
        "fa_icon": "file-text-o",
        "hexcolor": "#F0F9DC",
        "label": "Markdown Documents",
        "route": "/#/workspace/{workspace_id}/contents/?type=mardown-page"
    }
```

Unfortunately: 

- route is wrong (the `/#` prefix should be removed)
- the frontend seems not to use this route. It should.

Expected:

- in backend, update the routes
- in frontend use these routes in order to setup sidebar entries.

**Comment by Skylsmoi** [comment]
Frontend does use this endpoint.  
Sidebar entries are used to generate sidebar  
frontend manually removes the '/#' from routes

I'd say this is mostly a backend issue.  
Frontend will only have to remove the hack that removes the '/#' when backend in ready

**Comment by lebouquetin** [comment]
ok. good news. lets fix it right now.

**Comment by lebouquetin** [comment]
The MR has been merged. @Skylsmoi the issue is now on your side.

**Comment by Skylsmoi** [comment]
done

**Comment by Skylsmoi** [comment]
to test:  
check that every links in sidebar works properly

**Comment by PhilippeAccorsi** [comment]
Verified.
