### ISSUE TITLE
CaldavZap credentials: 401

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#103]
> jquery-2.1.4.min.js:4 PROPFIND http://algoo.trac.im/caldav/workspace/ 401 (Unauthorized)

**Comment by tracim** [comment]
Bux, il faut une description sur ce bug (incompréhensible à part pour toi probablement)

**Comment by buxx** [comment]
En effet c'est pas compréhensible du tout ... C'étais un note perso (ce qui ne devrais pas être fait sur le bug tracker tout à fait ^^). Le bug correspond à un problème d'authentification corrigé depuis. C'était la configuration nginx de notre serveur algoo.trac.im qui récrivait mal les urls.
