### ISSUE TITLE
Refactor routes of the API

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#1031]
The attached file is a list of routes to be defined as the tracim v2 API.
This is in majority about refactoring the endpoints (but there are also some duplicates for distinguishing logged in user from standard user)

**Comment by lebouquetin** [comment]
[routes.new.xlsx](https://github.com/tracim/tracim/files/2480575/routes.new.xlsx)

**Comment by PhilippeAccorsi** [comment]
@lebouquetin I assign this to inkey?

**Comment by Skylsmoi** [comment]
I added "blocked by backend" to show that backend should do it's part first

**Comment by Skylsmoi** [comment]
updates in front:
- frontend: dashboard known members
- frontend: account update name
- frontend: account update email
- frontend: account update password
- app_admin: admin user update self profile
- frontend: login get workspace list
- frontend: tracim get workspace list (load tracim while already connected)
- frontend: dashboard get content read status
- frontend: workspace get content read status
- frontend: dashboard update read status
- frontend: dashboard get recent activity list
- frontend: account change notification
- frontend: dashboard change notification
- app_file: all previews url
- app_file: all download url (pdf or not)
- frontend: login
- frontend: logout
- frontend: reset password (all process)
- app_admin: admin user enable / disable user
- app_admin: delete workspace
- app [html-doc, thread, file]: delete/restore content
- app [html-doc, thread, file]: archive/restore content

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi all check box are validated?
If yes put this issue directly in need test.

**Comment by Skylsmoi** [comment]
@PhilippeAccorsi I have tested all of them but I have created them for you since there is many things to test

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi missing endpoint:

frontend: advanced dashboard delete workspace

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi last comment about what is not ready.

**Comment by PhilippeAccorsi** [comment]
Verified.
