### ISSUE TITLE
translation and/or translation key is missing

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1033]
**member list:**

- [x] Shared space manager (role is not translate)

**My account > notification:**

- [x] Shared space manager (role is not translate)

**Add member:**

- [x] Email notifications are disabled, you can't create new users from here

**Add user:**

- [x] Warning Please type a name, an email and select a profile
(For this flash message we need to add password and translate all)

**Comment by lebouquetin** [comment]
try to avoid words like "trad" which have no meaning for most of people . Especially when you write in English (the english word is translation, not traduction). Do not forget that tracim is open source and bugtracker visible by virtually the whole world.

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi In memberlist, after public_name, the role stay in english.

**Comment by PhilippeAccorsi** [comment]
Verified.
