### ISSUE TITLE
forgot password: redirect to page for changing password show warning email notification not activated

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1039]
At present

When I forgot my password, I type my email and I receive an email with link to reset password.
When I open this link, I can see in the header the warning message about email notification not activated (but its activate because I receive an email).

Expected

- [x] Don't show warning in header of password reset page

**Comment by lebouquetin** [comment]
This warning should be shown only if configuration tells "email.notification.enabled = False". @Skylsmoi why do you show this notif in this case?

**Comment by lebouquetin** [comment]
I mean... there is no default case : 

- if notifs disabled : show warning
- if notifs enable : do not show warning

That's it

**Comment by PhilippeAccorsi** [comment]
@lebouquetin do you think its good to show warning in login page or password reset page?
for me its just an information when you are logged.

**Comment by Skylsmoi** [comment]
@lebouquetin I can't know whether notif are enabled or not if you are not logged in since I get 403 on any api request.  
So it's just a small bug

**Comment by PhilippeAccorsi** [comment]
Verified.
