### ISSUE TITLE
member list: remove my own name show 2 different flash message (in dashbord or in advanced workspace)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1041]
**At present**

- If I try to delete my own name in member list in advanced workspace I have this error:

Information
Error while removing user from shared space

- If I try to delete my own name in member list in dashboard I have this error:

Warning
Error while removing the member

**Expected**

- [ ] Don't show or make readonly the delete button at end of member name if you don't have right to delete or if its you'r own account.

**Comment by Skylsmoi** [comment]
I have normalized the 2 error msg  
In a previous commit, I also have removed the delete btn on yourself

**Comment by PhilippeAccorsi** [comment]
Verified.
