### ISSUE TITLE
Apps crash if translation keys contains a dot "."

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1045]
currently: if there is a dot "." in a translation key somewhere, it might generate js error during the resource loading of the translations list from apps.  
  
I haven't exactly identified the issue, sometimes, the dot doesn't seem to cause any issues. But usually, when I get the crash, removing the dots from translation keys fixes everything.  
  
The js error appears in i18n library during the i18n.addResources() from frontend_lib which is called by every apps on mount by the function addAllResourceI18n() in the constructor. 
  

- Short term solution: Avoid dots in translations keys at all cost. Use coma separation instead. Split keys if necessary. You can also add the dot outside of the key, in the jsx, eg: `<span>{props.t('Welcome home')}.</span>` instead of `<span>{props.t('Welcome home.')}</span>`

- Middle term solution: Run a script after any build-translation that check that no translation keys contains a dot.  
  
- Long term solution: Refactor translation process to identify keys from js object property instead of string. Eg: `props.t(Header.User.Disconnect)` instead of `props.t('Disconnection')`

**Comment by Skylsmoi** [comment]
I'm already applying short term solution.  
Todo: do the middle term solution

**Comment by Skylsmoi** [comment]
After some researches, it appears that the crash appears when there is the same translation key on different apps with some containing a dot and some not.

This information was discovered during the fix of https://github.com/tracim/tracim/issues/1373

The keys that were causing trouble were "This content is archived" and "This content is deleted".
On some apps they had a dot and on some other they didn't.

Harmonizing theses keys then rebuilding translation on every apps (`npm run build-translation`) removed any crash.

**Comment by lebouquetin** [comment]
@Skylsmoi translations should be allowed with a dot inside. Is this really forbidden?

**Comment by basilelegal** [comment]
@Skylsmoi I cannot reproduce, I changed a translation present in 2 apps, added a dot in one but not in the other app and it wouldn't crash.

**Comment by gbonaspetti** [comment]
Verified.
