### ISSUE TITLE
Travis: run travis test with other database

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1046]
**Is your feature request related to a problem? Please describe.**
Run travis tests on postgresql, mysql and sqlite.

**Comment by lebouquetin** [comment]
if possible : 

- execute tests on sqlite
- if success, execute on postgresql
- if success, execute on mysql

Do it on python 3.6 only for now

**Comment by lebouquetin** [comment]
also, do we test on python 3.7 ?

**Comment by lebouquetin** [comment]
@inkhey you told me this issue wwas fixed, no?

**Comment by PhilippeAccorsi** [comment]
Verified.
