### ISSUE TITLE
add minimum number of letter for public name, password and email

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1050]
At present

You can hace user with just one letter in public name but if you need to add this user in one workspace you cant find this user because frontedn send request to backend when we type minimum 2 letters.

Expected

- [ ] define a minimum/max of necessary letter for the public name.
- [ ] define a minimum/max of necessary letter for the email.
- [ ] define a minimum/max of necessary letter for the password.

**Comment by tracim** [comment]
We must allow 3 chars minimum. This is to implement on backend side first.

**Comment by PhilippeAccorsi** [comment]
@inkhey please assign @Skylsmoi when you change label. This issue is available for frontend since 7 hour but frontend dont know that.

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi in my account if I tried to change name with less than 3 caracter i can see this message: `Warning
Error while changing name`

Expected

- [ ] Have same flash message that we have in add user `Warning
Full name must be at least 3 characters`

**Comment by Skylsmoi** [comment]
added in my account and admin account

**Comment by PhilippeAccorsi** [comment]
Verified.
