### ISSUE TITLE
Sidebar: if one workspace is open, its impossible to close the sidebar

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1051]
At present

You can close the sidebar if you have close all workspace before in the sidebar.

Expected

Its possible to close the sidebar all the time.

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi Do you think its a fast issue (with label fast).

**Comment by Skylsmoi** [comment]
fixed here https://github.com/tracim/tracim_v2/commit/9e89d9d78e127e6b8d1dcf857947be8c24efd85f

It was a quick issue

**Comment by PhilippeAccorsi** [comment]
Verified.
