### ISSUE TITLE
Make some libraries dependency "importable" for other React Apps in the webpage

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1059]
Now:
Apps are imported by tracim_v2 through script tags.

Since then, we can't externalize apps's libraries using webpack because apps wont be able to import it since they are bundled in a different React app.

So every apss will have React, frontend_lib, i18n, babel ... in their build which is really heavy and no optimized.

Expected:
Tracim_v2 libraries are accessible by other React app in the browser so that we can externalize libraries in every plugin dividing plugin size.
Other possibility is to build frontend and all apps using another webpack.config.js that could optimize this. But I don't know if this is possible

**Comment by Skylsmoi** [comment]
this issue has been imported from https://github.com/tracim/tracim_frontend/issues/7

**Comment by Skylsmoi** [comment]
Just found a possible solution to look at for this issue:
https://www.pika.dev/cdn

I haven't dug into it right now.

**Comment by inkhey** [comment]
@Skylsmoi is this issue still up to date ?

**Comment by Skylsmoi** [comment]
No.
Since we have the "optimized" build system, this issue can be closed
