### ISSUE TITLE
wrong lang initialization after login

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1062]
If I switch language to french before login, after login, the language is in french but the language button has english selected

**Comment by PhilippeAccorsi** [comment]
Its the same when you logout.
If you have choice french with button, after logout the language in button is english but all text is in french.

**Comment by PhilippeAccorsi** [comment]
Verified.

**Comment by PhilippeAccorsi** [comment]
By default new user don't have default langage in bdd and its a problem for frontend when you are changed de login langage. 
Sometime you have some part of frontedn in english and other part in french.

**Comment by Skylsmoi** [comment]
frontend now detect browser language + fixed missing translation + fixed role and profile translation

**Comment by PhilippeAccorsi** [comment]
Verified.
