### ISSUE TITLE
admin user: add user: replace "name" by an explicit text

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1063]
At present

When we add a user, the first input is "name" but we don't know if its just name or name + surname or something else.

Expected

Input name is for public_name

- [ ] change "name" by an explicit text about possibility in this input

- [ ] change also in my account

Idea:
- username
- firstname/lastname

**Comment by tracim** [comment]
Use *nickname* or *username* for example.

**Comment by Skylsmoi** [comment]
I thinks it's better to use the wording "Full name" and "Display name" (same as Slack)

**Comment by tracim** [comment]
Here the concet is more "display name" than "full name" (as its the publicly visible name)
Hm... What is the translation of "display name" in french in Slack? @Skylsmoi

**Comment by tracim** [comment]
use "full name" and "Nom complet"

**Comment by tracim** [comment]
it sounds a bit strange "change your full name", no?

**Comment by PhilippeAccorsi** [comment]
Is it a good idea to use full name in create user form? and another word in my account and in add member. Its not easy in documentation to explain fullname and name its the same but with two diffent word.

**Comment by Skylsmoi** [comment]
@tracim I think it's a bit odd yes, that's why I'm asking you

**Comment by tracim** [comment]
So, do we still need to discuss this?

**Comment by Skylsmoi** [comment]
no. I put it in "need test"

**Comment by PhilippeAccorsi** [comment]
Verified.
