### ISSUE TITLE
Clicking on the same status in the dropdown generate a new revision

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1067]
when changing status of a content, if we select the same status, it generate a new revision

**Comment by tracim** [comment]
- Must generate a HTTP 400 in the API. @inkhey it's job for you in first.
- Then disable the feature in the UI. @Skylsmoi it's for you.

@inkhey assign the issue to @Skylsmoi as soon as your backend development is finished.

**Comment by basilelegal** [comment]
#1528 Fix the API

**Comment by basilelegal** [comment]
@Skylsmoi You need to refactor handlers for status changes for apps `file`, `htmldoc` and `thread`

**Comment by basilelegal** [comment]
merged

**Comment by PhilippeAccorsi** [comment]
Verified.
