### ISSUE TITLE
impossible to reopen an archived or deleted content avec having archived or deleted it

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1068]
before we could access it using the exact url
  
now nothing opens, no error message
  
this behavior is consistent with deletion but a bit misleading for archived content.
  
that issue will self solve itself when we'll be able to filter archived and deleted content
  
possible solution, remove the "archive" feature, from tracim, allow only deletion, until we have a better solution ? like in 2.1

**Comment by PhilippeAccorsi** [comment]
@lebouquetin possible solution, remove the "archive" feature, from tracim, allow only deletion, until we have a better solution ? like in 2.1

Other solution its to make not clickable the archive button and for Capitole du libre we can explain why this function is deactivated for the moment.

**Comment by Skylsmoi** [comment]
The archived feature has been removed
closing this issue
