### ISSUE TITLE
hide enable/disable email subscription buttons if email notification are deactivated in backend

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1069]
currently, we can set email notification subscription on workspaces even if emails are deactivated by backend

It doesn't make a lot of senses

- [x] deactivate in dashboard
- [x] deactivate in my account > notification
- [x] login page -> forgotten password

**Comment by tracim** [comment]
The right way to fix this is probably to hide the information and link in all related screens (dashboard and user profile)

**Comment by PhilippeAccorsi** [comment]
Verified.
