### ISSUE TITLE
app file: allow button left and right (< and >) on app file for when the content is in fullscreen (using lightbox)

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1071]
currently, when we click on a file content, it opens in fullscreen but even if the content has many pages, we must close the fullscreen, switch page then reopen fullscreen mode

it would be better to be able to switch pages directly from lightbox (the fullscreen js library)

**Comment by PhilippeAccorsi** [comment]
If its done yet in V2.0, please change milestone and project to 2.0

**Comment by Skylsmoi** [comment]
done in 2.0.
@PhilippeAccorsi I let you test and close please

**Comment by PhilippeAccorsi** [comment]
Verified.
