### ISSUE TITLE
reduce header height, most important for small screens

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1074]
currently, the header height is always the same regardless of the screen size

expected, reduce the header height for some small screen size

**Comment by lebouquetin** [comment]
@Skylsmoi how did you fix the header size? there are no information about the way you fixed it, so reviewing the code is impossible (or it as no sens).

Could you explain here what you have implemented?

**Comment by lebouquetin** [comment]
By the way, everything which is design is quite impossible to review without to have a screenshot. Is it possible to add screenshot about what you fixed?

**Comment by Skylsmoi** [comment]
I reduced the header height by reducing a lot of margin-top/bottom and by reducing the font size

**Comment by lebouquetin** [comment]
In the description you write:

>expected, reduce the header height for some small screen size

So :

- what are the breakpoints you take into account now and what is the size of the header in these cases? (this is required for @PhilippeAccorsi to test)

**Comment by lebouquetin** [comment]
If you have no clear rule (which should not - you took decisions during your development, theses decisions must be visible in the issue), at least some screenshots will help test your fix

**Comment by Skylsmoi** [comment]
I did it for every screen sizes.
We agreed on the fact the header is too wide even on desktop.
I should have changed the issue description

**Comment by PhilippeAccorsi** [comment]
Some problem with header.
- Sometime the margin right for account button is not the minimal value that we have in desktop resolution (1024 for exemple)
- And other problem visible on screenshot here. Sometime text is broken (and scroll horizontally available with broken background)

Test with firefox on desktop.

At 575:
![575](https://user-images.githubusercontent.com/25848257/56727559-332b5300-6751-11e9-8a8b-540dede969fa.jpg)

At 576:
![576](https://user-images.githubusercontent.com/25848257/56727570-39b9ca80-6751-11e9-8134-b33affb5349b.jpg)

At 767:
![767](https://user-images.githubusercontent.com/25848257/56727580-42aa9c00-6751-11e9-90db-83813d87ea0d.jpg)

At 768:
![768](https://user-images.githubusercontent.com/25848257/56727590-4a6a4080-6751-11e9-9251-daeeb11a5031.jpg)

**Comment by PhilippeAccorsi** [comment]
Exactly the same problem on Chrome.

**Comment by gbonaspetti** [comment]
I change the breakpoint for not showing the dropdown menu from md to lg, change the breakpoint for show in two lines from xs to sm and add a padding in sm and xs screens.

**Comment by PhilippeAccorsi** [comment]
@gbonaspetti Between 576 and 602 when we select account button we can see blue selection is above other button.

![chevauchement](https://user-images.githubusercontent.com/25848257/57780090-d1468380-7727-11e9-8a76-2664c61985d3.gif)

**Comment by PhilippeAccorsi** [comment]
Verified.
