### ISSUE TITLE
html-doc: wrong behavior when saving new content label when content has no revision

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1075]
currently, when saving new label on a content that has no revision (except the creation one) it also save the content because it is in edition mode (with tinymce opened)
Since it create a revision, the content doesn't have only one revision anymore and switch to view mode (close the tinymce editor)

expected, saving the label saves only the label

**Comment by lebouquetin** [comment]
Since it create a revision, the content *doesn't have only one revision anymore and switch to view mode* (close the tinymce editor)

@Skylsmoi the edit/view mode should not be based on first or not first revision but on "the document body has always been empty".

**Comment by Haskaris** [comment]
Can't reproduce.
