### ISSUE TITLE
all app: we can still change content label when contents are archived or deleted

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1076]
currently, if I archive or delete a content, I can still change it's label

Is this the expected behavior ? It might be confusing

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi I see also an another but, if you archive and unarchive when app is open you don't see label changing. But when you close the app, the label is changed and label append "-archived-2018-10-26T17.12.04.759299"

**Comment by Skylsmoi** [comment]
I see.
Todo: refresh app content after archiving and/or trashing

**Comment by tracim** [comment]
@Skylsmoi is this fixed?
@inkhey is it fixed on backend?

**Comment by Skylsmoi** [comment]
frontend part is fixed

**Comment by inkhey** [comment]
backend part is also fixed since 3cab4ad

**Comment by PhilippeAccorsi** [comment]
Verified.
