### ISSUE TITLE
admin account page, refresh datas after saving a modification to refresh the displays

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1078]
currently, when saving a modification of the user public_name or email, the top part that recap user's data isn't refreshed

expected, the top part should show the changes after save

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi for your information: if you access on this page with an admin account and with workflow admin user > account of user, if you change public_name or email the refresh working good.

Maybe its just a small missing code.

**Comment by Skylsmoi** [comment]
It is indeed two different components `<Account>` and `<AdminAccount>`

**Comment by Skylsmoi** [comment]
I have set it to 2.0 since this issue if referenced by an issue that is for 2.0. See #1031

**Comment by PhilippeAccorsi** [comment]
Verified.
