### ISSUE TITLE
Add support for folder:  full support

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1082]
At present

Migration is not really possible from v1 to v2 because we can't have folder in v2.0

Expected

- [x] its possible to show folder in app

- [x] its possible to edit/add/delete content in folder

**Comment by Skylsmoi** [comment]
for test:
- this dev is on the branch `1082/dev/folder_support`
- you need to update your backend/development.ini and edit `app.enabled` to add "contents/folder"
- App folder advanced (to edit folder name and content type available inside it) is NOT implemented
- If a content is open, it's path in the workspace should have all it's folders open and their contents loaded (unless you close a folder after opening the content)
- url should be kept synced with workspace's state. That means that if you full refresh the page (f5), the previously opened folders should be opened on page load (all opened folders are in the GET param 'folder_open')
- verify workspace filters. Combining their mechanism with the 'folder_open' GET param was a bit tricky. Switching from workspace filters to others should keep the url clean: get params doesn't multiply themselves.
- check popup create content. For the same reasons as above

**Comment by Skylsmoi** [comment]
before testing, I need to implement the advanced folder app

**Comment by Skylsmoi** [comment]
For app advanced folder, I'm waiting for this fix to validate the process of checking and unchecking content type available in the folder
https://github.com/tracim/tracim/issues/1158

**Comment by PhilippeAccorsi** [comment]
For me folder working. Issue about folder is in sort, no big bug detected.

@Skylsmoi @lebouquetin do you think its possible to save which folder is open in each workspace? At the moment if I go in one workspace, I lost folder open in preview workspace.
if I work on 2 content in different worksapce (and this content is in folder) I can move quickly from one content to another.

Maybe the solution for this is to open content in different tab?

**Comment by Skylsmoi** [comment]
it'll be complicated. Possible but might require some time.
We will need to save opened folder in redux and sync the url get params with it

**Comment by PhilippeAccorsi** [comment]
Verified.
