### ISSUE TITLE
recent activity: improve view for new/updated content

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1084]
**At present**

In list of recent activity the new/updated content is show in bold and its not very easy to see difference with not new/updated content.

![bold_recent_activity](https://user-images.githubusercontent.com/25848257/47552688-97399f80-d905-11e8-96d5-ff73a0a4b6d4.png)

**Expected**

Idea:
Improve this view by added badges => https://getbootstrap.com/docs/4.1/components/badge/

**Comment by tracim** [comment]
The idea is both for last activity and for content views.

![image](https://user-images.githubusercontent.com/9657115/48726273-20a36f80-ec2f-11e8-8dd7-b989c738535a.png)

**Comment by tracim** [comment]
Note: if name is too long, the new label must be over the label

**Comment by lebouquetin** [comment]
As of tracim 2.1, showing text in bold is enough.
