### ISSUE TITLE
admin user > add user: tricky problem when change language after error 500 appear if add user failed

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1085]
**At present**

Prerequisites:
Notification by email: True
Config smtp: need to have some error in config (exemple change port of smtp)

Workflow:
- add user in admin user interface
- type all necessary information
- click on create the user

Now you show an error 500 "Error Unexpected error, please inform an administrator" this error message is in english.
Now change language by an another, in french in this case.
try to click on "Créer l'utilisateur"

Now you can see error message stay in english "Erreur Unexpected error, please inform an administrator".

**Expected**

- [x] If you change language all translation need to change direclty, also translation about flash message.

**Comment by tracim** [comment]
@PhilippeAccorsi could you test and close if not valid anymore?

**Comment by tracim** [comment]
@PhilippeAccorsi what is the issue?

- the HTTP 500 error?
- the missing translation?

**Comment by PhilippeAccorsi** [comment]
The translation of this error message exist if error appear when you are in french.
But if you have this error in english and you switch to french, the error message stay in english: just in this special case:  interface in english => create user => validate => error 500 => change interface to french => validate => message stay in english

**Comment by PhilippeAccorsi** [comment]
Waiting #1234

**Comment by PhilippeAccorsi** [comment]
Verified.

**Comment by PhilippeAccorsi** [comment]
I have detected one new case for this error. 
Interface is in french, I can refresh with F5 and interface is in french.

But when error 500 appear, error is in english by default. If I change language manualy to english and to french, this message appear in french.

**Comment by PhilippeAccorsi** [comment]
Verified.
