### ISSUE TITLE
add context prefix to every routes (front and back)

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1087]
currently, backend always respond the react app if the route doesn't start with /api or if the file is not found. It cannot return 404.

Expected, to allow backend to know when to display a 404 error, every routes must starts with a prefix that will define if it is a frontend route, an api route or an asset route.

The backend behavior must be the following one:

- if route starts with `/api`, then the route is an API, so return the associated API
- if route starts with `/assets` return the given asset or a 404 if the file is not found (this also required to rename `/asset` to `/assets` in frontend)
- if route starts with `/ui`, then return the index page
- in other cases do nothing special for the moment (this will result in a 404).

**Comment by lebouquetin** [comment]
@Skylsmoi the backend code is ready

**Comment by Skylsmoi** [comment]
https://github.com/tracim/tracim_v2/pull/106

**Comment by PhilippeAccorsi** [comment]
Verified.
