### ISSUE TITLE
adding a member that already is in the workspace return error http 500

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1091]
currently, when I add a member to a workspace that already is in the workspace, api return error 500

- [X] backend : expected, it should return an error 400 with a custom error code

additional info, data sent to api is: 
id: null,
email: null,
public_name: 'name_of_user_that_already_is_in_the_workspace',
role: any

- [ ] Frontend : support this error case

**Comment by inkhey** [comment]
Exception case for role already exist should be handled somehow by the frontend too as soon as PR is merged.

**Comment by PhilippeAccorsi** [comment]
Verfieid.
