### ISSUE TITLE
plural of backend keys for french translation

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1094]
currently, for app list, backend returns an object containing the label.
Eg: Thread, File, Text document
We can't properly make a generic plural process.
For Thread and File, it's easy, but the french plural translation of "Text document" is "Documents texte". The -s is after the first word.
~~The current only solution is to parse the string and add -s to first word only~~ => This is not a solution. Translations must be given statically.

Expected: need discussion but I guess if backend returns the plural version of the label, I can create the translation key for it using the `const translationKeyFromBackend` from [frontend/helper.js](https://github.com/tracim/tracim_v2/blob/develop/frontend/src/helper.js#L140)

**Comment by tracim** [comment]
@Skylsmoi I thought we did only have backend translations for emails?!

**Comment by Quiwy** [comment]
Not relevant since using weblate for translations
