### ISSUE TITLE
opening popup create content removes the current content filter

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1097]
currently, if I am on the workspace content list with an active filter and I create a new content, I am redirected to the workspace content list without any filter.
This is because the popup create content urls doesn't keep the query param "type"

expected, opening the create content popup keep the active filter

It should only need to keep the query param type upon changing the url

**Comment by Skylsmoi** [comment]
I can't reproduce.
It might have been fixed by https://github.com/tracim/tracim/commit/ebd48e316437652b05f96300c1e448e3643c2878

**Comment by Skylsmoi** [comment]
I think @PhilippeAccorsi can test it a bit too to be sure and close the issue in he cannot reproduce either.

I put the issue in need tests

**Comment by PhilippeAccorsi** [comment]
Thats ok, problem solved.
Verified.
