### ISSUE TITLE
Revision filename should be done according to filename of revision not filename of content

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1098]
**Describe the bug**
Actually when an old revision is download, filename of downloaded file is not created filename of revision.
This means that file extension does not match correctly with content.

**Expected behavior**
Return always filename of current revision.
if "toto.jpg" has and old revision which is "rapport.odt", we should have when downloading odt file rapport.odt something like rapport-r14.odt not something like toto-r14.jpg .

**Comment by lebouquetin** [comment]
@inkhey the API gives the filename for every revision, you confirm?
@Skylsmoi by the way, please remove the revision part `rxxx` in the filename: it gives a name to files that is not expected by endusers so its confusing

**Comment by PhilippeAccorsi** [comment]
Verified.
