### ISSUE TITLE
sidebar: if you select a filter you can see some small black point (on Firefox, not in chrome)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1099]
At present

If you select filter in sidebar you can see some small black point like this:

![capture d ecran de 2018-10-30 16-50-24](https://user-images.githubusercontent.com/25848257/47731257-0562c700-dc64-11e8-88cf-8c0c8dacc49b.png)

Expected

- [ ] Have same screen on firefox like we have on chrome, so without view of there black point

**Comment by Quiwy** [comment]
Ui changed, not relevant anymore.
