### ISSUE TITLE
Webdav support of copy/paste is broken

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#110]
Currently : I try to copy a file from "c:\" to "z:\" which is the mount point of my webdav server. Copy fails according to the windows explorer but the item is created in database (and is available from the web interface). Unfortunately, the file is empty (0 byte). If I try to copy again, another instance of the object is created in database (with size 0byte) but windows explorer says "the operation failed".

Expected : allow to copy/paste files.

Note : failure is from a windows 7 client.

**Comment by buxx** [comment]
Solved in recents commits (in particular 73f79ef8110775ddae382369ceca53b52caa2d81).
