### ISSUE TITLE
frontend support for 2041 error code

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1105]
**Describe the bug**
modify label or/and description in content without any modify may failed with error 400, with code 2041. 
Currently this error code seems to not been handled properly by frontend .

**Comment by Skylsmoi** [comment]
Error isn't handled but I think there is nothing to do here.
Currently, when saving the same label, it indeed return a http 400 but since it isn't handled, it doesn't display any error message, the label switch back from edit mode (input > div) and nothing more happens

**Comment by tracim** [comment]
@Skylsmoi we talk a few weeks ago about showing a popup by default for all API errors. I understand it's not the case?

The frontend should by default always show a popup error, then hide it for specific cases

**Comment by Skylsmoi** [comment]
a bit late but, currently, a default error msg in a popup appears for error http 500.
Error http 400 must be handled regarding its custom error code

**Comment by PhilippeAccorsi** [comment]
at present:
Flash message for user:
~~~
Warning
Error while saving new title
~~~

Error 400 code 2041:
~~~
message | The content did not changed
-- | --
details | {…}
error_detail | {}
code | 2041
~~~


I think its better for user to know label not changed. Its not a really error for user.

**Comment by Skylsmoi** [comment]
@lebouquetin 
What if we decide to not display anything in case of code 2041 ?
This might answer the question "where do we put the cancel button when editing the title of a content ?".
Or, at least, giving it a better temporary solution

Example:
- user open an app (html-doc, thread, file)
- user click on edit title
- interface replace the "edit" picto (the pen) by the "validate" picto (the check)
- user doesn't change anything and click on the "validate" btn (the check)
- api returns 2041, nothing is displayed, the title didn't changed and the interface replace back the "validate" btn by the "edit" one

I think it's better than displaying  "error, your title must be different"

**Comment by tracim** [comment]
The frontend behavior should by :

- by default a HTTP 400 should result in a flash message
- in case of 2041, exceptionnaly the flash should not be shown

**Comment by lebouquetin** [comment]
Currently :

- if I edit and save label without changing it, I get an error "Erreur lors de la sauvegarde du nouveau titre"

Suggestions are:

- from @PhilippeAccorsi : show a message "can't save : label did not change"
- from @Skylsmoi : show no error at all

I agree with suggestion from @Skylsmoi.

**Comment by PhilippeAccorsi** [comment]
Verified.
