### ISSUE TITLE
Html sanitize of content send to API

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1109]
**Describe the bug**
When HTML content is send to API, it may contains script or thing like this. to avoid maximum of security issue, we probably should sanitize this to avoid trouble.
This is probably related to #1101

**Comment by basilelegal** [comment]
will be fixed by the MR #1459

**Comment by lebouquetin** [comment]
The fix has been reverted through https://github.com/tracim/tracim/pull/1557

**Comment by buxx** [comment]
Tested and ready for 2.3
