### ISSUE TITLE
app file: add default icon or text about preview not exist

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1111]
At present

If no preview of file is available we only see a small circle.

Expected

- [ ] show icon or text to saying that preview doesn't exists

**Comment by Skylsmoi** [comment]
waiting for backend to return data about whether a jpg preview exists

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi why we not show same message in popup to add file like we have in update file when no jpg preview is available before validate the new file?

paperclip and filename

**Comment by Skylsmoi** [comment]
@PhilippeAccorsi #1116 is fixed, so is this issue fixed too ?

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi yes, you can put this issue in nedd test also.

**Comment by PhilippeAccorsi** [comment]
Verified.
