### ISSUE TITLE
app file: update file or preview of file not really working all the time

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1112]
At present

I have updated my repo, install backend, install frontend and build full frontend.
- if I add file with not preview visible directly in popup, I dont see same information that I have in update file.

- I can see some error 500 whend I update file with other mimetype file.

- error: File has not been decrypted
- error: Multiple definitions in dictionary at byte 0x6446 for key /F7

This error appear with different kind of mimetype.

- Sometime after update a pdf file with a jpg file, I cant see preview or message about preview not available and I see in log:
error 400: Code error: 1012 
Log backend:
tracim_backend.exceptions.PageOfPreviewNotFound: page 2 of revision 20 of content 4 does not exist

- After upload a *.ini file, I can see preview of this file but if I look inspect network, I can see one error 500 : `message | [Errno 2] No such file or directory: '/tmp/tracim/preview/23272ed8cd9a175ac419c04d24052cf4-1920x1080-page1'`

Expected

- [ ] File, update file and preview working without error

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi @inkhey I think we can use my local pc to see directly what is wrong and to know if its backend or frontend issue and after that I make new issue for each bug.

**Comment by lebouquetin** [comment]
@PhilippeAccorsi could you upload files that fail? the encryption error is related to PDF which are encrpyted sometimes (I fixed it yesterday in preview-generator, but I dont known if @inkhey has upgraded the version of preview-generator)

By the way, you seem to have differents issues - you should create several issues.

**Comment by lebouquetin** [comment]
@Skylsmoi @inkhey when you return the has_pdf_preview and has_jpeg_preview, you do it for every revision, right ? And @Skylsmoi you use the information taken from current shown revision, right?

**Comment by inkhey** [comment]
@PhilippeAccorsi Preview_generator 0.8 is now available issue related to unencrypted pdf without password should be fixed.

**Comment by PhilippeAccorsi** [comment]
Ok @lebouquetin 
I tried today to make specific issue for all problem, but I cant push here the file, file is private.

**Comment by PhilippeAccorsi** [comment]
Related to:

https://github.com/tracim/tracim/issues/1116
https://github.com/tracim/tracim/issues/1117
https://github.com/tracim/tracim/issues/1118
https://github.com/tracim/tracim/issues/1120
https://github.com/tracim/tracim/issues/1121

**Comment by Skylsmoi** [comment]
related https://github.com/tracim/tracim/issues/1130
