### ISSUE TITLE
Implement necessary for auth by apache

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#1114]
Objectives
-------------

Permit to use apache2 (or any reverse-proxy) as authentication provider. In this mode, Tracim must use a header value (provided by apache2) or environment variable as user identification.

Probable changes
-----------------------

* Add a config to enable this mode
* Add Tracim auth strategy based on header or environment variable
* Disable/Change Tracim features when this mode is enabled (backend and frontend)
  * Password recovery
  * Password change
  * Email change
  * Account creation: only email/login required
  * login

Take care of
----------------

* User must exist in Tracim database
* Ensure apache2 header cannot be set/overrided by client ...
* Other services like radicale or webdav are they impacted ?
* We want permit auth strategy chaining, make a reflexion about that
* Add an header (set by apache) who ensure request is from apache ?

Bonus
--------

When web browser will make request on apache2 reverse proxy, apache2 will immediately respond with 401 http response with require of credentials. Web browser will display a login box.

If we want a html login page, we must configure apache2 virtualhost to allow urls without auth. Like "/" or "/login". Afetr login, the html login page must redirect on page with url like "https://myusername:mypassword@mytracim.tdl/...". This behavior permit to keep a html login page.

**Comment by buxx** [comment]
See https://github.com/tracim/tracim/issues/1115 for anonymous browsing reflexion.

**Comment by buxx** [comment]
More info about authentication chaining:

The goal is to be able to offer authentication with multiple way in addition of apache auth. The main problem is following: When apache is configured to require authentication, if no authentication provided apache will return 401 HTTP response without contacting Tracim. So, it is not possible to communicate with Tracim (and it's authentications) when apache doesn't receive authentication.

A way to solve this problem: use apache [mod_authn_anon](https://httpd.apache.org/docs/current/fr/mod/mod_authn_anon.html) who permit to login with anonymous user. With this module we can auth as anonymous with apache the use Tracim authentications. But apache **require** credentials to authenticate as anonymous (eg. "anonymous" login and empty passwd). So it is not possible to offer at the same point an apache2 authentication + Tracim authentications (Question [opened here](https://httpd.apache.org/docs/current/fr/mod/mod_authn_anon.html) to know if with can mahe apache2 auth only if credentials provided).

A bypass strategy: We can use this scenario: 

* URL like "/*" where apache don't require authentication: Tracim offer a login page with two option: A) login with apache (make a redirect with http://login:passwd@mytracim.fr/a2auth/). B) standard login on "/"
* URL like "/a2auth/* where apache require authentication

**Comment by inkhey** [comment]
@PhilippeAccorsi some info about testing 

### Test without Webserver proxy

To test this with `Remote-User ` HTTP Header (remote_user_header is a CGI env var, so header is converted with HTTP_ prefix, '-' is converted to '_', etc..)

`
remote_user_header = HTTP_REMOTE_USER
`

#### easy test with httpie without apache auth 

tracim backend : 
`http localhost:6543/api/v2/auth/whoami Remote-User:test@test.test`
for webdav in :3030 :
 `http localhost:3030 Remote-User:test@test.test`

**Comment by PhilippeAccorsi** [comment]
Issue is not finish here. Some case in issue description is not solved.
ex:
- change password in "my account" or email (function is not available with this auth type)
- forgotten password available (not possible to change password because after that you can't use tracim)
- How to disconnect **or** dont permit to disconnect in interface.
- etc...
 
@inkhey if for you, everything is make in backend, make a comment for the front to make necessary configuration for this type of auth. 
The Frontend can know backend use the auth apache?

thanks.

**Comment by PhilippeAccorsi** [comment]
After some other test, some need improvement are now available:
    - change password in "my account" or email is not visible if account is not internal => **good**
    - forgotten password is available but email is not accepted => **good**

**Comment by PhilippeAccorsi** [comment]
After discuss with @lebouquetin :

Disconnect fuction is not available for the moment. The auth apache protocol don't have default disconnect function, so we need to add this possibility in the futur.

For the moment its necessary to close the web-browser to have apache disconnection.

issue related: #1404 #1403 #1405

**Comment by PhilippeAccorsi** [comment]
Verified.
