### ISSUE TITLE
changes in API to allow proper folder support

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1119]
modifications of end point `/api/v2/workspaces/{workspace_id}/contents`:
- `parent_id` is now a string and expect a list of integer like so: "4,50,31,14"
  - endpoint must return every contents that have theses ids as `parent_ids`
  - related issue: https://github.com/tracim/tracim/issues/1113
- new query param: `complete_path_to_id` (int)
  - endpoint must return every contents that will allow frontend to generate the complete path of that content id. That means every parents folders of that content, including every contents of theses folders

**Comment by Skylsmoi** [comment]
endpoint with query param repetition to refactor:
- /api/v2/users/me/workspaces/{workspace_id}/contents/read_status
- /api/v2/users/{user_id:\d+}/known_members

**Comment by Skylsmoi** [comment]
@inkhey a small issue I have just found:
- I need to be able to ask the API for a complete_path_to_id of an archived or deleted content. Right now, the API returns `{code: 1003, details: {...}, message: "Content "68" not found in database"}`

**Comment by tracim** [comment]
@inkhey also add test cases for this

**Comment by inkhey** [comment]
@tracim tests already exist for most case in https://github.com/tracim/tracim_v2/pull/124, test for #1192 issue explained here( https://github.com/tracim/tracim/issues/1119#issuecomment-438300743) by @Skylsmoi  is available here: https://github.com/tracim/tracim/pull/1215

**Comment by PhilippeAccorsi** [comment]
Verified.
