### ISSUE TITLE
app file: deactivate clic on: no preview available

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1120]
At present

If my file dont have preview I see message "no preview available" but I can click on this message.

Expected

- [x] Deactivate click when "no preview available" is show.

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi Can you deactivate mouse icone with hand when you show "no preview available".

**Comment by Skylsmoi** [comment]
@PhilippeAccorsi ok

**Comment by Skylsmoi** [comment]
@PhilippeAccorsi done

**Comment by PhilippeAccorsi** [comment]
Verified.
