### ISSUE TITLE
app file: sometimes a "/" is missing from the path of preview

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1121]
At present

Sometime when you see preview of file and you navigate in the preview pages you can see an error 404:
~~~
/api/v2/workspaces/2/files/4/revisions/19preview/jpg/500x500/guide_tls_v1.1.jpg is not a valid path
~~~

Expected

- [ ] the path use all the time "/"

**Comment by tracim** [comment]
@PhilippeAccorsi, you should point exactly the error. Instead of « the path use all the time "/"» you should write where the issue is : « slash is missing between `preview` and `19```

**Comment by PhilippeAccorsi** [comment]
Verified.
