### ISSUE TITLE
app file: probleme with preview if you have look one page in preview before update file or look an another revision

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1122]
At present

Sometime after update a pdf file with a jpg file, I cant see preview or message about preview not available and I see in log:
error 400: Code error: 1012
Log backend:
tracim_backend.exceptions.PageOfPreviewNotFound: page 2 of revision 20 of content 4 does not exist

This problem exist if you are on page 4 (for exemple) before uploading the new file.

Expected

- [ ] refresh information about the preview(dont try to show same page of preview) when you upload a new file or if you look an another revision

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi sa ne fonctionne pas. Tjrs le même soucis.

**Comment by Skylsmoi** [comment]
@PhilippeAccorsi fixed

**Comment by PhilippeAccorsi** [comment]
Verified.
