### ISSUE TITLE
Admin account page wording

### ISSUE THREAD

**Issue by basilelegal** [tracim/tracim#1138]
URL: `/ui/admin/user/<id>`
Title would be more clear if it was `Name of the user account edition` instead of `Admin account page`

Typo in `My profil` => `My profile`
As you are the administrator you are not editing your profile but the user profile `Profile` alone is enough.

- ~~Title of the page `Account information` => `Account informations`~~.
- Tab's name doesn't match its title pick either `Information` or `Profile` (Suggestion: tab name = `Account information` and title = `Edit account information` . 
- Placeholders `Change your name` => `New name`

In `Shared spaces and notification` it would be handy to be able to change the role of the user using a dropdown. Title should be `Edit Shared spaces and notification`

In `my profil` the button says `validate` and in `password` the button says `send`. For more clarity you should pick one word and stick to it. `Save` for exemple is more commonly used. And to be consistent tab's title should be `Edit password` instead of `Change your password`

**Comment by tracim** [comment]
@basilelegal there is no plural form of information (informations does not exist in English)

**Comment by tracim** [comment]
Change password is more common than edit password, I think

**Comment by tracim** [comment]
@basilelegal a note: when speaking of a frontend screen, a good reflex is to give the uri (path of the url)

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi menu in account not translate when you change language.
If you change from english to french, menu stay in english but if you return in admin user and you click again on one name, menu is now in french. if you change now for english, menu stay in french.

**Comment by PhilippeAccorsi** [comment]
Verified.
