### ISSUE TITLE
Creation date: display in FR

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#114]
In frontend, display created date of workspaces, folder and other in French when user is in french.

Note: Serialized data must be in standart utc format, traduction must be done in frontend (template)

**Comment by Skylsmoi** [comment]
string msg is now correcly translated.
there is still to translate the date

**Comment by buxx** [comment]
@lebouquetin Les dates sont déjà correctement affichées en Français lorsque la langue du navigateur déclare le Français.

Je peux fermer le ticket ou il y a autre chose à vérifier ?

**Comment by buxx** [comment]
Vu avec Come: Il y a aussi une date dans l'admin qui est mal affiché. A faire.
@lebouquetin Du coups, par rapport à la question précédente: On garde l'affichage de la date en fonction de la langue navigateur ? Ce serais surement plus cohérent de l'afficher dans la langue du "site".

**Comment by tracim** [comment]
@buxx tu as raison sur la cohérence, ce que tu proposes c'est bien ce qu'il faut faire. Si c'est ce que vous avez fait, vous pouvez clore le ticket.

**Comment by buxx** [comment]
@lebouquetin En allant dans ce sens je suis tombé sur un problème:

Actuellement, Tracim se positionne obligatoirement en FR. Que l'on renseigne ou non le paramètre "lang" dans la config, tracim sera en FR. Cela se produit car babel, qui en essayant de se baser sur les langue du navigateur web, ne trouve que les traductions FR.

La solution: Générer la traduction pour le EN. A partir de la, si le navigateur est configuré pour du EN, le site est en EN. Si le navigateur est configuré pour du FR, le site est en FR.

**Mais**: Le paramètre "lang" de la config est sans effet. C-a-d que si je le met à "FR" et que mon navigateur est en EN, le site est affiché en EN. Ce que je propose du coups c'est de ne pas mettre un paramètre "lang" mais "default_lang" ou "force_lang" pour avoir une langue par défaut lorsque le navigateur demande des langues que l'on as pas et pour pouvoir forcer une langue à tout le monde.

* Pour forcer la langue: La doc en parle (http://turbogears.readthedocs.io/en/latest/turbogears/i18n.html#forcing-a-language) mais je ne sais pas ou executer ce code.
* Pour avoir une langue par défaut: Je ne sais pas comment configurer ça pour le moment.
