### ISSUE TITLE
Create Better default config file in backend : avoid duplication

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1142]
**Is your feature request related to a problem? Please describe.**
Actually config file development.sample.ini is a bit complex and some elem are duplicate, we can use variable to avoid duplication. We can also think about a simpler section in order to set easily most important tracim config param.

**Comment by PhilippeAccorsi** [comment]
@inkhey when #1208 is merged, please inform me. I need to change some line in internal script (about latest) about new development.ini file.

**Comment by buxx** [comment]
@PhilippeAccorsi It is merged !

**Comment by PhilippeAccorsi** [comment]
Modification make in script for latest and latest server is ready for this update:
- script on server is updated
- development.ini is deleted

**Comment by PhilippeAccorsi** [comment]
I'm waiting update of latest instance to verify if this new file is correctly working on pre-prod.

**Comment by PhilippeAccorsi** [comment]
Verified.
