### ISSUE TITLE
FIx unwanted error 500 on standard endpoint when depot file is corrupted

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1144]
**Describe the bug**
Currently when using a corrupted depot file (does not match with link in database) we get error 500 on endpoint who are not directly related to depot generic info content endpoint or revisions endpoints.

**Expected behavior**
Return 200 for those endpoint with logged stacktrace about the issue.

**Comment by PhilippeAccorsi** [comment]
If its done yet in v2.0 please change Milestone and project to 2.0

**Comment by PhilippeAccorsi** [comment]
For test: rename depot folder and try to use tracim.
Everything work but not preview of file and its not  possible to download file from old depot.

**Comment by PhilippeAccorsi** [comment]
Verified.
