### ISSUE TITLE
Create document popup doesn't close

### ISSUE THREAD

**Issue by basilelegal** [tracim/tracim#1149]
**To Reproduce**
Go to `/ui/workspace/<id>/dashboard` or `/ui/workspace/<id>/contents`  
2. Click on `Write a document`
3. Click on any other link in the sidebar
4. The popup to create a new document

**Expected behavior**
The popup should close like the poput for a new file or a new Thread

**Comment by Skylsmoi** [comment]
on branch develop, the issue seems the same for any popup create content.

on branch 1082/dev/folder_support It seems that the issue is fixed

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi after discuss with @lebouquetin: its better to block click outside the create popup.

**Comment by Skylsmoi** [comment]
Meanings: add an overlay behind the create popup

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi its working but its not really user freindly if you use header button because you can go to admin user, validate creation of document and you stay in admin user. Maybe close popup automatically if you click on header button.

Is it also possible to decrease white color of overlay?

**Comment by Skylsmoi** [comment]
overlay is now over header and transparency has been reduced

**Comment by PhilippeAccorsi** [comment]
Verified.
