### ISSUE TITLE
add websocket for Timeline

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1151]
Timeline should be able to automatically add new comments/revisions on the fly.

For that, we should open a websocket so the Timeline can get new items every x (x = 30 ?) seconds.

Be advised that since this modification should be applied to every apps implementing the Timeline, it should be a good time to refactor that Timeline

Backend part: create an endpoint with websocket protocol

**Comment by grignards** [comment]
@Skylsmoi If you are ok, I think we can close this issue as this on the fly update is now handled by TLMs.

**Comment by raphj** [comment]
Let's close it, yes.
