### ISSUE TITLE
add possibility to modify config file before starting tracim image

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1152]
At present:

If you want to configure email or something else, you need to start the docker image one time and stop this image. Now config file are available.

Expected

Its possible to start tracim image directly with good parameter.

- Idea: 

- [ ] use docker exec to start image, change config file and stop image. 
After that, you can access to the config file and when already is done, starting your tracim image with the good parameter.

- [ ] add more variable to modify some or all config file.

**Comment by tracim** [comment]
The origin of the issue is to use mail notifications and mail fetcher in the docker. The right way to do this should be to manually upgrade the configuration and to add an option `RUN_MAIL_FETCH=1`

**Comment by lebouquetin** [comment]
maybe the right solution is not to use volumes for configuration but to setup all parameters through environment variables. See 1311

**Comment by PhilippeAccorsi** [comment]
Now its possible to start tracim with env variable.
Check if its working good with docker image and add some documentation about that.

**Comment by PhilippeAccorsi** [comment]
The list of all environnement variable is visible here https://github.com/tracim/tracim/blob/develop/doc/backend/env_settings.md

Is it possible to configure all needed parameter and start tracim directly without necessary of restarting Tracim.
I close this issue.
