### ISSUE TITLE
Check for empty comment does not verify html markup case

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1154]
**Describe the bug**
Currently check for empty comment verify only case when content given is completely empty. As comment content can be html, we should not allow empty comment contaning only html tag without any meaning of consistent content (like `<p>`)
This issue will probably need https://github.com/tracim/tracim/issues/1101 to be resolved first in order to simplify case.

**Comment by PhilippeAccorsi** [comment]
Verified.

**Comment by inkhey** [comment]
@basilelegal your fix doesn't have the correct behaviour, so, we reverted all you commit for this fix. Can you fix this ?

**Comment by PhilippeAccorsi** [comment]
We have reverted also about big regression for image or media link with tinymce. If this kind of content is send, the backend don't save value and you cant see image or media link in timeline.

**Comment by gbonaspetti** [comment]
Still not doing:

- [ ]  show explicit message with error code 2003

- [ ]  translate this error message

(Linked to #1553)

**Comment by lebouquetin** [comment]
I mark this "need test" because #1553 is need test too

**Comment by gbonaspetti** [comment]
Verified.
