### ISSUE TITLE
Endpoint PUT `api/v2/workspaces/:id/folders/:id` returns 500 when required params are missing

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1157]
I have called this endpoint with that json body:
`{"label":"Bonjour?","description":"","sub_content_types":["comment","file","html-document","folder","thread","file"]}`

the param raw_content is misspelled "description"

and I got a http 500 with:
`
code: null
details: {,…}
error_detail: {}
traceback: "..."
message: "__init__() missing 1 required positional argument: 'raw_content'"
`

I would have expected a 400 with better error message

**Comment by PhilippeAccorsi** [comment]
Verified.
