### ISSUE TITLE
Endpoint PUT `/api/v2/workspaces/:id/folders/:id` returns http 400 code 2041 (no changes) even if 'sub_content_types' is different

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1158]
currently, if I PUT `/api/v2/workspaces/:id/folders/:id` without changing neither the label nor the raw_content, I can't change the third param 'sub_content_types' because endpoint returns http 400 with code 2041 with the message 'message: `The content did not changed"`

**Comment by PhilippeAccorsi** [comment]
Verified.
