### ISSUE TITLE
Simplify webdav templates for html documents

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#1166]
Currently:

Webdav allow to access documentation pages as an HTML view of documents. The view is design to be similar to tracim v1 view. Its not perfect and it make document being read-only

Expected:

- [ ] Build webdav view of html documents with only real HTML content of  the document
- [ ] ~Make HTML documents editable through webdav - this is now possible and easy to manage because html content displayed in webdav will be exactly the html content of the documentation~ moved to #1381 

This will make the code more simple to maintain and add the possibility to edit HTML documents as simple html files

**Comment by PhilippeAccorsi** [comment]
Exemple for thread:

~~~
<p style="font-style: italic; color: #999">
1 hour ago, toto@toto.toto wrote :
</p>
<p>
oui oui sa va bien
</p>
<blockquote style="border-left: solid 2px #999; margin-left: 1em; padding-left: 1em;">
	<p>
		1 hour ago, Global manager wrote : 
	</p>
	
	<p>
comment vas tu
	</p>

	<blockquote>
		<p>
			1 hour ago, Global manager wrote : 
		</p>
		<p>
			hello toto
		</p>
	</blockquote>
</blockquote>
~~~

**Comment by PhilippeAccorsi** [comment]
Exemple for document.html:
~~~
<p><code>\ / =&gt; g&eacute;r&eacute; correctement</code></p>
<p><code> : =&gt;&nbsp;g&eacute;r&eacute; correctement</code></p>
<p><code> * =&gt;&nbsp;g&eacute;r&eacute; correctement</code></p>
<p><code> ? =&gt; g&eacute;r&eacute; correctement</code><code></code></p>
<p><code> " =&gt;&nbsp;g&eacute;r&eacute; correctement</code></p>
<p><code> &lt; &gt; =&gt; g&eacute;r&eacute; correctement</code></p>
<p><code>| =&gt;&nbsp; g&eacute;r&eacute; correctement</code></p>
~~~

**Comment by PhilippeAccorsi** [comment]
Its merged => 7e63ca2c7d65d1c1a89f3b8700a43d9da89d80de

**Comment by PhilippeAccorsi** [comment]
@basilelegal This part of issue not working "Make HTML documents editable through webdav"

If I try to modify one file (*.document.html) by addind for exemple one new line <p>test</p> or just adding text, when I save this file I can see in tracim web interface a new revision but content is not saved (the new text is not visible). If I open again the file, my new text is not visible.
 
When I open this file with Gedit I can see all line but if I open with Atom I can't see all text.

@lebouquetin do we save this issue in mandatory for tracim_v2.1 ?

**Comment by basilelegal** [comment]
> Make HTML documents editable through webdav - this is now possible and easy to manage because html content displayed in webdav will be exactly the html content of the documentation

Moved in #1381

**Comment by PhilippeAccorsi** [comment]
Verified.
