### ISSUE TITLE
Simplify Email templates

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#1167]
Currently:

Emails are sent with a html template which try to be user-friendly. This is not really the case and it makes more code to maintain and it make difference for the user between a "normal" email and a tracim email

Expected:

upgrade the templates to be "like a real email", without advanced layout and straight and friendly text.

Example for user account creation notification:

Suppose the title of the tracim instance is "Algoo Extranet"

Subject: `You've been invited to join Algoo Extranet`

Content of the email:

----

Hello Damien Accorsi,

Someone invited you to join *Extranet Algoo*. An account has already been created for you.

Your credentials are:

- login : *damien.accorsi@company.email*
- password: *rekngoiinr*

Let's start to discuss, share files and documention with collaborators by signing in at [https://algoo.trac.im](https://algoo.trac.im)

note: as soon as you are connected, we strongly recommend you to change your password and delete this email.

Enjoy your day :)

Suricat', the bot

--  
Suricat', the bot  
Algoo Extranet  
https://algoo.trac.im  
Powered by tracim software - https://www.tracim.fr

**Comment by lebouquetin** [comment]
Work in progress code has been pushed to `fix/1167_simplify_email_templates`. @inkhey could you finish the work please?:

- check there are no regression like crash
- upgrade the templates in order to make them translatable
- add translations.

Note : the strategy is to generate emails in HTML format only. TEXT-Only mail clients (like MUTT) know how to interpret html mails.

**Comment by inkhey** [comment]
I don't find regression up to now, but i've some thought about template : 

- renaming title and modifing content give the same result, so we received all content of the file if just title as change.
- Distinction between file name and content seems to me unclear.
- Comments are just plain text, without any clear reference in mail content to the content.

And one other thing : should we support Delete/undelete, archive/unarchive notifications ?

**Comment by inkhey** [comment]
@lebouquetin
 removing default value for `self.EMAIL_NOTIFICATION_CREATED_ACCOUNT_TEMPLATE_HTML `
and  `self.EMAIL_NOTIFICATION_RESET_PASSWORD_TEMPLATE_HTML` broke notification tests.

Should we;
- restore them ?
- set correct config in test **and** raise specific exception when someone try to send mail without any template configured.
- something else ?

**Comment by inkhey** [comment]
Another question about mail template:
- Should we add some semantic in email ? This mail help for some case like test or gmail go to action (actually we just verifiy email is received, we don't check if value in email are valid/correct). As far is see this is done by other web service like github or gitlab. 
see also this (https://gitlab.com/gitlab-org/gitlab-ce/issues/1517) and this (https://developers.google.com/gmail/markup/reference/go-to-action)

**Comment by inkhey** [comment]
i've had to make some modification in code to allow translation of both default email subject and content_status. (see https://github.com/tracim/tracim/commit/8c1d29642b361e6e37c5545b88c97eac48475d60)
i've also discovered this issue : https://github.com/tracim/tracim/issues/1374 in frontend that disable usability for backend translation.

**Comment by lebouquetin** [comment]
- check at start if notifications arre activated and templates not configured => stop with explicit error
- also check that template file exist

**Comment by PhilippeAccorsi** [comment]
Verified.
