### ISSUE TITLE
change sidebar background color to black and text in white

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#1168]
Currently:

The background color of the sidebar is the primary color. In some cases, we'd like for example to keep primary color (for global rendering) but to have a black (or dark) sidebar.

Expected:

- [x] sidebar color is always black and text is always white

- [ ] ~~add an optionnal `sidebar` color in the color.json file and use associated classes in the HTML~~
- [ ] ~~implement in backend the behavior:~~
    - ~~if sidebar is not defined, then sidebar color is primary~~
    - ~~add new css classes in the index.mak file in order to always have the css class available~~

~~Note : this probably also require to add a `sidebar-text` color which is also optionnal (in order to allow light color for text on dark background)~~

Bonus:

- [ ] put the background color of apps of the color associated to the contents. icon in white. Cf below:

![selection_097](https://user-images.githubusercontent.com/9657115/48894132-3e94ee00-ee42-11e8-9912-8880902d223b.png)

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi after discuss with @lebouquetin :+1: 

- Dont add parameter in color.json.sample

- [ ] sidebar color is always black and text is white

**Comment by Skylsmoi** [comment]
@tracim Is this decision a quick fix or is it gonna be the final implementation ?

**Comment by tracim** [comment]
@Skylsmoi two possibilities:

-  final implementation if possible. In this case, `sidebarBackgroudColor` and `sidebarTextColor` should be added to color.json file
- quick fix if time is not enough for releasing 2.1

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi what do you think about bonus? Is it complicated to make this bonus or do you need more backend job to make this?

**Comment by Skylsmoi** [comment]
What is the "bonus" you're talking about ?

**Comment by tracim** [comment]
@Skylsmoi the bonus is written in the description of the bug: put the color of apops as background of icons (like in the screenshot I put in the issue)

**Comment by PhilippeAccorsi** [comment]
Verified.
