### ISSUE TITLE
Improve view of "new" items

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#1169]
currently:

items with new content are shown in bold. this distinguish them from others, but it's not very clear

expected:

add also a label "new". cf screenshot

![selection_098](https://user-images.githubusercontent.com/9657115/48894368-e90d1100-ee42-11e8-96d5-c9da742eb538.png)

**Comment by tracim** [comment]
the label background color should be primary

**Comment by Skylsmoi** [comment]
"new" would more likely means "has just been created"
I think it would be more confusing to have "new" when it's just an update.

I wonder if just using bold is that unclear, any webmail uses that way to display read from unread

That being said, having a "new" tag only for contents that we never have open would be a good idea. I'm not sure if that's possible with API right now though

**Comment by Skylsmoi** [comment]
Ok I agree on the necessity to have more than a bold font
I'd rather not have something too verbose, what about a red dot on the top right corner of the content type ?

**Comment by Skylsmoi** [comment]
exemple:
![selection_015](https://user-images.githubusercontent.com/11177014/48914772-bf70db80-ee7c-11e8-85d6-c9be730bf974.png)

**Comment by tracim** [comment]
The interesting thing in email client example is: the information about new message is visible on the full width of the page. The suggestion of a red point is located in a few pixels of a 1920px large row... and it does not explain what it means.

Let's do it with a label - there is plenty of place, and you won't get new information on every line: contents are marked read as soon as you read it.

**Comment by Skylsmoi** [comment]
Let's call the "new information" a "tag"
Your last comment is true for a widescreen, but on mobile, a verbose tag might be problematic.
Also, where do you expect the tag to be ?
I expect it to be located at the same place on each line, preferably at the begining of each ; so not after the content label. That way it's easier to quickly see all unread contents.

**Comment by tracim** [comment]
> Your last comment is true for a widescreen, but on mobile, a verbose tag might be problematic.

It's not a problem to hide a label on a small device.

> I expect it to be located at the same place on each line, preferably at the begining of each ; so not after the content label. That way it's easier to quickly see all unread contents.

The bold is already explaining "new" status. The tag should be moving - this is not a problem for me.

Anyway, current tests let me think bold is enough for the moment. So let's close this issue as WONTFIX.
