### ISSUE TITLE
folder: add possibility to copy URl of just one folder

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1172]
At present

If you have open some folder , URL have the id of all folder open. So if you want to give a link of just one folder you need to close other folder before.

In the view of tracim_v1 I cant see some other openned folder in same time.

Sometime you want to send link for an another user and says "you can find all documentatiuon in this folder" and you send link of the folder.
What is the solution for this with tracim v2.

**Comment by lebouquetin** [comment]
It's not a problem to have extra opened-folders. We won't fix this (the copy/paste is working). Associated difficulty is: if copy/paste an url, it's not clear which opened folder is the one you want to share
