### ISSUE TITLE
Form add member autocomplete sometimes doesn't display autocomplete choices

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1175]
the autocomplete popup should be displayed after typing 2 char but sometimes it doesn't

there is a process error in the Dashboard's script around the affectation of the state variable "firstLoadKnownMemberCompleted" in `handleChangeNewMemberNameOrEmail` and `handleSearchUser`

**Comment by PhilippeAccorsi** [comment]
Verified.
