### ISSUE TITLE
sidebar: chevron to open/close sidebar is not all the time visible.

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1176]
At present

its not possible to close or open the sidebar if you scroll to end off page when you have many shared space.

Expected 

- [x] show chevron to open/close sidebar all the time.

**Comment by Skylsmoi** [comment]
it should be yes

**Comment by Skylsmoi** [comment]
https://github.com/tracim/tracim/commit/73539585658aefc70ca28c5c627e753b4e7c2c80

**Comment by PhilippeAccorsi** [comment]
Added in this issue: 

- [ ] One chevron added to scroll to the beggening automaticaly.

**Comment by PhilippeAccorsi** [comment]
Verified.
