### ISSUE TITLE
sidebar: improve UX when you have multiple sharedpsace

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1177]
At present:

If you have 10+ shared spaces and you want to see something in last shared space, you need to sroll to the end, click on "all content", then scroll to the top. Now you can see all content of this workspace.

Expected:

- [x] make sidebar vertical scrolling independant of main content vertical scrolling
- [x] when clicking on a sidebar menu item, then always scroll top on the main content panel

**Comment by Skylsmoi** [comment]
this issue has been fixed by the new layout with separated scrolls

**Comment by Skylsmoi** [comment]
I'm putting it directly in "need test"

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi I put here the discussion we have make in mattermost about this issue. Some change is needed:

~~~
**damien_accorsi 11:55**
on peut afficher la scrollbar au survol au moins
en mode comme dans gitlab où la scrollbar est aux couleurs de l'interface
ça fait pas trop dégueu
pour la partie droite, tu peux retester ? ça dépend peut-être des écrans
**philippe 11:57**
Pour le moment je retrouve pas  mais je cherche car je suis sûr d'avoir vu sa quelques part 
**damien_accorsi 11:57**
ok
**philippe 11:57**
Bon effectivement j'ai trouvé: dans les pages d'admin de workspace par exemple.
**damien_accorsi 11:58**
ok. il faut laisser la scroll sur l'écran principal, tout le temps
et sur le menu latéral, un affichage "on mouseover me semble adapté"
~~~

**Comment by PhilippeAccorsi** [comment]
The problem is we not have information about possibility to scroll when you are in sidebar, in admin workspace or admin user.

**Comment by PhilippeAccorsi** [comment]
This issue is related to #1547.

**Comment by PhilippeAccorsi** [comment]
This issue is verified.
