### ISSUE TITLE
dashbord and all content: in recent activity one line out of 2 is grey but not in all content

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1179]
At present

in recent activity one line out of 2 is grey but not in all content and I dont really understand why we show grey line in recent activity.
Folder is grey so in recent activitty you can have 3 line in grey.

Expected

UX is same in all windows. Maybe find another color for recent activity.

**Comment by lebouquetin** [comment]
Not reproduced. Wontfix
