### ISSUE TITLE
log message not good about async or sync when sending email

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1183]
At present

When one email is send by tracim, log message is "Sending asynchronous email to" but this message is the same with config async or sync.

Todo :
- Change the log to something that match to reality.
- Explain with log if emails are send synchronously or asynchronously in log.
- One other nice thing to do is to replace log file for notification (email.notification.log_file_path) to a log handle the same way as normal log.

**Comment by inkhey** [comment]
In fact, log message is incorrect, at this level, it's not possible to know if message is send synchronously or asynchronously. The correct log should be like "Generating content X notification email for X user(s)"

**Comment by inkhey** [comment]
https://github.com/tracim/tracim/pull/1344  resolve all 3 issue : 
- Log for building notification correctly named
- Log for sending asynchronously/synchronously email
- Log for notification are converted as pastedeploy format but default config allow us to use almost same way as before, in a separate log file.
This log file is different from main log of tracim as it log only some information about email in a specific format.

**Comment by PhilippeAccorsi** [comment]
@inkhey More information about this issue (after test):

~~~
FROM users 
WHERE users.is_deleted = 0 AND users.email = ?
16:28:38 INFO  [sqlalchemy.engine.base.Engine:1154][waitress] ('admin@admin.admin',)
16:28:38 DEBUG [tracim:24][waitress] [EmailManager] user: 1
16:28:38 INFO  [tracim:38][waitress] [EmailManager] Sending asynchronous email to 1 user (admin@admin.admin)
16:28:38 INFO  [tracim:38][waitress] [send_email_through] send email to Global manager <admin@admin.admin> synchronously
16:28:38 INFO  [tracim:38][waitress] [EmailSender] Connecting from SMTP server mail.gandi.net
16:28:39 INFO  [tracim:38][waitress] [EmailSender] SMTP Start TLS OK
16:28:39 DEBUG [tracim:24][waitress] [EmailSender] SMTP Start TLS return code: 220 with message: 2.0.0 Ready to start TLS
16:28:39 INFO  [tracim:38][waitress] [EmailSender] SMTP Authentication Successful
16:28:39 DEBUG [tracim:24][waitress] [EmailSender] SMTP login return code: 235 with message: 2.7.0 Authentication successful
16:28:39 INFO  [tracim:38][waitress] [EmailSender] Sending email to Global manager <admin@admin.admin>
16:28:39 ERROR [tracim:32][waitress] [EmailSender] SMTP sending message return error: {'admin@admin.admin': (550, b'5.1.2 <admin@admin.admin>: Recipient address rejected: Domain not found')}
16:28:39 INFO  [tracim_email_notification:209][waitress] fail to send email to Global manager <admin@admin.admin>
16:28:39 INFO  [sqlalchemy.engine.base.Engine:1151][waitress] UPDATE users SET reset_password_token_hash=?, reset_password_token_created=? WHERE users.user_id = ?
16:28:39 INFO  [sqlalchemy.engine.base.Engine:1154][waitress] ('72b4e404aeb61b9861b96a112565348ac0003a7fc94527328d9d63e846701b003cd03d004c84cc4711092b4b88945486ad72e89eb137b5296abc3f81544f09d9', '2019-02-04 15:28:38.753938', 1)
16:28:39 INFO  [sqlalchemy.engine.base.Engine:722][waitress] COMMIT
~~~
 in log after sending a email (with password reset)

Here we see:
- "Sending asynchronous email to 1 user (admin@admin.admin)" => this is visible in notifier.py (line 382)

My email config use default parameter => `sync`

**Comment by PhilippeAccorsi** [comment]
Verified.
