### ISSUE TITLE
log message indicate "connection ok" when connecting to smtp but also if credential is wrong

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1184]
At present

When tracim try to send email, one log message appear and indicate if connection to smtp is ok or not.
But if you enter wrong credentials you always have message connection ok.

For exemple with mailjet, I dont have type user information in development.ini, just password (but not a good password) and log says "connection ok".

~~~
10:03:42 DEBUG [tracim:24][waitress] [EmailManager] user: None
10:03:42 INFO  [tracim:38][waitress] [EmailManager] Sending asynchronous email to 1 user (testmail2@testmail2.testmail2)
10:03:42 INFO  [tracim:38][waitress] [EmailSender] Connecting from SMTP server mail.gandi.net
10:03:42 INFO  [tracim:38][waitress] [EmailSender] Connection OK
~~~

Expected

- [ ] if credential is wrong, Tracim must know that it doesn't work

**Comment by lebouquetin** [comment]
we MUST NEVER log information that we are not sure about. If login is not checked, do not log success message if you did not check the success

**Comment by PhilippeAccorsi** [comment]
Verified.
