### ISSUE TITLE
Distinguish user name and role in member list

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#1197]
Currently, member list is shown like second item of the following image: role is witten with same font 

![image](https://user-images.githubusercontent.com/907161/49118084-5ede0600-f2a3-11e8-8e31-f066109a742d.png)

Expected : 

- write role smaller and in grey in order to easily distinguish user name (which is the most important) and associated role which is secondary information

**Comment by PhilippeAccorsi** [comment]
Verified.
