### ISSUE TITLE
tinymce: translation about file bigger than 1Mo not exist

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1202]
If I try to upload an image bigger than 1Mo this message appear in tracim:
"Capture d’écran de 2018-10-11 17-23-45.png is bigger than 1mo, it can takes some time to upload, do you wish to continue?"
With two button "annuler" and "ok"

This message is not translated in french.
Button is not also translated "Annuler" is in french (and stay annuler if interface is in english)

Expected

- [ ] Translate message in tinymce if language in tracim is french.
- [ ] Translate button in english and in french

**Comment by Skylsmoi** [comment]
The file where this string is declared isn't part of the bundle.
It might be a bit tricky to give it the translation object.

**Comment by tracim** [comment]
@Skylsmoi I'm not sure to understand.

- This string is neither in TinyMCE nor in tracim code?
- The given module does not support translations?

**Comment by Skylsmoi** [comment]
file is here : https://github.com/tracim/tracim/blob/develop/frontend/dist/assets/tracim/tinymceInit.js

it's not a module, it's just a script to initialize tinymce

**Comment by tracim** [comment]
Isn't it possible to add this file in the translation process?
The file is stored with "dist/assets/tracim" but is a tracim specific file... shouldn't it be with other js stuff?

**Comment by Skylsmoi** [comment]
It might be possible, but it requires some testing.
This script must be loaded before any textareas starts to initialize tinymce or it will fail, that's why it is out the bundle and added to the page with it's own script tag declared before the app's ones

**Comment by tracim** [comment]
Ok, so lets move this fix to a future release

**Comment by Quiwy** [comment]
Not relevant anymore since using weblate
