### ISSUE TITLE
all app: if content is not created by user interface, you dont have first revision (just creation)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1206]
At present:

If you use webdav or if you import database in tracim v2, your content dont have first revision. When you open your content whis app, you are directly in edit mode.
For exemple; if you used webdav to upload one file. When you want to see this file in tracim the app is open directly en edit. If you click on 'cancel' you can see the preview of this file.

Expected

- [ ] if i upload content with webdav or if I import tracim v1 database, the file is visible with his first revision.
- [ ] edit mode is just when content is empty.

**Comment by Skylsmoi** [comment]
solution is: 
I only set app in EDIT mode if there is only one revision AND user has edit authorization **AND that revision has it's property `raw_content` to "" (empty string)**

**Comment by tracim** [comment]
Its not enough for files which have raw_content empty...

**Comment by PhilippeAccorsi** [comment]
@lebouquetin this is fix since yesterday night.

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi This modification add one regression. If you edit file, choose anther file and validate, you can see new revision in timeline but you stay in edit mode.

**Comment by PhilippeAccorsi** [comment]
Verified.
