### ISSUE TITLE
app file: download button in header of app file

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1228]
At present

button about download of file is visible before preview. All button is visible in same time.

Expected

Idea:
- [ ] have a button like we used for status with list of possibilities.

**Comment by LucBarry** [comment]
Currently 

Button about downloading files are always visible, even if the preview has not finished loading. All buttons are visible at the same time.

Expected 

Have a drop-down list with all the buttons grouped together

**Comment by PhilippeAccorsi** [comment]
Related to new design of app. See #2594
