### ISSUE TITLE
Files seems to be loaded in memory before to be sent

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#1233]
Currently : if I select a file of something like 60MB, then my browser hangs for a while. Then I can click on "validate" button.

It looks like the file is totally loaded in the browser - which must not be done

Expected:

- do not hangs on large file selection
- probably do not load file into memory (this is done for previewing images, doesn't it?)

I did this with a `.tar.gz` file.

**Comment by Skylsmoi** [comment]
files are b64 encoded for preview

**Comment by tracim** [comment]
This is useless for all file types except image files.

This must be limited to image files smaller than 2MB

**Comment by PhilippeAccorsi** [comment]
Verified.
