### ISSUE TITLE
add user: now backend check the lenght of password but frontend dont send 'none or null'

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1234]
**At present:**

Email is True in development.ini
Try to create a new user
An error 400 appear: code 2001: Length must be between 6 and 512.

The problem is because now backend check the lenght of password but frontend don't send value for password (blank value).

**Expected:**

Frontend:
- [ ] send none, null, or string (discuss with @inkhey )  for password when email notification is activated
@Skylsmoi when its done, assign @inkhey for this issue.

Backend:
- [ ] if email notification is activated backend need to add control about this value.

**Comment by Skylsmoi** [comment]
will send null

**Comment by PhilippeAccorsi** [comment]
@inkhey This issue is in todo, is normal?

**Comment by PhilippeAccorsi** [comment]
Verified.
