### ISSUE TITLE
sidebar: show primary color in sidebar just when you are in one sharedspace

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1242]
At present

In sidebar we show all shared space item number with the primary color.

Expected

- [ ] just show with primary color the shared space where you are.

**Comment by PhilippeAccorsi** [comment]
Related to #1168

**Comment by lebouquetin** [comment]
Show explicitly current active item. TODO @celiamgtt make proposals.

**Comment by Quiwy** [comment]
Closed in favor of [#5814](https://github.com/tracim/tracim/issues/5814)
