### ISSUE TITLE
sidebar: color consistency about app

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1244]
at present

- dashboard: color of app and icon in white
- sidebar: color of app and icon in black
- filter by app: icon in black in title of the page

Expected

- [ ] have text-icon in white in the sidebar
- [ ] have text-icon in the app color in title of the page ? (to be discussed)

**Comment by PhilippeAccorsi** [comment]
Related to #1168

**Comment by tracim** [comment]
@Skylsmoi to fix if you have time. Otherwise, we'll push this to 2.2

**Comment by tracim** [comment]
After  test, this is not better with white. Here are screenshots:

With text in white:

![image](https://user-images.githubusercontent.com/9657115/49661891-a5252900-fa4a-11e8-9388-9d59e343e741.png)

With text in black:

![image](https://user-images.githubusercontent.com/9657115/49661917-b9692600-fa4a-11e8-8428-141c9fa3718e.png)
