### ISSUE TITLE
dont allow to change password/email if user auth type is not in ['unknown','internal']

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1246]
**Describe the bug**
currently account modification is allowed for all account type in frontend, it should be disabled for all non-internal account and also for 'unknown' case.

**Comment by tracim** [comment]
@Skylsmoi if not enough time for fix, then we'll add a note in the release explaining this is a known bug

**Comment by PhilippeAccorsi** [comment]
After discuss with @inkhey : @Skylsmoi you need to accept 'unknown'

**Comment by PhilippeAccorsi** [comment]
Verified.
