### ISSUE TITLE
add CaldavZap to tracim v2

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1250]
add the calendar from tracim v1 (see release_01.xx.xx_end_of_life) into tracim v2.

This requires backend to have Radical server ready

Depends on #1181

**Comment by Skylsmoi** [comment]
caldavzap integration report
1) integrate caldavzap in backend like in tracim v1

pros:

    easy to setup in frontend
    app bundler of ~30ko (no react, no babel, nothing)
    allow lazy loading caldavzap by the iframe (the app doesn't includes caldavzap code, the iframe will load it on demande)

cons:

    require work in backend
    need to figure out a solution for auth

2) bundle caldavzap by webpack

pros:

    consistency with other apps
    full frontend integration

cons:

    require work to convert any global declaration into module.exports (spoiler: there's a lot)
    big bundle size (all caldavzap + react) (need lazy loading)

**Comment by tracim** [comment]
TODO : 

- integrate caldavzap with user calendar (= user calendar + calendar of all shared spaces the user belongs to)
- allow caldavzap to load an explicit list of caldav urls
- iframe with index.html should be open with right variables/parameters (LANG + SERVER URL or list of CALENDAR URLS)
- integration with sidebar menu (for workspace calendars) + color.json

**Comment by inkhey** [comment]
Main issue with caldavzap is actually fixing it to force visibility of all calendar given in configuration.
@Skylsmoi if you have more specific information about this issue, please explain here.

**Comment by Skylsmoi** [comment]
to test caldavzap:
- `git checkout feature

**Comment by PhilippeAccorsi** [comment]
We need also to copy `basic_setup.caldav_storage_dir = %(here)s/radicale_storage/` from `backend/development.ini.sample`to BASIC SETUP part in `backend/development.ini` .

**Comment by PhilippeAccorsi** [comment]
Verified.
