### ISSUE TITLE
My account: Profile menu is visible if juste LDAP authorized / Password menu is also visible if LDAP,INTERNAL authorized

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1268]
At present

Two case:
- 1 => only LDAP authorized (in development.ini)
In my account you can see Profile menu and you have fullname and change email input.

- 2 => LDAP, INTERNAL authorized (in development.ini)
In my account you can see Profile and Password menu and you have all input visible.

Expected

If user is an LDAP user:
- [x] Password menu not visible
- [x] Profile menu is visible but just change fullname is available for administrator (dont show change email input)

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi missing case:
- if admin go in account of user => if its LDAP user: just show profile with fullname input. (dont show email input and password menu).

**Comment by PhilippeAccorsi** [comment]
Verify also that you check auth_type about user you see information.

**Comment by Skylsmoi** [comment]
@PhilippeAccorsi I couldn't properly test the fix since I don't have the ldap server.
I haven't tested the display that a user with auth_type as "ldap" see in its account page (/ui/account)

If you validate it, I'll merge the PR

**Comment by PhilippeAccorsi** [comment]
Thats ok for me. You can merge.

**Comment by PhilippeAccorsi** [comment]
Verified.
