### ISSUE TITLE
Webdav digest invalided when user email changed

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#127]
Directly related to #92.

When user email is updated, we can't update webdav digest (because we need origin password to make it). Two case:

* User edit his own email: We can add "current_password" field
* Admin edit user email: User should be invited to validate this new email. Process will ask password and we will able to make webdav digest.

**Comment by inkhey** [comment]
webdav digest auth as been removed in tracim v2+, there is only the basic auth mecanism now. So this issue is deprecated.
