### ISSUE TITLE
forgot password: not working if email notification is activated but working after first login and logout

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1270]
At present

When you arrive in login page, if you click on forgot password, you see a message about notification being not activated. But it's activated in backend.
Login with an account, you can see all option about notification by email activated. 
Logout and return to forgot password.
You have the good form to enter your email.

Expected

- [ ] show good message if email is activated.

You can use GET /api/v2/system/config

**Comment by Skylsmoi** [comment]
@inkhey @lebouquetin 

to do this, I need to be able to get the tracim's config even if there is no user connected

The endpoint `/api/v2/system/config` should not return 401 unauthorized

**Comment by Skylsmoi** [comment]
backend related pr https://github.com/tracim/tracim/pull/1279

**Comment by PhilippeAccorsi** [comment]
Verified.
