### ISSUE TITLE
set Tracim as Progressive Web App (PWA)

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1272]
setup a manifest.json in the repo

use this logo https://algoo.trac.im/workspaces/30/folders/7842/files/7851

**Comment by Skylsmoi** [comment]
@lebouquetin 
in the manifest.json, we should set a background color for the slapsh screen.
Problem: the background color is configurable and manifest is a json file.

I'm not sure I can set the primary color in the manifest.json automatically

should we set a default value and manually set the primary color ?

**Comment by Skylsmoi** [comment]
https://github.com/tracim/tracim/pull/1286

**Comment by Skylsmoi** [comment]
I can't test it on my unsecure context (self signed certificate)
We need to test this demo.tracim

It means switching demo.tracim to the branch feature/1272/add_manigest_json (yes, mani**g**est. It's a typo in the branch name) and rebuild

**Comment by Skylsmoi** [comment]
docs: https://developer.mozilla.org/en-US/docs/Web/Apps/Progressive/Add_to_home_screen

**Comment by PhilippeAccorsi** [comment]
Done.
