### ISSUE TITLE
cypress_test: config file not use new development.ini.sample and bdd is not generated automatically

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1274]
At present

Cypress use cypress_test.ini but its not generated by development.ini.sample and its used old development.ini.sample (before refactoring).
Cypress use also a bdd not generated by cypress

Expected

- [ ] generate this config file with script setup_functionnal_tests.sh (use development.ini.sample)
- [ ] generate bdd also with this script setup_functionnal_tests.sh (you can find information about that in setup_default_backend.sh)

**Comment by raphj** [comment]
This has been revamped. I think we are good now on this topic. See the run_dev_backend.sh script.
