### ISSUE TITLE
error code 500 instead of 400 for ExternalAuthModificationDisabled error

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1275]
```
PUT /api/v2/users/me/email
PUT /api/v2/users/me/password
```
raise http status code 500 instead of 400 for error :
`
EXTERNAL_AUTH_USER_PASSWORD_MODIFICATION_UNALLOWED
EXTERNAL_AUTH_USER_EMAIL_MODIFICATION_UNALLOWED
`

**Comment by PhilippeAccorsi** [comment]
Related to #1267

**Comment by PhilippeAccorsi** [comment]
Verified.
