### ISSUE TITLE
Special case: webdav: duplication of file instead new revision

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#129]
(cf. private discussion with Damien)

After copy paste document in folder where file name already exist, document was not "replaced" but a second document has been created.

TODO: Try to reproduce (not fail like this usually ...) and fix it.

**Comment by tracim** [comment]
@buxx even if you do not reproduce, this issue need to be investigated in our code (ie ensure there is a check before creating a new Content through webdav). Note : the fix of this issue must include unit test cases

**Comment by buxx** [comment]
@lebouquetin Question about bug: Document duplicate itself at thirst copy-paste" (it doesn't exist before) or after a copy-paste on existing file ?

**Comment by tracim** [comment]
@buxx I don't really know.

When asking for "creation of a new Content", our code must check if the ressource is already registered then create it (not "just create what is asked to be created")

**Comment by buxx** [comment]
Solved in recents commits (in particular 73f79ef and 459727259ecbb07fb68e1a16db02024d49168233 ).
