### ISSUE TITLE
Disabled admin user can connect

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#1298]
**Describe the bug**

Just after disable admin user, i can disconnect and connect with it's credentials.

**To Reproduce**

1. Use docker image "latest"
2. Login with admin@admin.admin
3. Disable admin@admin.admin user
4. disconnect
5 login with admin@admin.admin

**Expected behavior**

Should not be possible to login with admin@admin.admin

**Comment by tracim** [comment]
You should not be able to disable yourself.

Issue(s) may be:
- in rest api
- in frontend ignoring HTTP 400
- in frontend which should disable this feature for current user.

@inkhey, @Skylsmoi, the 3 cases must be fixed

**Comment by buxx** [comment]
I test again, i was wrong, i disabled an other user account. Sorry for disturbing.
