### ISSUE TITLE
Old contents "page" are still pages (which make some notification not working)

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#1299]
**Description**

When editing label of an old page content, no notification is send. The reason is source code is looking at content type and search for html-document (and the content has page)

Todo : add a data upgrade which convert all page into htmldocument

**Comment by inkhey** [comment]
@lebouquetin should i also correct the code to work with alias mecanism (as that the main reason of the problem) or should i just create a migration script ?

**Comment by tracim** [comment]
Hm... what seems to be the simplest for you? My feeling is the following one:

- if migration is done (and working well), the alias code will become useless
- currently, the alias code is working almost everywhere...

So, the options are:
- make a migration and remove the alias code
- use the alias code everywhere (and do not make the migration)

I suggest you evaluate the option of writing a migration (particularly with the json column) and if you are confident, then go for the first option, otherwise go for the second one.

What do you think?

**Comment by lebouquetin** [comment]
@PhilippeAccorsi test this fix with data from our production

**Comment by PhilippeAccorsi** [comment]
Maybe I have missed to update database.

**Comment by PhilippeAccorsi** [comment]
@lebouquetin After migration of bdd with command `alembic -c development.ini upgrade head` Thats working good.

FI: in first step, I have misse to upgrade bdd.

**Comment by PhilippeAccorsi** [comment]
Verified.
