### ISSUE TITLE
Email template not found with docker image release_02.01.00_rc2

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#1304]
**Describe the bug**

When ask for a forgotten password, backend produce 500 error. Error is the email template is not found. Template is searched in "/etc/tracim/tracim_backend/..." folder.

**To Reproduce**

1. User docker image release_02.01.00_rc2
2. Configure email notifications
3. Ensure configuration of template folder is default value `email.template_dir = %(here)s/tracim_backend/templates/mail`
4. Ask for forgotten password

**Expected behavior**

Template should be searched in `/tracim/backend/tracim_backend/...` folder instead `/etc/tracim/tracim_backend/...`.

**Comment by tracim** [comment]
I think this is solved. Just verify if fix is in  common.sh

**Comment by PhilippeAccorsi** [comment]
I think this is solved. Just verify if fix is in common.sh

**Comment by PhilippeAccorsi** [comment]
This is solved since release_02.01.00_rc5.

I close this issue.
