### ISSUE TITLE
docker image after 2.0.0: development.ini use parameter "%(here)s" but some lines are not automatically modified when you start docker

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1308]
At present

With release_02.01.00-rc1, rc2,rc3 and rc4.

When you start docker for the first time, some line are modified in development.ini about path for exemple.
But some "%(here)s" are not replaced so path is wrong.

Ex: email template:
~~~
## shortcut for template_dir path
email.template_dir = %(here)s/tracim_backend/templates/mail
~~~

Expected

- [ ] verify all line with "%(here)s" and modify value automatically if its necessary.

**Comment by lebouquetin** [comment]
Not sure I understand exactly what is expected.

**Comment by PhilippeAccorsi** [comment]
Verified.
