### ISSUE TITLE
logo in header: max size for logo is not defined

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1309]
At present

If I use logo with big size of height and width, the header increase to show the entire logo.
Example:
![capture d ecran de 2019-01-11 16-10-19](https://user-images.githubusercontent.com/25848257/51042039-925ac280-15bb-11e9-99b7-44b7b9970cd0.png)

Expected

- [ ] define max-height and max-width
- [ ] add transparency for logo background to make sure header size not moving.

example:
![capture d ecran de 2019-01-11 16-11-00](https://user-images.githubusercontent.com/25848257/51042054-9dadee00-15bb-11e9-92d0-da1d54034b97.png)

**Comment by Skylsmoi** [comment]
fixed in https://github.com/tracim/tracim/commit/7718e2dd96a246420d8e59603029ee882911f1b3

**Comment by PhilippeAccorsi** [comment]
Issue fixed.
