### ISSUE TITLE
Documentation: wrong command in /backend/doc/cli.md

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1310]
**At present**

In Help I can see this two command `tracim user create -h` and `tracim user update -h` but this command not working.

**Expected**

Command working are:
- [ ] tracimcli user create -h
- [ ] tracimcli user update -h

**Comment by inkhey** [comment]
I just make a try and it's working correctly on my system.
@PhilippeAccorsi  can you provide more information about you case (and of course verify if you test command in correct venv).


>  user: ~/tracim_v2 develop[c39f4757] ✔ $                                                                                                                         [⬢ 7.10.1] [ve:env] [9:18] 
>  ❯ tracimcli user update -h
> /home/user/tracim_v2/backend/env/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
>   """)
> usage: tracimcli user update [-h] [-c CONFIG_FILE] -l LOGIN [-p PASSWORD]
>                              [-g [ADD_TO_GROUP [ADD_TO_GROUP ...]]]
>                              [-rmg [REMOVE_FROM_GROUP [REMOVE_FROM_GROUP ...]]]
>                              [--send-email]
> 
> Create or update user.
> 
> optional arguments:
>   -h, --help            show this help message and exit
>   -c CONFIG_FILE, --config CONFIG_FILE
>                         application config file to read (default:
>                         development.ini)
>   -l LOGIN, --login LOGIN
>                         User login (email)
>   -p PASSWORD, --password PASSWORD
>                         User password
>   -g [ADD_TO_GROUP [ADD_TO_GROUP ...]], --add-to-group [ADD_TO_GROUP [ADD_TO_GROUP ...]]
>                         Add user to group
>   -rmg [REMOVE_FROM_GROUP [REMOVE_FROM_GROUP ...]], --remove-from-group [REMOVE_FROM_GROUP [REMOVE_FROM_GROUP ...]]
>                         Remove user from group
>   --send-email          Send mail to user
>                                                                                                                                                                                                           
>  user: ~/tracim_v2 develop[c39f4757] ✔ $                                                                                                                         [⬢ 7.10.1] [ve:env] [9:18] 
>  ❯ tracimcli user create -h
> /home/user/tracim_v2/backend/env/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
>   """)
> usage: tracimcli user create [-h] [-c CONFIG_FILE] -l LOGIN [-p PASSWORD]
>                              [-g [ADD_TO_GROUP [ADD_TO_GROUP ...]]]
>                              [-rmg [REMOVE_FROM_GROUP [REMOVE_FROM_GROUP ...]]]
>                              [--send-email]
> 
> Create or update user.
> 
> optional arguments:
>   -h, --help            show this help message and exit
>   -c CONFIG_FILE, --config CONFIG_FILE
>                         application config file to read (default:
>                         development.ini)
>   -l LOGIN, --login LOGIN
>                         User login (email)
>   -p PASSWORD, --password PASSWORD
>                         User password
>   -g [ADD_TO_GROUP [ADD_TO_GROUP ...]], --add-to-group [ADD_TO_GROUP [ADD_TO_GROUP ...]]
>                         Add user to group
>   -rmg [REMOVE_FROM_GROUP [REMOVE_FROM_GROUP ...]], --remove-from-group [REMOVE_FROM_GROUP [REMOVE_FROM_GROUP ...]]
>                         Remove user from group
>   --send-email          Send mail to user
>

**Comment by PhilippeAccorsi** [comment]
I have updated issue. The command you try is working, but this is not command visible in documentation ;)

**Comment by PhilippeAccorsi** [comment]
Verified.
