### ISSUE TITLE
Docker environment variables

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#1311]
Docker documentation says:

```
Environment variables can be given to the container:

    DATABASE_TYPE (values: postgresql, mysql, sqlite)

If DATABASE_TYPE is postgresql or mysql set these variables:

    DATABASE_USER
    DATABASE_PASSWORD
    DATABASE_HOST
    DATABASE_PORT
    DATABASE_NAME
```

But, if they environment variables are without effect if tracim config file already exist. This is because we use these env vriable only at [config creation](https://github.com/tracim/tracim/blob/develop/tools_docker/Debian_Uwsgi/common.sh#L4).

This can be disturbing. We should have discussion about that.

**Comment by PhilippeAccorsi** [comment]
In the futur, all parameters for config files will be available directly with environment variables. 
And if you update some environment variables, config files are changes automatically.

**Comment by PhilippeAccorsi** [comment]
Verify if env parameter working correctly.

**Comment by PhilippeAccorsi** [comment]
Need some test, for the moment I'm not sure all env variable working correctly if variable is added at docker run.

**Comment by PhilippeAccorsi** [comment]
Its not possible to use env variable when tracim is started with service.

Need to solved this issue first #1860

**Comment by PhilippeAccorsi** [comment]
Documentation about env variable and fix for that are in this issue #1860

**Comment by PhilippeAccorsi** [comment]
Waiting merge of #1869 to test env variable working correctly

**Comment by PhilippeAccorsi** [comment]
Env variable is working good.
Verified.
