### ISSUE TITLE
UX: use loaders when screen refreshs

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#1316]
**Is your feature request related to a problem? Please describe.**

When change dashboard, or change filter, screen can make some time to be refreshed. We should use loaders like a gif loader or screen shadow.

**Describe the solution you'd like**

When part of screen will be updated after ajax requet(s), replace page part by a loader.
Note: Loader when image previews is loading could be appreciated to.

**Comment by PhilippeAccorsi** [comment]
I think its also necessary when you save document with image inside for exemple. Sometime is long to upload this revision but user don't know what is going on.

**Comment by Quiwy** [comment]
We have some loaders now, but not for everything : https://github.com/tracim/tracim/issues/5795#issue-1308166646

**Comment by buxx** [comment]
:ok_hand:
