### ISSUE TITLE
Docker: missing mail_fetcher in entrypoint and also mail_notifier

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1318]
At present

Reply by email not working in docker images because some parameter is not correctly added.
Daemon about mail_fetcher (sync) and mail_notifier (async) is not started.

Expected

- [x] add possibility to start mail_fetcher or mail_notifier
=> its necessary to export 'export TRACIM_CONF_PATH="$(pwd)/development.ini"' before starting daemon.

**Comment by PhilippeAccorsi** [comment]
Idea for running mail_fetcher daemon:

`export TRACIM_CONF_PATH="/etc/tracim/development.ini"`
`nohup python3 /tracim/backend/daemons/mail_fetcher.py > /var/tracim/logs/mail_fetcher.log 2>&1 </dev/null &`

**Comment by PhilippeAccorsi** [comment]
@lebouquetin do you think its necessary to save the mail_fetcher log? Because inside we can see raw_content of reply.

**Comment by PhilippeAccorsi** [comment]
Idea to entrypoint:

Use env variable to start email_fetcher or mail_notifier (but what is going on if you dont use reply by email?).
EMAIL_MODE=sync 
EMAIL_MODE=async

**Comment by PhilippeAccorsi** [comment]
First test with daemon is working good for reply_by_email (after install lib requests see #1317 )

Now I try to use supervisord for better solution.

**Comment by buxx** [comment]
@PhilippeAccorsi 

> Idea to entrypoint:
>
>Use env variable to start email_fetcher or mail_notifier (but what is going on if you dont use reply by email?).
>EMAIL_MODE=sync
>EMAIL_MODE=async

Take care with `EMAIL_MODE` env variable: there are config in development.ini to configure that in Tracim. Is docker image user use this env variable, he must update tracim config too (or config must be updated automatically).

**Comment by PhilippeAccorsi** [comment]
@buxx my answer is just an idea, but thanks for your information.

I have used more explicit variable:
- REPLY_BY_EMAIL
- EMAIL_MODE_ASYNC

**Comment by PhilippeAccorsi** [comment]
Verified.
