### ISSUE TITLE
Add link to webdav in the homepage of a workspace

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#132]
Currently, the webdav url is not available in the user interface.
Required : 
- allow user to get the information (as he can for calendars)
- show the information in the workspace home page (like it is done for calendars)

@Skylsmoi , Ask @buxx for extra information about this subject

**Comment by Skylsmoi** [comment]
https://github.com/tracim/tracim/commit/6fca576776cebd605772ff8a6128753cb4132e40
the front is ready.
see tracim/tracim/tracim/controllers/workspace.py l 70 for TODO

Bug assigned to @buxx to set the real url
