### ISSUE TITLE
White screen on web interface with old firefox

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#1326]
**Describe the bug**

White screen when open Tracim web interface with old firefox version (~3 years)

**To Reproduce**

**Expected behavior**

Two possibility (open second issue if both solution must be used):

* Display a page when Tracim web interface fail to load.
* Be compatible with old web browsers

**Additional context**

I don't have javascript error under the hand. I will try to found it on my "old" computer.

**Comment by Quiwy** [comment]
@buxx : I think we can close this as the oldest esr firefox version supported by mozilla was released in August 2021.

**Comment by buxx** [comment]
yes !
