### ISSUE TITLE
Cypress test: test not working good all the time tiny_mce__can_type_content_spec.js

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1327]
**At present**

The test "app_html-document/tiny_mce__can_type_content_spec.js" is not working correctly each time is starting. Sometime you just need to restart this test and its working

~~~
Running: app_html-document/tiny_mce__can_type_content_spec.js...                       (19 of 53) 
  Known users as a workspace-manager
  1) Type into tiny mce and save from dashboard
  ✓ Type into tiny mce and save (14127ms)
  2) Check if TinyMCE open content of the document
  ✓ Check TinyMCE is active if document is empty when opening (13888ms)
  ✓ Check TinyMCE is not active when opening if document has been modified (17101ms)
  3 passing (1m)
  2 failing
  1) Known users as a workspace-manager Type into tiny mce and save from dashboard:
     CypressError: Timed out retrying: cy.click() failed because this element is disabled:
<button type="button" data-cy="editionmode__button__submit" class="html-document__editionmode__submit editionmode__button__submit btn highlightBtn" disabled="" data-radium="true" style="background-color: rgb(0, 204, 0); color: rgb(253, 253, 253); border-color: rgb(0, 204, 0);">Validate</button>
Fix this problem, or use {force: true} to disable error checking.
https://on.cypress.io/element-cannot-be-interacted-with
      at Object.cypressErr (http://localhost:1337/__cypress/runner/cypress_runner.js:65238:11)
      at Object.throwErr (http://localhost:1337/__cypress/runner/cypress_runner.js:65203:18)
      at Object.throwErrByPath (http://localhost:1337/__cypress/runner/cypress_runner.js:65230:17)
      at Object.retry (http://localhost:1337/__cypress/runner/cypress_runner.js:58775:16)
      at retryActionability (http://localhost:1337/__cypress/runner/cypress_runner.js:50564:19)
      at tryCatcher (http://localhost:1337/__cypress/runner/cypress_runner.js:127090:23)
      at Function.Promise.attempt.Promise.try (http://localhost:1337/__cypress/runner/cypress_runner.js:124464:29)
      at tryFn (http://localhost:1337/__cypress/runner/cypress_runner.js:59011:24)
      at whenStable (http://localhost:1337/__cypress/runner/cypress_runner.js:59039:12)
      at http://localhost:1337/__cypress/runner/cypress_runner.js:58799:16
      at tryCatcher (http://localhost:1337/__cypress/runner/cypress_runner.js:127090:23)
      at Promise._settlePromiseFromHandler (http://localhost:1337/__cypress/runner/cypress_runner.js:125108:31)
      at Promise._settlePromise (http://localhost:1337/__cypress/runner/cypress_runner.js:125165:18)
      at Promise._settlePromise0 (http://localhost:1337/__cypress/runner/cypress_runner.js:125210:10)
      at Promise._settlePromises (http://localhost:1337/__cypress/runner/cypress_runner.js:125289:18)
      at Promise._fulfill (http://localhost:1337/__cypress/runner/cypress_runner.js:125234:18)
  2) Known users as a workspace-manager Check if TinyMCE open content of the document:
     Uncaught TypeError: Cannot read property 'startContainer' of null
This error originated from your application code, not from Cypress.
When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
This behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.
https://on.cypress.io/uncaught-exception-from-application
      at xc (http://localhost:1337/assets/tinymce/js/tinymce/tinymce.min.js:2:128043)
      at Object.getUndoBookmark (http://localhost:1337/assets/tinymce/js/tinymce/tinymce.min.js:2:868)
      at Object.add (http://localhost:1337/assets/tinymce/js/tinymce/tinymce.min.js:2:225463)
      at Ax.<anonymous> (http://localhost:1337/assets/tinymce/js/tinymce/tinymce.min.js:2:223694)
      at $m.c.fire (http://localhost:1337/assets/tinymce/js/tinymce/tinymce.min.js:2:182368)
      at Ax.fire (http://localhost:1337/assets/tinymce/js/tinymce/tinymce.min.js:2:182880)
      at $C (http://localhost:1337/assets/tinymce/js/tinymce/tinymce.min.js:2:310333)
      at http://localhost:1337/assets/tinymce/js/tinymce/tinymce.min.js:2:313699
      at http://localhost:1337/assets/tinymce/js/tinymce/tinymce.min.js:2:84969
      at http://localhost:1337/assets/tinymce/js/tinymce/tinymce.min.js:2:57929

~~~

**Expected**

- [ ] If this test not working good all the time, we need to disabled this test.

**Comment by PhilippeAccorsi** [comment]
The problem here is the time necessary for tinymce to be full ready.

Hotfix can be to increase wait timer for tinymce.
At present we used 2second wait. We need to try with 4second.
If its not working, we need to deactivate this test and find better solution to make sure tinymce is charged.

**Comment by PhilippeAccorsi** [comment]
Idea:
Find one tinymce element just visible when tinymce is full ready, and use the visibility of this element before next test.

**Comment by Skylsmoi** [comment]
there might be some solutions here: https://stackoverflow.com/questions/37641019/execute-js-function-after-tinymce-is-loaded

**Comment by Skylsmoi** [comment]
> Idea:
> Find one tinymce element just visible when tinymce is full ready, and use the visibility of this element before next test.

Problem is, this will never be 100% safe

**Comment by Skylsmoi** [comment]
Tests result:
There is 2 things to check:
- tinymce library is loaded
- editor is loaded

they are on 2 different data
`window.tinymce` means that the library is loaded but doesn't have to imply that the editor is loaded
`window.tinymce.activeEditor` ensure that the editor is loaded

to send an event when the editor is loaded, set the code bellow in `tinymce.init({...setup: function (editor) { ... })`
``` javascript
$editor.on('init', function (e) {
  const event = new CustomEvent('tinymceLoaded', {detail:
  document.dispatchEvent(event)
})
```

to handle this event, in your test, use:
``` javascript
cy.window().then(win => {
  Cypress.$(win.document).on('tinymceLoaded', () => {
    ...
  })
})
```

Current problem is: once in the handler of tinymceLoaded, you should only write 
``` javascript
win.tinyMCE.activeEditor.setContent(DOCUMENT_HTML_CONTENT)
win.tinyMCE.activeEditor.save()
```
setContent will set the string in param in the tinymce iframe and .save() is supposed to propagate that change in the real textarea of the dom.
But the .save() doesn't seem to properly trigger everything and without this, the onChange handler on the textearea in the React code isn't triggered. Then, the React component doesn't know that the text has changed so the component doesn't know it's supposed to enable the submit btn. So the test fails

**Comment by PhilippeAccorsi** [comment]
@lebouquetin What do you think about this issue. Sometime we need to restart cypress test manually in travis. But its not easy to solve this problem.
Do you think we need to add mandatory and project 2.2 for this issue?

**Comment by rajneeshm49** [comment]
> Tests result:
> There is 2 things to check:
> 
> * tinymce library is loaded
> * editor is loaded
> 
> they are on 2 different data
> `window.tinymce` means that the library is loaded but doesn't have to imply that the editor is loaded
> `window.tinymce.activeEditor` ensure that the editor is loaded
> 
> to send an event when the editor is loaded, set the code bellow in `tinymce.init({...setup: function (editor) { ... })`
> 
> ```js
> $editor.on('init', function (e) {
>   const event = new CustomEvent('tinymceLoaded', {detail:
>   document.dispatchEvent(event)
> })
> ```
> 
> to handle this event, in your test, use:
> 
> ```js
> cy.window().then(win => {
>   Cypress.$(win.document).on('tinymceLoaded', () => {
>     ...
>   })
> })
> ```
> 
> Current problem is: once in the handler of tinymceLoaded, you should only write
> 
> ```js
> win.tinyMCE.activeEditor.setContent(DOCUMENT_HTML_CONTENT)
> win.tinyMCE.activeEditor.save()
> ```
> 
> setContent will set the string in param in the tinymce iframe and .save() is supposed to propagate that change in the real textarea of the dom.
> But the .save() doesn't seem to properly trigger everything and without this, the onChange handler on the textearea in the React code isn't triggered. Then, the React component doesn't know that the text has changed so the component doesn't know it's supposed to enable the submit btn. So the test fails

This doesn't work. though tinymce is emitting the event but this code in cypress is unable to catch the event. Is there any soultion we can check whether tinymce is loaded.

**Comment by Skylsmoi** [comment]
You can find the custom cypress command we developed using this theory here:
https://github.com/tracim/tracim/blob/develop/functionnal_tests/cypress/support/commands.js#L108

The code to add in the tinymce init function to fire the event here:
https://github.com/tracim/tracim/blob/develop/frontend/dist/assets/tracim/tinymceInit.js#L55

And an example of its usage here:
https://github.com/tracim/tracim/blob/develop/functionnal_tests/cypress/integration/generic_frontend/operation_tinymce.js#L18

**Comment by Skylsmoi** [comment]
The feature might not be perfect but it helped us a lot to reduces our issues with cypress and tinymce when running on travis

**Comment by rajneeshm49** [comment]
is the `editor` property over here mandatory to pass - 
const event = new CustomEvent('tinymceLoaded', {detail: {}, editor: this}) 

I get an error 
Argument of type '{ detail: {}; editor: any; }' is not assignable to parameter of type 'CustomEventInit<{}>'.
  Object literal may only specify known properties, and 'editor' does not exist in type 'CustomEventInit<{}>'

**Comment by rajneeshm49** [comment]
i copied
Cypress.Commands.add('waitForTinyMCELoaded', () => {
  cy.document().then($doc => {
    return new Cypress.Promise(resolve => { // Cypress will wait for this Promise to resolve
      const onTinyMceLoaded = () => {
        $doc.removeEventListener('tinymceLoaded', onTinyMceLoaded) // cleanup
        resolve() // resolve and allow Cypress to continue
      }
      $doc.addEventListener('tinymceLoaded', onTinyMceLoaded)
    })
  })
})

Cypress.Commands.add('typeInTinyMCE', (content) => {
  cy.window()
    .its('tinyMCE')
    .its('activeEditor')
    .then(activeEditor => {
      activeEditor.setContent(content)
      activeEditor.save()
    })
})
in command.js and 

cy.waitForTinyMCELoaded().then(() => {
  cy.typeInTinyMCE(termsContent)
})
in my spec-file but it throws an error "Your callback function returned a promise which never resolved." Looks like this part 
$doc.addEventListener('tinymceLoaded', onTinyMceLoaded)
isnt working

**Comment by raphj** [comment]
Might still be relevant, manipulating TinyMCE from our tests is (was?) kind of fragile. However, now, Cypress tests pass for all intent and purposes.
