### ISSUE TITLE
Create documentation for apache auth.

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1337]
we need to document clearly how to use apache auth.

**Comment by PhilippeAccorsi** [comment]
More information available to make an explicit exemple for using auth apache (with user/password file).

**Necessary module:**
- mod_headers (necessary on ubuntu)
- mod_authz_user (need to verify if this module is not install by default)  

**Using file with encrypted password:**
add first user => sudo htpasswd -c /etc/apache2/.htpasswd "test@test.test"
add more useer => sudo htpasswd /etc/apache2/.htpasswd "test1@test1.test1"

**Idea to close apache session:**
https://stackoverflow.com/questions/233507/how-to-log-out-user-from-web-site-using-basic-authentication

**Comment by PhilippeAccorsi** [comment]
https://httpd.apache.org/docs/2.4/fr/howto/auth.html

**Comment by PhilippeAccorsi** [comment]
Exemple of auth with file and ldap:
in development.ini you need to autorised ldap.

in apache conf:
~~~
    <Location "/">
      AuthType Basic
      AuthName "Restricted Access"
      AuthBasicProvider file ldap
      AuthUserFile /etc/apache2/.htpasswd
      AuthLDAPURL ldap://127.0.0.1:389/ou=Users,dc=tracim,dc=fr
      Require valid-user
    </Location>
~~~

User in file can connect to tracim and user in ldap also.

**Comment by PhilippeAccorsi** [comment]
Verified.
