### ISSUE TITLE
Frontend: url probleme with tinymce

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1342]
**At present**

When you use rich text you can add url link but when you validate option in tinymce, tinymce cut the beginning of url:
ex:
If you want to add this link "https://algoo.tracim.fr/ui/workspaces/30/contents/html-document/8211?folder_open=1996,8210"

**In tinymce you have:**
url: https://algoo.tracim.fr/ui/workspaces/30/contents/html-document/8211?folder_open=1996,8210
Text to display: https://algoo.tracim.fr/ui/workspaces/30/contents/html-document/8211?folder_open=1996,8210

**When you validate form, url is change**
url: workspaces/30/contents/html-document/8211?folder_open=1996,8210
Text to display: https://algoo.tracim.fr/ui/workspaces/30/contents/html-document/8211?folder_open=1996,8210

So now if you try to open url, you not arrive directly on the document.

**Expected**

- [ ] tinymce don't cut url automatically.

**Comment by celiamgtt** [comment]
Update : with TinyMCE links don't work between workspaces (and when we're creating a link on a specific text even in the same workspace).

![bug_url](https://user-images.githubusercontent.com/50453784/63257087-538b9a00-c279-11e9-9a28-226d2fc8ad55.gif)

**Comment by metzgegu** [comment]
This bug appears only with same domain links,
This isn't a bug but a feature of tinyMCE, we just need to configure it. [See](https://www.tiny.cloud/docs/configure/url-handling/)

**Comment by PhilippeAccorsi** [comment]
Verified.
