### ISSUE TITLE
Docker: automated build not really working on docker hub. Its necessary to use jenkins.

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1352]
At present

Its not possible to start automatic build on dockerhub with specific tag present on github repo.
So its not possible to build image correctly with dockerhub.

Expected

- [ ] re-use jenkins like we use for tracim_v1
- [ ] adapt script and scenario in jenkins for tracim_v2
- [ ] create dockerfile and other file for testing.

**Comment by PhilippeAccorsi** [comment]
Need to fix jenkins problem (local jenkins) before continue this issue.

**Comment by raphj** [comment]
We don't use Jenkins anymore.
