### ISSUE TITLE
Folder: right problem for contributor

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1353]
At present

Contributor cant create folder because this is role of shared space manager. If you are in "List of contents" you not see option in button "Create" (this is normal).
But in dashboard, you can see button "Create folder" (this is not normal).
If you try to create folder, popup appear, but when you validate, this error 403 appear:
~~~
{"message": "InsufficientUserRoleInWorkspace", "code": 4003, "details": {"error_detail": {}}}
~~~

Expected

- [ ] dont show option if user don't have right for this.

**Comment by PhilippeAccorsi** [comment]
@lebouquetin I have the impression that there is a regression, I don't know why but  I remember checking the roles and visual effect. Its strange if I missing this.

**Comment by tracim** [comment]
I confirm contributor should not see create folder button

**Comment by PhilippeAccorsi** [comment]
Verified.
