### ISSUE TITLE
Workspace invitation must result in notification subscription by default

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#1358]
Currently:

if I invite a member to the current workspace, the member is invited, but the notification subscription is set to false by default

Expected: new member of a workspace must be subscripted to notifications by default.

**Comment by inkhey** [comment]
@lebouquetin if user was just created with invitation, i'm not sure that set notification subscription to true as user was not connected yet is a great idea. 

I propose to set notification by default to true when adding workspace to user **but** disable notification for "unknown" auth user.

**Comment by PhilippeAccorsi** [comment]
Verfiied.
