### ISSUE TITLE
unexpected error when creating a file

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#136]
On Windows 10.
I tried to create a file and got an error
![selection_006](https://cloud.githubusercontent.com/assets/11177014/20520285/82bec69a-b0a6-11e6-99df-3afc47c98319.png)

[unexpected_error_when_creating_file.zip](https://github.com/tracim/tracim/files/606066/unexpected_error_when_creating_file.zip)

**Comment by buxx** [comment]
Marked as invalid (windows incompatibility with http dump debug method). Tests will be done again.
