### ISSUE TITLE
slash-like `⧸` special char breaks webdav server

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#1362]
Current status:

In order not to limit user usage of special chars, we implemented a workaround on webdav 2 years ago which is an on-the-fly special char replacement.

For example `/` is replaced by `⧸` was webdav interface. This was working and allows to use special chars like `/`, `*`, and other special chars.

Now, this replacement seems broken - at least for shared space names.

TODO:

- [X] find in the code the list of special char replacements
- [X] fix the bug for shared spaces
- [X] verify that it works fine for contents (file, folder, thread, document)
- [X] add test cases (they can be done using minimal http request - the bug is also visible in this case) for workspaces and contents

To reproduce: 

- create a workspace named "Mission Cab/Split"
- open it on the web - it should be ok
- open webdav - you see the folder `Mission Cab/Split` (which should instead be `Mission Cab⧸Split` (the slash is another char)
- double-click on the folder : it fails
- open the url : https://algoo.tracim.fr/webdav/Mission%20Cab/Split%20(interne) - it fails
- open the url : https://algoo.tracim.fr/webdav/Mission%20Cab%E2%A7%B8Split%20(interne) - it works (webdav open the right folder, but the label listing is wrong)

**Comment by inkhey** [comment]
@lebouquetin It look like problem is related to path mecanism. '/' is a separator, this allow in webdav to get workspaces and folder hierarchy.
If we allow '/', how can we distinct  : 
`Mission Cab/Split` workspace and `Split` file/folder in `Mission Cab` workspace ?

**Comment by inkhey** [comment]
- Correct  behaviour should be that webdav doesn't have to work with "/" in content a tracim content may (should we continue to allow it ?) include "/" char but in those case, char should be replaced in whole webdav ui to ⧸ . 

- Mecanism seems to work for content but not for workspace name.

**Comment by inkhey** [comment]
>     * Correct  behaviour should be that webdav doesn't have to work with "/" in content a tracim content may (should we continue to allow it ?) include "/" char but in those case, char should be replaced in whole webdav ui to ⧸ .
> 
>     * Mecanism seems to work for content but not for workspace name.

Convertion should be done through webdav_convert_file_name_to_display method.

**Comment by lebouquetin** [comment]
Note : move, copy and create content is not fixed here. see #1399

**Comment by PhilippeAccorsi** [comment]
Verified.

**Comment by PhilippeAccorsi** [comment]
This issue is corrected in branch `fix/1399_fix_webdav_move_with_special_characters`.

**Comment by PhilippeAccorsi** [comment]
Verified.
