### ISSUE TITLE
sidebar is not updated when a workspace is renamed

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#1363]
Currently:

- I want to rename a sharedspace.
- I go to admin screen listing all the sharedspaces.
- I select my shared space and modify its name.
- When saving, the listing screen is updated but sidebar is not updated

Note : the bug also appears if the modification comes from workspace dashboard advanced edition

Expected:

- side bar should be updated

TODO : 

- [ ] update sidebar when workspace is updated through admin screen 
- [ ] check that the bug is also fixed when modification comes from workspace dashboard
- [ ] add an automatic test case for this issue - including the issue id in test name

**Comment by PhilippeAccorsi** [comment]
@lebouquetin I have tested this on demo and its working good.
Can you reproduce or change issue to make automatic test case only.
Thanks

**Comment by Quiwy** [comment]
Seems to work on build_088, closing it.

![changed_title](https://user-images.githubusercontent.com/20048264/185616845-b7715048-e7b1-4201-80aa-f7e420a0e0bd.gif)
