### ISSUE TITLE
Support for implicit ssl port in smtp

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1368]
Currently, email notifier support ssl/tls using starttls . We should provided support for implicit ssl port when all the discussion in made in full tls/ssl.

see todo here: 
https://github.com/tracim/tracim/blob/0c9b9eb7bc8428d8ff112d1c0f092b46cbbcc50d/backend/tracim_backend/lib/mail_notifier/sender.py#L66

**Comment by PhilippeAccorsi** [comment]
Related to #2793 
I close this issue.
