### ISSUE TITLE
After moving file with webdav and after click on old revision, url of file is wrong (use old workspace id)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1370]
**At present**

- import file with web-interface or with webdav in one workspace (tested with "dockertoolbox.exe" 200Mo)
- move this file with webdav to another workspace
- if you try to download this file its possible
Now:
- click on old revision
- click agin on last revision (named "Item moved")
=> an error 400 appear : `{"message": "Content \"8151\" not found in database", "details": {"error_detail": {}}, "code": 1003}`
~~~
"Warning
Error while loading file"
~~~

- try to download file
=> you arrive on blank page "Fichier introuvable"

file is now not available from web-interface.

More information:
content revision use url with workspace id, so when I move this file, workspace id as change, but stay in content revision. When I want to show last revision of this file, url is not updated with actual workspace id, so backend says: "file is not in database". 

**Expected**

- [ ] file stay available after moving from workspace to another workspace.

**Comment by inkhey** [comment]
@PhilippeAccorsi Does file name contains any special characters, can you give file_name and type of content where this issue happened ?

**Comment by PhilippeAccorsi** [comment]
@inkhey I have updated issue.
filename "dockertoolbox.exe".

**Comment by PhilippeAccorsi** [comment]
Verified.
