### ISSUE TITLE
Timeline: translation not working in timeline about revision status (created, moved, etc...)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1371]
**At present**

In timeline of content we can see text and date, but text is not translated.
exemple: interface in french:
`Item created il y a 2 mois`
`New revision il y a 3 mois`
`Item moved il y a 7 minutes`

**Expected**

- [ ] make translation about all status in timeline
- [ ] translation working also in timeline.

**Comment by Skylsmoi** [comment]
fixed in https://github.com/tracim/tracim/commit/7718e2dd96a246420d8e59603029ee882911f1b3

**Comment by Skylsmoi** [comment]
fixed again in https://github.com/tracim/tracim/pull/1526

**Comment by PhilippeAccorsi** [comment]
Verified.
