### ISSUE TITLE
Login redirection wrong path when validate html document and when you are disconnected

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#1372]
**Describe the bug**

When Tracim redirect browser into login page, we got a 404 error.

**To Reproduce**

1. Open and login into tracim
2. Open a html document and modify content
2. Disconnect into a second tab
3. Validate html document in first tab

**Expected behavior**

Redirection should be on `/ui/login` instead `/login`

**Comment by PhilippeAccorsi** [comment]
In this case you lost also your modification because the local storage is deleted when you click on "Validate".

**Comment by PhilippeAccorsi** [comment]
This is solved. I not find when but its related to the TLM feature.

**Comment by raphj** [comment]
Likely fixed by commits 93e3e5d6d1 (2020-08-25) and e0858f5884 (2020-10-20)
