### ISSUE TITLE
Local-storage: add message to inform user about what he see is not save on tracim (this is version present in localstorage)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1373]
At present

If you use local--storage after editing a html-doc, when you come-back on your document, you can see your modifications but you might think this modification is available for other users (you are not in edit mode)
If you look in timeline, you can't see new revision, its normal because you use local-storage.

Related to #758 

Expected

- if what you see comes from local-storage, then open the app in edit mode

**Comment by Skylsmoi** [comment]
I can't manage to display a htmldoc from localStorage in VIEW mode

I need a more detailed reproduction process please

**Comment by Skylsmoi** [comment]
the "expected" statement is what's happening right now.

The issue is more about telling the user that there is a draft version of the doc or that he is editing from a draft version upon clicking on "Edit" button.

We need to define where and what to display to the user

**Comment by lebouquetin** [comment]
After discusison: Add a message on top of page : "Vous avez un brouillon en cours de rédaction. reprendre la rédaction " (with a link to edit mode in "reprendre la rédaction"

**Comment by PhilippeAccorsi** [comment]
After test:
When I save modification I can see message about local-storage just before creating new revision.

Idea:
1 - when I save => clear local-storage first

**Comment by PhilippeAccorsi** [comment]
Tested and verified.
