### ISSUE TITLE
Deleted folder: recent activity continue to show content present in this deleted folder.

### ISSUE THREAD

**Issue by LucBarry** [tracim/tracim#1377]
**Describe the bug**

When I delete a folder added with webdav in tracim, the folder is deleted, but then contains files continues to appear in the recent activity section.

**To Reproduce**
1. Add folder with contains with webdav
2. Click on delete this folder
3. Go to dashboard 
4. Check recent activity

**Comment by gbonaspetti** [comment]
Duplicated with https://github.com/tracim/tracim/issues/1796
