### ISSUE TITLE
Download fails in case of slow download

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#1387]
On my tracim instance I uploaded a fie of 30MB.

- If I download it from a fast internet connexion everything is ok.
- If I download it from a slow connexion, the DL is stopped around 24/27MB
    - in this case I cant see progress bar in web browser. The browser don't know the size of file. Maybe header problem.
- If I download from webdav, it works

**Comment by inkhey** [comment]
- I wasn't able to reproduce it with dev server, this may be related to Uwsgi, especially socket-timeout issue (https://github.com/tracim/tracim/issues/1437).
- Headers are effectively uncorrect for endpoint relating to content which are stored in database (content and content_revision) but not preview.
 As we use a specific method in hapic for those case (pyramid doesn't have built-in methods for thoses), we do not set properly headers. It means that we send content more as a stream than as a static sized file. This means also than HTTP range request cannot work : https://github.com/tracim/tracim/issues/1462.

I've done a patch in hapic here for headers: https://github.com/tracim/tracim/issues/696 but actually hapic codebase is broken (dependencies issues), so i wasn't able to make last version of hapic work correctly with tracim.

**Comment by inkhey** [comment]
#1646 use the patch from hapic with corrected headers

**Comment by PhilippeAccorsi** [comment]
Verified.
