### ISSUE TITLE
Dossier toujours visible après avoir été déplacé

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#139]
Lorsqu'un dossier est déplacé d'un workspace à un autre, il apparait toujours sur la page d'accueil du workspace.

Pour reproduire : 

- créer un workspace A
- créer un dossier DOSSIER dans workspace A
- créer un workspace B
- afficher le dossier DOSSIER et le déplacer vers le workspace B (à la racine)
- afficher le contenu du workspace A : le dossier DOSSIER y est visible.

Attendu : 

- n'afficher le dossier que dans le workspace où il a été déplacé.
- écrire les cas de test associés pour éviter toute régression

**Comment by buxx** [comment]
Résolue avec 2ffbe33.
