### ISSUE TITLE
Add user: error appear without explicit message.

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1394]
At present

Create user account with whitespace before and/or after email address, when you validate form, an error appear but with no explicit message and you don't know where is the problem.

In network information => error 400 with code 2001

Expected

- [ ] Show specific flash message about this error. Error code have explicit information.
- [ ] translate this flash message.

**Comment by Skylsmoi** [comment]
regarding this issue: https://github.com/tracim/tracim/issues/1108
I think emails should be trimmed by backend

I will handle the error 2001

**Comment by PhilippeAccorsi** [comment]
Verified.
