### ISSUE TITLE
Webdav: Fix move/copy/create with special characters

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1399]
https://github.com/tracim/tracim/issues/1362 patch fix get of content but move file with special characters is still broken. (this need patch to be fix on top of https://github.com/tracim/tracim/issues/1362 and https://github.com/tracim/tracim/issues/1376)
We should fix issue with special characters and have simple (check status code) webdav functional tests for most case with content "creation" (all move case, all create case, all copy case) .

**Comment by PhilippeAccorsi** [comment]
This branch `fix/1399_fix_webdav_move_with_special_characters` is not in MR because some test for move in webdav not working correctly.

**Comment by PhilippeAccorsi** [comment]
Verified.
