### ISSUE TITLE
When edit html document TAB is dangerous

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#1409]
## Bug description & symptom

It is possible (and it already happened) to loose your work while working on an html document. And you can't get it back from the database or the local storage.

## Diagnostic

When the focus is on the tinymce textarea, if you press "tab" button (keyboard), the focus goes to the "cancel" button. And if you press "space" or "enter", it clicks the button which delete your current modifications.

## Expected

When hitting "tab" button, set the focus to the "Save" button. While this is not ideal, this is the minimum fix.

## How to reproduce

Open a html document
Do some changes
Hit "tab" button
Hit "space" or "enter" button
Reopen the content in edition, you lost you changes

## Impacted components

App Html doc
frontend_lib (comment)

## Extra information

Other possibilities to explore:
- Add a popup to confirm the cancel button when modifications exists
- Add an auto save process
  - This requires backend changes
- Keep the localStorage available when clicking Cancel
  - This will need to defines when to invalidates the localStorage

**Comment by gbonaspetti** [comment]
The solution made was to add tabindex attributes to the buttons to determine the order in which they will be focused.

**Comment by metzgegu** [comment]
Verified on branch (wait merge to close).
