### ISSUE TITLE
access the translation file from main.js

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#141]
main.js is the file that will hold every bit of javascript.

this file should have access to the translations for DOM manipulation

**Comment by tracim** [comment]
Regarder ce que caldavzap peut utiliser pour faire des traductions et ensuite on revoit ce point

**Comment by Skylsmoi** [comment]
Todo : 
- trad pour tinyMCE
- trad pour caldavzap
- trad pour le js
- trad pour le wizzard (TWSM)

**Comment by Skylsmoi** [comment]
Todo :

- trad pour tinyMCE
- trad pour caldavzap

~~- trad pour le js~~
trad pour le wizzard (TWSM) => see repository manage_ws

**Comment by Skylsmoi** [comment]
assigned to @buxx to setup the dynamic lang call. Right now, it is hard coded in french.

todo : 
edit templates/master_anonymous.mak templates/master_authenticated.mak and templates/master_no_toolbar_no_login.mak and replace 'fr_FR' (globalTracimLang assignation) with the dynamic value
