### ISSUE TITLE
Generic handling of http status code

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1423]
The generic fetch wrapper of frontend_lib will:
- handle every http status 2xx and 3xx as success code
- let the handling of any 4xx to the specific end point handler
  - the specific endpoint handler will handle the 4xx specifically regarding the response error code (in the json)
  - the specific endpoint handler will handle any unhandled 4xx error code
- handle every http status 5xx as a generic error
- handle any other http status with a msg telling user that something unexpected happend

:bulb: Be advised that there is some technical dept of old specific endpoint that uses Promises instead of async functions that wont handle unhandled 4xx error code

**Comment by PhilippeAccorsi** [comment]
Verified.
