### ISSUE TITLE
Copy from webdav to webav result error: message corrupt

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#144]
Try to copy paste from and to webdav result an error "Message corrupt".

**Comment by buxx** [comment]
I don't find reason of this "message corrupt" ... Note: files are correctly created.

**Comment by tracim** [comment]
Vérifier si c'est lié à la transfo %20 en espaces. A tester sans reverse proxy.
Si pas identifié, on le repousse à une date ultérieure

**Comment by Skylsmoi** [comment]
commit "#144 added trad for js" is not related to this bug, commited with wrong commit message, it actually refers to #141

**Comment by tracim** [comment]
first next step : test directly with a webdav share through wsgidav only (not through tracim)

**Comment by tracim** [comment]
Seems to be also "buggy" in latest wsgidav version...

**Comment by tracim** [comment]
We will not fix this in the v1.0
