### ISSUE TITLE
Don't show deactivated users in app advanced dashboard

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1444]
At present

On shared space dashboard you can seen activated members. In advanced dashboard you can seen all member of this shared space, also deactivated users.

Expected

- [x] don't  show deactivated users in app advanced dashboard or show it in grey

**Comment by metzgegu** [comment]
Solution implemented is to filter user fetched in workspace advanced to have only active users

**Comment by gbonaspetti** [comment]
Verified on branch (wait merge to close).
