### ISSUE TITLE
New feature - Cut / Paste

### ISSUE THREAD

**Issue by basilelegal** [tracim/tracim#1447]
## New feature - Cut / Paste

In the current version of Tracim, it is possible to move a content using the endpoint:

```
PUT /api/v2/workspaces/{workspace_id}/contents/{content_id}/move

{
  "new_parent_id": 42,
  "new_workspace_id": 2
}
```

But this functionality isn't available through the frontend application

## Solution

Adding 2 new options in the extended action menu of a content, in between options `Edit` and `Archiv`.

1. Cut:
  - Visible on contents and folders
  - Available only for users who have permissions to edit contents in the current workspace
  - After clicking, pop an alert saying "Content xxx is ready to be Pasted"

2. Paste:
  - Visible only on folders
  - Available only for users who have permissions to edit contents in the current workspace
  - If nothing is "cut", the option is disabled
  - After clicking, pop an alert saying "Content xxx was moved to folder yyy"

## Issue

Where can we put the options "paste" if we want to paste at the root of a workspace

## Alternatives solution

`Drag and Drop`, much more difficult to implement and less intuitive when you want to move contents between workspaces.

**Comment by PhilippeAccorsi** [comment]
@basilelegal For your issue, its possible to show one button on top of list of content "Paste in home of this shared-space" and this button is just visible if you have click on "cut" on one content before.

**Comment by Quiwy** [comment]
Seems we can move files now with drag and drop : https://public-community.tracim.fr/ui/workspaces/166/contents/html-document/18329

It's be introduced in version [2.3.0](https://github.com/tracim/tracim/blob/develop/changelog.md#230--2019-06-21)
