### ISSUE TITLE
Travis CI: Fix travis tests for all supported python version.

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1453]
**Describe the bug**
Travis "Quick Unit-Test for Backend" for all supported version seems broken : 3,5; 3,6; 3.7, it seems to only check one version, not all.

todo : 
- [ ] check/fix this test for all python versions
- [ ] update python classifiers in setup.py accoriding to them.

**Comment by PhilippeAccorsi** [comment]
Information about virtualenv: https://docs.travis-ci.com/user/languages/python/

**Comment by inkhey** [comment]
already done.
