### ISSUE TITLE
Can not write to contact address

### ISSUE THREAD

**Issue by nicolas-75** [tracim/tracim#1457]
## Bug description & symptom

Could not send an email to the contact address. The remote server returns an error.

Remote server response:
550 5.1.1 <contact@tracim.fr>: Recipient address rejected: User unknown in virtual mailbox table 

## How to reproduce

1. Write an email to: ontact@tracim.fr
1. Wait an answer from the server to obtain the error

**Comment by PhilippeAccorsi** [comment]
Thanks for your ticket.

its now resolved.
