### ISSUE TITLE
Erreurs lors d'une installation. Problème ARM ?

### ISSUE THREAD

**Issue by nicolas-75** [tracim/tracim#1458]
## Bug description & symptom

Lors de l'installation sur un serveur ARMv7 (2Go de ram), j'ai plusieurs erreurs. Par exemple

    

1. File "/root/tracim/backend/env/lib/python3.5/site-packages/alembic/util/compat.py", line 145, in load_module_py
        spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 665, in exec_module
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "tracim_backend/migration/env.py", line 7, in <module>
        from tracim_backend.models.setup_models import *
    ImportError: No module named 'tracim_backend'

    [07:30:55] $ some error

1. ou encore :

    UUID 5b3e19bf-c7ea-4ce7-b1d9-c3104ffa75de doesn't exist in /dev/disk/by-uuid
    Warning: root device /dev/disk/by-uuid/5b3e19bf-c7ea-4ce7-b1d9-c3104ffa75de does not exist

Pour info:
$ blkid
/dev/nbd0: LABEL="root" UUID="5b3e19bf-c7ea-4ce7-b1d9-c3104ffa75de" TYPE="ext4"
**$ ls /dev/disk/
ls: cannot access '/dev/disk/': No such file or directory**

Mais j'arrive quand même à exécuter l'application :

    [10:59:46] $ build frontend_app_folder

    > tracim_app_folder_advanced@1.0.0 build /root/tracim/frontend_app_folder_advanced
    > NODE_ENV=production webpack -p

    isProduction :  true

Par contre lorsque j'essaye de saisir le nomdedomaine:6543 le navigateur m'indique que le site n'existe pas.

Est-ce que vous pensez que c'est lié ?

**Comment by PhilippeAccorsi** [comment]
Bonjour, 

Comme la dit @lebouquetin sur linuxfr.org , nous n'avons pas pour le moment fait de test sur ARM.

Nous feront la semaine prochaine des tests dinstallation sur un serveur ARM chez scalway afin de reproduire le bug et de corriger/indiquer comment faire une installation sur ce type de serveur.

Pour ce qui est de l'UUID, nous ne voyons pas de relation avec l'installation de tracim.

**Comment by PhilippeAccorsi** [comment]
Après des tests sur un serveur ARM64-2GB avec une Debian Stretch chez Scaleway, voici les étapes à suivre pour installer tracim:

Par défaut l'installation de debian stretch (9.4) chez Scaleway a une erreur dans /etc/apt/source.list, il faut commenter les 2 lignes qui comporte "stretch/update"; seul les 2 lignes avec "stretch-update" fonctionnent.

Ensuite il faut faire:
  - apt-get update
  - apt-get install python3-lxml
  - apt-get build-dep python3-lxml
  - apt-get install git

A partir de maintenant vous pouvez suivre les étapes d'installation de tracim:
- ./setup_default_backend.sh root
- ./install_frontend_dependencies.sh root
- ./build_full_frontend.sh

Avant de démarrer tracim, bien penser à modifier le development.ini afin de rendre tracim accessible avec votre domaine.

**Comment by lebouquetin** [comment]
@nicolas-75 as-tu ré-essayé d'installer tracim sur ton serveur ?

**Comment by lebouquetin** [comment]
@PhilippeAccorsi le ticket est résolu, non ? ça marche sur ARM ? Peut-être qu'il faut faire une documentation...

**Comment by PhilippeAccorsi** [comment]
Il faut effectivement faire une documentation.
Je pense que l'on peut fermer l'issue (et mettre un lien vers une issue pour faire de la documentation)

**Comment by Haskaris** [comment]
Fixed with #3985
