### ISSUE TITLE
tinymce not show document correctly. About document imported from tracim-v1

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1466]
## Bug description & symptom

I can't see correctly my document with tracim-v2, if I want to see something correctly I need to enter in edit mode.

## Diagnostic

"unknown"

## Expected

Tinymce show document correctly

## Prerequisites

have an old document imported from tracim-v1

## How to reproduce

Use this file visible in tracim-v1: content_id 5313 workspace_id 51

## Screenshots

**On tracim-v1:**
![capture d ecran de 2019-03-08 15-25-17](https://user-images.githubusercontent.com/25848257/54034283-c8c94e00-41b6-11e9-83ef-4c3b4a62d213.png)

**On tracim-v2:**
![capture d ecran de 2019-03-08 15-25-39](https://user-images.githubusercontent.com/25848257/54034300-cff05c00-41b6-11e9-9370-9ba5e78755ff.png)

**On tracim-v2 in edit mode:**
![capture d ecran de 2019-03-08 15-28-56](https://user-images.githubusercontent.com/25848257/54034390-ff9f6400-41b6-11e9-837f-045825d34175.png)

**Comment by PhilippeAccorsi** [comment]
The problem seem to not be a tinymce bug but a bug with Tracim html document rendering.

The problem for me is when I wrote some documentation because all preformated text is not correctly visible in Tracim rendering.

What is necessary to improve rendering in Tracim ?

(for exemple, its very difficult to create administrator system documentation with good rendering of which is text and command line.

**Comment by PhilippeAccorsi** [comment]
Another example of what we have at present
![Screenshot_2020-09-15 Liens utile activité de montagne ( département de l'isère) · Documentation générale · Tracim - demo](https://user-images.githubusercontent.com/25848257/93209846-f81f2a80-f75e-11ea-88fb-54e07c2419ab.png)

**Comment by Haskaris** [comment]
Closing this issue, since we don't have any document v1 to v4. If anyone encounter this issue/bug again, please create a new issue so we can investigate.
