### ISSUE TITLE
Radicale: Add support for carddav in backend

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1469]
## Feature description
As we will support radicale for caldav, we can support carddav too using radicale.
Integration of such element in frontend need to be discussed in another issue.

## todo:
to support such thing, we need to : 
- decide on path to address, those paths will be handled the same as for calendar, so we need to be sure path already exist, i suggest something like `/addressbook/user/1/ ` with similar logic as for caldav
- proxy `/addressbook/user/{user_id}/`, ` /addressbook/user/{user_id}/{vcf_filename}.vcf` and `/addressbook/user/{user_id}/.well-known/carddav/.`
- find a solution to force creation fo addressbook.  to do this we need proper folder hierarchy existence and `.Radicale.props` in addressbook dir with content like this : 
`{"CR:addressbook-description": "test", "D:displayname": "test", "tag": "VADDRESSBOOK", "{http://inf-it.com/ns/ab/}addressbook-color": "#f6d3dbff"}`
- anything else ?

## Implemented solution:
implemented at the same time of another issue, see "implemented solution" section of https://github.com/tracim/tracim/issues/2099

**Comment by grignards** [comment]
Even without any frontend support, having all known users available in a carddav collection would be useful I think (for email clients).

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by gbonaspetti** [comment]
Done
