### ISSUE TITLE
tracim.org site not avaiable

### ISSUE THREAD

**Issue by ferriswheel** [tracim/tracim#147]
hello,

is tracim.org still an active site?
below is the error i got today.

regards
john

Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /.

Reason: Error reading from remote server

Apache/2.2.22 (Debian) Server at tracim.org Port 80

**Comment by buxx** [comment]
Hello,
Our server encountered an error, we fixed it.
Thank you very much for report !
bux.
