### ISSUE TITLE
Email login case sensitive

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#1470]
## Bug description & symptom

When enter my login email on login page with a typo, login failed.

## Diagnostic

Email is case-sensitive on login page.

## Expected

Email should not be case sensitive.

## Impacted components

- Backend / auth endpoints

**Comment by PhilippeAccorsi** [comment]
@buxx do you know if its the same in other email form? When you create user or change email in "My account"" page?

**Comment by PhilippeAccorsi** [comment]
@lebouquetin I think this issue is for 2.2 (quick issue).

**Comment by PhilippeAccorsi** [comment]
@lebouquetin Is it not important to solved this issue quickly?

**Comment by inkhey** [comment]
@buxx solution is not that easy:

https://tools.ietf.org/html/rfc5321
`
The local-part of a mailbox MUST BE treated as case sensitive.
`

**Comment by inkhey** [comment]
with @lebouquetin, decision as been made to lowercase email at lib level, despite this does not follow strictly rfc5321. see https://github.com/tracim/tracim/pull/2043

**Comment by tracim** [comment]
No fix make for this issue. Its an error.

**Comment by PhilippeAccorsi** [comment]
After discuss: we need to migrate all email in database to transform all email in lower case.
After that login input is transfom to lowercase all the time before verification of email.

**Comment by PhilippeAccorsi** [comment]
Verified.
