### ISSUE TITLE
refactor account endpoint code

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1478]
We have both `/api/v2/users/{user_id}/... `and `/api/v2/users/me/...` endpoints we should see how we can avoid duplication of code there : 

**1rst solution : reroute to same internal code:**
- need 2 right checker for both url, there are also different actually (checker need to be more complex if we want only one there)
- need to be explicit for all input and output schema if we want check !
- implicit redirection

example (untested code) :
```
   def _route_calendars(context, request, hapic_data, user):
        app_config = request.registry.settings['CFG']
        calendar_api = CalendarApi(
            current_user=user,
            session=request.dbsession,
            config=app_config,
        )
        return calendar_api.get_user_calendars(
            user,
            workspaces_ids_filter=hapic_data.query.workspace_ids
        )

    @hapic.with_api_doc(tags=[SWAGGER_TAG__USER_CALENDAR_ENDPOINTS])
    @check_right(has_personal_access)
    @hapic.input_path(UserIdPathSchema())
    @hapic.input_query(CalendarFilterQuerySchema())
    @hapic.output_body(CalendarSchema(many=True))
    def user_calendars(self, context, request: TracimRequest, hapic_data=None):
        user = request.candidate_user
        return self._route_calendar(context,request, hapic_data, user)

    @hapic.with_api_doc(tags=[SWAGGER_TAG__USER_CALENDAR_ENDPOINTS])
    @check_right(is_user)
    @hapic.input_query(CalendarFilterQuerySchema())
    @hapic.output_body(CalendarSchema(many=True))
    def account_calendars(self, context, request: TracimRequest, hapic_data=None):
        user = request.current_user
        return self._route_calendar(context,request, hapic_data, user)
```

**2nd solution : use redirection :** 

- no need to check right here
- no need to explain input and output schema.
- able to document input schema if we want to document better
- output schema always the same.
- explicit redirection
- able to redirect many endpoints with only one "catch all redirection" if documentation is not needed here.

example with already existing endpoint:
```
    @hapic.with_api_doc(tags=[SWAGGER_TAG__CONTENT_ENDPOINTS])
    @hapic.input_path(ContentIdPathSchema())
    @hapic.output_body(NoContentSchema(), default_http_code=HTTPStatus.FOUND)  # nopep8
    def get_content(
            self,
            context,
            request: TracimRequest,
            hapic_data=None,
    ) -> None:
        """
        Convenient route allowing to get detail about a content without to known routes associated to its content type.
        This route generate a HTTP 302 with the right url
        """
        app_config = request.registry.settings['CFG']
        api = ContentApi(
            current_user=request.current_user,
            session=request.dbsession,
            config=app_config,
        )
        content = api.get_one(
            content_id=hapic_data.path['content_id'],
            content_type=content_type_list.Any_SLUG
        )
        content_type = content_type_list.get_one_by_slug(content.type).slug
        # TODO - G.M - 2018-08-03 - Jsonify redirect response ?
        raise HTTPFound(
            "{base_url}workspaces/{workspace_id}/{content_type}s/{content_id}".format(
                base_url=BASE_API_V2,
                workspace_id=content.workspace_id,
                content_type=content_type,
                content_id=content.content_id,
            )
        )

```

## Implemented solution:

see https://github.com/tracim/tracim/pull/3085
- Use redirection with HTTP 307 code for /users/me endpoint

**Comment by lebouquetin** [comment]
Note about the redirection case:

The redirection for getting a content is a bit more complex. As a content id is unique, there are no reason you need to know its type in order to get it. So the redirection is a required feature.

In the case of /users/me => /users/<id>, the redirection is not required as you already know the user id - it's more a convenient way to expose API, not a requirement.

**Comment by inkhey** [comment]
as @grignards suggested, we should use 307 instead for 302 as we have non-get method :
https://developer.mozilla.org/fr/docs/Web/HTTP/Status/307
