### ISSUE TITLE
Check docker image before release of Tracim 2.2

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1482]
Some modifications change dockerfile:
- https://github.com/tracim/tracim/issues/1472 .
- ...

**Comment by PhilippeAccorsi** [comment]
We need to make a quick test after merge last issue #1769 #1688 #1746

We have tested docker image today, also with webdav, caldav and email (send and reply).

**Comment by PhilippeAccorsi** [comment]
Verified.
