### ISSUE TITLE
Remove support for deprecated parameters

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1483]
## Feature description and goals

We need to remove all deprecated parameters in tracim backend config and document the changelog accordingly:

To do:

 - [x] remove user.reset_password.validity
 - [x]  remove caldav.enabled
 - [x] remove collaborative_document_edition.activated
 - [x] remove  email.notification.from

## Related issue
See https://github.com/tracim/tracim/issues/970.
`user.reset_password.validity ` has been deprecated since 2.2, we had to drop support for it in 2.3 and later versions of Tracim.

## Implemented solution:

- remove all current deprecated parameters from tracim : `user.reset_password.validity`, `caldav.enabled`, `collaborative_document_edition.activated` and `email.notification.from`, only `user.reset_password.validity` was actively used (as fallback for `user.reset_password.token_lifetime` )
- update and fix current config parameter list in documentation.

**Comment by inkhey** [comment]
@buxx has found an issue with broken support of user.reset_password.validity is 2.6 (not correctly casted into integer).
As 3.0 is coming, i do suggest to solve this by removing this parameters and potentially other deprecated parameter for 3.0 or 3.1.

**Comment by inkhey** [comment]
other deprecated parameter (current 3.0 rc1) are:
- `caldav.enabled`
- `collaborative_document_edition.activated`
- `email.notification.from`

**Comment by inkhey** [comment]
Note: As soon as we merged this, we need to update current version changelog accordingly : 

- Remove all deprecated parameters:
    - `user.reset_password.validity`
    - `caldav.enabled`
   - `collaborative_document_edition.activated`
   - `email.notification.from`

**Comment by inkhey** [comment]
To test this: 
- set these config parameters:
```
    user.reset_password.validity
    caldav.enabled
    collaborative_document_edition.activated
    email.notification.from
```

and verify that : 
- tracim is correctly launching
- tracim forgot them (not listed at startup)

There should not be any real difference except for `user.reset_password.validity` (other deprecated parameters where already skipped in previous versions.

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
