### ISSUE TITLE
Button "explore content" is missing on shared space dashboard

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#1488]
## Bug description & symptom

On dashboard, the button "explore contents" is missing. If you look at the video https://www.tracim.fr/demo (at 20 seconds), there is a button "explore contents" which is a link to "all contents"

## Expected

Add the following button on top left of dashboard buttons:

![Sélection_121](https://user-images.githubusercontent.com/907161/54425939-e2b6e380-4716-11e9-8e5f-9f251f3856b4.png)

## Impacted components

Not sure if the button is configured in backend or in frontend. This button should be available if "all contents" button is available on the left.

So...

- backend?
- frontend?

**Comment by lebouquetin** [comment]
@Skylsmoi I assigned this bug to you, let investigate and tell us if buttons are configured in frontend or in backend

**Comment by PhilippeAccorsi** [comment]
Verified.
