### ISSUE TITLE
Syntaxes error in email template

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1491]
## Bug description & symptom

When we receive an mail we can see in this email template an " at end of first line. Its also not very simple to know where is standart information and juste the comment from user.

## Diagnostic

unknown

## Expected

- [ ] Don't show this " at end of first line
- [ ] Add separation line to make difference between information from standart template and comment from tracim user (comment or content)

## Prerequisites

Notification by email need to be activated.

## Screenshots

![Capture d’écran de 2019-03-20 09-29-51](https://user-images.githubusercontent.com/25848257/54670033-08ffc900-4af3-11e9-973c-811aa97268b2.png)

**Comment by inkhey** [comment]
@PhilippeAccorsi probably related to https://github.com/tracim/tracim/issues/1489

**Comment by inkhey** [comment]
fixed by https://github.com/tracim/tracim/commit/0d4160dfcac50fe4efb830dc67eaa7ccbc611f88

**Comment by PhilippeAccorsi** [comment]
Verified.
