### ISSUE TITLE
Allow to setup default lang in backend

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1495]
currently default lang in backend is not settable, we should add a parameter "default_lang" in config to allow force default lang.

**Comment by PhilippeAccorsi** [comment]
**For testing:**
- uncomment `default_lang = en`
- change "en" by "fr"
- create one notification
=> you can see email in french
- change "fr" by "en"
- create one notification
=> you can see email in english

**Comment by PhilippeAccorsi** [comment]
Verified.
