### ISSUE TITLE
Frontend should enable/disable calendar of workspace

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1498]
Currently there is no way to change calendar activation for workspace.
As Backend re-enabled it here : https://github.com/tracim/tracim/issues/1181, Frontend should allow to change this in ui.

**Comment by Skylsmoi** [comment]
@inkhey when the calendar has been disabled, the endpoint api/v2/users/me/workspaces still returns the calendar in the property sidebar_entries. So the calendar is still visible in the sidebar. It should not

**Comment by Skylsmoi** [comment]
The change for frontend will be included in the PR with Caldavzap

**Comment by lebouquetin** [comment]
@Skylsmoi 

> @inkhey when the calendar has been disabled, the endpoint api/v2/users/me/workspaces still returns the calendar in the property sidebar_entries. So the calendar is still visible in the sidebar. It should not

Did you open an issue? If not, please do it (with tracim 2.2 as target, and `backend` and `mandatory` labels)

**Comment by Skylsmoi** [comment]
done https://github.com/tracim/tracim/issues/1527

**Comment by PhilippeAccorsi** [comment]
Verified.
