### ISSUE TITLE
Webdav: file copy return error but done properly on linux (Nautilus) when copy file from root to another root workspace

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1499]
## Bug description & symptom

(we need to reproduce with log) 
Copy done with linux (Nautilus) in webdav has return error to ui but has been done properly. 
We should inspect this.

Some complementary information: 
- Has this issue happened on webdav copy with nautilus, webdav method used is probably COPY.
- Done with File.
- ~~Error can have occured on method used after copy not copy itself.~~

- Error happened from root to another root workspace.

## Screenshot

![Capture d’écran de 2019-03-23 10-29-45](https://user-images.githubusercontent.com/25848257/54864388-d3f3b080-4d56-11e9-8031-59811150e4f3.png)

**Comment by buxx** [comment]
There is wedav log for "paste" action.
[webdav_error_1499.txt](https://github.com/tracim/tracim/files/2999188/webdav_error_1499.txt)

**Comment by buxx** [comment]
There is log of working case (when copy from sub dir of workspace and copy in subfolder of other workspace)

[webdav_ok_1499.txt](https://github.com/tracim/tracim/files/2999192/webdav_ok_1499.txt)

**Comment by inkhey** [comment]
```
❯ ack 500 webdav_error_1499.txt 
<139669296310144> --- COPY Response(500 Internal Server Error): ---
b"<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01//EN' 'http://www.w3.org/TR/html4/strict.dtd'>\n<html><head>\n  <meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>\n  <title>500 Internal Server Error</title>\n</head><body>\n  <h1>500 Internal Server Error</h1>\n  <p>500 Internal Server Error: An internal server error occurred\n    Source exception: &#x27;&#x27;</p>\n<hr/>\n<a href='https://github.com/mar10/wsgidav/'>WsgiDAV/2.4.1</a> - 2019-03-23 09:27:54.575103\n</body></html>"
[pid: 508|app: 0|req: 2536/2536] 127.0.0.1 () {40 vars in 898 bytes} [Sat Mar 23 09:27:54 2019] COPY /webdav/Intranet/Bonnes%20pratiques%20d'utilisation%20des%20documents%20tracim.html => generated 484 bytes in 279 msecs (HTTP/1.1 500) 3 headers in 121 bytes (1 switches on core 0)
```

**Comment by inkhey** [comment]
after some search i found a potential reason for this issue. copy/move on content with comment is broken at tracim api level.

**Comment by tracim** [comment]
Remember that moving a content does not move subcontents, except if the workspace change

**Comment by PhilippeAccorsi** [comment]
Verified.
