### ISSUE TITLE
Role displayed on multiple line in workspace edition.

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1510]
## Bug description & symptom
In workspace edition (https://algoo.tracim.fr/ui/admin/workspace) roles Content manager with french translation: «gestionnaire de contenu» are centered and display on 2 line.

## Expected
Find a solution to avoid display on multiple lines.

**Comment by PhilippeAccorsi** [comment]
@inkhey I think this issue not more exist.

**Comment by PhilippeAccorsi** [comment]
After discuss I close this issue. Problem solved.
