### ISSUE TITLE
move add member button before list of shared space member

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1513]
## Feature description

Move button to add member at the begining of member list visible in shared space dashboard.

## Context

At present, its necessary to scroll down to find add member button when you have a big list of member.

## Impacted components

- *frontend*

## Extra information

**At present**

![Screenshot_2020-03-05 Tableau de bord · Tracim - demo · Tracim](https://user-images.githubusercontent.com/25848257/75989896-550a7000-5ef4-11ea-84a1-6cb98aebf93b.png)

**Expected like this**

![Screenshot_2020-03-05 Dashboard · test-bureau · Tracim](https://user-images.githubusercontent.com/25848257/75989964-6ce1f400-5ef4-11ea-8838-f4a7b8373b2b.png)

**Comment by Skylsmoi** [comment]
I agree that a button should be added but at top right of the list might not be the best idea.

I'm adding "unclear" tag

**Comment by gbonaspetti** [comment]
An idea is to put just the + symbol next to the title. Something like that: 

![AddMemberBtn](https://user-images.githubusercontent.com/35422692/58014153-754d7780-7af8-11e9-885b-fe2148e8cb80.png)

**Comment by lebouquetin** [comment]
> I agree that a button should be added but at top right of the list might not be the best idea.

Could you give some arguments?

**Comment by PhilippeAccorsi** [comment]
I think its important for the moment to save "Add a member" button in top of the list. If you have more than 5-10 member, you need to scroll down all the time to add member (some client have more than 50 member in one sharedspace and need to add more member).

@lebouquetin is it also important for @celiamgtt and @LucBarry to put this button before list of member.

I think we can fix this quickly.

**Comment by PhilippeAccorsi** [comment]
Verified. (wait merge to close)

**Comment by metzgegu** [comment]
The `add member` button need also to be before list of member of workspace in the workspace advanced dashboard

**Comment by PhilippeAccorsi** [comment]
Verified.
