### ISSUE TITLE
Z-Index too high for copyright in login-page.

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1514]
## Bug description & symptom
Z-index is too high for copyright in login page.

> Page de login : "copyright © 2013 - 2018 tracim.fr" en zindex trop élevé (il passe par dessus le bouton valider). il faudrait que ça passe sous le formulaire.

## Expected
reduce it.

**Comment by gbonaspetti** [comment]
The copyright didn't have a high z-index, so I changed the z-index from the card to be a little higher.

**Comment by Skylsmoi** [comment]
Also change the year of the copyright to 2019
Do the same for the sidebar

**Comment by PhilippeAccorsi** [comment]
Verified.
