### ISSUE TITLE
add ctrl+click to open a content in new tab

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1518]
## At present

Its not possible to open one content in other tab without before opening tracim in this tab. 

## Expected

- [ ] add possibility to open one content in new tab with "ctrl+clic"

**Comment by Skylsmoi** [comment]
frontend/src/component/Workspace/ContentItem.jsx should use the <Link> component from react-router-

Use link with an onClick handler that do a prevent default, then do the history.push()

**Comment by Skylsmoi** [comment]
duplicate https://github.com/tracim/tracim/issues/1518

**Comment by lebouquetin** [comment]
So we close this oine.
