### ISSUE TITLE
limit the size of images included in comments

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1519]
## Bug description & symptom

Currently, when a large image in included in a comment, the image is not limited in width.

## Expected

- ~~Limit the width to 100% of the div~~
- allow to view the image in large by clicking on it ! https://github.com/tracim/tracim/issues/1205

**Comment by gbonaspetti** [comment]
The first topic was done at the issue #1058 and second topic is too difficult to be done because the image in tinymce is data coded, so we don't have an url to this image.

**Comment by lebouquetin** [comment]
closed as duplicated of #1205
