### ISSUE TITLE
reduce loading duration of app  

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1520]
## Bug description & symptom

When loading an app (htmldoc, file, etc), the frontend loads the data before showing the app.

## Expected

- start loading
- show app
- update app with content

This way, the user experience is improved as tracim does not looks like being "frozen"

**Comment by gbonaspetti** [comment]
The solution found for this issue was to pass the data loading that happened in componentDidMount to the constructor, without preventing the render function from happening.

**Comment by Skylsmoi** [comment]
As seen with @gbonaspetti:
The app feature already renders empty, then loads the data from the api and then update themselves to render the content.
So, there is nothing to do for that issue.

The description telling that the data load from api should start before the first rendering is wrong, actually, it doesn't matter. The loading can start anytime, all that matter is that the app is rendered empty as soon as possible.

I'm closing this issue
