### ISSUE TITLE
add tool tip when mouseover on each chevron (on sidebar)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1521]
## At present

We don't know function for each chevron. 

## Expected

- [ ] add tool tip mouseover on each chevron

**Comment by PhilippeAccorsi** [comment]
- Tool tip need to be write with first letter in uppercase (this is not the case for chevron)
- In agenda button about fullscreen is not translated.

@gbonaspetti Can you check simply all tooltip or its not easy to know if translation is about tooltip or not?

**Comment by gbonaspetti** [comment]
> * Tool tip need to be write with first letter in uppercase (this is not the case for chevron)
> * In agenda button about fullscreen is not translated.
> 
> @gbonaspetti Can you check simply all tooltip or its not easy to know if translation is about tooltip or not?

I check the tooltips and its translations at all React components, but for the things like agenda it's a little difficult because they are HTML pure files and they don't have our translation files. I change the fullscreen button, but I didn't check in the code if there was other like this.

**Comment by basilelegal** [comment]
Tested
