### ISSUE TITLE
Refuse to launch tracim/webdav/caldav if paths given does not exist

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1524]
## Currently

- preview_generator dir is created automatically
- caldav path existence is mandatory (radicale branch)
- session data dir is created automatically (needed for beaker)
- depot dir is created automatically

## Expected : 
- processus (tracim,caldav,webdav, ...) return error if one of this file doesn't exist as file and is not writable. Raise error probably during config settings.
- Explicit error : propose user to change config or create dir/ change permission

**Comment by inkhey** [comment]
#1544 allow to fix this issue, but cause lot of trouble for tests.
Currently: 
- [X] Backend test  : we force a code which default those path parameters in test with autocreated file and default value which can be overrided by environnement var, this means that we can more easily configure test behaviour. 
- [X] Command Backend test: we change the behaviour of command and command test to allow override default param, so we can use same env var like for other backend tests.
- [ ] Cypress functionnal test : We launch tracim as 'normal' with a specific conf file, so env var doesn't work, launch failed because of not finding params or folder existence, like normal tracim behaviour.

**Comment by inkhey** [comment]
after discussion, we should do #1550 before finished work on this.

**Comment by PhilippeAccorsi** [comment]
@inkhey is it testable or not?

**Comment by inkhey** [comment]
#1687 does:
- makes paths mandatory for running tracim.
- add CALDAV__RADICALE__STORAGE__FILESYSTEM_FOLDER as tracim param.
- update travis file to user env variables
- add some log for travis debugging.
- add TEST_MIGRATION_SCRIPT_LOCATION env var and TEST_CONFIG_FILE_PATH env var mecanism that allow to run test from anywhere (not just /backend) if env var are correctly setted. This allow to fix https://github.com/tracim/tracim/issues/1083.
- fix https://github.com/tracim/tracim/issues/1083 by doing coverage and test from depot root dir instead of /backend.
- add one working default dir tree for test in backend/ and one other for run in backend/ + add fix related to allow not handled file when deleting depot in tests.

**Comment by inkhey** [comment]
@lebouquetin Current behavior was to have default dir tree for both test and run to have something running "by default", is this behavior ok, or should we do in script somewhere ?

**Comment by inkhey** [comment]
@lebouquetin https://github.com/tracim/tracim/issues/1525 is about doing this by script. For running that's ok, but what about tests ? should a test "fixture"(we have not yet pytest-style test) create those dir ? 
Idea is to have a default dir tree prepared for tests, which is automatically used when running test in backend with pytest command. Althought all those parameter are overridable by env var and it is for travis test.

**Comment by lebouquetin** [comment]
As we talked at the moment, what you shoud do is:

- add short explanation about the `.test.env` file
- add a bash or python script named something like `prepare-testenv.sh` which create required directories, based on `.test.env` content (this way, the created folders will be exactly the same as the expected ones)

**Comment by Skylsmoi** [comment]
to test:
- basic_setup.caldav_storage_dir = %(here)s/radicale_storage
- basic_setup.preview_cache_dir = %(here)s/previews
- basic_setup.sessions_data_root_dir = %(here)s
- session.data_dir = %(advanced_setup.session_data_dir)s
- session.lock_dir = %(advanced_setup.session_lock_dir)s

**Comment by PhilippeAccorsi** [comment]
Tested and verified by @Skylsmoi .
