### ISSUE TITLE
Create default folder `depot` and `radicale_storage` in default path visible in develoment.ini.sample

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1525]
## At present

`depot/` folder is automaticaly created by backend api and calendar folder need to be created manually. 

If user change default path in development.ini some error can appear if tracim is not authorized to create folder in the requested path.

## Expected

- Tracim software should raise an error if folders does not exist
- creation of folders must be done in installation script
    - [ ] default folder `depot` in tracim/backend/
    - [ ] default folder `radicale_storage` in tracim/backend/

The reason for that is: if the user makes a typo in the config file, currently tracim will start and will store data in the wrong place without to raise any warning.

**Comment by lebouquetin** [comment]
@PhilippeAccorsi à mettre :

en known issue dans la 2.2
en todo dans la 2.3

**Comment by inkhey** [comment]
related to #1524

**Comment by inkhey** [comment]
fixed with #1524 and related PR #1687
