### ISSUE TITLE
missing line in index.mak for app calendar

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1536]
## at present

One line is missing in index.app for calendar

## expected

- [ ] verify if all necessary line is present in index.mak for all app

**Comment by PhilippeAccorsi** [comment]
this line `<script type='text/javascript' src='/app/caldavzap.app.js'></script>` is missing after list of other app script.

**Comment by inkhey** [comment]
@PhilippeAccorsi this will be fix by https://github.com/tracim/tracim/pull/1534

**Comment by PhilippeAccorsi** [comment]
Loop is now used for app in index.mak.

Verified.
