### ISSUE TITLE
caldavzap doesn't save timezone properly

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1539]
currently,
Caldavzap doesn't save the timezone properly

expected:
get the timezone from the saved cookie, if there isn't, get the timezone from the browser and if not possible, have the default fallback

**Comment by Skylsmoi** [comment]
I created this issue since the branch feature/1250__caldavzap has been merged

**Comment by Skylsmoi** [comment]
this commit adds:
- the list of values for possible timezone for caldavzap
- the save the timezone through a specific cookie
- the disabling of the function netSaveSettings from webdab_protocol.js that creates unexpected side effects

**Comment by Skylsmoi** [comment]
wait for the changes from inkhey to fix the api to returns the calendar app properly before merging the  branch associated to this issue

**Comment by Skylsmoi** [comment]
the commit above adds missing caldavzap app to frontend build scripts

**Comment by PhilippeAccorsi** [comment]
Verified.
