### ISSUE TITLE
Normalize calendar app name between frontend and backend

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1540]
related to https://github.com/tracim/tracim/issues/1536.
~~Calendar app slug is now caldavzap to be sync with frontend. app slug is now correct but default_enabled_app is not.~~
We should use a normalized slug for both frontend and backend for calendar app that have a generic name.

**Comment by inkhey** [comment]
decision has been made to make change in the other side (from caldavzap to probably calendar), we should change naming use by frontend too.

**Comment by Skylsmoi** [comment]
done here https://github.com/tracim/tracim/commit/c378f91cd4acd250928e0cfae1d181e89910a270

**Comment by PhilippeAccorsi** [comment]
I close this issue because another commit replace calendar by agenda.
Agenda is the new name in tracim.
