### ISSUE TITLE
sidebar is not refresh if you activate or deactivate calendar in advanced dashboard

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1545]
## Bug description & symptom

If you activate calendar in one workspace, the sidebar is not refreshed so you need to refresh manually the page (or click on all content for exemple) to see new line in sidebar about calendar.

Same refreshing problem when you deactivate calendar. 

## Diagnostic

"unknown"

## Expected

- [ ] sidebar is automatically refreshed when you activate/deactivate calendar in workspace

## Prerequisites

Have caldav server started and calendar path created in backend (if you use old database you need to use `tracimcli caldav calendar create`)

## How to reproduce

open advanced dashboard and click on button to activate/deactivate calendar

## Screenshots

![calendar_refresh_sidebar_not_working](https://user-images.githubusercontent.com/25848257/55482779-8c5a0800-5625-11e9-9efe-796fc3b6e93c.gif)

**Comment by Skylsmoi** [comment]
The sidebar is now properly updated when activating/deactivating agenda

**Comment by Skylsmoi** [comment]
the fix has been made during some fixes related to agenda
