### ISSUE TITLE
error message is not explicit if comment is empty but with html tag

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1553]
## Bug description & symptom

If I put `<p></p>` in empty comment (in all app) I can click on `send`but an error is visible `Warning
Error while saving new comment` (related to #1154).

## Diagnostic

"unknown"

## Expected

- [ ] show explicit message with error code 2003
- [ ] translate this error message

## How to reproduce

Add `<p></p>` in empty message and click on `send` in timeline of app html-document or app file for example.

**Comment by Skylsmoi** [comment]
Waiting for #1154 to be resolved
adding blocked by backend

**Comment by basilelegal** [comment]
@Skylsmoi #1154 is fixed

**Comment by gbonaspetti** [comment]
Verified.
