### ISSUE TITLE
Add back the button "scroll to top" in sidebar

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1554]
## Feature description

Add back the button to scroll to top in the sidebar

## Context

The btn has been removed when the sidebar got its separated scroll from the content because its design wasn't clear enough

## Impacted components

only Sidebar.jsx from frontend

## Extra information

We need to have a better design for this button.

**Comment by Skylsmoi** [comment]
button removed in issue https://github.com/tracim/tracim/issues/1556

**Comment by Quiwy** [comment]
Note sure this is relevant since #5814
