### ISSUE TITLE
Refactor of apps to merge generic code

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1560]
Currently, apps html-doc, thread and file share a large portion of same code.
This code is related to status changing, archiving, deleting, changing title, timeline loading content ...

Expected, all this code should be in a single place, probably in frontend_lib.
Don't forget that it might be necessary to let dev the possibility to overrides it for specific code in some apps. The same goes for the Timeline. For example, thread app will have to handle it a bit specifically.

issue about refactoring Timeline: https://github.com/tracim/tracim/issues/1128

The result refactor should create some kind of an empty shell or skeleton to easily create a new app by not having to code all the generic features of all apps.

**Comment by Skylsmoi** [comment]
to test:
Things that have been refactored and require test in apps html-document, file and thread:
- changing the content title
- changing the content status
- saving a new comment
- archiving (not testable since we hide the button)
- deleting
- restore archive (not testable since we hide the button)
- restore delete

The custom events management of the apps have also been refactored. To test it check that the 3 apps opens, closes and reload their data properly. Also check the language change

**Comment by PhilippeAccorsi** [comment]
Tested on branch:
- [x] thread
- [x] html-doc
- [x] file

**Comment by PhilippeAccorsi** [comment]
Verified (wait merge to close issue)
