### ISSUE TITLE
Creating several contents opens the wrong one right after creation

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1563]
## Bug description & symptom

After creating a content, it is opened.
After creating a second content, the wrong one is opened
The one wrongly opened is actually the previous one.
And so on.

## Expected

After creating a content, the good content is opened

## How to reproduce

Create a content in a folder
Close it
Create another content
-> the wrong one gets opened

**Comment by Skylsmoi** [comment]
This is a regression caused by https://github.com/tracim/tracim/commit/4cb013b11beb36fe62edf62df3180badac3b884f and the route refactor

**Comment by PhilippeAccorsi** [comment]
Verified.
