### ISSUE TITLE
Mail notifications : set sender name to real user name

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#157]
Currently mail notifications appears to be send by Tracim Team <info@tracim.fr>. Expected : set the humain-friendly sender name to real user name.

Example : set sender like this: 

`Damien Accorsi [tracim]<info@tracim.fr>`

**Comment by buxx** [comment]
Note: Mettre à jour industracim avec les deux nouveaux paramètres (email.notification.from.email et email.notification.from.default_label).

**Comment by buxx** [comment]
Done: 1a0548f6971f17087f30ac4a1d9464798857d397
TODO: Update industracim.

**Comment by tracim** [comment]
Not working : (via tracim) is not shown.
Note : do not use _() function for translations as it may not work in the context (it will return the language of the sender instead of the language of the receiver - or no translation at all in the context of an async job)
