### ISSUE TITLE
Editing a html doc by sending an empty content doesn't update the doc

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1582]
## Bug description & symptom

When we edit a html-doc that has a raw_content and remove every data, the json sent by frontend has an attribute `raw_content === ''`.
The api returns http status 200 but didn't change anything in the document while still creating a new revision

## Expected

The html doc should have the new revision without any content

## How to reproduce

- create a htmldoc with some content
- save it
- edit that htmldoc
- remove any content
- save it again

the last revision is equal to the previous revision

## Impacted components

backend API

## Extra information

@inkhey stated that this might be related to webdav management by windows

**Comment by inkhey** [comment]
This a been fixed in https://github.com/tracim/tracim/issues/4133 , need one more verification.

**Comment by gbonaspetti** [comment]
Done
