### ISSUE TITLE
Caldav calendar: do better right check between content_manager and contributor.

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1584]
## Bug description & symptom

Currently, there is a 2 step right mechanism for calendar:
- contributor can do any read action and any write action anything
- read can do any read action

That's mean that any contributor can destroy event.

## Expected

For Tracim consistency of right, we need a 3 step right:

On calendar:
- content_manager can do any read action and any write action anything
- reader can do any read action

On sub-item of calendar(like event):
- content_manager can don any read and write actions.
- contributor can do any read action and most write action (cannot delete, move) 
- read can do any read action

We should check caldav clients behavior to this mechanism as Caldav protocol doesn't really support itself those kinds of complex right access.

**Comment by inkhey** [comment]
:warning: Merged but need to be test on other client ! (and restested on caldavzap)

**Comment by PhilippeAccorsi** [comment]
If you are contributor:
- you can change event from one agenda to another and in this case new event is created in selected agenda but old one stay because you don't have right to delete event.

**Comment by PhilippeAccorsi** [comment]
Verified.
