### ISSUE TITLE
Rsync fails when using a webdav mount

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#159]
La sortie du log : 

> $ rsync -arv /cygdrive/d/algoo/biologic/dossier_archi/Current/Drawings/* ./Drawings/
> sending incremental file list
> 2016-11-02_BT-Software_Archi_Diags.odg
> 2016-11-02_BT-Software_Archi_Diags_software_on_hardware.odg
> rsync: rename "/cygdrive/z/Biologic - Documents Architecture/Current/Drawings/.2016-11-02_BT-Software_Archi_Diags.odg.Bmqqwh" -> "2016-11-02_BT-Software_Archi_Diags.odg": Permission denied (13)
> rsync: rename "/cygdrive/z/Biologic - Documents Architecture/Current/Drawings/.2016-11-02_BT-Software_Archi_Diags_software_on_hardware.odg.IDyzKv" -> "2016-11-02_BT-Software_Archi_Diags_software_on_hardware.odg": Permission denied (13)
> 
> sent 221605 bytes  received 65 bytes  15287.59 bytes/sec
> total size is 445021  speedup is 2.01
> rsync error: some files/attrs were not transferred (see previous errors) (code 23) at /home/lapo/package/rsync-3.0.9-1/src/rsync-3.0.9/main.c(1052) [sender=3.0.9]
> 

A faire : 
- vérifier le mécanisme de rsync (sync du fichier A = copie A en .A.qqchose + renommage une fois que la copie est terminée ?)
- tester le mécanisme manuellement
- investiguer l'origine de l'erreur

**Comment by tracim** [comment]
Le comportement de rsync est bien : 

1. copie du fichier A (local) vers .A.gjorig (distant)
2. renommage .A.gjorig en A

Travail à faire : vérifier le comportement de tracim (webdav) avec les fichiers cachés.

**Comment by buxx** [comment]
Problème résolue en partie avec commit précedent + 501ffb9d745224850b907ee32571a902c78b6300
