### ISSUE TITLE
the responsive is broken on small and very small screens

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1602]
## Bug description & symptom

Many CSS rules are broken with middle and small screens.

## Expected

- [x] the responsive is working again on middle and small screen.

## How to reproduce

try tracim on middle and small screen

## Impacted components

- *frontend*

## Extra information

The majority of theses css problems arrived when we added agenda and the layout rework adding separated scrolls.

**Comment by lebouquetin** [comment]
@PhilippeAccorsi in this case, you should add screenshots in order to show the broken parts (at least the main broken parts)

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi here you can see list of bug with responsive:

XS:
On firefox with 439x644 (same on LG G4 smartphone)
![Sélection_004](https://user-images.githubusercontent.com/25848257/56666293-e6da0780-66ab-11e9-8275-e5ff4f56c37e.jpg)

**Comment by PhilippeAccorsi** [comment]
After some change in responsive, the login page have changed but need some modification:
- login card width is not same that we have in demo.tracim.fr
- login card position is not same that we have in demo.tracim.fr

**Comment by Skylsmoi** [comment]
add max-width 500px on the card for login

**Comment by PhilippeAccorsi** [comment]
Verified.
