### ISSUE TITLE
change icon fullscreen for caldavzap

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1608]
currently, icon is fa-expand

expected, icon is fa-arrows-alt

**Comment by PhilippeAccorsi** [comment]
Something is wrong when we click on fullscreen button. Header is under the top of agenda.
Fix coming soon.

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi I move this issue in todo to make sure you scheduled the fix for full screen.

**Comment by Skylsmoi** [comment]
yes, thx

**Comment by Skylsmoi** [comment]
I have harmonized the z-index. Here is the current (2019/04/26) list:

| z-index | Component | css selector |
| --- | --- | --- |
| 1050 | Generic | div.mce-fullscreen |
| 60 | FlashMessage | .flashmessage |
| 50 | CardPopupCreateContent | .popupCreateContentOverlay // over header |
| 40 | Agenda | #agendaIframe |
| 30 | Header | .header .navbar |
| 20 | cardPopup | .cardPopup |
| 20 | PopinFixed | .wsContentGeneric |
| 10 | Sidebar | .sidebar |

**Comment by PhilippeAccorsi** [comment]
Verified.
