### ISSUE TITLE
Migration of calendar from tracim_v1 to agenda in tracim_v2

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1612]
### In tracim_v1
data/file about all calendar are in this folder `radicale_data/` in your instance server.
Files is in format of radicale 1.1.x

### In tracim_v2
data/file about all agenda are in this folder `radicale_storage/`in path `/tracim/backend/`.
Files is in format of radicale 2.0.0

### working execution
- Create folder to make migration of files, ex: `migration_process/`
- create venv with python3.4
- install radicale 1.1.6 in this venv
- copy folder `radicale_data/` from tracim_v1 to folder `migration_process/`
- make a config file (ex: `conf.ini`) for migration in `migration_process/` with this parameter:
~~~
    [storage]
    filesystem_folder = {your_path}/migration_process/radicale_data
~~~
- convert file with this command:
    `radicale --export-storage export -C conf.ini --debug`
- after migration, file is accessible in `migration_process/export/`

### not yet implemented
- move folder present in `migration_process/export/collection-root/collections/` to `radicale_storage/collection-root/agenda/`
- in each folder:
    - `user/`: rename folder x.ics/ to x/ 
    - `workspace/`: rename folder x.ics/ to x/ 
- now you can start tracim and radicale and use agenda with all event

## prerequiste with script
- move folder
- renaming folder
- find solution to show workspace title and public name of user in agenda. For the moment the name is just de path of the agenda => if you use tracim like this, and if you deactivate and re-activate agenda in one workspace, the name of all agenda is now the good one).

## Expected

- [x] agenda with event is visible correctly in tracim_v2
- [x] the name of each agenda is the good one

**Comment by PhilippeAccorsi** [comment]
Question about naming:
Why we used `radicale_storage/` in v2 ? (in v1 is `radicale_data/`)
Why we used `agenda/` in v2 ? (in v1 is `collections/`)
Why we use naming for folder `x/`? I know migration process make folder name x.ics, but in v1 all user or workspace calendar is naming x.ics Its just a file with all event in this file but why we not use x.ics for folder of each users or each workspaces?

**Comment by PhilippeAccorsi** [comment]
I have updated issue about naming of agenda in tracimv2.
Fronted show name sending by backend.
Reminder:
After migration of agenda from v1 to v2, the name of agenda is just the path of this agend.

If in frontend I deactivate one workspace agenda and after that I reactivate this agenda, the backend change something and after that the good name of agenda for workspace or for public name is showed.
So I think its not to difficult to have the good name of agenda directly after make a migration v1 -> v2

**Comment by PhilippeAccorsi** [comment]
This is what we need to make migration and path for tracim_v2:

`radicale --export-storage export -C conf.ini --debug && cd export/collection-root/ && mv collections/ agenda/ && cd agenda/user/ && for i in $(find [0-9]* -type d); do mv "$i" `echo $i | sed -E 's/^([0-9]+)(\.ics)/\1/g'`;done && cd ../workspace/ && for i in $(find [0-9]* -type d); do mv "$i" `echo $i | sed -E 's/^([0-9]+)(\.ics)/\1/g'`;done`

**Comment by PhilippeAccorsi** [comment]
@inkhey @buxx @lebouquetin  what do you think about naming of folder for radicale:
- radicale_storage/ (like we have in tracim v2) 
or
-radicale_data/ (like we have in tracim v1)

If we change this name we need to change some file:
- backend/development.ini.sample
- backend/.gitignore
- tools_docker/Debian_Uwsgi/common.sh (for docker images)

**Comment by PhilippeAccorsi** [comment]
Need some documentation for:
- old name `radicale_data` changed to 'radicale_storage'
- after migration of calendar from v1 to v2:
    - new url for personal agenda => `http://{domain or ip}/agenda/user/{user_id}/`
    - new url for workspace => `http://{domain or ip}/agenda/workspace/{workspace_id}/`

**Comment by PhilippeAccorsi** [comment]
After discuss with @lebouquetin we save `radicale_storage` name in tracim v2.

**Comment by buxx** [comment]
+1 for radicale_storage

**Comment by PhilippeAccorsi** [comment]
@PhilippeAccorsi Add some documentation in `backend/doc/`.
Verify if all doc is up-to-date.

**Comment by inkhey** [comment]
About migration problem, reason is that tracim_v1 doesn't store description/name as caldav props.

Before forcing change of user name or running script that automatically update all calendar
```
 ❯ cat .Radicale.props
{"ICAL:calendar-color": "#487eae", "tag": "VCALENDAR"}
```
After:
```
 ❯ tailf .Radicale.props
{"C:calendar-description": null, "D:displayname": "Gu\u00e9na\u00ebl Muller", "ICAL:calendar-color": "#487eae", "tag": "VCALENDAR"}
```

I do not reproduce case where all name got fixed when we just updated one user or one workspace. System work as expected: if change of name or description of user/workspace, there is an update of selected user/workspace properties if there are different. In this case, properties doesn't exist, so they are automatically created.

**Comment by PhilippeAccorsi** [comment]
@inkhey thats "I do not reproduce case where all names got fixed when we just updated one user or one workspace.". I can't also reproduce this.

@lebouquetin We have two option after migration of calendar to show the good name in all agenda:
- start specific tracimcli command like `tracimcli caldav update name` or something like that. This is just for updating all agenda name.
Or
- use existing tracimcli command `tracimcli caldav agenda create`. I think we need to rename this command to `tracimcli caldav synchronize` to make sure all agenda and all name is up-to-date between database and radicale folder/data.

**Comment by PhilippeAccorsi** [comment]
@inkhey after discuss with @lebouquetin :

- [ ] Rename `tracimcli caldav agenda create` to `tracimcli caldav` (this command is to synchronize radicale with tracim data, because radicale and tracim is note started by same server).

@PhilippeAccorsi 
- [ ] add this command at end of documentation after migration of agenda.

**Comment by PhilippeAccorsi** [comment]
Documentation available in instance of tracim `tracim/backend/doc/migrate_from_v1.md`

**Comment by PhilippeAccorsi** [comment]
Verified.
