### ISSUE TITLE
Browserstack logo and message is missing from the README.md

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1613]
Currently, the browser stack logo is missing from the README.md page.
It has been lost during the repository migration

Exepected:
Put it back on bottom of README.md.

See dfb116958da3c2182ea9b60f4905016103be04f7 to get the source code

**Comment by Skylsmoi** [comment]
code to add
```
<a href='https://www.browserstack.com' target="_blank">
    <img src="https://raw.githubusercontent.com/tracim/tracim/master/tracim/tracim/public/assets/img/logo_browserstack.png" width="150">
</a>
BrowserStack support open source project and graciously helps us testing Tracim on every devices.
```

**Comment by gbonaspetti** [comment]
The image is now added and the README is updated.

**Comment by gbonaspetti** [comment]
I reopened that issue to make the image independent of branche.

**Comment by metzgegu** [comment]
Verified on branch (wait merge to close).
