### ISSUE TITLE
change wrong font-awesome icons

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1621]
currently, the 2 wrong icons are the lock icon for button admin and the fullscreen icon of caldavzap

expected:
- lock icon should be cog
- fullscreen icon should be always expand

**Comment by Skylsmoi** [comment]
changes:
- btn admin is now cog
- btn fullscreen of caldavzap doesn't change upon switching to fullscreen

**Comment by PhilippeAccorsi** [comment]
Verified.
