### ISSUE TITLE
app file is not in full height after decrease size of header

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1624]
## Bug description & symptom

After reduce size of header, the file app not use the maximum height available.

## Diagnostic

"unknown"

## Expected

- [ ] The appa file use the maximum height is possible.

## Context and version information
Visible on firefox.

## How to reproduce

Open file app.

## Screenshots

![Sélection_003](https://user-images.githubusercontent.com/25848257/56588469-b169e700-65e3-11e9-833b-9a486b81b8c7.jpg)

## Impacted components

- *frontend*
- *css*

## Extra information

Space at end of thread app is too big also after decrease size of header, so I think its necessary to verify other app for bug like this.

**Comment by Skylsmoi** [comment]
the height of app file is now correct

**Comment by PhilippeAccorsi** [comment]
Verified.
