### ISSUE TITLE
Agenda should not be in list of content to allow in folder

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1631]
## Bug description & symptom

Currently agenda is in list of content allowed in folder, it should not be there as agenda is not a valid content_type.
![agenda_in_folder_content_list](https://user-images.githubusercontent.com/7851652/56720493-46372680-6743-11e9-8e18-41e928d86f98.png)

## Diagnostic

This happened because Frontend rely on applications list instead of content_types list in API.

## Expected

Frontend should not display agenda in this list. 
First we need a quick fix to not show this in frontend for tracim 2.2, then we should do something better.

**Comment by Skylsmoi** [comment]
neither "agenda" no "comment" should appear on the content types list.

the app list is now get through the proper content type endpoint

**Comment by PhilippeAccorsi** [comment]
Verified.
