### ISSUE TITLE
Better exception for error return by user_with_email_exists method

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1635]
## Bug description & symptom

`user_with_email_exists` method (`backend/tracim_backend/lib/core/user.py`) contain a catch all exception, that's not correct, we should catch only specific exception here.

## Expected

Do a better catch of specific exception in  `user_with_email_exists`

**Comment by buxx** [comment]
I open a pull request to fix it: https://github.com/tracim/tracim/pull/2932 by simply replace caught exception.

**Comment by buxx** [comment]
I close this issue after merge of https://github.com/tracim/tracim/pull/2932
