### ISSUE TITLE
Create React App to display the leftmenu tree view

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#164]
An Api is already available for the left menu.
It uses jstree
Create a react app that will asynchronously load the menu with the same API

**Comment by Skylsmoi** [comment]
see https://github.com/tracim/sidebar_left

**Comment by tracim** [comment]
Check if this has been merged into tracim. If not, merge it.

**Comment by tracim** [comment]
Check if this stuff has been merge. If not, merge it.

**Comment by Skylsmoi** [comment]
it has been merged :  
https://github.com/tracim/tracim/blob/3d2ce79d634813dfbba5bb5708fbc9e9d6a0f624/tracim/tracim/templates/user_workspace_widgets.mak#L154
