### ISSUE TITLE
Travis CI : use xenial for all jobs

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1640]
## Bug description & symptom

Currently `dist:trusty` is used (from https://github.com/tracim/tracim/issues/1640, used fixed value to avoid issue later as travis should be using xenial by default soon) for all travis_ci jobs except python 3.7 one (which use `xenial`). This is due to issue with making postgresql work with travis on xenial.

## Expected

having all travis jobs running with postgresql and work correctly

**Comment by raphj** [comment]
We haven't used xenial for long. Closing.
