### ISSUE TITLE
add possibility to open content in new tab directly from recent activity on dashboard

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1641]
## Feature description

Add possibility to CTRL+click on recent activity to open content in new tab.

## Context

At present you can open content in new tab with ctrl+click just in list of content. Not from dashboard recent activities.

## Impacted components

- *frontend*

**Comment by Skylsmoi** [comment]
the link now handle the "open in new tab"
For folders:
- if user is at least content manager, he can click on it and it'll open the folder advanced app
- if user doesn't have enough rights, he can't click on it

**Comment by PhilippeAccorsi** [comment]
Verified.
