### ISSUE TITLE
agenda is visible in header on login page after specific process

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1644]
## Bug description & symptom

Agenda is visible in header after disconnect from tracim and try to reset password

## Diagnostic

"unknown"

## Expected

- [ ] when you are disconnected, you just can see element normally available in login page

## Context and version information

- Desktop environment (if applicable)
    - *Browser firefox*

## How to reproduce

- go on login page
- make login with user credential
- disconnect from tracim
- click on reset password
=> now you can see agenda button on header

## Screenshots

![bug_agenda_header](https://user-images.githubusercontent.com/25848257/56797306-b6fa4380-6814-11e9-996f-5b6fe1399d11.gif)

## Impacted components

- *frontend*

**Comment by Skylsmoi** [comment]
The issue actually is that the agenda btn is shown on page forgot password only when email notifications are disabled

**Comment by Skylsmoi** [comment]
agenda btn removed from header on page forgot password when email not activated

**Comment by PhilippeAccorsi** [comment]
Verified.
