### ISSUE TITLE
Remove automatic scroll to the top when opening content

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1648]
## Bug description & symptom

When I open a content, in background I can see automatic scroll to the top.

## Diagnostic

"unknown"

## Expected

- [ ] When I open a content, no scroll is activated (look on demo.tracim.fr for normal case)

## Prerequisites

- Have more than 14 content in list of all content to see scroll bar on the right of the page

## How to reproduce

- go down with scroll bar
- open a content
=> you can see scroll to the top when your app is open
- if you need to open a content near the first one, you need to scroll down first.

## Screenshots

![automatic scroll to top](https://user-images.githubusercontent.com/25848257/56816415-cba20000-6843-11e9-9d20-c8ae5e16af4a.gif)

## Impacted components

"unknown"*

**Comment by PhilippeAccorsi** [comment]
@lebouquetin I think its important to solved that for 2.2
In demo.tracim.fr (2.1) no automatic scroll when opneing content.

**Comment by Skylsmoi** [comment]
the issue come from this commit https://github.com/tracim/tracim/commit/78b3704cd79a414fd2e929e13c18201f60bdb17c
which is fixing this issue https://github.com/tracim/tracim/issues/1563

**Comment by Skylsmoi** [comment]
The problem is the routing of workspace content.
It needs 2 routes:
- list of content like `/ui/workspaces/1/contents`
- open a content like `/ui/workspaces/1/contents/html-document/4`

Having the 2 routes declared separately create the current issue.
Having them merged like in 78b3704 fixes the current issue but will recreate #1563

**Comment by Skylsmoi** [comment]
apps should now properly reload the data from api when the content id change

**Comment by Skylsmoi** [comment]
I rolled back the routing with the switch and put back the double matching route on content list and content open.
But I have fixed the usage of data received by _app_name__showApp custom event.
The handlers of "_showApp" events will now call a "_reloadContent" when the content id has changed

**Comment by PhilippeAccorsi** [comment]
Verified.
