### ISSUE TITLE
Better escaping for email

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1649]
## Bug description & symptom

Currently as found https://github.com/tracim/tracim/issues/1617, escaping of content in email is not correctly done. 

**Diagnostic**

We probably need to refactor the way we deal with email template, because that unclear and the way we deal with it actually means, it's complex to know where we should escape and where we should not.

We should maybe using more complex mako mecanism in order to have all html code source in mako template (and not one part generated by python source code, the other in make template), this permit to automatically parse all data insert into mako file and have a strict distinction between integrated data and html.

**Expected:**

- [ ] - All data integrated into mail should be escaped.

**Comment by inkhey** [comment]
Done in #1650:
- Escape most strings (html content field like comment and body are not included because it's feature breaking)
- Refactoring template, work on html is done at only one place: mako template.

**Comment by PhilippeAccorsi** [comment]
Verified.
