### ISSUE TITLE
Better copy: preservate revision_id order by creating subcontent and revision in correct order

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1652]
## Bug description & symptom

Found during fixing #1499, before this fix, issue cannot occured as copy of content with comment is broken.
Currently copy is done by copying all revision and then copying all subcontent. This means that revision_id order beteween revisions of content and subcontent are not orderer the same way as before.
This broke "comment_ids" of revision in api which rely of revision_id order. Currently we can have same comment associated to multiple revision using current copy feature.

## Expected

- Do a correctly ordered copy.
- Verify comment_ids of revision work correctly.

**Comment by PhilippeAccorsi** [comment]
Verified.
