### ISSUE TITLE
Move ROLE constant to frontend lib and refactor it's usage

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1656]
## Bug description & symptom
The Role management in done with a variable duplicated in frontend and frontend_lib
(apps get that variable from frontend)

Since apps doesn't have access to that variable, they mimic the mechanism by just comparing the user role level to some magic number (from 0 to 8) that match the ROLE constant from /frontend

## Diagnostic
There are 2 ways of fixing it:

1) The easiest way is to put Role constant in frontend_lib. Then frontend and each apps get it from there using imports.
- pros: Data is in frontend, it makes the code simpler, reduce async dependencies
- cons: The object must stay synchronized with the backend Roles

2) The other way is to let frontend get it from API and give it to each apps the same way it currently does.
- pros: Data is always sync with backend
- cons: Add an api call that needs to be created in backend

:warning: The same fix should be made for the Profile list

:bulb: Don't forget to create a Role object AND a Role Array. We need to be able to list through the roles and to access a role details like so: `ROLE[user.role].hexcolor` for example (see https://github.com/tracim/tracim/issues/1396)

## Impacted components
potentially the entire frontend and a bit of backend depending on the solution

Note: There is a PR for 1)

**Comment by Skylsmoi** [comment]
Related: https://github.com/tracim/tracim/issues/1396

**Comment by Skylsmoi** [comment]
To test this:
We cannot test these fix specifically as they involves the entire app.
All we should do is to tests tracim for next release with different role and profile and keep an eye on the feature that we should and shouldn't be able to use

**Comment by Skylsmoi** [comment]
### Post dev report
The old Giulia's branch has been merged.
It includes the solution 1) in that issue's description.

#### What it lacks
The role and profile harmonization. Which is the fix of the fact that highest PROFILE is 1 and highest ROLE is 8.

It also lacks the ROLE array. Problem is, there is already ROLE, ROLE_OBJECT and PROFILE. We need to find a consistent way for all of this.
**Solution**: have a constant for each roles and profiles and have ROLE created with theses constants and ROLE_LIST created the same way. And idem for PROFILE

**Comment by Skylsmoi** [comment]
the ROLE and PROFILE harmonization is done with the **solution** explained above

**Comment by PhilippeAccorsi** [comment]
Some problem/regression exist with this refactor:
- Office document can't be modify
- Need modification to use same value (level of rights) in back and frontend

**Comment by Skylsmoi** [comment]
The office document issue is fixed in a different issue https://github.com/tracim/tracim/issues/2607

**Comment by PhilippeAccorsi** [comment]
Need some verification on develop when all refactor is done and merge in develop.

**Comment by PhilippeAccorsi** [comment]
Verified on develop
