### ISSUE TITLE
Better support for env var settable config

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1661]
## Bug description & symptom

Mechanism allowing to set environnement variable to override config file work great but some config parameters are not setted through into CFG object.
Those included some  important  "global" settings:
- sqlalchemy.url :warning: 
- beaker cookie dirs (session.data_dir, session.lock_dir)

But also some more specific settings:

- radicale special config
- other beaker session parameters
- other sqlalchemy parameters

## Diagnostic

We should at least allowed relying of CFG object parameter for sqlalchemy.url and beaker cookies dirs in order to support most case and be able to force beaker dir existence ( see https://github.com/tracim/tracim/issues/1524)

## Expected

- Fully Support only needed parameters, other parameter support should work only in config file.

**Comment by inkhey** [comment]
i proposed to support now sqlalchemy.url and beaker cookies dir to allow fixing #1524 as soon as possible and think about a more complex support later.

**Comment by inkhey** [comment]
done in  #1672: 
- use of env_var in travis conf file
- remove most generic config param in test_config.ini file, using dotenv mecanism instead in order to allow setting more easily default database and dir used for tests.
- rename TRACIM_BACKEND_TEST_CONFIG_FILE to BACKEND_TEST_CONFIG_FILE to avoid confusion between tracim var and non-tracim var.
- support for env var for 'session.data_dir' and 'session.lock_dir'.
- support for env var for 'sqlalchemy.url' for both tracim and alembic.
- move sliced_dict method to utils.
- fix issue on with 'type_' on migration script with mysql. (don't really know the reason of origin of the issue as tests work before, dependencies update which means more strict check ?)

**Comment by inkhey** [comment]
@PhilippeAccorsi , @lebouquetin we merge the associated branch but we do not set the ticket in done, i move in to 2.3, "need test".

**Comment by inkhey** [comment]
@PhilippeAccorsi to check if this work, you can just test if you can set beaker session path, sqlalchemy_url, radicale path, etc... 
Another way to check this, is just waiting https://github.com/tracim/tracim/pull/1687 which will use fully the feature for travis. If tests doesn't fail, this mean feature is working .

**Comment by Skylsmoi** [comment]
As inkhey said, since #1687 is merged and tests have passed, I consider this issue verified
