### ISSUE TITLE
Its not possible to open all agenda view in new tab when ctrl+click on button Agenda

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1664]
## Bug description & symptom

You can't open all agenda with button visible in headbar, in new tab if you ctrl+click on button Agenda

## Diagnostic

"unknown"

## Expected

- [ ] open all agenda in new tab with ctrl+click
- [ ] open all agenda in new tab with wheelmouse click

## How to reproduce

- try to ctrl+click or wheelmouse click on button Agenda (in headbar)

## Impacted components

- *frontend*

**Comment by celiamgtt** [comment]
The problem no longer exists.
