### ISSUE TITLE
add research in tracim 

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1668]
## Feature description

Add possibility to research in all content

## Context

For the moment its not possible to research content in tracim.

## Prerequisites

- issue #1667 is done

## Impacted components

- *backend*
- *frontend*

## Extra information

What we need after discuss on 2019/05/03:
- research input is in headbar
- validate research with Enter key
- if its possible => validate research with a button near research input
- Frontend just make one request to backend for research
- result is show in one full screen app
- if research is not activated in backend, don't show research input
- In case of responsive problem with research input, deactivate research in responsive.

**Comment by gbonaspetti** [comment]
Linked to https://github.com/tracim/tracim/issues/1667 and being done in the corresponding branch

**Comment by basilelegal** [comment]
@gbonaspetti @Skylsmoi 
 - If I type straight into the browser the url: `/ui/search-result`, I'll get a search for an empty string.
 - If I change the language the breadcrump isn't translated, I have to reaload the page for it to be translated
 - @lebouquetin Should we display "0 best results"  and the header of tab (see screenshot bellow).
![Screenshot at 2019-06-17 08-13-35](https://user-images.githubusercontent.com/7879232/59603715-2800fd80-90d8-11e9-9695-7f474772aaca.png)

**Comment by basilelegal** [comment]
@gbonaspetti @Skylsmoi Point 3 Tab's header can be refacted to all content list.

**Comment by celiamgtt** [comment]
Verified
