### ISSUE TITLE
add move of content with drag-&-drop feature

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1669]
## Feature description

Add possibility to drag-&-drop content from one folder to another or directly at the begining path of sharedspace.

## Context

For the moment its just possible to move content with webdav feature.

## Prerequisites

- Verify if backend API is available and working correctly for move content.

## Impacted components

- *backend*
- *frontend*

## Extra information

What we need after discuss on 2019/05/03:
- Possibility to move content in one specific sharedspace. For the moment its not importent if its not possible to move from one sharedspace to another
- If you move folder, all content of this folder is also moved
- just "content manager" and "shared space manager" can move content
- add small icon to know if we can move this content (ex: `...` at begening of name of content is list off all content)
- its possible to move also from filtered view. Ex: if you just see files, you can also move this files.

**Comment by LucBarry** [comment]
Verified
