### ISSUE TITLE
Allow to use RedisQueue for email sending

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#167]
Currently we send emails using tgext.asyncjob, which is not working correctly in conjonction with uwsgi.

TODO : 
- add a parameter which allows to use RQ - http://python-rq.org/ for asynchronous / background tasks
- add configuration parameters for RQ in the .ini file
- add associated documentation
- make tracim to send emails  through an asynchrounous-fake function by default
- remove useless dependency tgext.asyncjob

Note : this bug fix must include documentation of the feature

**Comment by buxx** [comment]
Some reflexion before implement it:

* rq worker is independent, so:
  * In production, It need to be managed with something like uwsgi/supervisor (note: my preliminary tests faisl with uwsgi, it look like more easier with supervisor: http://python-rq.org/patterns/supervisor/)
  * it need to be started with entire tracim/tg environement loaded

Additional note: It should be important to track error on rq worker. rq provide Sentry ready config: http://python-rq.org/patterns/sentry/

**Comment by tracim** [comment]
- supervisord is the tool for that, yes
- second point
  - no need for tracim/tg environement if the module is only in charge of sending emails (not building them)
  - a way to do so (ie load tracim/tg environment is to create a gearbox task)

**Comment by buxx** [comment]
Note: Create gearbox task (with app context) who only send mails. Then, create issue to create a task who generate email.

Note: Don't use supervisor for now, create Tracim Daemon who run rq worker.
