### ISSUE TITLE
Add documentation for CalDAV and WebDAV

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1675]
## Feature description

Add the documentation for CalDAV and WebDAV.
What it is and how to use it.

Theses information should be place in issue 1673 and 1674 (not linking to avoid reference)
Theses 2 issues will be used as documentation pages while a real documentation is ready.

**Comment by PhilippeAccorsi** [comment]
Some information added.
Tested also by @inkhey 

I close this issue.
