### ISSUE TITLE
use pre-commit mecanism to simplify syntax check

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1682]
## Feature description

pre-commit mecanism allow us to avoid thinking about running flake8, isort, black and other stuff. it allow to does those check during commit and propose direct solution.

## Context

With new formatting check mecanism, i failed many time because i forgot to blake or isort my code. pre-commit mecanism permit me to know directly this issue before committing.

Expected:

Running git commit does black, isort, flake8 and some other check directly using pre-commit mecanism.

**Comment by inkhey** [comment]
this need to move some wsgi code to avoid issue with import

**Comment by PhilippeAccorsi** [comment]
@inkhey 
Can I test something for this?
Documentation exist on repo?

**Comment by lebouquetin** [comment]
I dont think so. @PhilippeAccorsi consider it ok; developers will fix it if it's broken (they are the target of this fix, not the enduser)

**Comment by PhilippeAccorsi** [comment]
Verified.
