### ISSUE TITLE
timeline stay close sometime when opening html document (completly random)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1686]
## Bug description & symptom

Sometime when I open html document the timeline stay closed.

## Diagnostic

"unknown"

## Expected

- [ ] timeline is open /close all the time for the same reason. Random is not an option.

## Context and version information

- Desktop environment (if applicable)
    - *Browser firefox*

## Prerequisites

- create 2 html document
- write text in one document

## How to reproduce
 
- open first document or second document alternatively.

## Screenshots

![randomtimeline](https://user-images.githubusercontent.com/25848257/57300491-36bac480-70d7-11e9-9e3a-366365ba06dd.gif)

**Comment by Skylsmoi** [comment]
This is an old behavior that was developed a while ago but it seems it broke and we didn't noticed it.
The behavior is supposed to always open the app with the timeline hidden when it opens in edit mode.

I have checked a bit and it seems quite complicated to properly fix.

We have seen with @PhilippeAccorsi and we decided to remove this behavior, at least for now.
That means that the app htmldoc will always opens with the timeline open when opening in edit mode. (eg, when there is only one revision)

**Comment by lebouquetin** [comment]
"It is complicated to properly fix it" is not enough as an explanation. There is no reason to show timeline when opening the first time the app because the timeline is empty.

If it is complicated to fix it properly, then do a dirty hotfix and keep the ticket open for next release.

**Comment by PhilippeAccorsi** [comment]
Reminder:
- [ ] hotfix to close timeline all the time when document is empty.
- Issue #1709 is created to solved correctly this bug for tracim 2.3

**Comment by Skylsmoi** [comment]
commits above where reverted

**Comment by Skylsmoi** [comment]
The timeline wont closes itself when opening a htmldoc that has no content

**Comment by PhilippeAccorsi** [comment]
Verified.
