### ISSUE TITLE
2 bug in html document: height problem in full screen and also in app between text and timeline (regression)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1693]
## Bug description & symptom

two bug:
- full screen not use the maximum height of the page (since reduction of header)
- Different height in app between texte (in left) and timeline

## Diagnostic

*Optional - explain what has been found and what is not yet clear. If unknown, write "unknown".*

## Expected

- [x] the full screen use the maximum of height available (see first gif)
- [x] No difference between height of text zone and timeline (see second gif)

## Context and version information

    - *Browser firefox*

## How to reproduce

- open one html-document in full screen (bug1)
- just look bottom of the app html document (in edit or not)

## Screenshots

Bug1:
![bug1](https://user-images.githubusercontent.com/25848257/57443855-40ffce80-724f-11e9-97ff-c21a023b1d4a.gif)

Bug2:
![bug2](https://user-images.githubusercontent.com/25848257/57443865-452bec00-724f-11e9-9622-e2dcce6d3fd9.gif)

## Impacted components

- *frontend*

**Comment by gbonaspetti** [comment]
Bug 1: correct the initialization script for tinymce.
Bug 2: put the same layout for html-document that file app has

**Comment by PhilippeAccorsi** [comment]
One bug appear when you are in full screen and if you resize your webbrowser. At this moment you lost end of page with message " Powered by tinymce". And when you show you web browser in standart size, this line " Powered by tinymce" stay invisible. You can't see also last line of text editor.

We have the same problem on tracim 2.1

**Comment by PhilippeAccorsi** [comment]
With gif is more explicit.
![bug_tinymce](https://user-images.githubusercontent.com/25848257/57710366-1954a000-766d-11e9-9b7e-7cecc9f798dc.gif)

**Comment by gbonaspetti** [comment]
The problem was that when tinymce recalculates the window size, it does not know that we have a header, so after its calculation I change the new height of the iframe by discounting the header.

**Comment by PhilippeAccorsi** [comment]
The fix is working, but we have another bug:
- Edit document
- go in fullscreen
- resize your browser 
- close full screen
- make your browser in full screen
=> now you can see tinymce is not show with same height like we have at beginning.

![bug_tiny](https://user-images.githubusercontent.com/25848257/57917779-b1cd6900-7895-11e9-87b3-dd81805f69f4.gif)

**Comment by PhilippeAccorsi** [comment]
Verified.
