### ISSUE TITLE
Document params name for all variable fully supported (env var and config file).

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1696]
## Bug description & symptom

- We need to know and document all supported var for both env var and config file with naming associated
- We need to known which parameters are partially supported.

## Expected

- Get list of env var supported easily automatically
- Know which parameters are not supported now and why.

**Comment by inkhey** [comment]
@PhilippeAccorsi The why of partially supported for all partially supported parameters in https://github.com/tracim/tracim/pull/1697 list is the same: 
- It's not straightforward to support them as there is already a magic mechanism to handle them that work outside tracim
- Those parameters are not considered as needed for overriding by env var.

**Comment by inkhey** [comment]
#1697 explain supported and unsupported params as environment variable but do not explain the why for all params. I will add explanation here (as documentation doesn't seems the good place to explain this): 

- sqlalchemy.url and beaker path parameters (session.lock_dir, session.data_dir) will be added with `https://github.com/tracim/tracim/pull/1687`

**Comment by PhilippeAccorsi** [comment]
Verified.
