### ISSUE TITLE
build frontend show warning "error  Closing curly brace does not appear"

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1698]
## Bug description & symptom

This warning is visible when you use `build_full_frontend.sh` and when is build frontend:
~~~
WARNING in ./src/component/Dashboard/RecentActivity.jsx
Module Warning (from ./node_modules/standard-loader/index.js):
(Emitted value instead of an instance of Error) 
/home/algoo/repo/tracim/frontend/src/component/Dashboard/RecentActivity.jsx
  57:11  error  Closing curly brace does not appear on the same line as the subsequent block  brace-style

✖ 1 problem

 @ ./src/container/Dashboard.jsx 38:0-71 974:29-43
 @ ./src/container/Tracim.jsx
 @ ./src/index.js
 @ multi @babel/polyfill ./src/index.js
~~~

## Diagnostic

*Optional - explain what has been found and what is not yet clear. If unknown, write "unknown".*

## Expected

- [ ] no warning error arrived when you build app

## How to reproduce

- start `build_full_frontend.sh` on tracim in develop branch.

## Impacted components

- *frontend*

## Extra

I don't see this error when I build docker images. Strange.

**Comment by PhilippeAccorsi** [comment]
I have also an error when build  app html_document
~~~
WARNING in ./src/container/HtmlDocument.jsx
Module Warning (from ./node_modules/standard-loader/index.js):
(Emitted value instead of an instance of Error) 
/home/algoo/repo/tracim/frontend_app_html-document/src/container/HtmlDocument.jsx
  324:1  error  Trailing spaces not allowed  no-trailing-spaces

✖ 1 problem

 @ ./src/index.js 3:0-56 15:47-59
~~~

**Comment by gbonaspetti** [comment]
Change place of curly brace from frontend and delete spaces from html_document.

**Comment by PhilippeAccorsi** [comment]
Verified.
