### ISSUE TITLE
Breadcrumb is not updated when updating content name

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1699]
## Bug description & symptom

Breadcrumb path and content name doesn't match:

![Capture d'écran de 2019-05-09 16-45-58](https://user-images.githubusercontent.com/7851652/57463778-c0a39280-727b-11e9-8b01-871130b09d31.png)
To reproduce:
- go to a content
- rename it
- close content to return to content list view.

## Expected

 1. Breadcrumb path should be updated when content name is updated by user.
 2. Added (https://github.com/tracim/tracim/issues/1699#issuecomment-490942589) When content is closed, breadcrumb should be updated to not point to content closed.

## Check this before development

https://github.com/tracim/tracim/issues/1637

**Comment by PhilippeAccorsi** [comment]
One another bug is when you close app, the breadcrumbs is not updated. Normaly it not show filename because the file is closed.

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi @lebouquetin the breadcrumb path not show folder, is it correct?

**Comment by Skylsmoi** [comment]
@PhilippeAccorsi Yes, the folders are not included in the breadcrumbs.
We might implement it later but for now we will keep it that way

**Comment by Quiwy** [comment]
Can't reproduce on build_088
![breadcrumb_title](https://user-images.githubusercontent.com/20048264/185622030-3c1fabbc-800b-47ed-8dcc-4763744fdded.gif)
