### ISSUE TITLE
color about agenda is all the time the same (but not in unstable at 1pm on 09/05/2019) 

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1700]
## Bug description & symptom

When you create sharedspace, associated agenda have all the time the same color

## Diagnostic

*Optional - explain what has been found and what is not yet clear. If unknown, write "unknown".*

## Expected

- [ ] backend code generate color for each shared space correctly

## How to reproduce

- use docker images 2.2.0_rc1
- create new shared space 

## Impacted components

*"unknown"*

## Extra information

On unstable is not the case, maybe something wrong in last backend commit

**Comment by PhilippeAccorsi** [comment]
Need to find why its not the same in unstable and in 2.2.0_rc1.

**Comment by inkhey** [comment]
#1702 fix this but some other:
- fix this issue: use string generated instead of always same string.
- support for all utf8 character by better escaping  xml and encoding explictly to utf8
- make color algorithm for creation deterministic (= created color from same string are the same)

**Comment by inkhey** [comment]
@PhilippeAccorsi to recheck behaviour of this PR:
- check if color of calendar are different
- create a workspace name "Global manager" and check if color is same as admin. (deterministic algorithm)
- check with workspace or user display name with special character: emoji and "<> &"

**Comment by PhilippeAccorsi** [comment]
Verified.
