### ISSUE TITLE
Using resetpassword fork

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#171]
We actually use a tgapp resetpassword fork because: https://github.com/gasbasd/tgapp-resetpassword/pull/4 .

Check if it is merge.

**Comment by herawo** [comment]
It has been merged but the pypi package is not up-to-date.

**Comment by tracim** [comment]
We must at the end use the pypi installation.
See issue https://github.com/gasbasd/tgapp-resetpassword/issues/5 - when closed, check that pypi is up-to-date and update requirements.txt

**Comment by tracim** [comment]
Use tgapp-resetpassword==0.2.0 from pypi in requirements.txt
