### ISSUE TITLE
Some buttons is now blue, ex in app file (regression)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1712]
## Bug description & symptom

Some buttons are now in blue color. In tracim 2.1 the color is black. Ex: download button in app file.

## Diagnostic

"unknown"

## Expected

- [ ] find all regression about color button
- [ ] Color of all button is black now

## How to reproduce

- open app file on tracim rc1

## Screenshots

Old color (visible on https://demo.tracim.fr)
![old color](https://user-images.githubusercontent.com/25848257/57696434-0b912180-7651-11e9-981e-b4ad0c9de9db.jpg)

Current color (with tracim rc1)
![current color](https://user-images.githubusercontent.com/25848257/57696477-22377880-7651-11e9-9bfd-3d31cb839ba8.jpg)

## Impacted components

- *frontend*
- *htmldoc / file / thread app*
- maybe more ....

**Comment by gbonaspetti** [comment]
The default color for <a> tags it's blue according Bootstrap. I change the default for black in the Generic file in the frontend.

**Comment by PhilippeAccorsi** [comment]
Verified.
