### ISSUE TITLE
Responsive issue on app htmldoc when switch from lg to md with timeline closed

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1718]
## Bug description & symptom

When switching breakpoints to md with the timeline closed, the content (the left part) take half the available space.

## Expected

The left part should take all the available space

## How to reproduce

- open a htmldoc content in at least lg breakpoit
- close the timeline
- reduce window size to md or sm breakpoint

**Comment by gbonaspetti** [comment]
There was the same problem in the file app. I change the configuration for all screens smaller than lg and I adapted the elements for the new configuration.

**Comment by PhilippeAccorsi** [comment]
Verified.
