### ISSUE TITLE
Responsive some small problem

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1726]
## Bug description & symptom

- At present the button `create a shared space` visible in card `WELCOME TO TRACIM`(when you don't have any sharedspace) is not centered when width is gooing less than 408
- ~~Also the text `Have a good day !` is not visible in card when you have a small screen size~~
- Breadcrumbs is not good for UX 
![responsive-breadcrumb](https://user-images.githubusercontent.com/25848257/57847239-47092880-77d6-11e9-95bc-855f8ad31e7a.gif)

## Diagnostic

*"unknown"*

## Expected

- [ ] The button is all the time centered
- [ ] The height of card is modified when text present in card is show on multiple line

## Context and version information

- Smartphone/Tablet (if applicable)
    - *Browser: chrome, firefox, opera

## Impacted components

- *frontend*

Edited: one bug not exist since last fix merge in develop

**Comment by gbonaspetti** [comment]
@PhilippeAccorsi can you do a gif for the second topic (- Also the text Have a good day ! is not visible in card when you have a small screen size)? I did not succeed to reproduce the problem.

**Comment by PhilippeAccorsi** [comment]
@gbonaspetti For the second topic, I can't reproduce this afternoon. So I think something merged this morning fix this bug :)

**Comment by gbonaspetti** [comment]
I centered the button and put a little margin for not be to close of the breadcrumbs. For the breadcrumbs I left all the words referring to the same space in the same line and I put in the next word in the line below if the screen is too small for all path.

**Comment by PhilippeAccorsi** [comment]
@gbonaspetti My issue is not clear, sorry.
So One another point is about card when we don't have any sharedspace.
- At present the button create a shared space visible in card WELCOME TO TRACIM (when you don't have any sharedspace) is not centered when width is gooing less than 408

![button_not_in_center_of_card](https://user-images.githubusercontent.com/25848257/57914626-48e2f280-788f-11e9-8c5b-75811ee4583a.gif)

Can you fix this for 2.2

**Comment by gbonaspetti** [comment]
ok, sorry @PhilippeAccorsi 
Should I change the button that I centered last time?
![Screenshot from 2019-05-17 10-38-29](https://user-images.githubusercontent.com/35422692/57914967-066de580-7890-11e9-835c-ec1450bbdd81.png)

**Comment by PhilippeAccorsi** [comment]
Yes.
Thanks

**Comment by PhilippeAccorsi** [comment]
Verified.
