### ISSUE TITLE
Changing the message in link to integrate agenda space

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#1730]
## Bug description & symptom

*Change the message in Dashboard and My Account > Agenda to be more clear for the user*

## Expected

*A clearer message, not including the words "shared space's"**

## Screenshots
![AgendaMessageDashboard](https://user-images.githubusercontent.com/35422692/57858241-f6eb8f80-77f0-11e9-9a98-55e5b75905c1.png)
![AgendaMessageMyAccount](https://user-images.githubusercontent.com/35422692/57858242-f7842600-77f0-11e9-9c21-ea1a93838b1c.png)

## Extra information

*English and French*

**Comment by PhilippeAccorsi** [comment]
Verified.
