### ISSUE TITLE
copyright is not updated with year 2019 and is to hight in sidebar

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1742]
## at present

- Copyright in sidebar is too high
- Copyright in Login page and in side bar is not updated with present year (2019)

## expected

- [x] copyright is 2013-2019 (in login page and in sidebar) 
- [x] copyright is visible all the time at bottom of sidebar (verify if its ok when you have multiple shared space).

**Comment by gbonaspetti** [comment]
Done at issue #1741

**Comment by PhilippeAccorsi** [comment]
Verified.
