### ISSUE TITLE
UX add message about file is Deprecated like we have when file is deleted or archived

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1743]
## Feature description

Add message at beginning of content to know this content is deprecated.

## Context

When we open content we need to see status to now if its deprecated or not. No other message is show for that. If content is deleted or archived we have specific message to inform user.

## Impacted components

- *frontend*

## Extra information

Show message "This content is deprecated" or something like that.

Ex with what we have when content is deleted:

![Sélection_007](https://user-images.githubusercontent.com/25848257/57930344-fff26480-78b5-11e9-95b5-9286e8d65708.jpg)
 
## Expected

- [ ] show specific message about deprecated
- [ ] translation of this message is working
- [ ] this message is visible for all content type

**Comment by gbonaspetti** [comment]
I put a tag on some components to mark that the content status was deprecated (comparing the status slug with the content status) and if the tag was positive, it prints the message.

**Comment by PhilippeAccorsi** [comment]
In case of thread we can see this bug:

![deprecated_in_thread](https://user-images.githubusercontent.com/25848257/59034968-95a56200-886c-11e9-8049-e182d32b201a.gif)

@Skylsmoi do you think its complicated to solved that ?
@lebouquetin do we need to solved that for 2.3 or we had this to know issue?

**Comment by gbonaspetti** [comment]
@PhilippeAccorsi the bug is just the link that the warning makes?

**Comment by PhilippeAccorsi** [comment]
@gbonaspetti sorry. The bug here is the message is under the first content in this thread. We can see correctly the first version.

About the link: I think its not a problem. I think its better if its not a link make by warning (this link not exist) but I don't know if its important.

**Comment by gbonaspetti** [comment]
@PhilippeAccorsi this was based in the *archive* and *delete* behavior, but it's easy to change. Do you want that I change this for all three or just for *deprecated*?

**Comment by PhilippeAccorsi** [comment]
after discuss: just remove link about deprecated.

**Comment by LucBarry** [comment]
Verified
