### ISSUE TITLE
Its not possible to delete or archive content with button "..." visible in list of all content

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1745]
## Bug description & symptom

On tracim_rc1 if I tried to delete or archive content directly from list of all content an error appear "server unreachable" and the content app is open with refresh of tab. The content is not deleted or archived. 

## Diagnostic

*Optional - explain what has been found and what is not yet clear. If unknown, write "unknown".*

## Expected

- [ ] its possible to delete or archive content directly from list off all content like we have in tracim_2.1 (visible on https://demo.tracim.fr)

## Screenshots

![bug delete and archive](https://user-images.githubusercontent.com/25848257/57938729-076f3900-78c9-11e9-8fca-cb182b85d00d.gif)

## Impacted components

- *backend* ??
- *frontend*

**Comment by Skylsmoi** [comment]
Note that the "Edit" button in the extended action (button "...") cannot be opened in a new tab.
On chrome, it's possible with middle mouse btn click ; it might be possible with some other browser/way but it'll be browser specific behavior.

For a link to be able to open in a new tab, it has to be declared with a <a> tag.

Problem is, the content item is already a <a> tag so we can't add another one inside it in the extended action button.

**Comment by PhilippeAccorsi** [comment]
Verified.
