### ISSUE TITLE
Responsive: card about "Welcome to tracim" is under header

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1746]
## Bug description & symptom

On small screen (hight less than 585px) the card going under header so at 520px * 484px we can't see the enttire title.

## Diagnostic

*"unknown"*

## Expected

- [ ] its possible to see card correctly on small screen size

## Context and version information

- Smartphone/Tablet (if applicable)
    - *Device: LG G4*
    - *Browser opera, firefox*

## Screenshots

![z-index_card_responsive](https://user-images.githubusercontent.com/25848257/57941102-4a7fdb00-78ce-11e9-85e0-ca1e7c6ada86.gif)

## Impacted components

- *frontend*

**Comment by gbonaspetti** [comment]
I change the card height to 100% of its parent when we are in small screens.

**Comment by PhilippeAccorsi** [comment]
@gbonaspetti Something goes wrong with small size. The bottom of card is always at the same size so we can have text outside card:

![responsive_card_bug](https://user-images.githubusercontent.com/25848257/58100475-faf72300-7bdd-11e9-8953-c7800ea620a7.gif)

Try to find fix for this, speek with @Skylsmoi if you not find quick solution.
Goals => fix today for 2.2

**Comment by Skylsmoi** [comment]
this issue has been fixed in a dirty way to be able to release the 2.2.

This issue will track the proper fix: https://github.com/tracim/tracim/issues/1779

**Comment by PhilippeAccorsi** [comment]
Tested on branch => test ok (also with smartphone on firefox and safari)

**Comment by PhilippeAccorsi** [comment]
Verified on develop.
