### ISSUE TITLE
Comment render is different between text or rich mode

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#1749]
## Bug description & symptom

Write two same messages on simple text or rich text have different render.

## Diagnostic

The simple text use two break lines to render break lines. Rich text use paragraphs. And render is different.

## Expected

Result should be the same. Notice in rich text there is no more space between two line than two paragraphs. Paragraph should be more spaced.

## Context and version information

*Optional - describe the environment which reveals the bug:*

* Tracim 2.2 RC1

## How to reproduce

Write comment with three lines in simple text mode

![Sélection_037](https://user-images.githubusercontent.com/1104637/58003541-4c6db800-7ae1-11e9-8627-d7dcd7590ea2.png)

Write comment with three lines in simple html mode

![Sélection_038](https://user-images.githubusercontent.com/1104637/58003578-5abbd400-7ae1-11e9-92b5-07d6264f4ee2.png)

Render is different:

![Sélection_039](https://user-images.githubusercontent.com/1104637/58003592-60b1b500-7ae1-11e9-9a52-ef198f1f1d11.png)

## Impacted components

*For example:*

- frontend

**Comment by Quiwy** [comment]
Can't reproduce in build_088
![test_simple_advanced](https://user-images.githubusercontent.com/20048264/185621414-8bc5e876-3539-4e81-a067-09a615438bdf.gif)
