### ISSUE TITLE
cypress test is broken for pdf file since cypress use v3.3 

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1755]
## Bug description & symptom

This test `add_file__as_user_spec.js` failed, and this test just verify DropZone (not to test to upload this type of file).

## Diagnostic

Something is wrong with cypress 3.3 and POST pdf not work. POST png file works good.
Also `commands.js` need improvement.

An issue has been open on cypress itself: https://github.com/cypress-io/cypress/issues/4253

## Expected

- [x] fix cypress test

## Impacted components

- *frontend*

**Comment by lebouquetin** [comment]
@Skylsmoi @PhilippeAccorsi before to merge, please explain here the reason for cypress working with PNG files but not working with PDF. This is not an expectable behavior not to be strong on binary file content

**Comment by Skylsmoi** [comment]
see https://github.com/tracim/tracim/issues/1755

**Comment by PhilippeAccorsi** [comment]
Verified.
