### ISSUE TITLE
Sidebar responsive problem in xl screen

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#1757]
## Bug description & symptom

*Sidebar is chopped at xl screens in the Users page.*

## Expected

*Sidebar works like in other screens.*

## How to reproduce

1. *Put the screen configuration whit a width higher then 1200px*
1. *Go to Administration > Users*

## Screenshots

![SideBarUsers](https://user-images.githubusercontent.com/35422692/58015151-c9595b80-7afa-11e9-8969-6159460f61b2.png)

**Comment by gbonaspetti** [comment]
Linked to https://github.com/tracim/tracim/issues/1572.
As we can see at page 105 of Flexbox in CSS (https://books.google.fr/books?id=xwsmDwAAQBAJ&dq), the image shows that if we use flex-basis 0% we give more importance to the flex parameters grow and shrink that the content, and its works for us.
![Screenshot from 2019-05-22 14-57-01](https://user-images.githubusercontent.com/35422692/58188465-ec316e80-7cb8-11e9-8516-713169fd2789.png)
 So I change the properties deleting the lines specifics for change this at componentWillUnmount and componentDidMount.

**Comment by celiamgtt** [comment]
Verified
