### ISSUE TITLE
A notification block the click

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#1758]
## Bug description & symptom

*You can not click on nearby things while a notification is on the screen.*

## Expected

*You can click in everything that is not under the notification.*

## Screenshots

![Peek 2019-05-20 12-55](https://user-images.githubusercontent.com/35422692/58016886-26571080-7aff-11e9-8990-6c0a601ed2d7.gif)

**Comment by gbonaspetti** [comment]
As the notification width is fixed, instead of there being a div with width 100% behind it, I changed to a margin left that use the notification width in its calculation. With this the click is not blocked by the notification.

**Comment by PhilippeAccorsi** [comment]
Verified.
