### ISSUE TITLE
English don't have a white space before punctuation

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#1759]
## Bug description & symptom

*Change all English translation to not to have a white space before punctuation*

## Screenshots
*Example:*
![EnglishTranslation](https://user-images.githubusercontent.com/35422692/58017604-e8f38280-7b00-11e9-91ba-38653bbfcb58.png)

**Comment by lebouquetin** [comment]
@Skylsmoi @gbonaspetti the right way to fix this is to include punctuation in translations. Rules may change from a language to another. For example, in spanish, punctuation on short sentences is both at the beginning and at the end of sentences. See https://www.espagnolfacile.com/exercices/exercice-espagnol-2/exercice-espagnol-26703.php for some examples

**Comment by Quiwy** [comment]
@gbonaspetti : is this still relevant as we use weblate now?

**Comment by gbonaspetti** [comment]
No, I think wee can close it
