### ISSUE TITLE
Find better solution to use tg.url in wsgidav context

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#176]
When wsgidav request (webdav) generate a notification mail (ex. we update text file content), an error occured when code try to use tg.url (because tg.url can't be used in other thread than main thread).

A temporary solution is used, see "WSGIDAV.CONTEXT.TG.URL" tag in source code and fin a better solution.

**Comment by tracim** [comment]
Is this working or not ? If the temporary solution is working, then change milestone to "technical improvment"

**Comment by tracim** [comment]
Check that an email notification is sent and is correct (especially urls) when creating a file. If its ok, then close it.

**Comment by algooapy** [comment]
The temporary solution is still in place and working.

**Comment by inkhey** [comment]
tg.url is turbogears related, we use pyramid in tracim v2+.
