### ISSUE TITLE
Wrong app name in Dockerfile calendar (old name)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1763]
## Bug description & symptom

One folder is not deleted at end of docker build.

## Diagnostic

Wrong app name in dockerfile `frontend_app_calendar`=>`frontend_app_agenda`

## Expected

- [ ] change name of this app in docker

## How to reproduce

Look in docker image if folder `frontend_app_agenda/node_modules`

## Impacted components

- *backend*

**Comment by inkhey** [comment]
https://github.com/tracim/tracim/compare/fix/1763__fix_wrong_app_name_in_dockerfile
fix wrong app name issue and some other problem with docker image:
- consistent port used between documentation and docker image default config
- update webdav.base_url .

**Comment by PhilippeAccorsi** [comment]
Verified.
