### ISSUE TITLE
Creating multiple workspaces sometimes doesn't refresh the dashboard display

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1769]
## Bug description & symptom

After creating at least 2 workspaces in a row, the dashboard is sometime not refreshed and display the previously created one

## Diagnostic

It seems that after creating a new workspace, there are 2 api call to get the workspace data.
One of them asks the api for the previous one.
If the call for the previous one answers last, the dashboard will display the wrong one.

## Expected

There should be only one call to get workspace data.

## How to reproduce

Create several workspaces and check if the dashboard displays the right one

## Impacted components

Frontend

**Comment by Skylsmoi** [comment]
In the dashboard, there was a handler for a custom event that was reloading the content for the wrong workspace id.
I have removed this handler.
This handler was used to refresh the workspace data when changing the title from the app worksapce advanced so I have added a new custom event for that action.

I have also started to factorize the custom event in a file in frontend_lib

**Comment by PhilippeAccorsi** [comment]
Tested on branch => test ok.

**Comment by PhilippeAccorsi** [comment]
Verified on develop.
