### ISSUE TITLE
We not see file extension after click on See more button in recent activity

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#1774]
## Bug description & symptom

We not see file extension after See More in Recent Activity of the Dashboard. 

## Screenshots

![Peek 2019-05-21 14-21](https://user-images.githubusercontent.com/35422692/58095645-c9795a00-7bd3-11e9-9ac3-941ac0f4c771.gif)

## Expected

- [x] show file extension also for file after click on See More

**Comment by PhilippeAccorsi** [comment]
I have updated issue.

**Comment by PhilippeAccorsi** [comment]
Verified.
