### ISSUE TITLE
Wrong message to Reader user

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#1776]
## Bug description & symptom

*If the user has Reader role at a empty dashboard and he goes to List of contents, there is the message "This shared space has no content yet, create the first content by clicking on the button 'Create'" even if there isn't the button 'Create' to a Reader.*

## Screenshots

![Screenshot from 2019-05-21 14-49-26](https://user-images.githubusercontent.com/35422692/58097714-51f9f980-7bd8-11e9-906d-3f2c5182093b.png)

**Comment by gbonaspetti** [comment]
I change the message to just show the second part if you are not a Reader.

**Comment by PhilippeAccorsi** [comment]
Message for reader is not show directly all the time. sometime we can see the default message before the message for reader.

After discuss: @gbonaspetti check if its possible to not show default message before specific message for reader.

**Comment by gbonaspetti** [comment]
After all, I think it's not so easy to fix this.

**Comment by PhilippeAccorsi** [comment]
So this issue is correctly fix.
Verified.
