### ISSUE TITLE
Sidebar breaks in Administration when we have a big description for a Shared space

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#1781]
## Bug description & symptom

*If we put a big description for a shared space and we go to Administration > Shared space, the sidebar it's broken (see the gif).*

## How to reproduce

1. *Put a big description to a shared space*
2. *Go to Administration > Shared space*

## Screenshots

![Peek 2019-05-21 17-04](https://user-images.githubusercontent.com/35422692/58108073-6eebf800-7beb-11e9-85af-6f8a6bae7592.gif)

**Comment by gbonaspetti** [comment]
I've limited the description and title width in *Administration > Shared* spaces and added ellipses if the height exceeds one line.

**Comment by PhilippeAccorsi** [comment]
This is not working, text is visible just in one line.

**Comment by gbonaspetti** [comment]
Apparently, it is necessary to have a max-width in order for the ellipsis to work within a table. So, I added max-width 0

Information taken from here: https://stackoverflow.com/questions/9789723/css-text-overflow-in-a-table-cell

**Comment by LucBarry** [comment]
Verified

**Comment by LucBarry** [comment]
Verified
