### ISSUE TITLE
Split cypress test switch app feature

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1783]
## Bug description & symptom

this test keeps failing for some reason

## Diagnostic

the fail seems to occurs in the before each hook so splitting it might resolves it

## Expected

it pass

**Comment by PhilippeAccorsi** [comment]
This fix seem to be working. 
Test in progress in this branch `fix/1769__creating_workspace_doesnt_display_right_data_in_dashboard`

**Comment by Skylsmoi** [comment]
a solution has been found.
The test doesn't randomly fails anymore.
I'm closing this issue
