### ISSUE TITLE
UX change the warning when add a member who is already in the shared space

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#1789]
## Bug description & symptom

*At the time, if we try to add a member who is already in the shared space we see a message "Unknown user" instead of "This user already is in the shared space". 
This can be a UX problem especially if the shared space has a lot of members and it's not practical to see if the user is already there.*

## Expected

*A more specific message.*

## Screenshots

![Peek 2019-05-22 15-02](https://user-images.githubusercontent.com/35422692/58179386-63123b80-7ca8-11e9-915e-56638b2255e0.gif)

## Extra information

*There is a similar message already in the translation files.*

**Comment by lebouquetin** [comment]
TODO @Skylsmoi investigate the exact origin of the issue.

**Comment by metzgegu** [comment]
This bug appear only when email notification is disabled,
Indeed the endpoint `/users/{user_id:\d+}/known_members` doesn't return anything if the user is already in the current workspace, so when validating the form it check first if this endpoint find someone, if not: the error `Unknown user` is displayed and the POST is canceled.

When email notification is enabled, POST `/workspaces/${workspaceId}/members` will return a code 3008 if the user is already in the current workspace.

**Comment by PhilippeAccorsi** [comment]
Ok, so its a backend issue.
Thanks for your investiguation.

**Comment by Quiwy** [comment]
@gbonaspetti : is this bug still existing?

I could not reproduce it
![add_already_existent](https://user-images.githubusercontent.com/20048264/181012221-5d7ba88f-7ce6-4ae8-9b07-bd1ff80a6ad3.gif)

**Comment by gbonaspetti** [comment]
I think it was fixed, I'll close the issue.
