### ISSUE TITLE
breadcrumb is not correctly updated when you change language in interface

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1799]
## Bug description & symptom

If I change language the breadcrumb is updated, but we lost label of opened content.

## Diagnostic

*"unknown"*

## Expected

- [ ] if content is open, breadcrumb show label of this content

## How to reproduce

- open one content
- switch lang
- => breadcrumb is updated (with good translation), label of content is not visible.

## Screenshots

![bug_breadcrumb_when_update](https://user-images.githubusercontent.com/25848257/58259837-a5ee1500-7d75-11e9-86d1-af9cd58d50e5.gif)

## Impacted components

- *frontend*

**Comment by PhilippeAccorsi** [comment]
Still exist in 2.7.2
I have ssen also something wrong because breadcrumb show me something very wrong. First I'm going in admin user and I see one user profile. So now, when I tried this issus, end of breadcrumb show me name of user profile.

Example:
- `Home > Algoo -Philippe > All contents > Bonnes pratiques d'utilisation des documents`
- change language to french
- `Accueil > Algoo -Philippe > Tous les contenus > Alexi`
=> if I click on `Alexi`, I'm going directly to `Accueil > Administration > Utilisateurs > Alexi`

Why frontend save this path ? Because to open my document, I have openning all content list of one shared space first, so..........

**Comment by Quiwy** [comment]
@PhilippeAccorsi : I think this is not relevant anymore as language is selected in "account settings" and not in header anymore.
Do you confirm it?

**Comment by PhilippeAccorsi** [comment]
Yes. I close this issue because we can't change anymore the language without recharging page.
