### ISSUE TITLE
Unexpected space at the bottom of the screen

### ISSUE THREAD

**Issue by celiamgtt** [tracim/tracim#1802]
## Bug description & symptom

Unexpected space at the bottom of the screen (under sidebar & content space) when the screen is 990 px width or less. 

## Diagnostic

"unknown"

## Expected 

- [ ] Screen/content should be at full height.

## Context and version information

Noticed on Chrome & Firefox browser.

- Desktop environment
    - Chrome, Firefox
- Smartphone/Tablet
    - to test
    - bug doesn't exist with the progressive web app

## Screenshots

![bug_space](https://user-images.githubusercontent.com/50453784/58312394-7ab60500-7e0b-11e9-9851-e5e350e25d0e.png)

## Impacted components

- *frontend*

**Comment by PhilippeAccorsi** [comment]
Verified.
