### ISSUE TITLE
improve travis testing with specific parameter in commit message

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1807]
## Feature description

Add some parameter in travis to test just backend or frontend when is it necessary.

## Context

At present travis test backend and frontend for each commit. If we add `[skip ci]` travis is not started. We need to make travis more quick if we push just frontent commit (for test before MR) or just backend.

## Prerequisites

Some good documentation/idea:
~~~
Build only when the commit message matches against the given regular expression:
    commit_message !~ /(no-deploy|wip)/
~~~
https://docs.travis-ci.com/user/conditions-v1
With that we can activate just backend or just frontend stage if other stage is not necessary. Exemple: if we add [frontend] in commit message, travis just start stage for frontent. We can save lot of time with this.

https://docs.travis-ci.com/user/build-stages/
https://docs.travis-ci.com/user/conditional-builds-stages-jobs/
https://docs.travis-ci.com/user/conditions-testing

## Impacted components

- *backend*
- *frontend*

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi @basilelegal @inkhey @buxx @lebouquetin 
Do you think its a good idea to look in this direction to see if its possible to save some time when we push some commit ?

**Comment by buxx** [comment]
Yes i think so.

**Comment by PhilippeAccorsi** [comment]
To fix this we have added this possibility:

- skip cypress test by adding [skip ci cypress] in commit message
- skip pytest test by adding [skip ci pytest] in commit message

**Comment by PhilippeAccorsi** [comment]
Verified.
