### ISSUE TITLE
Switching from app agenda to app agenda of another workspace doesn't work

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1811]
## Bug description & symptom

1) When you switch from a workspace's agenda to another workspace's agenda, the agenda isn't refreshed

2) Workspace agenda isn't full screen

## Diagnostic

It seems to be a refresh issue

## Expected

The workspace's agenda displayed is always the agenda of the workspace id in url

## Context and version information

Bug visible in 2.2

## Prerequisites

Have 2 workspaces with agenda activated

## How to reproduce

Open a workspace's agenda, click on another workspace's agenda

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi make a fix for this issue in priority.
We need to fix this for release_2.2.1

**Comment by gbonaspetti** [comment]
Verified.
