### ISSUE TITLE
Config SQLALCHEMY__URL should be mandatory

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#1812]
## Bug description & symptom

If `sqlalchemy.url` is not set, Tracim start. But crash with non explicit error.

## Diagnostic

This parameter should be considered as required at config initialization.

## Expected

Explicit error should be raised if config not provided OR (discuss it) use a default sqlite.

## Context and version information

All Tracim versions

## Prerequisites

no one

## How to reproduce

Remove `sqlalchemy.url`  config and start Tracim.

## Impacted components

*Optional - list components which will be impacted.*

*For example:*

- *backend*

**Comment by inkhey** [comment]
@buxx i do think, we should return an error.
This was problematic before as sqlalchemy_url wasn't a true "tracim parameter". That's now ok, so we can add mandatory mecanism like other parameter.
We should discuss if we want to have similar mecanism for alembic, which mean some specific code in alembic part.

**Comment by Skylsmoi** [comment]
I'm seeing this error `tracim_backend.exceptions.ConfigurationError: ERROR: "SQLALCHEMY__URL" configuration is mandatory .Set it before continuing.`

I find it explicit enough.
Although there is a punctuation typo around the dot
