### ISSUE TITLE
avatar and name about last change in content timeline is not the name of present user when status is changed

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1815]
## Bug description & symptom

When we change status the name of author of this change is not the present user but the author of this content.

## Expected

- [ ] show the name of user who changed the status of content
 
## How to reproduce

- open one content created by another user
- change its status
- look at the name of user who changed the status

## Impacted components

- *backend*

**Comment by inkhey** [comment]
This bug concern : 
- move
- copy
- change status

After rapid check, that's a backend bug. Setting of owner of revision is not done in those case, so owner remain same as latest.

**Comment by lebouquetin** [comment]
@PhilippeAccorsi you write that backend and frontend are impacted. Could you check directly in the API if the returned information is good. If so, then the issue is frontend, if info is wrong, then the only impacted component is backend

**Comment by PhilippeAccorsi** [comment]
I have updated issue (just backend issue)

@inkhey all situations:

- create
- delete
- restore delete
- archive
- restore archive
- status
- label
- edit / description / raw content
- update file
- move
- copy
- comment

**Comment by gbonaspetti** [comment]
Verified.
