### ISSUE TITLE
edit app folder not working correctly when you switch from one folder to another one. Refresh issue

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1818]
## Bug description & symptom

When I edit one folder in one workspace and after that I close app folder to open another one I can see the first folder I have opened. If I look in dev tool, I can see the same request about first folder.

## Diagnostic

*Optional - explain what has been found and what is not yet clear. If unknown, write "unknown".*

## Expected

- [x] the good folder is opened when you click on edit

## How to reproduce

- Go inside shared space with more than one fodder
- click on edit button in "..." of one folder
- App folder is opened and you can edit this folder
- close this app
- click on edit button in "..." of one another folder
=> App folder is opened but you can edit the last folder and not the new one

## Screenshots

![refresh_edit_folder](https://user-images.githubusercontent.com/25848257/58477674-65671080-8154-11e9-9d0d-de90d621fba8.gif)

## Impacted components

- *frontend*

**Comment by celiamgtt** [comment]
Verified
