### ISSUE TITLE
Make Index pattern and index alias name as true tracim config param

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1835]
## Bug description & symptom

Currently we have 2 env_var-only params:
- `TRACIM_SEARCH__ELASTICSEARCH__INDEX_ALIAS`
- `TRACIM_SEARCH__ELASTICSEARCH__INDEX_PATTERN_TEMPLATE`

Those should be tracim config params.
This is currently not possible because it mean that class IndexedContent should be not static anymore and we have some kind of context info with this that we share accross some Lib in internal api (we need not static IndexedContent in SearchApi, and we currently user SearchApi in ContentApi due to lack of event mecanism #1487)

## Expected

- Wait  #1834 (and  maybe #1487 fix)
- Refactor SearchApi (and maybe ContentApi) to allow IndexedContent class as parameter (or something which contained it. 
- make IndexedContent  class as generated on the fly (not static anymore)
- Convert TRACIM_SEARCH__ELASTICSEARCH__INDEX_ALIAS and TRACIM_SEARCH__ELASTICSEARCH__INDEX_PATTERN_TEMPLATE to tracim config params.

**Comment by PhilippeAccorsi** [comment]
Verified.
