### ISSUE TITLE
update changelog / doc / tracim version before tag 2.3

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1838]
## expected

- [x] changelog is up-to-date
- [x] explain website.server_name deprecated
- [x] small description in changelog to know how or where you find documentation about nes feature
- [x] small description to activate agenda after migration
- [x] version of tracim is visible in /api/v2/doc/  is in this file `system_controller.py`
- [x] Update version of tracim front in `frontend/src/version.json`

**Comment by Skylsmoi** [comment]
known limitation to add for v2.3:
- Debian 9 is released with Firefox ESR v60.x.x. In this version, there is a known bug with the drag & drop feature: when hovering a content over a workspace in the sidebar, only the first one gets to have its icon updated.

**Comment by PhilippeAccorsi** [comment]
Verified.
