### ISSUE TITLE
add frontend/backend version of tracim readable for all user 

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1841]
## Feature description

- [ ] Add possibility for basic user to know exactly which version of tracim is running. 
- [ ] Add possibility for advanced user to know exactly which version of each server/app/etc is running

For example:
- basic user see "tracim 2.3" just near copyright
- advanced user can see:
  - frontend version
  - backend version
  - app folder version
  etc.

## Context

At present is not easy to know exactly which version is running on client server. When user need some help, its difficult to know if user use tracim 2.0 or the last one.

## Prerequisites

*Optional - if some other issues must be closed before the current, list them here.*

- *#xxx*
- *...*

## Impacted components

*Optional - list components which will be impacted.*

*For example:*

- *backend*
- *frontend*
- *htmldoc / file / thread app*
- *webdav*
- *...*

*If unsure, write "unknown"*

**Comment by PhilippeAccorsi** [comment]
**damien_accorsi 11:55**
il faut à mon avis un numéro de version frontend, un numéro backend, et les tags git associés (et potentiellement un numéro de version par app)
et qu'on ait possibilité d'avoir les id de commit git

**damien_accorsi 11:57**
oui ; je pense qu'il faut une version sur l'ihm qui soit écrite dans l'ihm (au moment du transpiling)

**damien_accorsi 11:59**
pour la première version on va faire encore plus simple (pas pris dans l'api mais écrit en dur dans le code frontend)

**Comment by PhilippeAccorsi** [comment]
Vu que l'api est déjà capable de retourner un numéro de version, on peut aussi déjà avoir dans l'IHM ce numéro de version au lieu d'écrire le numéro en dur dans le front.

**Comment by Quiwy** [comment]
@PhilippeAccorsi : not sure this is relevant anymore, any thought?

**Comment by PhilippeAccorsi** [comment]
This is done. But I don't find any information about that in changelog or issue.
