### ISSUE TITLE
smartphone: when I open tracim, if flash message about "you are disconnected...." is show, I can't see all flash message.

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1843]
## Bug description & symptom

When I open tracim on my smartphone, sometime I can see flash message about disconnected from last session. In this case the flash message is not entirely visible.

## Diagnostic

*Optional - explain what has been found and what is not yet clear. If unknown, write "unknown".*

## Expected

- [ ] responsive working for all flash message

## Context and version information

- Smartphone/Tablet (if applicable)
    - *Device: LG G4*
    - *OS: ANDROID*
    - *Browser FIREFOX*

## How to reproduce

- open one tab with tracim
- login to tracim
- open another tab
- disconnect from this tab 
- refresh first tab

## Impacted components

- *frontend*

**Comment by gbonaspetti** [comment]
I changed the warning width to be 100% of the screen in small screens.

**Comment by LucBarry** [comment]
Verified
