### ISSUE TITLE
add version of tracim directly in frontend code (visible on top of copyright)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1844]
## Feature description

Its possible to know wich version of tracim is used.

## expected

- [ ] add version of tracim directly on top of copyright. Center this information.

## Context

At present its not easy to know if client use last version of tracim or not.

## Impacted components

- *frontend*

## Extra information

For the moment its just a small fix in frontend.
One API exist but the API not return all information correctly for the moment, so we need to fix this quickly for tracim 2.3   
In the futur, this value need to be changed dynamicaly.

**Comment by PhilippeAccorsi** [comment]
We need to define what is the good solution first to fix this quick without loss time when we make final solution.

**Comment by lebouquetin** [comment]
The goal is to have a constant used in frontend which is easy to update without risk of breaking the code.

**Comment by celiamgtt** [comment]
Working, but the current version displayed is 2.2 instead of 2.3

**Comment by celiamgtt** [comment]
We'll change the version later in the process.
