### ISSUE TITLE
the name of workspace in app agenda is not show correctly if special character exist in name of workspace

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1847]
## Bug description & symptom

If I add special character in name of workspace, this character is not correctly show when I see agenda of this workspace.

## Diagnostic

*Optional - explain what has been found and what is not yet clear. If unknown, write "unknown".*

## Expected

- [x] all spacial character is show correctly in name of sharedspace visible in his own agenda

## How to reproduce

- create one workspace `totot'`
- open agenda of this workspace
=> the title of this agenda is "Agenda of shared space totot&#39;"

## Screenshots

![bug_name_sharedspace_agenda](https://user-images.githubusercontent.com/25848257/58944792-cc9f4900-8782-11e9-9bcc-1d68b6d0ff40.gif)

## Impacted components

- *frontend*

**Comment by gbonaspetti** [comment]
I changed all variables in the translation files because i18next do not handle special characters and did a function when necessary to handle the phrases order that change depending of the language.

**Comment by celiamgtt** [comment]
Verified
