### ISSUE TITLE
An administrator can manage the account of an user but can't see personal link for agenda (same for the administrator's own account)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1855]
## Bug description & symptom

An administrator can edit user account (from Administration > user), he can change public name, password, email, activate/deactivate notification but he can't see link about personnal agenda

## Expected

- [x] administrator can see agenda menu in user account

## How to reproduce

- open Administration > users
- click on one name
=> user account is opened but you can't see agenda menu

## Screenshots

![agenda_not_visible_for_admin](https://user-images.githubusercontent.com/25848257/58961484-84dfe800-87a9-11e9-9f5d-20137c5637e7.gif)

## Impacted components

- *frontend*

**Comment by gbonaspetti** [comment]
@PhilippeAccorsi @celiamgtt @Skylsmoi @lebouquetin  
To be more coherent, in this situation I think it is good to replace the phrase "Use this link to integrate this agenda to your CalDAV compatible software" with "This agenda is private, to access it you will need the user's credentials." or something like that. What do you think ?

**Comment by Skylsmoi** [comment]
I think we don't want administrators to be able to see a user's agenda because, as you said, it's private.
So we might not even have to say "you need credentials", we can just say:
"The user's agenda is private, you cannot see it."

**Comment by PhilippeAccorsi** [comment]
I'm not sure about what you explain.
An administrator need to know the path of user agenda. Its not to see user agenda but to communicate this link to the user.

**Comment by celiamgtt** [comment]
Administrators are already able to chose user's password, I think it's useful if an administrator has to help users with their agendas.

**Comment by PhilippeAccorsi** [comment]
> I'm not sure about what you explain.
> An administrator need to know the path of user agenda. Its not to see user agenda but to communicate this link to the user.

This is for user support. For example, you not have access to the webbrowser, but you want to add your agenda in thunderbird or in your smartphone.

**Comment by Skylsmoi** [comment]
yes, I didn't express myself properly.
I did not mean to hide the url, just saying that it's private and that he cannot open it.
Indeed, if he changes his password he will be able, but I'd say it's an advanced feature. It can be document but I don't think we need to explain it in the ui

**Comment by gbonaspetti** [comment]
I think we all agree that the phrase "Use this link to integrate this agenda to your CalDAV compatible software" is not appropriate for this context. My suggestion is "This link is for the user's private agenda, only _user_name_ will have access to the agenda itself".

**Comment by Skylsmoi** [comment]
I like your second proposition better

**Comment by PhilippeAccorsi** [comment]
> I think we all agree that the phrase "Use this link to integrate this agenda to your CalDAV compatible software" is not appropriate for this context. My suggestion is "This link is for the user's private agenda, only _user_name_ will have access to the agenda itself".

I'm not sure is necessary to change this. For exemple, an administrator can see (in user profile) this kind of message about the shared space `You are not a member of any shared space yet`.

An administrator says is not is own profile. For me its not necessary to change title. But if we change title, I think we need to update issue and change all other not explicit title.

**Comment by gbonaspetti** [comment]
> I'm not sure is necessary to change this. For exemple, an administrator can see (in user profile) this kind of message about the shared space `You are not a member of any shared space yet`.
> 
> An administrator says is not is own profile. For me its not necessary to change title. But if we change title, I think we need to update issue and change all other not explicit title/message.

Yes, the idea was to reach a consensus with you before changing the issue. 
I still don't love the phrase in that context, but I can see it's not necessarily a problem... I'll do the PR with the current phrase then :) 

Thank you all for your feedbacks.

**Comment by gbonaspetti** [comment]
So, the solution made in PR was to create a function to get the agenda url of a specific user (option already existed in the backend) and update the view of Admin to see the agendas.

**Comment by metzgegu** [comment]
Verified on branch (wait merge to close).
