### ISSUE TITLE
Its not possible to use environnement variable TRACIM_XXXXX with docker image and service

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#1860]
## Bug description & symptom

Without docker I can export some variable and this variable is used to replace value in development.ini

This is not working with tracim docker image because tracim is not started with pserve but as a service. This service do not use env variable.

## Diagnostic

- ENV VARS given to docker run command are not "forwarded" to the uwsgi service. This is a "normal" behavior, this is what must be fixed.

## Expected

- [ ] ~~make sure its not possible to use env variable like we used with pserve~~
- [ ] ~~find solution to use env variable with service (maybe create file with all variable detected whend docker start and give this variable to each service)~~
- [ ] I (@lebouquetin ) suggest to add a rule in the docker start script which forward all TRACIM_xxx environment variables to all tracim daemon processes.

## Prerequisites

Verify if its not possible to use docker env variable with service

## How to reproduce

start docker image with `-e TRACIM_WEBSITE__TITLE=ahahah` and check if site title change.
Go in container and start pserve. Now you can see tracim use `ahahah` in config.

## Impacted components

- dockerfile

**Comment by lebouquetin** [comment]
@PhilippeAccorsi can you organize a meeting on friday morning with I, @buxx and @inkhey ? 30 minutes should be enough

**Comment by PhilippeAccorsi** [comment]
Idea for docker and services:

we can do `printenv > /var/data/env_variable` when starting image and make a link to this file in uwsgi service and in supervisord.

With that, all env_variable is available all the time also if you restart container.

**Comment by PhilippeAccorsi** [comment]
With this is more explicit to just use specific variable for config

`printenv |grep TRACIM > env_varaible`

**Comment by PhilippeAccorsi** [comment]
Solution :

`printenv |grep TRACIM > /env_variable`

and in uwsgi file

~~~
for-readline = /env_variable
  env = %(_)
endfor = 
~~~


With that, variable is used correctly when tracim running

**Comment by PhilippeAccorsi** [comment]
Solution for uwsgi https://github.com/unbit/uwsgi/issues/629

**Comment by PhilippeAccorsi** [comment]
Supervisord working correctly with env variable available directly in container.

**Comment by PhilippeAccorsi** [comment]
After discuss with @buxx we add the fix for he moment with just one file with env variable for all uwsgi services. All service used the same list of env variable so its not really necessary to have one file per service.

**Comment by PhilippeAccorsi** [comment]
Verified.
