### ISSUE TITLE
End point move content returns 500 when trying to move a content into itself

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1866]
## Bug description & symptom

sending to the api this request:
`/api/v2/workspaces/3/contents/14/move`
with this body:
`{"new_workspace_id":3,"new_parent_id":14}`

returns error 500:
`{"details": {"error_detail": {}}, "code": null, "message": "maximum recursion depth exceeded while getting the str of an object"}`

## Expected

- [ ] I would assume a 400 with a specific error code
- [ ] add an API test case (this is a border which will not be tested often if not auto-tested)

## How to reproduce

curl:
```
curl 'http://192.168.1.153:6543/api/v2/workspaces/3/contents/14/move' -X PUT -H 'Pragma: no-cache' -H 'Origin: http://192.168.1.153:8090' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Cache-Control: no-cache' -H 'Referer: http://192.168.1.153:8090/ui/workspaces/3/contents?folder_open=15,13,14,19' -H 'Cookie: defaultLanguage=fr; lastConnection=1; session_key=d9d7fb1b170383c67fea5f933898fe34d419f1f16a62f22f5bef43b0b1501f1f06c1797b' -H 'Connection: keep-alive' --data-binary '{"new_workspace_id":3,"new_parent_id":14}' --compressed
```

Note that it was taken from a development server

## Impacted components

Backend API

## Extra information

Frontend will do the necessary to avoid to be able to send such request that makes no sens

**Comment by Skylsmoi** [comment]
Note that the same occur if you try to move a folder in one of its subfolder

**Comment by lebouquetin** [comment]
This is another border case to test (especially when moving to an indirect child).
@Skylsmoi you implement the check on frontend, right? (to avoid this case even without to send a request)

**Comment by Skylsmoi** [comment]
Mmh I didn't plan to since I only have the immediate parent id for a given content.
But I can

**Comment by tracim** [comment]
You must check this. You have all content available for checking this (you can just make a recursive call for this to check «on mouseover»)

**Comment by gbonaspetti** [comment]
Verifed.
