### ISSUE TITLE
Use  tracim_backend.models.roles.WorkspaceRoles instead of int in get_user_workspaces_ids

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1876]
## Bug description & symptom

Why not use `tracim_backend.models.roles.WorkspaceRoles` type for `min_role` parameter ?

_Originally posted by @buxx in https://github.com/tracim/tracim/pull/1717_

## Expected

Use  `tracim_backend.models.roles.WorkspaceRoles` instead of int in **get_user_workspaces_ids**

**Comment by buxx** [comment]
I opened #1881 (more general refactor)
