### ISSUE TITLE
Email with password : improve user experience

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#188]
Currently, when a user is created with no password, a random password is generated in the form of a uuid.
This is bad for user experience, because : 

- the user can't copy/paste it by double-click (because of dashes)
- triple click selects the entire line (including text before the password)
- select using the mouse will most of the time also select the blank space at the end.

Todo:
- generate a "more common" password : letters (upper/lower case), numbers, special chars (but not the ones breaking double-click select)

**Comment by xandercagexxx** [comment]
verified. Ubuntu 17.04
