### ISSUE TITLE
rename is_deleted_by_parent_id and is_archived_by_parent_id to something else

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1880]
## Bug description & symptom

name of these 2 parameters, used in indexing and content_in_context model is not clear enough.
Those parameters are not yet returned by any rest api endpoint.

origins:

`is_xxx` function must return `bool`. Rename function or change return type.

_Originally posted by @buxx in https://github.com/tracim/tracim/pull/1717_

`is_xxx` function must return `bool`. Rename function or change return type.

_Originally posted by @buxx in https://github.com/tracim/tracim/pull/1717_

## Expected

?

**Comment by buxx** [comment]
Original remark is [here](https://github.com/tracim/tracim/pull/1717#discussion_r291520595)

**Comment by lebouquetin** [comment]
@inkhey try to rename the attributes to:

- deleted_through_parent_id
- archived_through_parent_id

Also try to use 0 as default value (meaning  not deleted / not archived).

If easy, then put the fix in your MR and close this issue by telling it is already fixed

**Comment by inkhey** [comment]
done in #1717

**Comment by PhilippeAccorsi** [comment]
For testing : merge elastic search first.

**Comment by basilelegal** [comment]
tested.
