### ISSUE TITLE
ES models must be loaded only at execution

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#1892]
## Currenlty

When `backend/tracim_backend/lib/search/es_models.py` module is loaded, `TRACIM_SEARCH__ELASTICSEARCH__INDEX_ALIAS` env var is required and an error is raised if not.

Import `backend/tracim_backend/lib/search/search.py` was importing `backend/tracim_backend/lib/search/es_models.py` so `TRACIM_SEARCH__ELASTICSEARCH__INDEX_ALIAS` was always required.

These imports have been moved in methods to protect against this error.

## Expected

As required in  #1835 this environment variable will be not required. After that, these imports can be moved on top of file.

**Comment by raphj** [comment]
This seems solved, closing.
