### ISSUE TITLE
Add role of user in endpoint /api/v2/users/me/workspace

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1897]
## Feature description

Currently, the only way to get a user's role in a workspace is the endpoint `/api/v2/workspace/:id/members`.
I need that information in each workspaces returned by `/api/v2/users/me/workspace`

## Context

Since the drag & drop feature, I need the role for every workspace returned by the endpoint `/api/v2/users/me/workspace`. And my only way of doing that is to call `/api/v2/workspace/:id/members` for each workspaces

## Impacted components

Backend Api

## Extra info

When this issue is merged, notify frontend dev to do the necessary

## Linked PR
PR ref #5658

**Comment by Skylsmoi** [comment]
This issue is planed for v2.4

**Comment by Haskaris** [comment]
Closing this issue since:
- An endpoint to retrieve the member role is already existing: `workspace/<id>/members/<id>`
- This breaks the REST API
