### ISSUE TITLE
Improve path lisibility in search results

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#1904]
## Bug description & symptom

Search results are currently like first item in the screenshot below :

![image](https://user-images.githubusercontent.com/907161/59368196-fdacea00-8d3d-11e9-801d-071ad4495a37.png)

## Expected

- [x] Separate shared space from folders path with a `>`
- [x] Add spaces around `/`

## Extra information

Other improvments have been suggested but did not make everbody happy:

- showing path in a lighter color (the file name and the workspace are important informations, path is secondary)
- showing path in a smaller font size (same reason)

**Comment by LucBarry** [comment]
Verified
