### ISSUE TITLE
Fix Tracim license (from list of all dependencies)

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1908]
## Bug description & symptom

Current "official" tracim license is MIT. Unfortunately, it's not compatible with all dependencies (eg a modified version of caldavzap is integrated, this part is not compatible with distributing tracim under MIT licence).

We should list here, all dependencies licences

## Expected

- [ ] list all python (backend) dependencies
- [x] list all javascript/css/html (frontend) dependencies
- [ ] list all system dependencies

Then 

- [ ] Adapt tracim licence according to all the licenses.

**Comment by inkhey** [comment]
## Backend Python:

Sync package with requirements
`
pip-sync requirements.txt
`
Install pip-licences:
`
pip install pip-licenses
`

Get licenses from default tracim (pip install -e ".[dev,testing, mysql, postgresql]"
`pip-licenses --format=csv --from=mixed > licences.csv`

```
"Name","Version","License"
"Babel","2.6.0","BSD License"
"Beaker","1.10.0","BSD License"
"Click","7.0","BSD License"
"IMAPClient","2.1.0","BSD License"
"Jinja2","2.10","BSD License"
"Mako","1.0.7","MIT"
"Markdown","3.0.1","BSD License"
"MarkupSafe","1.1.0","BSD License"
"PasteDeploy","2.0.0","MIT License"
"Pillow","5.3.0","Other/Proprietary License"
"PyPDF2","1.26.0","BSD License"
"PyYAML","3.13","MIT License"
"Pygments","2.3.0","BSD License"
"Radicale","2.1.11","GNU General Public License (GPL)"
"SQLAlchemy","1.2.14","MIT License"
"Unidecode","1.0.23","GNU General Public License v2 or later (GPLv2+)"
"Wand","0.4.5","MIT License"
"WebOb","1.8.4","MIT License"
"WsgiDAV","2.4.1","MIT License"
"alembic","1.0.5"Other/Proprietary License"
"PyPDF2","1.26.0","BSD License"
"PyYAML","3.13","MIT License"
"Pygments","2.3.0","BSD License"
"Radicale","2.1.11","GNU General Public License (GPL)"
"SQLAlchemy","1.2.14","MIT License"
"Unidecode","1.0.23","GNU General Public License v2 or later (GPLv2+)"
"Wand","0.4.5","MIT License"
"WebOb","1.8.4","MIT License"
"WsgiDAV","2.4.1","MIT License"
"alembic","1.0.5","MIT"
"apispec","1.1.0","MIT License"
"apispec-marshmallow-advanced","0.4","MIT License"
"attrs","18.2.0","MIT License"
"beautifulsoup4","4.6.3","MIT License"
"caldav","0.6.0","GNU General Public License (GPL), Apache Software License"
"certifi","2018.11.29","Mozilla Public License 2.0 (MPL 2.0)"
"chardet","3.0.4","GNU Library or Lesser General Public License (LGPL)"
"cliff","2.14.0","Apache Software License"
"cmd2","0.9.6","MIT License"
"colorama","0.4.1","BSD License"
"colour","0.1.5","BSD License"
"defusedxml","0.5.0","Python Software Foundation License"
"elasticsearch","7.0.1","Apache Software License"
"elasticsearch-dsl","7.0.0","Apache Software License"
"email-reply-parser","0.5.9","MIT"
"filedepot","0.5.2","MIT"
"filelock","3.0.10","License"
"hapic","0.77","MIT"
"hupper","1.4.2","MIT License"
"idna","2.8","BSD License"
"jsmin","2.2.2","MIT License"
"ldap3","2.5.1","GNU Lesser General Public License v3 (LGPLv3)"
"lxml","4.2.5","BSD License"
"marshmallow","2.16.3","MIT License"
"multidict","4.5.2","Apache Software License"
"packaging","18.0","Apache Software License, BSD License"
"pathlib","1.0.1","MIT License"
"pbr","5.1.1","Apache Software License"
"pdf2image","1.1.0","MIT License"
"pip-tools","3.7.0","BSD License"
"plaster","1.0","MIT License"
"plaster-pastedeploy","0.6","MIT License"
"prettytable","0.7.2","BSD License"
"preview-generator","0.10","UNKNOWN"
"pyasn1","0.4.4","BSD License"
"pyexifinfo","0.4.0","GNU General Public License v3 or later (GPLv3+)"
"pyparsing","2.3.0","MIT License"
"pyperclip","1.7.0","BSD License"
"pyramid","1.10.1","Repoze Public License"
"pyramid-beaker","0.8","BSD-derived (http://www.repoze.org/LICENSE.txt)"
"pyramid-debugtoolbar","4.5","Repoze Public License"
"pyramid-jinja2","2.7","Repoze Public License"
"pyramid-ldap3","0.4","Repoze Public License"
"pyramid-mako","1.0.2","Repoze Public License"
"pyramid-multiauth","0.9.0","Mozilla Public License 2.0 (MPL 2.0)"
"pyramid-retry","1.0","MIT License"
"pyramid-tm","2.2.1","Repoze Public License"
"python-dateutil","2.7.5","BSD License, Apache Software License"
"python-editor","1.0.3","Apache Software License"
"python-magic","0.4.15","MIT License"
"python-slugify","1.2.6","MIT License"
"pytz","2018.7","MIT License"
"redis","2.10.6","MIT License"
"repoze.lru","0.7","Repoze Public License"
"requests","2.21.0","Apache Software License"
"rq","0.12.0","BSD License"
"six","1.11.0","MIT License"
"stevedore","1.30.0","Apache Software License"
"transaction","2.4.0","Zope Public License"
"translationstring","1.3","BSD-like (http://repoze.org/license.html)"
"tzlocal","1.5.1","MIT License"
"urllib3","1.24.1","MIT License"
"venusian","1.1.0","BSD-derived (http://www.repoze.org/LICENSE.txt)"
"vobject","0.9.6.1","Apache Software License"
"waitress","1.1.0","Zope Public License"
"wcwidth","0.1.7","MIT License"
"xvfbwrapper","0.2.9","MIT License"
"zope.deprecation","4.3.0","ZPL 2.1"
"zope.interface","4.6.0","Zope Public License"
"zope.sqlalchemy","1.0","Zope Public License"
```

install all optionals packages :
`pip install -e ".[dev,testing, mysql, postgresql]"`

get all licenses:
` pip-licenses --format=csv --from=mixed > licences_with_optionals_deps.csv`


"Name","Version","License"
"Babel","2.6.0","BSD License"
"Beaker","1.10.0","BSD License"
"Click","7.0","BSD License"
"IMAPClient","2.1.0","BSD License"
"Jinja2","2.10","BSD License"
"Mako","1.0.7","MIT"
"Markdown","3.0.1","BSD License"
"MarkupSafe","1.1.0","BSD License"
"PasteDeploy","2.0.0","MIT License"
"Pillow","5.3.0","Other/Proprietary License"
"PyMySQL","0.9.3","MIT License"
"PyPDF2","1.26.0","BSD License"
"PyYAML","3.13","MIT License"
"Pygments","2.3.0","BSD License"
"Radicale","2.1.11","GNU General Public License (GPL)"
"SQLAlchemy","1.2.14","MIT License"
"Unidecode","1.0.23","GNU General Public License v2 or later (GPLv2+)"
"Wand","0.4.5","MIT License"
"WebOb","1.8.4","MIT License"
"WebTest","2.0.33","MIT License"
"WsgiDAV","2.4.1","MIT License"
"alembic","1.0.5","MIT"
"apispec","1.1.0","MIT License"
"apispec-marshmallow-advanced","0.4","MIT License"
"appdirs","1.4.3","MIT License"
"aspy.yaml","1.3.0","MIT License"
"atomicwrites","1.3.0","MIT License"
"attrs","18.2.0","MIT License"
"beautifulsoup4","4.6.3","MIT License"
"black","19.3b0","MIT License"
"caldav","0.6.0","GNU General Public License (GPL), Apache Software License"
"certifi","2018.11.29","Mozilla Public License 2.0 (MPL 2.0`)"
"cfgv","2.0.0","MIT License"
"chardet","3.0.4","GNU Library or Lesser General Public License (LGPL)"
"cliff","2.14.0","Apache Software License"
"cmd2","0.9.6","MIT License"
"colorama","0.4.1","BSD License"
"colour","0.1.5","BSD License"
"defusedxml","0.5.0","Python Software Foundation License"
"elasticsearch","7.0.1","Apache Software License"
"elasticsearch-dsl","7.0.0","Apache Software License"
"email-reply-parser","0.5.9","MIT"
"entrypoints","0.3","MIT License"
"filedepot","0.5.2","MIT"
"filelock","3.0.10","License"
"flake8","3.7.7","MIT License"
"freezegun","0.3.12","Apache Software License"
"hapic","0.77","MIT"
"hupper","1.4.2","MIT License"
"identify","1.4.4","MIT License"
"idna","2.8","BSD License"
"importlib-metadata","0.18","Apache Software License"
"importlib-resources","1.0.2","Apache Software License"
"isort","4.3.20","MIT License"
"jsmin","2.2.2","MIT License"
"ldap3","2.5.1","GNU Lesser General Public License v3 (LGPLv3)"
"lxml","4.2.5","BSD License"
"marshmallow","2.16.3","MIT License"
"mccabe","0.6.1","MIT License"
"mock","3.0.5","BSD License"
"more-itertools","7.0.0","MIT License"
"multidict","4.5.2","Apache Software License"
"mypy","0.701","MIT License"
"mypy-extensions","0.4.1","MIT License"
"nodeenv","1.3.3","BSD License"
"packaging","18.0","Apache Software License, BSD License"
"parameterized","0.7.0","BSD License"
"pathlib","1.0.1","MIT License"
"pbr","5.1.1","Apache Software License"
"pdf2image","1.1.0","MIT License"
"pip-tools","3.7.0","BSD License"
"plaster","1.0","MIT License"
"plaster-pastedeploy","0.6","MIT License"
"pluggy","0.12.0","MIT License"
"pre-commit","1.17.0","MIT License"
"prettytable","0.7.2","BSD License"
"preview-generator","0.10","UNKNOWN"
"psycopg2","2.8.2","GNU Library or Lesser General Public License (LGPL), Zope Public License"
"py","1.8.0","MIT License"
"pyasn1","0.4.4","BSD License"
"pycodestyle","2.5.0","MIT License"
"pyexifinfo","0.4.0","GNU General Public License v3 or later (GPLv3+)"
"pyflakes","2.1.1","MIT License"
"pyparsing","2.3.0","MIT License"
"pyperclip","1.7.0","BSD License"
"pyramid","1.10.1","Repoze Public License"
"pyramid-beaker","0.8","BSD-derived (http://www.repoze.org/LICENSE.txt)"
"pyramid-debugtoolbar","4.5","Repoze Public License"
"pyramid-jinja2","2.7","Repoze Public License"
"pyramid-ldap3","0.4","Repoze Public License"
"pyramid-mako","1.0.2","Repoze Public License"
"pyramid-multiauth","0.9.0","Mozilla Public License 2.0 (MPL 2.0)"
"pyramid-retry","1.0","MIT License"
"pyramid-tm","2.2.1","Repoze Public License"
"pytest","4.6.3","MIT License"
"pytest-dotenv","0.4.0","MIT License"
"python-dateutil","2.7.5","BSD License, Apache Software License"
"python-dotenv","0.10.3","BSD License"
"python-editor","1.0.3","Apache Software License"
"python-magic","0.4.15","MIT License"
"python-slugify","1.2.6","MIT License"
"pytz","2018.7","MIT License"
"redis","2.10.6","MIT License"
"repoze.lru","0.7","Repoze Public License"
"requests","2.21.0","Apache Software License"
"responses","0.10.6","Apache 2.0"
"rq","0.12.0","BSD License"
"six","1.11.0","MIT License"
"stevedore","1.30.0","Apache Software License"
"toml","0.10.0","MIT License"
"tracim-backend","1.9.1","MIT License"
"transaction","2.4.0","Zope Public License"
"translationstring","1.3","BSD-like (http://repoze.org/license.html)"
"typed-ast","1.3.5","Apache License 2.0"
"tzlocal","1.5.1","MIT License"
"urllib3","1.24.1","MIT License"
"venusian","1.1.0","BSD-derived (http://www.repoze.org/LICENSE.txt)"
"virtualenv","16.6.0","MIT License"
"vobject","0.9.6.1","Apache Software License"
"waitress","1.1.0","Zope Public License"
"wcwidth","0.1.7","MIT License"
"xvfbwrapper","0.2.9","MIT License"
"zipp","0.5.1","MIT License"
"zope.deprecation","4.3.0","ZPL 2.1"
"zope.interface","4.6.0","Zope Public License"
"zope.sqlalchemy","1.0","Zope Public License","MIT"
"apispec","1.1.0","MIT License"
"apispec-marshmallow-advanced","0.4","MIT License"
"attrs","18.2.0","MIT License"
"beautifulsoup4","4.6.3","MIT License"
"caldav","0.6.0","GNU General Public License (GPL), Apache Software License"
"certifi","2018.11.29","Mozilla Public License 2.0 (MPL 2.0)"
"chardet","3.0.4","GNU Library or Lesser General Public License (LGPL)"
"cliff","2.14.0","Apache Software License"
"cmd2","0.9.6","MIT License"
"colorama","0.4.1","BSD License"
"colour","0.1.5","BSD License"
"defusedxml","0.5.0","Python Software Foundation License"
"elasticsearch","7.0.1","Apache Software License"
"elasticsearch-dsl","7.0.0","Apache Software License"
"email-reply-parser","0.5.9","MIT"
"filedepot","0.5.2","MIT"
"filelock","3.0.10","License"
"hapic","0.77","MIT"
"hupper","1.4.2","MIT License"
"idna","2.8","BSD License"
"jsmin","2.2.2","MIT License"
"ldap3","2.5.1","GNU Lesser General Public License v3 (LGPLv3)"
"lxml","4.2.5","BSD License"
"marshmallow","2.16.3","MIT License"
"multidict","4.5.2","Apache Software License"
"packaging","18.0","Apache Software License, BSD License"
"pathlib","1.0.1","MIT License"
"pbr","5.1.1","Apache Software License"
"pdf2image","1.1.0","MIT License"
"pip-tools","3.7.0","BSD License"
"plaster","1.0","MIT License"
"plaster-pastedeploy","0.6","MIT License"
"prettytable","0.7.2","BSD License"
"preview-generator","0.10","UNKNOWN"
"pyasn1","0.4.4","BSD License"
"pyexifinfo","0.4.0","GNU General Public License v3 or later (GPLv3+)"
"pyparsing","2.3.0","MIT License"
"pyperclip","1.7.0","BSD License"
"pyramid","1.10.1","Repoze Public License"
"pyramid-beaker","0.8","BSD-derived (http://www.repoze.org/LICENSE.txt)"
"pyramid-debugtoolbar","4.5","Repoze Public License"
"pyramid-jinja2","2.7","Repoze Public License"
"pyramid-ldap3","0.4","Repoze Public License"
"pyramid-mako","1.0.2","Repoze Public License"
"pyramid-multiauth","0.9.0","Mozilla Public License 2.0 (MPL 2.0)"
"pyramid-retry","1.0","MIT License"
"pyramid-tm","2.2.1","Repoze Public License"
"python-dateutil","2.7.5","BSD License, Apache Software License"
"python-editor","1.0.3","Apache Software License"
"python-magic","0.4.15","MIT License"
"python-slugify","1.2.6","MIT License"
"pytz","2018.7","MIT License"
"redis","2.10.6","MIT License"
"repoze.lru","0.7","Repoze Public License"
"requests","2.21.0","Apache Software License"
"rq","0.12.0","BSD License"
"six","1.11.0","MIT License"
"stevedore","1.30.0","Apache Software License"
"transaction","2.4.0","Zope Public License"
"translationstring","1.3","BSD-like (http://repoze.org/license.html)"
"tzlocal","1.5.1","MIT License"
"urllib3","1.24.1","MIT License"
"venusian","1.1.0","BSD-derived (http://www.repoze.org/LICENSE.txt)"
"vobject","0.9.6.1","Apache Software License"
"waitress","1.1.0","Zope Public License"
"wcwidth","0.1.7","MIT License"
"xvfbwrapper","0.2.9","MIT License"
"zope.deprecation","4.3.0","ZPL 2.1"
"zope.interface","4.6.0","Zope Public License"
"zope.sqlalchemy","1.0","Zope Public License"
```

install all optionals packages :
`pip install -e ".[dev,testing, mysql, postgresql]"`

get all licenses:
` pip-licenses --format=csv --from=mixed > licences_with_optionals_deps.csv`

```
"Name","Version","License"
"Babel","2.6.0","BSD License"
"Beaker","1.10.0","BSD License"
"Click","7.0","BSD License"
"IMAPClient","2.1.0","BSD License"
"Jinja2","2.10","BSD License"
"Mako","1.0.7","MIT"
"Markdown","3.0.1","BSD License"
"MarkupSafe","1.1.0","BSD License"
"PasteDeploy","2.0.0","MIT License"
"Pillow","5.3.0","Other/Proprietary License"
"PyMySQL","0.9.3","MIT License"
"PyPDF2","1.26.0","BSD License"
"PyYAML","3.13","MIT License"
"Pygments","2.3.0","BSD License"
"Radicale","2.1.11","GNU General Public License (GPL)"
"SQLAlchemy","1.2.14","MIT License"
"Unidecode","1.0.23","GNU General Public License v2 or later (GPLv2+)"
"Wand","0.4.5","MIT License"
"WebOb","1.8.4","MIT License"
"WebTest","2.0.33","MIT License"
"WsgiDAV","2.4.1","MIT License"
"alembic","1.0.5","MIT"
"apispec","1.1.0","MIT License"
"apispec-marshmallow-advanced","0.4","MIT License"
"appdirs","1.4.3","MIT License"
"aspy.yaml","1.3.0","MIT License"
"atomicwrites","1.3.0","MIT License"
"attrs","18.2.0","MIT License"
"beautifulsoup4","4.6.3","MIT License"
"black","19.3b0","MIT License"
"caldav","0.6.0","GNU General Public License (GPL), Apache Software License"
"certifi","2018.11.29","Mozilla Public License 2.0 (MPL 2.0)"
"cfgv","2.0.0","MIT License"
"chardet","3.0.4","GNU Library or Lesser General Public License (LGPL)"
"cliff","2.14.0","Apache Software License"
"cmd2","0.9.6","MIT License"
"colorama","0.4.1","BSD License"
"colour","0.1.5","BSD License"
"defusedxml","0.5.0","Python Software Foundation License"
"elasticsearch","7.0.1","Apache Software License"
"elasticsearch-dsl","7.0.0","Apache Software License"
"email-reply-parser","0.5.9","MIT"
"entrypoints","0.3","MIT License"
"filedepot","0.5.2","MIT"
"filelock","3.0.10","License"
"flake8","3.7.7","MIT License"
"freezegun","0.3.12","Apache Software License"
"hapic","0.77","MIT"
"hupper","1.4.2","MIT License"
"identify","1.4.4","MIT License"
"idna","2.8","BSD License"
"importlib-metadata","0.18","Apache Software License"
"importlib-resources","1.0.2","Apache Software License"
"isort","4.3.20","MIT License"
"jsmin","2.2.2","MIT License"
"ldap3","2.5.1","GNU Lesser General Public License v3 (LGPLv3)"
"lxml","4.2.5","BSD License"
"marshmallow","2.16.3","MIT License"
"mccabe","0.6.1","MIT License"
"mock","3.0.5","BSD License"
"more-itertools","7.0.0","MIT License"
"multidict","4.5.2","Apache Software License"
"mypy","0.701","MIT License"
"mypy-extensions","0.4.1","MIT License"
"nodeenv","1.3.3","BSD License"
"packaging","18.0","Apache Software License, BSD License"
"parameterized","0.7.0","BSD License"
"pathlib","1.0.1","MIT License"
"pbr","5.1.1","Apache Software License"
"pdf2image","1.1.0","MIT License"
"pip-tools","3.7.0","BSD License"
"plaster","1.0","MIT License"
"plaster-pastedeploy","0.6","MIT License"
"pluggy","0.12.0","MIT License"
"pre-commit","1.17.0","MIT License"
"prettytable","0.7.2","BSD License"
"preview-generator","0.10","UNKNOWN"
"psycopg2","2.8.2","GNU Library or Lesser General Public License (LGPL), Zope Public License"
"py","1.8.0","MIT License"
"pyasn1","0.4.4","BSD License"
"pycodestyle","2.5.0","MIT License"
"pyexifinfo","0.4.0","GNU General Public License v3 or later (GPLv3+)"
"pyflakes","2.1.1","MIT License"
"pyparsing","2.3.0","MIT License"
"pyperclip","1.7.0","BSD License"
"pyramid","1.10.1","Repoze Public License"
"pyramid-beaker","0.8","BSD-derived (http://www.repoze.org/LICENSE.txt)"
"pyramid-debugtoolbar","4.5","Repoze Public License"
"pyramid-jinja2","2.7","Repoze Public License"
"pyramid-ldap3","0.4","Repoze Public License"
"pyramid-mako","1.0.2","Repoze Public License"
"pyramid-multiauth","0.9.0","Mozilla Public License 2.0 (MPL 2.0)"
"pyramid-retry","1.0","MIT License"
"pyramid-tm","2.2.1","Repoze Public License"
"pytest","4.6.3","MIT License"
"pytest-dotenv","0.4.0","MIT License"
"python-dateutil","2.7.5","BSD License, Apache Software License"
"python-dotenv","0.10.3","BSD License"
"python-editor","1.0.3","Apache Software License"
"python-magic","0.4.15","MIT License"
"python-slugify","1.2.6","MIT License"
"pytz","2018.7","MIT License"
"redis","2.10.6","MIT License"
"repoze.lru","0.7","Repoze Public License"
"requests","2.21.0","Apache Software License"
"responses","0.10.6","Apache 2.0"
"rq","0.12.0","BSD License"
"six","1.11.0","MIT License"
"stevedore","1.30.0","Apache Software License"
"toml","0.10.0","MIT License"
"tracim-backend","1.9.1","MIT License"
"transaction","2.4.0","Zope Public License"
"translationstring","1.3","BSD-like (http://repoze.org/license.html)"
"typed-ast","1.3.5","Apache License 2.0"
"tzlocal","1.5.1","MIT License"
"urllib3","1.24.1","MIT License"
"venusian","1.1.0","BSD-derived (http://www.repoze.org/LICENSE.txt)"
"virtualenv","16.6.0","MIT License"
"vobject","0.9.6.1","Apache Software License"
"waitress","1.1.0","Zope Public License"
"wcwidth","0.1.7","MIT License"
"xvfbwrapper","0.2.9","MIT License"
"zipp","0.5.1","MIT License"
"zope.deprecation","4.3.0","ZPL 2.1"
"zope.interface","4.6.0","Zope Public License"
"zope.sqlalchemy","1.0","Zope Public License"
```

**Comment by inkhey** [comment]
All python backend dependencies as markdown, for readability:
`pip-licenses --format=markdown --from=mixed > licences.md`

| Name                         | Version    | License                                                                  |
|------------------------------|------------|--------------------------------------------------------------------------|
| Babel                        | 2.6.0      | BSD License                                                              |
| Beaker                       | 1.10.0     | BSD License                                                              |
| Click                        | 7.0        | BSD License                                                              |
| IMAPClient                   | 2.1.0      | BSD License                                                              |
| Jinja2                       | 2.10       | BSD License                                                              |
| Mako                         | 1.0.7      | MIT                                                                      |
| Markdown                     | 3.0.1      | BSD License                                                              |
| MarkupSafe                   | 1.1.0      | BSD License                                                              |
| PasteDeploy                  | 2.0.0      | MIT License                                                              |
| Pillow                       | 5.3.0      | Other/Proprietary License                                                |
| PyMySQL                      | 0.9.3      | MIT License                                                              |
| PyPDF2                       | 1.26.0     | BSD License                                                              |
| PyYAML                       | 3.13       | MIT License                                                              |
| Pygments                     | 2.3.0      | BSD License                                                              |
| Radicale                     | 2.1.11     | GNU General Public License (GPL)                                         |
| SQLAlchemy                   | 1.2.14     | MIT License                                                              |
| Unidecode                    | 1.0.23     | GNU General Public License v2 or later (GPLv2+)                          |
| Wand                         | 0.4.5      | MIT License                                                              |
| WebOb                        | 1.8.4      | MIT License                                                              |
| WebTest                      | 2.0.33     | MIT License                                                              |
| WsgiDAV                      | 2.4.1      | MIT License                                                              |
| alembic                      | 1.0.5      | MIT                                                                      |
| apispec                      | 1.1.0      | MIT License                                                              |
| apispec-marshmallow-advanced | 0.4        | MIT License                                                              |
| appdirs                      | 1.4.3      | MIT License                                                              |
| aspy.yaml                    | 1.3.0      | MIT License                                                              |
| atomicwrites                 | 1.3.0      | MIT License                                                              |
| attrs                        | 18.2.0     | MIT License                                                              |
| beautifulsoup4               | 4.6.3      | MIT License                                                              |
| black                        | 19.3b0     | MIT License                                                              |
| caldav                       | 0.6.0      | GNU General Public License (GPL), Apache Software License                |
| certifi                      | 2018.11.29 | Mozilla Public License 2.0 (MPL 2.0)                                     |
| cfgv                         | 2.0.0      | MIT License                                                              |
| chardet                      | 3.0.4      | GNU Library or Lesser General Public License (LGPL)                      |
| cliff                        | 2.14.0     | Apache Software License                                                  |
| cmd2                         | 0.9.6      | MIT License                                                              |
| colorama                     | 0.4.1      | BSD License                                                              |
| colour                       | 0.1.5      | BSD License                                                              |
| defusedxml                   | 0.5.0      | Python Software Foundation License                                       |
| elasticsearch                | 7.0.1      | Apache Software License                                                  |
| elasticsearch-dsl            | 7.0.0      | Apache Software License                                                  |
| email-reply-parser           | 0.5.9      | MIT                                                                      |
| entrypoints                  | 0.3        | MIT License                                                              |
| filedepot                    | 0.5.2      | MIT                                                                      |
| filelock                     | 3.0.10     | License                                                                  |
| flake8                       | 3.7.7      | MIT License                                                              |
| freezegun                    | 0.3.12     | Apache Software License                                                  |
| hapic                        | 0.77       | MIT                                                                      |
| hupper                       | 1.4.2      | MIT License                                                              |
| identify                     | 1.4.4      | MIT License                                                              |
| idna                         | 2.8        | BSD License                                                              |
| importlib-metadata           | 0.18       | Apache Software License                                                  |
| importlib-resources          | 1.0.2      | Apache Software License                                                  |
| isort                        | 4.3.20     | MIT License                                                              |
| jsmin                        | 2.2.2      | MIT License                                                              |
| ldap3                        | 2.5.1      | GNU Lesser General Public License v3 (LGPLv3)                            |
| lxml                         | 4.2.5      | BSD License                                                              |
| marshmallow                  | 2.16.3     | MIT License                                                              |
| mccabe                       | 0.6.1      | MIT License                                                              |
| mock                         | 3.0.5      | BSD License                                                              |
| more-itertools               | 7.0.0      | MIT License                                                              |
| multidict                    | 4.5.2      | Apache Software License                                                  |
| mypy                         | 0.701      | MIT License                                                              |
| mypy-extensions              | 0.4.1      | MIT License                                                              |
| nodeenv                      | 1.3.3      | BSD License                                                              |
| packaging                    | 18.0       | Apache Software License, BSD License                                     |
| parameterized                | 0.7.0      | BSD License                                                              |
| pathlib                      | 1.0.1      | MIT License                                                              |
| pbr                          | 5.1.1      | Apache Software License                                                  |
| pdf2image                    | 1.1.0      | MIT License                                                              |
| pip-tools                    | 3.7.0      | BSD License                                                              |
| plaster                      | 1.0        | MIT License                                                              |
| plaster-pastedeploy          | 0.6        | MIT License                                                              |
| pluggy                       | 0.12.0     | MIT License                                                              |
| pre-commit                   | 1.17.0     | MIT License                                                              |
| prettytable                  | 0.7.2      | BSD License                                                              |
| preview-generator            | 0.10       | UNKNOWN                                                                  |
| psycopg2                     | 2.8.2      | GNU Library or Lesser General Public License (LGPL), Zope Public License |
| py                           | 1.8.0      | MIT License                                                              |
| pyasn1                       | 0.4.4      | BSD License                                                              |
| pycodestyle                  | 2.5.0      | MIT License                                                              |
| pyexifinfo                   | 0.4.0      | GNU General Public License v3 or later (GPLv3+)                          |
| pyflakes                     | 2.1.1      | MIT License                                                              |
| pyparsing                    | 2.3.0      | MIT License                                                              |
| pyperclip                    | 1.7.0      | BSD License                                                              |
| pyramid                      | 1.10.1     | Repoze Public License                                                    |
| pyramid-beaker               | 0.8        | BSD-derived (http://www.repoze.org/LICENSE.txt)                          |
| pyramid-debugtoolbar         | 4.5        | Repoze Public License                                                    |
| pyramid-jinja2               | 2.7        | Repoze Public License                                                    |
| pyramid-ldap3                | 0.4        | Repoze Public License                                                    |
| pyramid-mako                 | 1.0.2      | Repoze Public License                                                    |
| pyramid-multiauth            | 0.9.0      | Mozilla Public License 2.0 (MPL 2.0)                                     |
| pyramid-retry                | 1.0        | MIT License                                                              |
| pyramid-tm                   | 2.2.1      | Repoze Public License                                                    |
| pytest                       | 4.6.3      | MIT License                                                              |
| pytest-dotenv                | 0.4.0      | MIT License                                                              |
| python-dateutil              | 2.7.5      | BSD License, Apache Software License                                     |
| python-dotenv                | 0.10.3     | BSD License                                                              |
| python-editor                | 1.0.3      | Apache Software License                                                  |
| python-magic                 | 0.4.15     | MIT License                                                              |
| python-slugify               | 1.2.6      | MIT License                                                              |
| pytz                         | 2018.7     | MIT License                                                              |
| redis                        | 2.10.6     | MIT License                                                              |
| repoze.lru                   | 0.7        | Repoze Public License                                                    |
| requests                     | 2.21.0     | Apache Software License                                                  |
| responses                    | 0.10.6     | Apache 2.0                                                               |
| rq                           | 0.12.0     | BSD License                                                              |
| six                          | 1.11.0     | MIT License                                                              |
| stevedore                    | 1.30.0     | Apache Software License                                                  |
| toml                         | 0.10.0     | MIT License                                                              |
| tracim-backend               | 1.9.1      | MIT License                                                              |
| transaction                  | 2.4.0      | Zope Public License                                                      |
| translationstring            | 1.3        | BSD-like (http://repoze.org/license.html)                                |
| typed-ast                    | 1.3.5      | Apache License 2.0                                                       |
| tzlocal                      | 1.5.1      | MIT License                                                              |
| urllib3                      | 1.24.1     | MIT License                                                              |
| venusian                     | 1.1.0      | BSD-derived (http://www.repoze.org/LICENSE.txt)                          |
| virtualenv                   | 16.6.0     | MIT License                                                              |
| vobject                      | 0.9.6.1    | Apache Software License                                                  |
| waitress                     | 1.1.0      | Zope Public License                                                      |
| wcwidth                      | 0.1.7      | MIT License                                                              |
| xvfbwrapper                  | 0.2.9      | MIT License                                                              |
| zipp                         | 0.5.1      | MIT License                                                              |
| zope.deprecation             | 4.3.0      | ZPL 2.1                                                                  |
| zope.interface               | 4.6.0      | Zope Public License                                                      |
| zope.sqlalchemy              | 1.0        | Zope Public License                                                      |

**Comment by Skylsmoi** [comment]
frontend list of direct dependencies (depth=0) for all apps combined:
```
- "@babel/core": "^7.1.6",
- "@babel/plugin-proposal-class-properties": "^7.1.0",
- "@babel/plugin-proposal-object-rest-spread": "^7.0.0",
- "@babel/plugin-transform-object-assign": "^7.0.0",
- "@babel/polyfill": "^7.0.0",
- "@babel/preset-env": "^7.1.6",
- "@babel/preset-react": "^7.0.0",
- "babel-eslint": "^8.2.6",
- "babel-loader": "^8.0.4",
- "classnames": "^2.2.5",
- "css-loader": "^0.28.7",
- "file-loader": "^1.1.5",
- "i18next": "^10.5.0",
- "js-cookie": "^2.2.0",
- "lodash": "^4.17.11",
- "prop-types": "^15.6.0",
- "query-string": "^6.1.0",
- "radium": "^0.24.1",
- "react": "^16.0.0",
- "react-animate-height": "^0.10.10",
- "react-dnd": "^7.4.5",
- "react-dnd-html5-backend": "^7.4.4",
- "react-dom": "^16.0.0",
- "react-i18next": "^7.4.0",
- "react-redux": "^5.0.6",
- "react-router": "^5.0.1",
- "react-router-dom": "^5.0.1",
- "react-select": "^1.2.1",
- "redux": "^3.7.2",
- "redux-logger": "^3.0.6",
- "redux-thunk": "^2.2.0",
- "standard": "^11.0.0",
- "standard-loader": "^6.0.1",
- "style-loader": "^0.19.0",
- "stylus": "^0.54.5",
- "stylus-loader": "^3.0.1",
- "url-loader": "^0.6.2",
- "webpack": "^4.26.1",
- "webpack-cli": "^3.1.2",
- "whatwg-fetch": "^2.0.3"
- "i18next-scanner": "^2.6.1",
- "json-server": "^0.12.0",
- "webpack-dev-server": "^3.1.10"
- "script-loader": "^0.7.2",
- "caldavzap": "0.13.0"
- "react-dropzone": "^5.0.1",
- "react-images": "^0.5.19",
- "date-fns": "^1.29.0",
- "cypress": "^3.3.1",
- "cypress-wait-until": "^1.2.1"
```

details of frontend licenses for each apps:
[licenses_frontend.zip](https://github.com/tracim/tracim/files/3286068/licenses_frontend.zip)

**Comment by inkhey** [comment]
**System Dependencies:**

debian package package currently required in setup_default_backend script:

`
python3 python3-venv python3-dev python3-pip redis-server zlib1g-dev libjpeg-dev imagemagick libmagickwand-dev libpq-dev ghostscript libfile-mimeinfo-perl poppler-utils libimage-exiftool-perl qpdf libldap2-dev libsasl2-dev libreoffice inkscape'`

Other dependencies:
- nodejs (with npm)

**Comment by lebouquetin** [comment]
Fixed through commits:

- https://github.com/tracim/tracim/commit/6658fe85c611f2ae87aa0baf7a802ae134ad20ac
- https://github.com/tracim/tracim/commit/0eded982614dcf8c22bdac22a249f343f354909e
- https://github.com/tracim/tracim/commit/03628b2f4123790c29ccfc7d387329ad017f1458
- https://github.com/tracim/tracim/commit/2e75c8b2ac4b95c469c51b682d2fe62d674184d4
- https://github.com/tracim/tracim/commit/34ed7a36a99f94526e64880ae0901c62c107733a

**Comment by PhilippeAccorsi** [comment]
Verified.
