### ISSUE TITLE
Create and refactor debug process of apps with servdev

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#1910]
## Bug description & symptom

Each apps have can be run as stand alone (out of tracim frontend) to be able to use webpack dev server.
This allows fast rebuild.
That process is the same for each apps but hasn't been maintain in a while and needs to be refactored.

## Expected

Each apps works with webpack dev server (cli: `npm run servdev`)
Update doc accordingly

**Comment by Skylsmoi** [comment]
To test this issue:
You need to run each app's dev server.
To do so:
- have a backend running
- run the frontend's dev server: `npm run servdev` with a configEnv.json pointing to a proper api url. Eg: `local_ip:6543/api/v2`
- login to frontend's dev server to have a cookie
- run the app's dev server: `npm run servdev` with a proper content id and workspace id in the debug.js filer matching an actual content in your database

**Comment by PhilippeAccorsi** [comment]
Testing app file:
I have uploaded a file in workspace '3' and contend_id '27' and make modification in debug.js but servdev show this error in console (firefox):
~~~
[WDS] Disconnected! client:196
[HMR] Waiting for update signal from WDS... log.js:24
<File> did mount File.jsx:139
<File> did update 
Object { appName: "file", isVisible: true, config: {…}, loggedUser: {…}, content: {…}, timeline: [], externalTranslationList: (5) […], newComment: "", newFile: "", newFilePreview: null, … }
 
Object { appName: "file", isVisible: true, config: {…}, loggedUser: {…}, content: {…}, timeline: [], externalTranslationList: (5) […], newComment: "", newFile: "", newFilePreview: null, … }
File.jsx:155
Unhandled promise rejection SyntaxError: "JSON.parse: unexpected character at line 1 column 1 of the JSON data" es6.promise.js:110
Erreur dans les liens source : request failed with status 404
URL de la ressource : http://192.168.1.150:8075/assets/bootstrap/bootstrap-4.0.0-beta.css
URL du lien source : bootstrap.min.css.map

[WDS] Hot Module Replacement enabled.
~~~

**Comment by PhilippeAccorsi** [comment]
Same error with other app

**Comment by PhilippeAccorsi** [comment]
Its possible to start all app with is own servdev.

**Comment by Skylsmoi** [comment]
Just some informations about this:
`SyntaxError: "JSON.parse: unexpected character at line 1 column 1 of the JSON data"` usually means that the frontend got an answer to the request that isn't json. That's why the JSON.parse fails.

It doesn't always means that the front has a bug, it might be the backend that didn't answer json for some reason.
In that case, it might be a configuration related issue, or the front is asking for files that it shouldn't.

**Comment by gbonaspetti** [comment]
> Same error with other app

Each app has a configuration to be changed in the debug.js file, more details in the README file of the respective app, please, make sure that you changed the settings correctly.

**Comment by PhilippeAccorsi** [comment]
Verified.
