### ISSUE TITLE
When we archived or deleted a folder the message does not appear correctly

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#1918]
## Bug description & symptom

When we archived or deleted a folder at advanced mode the message does not appear correctly and it shows only half of the Restore button.

## Expected

To see all message.

## Screenshots

![FolderAdvanced](https://user-images.githubusercontent.com/35422692/59491502-2d1b3e00-8e87-11e9-8796-93ce01c42fb9.png)

**Comment by PhilippeAccorsi** [comment]
Verified.
