### ISSUE TITLE
Problems in the header after Search feature

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#1926]
## Bug description & symptom

Three bugs in the header find after search feature was merged:
1. At home page, if we have a small height and we use the internal scroll, the *Welcome* message have a strange border that goes over the text.
2. If the header is bigger then normal (e.g. dropdown menu) we have a sidebar problem in the *hide/see sidebar* button when we use the external scroll.
3. The user's name doesn't appears in dropdown menu when we decreases the screen width

## Expected

- [x] A border that embrace all text in *Welcome* message
- [x] The *hide/see sidebar* button stays always just bellow the header
- [x] A responsive behavior in the username and *email notification* message

## Screenshots

1. 
![Screenshot from 2019-06-17 09-42-34](https://user-images.githubusercontent.com/35422692/59590743-078f6e00-90ed-11e9-99a5-02081cc6ea2b.png)

2. 
![Screenshot from 2019-06-17 09-42-46](https://user-images.githubusercontent.com/35422692/59590801-1bd36b00-90ed-11e9-9e65-24df71e8d0b0.png)

3. 
![Screenshot from 2019-06-17 09-55-58](https://user-images.githubusercontent.com/35422692/59590859-36a5df80-90ed-11e9-9252-fabe7a35a82c.png)

**Comment by celiamgtt** [comment]
Still have some problems with the user's name around ~980-1010px width  (+ a horizontal scrollbar displayed)

![Capture d'écran de 2019-06-18 17-17-31](https://user-images.githubusercontent.com/50453784/59696994-620ff380-91ed-11e9-9250-1c0ea8b87cce.png)

**Comment by celiamgtt** [comment]
Verified
