### ISSUE TITLE
Searched keywords query must appear in the url

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1928]
## Feature description

Add a query parameter `?q=Searched Keywords` to the url of the search results.
the search request must use that query param.
Keep the redux mechanism but it must come from the query param

Also add query parameters for page number, page size, show archived,, show deleted ...
every search parameters actually

## Context

Search result page should be sharable. So it should include the query.

## Impacted components

Frontend
  Search

**Comment by PhilippeAccorsi** [comment]
@gbonaspetti I can see this label " blocked by backend ", backend work is it still necessary?

**Comment by gbonaspetti** [comment]
> @gbonaspetti I can see this label " blocked by backend ", backend work is it still necessary?

Yes, we need to wait for the issue #1973 to be merged.

**Comment by PhilippeAccorsi** [comment]
@gbonaspetti #1973 merged.

**Comment by PhilippeAccorsi** [comment]
Can I test this issue?

**Comment by gbonaspetti** [comment]
> Can I test this issue?

yes

**Comment by PhilippeAccorsi** [comment]
I don't know if its what we want in this issue:
`http://192.168.1.150:6543/ui/search-result?act=1&arc=0&del=0&nr=10&p=1&q=taratatata&t=html-document%2Cfile%2Cthread%2Cfolder%2Ccomment`

I can see word I have search. @Skylsmoi is it what we need with this feature?

**Comment by Skylsmoi** [comment]
@PhilippeAccorsi It is.
The point is to be able to share a search url. So it needs to include everything

**Comment by PhilippeAccorsi** [comment]
Ok, great :)
Verified.
