### ISSUE TITLE
Changing description of a workspace in app workspace advanced reactivate agenda

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1929]
## Bug description & symptom

Changing the description of a workspace in app workspace advanced always activate the agenda

## Diagnostic

The PUT that changes the description doesn't send the key "agenda_enabled"
The PUT that activate/desactivate agenda send the 3 keys "agenda_enabled", "label", "description"

Ideally, the PUT should only send the changed properties

## Expected

Each PUT on api/workspace/:id (for changing label, description and agenda) should only send the changed key

## How to reproduce

- Open a workspace's dashboard
- Open app workspace advanced
- Deactivate agenda
- Change the workspace's description

## Impacted components

App workspace advanced should only send the changed properties
Backend should allow to receive only the changing property without changing the others

## Prerequisite

https://github.com/tracim/tracim/issues/1935

**Comment by inkhey** [comment]
@lebouquetin i've done fix making all parameters optional, see #1933, is this change ok ?

**Comment by inkhey** [comment]
@lebouquetin i've done fix making all parameters optional, see #1933, is this change ok ?

**Comment by lebouquetin** [comment]
@Skylsmoi you have work to do on this, no? If not, then move to Need Test

**Comment by Skylsmoi** [comment]
I will add the missing properties to the PUT endpoints of the app

**Comment by Skylsmoi** [comment]
hum... issue actually was the refactor of `calendar` to `agenda` that was missing on the endpoint properties

**Comment by LucBarry** [comment]
Verified
