### ISSUE TITLE
rename search commands

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1937]
## Bug description & symptom

search commands aren't explicit enough

## Expected

have those command names :

-   search index-create  create index of search engine
-   search index-drop  Delete all index, alias and template of tracim document
-   search index-populate  index content(s) into search engine
-   search index-upgrade-experimental  upgrade index: create a copy of current index with updated index template (useful for migration), set index alias to this new index (experimental)

**Comment by PhilippeAccorsi** [comment]
Verified.
