### ISSUE TITLE
Search returns the same result twice

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#1955]
## Bug description & symptom

Sometimes the search return the same result twice for the searched keywords.

## Expected

Unique results for the same searched keywords.

## Screenshots

![Screenshot from 2019-06-19 11-55-59](https://user-images.githubusercontent.com/35422692/59756181-83beb880-9289-11e9-8f6e-c3c001222a9f.png)

**Comment by inkhey** [comment]
Verified by reproducing case where backend return doublon :  happened when we get same content in multiple pages (bad remove duplicate code in backend) as we have multiple comment returning it.
