### ISSUE TITLE
Drag & Drop icon on mouse over isn't always the proper one

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1958]
## Bug description & symptom

When dragging a content of folder over a workspace where you should be able to drop, it doesn't always display the arrow down icon.
Only appear right after connection

## Expected

The icon arrow down should be displayed whenever it is possible to drop

## How to reproduce

- disconnect user
- reconnect user
- open workspace content
- drag a content hover a different workspace where you should be able to drop

## Impacted components

frontend

**Comment by LucBarry** [comment]
Verified
