### ISSUE TITLE
Refactor Warning Icons

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#1972]
## Bug description & symptom

The Warning Icon is used multiple times and in different places in the code. It is good to do a refactoring an like that the same code is not repeated several times and we have a pattern for this type of icon.

## Expected

All Warning Icons originate from the same React component and use the same CSS code.

## Screenshots

Example:
![Screenshot from 2019-06-17 14-27-39](https://user-images.githubusercontent.com/35422692/59843013-0746db00-9358-11e9-96ec-e3b0d5c68449.png)

**Comment by gbonaspetti** [comment]
Please, add a margin bottom in xs screens

![Screenshot from 2019-06-21 11-42-17](https://user-images.githubusercontent.com/35422692/59914143-0bd3c800-941a-11e9-881d-2cb224eb63e4.png)

**Comment by Skylsmoi** [comment]
verified
