### ISSUE TITLE
Backend simple search should not return doublon.

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#1973]
## Bug description & symptom

Doublon issue with simple search is solved here in frontend: https://github.com/tracim/tracim/issues/1955
But that's also mean backend always does not return proper result.

## Expected

- Do not return anymore doublon result with simple search
- non regression test in our case (does happened with comment returning to same content): add a content with multiples comment with search string into them and verifiy if not doublon are found.

**Comment by PhilippeAccorsi** [comment]
@inkhey what kind of simple test can I make to test this feature?

**Comment by inkhey** [comment]
> @inkhey what kind of simple test can I make to test this feature?

Not so easy. You should verify that /api/v2/search/content doesn't return at all doublon.

The Easiest way to check this is done by non-regression test here, it is to create a tracim with 2 comments , having a keyword in both comments, search by size of "1" and verify if page 2 is empty. (there is just one content, you should not return multiple items).

**Comment by PhilippeAccorsi** [comment]
Ok. So Test of non-regression exist, so Its ok for me.
Thanks.

Verified.
