### ISSUE TITLE
Changing folder's allowed content should reload workspace content list

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1977]
## Bug description & symptom

When changing a folder's allowed sub content, workspace content list isn't updated and the folder still allow to create the sub content 

## Diagnostic

Changing the allowed sub content type should send the custom event to reload content list

## Expected

Changing an allowed sub content should update the folder in content list

## How to reproduce

open a folder advanced app
uncheck a content type
close the folder advanced app
create a content of the type you just unchecked in that folder

## Impacted components

app folder advanced

**Comment by LucBarry** [comment]
Verified
