### ISSUE TITLE
In xl screens, the Advanced Dashboard button is under the square with the user name

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#1981]
## Bug description & symptom

If the screen width is between 1200px and 1246px, the Advanced Dashboard button is 
under the square with the user name (only in French).

## Expected

That the button is fully visible.

## Screenshots

![Screenshot from 2019-06-20 16-20-07](https://user-images.githubusercontent.com/35422692/59856544-6c5df900-9377-11e9-9441-32b071c08cae.png)

**Comment by celiamgtt** [comment]
Button cropped sometimes in french version
![Capture d'écran de 2019-06-21 10-05-00](https://user-images.githubusercontent.com/50453784/59908281-5b5fc700-940d-11e9-9f6f-b86510db75ed.png)

**Comment by celiamgtt** [comment]
Verified
