### ISSUE TITLE
Processus d'installation ourSQL

### ISSUE THREAD

**Issue by herawo** [tracim/tracim#199]
L'installation de ourSQL n'est pas claire, la ligne a executer n'est pas au bon endroit.

**Comment by tracim** [comment]
Is it fixed with new documentation ? If it is, then close this bug

**Comment by algooapy** [comment]
- `ourSQL` isn't the Python `MySQL` driver in Tracim any more.
- documentation has been updated, [see here](https://github.com/tracim/tracim/blob/master/doc/database.md#driver-1)
