### ISSUE TITLE
Scroll appears above Tinymce fullscreen at files

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#1992]
## Bug description & symptom

If we use TinyMce (rich text) fullscreen in the comments of a file and we are on a small screen, the scroll appears above the text editor.

## Expected

The scroll does not appears.

## How to reproduce

1. Open a file
2. Put rich text in the commentary
3. Put in fullscreen
4. Set the screen size to 600px by 600px

## Screenshots

![Screenshot from 2019-06-21 14-07-30](https://user-images.githubusercontent.com/35422692/59921910-83f8b880-942f-11e9-96db-92b7f9a9c442.png)

**Comment by PhilippeAccorsi** [comment]
Verified.
