### ISSUE TITLE
Buttons for drag & drop are no longer visible, after passing over the header

### ISSUE THREAD

**Issue by LucBarry** [tracim/tracim#1994]
## Bug description & symptom

When I move a file and switch to the header, the buttons for moving no longer appear.

## Expected

Drag and drop buttons are always accessible after passing over the header.

## How to reproduce

1. Click on button for drag & drop
2. Go on the header with the cursor
3. Now try to move the file

## Screenshots
![issue bug](https://user-images.githubusercontent.com/39124679/59928208-857dad00-943e-11e9-8bc4-9f4926bee885.gif)

**Comment by metzgegu** [comment]
Could not be reproduced
