### ISSUE TITLE
Drag & Drop issue on workspace on Firefox 60.7

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#1997]
## Bug description & symptom

The dragged element doesn't always display the proper icon when hovered over a workspace in the sidebar

## Diagnostic

The first hovered workspace shows the right icon but not the further ones
The issue only appear on Firefox Linux version around v60.7
It is the default version distributed with debian 9 and 10

## Expected

The hovered workspace always shows the proper icon

## Context and version information

Only appear on Firefox ESR v60.7

## How to reproduce

be on Firefox ESR v60.7
open a workspace content
drag a content or folder over a workspace from sidebar
drag it over another workspace from sidebar

the icon doesn't change

## Impacted components

frontend

**Comment by Haskaris** [comment]
Closing this issue since the bug is from 2019 on a non stable Firefox version.
Can't reproduce this issue on Firefox 108 with Tracim 4.4.3 build_099
