### ISSUE TITLE
Limit default handled file for elasticsearch

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2001]
## Bug description & symptom

Currently, we try to upload any file to elasticsearch with ingest mecanism.
We should avoid uploading any file or at least make this configurable.

## Diagnostic

Case we do not want to index file:
- Not document file: we can use whitelist_mimetype parameter but we should rely know value to put in it by default which is not trivial
- Big file. as we send file as b64, see #1877, it cause memory trouble and take time for large file. We should probably have some thing of limit for this. Another reason to have strict limit here is that it's almost certain that elasticsearch process itself as by default some kind of similar limitation, we should do thing in a way it work similar way (same limitation for elasticsearch ingest and tracim indexing). We should also think about making this configurable is possible.

## Expected

Unclear

**Comment by inkhey** [comment]
Elasticsearch limit of file size is related to :
`http.max_content_length` configured by default as 100mb.
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html
That's means we cannot using this configuration by default, send a request bigger than 100mb.
This size does include:
- Content file body (of course) which is b64encoded, so is size is bigger than normal
- Other part of the request and the body (we send content of all comment, so if we put image data in comment or thing like this, that may fail)

**Comment by inkhey** [comment]
PR add 2 config parameter to configure most easily what to ingest : 
- mimetype blacklist.
- size_limit in bytes for ingest.

**Comment by PhilippeAccorsi** [comment]
This issue is fixed directly in tracim 2.3.1
I close this issue.
