### ISSUE TITLE
result of search is not usable in progressive view

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2009]
## Bug description & symptom

If I search something with tracim, its not possible to understand result of research.

## Diagnostic

*"unknown".*

## Expected

- [ ] Its possible to use search in tracim with progressive view.

## Context and version information

- Smartphone/Tablet

## How to reproduce

- open burger button
- search one word
=> you can see table with some result but result is not usable. You can just now correctly the type of the content. Other thing is not show correctly.

## Screenshots

![Screenshot_2019-06-25-09-43-10](https://user-images.githubusercontent.com/25848257/60079700-c15e8e00-972e-11e9-9442-73d620a0ea6e.png)

## Impacted components

- *frontend*

## Extra information

Maybe we not need to show same information like we have in desktop. Or its necessary to show result whit another kind of view.

**Comment by PhilippeAccorsi** [comment]
Idea: just show type of content and filename (not show other information).

**Comment by Quiwy** [comment]
Seems better on build_088, only type and title are shown :
![image](https://user-images.githubusercontent.com/20048264/185625297-4fc3ea3c-9635-41c5-9a7d-a9ba375dc413.png)

Feel free to reopen if it's not enough :smile:
