### ISSUE TITLE
Documentation : make LDAP part easier to understand

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#201]
Instead of 

> To use LDAP authentication, set auth_type parameter to "ldap":

Write : 

> You can use LDAP for users authentication. It's not the default configuration and if unsure, do not activate it.
>
> In order to activate it, set auth_type parameter to "ldap":

**Comment by algooapy** [comment]
Isn't this a bit too verbose ? If one reads that deep in the documentation, shouldn't she know if `LDAP` is interesting to her ?
