### ISSUE TITLE
Adding an image to Tinymce causes an input to appear at the bottom of the screen

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#2011]
## Bug description & symptom

Adding an image to Tinymce causes an input ("Choose file" + file name) to appear at the bottom of the screen and this allows a horizontal scroll that shouldn't exist.

## Expected

Adding an image does not impact the general interface, this input must be hidden.

## Context and version information

input id : hidden_tinymce_fileinput

## How to reproduce

1. Go to a content of any type
2. Click at Rich text in the timeline
3. Add an image
4. Scroll to the bottom of the page

(The same happens at Rich text in Text Documents)

## Screenshots

![Peek 2019-06-25 09-49](https://user-images.githubusercontent.com/35422692/60080504-5910ac00-9730-11e9-997e-45e427f28f71.gif)

**Comment by PhilippeAccorsi** [comment]
Verified.
