### ISSUE TITLE
you not see your comment when you write comment in timeline (on mobile)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2012]
## Bug description & symptom

If you use tracim on smartphone and if you try to write comment, keyboard appear on screen and you can write message but you can't see what you write.

## Diagnostic

*"unknown".*

## Expected

- [ ] its possible to see what you write when you use tracim on smartphone

## Context and version information

- Smartphone/Tablet (if applicable)

## How to reproduce

- Open one content (html doc for exemple)
- Click on comment input
- write text
=> keybord is above comment input.

## Screenshots

**Input for comment visible**

![Screenshot_2019-06-25-10-09-23](https://user-images.githubusercontent.com/25848257/60081095-73975500-9731-11e9-919d-dd7101d448ef.png)

**After click in input for comment**

![Screenshot_2019-06-25-10-09-28](https://user-images.githubusercontent.com/25848257/60081130-827e0780-9731-11e9-9ad6-9e40cb518ef8.png)

## Impacted components

- *frontend*
- *htmldoc / file / thread app*

**Comment by PhilippeAccorsi** [comment]
Need to checkif still exist on 2.6.1

**Comment by Quiwy** [comment]
Not anymore relevant since #5814
