### ISSUE TITLE
Avoid/limit storing of full file with elasticsearch ingest

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2016]
## Bug description & symptom

Currently elasticsearch ingest do index origin content given, that mean high cost of data storage.

## Expected

remove content source from ingested doc. see https://discuss.elastic.co/t/storing-binary-files-in-elastic/63078/5

**Comment by PhilippeAccorsi** [comment]
This issue is fixed directly in 2.3.1
I close this issue.
