### ISSUE TITLE
update preview_generator to 0.11

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2022]
## Bug description & symptom

use new version of preview_generator to have better handling of b&w image
see https://github.com/algoo/preview-generator

## Expected
b&w image preview are correctly rendered using preview_generator 0.11

**Comment by tracim** [comment]
@philippe what's wrong?

**Comment by PhilippeAccorsi** [comment]
Nothing, this issue is just not tested.

**Comment by PhilippeAccorsi** [comment]
This new version is for this fix https://github.com/algoo/preview-generator/issues/84
image for testing:
![800px-Hiboux](https://user-images.githubusercontent.com/25848257/60593717-a4b3fd00-9da3-11e9-9c96-5e463eea4a27.jpg)
![57465349-b767f500-727e-11e9-9af7-2f6be14783f2](https://user-images.githubusercontent.com/25848257/60593718-a4b3fd00-9da3-11e9-8ad0-0abfe5e369c2.png)
![The_Wire_logo](https://user-images.githubusercontent.com/25848257/60593721-a54c9380-9da3-11e9-9847-72bb6d6cb838.png)
![RGBA_image](https://user-images.githubusercontent.com/25848257/60593722-a54c9380-9da3-11e9-8750-ead20159b76d.png)
![LA_image](https://user-images.githubusercontent.com/25848257/60593723-a5e52a00-9da3-11e9-84da-22d322503307.png)

**Comment by PhilippeAccorsi** [comment]
Verified.
