### ISSUE TITLE
Add possibility to know which user have created specific workspace

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2027]
## Feature description

Add possibility to know which user have created specific workspace.

- [X] add a `owner` column 
- [x] for old workspaces, set owner to workspace manager with lowest user_id
- [x] check on algoo instance that we always have at least a workspace manager

## Context

We need this feature for hosting.

## Impacted components

- *backend*
- *frontend*

**Comment by inkhey** [comment]
This probably means that we should know who is the creator of one workspace, this information is not stored yet.

We should find a solution to make this work also in context of migration of database. 
What should be the behavior for workspace that already exist ?

_Originally posted by @inkhey in https://github.com/tracim/tracim/issues/2031#issuecomment-507212241_

**Comment by PhilippeAccorsi** [comment]
Description edited this morning.

**Comment by inkhey** [comment]
need to set more properly default value of owner with available values.

**Comment by PhilippeAccorsi** [comment]
Verified.
