### ISSUE TITLE
add possibility to specify limit for file what you want to upload in tracim

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2028]
## Feature description

Limit size of file its possible to upload in tracim

- limit is for file size (not for html page for example)
- check size on frontend size and on backend size
- use content-length for check
- add documentation for apache configuration
- add max file size in config endpoint.

## Context

Need this feature for hosting.

## Impacted components

- *backend*
- *frontend*

UPDATE 02:09.2019 :warning:  Only backend part of the feature is done in this issue for apache doc/frontend part see new issue #2345

**Comment by inkhey** [comment]
For frontend: 
It depend on what frontend can do, but frontend seems the best place to disallow sending big file without having to wait for error.

For Backend: 
I'm not sure that's really interesting to make limit here in api, it's already possible to limit size of body request send and this return, as far i know, specific error code. Does it make sense to handle case where webserver doesn't failed but return error in backend in those situation ?

**Comment by inkhey** [comment]
https://developer.mozilla.org/fr/docs/Web/HTTP/Status/413

**Comment by inkhey** [comment]
If frontend is able to make limitation, we should maybe return size limitation information with a backend endpoint, in this case it make sense to technically refuse too big file in backend although it was already received.

**Comment by inkhey** [comment]
try limitation in backend according to content_length value, work for both webdav and api context.
see https://github.com/tracim/tracim/tree/fix/2028__limit_size_of_file_upload

**Comment by PhilippeAccorsi** [comment]
Description edited this morning.

**Comment by inkhey** [comment]
Wip branch here : https://github.com/tracim/tracim/tree/feature/2028__limit_size_of_file_upload

**Comment by inkhey** [comment]
@PhilippeAccorsi 
- Backend part is done in : https://github.com/tracim/tracim/tree/feature/2028__limit_size_of_file_upload
- Frontend part can be done with value given in /config endpoint (in backend part)
- Documentation for apache is unclear ?

**Comment by inkhey** [comment]
frontend should :
- do not allow upload file with more than size limit given by content_length_file_size_limit in content endpoint.
- support specific error code related to size limit ? (should not occured at all because of first check in /config )

**Comment by PhilippeAccorsi** [comment]
> @PhilippeAccorsi
> 
>     * Backend part is done in : https://github.com/tracim/tracim/tree/feature/2028__limit_size_of_file_upload
> 
>     * Frontend part can be done with value given in /config endpoint (in backend part)
> 
>     * Documentation for apache is unclear ?

I think its not necessary to have documentation here because limitation of file size is in tracim code. If Admin want to add more limitation, He can do this in apache conf with apache documentation.

**Comment by PhilippeAccorsi** [comment]
Limitation of file size (in development.ini) is working.
Verified.

**Comment by PhilippeAccorsi** [comment]
Frontend part not done so no error message visible in frontend for the moment. Just this error in network.
~~~
code | 6002
message | File cannot be added because his size "30329686" is higher than max allowed size : "10485760"
~~~
