### ISSUE TITLE
add possibility to specify limit for workspace created by user

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2029]
## Feature description

Its possible to specify limit of size available in one workspace.

- add workspace max size config endpoint
- add current size in workspace endpoint
- do not take into account deleted files

## Context

Need this feature for hosting.

## Impacted components

- *backend*
- *frontend*

**Comment by inkhey** [comment]
@PhilippeAccorsi What mean "size" in this context ?
I do think the most easy is to limit only size to size of Sum of Depot Files in one workspace.
but problem is that html-document can be large and comment too.

**Comment by inkhey** [comment]
@PhilippeAccorsi Does all workspace should be limited the same or is there a limit per worspace, if so, should default limit be the same for all users ?

**Comment by PhilippeAccorsi** [comment]
Need more reflection on the subject to make sure solution is the good one.

**Comment by inkhey** [comment]
other problem with this is about old revisions size to include in count. It mean we need to have some way to delete old file.
By the way, each revision create new copy of file so, it currently mean weird case like not able to rename big file, etc... If problem could happened with each new revision this means also check should be done prior revision and we have to speculate on future size of workspace according to current revision which is not so trivial.

**Comment by inkhey** [comment]
Problem related to ui should be also fixed : 
As user can be owner of workspace but not into the workspace, we need to have some kind of ui to know which workspace are ours and size limitation on them. That's a different list from workspace membership/ notification.

**Comment by PhilippeAccorsi** [comment]
Idea we have discuss in meeting with @lebouquetin is:

We check size before update. if the size limit is not reached, user can update file (or new revision for other kind of content). After that, if user try to update again, if size limit is reached user can't update file (or new revision of content).

> other problem with this is about old revisions size to include in count. It mean we need to have some way to delete old file.
> By the way, each revision create new copy of file so, it currently mean weird case like not able to rename big file, etc... If problem could happened with each new revision this means also check should be done prior revision and we have to speculate on future size of workspace according to current revision which is not so trivial.

**Comment by PhilippeAccorsi** [comment]
Example:

The Sharedspace have just 10Mo free space available. The user want to update documentation with some picture and zise of this document is bigger than 10Mo. When user try to save this update, tracim says "free space available so you can save your document".

After that free space available is zero. So at this time the user can't update agin document or create something else.

**Comment by inkhey** [comment]
Work in progress branch here: https://github.com/tracim/tracim/tree/feature/2029__limit_size_of_workspace  with new specification.

This means that a content which is active (not deleted and not archived) will count in workspace size for all his revision file size.

**Comment by PhilippeAccorsi** [comment]
> Work in progress branch here: https://github.com/tracim/tracim/tree/feature/2029__limit_size_of_workspace with new specification.
> 
> This means that a content which is active (not deleted and not archived) will count in workspace size for all his revision file size.
> There is actually only check in upload file endpoint, so restoring archive/deleted file may grow up workspace size significantly.
> 
> @PhilippeAccorsi did you remember any discussion about doing such check ?

I think its the same like when we try to upload file. If limit is not reach, you can restore file. After that if you want to make something, if limit is reach, you can't upload or restore more file.

**Comment by PhilippeAccorsi** [comment]
This feature not working if I used shared feature in upload.No verification is make about size limit.
After uploading file I can move file from "Received files" to another folder or directly in worksapce.

Need correction of this.
After reflexion I think we can use same error with same message about no more space in this workspace.

**Comment by inkhey** [comment]
This need some work:
- need to check content_length per file given. This require to find and verify if content_length checked doesn't mean reading whole file. (i have to check `content_api.check_upload_size(os.fstat(_file.file.fileno()).st_size, upload_permission.workspace)` 
)
- Frontend cannot handle easily exception at post, we do need to give information to frontend before to avoid weird redirection. It's not clear how we should handle this.

**Comment by inkhey** [comment]
https://github.com/tracim/tracim/pull/2384 is a simple fix to do only workspace size check. We should think about doing a better check later.

**Comment by PhilippeAccorsi** [comment]
Frontend is not developed to show error message for this kind of feature (available in 2.4.x)
Verified.
