### ISSUE TITLE
Feature: Share and upload files

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#2030]
## Feature description

A Tracim user can share a file so that others (not necessarily Tracim users) can download it and he can also give access to others to upload files to him.
- File sharing will be done via e-mail (personal link) invitation or a public link. The shares may or may not have a protected password.
- The uploaded files will be in a folder of their own on the respective shared space. Access to the upload URL will also be given via e-mail or public link, and may or may not have a password to protect it.
- It will be possible for the Tracim user to stop sharing a file/the upload access of an e-mail/link at any time.
- We are going to have email notifications when sharing/upload or stopping sharing/upload.

## Context

Today, if you want to share files with a limited number of people, you must create a shared space and invite only the people with whom you want to share your files / information. It is not possible to share files with a person who does not have a Tracim account.

## Backend implementation

When receiving files, the backend should:

1. check if the password it’s the good one to the upload link
2. create inside the upload folder a subfolder named something like: `2019-07-12 @ 14:19:30 - from Michel Dupont`
3. for each received file:
    1. store the file in the subfolder
    2. add a comment with user message, written like: "Message from Michel Dupont: xxx"

Sharedspace collaborators should be notified with message + list of files + link to the folder:

```
Michel Dupont shared some files with you:

xxx

The attached files are the following ones:

- cv.pdf
- copie carte identite.png
- ...

Go to [the files on tracim](https://xxx)

```

**Comment by inkhey** [comment]
Backend difference between normal folder and shared_folder : 

|                                                                                     | Folder                     | Shared Folder                  |
|----------------------------------------------------------------------------------------|----------------------------|--------------------------------|
| Location                                                                               | Anywhere in workspace tree | Always root for workspace tree |
| **Caracteristics**                                                                         |                            |                                |
| label                                                                                   | Anything, can be changed   | Fixed and always the same      |
| description                                                                            | Can be changed             | Fixed ?                        |
| Sub-content-types                                                                      | Anything, can be changed   | Anything ? Cannot be changed.  |
| Status                                                                                 | Anything, can be changed   | Cannot be changed              |
| Deleted/archived                                                                       | Yes                        | No, always visible             |
| **Endpoints**                                                                           |                            |                                |
| GET /api/v2/workspaces/{workspace_id}/folders/{content_id}                             | Ok                         | Ok                             |
| PUT /api/v2/workspaces/{workspace_id}/folders/{content_id}                             | Ok                         | Should be disabled             |
| GET /api/v2/workspaces/{workspace_id}/folders/revisions                                | Ok                         | Ok                             |
| PUT /api/v2/workspaces/{workspace_id}/folders/{content_id}/status                      | Ok                         | Should be disabled             |
|                                                                                        |                            |                                |
| PUT /api/v2/workspaces/{workspace_id}/contents/{content_id}/archived                   | Ok                         | Should be disabled             |
| PUT /api/v2/workspaces/{workspace_id}/contents/{content_id}/archived/restore           | OK                         | Should be disabled             |
| PUT /api/v2/workspaces/{workspace_id}/contents/{content_id}/trashed                    | Ok                         | Should be disabled             |
| PUT /api/v2/workspaces/{workspace_id}/contents/{content_id}/trashed/restore            | Ok                         | Should be disabled             |
| PUT /api/v2/users/{user_id:\d+}/workspaces/{workspace_id}/contents/{content_id}/read   | Ok                         | Ok                             |
| PUT /api/v2/users/{user_id:\d+}/workspaces/{workspace_id}/contents/{content_id}/unread | Ok                         | Ok                             |
| PUT /api/v2/workspaces/{workspace_id}/contents/{content_id}/move                       | Ok                         | Should be disabled             |
|                                                                                        |                            |                                |
| **Webdav : FolderResource**                                                                |                            |                                |
| delete                                                                                 | Ok                         | Forbidden                      |
| move recursive                                                                         | Ok                         | Forbidden                      |
| others                                                                                 | Ok                         | Ok                             |

**Comment by PhilippeAccorsi** [comment]
The code about upload file is merge in develop branch but is commented because backend is not finished.
This solution is make to try 2.4.0_rc1 with download feature.

**Comment by PhilippeAccorsi** [comment]
Verified.
