### ISSUE TITLE
add possibility to limit number of sharedspace available for each user

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2031]
## Feature description

- We need to define how many sharedspace each user can create.
- at the moment we define in the config file the number of sharedspaces peruser
    - 0 means no mlimit

note: do not count deleted sharedspaces

Informations to add in the APIs:

- add max_sharedspace_per_user in config endpoint
- add owned_sharedspaces in user sharedspaces endpoint + query filters that allow to choose to get owned sharedspaces or sharedspaces with a role or all sharedspaces (by default)
- add owner in sharedspace serialisation

## Context

Need this feature for hosting.

## Impacted components

- *backend*
- *frontend*

**Comment by inkhey** [comment]
This probably means that we should know who is the creator of one workspace, this information is not stored yet.

We should find a solution to make this work also in context of migration of database. 
What should be the behavior for workspace that already exist ?

**Comment by inkhey** [comment]
this look depending on #2027

**Comment by inkhey** [comment]
begin a fix here : https://github.com/tracim/tracim/tree/fix/2031__limit_number_of_workspaces_allowed_for_user

This code, does a default limit of 100 workspace per user and return error when creating new workspace over this limit. The limit can be setted only by database.

We do need to explicit : 
- how should we change this value (specific endpoint available only for admin, something else ?)
- Which value to use when creating/inviting a new account ?
- if we handle "unlimited case", this can be tricky as we cannot use none which can already mean "no change". current solution is consider that 100+ value is ok for most case so no need for unlimited if maximum value is easy to set.

**Comment by PhilippeAccorsi** [comment]
Description edited this morning with new information.

**Comment by inkhey** [comment]
not sure about api : 
current filter on workspace user are : 
"show_workspace_with_role" and  "show_owned_workspace" both as query bool (0 or 1 value) parameter.

**Comment by inkhey** [comment]
@gbonaspetti , @basilelegal , with the new spec here. it mean 
`/api/v2/users/me/workspaces` and `/api/v2/users/{user_id}/workspaces` return not same default value as before. You should set `show_owned_workspace` query param to 0 to retrieve legacy behavior. 
Don't know how important this change may affect frontend.

**Comment by inkhey** [comment]
after discussion avec @Skylsmoi, seems that's not a big refactor to make thing works correctly in frontend.

so all previous call to /api/v2/users/me/workspaces and /api/v2/users/{user_id}/workspaces should be changed to add query param show_owned_workspace to 0.

**Comment by PhilippeAccorsi** [comment]
Tested with modification in development.ini. Frontend is not done for the moment.
Frontend is done in this issue or in other issue @inkhey ?

**Comment by inkhey** [comment]
@PhilippeAccorsi issue for frontend is https://github.com/tracim/tracim/issues/2345

**Comment by PhilippeAccorsi** [comment]
Ok. 
Verified.
