### ISSUE TITLE
url link in timeline is not visible when background color is blue

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2032]
## Bug description & symptom

When background color of comment is blue, its not possible to see url link.

## Diagnostic

Color of url link is blue.

## Expected

- [ ] url link is always visible

## How to reproduce

- open thread or timeline of one content
- Write comment with url link

## Screenshots

![Sélection_009](https://user-images.githubusercontent.com/25848257/60337148-86649080-99a2-11e9-9c11-7f1066065644.jpg)

## Impacted components

- *frontend*
- *htmldoc / file / thread app*

**Comment by Skylsmoi** [comment]
changes:
links in Timeline comments are now always underlined and of the same color as the text. Text also now appear in bold on mouse over

**Comment by PhilippeAccorsi** [comment]
Verified.
