### ISSUE TITLE
its possible to create two user account with same email

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2034]
## Bug description & symptom

If you create user account with email "toto@toto.toto" and another one with "Toto@toto.toto", 2 account is created in tracim. But email is not case sensitive for provider.

## Diagnostic

*Optional - explain what has been found and what is not yet clear. If unknown, write "unknown".*

## Expected

- [ ] case sensitive is not apply for email input
- [ ] fix also #1470

## How to reproduce

- create account "toto@toto.toto"
- create user account "Toto@toto.toto"
=> 2 account exist for the same user (in reallity just one email exist for provider)

## Impacted components

- *backend*
- *frontend*

**Comment by inkhey** [comment]
sensitiveness of email is tricky : https://www.techjunkie.com/are-emails-case-sensitive/

https://tools.ietf.org/html/rfc5321
The local-part of a mailbox MUST BE treated as case sensitive.

**Comment by inkhey** [comment]
fix for this and #1470, made #2043.

**Comment by PhilippeAccorsi** [comment]
Verified.
