### ISSUE TITLE
Auto-reply received by mail are included in comment thread

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#2036]
## Bug description & symptom

Empêcher que les auto-reply d'absence viennent polluer une conversation : ça
n'est arrivé qu'une fois mais retrouver un message d'absence au milieu de la
discussion, ça ne va pas (potentiellement il peut y en avoir beaucoup).

## Diagnostic

*...*

## Expected

*...*

## Context and version information

*...*

## Prerequisites

*...*

## How to reproduce

*...*

## Impacted components

- *backend*

**Comment by inkhey** [comment]
@lebouquetin Should we disable other type of mail generated by software or should we very specific to "auto-reply" message ?

**Comment by PhilippeAccorsi** [comment]
Verified.
