### ISSUE TITLE
update version, changelog and ready to make tag 2.3.1

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2044]
## expected

- [x] update changelog
- [x] Ready to create tag 2.3.1
- [x] Update version of tracim backend in `backend/tracim_backend/lib/core/system.py`
- [x] Update version of tracim front in `frontend/src/version.json`

**Comment by tracim** [comment]
check issue for changelog, some issue as moved.

**Comment by PhilippeAccorsi** [comment]
Verified.
