### ISSUE TITLE
Bug with the click area to open the contents

### ISSUE THREAD

**Issue by LucBarry** [tracim/tracim#2046]
## Bug description & symptom

On firefox and Chrome when you want to open a document, there is a area (top and bottom) where the left click does not work.

## Expected

When you click anywhere on the document it opens.

## How to reproduce

Click on the upper or lower end of the document title area

## Screenshots

![bug zone bleu](https://user-images.githubusercontent.com/39124679/60523278-b9808a00-9cea-11e9-9a00-dcadc87901f4.gif)

## Impacted components

*Optional - list components which will be impacted.*

Frontend

**Comment by metzgegu** [comment]
#1986

**Comment by PhilippeAccorsi** [comment]
Verified.
