### ISSUE TITLE
[Regression] Content title : long titles are not limited

### ISSUE THREAD

**Issue by celiamgtt** [tracim/tracim#2058]
## Bug description & symptom

Content title : long titles are not limited, if title is too long, it pushes the buttons away & get out the container (tested on folders, document titles & upload titles).

## Expected

If title is too long don't show entire title. Show title if mouseover.

## Screenshots

![title_too_long](https://user-images.githubusercontent.com/50453784/60603543-43495980-9db6-11e9-9b00-0da7019b518d.gif)

## Impacted components

- frontend

## Extra information

Linked with https://github.com/tracim/tracim/issues/1002

**Comment by PhilippeAccorsi** [comment]
I think this is a regression since new wrapper for drag and drop.

**Comment by PhilippeAccorsi** [comment]
Verified.
