### ISSUE TITLE
Update frontend dependencies

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2064]
## Feature description

Some dependencies are a bit old.
Do a full upgrade of every dependencies

## Context

It is important to keep the dependencies up to date

## Impacted components

frontend,
frontend_lib
every apps

### EDIT 2019-08-05
Due to many issues related to [this](https://reactjs.org/docs/error-decoder.html/?invariant=321), some workaround has been implemented. ("file:" in package.json)

It appears that this workaround in insufficient. The problem can still occur.

It has been decided that, for Tracim v2.4, we won't update React to 16.8.x. We will cap it at 16.7.0 and we will address this for Tracim v2.5.

**Comment by Skylsmoi** [comment]
Pour les frontent : (@basile @giulia @guillaumem)
Je viens de merger la PR sur l'update des dépendances.

Cela signifie que votre prochain pull de develop va :
- si votre branche a beaucoup de changement, créer des merges conflicts
- vous créer des erreurs de linting
___
Les erreurs de lintings sont due à la nouvelle version de Standard.js qui rajoute la règle suivante :
``` javascript
const book = {author: 'Damasio', title: 'La horde du contrevent'} // old standard was ok with that, new wont
const book2 = { author: 'Damasio', title: 'La zone du dehors' } // new standard is ok with that
```
La différence est l'espace à rajouter après l'accolade ouvrante d'un objet inliné et l'espace avant la fermante.
___
:warning: Ne faite le pull QUE quand votre branche est stable. :warning: 
___
Ce qu'il vous faudra faire suite au pull :
- delete tous vos dossiers node_modules
- delete tous vos fichier package-lock.json
- installer toutes vos dépendances
- rebuild tout le front

Voici les commandes pour delete les node_modules et package-lock facilement :

:arrow_right:  :warning: A EXECUTER DEPUIS LE ROOT DE VOTRE REPO TRACIM (exemple chez moi : `/home/come/repo/tracim`)

``` bash
rm -rf frontend/node_modules/
rm frontend/package-lock.json

rm -rf frontend_app_admin_workspace_user/node_modules/
rm frontend_app_admin_workspace_user/package-lock.json

rm -rf frontend_app_agenda/node_modules/
rm frontend_app_agenda/package-lock.json

rm -rf frontend_app_file/node_modules/
rm frontend_app_file/package-lock.json

rm -rf frontend_app_folder_advanced/node_modules/
rm frontend_app_folder_advanced/package-lock.json

rm -rf frontend_app_html-document/node_modules/
rm frontend_app_html-document/package-lock.json

rm -rf frontend_app_thread/node_modules/
rm frontend_app_thread/package-lock.json

rm -rf frontend_app_workspace/node_modules/
rm frontend_app_workspace/package-lock.json

rm -rf frontend_app_workspace_advanced/node_modules/
rm frontend_app_workspace_advanced/package-lock.json

rm -rf frontend_lib/node_modules/
rm frontend_lib/package-lock.json
```

Puis faire :
``` bash
./install_frontend_dependencies.sh
./build_full_frontend.sh
```

**Comment by PhilippeAccorsi** [comment]
Bug with hook is not solved.
To reproduce:
- modify development.ini => `email.notification.activated = True` (with wrong smtp parameter, use default value for exemple)
- restart tracim
- go to admin > user
- try to create new user
=> blanck page appear with error in console (backend says error 500)

**Comment by PhilippeAccorsi** [comment]
Error "Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. " appear when we switch from agenda to admin user or inverse.

**Comment by Skylsmoi** [comment]
see issue description "EDIT"

**Comment by PhilippeAccorsi** [comment]
We not see more regression.

Verified.

**Comment by Skylsmoi** [comment]
Something to look at: https://github.com/whitecolor/yalc

it appears it can workaround the npm link issue with react 16.8+
