### ISSUE TITLE
Better token system for collabora

### ISSUE THREAD

**Issue by basilelegal** [tracim/tracim#2074]
The actual token system is based on the cookie system.
It will create a new db session for everycall of collabora.

Find a better solution that can be used for further need.

**Comment by inkhey** [comment]
> The actual token system is based on the cookie system
> It will create a new db session for everycall of collabora.
> 
> Find a better solution that can be used for further need.

In tracim code, database session change at each request, that's normal.
beaker session are not "database" session, it's something different related to authentication stuff and cookie.

We can accept some kind of token auth for tracim (so wopi endpoint too) , so we can accept to any endpoint with something like : 
`http://localhost:6543/api/v2/auth/whoami?auth_token=iu0aMCsaepPy6ULphSX5PT32oPvKkM5dPl131knIDq9Cr8OUzzACsuBnpSJ_rE9XkGjmQVawcvyCHLiM4Kr6NA`

**Comment by inkhey** [comment]
After discussion, we convert hack auth to a new auth mecanism.
We can now auth to tracim using user `access_token` as query parameter.

http://localhost:6543/api/v2/auth/whoami?access_token=iu0aMCsaepPy6ULphSX5PT32oPvKkM5dPl131knIDq9Cr8OUzzACsuBnpSJ_rE9XkGjmQVawcvyCHLiM4Kr6NA

**Comment by inkhey** [comment]
this is added to #2139

**Comment by PhilippeAccorsi** [comment]
Ok. I think thats ok.
