### ISSUE TITLE
Page admin user doesn't work anymore

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2076]
## Bug description & symptom

The page admin user fails at getting the user from api.

## Diagnostic

The api is called with an user id to `undefined`

## Expected

The api is called with the proper user id in the url

## Context and version information

It has been introduced with a naming refactor.
The thing to change is here https://github.com/tracim/tracim/blob/develop/frontend/src/container/Tracim.jsx#L262.
The `PAGE.ADMIN.USER_EDIT(':iduser')` has been missed in the refactor, it needs to be `PAGE.ADMIN.USER_EDIT(':userid')`

## How to reproduce

- login as admin
- go to admin user
- click on a user

## Impacted components

- frontend

**Comment by lebouquetin** [comment]
@Skylsmoi the admin is broken in 2.3.1?

**Comment by Skylsmoi** [comment]
@lebouquetin No, but develop is

**Comment by lebouquetin** [comment]
By the way, naming the var `props.match.params.userid` is better than `props.match.params.iduser` (id is a property of user) ; I feel like the refactor is incorrect

**Comment by Skylsmoi** [comment]
yes, the refactor is fine, my issue isn't.
I'm fixing it

**Comment by lebouquetin** [comment]
ok :)

**Comment by Skylsmoi** [comment]
fixed

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi this is fixed?
With specific MR or directly in another?

**Comment by Skylsmoi** [comment]
no it's not

**Comment by PhilippeAccorsi** [comment]
Verified.
