### ISSUE TITLE
Error using collabora docker on server dev

### ISSUE THREAD

**Issue by basilelegal** [tracim/tracim#2080]
Running the docker command working on a local machine (debian) but cause errors on the server (debian jessie or stretch).

Command used to start collabora image:

`sudo docker run -d -t -p 9980:9980 -e "domain=172.0.0.1" -e "username=admin" -e "password=S3cRet" -e "SLEEPFORDEBUGGER=0" --cap-add MKNOD --restart always collabora/code`

Error visible with this command `docker logs -f {container_id}`

```
frk-00032-00032 2019-07-01 10:26:35.119723 [ forkit ] INF  Ignored setting RLIMIT_NOFILE to unlimited.| common/Seccomp.cpp:256
loolforkit version details: 4.0.4 - 305832f
frk-00032-00032 2019-07-01 10:26:35.119757 [ forkit ] FTL  Capability cap_sys_chroot is not set for the loolforkit program.| kit/ForKit.cpp:170
frk-00032-00032 2019-07-01 10:26:35.119775 [ forkit ] FTL  Capability cap_mknod is not set for the loolforkit program.| kit/ForKit.cpp:170
frk-00032-00032 2019-07-01 10:26:35.119791 [ forkit ] FTL  Capability cap_fowner is not set for the loolforkit program.| kit/ForKit.cpp:170
FATAL: Capabilities are not set for the loolforkit program.
Please make sure that the current partition was *not* mounted with the 'nosuid' option.
If you are on SLES11, please set 'file_caps=1' as kernel boot option.
```

**Comment by PhilippeAccorsi** [comment]
@basilelegal Which kind of command ?
You have this error when you start tracim? Where you seen this error?

**Comment by basilelegal** [comment]
Sorry this is a collabora related issue

**Comment by PhilippeAccorsi** [comment]
No error appear when starting this command on Ubuntu 18.04.2 LTS

**Comment by PhilippeAccorsi** [comment]
@inkhey and @basilelegal can you write here your OS version and docker version you have used for started this command?

**Comment by inkhey** [comment]
@PhilippeAccorsi 
 
```
❯ docker -v                                                                                                                                                
Docker version 18.09.7, build 2d0083d

```
```
 ❯ lsb_release -da
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.9 (stretch)
Release:        9.9
Codename:       stretch
```

It work correctly if y set ssl to disable like this : 

```
❯ sudo docker run -d -t -p 9980:9980 -e "domain=172.0.0.1" -e "username=admin" -e "password=S3cRet" -e "SLEEPFORDEBUGGER=0" --cap-add MKNOD -e "extra_params=--o:ssl.enable=false" --restart always collabora/code
```

and if i add my ip to allowed origin for backend storage in `/etc/loolwsd/loolwsd.xml` (this file should stay readable for collabora process !)
```
    <storage desc="Backend storage">
        <filesystem allow="false" />
        <wopi desc="Allow/deny wopi storage. Mutually exclusive with webdav." allow="true">
            <host desc="Regex pattern of hostname to allow or deny." allow="true">my_ip</host>
 
```

**Comment by PhilippeAccorsi** [comment]
This parameter `-e "domain=<your-dot-escaped-domain>"` is the WOPI host (https://www.collaboraoffice.com/code/docker/)

So for tracim we need to explicit here each tracim backend server ip or domaine. Look documentation for syntaxes.

**Comment by PhilippeAccorsi** [comment]
For starting collabora on debian without ssl, its necessary to add this in docker command `-e "extra_params=--o:ssl.enable=false --o:ssl.termination=false"` when starting docker image. Also add `-e "domain=xxx\\.xxx\\.xxx\\.xxx"` (replace xxx by your ip adress)

I close this issue because it is just a not good usage of docker image (with necessary parameters)

**Comment by PhilippeAccorsi** [comment]
In some case, this error appear when you have migrate debian version from debien 8 to debian 9 with docker allready installed.

In this case, driver used by container is "aufs" and with this kind of migration its not working (many information about collaboraonline with aufs driver).
You need to backup your docker data, remove docker and delete /var/lib/docker folder, install docker again. After that docker use overlay2 driver and error not appear agian. Problem with driver is about cgroup permission.
