### ISSUE TITLE
Office document app

### ISSUE THREAD

**Issue by basilelegal** [tracim/tracim#2082]
Create a new app for office document, it will add:

A button for dashboard to open creation pop up:
  - title: create office document

A pop up to create a new content:
  - title: new office document
  - input title: 
    - type: text
    - placeholder: Title of the document 
  - input file type:
    - type: radio
    - label: Document type
    - choices: Text, Spreadsheet, Presentation

On submit of this pop up, open the new route of `file app` =>  `/online_edition/workspace/<id>/file/<id>`.

 Transfer all the inteligence already written in `File.jsx` to create a new container linked to this route.

**Comment by PhilippeAccorsi** [comment]
What I need to test here? Issue is not up-to-date and not related to collabora merge request. 
Also I can see question about color, but this is not solved in MR.

Please update issue, after that I can test something but for the moment its not possible to test (route is also wrong so I don't know if its normal or not).

**Comment by PhilippeAccorsi** [comment]
@basilelegal can you edit/update this issue ?
Look last comment.

**Comment by basilelegal** [comment]
done in #2139

**Comment by basilelegal** [comment]
done in #2139

**Comment by PhilippeAccorsi** [comment]
Verified.
