### ISSUE TITLE
opening folder url not scroll to show opened folder

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2087]
## Bug description & symptom

When someone shared folder link with you, if you open this link you arrive directly on top of page. If folder is not visible directly in page, you do not understand what is going on. You need to scroll manually to see which folder is opened.

## Diagnostic

*"unknown".*

## Expected

- [ ] scroll directly to opened folder when you open folder url

## How to reproduce

- shared folder url in one big sharedspace (with many content)
- open this url in new tab
=> you arrive in top of the page and you don't understand what is going on, what is expected.

## Impacted components

- *frontend*

**Comment by metzgegu** [comment]
**The problem is :** 
You share a url with a list of folders opened : `folder_open=8733,7929,8739,7564,7593`, you don't share one folder but all the workspace with this parameter, so tracim can't know which folder do you want to share with this url

**Comment by PhilippeAccorsi** [comment]
Ok.
I think we can use last folder openned (last id in url).
This is possible to scroll to this id or not?

**Comment by metzgegu** [comment]
Yes it is possible 
cf. [fix/2087_scroll_to_last_folder_open_in_the_url](https://github.com/tracim/tracim/tree/fix/2087_scroll_to_last_folder_open_in_the_url)
but I need to discuss with @Skylsmoi to find (maybe) a better solution

**Comment by Skylsmoi** [comment]
@PhilippeAccorsi @metzgegu 
Shouldn't this issue also include a scroll for when opening a content ?

**Comment by PhilippeAccorsi** [comment]
I think this issue is just for folder. If you open content url, the content is automatically openned so you understand what other user share with you.

But in case of folder, you don't know.

Is it complecated to scroll to openned content (like html doc)?
@lebouquetin do you have an idea if its necessary in this issue?

**Comment by Skylsmoi** [comment]
No, it's not more complicated.
I agree that having the feature for folders is the most important. But it would be more consistent to also have it for content.
Btw @metzgegu, if I'm not mistaken, the way it's implemented right now will scroll to the last opened folder even if a content is open.
So I guess we should either not scroll to folder if there is a content to open or scroll to the content.
In my opinion, scroll to the content is better

**Comment by lebouquetin** [comment]
@Skylsmoi @PhilippeAccorsi @metzgegu it's better to always scroll to "active" content (ie opened content or opened folder)

**Comment by PhilippeAccorsi** [comment]
Verified.

**Comment by inkhey** [comment]
@Skylsmoi there is a pending branch https://github.com/tracim/tracim/tree/fix/2087_scroll_to_last_folder_open_in_the_url about theses fix, did you know any reason to keep it ?
