### ISSUE TITLE
Update: changelog, version of frontend and backend, make sure documentation is update

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2088]
- [x] changelog is up-to-date
- [x] known issue are present in changelog
- [x] backend version is 2.4 in `backend/tracim_backend/lib/core/system.py`
- [x] frontend version is 2.4 in `frontend/src/version.json`
- [x] Ready to create tag 2.4

**Comment by PhilippeAccorsi** [comment]
Add information about known issue for this bug with firefox-esr on stretch https://github.com/tracim/tracim/issues/2062

**Comment by PhilippeAccorsi** [comment]
Change elasticsearch running command in documentation by this one => `docker run -d -p 9200:9200 -p 9300:9300 --name elasticsearch -v esdata:/usr/share/elasticsearch -v esconfig:/usr/share/elasticsearch/config -e "discovery.type=single-node" -e "cluster.routing.allocation.disk.threshold_enabled=false" elasticsearch:7.0.0`

With this command:
- Container name is "elasticsearch"
- Volume are available for data and conf => stopping elasticsearch (and restart with docker run) not lost index.

**Comment by PhilippeAccorsi** [comment]
Add known issue : https://github.com/tracim/tracim/issues/2219

**Comment by inkhey** [comment]
changelog update should add information about no support for lock mecanism in collaborative edition.

**Comment by PhilippeAccorsi** [comment]
This issue need to be finished when we want to create stable version of tracim 2.4.0

**Comment by PhilippeAccorsi** [comment]
Verified.
