### ISSUE TITLE
Missing api call to /api/v2/system/config when getting a disconnection

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2091]
## Bug description & symptom

When loading Tracim without being logged and getting a redirection to `/ui/login?dc=1` and logging, the call to the endpoint /api/v2/system/config is missing.

You then, can't create users through admin user because the endpoint expect a value for `email_notification` which is missing.

It then fails with an error 500

## Diagnostic

In case of having the `?dc=1` in url, you wont call the getConfig() in here: https://github.com/tracim/tracim/blob/develop/frontend/src/container/Login.jsx#L75

Note that you don't usually see the `?dc=1` in the url since you get automatically redirected to `/ui/login`

## Expected

The endpoint api/v2/system/config is call in every cases

## How to reproduce

- disconnect your account
- close the tracim tab
- open a new tab
- connect to this url `/ui/login?dc=1`
- connect to tracim
- create a new user through admin user
- you get an error 500

## Impacted components

- Frontend

**Comment by PhilippeAccorsi** [comment]
Verified.
