### ISSUE TITLE
[Regression] blank page visible if I open Shared spaces and notifications in user profile after comming from Admin > users

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2096]
## Bug description & symptom

If I click on Shared spaces and notifications in user profil after opening this profile from administration users, A blank page is visible with this error in console:
~~~
TypeError: "n is undefined"
    r https://xxxx/assets/tracim.app.js:8
    fi https://xxxx/assets/tracim.app.js:8
    fi https://xxxx/assets/tracim.app.js:8
    Qo https://xxxx/assets/tracim.vendors~app.js:81
    Di https://xxxx/assets/tracim.vendors~app.js:81
    Ka https://xxxx/assets/tracim.vendors~app.js:81
    qa https://xxxx/assets/tracim.vendors~app.js:81
    Tu https://xxxx/assets/tracim.vendors~app.js:81
    Eu https://xxxx/assets/tracim.vendors~app.js:81
    Ru https://xxxx/assets/tracim.vendors~app.js:81
    En https://xxxx/assets/tracim.vendors~app.js:81
tracim.vendors~app.js:81:74997
~~~

## Diagnostic

*"unknown".*

## Expected

- [x] Its possible to open `Shared spaces and notifications` correctly
- [ ] ~write cypress test about this regression~

## Context and version information

Tracim 2.3.1

## Prerequisites

To test on develop branch, you need this fix first https://github.com/tracim/tracim/issues/2076

## How to reproduce

- On serve tracim 2.3.1
- activate email notification
- Create 2 users
- create one workspace
- add this two users in this workspce
- go in Administration > users
- Click on name of one users
=> now you can see profile of this users
- click on `Shared spaces and notifications`
=> tracim show blank page 

## Impacted components

* "unknown"*

**Comment by metzgegu** [comment]
We can't write cypress test because now in our cypress test config, we don't have e-mail notification enabled

**Comment by PhilippeAccorsi** [comment]
I think we need to start two kind of cypress test. First, each test where email notification is not necessary, second, each test where email notification is necessary.
In this case, we just need to activate email notification (without smtp configuration).

I think we need to add new test in travis with specific config of backend (config with email notification).

**Comment by PhilippeAccorsi** [comment]
@inkhey what do you used to test email in backend test? Do you use specific config for that.

**Comment by inkhey** [comment]
@PhilippeAccorsi we do support email notification test with mailhog feature, there is many working example in config. It mean specific configuration for test but also specific fixture for mailhog.
`
test_mail_notification.py  
`
show some examples

```
@pytest.mark.usefixtures("base_fixture")
@pytest.mark.usefixtures("default_content_fixture")
@pytest.mark.parametrize("config_section", [{"name": "mail_test"}], indirect=True)
class TestNotificationsSync(object):
    def test_func__create_user_with_mail_notification__ok__nominal_case(
        self, user_api_factory, mailhog
    ):
        api = user_api_factory.get()
        u = api.create_user(
            email="bob@bob",
            password="password",
            name="bob",
            timezone="+2",
            lang="fr",
            do_save=True,
            do_notify=True,
        )
        assert u is not None
        assert u.email == "bob@bob"
        assert u.validate_password("password")
        assert u.display_name == "bob"
        assert u.timezone == "+2"

        # check mail received
        response = mailhog.get_mailhog_mails()
        headers = response[0]["Content"]["Headers"]
        assert headers["From"][0] == "Tracim Notifications <test_user_from+0@localhost>"
        assert headers["To"][0] == "bob <bob@bob>"
        assert headers["Subject"][0] == "[TRACIM] Created account"

```

**Comment by Skylsmoi** [comment]
I have merged the PR fixing this issue since it might take a little while before we are up and ready for running cypress with email activated
I have created a specific issue for it here https://github.com/tracim/tracim/issues/2116

**Comment by PhilippeAccorsi** [comment]
I think this issue is not correctly corrected.
I have new case about notification and blank page.

**Comment by PhilippeAccorsi** [comment]
Its not possible to activate notification and if I tried to open Shared spaces and notifications directly from user button in header, I have the blank page.

**Comment by PhilippeAccorsi** [comment]
Verified.
