### ISSUE TITLE
Feature: Share and upload files

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2101]
## Feature description

A Tracim user can share a file so that others (not necessarily Tracim users) can download it and he can also give access to others to upload files to him.
- File sharing will be done via e-mail (personal link) invitation or a public link. The shares may or may not be password protected.
- The uploaded files will be available in a virtual dedicated folder (with content_id -1) on the respective shared space. Access to the upload URL will also be given via e-mail or public link, and may or may not be password protected.
- It will be possible for Tracim users to stop sharing a file/the upload access of an e-mail/link at any time.
- We are going to have email notifications when sharing/upload or stopping sharing/upload.

## Context

Today, if you want to share files with a limited number of people, you must create a shared space and invite only the people with whom you want to share your files / information. It is not possible to share files with a person who does not have a Tracim account.

## Backend implementation

When receiving files, the backend should:

1. check if the password it’s the good one to the upload link
2. create inside the upload folder a subfolder named something like: `2019-07-12 @ 14:19:30 - from Michel Dupont`
3. for each received file:
    1. store the file in the subfolder
    2. add a comment with user message, written like: "Message from Michel Dupont: xxx"

Sharedspace collaborators should be notified with message + list of files + link to the folder:

```
Michel Dupont shared some files with you:

xxx

The attached files are the following ones:

- cv.pdf
- copie carte identite.png
- ...

Go to [the files on tracim](https://xxx)

```

Backend difference between normal folder and shared_folder : 

|                                                                                     | Folder                     | Shared Folder                  |
|----------------------------------------------------------------------------------------|----------------------------|--------------------------------|
| Location                                                                               | Anywhere in workspace tree | Always root for workspace tree |
| number                                                                               | Any number | unique per workspace |
| **Caracteristics**                                                                         |                            |                                |
| label                                                                                   | Anything, can be changed   | Fixed and always the same      |
| description                                                                            | Can be changed             | Fixed ?                        |
| Sub-content-types                                                                      | Anything, can be changed   | Anything ? Cannot be changed.  |
| Status                                                                                 | Anything, can be changed   | Cannot be changed              |
| Deleted/archived                                                                       | Yes                        | No, always visible             |
| **Endpoints**                                                                           |                            |                                |
| GET /api/v2/workspaces/{workspace_id}/folders/{content_id}                             | Ok                         | Ok                             |
| PUT /api/v2/workspaces/{workspace_id}/folders/{content_id}                             | Ok                         | Should be disabled             |
| GET /api/v2/workspaces/{workspace_id}/folders/revisions                                | Ok                         | Ok                             |
| PUT /api/v2/workspaces/{workspace_id}/folders/{content_id}/status                      | Ok                         | Should be disabled             |
|                                                                                        |                            |                                |
| PUT /api/v2/workspaces/{workspace_id}/contents/{content_id}/archived                   | Ok                         | Should be disabled             |
| PUT /api/v2/workspaces/{workspace_id}/contents/{content_id}/archived/restore           | OK                         | Should be disabled             |
| PUT /api/v2/workspaces/{workspace_id}/contents/{content_id}/trashed                    | Ok                         | Should be disabled             |
| PUT /api/v2/workspaces/{workspace_id}/contents/{content_id}/trashed/restore            | Ok                         | Should be disabled             |
| PUT /api/v2/users/{user_id:\d+}/workspaces/{workspace_id}/contents/{content_id}/read   | Ok                         | Ok                             |
| PUT /api/v2/users/{user_id:\d+}/workspaces/{workspace_id}/contents/{content_id}/unread | Ok                         | Ok                             |
| PUT /api/v2/workspaces/{workspace_id}/contents/{content_id}/move                       | Ok                         | Should be disabled             |
|                                                                                        |                            |                                |
| **Webdav : FolderResource**                                                                |                            |                                |
| delete                                                                                 | Ok                         | Forbidden                      |
| move recursive                                                                         | Ok                         | Forbidden                      |
| others                                                                                 | Ok                         | Ok                             |

**Comment by PhilippeAccorsi** [comment]
Related to #2030 
@lebouquetin I have put here all information available in frontend issue. You can update this issue with all backend specification.
@inkhey same for you, don't hesitate to update/comment this issue 

When all spec are write here we can start to solved this issue.

**Comment by inkhey** [comment]
After discussion, idea what to not create specific folder and/or type.
Idea is to set parent of content in shared_folder to a negative fixed value like -1.

**Comment by lebouquetin** [comment]
Backend issue for sharing files: #2125 2125

**Comment by gbonaspetti** [comment]
API client side:

`method PUT`    
 `-> _apiURL_/api/v2/workspaces/_workspaceId_ `
 `-> response: as well as the agenda, I need the PUT methods to enable upload and download `
     `    - label: workspace label `
 `    - description: workspace description `
 `    - upload/download_enabled `

`method PUT`    
`     -> _apiUrl_/workspaces/_workspaceId_/share_folder`    
`    	-> response: update the share links list (upload)`    
`    - share_link_list: shareLinkList`    

`method GET `    
`    ->_ apiUrl_/workspaces/_workspaceId_/files/_contentId_/share`    
`    	-> response: the share link list (download)`    

`method PUT`    
`     -> _apiUrl_/workspaces/_workspaceId_/files/_contentId_/share`    
`    	-> response: update the share links list (download)`    
`    - share_link_list: shareLinkList`    

Still to be defined:

- Endpoint to make a direct download (maybe use the parameter `    &force_download=1`     inside the url)
- Share folder id to do
`method PUT`    
`        -> _apiURL_/api/v2/workspaces/_workspaceId_/files/_contentId_`    
 `              -> response: create a file inside the share folder`    
 `                - folderId: share folder`    
     `            - password or not`    
      `            - nameGuest: “GUEST create this”?`    
        `          - comment: in the file’s comments`    
`method GET`    
`     -> _apiUrl_/workspaces/_workspaceId_/folders/_folderId_`    
 `    	-> response: the share link list`

**Comment by tracim** [comment]
@PhilippeAccorsi, what is unclear now?

**Comment by PhilippeAccorsi** [comment]
I think everything it's ok now.

**Comment by inkhey** [comment]
@PhilippeAccorsi Seems that content of this issue is dispatched in other merged issue. This issue should be moved to "need to", no ?

**Comment by PhilippeAccorsi** [comment]
That's ok for me.
Verified.
