### ISSUE TITLE
Create office document popup

### ISSUE THREAD

**Issue by basilelegal** [tracim/tracim#2115]
Make the design for the popup and improve wordings.

Current raw design:
![Screenshot at 2019-07-23 05-14-54](https://user-images.githubusercontent.com/7879232/61699550-19c28480-ad09-11e9-898d-4171a0a4dd67.png)

**Comment by celiamgtt** [comment]
Proposition : 
![Popup  Collabora](https://user-images.githubusercontent.com/50453784/61721558-ef081880-ad68-11e9-9ca1-904f3b424f7d.png)

**Comment by lebouquetin** [comment]
![Collabora original icons](https://user-images.githubusercontent.com/907161/62062139-b795e200-b228-11e9-8bb5-1b2b259dbcc4.jpg)

**Comment by PhilippeAccorsi** [comment]
tested with collaboraOnline.
Verified.
