### ISSUE TITLE
Documentation about new feature (collabor, share content)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2117]
## Expected

- [x] Backend documentation exist to use collabora and libreoffice online (see here for docker information #2080), documentation about how create/run docker image of collabora / libreoffice online and what is necessary to start (modification in development.ini and start/restart tracim)
- [x] Change version of collabora we used
- [x] explain tracim working with libreofficeOnline (like with collabora)

- [x] Backend documentation is up-to-date (ex: setting.md with all env variable)
- [x] This documentation need to be updated for office document https://github.com/tracim/tracim/blob/develop/backend/doc/roles.md
- [x] change docker run command for elasticsearch to use docker volume for data and config
- [x] backend internationalization best practices

- ~~Documentation (small one) about frontend unit test (need to write by frontend dev)~~ This is for 2.4.x version
- ~~User documentation about new functionnality with office tool (frontend documentation)~~ Not done in 2.4.0
- ~~User documentation about new feature : share content~~ Not done in 2.4.0

**Comment by PhilippeAccorsi** [comment]
Issue edited to add frontend unit test documentation missing.

**Comment by PhilippeAccorsi** [comment]
Issue edited.

**Comment by inkhey** [comment]
just added clarification about backend internationalization best practices.

**Comment by PhilippeAccorsi** [comment]
Some information necessary for libreoffice documentation are visible here https://github.com/tracim/tracim/issues/1007

**Comment by inkhey** [comment]
:warning: somes config parameters about default config for public namespace (like default number of namespace limitation,etc ... will be added later).

**Comment by lebouquetin** [comment]
@PhilippeAccorsi Celia and Luc can help for end user documentation

**Comment by PhilippeAccorsi** [comment]
Change elasticsearch running command in documentation by this one => docker run -d -p 9200:9200 -p 9300:9300 -v esdata:/usr/share/elasticsearch -v esconfig:/usr/share/elasticsearch/config -e "discovery.type=single-node" -e "cluster.routing.allocation.disk.threshold_enabled=false" elasticsearch:7.0.0

With this command:

    Volume are available for data and conf => stopping elasticsearch (and restart with docker run) not lost index.

**Comment by inkhey** [comment]
About sharing file, it's important to notice that : 
-  we could share file which are in inbox dir
- moving file in another dir, in another workspace... anywhere doesn't change at all share access. to summarize this more easily :

| origin            | destination        | role user access                                  |  access with token                                                  |
|-------------------|--------------------|---------------------------------------------------|---------------------------------------------------------------------|
|  workpace 1 dir 1 |  workspace 1 dir 2 | doesn't change                                    |  working, no change                                                 
|  workspace 1      |  workspace 2       |   different (according to current workspace role) |   working :warning: unless workspace 2 as _download_ feature disabled |

**Comment by PhilippeAccorsi** [comment]
Last comment information is present in documentation issue for 2.4.x
Verified.
