### ISSUE TITLE
menu in my profile is not correctly translated if I come from admin user interface

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2118]
## Bug description & symptom

I used tracim in french, I go in admin users. After that I click on one name user and its open account configuration for this user. If I changed language from french to english, menu stay in french. (Profil, mot de passe, etc. stay visible in french)

## Diagnostic

*"unknown"*

## Expected

- [ ] menu is translated automaticaly when I change language in user interface.

## Context and version information

- Desktop environment (if applicable)
    - *OS: ubuntu*
    - *Browser firefox*
    - *Version 68*

## How to reproduce

- Open tracim (sign in)
- put interface in french
- go in admin > users
- click on one name of user
=> account config is openned
- change language of user interface
=> all text is translated but not text in menu

## Screenshots

![translation_problem_user_account](https://user-images.githubusercontent.com/25848257/61805003-45428d80-ae35-11e9-9af8-4dada6a1263d.gif)

## Impacted components

- *frontend*

## Extra information

**Comment by PhilippeAccorsi** [comment]
Still exist in 2.7.2

**Comment by Quiwy** [comment]
@PhilippeAccorsi : I think this is not relevant anymore as language is selected in "account settings" and not in header anymore.
Do you confirm it?

**Comment by PhilippeAccorsi** [comment]
I think it is true, because we can't change anymore the language without recharging page.
I close this issue.
