### ISSUE TITLE
[regression] can't modify two shared space in a row 

### ISSUE THREAD

**Issue by ecureuilfourbe** [tracim/tracim#2121]
## Bug description & symptom

After I open or modify shared space's option, I need to refresh the page to open another one or the same 

## Diagnostic
unknown

## Expected

I open and modify or close one shared space option, then i can do the same directly after without refreshing the page.

## Context and version information

Ubuntu server 18.04.2

Tracim version v2.3.1

- Desktop environment (if applicable)
    - Windows 7
    - Mozilla Firefox 
    - 52.6.0 (64 bits)

## How to reproduce

1. Log on as Global Manager
2. Click on the "administration" tab
3. Click on "shared spaces"
4.Click on one of your "shared space"
5.Close right away
6.Click on another "shared space"
7. *See error*

Busan

**Comment by PhilippeAccorsi** [comment]
Thanks. Its a regression in develop branch.
This bug not exist in 2.3.1 stable version, so we need to fix this for 2.4

**Comment by PhilippeAccorsi** [comment]
Verified.
