### ISSUE TITLE
Public share of a file

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#2125]
## Feature description

A tracim user can share a file so that other users (not necessarily Tracim users) can download it (latest version)

In file application, a tab allow to share / unshare file:

- form includes an email field (which can contain one or several email adresses separated by coma or line return).
- an optional password field

Example of email address content:

```
Damien Dupond <ddupond@voila.fr>
Michel Delpech <mdelpech@voilaa.fr>, n.mouskouri@goodmusic.io
```

When tracim user validates "the share", the backend should create a `content_share` entity related to the content:
    - relationship is based on the `content_id`
    - one share by email address
    - send a notification to each recipient

Note: the share should have the following properties:

- `created` datetime property (default value is now())
- `disabled` datetime property (default value is null)
- `enabled` boolean property (default value is True)

The shares must appear in the timeline like: `file shared with XXX` (where XXX is the email or the associated name). If the share was for several users, then the message should be `file shared with 10 users` (and the overlay should be the list of users)

When the user decides to drop a share (for 1 user at a time), the backend should set the given share to disabled and set the disabled datetime. Then, in timeline, the disable of the share should also appear like `stop sharing of the file with XXX`.

Note : the share table may be a sub-content of given content where created/disabled would be based on the statut of the share object.

For each share, a token is created (so if you share with 3 users, there are 3 share objects, each with a dedicated token), allowing to disable a share for one user at a time and allowing to protect access according to token+password.

The notification email sent to the user must be translatable (and translated), and the content would be:

```
Michel Dupont shared a file with you: [cv.pdf]({user_friendly_link})

<p>Note: you can also use the direct link: {direct_link})</p>
<p>${_("Enjoy your day :)")}</p>
<p>${_("Suricat', your digital assistant")}</p>

<pre>
--
${_("Suricat', the bot")}
${config.WEBSITE__TITLE}
<a href="${config.WEBSITE__BASE_URL}">${config.WEBSITE__BASE_URL}</a>
${_("powered by tracim software")} - <a href="https://www.tracim.fr">https://www.tracim.fr</a>
</pre>
```

Note : public share APIs are:

- private and related to content APIs for configuration stuff
- public and in another set of routes for getting content

**Comment by lebouquetin** [comment]
Screenshot of the share list: https://algoo.tracim.fr/ui/workspaces/93/contents/file/10354

**Comment by inkhey** [comment]
@lebouquetin what should be the behaviour in case of sharing and unsharing same file for same user multiple time. Should we have unique share for user/content or should we allow multiple share for same user/file for logging purpose ?

**Comment by PhilippeAccorsi** [comment]
Necessary:
- Send email with name of file shared and password associated (if set) to user have shared file
- Send email to each email address with link to download file (with token, each user have is own token)

Translation:
- all email exist in english and french

**Comment by inkhey** [comment]
![image-f5bc2d96-8d07-428d-9551-968901a79dab](https://user-images.githubusercontent.com/7851652/62109915-90352880-b2ad-11e9-91b3-430342925209.jpg)

**Comment by inkhey** [comment]
trying to clarificate endpoint api: 


```
POST /api/v2/workspace/{workspace_id}/files/{content_id}/share
{
   'emails': [
      'damien.accorsi@algoo.fr',
      'admin@admin.admin',
   ]
   'password': '1234',
}

RETURN : 
[
  {
     'email': 'damien.accorsi@algoo.fr',
     'has_password': True,
     'share_id': 4,
     'content_id': 5
  }
  {
     'email':'admin@admin.admin',
     'has_password': True,
     'share_id': 5,
     'content_id': 5,
  }
]
```

```
GET /api/v2/workspace/{workspace_id}/files/{content_id}/share

RETURN : 
[
  {
     'email': 'damien.accorsi@algoo.fr',
     'has_password': True,
     'share_id': 4,
     'content_id': 5
  }
  {
     'email':'admin@admin.admin',
     'has_password': True,
     'share_id': 5,
     'content_id': 5,
  }
]
```

DELETE /api/v2/workspace/{workspace_id}/files/{content_id}/share/{share_id}
-> 204

**Comment by inkhey** [comment]
Some technical questions:
- Does we store token or hash of token ? In the second case valid token is given only one time by email and cannot be retrieved

- Has other feature for upload is done on a workspace an does not concern content, data models doesn't seems to fit well with one table for all shares. I suggest a 'content_share" table and something like "workspace_upload_share_access" (i really don't find a good way to name this) for upload part.

- When does we consider sharing to 20 people as one element and when as 20 ? It's not a big deal to make this work for email. if we do need to show in frontend that one share is multiple one, we need to store the information somewhere. One solution could be another "id",  as autoincrement will be complicated. if we go this way, i suggest to have a common uuid for "share group".

**Comment by inkhey** [comment]
About timeline information issue:
- Adding timeline information about sharing in file mean new revision, that's not so nice.
- Adding timeline information about sharing outside file, like comments means we do need to have all the needed information somehere else. we can generated them from content_share, but this means we require a "share_group_id" to clarify that some share are related to the same event.

**Comment by PhilippeAccorsi** [comment]
I think we need to have access to the token in case of email notification is not activated (this case is for sharing and upload).

**Comment by lebouquetin** [comment]
@inkhey @gbonaspetti here comes the API for sharing files (actually, the API should be ready for sharing other types of content):

Get list of shares associated to a content

```
GET /api/v2/workspaces/{workspace_id}/contents/{content_id}/shares

RETURN : 
[
  {
     'email': 'something.somethingelse@somewhere',
     'has_password': True,
     'share_id': 4,
     'content_id': 5,
     'created': '201908...', // datetime of the creation
     'is_disabled': false,
     'disabled': '201908...' // datetime of the disabling
     'created': '201908...', // datetime of the creation
     'author_id': 4 // the user who created the share
     'url': 'http://algoo.tracim.fr/ui/guest-download/<token>'
     'direct_url': 'http://algoo.tracim.fr/api/v2/public/guest-download/<token>/<filename>' // filename may be anything, this is the name which will be considered by the browser as the file name
     'type': 'email' // types will be 'email', 'public-link', 
  },
  [...]
]
```


Create a list of shares on any type of content

```
POST /api/v2/workspaces/{workspace_id}/contents/{content_id}/shares
{
   'emails': [
      'something.somethingelse@somewhere',
      'admin@admin.admin',
   ]
   'password': '1234',
}

RETURN : list of newly created shares (one by email)
[
  // list of same structure as in the GET method
  
]
```


Suppression d'un partage :

```
DELETE /api/v2/workspaces/{workspace_id}/contents/{content_id}/shares/{share_id}
-> 204 
```

Pour les URLs publiques :

- GET http://algoo.tracim.fr/ui/guest-download/<token> écran d'affichage des infos 
- GET http://algoo.tracim.fr/api/v2/public/guest-download/<token>/'  // retourne les infos minimales requises pour l'affichage public du fichier (nom du fichier, id et non de l'auteur du partage, taille du fichier)
- GET http://algoo.tracim.fr/api/v2/public/guest-download/<token>/<filename>'  // retourne le binaire du fichier

**Comment by inkhey** [comment]
@lebouquetin just to be sure, endpoint are commons for all content but now, only content of type 'file' are allowed here, is it right ?

**Comment by inkhey** [comment]
@lebouquetin @gbonaspetti . 
Just some clarification about group token, timeline information and work delegate to backend or frontend: 
- Should we return group_token in GET /api/v2/workspaces/{workspace_id}/contents/{content_id}/shares. Seems logical to me but not sure.
- In this case, mecanism to explain event at date x on timeline for frontend should be done only using GET /api/v2/workspaces/{workspace_id}/contents/{content_id}/shares information by frontend itself or should i create another endpoint to handle this case ?

**Comment by lebouquetin** [comment]
> - Should we return group_token in GET /api/v2/workspaces/{workspace_id}/contents/{content_id}/shares. Seems logical to me but not sure.

Yes, it's logical to also return the group token.

> In this case, mecanism to explain share event at date x on timeline for frontend should be done only using GET /api/v2/workspaces/{workspace_id}/contents/{content_id}/shares information by frontend itself or should i create another endpoint to handle this case ?

For the moment, I suggest that the frontend make the grouping itself. In order to make this easier, I suggest that for a given group of shares, @inkhey you put **exactly* the same created datetime so the grouping will be easier to redo.

**Comment by inkhey** [comment]
> > In this case, mecanism to explain share event at date x on timeline for frontend should be done only using GET /api/v2/workspaces/{workspace_id}/contents/{content_id}/shares information by frontend itself or should i create another endpoint to handle this case ?
> 
> For the moment, I suggest that the frontend make the grouping itself. In order to make this easier, I suggest that for a given group of shares, @inkhey you put *_exactly_ the same created datetime so the grouping will be easier to redo.

It seems that this decision can't handle properly the case where we want a reader to get only "this file has been shared with 4 person" . We should either:
- let reader access to "GET /api/v2/workspaces/{workspace_id}/contents/{content_id}/shares"
- let only contributor+ access to "GET /api/v2/workspaces/{workspace_id}/contents/{content_id}/shares" (timeline will differ between users)
- create another endpoint.

**Comment by gbonaspetti** [comment]
> > > In this case, mecanism to explain share event at date x on timeline for frontend should be done only using GET /api/v2/workspaces/{workspace_id}/contents/{content_id}/shares information by frontend itself or should i create another endpoint to handle this case ?
> > 
> > 
> > For the moment, I suggest that the frontend make the grouping itself. In order to make this easier, I suggest that for a given group of shares, @inkhey you put *_exactly_ the same created datetime so the grouping will be easier to redo.
> 
> It seems that this decision can't handle properly the case where we want a reader to get only "this file has been shared with 4 person" . We should either:
> 
> * let reader access to "GET /api/v2/workspaces/{workspace_id}/contents/{content_id}/shares" which is not really secure depending on how we imagine reader role.
> * let only contributor+ access to "GET /api/v2/workspaces/{workspace_id}/contents/{content_id}/shares" (timeline will differ between users)
> * create another endpoint.

@lebouquetin complementing the problem: discussing with Celia in relation to UX, we had put the message cited by Guenael to the readers and contributors of the file. Because at least for the contributor we find it very important that he knows that this file is shared.

**Comment by lebouquetin** [comment]
there are two sources of information for content related information:

- the list of contents and content itselft, which should return an information saying "active_shares: 5" for example
- the list of shares with detailled information which contains also email / date etc

the first information is the one to use for showing the icon of the content - the endpoint is accessible to all shared space members

the second information is the one to use for filling the timeline, this endpoint is accessible to contributor+ users

Note: the timeline should show:

- shared with Damien Accorsi (with email as title) if the share group contains 1 share
- shared with 4 persons (with email list as title) if the share group contains more than one person

**Comment by inkhey** [comment]
About password :
- Where should be password put for guest : only direct download link endpoint ? as json body or something else ?

**Comment by lebouquetin** [comment]
yes only direct download link. Previous screen will show somethink like : "Michel shared a file with you : CV.pdf (3MB). Set the password and click on the button to start downloading the file"

The way to put the password may be a header or as a POST parameter (GET ?) - What are the standard ways to do so? What is done on http://dl.free.fr ? On NextCloud ?

**Comment by inkhey** [comment]
> yes only direct download link. Previous screen will show somethink like : "Michel shared a file with you : CV.pdf (3MB). Set the password and click on the button to start downloading the file"

current work on the subject does this with header `Tracim-Share-Password` : https://github.com/tracim/tracim/tree/feature/2125__public_share_of_a_file

> The way to put the password may be a header or as a POST parameter (GET ?) - What are the standard ways to do so? What is done on http://dl.free.fr ? On NextCloud ?

dl.free.fr work using http-basic-auth.
nextcloud seems to use header : https://central.owncloud.org/t/calling-the-share-url-with-the-share-password-within-so-user-wont-need-to-see-the-password-page/4499

**Comment by inkhey** [comment]
Some question/issue related to current draft MR  (https://github.com/tracim/tracim/pull/2147)
1. is separation between public share code and core code ok ? Especially email notification config naming.
2. :warning: as we add new template, with relative path, update may cause trouble there ! We do need to have in config but we cannot set them with default valid value. Not sure how we should handle this 
3. Does sharing feature can be disabled ? If so, this may be a partial solution for 2.
4. Email template does work but are not really nice, we do need to do some change there.

**Comment by inkhey** [comment]
Some thing not done yet : 
5. French translation as template are currently draft, we do need to fix 4. first.

**Comment by PhilippeAccorsi** [comment]
@inkhey this is not implemented yet (not visible in frontend). Can you create specifc issue about this and add "to sort" label? thanks in advanced.
~~~
The shares must appear in the timeline like: file shared with XXX (where XXX is the email or the associated name). If the share was for several users, then the message should be file shared with 10 users (and the overlay should be the list of users)

When the user decides to drop a share (for 1 user at a time), the backend should set the given share to disabled and set the disabled datetime. Then, in timeline, the disable of the share should also appear like stop sharing of the file with XXX.

Note : the share table may be a sub-content of given content where created/disabled would be based on the statut of the share object.
~~~

**Comment by PhilippeAccorsi** [comment]
I think discussion about timeline need also to added in new issue. Please make a recap off necessary information in this new issue.
When its done, I can close this issue.

**Comment by PhilippeAccorsi** [comment]
This issue is verified. Some necessary point/enhancement come in next version of tracim.
