### ISSUE TITLE
public upload of a (set of) files

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#2126]
## Feature description

A sharedspace manager or administrator can activate public upload feature. This feature allow a remote user to upload one or more files to tracim. The feature can be protected by a password (this is optionnal).

Behavior is similar to #2125 in aspects of password/token/activation/deactivation/multiple users, etc.

In the sharedspace advanced app, a tab allow to create/disable upload rights.

When a right is created, the external user is notified by email with the following email:

```
Hello xxx,

I invite you to share your files with me through our secured software tracim.

Please [upload them]({user_friendly_link}) as soon as you can.

<p>Note: if the link does not work, please copy/paste the following one: {direct_link}</p>

<p>${_("Thanks a lot")}</p>
<p>${_("Damien XXX (through tracim)")}</p>

<pre>
--
${config.WEBSITE__TITLE}
<a href="${config.WEBSITE__BASE_URL}">${config.WEBSITE__BASE_URL}</a>
${_("powered by tracim software")} - <a href="https://www.tracim.fr">https://www.tracim.fr</a>
</pre>
```

Example of email address content:

```
Damien Dupond <ddupond@voila.fr>
Michel Delpech <mdelpech@voilaa.fr>, n.mouskouri@goodmusic.io
```

Public part of the "upload feature": 

- The form the public user can fill in order to upload files https://algoo.tracim.fr/ui/workspaces/93/contents/file/9957
- When form is valided, then the progress bar appears: https://algoo.tracim.fr/ui/workspaces/93/contents/file/9949
- Then, when upload is finished: https://algoo.tracim.fr/ui/workspaces/93/contents/file/9951

When upload is completed, the backend must:

- create a folder named `Files uploaded by {public user} on {date} ` (parent is virtual folder)
- put all files in this folder (without to send email notifications)
- for each file, add a comment : "Message of <username>: <message body>"
- force a unique notification telling that the user xxx has sent 4 files : xx.pdf, cv.docx, etc

```
Michel Dupont shared some files with you:

- [cv.pdf]({private_link_to_file})
- [file2.docx]({private_link_to_file})

[standard notification signature here]
```

Note : this notification must be sent to all workspace users, even if they did not subscribed to notifications (except if the instance email settings are not set)

Note: screenshot of the whiteboard is available in #2125

**Comment by PhilippeAccorsi** [comment]
When file is uploaded, email is send to all activated user of sharedspace where file is uploaded.

**Comment by inkhey** [comment]
This need some research to find a good way to deal with "virtual upload folder"/
idea were : 
- A true folder but with specific behaviour -> not easy too many difference between a fake folder static and undeletable and a true content. :-1: 
- Use negative value for parent_id to refert to upload virtual folder -> does break some behavior with sqlalchemy, not really easy. :-1: 
- Use a combinaison of new content parameter meaning "is in virtual folder root" + parent is none meaning content is in upload virtual folder -> This need to be tested :question:

**Comment by inkhey** [comment]
## current spec (WIP)
This specification is very similar to download endpoint spec, with few distinctions.

### GET /api/v2/workspaces/{workspace_id}/upload_permissions
return:
```
[
  {
    "author": {
      "avatar_url": "/api/v2/asset/avatars/john-doe.jpg",
      "public_name": "John Doe",
      "user_id": 3
    },
    "author_id": 3,
    "created": "2019-08-09T09:27:57.864Z",
    "disabled": "2019-08-09T09:27:57.864Z",
    "email": "hello@tracim.fr",
    "has_password": true,
    "is_disabled": true,
    "type": "email",
    "upload_permission_group_id": "string",
    "upload_permission_id": 4,
    "url": "/ui/guest-upload/<token>",
    "workspace": {
      "agenda_enabled": true,
      "is_deleted": false,
      "label": "Intranet",
      "sidebar_entries": [
        {
          "fa_icon": "file-text-o",
          "hexcolor": "#F0F9DC",
          "label": "Markdown Documents",
          "route": "/workspace/{workspace_id}/contents/?type=mardown-page",
          "slug": "markdown-pages"
        }
      ],
      "slug": "intranet",
      "workspace_id": 4
    },
    "workspace_id": 6
  }
]
```

### PUT /api/v2/workspaces/{workspace_id}/upload_permissions
body:
```
{
  "emails": [
    "user@example.com"
  ],
  "password": "8QLa$<w"
}
```
return:
```
[
  {
    "author": {
      "avatar_url": "/api/v2/asset/avatars/john-doe.jpg",
      "public_name": "John Doe",
      "user_id": 3
    },
    "author_id": 3,
    "created": "2019-08-09T09:29:22.886Z",
    "disabled": "2019-08-09T09:29:22.886Z",
    "email": "hello@tracim.fr",
    "has_password": true,
    "is_disabled": true,
    "type": "email",
    "upload_permission_group_id": "string",
    "upload_permission_id": 4,
    "url": "/ui/guest-upload/<token>",
    "workspace": {
      "agenda_enabled": true,
      "is_deleted": false,
      "label": "Intranet",
      "sidebar_entries": [
        {
          "fa_icon": "file-text-o",
          "hexcolor": "#F0F9DC",
          "label": "Markdown Documents",
          "route": "/workspace/{workspace_id}/contents/?type=mardown-page",
          "slug": "markdown-pages"
        }
      ],
      "slug": "intranet",
      "workspace_id": 4
    },
    "workspace_id": 6
  }
]
```

### DELETE /api/v2/workspaces/{workspace_id}/upload_permissions/{upload_permission_id}
-> 204


### `GET /api/v2/public/guest-upload/{upload_permission_token}`
-> return
```
{
  "author": {
    "avatar_url": "/api/v2/asset/avatars/john-doe.jpg",
    "public_name": "John Doe",
    "user_id": 3
  },
  "author_id": 3,
  "upload_permission_id": 4,
  "workspace": {
    "agenda_enabled": true,
    "is_deleted": false,
    "label": "Intranet",
    "sidebar_entries": [
      {
        "fa_icon": "file-text-o",
        "hexcolor": "#F0F9DC",
        "label": "Markdown Documents",
        "route": "/workspace/{workspace_id}/contents/?type=mardown-page",
        "slug": "markdown-pages"
      }
    ],
    "slug": "intranet",
    "workspace_id": 4
  },
  "workspace_id": 6
}
```
Question here is : Should we return workspace information and if yes, we should probably use another serializer (this one is workspaceDigest, but contain too much information, sidebar entry are not needed there).

### `POST /api/v2/public/guest-upload/{upload_permission_token}`
Specification of this is fully unclear.

entry as forms. current form is : 

```
message: str
password: str
name: str
file: file
```

There seems to be some hapic related issue about usage of forms for
- optional password
- handling of unlimited number of file.

**Comment by inkhey** [comment]
Other problem found here: upload mean user. but uploader are not real user.
Current code fail because code doesn't allow this. In fact, it failed we he try to mark content as read for non existent user.

To support this we can: 
- support content without author
- set author of uploaded file to emitter of the permission
- have true user with lower right level than user. This way, there can't use at all tracim but they do exist. problem here is that user required email and put email given may cause some weird cases :
    1. an existing account of tracim is given as receiver for upload. This mean that will existing user of tracim used instead of "anonymous" one which will be use, which is nice, but potentially dangerous (we can create file as a user without being authenticated the normal way)  
    2. if an user is created as uploader and then want to create a tracim account, we do need in this particular case consider user creation as "upgrade account".

**Comment by inkhey** [comment]
Decision has been made to set author of uploaded file to emitter of permission and add comment beginning with original sender of uploaded file like : "message from john: here is my report."

**Comment by inkhey** [comment]
There is a problematic about hapic for supporting unlimited number of file (need to bet check with @buxx). Current implementation on https://github.com/tracim/tracim/tree/feature/2126__public_upload_of_a_file does support up to 10 files.

**Comment by inkhey** [comment]
Current mail template need to check recheck.
I see few problem, so there is some difference between spec and actual code in PR:

-  UPLOAD_PERMISSION_TO_EMETTER: no spec
- UPLOAD_PERMISSION_TO_RECEIVER : no direct link exist
- UPLOAD_PERMISSION_TO_RECEIVER : no user name, we can't do hello xxx
- UPLOAD_PERMISSION_TO_RECEIVER : why first person email there whereas all other are third person one, that's normal ?
- UPLOAD_PERMISSION_TO_RECEIVER and NEW_UPLOAD_EVENT : link mecanism is unclear.

**Comment by inkhey** [comment]
Some others issues:
- Consistency between upload and download email
- password protected link need to be clearly indicated.

**Comment by inkhey** [comment]
Example for receiver email:

specification here (see at beginning of the message):

> Hello xxx,
> 
> I invite you to share your files with me through our secured software tracim.
> 
> Please [upload them]({user_friendly_link}) as soon as you can.
> 
> <p>Note: if the link does not work, please copy/paste the following one: {direct_link}</p>
> 
> <p>${_("Thanks a lot")}</p>
> <p>${_("Damien XXX (through tracim)")}</p>
> 
> <pre>
> --
> ${config.WEBSITE__TITLE}
> <a href="${config.WEBSITE__BASE_URL}">${config.WEBSITE__BASE_URL}</a>
> ${_("powered by tracim software")} - <a href="https://www.tracim.fr">https://www.tracim.fr</a>
> </pre>

current implementation for upload:


```
<p>${_('Hello,')}</p>
<p>${_('{username} allowed you to upload on sharespace {workspace_name}').format(username=emitter.display_name, workspace_name=workspace.label)}</p>
<a href="${upload_permission.url}" id='call-to-action-button'>${_('Upload file')}</a>

%if upload_permission_password_enabled:
    <p>${_("This permission is protected by password, please contact {username} to get password.").format(username=emitter.display_name)}</p>
%endif
<p>${_("Enjoy your day :)")}</p>
<p>${_("Suricat', your digital assistant")}</p>

<pre>
--
${_("Suricat', the bot")}
${config.WEBSITE__TITLE}
<a href="${config.WEBSITE__BASE_URL}">${config.WEBSITE__BASE_URL}</a>
${_("powered by tracim software")} - <a href="https://www.tracim.fr">https://www.tracim.fr</a>
</pre>
```

Similar template for download (in develop branch):

```

<p>${_('Hello,')}</p>
<p>${_('{username} shared a file with you:').format(username=emitter.display_name)}</p>
<a href="${content_share.url}" id='call-to-action-button'>${shared_content.file_name}</a>

%if share_password_enabled:
    <p>${_("This content is protected by password, please contact {username} to get password.").format(username=emitter.display_name)}</p>
%else:
        <p>${_("Note: you can also use the direct link: {direct_url}").format(direct_url=content_share.direct_url)}<p>
%endif
<p>${_("Enjoy your day :)")}</p>
<p>${_("Suricat', your digital assistant")}</p>

<pre>
--
${_("Suricat', the bot")}
${config.WEBSITE__TITLE}
<a href="${config.WEBSITE__BASE_URL}">${config.WEBSITE__BASE_URL}</a>
${_("powered by tracim software")} - <a href="https://www.tracim.fr">https://www.tracim.fr</a>
</pre>

```

**Comment by tracim** [comment]
@inkhey in the following example:

```
Hello xxx,

I invite you to share your files with me through our secured software tracim.

Please upload them as soon as you can.

Note: if the link does not work, please copy/paste the following one: {direct_link}

${_("Thanks a lot")}

${_("Damien XXX (through tracim)")}
```

The only information that you may not have is the name. I do not understand why the implementation is totally different.

By the way, the username may be available : when you enter an email like `Michel Durand <mdurand@my.company>`, you have an email address (mdurand@my.company) and a username (Michel Durand). So your implementation must be:

- if there is a username, start the email with `Hello Michel Durand,`
- if there is no username (only an email address), start with `Hello,`

**Comment by tracim** [comment]
My answers:

> - UPLOAD_PERMISSION_TO_EMETTER: no spec

When you are in this case, I suggest you make a suggestion. It will be easier to go on.

> - UPLOAD_PERMISSION_TO_RECEIVER : no direct link exist cannot bet put

In this case, the link to show is the user friendly link. The reason for this part of the email is to allow the user to copy/paste the link (which may be replaced by the email client in some webmail cases)

> - UPLOAD_PERMISSION_TO_RECEIVER : no user name, we can't do hello xxx

In some cases, you can (see my previous answer)

> - UPLOAD_PERMISSION_TO_RECEIVER : why first person email there whereas all other are third person one, that's normal ?

Actually, all emails should be at the first person when possible. All emails are not at the third person, for example I received a tracim notification with the following content: `J'ai modifié le statut de Secret URL to create docker image CollaboraOnline.`

> - UPLOAD_PERMISSION_TO_RECEIVER and NEW_UPLOAD_EVENT : link mecanism is unclear.

I'm pretty sure there are examples of "text including links" in existing templates

**Comment by PhilippeAccorsi** [comment]
Quelques retour sur l'upload:
## Upload

### Template "you give upload permission on test workspace to 2 users"

- On ne distingue pas le nom de l'espace partagé dans la phrase => `You give permission on workspace test workspace with :`
- Je pense qu'il faudrait dire : avec test@test.test disponible à cette url `http://tatatatatatatata`


### Template "toto uploaded 1 contents into test workspace share space"

- Même remarque, il est difficile de distinguer le nom de l'espace partagé
- Le message devrait permettre de comprendre s'il y a un seul fichier ou plusieurs (voir comment sous-entendre qu'il "peut" y avoir plusieurs fichier si besoin de simplifier le mail)
- Même remarque que précédement sur le lien entre nom de fichier et url

### Template "Global manager give you access to upload content into test workspace share space"

- manque le point en fin de ligne "Global manager allowed you to upload on sharespace test workspace"
- manque un phrase du style: cliquer ici "Upload file" pour être rediriger vers l'interface d'envoie de vos fichier (un truc du style).

**Comment by inkhey** [comment]
> My answers:
> 
> > * UPLOAD_PERMISSION_TO_EMETTER: no spec
> 
> When you are in this case, I suggest you make a suggestion. It will be easier to go on.


Current spec: 

```
<p>${_('Hello, {username}').format(username=emitter.display_name)}</p>
<p>${_('You give permission on workspace {workspace_name} with :'.format(workspace_name=workspace.label))}</p>
<ul>
% for upload_permission in upload_permission_receivers:
<li>${_('{email} : {url}'.format(email=upload_permission.email, url=upload_permission.url))}</li>
% endfor
</ul>

%if upload_permission_password:
    <p>${_('This content is protected by password, password is "{upload_permission_password}"').format(upload_permission_password=upload_permission_password)}</p>
%endif

<p>${_("Enjoy your day :)")}</p>
<p>${_("Suricat', your digital assistant")}</p>

<pre>
--
${_("Suricat', the bot")}
${config.WEBSITE__TITLE}
<a href="${config.WEBSITE__BASE_URL}">${config.WEBSITE__BASE_URL}</a>
${_("powered by tracim software")} - <a href="https://www.tracim.fr">https://www.tracim.fr</a>
</pre>

```

**Comment by inkhey** [comment]
@gbonaspetti somes note about making upload work for frontend:

- "form parameter name" (don't know what the correct name) for files should always match file_* pattern in upload form, if it does not file send will not be added.
-  to show uploaded content, you need to use namespaces_filter to upload in /api/v2/workspaces/{workspace_id}/contents

**Comment by inkhey** [comment]
some tricky case related to namespaces, unclear, to be discussed @lebouquetin :

- should be allow creating file/content  directly to upload namespaces ? (this is currently not possible for any content but comment)
- should be allow moving file from namespace to another (in both way ?) ? (this should currently work if we do not try to move file to another namespace root) 
- should we allow modification of uploaded file in upload namespaces ? (currently all modifications are allowed)

**Comment by inkhey** [comment]
Another trouble is webdav support of the feature:
should we : 
- do not show upload namespace content
- adapt hierarchy to show them.
- completely ignore namespace filter and show all content at same level (may cause some tricky case with same name folder).

**Comment by PhilippeAccorsi** [comment]
For me that's ok.
Verified.
