### ISSUE TITLE
Backend test require test_storage_dir and subdir, by default (see .test.env) but those tests doesn't exist

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2129]
## Bug description & symptom

Running tracim backend test on fresh install will failed because test_storage_dir and subdir doesn't exist by default. Travis is not concerned as far as travis does use different dirs path and create those dir explicitly on his side.

## Expected

We do need a script or something else to create thoses folder to allow user to run test "almost" out of the box with documentation.

**Comment by inkhey** [comment]
@PhilippeAccorsi to test this, you need to run on a clean tracim and follow documentation (README.md in backend dir) about running test, and then run them.

**Comment by PhilippeAccorsi** [comment]
Verified.
