### ISSUE TITLE
Full datetime on logger by default

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2132]
## Bug description & symptom

Currently, default tracim logger doesn't log anything related to specific day the log happened.
That's because datefmt in *.ini file is like this:

`datefmt = %H:%M:%S`

which does with default logger to stdout log like this:
`
10:26:04 INFO  [tracim:32][MainThread] [CFG] CONFIG: [ SOURCE_DEFAULT  | WEBDAV__BLOCK_SIZE | 8192 | None ]
`
(rest of the format orderaof log is set in `format` but that's another thing.)

## Expected

We should have a more complete default datefmt for all available formatter by default. It should allow us to know when the log happened: year, month, day.

like this `[2019-11-22 10:26:04]` or `2019-11-22 10:26:04`

**Comment by PhilippeAccorsi** [comment]
issue updated.

**Comment by PhilippeAccorsi** [comment]
All logger config is different on system. Date and time is not show with same syntax in syslog, kern.log, apache log, uwsgi log, dpkg log.

I think this is the best solution `2019-11-22 10:26:04` all the time in the beginning of each line (if you want to grep something is easier to find).

**Comment by inkhey** [comment]
fix this on #2249 + support for utc datetime.

**Comment by PhilippeAccorsi** [comment]
Tested on local with pserve => working good
- need test with uwsgi (with docker image)

**Comment by PhilippeAccorsi** [comment]
Tested with docker image of tracim:
All log have date and time.

Verified.
