### ISSUE TITLE
crash when accessing a non existant or a forbidden workspace

### ISSUE THREAD

**Issue by basilelegal** [tracim/tracim#2141]
## Bug description & symptom

If you try acessing a non existant workspace or a forbidden workspace, you get a white screen.

## Expected

A flash message saying the workspace does not exists and a redirect to `/ui`

![tracim crash](https://user-images.githubusercontent.com/7879232/62301137-02d90c00-b446-11e9-8af7-46c494d88b2e.png)

**Comment by PhilippeAccorsi** [comment]
@basile missing translation if workspace_id not exist
~~~
Information
Unknown shared space
~~~

I think something make regression in redirection. I can't open "all content" from first one workspace and clic on "all content" in another workspace.
When I clic on "all content" button no request is send to tracim.

**Comment by PhilippeAccorsi** [comment]
This problem just exist between different shared space if you click on same filter in sidebar (issue not exist in 2.3.2).

**Comment by PhilippeAccorsi** [comment]
Verified.
