### ISSUE TITLE
Crash when accessing a non existant content

### ISSUE THREAD

**Issue by basilelegal** [tracim/tracim#2142]
## Bug description & symptom

If you try acessing a non existant content though the url, you an error and an empty content popup.

## Expected

A flash message saying the content does not exists and redirect to the content list.

![Screenshot at 2019-08-01 10-52-55](https://user-images.githubusercontent.com/7879232/62303659-8ac11500-b44a-11e9-82bc-37369734490c.png)

**Comment by Quiwy** [comment]
Seems to have an error message now :
![other_file](https://user-images.githubusercontent.com/20048264/185626506-b44e4598-e71f-4666-8ff0-b710167eaf02.gif)
![other_workspace](https://user-images.githubusercontent.com/20048264/185626524-ac80d439-67e9-4435-ba9a-451494abf0f2.gif)
