### ISSUE TITLE
Regression in app htmldoc, the link to resume writing from a draft is missing

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2149]
## Bug description & symptom

The button to resume writing from a draft in app htmldoc is missing

## Diagnostic

Some refactor for the component DisplayState has been missed, the props type should be btnType

## Expected

- [x] The button is displayed
- [ ] Cypress test for non-regression

## How to reproduce

- display the message related to draft (start a change and open another app without saving it)
- the button is missing

## Impacted components

Html doc

## Extra information

Change the label 'type' to 'btnType' for component DisplayState

**Comment by PhilippeAccorsi** [comment]
I have update issue with cypress test in expected.

**Comment by Skylsmoi** [comment]
I don't think a Cypress test really apply here.
This button is used in many places across Tracim, having to write cypress test for each wouldn't be really advised.
There will be unit tests for this component soon.
For this kind of validation, as it is just a missing refactor that end up in a wrong props usage of the component, component propTypes should be enough.

My advise is to write propTypes for this component that ensure that the btnType exists and has one of the 2 values: ["label", "link"]

**Comment by lebouquetin** [comment]
this fix does not include non-regression test(s) case(s). It should not have been merged.

**Comment by PhilippeAccorsi** [comment]
Verified.

I close this issue and open another one to write test for this case.
