### ISSUE TITLE
Test libre office online with Tracim

### ISSUE THREAD

**Issue by basilelegal** [tracim/tracim#2153]
## Bug description & symptom

The feature collaborative edition is tested with `collabora CODE` but not with the more advanced `libre office online`.

## Expected

Test if Tracim is working with `libre office online `out of the box. If it doesn't document what is needed to done to make it work.

**Comment by PhilippeAccorsi** [comment]
Modify documentation if libreoffice work correctly in tracim 2.4.0.

**Comment by PhilippeAccorsi** [comment]
Related to https://github.com/tracim/tracim/issues/1007
I close this issue.
