### ISSUE TITLE
update docker file to add new parameter visible in development.ini about collabora and else

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2154]
## Feature description

Update docker images to be available for running collabora and other new feature available in tracim 2.4.0 

## Context

Some new parameters are available in develoment.ini so we need to know if this paramter need to be change when starting docker images.

## Prerequisites

- [x] list of all new parameter is available.
 
## Impacted components

docker file/config

## Extra information

**Comment by inkhey** [comment]
For actual public share PR download side : https://github.com/tracim/tracim/pull/2147
some change are required to make think work: 
see https://github.com/tracim/tracim/pull/2147/files development.ini.sample or: 

```
email.notification.share_content_to_emitter.subject = [{website_title}] you shared {content_filename} to {nb_receivers} users
email.notification.share_content_to_receiver.subject = [{website_title}] {emitter_name} shared content {content_filename} with you
email.notification.share_content_to_emitter.template.html = %(email.template_dir)s/shared_content_to_emitter_body_html.mak
email.notification.share_content_to_receiver.template.html = %(email.template_dir)s/shared_content_to_receiver_body_html.mak

```

:warning: these parameters naming are actually not validated, they may change after review.

**Comment by PhilippeAccorsi** [comment]
Need to modify Dockerfile about new app "frontend_app_share_folder_advanced". Check if other thing is necessary (for backend or frontend).

**Comment by PhilippeAccorsi** [comment]
No modification needed in docker image about new feature. We just rework delete command of node_module/  folder in Dockerfile.

**Comment by PhilippeAccorsi** [comment]
Verified.
