### ISSUE TITLE
Collaborative edition frame - no redirect when you can't edit

### ISSUE THREAD

**Issue by basilelegal** [tracim/tracim#2157]
## Bug description & symptom

If you open a document in edit mode via url, a message appear saying you can't edit but you are not redirected.

## Expected

If you open a document in edit mode via url, a message appear saying you can't edit and you are redirected.

**Comment by PhilippeAccorsi** [comment]
@basilelegal Message appear in english also if we are in french.

~~~
Attention
You are not allowed to edit this file
~~~

**Comment by PhilippeAccorsi** [comment]
Now if I don't right to open document in edit mode, the file is openned in view mode (this issue is created before authorization for user to use view mode of collabora)
So I think its not easy now to see this error.

**Comment by PhilippeAccorsi** [comment]
Verified.
