### ISSUE TITLE
Text editor: add url edit button

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#216]
When url is malformed, it's not possible to edit the link. We have to delete it and re write/paste it. 

* Enable URL edit button if exist
* Or add source code button

**Comment by tracim** [comment]
The best solution is probably to restore the rich text editor source code button

**Comment by tracim** [comment]
@buxx start the investigation, then give the bug to @algooapy or @Skylsmoi

**Comment by buxx** [comment]
TODO:

- Update TinyMCE
|-> To have right-click, edit link
- add source code button
- Keep actual buttons (ex image, fullscreen)

**Comment by lebouquetin** [comment]
Fixed throughTtinyMCE update
