### ISSUE TITLE
Popup create office document doesn't take enter or escape

### ISSUE THREAD

**Issue by basilelegal** [tracim/tracim#2167]
## Bug description & symptom

All popup creation in tracim handle `enter` and `escape` buttons but not the new popup for office document.

## Expected

`enter` should be the same as pressing `validate` button.
`escape` should be the same as pressing the `X` button.

**Comment by PhilippeAccorsi** [comment]
@basilelegal this is working just if you are in input field. But process is (I think, we read from up to down):
- choice tilte
- choice kind of document
=> and at this moment I can't validate (enter) or escape (echap).

**Comment by PhilippeAccorsi** [comment]
Verified.
