### ISSUE TITLE
Feat: Allow users to modify a content without notifying subscribers

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#217]
Il m'arrive souvent d'enregistrer un document en plusieurs fois pour plusieurs raison:

* Sauvegarde régulière pour ne pas perdre le travail en cours
* Sauvegarde pour reprendre le travail le lendemain, etc

Et c'est toujours un problème pour moi que de savoir que les abonnés vont être notifié un peu pour pas grand chose. En tout cas à propos d'un document clairement pas encore lisible.

Ce serait donc intéressant d'avoir un feature du genre "Enregistrer sans notifier les abonnés". Ou un statut de document "Brouillon" qui désactive implicitement les notifs.

**Comment by lebouquetin** [comment]
C'est effectivement une bonne idée. Quelle implémentation te paraît la plus pertinente ?

- un bouton "sauvegarder sans notifier" à côté du bouton "sauvegarder" ?
- un statut spécifique me paraît compliqué, dans le sens où devrais changer le statut pour simplement notifier les utilisateurs.

Autres pistes : 

- dans l'interface "normale", afficher un bouton "notifier les utilisateurs d'une modification", ce qui aurait pour effet de décorréler l'envoi de notifications et la modification elle-même
- implémenter un mécanisme de notification intelligent et personnalisé/personnalisable (exemple : je veux être notifié seulement une fois par jour). Mais dans ce cas : quelles stratégies proposer ?

Le sujet des notifications est un sujet *très* important.

**Comment by buxx** [comment]
A mon avis le bouton "sauvegarder sans notifier" est une bonne solution qui implique peu d'impact. Un bouton "notifier les utilisateurs d'une modification" risque de n'être que trop peu utilisé et faire manquer des notifications. Ou alors, au lieu du bouton "sauvegarder sans notifier", une case à coché (coché par défaut) "notifier ...".

"mplémenter un mécanisme de notification intelligent et personnalisé/personnalisable" Pourrais être une fonctionnalité à part. Fonctionnalité qui serais intéressante d'ailleurs.

**Comment by Haskaris** [comment]
Irrelevant in Tracim 4.3 since we are filtering notifications (TLM) in `development.ini`. Closing this issue.

**Comment by Haskaris** [comment]
My mistake, actually a notification can be a mail notification. This issue is probably about the mail and not the notification wall. Reopening this issue.
