### ISSUE TITLE
Button 'Edit' for Collabora files should be rename to 'Edit online' and the icon should be changed

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#2172]
## Bug description & symptom

Button 'Edit' for Collabora files should be rename to Edit online and the icon should be changed to an edit style icon

## Diagnostic

Edit button name & Icon for the case of collabora files isn't pertinant

## Expected

- [x] Rename this button to 'Edit online' with his traduction in french and change his icon to fa-edit
- [x] Add or modify units tests to frontend_lib for component impacted

## Impacted components

- frontend_lib/NewVersionBtn
- App file

**Comment by metzgegu** [comment]
I created a new component (GernericButton.jsx) button in frontend_lib which is more generic than NewVersionBtn to be able to have a custom Icon. This component is now use by NewVersionBtn.

**Comment by PhilippeAccorsi** [comment]
verified.
