### ISSUE TITLE
App File stays in an old revision display when switching content

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2174]
## Bug description & symptom

When switching from 2 different content file while the first one has a old revision displayed, the new one stays in the old revision state.

## Diagnostic

When a new content is loaded, the app file must switch back to the VIEW state

## Expected

When opening a different content, the new one must always open in VIEW state

## Context and version information

Visible in 2.3.x and 2.4

## How to reproduce

- have 2 content type file with a few revisions
- open one on an old revision
- open the other one

## Impacted components

app file

**Comment by PhilippeAccorsi** [comment]
Verified.
