### ISSUE TITLE
authentication problem with webdav

### ISSUE THREAD

**Issue by xandercagexxx** [tracim/tracim#218]
When you try to authenticate, the password not working.
If you logout and login: same problem

You need to change password, logout and login with this new password and its working good.

**Comment by tracim** [comment]
Normally, the code already update the webdav token on login. @algooapy to discuss with @lebouquetin before to start investigating

**Comment by tracim** [comment]
In the code of authentication, we generate the webdav token if it does not exist. The following code should work out-of-the-box - the only case it will not work is if : 

- password is changed and token not regenerated
- email is changed and token not regenerated

See the code:

```
        if user and user.validate_password(identity['password']):
            if not user.webdav_left_digest_response_hash:
                user.webdav_left_digest_response_hash = '%s:/:%s' % (identity['login'], identity['password'])
                DBSession.flush()
                # TODO : temporary fix to update DB, to remove
                transaction.commit()
            return identity['login']
```

**Comment by tracim** [comment]
Not reproducedfor now

**Comment by xandercagexxx** [comment]
Verified. Ubuntu 17.04
