### ISSUE TITLE
Delete share content on file deleted ?

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2181]
## Bug description & symptom

If file is deleted, what should be the behavior of related share ?

## Diagnostic

origin of the issue : 
> I'm considering this controller view should not manage this case because the case where binary file is not on disk should not happen because:
> 
>     * When File `Content` type  do not own file: we should not be able to share it
> 
>     * When File `Content` type has been deleted: shares are they deleted ? They must.
> 
> 
> But, as you say the case "binary file can be absent on disk when deal with DepotManager" is a general case on Tracim. So i suggest opening a technical debt issue to think about all of that.

_Originally posted by @buxx in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMTkxMzMyNDcxOnYy/pull_request_review_threads/discussion_

## Expected

Updated  02/09/2019 :warning: :
We should not deleted content share. we should just access to content through contentapi without specific filter, meaning no deleted and not archived content visible by default.

**Comment by PhilippeAccorsi** [comment]
Do you have discuss with @lebouquetin or @buxx about this ?
Please add "to sort" or add project if its in project directly.

**Comment by inkhey** [comment]
as noted in #2221. 
there is many way to deal with this: 

- Disallow guest endpoint for share if share is linked to a content archived/deleted
- Disable shares when we do archive/delete a file.
- Do not change current behavior

It's also unclear how archive case should be treated .

**Comment by inkhey** [comment]
> @inkhey  ContentApi  is the core API; all stuff **must** access contents through it

_Originally posted by @tracim in https://github.com/tracim/tracim/issues/2231#issuecomment-523020028_

**Comment by PhilippeAccorsi** [comment]
@inkhey What is the way to test this?
