### ISSUE TITLE
Content Share: Change put to post for creating content_share

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2184]
## Bug description & symptom

content share endpoint use now put, it should be post.

## Expected

convert put /api/v2/workspaces/{workspace_id}/contents/{content_id}/shares to post /api/v2/workspaces/{workspace_id}/contents/{content_id}/shares

Backend should fix endpoint and frontend should adapt code to this fix.

**Comment by PhilippeAccorsi** [comment]
Verified.
