### ISSUE TITLE
Content Share: rename group_id to group_uuid

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2186]
## Bug description & symptom

content_share use  share_group_id, this should be renamed to share_group_uuid

## Diagnostic

*Optional - explain what has been found and what is not yet clear. If unknown, write "unknown".*

## Expected

convert use  share_group_id to share_group_uuid

frontend should modify code according to this fix in backend.

**Comment by PhilippeAccorsi** [comment]
Verified.
