### ISSUE TITLE
button visible in dashboard about shared file (for the moment just backend is merged

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2194]
## Bug description & symptom

When I am connected in one dashboard with collabora activated in backend, I can see one button with fa-share icon. 

## Diagnostic

*"unknown".*

## Expected

- [ ] don't show button for inactive app.
- [ ] don't show button about shared with upload and download

## How to reproduce

- Open dashboard of one shared space

## Screenshots

![Sélection_017](https://user-images.githubusercontent.com/25848257/62869017-428dd680-bd17-11e9-9350-7f2265d46512.jpg)

## Impacted components

- *backend*
- *frontend*

## Extra information

**Comment by PhilippeAccorsi** [comment]
For the moment just backend shared file feature is merged. Need to be check when frontend is merged. If bug still exist, we can work on it after modification of issue.

**Comment by PhilippeAccorsi** [comment]
Now download and upload is merged, so we do not seen button about share upload and share download.

**Comment by gbonaspetti** [comment]
Frontend side: the dashboard button list is created from the list of alls applications installed in this tracim instance sent in by the backend (endpoint: /api/v2/system/applications). After, some elements of this list are filtered if the user role is not enough (folder case) or the application is disabled (agenda case). The share_folder is always filtered.

**Comment by PhilippeAccorsi** [comment]
Verified.
