### ISSUE TITLE
"Not allowed content property" 500 error in frontend if allowed_content in database doesn't match activated content_type

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2217]
## Bug description & symptom

In case we use tracim with some app adding content type like office_document, we can have properties field of content_revision like : 

```
{
"allowed_content": {"folder": true, "office_document": true, "comment": true, "file": true, "thread": true}
}
```
Which is normal.
Then if we do disable app for office_document. We will get error 500 at some endpoint with "Not allowed content property" because loading of allowed_content will failed to find correct content_type according to "office_document" slug.

## Expected

Solution seems to ignore unknown value instead of raising error here.

**Comment by PhilippeAccorsi** [comment]
Verified.
