### ISSUE TITLE
Fix Support for password protected share content

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2228]
## Bug description & symptom

Currently password protected shared content return error 403, this is because password is not given at all to content. This should be done by setting header `Tracim-Share-Password` with valid password. If this cause some trouble, we need to discuss how to handle this differently.

## Expected

Support password protected share content.

**Comment by inkhey** [comment]
After discussions, this cause trouble. 
Only way to deal with this in frontend is by using POST method.
To handle both direct link (GET) and forms post (POST) for password protected link, we do need one more endpoint doing almost same. We can remove header support here.

So temporary spec is : 

```
GET /api/v2/public/guest-upload/{upload_permission_token}
POST /api/v2/public/guest-upload/{upload_permission_token}
```

**Comment by inkhey** [comment]
backend part is done with https://github.com/tracim/tracim/pull/2238.

**Comment by inkhey** [comment]
frontend part is #2246

**Comment by PhilippeAccorsi** [comment]
Verified.
