### ISSUE TITLE
Add french translation to upload permission/share_content email templates

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2229]
## Bug description & symptom

Currently upload permission/share_content email template doesn't have french translation.

## Expected

have french translation for upload permission/share_content features

**Comment by PhilippeAccorsi** [comment]
If a user share file (user interface in french) email is send in french but subject is not translated.

we need also to add space between end of file name and size of file. At present: "190325_ALGOO_Ansible.pdf(778.8 kB)"

**Comment by PhilippeAccorsi** [comment]
This is an error in my development.ini with the last change.

Thats working good.

**Comment by PhilippeAccorsi** [comment]
We add space fix in another branch. 
Verified.

**Comment by PhilippeAccorsi** [comment]
Also related to #2200
