### ISSUE TITLE
Do not allow access to disabled/deleted content share

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2231]
## Bug description & symptom

Currently disabled/deleted content share stay accessible.

## Expected

Make deleted content share not accessible anymore

**Comment by tracim** [comment]
@inkhey this should be thé case by default: when you use ContentApi without to explicitly ask for deleted/archived content, the ContentApi returns an error.

Why do you have a specific issue for that?

**Comment by inkhey** [comment]
@tracim Because We didn't get content through contentApi here. We get a ContentShare object which is linked to a content.
By the way, it's unclear if we should prefer to deleted content-share for deleted content or make content-share unable to get content. Both choice could make sense.

**Comment by inkhey** [comment]
By the way, this issue is not related to Content stuff, but to disabled **content-share** and not deleted content. Currently disabling content share doesn't block content-share link to work. it's a trivial issue that is being fixed now.

**Comment by inkhey** [comment]
Issue for content deleted is here : https://github.com/tracim/tracim/issues/2181 . Here is about bug in query to select only enabled content-share .

**Comment by inkhey** [comment]
Similar issue does exist for similar endpoint for upload_permission : https://github.com/tracim/tracim/pull/2234 fix both issues.

**Comment by tracim** [comment]
@inkhey  ContentApi  is the core API; all stuff **must** access contents through it

**Comment by tracim** [comment]
Event ContentShare api: this IS a paradigm if layers/encapsulation

**Comment by inkhey** [comment]
@tracim, just move your comment in #2181, which is the related issue to this problem.

**Comment by PhilippeAccorsi** [comment]
Verified.
