### ISSUE TITLE
CSS issues at new interface of dashboard advanced

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#2237]
## Bug description & symptom

There are some css problems at new interface os dashboard advanced:

- [x]  Scroll didn't work only to one side.
- [x]  Inside menu does not close properly
- [x]  Roles are not aligned
- [x]  Share and Upload switch buttons still exists at optional functionalities
- [x]  Delete button is hidden at members list
- [x]  Change the white background at new members form
- [x]  Change size of inside menu

**Comment by PhilippeAccorsi** [comment]
Some small modification needed:
- [ ] Roles description is not align (for content manager)
- [ ] title `Members list` is not align with member name
- [ ] if I close menu, the menu is visibla at half of his own size
- [ ] need to find solution about text to explain role (and text near lightbulb) => text is too visible

**Comment by PhilippeAccorsi** [comment]
Tested and verified:
- Roles description is not align (for content manager)
- ~~title Members list is not align with member name~~
- ~~if I close menu, the menu is visibla at half of his own size~~
- ~~need to find solution about text to explain role (and text near lightbulb) => text is too visible~~

**Comment by PhilippeAccorsi** [comment]
Tested and verified:
- ~~Roles description is not align (for content manager)~~

Verified.
