### ISSUE TITLE
calendar url is not visible

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#225]
The url of all calendar is not show in "Calendar".
To find url, we need to go to "My Home", its better if we can see available url directly in "Calendar"

**Comment by lebouquetin** [comment]
by the way, is it possible to include a link that will automatically be openned with calendar application on the mobile phone and/or computer ?

**Comment by Skylsmoi** [comment]
It is possible to have a link that will open the calendar app. But a link that will create the event or directly link to an event might be much more complexe

some ref : https://developer.chrome.com/multidevice/android/intents
