### ISSUE TITLE
Fix support password protected upload permission and share content

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2254]
## Bug description & symptom

Actual endpoint for password protected upload doesn't allow frontend to handle properly exception case. In fact, browser do redirect to api endpoint when post failed and return 400 error.

## Expected

- Add endpoint to check password validity of upload permission to not do a post when password happened, this will not avoid at all the issue but mitigate it for most case.
- Add endpoint to check password validity of share content to not do a post when password happened, this will not avoid at all the issue but mitigate it for most case.

**Comment by inkhey** [comment]
Same problem occured for download case. need to be fixed too.

**Comment by PhilippeAccorsi** [comment]
Verified.
