### ISSUE TITLE
its impossible to move file from inbox to root of workspace

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2255]
## Bug description & symptom

When I try to move file from inbox to root of worksapce, file stay in inbox. But if I move this file from inbox to another folder its work good and after that if I move file to root of workspace is work also.

## Diagnostic

idée: something wrong with parent_id of file. Maybe need discuss with backend about that.

*"unknown".*

## Expected

- [ ] its possible to move file from inbox folder (or children folder of inbox) to root of the worksapce. 

## Context and version information

- tested on firefox

## How to reproduce

- upload a file
- try to move this file to root of workspace
=> file stay in root of inbox folder

## Screenshots

![moving_file_to_workspace_root](https://user-images.githubusercontent.com/25848257/63496376-1bc36300-c4c2-11e9-9f1a-5e81824dd989.gif)

## Impacted components

*"unknown"*

**Comment by inkhey** [comment]
Problem is backend related as we do not allow yet in endpoint to move to another namespace (we can move to another namespace implicitly when we put in another workspace folder, but not at root level). 
But i've a question about this:
-  Should we handle move both way and consider share folder as a normal folder where we could but stuff, etc...  If not we need a specific behavior in backend and probably in frontend too.

By the way, adding this feature will mean that frontend should be aware of namespace to not do incorrect move.

**Comment by PhilippeAccorsi** [comment]
Verified.
