### ISSUE TITLE
Share folder advanced : Icon of cancel button isn't centered

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#2258]
## Bug description & symptom

- [x] In the app_share_folder_advanced, the fa-times icon in the cancel button isn't centered
- [x] Same in ShareDownload

## Diagnostic

Remove the css property `Display: flex` in the cancel button remove this issue.

## Expected

Icon is centered

**Comment by PhilippeAccorsi** [comment]
Missing modification in share of file.

**Comment by PhilippeAccorsi** [comment]
Verified.
