### ISSUE TITLE
Display formatted dates in a tooltip and fix translation in properties of app file

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#2265]
## Bug description & symptom

The properties labels of a file should have the proper translation in french, ':' => ' :' 
Distances dates should display a tooltip with the formatted date in file properties

## Expected

Change i18n translation file in app_file
Add a title to properties dates divs in FileProperties

**Comment by PhilippeAccorsi** [comment]
Translation in french not working in properties:
~~~
Propriétés

 Type : .odt
 Size : 7.67 KB
 Page number : 1
 Creation date : il y a 4 jours
 Last modification : il y a 4 jours
 Description 
~~~

After discuss with @lebouquetin this morning we need to change something in properties view:
- `Creation date:` need to show exactly date like "month/day/year" or in french "day/month/year" (note x days ago)
- align `Properties` with all other properties like this:
~~~
Properties

Type : .odt
Size : 7.67 KB
Page number : 1
Creation date : il y a 4 jours
Last modification : il y a 4 jours
Description 
~~~

**Comment by LucBarry** [comment]
Verified
