### ISSUE TITLE
unable to install PyMySQL MySQL driver with 3.5 and 3.6 versions of Python

### ISSUE THREAD

**Issue by algooapy** [tracim/tracim#227]
Sister issue of #220 which requires to fix the travis script: using `pip` in the `before_script` clause induces the travis job to be errored. I will probably install the MySQL driver in the `install` clause of the script, as do the PostgreSQL one, but this solution is sub optimal because of the installation of two RDBMS drivers although only one is needed.

**Comment by tracim** [comment]
@algooapy "le mieux est l'enemi du bien". Mets les deux drivers RDBMS dans la section "install" et créés un bug éventuellement pour dire "à améliorer"
