### ISSUE TITLE
Validation buttons in timeline not visible when there are a few comments

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#2276]
## Bug description & symptom

Validation and Rich text button are not visible when there are enough comment or revision to hide theses buttons.

**Comment by PhilippeAccorsi** [comment]
Verified.

**Comment by metzgegu** [comment]
Validation and Rich text button are not fixed in the bottom when there is too few comments in the timeline

**Comment by PhilippeAccorsi** [comment]
Verified.
