### ISSUE TITLE
Webdav support for upload permission feature : disable upload namespace

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2279]
## Bug description & symptom

Webdav support with upload namespace need to be clarify. Current behaviour is displaying directly upload dir at same level that othe namespace which may create view of same name dir in same workspace root.

> Another trouble is webdav support of the feature:
> should we : 
> - do not show upload namespace content
> - adapt hierarchy to show them.
> - completely ignore namespace filter and show all content at same level (may cause some tricky case with same name folder).

_Originally posted by @inkhey in https://github.com/tracim/tracim/issues/2126#issuecomment-521235912_
## Diagnostic

*Optional - explain what has been found and what is not yet clear. If unknown, write "unknown".*

## Expected

~~to be discussed.~~ UPDATE 02/09/2019: Disable upload namespaces, better strategy for #2343  issue.

**Comment by inkhey** [comment]
1. We do not show upload namespace content.
2. "Inbox" dir with all uploaded content
3. No filter (actual case)

Problems:
- 1 reduce tracim webdav feature but is easy to make workable.
- 3 create messy dir hierarchy (it's actual behaviour) and allow naming collision.
- 2 seems the more appropriate logic but allow naming collisions. It's technically possible to avoid it in 2 (by renaming on the fly the fake inbox folder) but not so easy.

**Comment by inkhey** [comment]
If we follow 2 "inbox" dir: 
there is also some work to make:
- Translation of "Inbox" dir (should we translate it ?)
- Consistent move/create/copy mechanism between web UI and Webdav

**Comment by inkhey** [comment]
After disucssion, decision was made to choose strategy 1 (do not show upload namespace in webdav) now and create a new ticket for strategy 2 (show inbox dir, see #2343).

**Comment by PhilippeAccorsi** [comment]
Verified.
