### ISSUE TITLE
review installation documentation in README.md

### ISSUE THREAD

**Issue by algooapy** [tracim/tracim#228]
See sub issues:
* simplify development environment installation,
* externalize RDBMS specific configuration,
* externalize tracim configuration options,
* externalize Apache configuration,
* add a part describing tests,
* add production environment ?

**Comment by lebouquetin** [comment]
@algooapy please send your pull request about the documentation. (see also https://github.com/tracim/tracim/issues/237 - as soon as something is done, it must be pull-requested - except if it breaks things)
