### ISSUE TITLE
Error when uploading .png file on Tracim

### ISSUE THREAD

**Issue by herawo** [tracim/tracim#229]
I got this error when uploading a png file on Tracim using MySLQ:
`sqlalchemy.exc.ProgrammingError: (oursql.CollatedWarningsError) (None, 'query caused warnings', [(<class 'oursql.Warning'>, ("Data truncated for column 'file_content' at row 1", 1265))]) [SQL: 'INSERT INTO content_revisions (content_id, owner_id, label, description, file_extension, file_mimetype, file_content, properties, type, status, created, updated, is_deleted, is_archived, is_temporary, revision_type, workspace_id, parent_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: (12, 1, 'Screenshot from 2017-05-19 14:54:37', '', '.png', 'image/png', b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x07\x80\x00\x00\x04\xb0\x08\x06\x00\x00\x00\x1a0W\xf6\x00\x00\x00\x04sBIT\x08\x08\x08\`

**Comment by tracim** [comment]
Try to reproduce, then fix and/or close

**Comment by algooapy** [comment]
Didn't reproduce it. Moreover the error message mentions the `oursql` python MySQL driver that we don't use this one anymore.
