### ISSUE TITLE
need modification in upload loader

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2291]
## Bug description & symptom

At present its not possible to know percentage of uploding file (value is not visible)

## Diagnostic

*"unknown".*

## Expected

- [ ] all color in upload loader are clear enough

## Context and version information

Tested on firefox

## How to reproduce

upload file from upload form (shared feature).

## Impacted components

- *frontend*

## Extra information

**Comment by gbonaspetti** [comment]
Duplicated with #2305.
