### ISSUE TITLE
Comments in timeline don't handle well long words

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#2300]
## Bug description & symptom

When a comment with a long word is added, a part of this word isn't in the div

## Screenshots

![Capture du 2019-08-27 11-50-31](https://user-images.githubusercontent.com/31687635/63761979-5104f200-c8c2-11e9-9320-fe03fc33555d.png)

**Comment by PhilippeAccorsi** [comment]
Need to check what we used at present on tracim 2.3.2
comment message need to show also rich text correctly. Maybe discuss with @Skylsmoi to find solution with new design of history.

**Comment by PhilippeAccorsi** [comment]
Need test on comment with uploaded file.

**Comment by LucBarry** [comment]
Verified

**Comment by Skylsmoi** [comment]
We are going to revert this fix because it causes more issues than it fixes.

Now any word can be break which leads to bad display.

**Comment by metzgegu** [comment]
Duplicate of #2595
