### ISSUE TITLE
language button need some css fix

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2302]
## Bug description & symptom

At present we have this:
![Sélection_026](https://user-images.githubusercontent.com/25848257/63767703-a5ae6a00-c8ce-11e9-97c5-8d22aad58833.jpg)

And we need to see same flag size, with same border,etc.

## Diagnostic

*"unknown".*

## Expected

- [ ] flag have same size for language selected and language in list of available
- [ ] margin left is the same (look on Administration button)
- [ ] same space between flag and text

## Context and version information

- Desktop environment (if applicable)
    - *OS: ubuntu*
    - *Browser firefox*

## How to reproduce

- click on language button

## Impacted components

*If unsure, write "unknown"*

## Extra information

**Comment by gbonaspetti** [comment]
Updated at #4562
