### ISSUE TITLE
NewUpload should have the password input optional with a button to display it

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#2303]
## Bug description & symptom

Password should be optional. 

## Expected

- [x] NewUpload should have the password input optional with a button to display it, exactly like in NewShareDownload
- [x] This button need to have the pointer cursor in NewUpload and NewShareDownload
- [x] User should be able to re-hide the password field if he changes his mind

**Comment by PhilippeAccorsi** [comment]
Verified.
