### ISSUE TITLE
Remove the button for rename content in ShareFolderAdvanced

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#2310]
## Bug description & symptom

ShareFolderAdvanced don't need the button to rename the title in PopinFixedHeader

## Expected

PopinFixedHeader need to have a props to hide the edit button,
`disableChangeTitle` can't do the job because it tell that the title can be changed but not in this content or not you.

a solution is to add a props `hideChangeTitleButton` to hide it when set to `true`

**Comment by PhilippeAccorsi** [comment]
Verified.
