### ISSUE TITLE
New endpoint to get guest upload informations

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#2322]
## Bug description & symptom

A endpoint is needed in order to get guest-upload information, This endpoint should provide information such as if a password is needed for the upload and if the token is valid

## Expected

Path : `${apiUrl}/public/guest-upload/${upload_permission_token}`
Method : **GET**

Response : 
- Code **200** description : 200, exemple value : `{ "has_password": true }`
- Code **400** description : BAD_REQUEST, error code = 1008 for `UPLOAD_PERMISSION_NOT_FOUND` if token isn't valid

## Impacted components

- *backend*

**Comment by PhilippeAccorsi** [comment]
if I tried this api in /api/v2/doc/ and I give valid token, an error appear ""message": "Upload permission with token \"1d8cc9c7-425c-4c6b-9ee0-a9f397cc8f5a\" not found in database""

Tested on local and if I open link with this token, I can downlload file.

**Comment by PhilippeAccorsi** [comment]
Verified.

**Comment by PhilippeAccorsi** [comment]
> if I tried this api in /api/v2/doc/ and I give valid token, an error appear ""message": "Upload permission with token "1d8cc9c7-425c-4c6b-9ee0-a9f397cc8f5a" not found in database""
> 
> Tested on local and if I open link with this token, I can downlload file.

Error whane testing: download token in upload api :(
With good token in each good api everything is working good.
