### ISSUE TITLE
New share input emails change

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#2330]
## Bug description & symptom

- [x] There is no action caused when you click on the question mark, the (?) should not be displayed as action icons.
- [x] The emails input should have one row and allow resize.

## Expected

A grey button and a smaller input, like the image below:
![image](https://user-images.githubusercontent.com/35422692/63936779-01a8f800-ca61-11e9-8ddb-099b3c47c345.png)
For share at files and upload.

**Comment by celiamgtt** [comment]
I put it in 'in progress' because of the color of the question mark (?) and the link bellow the email field (should be corrected with the latest PR)

**Comment by PhilippeAccorsi** [comment]
Verified.
