### ISSUE TITLE
Share: the interaction with the password field is not clear

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#2337]
## Bug description & symptom

If you click on the link "protect with a password" at share form it is not possible to stop displaying the field afterwards, this is not so clear to the user.

## Expected

- when you click on "protect by password" you will see the field "password" without the "optional" part
- if the field is left blank, it is an error (since the user has chosen to protect with a password)
- if the user changes his mind, he clicks on a link "cancel password protection" or "do not protect by password" before validating the form

**Comment by PhilippeAccorsi** [comment]
Verified.
