### ISSUE TITLE
Review Apache configuration documentation in doc/apache.md

### ISSUE THREAD

**Issue by algooapy** [tracim/tracim#234]

**Comment by xandercagexxx** [comment]
Verified.

**Comment by xandercagexxx** [comment]
One missing information (Before "Load needed proxy modules"):

Open app.wsgi (on Tracim folder)
on line: APP_CONFIG = "/var/www/tracim/tracim/development.ini"
Replace "/var/www/" by your tracim installation path.

**Comment by xandercagexxx** [comment]
Verified.
