### ISSUE TITLE
Better support for public instance limitation in Frontend

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2345]
## Bug description & symptom

Public instance limitations create new error case which should be handled properly by frontend.

backends related issues (merged):
  https://github.com/tracim/tracim/pull/2331, bug:  https://github.com/tracim/tracim/issues/2028, but also #2031 and #2029

## Expected

full frontend support of PR  https://github.com/tracim/tracim/pull/2331, bug:  https://github.com/tracim/tracim/issues/2028, but also #2031 and #2029: Obtain always explicit error message in frontend as user when trying too push too big file in tracim, creating more than limit of workspace allowed or adding file in an already full workspace

More specifically:

- [x] do not allow upload file with more than size limit given by content_length_file_size_limit in config endpoint.
- [x] support specific backend error code related to size limit ? (should not occur at all because of first check in /config) , related to max workspace number allowed and max size of workspace (6001,6002,6003)
- [ ] ~~handle specific content_length_file_size_limit = 0 meaning no limit case.~~

- [ ] ~~add documentation for apache configuration (unclear)~~

**Comment by inkhey** [comment]
@PhilippeAccorsi can you explain what you mean about apache documentation here ( see also previous issue https://github.com//issues/2028)

**Comment by inkhey** [comment]
apache docummentation as been removed from todo list see https://github.com/tracim/tracim/issues/2028#issuecomment-527140951

**Comment by inkhey** [comment]
@Skylsmoi 
to test if this is working correctly, you can play with "limitation.*" parameter in development.ini config.
:warning: https://github.com/tracim/tracim/issues/2029 is not merged yet, so workspace size limitation is not implemented in develop.

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi issue #2029 is now merged.
For the moment limitation is just make about size of shared space. For first version of tracim 2.4, we not control size of each individual file when we upload one or multiple files.

**Comment by Skylsmoi** [comment]
This issue is in stand by and will be fixed in v2.4.1

**Comment by inkhey** [comment]
error 6001 -> POST /api/v2/workspaces
error 6002 -> POST /api/v2/workspaces/{workspace_id}/files, PUT /api/v2/workspaces/{workspace_id}/files/{content_id}/raw/{filename:[^/]*},  (POST /api/v2/public/guest-upload/{upload_permission_token} raise not yet this exception but should if https://github.com/tracim/tracim/issues/2385 is fixed )
error 6003 -> OST /api/v2/workspaces/{workspace_id}/files, PUT /api/v2/workspaces/{workspace_id}/files/{content_id}/raw/{filename:[^/]*}, POST /api/v2/public/guest-upload/{upload_permission_token}

**Comment by Skylsmoi** [comment]
I'm removing the task of handling content_length_file_size_limit = 0 since the backend does this check at the very beginning of the upload so it doesn't add any value to check the file size right before sending it

**Comment by PhilippeAccorsi** [comment]
Error code 6004 have no message:
~~~
details    {…}
error_detail    {}
message    File cannot be added (size "277902") because owner space is full: "5253904/5242880"
code    6004
~~~

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi can you add this error code, this error code not existed at beggening of this issue.

**Comment by PhilippeAccorsi** [comment]
Other error code working good (with translation).

**Comment by Skylsmoi** [comment]
error 6004 is now handled

**Comment by PhilippeAccorsi** [comment]
Verified.
