### ISSUE TITLE
Creation of contents with the same label and/or filename

### ISSUE THREAD

**Issue by herawo** [tracim/tracim#235]
When creating  2 files with the same name, a message saying that it's not possible is displayed when creating the second one, but it still is created.

**Comment by algooapy** [comment]
- The `PathValidationManager` (`tracim/tracim/lib/integrity.py`) detects the invalid path.
- The renderer `tracim/tracim/lib/integrity.py:render_invalid_integrity_chosen_path`, at some point, commits the pending transaction instead of rolling it back.

**Comment by xandercagexxx** [comment]
verified. Ubuntu 17.04
