### ISSUE TITLE
Fix migration issue with Sequence

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2354]
## Bug description & symptom

Latest database change about share and upload does not match correctly between migration script and latest database current state (the one we get when we do create database at first.

## Expected

Repair migration scripts to have all database with same configuration, unless not created the same way.

**Comment by inkhey** [comment]
Current sequences names on fresh database install in postgresql :

- content_id_seq
- content_revisions_revision_id_seq
- seq__content_share__share_id
- seq__groups__group_id
- seq__permissions__permission_id
- seq__upload_permission__permission_id
- seq__users__user_id
- seq__workspaces__workspace_id

**Comment by inkhey** [comment]
After few search, i can confirm this issue cannot happened on sqlite and mysql/mariadb as Sequence is not supported there (they do support only autoincrement mecanism which doesn't give name to sequence).

**Comment by inkhey** [comment]
Trouble with upload_permission may be solved with : 
```
ALTER SEQUENCE upload_permissions_upload_permission_id_seq RENAME TO seq__upload_permission__permission_id;
```

**Comment by inkhey** [comment]
Migration script here:  https://github.com/tracim/tracim/commit/7464b82612d0ea315d9f81ebdf751c86f1b54e58 solve the issue (checked manually).
- need to be check with production database to verify it really solve the issue in real context.
- wait for tests: https://travis-ci.org/tracim/tracim/builds/580204262?utm_source=github_status&utm_medium=notification

This is just a migration script which mean it doesn't require any downgrade.
This patch doesn't solve the inconstency of seq name in tracim. it's unclear how we should deal with it.

content and content_revision do a implicit seq with look created automatically by sqlalchemy (not reference at all about them in source code).

Other, use explicit sequence which is used to get next valid value in sqalchemy context but is not setted as default value in postgresql server side. so if we do use sqlalchemy, next value use will be associated to sequence but if we do use directly database, we should explictly add a value to the field.

**Comment by PhilippeAccorsi** [comment]
>     * need to be check with production database to verify it really solve the issue in real context. (@PhilippeAccorsi )
> 

tested with dump of production and its working good with this command `alembic -c development.ini upgrade head`.

**Comment by PhilippeAccorsi** [comment]
Verified.
