### ISSUE TITLE
The semicolon does not work as a email separator

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#2356]
## Bug description & symptom

For sharing creation, the semicolon does not work as a email separator.

## Expected

Add new separator ;

**Comment by PhilippeAccorsi** [comment]
Semicolon already exist in code but not explicit in frontend. Fix with this commit https://github.com/tracim/tracim/commit/dcde97ab77919536fe0289f5ac57d379095ea469

**Comment by PhilippeAccorsi** [comment]
Verified.
