### ISSUE TITLE
Content list cycling when closing collaborative Iframe

### ISSUE THREAD

**Issue by basilelegal** [tracim/tracim#2360]
## Bug description & symptom

If you open a content with collabora, close it then open a new content from another workspace with collabora. The content list of the last workspace will appear before loading to the actual. 

## Expected

The last workspace's content list should not appear

**Comment by PhilippeAccorsi** [comment]
Verified.

**Comment by PhilippeAccorsi** [comment]
Verified with small database and content.
Need to be check with bigger database to make sure is working good.

**Comment by PhilippeAccorsi** [comment]
Verified.
