### ISSUE TITLE
UX: better messages and its translations at upload

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#2365]
## Bug description & symptom

Some messages are not clear enough or don't have a good translation.

## Expected

Replace ... by ...
- [ ] "You can now close this page, your recipient will receive the notification of your import" ("Vous pouvez maintenant fermer cette page, votre destinataire va recevoir la notification de votre import.") => "Your interlocutor has been notified of your upload. You can close this window." ("Votre interlocuteur a été notifié de votre téléversement. Vous pouvez fermer cette fenêtre.")
- [ ] In french, "importer/importation" => "téléverser/téléversement".
- [ ] Drag and drop your file here ("Glisser déposer un fichier ici") => Drag and drop your files here ("Glisser déposer vos fichiers ici")
- [ ] You can also import your file by clicking here ("Vous pouvez aussi sélectionner votre fichier en cliquant ici") => You can also import your files by clicking here ("Vous pouvez aussi sélectionner vos fichiers ici")
- [ ] You have not yet chosen any files to download. ("Vous n'avez pas encore sélectionné de fichiers à télécharger.") => You have not yet chosen any files to upload. ("Vous n'avez pas encore sélectionné de fichiers à téléverser.")
- [ ] "Email notification are disabled, please manually notify the link"("Les notifications par email sont désactivées, veuillez informer le lien manuellement") => "Email notification are disabled, please manually share the link" ("Les notifications par email sont désactivées, veuillez communiquer le lien manuellement")

**Comment by PhilippeAccorsi** [comment]
@gbonaspetti For this 
~~~
Just the translation "Les notifications par email sont désactivées, veuillez informer le lien manuellement" => "Email notification are disabled, please manually notify the link"
~~~
Discuss with @Skylsmoi to find better message.

**Comment by gbonaspetti** [comment]
@Skylsmoi "Email notification are disabled, please manually notify the link": "Les notifications par email sont désactivées, veuillez communiquer le lien manuellement" ?

**Comment by gbonaspetti** [comment]
After discussion, we decided for "Email notification are disabled, please manually inform the link": "Les notifications par email sont désactivées, veuillez communiquer le lien manuellement"

**Comment by PhilippeAccorsi** [comment]
Verified.
