### ISSUE TITLE
add upload message to upload notification email

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2366]
## Bug description & symptom

Currently, upload message doesn't return message of the uploader in email received by workspaces users.

## Expected

- [ ] add uploader message in mail template after files list.
- [ ] translation working
- [ ] if  line start with word "Message:", in case are without message need to be explicit

**Comment by PhilippeAccorsi** [comment]
Edited issue to add what is expected.

**Comment by PhilippeAccorsi** [comment]
Verified.
