### ISSUE TITLE
Fichier CSS et JS manquant ?

### ISSUE THREAD

**Issue by d-stephane** [tracim/tracim#237]
Je viens de faire l'install de la dernière version présente sur github. Tout s'est bien déroulé.
Après lancement de l'appli par run.sh je vais sur la page d'accueil qui s'ouvre bien mais sans avoir chargé le CSS. Firebug indique que le fichier ``assets/dist.all.css`` est introuvable, idem pour ``assets/dist.all.js``

**Comment by tracim** [comment]
Bonjour,
Effectivement, il faut installer les dépendances frontend :
https://github.com/algooapy/tracim#frontend-dependencies
Cordialement,

**Comment by d-stephane** [comment]
Ok vu, je viens de relancer l'install et ça plante sur le message suivant :
<pre>
└─ $ ▶ npm run gulp-dev
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "gulp-dev"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0

npm ERR! missing script: gulp-dev
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/stephane/.npm/_logs/2017-06-12T06_51_13_301Z-debug.log
</pre>
Le fichier de log :
<pre>
└─ $ ▶ cat /home/stephane/.npm/_logs/2017-06-12T06_51_13_301Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'gulp-dev' ]
2 info using npm@4.2.0
3 info using node@v7.10.0
4 verbose stack Error: missing script: gulp-dev
4 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
4 verbose stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:311:12
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:449:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
5 verbose cwd /home/stephane/tracim
6 error Linux 3.16.0-4-amd64
7 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "gulp-dev"
8 error node v7.10.0
9 error npm  v4.2.0
10 error missing script: gulp-dev
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
</pre>
Une idée d'ou peut venir le soucis ?

**Comment by Skylsmoi** [comment]
npm run gulp-dev est une commande qui n'est pas encore merge sur le master tracim/tracim, il le sera bientôt, en attendant tu peux faire, depuis la racine du dossier tracim :
$ gulp dev
ou
$ gulp prod
en fonction de si tu souhaites un environnement de dev ou de prod. Cela générera les fichiers all.css et all.js

**Comment by lebouquetin** [comment]
@algooapy @Skylsmoi il faut que vous vous synchronisiez pour avoir une doc à jour sur master (quitte à l'upgrade plus tard

**Comment by d-stephane** [comment]
Super, avec **gulp dev** tout fonctionne. Merci bien
