### ISSUE TITLE
Remove collabora from end point content type list

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2372]
## Feature description

Collabora content type wont be returned by api anymore. Do the necessary to still have the option in dropdown create content

## Context

Collabora files are not real content type. The content type is File which now has a sub content type Collabora.

## Impacted components

frontend
frontend_lib

## Extra information

This will require an ugly as hell fix since it'll require to hard code the collabora entry in the dropdown.
It'll include a FIXME with an associated issue that will be addressed in v2.5

**Comment by Skylsmoi** [comment]
Hack added by this commit:
https://github.com/tracim/tracim/commit/c3f117e191c4bed3e14087c961a650c880254f64

**Comment by PhilippeAccorsi** [comment]
Verified.
