### ISSUE TITLE
Adding the same file mulitple time in the guest upload form

### ISSUE THREAD

**Issue by basilelegal** [tracim/tracim#2379]
## Bug description & symptom

You can add the same file multiple time to the guest upload form. That cause a javascript error but it won't crash app. When submitting the form an error will  happen on the server side causing the API to upload nothing.

## Expected

If you try to add a  file with the same filename, warn the user that the file is already in the form and don't add it.

**Comment by PhilippeAccorsi** [comment]
Verified.
