### ISSUE TITLE
Collabora : missing collabora edit button in app file + wrong icon in dashboard

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2389]
## Bug description & symptom

The button to edit a content with Collabora is missing.
The button to create a collabora content from the Dashboard is wrong
The button to create a collabora content label isn't translated

## Diagnostic

the first one is due to a missing variable during the refactor of app collabora name
the second one might be due to the hack of content type for collabora

## Expected

The buttons are properly displayed

## How to reproduce

- Create a Collaborative document
- you can't edit it.

## Impacted components

Frontend
App collaborative document

**Comment by PhilippeAccorsi** [comment]
This is fix in 2.4
