### ISSUE TITLE
New workspace's properties (about public share) haven't been added to redux

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2392]
## Bug description & symptom

When switching workspaces, if one has share features activated and the other doesn't, the inbox in content list isn't refreshed

## Diagnostic

Api now give properties about share feature that aren't replicated in redux.
Also, the state `currentWorkspace` doesn't stay up to date when switching workspace.

## Expected

When switching to a workspace that doesn't have the share folder features activated, the share folder should not be visible

## How to reproduce

Have 2 workspace, one with public upload activated and one without.
- open the content list of a workspace
- switch to the content list of the other workspace
The share folder neither appear not disappear (depending on which you opened first)

## Impacted components

frontend

**Comment by PhilippeAccorsi** [comment]
Message about last commit:
~~~
    The issue was already fixed but I added a new cypress test for this issue and add more constency between workspaceList and currentWorkspace
    When a share property is changed, the workspaceList and the currentWorkspace is refresh in redux (same for agenda)
~~~

This issu is fixed.
