### ISSUE TITLE
Better support for emoji in comment

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2399]
## Bug description & symptom

Currently there is not specific frontend support for emoji in comment, which may be nice.

## Expected

- emoji list available in rich text editor(maybe https://www.tiny.cloud/docs/plugins/emoticons/ )
- support for colored emoji ?

**Comment by PhilippeAccorsi** [comment]
We want also to support emoji without tinymce on non rich text. 

We can add a button like this one visible in Tinymce:
![Screenshot_2020-09-23 ef · defe · Unstable](https://user-images.githubusercontent.com/25848257/94012937-b23f1380-fda9-11ea-9572-14f941028d83.png)
And when we clic on this button we seen something like this (also visible in tinymce):
![Screenshot_2020-09-23 ef · defe · Unstable(1)](https://user-images.githubusercontent.com/25848257/94013055-d39fff80-fda9-11ea-841b-1d27af0d4a74.png)

**Comment by inkhey** [comment]
duplicate of https://github.com/tracim/tracim/issues/4436
