### ISSUE TITLE
Allow to delete a user and anonymise information about him/her (from CLI + from User admin. page)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2401]
## Feature description

Add one button to delete user completely in tracim. When user is deleted, all information about this user need to be anonymized.

## Context

For the moment, its necessary to manually delete user directly in database.

## Prerequisites

- find solution to anonymize tracim about deleted user (changing name by random name, or change by unnamed, etc.)

## Impacted components

- *backend*
- *frontend*

## Extra information

For first version, it is acceptable to use CLI command to solve this problem if it's complicated to solve that in 2.4.x

**Comment by lebouquetin** [comment]
After talk with @PhilippeAccorsi and first release of the feature through a python script, here comes my expectation (to be discussed) about this feature:

- allow to delete a revision
- allow to delete a content (which also drops all related stuff: revisions, shares, comments, etc)
- allow to delete a shared space (which also drops all related stuff: roles, contents, revisions, calendar, etc)
- allow to delete a user account (only the  user account and direct stuff like roles)
- allow to delete a user account "full" (user + workspaces)

All operations must be explicit or fail. Eg "full drop of a user" (ie user + shared spaces) should drop all data or fail. If anonymisation is required, an option should be given as CLI parameter.

Eg:

- `tracimcli delete_user --transfer-sharedspace-ownership-to 4` (drop user and give workspaces to user ')
- `tracimcli delete_user --drop-owned-sharedspaces` (drop user and owned shared spaces - fails if contents or comments make problem')
- `tracimcli delete_user --anonymize-undeletable-content`
- `tracimcli anonymize_user --anonymize-undeletable-content`

You should also add a `--force` parameter which allow to bypass the controls.

Note: commands must always execute explicit operations. Do not anonymize some data if the CLI user did not explicitly ask for doing this. Better fail and suggest to add an option

**Comment by inkhey** [comment]
Some other technical aspect:

1. To make this work more correctly, we do need to make prevent_content_revision_delete skippable, if we do not do this, we can't easily delete revision.
2. As code may be really similar to Lib (internal api), it make sense to extend either existing lib with delete method or have a "cleanup" lib. Extend existing lib can look more logical, but specific lib has both advantage of clearly distinct this kind of hard deletion from other part of tracim source code and allow us to more easily provide a "test mode" which will do nothing but explain what will be done.
3. to avoid delete thing if something crash during transaction, we should probably apply depot file and calendar deletion at the end of the deletion process.

**Comment by lebouquetin** [comment]
Some part of mattermost discussion:

principe derrière ça : 

- ouvert à l'extension (tu développes des fonctionnalités qui peuvent être utilisées différemment de ce que tu as en tête au moment de développer)
- fermé à la modification (utiliser ton code "métier" dans un autre contexte ne doit pas nécessiter de réécrire le code)

en terme de granularité, je pense qu'on doit pouvoir aller au moins jusqu'au contenu (si j'ai importé par erreur un document sur tracim, je dois pouvoir le supprimer totalement), voire une révision (même cas de figure mais pour ne pas perdre l'historique - par exemple, j'ai upload une nouvelle version de mon fichier qui est pas du tout le bon document)

à noter qu'il faut qu'on puisse indifféremment supprimer tout type de contenu (un fichier, un doc html, mais aussi un commentaire directement)

les options d'exécution qui me paraissent nécessaires dans cette première version :

- pas d'option spécifique = soit ça réussit simplement soit ça échoue
- option "best-effort" = supprime ce que ça peut et anonymise ce qui ne peut pas être supprimé

idéalement, on propose aussi une fonction "anonymiser l'utilisateur" qui ne supprime rien et qui se content d'anonymiser pour supprimer les infos perso (exemple d'utilisation : un collaborateur quitte l'entreprise, on veut garder ses commentaires, ses révisions, etc, mais on veut plus son email et on remplace son nom "Michel DUPONT" par "Michel D."

**Comment by lebouquetin** [comment]
> 1. To make this work more correctly, we do need to make prevent_content_revision_delete skippable, if we do not do this, we can't easily delete revision.

Make sense.

> 2. As code may be really similar to Lib (internal api), it make sense to extend either existing lib with delete method or have a "cleanup" lib. Extend existing lib can look more logical, but specific lib has both advantage of clearly distinct this kind of hard deletion from other part of tracim source code and allow us to more easily provide a "test mode" which will do nothing but explain what will be done.

make sense also. A dedicated lib is a good idea

> 3. to avoid delete thing if something crash during transaction, we should probably apply depot file and calendar deletion at the end of the deletion process.

Make sense also. I'm pretty sure the depot module manage this for you. Please check before to start "writing something to manage this case"

**Comment by inkhey** [comment]
@lebouquetin 
We need to make decision about the form of the anonymous user display_name 
and the anonymous user email (it should be always an email like to not break code).

Email should be unique so we need an id into it. 
For display name, it's possible to have more user-friendly naming. It's unclear if we did need/want/should allow to always distinct 2 anonymous user in UI.

see also WIP PR:
https://github.com/tracim/tracim/pull/2591/files#diff-c0143b5b932b3a2c589d95174a07d11bR308

**Comment by lebouquetin** [comment]
There are two cases, I think:

- on "Mon Tracim" public instance the anonymisation should be standard, like what is going on on Github for example
- on an on-premise instance, the anonymisation should be better done with possiblity for the admin to choose a public_name.

For example, instead of storing `Damien Accorsi`, Algoo would replace my public name to `Damien`. This way the content keep on being coherent, but no private information stay on the server

**Comment by PhilippeAccorsi** [comment]
@inkhey Some necessary modification:
- [ ] `(!) Running in best_effort mode`,change to `best-effort` (like visible in cli command) or `best effort`.
- [ ] `(!) Will Anonymize user if not possible to delete it` change to `(!) Will anonymize user if not possible to delete it`
- [ ] `(!) Custom anonymize name choosen is : "totonestplus"` change to `(!) Custom anonymize name choosen is: "totonestplus"`
- [ ] is it possible to not show this warning all the time but just if we use debug mode? (many line are visible)
~~~
/home/philippe/repo/tracim/backend/env/lib/python3.7/site-packages/apispec/ext/marshmallow/__init__.py:215: UserWarning: <class 'tracim_backend.views.search_api.schema.SearchFilterQuerySchema'> has already been added to the spec. Adding it twice may cause references to not resolve properly.
  UserWarning,
~~~

**Comment by PhilippeAccorsi** [comment]
Verified directly on branch (new workflow for testing).
