### ISSUE TITLE
on smartphone file openned show timeline view and not preview of file

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2403]
## Bug description & symptom

If I open one file on smartphone, I can see timeline information but not preview of file by default. If I want to see preview, I need to scroll up.

## Diagnostic

*Optional - explain what has been found and what is not yet clear. If unknown, write "unknown".*

## Expected

- [ ] on smartphone: show preview of file when you tried to open file (like we have on desktop)

## Context and version information

- Smartphone/Tablet (if applicable)
    - *Device: LG G4*
    - *OS: android*
    - *Browser Firefox, Chrome*

## How to reproduce

- open tracim on smartphone
- open one file
=> tracim not show preview offile but show timeline direclty

## Screenshots

*Optional - add screenshots to help explain your problem.*

*Please consider sharing a [animated GIF screencast generated with peek](https://github.com/phw/peek)* 

## Impacted components

*Optional - list components which will be impacted.*

*For example:*

- *backend*
- *frontend*
- *htmldoc / file / thread app*
- *webdav*
- *...*

*If unsure, write "unknown"*

## Extra information

*Optional - add any extra information which will be usefull for understanding and developing the feature*

**Comment by inkhey** [comment]
This issue is not reproductible in version 4.0. It has already been fixed.
