### ISSUE TITLE
Rich text button displayed in apps is confusing

### ISSUE THREAD

**Issue by celiamgtt** [tracim/tracim#2406]
## Bug description & symptom

Rich text button displayed in apps is confusing because it has the same level of hierarchy as the 'send' or 'cancel' buttons. 

## Expected

To discuss: display a link "text editing in advanced mode" below the comment

## Screenshots

![image](https://user-images.githubusercontent.com/50453784/65042600-7634cf80-d959-11e9-962f-e228a3995866.png)

**Comment by metzgegu** [comment]
The implemented solution in my PR is to transform the `advancedEdition` button to a clickable div

**Comment by gbonaspetti** [comment]
The label and the size of the button are different from that shown on the issue screenshot.

Currently:
![Screenshot from 2020-04-07 16-16-07](https://user-images.githubusercontent.com/35422692/78681801-7bee0480-78ed-11ea-9b41-cb789c40a830.png)

**Comment by gbonaspetti** [comment]
Besides the label and size changes to make the button more similar to the one presented in the issue, I changed the code that made this same button hidden in small interfaces (the commit date was 2 years ago) and this for me didn't make sense with the current interface anymore. @Skylsmoi and @celiamgtt I'm open to discussion if you think it still makes sense to hide the button.

**Comment by celiamgtt** [comment]
For me, it's not mandatory to display it (because it's an advance feature, and I'm not sure it will be useful on mobile), but it could be interesting for 'pro' users.

**Comment by Skylsmoi** [comment]
we hid it because on mobile it is complicated to use tinymce. The screen gets too small when the mobile's keyboard appears. So we disabled the feature to keep things easy for users
Whether we should enable it should be discussed in another issue so I'm commenting your PR to roll back that change

**Comment by lebouquetin** [comment]
@Skylsmoi I'm not sure what you want to rollback @Skylsmoi . If the button is about to re-appear in mobile, then the description of the issue must be updated.

I'm not sure there is good reason for having this feature on small screen because it is not really usable.

**Comment by gbonaspetti** [comment]
@lebouquetin rollback the changes I had made to reappear the button. Back to the way it was.

**Comment by Skylsmoi** [comment]
@lebouquetin in the related PR, @gbonaspetti removed the "display: none" on mobile. This what I want to rollback because the issue wasn't about this fix

**Comment by buxx** [comment]
#2800 tested on it's branch: ok
