### ISSUE TITLE
Indicate the name of the document in the browser tab

### ISSUE THREAD

**Issue by celiamgtt** [tracim/tracim#2408]
## Feature description

It could be interesting to indicate the name of the document in the browser tab. When we have several opened tab, it's not easy to remember which one corresponds to what.

![image](https://user-images.githubusercontent.com/50453784/65044791-e2b1cd80-d95d-11e9-8dcb-f290f9f9153d.png)

**Comment by metzgegu** [comment]
This is resolved with #2593

**Comment by metzgegu** [comment]
This is resolved with #2593
