### ISSUE TITLE
Allow multi-upload in file app

### ISSUE THREAD

**Issue by celiamgtt** [tracim/tracim#2409]
## Feature description

Currently, we can upload a file on tracim. Each file has to be upload independently. It's not really user-friendly. For example, if an user want to upload 20 pictures, he has to do it one by one or use webDAV.

Allow multi-upload in file app is interesting because the user will be able to stay on tracim to do his task.

## Questions

In this case, the management of the interaction with tracim is different from the one we have now. Possibilities : 
- Not display the file app when importing a single or several documents
- All imported files are opened in different tabs
- Open the app file with a file, display the view of all contents when there are several files

**Comment by metzgegu** [comment]
### State of multi-upload in file app :

Without errors :
![MultipleFiles](https://user-images.githubusercontent.com/31687635/71250339-b83a2c80-231f-11ea-9d35-49f7ae9ac40b.gif)

With errors :
![MultipleFilesErrors](https://user-images.githubusercontent.com/31687635/71250369-c6884880-231f-11ea-9759-0959dd33e2fd.gif)

Discussions about design is open

**Comment by metzgegu** [comment]
I closed this issue by mistake

**Comment by PhilippeAccorsi** [comment]
Tested on branch and verified. (wait merge to close issue).

**Comment by PhilippeAccorsi** [comment]
Verified on develop.
