### ISSUE TITLE
drag and drop on smartphone

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2434]
## Bug description & symptom

On smartphone, we can see a cross about drag&drop feature but this feature is not available.

## Diagnostic

*"unknown".*

## Expected

- [ ] not show drag&drop button on smartphone if drag&drop feature can't work on smartphone

## How to reproduce

- click on the left of content visible in list of contents. 
- a cross about drag&drop is shown.

## Impacted components

- *frontend*

## Extra information

**Comment by gbonaspetti** [comment]
Fixed at https://github.com/tracim/tracim/commit/8398b5337ed35e90168001132aa265d87b6bf05d
