### ISSUE TITLE
Change buttons label in app file for online editable content

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2444]
## Bug description & symptom

In app File with Collaborative document, there are 2 edit buttons.
One to update a new file and other to open collabora and edit the document online.

The 2 labels are "Update" and "Edit online"

## Diagnostic

Problem is that the generic Update button could be rename "Replace" but it would be inconsistent with other content type File

## Expected

The labels are clearer.
Following what was discussed in the comments on this issue, the change should be as follows:

- Before
![antes](https://user-images.githubusercontent.com/35422692/79723606-58ac5780-82e6-11ea-9de1-381dc8239bc9.png)

- After
![expected](https://user-images.githubusercontent.com/35422692/79723621-5cd87500-82e6-11ea-9f0f-7a6e6299ecf7.png)

## How to reproduce

Open a collaborative edition in a workspace you are at least collaborator

## Impacted components

app File
app Collaborative

## Side effects
By making this change some side effects will be found:

- Problem of interface on medium screens (991 - 768px).

![sideeffectMD](https://user-images.githubusercontent.com/35422692/79723837-c2c4fc80-82e6-11ea-9ca7-94ce424280fb.png)

The solution discussed was to hide the button label, as is done on small and extra small screens.

![solutionMD](https://user-images.githubusercontent.com/35422692/79723924-edaf5080-82e6-11ea-9520-606483c2def1.png)

- Problem of interface on large screens (1199 - 992px) in languages other than English.

![sideeffectFR](https://user-images.githubusercontent.com/35422692/79724037-27805700-82e7-11ea-9ff4-73c13dc99b80.png)

The solution discussed was to hide the Status button label only for file type content, as is done on medium, small and extra small screens.

![SolutionFR](https://user-images.githubusercontent.com/35422692/79724186-644c4e00-82e7-11ea-8849-84631d1be2f9.png)

**Comment by celiamgtt** [comment]
Idea:
<img width="634" alt="Capture d’écran 2019-12-24 à 14 40 18" src="https://user-images.githubusercontent.com/50453784/71415317-59e0b700-265b-11ea-8b92-6a2765ee605b.png">

**Comment by Skylsmoi** [comment]
I like the icons.
One thing I don't like is to change the Update btn too much because it should stay relatively the same as the other apps.
Could we put "Update new version" and "Edit online" ?

**Comment by celiamgtt** [comment]
I like "Update new version", it's even more understandable! But I wonder if it's not a little too long (especially on mobile).

**Comment by Skylsmoi** [comment]
On mobile, buttons label are already hidden so that wont be a problem

**Comment by raphj** [comment]
I suggested "Upload a new version" instead of "Update new version" to @celiamgtt, seems good to her.

**Comment by Skylsmoi** [comment]
good to me too

**Comment by gbonaspetti** [comment]
@Skylsmoi @celiamgtt @raphj 
Currently the button labels are hidden from the small screens (767px -), but with this update we have an interface problem in the medium screens too (991 - 768px), so the label will be hidden sooner. 
Knowing that the button component is the same used in html-document, I am adding a screenshot of the html-document app with the hidden button for you to see how it looks and give your approval.

![doc1](https://user-images.githubusercontent.com/35422692/79571168-09361380-80bb-11ea-88c3-95cd570d5cad.png)

**Comment by celiamgtt** [comment]
Looks fine for me! How does it behave for the file app? (especially the 'visualize' button)

**Comment by Skylsmoi** [comment]
it's fine to me too

**Comment by gbonaspetti** [comment]
@celiamgtt file app 991px
![Screenshot from 2020-04-17 15-02-05](https://user-images.githubusercontent.com/35422692/79572082-9f1e6e00-80bc-11ea-8f18-7e7c6c8a11ab.png)

**Comment by gbonaspetti** [comment]
When doing some more tests, I saw that the problem persists on large screens (1199 - 992px) when we change the language. As you can see in the image below:

![Screenshot from 2020-04-17 15-53-14](https://user-images.githubusercontent.com/35422692/79576511-b0b74400-80c3-11ea-925f-56f71a53a787.png)

In this case I think it is better to simplify the Status button only in the app file, as it is already done in the medium screens. What do you think?

![Screenshot from 2020-04-17 15-57-20](https://user-images.githubusercontent.com/35422692/79577020-5bc7fd80-80c4-11ea-9eff-49038cf3d6d7.png)

**Comment by celiamgtt** [comment]
Yes I think it's the best idea to reduce the status button like for the medium screens.

**Comment by Skylsmoi** [comment]
I think the button is too big, but it is self explanatory
I'm a bit stuck

**Comment by Skylsmoi** [comment]
I will agree with celiamgtt for now

**Comment by gbonaspetti** [comment]
To solve this issue the changes made in the PR were:
- Change the label of the button from "Update" to "Update a new version" and its translations.
- Change the icon of the same button. To do this by keeping the same icon in the html-document, the icon became a props of the component.
- Hide the label of the same button from the medium screen.
- Hide the status details in the app file from the large screen.

**Comment by lebouquetin** [comment]
Sorry I arrive late, but in an issue related to a given button you must not change another button.

I totally disagree with the choice to change status button in current bugfix: the issue label is "In app File with a Collaborative document, difference between the 2 update buttons in unclear", nobody can expect that there is a change in another button.

By the way, the issue is about changing something but does not show what to change. How a user/developer/project manager can understand the issue if change does not show before/after result?

If you decide to change the status button also, then the issue label and description must be updated.

**Comment by gbonaspetti** [comment]
Issue updated with the missing information.

**Comment by lebouquetin** [comment]
:+1:

**Comment by metzgegu** [comment]
Verified on branch (wait merge to close).

**Comment by metzgegu** [comment]
After merging the first PR, some consistency issue where found with the upload icon (`FileDropzone` use `fa-download` instead of `fa-upload`), this new PR #2913 fix that.
