### ISSUE TITLE
Upload popup : attached files with a long name aren't cropped and delete button is hidden

### ISSUE THREAD

**Issue by celiamgtt** [tracim/tracim#2451]
## Bug description & symptom

When the upload popup is displayed, attached files with a long name aren't cropped and delete button (icon) is hidden with a horizontal scrollbar. 

## Screenshots

![bug_upload_longname](https://user-images.githubusercontent.com/50453784/65673873-ef17e380-e04b-11e9-985d-6d1e44ca57bf.gif)

## Impacted components

- frontend
- upload

**Comment by PhilippeAccorsi** [comment]
@metzgegu Can you add commit reference for this fix (its seem to be fix in 2.6.1)

**Comment by metzgegu** [comment]
It was fixed in this commit: 5276413d7dc82f2c6c62f55cfe4bd4d2a4d09ceb
