### ISSUE TITLE
Comments : links are not clickable (simple text)

### ISSUE THREAD

**Issue by celiamgtt** [tracim/tracim#2454]
## Bug description & symptom

When the user writes a comment in simple text, the links are not clickable. Links are clickable when they're created in rich text.

## Diagnostic

 It is necessary to add a behavior that detects links and wrap in html (tag < a / >) to make them clickable. 

## Expected

All links should be clickable.

## Screenshots

![image](https://user-images.githubusercontent.com/50453784/65675074-e6281180-e04d-11e9-8d47-71bf578a0dae.png)

## Impacted components

 unknown

**Comment by metzgegu** [comment]
In order to transform html string with links in anchor `tag` to get clickable links, we could use some lib which is mentioned [here](https://stackoverflow.com/a/21925491), I tested [Autolinker.js](https://github.com/gregjacobs/Autolinker.js) and it works well.
But it will force every comments to have links when the user write any url, and this is not the behavior of rich text, indeed links need to be made with the tinyMCE url tool

**Comment by Skylsmoi** [comment]
Every comments are html content, so the normal comments wont be an issue.

The question is whether we run linker script right before displaying the comments or at the comment's creation.

**"linking" comments before displaying them in timeline:**
pros:
  - the user's comment is saved as it is created

cons:
  - require parsing every comments

**"linking" comments at creation:**
pros:
  - no additional processing for viewing

cons:
  - a script will edit the user's comment after he saves it

**Comment by Skylsmoi** [comment]
I'm for the script running at the comment save.

The changes that it will do is manageable and it'll reduce the processing time for display.

We can also handle the case where a link added without the `<a>` tag in rich text can have been done intentionally

**Comment by metzgegu** [comment]
I'm also for the script running at comment save

**Comment by gbonaspetti** [comment]
Verified on branch (wait merge to close).

**Comment by PhilippeAccorsi** [comment]
Do you have tested comment visible in thread app ?

**Comment by gbonaspetti** [comment]
@PhilippeAccorsi yes

**Comment by PhilippeAccorsi** [comment]
Great :)
