### ISSUE TITLE
Comments : links aren't displayed correctly (white on white background)

### ISSUE THREAD

**Issue by celiamgtt** [tracim/tracim#2455]
## Bug description & symptom

In comments, links created in rich text are written in white on a white background.

## Expected

Links should be the color of the application to which they belong.

## Screenshots

![bug_whitelinks](https://user-images.githubusercontent.com/50453784/65675642-d3620c80-e04e-11e9-9a76-a1559fc06acb.gif)

## Impacted components

unknown

**Comment by PhilippeAccorsi** [comment]
Make sure url link color is also good when it is a comment from one other user.
We have changed the color since client says url link is not really visible in app thread (app color is blue and color for link is also blue by default)

**Comment by inkhey** [comment]
To be sure, we should verify this issue for both sender (be the user that send the link in comment) and receiver (be another person that received the comment) case.

**Comment by PhilippeAccorsi** [comment]
Verified.
