### ISSUE TITLE
Upload a file : long names without space aren't cropped

### ISSUE THREAD

**Issue by celiamgtt** [tracim/tracim#2457]
## Bug description & symptom

When the user uploads a file, if the name is long and without space, it's not cropped.

## Screenshots

![bug_nomtroplong_upload](https://user-images.githubusercontent.com/50453784/65677877-a9aae480-e052-11e9-97a9-96c4379d8f9e.gif)

## Impacted components

unknown

**Comment by PhilippeAccorsi** [comment]
Fix with multiple import.
