### ISSUE TITLE
Add limit for user-workspaces size

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2476]
## Feature description

A good limitation feature for tracim, should be having a user workspace size limit. Idea is that limit is not per workspace but per user. After limit is reached anyone in workspace concerned cannot add any file content on thoses workspace.

Example: User A should have 1Go of space but may have 3 workspaces where he is owner. In all those three workspace, maximum size of all files summed should not excess more than 1 Go (in fact we do limit after first excess).

This feature should also be added to api in order to change default value for user at user creation and user deletion.

Default value for new user must be defined in config file, default default is 0 meaning "no limit".

Todo:

- Add `allowed_space` field to user table with integer value as byte size of max allowed size.
- Default value is defined in config file; default default value is 0 meaning "no limit".
- Add allowed_space to user create/update endpoint
- `limitation.default_allowed_space_per_user` config in config file ? (default value to 0 aka infinite)

**Comment by lebouquetin** [comment]
I edited the description, it's ready now.

**Comment by inkhey** [comment]
it's unclear which endpoint to use to add allowed_space parameter to update user limit.
Only endpoint with similar approach is `/api/v2/users/{user_id:\d+}/profile` as it's only available for administrator user and does action on user. Should we use this one, add a new one, other ?

**Comment by inkhey** [comment]
decision was made to create a new endpoint : /api/v2/users/{user_id:\d+}/allowed_space

**Comment by PhilippeAccorsi** [comment]
Tested with one user and two shared space, and also with one external user. Space is correctly  managed.

Verified.
