### ISSUE TITLE
Support workspace with same name without any trouble

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2477]
## Bug description & symptom

According to https://github.com/tracim/tracim/issues/1093, it's not anymore possible to create 2 workspaces with same label. This is not a database limitation so, it's always possible to have same label workspace (see https://github.com/tracim/tracim/issues/1096 old issue about making database more strict).

This limitation on name is not really useful, so, we need to find a way to re-allow same label in workspace without breaking things. For exemple webdav, is a context where it's will cause many trouble to have 2 dir with same name at same level, we do need to adapt name when name doublon does exist in webdav view. We also do need to have similar mecanism in frontend in order to return clear result.

## Expected

- User can be member of multiple workspace with same name. It's possible to create workspace with an already used name
- ~~unicity on owner/workspace name ?~~ useless
- When user is member of multiple workspace with same name, they do appear with distinct name in both web ui and webdav. ex: `perso~~234` (with 234 as workspace_id)

**Comment by PhilippeAccorsi** [comment]
Verified.
