### ISSUE TITLE
Unable to handle 2go+ byte value in allowed_space

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2489]
## Bug description & symptom

`allowed_space` is store as integer field in users database table. As value are byte value of size, this mean limit is 2147483647 Which mean we can't use 2Go+ value.

We should allow using bigger value there.

## Expected

- convert allowed_space as bigint (handle more than 8000 petabyte as value) to allow work with bigger value.

**Comment by PhilippeAccorsi** [comment]
Verified.
