### ISSUE TITLE
Filename "Feedback SW - 24/10/2019" does not allow online edition with collabora

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#2493]
## Bug description & symptom

I created an office doc on tracim with name `Feedback SW - 24/10/2019`. The file is created but Collabora fails to open it.

## Diagnostic

I suspect the slash to be the reason for this file not being editable: if I replace the `/` with `-`, the file is editable.

## Expected

Being able to edit any file available on tracim.

## Context and version information

I'm running tracim v2.4.3 with the docker image.

**Comment by PhilippeAccorsi** [comment]
Related to #2219 
This is a bug in collabora.

**Comment by inkhey** [comment]
as explained in #2219,  a workaround (https://github.com/tracim/tracim/pull/2220) to make '/' naming working in collabora is not merged. Best solution will be a fix from collabora side.
