### ISSUE TITLE
Contents icons aren't correctly aligned

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#2494]
## Bug description & symptom

Contents icon and folder icon aren't correctly aligned : 

![image](https://user-images.githubusercontent.com/31687635/67931284-cd1cfe00-fbc1-11e9-9a5b-ca78da776652.png)

## Diagnostic

Content icon don't have fixed width like folder icons 

## Expected

Content icon and text to be correctly aligned

**Comment by PhilippeAccorsi** [comment]
Verified.
