### ISSUE TITLE
Installation failed on Debien 8 jessie

### ISSUE THREAD

**Issue by tiaris** [tracim/tracim#2497]
## Bug description & symptom
./setup_default_backend.sh

Installation stopped with message

install nodejs success

[10:35:27] $ verify if nodejs 10.x is now installed
./setup_default_backend.sh: line 149: node: command not found

[10:35:27] $ nodejs 10.x and npm are not installed - you use node "" - Please re-install manually your version of nodejs - tracim install stopped

## Expected

*Describe the expectations in order to consider the bug resolved**

## Context and version information

*Optional - describe the environment which reveals the bug:*

- Desktop environment (if applicable)
    - *OS: [e.g. iOS]*
    - *Browser [e.g. chrome, safari]*
    - *Version [e.g. 22]*
- Smartphone/Tablet (if applicable)
    - *Device: [e.g. iPhone6]*
    - *OS: [e.g. iOS8.1]*
    - *Browser [e.g. stock browser, safari]*
    - *Version [e.g. 22]*

*...*

## Prerequisites

*Optional - list issues that must be closed before the current one.*

- *#xxx*
- *...*

## How to reproduce

*Optional - detail steps to reproduce the behavior:*

1. *Go to '...'*
1. *Click on '....'*
1. *Scroll down to '....'*
1. *See error*

## Screenshots

*Optional - add screenshots to help explain your problem.*

*Please consider sharing a [animated GIF screencast generated with peek](https://github.com/phw/peek)* 

## Impacted components

*Optional - list components which will be impacted.*

*For example:*

- *backend*
- *frontend*
- *htmldoc / file / thread app*
- *webdav*
- *...*

*If unsure, write "unknown"*

## Extra information

*Optional - add any extra information which will be usefull for understanding and developing the feature*

**Comment by PhilippeAccorsi** [comment]
Hi @tiaris,

Can you give me the version of Debian Jessie you used?
Can you paste here the command you have used to install tracim? (like you have used in your terminal). Do you used sudo or do you have added root in parameter of the script?

Thanks in advanced.

> ## Bug description & symptom
> 
> ./setup_default_backend.sh
> 
> Installation stopped with message
> 
> install nodejs success
> 
> [10:35:27] $ verify if nodejs 10.x is now installed
> ./setup_default_backend.sh: line 149: node: command not found
> 
> [10:35:27] $ nodejs 10.x and npm are not installed - you use node "" - Please re-install manually your version of nodejs - tracim install stopped

**Comment by tiaris** [comment]
My debian is a classical Debian 8 with ISPconfig

cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ cat /etc/debian_version
8.11

problem was with ntm package I have installed it with apt-get npm
I tried another time and get these other errors. 

ERROR: Package 'pip' requires a different Python: 3.4.2 not in '>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*'
[16:41:46] $ failed to install pip and setuptools
ERROR: Could not find a version that satisfies the requirement preview-generator==0.11 (from -r requirements.txt (line 51)) (from versions: 0.1.22, 0.1.24, 0.1.25, 0.1.26, 0.1.27, 0.1.28, 0.1.29, 0.1.30, 0.1.31, 0.1.32, 0.1.33, 0.1.34, 0.1.35, 0.1.36, 0.1.37, 0.1.38, 0.1.39, 0.1.40, 0.1.41, 0.1.42, 0.1.43, 0.1.44, 0.1.45, 0.2.1, 0.2.2, 0.2.3, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.10)
ERROR: No matching distribution found for preview-generator==0.11 (from -r requirements.txt (line 51))
[16:41:57] $ failed to install requirements.txt

ERROR: Package 'python-slugify' requires a different Python: 3.4.2 not in '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*'
[16:42:04] $ failed to install tracim-backend (sqlite_backend)

[16:42:04] $ db init error
./setup_default_backend.sh: line 121: alembic: command not found
[16:42:04] $ alembic stamp head failed

/usr/bin/env: node: No such file or directory
[16:42:05] $ failed to translate ./tracim_backend/locale/en/
/usr/bin/env: node: No such file or directory
[16:42:05] $ failed to translate ./tracim_backend/locale/fr/

**Comment by PhilippeAccorsi** [comment]
Hi,
Thanks for your reply. 
Tracim not work anymore with python 3.4 (we have not change the README but I did now), you need to install python >= 3.5 and use a venv on your system (more information about how to activate a venv https://github.com/tracim/tracim/tree/develop/backend#setup-python-virtualenv )

After activation of your venv you can install tracim correctly.

**Comment by PhilippeAccorsi** [comment]
Hi @tiaris, 
Tracim is it now working on your server?

If not, you can use tracim also with docker image.
Best regards,

**Comment by tiaris** [comment]
Hello,
I want to install it on a production server, as described, No docker system available, and I can not change server configuration. 
I am not a python developper, and I do not have time to understand all requirements. 
For the moment I do not go further on this project.
