### ISSUE TITLE
App File might try to load page 2 even if content only has one page

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2501]
## Bug description & symptom

The app file might try to load the page 2 of a content even if there is only one page. It then fails with an http status 400 that fails to display the content preview.

## Diagnostic

The app asks for the page 2 of the content but it shouldn't since the content only has one page.
The issue happens if you open a content with more than one page, switch to its second page and then open a new content without closing the app.
The app then keep on trying to open the page 2.

## Expected

The app always loads the first page when switching content.

## Context and version information

discovered on mon.tracim.fr

## How to reproduce

- Open a content with more than one page
- Show page 2
- Open another content with only one page without closing the app
- The preview doesn't displays

## Impacted components

App File

**Comment by lebouquetin** [comment]
@Skylsmoi when you open the app, you should drop all its context, shouldn't you?

In current state of source code:

- do you reset each part of context (except this one)
- do you reset none of the context

**Comment by lebouquetin** [comment]
The behavior of an application should be:
1. first load app empty
2. load data (eventually, do not call API if the content id is the same than previous view)

Data and application state should not be stored in the same part of your store

**Comment by PhilippeAccorsi** [comment]
Verified.
