### ISSUE TITLE
App gallery

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#2512]
## Feature description

New app which display files previews of a folder

- Name of the app : frontend_app_gallery
- This app will be a fullscreen app
- Endpoints in backend already exist
- A button will be added in the BtnExtandedAction menu of folders
- A button need to be added for the root of workspace

**Comment by PhilippeAccorsi** [comment]
With this app, we can also delete file directly from gallery.

**Comment by PhilippeAccorsi** [comment]
Verified.
