### ISSUE TITLE
Caractère "?" non supporté dans les noms de fichiers des documents modifiables via Collabora

### ISSUE THREAD

**Issue by jeey** [tracim/tracim#2517]
## Bug description & symptom

Lors de la création d'un "doc. bureautique" (bouton "Créer" / "Créer un doc. bureautique"), si l'on met un "?" dans le nom du fichier, le fichier est apparemment bien créé mais non modifiable (via Collabora) avec un message d'erreur non explicite.
![image](https://user-images.githubusercontent.com/10157300/69000250-e82f8380-08cc-11ea-8250-756b75692a43.png)

## Diagnostic

unknow

## Expected

Rendre impossible la création d'un doc. bureautique comprenant des caractères non supportés ( le caractère "?" notamment - mais pas les """", ça, c'est OK).
Mieux, rendre possible l'édition des fichiers comprenant un ?

## Context and version information

Testé sur Firefox et Chromium (Linux) sous la demo de Tracim (https://demo.tracim.fr/ui/workspaces/11/contents/file/110)

## Prerequisites

*Optional - list issues that must be closed before the current one.*

- *#xxx*
- *...*

## How to reproduce

1. Cliquer sur "Créer" / "Créer un doc. bureautique"
![image](https://user-images.githubusercontent.com/10157300/69000313-b0750b80-08cd-11ea-829b-1f9d2770c9be.png)

1. Saisir un nom avec un ? et cliquer indifféremment sur "Tableur", "Texte" ou "Présentation"
![image](https://user-images.githubusercontent.com/10157300/69000326-f29e4d00-08cd-11ea-8d06-08ac980f3763.png)

1. Puis cliquer sur "Valider et créer" pour avoir le message d'erreur abscons
![image](https://user-images.githubusercontent.com/10157300/69000334-12357580-08ce-11ea-9fbb-a2ba7b223f18.png)

**Comment by inkhey** [comment]
Bonjour et merci pour ce retour.
Le problème présenté ici à déjà été identifié : https://github.com/tracim/tracim/issues/2219 (l'issue est en anglais) et provient de Collabora même. Elle à été reporté à collabora mais en attendant l'issue reste ouverte.
Les caractères "?" et "/" sont bien supporté dans le reste de Tracim.

**Comment by jeey** [comment]
Est-il envisageable en solution de contournement de ne pas autoriser la création d'un document bureautique comprenant le caractère "?" pour éviter toute incompréhension de la part d'un utilisateur lambda ? Cela me paraissant être du côté Tracim et non Collabora.

Définition du problème - Diagnostic - Mise en place d'une solution de contournement - demande de changement (côté Collabora)

**Comment by PhilippeAccorsi** [comment]
Le souci n’est pas seulement visible à la création d’un document bureautique car pour tracim, un document bureautique est en réalité seulement un document de type fichier. Et les caractères spéciaux sont bien gérés pour les fichiers (il y a eu pas mal de test à ce sujet lors de l’ajout du support de ce type de caractère, que ce soit dans tracim ou via webdav).

Néanmoins, c’est une vraie problématique avec les documents qui sont gérés par Collabora  Online/Libreoffice Online. Une solution pourrait être à mon avis d’avoir un message d’erreur explicite qui informe l’utilisateur que les documents de type bureatique ne peuvent avoir les caractères spéciaux”?” et "/" dans leur nom de fichier.

Cela permettrait de comprendre pourquoi je ne peux pas ouvrir un docx par exemple (qui n’a pourtant pas été créé via tracim).

**Comment by inkhey** [comment]
Il existe une proposition de patch à ce sujet, permettant le support des fichiers avec les caractères spéciaux, le principe étant de remplacé les caractères blocant par d'autres non blocants:
https://github.com/tracim/tracim/pull/2220

Le code n'a pas été intégré car non requis dans la version précédente, néanmoins il est envisageable de le réintégré. Cela reste la solution la plus simple en dehors d'une correction côté collabora.

**Comment by gbonaspetti** [comment]
Duplicated with https://github.com/tracim/tracim/issues/2219
