### ISSUE TITLE
Workspace and used used/allowed space info in endpoint

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2518]
## Feature description

We don't currently have endpoint to get used and allowed space for user and workspace.

We should had them.

Api proposal  for workspace:

```
GET /api/v2/workspaces/{workspace id}/allowed_space

{
    "allowed_space": 0, 
    "label": "test", 
    "slug": "test", 
    "used_space": 600212650, 
    "workspace_id": 1
}
```

**Comment by inkhey** [comment]
@Skylsmoi can you check if "size" param of get workspace endpoint is used somewhere in tracim web ui ?

**Comment by inkhey** [comment]
Api proposal for user

GET /api/v2/users/{user_id}/allowed_space

{
    "allowed_space": 0, 
    "public_name": "toto", 
    "avatar_url": None, 
    "used_space": 600212650, 
}

**Comment by lebouquetin** [comment]
@inkhey here comes my suggestions:

```
GET /api/v2/users/{user_id}/disk_space

{
    "allowed_space": 0, 
    "used_space": 600212650, 
    "user_id": 1
    "user": {
        "avatar_url": None,
        "public_name": "XXX",
        "user_id": 1
    }
}

GET /api/v2/workspaces/{workspace id}/disk_space

{
    "allowed_space": 0, 
    "used_space": 600212650, 
    "workspace_id": 1
    "workspace": {
        "workspace_id": 1,
        "label": "Xxx"
        "slug": "xxx
    }
}
```

**Comment by inkhey** [comment]
@Skylsmoi 
Endpoints where size parameter is removed:
```
GET /workspaces
GET /workspaces/{workspace_id}
POST /workspaces
PUT /workspaces/{workspace_id}
```

**Comment by Skylsmoi** [comment]
> p.s : None for a URL is ok for @Skylsmoi ? Isn't it better to have an empty string?

I do prefer empty string.

**Comment by inkhey** [comment]
> > p.s : None for a URL is ok for @Skylsmoi ? Isn't it better to have an empty string?
> 
> I do prefer empty string
> Although, if you can confirm that None in python gets converted to null in json, I can live with it

i confirm : 
`    "avatar_url": null,`

**Comment by Skylsmoi** [comment]
> @Skylsmoi
> Endpoints where size parameter is removed:
> 
> ```
> GET /workspaces
> GET /workspaces/{workspace_id}
> POST /workspaces
> PUT /workspaces/{workspace_id}
> ```

frontend and apps don't use any size property from theses endpoints

**Comment by inkhey** [comment]
@PhilippeAccorsi @lebouquetin We should probably document something the removing of size parameter in thoses endpoints.

**Comment by PhilippeAccorsi** [comment]
I think its just necessary to document this change in changelog.

**Comment by Skylsmoi** [comment]
modification list:
- new endpoint `/api/v2/users/me/disk_space`
- new endpoint `/api/v2/users/:userId/disk_space`
- new endpoint `/api/v2/workspaces/:workspaceId/disk_space`
- modified endpoint `GET /api/v2/workspaces` doesn't return `size` property anymore
- modified endpoint `GET /api/v2/workspaces/:workspaceId` doesn't return `size` property anymore
- modified endpoint `POST /api/v2/workspaces` doesn't return `size` property anymore
- modified endpoint `PUT /api/v2/workspaces/:workspaceId` doesn't return `size` property anymore
- modified endpoint `GET /api/v2/users/:userId` now  returns `allowed_space`
- modified endpoint `GET /api/v2/users/me` now  returns `allowed_space`

@inkhey is this list exhaustive ?

**Comment by inkhey** [comment]
@Skylsmoi it's ok.

**Comment by PhilippeAccorsi** [comment]
Verified.
