### ISSUE TITLE
Use preview_generator 0.13

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2532]
## Feature description

Use new preview_generator version (0.13) in tracim.

preview_generator 0.13 changes: 
- add support for raw camera file.
- fix issue https://github.com/algoo/preview-generator/issues/160 about temporary file not deleted.
- better support for 3d file (:warning: not usable in tracim production headless environnement due to issue https://github.com/algoo/preview-generator/issues/163 )
- somes others minors/api fix.

**Comment by PhilippeAccorsi** [comment]
@PhilippeAccorsi add what is necessary in changelog about this version of preview generator.

**Comment by inkhey** [comment]
code part fixed by https://github.com/tracim/tracim/commit/efa76f291659b1870b4a87abfe4157fc9c607459 , wait for changelog update.

**Comment by PhilippeAccorsi** [comment]
Verified.
