### ISSUE TITLE
Rotated images have incorrect sizes in the gallery application

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#2537]
## Bug description & symptom

When rotating an image in the gallery, it does not occupy all the available space.

## Expected

After rotate an image on the gallery, it must be resized to take upall the available space.

## How to reproduce

1. Open gallery
2. Visualize image which can be rotated
3. Rotate it

## Screenshots

![rotate](https://user-images.githubusercontent.com/1104637/69955154-49766a00-14fd-11ea-802d-ca7067b69ed6.png)

## Impacted components

*Optional - list components which will be impacted.*

- *frontend*

**Comment by metzgegu** [comment]
The solution implemented in the PR is to compute the new size ratio of the img preview when the rotation has changed in order to fit the current container div size.

**Comment by gbonaspetti** [comment]
Verified on branch (wait merge to close).
