### ISSUE TITLE
buttons are all the time visible in fullscreen and Slideshow

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2541]
## Bug description & symptom

Button to rotate image, zoom, etc are visible all the time also when we are in fullscreen or in slideshow.

## Diagnostic

*Optional - explain what has been found and what is not yet clear. If unknown, write "unknown".*

## Expected

- [x] button's are visible if I place my mouse near corner for exemple. Normal process is to show this button at the begining but not after (just if I move mouse in button zone).

## How to reproduce

- Open image in full screen and start slideshow

## Impacted components

- *frontend*

## Extra information

**Comment by Skylsmoi** [comment]
I agree and I would add that the buttons should only be visible when moving the cursor and should fadeout when mouse is idle
Like in video player in fullscreen (youtube, netflix, vlc ...)

**Comment by PhilippeAccorsi** [comment]
Regression when you are in fullscreen, button is visible but we can't click on it.

Question: is it possible to activate white view on button when mouse is over (like its visible for cross or zoom)

**Comment by metzgegu** [comment]
Yes it is possible to activate white color on button when mouse is hover,
however `React-image-lightbox` don't provide any props to add tooltip on prev or next button

Also can you give more information about how to reproduce the regression bug in fullscreen mode ?

**Comment by PhilippeAccorsi** [comment]
I think the bug appear before we revert this commit https://github.com/tracim/tracim/commit/82c15583b9753e26b9e14363739a5dba87863a34

**Comment by metzgegu** [comment]
TODO : 

- [ ] Hide arrows buttons when auto play enabled
- [ ] Add hover style to react-lightbox custom buttons
- [ ] Add title to next and prev buttons in react-lightbox

**Comment by PhilippeAccorsi** [comment]
After discuss with @Skylsmoi and @metzgegu :
- Hide arrows buttons also when mouse not moving (like we have for gallery__action__button__lightbox ).

**Comment by PhilippeAccorsi** [comment]
> however `React-image-lightbox` don't provide any props to add tooltip on prev or next button
> 
It is the same problem for zoom button and cross to close fullscreen?

**Comment by metzgegu** [comment]
> > however `React-image-lightbox` don't provide any props to add tooltip on prev or next button
> 
> It is the same problem for zoom button and cross to close fullscreen?

Yes

**Comment by PhilippeAccorsi** [comment]
Tested on branch and verified (wait merge to close)

**Comment by PhilippeAccorsi** [comment]
Verified on develop.

**Comment by metzgegu** [comment]
Hello @PhilippeAccorsi, The lib `react-image-lightbox` now add a title to the prev and next buttons in the new version [5.1.3](https://www.npmjs.com/package/react-image-lightbox) since [this](https://github.com/frontend-collective/react-image-lightbox/issues/265) is merged and a new version has been published.
