### ISSUE TITLE
add limit to know its small preview (zone to scroll) and normal preview (to look image)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2551]
## Feature description

Add separation between small and normal preview (see screenshot)

## Impacted components

- *frontend*

## Extra information

![feature_color_separation](https://user-images.githubusercontent.com/25848257/69965285-391db980-1514-11ea-99a1-5b05cc4c9013.png)

**Comment by PhilippeAccorsi** [comment]
We need some modification here:
- separation between small and normal preview need to be visible on left and right (like separation visible in dashboard)
- vertical scroll on gallery is not user freindly and its not working with same process on different screen size (sometime no bottom margin visible, sometime a small margin, sometime bigger margin)

Regression:
- when you click on preview (biggest view is opened) some regression are visible:
  - Vertical and horizontal scroll appear
  - on left we can see some pixel of last preview
- sometime when you change the browser size and when you close fullscreen, tracim show a blanck page. error visible in console:
~~~
TypeError: "t.imagesPreviews[t.fileSelected] is undefined"
TypeError: t.imagesPreviews[t.fileSelected] is undefined
TypeError: "_(...) is null"
TypeError: document.getElementsByClassName(...)[0] is undefined
~~~

**Comment by metzgegu** [comment]
First regression was fixed with this commit : 229dc4e

**Comment by metzgegu** [comment]
TO DO :

- [ ] separation between small and normal preview need to be visible on left and right (same as dashboard separation)
- [ ] Remove useless margin at the bottom

**Comment by PhilippeAccorsi** [comment]
Margin exist when no scroll exist on gallery page. We need to find solution to remove this margin all the time and save this space to improve available space for preview of file.

@Skylsmoi we need your help to find solution.

**Comment by PhilippeAccorsi** [comment]
Tested on branch and verified (wait merge to close issue)

**Comment by PhilippeAccorsi** [comment]
Verified on develop.
