### ISSUE TITLE
Explicit origin user in invite message when possible.

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2565]
## Bug description & symptom

When we receive invitation in tracim, we get "Someone invited you to join tracim" message
Something like: "John invited you to join tracim" will be better;

This mean change for:
- email subject (currently `[{website_title}] Someone created an account for you`)
- email content (currently `{origin_user_name} invited you to join <i>{website_title}</i>.` )
- email FROM header (obtain "username (through tracim)" instead of "tracim notification")

As user invitation can be done in some very specific case without origin (command line, ldap, etc...), we should think about case where there is no "origin_user" and adapt subjet, content and from to these case.

**Comment by PhilippeAccorsi** [comment]
Verified.
