### ISSUE TITLE
When changing public name, autogenerated avatar in sidebar is done with unstripped string

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2569]
## Bug description & symptom

When user change his public name with a name beginning with "  "(space char), avatar in sidebar is made from this unstripped (no space at beginning or at ending) string so, il we put " aa" we get a, when logical behavior should be getting "aa" as string is stripped in backen so user name will be "aa" and not " aa".

![empty_avatar](https://user-images.githubusercontent.com/7851652/70327215-937d8980-1836-11ea-92e2-fcc438c89854.gif)
 
## Expected

Always create avatar with stripped (removing space at beginning and ending) string.

# Implementation

The fix trims trailing whitespaces.

**Comment by gbonaspetti** [comment]
> if we put " aa" we get "a", when logical behavior should be getting "aa"
[...]
Always create avatar with stripped (removing space at beginning and ending) string.

This is still happening with the spaces at the end of the name. If we put "aaa" or " aaa" the avatar is "aa", but when we put "aaa " or " aaa " the avatar is "a".

**Comment by metzgegu** [comment]
> > if we put " aa" we get "a", when logical behavior should be getting "aa"
> > [...]
> > Always create avatar with stripped (removing space at beginning and ending) string.
> 
> This is still happening with the spaces at the end of the name. If we put "aaa" or " aaa" the avatar is "aa", but when we put "aaa " or " aaa " the avatar is "a".

Yes the public name was trimmed only left side but it must be trimmed both side in order only one word in this case.

**Comment by gbonaspetti** [comment]
Verified on branch (wait merge to close).
