### ISSUE TITLE
new release_02.06.00

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2571]
## Create new release 2.6.0

- [x] frontend version updated
- [x] backend version updated
- [x] changelog updated

For changelog:
- preview of raw file available
- preview of 3D file (working with xvfb in container)

**Comment by inkhey** [comment]
@PhilippeAccorsi with https://github.com/tracim/tracim/pull/2619, you now need to update backend version in `setup.cfg`. You should not touch anymore to python code source.

**Comment by PhilippeAccorsi** [comment]
Need to add some information in changelog about deprecated/removed parameter about ldap
https://github.com/tracim/tracim/issues/2613

**Comment by PhilippeAccorsi** [comment]
Add information in changelog about new apache configuration for docker image, need manual modification to use browser cache policy.

**Comment by PhilippeAccorsi** [comment]
Deprecated parameter about ldap (need information in changelog)
- ldap_base_dn
- ldap_base_url

More [here](https://github.com/tracim/tracim/issues/2613)

**Comment by inkhey** [comment]
### app.enabled breaking change

agenda, share_content, upload_permission, collaborative_document_edition are now real applications and add/remove them from app.enabled list add/remove the associated feature. 

- `agenda` app is activated by default, so you must have app.enabled list according to your old caldav.enabled parameter, you should add or remove agenda app according to activate/desactivate agenda feature (or set START_CALDAV parameter in docker)

- `upload_permission` and  `share_content` are activated by default but they now MUST be in app.enabled list to work properly, before 2.6.0 theses apps do work without being activated properly.

- `collaborative_document_edition` is now a real app. disable by default. to activate it you should not anymore set collaborative_document_edition.activated, but add/remove collaborative_document_edition in app.enabled list (or set ENABLE_COLLABORATIVE_DOCUMENT_EDITION parameter in docker)

**Comment by PhilippeAccorsi** [comment]
- [x] change copyright from `Copyright - 2013 - 2019
` to `Copyright - 2013 - 2020`

**Comment by PhilippeAccorsi** [comment]
Verified.
