### ISSUE TITLE
Add unit tests to app gallery

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#2574]
## Feature description

The new gallery application need some unit tests

## Context

There is no unit tests for app_gallery

**Comment by Skylsmoi** [comment]
info for test:
Just check that the unit test for app gallery pass on travis

**Comment by PhilippeAccorsi** [comment]
Test is not started in travis.

**Comment by Skylsmoi** [comment]
Other issue, unit tests of app gallery fails locally with fetch related error.
The same error occurs when running on travis.

**Comment by PhilippeAccorsi** [comment]
Tested and verified.
