### ISSUE TITLE
add possibility to remove his own account from a shared space

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2584]
## Feature description

Add possibility to remove is own account from one sharedspace without asking another manager of this sharedspace.

## Context

Its not possible for one member to remove is own account from an existing sharedspace. Thats not possible also if you are manager of this sharedspace (in case of other member are manager of this shared space.

## Prerequisites

*Optional - if some other issues must be closed before the current, list them here.*

- *#xxx*
- *...*

## Impacted components

*If unsure, write "unknown"*

## Extra information

**Comment by Skylsmoi** [comment]
it is possible from user's settings.
