### ISSUE TITLE
No <html> tag in emails

### ISSUE THREAD

**Issue by frederic-peters** [tracim/tracim#2592]
## Bug description & symptom

SpamAssassin marks emails originating from tracim with HTML_MIME_NO_HTML_TAG, meaning its HTML part doesn't have a <html> tag.

Indeed, it started like this:

```
<!--FIXME` After discuss with Damien: dont add intelligent code in template -->
<style>
  ins { background-color: #c0ffc0; }
```

## Expected

A `<html>` tag.

## Extra information

Fwiw a few years back I looked around and settled on https://tedgoas.github.io/Cerberus/ as the base template for HTML emails (https://git.entrouvert.org/publik-base-theme.git/tree/templates/emails/body_base.html).

**Comment by PhilippeAccorsi** [comment]
Tested and verified.
