### ISSUE TITLE
Page title should change according to current route

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#2593]
## Feature description

In order to easily navigate through tracim contents, the title should change depending of the current route

## Context

Page title need to change when the route is changed

## Impacted components

Frontend

**Comment by metzgegu** [comment]
Currently the `title` is hardcoded in index.html (eg `<title>Tracim</title>`) but I think it should be a parameter in development.ini in order to set the default title with the instance name and change the title according to which app is currently rendered

**Comment by metzgegu** [comment]
### We need to define which pages will change the default title.
Obvious pages are contents app pages : 
- App file
- App html-document
- App thread
- App collabora online
Other interesting pages : 
- Workspace content list, dashboard, gallery, agenda
- Admin interfaces
- Account management

**Comment by Skylsmoi** [comment]
spec [here](https://algoo.tracim.fr/ui/workspaces/49/contents/file/11518)

**Comment by PhilippeAccorsi** [comment]
problem with 
- ui/guest-upload | Public upload => wording here is `Share folder` but page name is `Received files`
- ui/guest-upload/ => title is not translated dynamically
- when file is opened with collabora, title is not refreshed and if I refreshed page with F5 title just show website.title (value visible in development.ini).

**Comment by PhilippeAccorsi** [comment]
Verified on branch.

- ~~ui/guest-upload | Public upload => wording here is Share folder but page name is Received files~~
- ~~ui/guest-upload/ => title is not translated dynamically~~
- ~~when file is opened with collabora, title is not refreshed and if I refreshed page with F5 title just show website.title (value visible in development.ini).~~

**Comment by PhilippeAccorsi** [comment]
Verified on develop.
