### ISSUE TITLE
Feat: App header evolution (remove the double header)

### ISSUE THREAD

**Issue by celiamgtt** [tracim/tracim#2594]
## Feature description

To simplify the user experience, we worked on a new app header evolution to simplify it.
The idea was to remove the double header.

## Context

Currently, when the user open an app, 3 different headers are diplayed:
<img width="1280" alt="Capture d’écran 2019-12-23 à 10 02 25" src="https://user-images.githubusercontent.com/50453784/71347822-743b6780-256b-11ea-9b24-2d6671fd1fdd.png">

The following features will be added : 

- [x] The breadcrumbs will be rendered in the content 
- [x] All the buttons, except for the edit, reactions and favorite buttons, will be added in a drop down icon (fas fa-ellipsis-v)
- [x] The status drop down button will be rendered on the content with a different style (similar to profile header button)
- [x] The version will be rendered on the content (next to the validate button), it will also be added in the file content
- [x] The style of the new header will change and be more similar to the mockups below

Notes : 
The right part of the content (with the tabs) will take 50% of the available space.
There wont be a full screen feature in a first time.

## Mockups

App file:
![App-file-no-header-expand-bttn-breadcrumb-status](https://user-images.githubusercontent.com/50453784/71347949-c7151f00-256b-11ea-877d-982fb53bbaad.png)

Fullscreen app file:
![App-file-no-header-full-screen-closed-timeline](https://user-images.githubusercontent.com/50453784/71348112-18bda980-256c-11ea-8fa4-69eaf70a188d.png)

App html:
![App-html-no-header-expand-bttn-breadcrumb-status](https://user-images.githubusercontent.com/50453784/71347984-d5633b00-256b-11ea-8840-d3b7ea00ff8c.png)

App html in edition mode:
![App-html-no-header-edition](https://user-images.githubusercontent.com/50453784/71348003-dd22df80-256b-11ea-9ad5-fa3217eed2b5.png)

Fullscreen app html:
![App-html-no-header-full-screen-closed-timeline](https://user-images.githubusercontent.com/50453784/71348045-f62b9080-256b-11ea-833e-995defceebf1.png)

Fullscreen app html & opened sidebar:
![App-html-no-header-full-screen-open-timeline](https://user-images.githubusercontent.com/50453784/71348078-0b082400-256c-11ea-8878-3cfa82478da0.png)

## Interface example 
![Capture d’écran de 2021-06-23 11-12-04](https://user-images.githubusercontent.com/35422692/123071243-c9805f80-d414-11eb-86ed-4df7ca6877bf.png)

**Comment by lebouquetin** [comment]
estimated time: 5 days.

**Comment by charline-rageade** [comment]
Tested on a branch
