### ISSUE TITLE
Long strings aren't cropped in comments & text areas

### ISSUE THREAD

**Issue by celiamgtt** [tracim/tracim#2595]
## Bug description & symptom

Long strings aren't cropped in comments & text areas (Mac OS Catalina 10.15.1 & Chrome Version 79.0.3945.88).

## Context and version information

- Mac OS Catalina 10.15.1
    - Chrome Version 79.0.3945.88 (Build officiel) (64 bits)

## Screenshots

<img width="897" alt="Capture d’écran 2019-12-23 à 10 31 59" src="https://user-images.githubusercontent.com/50453784/71350061-b87d3680-2570-11ea-8f88-4542b23c8590.png">
<img width="896" alt="Capture d’écran 2019-12-23 à 10 32 35" src="https://user-images.githubusercontent.com/50453784/71350062-b87d3680-2570-11ea-8304-f6022dc76859.png">

**Comment by gbonaspetti** [comment]
Fixed at #2809 where a maximum width limit per line was added taking into account the scope where the string is.

**Comment by Skylsmoi** [comment]
Bellow is just a reminder for my research of 2020-04-03:
``` diff
/* Feuille de style intégrée #27 | /ui/workspaces/55/contents/html-document/8154 */

.comment__body {
  overflow: scroll;
}

/* Élément | /ui/workspaces/55/contents/html-document/8154 */

li.html-document__contentpage__messagelist__item:nth-child(11) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(3) {
  width: 410px;
}

```

**Comment by metzgegu** [comment]
Tested and verified on branch.
