### ISSUE TITLE
FileDropzone.jsx in frontend_lib needs some small refactor

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2603]
## Bug description & symptom

The code includes a fallthrough statement in the switch with a condition.
This is poorly designed and need to be fixed with proper condition and return cases

## Diagnostic

the `case false:` has neither break nor return

## Expected

each cases should have a break or a return

## Impacted components

frontend_lib

**Comment by Haskaris** [comment]
Is that still on?
Maybe fixed in #2409?

**Comment by Skylsmoi** [comment]
The commit to which metzgegu linked this issue seems to fix it because if you check the diff, it comes from a switch that handles "null" and "false" cases to a switch that handles FILE_PREVIEW_STATE cases.

So I think this issue can be closed

**Comment by Haskaris** [comment]
Closing this issue since it's solved.
