### ISSUE TITLE
app Collabora have a wrong boolean test on role to test if edition is available

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2607]
## Bug description & symptom

The app Collabora can open in view mode even if user is workspace manager

## Diagnostic

if this file https://github.com/tracim/tracim/blob/develop/frontend_app_collaborative_document_edition/src/container/CollaborativeEditionFrame.jsx the function `buildCompleteIframeUrl` does a wrong boolean test

the correct boolean test:
``` diff
--- const readyonly = !state.content.is_editable || !state.loggedUser.userRoleIdInWorkspace <= ROLE.contributor.id
+++ const readyonly = !state.content.is_editable || !(state.loggedUser.userRoleIdInWorkspace <= ROLE.contributor.id)
```

## Expected

App handle role properly

## How to reproduce

- login as admin
- create / open a collaborative document
- you are in view mode even if you are workspace manager

## Impacted components

app collabora

**Comment by Skylsmoi** [comment]
to test: confirm that collabora opens with in read/view according to the user's ROLE in workspace

**Comment by PhilippeAccorsi** [comment]
Verified on branch.
