### ISSUE TITLE
frontend may open app fullscreen with an incorrect role

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2608]
## Bug description & symptom

The frontend may open fullscreen app using their respective `renderAppFullscreen` function with an incorrect property `userRoleIdInWorkspace`.

## Diagnostic

When calculating the `userRoleIdInWorkspace` property in function renderAppFullscreen of appFactory.js, the redux state `currentWorkspace` may be not initialized and `memberList` property is a empty array.
The function `findUserRoleIdInWorkspace` then return the minimal role which is reader.

## Expected

The fullscreen apps are opened with the proper role id.
The issue doesn't exists for feature apps, the same process should be applied

## How to reproduce

To reproduce the error, you must open a fullscreen app on first page load.
If you click on a tracim button to open the fullscreen app, the issue doesn't exists, you must have an url that will open a fullscreen app a do a first load on it.

## Impacted components

frontend

**Comment by PhilippeAccorsi** [comment]
test this app:
- admin workspace
- admin user
- agenda (all)
- agenda workspace
- gallery
- collabora

**Comment by PhilippeAccorsi** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Need some verification on develop when all refactor is done and merge in develop.

**Comment by PhilippeAccorsi** [comment]
Verified on develop.
