### ISSUE TITLE
tracimcli command show not explicit message on error with command create user

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2610]
## Bug description & symptom

When I tried to create new user with tracimcli command, I can see this error `Something goes wrong during command`. If I want an explicit message I need to add  `-d` option (debug).

Command:  `tracimcli user create -l toto2@toto.toto -p toto2@toto.toto`

## Diagnostic

*Optional - explain what has been found and what is not yet clear. If unknown, write "unknown".*

## Expected

- [ ] Add explicit message how command goes wrong directly with debug mode

## How to reproduce

User need to be exist in tracim before try to create again this user

## Impacted components

- *backend*

**Comment by inkhey** [comment]
@PhilippeAccorsi this was already fixed by https://github.com/tracim/tracim/pull/2591
tested on `develop` :
```
 ❯ tracimcli user create -l toto2@toto.toto -p toto2@toto.toto
Error: User already exist (use `user update` command instead)
Something goes wrong during command

```

**Comment by PhilippeAccorsi** [comment]
Verified.
