### ISSUE TITLE
Collabora always open as ReadOnly

### ISSUE THREAD

**Issue by mael-turon** [tracim/tracim#2612]
## Bug description & symptom
We installed tracim in order for services to manage files and exchange document/agenda which we like using but there is a problem with collabora edition.
Whoever user I connect use, even admin@admin.admin, any file I edit using Collabora is opened with Readonly permission.

## Diagnostic
We use internal and ldap as connection, but the problem still exist even when i disable ldap.

#### On collabora logs I see: 

wsd-00030-00036 2020-01-08 14:03:09.262305 [ websrv_poll ] INF  Find or create DocBroker for docKey [/api/v2/collaborative-document-edition/wopi/files/15] for session [006] on url [http://tracim.my.url/api/v2/collaborative-document-edition/wopi/files/15?access_token=b0d0d88935a54bb3b8d9b4de3873503f&access_token_ttl=0&permission=readonly].| wsd/LOOLWSD.cpp:1707
wsd-00030-00036 2020-01-08 14:03:09.262126 [ websrv_poll ] DBG  Query param: permission, value: readonly| wsd/LOOLWSD.cpp:2826

#### On Tracim :
On Tracim even when the user is manager or contributor of the shared space, whenever I try to edit a file it opens as ReadOnly (I still can edit the file by drag and dropping but this seems to come from Collabora)

When I use Tracim Docker on this same collabora without LDAP because i can't manage to make it work with ldap, Collabora works fine.

## Expected

Be able to edit files using CODE

## Context and version information

- Desktop environment (if applicable)
    - *OS: Windows 10*
    - *Browser Firefox/Chrome*
    - *Version latests*
- Server environment 
  - *OS: Debian Buster(10)*
  -  Version : 2.5.1

## Screenshots
I just created this file and this is the page i'm sent to
![image](https://user-images.githubusercontent.com/59658301/71994313-cd2c2080-3238-11ea-9b77-350ff3c958ab.png)

## Impacted components

unknown

## Extra information

Collabora CODE runs on the latest docker image 
I understand might come from my configuration but I can't manage to understand why, so if you could help that would be great
I'm attaching my config file as it might help :  [development.txt](https://github.com/tracim/tracim/files/4036173/development.txt)

Just tell me if you need any more information
Thanks

**Comment by PhilippeAccorsi** [comment]
Hi, which version do you have installed?

**Comment by PhilippeAccorsi** [comment]
Sorry but you says you use docker, I think its a 2.5.1.
But are you sure you not use version of tracim on develop branch on your server? Because we have some problem on develop branch with role and profile and we work on it.

**Comment by PhilippeAccorsi** [comment]
Can you try also with Collabora CODE version visible here: https://github.com/tracim/tracim/blob/develop/backend/doc/setting.md#collaborative-edition-online-tracim-v24

(We have not tested Collabora CODE since version 4.0.5.2)

**Comment by mael-turon** [comment]
Sorry, I might not have been clear 
Collabora is running on a docker so it's version 4.2.0.2

Tracim isn't working in a docker, it was installed using git on a debian server so it's 2.5.1

But still i tried it with your tracim docker and worked fine with collabora but can't manage to make it work with ldap . Going through the parameters usable for docker I see 

TRACIM_LDAP_BASE_URL | ldap_base_url | LDAP_BASE_URL
-- | -- | --
But ldap_base_url doesn't exist in the conf file and ldap_base_dn (not ldap_user_base_dn) is missing in docker parameters so maybedocker it's just a typo ?

I'll try with the version of collabora you sent me and tell how it goes.

**Comment by lebouquetin** [comment]
@buxx @inkhey could you give a hand on this issue?

**Comment by mael-turon** [comment]
I still have the same issue with version 4.0.5.2 
If you need anything else just tell me

**Comment by PhilippeAccorsi** [comment]
> Tracim isn't working in a docker, it was installed using git on a debian server (and use this command to do so :
> 
> ```
> git clone https://github.com/tracim/tracim.git
> cd tracim/
> ```

Hi, When you use this command your local version is in develop branch (default branch on repo), not in stable version. You need to use command `git checkout release_02.05.01` to use the stable version (and start again script to install and build backend and frontend). In frontend you can see version 2.5.1 but in reality its a version 2.5.1-dev (we need to improve naming when we are in develop branch).

**Comment by PhilippeAccorsi** [comment]
For LDAP:

|<env_var_name>|<config_file_name>|
|----------------------|-------------------------|
|TRACIM_LDAP_USER_BASE_DN|ldap_user_base_dn|

Deprecated paramter (missing information in documentation)

|<env_var_name>|<config_file_name>|
|----------------------|-------------------------|
|TRACIM_LDAP_BASE_URL|ldap_base_url|

This parameter exist but not used by code for the moment (its from tracim_v1):

|<env_var_name>|<config_file_name>|
|----------------------|-------------------------|
|TRACIM_LDAP_BASE_DN|ldap_base_dn|

**Comment by mael-turon** [comment]
Oh sorry didn't see that
I tried the stable release but i still get the same error 

I think i'm using the good one, don't know how to be sure but :

```
root@tracim:/etc/tracim# git show
commit c4365d9e657eb77f88d78009fdd04957f6a480f9 (HEAD, tag: release_02.05.01, origin/master)
Author: PhilippeAccorsi <philippe.accorsi@algoo.fr>
Date:   Fri Dec 6 14:28:16 2019 +0100

    New stable version of tracim: release_02.05.01
    * new release_02.05.01
```

I still get this on collabora logs : wsd-00029-00039 2020-01-09 09:32:18.847415 [ websrv_poll ] INF  URL [http://tracim.addeobx.bsq/api/v2/collaborative-document-edition/wopi/files/1?access_token=f6a3da2eab8a4dcc8f8adc05ac33df8f&access_token_ttl=0&permission=readonly].| wsd/LOOLWSD.cpp:2615

Even when i'm the author of the document, even using Admin@admin.admin

**Comment by mael-turon** [comment]
Okay, don't know what exactly went wrong i reinstalled it(even reinstalled debian) using the same config file and everything works fine
