### ISSUE TITLE
remove deprecated LDAP parameters

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2613]
## Bug description & symptom

bug discovered with https://github.com/tracim/tracim/issues/2612
Some ldap parameters are now deprecated because there not used to connect to LDAP.
These parameters are legacy config from tracim v1. Connection mecanism has changed making those parameters not useful anymore.

`LDAP_URL` is the correct url parameter to connect to ldap.
DN config needed are user and bind one, we do not need anymore base dn : `LDAP_BIND_DN` and 
`TRACIM_LDAP_USER_BASE_DN`.

useful ldap parameters:

|<env_var_name>|<config_file_name>|<config_name>|
|--------------|------------------|-------------|
|TRACIM_LDAP_URL               |ldap_url                      |LDAP_URL                      |
|TRACIM_LDAP_BIND_DN           |ldap_bind_dn                  |LDAP_BIND_DN                  |
|TRACIM_LDAP_BIND_PASS         |ldap_bind_pass                |LDAP_BIND_PASS                |
|TRACIM_LDAP_TLS               |ldap_tls                      |LDAP_TLS                      |
|TRACIM_LDAP_USER_BASE_DN      |ldap_user_base_dn             |LDAP_USER_BASE_DN             |
|TRACIM_LDAP_LOGIN_ATTRIBUTE   |ldap_login_attribute          |LDAP_LOGIN_ATTRIBUTE          |
|TRACIM_LDAP_NAME_ATTRIBUTE    |ldap_name_attribute           |LDAP_NAME_ATTRIBUTE           |

Deprecated ldap parameters:

|<env_var_name>|<config_file_name>|<config_name>|
|--------------|------------------|-------------|
|TRACIM_LDAP_BASE_URL          |ldap_base_url                 |LDAP_BASE_URL                 |
|TRACIM_LDAP_BASE_DN          |ldap_base_dn                   |LDAP_BASE_DN                 |

## Expected

Remove these deprecated parameters from tracim config sample and tracim code.

**Comment by lebouquetin** [comment]
> Some ldap parameters are now deprecated because there not really used in source code to connect to LDAP.

@inkhey you write "not really". Do you mean "they are  used in some specific cases" or "they are ignored by the source code". You should write the same thing without the really word which make things unclear

**Comment by inkhey** [comment]
> > Some ldap parameters are now deprecated because there not really used in source code to connect to LDAP.
> 
> @inkhey you write "not really". Do you mean "they are used in some specific cases" or "they are ignored by the source code". You should write the same thing without the really word which make things unclear

i corrected the sentence to make thing more clear. `LDAP_BASE_URL` parameters exist in code (so it is "used" somehow) but does nothing, so we can drop it without any consequences.

**Comment by PhilippeAccorsi** [comment]
Verified.
