### ISSUE TITLE
folder's contents might appear duplicated

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2615]
## Bug description & symptom

It is possible for a folder to display it's content multiple times

## Diagnostic

It happens if you quickly click on the folder multiple times, it will send multiple get requests. If the subsequent requests are sent before the first one has answered, the contents will be duplicated

## Expected

The content of a folder is never displayed as duplicated

## How to reproduce

- Have a folder with some content (3 is fine)
- Load the url of the parent workspace or folder so that the folder's content is not loaded
- Using the dev tools, add a big throttling to your connection
- Spam click the folder
=> once the endpoints answers the folder's content is duplicated
- (don't forget to remove the throttling after your test)

## Impacted components

frontend

## Extra information

Possible solutions:
1) parse folder content for any duplicated content to remove [quick fix]
2) Avoid having multiple get request sent to the api before the first one has answered [long fix]

**Comment by lebouquetin** [comment]
@Skylsmoi my point of view is this is a bad design of the state management.

The folder should have a state, which is something like closed/opened/opening/closing and sends requests according to this state and/or process data according to the state.

If two GET requests are executed, then the second shoud (must) overwrite the first one; I do not see any reason for "appending" new list of content.

So I think the solutions are:

1. parse folder content for any duplicated content to remove [quick fix]
2. Avoid having multiple get request sent to the api before the first one has answered [long fix]
3. if multiple GET requests are sent, overwrite the folder content [quick fix?]

And the way to fix the issue should be both implement 3 and 2, in this ordern (implement 3 first, then #2) . Let's talk about this tomorrow. 

By the way I think it should be integrated in next release.

**Comment by Skylsmoi** [comment]
@lebouquetin your `1.` and `3.` solution has been implemented during the fix of this issue https://github.com/tracim/tracim/issues/3255 and will be part of the 3.0 release

I suggest we keep that issue open to to `2.` and update its title

**Comment by Skylsmoi** [comment]
reopening the issue because it has been wrongly closed by message "fix #2615" in commit message

**Comment by PhilippeAccorsi** [comment]
It is done or not ? I move this issue from Done to To do, to know if it is solved or not.

**Comment by Skylsmoi** [comment]
mmh judging by the issue history, when the automatic closes appeared, the issue was in "Need test on develop".
The close put it in "Done".
I reopened it by I didn't moved it in the right column.
I'd say to put it back in "Need test on develop"

**Comment by PhilippeAccorsi** [comment]
ok.

**Comment by grignards** [comment]
Tested on preprod
