### ISSUE TITLE
add .editorconfig file at root of tracim

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2631]
## Feature description

Add an .editorconfig file at root of tracim with current develop rules for both python and javascript:
https://editorconfig.org/

It's a good practice, allowing different developper to have same rules apply when editing file.

**Comment by inkhey** [comment]
@Skylsmoi as explained here:  https://github.com/tracim/tracim/pull/2633#issuecomment-575621398 , you should check for javascript rules.

**Comment by Skylsmoi** [comment]
there are already .editorconfig files in each frontend folders:
```
./frontend_app_collaborative_document_edition/.editorconfig
./functionnal_tests/.editorconfig
./frontend_app_workspace/.editorconfig
./frontend_app_admin_workspace_user/.editorconfig
./frontend_app_share_folder_advanced/.editorconfig
./frontend_app_gallery/.editorconfig
./frontend_app_agenda/.editorconfig
./frontend/.editorconfig
./frontend_app_thread/.editorconfig
./frontend_app_html-document/.editorconfig
./frontend_lib/.editorconfig
./frontend_app_workspace_advanced/.editorconfig
./frontend_app_folder_advanced/.editorconfig
```

**Comment by Skylsmoi** [comment]
use js config from these files. They should all be the same.

If you refactor this with only one file at root level of repository, don't forger to remove all these files.

**Comment by gbonaspetti** [comment]
Verified on branch (wait merge to close).
