### ISSUE TITLE
Configure browser cache policy

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2637]
## Feature description

Browser cache policy must be configured by Tracim for the purpose of:

* Optimize loading time of Tracim
* Keep control on script browser download when it is required (when upgrade)

## Context

Currently, browser receive no particular information about how cache downloaded files. 

# Implementation proposition

Following policy must be indicated to the browser (with [Cache-Control header](https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Cache-Control)):

* `index.html` must always be downloaded by browser
* JavaScript scripts and CSS files must be cached by browser (how long ?)

This way, the browser caches all the files that never change but always download `index.html`. Since #2010 JavaScript and CSS files name change when Tracim is upgraded: Browser will download them once if Tracim upgrade.

## Prerequisites

- #2010 

## Impacted components

If [Cache-Control header](https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Cache-Control) managed in backend: backend. Else Apache.

Suggestion: manage it in backend. apache proxy is not always used. But be sure than Apache keep this headers.

**Comment by inkhey** [comment]
@lebouquetin @buxx Which duration of cache seems better by default for assets and app javascript ?

**Comment by PhilippeAccorsi** [comment]
After some research and reflexion, we have decided to use apache configuration to make browser cache policy.

We need to add :
- mod `expires` in entrypoint.sh for apache
- add this config in Directory for assets and app in apache2.conf.sample:
~~~
RequestHeader edit "If-None-Match" '^"((.*)-(gzip|br))"$' '"$1", "$2"'
        <IfModule mod_expires.c>
            ExpiresActive On
            ExpiresDefault "access plus 1 months"
        </IfModule>
~~~
More information about why we used `RequestHeader edit` visible here https://bz.apache.org/bugzilla/show_bug.cgi?id=45023#c26

With this modification when cache working, the frontend just download 6Ko of data (3Mo without cache policy).

**Comment by PhilippeAccorsi** [comment]
Tested on branch and verified. (wait merge to close)
