### ISSUE TITLE
Better UI With using tracim with app that do not allow to upload file

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2645]
## Bug description & symptom

When we enable only app which does not add items in "create" menu, like:
`app.enabled = gallery`

we get empty menu:
![Peek 28-01-2020 14-37](https://user-images.githubusercontent.com/7851652/73268899-10e0cd00-41dc-11ea-88c8-829c8d6c4fa1.gif)

## Expected

Remove or mark "create" buttons in gray.

**Comment by Skylsmoi** [comment]
fixed
