### ISSUE TITLE
Refactor elasticsearch indexing organization using multi-fields

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2660]
## Feature description

We should multi-field to support different indexing of same data instead of using multiple field : https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-fields.html

This is clearer and allow us to support some feature like #2658 .

**Comment by PhilippeAccorsi** [comment]
Tested and verified on branch. Wait merge to close issue.
Its important to drop and re-create index with this fix.

**Comment by PhilippeAccorsi** [comment]
For existing installation:

### When elasticsearch and tracim running (without docker), you need to:
- open path where tracim is installed
- cd backend
- activate env: `source env/bin/activate`
- tracimcli search index-drop -d && tracimcli search index-create -d

When its done, you can continu to use tracim (not necessary to reload tracim)

### When elasticsearch and tracim running (with docker), you need to:
- connect on your docker container with:
  docker exec -it {container_id} /bin/bash
- When you are in your container
  - cd tracim/backend/
  - tracimcli search index-drop -c /etc/tracim/development.ini -d && tracimcli search index-create -c /etc/tracim/development.ini -d

When all its done, you can exit from your container and continue to use tracim (not necessary to reload tracim)
