### ISSUE TITLE
Infinite loader for file in gallery

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2661]
## Bug description & symptom

Content with supported mimetype/file_extension for preview but failed to generate preview show infinite loader with file name : 

![infinite_loader](https://user-images.githubusercontent.com/7851652/73544529-a75dfa00-4439-11ea-8464-d09e1c71b9c7.gif)

This happened in specific case for example:
- .png file with no data (0 bytes)
- very large image that imagemagick builder refuse to process.

## Expected

unclear

**Comment by metzgegu** [comment]
The app file already handle this file with a function named `isJpegPreviewDisplayable` which create a `img` and listen to `onError` attribute to know if it can be displayable,
We could refactor this function in frontend_lib and use it in app gallery

**Comment by gbonaspetti** [comment]
Verified on branch (wait merge to close).
