### ISSUE TITLE
Refactor unit tests in frontend and frontend_lib

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#2663]
## Bug description & symptom

- #2601 Introduce a proper way to mock api calls, other tests need to use the same way,
- Unit tests which test callback use `sinon.stub()`, or most of the case `sinon.spy()` is enough because we just test if the callback is called and we don't test with custom return statement. 
more information can be found [here](https://jaketrent.com/post/sinon-spies-vs-stubs/)

## Expected

Cleaner unit tests

## Impacted components

- *frontend* unit tests

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi @metzgegu I can't see documentation about what is necessary to start unit test, if documentation not exist, please add documentation in this issue.

**Comment by PhilippeAccorsi** [comment]
> @Skylsmoi @metzgegu I can't see documentation about what is necessary to start unit test, if documentation not exist, please add documentation in this issue.

@Skylsmoi @metzgegu :up:  Documentation is not an option

**Comment by PhilippeAccorsi** [comment]
Verified.
