### ISSUE TITLE
Wrong sharedspace is opened when create new shared space [regression]

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2665]
## Bug description & symptom
If all my existing shared space is closed (named 1,2,3 and 4), when I create a new sharedspace `5` I can see in the sidebar the `4` opened. When I create again a new one `6`, same result.

## Diagnostic

*Optional - explain what has been found and what is not yet clear. If unknown, write "unknown".*

## Expected

- [x] open shared space now
- [x] need non regression test

## Context and version information

*Optional - describe the environment which reveals the bug:*

- Desktop environment (if applicable)
    - *OS: [e.g. iOS]*
    - *Browser [e.g. chrome, safari]*
    - *Version [e.g. 22]*
- Smartphone/Tablet (if applicable)
    - *Device: [e.g. iPhone6]*
    - *OS: [e.g. iOS8.1]*
    - *Browser [e.g. stock browser, safari]*
    - *Version [e.g. 22]*

*...*

## Prerequisites

*Optional - list issues that must be closed before the current one.*

- *#xxx*
- *...*

## How to reproduce

*Optional - detail steps to reproduce the behavior:*

1. *Go to '...'*
1. *Click on '....'*
1. *Scroll down to '....'*
1. *See error*

## Screenshots

*Optional - add screenshots to help explain your problem.*

*Please consider sharing a [animated GIF screencast generated with peek](https://github.com/phw/peek)* 

## Impacted components

*Optional - list components which will be impacted.*

*For example:*

- *backend*
- *frontend*
- *htmldoc / file / thread app*
- *webdav*
- *...*

*If unsure, write "unknown"*

## Extra information

*Optional - add any extra information which will be usefull for understanding and developing the feature*

**Comment by PhilippeAccorsi** [comment]
This bug exist in 2.5.x also.

**Comment by metzgegu** [comment]
Regression bug was created with a merged PR of this issue #2039

**Comment by PhilippeAccorsi** [comment]
Tested and verified (wait merge on develop)
