### ISSUE TITLE
Wrong url after uploading a new content of type File

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2669]
## Bug description & symptom

After the upload of new content type File, the app File open displaying the new file but the url is still the url for workspace content list.

## Diagnostic

This is a regression. It probably has been added with the new multiple import feature.

## Expected

The url stays sync with the Tracim's state. If the url is the content list one, the app File should not be displayed. Therefore, if the app File is displayed, the url should be the content one.

## Context and version information

Bug visible in version 2.6.0 and 2.6.0_rc1.
Bug doesn't exists on version 2.5.0.

## How to reproduce

Create a new content of type File. Choose one file and click "validate".
Once the upload is completed, the app File opens but the url stays the content list one.

## Impacted components

app File

## Extra information

From my quick tests, it seems that, due to the app File opening and the logs in the console that show `GLOBAL_dispatchEvent openContentUrl 
Object { workspaceId: 1, contentType: "file", contentId: 1 }`, the url is properly changed after the upload because it's supposed to be that rerouting that triggers the app File opening.
Something might change url again right after.

**Comment by PhilippeAccorsi** [comment]
tested and verified.
