### ISSUE TITLE
Multi uploaded files aren't tag as read

### ISSUE THREAD

**Issue by celiamgtt** [tracim/tracim#2676]
## Bug description & symptom

When a user upload multiple files, they aren't tagged as read.

## Expected

Files uploaded by a user have to be tagged as read for him/her.

## Screenshots

![import_fichiers_multiple_read_status](https://user-images.githubusercontent.com/50453784/74141148-ac1f6c80-4bf6-11ea-9226-1005d5e577c9.gif)

**Comment by PhilippeAccorsi** [comment]
Verified.
