### ISSUE TITLE
Regression : Translation problem with ROLE on the dashboard 

### ISSUE THREAD

**Issue by LucBarry** [tracim/tracim#2680]
## Bug description & symptom

On the dashboard all roles members are translated in English even if the languages of Tracim is French. The description of roles is also in English when the language is French.
In the user admin page there are roles in English or French when the language is French

This regression is maybe link with this two tickets : 
https://github.com/tracim/tracim/issues/1396
https://github.com/tracim/tracim/issues/1656

## Expected

- [x] Role are translated in French
- [ ] Test case exist for this regression

**Comment by metzgegu** [comment]
Translation key for social role in frontend_lib was not created because the `npm run build-translation` was not run after the the refactor of Role

**Comment by PhilippeAccorsi** [comment]
Tested and verified.
