### ISSUE TITLE
breadcrumb no work correctly: not show list of contents when app is opened and I click on All contents and also bug with filename not visible

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2681]
## Bug description & symptom

- If I click on All contents in breadcrumb (after opening app), I can see url change but nothing append, app stay open.
- If I open a content, the breadcrumb not show the name of the file (name is visible but disappear) in case of I open this file from search. If I open this file from list of contents, the breadcrumb show filename correctly.

## Diagnostic

*Optional - explain what has been found and what is not yet clear. If unknown, write "unknown".*

## Expected

- [x] breadcrumb work correctly in all case

## Impacted components

- *frontend*

## Extra information

Some other case is not clear with breadcrumb:
- in admin sharedspace/user, the breadcrumb show naming `Administration` with same color like we have for clickable name => need to use black color for exemple to explain this name is not clickable
- When I go to user profile from admin user, I can't come back in admin user, so breadcrumb need to show where I come from like this `Home > Administration > Users > Public_name` and If I click on Users, I come back to admin user.

**Comment by metzgegu** [comment]
In order to resolve issues with the url and the breadcrumbs, We need to hide the current opened app if the url has changed to `workspace/:id/contents` on every update of `WorkspaceContent` and rebuild the breadcrumbs.
This will fix an other issue when a sidebar content entry is clicked and the app opened is still open while the url has changed.

**Comment by metzgegu** [comment]
Each content app append the breadcrumbs with his current file so tracim app need to check if the file currently exist in breadcrumbs and the app is opened in order to add it when building the breadcrumbs

**Comment by metzgegu** [comment]
Also, I removed `async` to `customEventReducer` functions which it isn't necessary

**Comment by gbonaspetti** [comment]
The second case still does not work if the open content is a folder (folder edit app), even if the content is opened from the list of contents.

> If I open a content, the breadcrumb not show the name of the file (name is visible but disappear) in case of I open this file from search. If I open this file from list of contents, the breadcrumb show filename correctly.

**Comment by gbonaspetti** [comment]
To fix the problem found during the tests, I updated the folder advanced app so that it has the same breadcrumbs mechanism as the other apps.

**Comment by metzgegu** [comment]
Verified on branch (wait merge to close).
