### ISSUE TITLE
Regression : Content manager can't use the "share" feature, can't move content to another sharedspace

### ISSUE THREAD

**Issue by LucBarry** [tracim/tracim#2683]
## Bug description & symptom

The content manager don't have access to the button "share" in any file when a file in open. 

## Expected

- [x] Content manager can share any file 
- [x] Content manager can move content from one sharedspace to another one
- [x] Test case exist for this regression => issue created here #2688

**Comment by PhilippeAccorsi** [comment]
Need hight verification about feature available for content manager to make sure everything is working correctly.

Make also this verification of others kind of role to make sure no others regression exist.
Information about rights available here https://github.com/tracim/tracim/blob/develop/backend/doc/roles.md

**Comment by PhilippeAccorsi** [comment]
@metzgegu I think something is wrong with contributor role. Contributor can't edit folder but edit function is visible. If I click on edit nothing append.

![Screenshot_2020-02-19 Home · test-bureau · Tracim](https://user-images.githubusercontent.com/25848257/74847780-f8735680-5332-11ea-8c3d-eefd2a165d13.png)

**Comment by PhilippeAccorsi** [comment]
@metzgegu I think something is wrong with contributor role. Contributor can't edit folder but edit function is visible. If I click on edit nothing append.

![Screenshot_2020-02-19 Home · test-bureau · Tracim](https://user-images.githubusercontent.com/25848257/74847780-f8735680-5332-11ea-8c3d-eefd2a165d13.png)

**Comment by metzgegu** [comment]
Yes this is wrong, but `BtnExtendedAction.jsx` is used for contentItems and folders but file and folder don't have the same permissions right for the edit buttons.
So we need to refactor `BtnExtendedAction.jsx` in order to make it more independent.

**Comment by PhilippeAccorsi** [comment]
Tested and verified.
