### ISSUE TITLE
Add tests about roles permissions and roles tranlations 

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#2688]
## Bug description & symptom

We need to write test to cover theses regressions bugs : 
- [x] #2683 Cypress test + unit test
- [x] #2680

**Comment by metzgegu** [comment]
To tests translations my strategy is to run the command `npm run build-translation` in each tracim app and check if '__NOT_TRANSLATED__' is present in translations files. Tests will be run in Travis CI

**Comment by PhilippeAccorsi** [comment]
No test needed. Travis test working with this fix.
