### ISSUE TITLE
Make the frontend tests concurrent in TravisCI

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#2692]
## Feature description

In order to reduce the time of tests execution in Travis we should make the frontend tests concurrent in Travis CI, like backend already does

We could shorten the tests execution time by 10 minutes at least

### Result:

![image](https://user-images.githubusercontent.com/31687635/74754017-445dc700-5271-11ea-9475-ad79b01570c1.png)

**Comment by PhilippeAccorsi** [comment]
Verified. Wait merge to close.
