### ISSUE TITLE
Creating a workspace do not scroll to show the new workspace in sidebar

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#2693]
## Bug description & symptom

When a new workspace is created, the workspace is opened in the sidebar but it doesn't scroll to this new workspace, it is a problem when there is a lot of different workspaces

## Diagnostic

- Sidebar item need to have html `id` in order to scroll to it

## Expected

- [x] scroll directly to created workspace in the sidebar when you creating it

## How to reproduce

- Create a workspace in a instance which have already a lot of workspaces

**Comment by metzgegu** [comment]
Implemented solution is to add a id to each workspace `li` in sidebar, in order to scroll into the workspace which is open when the the workspaceList is loaded.

**Comment by gbonaspetti** [comment]
Verified on branch (wait merge to close).
