### ISSUE TITLE
Add ctrl+click feature to open a folder in new tab

### ISSUE THREAD

**Issue by celiamgtt** [tracim/tracim#2701]
## Feature description

Add the possibility to open a folder in a new tab with "ctrl+clic".

## Context

Right now the feature doesn't exist.

**Comment by metzgegu** [comment]
The solution is to use `<Link>` instead of `<div>` in order to have a route which the browser can follow, but the folder have `extendedActions` which one of these is a `Link` and it isn't possible to have nested `Link` so we need to find a way to work around this problem.

**Comment by metzgegu** [comment]
The solution implemented has changed. To avoid nested link I finally use the onClick of Folder to handle `ctrl + clikc` behavior eg. it open the new tab if it is a `ctrl + click` directly in JS with `windows.open`, so previous behaviors isn't changed.

**Comment by gbonaspetti** [comment]
Verified on branch (wait merge to close).
