### ISSUE TITLE
some responsive bug on smartphone and on IOS progressive web app

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2703]
## Bug description & symptom

When we use tracim directly on smartphone web browser, the header is not fix, so in some case we can see bugs when header is moving.

In progressive web app, header is fix so no bug appear. Its more user freindly in progressive web app.

## Diagnostic

*Optional - explain what has been found and what is not yet clear. If unknown, write "unknown".*

## Expected

- [ ] Tracim working correctly in smartphone web browser like we see in progressive web app

## Context and version information

- Smartphone/Tablet (if applicable)
    - *Device: OnePlus 7T*
    - *OS: android 10*
    - *Browser chrome*
    - *Version 80.0*
- Smartphone/Tablet (if applicable)
    - *Device: OnePlus 7T*
    - *OS: android 10*
    - *Browser firefox*
    - *Version 68.5.0*
- Smartphone/Tablet (if applicable)
    - *Device: Iphone*
    - *OS: IOS 13.3.1*
    - *Browser safari*
    - *Version ??*

## How to reproduce

- Open Tracim on your web browser
- Go down of the page and you can seen the header disappear.
  - On Safari if you click on header, you just need to move page to see header moving
  - On Chrome, when you refresh page, the header disappear
    - On firefox, sometime its working and sometime not.

In progressive web app => you can't recreate this kind of bug on Firefox and Chrome but this bug exist on Safari.

## Screenshots
**On chrome:**

![header_bug_chrome-360](https://user-images.githubusercontent.com/25848257/75347988-41328e80-58a2-11ea-9196-e44cb513a6cd.jpg)

**On Safari:**

![header_bug_safari-360](https://user-images.githubusercontent.com/25848257/75348091-763ee100-58a2-11ea-8869-a6b719e3fe28.jpg)

## Impacted components

- *frontend*

**Comment by gbonaspetti** [comment]
Doubled with #5117
