### ISSUE TITLE
refactor appFactory.js api

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2713]
## Bug description & symptom

appFactory.js need improvement

## Diagnostic

"unknown"

## Expected

- [ ] Refactor done

## Impacted components

- *frontend*

## Extra information

**Comment by raphj** [comment]
Hello @PhilippeAccorsi, do you remember what improvement / refactor you had in mind with this issue?

**Comment by PhilippeAccorsi** [comment]
I don't know. I have created this issue on demand.

**Comment by raphj** [comment]
Ok. If you or someone else remembers, let me know. appFactory does indeed probably need some refactoring. In the meantime, related issues:

- https://github.com/tracim/tracim/issues/4897
- https://github.com/tracim/tracim/issues/4397
- https://github.com/tracim/tracim/issues/3925

**Comment by Skylsmoi** [comment]
no information, closing
