### ISSUE TITLE
Drop PreviewsController

### ISSUE THREAD

**Issue by ghost** [tracim/tracim#272]
Unused, removal planned.

**Comment by algooapy** [comment]
The `PreviewsController` is _almost_ unused:
it provides the `/previews/` url part of pages preview.

I tried to nest preview `PagesController` pages controller in the `UserWorkspaceFolderFileRestController` file controller, but didn't achieve to make it work.
see: aa9a7e3

Futhermore, modifications will maybe be required on:
- `/assets/js/previewGenerator.vendor.bundle.js` and / or
- `/assets/js/previewGenerator.app.entry.js`.
