### ISSUE TITLE
Feature: Add a button "add member" before list of member of workspace near "Member list" text

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2724]
## Feature description

Add a "add member button" at top right before list of member of workspace.

## Impacted components

- *frontend*

## Extra information
Idea from gbonaspetti

An idea is to put just the + symbol next to the title. Something like that: 

![AddMemberBtn](https://user-images.githubusercontent.com/35422692/58014153-754d7780-7af8-11e9-885b-fe2148e8cb80.png)

**Comment by PhilippeAccorsi** [comment]
Some return from this issue #1513 before changing description of issue.

~~~
Skylsmoi commented on 13 May 2019
I agree that a button should be added but at top right of the list might not be the best idea. I'm adding "unclear" tag
--
~~~
 
~~~
lebouquetin commented on 20 May 2019 
`I agree that a button should be added but at top right of the list might not be the best idea.`

Could you give some arguments? The reasons for suggesting that button is right aligned are:  keep user interface homogeneous do not move action button when you change language (it's a common  anti-feature to have actionner zones not static on a given rendering  context)
--
~~~

**Comment by Skylsmoi** [comment]
Fixed
