### ISSUE TITLE
Feature: add portugues translation

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2743]
## Feature description

Add Portugues translation available in tracim.

## Context

At present tracim is translate in English and French.

## Impacted components

*"unknown"*

## Extra information

**Comment by PhilippeAccorsi** [comment]
@gbonaspetti Hello :)
Can you make a quick check on this all pull requests to verify if for you translation is correct?

Best regards.

**Comment by gbonaspetti** [comment]
Besides the translations done by @mlopes21, I updated the configuration and build files to make the Portuguese translation possible and I did the backend translation of the emails. While doing the local testing I found some missing translations (words that were the same in French and English, for example), so I added the translation to the code.

**Comment by metzgegu** [comment]
Verified on branch (wait merge to close).
