### ISSUE TITLE
Installing frontend dependencies is slow and requires being root

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#2747]
See #2916 for a comprehensive explanation about the migration to Yarn, that fixes this issue.

## Bug description & symptom

The script to install frontend dependencies runs npm install several times, leading  to duplicate downloads of dependencies.

The npm link also requires being root to build Tracim.

## Diagnostic

Run: ./install_frontend_dependencies.sh

## Expected

Each dependency is not downloaded more than once.
Root is not required to install the dependencies is all the system dependencies (Debian packages) are already there.

## Context and version information

tracim develop branch (984d624f53ea25ffa5aa16ead91b297d39165268) and up-to-date Debian Buster

## Prerequisites

This issue does not depend on any other issue 

## Impacted components

The build system

## Extra information

The following pull request fixes this issue: #2873

**Comment by PhilippeAccorsi** [comment]
Can you use bug or feature template of issue for this request? 
Here we not seen what is expected, and also what is not good in script (peace of code is better to understand what is not optimized).

Some of description visible in merge request can be added here, I think.

**Comment by PhilippeAccorsi** [comment]
There are some impacts in Tracim docker image?

**Comment by raphj** [comment]
I edited the bug report as requested. Thanks. I am going to check the Docker image in the pull request.
