### ISSUE TITLE
Copyright years is not up to date (2020)

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#2752]
## Bug description & symptom

Copyright years are not updated in the FooterLogin 

## Diagnostic

Copyright years was updated for the sidebar but not the FooterLogin 

## Expected

It need to be updated according the current year (2020),
Maybe should we add a mechanism in order to update this date automatically.

## Context and version information

Tracim 2.6.0, found in mon.tracim.fr

![image](https://user-images.githubusercontent.com/31687635/76315415-eb65d980-62d8-11ea-8935-fb9b144836a4.png)

**Comment by PhilippeAccorsi** [comment]
This is fix in tracim 2.6.2 see 3864030afd6f57b9f682ccea518e26372e10decd
I close this issue.
