### ISSUE TITLE
The repo URL is hardcoded in the Dockerfile

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#2753]
## Bug description & symptom

When attempting to build the Docker image from a fork of Tracim, the Docker recipe still fetches the main Tracim repository. 

## Expected

It should be possible to build the Docker image from a local repository, or from a fork, without editing the Dockerfile.

## Suggestion

~By default, the docker image could clone the `tracim/.git` local repository instead of re-cloning the repo from internet. We may not want this, though.~ Actually, this is impossible without bind-mounting or copying the repository inside the Docker container.

## Impacted components

- deployment with Docker

**Comment by PhilippeAccorsi** [comment]
Verified.
