### ISSUE TITLE
Provide a Link / Share button from documents in Tracim 

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#2754]
## Feature description

When a document or a thread is opened in Tracim, it would be nice to have a way to get the link from this content for sharing in an email or a chat.

## Context

I opened a thread an wanted to invite discussion in Tracim from the team chat.

## Impacted components

Frontend applications

## Suggestion

![image](https://user-images.githubusercontent.com/3817365/76509575-88974e00-6450-11ea-914c-6d942c28ae05.png)

The title could become a link? There could be a share button?

**Comment by Skylsmoi** [comment]
There now is the feature public sharing. Also, the private link is now copyable with a button
closing
