### ISSUE TITLE
Add a button to insert an inline <code> HTML tag / monospace snippet in the WYSIWYG html editor

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#2755]
## Feature description

It would be nice to be able to insert a code snippet in HTML documents and comments in Tracim, using the `<code>` HTML tag.

## Impacted components

- *frontend*, TinyMCE

## Extra information

Related: #1255

**Comment by Skylsmoi** [comment]
Prismjs lib has been added to tracim
closing
