### ISSUE TITLE
NVIDIA non-free drivers are installed when building the Docker image 

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#2756]
## Bug description & symptom

While building the Docker image, I noticed nvidia-* non-free packages being installed.
## Diagnostic

To reproduce, build the Docker image and watch closely.

## Expected

No non-free package should be used when building the Docker image. They are probably not needed anyway.

## Context and version information

*For example:*

- *deployment* - Docker

**Comment by PhilippeAccorsi** [comment]
Maybe something not good in default source.list of this docker image `debian:stretch` used to build tracim image ?
