### ISSUE TITLE
Warning about the apt command being used in a script when building the docker image

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#2757]
## Bug description & symptom

This is mostly harmless, but when building the Docker image, there is a warning about the apt command being used:

    WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Should we use `apt-get` instead?

## Expected

We probably should aim at as few warnings as possible.

## Impacted components

- *deployment* - Docker

**Comment by Skylsmoi** [comment]
There is no apt in any docker scripts
closing
