### ISSUE TITLE
Generic font is missing in some CSS rules

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#2762]
## Bug description & symptom

Some `font-family` CSS rules do not specify a generic font (`sans-serif` or `serif`). This does not conform to the CSS standard and may lead to font rendering issues on some configurations.

## Expected

All `font-family` rules end with a generic font.

## Impacted components

- *frontend*

**Comment by Skylsmoi** [comment]
each font-family declaration have a fallback to either "sans-serif" or "monospace".
Closing
