### ISSUE TITLE
Responsive problems with TinyMCE : edition area isn't large enough

### ISSUE THREAD

**Issue by celiamgtt** [tracim/tracim#2764]
## Bug description & symptom

When the user edits a html document under ~1200px the edition area is too small.
There is a second problem: if the user clicks on 'edit' under 1200px and then enlarge the window, the edition area isn't following (responsive is broken).
The last problem is: sometimes, the 'cancel' and 'validation' buttons are cropped or hidden.

## Expected

TinyMCE should be responsive to allow the edition. Buttons should be displayed correctly at all times.

## Context and version information

- Desktop environment (if applicable)
    - macOS Catalina 10.15.1
    - Chrome

## Screenshots

Cropped buttons
![Capture d’écran 2020-03-17 à 10 59 37](https://user-images.githubusercontent.com/50453784/76846183-6763a280-6840-11ea-861c-cd1ad6c80b72.png)

Buttons not displayed
![Capture d’écran 2020-03-17 à 11 00 26](https://user-images.githubusercontent.com/50453784/76846233-78141880-6840-11ea-8980-78e4dbf0a795.png)

Small edition area
![Capture d’écran 2020-03-17 à 11 01 19](https://user-images.githubusercontent.com/50453784/76846313-9843d780-6840-11ea-9233-9548fe1301b1.png)

Small edition area even if the window is larger
![Capture d’écran 2020-03-17 à 11 01 45](https://user-images.githubusercontent.com/50453784/76846338-a4c83000-6840-11ea-8780-3a50b8fd5063.png)

## Impacted components

- frontend

**Comment by PhilippeAccorsi** [comment]
I have seen also this two first bug with Firefox 68.5.0 on Debian Buster (10).

**Comment by metzgegu** [comment]
We need to make tinyMCE height responsive.
For now I successfully made it with [this answer](https://stackoverflow.com/questions/19861838/tinymce-4-and-100-height-within-containing-element?answertab=votes#tab-top), but it is HACKY and a better solution is required

**Comment by gbonaspetti** [comment]
Verified on branch (wait merge to close).
