### ISSUE TITLE
Feat: add rich text on description available in advanced dashboard

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2770]
## Feature description

Add rich text in description of dashboard. This advanced edition is always active like the one in note documents.

## Prerequisites

None

**Comment by grignards** [comment]
One remark: mentions in this field won't be interpreted by the backend (as it is not a content). So not showing the auto-complete mention popup in this case seems a good idea.

**Comment by gbonaspetti** [comment]
Tested on branch
