### ISSUE TITLE
Fix cypress switching_different_workspace_advanced.js

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#2783]
## Bug description & symptom

The cypress test `switching_different_workspace_advanced.js` fail sometimes in Travis

## Expected

The test works properly and is stable

## How to reproduce

(it doesn't fail every time)
- push a commit on github
- check Travis ci cypress test results

## Impacted components

functionnal_test

**Comment by PhilippeAccorsi** [comment]
Screenshot of error:
![Screenshot_2020-04-24 Job #6519 11 - tracim tracim - Travis CI](https://user-images.githubusercontent.com/25848257/80218722-d43d3a00-8641-11ea-85f1-5b46db46af93.png)

**Comment by metzgegu** [comment]
First, I think it randomly fail because the test is badly written (unfortunately by me)
The error which appears is linked to the `beforeEach` hook of the test, In fact it should be a `before` instead of `beforeEach` because it need to create just one workspace.
The test file need also this hook `afterEach(() => { cy.cancelXHR() })` which is a common practice in Tracim Cypress test to improve their stability
