### ISSUE TITLE
poor performance on large database for content/read status endpoint

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2787]
## Bug description & symptom

On large database, content and read status endpoint may take few second to return result.

## Diagnostic

- Too much sql query are done for read status, see also #697 .
- There does exist where clause on both workspace_id and content_id for getting restricted list of content visible by user, but neither workspace_id nor content_id does have index in content_revision table now.

## Hotfix

One way to mitigate the issue is by creating index for both workspace_id and content_id in content_revisions, in order to allow database to filter more easily content_revision:

for postgresql (should probably work on other database):

```
create index content_revisions_content_id_index
	on content_revisions (content_id);
```

```
create index content_revisions_workspace_id_index
	on content_revisions (workspace_id);
```

On postgresql 9.6.17, this lead to a 7s to less than 100ms performance on this kind of query on my own machine:

```
SELECT content.id AS content_id
FROM content JOIN content_revisions ON content.id = content_revisions.content_id AND content_revisions.revision_id = (SELECT content_revisions.revision_id AS content_revisions_revision_id
FROM content_revisions
WHERE content_revisions.content_id = content.id ORDER BY content_revisions.revision_id DESC
 LIMIT 1)
WHERE content_revisions.type IN ('file', 'html-document', 'thread', 'page', 'folder', 'comment', 'any')
    AND content_revisions.workspace_id = 552
    AND (content_revisions.workspace_id IN (552) OR content_revisions.workspace_id IS NULL
    AND content_revisions.owner_id = 1)
  AND content_revisions.is_deleted = false
  AND content_revisions.is_archived = false
  AND content_revisions.is_temporary = false
ORDER BY content_revisions.updated DESC, content_revisions.revision_id DESC, content_revisions.content_id DESC;
```
Instead of needing to real all value of the content_revision table, postgresql can do 
- bitmap index scan on workspace_id index
- index scan on content_id index.

to remove hotfix:

```
drop index content_revisions_workspace_id_index;
drop index content_revisions_content_id_index;
```

## Expected

Better performances for contents and read_status on large database.

**Comment by inkhey** [comment]
Postgresql allow to create index without locking table with
see https://blog.dbi-services.com/create-index-concurrently-in-postgresql/ (1)
and (in french) https://docs.postgresql.fr/9.6/sql-createindex.html  section " Construire des index en parallèle"  (2)

To summarize briefly:
-  CREATE INDEX CONCURRENTLY  allow to add an index without locking table, this is useful for production. 
- CREATE INDEX CONCURRENTLY cannot be used in transaction. If the command failed, it should be dropped, to avoid invalid index, see (1)
-  CREATE INDEX CONCURRENTLY cost more than CREATE INDEX, it should be use only for "hot swapping" like index creation.

```
create index concurrently content_revisions_content_id_index
	on content_revisions (content_id);
create index concurrently content_revisions_workspace_id_index
	on content_revisions (workspace_id);

```

```
drop index concurrently content_revisions_workspace_id_index;
drop index concurrently content_revisions_content_id_index
```

**Comment by PhilippeAccorsi** [comment]
~~~
I hope indexes are build on all database systems ? @inkhey could you confirm?

I confirm, the only specific database behaviour is when upgrading a mysql database, which automatically create index on foreign key, we do not recreate index that already exist.
~~~

**Comment by PhilippeAccorsi** [comment]
Verified on branch (wait merge to close).
