### ISSUE TITLE
Email notifications : when sender name contains non-ascii chars, the email disappear silently

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#279]
Currently : when "Benoît Lapère" updates a content on Tracim the notification is not sent. If "Benoît Lapère" is renamed to "Benoit Lapere", then the mail is sent.
The sender of the email is built like this : "Benoît Lapère via Tracim <info-213@tracim.com>

Expected : 
- Manage accentuated chars in order to send emails in all case
- Do not catch exceptions silently (and probably add a try/except generic bloc at root of asynchronous task in order to log it)

Tools : for bugfix, test using a python 3.5 script sending mail through Mailjet SMTP.

**Comment by xandercagexxx** [comment]
verified. Ubuntu 17.04
