### ISSUE TITLE
Wrong warning message when disconnecting from Gallery App

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#2791]
## Bug description & symptom

When the user disconnect from gallery app page, a warning message appears (error while getting contents)

## Diagnostic

In fact, all fullscreen app are re-rendering when the user disconnects.
Indeed, `Header.jsx`, when disconnecting,  dispatch the redux action to modify the state of `user`, so when `user` has changed `AppFullscreenRouter.jsx` re-render because it is connected with `user` by redux, and for a little time the url hasn't changed yet so it re-render the fullscreen app (in this case the gallery try to fetch data while the user is disconnected)

## Expected

- [ ] Fullscreen app can't be shown when the user is disconnected 

## Impacted components

- frontend

**Comment by metzgegu** [comment]
We could check if user is connected in `AppFullscreenRouter.jsx` but I don't know if it is the best solution to fix it (?)

**Comment by metzgegu** [comment]
Issues doesn't appear in `app_admin_workspace_user` because in `AppFullscreenRouter.jsx` there is a check on the Route to ensure that `user.profile === PROFILE.administrator.slug`

**Comment by gbonaspetti** [comment]
Verified on branch (wait merge to close).
