### ISSUE TITLE
Edit a message in a thread

### ISSUE THREAD

**Issue by YannickBiet** [tracim/tracim#2797]
## Feature description

Being able to edit a message after having been sent to Tracim

## Context

When using threads and sending messages to Tracim threads, I can have done some typo mistakes needed to be fixed. I can't see any way to edit a message, nor to delete it if in the meantime some other members of the shared space already answered a question or if the message is useless now.

## Impacted components

- unkown

**Comment by PhilippeAccorsi** [comment]
Related to #1455

**Comment by YannickBiet** [comment]
I agree with @PhilippeAccorsi this is related, the #1455 only mention timeline but it should maybe be system wide and so including also threads.

I don't know what is the preference of Algoo for dealing about similar requests, i let Philippe decide if we need to close this one.
TY

**Comment by PhilippeAccorsi** [comment]
Thread app and time line use the same code in tracim.
@Skylsmoi what do you think about this issue, do we need to save 2 issues (one for thread and one for timeline) or to update this issue with information available in the other issue ?

**Comment by lebouquetin** [comment]
@PhilippeAccorsi this is a unique issue. If the source code requires several fixes, it means that a refactor is required.

**Comment by Skylsmoi** [comment]
I agree with lebouquetin

**Comment by gbonaspetti** [comment]
Done at https://github.com/tracim/tracim/issues/4367
