### ISSUE TITLE
Bold text is not bold (making difference between read/unread content not clear)

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#2801]
(:warning: only work on this ticket if it is quick)

## Bug description & symptom

In content lists, unread items are shown with a bold font. There is almost no difference between bold and regular items, making difficult to know if the item is read or not read.

Example:

![image](https://user-images.githubusercontent.com/907161/77959709-58b4cb00-72d7-11ea-9f0f-cf0580674b1e.png)

First item is bold, second is not.

The font is Quicksand in 17px. If you go to google fonts, there is a huge difference between regular and bold font in 17px:

![image](https://user-images.githubusercontent.com/907161/77959780-78e48a00-72d7-11ea-91cd-1b55271ea44d.png)

(see https://fonts.google.com/specimen/Quicksand)

## Diagnostic

Things to explore:
 - `@font-face` directives
 - which font files are loaded (variants: Light, Regular Medium, Bold, etc). Regular and Bold should be loaded, the others should not.
 - I (@raphj) happen to remember that a few years ago, Firefox had a mechanism that automatically boldens the font if the right variant is not found, whereas Webkit didn't have such a mechanism. It is possible that for some reason, Chromium finds the bold variant of the font and uses this, while Firefox does not and applies its mechanism) 

## Expected

- [x] explain the reason for this "not standard bold font"
- [x] use the Regular variant everywhere for non bold content in any browser
- [x] use the Bold variant everywhere for bold content in any browser
- [x] never use the light and medium variant

## Extra information

- Font is Quicksand, 17px on content list page (and 18px on dashboard :-s) - the problem is not related to font size, I think, because there is the same issue on both sizes.

## Related

#2763

**Comment by Skylsmoi** [comment]
From a css point of view, there is nothing wrong.

The is in bold.

All I have found is that is chromium, the bold looks, indeed, more bold.

So, it might be firefox that isn't rendering it bold enough

**Comment by Skylsmoi** [comment]
All I did was a quick check.

I think some deeper investigation is required for this issue. If issue there is.

**Comment by lebouquetin** [comment]
> So, it might be firefox that isn't rendering it bold enough

No: look at the two screenshots: they are both taken from firefox. The issue is not about firefox not rendering well the font. I think there is a CSS rule that lighten the font or something like this.

> If issue there is.

There is:

- result is ok on Chrome
- result is ok on Firefox for a google fonts page, not for a Tracim page

**Comment by metzgegu** [comment]
The font `QuickSand` isn't correctly imported to be able to use the different `font-weight` available for this font.
Indeed to import font-weights with a `<link>` the url should have: `?family=Quicksand:wght@300;400;500;600;700` see: https://fonts.google.com/specimen/Quicksand

We need to find how to do it with `.ttf` file

**Comment by metzgegu** [comment]
In fact we already have the 4 `.ttf` files which contains each `font-weight` options, we only need to add :
```
@font-face {
      font-family: 'Quicksand';
      src: url('/assets/font/Quicksand/Quicksand-Bold.ttf');
      font-weight: bold;
    }
```
in index.html & index.mak

**Comment by raphj** [comment]
This is quick fix then @lebouquetin?

**Comment by lebouquetin** [comment]
if so, add it to tracim 3.1

**Comment by inkhey** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Verified.
