### ISSUE TITLE
Mail Reply support for non-subaddress ?

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2811]
## Bug description & symptom

Mail Fetcher should work with:
- sub-address like `toto+content{id}@mysite.com`
- address pattern like `{id}.content@mysite.com` (wildcard should be set )
- fallback with any of these using `References` header.
- support with app specific header (need specific client support)

It seems that other mode than sub-address doesn't work correctly, this issue is about inspecting what is working and what doesn't work now.

## Expected

Know what is working and what is not to clarify how to use mail fetcher if sub-addressing is not allowed by email provider.

**Comment by inkhey** [comment]
Verdict After Audit:

- sub-addressing as expected work.
- alias pattern in reply work too.
- fallback with References fail:
    - Mail Fetcher is not coded in a way that allow this usage. It will fail if from header search fail.
    - Tested Webmail does not return correctly References header : 
        - `Roundcube` add external `mid:{number}` to the header, parsing to support is possible but not easy.
        - `Sogo` don't return References Header
- logging issue in email-fetcher: https://github.com/tracim/tracim/issues/2812

**Comment by inkhey** [comment]
After new research, 
i found that Roundcube behavior is not abnormal, as References Field should be completed by new references for each email, but the issue is related to a parsing issue of reference, if reference is not under "<>" bracket, it cause trouble on many software (including thunderbird) and python parsing tool we use for mail fetcher to properly retrieve the information.

**Comment by PhilippeAccorsi** [comment]
Tested and verified on branch. (Wait merge to close)

**Comment by PhilippeAccorsi** [comment]
Some exemple added in setting.md
