### ISSUE TITLE
Uncorrect log in Tracim (especially mailFetcher) return empty value instead of returning Traceback

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2812]
## Bug description & symptom

Some logging return error but with empty explanation, especially in mailFetcher.
This issue as not been reported yet because these error case are something very hard to reproduce (should not happened in normal usage for exemple), they do exist to ensure daemon process like mailFetcher will not stop.

## Diagnostic

logging like : 

```python
try:
    dosomething()
except SomeException as exc:
    log = "Some log message {}"
    logger.error(self, log.format(exc.__str__()))
```

are broken, because exception may have empty str value.

## Expected

replace these logging to something like:

```python
try:
    dosomething()
except SomeException as exc:
    log = "Some log message"
    logger.exception(self, log))
```

in order to have real log

**Comment by PhilippeAccorsi** [comment]
Tested and verified on branch. Wait merge to close.
