### ISSUE TITLE
Building frontend components is slow

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#2813]
## Bug description & symptom

Building component is slow, we can do better.

Here is what we can do (we need to discuss each point):

- [x] Add a way disable linting when end users are building
- [X] stop bundling react, react-dom, frontend_lib and other common libraries in each frontend component, and include them in the html webpage and use Webpack's `externals` feature ~~, or in a Webpack DLL~~ see #3016 #3017.

Preliminary investigation (putting react and tracim frontend lib in externals) more than halves the build time and produces a much lighter bundle in the component on which I tested it, and I expect this result to be identical for each frontend component.

Ideally:
 - when building a component, we should only have to build its own specific code
 - when changing the frontend lib, we should only have to rebuild the frontend lib and application that needed edition

## Impacted components

- *frontend* build

**Comment by Skylsmoi** [comment]
If I understand correctly, the precommit hook will make the standard js parse on every push.
So every push will take about 15s.
While this isn't that big of an issue, it will also be the case for backend only push.

Or we will have to add a process that check if the commit is fontend related.

For the solution to enable linting only for dev, I don't see any downside.

**Comment by raphj** [comment]
This is done
