### ISSUE TITLE
Add a SMTP Mail Checker Script

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2827]
## Feature description

Add a script to test if tracim smtp configuration does work properly.

## Context

The feature goal is to avoid issue related to bad configuration like the very long response time when configuring unencrypted smtp for a smtp server that expect TLS.

## Implementation 
#5385

- Add command to test tracim email configuration that send a test email directly.

**Comment by inkhey** [comment]
tested on branch by @Haskaris

**Comment by knodelle** [comment]
done
