### ISSUE TITLE
Add endpoint to return the list of a user's notifications

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2831]
## Feature description

The endpoint must return the list of x most recent and unread notifications
It must have a param to returns the x most recent read notification (archived)
It must have pagination (like the search endpoint)
x should be a query param

## Context

This will be used in the notification pane

## Impacted components

backend

**Comment by Skylsmoi** [comment]
Need to decide how must notifications are returned by page

**Comment by lebouquetin** [comment]
This feature will be implemented with #2835

**Comment by raphj** [comment]
Closed because it is a duplicate of #2835.
