### ISSUE TITLE
 Add endpoints to set messages (TLMs) as read/not read

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2835]
## Feature description

We need to be able to mark messages as (un)read when clicking on the "mark all as read" button (#3322) on the notification pane or on a notification.

Add these endpoints:
- [x] PUT `/api/users/<user_id>/messages/<event_id>/read` that will set the message's `read` field to the current UTC datetime
- [x] PUT `/api/users/<user_id>/messages/<event_id>/unread` that will set the message's `read` field to `None`/`null`
- [x] PUT `/api/users/<user_id>/messages/read` that will set all messages `read` field to the current UTC datetime if they not already have a read date.

## Implemented solution
add endpoints as expected:
- PUT `/api/users/<user_id>/messages/<event_id>/read`, 
- PUT `/api/users/<user_id>/messages/<event_id>/unread` 
- PUT `/api/users/<user_id>/messages/read` 

All theses endpoint  returning , returning 204 NO CONTENT if ok.
- When tuple user_id,event_id don't match with a valid, should return error 400, errorcode  1009 (MESSAGE_NOT_FOUND)
- Reread a content will reset the read datetime.
- Unread a readed content will delete the read datetime.
- Unread an unread content change nothing
---
_13-07-2020 - Description edition: Added task list and unread endpoint._
_17-07-2020 - Description edition: Added specification at message_id and event_id._
_20-07-2020 - Update with state of the PR: https://github.com/tracim/tracim/pull/3362 and use `event_id` instead of composite key `message_id` ._

**Comment by lebouquetin** [comment]
> NB: the message_id is in fact event_id in database as the messages have a composite primary key (user_id, event_id).

I'm not very confident with this design. The API design let us understand that `message_id` is the primary key. If writing issues need this kind of explanation, what about a developer who wants to use our API without knowing how Tracim works?

**Comment by inkhey** [comment]
> > NB: the message_id is in fact event_id in database as the messages have a composite primary key (user_id, event_id).
> 
> I'm not very confident with this design. The API design let us understand that `message_id` is the primary key. If writing issues need this kind of explanation, what about a developer who wants to use our API without knowing how Tracim works?

As there is always one message per user per event, i don't see any reason to name it message_id. Using event_id seems to me better.

**Comment by PhilippeAccorsi** [comment]
api visible here http://localhost:7999/api/doc/
