### ISSUE TITLE
Redesign of header

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2839]
## Feature description

- [ ] redesign the header to be lighter
  - improve responsiveness but keep the header as much ergonomic as possible (don't remove text of buttons)

## Context

- Too much information
- Responsive problems

## Impacted components

frontend

## To be discussed before start development

There are three points to be discussed before start this development.

1. Language button: The button wont change when clicked, the dropdown menu will show `flag + text`, the discussion is only about the label that stay in header 
     - Leave flag + text
          - Pros: easy to understand
          - Cons: the size changes according to the language and can be big 
![flagEnglish](https://user-images.githubusercontent.com/35422692/87051401-cf7b3180-c1ff-11ea-8a96-aabd9e5fc2ac.png)

     - Just the text
          - Pros: easy to understand
          - Cons: the size changes according to the language and can be big
![English](https://user-images.githubusercontent.com/35422692/87051414-d3a74f00-c1ff-11ea-8304-0ea8bbb83516.png)

     - Just the flag
          - Pros: lighter, size fixed, easy link to "here I change the language" (even if the user doesn't know the current flag that the header shows he probably knows that it's a flag and flag it's linked to a country that it's linked to a language )
          - Cons: similar flags (ex: france and netherlands)
![flag](https://user-images.githubusercontent.com/35422692/87051439-dace5d00-c1ff-11ea-8f4d-7d8e17ef1736.png)

     - Language abbreviation (ISO 639-1)
          - Pros: lighter, size fixed
          - Cons: need some knowledge (its not clear for all users that you can click on FO to see other language, FO is for Féroïen), we will need to add this information at dropdown menu
![EN](https://user-images.githubusercontent.com/35422692/87051455-e0c43e00-c1ff-11ea-8c07-7204b01f7f26.png)

2. Add the current language at dropdown menu (especially if we choose just the flag or the abbreviation)
3. Decide the buttons order
![header](https://user-images.githubusercontent.com/35422692/87040453-03028f80-c1f1-11ea-9cbb-8ab84859ccaa.png)
 - Proposition: `Administration` - `Search bar` - `Agenda` - `To do` - `Notification` - `Language option` - `Account`
    - Administration in the left to not "move" the buttons positions if you are admin in one Tracim instance and user (or trusted-user) in other
   - Notification at left should be near to the wall to the left that it opens (https://github.com/tracim/tracim/issues/2840) 
   - To do and Notification at left since they will have a count icon that will be pretty visible, therefore, it's better to put them as far right as we can

**Comment by PhilippeAccorsi** [comment]
Idea to imporve Tracim header is to show a small button for language with flag of country. When clicking on flag we shown list of available language (show flag and language name).

In Mailtrain (v2) Software, one button also exist in header but just show 2 letter of each language. 
I think, showing flag its better because its more simple to understand its about language. If I just show one button with this two letters `fo`, its not clear for all users that you can click on `fo` to see other language (`fo` is for `Féroïen`).

**Comment by Skylsmoi** [comment]
I like the idea of only having the flag in the button and having the text only when clicking on it

**Comment by lebouquetin** [comment]
> I like the idea of only having the flag in the button and having the text only when clicking on it

Not showing the text is a fallback. For example, if you are belgium you will have to choose french flag or netherlands flag... :-s

**Comment by lebouquetin** [comment]
this issue must include up-to-date wireframe built by @celiamgtt

**Comment by celiamgtt** [comment]
We have to determine the buttons order: 
![Capture d’écran 2020-04-23 à 15 48 06](https://user-images.githubusercontent.com/50453784/80106230-e358b500-8579-11ea-9a19-051d2220bea1.png)

**Comment by PhilippeAccorsi** [comment]
I'm not sure but for me, this order is better :
- "search" - "Notification" - "To do" - "Agenda" - "flag" - "account" (user and trusted-user)
- "search" - "Administration" - "Notification" - "To do" - "Agenda" - "flag" - "account" (admin)
or
- "Administration" - "search" - "Notification" - "To do" - "Agenda" - "flag" - "account" (admin)

**Comment by PhilippeAccorsi** [comment]
>     * "Administration" - "search" - "Notification" - "To do" - "Agenda" - "flag" - "account" (admin) => I prefer this

For me its better like this for admin because other button not move if you are admin in one tracim and user (or trusted-user) in other Tracim instance.

So admin button just appear and not really change interface and button position.

**Comment by Skylsmoi** [comment]
I agree for the administration button.
About the notif and todo, I think it's better to put them on the right of agenda since they will have a count icon that will be pretty visible, therefore, it's better to put them as far right as we can

**Comment by gbonaspetti** [comment]
I'm going to close this issue since the header was merged with sidebar at #5111
