### ISSUE TITLE
Feat: Implement the notification wall

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2840]
## Feature description

We need to display the most recent notifications. For that, we shall implement a notification wall (see interface below). 

**Expected:**
- a list of notification is displayed with
    - [x] Maximum 15 notifications are displayed by default and if the list has more than 15 notifications, we show the "see more" button
    - [x] A read notification has a different design that not-read (see interface below)
    - [x] When the component mounts, a request of the newest 10 notifications of the user is done to the API and this list is saved in redux
    - [x] Each incoming TLM updates the redux list
    - [x] Each element of the redux list is an object with:
        - notification id
        - the type of the notification and its icon
        - the read status of the notification
        - the document url and label
        - the author
        - the shared space
        - the creation date of this notification
- [x] there is a close button
- [x] clicking on a notification (anywhere, doesn't need to be in the content title) opens the related content
     - it's a redirection, the content does not open in a new tab
- [x] clicking on a notification marks the notification as read
- [x] there is a button "see more" at the bottom (if the list has more than 15 notifications, for pagination)
    - clicking on this button shows 15 more notifications at the bottom of the already present ones

**Note**: For the notifications that are not at the translation table, it was decided to put "{{author}} {{notification_type}}" and these notifications will redirect to the content associated or to the Home Page if there is no content associated. The objective is do not do useless development, so first we test what are the useful TLMs and just than do the filter for 'what TLMs are notification'

## Prerequisites

- #2835 (read/not read status in backend) - issue merged
- #3057 (pagination and filter) - issue merged

## Extra information

- This component will be a part a frontend repository. Pay attention to z-index (https://github.com/tracim/tracim/issues/2840#issuecomment-645277067).
- The button "Mark all as read" will be implemented at #3322 
- The filter button will be implemented at #3324 
- At the moment, for this issue, a click on a notification only opens the related content. An automatic scroll to mention will be implemented at #3321 (not for V.3.1.0)

### Instruction to test
An edition to the code is necessary to test this issue. The wall is opened by editing file `frontend/src/container/NotificationWall.jsx` as follows:

```
   constructor (props) {
     super(props)
     this.state = {
-      isNotificationWallOpen: false
+      isNotificationWallOpen: true
     }
   }
```
And rebuild the frontend after this modification.

## Translations

| English | French | Portuguese |
|--|--|--|
| Notifications |  Notifications | Notificações |
| {{author}} mentioned you in a comment in {{content}} at {{shared_space}} | {{author}} vous a mentionné dans un commentaire sur {{content}} dans {{shared_space}} | {{author}} mencionou-o num comentário do {{content}} no {{shared_space}} |
| {{author}} mentioned you in {{content}} at {{shared_space}} | {{author}} vous a mentionné dans {{content}} dans {{shared_space}} | {{author}} mencionou-o no {{content}} no {{shared_space}} |
| {{author}} added you to {{shared_space}} | {{author}} vous a ajouté dans {{shared_space}} | {{author}} adicionou-o à {{shared_space}} |
| {{author}} created {{content}} at {{shared_space}} | {{author}}  a créé {{content}} dans {{shared_space}} | {{author}} criou {{content}} em {{shared_space}} |
| {{author}} updated a new version of {{content}} at {{shared_space}} | {{author}} a mis à jour nouvelle version de {{content}} dans {{shared_space}} | {{author}} actualizou uma nova versão de {{content}} em {{shared_space}} |
| {{author}} updated the status of {{content}} at {{shared_space}} | {{author}} a mis à jour le statut de {{content}} dans {{shared_space}} | {{author}} actualizou o status de {{content}} em {{shared_space}} |

## Interface
_Some elements like icons can changed, please follow the spec bellow the screenshot for this type of detail._
![notifs_mur](https://user-images.githubusercontent.com/50453784/88295023-2e12d600-ccfd-11ea-8137-bcad39402bf4.png)

Notifications not readed: `background-color : #F6F6F6;`
Notifications readed: `color (text): #595959;`
Notifications hover: `background-color : grey-hover`
Design blue point: `fa-circle` icon, `8px`, `color #3F9FF7`
Mentioned at comment icon: `fa-comment-o`
Mentioned at document icon: `fa-check-square-o`
Added to a shared space icon: `fa-user-o`
New version icon: `fa-history`
New status icon: `fa-random`
Content creation icon: `fa-magic`
Notification's height: `50px`
Icons size of notifications: `23px`
See more button area's height: `60px`

----
_09-07-2020 - Description update: added "click on" behaviors._
_10-07-2020 - Description update: solve "see archived" discussion (it will not be implemented at v.3.1.0) and divided the issue at smaller ones (more details at Extra information section)._
_13-07-2020 - Description update: specified redux behavior, added translation and backend prerequisites._
_16-07-2020 - Description update: added context at begging, interface and its specifications._
_20-07-2020 - Description update: specified the number of notifications get at first request to API, updated interface, its specifications and divide the issue (mark the notification as read but not redirect to the content it will implemented/discussed at https://github.com/tracim/tracim/issues/3361 and it's not for V3.1.0)._ 
_22-07-2020 - Description update: simplify texts and its translations in order to avoid the text in three lines for big names._
_11-08-2020 - Description update: 10 → 15. Added test instructions_
_12-08-2020 - Description update: replace wrong value (old is 10, new is 15) for button "see more"

**Comment by lebouquetin** [comment]
The up-to-date wireframe built by @celiamgtt must be included here

**Comment by Skylsmoi** [comment]
current mockup (at 2020-04-23):

![notifs_mur_HF](https://user-images.githubusercontent.com/11177014/80085293-518c8000-8558-11ea-90c8-559ee66908da.png)

**Comment by Skylsmoi** [comment]
careful about z-index for the pane.

Here is the list of z-index in frontend:
| z-index | Component | css selector | comment |
| --- | --- | --- | --- |
| 1050 | Generic | div.mce-fullscreen | |
| 60 | FlashMessage | .flashmessage | |
| 50 | CardPopupCreateContent | .popupCreateContentOverlay // over header | |
| 40 | Agenda | #agendaIframe | I couldn't confirm this one |
| 30 | Header | .header .navbar |
| 25 | CollaborativeEditionFrame | #loleafletframe |
| 20 | cardPopup | .cardPopup |
| 20 | PopinFixed | .wsContentGeneric |
| 10 | Sidebar | .sidebar |

**Comment by grignards** [comment]
> When the Tracim.jsx component mounts, a request of all notifications of the user is done to the API and this list is saved at redux

Shouldn't it only request the newest notifications? The entire list of notification can become huge (which is why we have pagination).

**Comment by gbonaspetti** [comment]
This issue was moved to In Progress because some interface development is in progress, but the label remains because it's yet blocked by backend. I can start the development, just not finish it.

**Comment by raphj** [comment]
Tested  on branch.

**Comment by PhilippeAccorsi** [comment]
Tested on develop.

**Comment by PhilippeAccorsi** [comment]
Verified.
