### ISSUE TITLE
Connect to real time solution for notifications

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2842]
## Feature description

- [x] frontend implementation must be usable for tracim's app
  - specify the protocol and architecture
- [x] connect to backend with right session key
- [x] trigger frontend update on new notification
- [ ] ~~trigger frontend update on new todo~~ EDIT: there is nothing specific for TODOs
- [x] clean closing of connection

## Context

Frontend needs to connect to the backend stream server in order to get TLMs (Tracim Live Messages)

## Impacted components

frontend

## Extra information

backend related issue: https://github.com/tracim/tracim/issues/2837

## Next step

https://github.com/tracim/tracim/issues/2850

**Comment by Skylsmoi** [comment]
I have started the development of the frontend implementation.

I'm now refactoring the appInterface.js to include it in Tracim (currently it is in dist/asset/tracim/)

The point is to rationalize the code base and put all the code related to events handling in the same place.

Also, I put it outside of tracim to have an easier time with global function. I'm now using the globalThis feature for this and I can include it inside Tracim.

This will force me to lint the file properly.

**Comment by Skylsmoi** [comment]
About the refactor with globalThis, I need to refactor every usage of global function with globalThis.

This will make the code more readable

**Comment by Skylsmoi** [comment]
I have pushed the refactor into creating a folder frontend/src/util/ where I have put appInterface and tinymceInit to have them wandering at the root of src/.

I took advantage of this to also put files i18n.js, helper.js and appFactory.js.

The futur file LiveMessageManager.js will also be in there

**Comment by Skylsmoi** [comment]
The PR also fix every linting errors

**Comment by PhilippeAccorsi** [comment]
Tested with elasticsearch, collabora and agenda feature. Also created thread, document, file, and starting gallery.
