### ISSUE TITLE
Add mention process for all contents

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2843]
## Feature description

Mentioning someone will create a notification to the related users. The mentions can be done in a comment and in HTML documents.

- [x] add autocomplete list that it is displayed in front of the current interface after writing `@` and one following letter at the beginning of a sentence or after a blank space` ` (see list interface bellow)
  - auto complete popup must list the matching know members in the shared space (username, full name or email)
  - related backend issue: https://github.com/tracim/tracim/issues/2830
- [x] Pressing the _Enter_ key should complete with the user being hovered
     - there should always be a  "selected" user. By default, it is the first of the list
- [x] add group mentions on autocomplete lists (just `@all`)
    - these mentions should be translated according to the current language 
- ~~the comment parsing will be the addition of a html tag with at least a id unique~~
  - this task has been moved to its specific issue here: https://github.com/tracim/tracim/issues/3411

## Prerequisites

- backend for autocomplete https://github.com/tracim/tracim/issues/2830
- backend for TLM mentions https://github.com/tracim/tracim/issues/2838 

## Interface

[ Need @lebouquetin validation ]

![notifs_mention_popup_in_app](https://user-images.githubusercontent.com/50453784/88678678-00f46800-d0ef-11ea-890e-a6e611cdcc12.png)

![notifs_mention_popup_comment_advanced](https://user-images.githubusercontent.com/50453784/88678682-02be2b80-d0ef-11ea-8b85-388fc23befb2.png)

![notifs_mention_popup_comment](https://user-images.githubusercontent.com/50453784/88678695-05208580-d0ef-11ea-83b5-d99f39d4569f.png)

### TextArea

In order to show the autocomplete pop-up when typing a new comment, the textarea is parsed to find a mention candidate before the current cursor position (e.g. `@word|`), if a mention candidate is found the autocmplete popup will show up and it will fetch users according to the word typed. The user can validate his choice by pressing enter or click the mention item, it replace the mention candidate by the correct mention.

## TinyMCE

TinyMCE autompletion use the same popup as the texterea. but the trigger to open the popup is different. Indeed tinymce edit directly the html and getting the current selection is different. The autocomplete popup will be triggered if the user type `@` and will stay activated while the user type a correct mention candidate (e.g. `@word|` with `|` the current cursor position), when the user will validate the mention from the popup it will use html `<span>` to select and replace the mention in the text.

# Backend

`include_workspace_ids` parameters was not taken into account in the backend. We fixed this here.

----
_08-04-2020 - Description change: Confirm highlight functionality._
_10-07-2020 - Description change: Divided issue, the highlight will be implemented at #3325, and added "click on enter" behavior._ 
_13-07-2020 - Description change: Added backend prerequisites._
_20-07-2020 - Description and labels change: Deleted impacted component and added labels for it._
_21-07-2020 - Description and label change: Merged context into the main description. Added "needs discussion". Some proofreading_
_04-08-2020 - Description change: the task for wrapping the mention in a span has been moved to its specific issue https://github.com/tracim/tracim/issues/3411_
_24-08-2020 - Add implementation explanation of the current PR_
_24-08-2020 - Add implementation explanation of the current PR about backend fix._

**Comment by metzgegu** [comment]
This issue was moved to In Progress because some interface development is in progress, but the label remains because it's yet blocked by `backend`. I can start the development, just not finish it.

**Comment by inkhey** [comment]
tested on branch

**Comment by metzgegu** [comment]
A little bug with translations was detected, it need to be tested again.

**Comment by inkhey** [comment]
retested with translation in mind:
- mention itself was not translated, i was expecting mentioning all from french ui will be converted to "tous" 
- It seems to me, it was working before but the filter on user for mention is not correct, it should filter on workspace user of the specific workspace where we are commenting/modifying html-document, in my test, i can mention anyone i know in all workspaces without any link with who is in which workspace.

**Comment by raphj** [comment]
> mention itself was not translated, i was expecting mentioning all from french ui will be converted to "tous" in autocomplete

I'm fine for letting the user use the variant they want. They could be using the French interface in an English workspace. If we try to be helpful here, we could end up being irritating.

**Comment by inkhey** [comment]
> > mention itself was not translated, i was expecting mentioning all from french ui will be converted to "tous" in autocomplete
> 
> I'm fine for letting the user use the variant they want. They could be using the French interface in an English workspace. If we try to be helpful here, we could end up being irritating.

We could do this, but it's not the current behaviour. Currently we do support only all in autocomplete and the default proposal is always all when we don't type anything. I do think, as we have a default proposal with all, it should be the current language all that is proposed at first.

**Comment by grignards** [comment]
> retested with translation in mind:
> 
>     * mention itself was not translated, i was expecting mentioning all from french ui will be converted to "tous" in autocomplete

Yes this was forgotten, I'm adding it.

>     * It seems to me, it was working before but the filter on user for autocomplete mention is not correct, it should filter on workspace user of the specific workspace where we are commenting/modifying html-document, in my test, i can mention (with autocomplete) anyone i know in all workspaces without any link with who is in which workspace.

The frontend code does make the `known_members` query with `include_workspace_ids` properly set, so it this does not work it is likely a backend bug/misinterpretation of the parameter. @inkhey could you have a look at this?

**Comment by inkhey** [comment]
> > ```
> > * It seems to me, it was working before but the filter on user for autocomplete mention is not correct, it should filter on workspace user of the specific workspace where we are commenting/modifying html-document, in my test, i can mention (with autocomplete) anyone i know in all workspaces without any link with who is in which workspace.
> > ```
> 
> The frontend code does make the `known_members` query with `include_workspace_ids` properly set, so it this does not work it is likely a backend bug/misinterpretation of the parameter. @inkhey could you have a look at this?

I found and fix the problem on branch, need some review.

**Comment by PhilippeAccorsi** [comment]
Verified.
