### ISSUE TITLE
Add configuration options for notifications and todos

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2844]
## Feature description

unclear

## Context

User should be able to have some configuration options for their notification. Like use of email, deactivate for some shared spaces ...

## Impacted components

frontend

## Extra information

nyi

**Comment by inkhey** [comment]
@Skylsmoi  As this is a configuration per user, the information should be available in backend, so backend is impacted component to, no ?

**Comment by Skylsmoi** [comment]
Backend will have it's own related issue I think
This issue should only track the dev of the frontend feature which are a form and some api calls

**Comment by lebouquetin** [comment]
I think we first need a common issue. When its clear what is required for both backend and frontend, then we can have two issues for implementation.

**Comment by Skylsmoi** [comment]
Ok. That's better yes.
Since you added the tag backend, I assume we will use this issue for that purpose

**Comment by Skylsmoi** [comment]
The feature has been added in 4.9.2
closing the issue
