### ISSUE TITLE
Handle the migration regarding the new username field for already existing users

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2847]
## Feature description

- [ ] look for other platforms to know  how they handle identification of user with something else than the id
- [ ] Have a migration script that handle the username for every users

## Context

This issue https://github.com/tracim/tracim/issues/2829 will add a new field `username` in table user.
This field will be unique and not null. So we will have to create one for existing users during the migration script.

## Impacted components

backend
migration

**Comment by lebouquetin** [comment]
This issue is now included in #2829 I think. @inkhey, what do you think?

**Comment by inkhey** [comment]
> This issue is now included in #2829 I think. @inkhey, what do you think?

I do agree, it does make much sense to create migration separatly.
