### ISSUE TITLE
Display a prompt to notify members of the workspace when editing a file

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2849]
## Feature description and context

After saving a new version of a content, add a prompt in the app with a button to notify members of the new version. This prompt is only shown if the last modification of the content was made by the logged user. As long as the user does not make a decision, every time they enter the content the message will be there.
This is a way to notify members about a specific new version that might be important.

- [x] add the prompt if the user made the last change
- [x] if the user clicks on `X`, the prompt closes
- [x] if the user clicks to notify, a comment is automatically sent with *`@all` please notice that I did an important update on this content.* (this comment will generate a notification)

## Translations

| English | French | Portuguese |
|--|--|--|
| `@all` please notice that I did an important update on this content. | `@tous` veuillez noter que j'ai fait une mise à jour importante sur ce contenu. | `@todos` percebam que fiz uma actualização importante neste conteúdo. |
| To notify all members of the shared space of your modification, click here! | Pour notifier tous les membres de l'espace partagé de votre modification, cliquez ici ! | Para notificar a todos os membros do espaço partilhado da sua modificação, clique aqui! |

## Prerequisites

#3411  

## Interface

![notifications_notifier_message](https://user-images.githubusercontent.com/35422692/89786494-4e73ca80-db1c-11ea-88bb-4d4687f44114.jpg)

This prompt will be inside of the content part (left part) and will have the same color and specifications that the other prompts in the same place.
_Other prompts: deprecated and deleted content._

## Discussion

- _As long as the user does not make a decision, every time he enters the content the message will be there._
    - We'll have a backend variable or just a cookie? If we chose the cookie and the user decides not to notify, the next day he enters at this content, the message will appear again or we will have a timeout of the type "the message only appears if the user made the last change AND this change was less than X hours/days ago". We can also use the generic enpoint (https://github.com/tracim/tracim/issues/3380) to set user decision.

  - *2020-08-24: we'll use the generic config endpoint*. The stored key will be `content.<content_id>.notify_all_members_message`, its value is a bool.

----
_10-07-2020 - Description edition: Put context at the beginning and added task list, impacted components and backend variable vs cookie discussion._
_13-07-2020 - Description edition: Added translations._
_20-07-2020 - Description and label edition: Change impacted components to labels and comment text._
_21-07-2020 - Description and label edition: message → prompt to clarify._
_10-08-2020 - Add interface._
_24-08-2020 - Resolve discussions._

**Comment by lebouquetin** [comment]
> Impacted components

The impacted components are not frontend_app_file, frontend_app_html-document and frontend_app_thread but all content applications. It means that:

- custom form app is concerned
- any future content application should be automatically concerned.

Otherwise, we will have to re-implement this kind of behavior in all future content applications - this is not resilient.

By the way, the "message" (which is actually posting a comment) should not be something like `@all the content {{content_name}} was modified by {{author}}` but `@all Please notice that I did an important update on this content`.

**Comment by raphj** [comment]
@lebouquetin I think "message" here refers to something like a prompt ("do you want to [...]?"). Can you confirm @Skylsmoi?

**Comment by gbonaspetti** [comment]
> > Impacted components
> 
> The impacted components are not frontend_app_file, frontend_app_html-document and frontend_app_thread but all content applications. It means that:
> 
> * custom form app is concerned
> * any future content application should be automatically concerned.
> 
> Otherwise, we will have to re-implement this kind of behavior in all future content applications - this is not resilient.
> 
> By the way, the "message" (which is actually posting a comment) should not be something like `@all the content {{content_name}} was modified by {{author}}` but `@all Please notice that I did an important update on this content`.
>
> @lebouquetin I think "message" here refers to something like a prompt ("do you want to [...]?"). Can you confirm @Skylsmoi?

Yes, "message" refers at the warning message that the user received if he has the last modification. But I'll change the comment text for the one suggested by @lebouquetin and its translations.

**Comment by grignards** [comment]
> Decision: We'll use generic enpoint (#3380) to set user decision.

Using the generic configuration endpoint can work but it has a flaw: this decision is remembered for all edited contents, which means that storing it here will make the endpoint contents grow without bounds (and make the endpoint slower). Furthermore the storage is done in a JSON column so it is unclear whether getting only part (one key for instance) of the config will be efficient.

**Comment by lebouquetin** [comment]
@gbonaspetti i think this should not stored in configuration because it does not scale (like @grignards said). The case to show the message is:

- if the current user is the owner of last revision
- if there is no comment associated to this revision from the owner
- if the user did not click the top-right cross

You agree?

My feeling is we can store this in a cookie at the moment.

**Comment by gbonaspetti** [comment]
> * if the user did not click the top-right cross
> You agree?
> My feeling is we can store this in a cookie at the moment.

@lebouquetin @grignards I still have the same doubt: If we chose the cookie and the user decides not to notify (click the top-right cross), the next day he enters at this content, the message will appear again or we will have a timeout of the type "the message only appears if the user made the last change AND this change was less than X hours/days ago"?

**Comment by raphj** [comment]
The cookie is sent on each request, I don't think it is a good Idea. More generally, I don't think we should store anything for the frontend that the backend does not care about in cookies. Maybe localStorage?

But if we are to store a setting, my preference would be to store this kind of thing in the backend to be sure that the notifications are consistent across the devices. The initial development cost might be higher than just using the local storage but migrating this will probably be an hassle and is bound to happen.

**Comment by grignards** [comment]
A possibility would be to store in the user config and modify the user config endpoint to only allow string keys for the dict. Later on the backend could provide a `GET+PUT /api/users/<user_id>/config/<key>` endpoint + storage change (from one big JSON to several keyed JSONs). Of course this works if the frontend stores each notify choice as a separate key in the "main" dictionary.

**Comment by lebouquetin** [comment]
On a user point of view : there is no timeout. Actually, I think the behavior should be :

- as long as the author of last revision is the current user and no new activity has been done (ie no comment, no share, etc), the message should be shown
- if the user has mentionned all users or as clicked the cross, the message is hidden

In order to have something easy to implement, first iteration should be only based on the author of the last revision and cross clicked (or "cliquez ici" clicked)

**Comment by lebouquetin** [comment]
@grignards I think allowing only string key is mandatory for consistency / ease of upgrade. Your solution seems ok to me

**Comment by raphj** [comment]
@gbonaspetti After discussion with @grignards and @lebouquetin, we shall keep things flat: simple values (strings, numbers, booleans), and no tree in the configuration. We are going to define naming conventions for the keys in the user configuration object, taking inspiration from how Firefox's `about:config` configuration works, with a dotted notation to convey the hierarchy in property names.

For this issue, I think we should use a prefix for all the keys we are going to use here. I don't know wether we should store serialized object in json here or not.

**Comment by grignards** [comment]
> For this issue, I think we should use a prefix for all the keys we are going to use here. I don't know whether we should store serialized objects in json here or not.

For this case a boolean value (`true|false`) should be enough, isn't it? And yes store it under a common prefix, eg. `content.<content/revision_id>.notify_all_members.`. This would give this dictionary:
```json
{
   "content.442.notify_all_members": false,
   "content.4423.notify_all_members": true,
}
```

**Comment by raphj** [comment]
my question was if we should go for something like:

```json
{
   "content.442.notify_all_members": false,
   "content.4423.notify_all_members": true
}
```

or:

```json
{
   "content": "{\"442.notify_all_members\": false, content.4423.notify_all_members\": true}"
}
```

I see drawbacks and advantages to both and I am fine with both.

**Comment by grignards** [comment]
> my question was if we should go for something like:
> 
> ```json
> {
>    "content.442.notify_all_members": false,
>    "content.4423.notify_all_members": true
> }
> ```
> 
> or:
> 
> ```json
> {
>    "content": "{\"442.notify_all_members\": false, content.4423.notify_all_members\": true}"
> }
> ```
> 
> I see drawbacks and advantages to both and I am fine with both.

What we concluded is that we should prefer the first form as it will allow the backend to provides fine-grained filters if needed later on. With your second form the frontend will be forced to get all values (and this can become big).

**Comment by lebouquetin** [comment]
@raphj I agree with @grignards . KISS. maybe not optimized (not sure) but easy and simple. Easy to use, easy to understand, easy to implement, easy to hack, easy to upgrade...

**Comment by raphj** [comment]
Tested on branch and works correctly. However, I have one problem and one question with the current implementation:

    the "click here" button should either be a link ("a" tag) with an outliine, or remain a button but have an outline when it is focused. The outline should in this case probably look like the outline of the buttons at the top of the app.
    the language of the message that is left when clicking the button is in the language of the Tracim UI. Which is fine for now, but should we have a concept of "the language of a workspace" that would be used for this message? I can very well see a workspace used by people speaking different languages, where the working language is common but users can have their preferences regarding which language they use for the UI personally and this shouldn't impact anything other than the UI.

Invoking feedback from @celiamgtt for these two points.

**Comment by celiamgtt** [comment]
Yes it should be a link.
For the message, it could be disturbing for the users to not control the message sent.

**Comment by raphj** [comment]
I'll open an issue

**Comment by raphj** [comment]
After discussion with Giulia, I am ok with a button that acts like a link (like the one we can find on GitHub, "assign to me").
The button should have an outline on focus, and should not become bold. This will avoid the need of calling `preventDefault()`.

**Comment by raphj** [comment]
tested on branch.

**Comment by PhilippeAccorsi** [comment]
Verified.
