### ISSUE TITLE
Refactor frontend update with new real time events feature

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2850]
### TLM implementation DONE
- Account.jsx
- AdminAccount.jsx
- Dashboard.jsx
- Header.jsx
- Home.jsx
- Login.jsx (entry point of Tracim, must connect to SSE)
- ReduxTlmDispatcher.jsx (new component)
- Sidebar.jsx (workspace.modified, workspace_role...)
- SearchResult.jsx
- Tracim.jsx
- WorkspaceContent.jsx

### new unit tests
- reducer/currentWorkspace.js
- TLM for Dashboard
- reducer/user.js
- internal functions for Account
- frontend_lib/test/helper.spec.js (add serialize test)
- internal functions for Header
- internal functions for SearchResult

## Feature description

EDIT: this issue will handle the folder frontend/ only

Example with the save of the new comment in a content:
Currently: When saving a comment, after the api has returned 200, the front will reload the list of comments.
Expected: When saving a comment, after the api has returned 200, the front do nothing. And the backend will send a message through the real time feature that will tell the app to load the given comment. The app will then display it

Do this process for:
- new comment
- new version of content (revision)
- new content in a workspace
- new workspace
- role change in a workspace

**Actually, all data modified on server must be updated in the user interface after the TLM message is received.**

Frontend must have only one way for updating data shown on the interface.

The general behavior should/must be the following one:

- on first load / first view, get data from the API
- then all refresh of the data shown on the user interface should be triggered by TLM reception

## Impacted components

- frontend
- frontend_lib

NOTE: apps will be handled in specific issues

## Extra information

~~This feature is not the priority, we might choose to implement this incrementally~~
This feature is the base for switching to live update. It must be fully released for V3.0.0

## Prerequisite 
https://github.com/tracim/tracim/issues/2842

**Comment by inkhey** [comment]
@Skylsmoi Before refactoring this, we do need some clarification about a potential "fallback" mode of tracim without real time message. If we do expect such fallback, it may be better do not delete the old update mecanism code yet.

**Comment by lebouquetin** [comment]
@Skylsmoi @inkhey did you discuss about a fallback? This is a major point to know which technology we'll use for live messaging.

The fallback should not be an implementation of something very different - I mean the fallback should be very localized in code.

To be discussed in priority

@Skylsmoi the refactor about update from TLM instead of API request result must not be progressive. I changed the extra information. We can talk about it if you need it.

**Comment by lebouquetin** [comment]
@inkhey why did you add the `unclear` label?

**Comment by Skylsmoi** [comment]
@lebouquetin @inkhey Indeed, we might need to talk about this because I'm a bit confused about this right now

**Comment by Skylsmoi** [comment]
We wont have any fallback.
Everything must work using live messages.

**Comment by Skylsmoi** [comment]
I have created a first PR that implements TLM for the component frontend/src/container/Dashboard.jsx
https://github.com/tracim/tracim/pull/3074

**Comment by Skylsmoi** [comment]
this PR includes unit tests for Dashboard TLM handlers and the unit tests for the reducer currentWorkspace

**Comment by Skylsmoi** [comment]
I worked on the Dashboard page (Dashboard.jsx)

Everything works but a small detail: I can't update the read status for the recent activity list when the user "read" a document.
I don't have any TLM for that.

To reproduce:
- have 2 users in a workspace (user1 and user2)
- create a content with user2
- go to dashboard with user1
- open the content wither user1 in a different tab
- content stays in bold in recent activity of the first tab

**Comment by Skylsmoi** [comment]
Another related issue (with above) is the button "mark all as read".

When clicking on it, a PUT request is sent to the backend to put all content as read.
And, ideally, the backend should sent a TLM for each content marked as read, and front should update on each TLM.

But there is no TLM for read status.

**Comment by Skylsmoi** [comment]
I just realized I forgot to handle the connection to the TLM from the Login component

**Comment by Skylsmoi** [comment]
Added branch to handle Login.jsx (feature/2850__handle_TLM_connection_at_login)

**Comment by Skylsmoi** [comment]
this branch adds a new reducer to share the TLM Manager class

**Comment by metzgegu** [comment]
#3140 PR implements TLM for the component frontend/src/container/WorkspaceContent.jsx

**Comment by gbonaspetti** [comment]
#3150 PR implements TLM for the component frontend/src/container/Account.jsx

**Comment by gbonaspetti** [comment]
#3158 PR implements TLM for the component frontend/src/container/AdminAccount.jsx

**Comment by inkhey** [comment]
verified on branch

**Comment by gbonaspetti** [comment]
#3164 PR implements TLM for the component frontend/src/container/Header.jsx
#3166 PR implements TLM for the component frontend/src/container/Home.jsx
#3173 PR implements TLM for the component frontend/src/container/SearchResult.jsx
