### ISSUE TITLE
read status value is updated all the time when opening content (also if content is not unread)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2870]
## Bug description & symptom

When you open content, frontent send PUT request for read status, also for previously read content. With file with many revision, this request take 4sec and other request can't start before this resques is finished.

## Diagnostic

*Optional - explain what has been found and what is not yet clear. If unknown, write "unknown".*

## Expected

- [ ] not send not necessary request about read status when opening content.

## How to reproduce

- make sure you have one content with status read and many revision
- open dev tools
- open your content
=> you can see how many time is necessary to add content read on all revision for content previously read

## Impacted components

*"unknown"*

## Extra information

**Comment by Skylsmoi** [comment]
The PUT read status request now doesn't block the page load and the  endpoint is now faster.
Closing the issue
