### ISSUE TITLE
can apache handle well opened connections ?

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2875]
## Problem

As we want to integrate sse/websocket/long polling mecanism in tracim, we need to be sure our webserver (apache) can handle them well.

## Context

we discovered than on old apache version, apache poor performance when dealing with long polling :
https://stackoverflow.com/questions/14157515/will-apache-2s-mod-proxy-wait-and-occupy-a-worker-when-long-polling
as he used one thread per long polling

After some search, we discovered than apache 2.4 add a new mecanism, the MPM event which is the concurrent model strategy used automatically with modern unix server:

- https://www.datadoghq.com/blog/monitoring-apache-web-server-performance/ (this link contain a good explanation about different mpm mecanism)
- https://httpd.apache.org/docs/current/mod/event.html (event documentation)

The "event" MPM is made to optimise stay alive http connection.

About the specific websocket case, it seems that in current stable apache (2.4), websocket use one thread per connection.

http://apache-http-server.18135.x6.nabble.com/Asynchronous-HTTP-proxy-td5051964.html#a5052022

> 
> In trunk / 2.5.0 mod_proxy_wstunnel has some async support so idle
> websocket connections don't tie up a thread.  This only helps if your
> websockets traffic is proxied.
> 
> Event only offloads some very specific things, it doesn't cause this
> kind of multiplexing for most of request processing (for example while
> a slow CGI is running or while mod_proxy_http is waiting for the first
> byte or a subsequent byte)
> 
> Event does help a lot with keepalive and write completion (slow
> reading clients) and connection shutdown tieing up threads.
>

**Comment by grignards** [comment]
The one OS thread/websocket could be a problem if many clients are using a Tracim instance at the same time. But the "many" here probably means several thousands. The first constraint here should be the available RAM as one thread needs a stack (which can take up to some Mbytes) as the websockets are not CPU-bounded (they use most of their time waiting data).

**Comment by Skylsmoi** [comment]
persistent connection now exists with the endpoint /api/users/1/live_messages and is a SSE.
Closing the issue
