### ISSUE TITLE
Online document edition reload during usage

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#2878]
## Bug description & symptom

When editing a text document with the "online editing" feature and copy-pasting multiple cells in a Writer table, the document reloads and my changes are lost.

## Diagnostic

unknown

## Expected

no reload

## Context and version information

*Optional - describe the environment which reveals the bug:*

Firefox 68.6.0esr (64 bits), Debian.

- LOOLWSD 4.0.5 (git hash: 1e4154c)
- LOKit Collabora Office 6.0-29 (git hash: 9f66d95)

## How to reproduce

Select two columns, CTRL+C. Select two columns, CTRL+V. Again, again ... like in video:

![collabora](https://user-images.githubusercontent.com/1104637/79431721-1a075c00-7fcb-11ea-90ef-81cc155afd2d.gif)

related document: 
[Sevajol_Bastien_13042020.zip](https://github.com/tracim/tracim/files/4485788/Sevajol_Bastien_13042020.zip)

edit: philippe 10h44

**Comment by Skylsmoi** [comment]
On the video, we can see a quick appearance of the tooltip "Bastien S a quitté"
Which might indicate that a "quit" shortcut has been typed

**Comment by PhilippeAccorsi** [comment]
This bug appear on *.odt document. No problem exist on *.ods
I have seen also something not working about adding table in *.odt document. Its just possible to add table from small icon, from menu it is not working.

**Comment by PhilippeAccorsi** [comment]
We can see also at end of video a small flash message in top left about "Bastien a quitter" when screen is reloaded.

**Comment by Skylsmoi** [comment]
issue also reproduced on demo.tracim with is in version 2.6.2

**Comment by Skylsmoi** [comment]
To reproduce, you actually only need to:
- create a new text collaborative document
- insert an array of 3x3
- write something on tile 0x0 and 0x1
- copy these 2 tiles like in the video in the issue description (hard to explain, just do exactly has it is shown)
- past these 2 tiles like in the video in the issue description (same thing)
- the document reloads itself

**Comment by PhilippeAccorsi** [comment]
I have edited issue with collabora version we used.

**Comment by PhilippeAccorsi** [comment]
answer from collabora support about this issue
~~~
An update on the Insert Table dialog, it is going to be added in the next update, 4.2.4, planned to be released in a couple of weeks.
~~~
