### ISSUE TITLE
Frontend spec: Notification, mention and todo architecture

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2881]
## Feature description

Architecture spec for Tracim v3, frontend part

## Context

There is a big refactor which will allow real-time notifications and multiple notification channels (websocket, email, maybe instant messaging...)

Related to backend spec: https://github.com/tracim/tracim/issues/2845

**Comment by Skylsmoi** [comment]
[Web sequence diagram for connection and creating a new comment on an existing content](http://www.plantuml.com/plantuml/uml/bLJVJzim47xFNt7A2w11KqgdIPN2W8t10nD8OtkjZ7rjlIPsP3jq4-9_dtrDsjGBR3mrzTrtzzrtFywiOyRLPP4uwGg4BqOhXqg0hP3BcUJCIQrWfWqOP0KuMIBW8oe7bT4ShKqOTzxwtQ99AXzBSbanvUW1j15eu7YuOw4SZUbartHl69VbPOZ_bIastuGOx_fTCBxS11ycUGwVj5B8YMoU9o7vqUawqGIoMcQ5dakLqClHAS4dS7Lvtx65nos6LLN3fWMr5gDh9zMSD24aL9vewnKoTrD6L58icInIU0TfnQnT-HhIYDNTxJTFYrKxl5eZNw3_fI0-HXiYuZuQ3Y7LIyfI-_HJfvUeqaHfXr3WBFXitq5QKBW2feJ_30O1JeEkl8brkiut2lVKsgCibV0uodpMTf2YOkRee93MWPu1US7Cw184S-o1MNofgdGNmopyj5gb4Ikxq2jGTVc09lZMoY0J3KGgMFX_3yoymjjfeL_c6wnlf4kGDx4bH8SiDL0_UXz27_RjomIkqM3e9Aqsk0Msg-hZKGsEKDFr6akrxN5BgYyi3SGT6YjzNELettw5TTi_IFxstsYMqQ1rP-0ZJLs-7K0IhZ_fHiNU5AtKpjIOq14mo6Wt6N1Tbg6yFDyv7ETLTUtAuhFcTOcRA_H-64iB4pfWxHO8pHSU1joR0cmy2hhvrLlQYd64un6jZ_jTOIUtL45zKhQG2gDJm0lf5Kf_i48AvZ0DtR7eeooaRKFqdOPsFZVPRNOyoXfcDXk7RmBRtUbbGdIP_MDiuybNQ9X3EXJTyNcjTsb8qRawIVWFEJmbG4fDOAyRweZ8XT_GHTmxJ62hy5IAYLSvl3MLqikuUI7WskVav4Fod0GTG-9Nv-RgvlRY_6Ogf4_X-8ASzWF9WsJD8HwNjXtHimybciz1Nx38lG_FQ-lqckOrKw90in_ZkbVgBLEGaIG16YMEpjGJWJio7e9Xgsdpwfir60psdjF_gKOgYyPrfwtTWHWT7K1SzOBEK8cwBFu0)

___

[Web sequence diagram for a user editing a content while another user has it opened](http://www.plantuml.com/plantuml/uml/hLEnRjim4Dtv5GSjJW6xiXMdWm47IT0q6LAqWzrLOCbpH5WY1PAoKGJvzv8ohKXWuZPe5q7IlVVkyTxnobYgRLELPBc4jK4Do8K52an9YzB2lX0b0fNA5gxOU4H13JYCgb4YX-MIK6QLRjczrupKJbamKLDf3z9AS_USJQDATYpD1gKlsfa8fVCXQwKf4zNjpbdyIYLzxDJFBmQuwxg-jrNvMR6cmaviFetxv1kbyxwPYpzrZ1adUqVmJyC6DvHjkn5DYKTEBWyZM00hXQicFsWfEBMOW5LWK7AW874FEzH6A0bg0owdBhnv1dkbjwQc366MaLPjSjbsMi3tzGfeBT9TbdOeaywoj72k9ppOJkSPyOIEjgwz0t0F-fCQ3CMZqMmwXKHjao7d4ILgp_9cRJl97Fqe0omUhYCblaL2f7Ay4ZUM-6zOmXC1iBzgNC2eBpK9fvuW5zt7YC3B27B15suCOm8GokqVTy1ducVfEn6cqHaz6NTiEeAys8zGlLJl7hxTN3_aN3XxbXKjwCpJFXoZ6kwGvnnp-HXOVT8G_IgTDSQgWvrxAdc9-YpYTR7TtQuWVNL5mlnCjnrngsuL87aQZdiCckxpyC-b6Dx01uTyz9p4XlnGdQGfrBw_y6De3jjubA2IWnKLba8Y2Lb6zvkSIiwbCuIVpYcqUFEk7uBioxy9VL-uVojvCl28y4_HHsh_QGbYaq7zdVjmXP8tLVaR)

**Comment by Skylsmoi** [comment]
@lebouquetin mentioning you to check the spec please

**Comment by Skylsmoi** [comment]
My draft spec for new tracim_event naming.
This spec was originally aimed at frontend customEvent but it can be the same for tracim_event.

syntax: `{event_type}-{entity}-{action}[-{detail}]`
Where:
- **event_type** can be: tracim_event
  - and specific for customEvent: system, frontend, app
- **entity** can be: content, comment, folder, workspace, role, publicShare, publicUpload, notification, mention, todo
  - possibly add htmldocument, file, thread
    - not sure if required yet
- **action** can be: create, edit, delete, archive, move, enabled, disabled
- **detail**: not specified, can what is required for a given tracim_event (see examples of edit

Examples:
- new content: tracim_event-content-create
- edit content title: tracim_event-content-edit-title
- edit content's content (aka new version): tracim_event-content-edit-content
- new comment: tracim_event-comment-create
- new workspace: tracim_event-workspace-create
- new role (aka member invited to workspace): tracim_event-role-create

**Comment by lebouquetin** [comment]
@Skylsmoi I think we need a table for explaining all events structure. The naming we already use elsewhere is based on `.` as separator, eg `comment.created`

**Comment by Skylsmoi** [comment]
I have updated the comment with sequence diagram link with an updated version for the first one only.
second one is outdated

**Comment by raphj** [comment]
Closing as this seems outdated.
