### ISSUE TITLE
Feat: Documentation about notification

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2883]
## Feature description

Add end user documentation about mentions and notifications in https://doc.tracim.fr.

## Done

@raphj: I mentioned the mentions in sub sections 5.X, added 5.10 and 5.11 and mentioned the notification wall in 7.
_____
2020-10-01 - Moving the requirement to update the admin documentation in #2912.

**Comment by raphj** [comment]
Can we define a list of precise points to document about the mentions in this ticket?

**Comment by raphj** [comment]
I am ready for you to review those edits :-)

**Comment by PhilippeAccorsi** [comment]
Missing:
- `Bouton Notification` in `Ce bandeau est composé des élements suivant :`

**Comment by PhilippeAccorsi** [comment]
We speak about `Espace partagé` and not `un espace de partage`, i think its better for user to seen `un espace partagé` in title of 5.10

**Comment by raphj** [comment]
Fixed the missing entry, thanks @PhilippeAccorsi 

All right, I'll change « espace de partage » for « Espace partagé », but note that I used this phrase because it was present in the title of other sections. i'll update them as well.

**Comment by PhilippeAccorsi** [comment]
Ne faudrait-il pas dire directement que l'on parle des contenu de type fichier ?

`dans un commentaire attaché à un document ou un fichier,` Il ne me semble pas dans la documentation que l'on fasse référence à des document qui ne serait ni des fichiers, ni des discussion, ni des documents html (à voir comment tourner cette phrase).

> Fixed the missing entry, thanks @PhilippeAccorsi
> 
> All right, I'll change « espace de partage » for « Espace partagé », but note that I used this phrase because it was present in the title of other sections. i'll update them as well.

Ok. maybe we can review directly on same machine to improve modification delay ?

**Comment by PhilippeAccorsi** [comment]
Review done. Thanks for this documentation.

**Comment by PhilippeAccorsi** [comment]
Verified.
