### ISSUE TITLE
Change the icon of status validated and opened

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2885]
## Feature description

With the introduction of the To Do functionality, we will use the fa-square  and fa-check-square  icons for the functionality and need other icons for the statuses of a document.

### current status icons
![current_status_icons](https://user-images.githubusercontent.com/11177014/79850208-db571480-83c3-11ea-8857-63e328144a67.png)

### current propositions
- icon Validated
  - :+1: 
    - will probably be used for social features so no
  - :ok_hand: 
  - :handshake:

**Comment by Skylsmoi** [comment]
@celiamgtt When you know what is the new icon, feel free to update this issue

**Comment by celiamgtt** [comment]
Idea: use a thumb's up icon for the 'verified' status.

![Capture d’écran 2020-04-17 à 14 30 44](https://user-images.githubusercontent.com/50453784/79569586-274e4480-80b8-11ea-9fc7-f88a19d94237.png)

**Comment by lebouquetin** [comment]
@Skylsmoi what is this status about? The issue is not clear. If you think about changing an icon, old one must be included in the issue, and the associated entity should be explicit.

I think you are speaking of the `validated` status of a content... but there is nothing clear in the issue.

Please update it.

**Comment by lebouquetin** [comment]
by the way, the thumb-up will be used *probably* for adding social features... I would suggest `:ok_hand:` - 👌 U+1F44C

**Comment by PhilippeAccorsi** [comment]
Can you add also something about editing Tracim user documentation if you change icon. Its important to have same icon in documentation like we have in Tracim software.

**Comment by Skylsmoi** [comment]
I have updated the description.

If we will use the validated icon for todos, won't we also use the opened icon ?
For todos to do and done

**Comment by Skylsmoi** [comment]
Since this has never been an issue for users, I'm closing the issue
