### ISSUE TITLE
Choose if tracim_event are only related to notification or not

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#2886]
## Terminology
**tracim_event**: backend event related to any change in Tracim
**real time message**: a message from backend through the real time connection

## Current specification
The real time messages are associated to a notification.
This means that any real time messages create a new notification for frontend and triggers the appropriate update of the ui.

## Problem
The backend might want to trigger ui update without creating a new notification.
Even if it only is in some specific cases

## Example
User1 is viewing the dashboard of workspace A
User2 change the role of User3 in workspace A
This will make the member list that User1 is viewing obsolete and in need of a refresh
Backend has to send a real time message to User1
This will create a notification for User1 saying something like "User2 changed the role of User3" and we might not want to create a notification for that.

## Possible solution
Have real time messages not associated to a notification.
And have a specific real time message to create a notification.
So, in the example above, when the backend has to send a real time message to User1, it will send a real time message that only triggers a refresh of the member list

In the context of a new content version, the backend will send 2 real time messages:
- one triggering the refresh of the content
- one triggering the creation of a new notification in header

**Comment by lebouquetin** [comment]
@Skylsmoi first, you must consider that backend does not known anything about frontend. Backend is in charge of managing data/information and to give access to it. The only piece of software having knowledge about user interface and how data is represented to the user is the frontend.

When a user create or update an entity, the backend manage a new event : something happened. The websocket/SSE rôle is to dispatch this event to users who must be informed. The role of the backend is not to trigger something in the user interface, the role of the backend is only to transmit information "there is something new". Then, the frontend is in charge of knowning what to do with it and how to process it.

So I do not see any reason for the backend to distinguish messages and events, I see no reason for the backend to send two messages like what you suggested:

> - one triggering the refresh of the content
> - one triggering the creation of a new notification in header

Taking the decision of refreshing a content is in the responsability of the frontend.

Maybe the wording "notification" we use is wrong and make things not clear. I suggest the following one:

- in backend
    - we manage events (the global history of everything happening on tracim)
    - we build notifications from events (a notification is a message about an event targetting one specific user)
- in frontend
    - we manage tracim_events which represents backend events (for a given user - this is logical as frontend is single-user at execution time)
    - we manage notifications which are entities show on the notification wall (built from tracim_event)
    - tracim_events are dispatched to all applications which know if they must process or ignore tracim_events

Between backend and frontend, the data exchanged through socket would then be named `messages`

So:

- backend send a message to frontend,
- frontend transform this into `tracim_event` (the frontend representation of a message which is the representation of a backend event specialized for the current user)
- the tracim_event is dispatched to all frontend applications:
    - NotificationWall application build a notification entity from the tracim_event (if this is an event to be notified)
    - PersonnalTodo Application build a todo entity from the tracim_event (if the event is about a todo)
    - FileContent application shows a flash message related to the tracim_event to the user if the tracim_event is related to current shown file
    - ...

**Comment by lebouquetin** [comment]
Is this clear to you @Skylsmoi ? Tell me if you see something wrong. Keep in mind that backend does not know of the data must be processed in frontend. For example, you could have a frontend application notifying all events to the user and another frontend notifying only those related to files. Backend should stay the same for both types of client (this is an example)

**Comment by Skylsmoi** [comment]
I'm confused about this because you say tracim_event are frontend events and we did not say that.

Or you mean frontend has to handle the two types (tracim_event and customEvent) separately ?
Meanings frontend receives messages that contains a tracim_event and converts it into a customEvent to be used by frontend apps ?

What I thought was, there are:
- customEvents. Javascript events that rules all the frontend. Communication between apps
- messages. Messages through the real time socket feature (whether it is websocket or sse or ...) that comes from the backend
- tracim_event. The backend events which the frontend doesn't know about. Like the backend doesn't know about customEvents

**Comment by lebouquetin** [comment]
I think this issue is deprecated as we defined architecture schemas together. @Skylsmoi you agree with me?

**Comment by Skylsmoi** [comment]
Yes it is.
We have decided that a tracim event is related to anything that is changing in the backend.
And it is the frontend that knows if a tracim event (which is a tracim live message at the time it arrives to the frontend) must be added as a notification (in header and notification wall).

@lebouquetin If you agree with the above, you can close the issue

**Comment by Skylsmoi** [comment]
It is now implemented, I'm closing this issue
