### ISSUE TITLE
Bug: Clicking on View Online for a picture opens it with the online office suite

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#2890]
## Bug description & symptom

When opening an image (for instance, a PNG), clicking on View Online opens the image with the online office suite. While useful, this feels conter-intuitive. I expected the picture to open fullscreen.
Opening fullscreen is instead achieved by clicking on the picture.

There are several points to handle:

- the cursor on the picture is indeed the pointer showing the user that something will happen when they will click. But there isn't any tool-tip indicating that the action will trigger a full-screen display.
- "View online" is vague: anything done on Tracim is online. A better description should probably be found for this action. Naming this button "Open with Collabora" or "Open with Libreoffice Online" would be problematic since other online office suit could be used (CODE) or supported in the future. "Open with the online office suite" is a bit long.
- Someone looking for opening an image full-screen but who does not think of clicking the image is lost. Maybe a "Full-screen" button could be added somewhere in the UI?

## Screenshots

![image](https://user-images.githubusercontent.com/3817365/79723378-ef2c4900-82e5-11ea-9cda-cc28deb3a171.png)

## Impacted components

- *frontend*
- file app

**Comment by Skylsmoi** [comment]
The "View online" button is now behind the option dropdown so this is now less of an issue because it is less counter intuitive

Closing the issue
