### ISSUE TITLE
Using file-depot for storage breaks mimetype detection 

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#291]
Currently, if an EPS file is uploaded with tracim (and stored in depot) the mimetype is not detected correctly.

Example:
```
>>> import mimetypes
>>> mimetypes.guess_type('/home/damien/a_bouger_sur_tracim/ALGOOsas/05_DIVERS/FAVICON/EPS/FAVICON3.eps')
('application/postscript', None)
>>> mimetypes.guess_type('/home/damien/proj/tracim/tracim/depot/4e9d2d36-73b3-11e7-8c1e-b86b23543bb8/file')
(None, None)
```

Expected : on upload, setup the mimetype explicitly in file-depot?

**Comment by algooapy** [comment]
see this [preview-generator commit](https://github.com/algoo/preview-generator/commit/c86cce850afe42dc6a965fee38c73cbefdd1067c)
