### ISSUE TITLE
Feat: Update redux for username feature

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#2917]
## Feature description

Add username in the `user` object of the redux state.

## Context

Linked to #2829 

## Impacted components
- frontend

**Comment by gbonaspetti** [comment]
For this issue a `username` has been added on `user` at Redux . To make the difference clear, the functions linked to `public_name` that used the USER_NAME notation have been updated to USER_PUBLIC_NAME and new `username` fuctions have been added as USER_USERNAME.

**Comment by metzgegu** [comment]
Verified on branch (wait merge to close).
