### ISSUE TITLE
Bug: Cannot install frontend dependencies with yarn ≠ 1.21

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#2918]
## Bug description & symptom

Cannot install_frontend_dependencies with yarn version 1.19

## Screenshots

![Screenshot from 2020-04-24 16-33-00](https://user-images.githubusercontent.com/35422692/80225254-1ae36200-864b-11ea-80ad-7c9bdad88a49.png)

## Fix

The fix consists in using command `yarn policies set-version berry` instead of `yarn set version berry`, and checking that Yarn is not already version 2.

The fix supports installing and setting up the frontend dependencies using any version of Yarn but we still only use Yarn 2 after installation.

For the record and since the migration to Yarn, .yarnrc / .yarnrc.yml are not commited and are in .gitigore. If we commited these files, ./install_frontend_dependencies would fail because yarn would try to execute a non existent file in .yarn. These files therefore need to be created at install time.

**Comment by raphj** [comment]
The following command only seems to work with yarn 1.22.

    yarn set version berry

The following command seems to work with older versions as well as yarn 1.22:

    yarn policies set-version berry 

I am going to open a pull request with a fix.

The fix consists in replacing the former by the latter in `install_frontend_dependencies.sh` (line 166).
