### ISSUE TITLE
Broken image on search result page

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#292]
![selection_043](https://user-images.githubusercontent.com/1104637/28771270-7b85e564-75e2-11e7-976d-3f451a20aa6e.png)

A `img` source image url is invalid on the search results page.

**Comment by Skylsmoi** [comment]
this should not use an `<img />` tag, tracim uses font-awesome for icons  
todo : replace the `<img />` tag with a `<i class='fa ...'/>` tag

**Comment by algooapy** [comment]
Not reproduced,
`tracim/tracim/templates/search/display.mak` matches @Skylsmoi comment recommendations:
Closing the issue.

**Comment by xandercagexxx** [comment]
Verified.
