### ISSUE TITLE
Bug: Mismatch parameters default value in config don't match with code value + others defaut value issue

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2920]
## Bug description & symptom

1. Some parameters default value mismatch with example, for example collaborative document edition
value for : 
```
collaborative_document_edition.collabora.base_url ,
collaborative_document_edition.file_template_dir,
collaborative_document_edition.software
```
in config file don't match with used value in python code.

2. code default value for session_lock is incorrect.
3. ";" is sometime used for non default value
4. debug parameters should be in default section instead of web app one, as this is a tracim parameters, not a pyramid specific one.
5. This issue should contain also need to implement the first solution (1) for issue https://github.com/tracim/tracim/issues/2925 about "explicit default value for basic_setup parameters too".

## Expected

- (for 1) : Values for those parameters should be the same in code and in config file, and example should be provided if needed
- Others issues (2,3,4,5) are fixed to have clear config file.

## Implemented solution:
see https://github.com/tracim/tracim/pull/2921
- ";" always mean default value
- clarification in documentation about few points.
- fix wrong default value (in code only, not in config file) for session_lock. 
- fix issue related to 18next-conv version.

**Comment by PhilippeAccorsi** [comment]
- [ ] Manque
~~~
website.title
website.base_url
listen
~~~
- [ ] Pour caldav, il n'y a pas de paramètre par défaut dans le code ?

Ne devrait-on pas avoir 
caldav.radicale.storage.filesystem_folder

- [ ] Manque

advanced_setup.session_data_dir => lié à session.data_dir
advanced_setup.session_lock_dir => session.lock_dir

L'ordre des paramètre (ordre paramètre par défaut et exemple) ne correspond pas à ce qui est appliqué dans le reste du fichier. On met en premier le paramètre par défaut puis l'exemple ou la ligne utilisé.


- [ ] Modification

Je pense qu'il faut enlever se paramètre basic_setup.file_template_dir = %(here)s/tracim_backend/templates/open_documents

- [ ] Manque

api.key
session.secret

- [ ] Je pense que l'on peut modifier ça :
~~~
## Preview dimensions can be set as restricted. If set as restricted, access
## endpoint to get any other preview dimensions than allowed_dims will
## return error
; preview.jpg.restricted_dims = False
# preview.jpg.restricted_dims = True
~~~
On pourrait plutôt indiquer => If set as True, access .......
Et on enlève la ligne d'exemple. (mêm type de présentation que sur le choix des langue en fait)

- [ ] paramètre à éclaircir ici (valeur par défaut dans tracim ou valur lu directement par pyramid)

~~~
### pyramid_beaker parameters ###
~~~
Le paramètre session.reissue_time est commenté par exemple mais pas session.cookie_on_exception

- [ ] Pas clair (ou peut être que si ^^)
~~~
api.base_url
~~~
- [ ] Modification

mettre un `:` ici "Default profile of created user, valid values are users, trusted-users, administrators"
Peut être écrire les valeurs de la sorte 'users','trusted-users','administrators'

- [ ] A modifier
~~~
## active or disable filter on known user, if activate user cannot see at all informations about
## member with no common workspace. if false, it can access to these informations.
## This is used by search mechanism for invitation of user in workspace.
## default value to true.
; known_members.filter = True
~~~
Je propose de mettre un (True) après activate sur la première ligne.
Je propose aussi de supprimer la ligne "default value to true."

- [ ] erreur

Ceci semble être un exemple et non pas la valeur par défaut "; frontend.dist_folder_path = /home/user/tracim/frontend/dist"

- [ ] Manque

Il faudrait un exemple ici je pense "; frontend.cache_token ="

- [ ] reformuler
~~~
check for color.json file in Tracim, check by default in Tracim parent
# dir of backend
~~~
Je pense qu'il est plus clair décrire "directory of backend"

- [ ] Reformuler
~~~
## you can enable or disable if invited user to shared space will be notified
## on this shared space by default (default: True).
## NB: new users will not being notified until they login to Tracim a first time
; email.notification.enabled_on_invitation = True
~~~
Je pense qu'il n'y a pas besoin de dire default à True, mais d'indiquer que les valeurs doit être True ou False

- [ ] manque
~~~
# active implicit ssl if you are using implicit smtp with encryption port like 465
# by default, tracim will try to use explicit smtp encryption using starttls, and unencrypted
# connection as fallback.
; email.notification.smtp.use_implicit_ssl = False
~~~
Il manque l'explication true ou false

- [ ] Reformuler
~~~
Note: items between { and } are variable names
~~~
Le between sous-entend déjà "entre {}" docn pas besoin du "and"

- [ ] Pas clair

~~~
## valid variable is 'user_id' for 'from' header:
; email.notification.from.email =
## valid variable is 'content_id' for 'reply_to' header:
; email.notification.reply_to.email =
## valid variable is 'content_id' for 'references' header:
; email.notification.references.email =

# example of recommanded pattern (for 'from' header):
# email.notification.from.email = noreply+{user_id}@domainname.tld

# tagging reply_to header of email with content_id is needed for working
# email_reply feature
# example of recommanded pattern (for 'reply_to' header):
# email.notification.reply_to.email = reply+{content_id}@domainname.tld
# email.notification.reply_to.email = {content_id}@reply.domainname.tld
# email.notification.reply_to.email = reply+cid{content_id}@domainname.tld

# tagging reference header of email with content_id is nice to have
# all modification to a same content in a same email client thread
# Note: reference doesn't need to be an existing email account but should
# be a email like string.
# example of recommanded pattern (for 'references' header):
# email.notification.references.email = thread+{content_id}@domainname.tld
~~~

Ce bloque n'est pas clair. Habituellement les exemple font suite au paramètre par défaut. Là on a les 3 paramètre par défaut puis les block pour les exemples des différents paramètre. Il serait plus clair d'avoir les block d'exemple/explication à la suite des paramètre par défaut (pour éviter toute erreur ou ambiguité).

- [ ] Manque peut-être
~~~
; email.reply.imap.folder = INBOX
; email.reply.imap.use_ssl = True
~~~
Peut-être ajouter les paramètre dan les exemples ou une phrase sur les choix possible (s'il y a des contrainte dans le code par exemple. Les choix autre que INBOX sont-il limité par le code ?)

- [ ] Manque
~~~
### Parsing ###
; email.reply.use_html_parsing = True
; email.reply.use_txt_parsing = True
~~~
Il manque les choix possible

- [ ] Manque (peut-être)

un exemple pour "; email.reply.lockfile_path = %(here)s/email_fetcher.lock"

- [ ] Manque
~~~
webdav.listen = localhost:3030
~~~
Il n'y a pas de valeur par défaut dans le code ?

- [ ] a reformuler
~~~
### Webdav HTML dir browser ###
## Render HTML listing for GET requests on collections (default: True)
; webdav.dir_browser.enabled = True
## Raw HTML code, appended as footer, if not set, let Tracim created his own
## footer.
; webav.dir_browser.footer =
# webdav.dir_browser.footer = Just another footer
~~~
On peut remplacer "(default: True)" par les choix possible et dire que c'est un exemple pour "juste another footer"

- [ ] Manque
~~~
caldav.radicale_proxy.base_url = http://localhost:5232
~~~
Pas de valeur par défaut dans le code de tracim ?

- [ ] Manque
~~~
# main index alias use to search/index content in elasticsearch
; search.elasticsearch.index_alias =
~~~
Il manque une infor pour dire qu'une valeur est obligatoire pour utiliser elastic search

- [ ] Manque
~~~
# for search (default as false)
; search.elasticsearch.use_ingest = False
~~~
Il faut les choix possible plutôt que la valeur par défaut)

- [ ] Manque
~~~
# example with collabora:
~~~
Il faudrait plutôt dire: "example tu use CollaboraOnline or LibreofficeOnline:"

- [ ] Je suis pas sur qu'il y a des modifications/choixi à partir de cette partie:
~~~
##############################
# SPECIFIC CONFIG FOR WEBAPP #
##############################
~~~

**Comment by PhilippeAccorsi** [comment]
Verified on branch by @inkhey
