### ISSUE TITLE
Bug: Label in FR after having switched to EN

### ISSUE THREAD

**Issue by YannickBiet** [tracim/tracim#2923]
## Bug description & symptom

After having switched to English language, one button is still displayed in FR "modifier en ligne"

## Expected

The button label should appear in English : Edit online

## Screenshots

<img width="1420" alt="Capture d’écran 2020-04-26 à 15 04 01" src="https://user-images.githubusercontent.com/930391/80308458-7cccd480-87cf-11ea-8089-862cc98d8225.png">

## Impacted components

- *frontend*
- language file ?

**Comment by Skylsmoi** [comment]
Thank you for reporting this issue
I could reproduce it, we will look at it

**Comment by inkhey** [comment]
Unable to reproduce the issue in version 4.0 : this issue is already fixed.
