### ISSUE TITLE
Feat: allow to login with username

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#2927]
## Feature description

In login component :
- [x] Update placeholder, input icon and flash messages with the errors with username
- [x] Check if autocomplete of login still works with username

## Context

Linked to #2829

## Impacted components

- *frontend*

## Extra information

Translations :
- Invalid email or username: 
    - fr: "Adresse email ou identifiant invalide"
    - pt: "E-mail ou identificador inválido"
- Email address or username: 
    - fr: "Adresse email ou identifiant"
    - pt: "E-mail ou identificador"
- Invalid credentials: 
    - fr: "Identifiants invalide"
    - pt: "Credenciais inválidas"

**Comment by gbonaspetti** [comment]
Verified on branch (wait merge to close).

**Comment by metzgegu** [comment]
In order to login with `username` the login endpoint need to have a `username` param, so the frontend need to check the type of login to add the correct param.
To do that the frontend use an existing function in `frontend_lib`
