### ISSUE TITLE
Feat: Adapt the function of adding members with username

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#2930]
## Feature description

Change the on Add a member (dashboard and advanced dashboard):
- [x] the text to "Enter the username, email or full name of the user"
- [x] the placeholder to "Search user..."
- [x] the function itself to search by username as well

## Context

Linked to #2829 

## Extra information

Translations:
- Enter the username, email or full name of the user 
French: _Entrez l'identifiant, l'adresse email ou le nom complet de l'utilisateur_
Portuguese: _Introduza o identificador, e-mail ou nome completo do utilizador_
 - Search user...
French: _Rechercher un utilisateur..._
Portuguese: _Pesquisar utilizador..._

**Comment by gbonaspetti** [comment]
To resolve this issue all related texts have been updated to include the username or be more comprehensive (in the case of texts that could not be too big). The term nameOrEmail has also been maintained for personalData for the same purpose in the code. And the functions have been adapted to receive and send the username to the API backend.
It is now possible to search for a user by his username (the search can be done with or without @).

**Comment by metzgegu** [comment]
Verified on branch (wait merge to close).
