### ISSUE TITLE
Feat: Custom user properties

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2935]
## Feature description

Add properties to a user. The list of properties will be defined through configuration. The properties will then be accessible/editable through the HTTP API.
Internal document available **[here](https://algoo.tracim.fr/ui/workspaces/49/contents/html-document/16718?folder_open=9701,13842)**.

## Context

Custom properties for users can be used for several use-cases: user profile, private properties for administrators (eg mon.tracim),…

## Additional feature details

- [x] Property label must be translatable in json_schema : with these keys: "description, title, enumNames" 
- [X] Property label must be translatable in ui_schema: with theses keys: "title", "description", "placeholder", "help" + all "ui:*" version.
-  ~~Property values (enum) must be translatable~~ use enumNames/title instead

## Config file:
- [x] System administrator will define a JSON SCHEMA file to specify user properties.
- [x] System adminstrator will define a UISchema field to specify Ui properties  (see see https://react-jsonschema-form.readthedocs.io/en/latest/quickstart/#form-uischema)
- [x] System administrator will provide a dir containing translations files, one file per lang.

### Tracim Config:
- [x] Add a configuration parameter `user.custom_properties.json_schema_file_path` which indicates the path to a JSON schema file. existence, readability and json validity will be verify at startup.
- [x] Add a configuration parameter `user.custom_properties.ui_schema_file_path` which indicates the path to a  UI schema file.existence, readability and json validity will be verify at startup.
- [x] Add a configuration parameter `user.custom_properties.translations_dir_path` which indicates the path to the translations of the strings found in the json schema file. The existence and readability of the directory will be verified at startup.
  - [x] Translations files will be loaded in config at startup, this mean all .json file in dir will be parsed by backend and should be json valid (i18next valid ?). 
  - [x] The translation files will follow the [i18next format v3](https://www.i18next.com/misc/json-format). For this first version we'll only consider simple `(key,value)` pairs.
  - [x] Each file will be name `<language code>.json`, e.g `fr.json` for a french translation.

# Endpoints:
- [x]  Add an endpoint to get the schema: `GET /api/system/user-custom-properties-schema`. Accessible by all connected users. Will return the schema file with the following transformations:
  - [x] use current user lang and translations file to replace values.
  - permission filtering : https://github.com/tracim/tracim/issues/4004

- [x] Add an endpoint to get the ui schema: `GET /api/system/user-custom-properties-ui-schema`. Accessible by all connected users. Will return the Uischema directly. some transformations may be needed later:
  - [x] use current user lang and translations file to replace values.
  - permission filtering : https://github.com/tracim/tracim/issues/4004

- [X] Add an endpoint to get user properties. `GET /api/users/{user_id:\d+}/custom-properties`.  Will return an object with properties depending on the defined schema. 
    - [x] Accessible by users who "know" the given user id.Known users can either be all users (when `known_users.filter=False`) or users who are member of at least one space in common with the user in the url. need known_user filter: https://github.com/tracim/tracim/issues/4027
  - permission filtering may be needed later : https://github.com/tracim/tracim/issues/4004

- [X] Add an endpoint to set user properties. `PUT /api/users/{user_id:\d+}/custom-properties`. 
    - [x] Endpoint should be done in order to work like a put for frontend.
    - ~~Accessible by users who "know" the given user id.Known users can either be all users (when `known_users.filter=False`) or users who are member of at least one space in common with the user in the url. need known_user filter: https://github.com/tracim/tracim/issues/4027~~ Don't make sense until 4004 is fixed.
  - permission filtering may be needed later : https://github.com/tracim/tracim/issues/4004

## Schema file example:

```json
{
  "title": "A registration form",
  "description": "A simple form example.",
  "type": "object",
  "required": [
    "firstName",
    "lastName"
  ],
  "properties": {
    "firstName": {
      "type": "string",
      "title": "First name",
      "default": "Chuck",
    },
    "lastName": {
      "type": "string",
      "title": "Last name"
    },
    "telephone": {
      "type": "string",
      "title": "Telephone",
      "minLength": 10
    }
  }
}
```

### Translation file example:

```json
{
  "First name": "Prénom",
  "Last name": "Nom"
}
```

## Ui file example:

```json
{
  "firstName": {
    "ui:autofocus": true,
    "ui:emptyValue": "",
    "ui:autocomplete": "family-name"
  },
  "lastName": {
    "ui:emptyValue": "",
    "ui:autocomplete": "given-name"
  },
  "age": {
    "ui:widget": "updown",
    "ui:title": "Age of person",
    "ui:description": "(earthian year)"
  },
  "bio": {
    "ui:widget": "textarea"
  },
  "password": {
    "ui:widget": "password",
    "ui:help": "Hint: Make it strong!"
  },
  "date": {
    "ui:widget": "alt-datetime"
  },
  "telephone": {
    "ui:options": {
      "inputType": "tel"
    }
  }
}
```

- [x] provide a user (administrator) documentation about these properties and some simple examples.

## Notes

A JSON field already exist in event table (for the example).

#4004 can be done during the same development.

## Pending questions

* User should be able to hide his entire profile?
* With these new specifications, it seems https://github.com/tracim/tracim/issues/3829 must be updated. @gbonaspetti @grignards you confirm ? (frontend must read schema to permit display/edit of these properties) note: **custom form part/knowledge must be used to do not make wheel again**

## Time Estimation

5 man.day

## Implemented solution
see PR: https://github.com/tracim/tracim/pull/4044/files

```
Add support for custom_user properties.

- add 3 new parameters in config to configure custom_properties: user.custom_properties.json_schema_file_path, user.custom_properties.ui_schema_file_path, user.custom_properties.translations_dir_path.
- add a table user_custom_properties in sql database to store user custom properties + migration schema
- add endpoint to get user custom properties, accessible only to know user: GET /api/users/{user_id:\d+}/custom-properties
- add endpoint to set user custom properties, accessible only to admin/user itself : PUT /api/users/{user_id:\d+}/custom-properties
- add endpoint to get json schema : GET /api/system/user-custom-properties-schema
- add endpoint to get ui schema : GET /api/system/user-custom-properties-ui-schema
- add translations mecanism and filtering return of ui and json schema according to translation
- add simple command line to check.
- add many tests for all theses things.
- add documentation about using user custom properties.

Refs: #2935 
```

**Comment by inkhey** [comment]
I'm not sure how we should deal with this feature to make it generic, should we follow same pattern as user config #3380 ?

**Comment by inkhey** [comment]
Need clarification between the goal of this issue and the profile custom field https://github.com/tracim/tracim/issues/3829
Goal of this issue:
- custom field for user usable in plugin/api

Goal of the profile custom field:
- Allow frontend to known how to deal with field (using jsonschema) ? We do need to be able to handle at least:  date / select / texte / textarea type of field. Frontend need to have also label and description for field (note: i18n ?)
- Allow to deal with different access rule depending on field : 
  - admin-only : read/write for admin only
  -  admin: read for anyone has access to profile + write for admin only
  - standard: read for anyone has access to profile + write for user itself and admin
- Some fields may be mandatory ? (what can it mean ? Does this mean default value for new user ?)
- Others informations (encrypted/unencrypted, etc...) ?

Storage mecanism and migration mecanism need to be clarify.

**Comment by raphj** [comment]
> I'm not sure how we should deal with this feature to make it generic, should we follow same pattern as user config #3380 ?

Yes, I think so.

I suggest we add a "custom user data" free-form JSON field, and we use a `public_profile.` namespace for anything related to the profile.

**Comment by grignards** [comment]
> > I'm not sure how we should deal with this feature to make it generic, should we follow same pattern as user config #3380 ?
> 
> Yes, I think so.
> 
> I suggest we add a "custom user data" free-form JSON field, and we use a `public_profile.` namespace for anything related to the profile.

You won't be able to enforce a naming as the requirement is to create a generic "user information" storage that a Tracim system admin will be able to enforce.

**Comment by buxx** [comment]
Internal document about this feature is [here](https://algoo.tracim.fr/ui/workspaces/49/contents/html-document/16718?folder_open=9701,13842,9701,13842,9701,13842,9701,13842,9701,13842,9701,13842,9701,13842,9701,13842,9701,13842,9701,13842,9701,13842,9701,13842&parent_id=13842).

**Comment by buxx** [comment]
I just edited issue with specifications.

**Comment by inkhey** [comment]
this point : 

>  Add and endpoint to get user properties. GET /api/users/{user_id:\d+}/properties. **Accessible by all connected users**. Will return an object with properties depending on the defined schema.

is not compatible with current access rules.
User information are not public, see this existing comment : https://github.com/tracim/tracim/issues/3829#issuecomment-728942677

**Comment by grignards** [comment]
> this point :
> 
> > Add and endpoint to get user properties. GET /api/users/{user_id:\d+}/properties. **Accessible by all connected users**. Will return an object with properties depending on the defined schema.
> 
> is not compatible with current access rules.
> User information are not public, see this existing comment : [#3829 (comment)](https://github.com/tracim/tracim/issues/3829#issuecomment-728942677)

As long as we provide an option for all users to choose whether their profile is accessible or not I think this is OK. This option isn't described yet.

**Comment by grignards** [comment]
> > this point :
> > > Add and endpoint to get user properties. GET /api/users/{user_id:\d+}/properties. **Accessible by all connected users**. Will return an object with properties depending on the defined schema.
> > 
> > 
> > is not compatible with current access rules.
> > User information are not public, see this existing comment : [#3829 (comment)](https://github.com/tracim/tracim/issues/3829#issuecomment-728942677)
> 
> As long as we provide an option for all users to choose whether their profile is accessible or not I think this is OK (and possibly a configuration to set the default value of this option). This isn't described yet.

**Comment by inkhey** [comment]
> > this point :
> > > Add and endpoint to get user properties. GET /api/users/{user_id:\d+}/properties. **Accessible by all connected users**. Will return an object with properties depending on the defined schema.
> > 
> > 
> > is not compatible with current access rules.
> > User information are not public, see this existing comment : [#3829 (comment)](https://github.com/tracim/tracim/issues/3829#issuecomment-728942677)
> 
> As long as we provide an option for all users to choose whether their profile is accessible (and possibly a configuration parameter to set the default value of the visibility) or not I think this is OK. This isn't described yet.

Not sure we do want in all context allowing user to make their own profile accessible to anyone.
I do suggest that we base the visibility of the endpoint on the same mechanism as known_users, this way we do have something both consistent and configurable depending on context (through known_members.filter parameter or user profile)

**Comment by inkhey** [comment]
2 points:
- We should probably verify jsonschema validity before add it has default.
- Is there any idea how we store this in database. It's seems we do currently need to only store one json schema field. A table with only one element and only one (json) column is strange.

**Comment by Skylsmoi** [comment]
Check if custom forms handles translations.

**Comment by Skylsmoi** [comment]
properties -> custom-properties here, properties for the static ones (public name/...) @grignards Create the issue

**Comment by inkhey** [comment]
parameters `users.` doesn't exist currently but parameters  `user.` exist.
I suggest to rename `users.custom_properties_file_path` to  `user.custom_properties_file_path`

**Comment by PhilippeAccorsi** [comment]
Question: all informations save with the custom properties about user are be correctly deleted when user is deleted from tracimcli command ?

**Comment by inkhey** [comment]
> Question: all informations save with the custom properties about user are be correctly deleted when user is deleted from tracimcli command ?

Yes.

**Comment by PhilippeAccorsi** [comment]
@inkhey something wrong in documentation link visible in setting.mg
~~~
User Custom Properties

It's possible to configure custom properties attached to user per instance, read specific documentation to know more about this feature.
~~~

**Comment by PhilippeAccorsi** [comment]
Done.
