### ISSUE TITLE
Feat: allow to reset password from username 

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#2940]
## Feature description

In resetPassword component:
- [x] Update placeholder, icon
- [x] add a new error screen (such as the screen for notifications by emails not activated) or a flash message with the error
- [x] add a new check to see if the username is linked to a email.

This feature needs the backend to be updated in order to remove email format verification and give info if the username is linked to a email

## Context

Linked to #2829

## Extra information

Translations :
- Unknown email or username: 
    - fr: "Adresse email ou identifiant inconnu"
    - pt: "E-mail ou identificador desconhecido"
- Email address or username: 
    - fr: "Adresse email ou identifiant"
    - pt: "E-mail ou identificador"
- This username is not linked to any email: 
    - fr: "`Ce identifiant n'est lié à aucun e-mail`"
    - pt: "Este identificador não está ligado a nenhum e-mail"

**Comment by metzgegu** [comment]
I think a flash message to tell the user that his username is not linked to any email is better because every warning messages is already using flash message

**Comment by metzgegu** [comment]
In order to complete this feature, a new error code need to be created in backend for the case `This username is not linked to any email`

**Comment by PhilippeAccorsi** [comment]
If email is not mandatory to create user, this flash message `This username is not linked to any email` not give usable information to the user. Because If I not added email or if admin have created my account without email, I don't now what is the solution for me to reset my password.

I think when we show this message, we need to add information about "you need to contact an administrator" or something like that.

**Comment by gbonaspetti** [comment]
> If email is not mandatory to create user, this flash message `This username is not linked to any email` not give usable information to the user. Because If I not added email or if admin have created my account without email, I don't now what is the solution for me to reset my password.
> 
> I think when we show this message, we need to add information about "you need to contact an administrator" or something like that.

Maybe change the message to "This username is not linked to any email, contact an administrator to reset your password."

**Comment by gbonaspetti** [comment]
To solve this issue the texts and placeholders were updated, a check was made to see if the user was putting an email or username and the right data was sent to api.
