### ISSUE TITLE
Feat: Add username field in user personal data

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#2943]
## Feature description

Add username field in admin personal data in order to be able to change it (add a warning to explain  to the user that old mention would be removed)

- [x] Add a username field between User and Email with placeholder: `New @username`
- [x] When the field is selected below it a message with the fa-exclamation-triangle icon appears and the message: Changing your username will not update the mentions using your current username.
- [x] Username is minimal length of 3 characters (sometimes the user will enter @username, sometimes just username, the frontend should handle both cases)
- [x] Add a warning message (flash message) for non-standard or non-unique usernames: allowed chars: azAZ09-_ 
- [x] Add the list of allowed characters when the username field is selected.
- [x] Add a error message when username is not available (non-unique)
- [x] Explicit message explaining when updating the username fails

## Context

Linked to #2829

## Extra information

Translations :
- Username must be at least 3 characters: 
    - fr: "L'identifiant doit faire au moins 3 caractères"
    - pt: "O identificador deve ter pelo menos 3 carateres"
- Username can't contain any whitespace: 
    - fr: "L'identifiant ne doit pas contenir d'espace"
    - pt: "O identificador não pode conter nenhum espaço em branco"
- New @username: 
    - fr: "`Nouveau @identifiant`"
    - pt: "Novo @identificador"
- Changing your username will not update the mentions using your current username: 
    - fr: "Le changement de votre identifiant ne mettra pas à jour les mentions en utilisant votre identifiant actuel"
    - pt: "A alteração do seu identificador não actualizará as menções utilizando o seu identificador actual."
- Your personal data has been changed: 
    - fr: "Vos données personnelles ont été modifiées"
    - pt: "Os seus dados pessoais foram alterados"
- Your username and your name has been changed: 
    - fr: "Votre identifiant et votre nom a été changé"
    - pt: "O seu identificador e o seu nome foi alterado"
- Your username has been changed: 
    - fr: "Votre identifiant a été changé"
    - pt: "O seu identificador foi alterado"
- Error while changing username: 
    - fr: "Erreur lors du changement d'identifiant"
    - pt: "Erro ao alterar o identificador"
- Username and name has been changed: 
    - fr: "L'identifiant et le nom a été changé"
    - pt: "O nome e o identificador foram alterados"
- Username has been changed: 
    - fr: "L'identifiant a été changé"
    - pt: "O identificador foi alterado"
- Personal data has been changed: 
    - fr: "Les données personnelles ont été modifiées"
    - pt: "Os dados pessoais foram alterados"

## Interface examples

![allowed](https://user-images.githubusercontent.com/35422692/82053192-3d522380-96bd-11ea-920b-0847403b8d7a.png)

![error](https://user-images.githubusercontent.com/35422692/82051666-98cee200-96ba-11ea-95d8-1e600d98a53c.png)

**Comment by metzgegu** [comment]
In this PR, I added the username field in `PersonalData` which check the availability of the new username every time a new char is added in order to add a warning message when it isn't available.
The new username is displayed also in the header of the Account info page

**Comment by raphj** [comment]
This warning message when changing the user name does not seem explicit enough:
> When you change it, your old username and everything linked to it will be lost

I'd suggest something like:

"When you change your username, everything linked to the old one, including mentions and TODOs (?) will be lost"

@celiamgtt ?

**Comment by celiamgtt** [comment]
I like your version! I think it's to soon to talk about TODOs.

**Comment by raphj** [comment]
so, just mentions? Is it correct by the way?

**Comment by celiamgtt** [comment]
@lebouquetin What's your opinion?

**Comment by lebouquetin** [comment]
> "When you change your username, everything linked to the old one, including mentions and TODOs (?) will be lost"

Nothing will be lost. Links will be broken but as soon as a user has been mentionned, TODOs and notificatins are created for the given user based on its user_id, so items will stay linked. What will be broken is in a comment a mention will appear with old username (which is not linked to a user anymore)

**Comment by gbonaspetti** [comment]
> > "When you change your username, everything linked to the old one, including mentions and TODOs (?) will be lost"
> 
> Nothing will be lost. Links will be broken but as soon as a user has been mentionned, TODOs and notificatins are created for the given user based on its user_id, so items will stay linked. What will be broken is in a comment a mention will appear with old username (which is not linked to a user anymore)

After that clarification, I suggest we change the warning to something simple like: "Changing the username will not change the old mentions."
What do you think @lebouquetin @celiamgtt @raphj?

**Comment by raphj** [comment]
Yes. I suggest "Changing your username will not (update|change) the mentions using your current username."

I'd say we will change this as needed anyway.

**Comment by inkhey** [comment]
verified on branch.
