### ISSUE TITLE
Feat: Add username on Admin screens

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#2945]
## Feature description

On the admin screens:
- [x] Add username field in the table between User and Email that when it is null it will be empty, same for the field Email
- For create new user:
  - [x] Add a username field between User and Email with placeholder @username
  - [x] Add a warning about e-mails/reset password (question mark icon next to the email label): The user will not be able to reset his password by himself without an email linked to his account. This warning should only be visible if the e-mail notifications are activated.
  - [x] Add a warning message for non-standard or non-unique usernames: allowed chars: azAZ09-_ and minimal lenght of 3 chars (sometimes the user will enter @username, sometimes just username, the frontend should handle both cases)
  - [x] Add a warning when the user is created if the email field is empty and the notifications are activated

## Context

Linked to #2829

## Prerequisites

#2933 

## Impacted components

  - frontend_app_admin_workspace_user
  - frontend

## Extra information

Interface example:
![Screenshot from 2020-05-11 14-23-14](https://user-images.githubusercontent.com/35422692/81566277-f7365080-939a-11ea-8cf1-1f3a5c13e85a.png)

Translations:
- **username** 
French: _identifiant_
Portuguese: _identificador_
- **Linking an email address is required for the user to be able to reset the password.**
French: _Un email est nécessaire pour que l'utilisateur puisse réinitialiser son mot de passe._
Portuguese: _A atribuição de um endereço de e-mail é necessária para que o utilizador possa redefinir a palavra-passe._
- **Your username is incorrect, the allowed characters are azAZ09-_**
French: _Votre identifiant est incorrect, les caractères autorisés sont azAZ09-__
Portuguese: _O seu identificador está incorreto, os carateres permitidos são azAZ09-__
- **Username must be at least 3 characters**
French: _L'identeifiant doit faire au moins 3 caractères_
Portuguese: _O identificador deve ter pelo menos 3 carateres_
- **Username can't contain any whitespace**
French: _L'identifiant ne doit pas contenir d'espace_
Portuguese: _O identificador não pode conter nenhum espaço em branco_
- **Please enter a name, a password, select a profile, and at least one between username or email**
French: _Veuillez saisir un nom, un mot de passe, sélectionner un profil, et au moins un identifiant ou un email_
Portuguese: _Por favor, digite um nome, uma palavra-passe, seleccione um perfil e pelo menos um entre identificador ou e-mail_
- **Error while checking username availability**
French:  _Erreur lors de la vérification de la disponibilité de l'identifiant_
Portuguese:  _Erro ao verificar a disponibilidade do identificador_
- **This username is not available**
French: _Cet identifiant n'est pas disponible_
Portuguese: _Este identificador não está disponível_

**Comment by gbonaspetti** [comment]
To solve this issue texts and translations have been updated, the username has been added to all the functions linked to the creation of a user, the necessary checks for it have been added and the username has also been added in the table of information that admin has about the user.

**Comment by metzgegu** [comment]
I found a little bug in the current pull request, when the username is not available and the form is closed and reopened the warning message is sill here:

![Test2945](https://user-images.githubusercontent.com/31687635/81184676-f96e6880-8fb0-11ea-8359-4bae92bc8ac6.gif)

**Comment by gbonaspetti** [comment]
> I found a little bug in the current pull request, when the username is not available and the form is closed and reopened the warning message is sill here:
> 
> ![Test2945](https://user-images.githubusercontent.com/31687635/81184676-f96e6880-8fb0-11ea-8359-4bae92bc8ac6.gif)

To fix this bug, I check if username field is empty before print the warning message.

**Comment by PhilippeAccorsi** [comment]
`Linking an email address is required for the user to be able to reset the password.` This message is not necessary when Tracim running without email feature activated.

In this case, just an admin user can reset password for user.

**Comment by PhilippeAccorsi** [comment]
Username is it mandatory to create new user ? (if yes, what is going on if I tried to create user with add member feature ?)

in tracim 2.7.3 or oldest, email is mandatory to create account (email not need to be really exist), what is going on here if email is not added ?

**Comment by gbonaspetti** [comment]
> `Linking an email address is required for the user to be able to reset the password.` This message is not necessary when Tracim running without email feature activated.
> 
> In this case, just an admin user can reset password for user.

@PhilippeAccorsi you're right, I will update the issue description and put it back in To Do to fix this point.

> Username is it mandatory to create new user ? (if yes, what is going on if I tried to create user with add member feature ?)
> 
> in tracim 2.7.3 or oldest, email is mandatory to create account (email not need to be really exist), what is going on here if email is not added ?

From this version neither email nor username are required (more details of the discussion at #2829 ), but it is mandatory to have at least one of the two.
The admin can't create a user if it hasn't filled at least one of the two (button is disabled).

**Comment by PhilippeAccorsi** [comment]
> The admin can't create a user if it hasn't filled at least one of the two (button is disabled).

Ok.

Is it possible to create user with add member feature without giving email ? Or in this case, its just possible to create user with one email ?

**Comment by gbonaspetti** [comment]
> Is it possible to create user with add member feature without giving email ? Or in this case, its just possible to create user with one email ?

No, the behavior in "Add member" is still the same, you can only create a user via e-mail and the notifications must be activated (i.e. you cannot create with null e-mail).

**Comment by grignards** [comment]
Verified on branch (wait merge to close).
