### ISSUE TITLE
Feat: Tool for manual tracim test and automatic test for docker image of tracim

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2948]
## Feature description

Currently testing docker image is complex, we run with one configuration, we forget one parameter, etc… 
We should have some kind of tool to automatically verificate that we can run a full featured working tracim (all service running) using our docker image.

This tools can also provided a manual test mode permitting to set custom tracim config and stay running after all test passed.

## Context

When trying to manually test tracim docker, it really complicated to not forget to set this and this, to rerun this and this service.
That's why i created a small tool based on pytest/testinfra, helping me to test this with fewer risks of errors:
see https://github.com/tracim/tracim/tree/feat/2948__semi_automatic_docker_test

## Implemented solution
- pytest tests that run tracim docker, elasticsearch and collabora for a full working tracim environnement by fixture
- test on docker image using testinfra that can be adapted in future to be usable for production or any tracim environnement check.
- configuration of test process can be done through test_config.env, a parameter allow to switch between autostop and keep enabled mode with allow manual test after running.
- tracim docker environnement parameters can be passed to test with tracim.env config file allowing to easily test many tracim configurations with docker.

**Comment by inkhey** [comment]
Don't forget to document how to use this.

**Comment by PhilippeAccorsi** [comment]
Tested on branch.
Done
