### ISSUE TITLE
Feat: Popup at login when username is NULL

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#2950]
## Feature description

If username is NULL when the user sign in, a popup suggest user to set username, if he doesn't want he can just close or skip the popup with a checkbox: never ask me again (you can always set your username in your account preferences)

## Context

Linked to #2829 

## Impacted components

- frontend

## Extra information

Translations:
- Hello, you don't have a username yet!
French: _Bonjour, vous n'avez pas encore d'identifiant !_
Portuguese: _Olá, você ainda não tem um identificador!_
- Set your username:
French: _Définissez votre identifiant :_
Portuguese: _Defina o seu identificador:_
- never ask me again (you can always set your username in your account preferences)
French: _ne plus jamais me demander (vous pourrez toujours définir votre identifiant dans les préférences de votre compte)_
Portuguese: _nunca mais me pergunte (você pode sempre configurar o identificador nas preferências da sua conta)_

Interface example:

![Screenshot from 2020-04-29 16-37-00](https://user-images.githubusercontent.com/35422692/80608960-d9322d00-8a37-11ea-9ce4-369a49918f50.png)

**Comment by gbonaspetti** [comment]
In order for the popup not to appear every time for a user who decided to leave the username empty, you will need a variable in the backend that says if the user X decided to leave his username null or if he has not logged in yet. Something like a boolean `username_established`.

**Comment by inkhey** [comment]
> In order for the popup not to appear every time for a user who decided to leave the username empty, you will need a variable in the backend that says if the user X decided to leave his username null or if he has not logged in yet. Something like a boolean `username_established`.

Not sure how we should store that. Another solution may be using cookie. It seems to me more standard to have such mecanism with cookie, but It has some drawback.

**Comment by lebouquetin** [comment]
@gbonaspetti @inkhey I suggest to store it in a cookie. This is faster at the moment, It may be enough - we'll have issues in the bugtracker by users if not enough

**Comment by inkhey** [comment]
Verified on branch (wait merge to close).
