### ISSUE TITLE
Upgrade Node to version 12 or 14

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#2953]
`./install_frontend_dependencies.sh` currently installs node 12 if node is not installed since the migration to Yarn, but tests for version 10+.

Latest versions of Yarn (v2.2+) dropped support for node 10.16 or earlier, which is what Travis provides.

We need to migrate away from Node 10 and upgrade  to node 12 or 14.

## Impacted components

- *frontend*

## Extra information
https://github.com/nodejs/Release

> Release | Status | Codename | Initial Release | Active LTS Start | Maintenance Start | End-of-life
> -- | -- | -- | -- | -- | -- | --
> 10.x | Maintenance | Dubnium | 2018-04-24 | 2018-10-30 | 2020-05-19 | April 2021
> 12.x | Active LTS | Erbium | 2019-04-23 | 2019-10-21 | 2020-10-20 | April 2022
> 14.x | Current |   | 2020-04-21 | 2020-10-27 | 2021-10-19 | 2023-04-30
-- | -- | -- | -- | -- | -- | --

**Comment by raphj** [comment]
./setup_defaut_backend currently installs node 10 and should probably be updated as well if we don't revert to node 10

**Comment by raphj** [comment]
My take is that we shouuld keep supporting and testing on Node 10, but make sure that Tracim works with Node 12.

When we drop support for stretch we might want to stop adding node's specific repositories and install node from the Debian repositories, except if we want to drop support for Node 10 too.

**Comment by inkhey** [comment]
> My take is that we should keep supporting and testing on Node 10, but make sure that Tracim works with Node 12.
> 
> When we drop support for stretch we might want to stop adding node's specific repositories and install node from the Debian repositories, except if we want to drop support for Node 10 too.

is it possible to have a env var or a parameter helping us switching node version to install, this way we can in the future more easily test it ?

**Comment by raphj** [comment]
I think this is a good idea, but the default is what really matters here.

On the other end, I'm not sure it matters so much. We use node to build the frontend with tools that are probably already heavily tested with both versions.

**Comment by raphj** [comment]
I also expect failures to be noticable (e.g. a build error). The worse possible event I can think of would be an erroneous build, which would be catastrophic but seems highly unlikely too.

Currently, the scripts does not check for a specific Node version so there could be people building Tracim with node 12 or 13 already, which should be addressed if we think it is important.

**Comment by grignards** [comment]
Building the docker image today (2021-05-11), I got this big warning:
```
================================================================================
================================================================================

                              DEPRECATION WARNING                            

  Node.js 10.x is no longer actively supported!

  You will not receive security or critical stability updates for this version.

  You should migrate to a supported version of Node.js as soon as possible.
  Use the installation script that corresponds to the version of Node.js you
  wish to install. e.g.

   * https://deb.nodesource.com/setup_12.x — Node.js 12 LTS "Erbium"
   * https://deb.nodesource.com/setup_14.x — Node.js 14 LTS "Fermium" (recommended)
   * https://deb.nodesource.com/setup_15.x — Node.js 15 "Fifteen"
   * https://deb.nodesource.com/setup_16.x — Node.js 16 "Gallium"

  Please see https://github.com/nodejs/Release for details about which
  version may be appropriate for you.

  The NodeSource Node.js distributions repository contains
  information both about supported versions of Node.js and supported Linux
  distributions. To learn more about usage, see the repository:
    https://github.com/nodesource/distributions

================================================================================
================================================================================
```

**Comment by inkhey** [comment]
We do currently use node 14, so this ticket is already fixed.

@gbonaspetti Should we create a new ticket to upgrade to node 16 or better ?

**Comment by raphj** [comment]
FYI https://github.com/tracim/tracim/issues/5352 (@inkhey)
