### ISSUE TITLE
Bug: Fix support for smtp without authentification

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2954]
## Bug description & symptom

Until tracim 2.6.X it was possible to disable auth for SMTP if SMTP_USER parameter was not provided. It's not an explicit behavior.

With 2.7, SMTP_USER parameters became **clearly** mandatory, like some others parameters.
see https://github.com/tracim/tracim/commit/0004cb18a448776680a748b7086722c7c1b85824#diff-2904e03774c2dd7346b24aec492c8ce0R873 .
So this "hidden feature" is now broken.

Current workaround is to set some default value in SMTP_USER and SMTP_PASSWORD, as deamon doesn't failed after auth failing, but this will create unwanted logs.

## Expected

Allow to support smtp without authentification in an **explicit** way.

## Implemented solution:
https://github.com/tracim/tracim/pull/5595
- add explicit authentication parameter permitting anonymous auth
- refactorizing configuration for smtp encryption

:warning:  don't forget to update changelog !

**Comment by PhilippeAccorsi** [comment]
With empty value its also impossible to start Tracim with docker or to use elasticsearch command (to create index with tracimcli command for example).

**Comment by PhilippeAccorsi** [comment]
@lebouquetin what do you think about this `bug` ? At present if you want send email on port 25 (for example) and without authentication, you need to add wrong user and wrong password (example user=rien and password =rien). If you leave this two parameter empty, Tracim not working.

I think we need to fix this in 3.2.x (if its possible).

**Comment by inkhey** [comment]
@PhilippeAccorsi @grignards 
To clarify smtp configuration with the new anonymous case, i also refactor the encryption mode by deprecating the old parameter and replacing it by a new one. 
This will permit us to : 
- close this old technical debt ticket : https://github.com/tracim/tracim/issues/2851
- make transition to force starttls mode smoother (we just have to add an encryption method) : https://github.com/tracim/tracim/issues/2815

**Comment by knodelle** [comment]
done
