### ISSUE TITLE
Feat: Drop Stretch support and update docker to buster

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#2959]
## Feature description

Docker image seems to work correctly on buster (tested with develop tracim 2.7 + somes 3.0 fixes)
we should think about switching to buster for docker and drop the stretch support too.

**Comment by PhilippeAccorsi** [comment]
Just to know date of stretch end LTS support

Debian 9 “Stretch” | i386, amd64, armel, armhf and arm64 (to review before start) | 2020 to June 2022
-- | -- | --

**Comment by charline-rageade** [comment]
@inkhey why this ticket is mentioned in #2956 PR ? Is it still relevant ?

**Comment by inkhey** [comment]
This ticket is obsolete, so i put it in "to close".

**Comment by knodelle** [comment]
obsolete ticket
