### ISSUE TITLE
Feat: remove public_name from POST workspace member endpoint

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#2970]
## Feature description

Endpoint `/api/v2/workspaces/{workspace_id}/members` does not take a public_member field anymore. This does not remove any feature from the end user point of view. The frontend always sets the user_id to select the user found thanks to the known_members endpoint anyway.

The fix removes the function in the backend that select a user by its public name since it is not used anymore. This function was bound to be problematic anyway since public names are not unique.

## Context

See https://github.com/tracim/tracim/issues/2942

## Prerequisites

Sync with frontend (https://github.com/tracim/tracim/issues/2942).

## Impacted components

- *backend*
- *frontend*

**Comment by inkhey** [comment]
> Endpoint `/api/v2/workspaces/{workspace_id}/members` does not take a public_member field anymore. 

I agree that public_name should be removed. It's not reliable.


>This does not remove any feature from the end user point of view. The frontend always sets the user_id to select the user found thanks to the known_members endpoint anyway.

This is untrue. known_members can in specific case (depending on tracim configuration) not return all member, so removing this will remove some ability to add existing but not visible user.
I do no know if frontend handle this case.

see discussion about this here:
https://github.com/tracim/tracim/issues/2942#issuecomment-625216314

**Comment by raphj** [comment]
Merging anyway, this is being addressed in the linked issue.
