### ISSUE TITLE
Bug: the backend install script may issue errors and keep running

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#2979]
## Bug description & symptom

The backend install script, `setup_default_backend.sh`, may issue errors and keep running. The script should stop running if there are errors.

## Impacted components

- *backend*

## Fix

The fix in setup_default_backend.sh:
-  groups the apt install commands
-  makes the error stop the script with a return value of 1.

**Comment by lebouquetin** [comment]
@raphj this issue is in TODO in the project, but there seems to be some work on it. You should move the issue to In Progress, don't you?

**Comment by inkhey** [comment]
Backend Install script tested on existing install and on debian docker, run without issue in both case.
