### ISSUE TITLE
Bug: regression on translation (french, english, portugues)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#2986]
## Bug description & symptom

Translation not working on this page (maybe also on other page) when I switch from one language to another one:

- http://localhost:6543/ui/admin/workspace
- http://localhost:6543/ui/admin/user

## Expected

- [ ] translation work correctly like we have on 2.7.2
- [ ] cypress test to check translation working

## Context and version information

Tracim installed locally on develop branch

## How to reproduce

- Start from new database
- go in admin user or admin sharedspace
- change language
=> some word change but not all

## Screenshots

![bugè_translation_not_working](https://user-images.githubusercontent.com/25848257/80995108-03bc2580-8e3e-11ea-8d2d-3ca3c708893b.gif)

## Impacted components

*frontend*

## Solution

#3113 -  The problem was that `react-i18next` and some other libraries were incorrectly in the `externals` configuration of webpack. It somehow didn't break things while we were using NPM, and the issue surfaced when we switched to Yarn.

**Comment by PhilippeAccorsi** [comment]
Need some cypress test

**Comment by PhilippeAccorsi** [comment]
App file is also impacted.

**Comment by gbonaspetti** [comment]
In tests it seems that everything works correctly, the only thing that I found that was not translated is the version of the content (bottom left corner of the image below).
For example, in Portuguese it should be `versão nº3`.

![Screenshot from 2020-06-05 16-53-33](https://user-images.githubusercontent.com/35422692/83892020-572bd700-a74e-11ea-8050-d6fd9fe1568e.png)

**Comment by raphj** [comment]
Good catch!
(and bad news. *sigh*)

**Comment by raphj** [comment]
I found that this bug is also present on our internal instance, so it is not a regression on develop. I'll look into it.

**Comment by raphj** [comment]
ok, so this is a hard-coded string.

**Comment by inkhey** [comment]
verified on branch.
