### ISSUE TITLE
Bug: Regression : TINYMCE buttons do not appear with a certain window size, some responsive bug and portugues translation not working

### ISSUE THREAD

**Issue by LucBarry** [tracim/tracim#2993]
## Bug description & symptom

When I want to put in full screen a note in Tracim, the tiny MCE buttons only appear if my window is 70% un-zoomed. The problem does not come from the web browser.
Also some regression on responsive (Tinymce not permit to write text) and portugues language show an error in tinymce

## Expected :
- [x] Having the buttons accessible regardless of the size of the web browser window 
- [x] regressions of responsive are fixed
- [x] portugues translation work in tinymce

## Screenshot :

![80%](https://user-images.githubusercontent.com/39124679/81075014-15f39d80-8eea-11ea-991d-8083a4d808ed.png)

![100](https://user-images.githubusercontent.com/39124679/81075017-1724ca80-8eea-11ea-8b9e-fafaa4054878.png)

Edited:
by Philippe (07/05/2020)

**Comment by metzgegu** [comment]
I think this issue #2764  introduced this regression

**Comment by PhilippeAccorsi** [comment]
We fix also responsive problem and UX problem not solved correctly in 2.7.0 (visible in issue 2764).

**Comment by PhilippeAccorsi** [comment]
Missing portugues language is also added in this issue.

**Comment by metzgegu** [comment]
In order to have a bigger textAera with TinyMCE when the screen has a small width.

**Comment by PhilippeAccorsi** [comment]
Tested on branch by @PhilippeAccorsi @celiamgtt and @LucBarry
Tested on desktop (Linux and MacOs) and mobile version (Android and IOS)
Verified.
