### ISSUE TITLE
Feat: Add Ctrl+enter to post a comment/note on document

### ISSUE THREAD

**Issue by YannickBiet** [tracim/tracim#2995]
## Feature description

When entering a comment/note on a document in the document browser, pressing Ctrl+Enter (Cmd+Enter under MacOS) should trigger the send button like most of messaging systems (atlassian, teams, slack, ...)

## Context

lazy guy that don't want to use its mouse to press the button

## Prerequisites

Know there's usually shortcuts associated to most used commands in a software :)

## Impacted components

- *frontend*

**Comment by celiamgtt** [comment]
Duplicate of: #2817 - Allow sending a message in the timeline using a keyboard shortcut

**Comment by Haskaris** [comment]
Duplicate of #2817
