### ISSUE TITLE
Bug: Frontend unit tests are silently failing

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#2999]
## Bug description & symptom

Frontend unit tests are not running for the frontend apps. Addressed by fixing a mistake in the frontend unit test script.

## Impacted components

- *frontend*

**Comment by Skylsmoi** [comment]
it appears some tests are broken.

I don't know since when.

It's the tests of CollaborativeEditionFrame component in frontend_app_collaborative_document_edition

**Comment by Skylsmoi** [comment]
tests have been fixed in the PR

**Comment by gbonaspetti** [comment]
Verified on branch (wait merge to close).
