### ISSUE TITLE
Bug: long "document" (not so long) is long to load

### ISSUE THREAD

**Issue by YannickBiet** [tracim/tracim#3002]
![May-06-2020 19-25-26](https://user-images.githubusercontent.com/930391/81214656-72cd8180-8fd8-11ea-817e-62c5a230c254.gif)

## Bug description & symptom

I created a long document (for example there i used 50 paragrph of lorem ipsum generator)
Tracim request many seconds to load, and in term of UX, you see a blank document without spinner the time backend finish to load the infos

The text length is about 30 KB when saved on a RTF file
So i don't get why tracim need multiple seconds to load 30 KB of document.

## Expected

- Have a loading indicator
- see how to optimize the document compresison, loading system

## Impacted components

- *backend*
- *frontend*

**Comment by grignards** [comment]
The longest query is to get the document's revisions as they contain the document's contents. A better approach would probably to get a revision's content only when it is displayed.

**Comment by YannickBiet** [comment]
I didn't check in deed the content of the query, but if you're right @grignards, yes in deed the document history should only contain the few metadata and information to query the contents on the fly (like a endpoint to actually retrieve the document and revisionID

I noted down on really long history the same behavior (with 300+ revision in a document the FULL history is loaded and not lazy loaded as requested when scrolling the documents)

**Comment by lebouquetin** [comment]
There is a refactoring planned for merging all content behavior.

The behavior you are talking about is related to html documents only. (But yes, the strategy must be improved)

**Comment by gbonaspetti** [comment]
This issue seems to be fixed. I'm going to close it.
