### ISSUE TITLE
Feat: Group vendor dependencies to make faster and smaller frontend builds

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3016]
## Feature description

This tickets tracks the process of grouping dependencies so we don't bundle them for each app, which is slow and produces big bundles.

## Context

#2813 

## Impacted components

- *frontend*

## Proposed solution

We build common / big dependencies in a separate "fake" NPM package, `tracim_frontend_vendors`, leveraging Yarn workspaces. In this package, we produce a bundle with the dependencies. This bundle, as well as frontend lib, are added to every relevant html files:

- the main frontend html file
- the html files used in servdev mode

The vendor package is build before other packages.

This allows building the dependencies once and for all. Bundling each tracim frontend components is way faster, since we only build their code, plus some small or specific dependencies. 

Other features enabled by this change:
 - lint, test and test:quick build scripts are available in every frontend apps: test:quick run the unit tests, lint runs the linting and test runs both
 - linting in the frontend is enforced in the CI: a style issue will require fixing before merging
 - this also fixes many linting errors that were formerly hidden
 - source maps are available in development builds, which eases debugging a lot
 - memory consumption of a freshly opened Tracim tab drops from 50 MB to bellow 20 MB and first startup is faster

**Comment by lebouquetin** [comment]
One point about all frontend applications is they should be usable out of tracim.

Imagine the Agenda application. It is integrated in tracim. Perfect. It's one of the rare CalDAV clients written in web technology. I expect the application not being too complicated to integrate in another application (there is a JS API to implement - ok, but the "component" is extractible from Tracim)

**Comment by raphj** [comment]
This work should not change this aspect, only, the `frontend_lib` and the vendors will need to be included in the web page in addition to the code of the app.

**Comment by raphj** [comment]
https://github.com/tracim/tracim/pull/3017#issuecomment-713355773

**Comment by inkhey** [comment]
tested on branch

**Comment by raphj** [comment]
@grignards also tested it.

**Comment by PhilippeAccorsi** [comment]
Done.
