### ISSUE TITLE
Decide about notification parameter typing when creating a role API

### ISSUE THREAD

**Issue by algooapy** [tracim/tracim#302]
The function creating a role advertises a notification parameter as follow:
`tracim/tracim/lib/userworkspace.py:RoleApi.create_one([...], with_notif: bool, [...])`
But this parameter directly sets a `on_off_to_boolean` parameter there:
`tracim/tracim/lib/helpers.py:on_off_to_boolean(on_or_off: str) -> bool`
This leads to the incompatible `with_notif: bool` vs `on_or_off: str` signatures.

**Comment by lebouquetin** [comment]
To do:
- remove the use of `on_off_to_boolean()` in `create_one()` method body
- check that all calls to `create_one()` explicitly convert input data (which comes from http requests) using `on_off_to_boolean()`

Example of usage:

```
userworkspaceapi.create_one(... with_notif=on_off_to_boolean(on_or_off))
```
