### ISSUE TITLE
Bug: An automatic update of flake8 broke the backend tests in the CI

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3025]
## Bug description & symptom

An automatic update of flake8 broke the backend tests in the CI.

We need to:

- [x] set the version for the CI for the backend linters
- [x] decide whether we should also fix the version for the developers
- [ ] decide how to handle updates

## Diagnostic

In the CI (e.g. https://travis-ci.org/github/tracim/tracim/jobs/685987514):

    18.36s$ flake8 $TRAVIS_BUILD_DIR/backend/tracim_backend
    /home/travis/build/tracim/tracim/backend/tracim_backend/apps.py:7:80: E501 line too long (88 > 79 characters)
    /home/travis/build/tracim/tracim/backend/tracim_backend/apps.py:8:80: E501 line too long (98 > 79 characters)
    /home/travis/build/tracim/tracim/backend/tracim_backend/apps.py:18:80: E501 line too long (93 > 79 characters)
    /home/travis/build/tracim/tracim/backend/tracim_backend/apps.py:20:80: E501 line too long (108 > 79 characters)
    /home/travis/build/tracim/tracim/backend/tracim_backend/apps.py:27:80: E501 line too long (82 > 79 characters)
    /home/travis/build/tracim/tracim/backend/tracim_backend/exceptions.py:506:80: E501 line too long (82 > 79 characters)
    /home/travis/build/tracim/tracim/backend/tracim_backend/exceptions.py:510:80: E501 line too long (85 > 79 characters)
    /home/travis/build/tracim/tracim/backend/tracim_backend/__init__.py:40:80: E501 line too long (88 > 79 characters)
    /home/travis/build/tracim/tracim/backend/tracim_backend/__init__.py:41:80: E501 line too long (84 > 79 characters)
    /home/travis/build/tracim/tracim/backend/tracim_backend/__init__.py:42:80: E501 line too long (89 > 79 characters)
    /home/travis/build/tracim/tracim/backend/tracim_backend/__init__.py:43:80: E501 line too long (86 > 79 characters)
    /home/travis/build/tracim/tracim/backend/tracim_backend/__init__.py:44:80: E501 line too long (82 > 79 characters)

## Impacted components

- *backend*, CI

## Implementation summary

A first quick fix has been done in https://github.com/tracim/tracim/tree/3025__static_tests_requirements. It only fixes the build break by enforcing versions of the linters.
I leave this issue open to address the third point: how to handle the linter's updates ?

**Comment by inkhey** [comment]
most of the issue is done, the last part should be solved by https://github.com/tracim/tracim/issues/3191.

**Comment by PhilippeAccorsi** [comment]
CI working good.
