### ISSUE TITLE
Bug: REGRESSION rich text not working with comment feature

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#3026]
## Bug description & symptom

Its not possible to add comment or to cancel comment

![Screenshot_2020-05-12 g · APC · Algoo · Tracim](https://user-images.githubusercontent.com/25848257/81660216-c279d600-943a-11ea-8148-45874ace949d.png)

## Diagnostic

It seem this bug is introduced with commit https://github.com/tracim/tracim/commit/998c97c7d53b5413c957a3cf659b60f959e9c56d and this is the bug `height 200px`.

## Expected

- [x] its possible to add or cancel comment
- [x] automated test necessary for Tracim 2.3.x (https://github.com/tracim/tracim/issues/3030)
  - wont do in this issue

## Context and version information

Bug introduced in Tracim 2.7.0 

## How to reproduce

- open one content
- try to add comment with rich text

## Impacted components

- *frontend*

## Extra information

**Comment by Skylsmoi** [comment]
My solution is to remove the height 200px that was causing the issue.
I couldn't see it's uses.

I'll ask what it was there for.

In resolution at 1200x700, our tinymce for comment is too big. We just don't have enough room. My solution is to reduce the textarea height (the place where you type in advanced edition) to 100px.
I choose to do this on any screen size because it fits better and we don't need more place to write a comment. If you really need more space, you should use the fullscreen mode.

**Comment by Skylsmoi** [comment]
Note that this height 100px only does things for the comments.

In the html-document app in edition mode, it doesn't do anything because of the flex-shrink and flex-grow.

**Comment by Skylsmoi** [comment]
Also note that our layout minimum height at above 1200px for width is 675px.
Bellow 675px, some things will end up cropped.

Since screen size at 1200px is usually, by ratio, 720px, I say it's fine

**Comment by tracim** [comment]
The 100px is it used on mobile device ?

**Comment by PhilippeAccorsi** [comment]
> Note that this height 100px only does things for the comments.
> 
> In the html-document app in edition mode, it doesn't do anything because of the flex-shrink and flex-grow.

Is it also on mobile view, or it is just on desktop version ?

**Comment by Skylsmoi** [comment]
yes

**Comment by PhilippeAccorsi** [comment]
Full screen mode is broken

![Screenshot_2020-05-13 last test · tinymce · Tracim · Tracim](https://user-images.githubusercontent.com/25848257/81784628-6fb52280-94fd-11ea-82e6-b4c355f5ffb5.png)

The height is 200px (same size like tinymce in comment).

**Comment by Skylsmoi** [comment]
I have fix this by setting the height 100px only when not in fullscreen

**Comment by PhilippeAccorsi** [comment]
Tested and verified on branch by Team Algoo :)
Tested on MacOS, IOS, Android, Firefox, Chrome.

Wait merge to close.
