### ISSUE TITLE
Feat: Anonymized or deleted user is showing as "Deleted User"

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3050]
## Feature description

Anonymize or delete of a user will result in showing :
- "Deleted User" by default for anonymized user
- Nothing if user is completely deleted
- custom value if provided during anynomization

## Context

Anonymization context: https://github.com/tracim/tracim/issues/2401

## Implemented solution:
#3094 -> default anonymized user is renamed to "Deleted User"

**Comment by PhilippeAccorsi** [comment]
Why not use same like existing at present in Tracim ? (visible in development.ini and used by tracimcli command)

~~~
## Anonymized User
# You can set default display name for anonymized user.
; default_anonymized_user_display_name = "Lost Meerkat"
~~~

**Comment by gbonaspetti** [comment]
> Why not use same like existing at present in Tracim ? (visible in development.ini and used by tracimcli command)
> 
> ```
> ## Anonymized User
> # You can set default display name for anonymized user.
> ; default_anonymized_user_display_name = "Lost Meerkat"
> ```

I agree to use what already exists. I think @lebouquetin's request at #2829 was to change to "Someone" what's shown. @lebouquetin, you confirm that?

**Comment by lebouquetin** [comment]
I didn't remember that anonymized user appears with a parameterized username. @PhilippeAccorsi what is the name shown when a user has been deleted?

@gbonaspetti I change frontend to backend label because this part is about backend configuration.

My feeling is there will be nothing to do (maybe a default parameter change)...

**Comment by PhilippeAccorsi** [comment]
> I didn't remember that anonymized user appears with a parameterized username. @PhilippeAccorsi what is the name shown when a user has been deleted?
> 
This is what is shown when user is anonymized (for example: for comment in one content, when content can't be deleted)
`; default_anonymized_user_display_name = "Lost Meerkat"` and we can define another default name in development.ini or specific name when running tracimcli command.

> @gbonaspetti I change frontend to backend label because this part is about backend configuration.
> 
> My feeling is there will be nothing to do (maybe a default parameter change)...
The parameter is from discuss about what is the default name if public_name need to be anonymize.

**Comment by PhilippeAccorsi** [comment]
> @PhilippeAccorsi what is the name shown when a user has been deleted?
If user have no content in shared space where is not the owner of the shared space, all content is deleted. So no anonimyzed information needed.

**Comment by lebouquetin** [comment]
I suggest to

- change default value `Lost Meerkat` to `Deleted user`
- use a specific value on our client instances `Utilisateur supprimé`

@PhilippeAccorsi @gbonaspetti what do you think.

**Comment by gbonaspetti** [comment]
> I suggest to
> 
> * change default value `Lost Meerkat` to `Deleted user`
> * use a specific value on our client instances `Utilisateur supprimé`
> 
> @PhilippeAccorsi @gbonaspetti what do you think.

As the process is called anonymizing a user, I suggest `Unknown user` (_Utilisateur inconnu_ - _Utilizador desconhecido_).

**Comment by PhilippeAccorsi** [comment]
> > I suggest to
> > 
> > * change default value `Lost Meerkat` to `Deleted user`
> > * use a specific value on our client instances `Utilisateur supprimé`
> > 
> > @PhilippeAccorsi @gbonaspetti what do you think.
> 
> As the process is called anonymizing a user, I suggest `Unknown user` (_Utilisateur inconnu_ - _Utilizador desconhecido_).

For me `Deleted user` is acceptable. `Unknown user` can be understand by "Tracim can't define user" (like a bug), but this is a choice of admin to delete this user. I think in many company its also more simple to says `Deleted user` because you know exactly which member team have gone.

**Comment by inkhey** [comment]
I wasn't sure to understand the issue, so i try to delete a user with best effort mode (so it was anonymized). It work correctly, i get public name with "Lost Meerkat".
For really deleted user, of course, we do not have the information anymore.
So, is the issue about just renaming lost meerkat or is there something more to fix in backend (or frontend ?).

**Comment by PhilippeAccorsi** [comment]
For me its just necessary to rename `Lost Meerkat` to `Deleted user` in development.ini and in backend code (default value).

I don't know if something need to be done in backend about username visible in mention after deleted/anonymized user.

**Comment by gbonaspetti** [comment]
> I wasn't sure to understand the issue, so i try to delete a user with best effort mode (so it was anonymized). It work correctly, i get public name with "Lost Meerkat" in non deleted comment and created file.
> For really deleted user, of course, we do not have the information anymore.
> So, is the issue about just renaming lost meerkat or is there something more to fix in backend (or frontend ?).
> @gbonaspetti @PhilippeAccorsi ?

Yes, I believe it's just changing the name, @lebouquetin  had put that point too:
- use a specific value on our client instances `Utilisateur supprimé`

I don't know what that means as backend code changes.



Note: Deleted user in portuguese is `Utilizador eliminado`

**Comment by inkhey** [comment]
> > I wasn't sure to understand the issue, so i try to delete a user with best effort mode (so it was anonymized). It work correctly, i get public name with "Lost Meerkat" in non deleted comment and created file.
> > For really deleted user, of course, we do not have the information anymore.
> > So, is the issue about just renaming lost meerkat or is there something more to fix in backend (or frontend ?).
> > @gbonaspetti @PhilippeAccorsi ?
> 
> Yes, I believe it's just changing the name, @lebouquetin had put that point too:
> 
>     * use a specific value on our client instances `Utilisateur supprimé`
> 
> 
> I don't know what that means as backend code changes.
> 
> Note: Deleted user in portuguese is `Utilizador eliminado`

The default value is stored in config file, and currently not translated. We can either:
- not translated it : do nothing.
- translate it at user anonymization: will work only if we do not change the default value, it's similar mecanism as email subject where we can have custom value but translation is removed.

If we do translate, the logical choice will to rely on default instance language, So it will not be translated "automatically" like others things in ui, but more like account creation email.

**Comment by gbonaspetti** [comment]
Verified on branch.
