### ISSUE TITLE
Feat: Create Account endpoint for live_messages

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#3051]
## Feature description

We need to add "/users/me" account endpoint for lives messages features aside of existing "/users/{user_id}" 

This can be fixed either with code duplication or solving technical debt issue #1478.

**Comment by grignards** [comment]
What are the pros of those `me` endpoints compared to the `{user_id}` ones ?
Because:
- they duplicate code in backend
- they aren't RESTful (for example it wouldn't be possible to cache them as their results depend on the current user)

**Comment by lebouquetin** [comment]
My feeling is `/users/me` may be a redirect to `/users/{user_id}`, no?

**Comment by lebouquetin** [comment]
@grignards the reason for having /users/me is "ease of use". APIs are to be used by not-really-developers and the best way to publish an API is to allow to easily go to your target.

For exemple, if you are not yet authenticated, you can't access your profile so you do not know your user id

**Comment by inkhey** [comment]
tried refactoring /me endpoint using 307 redirection:
https://github.com/tracim/tracim/pull/3085

Some unclear questions:
- how frontend handle redirection 307, does it try to repost get parameters, post parameters, body ? depending on how frontend deal with it, it can break current behavior. After rapid check it's look like get parameters are not passed, so probably the same for others.
- should we convert get parameters into location using redirect 307 ?

That's why, i do suggest frontend to be refactored in order to not use /me endpoint if we follow this idea.

**Comment by grignards** [comment]
> tried refactoring /me endpoint using 307 redirection:
> #3085
> 
> Some unclear questions:
> 
>     * how frontend handle redirection 307, does it try to repost get parameters, post parameters, body ? depending on how frontend deal with it, it can break current behavior. After rapid check it's look like get parameters are not passed, so probably the same for others.

The [Mozilla doc](https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections) on this topic seems to suggest that the body and method of the request are preserved when executing the redirection, this would mean the full URI (including query parameters) should be returned in the `Location` header.

I think the redirection *should* be handled transparently by the browser, without needing javascript code for this, but ask @Skylsmoi to be sure.

>     * should we convert get parameters into location using redirect 307 ?
> 
> 
> That's why, i do suggest frontend to be refactored in order to not use /me endpoint if we follow this idea.

**Comment by Skylsmoi** [comment]
I have tested it and 307 redirections are handled nicely by browser. Front doesn't have to do anything.

![screen_307_redirect](https://user-images.githubusercontent.com/11177014/82433473-c4264800-9a91-11ea-8626-8fa57750cc7d.png)

in the screen above, first line is the OPTION to /users/me, the second one is the PUT that gets redirected, the third one is the OPTION to the new url /users/1 and then the last one is the actual PUT.
The request body is kept along the redirection

**Comment by inkhey** [comment]
> The [Mozilla doc](https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections) on this topic seems to suggest that the body and method of the request are preserved when executing the redirection, this would mean the full URI (including query parameters) should be returned in the `Location` header.

I confirm that query parameters have to be returned in location header.

**Comment by inkhey** [comment]
As this mean more query for frontend, best practice will be to avoid usage of theses endpoint in frontend, as frontend already know the user_id, a specific issue as been created: https://github.com/tracim/tracim/issues/3090. As the redirection is correctly handled out of the box by frontend theses two issue can be fixed independently.

**Comment by inkhey** [comment]
Fixed by issue #1478
