### ISSUE TITLE
Feat: add pagination and event_type filter to user message endpoint

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#3057]
## Feature description and goals

For performance concerns, we need a pagination mechanism like in other endpoints. Currently (see PR https://github.com/tracim/tracim/pull/3022), we only allow filtering by read status (The notification pane can display either only mentions or all messages).

On endpoint `/users/{user_id}/messages`:
- [X] add pagination with `count` and `page_token` parameters
  The pagination will return a maximum of `count` messages, the page token will allow to go to a specific "page", when using the endpoint, `previous_page_token` and `next_page_token` will be returned, allowing frontend to go easily to next/previous page.
- [X] add `event_types` filter.
  This filter will take a comma separated list of event types and only return messages matching one of the given types. It is optional.
- [X] make sure if we always use pagination somewhere in Tracim, to find a way to have similar mechanism everywhere if possible.

## ~~Needs discussion before development~~

~~It is unclear how pagination should be done offset-free or not, and if offset-free, it needs clarification on what should be the rule for all offset-free paginations for later endpoints: https://github.com/tracim/tracim/issues/3057#issuecomment-660875567~~

## Implemented solution

- add `event_types` filter to `/messages` endpoint
- reverse order `/messages `endpoint result to get last message first
- use library `sqlakeyset` for pagination in `/messages` endpoint : put messages in `items` field and add field `next_page_token`, `has_next`, `has_previous`, `next_page_token`, `per_page`, `previous_page_token`. frontend should set page_token query parameter to value obtain either by `next_page_token` or `previous_page_token`

effective endpoint specification:
```

GET /api/users/1/messages?read_status=read&event_types=user.created%2Cuser.modified&count=1&page_token=%3Ei%3A2 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: Basic YWRtaW5AYWRtaW4uYWRtaW46YWRtaW5AYWRtaW4uYWRtaW4=
Connection: keep-alive
Host: tracim.test
User-Agent: HTTPie/0.9.8

HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Type: application/json
Date: Thu, 23 Jul 2020 13:38:04 GMT
Keep-Alive: timeout=5, max=100
Server: Apache
Transfer-Encoding: chunked

{
    "has_next": false,
    "has_previous": true,
    "items": [
        {
            "created": "2020-07-23T11:24:17Z",
            "event_id": 1,
            "event_type": "user.modified",
            "fields": {
                "author": {
                    "allowed_space": 0,
                    "auth_type": "internal",
                    "avatar_url": null,
                    "created": "2020-07-23T11:23:02Z",
                    "email": "admin@admin.admin",
                    "is_active": true,
                    "is_deleted": false,
                    "lang": "fr",
                    "profile": "administrators",
                    "public_name": "Global manager",
                    "timezone": "",
                    "user_id": 1,
                    "username": "TheAdmin"
                },
                "client_token": "7d4fb048-0f5e-4f0f-bc03-27992674861f",
                "user": {
                    "allowed_space": 0,
                    "auth_type": "internal",
                    "avatar_url": null,
                    "created": "2020-07-23T11:23:02Z",
                    "email": "admin@admin.admin",
                    "is_active": true,
                    "is_deleted": false,
                    "lang": "fr",
                    "profile": "administrators",
                    "public_name": "Global manager",
                    "timezone": "",
                    "user_id": 1,
                    "username": "TheAdmin"
                }
            },
            "read": "2020-07-23T12:52:50Z"
        }
    ],
    "next_page_token": ">i:1",
    "per_page": 1,
    "previous_page_token": "<i:1"
}
```

----
_21-07-2020 - Description edition: adapt specification for sqlakeyset usage ._
_23-07-2020 - Add implemented solution section ._

**Comment by inkhey** [comment]
if we go for a offset-free mecanism, one possibility is using sqlakeyset ( https://github.com/djrobstep/sqlakeyset)
- We first need to verificate that all our support database can support it.
- This mean that frontend cannot access to any "page" he want. but we can send him a bookmark to be able to get to the next page without any pain, see : https://github.com/djrobstep/sqlakeyset#keyset-serialization.

**Comment by inkhey** [comment]
@Skylsmoi Two question:
1. Is this feature mandatory for 3.0 ?
2. Is the bookmark mecanism is ok for you ?

**Comment by inkhey** [comment]
moved to 3.1

**Comment by inkhey** [comment]
@grignards After thinking about using sqlakeyset vs before_event_id, i do think, we may rethink about it for consistency.
Here event_id does work only because we don't return multiple message with same event id to user, but in case we need multiple column to do the "offset id", it does not work.

sqlakeyset may need a bit more work but allow us to have a consistent parameter for frontend to use for offset-free pagination in all tracim.

**Comment by lebouquetin** [comment]
> if we go for a offset-free mecanism, one possibility is using sqlakeyset

@inkhey if we implement a pagination mechanism, it looks like technical choices should be consistent with extensibility of the endpoints. I'm not sure this is related

REST APIs are not dedicated to *our* frontend but are an application programming interface for potentially any client.

**Comment by grignards** [comment]
> @grignards After thinking about using sqlakeyset vs before_event_id, i do think, we may rethink about it for consistency.
> Here event_id does work only because we don't return multiple message with same event id to user, but in case we need multiple column to do the "offset id", it does not work.
> 
> sqlakeyset may need a bit more work but allow us to have a consistent parameter for frontend to use for offset-free pagination in all tracim.

Most (if not all) our API do have an integer id as key, if a composite key scenario appears it is possible to handle it by putting the columns in the response and have corresponding parameter(s) in the query.

**Comment by inkhey** [comment]
> > if we go for a offset-free mecanism, one possibility is using sqlakeyset
> 
> @inkhey if we implement a pagination mechanism, it looks like technical choices should be consistent with extensibility of the endpoints. I'm not sure this is related

Not sure to understand the idea. Problem here is how to deal with offset-free pagination (which is the only efficient way to pagination). As we made a decision here, we will be able to use the same logic for all other place where we do need pagination.
We currently as very few endpoint that does pagination using unefficient way (offset)

> 
> REST APIs are not dedicated to _our_ frontend but are an application programming interface for potentially any client.

I do agree, problem here is what is the best solution for an offset-free pagination api.

- @grignards suggest we do use "before_<something>" fields, This work in this case but mean different field name for each endpoints, and multiples fields for composite keys scenario. In this case, it's the frontend role to fill the correct ids to get the next page.

- sqlakeyset solution in the other hand, mean using sqlakeyset lib and use a "bookmark_page" (don't know which naming is the best) string field, that contain all the information needed to go to a specific page efficiently, it's the same field name for all endpoint that do use this solution. In this case, it's the backend role to field the previous/next page bookmark that the frontend will use.

**Comment by raphj** [comment]
I'm not familiar with the notion of "offset-free" pagination, can you explain @inkhey?

**Comment by inkhey** [comment]
> I'm not familiar with the notion of "offset-free" pagination, can you explain @inkhey?

French explanation, it's really sql related:
https://use-the-index-luke.com/fr/sql/resultats-partiels/recuperer-la-page-suivante

**Comment by grignards** [comment]
@inkhey what I see as pro/cons for the 2 implentations:

||Pro|Con|
|-|---|---|
|**Paged-based (sqlakeyset)**|same attribute|"external" attribute, cannot change page size without restarting paging|
|**Attribute-based**|only "internal" attribute(s), arguably easier to understand for simple cases|query parameters are different for each case|

**Comment by grignards** [comment]
> I'm not familiar with the notion of "offset-free" pagination, can you explain @inkhey?

The main idea is to avoid a full table scan: when using offset, the database has to go through all previous rows to know which one is the first to return. When using an ordered query you can define indexes on the ordered column set so that the database can almost directly jump to the first returned row.
This is mainly useful for big tables.

**Comment by inkhey** [comment]
After discussion with @grignards and @metzgegu , We decided to use `sqlakeyset`

**Comment by inkhey** [comment]
I got an issue with python 3.5 and `sqlakeyset` library as the library do use "fstring" syntax.
Created an issue in the upstream project about this: https://github.com/djrobstep/sqlakeyset/issues/32

Not sure how we should deal with this problem (drop python3.5/ debian stretch support ? Find a workaround ?)

note: 
- python 3.5 end of life is september 2020 (https://devguide.python.org/#status-of-python-branches)
- stretch support is already stopped : https://wiki.debian.org/fr/DebianReleases

**Comment by inkhey** [comment]
> I got an issue with python 3.5 and `sqlakeyset` library as the library do use "fstring" syntax.
> Created an issue in the upstream project about this: [djrobstep/sqlakeyset#32](https://github.com/djrobstep/sqlakeyset/issues/32)
> 
> Not sure how we should deal with this problem (drop python3.5/ debian stretch support ? Find a workaround ?)
> 
> note:
> 
>     * python 3.5 end of life is september 2020 (https://devguide.python.org/#status-of-python-branches)
> 
>     * stretch support is already stopped : https://wiki.debian.org/fr/DebianReleases

The support for python 3.5 as been fixed in last `sqlakeyset` version, so there is no blocking point here for pagination.
Verified manually on docker python3.5/Stretch.

**Comment by lebouquetin** [comment]
@inkhey in the description of your issue, you put all informations related to an author, including email / is_deleted / is_active / etc. What is the standard user structure shared with another user not being an administrator?

I'm not sure your proposal is ok on a security/confidentiality base

**Comment by inkhey** [comment]
> @inkhey in the description of your issue, you put all informations related to an author, including email / is_deleted / is_active / etc. What is the standard user structure shared with another user not being an administrator?

It's the current TLM user structure, we do not have different structure here (for TLM), having different structure will complexify the TLM mecanism.

About user we do have:
UserSchema (this one)
UserDigestSchema (limited one with only username/public_name/user_id/avatar_url) <- this one is probably the one you are thinking about.
UserDiskSpaceSchema(user_id, allowed_space, user_space, user(digest schema))

> 
> I'm not sure your proposal is ok on a security/confidentiality base

**Comment by grignards** [comment]
> @inkhey in the description of your issue, you put all informations related to an author, including email / is_deleted / is_active / etc. What is the standard user structure shared with another user not being an administrator?
> 
> I'm not sure your proposal is ok on a security/confidentiality base

@lebouquetin I re-checked, workspace members currently have access to this information (through https://algoo.tracim.fr/api/doc/#/Workspaces_%3E_Members/get_api_workspaces__workspace_id__members) which is accessible to any member of the workspace. Do you think we shouldn't disclose mail or other information to all workspace members?

**Comment by lebouquetin** [comment]
> workspace members currently have access to this information (through https://algoo.tracim.fr/api/doc/#/Workspaces_%3E_Members/get_api_workspaces__workspace_id__members) which is accessible to any member of the workspace. Do you think we shouldn't disclose mail or other information to all workspace members?

I don't know actually. do not change anything right now but I think we should write somewhere what the rules are in order to be clear about data confidentiality strategy. Do you agree? @grignards

**Comment by grignards** [comment]
> I don't know actually. do not change anything right now but I think we should write somewhere what the rules are in order to be clear about data confidentiality strategy. Do you agree? @grignards

Yes, I will initiate this document.

**Comment by PhilippeAccorsi** [comment]
api visible here http://localhost:7999/api/doc/
