### ISSUE TITLE
Feat: Allow WebDAV authentification with username

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3060]
## Feature description

A user should be able to login on WebDAV using his username **or** his email.

## Context

The email is not mandatory anymore with #2829 work.

## Prerequisites

N/A

## Impacted components

- *backend*

## Extra information

- the modification has to be done in `backend/tracim_backend/lib/webdav/authentification.py`

**Comment by inkhey** [comment]
@grignards It this ok, can we merge this ?
