### ISSUE TITLE
Feat: Support username in tracimcli user commands

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3061]
## Feature description

- [x] `create`
  - [x] replace `-l` by `--email` and `--username` options (one of the two must be given)
  - [x] allow `--send-email` only if email is given
- [x] `delete`: allow username or email, treat parameters with `@` inside as emails, usernames otherwise
- [x] `update`: 
  - [x] must be split from `create implementation`.
  - [x] allow username or email, treat parameters with `@` inside as emails, usernames otherwise
  - [x] add `--username` and `--email` options to update username/email
- [x] `anonymize`: 
  - [x] allow username or email, treat parameters with `@` inside as emails, usernames otherwise
  - [x] set username to NULL

## Context

The email is now optional with #2829 work.

## Prerequisites

None

## Impacted components

- *backend*

## Extra information

N/A

## Implemented solution
see https://github.com/tracim/tracim/pull/3093.

This PR solve #3061 but also refactor tracimcli command and auth method as:
- Tracimcli command code was messy and uncomplete (no proper validation for example).
- some related problem are found when refactoring auth method used by tracimcli to limit the number of way to authenticate with a login (email/username). 

Tracimcli command:
- add better validation for user create/update command using same rule an validator than http api.
- allow to set more field in user create/update command, allow to use both username and email in all tracimcli user command as login(s).
- allow to not set password with user create command, with autogenerated password feature is used with "send-email" parameter
- refactor tracimcli user create/update code in order to be more clear, these two command are splitted and have mostly specific code but simpler.
- update anonymization to set username to NULL when anonymizing user.

Auth Method:
- fix ldap/remote and Api Token auth to support both username and email as login
- refactor auth method to use  new method get_one_by_login when possible/useful to have only one way to distinct username and email login.

Documentation:
1. document `email.required` parameters in config file
2. update documentation for auth methods to clarifiy behavior, especially when email.required is set to true, which can be confusing.
3. update documentation for tracimcli user command in order to be more clear.

**Comment by raphj** [comment]
> allow username or login, treat parameters with `@` inside as emails, usernames otherwise

Suggestion: except if the @ is at the beginning of the parameter to allow `@user` to be handled as a username.

> update: must be split from create implementation.

What does this mean/imply?

**Comment by grignards** [comment]
> > allow username or login, treat parameters with `@` inside as emails, usernames otherwise
> 
> Suggestion: except if the @ is at the beginning of the parameter to allow `@user` to be handled as a username.
Sorry, I didn't see your remarks earlier.

I think that the `@user` form should be reserved for mentioning a user in a comment/..., but not for login or administrative operations. Is the username always prefixed with `@` in the frontend (I see that the placeholder for username has `@username` in it which is misleading as it is removed if given.

> > update: must be split from create implementation.
> 
> What does this mean/imply?

The current implementation of create/update was the same as the created user login was his email, but now create takes one email parameter and one username parameter.
Update now can be done by giving either the email or username to the command.

**Comment by lebouquetin** [comment]
@raphj @grignards two rules:

- the `@` char is not allowed in a username
- an email can't start with `@`

If your user name is `lebouquetin` on twitter, for exemple, you do not login by typing `@lebouquetin` but only `lebouquetin`. We shoudl have similar behavior (I think this is what you say @grignards)

**Comment by grignards** [comment]
> If your user name is `lebouquetin` on twitter, for exemple, you do not login by typing `@lebouquetin` but only `lebouquetin`. We shoudl have similar behavior (I think this is what you say @grignards)

Yes, this is what I meant.

**Comment by PhilippeAccorsi** [comment]
- [ ] update cli documentation (https://github.com/tracim/tracim/blob/develop/backend/doc/cli.md)

**Comment by metzgegu** [comment]
Verified on branch.
