### ISSUE TITLE
Refactor frontend_app_file update with new real time events feature

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#3065]
## Feature description

Refactoring of `frontend_app_file` with the new real time events feature, tracim live message
Related to #2850

## Context

The feature is already partially implemented in `frontend` and it need to be implemented in each content app

## Implementation

Refactoring the App file (File.jsx and PopupCreateFile.jsx) with the HOC TracimComponent from frontend_lib in order to add handlers for CustomEvent and TracimLiveMessage
TLM handlers update the state according to TLM datas

## Impacted components

- `frontend_app_file`

**Comment by gbonaspetti** [comment]
I found two problems during the tests:
- The shares are not updated.
![shares](https://user-images.githubusercontent.com/35422692/83625019-9cf07000-a593-11ea-968a-baea5ca70f43.png)

- The document title is not updated when it is deleted.

**Comment by metzgegu** [comment]
For the v3.0.0 the backend doesn't send TLM when a file is shared

**Comment by gbonaspetti** [comment]
When someone changes the status of the file while we are editing the description, it is still possible to validate the edition but the change is lost.

![description](https://user-images.githubusercontent.com/35422692/83737201-f8356780-a652-11ea-9f39-608471c7b915.gif)

**Comment by metzgegu** [comment]
In order to fix this issue, a message is displayed to tell the user that it can not change description anymore
See :
![StatusChanged](https://user-images.githubusercontent.com/31687635/83758460-69d0de00-a672-11ea-82fe-663579af028e.gif)

**Comment by gbonaspetti** [comment]
Test and verified on branch.
