### ISSUE TITLE
Refactor frontend_app_html-document for Tracim Live Message feature

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3066]
## Feature description

Refactor `frontend_app_html-document` for Tracim Live Message feature.
- [x] Refactor TLM Event Type
    - Add a warning in the case "I am editing a document and another user made a change to the same document during this"
![refreshDocument](https://user-images.githubusercontent.com/35422692/82460803-ec29a180-9ab9-11ea-9a1b-83ead16f3a1c.png)
- [x] Refactor Custom Event

Related to #2850

## Context

The feature is already partially implemented in `frontend` and it need to be implemented in each frontend app.

## Impacted components

- *frontend_app_html-document*

**Comment by gbonaspetti** [comment]
For this refactor it will be necessary to add a warning in the case "I am editing a document and another user made a change to the same document during this". I can see two warning options:
- Use the same form as the deleted content warning
![deletedContent](https://user-images.githubusercontent.com/35422692/82455044-cbaa1900-9ab2-11ea-8bb8-128d335186f0.png)

- Make a popup

My fear of making a popup is to have many editions in a row and disturb the user with several popups at a time.
@lebouquetin @Skylsmoi @celiamgtt What do you think?

Suggestion for a sentence: `Someone made an edition, do you want to update the document? You will lose your editions.`

**Comment by lebouquetin** [comment]
@gbonaspetti popup is too intrusive, I think. A flash is ok.

In my knowledge of the way TLM are implemented, you don't know if the new version is an edition or a status change or anything else. I suggest to keep a generic-enough wording like: "The content has been modified by XXX. Refresh ?" with a title attribute on the button saying "if you refresh, you will loose current changes"

**Comment by celiamgtt** [comment]
Also ok for the flash message. We should update it to leave a margin tho ;)

**Comment by gbonaspetti** [comment]
> @gbonaspetti popup is too intrusive, I think. A flash is ok.
> 
> In my knowledge of the way TLM are implemented, you don't know if the new version is an edition or a status change or anything else. I suggest to keep a generic-enough wording like: "The content has been modified by XXX. Refresh ?" with a title attribute on the button saying "if you refresh, you will loose current changes"

I like the sentence, but I don't know if the title attribute is enough, if the user will not click `Refresh` without reading the tooltip and end up losing the changes...
You think the sentence gets too long if it is "The content has been modified by XXX. If you refresh, you will loose current changes" and a `Refresh` button

**Comment by lebouquetin** [comment]
@gbonaspetti My feeling is it's intuitive... but if you disagree, maybe a popup in this case is ok. You click on refresh (which is always the way to actualize the view) *and if you are in edition mode, then a popup warn you about loosing your changes*.

What do you think @gbonaspetti ? @celiamgtt ?

**Comment by gbonaspetti** [comment]
> @gbonaspetti My feeling is it's intuitive... but if you disagree, maybe a popup in this case is ok. You click on refresh (which is always the way to actualize the view) _and if you are in edition mode, then a popup warn you about loosing your changes_.
> 
> What do you think @gbonaspetti ? @celiamgtt ?

I think we can do it initially with the message at the top of the document, because it is less intrusive, and after a feedback from users we see if it is intuitive enough or if it is better to add a popup.

**Comment by Skylsmoi** [comment]
about this:

> In my knowledge of the way TLM are implemented, you don't know if the new version is an edition or a status change or anything else. I suggest to keep a generic-enough wording like: "The content has been modified by XXX. Refresh ?" with a title attribute on the button saying "if you refresh, you will loose current changes"

Currently, there is indeed no way of knowing. But it is creating some issues and we might introduce a way of knowing when an update is for meta data or if it is a change of the content.
It should come at the form of 2 different TLMs but this will be discussed with backend next week.

The currently opened PR is adding a html "title" attribute to the button with the warning. While it serves the needs, I think it is not visible enough.
But maybe we can wait to know more about the way of differentiating meta change from content change to settle this.

**Comment by metzgegu** [comment]
I found an issue in the current implementation :  
When 2 window is opened connected with the same account and the 2 is on edition mode, if a windows post changes, nothing appears in the second window and the file is not up to date.

See : 

![TestHTML](https://user-images.githubusercontent.com/31687635/83537829-6106cd80-a4f5-11ea-8cfc-af9fb4db70e8.gif)

**Comment by gbonaspetti** [comment]
> I found an issue in the current implementation :
> When 2 window is opened connected with the same account and the 2 is on edition mode, if a windows post changes, nothing appears in the second window and the file is not up to date.
> 
> See :
> 
> [...]

@Skylsmoi should we deal with that particular case? If yes, how? Same warning?
(the warning `the content has been modified...` does not appear because it is the **same user**, editing the same document)

**Comment by Skylsmoi** [comment]
mmh this is a pretty specific case.
I don't think we should manage it.
What would it required to do in the code to handle it ?

**Comment by gbonaspetti** [comment]
> mmh this is a pretty specific case.
> I don't think we should manage it.
> What would it required to do in the code to handle it ?

If we are just going to activate the warning, at first we should make sure that the document is put in VIEW mode (done by the function that calls API) before the update made by TLM, this can be tricky.
Another solution is to change only one condition if and deactivate the warning as soon as the document is in VIEW mode, i. e. to the tab that made the change it would activate the warning and deactivate right after.

**Comment by Skylsmoi** [comment]
I would say that, if it could be handled very easily I would be ok to handle that specific case but, as it seems a bit complicated, I think we can ignore it.

**Comment by Skylsmoi** [comment]
after discussion, it is an issue.
A specific issue has been created here:  todo, put id

But this behavior isn't blocking the merge of the PR. It will be handled later
