### ISSUE TITLE
Webdav authentication may fail if user change password and/or email

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#307]
See comment in issue #218. Check following cases :

1. login in web interface
2. login in webdav. The login must succeed

1. login in web interface
2. change email address
3. login in webdav. The login must succeed (if not, then fix it)

1. login in web interface
2. change password
3. login in webdav. The login must succeed (if not, then fix it)

In all cases, a good idea would be to generate the webdav authentication hash in one part of the code only.

The following code taken from `tracim/lib/auth/internal.py`:

```
        if user and user.validate_password(identity['password']):
            if not user.webdav_left_digest_response_hash:
                user.webdav_left_digest_response_hash = '%s:/:%s' % (identity['login'], identity['password'])
                DBSession.flush()
                # TODO : temporary fix to update DB, to remove
                transaction.commit()
            return identity['login']
```

Should be factorized somewhere else (UserApi ?) and reused everywhere in the code (change_password() and/or change_email() methods). A good naming would be something like : `check_webdav_token_and_eventually_update_it()` (a bit long;)

**Comment by algooapy** [comment]
Updating only the email address is impossible:
The `WebDAV` authentication hash is computed using the email address and the _**clear**_ password, which is only available when setting up a new password.

**Comment by algooapy** [comment]
Concerning the other part of the issue, such a method already exists in:
`tracim/tracim/model/auth.py:User.update_webdav_digest_auth`
See the following work branch:
https://github.com/tracim/tracim/compare/fix/307/webdav_auth_once_pwd_email_changed

**Comment by lebouquetin** [comment]
So, what is the status of this? If your branch is ok for all cases except email change (which can't be handled properly for webdav authentication - except retyping the password), then consider to do a PR

**Comment by lebouquetin** [comment]
last point forwarded to #363
