### ISSUE TITLE
Bug: its not possible to delete description of file

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#3072]
## Bug description & symptom

I have one description in file. I tried to delete this description so I click on `Change description` and I erase all data. I click on `Validate` and frontend show me an empty description (backend send an email so I think description is deleted correctly).

When I refresh page Description is now visible.

## Diagnostic

*Optional - explain what has been found and what is not clear yet. If unknown, write "unknown".*

## Expected

- [ ] its possible to delete desciption of file

## Context and version information

- Tracim 2.7.4

## How to reproduce

- have one file
- add description
- try to delete description (edit, select text and suppr, and validate)

## Screenshots

*Optional - add screenshots to help explain your problem.*

*Please consider sharing an [animated GIF screencast generated with peek](https://github.com/phw/peek)*

## Impacted components

*If unsure, write "unknown"*

## Extra information

**Comment by lebouquetin** [comment]
It's not UX: it's not about "improving user experience" but "making things work like expected".
If a notification is send and no error is raised, then it's a backend bug.
