### ISSUE TITLE
Webdav : paste a file with same name result in a new file (and old one deleted) instead of a new revision

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#308]
Currently : 
- suppose you have a file rapport.pdf in tracim
- if you edit it and save it through webdav, all is fine
- if you edit it out of webdav, then copy paste the new version, the behavior of webdav is : 
  1. delete rapport.pdf (with full history)
  2. create rapport.pdf as a new file (with 1 revision only)

Expected : 
in the last case, the new rapport.pdf should be created as a new revision of the old one instead of creating a new content (with a new content id)

The way to do this : 
- when deleted a file, do not chagne anything
- when creating a file:
  1. search for a file with the same name in the same folder/workspace and in the deleted state.
  2. if a deleted file with same name is found,
     1. do not create a new file
     2. reopen the old file
     3. create a new revision to the old file

To do later (in another issue) : 

- remove events of delete/undelete
- manage a delta time (eg if the old file is 3 years old, probably that the new file is not a revision of the old one)

**Comment by algooapy** [comment]
Seems to already be working as expected.

**Comment by tracim** [comment]
The behavior explained in the description is not implemented (the part called « The way to do this :»). The bug was detected on windows 7.

Test on Windows 10, then you can close if W10 behave as expected

**Comment by algooapy** [comment]
I conducted few tests with a Windows 10 VM:
- given a simple text file already in tracim,
- as mention above, editing it and saving it through webdav is fine:
  - a new version of the content is created,
- editing it out of webdav, then copying pasting the new version results in:
  - at first, a new revision with an empty file is created,
  - at second, a new revision with the actual text file is created.

We could detect the case of this empty file revision to simply ignore it when it happens.

**Comment by tracim** [comment]
@algooapy in the second case (editing out of webdav, then copy/paste), the old revisions are still in the history or not ? The problem is not the empty revision but not to loose previous revisions.

In your second test case, the result is a file with 2 revisions (the empty one + the one with the real content) or a file with more revisions (old revisions + empty revision + revision with new content) ?

**Comment by algooapy** [comment]
- "in the second case (editing out of webdav, then copy/paste), the old revisions are still in the history or not ?"
Yes.
- "In your second test case, the result is a file with 2 revisions (the empty one + the one with the real content) or a file with more revisions (old revisions + empty revision + revision with new content) ?"
The result is a file with more revisions:
  - revision with new content,
  - empty revision,
  - old revisions.

**Comment by tracim** [comment]
Ok, so its fine :) close this issue and open a new one for the empty revision (put the new issue in technical improvment milestone)

**Comment by xandercagexxx** [comment]
verified. ubuntu 17.04
