### ISSUE TITLE
Feat: Pushpin in CI

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#3081]
## Feature description

We need to clarify how we use puhpin in CI for both pushpin backend test and integration test with cypress.

## Context

Current backend test run a local pushpin instance with specific script.
but as we get issue with local dev pushpin, this mecanism may be not really reliable:
https://github.com/tracim/tracim/pull/3078

We need also to find a proper way to run pushpin for cypress.

**Comment by inkhey** [comment]
Current implementation in https://github.com/tracim/tracim/tree/feat/2850__implement_live_message_for_dashboard
is:
- install pushpin and run pushpin locally for some specific dev backend test (pushpin is runned by python code)
- install pushpin but disable pushpin and zurl daemon then run cypress pushpin docker for cypress test, set cypress configuration to 7999 port (defaut pushpin config).

This is done this way because :
- python code that run pushpin locally does work as we do not do multiple async call to pushpin, and was made before we see the issue in production with the unreliable behavior of pushpin install in some configuration
- cypress test support was done later and follow the way cypress test are runned by frontend developer. Port 7999 is same for both pushpin_cypress and pushpin for dev docker as pushpin docker is not made to allow changing the port used, it's not possible to map it in another way as we do need to use host network mode in order to support reverse proxy setup.

**Comment by Skylsmoi** [comment]
> Current implementation in https://github.com/tracim/tracim/tree/feat/2850__implement_live_message_for_dashboard

pr of related branch:
https://github.com/tracim/tracim/pull/3074

**Comment by grignards** [comment]
With #3100 I modified the pushpin launch for tests (both backend and cypress) to use always use docker-compose (for two reasons: having the pushpin container config in one place and with the goal to use docker-compose to ease launching of other backend components).

**Comment by inkhey** [comment]
@grignards I do suggest to close this issue as #3100 clarify usage of pushpin in CI.
