### ISSUE TITLE
Bug: Files created in session folders are never deleted

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#3091]
## Bug description & symptom

Tracim creates files in the `sessions_data/` and `sessions_lock` folders each time the Tracim login page is opened.

These files are never deleted, which clutters these folders. On one Tracim instance we have a total of 10M files just in these two folders. This uselessly increases the time to backup data and the space used by Tracim.

## Expected

- [x] explain how the mechanism work
- [x] We need a solution to clean existing installations without breaking them. We need to know quickly what we can done (before we make changes in the Tracim code)
- [x] explore @lebouquetin's idea to use Redis to store `sessions_data` and `sessions_lock` with Docker. -> Added support for redis storage.

## How to reproduce

- delete all files/folders in `sessions_data/` and `sessions_lock`
- go to the login page
- look at files and folders created in the `sessions_data/` and `sessions_lock` folders

## Implemented Solution:

See https://github.com/tracim/tracim/pull/3161
- add Documentation how to upkeep file backend session 
- adapt code to support any kind of session supported by beaker, document redis based session
- solve datetime issue related to use of timezoned date instead of utc one.
- remove reissue time and the concept of reuissing new session after some time, this is not required as beaker does update timeout at each access and this create lot of unneeded session.
- fix the issue in the code to avoid the creation of sessions for user that are not logged in.

**Comment by inkhey** [comment]
These dirs can be safely deleted. The only think can may potentially cause trouble is in the case a user session is deleted at the same time user want to connect, but it's very unlikely and i will break anything.
This will break user active session, so, it's more something to do when we have to stop tracim instance.

To be more restrictive, we can do this:
`
find . -type f -mtime +10 -print -exec rm {} \;
`
in both session_lock and session_data dir. this will delete file older than 10 days (default session timeout in tracim is 604800 session = 7 day)

**Comment by lebouquetin** [comment]
@inkhey dropping old sessions is not something to do when service is stopped:

- first we should be able to upgrade without stopping the instance (this is not yet possible according to the way we deploy, but technically, there are not restriction about this)
- second: even if tracim is stopped it does not mean we accept to drop all opened sessions.
- third, we must have a way to drop sessions during live execution (the `find` command seems to do so)

The issue is not about dropping session data but about "how we should/must manage it".

I don't know if you are still working on this issue, but the two checkbox must be checked soon (your current comment can be considered as a hotfix)

**Comment by inkhey** [comment]
@lebouquetin @PhilippeAccorsi @grignards 
My PR solve the issue by reducing a lot the session created an permitting usage of redis backend.
They do exist some unclear point:
- Should "file" stay the default ? 
- Should "redis" backend set as default for docker image ?

**Comment by grignards** [comment]
> #3161
> 
> @lebouquetin @PhilippeAccorsi @grignards
> My PR solve the issue by reducing a lot the session created an permitting usage of redis backend.
> They do exist some unclear point:
> 
>     * Should "file" storage stay the default ?

I would say yes as we do not require redis currently for Tracim and the file storage is functional provided the now documented "manual" deletion of session files.

>     * Should "redis" backend set as default for docker image ?

I think we can as redis is already available in the docker image and :
- the only "downside" I see is that upgrading the docker image will lose currently active sessions and force users to login again.
- they provide the solution to this issue without having to add a mechanism to handle the deletion of expired session files.

>     * Should fix for now/utcnow reported in another ticket/issue ? pro: a bit more safe now, cons: unconsistent mecanism will stay in code longer.

I think you can change the session code `utcnow`/`now` but not the content share and read status  as this would change Tracim's behavior on non-UTC servers. Furthermore as we discussed it is difficult to provide a totally satisfying solution to handle migrating those datetimes. I would recommend to create another issue for this.

**Comment by PhilippeAccorsi** [comment]
> * Should "file" storage stay the default ?
> 
I think this is a default usage yes.

> * Should "redis" backend set as default for docker image ?
> 
I think its a good idea with docker.

> * Should fix for now/utcnow reported in another ticket/issue ? pro: a bit more safe now, cons: unconsistent mecanism will stay in code longer.

I don't know.

**Comment by inkhey** [comment]
So, i do:
- remove now/utcnow code here : https://github.com/tracim/tracim/pull/3161/commits/4c687da259405a54087647fbb9be9c4d34ffa2a2
- i will check how complex can be support in docker.

**Comment by inkhey** [comment]
Just tried to have docker using out of the box redis:
https://github.com/tracim/tracim/commit/7b9d626c20f49d692e20c5f58fdae0eec936797e

Note: This does not allow easily to switch old config file to redis as we do already rely on config file.

**Comment by inkhey** [comment]
> Just tried to have docker using out of the box redis:
> [7b9d626](https://github.com/tracim/tracim/commit/7b9d626c20f49d692e20c5f58fdae0eec936797e)
> 
> Note: This does not allow easily to switch old config file to redis as we do already rely on config file.

Just checked it manually, work as expected.

**Comment by raphj** [comment]
I just checked that no session files are created when accessing the login page on develop.
