### ISSUE TITLE
Feat: Add event types for each content type

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3095]
## Feature description

Add content_type in event_type field for content related events.

Replace `content.(modified|created|deleted)` by `content.(modified|created|deleted).(file|html-document|folder|comment|thread)` when generating events and TLMs.

The generated `content` field shall include the same information as returned by the corresponding HTTP API:

- `file`: `FileContentSchema`
- `folder`, `html-document`, `thread`: `TextBasedContentSchema`
- `comment`: `CommentSchema`

## Context

- most frontend reactions to TLMs are specific to a content-type and need all information on the content (including the specific values)
- still easily possible to filter on all content events as the event it still named `content.modified.xxx`

## Prerequisites

None

## Impacted components

- *backend*
- *frontend*

## Implemented solution:

see https://github.com/tracim/tracim/pull/3101

1.add entity_subtype to "events" table
2.change event_type in TLM to add the type of content.
3. add content-type to comment schema.
4. add current_revision_type to content schema.
5. remove warning in pytest

**Comment by lebouquetin** [comment]
@grignards I do not understand this issue... what is currently send through TLM?

**Comment by grignards** [comment]
> @grignards I do not understand this issue... what is currently send through TLM?
> 
> We do not have `event_type` for each TLM?

We have an `event_type` , currently for content messages :
- `event_type` can be `content.(created|modified|deleted)`
- `content` field contains the `content_type`, but is not specialized by `content_type`: it only contains information shared by all content types, not specific ones (file size/...).
- adding `content.(file|…).xxx` `event_type` was better to avoid a polymorphic `content` field.

**Comment by lebouquetin** [comment]
@grignards so it's not possible to have a generic handler for all content, is it? I mean: if I want to log every content created events, I sometimes need to search for information in content.file node, sometimes in content.thread, etc?

**Comment by Skylsmoi** [comment]
as an update:
The final new spec is adding the content type at the end of the event name.
`content.[created|modified|deleted].[file|html-document|thread]`
