### ISSUE TITLE
Feat: Handle TLM for app admin workspace user

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#3103]
## Feature description

Refactor the app admin workspace user with TLM usage

## Context

The v3.0 is the live update version. Apps must trigger update through this process

## Impacted components

App Admin workspace user

## Implementation

- The list of user is updated when a user is added/modified/deleted by another user/frontend
- The list of workspace is updated when a workspace is added/modified/deleted by another user/frontend

**Comment by PhilippeAccorsi** [comment]
- [x] The list of user is updated when a user is added/modified/deleted by another user/frontend **(deleted user not yet implemented in frontend)**
- [x] The list of workspace is updated when a workspace is added/modified/deleted by another user/frontend

Tested on branch.
