### ISSUE TITLE
Feat: Handle TLM for app Agenda and make refresh warning coherent between apps

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#3104]
## Feature description

Refactor the app agenda with TLM usage

## Context

The v3.0 is the live update version. Apps must trigger update through this process

## Impacted components

- frontend_app_agenda

## Expected

- [x] Handle user changes: If the user's info are changed and he has the agenda open, the information is updated in real time in the code, but in the interface a message appears on the right side of the screen asking if he wants to refresh the agenda (this will prevent the agenda from being refresh automatically while the user is creating an event). This change is only visible in "My agendas".
- [x] Handle shared space changes: If the shared space is modified (like the title is changed) the information is updated in real time in the code and if it is in the agenda of a specific shared space the breadcrumbs are also updated in real time. On the "My agendas" page a message appears on the right side of the screen asking if he wants to refresh the agenda (this will prevent the agenda from being refreshed automatically while the user is creating an event).
- [x] Adapt the 'modified content' warning to be a consistent design between apps that works for both an appFeature and an appFullScreen. (update *frontend_app_html-document*, *frontend_app_thread*, *frontend_app_file*)

Notes: 
- The events created in the calendar are not handled in this issue because there is currently no TLM generated by the backend for this, we are in pure CALDAV. 
- The cases of deletion of the shared space, loss of rights and disable of the agenda feature are not handled in this issue. See https://github.com/tracim/tracim/issues/3198

**Interface example**
- appFullScreen

![Screenshot from 2020-06-23 16-22-37](https://user-images.githubusercontent.com/35422692/85416407-b66f5100-b56e-11ea-808c-ed41c92bb872.png)

- appFeature

![Screenshot from 2020-06-23 16-22-13](https://user-images.githubusercontent.com/35422692/85416367-a8b9cb80-b56e-11ea-90fe-505c6c113f82.png)

*The interface above was made together with the designer @celiamgtt, it was decided to remove the coloured background from the warning as it would generate a line cutting the screen into an appFullScreen and by simplifying the button to be cleaner and more pleasant.*

**Comment by PhilippeAccorsi** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
wait merge to close.
