### ISSUE TITLE
Feat: Handle TLM for app Collabora

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#3105]
## Feature description

Refactor the app collabora with TLM usage

## Context

The v3.0 is the live update version. Apps must trigger update through this process

## Impacted components

App collabora

## Extra info

I'm not sure there is a lot to do here

**Comment by lebouquetin** [comment]
@Skylsmoi what do you think we'll have to do for collabora application?

**Comment by Skylsmoi** [comment]
not much, I'm not even sure there is anything to do.

There might be the setHeadTitle() function that calls api everytime to get the workspace label. And now, with TLm, it'll can only call it once and listen to the workspace.modified TLM to know when the label change

There is also the popupCreateContent that will need a few refactor, either for TLM and customEvent.

**Comment by Skylsmoi** [comment]
What I did:
- handle TLM for creation popup
- code cleaning in app Collabora
- add unit tests for app collabora

**Comment by Skylsmoi** [comment]
For Tester:
No new feature. But everything that existed must still work.
You must be able to create an office document and edit it.
The warning "there is a new version, refresh ?" is handled by the app File and is out of context of this PR.
Because the app Collabora only handles:
- the creation popup for office document
- the display oh the button "edit online"
- the opening of the collabora iframe when clicking on the "edit online" bouton

**Comment by PhilippeAccorsi** [comment]
All seems to work correctly on branch.

**Comment by gbonaspetti** [comment]
Verified on develop.
