### ISSUE TITLE
Feat: Handle TLM for app folder advanced

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#3106]
## Feature description

Refactor the app folder advanced with TLM usage

## Context

The v3.0 is the live update version. Apps must trigger update through this process

## Impacted components

App Folder advanced

## Implementation

- Folder title is updated silently when the folder is changed by another user/browser
- The list of checked content types is updated silently when it is changed by another user/browser
- The "this folder is deleted" warning is displayed if the folder is deleted by another user/browser

**Comment by PhilippeAccorsi** [comment]
When I tested this issue, I have seen something broken, explained here #3217 
Need more test when database migration is fixed.

**Comment by gbonaspetti** [comment]
Verified on develop.
