### ISSUE TITLE
Feat: Handle TLM for app share folder

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#3108]
## Feature description

Refactor the app share folder with TLM usage

## Context

The v3.0 is the live update version. Apps must trigger update through this process

## Impacted components

App share folder

## Extra info

I'm not sure there is a lot to do here
Because we haven't plan any TLM for share folder related features

**Comment by metzgegu** [comment]
This app doesn't need TLM handlers because no TLM for share feature are implemented yet.
This app only need a CustomEvent refactor with the new TracimComponent component

**Comment by gbonaspetti** [comment]
Verified on develop.
