### ISSUE TITLE
Feat: Handle TLM for app Thread

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#3109]
## Feature description

Refactor the app thread with TLM usage

## Context

The v3.0 is the live update version. Apps must trigger update through this process

## Impacted components

App thread

**Comment by Skylsmoi** [comment]
implemented TLM for app Thread

**Comment by inkhey** [comment]
verified on branch.

**Comment by gbonaspetti** [comment]
Verified on develop.
