### ISSUE TITLE
Feat: Handle TLM for app workspace

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#3110]
## Feature description

Refactor the app workspace with TLM usage

## Context

The v3.0 is the live update version. Apps must trigger update through this process

## Impacted components

App workspace

## Extra info

I'm not sure there is a lot to do here
As a reminder, this app is used to create the popup create sharespace

**Comment by metzgegu** [comment]
This app doesn't need TLM handlers because after a workspace is created, the next step is triggered by the result of the POST request and not a TLM `sharespace.created`,
This app only need a CustomEvent refactor with the new `TracimComponent` component

**Comment by gbonaspetti** [comment]
Verified on develop.
