### ISSUE TITLE
Handle timeline when a new revision of a content is created in App file

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#3116]
## Bug description & symptom

The app file need to handle timeline when a new revision of a content is created

## Impacted components

- frontend_app_file

**Comment by metzgegu** [comment]
In order to add TLM support for the timeline, it need to use the `addRevisionFromTLM` function from `frontend_lib` when the content is modified, deleted or restored.

**Comment by gbonaspetti** [comment]
Doing the tests I see that the date of comments is not "user friendly" (i.e. 2020-06-16T08:19:46Z should be `less than a minute ago`)

**Comment by lebouquetin** [comment]
@gbonaspetti @metzgegu this should not be changed - we have a source of information in ISO 8601 format and we must keep on showing it in a user-friendly manner.

I'm afraid by this comment @gbonaspetti because for me the refactor should be only about triggering the new data, not rework the way the information is parsed/processed

**Comment by gbonaspetti** [comment]
> @gbonaspetti @metzgegu this should not be changed - we have a source of information in ISO 8601 format and we must keep on showing it in a user-friendly manner.
> 
> I'm afraid by this comment @gbonaspetti because for me the refactor should be only about triggering the new data, not rework the way the information is parsed/processed

Yes, I was doing the quality tests, the comment was a bug report so the @metzgegu can fix it in the PR.

**Comment by lebouquetin** [comment]
I understand your feedback @gbonaspetti , my comment is : "how we can break something which should not be modified"

**Comment by metzgegu** [comment]
The distance date is created by the frontend with the data received from the API.
In this case I forgot to use the frontend function which return the distance date in the handler which handle TLM message `comment.created`, in order to have the same behavior as API handler.

**Comment by gbonaspetti** [comment]
Verified on develop.
