### ISSUE TITLE
Bug: clarify username validity at forms and email requirement

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3128]
## Bug description & symptom

Some points are necessary to clarify username validity at forms and email requirement.

- [x] explanations of the characters allowed in the username should be always visible
- [x] the username should be validated while typing and not only at the end by validating the form
- [x] disable submit button if e-mail is required and its field is empty
- [x] change placeholder `New @username` to `New username`

## Impacted components

- frontend
- frontend_app_admin_workspace_user

**Comment by gbonaspetti** [comment]
In addition to leaving the message of allowed characters always visible, error messages appear while you type the username, the same way that the message of username availability appeared. Now, the submit button is only enable if the user enters an e-mail.

**Comment by metzgegu** [comment]
Currently the PR doesn't validate all allowed characters
See : 
![Testdz](https://user-images.githubusercontent.com/31687635/83882428-6442c900-a742-11ea-83ec-7f52fd8bfe15.gif)

**Comment by grignards** [comment]
>     * the e-mail must be required

@raphj @gbonaspetti 
I think this is not always the case: it is possible to setup the backend with optional email now than we have a username. The config's option is visible on `/api/v2/system/config`. See #2829 and #3047.

**Comment by inkhey** [comment]
verified on branch
