### ISSUE TITLE
Feat: Have a request identification given by the associated TLM (frontend part)

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#3129]
## Feature description

When frontend POST or PUT something, it will add an id is the request (Body ? Header ?).
And, when the backend will generate the TLM associated with this modification, it will give back it.

## Todo list
- [x] specify this id (header, body, name, type ...)
- [x] backend implementation
- [x] frontend implementation

## Context

This will allow to handle this specific case https://github.com/tracim/tracim/issues/3066#issuecomment-637611391

## Impacted components

backend
frontend
apps

## (future) Implemented solution:
https://github.com/tracim/tracim/pull/3144
- Frontend can send `X-Tracim-ClientToken` Header for any request to backend.
- This header will set "client_token" field of TLM created from these request with the header value.

**Comment by grignards** [comment]
Like we discussed the id should be unique for a (user, browser, tab) tuple. making it unique/request is simpler but has the default of being unpredictable for frontend components that have not originated the request.
I don't know if the case to have an special case in a separate component is realistic though…

**Comment by grignards** [comment]
In backend this shouldn't be a big work as we already have access to the current (== authentified) user when creating the event/message. So we "just" have to add this id to the current user object.

**Comment by lebouquetin** [comment]
what about a uuid token generated at JS load time? IE in the first line of Tracim javascript code executed? Or when the store is setup?

Maybe something like `<ip_md5>-<userid>-<browser-string-md5>-<uuid>` would allow to easier investigate in case of bug? is it overkill?

**Comment by grignards** [comment]
> Maybe something like `<ip_md5>-<userid>-<browser-string-md5>-<uuid>` would allow to easier investigate in case of bug? is it overkill?
> 
`user_id` is already present in the TLMs (in author field). Including the ip address hash could have subtle effects if the same client's computer/phone changes IP while using Tracim (provided the id is updated in these cases).

Storing the id in the frontend's store will lead to losing it if the tab is reloaded but this doesn't seem a problem for our need.

**Comment by grignards** [comment]
>  specify this id (header, body, name, type ...)

I would be in favor of a request header for transmitting the id as it is orthogonal to what it's done in the request (kinda like the authentication cookie).
Also this will be much simpler to implement than transmitting it through the request's body/query parameters.

I would use a string type which will be "opaque" for the back-end: we will only copy it to the messages without interpreting it or enforcing any kind of validation.

As for its name… `client_id` in the author field of TLMs ?
For the request's header: `X-Tracim-ClientId`.

**Comment by grignards** [comment]
> When frontend POST or PUT something,

It could be transmitted in all requests, independently of how they are created (at a minimum DELETE is also required). Is it easy to add such a "middleware" function to add the client_id header in all requests (without having to modify every request made) ?

**Comment by Skylsmoi** [comment]
> Is it easy to add such a "middleware" function to add the client_id header in all requests (without having to modify every request made) ?

That won't be an issue for frontend and apps.

**Comment by Skylsmoi** [comment]
> As for its name… `client_id` in the author field of TLMs ?
I'm not a fan of having a property in the `author` field that isn't related to the backend user model. Frontend or apps might copy every properties of the `author` field is some cases. This would make the `client_id` appears in the data object of apps.

Could it have it's specific field at the root of TLM body ?

> For the request's header: `X-Tracim-ClientId`.
I'm ok for this name.

Side note : Since this `client_id` will be handled by TLM handlers, I don't think that receiving it through header is great, it would make the handler to make conditions from the body and the header it received like so:
``` javascript
if (
  response.body.author.user_id === connectedUser.id &&
  response.header['X-Tracim-Client'].client_id === globalThis.localClientId
) {
```
the above snippet is purely fictional

**Comment by grignards** [comment]
> > As for its name… `client_id` in the author field of TLMs ?
> 
> I'm not a fan of having a property in the `author` field that isn't related to the backend user model. Frontend or apps might copy every properties of the `author` field is some cases. This would make the `client_id` appears in the user object of apps or frontend
> 
> Could it have its specific field at the root of TLM body ?

Yes this is not a problem.

**Comment by grignards** [comment]
@Skylsmoi Should this issue correct the behaviour seen in https://github.com/tracim/tracim/issues/3066#issuecomment-637611391 too ?

**Comment by Skylsmoi** [comment]
not natively but we can now handle this specific case yes
