### ISSUE TITLE
Bug: fix handleContentModified at frontend_html_document

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3135]
## Bug description & symptom

Unnecessary code and better programming practices at handleContentModified.

- [x] remove localStorage manipulations
- [x] use only one setState
- [x] update refresh content should show the right content (see gif in this issue comments)

## Impacted components
- frontend_app_html_document

**Comment by metzgegu** [comment]
When I edited the document at the same time in another window and with different account,
The content doesn't update well, see :

![Test modified](https://user-images.githubusercontent.com/31687635/83852440-0dbe9600-a714-11ea-89bb-add81c2f767b.gif)

**Comment by inkhey** [comment]
verified on branch.
