### ISSUE TITLE
Bug: Events/messages aren't generated with webdav requests

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3145]
## Bug description & symptom

The webdav changes do not create events/messages.

## Diagnostic

Missing initialization of context in webdav application.

## Expected

Webdav should generate events/messages as in the web application.

## Context and version information

On develop.

## Screenshots

*Optional - add screenshots to help explain your problem.*

*Please consider sharing an [animated GIF screencast generated with peek](https://github.com/phw/peek)*

## Impacted components

- *backend*
- *webdav*

## Extra information

*Optional - add any useful information to understand and develop the feature*

**Comment by lebouquetin** [comment]
@grignards I'm afraid by this issue. The event mechanism must be in tracim core features. This issue let me think that it is not implemented like this...
