### ISSUE TITLE
preview-generator pagination not working correctly

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#315]
Currently : 

1. I upload a pdf with 2 pages, the preview is generated
2. On the page, I click on right to go to page 2
3. I click on the image to get it in large
4. when in large, I click on left

Result : I do not go back to first page
Expected : go back to previous page

**Comment by Skylsmoi** [comment]
reopening since fixed is not merged yet

**Comment by tracim** [comment]
fixed with https://github.com/tracim/tracim/pull/379
