### ISSUE TITLE
preview-generator : parameter pdfAvailable = false not taken into account

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#316]
Currently : 
- I upload a JPEG file
- I get the preview with buttons to download "full pdf" and "current page"
Note : the parameter pdfAvailable est bien à false : 

`
                    modifiedAt: 'août 11 at 01:25',
                    owner: 'Global manager',
                    sourceLink: '/workspaces/1/folders/1/files/3/download?revision_id=latest',
                    pdfAvailable: false
`

Expected : 

- do not show PDF download buttons if the pdfAvailable parameter is false

**Comment by Skylsmoi** [comment]
reopening since fix is not merged yet
