### ISSUE TITLE
Feat: Update develop with recent fixes from branch maintenance/2.7

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#3160]
## Feature description

Some fixes has been added to the branch maintenance/2.7 that aren't on develop.

## Context

They must be added to be able to release the 3.0

## Prerequisites

Fixes for the video player must be done

## Impacted components

frontend
backend

**Comment by PhilippeAccorsi** [comment]
All commit from maintenance/2.7 (about new release 2.7.5) can be added in develop.

**Comment by PhilippeAccorsi** [comment]
Tested on develop.
