### ISSUE TITLE
Feat: force minimal version of yarn 2 that does not have issues with checksum in yarn.lock

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3169]
## Feature description

We need to check the version of Yarn 2 and update it if it is too ancient during the installation of the frontend dependencies.

The related pull request requires Yarn v2.0.0-rc.34+.

## Context

Older versions of yarn 2 rewrite the entire yarn.lock file, introducing bogus `2/` or `3/` prefixes to the checksum. We did not find anything about this issue on the internet but the last version (2.0.0-rc.34) seems to fix this.

- *frontend*

**Comment by raphj** [comment]
And since yarn -v takes more than 0.5 seconds to run, I limited the usage of this command to the strict minimum.

**Comment by Skylsmoi** [comment]
You mean it was a bug in the rc33 that got fixed in rc34 ?

**Comment by raphj** [comment]
This was a bug in yarn 2 < rc34

**Comment by Skylsmoi** [comment]
cool

**Comment by metzgegu** [comment]
Test and verified on branch.
