### ISSUE TITLE
Error with Pale Moon and Basilisk (browser web) when using the collaborative editing feature

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#3177]
## Bug description & symptom

Opening a collaborative document fails with pale moon and basilisk browsers.

## Diagnostic

* With Firefox 68.9.0esr: Working
* With PaleMoon 28.10.0: Not Working (see below) on mon.tracim.fr v2.7.4
* With basilisk 2020.06.10 (64-bit) Linux: Not Working (user reported without trace)

![Sélection_278](https://user-images.githubusercontent.com/1104637/84651343-10866b80-af0a-11ea-9881-dd9da9f668a7.png)

Important note: PaleMoon and basilisk webbrowser are functional with collabora online when using Offidocs.com (LibreOffice Online is powered by LOOLWSD 6.1.1 LOKit LibreOfficeDev 6.1.1.2 (git hash: develop)) (user reported)

Note: When solved, think about reply to email "Bug d'affichage de LibreOffice en ligne avec les navigateurs Pale Moon et Basilisk" (user report)

**Comment by raphj** [comment]
It could be a difference of versions between the libreoffice version used in Tracim and in Offidocs.com?
