### ISSUE TITLE
Feat: Create the component reduxTLMDispatcher

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#3184]
## Feature description

This component should handle every redux modification related to a TLM.
This means it will call each actions depending on the TLM.

## Context

We used to have different components handling the redux update. Problem is, when 2 of these components are mounted, the same TLM can be handled twice resulting in potential dangerous behavior.

## Impacted components

Frontend

**Comment by Skylsmoi** [comment]
The new component has been added.

It fully handles the Dashboard feature.
For TESTER: validates that every features inside the Dashboard works and that automatic update related to TLM works.
These TLM:
- edit workspace label
- edit workspace description
- add member
- remove member
- change role of member
- creating/editing a content from the workspace should put it at first place of recent activities list
- deleting a content should remove it from recent activities
- adding a comment to a content should put it at first place of recent activities list
- page title (name of the browser tab) and breadcrumbs must stay sync with workspace label update

**Comment by inkhey** [comment]
Just tested now, all work but i do see few edge case not handled correctly yet:
- workspace deletion
- user removed from workspace (from the removed user point of view)

**Comment by gbonaspetti** [comment]
Verified on develop.
