### ISSUE TITLE
Feat: App redirection should be controlled by HTTP API return codes

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3185]
## Feature description

When a redirection has to be done after an HTTP request (creation/modification/...), the redirection should be handled using the HTTP API return code instead of waiting for the corresponding TLM.

Apps to be modified are:

- [x] frontend_app_file
- [x] frontend_app_html-document
- [x] frontend_app_thread
(to be completed if needed)

## Context

TLMs can be processed asynchronously so can be delayed which could lead to disturbing late redirections.

## Linked branch

`feat/3185__refactor_app_redirection`

**Comment by gbonaspetti** [comment]
Tested on branch (wait merge to close).

**Comment by PhilippeAccorsi** [comment]
Verified.
