### ISSUE TITLE
Bug: Lost title/name of content while editing if another user changes it

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3199]
## Bug description & symptom

The edited title/name of a content can be lost if another user changes the title/name of the same content and validates it before.

## Diagnostic

This case is not handled separately from the case "not in title edition".

## Expected

To be discussed.

## Context and version information

Tracim develop (future 3.0.0)

## Prerequisites

None

## How to reproduce

1. Edit the name of an html-document with one browser **without validating**
2. Edit the name of the same html-document with another browser and validate the change
3. The first browser's edited title is replaced by the other one

**Comment by gbonaspetti** [comment]
Fixed at https://github.com/tracim/tracim/issues/3238

**Comment by raphj** [comment]
I remember that I tested this behavior on the preprod, Tracim 3.0 and it worked correctly. I am moving this ticket to the Tracim 3.0 project as Done.
