### ISSUE TITLE
Exported PDF files have the name of the original file

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#320]
Example : 
- I upload a libreoffice calc file myfile.ods
- I try to download the PDF full document. The file I download is named "myfile.ods" - but it is the pdf verison
- I try to download the PDF of the current page. The file I download is named "myfile.ods" - but it is the pdf of the page

Expected : 
- the full document pdf export should be named "myfile.pdf"
- the export of one page of the document should be named "myfile.page-<page_id>.pdf"

**Comment by algooapy** [comment]
Sorry to stole this issue, I needed something simple to end today :)

**Comment by xandercagexxx** [comment]
verified.
