### ISSUE TITLE
Bug: TLM is broken when network connection is lost or when we stop/start backend server

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#3203]
## Bug description & symptom

If connection is lost with backend and it found again, user not see anything in frontend but when it add new comment in app file for example, nothing append in timeline. Message is not visible (but POST request in devtools show that request is send correctly).

Another user with new connection can seen this comment directly (because his connection is open after connection restablish). 

## Diagnostic

*"unknown".*

## Expected

- [x] immediately show user message about connection loss if no TLM connection during page load
- [x] show the message when a connection loss for more than 4 seconds is detected after page load
- [x] reconnect automatically in the background

## Context and version information

- Tracim 3.0.0 beta

## How to reproduce

You need an instance with two users, this two users are connected in Tracim and look same file. Each user can add comment in timeline, and the TLM show message correctly for this two users.

The administrator of Tracim server restart Tracim.

The 2 users think that tracim work correctly (no message about this connection break).
At this point, TLM are broken.

What is going on now:
- one user add a new comment
- his comment is not visible in his timeline but also not visible in timeline of the second user
- the second user open a new tab to see this document. He can see the comment of the first user (if this first user add a new comment, the TLM show this new comment in this new tab. First user have write two comment and not see anything in his timeline).
- If the first user reload his tab, all comment are visible (new one also) and at this time, each new comment can be visible correctly.

## Impacted components

*"unknown"*

## Extra information

This bug impact all TLM, so everywhere tlm are used, Tracim not show information correctly before reload page.

### For backend:
see https://github.com/tracim/tracim/pull/3234
- Add a "stream-opened" event at stream opening instead of returning empty.
- Add a "keepalive" event that keepalive connection by sending message each 30 sec.

**Comment by grignards** [comment]
The standard way of implementing reliability in this situation is to use a heartbeat: a special SSE is regularly sent by the backend and the frontend displays a message "Connection lost" when no SSE is received for a set duration (that we have to discuss).

Pushpin has a feature to implement such a heartbeat: https://pushpin.org/docs/advanced/#keep-alives.

**Comment by PhilippeAccorsi** [comment]
@celiamgtt we need to show a message about connection lost (or something like that), design system exist for this kind of message ?  (I think we can create label `design system` now).

**Comment by inkhey** [comment]
> The usual way of implementing reliability in this situation is to implement a [heartbeat](https://en.wikipedia.org/wiki/Heartbeat_(computing)): a special SSE is regularly sent by the backend and the frontend displays a message "Connection lost" when no SSE is received for a set duration (that we have to discuss).
> 
> Pushpin has a feature to implement such a heartbeat: https://pushpin.org/docs/advanced/#keep-alives.

I checked a bit how the mecanism is implemented in http://chat.fanoutapp.com/ which cause less trouble for some reason (issue related to AV that block sse): http://chat.fanoutapp.com/ , it does both create an initial event and create keepalive event. I do suggest to do the same.

**Comment by inkhey** [comment]
Just for information : 
about notification about "connexion lost" and similary case.
In Mattermost i just get a "web notifications" (notification found "outside" of the web page itself) because my session as expired : 
https://developer.mozilla.org/fr/docs/Web/API/notification/Using_Web_Notifications

**Comment by celiamgtt** [comment]
> we need to show a message about connection lost (or something like that), design system exist for this kind of message ? (I think we can create label design system now).

@PhilippeAccorsi We can use our classic design for warning flash messages. I will update the flash messages in the Design System.

**Comment by lebouquetin** [comment]
@grignards @inkhey we will implement something which reload connexion, right? If so, what behavior for the flash @celiamgtt? should it disappear automatically?

**Comment by celiamgtt** [comment]
I think it should yes, if the problem is solved.

**Comment by Skylsmoi** [comment]
We could have an icon similar to the "email not activated" one in the header too

**Comment by lebouquetin** [comment]
> We could have an icon similar to the "email not activated" one in the header that stays visible

I like this idea. probably with a warning-color flavour?

**Comment by Skylsmoi** [comment]
agreed, since Tracim behavior isn't reliable as long as this icon is visible

**Comment by celiamgtt** [comment]
> We could have an icon similar to the "email not activated" one in the header that stays visible

The idea is nice but Tracim isn't usable at all when the TLMs are broken, so it's not just a Tracim status information, it's a real problem/bug.

**Comment by lebouquetin** [comment]
> The idea is nice but Tracim isn't usable at all when the TLMs are broken, so it's not just a Tracim status information, it's a real problem/bug.

@celiamgtt you *almost* right: it's like mattermost: you can continue to use it while network connection is broken - but you won't be able to validate anything until network is ok again.

For example, if you're typing some text in an html document, you can continue typing and the content will still be stored on localstorage. @Skylsmoi you agree?

If so, the behavior should be something between the "status information" (like for email) and the "blocking popup" (like flash message). What do you think @celiamgtt @Skylsmoi?

**Comment by grignards** [comment]
> If so, the behavior should be something between the "status information" (like for email) and the "blocking popup" (like flash message). What do you think @celiamgtt @Skylsmoi?

In the current PR the message is displayed as a flash message but isn't blocking the usage of the interface.

**Comment by celiamgtt** [comment]
> @celiamgtt you almost right: it's like mattermost: you can continue to use it while network connection is broken - but you won't be able to validate anything until network is ok again.

More or less because you can continue what you were doing but you can't create a new file?

> In the current PR the message is displayed as a flash message but isn't blocking the usage of the interface.

I think this is the best solution, to warn the users, and if they want to save something they wrote, they can copy paste manually (allow them to avoid losing content).

**Comment by Skylsmoi** [comment]
> For example, if you're typing some text in an html document, you can continue typing and the content will still be stored on localstorage. @Skylsmoi you agree?
I agree, it is correct. I haven't tested it though but this is the expected behavior

> If so, the behavior should be something between the "status information" (like for email) and the "blocking popup" (like flash message). What do you think @celiamgtt @Skylsmoi?
For the email icon, we have an animation that make it blink.
Could it be "in between" enough?

**Comment by gbonaspetti** [comment]
Verified on develop (add a bug that will be handled at https://github.com/tracim/tracim/issues/3318).
