### ISSUE TITLE
Bug: "Click here to unsuscribe" in the dashboard is huge and unclear

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3210]
## Bug description & symptom

I got the feedback that button "Click here to unsuscribe" takes a lot of space on a regular / small screen and is often misclicked. The misclick is silent: no message is shown. The label does not mention that it is related to notifications and one has to hover it with a mouse to get this information.

## Context and version information

- Desktop environment (if applicable)
    - OS: Windows
    - Browser: Firefox

## Impacted components

- *frontend*

**Comment by obrowny** [comment]
Unsubscribe is confusing. We think it is a way to unsubscribe to a shared space. It could be renamed as : «Disable notifications».

**Comment by gbonaspetti** [comment]
Fixed at #4353
