### ISSUE TITLE
Bug: the difference between "All contents" and "Files" is unclear

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3214]
## Bug description & symptom

In the sidebar, there are several elements that one could expect to do the same things / between which the differences are unclear, in particular "All contents" and "Files": what is shown / hidden in both screens?

I suggest we think of better labels or just merge the two screens.

## Impacted components

- *frontend*

**Comment by yvan-algoo** [comment]
The UI has changed a lot since this issue has been reported: closing.
