### ISSUE TITLE
Bug: message "no preview available" when uploading a big document is misleading

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3215]
## Bug description & symptom

When uploading a document, the file app says "no preview available" for a while (and this can take time on a large document), and only then "loading preview".

This first message can be misleading and make the user thing that something when wrong, and make them retry sending the document several times.

(ticket based on feedback)

## Video

![no-preview-available](https://user-images.githubusercontent.com/3817365/85198666-beb75a00-b2ea-11ea-8b3d-1278224a477c.gif)

(in this video the message is not displayed for so long, but I don't have a big document handy)

## Impacted components

- *frontend*

**Comment by yvan-algoo** [comment]
I suppose this has been fixed: I just tried with a 12MB ODT file and the message `No preview available` does not appear.

Please re-open if you still encounter the issue.
