### ISSUE TITLE
Bug: apache config and uwsgi need improvement to make Tracim work correctly with Docker (with pushpin and multiple users)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#3222]
## Bug description & symptom
Pushpin not working if ` On` is in Apache configuration.
Also when many users used Tracim, uWSGI bottleneck exist.

## Diagnostic

- This directive  `ProxyPreserveHost On` is just necessary for webdav. Just need to add this directive in webdav context
- uWSGI is configured like this by default in `tracim_web.ini`:
~~~
#workers = 1
#threads = 8
~~~

## Expected

- [x] Pushpin work correctly with docker image
- [x] improve uWSGI configuration in `tracim_web.ini` : use 4 workers and 4 threads by default
- [x] add ProxyPreserveHost for webdav location only
- [x] add Destination header fix to docker image with comment.
- [x] document apache and uwsgi config file when needed
- [x] don't change tracim_webdav and tracim_caldav uwsgi config.
- [x] update documentation according to change made (Apache, uWSGI)
- ~~[ ]  add fix for pushpin with antivirus ?~~ => most probably unneeded, if modifications are done they will be in #3235.

## Context and version information

- Pushpin come in v3.0.0
- Apache configuration is from oldest Tracim version

## How to reproduce

Pushpin:
- Try to use pushpin available in Tracim unstable image
uWSGI:
- see what is going on when many user try to send file in same Tracim instance

## Impacted components

- Docker images

**Comment by PhilippeAccorsi** [comment]
After discuss with @lebouquetin , we can change uWSGI default configuration from 
~~~
#workers = 1
#threads = 8
~~~
to
~~~
workers = 8
threads = 8
~~~

**Comment by PhilippeAccorsi** [comment]
Need also modification in documentation, exemple here about apache https://github.com/tracim/tracim/blob/develop/backend/doc/apache.md

**Comment by inkhey** [comment]
After some research, we found that removing `ProxyPreserveHost On` broke webdav support for copy/move actions, in a similar but slighty different way than : https://github.com/tracim/tracim/issues/1765

```
curl --user 'username:password' -X COPY --header 'Destination:https//domainame/webdav/contentmanager' 'https://domainame/webdav/reader'
<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 4.01//EN' 'http://www.w3.org/TR/html4/strict.dtd'>
<html><head>
  <meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
  <title>502 Bad Gateway</title>
</head><body>
  <h1>502 Bad Gateway</h1>
  <p>502 Bad Gateway: Inter-realm copy/move is not supported.</p>
<hr/>
<a href='https://github.com/mar10/wsgidav/'>WsgiDAV/2.4.1</a> - 2020-06-30 15:08:05.932590

```

Solution is adding preserve host to /webdav urls only.

**Comment by PhilippeAccorsi** [comment]
With this example, webdav and pushpin can work correctly on same instance
~~~
<Location /webdav>
    ProxyPreserveHost On
    ProxyPass http://127.0.0.1:3030/webdav
    ProxyPassReverse http://127.0.0.1:3030/webdav
</Location>
~~~

With this example, `ProxyPreserveHost On` is just apply for webdav.

**Comment by inkhey** [comment]
I do suggest to add 
`
RequestHeader edit Destination ^https http early 
`
by default in docker,
and potentially in apache documentation sample, in order to minimize risk of getting same problem as #1765 if using https.

**Comment by PhilippeAccorsi** [comment]
> I do suggest to add
> `RequestHeader edit Destination ^https http early `
> by default in docker,
> and potentially in apache documentation sample, in order to minimize risk of getting same problem as #1765 if using https.

I'm not sure is a good idea to add this directly in apache configuration with docker. Maybe just add documentation about what is necessary if user want to use tracim with https. Need discuss about this point.

**Comment by inkhey** [comment]
It's still unclear what should be done here:
- uwsgi worker/process number ?
- `RequestHeader edit Destination ^https http early` only  in documentation ? Seems to me simpler to put it directly in docker, i don't see any reason to not want this as we "control" the docker context.

**Comment by inkhey** [comment]
Ticket updated with after discussion with @PhilippeAccorsi

**Comment by PhilippeAccorsi** [comment]
Can merge after test on preprod instance.

**Comment by PhilippeAccorsi** [comment]
RequestHeader can't be added in <Location>, information here https://httpd.apache.org/docs/2.4/en/mod/mod_headers.html

**Comment by PhilippeAccorsi** [comment]
Done. Not need specific test (test make on production).
