### ISSUE TITLE
Bug: Crash when first time connecting a new user

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#3225]
## Bug description & symptom

After creating a new user through admin user app, when connecting it, Tracim crashes.
If we reload the page, it then works fine.

## Diagnostic

The bug is related to the lang of the user that isn't defined on creation.
The frontend try to detect the broswer language and send a PUT request to update the user's lang.
When first time connecting, the user's lang is `undefined` and that's what crash Tracim, the component that shows the user's language expect a proper value

When the reducers where changed to serialize the variables and have everything in camelCase on redux, the frontend didn't take into account the undefined language.

## Expected

- [x] Set default language at reducer if it's undefined

## How to reproduce

- create a new user using the user administration app
- logout
- login with that new user

## Impacted components

frontend

**Comment by Skylsmoi** [comment]
Note: it seems to be a regression, the bug doesn't seem to exist in v2.7.5

**Comment by Skylsmoi** [comment]
It appears that the regression might be in backend.
Backend now serve a user without lang. Is it supposed to happen ?
@inkhey

**Comment by inkhey** [comment]
> It appears that the regression might be in backend.
> Backend now serve a user without lang. Is it supposed to happen ?
> @inkhey

Yes, Backend currently does support the fact an user can have no lang setted, and it's the "default" case.

**Comment by Skylsmoi** [comment]
I have tested that the backend is sending a user without a lang in the response of the POST /login for a user we just created.
This is not a regression, it's not the source of the issue

**Comment by PhilippeAccorsi** [comment]
We have this paramter in development.ini.sample
~~~
### Lang ###
## default lang used in backend if user doesn't provided any lang.
# Available parameter: en, fr, pt
; default_lang = en
~~~

Is it not possible to use this parameter to set default language ? If instance is in French by default, why set english for new user ?

**Comment by PhilippeAccorsi** [comment]
This bug not exist in old tracim version, I not understand what has change in tracim 3.0

**Comment by gbonaspetti** [comment]
> We have this paramter in development.ini.sample
> 
> ```
> ### Lang ###
> ## default lang used in backend if user doesn't provided any lang.
> # Available parameter: en, fr, pt
> ; default_lang = en
> ```
> 
> Is it not possible to use this parameter to set default language ? If instance is in French by default, why set English for new user ? (same if default language is Portuguese)
>
> This bug not exist in old tracim version, I not understand what has change in tracim 3.0

Searching a little bit more, I found the problem, it was a conditional missing at `user` redux after the addition of serialized variables, if the language was `undefined` it didn't know what set.

**Comment by PhilippeAccorsi** [comment]
Tested on branch. default lang of user is set on the first connection, and the language is the language setted on login page.

**Comment by PhilippeAccorsi** [comment]
Please verify if its working good on preprod, also with more browser like Safari or Edge (to make sure is working good in all case).

**Comment by PhilippeAccorsi** [comment]
Chechwith firefox on preprod.
