### ISSUE TITLE
Bug: app workspace can send a custom event to open the workspace in sidebar before the workspace was added

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#3230]
## Bug description & symptom

When a workspace is created with the frontend_app_workspace a customEvent is emit to the frontend to open the new workspace in the sidebar, but TLM are asynchronous and it can happens that the frontend didn't received the new workspace with its TLM.

## Diagnostic

We could use the TLM in frontend_app_workspace to send the customEvent after the TLM workspace.created is receive, but the redux state could be not updated yet because it is also asynchronous,
Maybe we could handle workspaceOpenInSidebar in redux state object with only id of workspace to open

## Expected

When create a workspace the workspace need to be opened in the sidebar

**Comment by Skylsmoi** [comment]
A potential solution:
- app workspace doesn't do anything on receiving the http status 200 on the POST workspace.
  - apart from closing the popup
- on the TLM member.created received
  - ReduxTlmDispatcher.jsx will trigger the addWorkspace in redux
  - Sidebar.jsx will trigger the open in sidebar if the fields.user is the same as fields.author

But where to put the redirection ? On the https 200 probably, that's where it makes the most sense

**Comment by metzgegu** [comment]
This solution works but if the user has 2 tabs opened, it will open the workspace in the sidebar on both tabs when one tabs has created a workspace.

**Comment by Skylsmoi** [comment]
Solution implemented:
- PopupCreateWorkspace
  - on http 200: close the popup
  - on TLM member.created: nothing
- ReduxTlmDispatcher
  - on TLM member.created: call `addWorkspaceMember()` which wont do anything since the new workspace isn't in the list
- Sidebar
  - on TLM member.created:
    - check if the new member is the logged user. If yes,
      - call `addWorkspaceList()` to add the workspace in redux
      - call again `addWorkspaceMember()` to add the new member now the workspace exists (first call was by ReduxTlmDispatcher)
      - check if the author of the TLM is the logged user. If yes,
        - call `setWorkspaceListIsOpenInSidebar()` to open it in the sidebar
        - call props.history.push() to redirect to the dashboard of the new workspace

**Comment by Skylsmoi** [comment]
For tester:
The goal here is to test the workspace creation and the member addition to a workspace.
When creating a workspace, the new workspace but open in the sidebar and the user must be redirected to its dashboard

**Comment by gbonaspetti** [comment]
Verified on develop.
