### ISSUE TITLE
Bug: Avoid generating the same preview several times on concurrent accesses to the same file

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#3231]
## Bug description & symptom

Generating preview takes a long time on some files. Accessing twice on such files at the same time makes previous generator generate the preview twice. On videos, ffmpeg blocks forever, asking whether it should overwrite the file.

## Solution

A locking mechanism should be added to preview generator to avoid generating the same preview several times.

## Status

- The locking mechanism has been added to preview generator.
- We need to add a test for this mechanism. Relevant issue:  #3338

## Implemented solution
- use preview_generator 0.14 with the new lock mecanism.

**Comment by raphj** [comment]
Tested on branch.

Tests are failing, @metzgegu is looking into it.
