### ISSUE TITLE
Bug: Tracim 3.0 TLMs do not work with Avast antivirus on MacOS

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3235]
## Bug description & symptom

No TLMs are received so the frontend is broken in several places. This is especially visible when creating a new content as the popup window is not closed and the content list not updated.

## Diagnostic

Avast antivirus breaks the TLMs transmission over SSE, for example Chrome displays this error:

![chrome_error](https://user-images.githubusercontent.com/51887114/85990129-d5983380-b9f1-11ea-8e9a-c707bb8377da.jpeg)

## Expected

TLMs must work with this setup.

## Context and version information

- macos X catalina
- chrome and safari are both affected
- avast antivirus 14.4 (up-to-date version)

## Prerequisites

None

## Impacted components

*For example:*

- *backend*
*If unsure, write "unknown"*

## Extra information

*Optional - add any useful information to understand and develop the feature*

**Comment by grignards** [comment]
What has been done:

- adding initial message and keep-alive messages (https://github.com/tracim/tracim/pull/3251)
- force apache to add `Transfer-Encoding` to the `Connection` header.

With those two modifications the TLMs are received but with a delay of around 20s.

**Comment by lebouquetin** [comment]
I strongly recommend to explictly compare the list of HTTP headers sent by the demo app and by our app. I'd like to see these lists here for comparison.

**Comment by inkhey** [comment]
To better troubleshoot the problem, This is some informations i do get about web protection of antivirus (it may help have some idea of what is happening):
What i understood is that in this particular case, we have a process that first intercept/proxy https and then the content of the http request is analysed by the antivirus.

1. This has impact on internet connexion performances : https://forum.avast.com/index.php?topic=94604.0
2. Intercepting https this way is not a very good practices : https://www.01net.com/actualites/pourquoi-les-antivirus-et-les-proxy-ssl-rendent-le-web-moins-sur-1113890.html
3. It's seems that in some case (bug ?), it can break https : https://www.malekal.com/desactiver-lanalyse-https-antivirus/

Rule applied by AV for analyse is unclear. It's possible that issue is depending on the content given.

**Comment by inkhey** [comment]
Similar but different issue in Sophos Av:
- https://community.sophos.com/products/free-antivirus-tools-for-desktops/f/sophos-anti-virus-for-mac-home-edition/5750/sophos-av-blocks-server-sent-events-sse-on-mac-os-x-yosemite
- https://community.sophos.com/products/endpoint-security-control/f/sophos-endpoint-software/74878/server-sent-events-blocked-by-download-scanner

Which : 
- seems to happened only in http
- is related to a buffer mecanism.

**Comment by grignards** [comment]
Headers of fanout example chat ():

```
HTTP/1.1 200 OK
Date: Wed, 01 Jul 2020 13:22:24 GMT
Server: gunicorn/19.9.0
Cache-Control: no-cache
X-Frame-Options: SAMEORIGIN
Content-Type: text/event-stream
Vary: Cookie
Access-Control-Allow-Methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
Access-Control-Expose-Headers: Date, Server, X-Frame-Options, Vary
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 3600
Transfer-Encoding: chunked
Connection: Transfer-Encoding
```

Headers of tracim unstable:

```
HTTP/1.1 200 OK
Date: Wed, 01 Jul 2020 13:03:15 GMT
Server: Apache
Strict-Transport-Security: max-age=31536000; preload
Content-Type: text/event-stream
Cache-Control: no-cache
Connection: Transfer-Encoding, Keep-Alive
Keep-Alive: timeout=5, max=100
Transfer-Encoding: chunked
```

**Comment by grignards** [comment]
Transmitting a tlm contents through the fanout example chat works without delay.

[tlm.txt](https://github.com/tracim/tracim/files/4858304/tlm.txt)

**Comment by lebouquetin** [comment]
@grignards if you test adding the following headers:

```
X-Frame-Options: SAMEORIGIN
Access-Control-Allow-Methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
Access-Control-Expose-Headers: Date, Server, X-Frame-Options, Vary
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
```

Does it work better?

**Comment by grignards** [comment]
> @grignards if you test adding the following headers:
> 
> ```
> X-Frame-Options: SAMEORIGIN
> Access-Control-Allow-Methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
> Access-Control-Expose-Headers: Date, Server, X-Frame-Options, Vary
> Access-Control-Allow-Credentials: true
> Access-Control-Allow-Origin: *
> ```
> 
> Does it work better?

Same results, there is a delay.

**Comment by grignards** [comment]
We also tried to remove the keep alive in apache, it doesn't change anything.

**Comment by grignards** [comment]
Current situation: tests with the latest avast version (14.5) do not reproduce the bug. @celiamgtt will try on her mac too to confirm this.

**Comment by grignards** [comment]
Also tried in a VM at home, 14.5 works with Tracim (it is updated automatically).

**Comment by raphj** [comment]
@celiamgtt confirmed that everything works correctly with the last version of Avast.
