### ISSUE TITLE
Bug: a FlashMessage error is always displayed when moving a content

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#3236]
## Bug description & symptom

When moving a contend in a folder or anywhere else, a flashMessage is displayed with an error
This is a regression bug coming from #2850 WorkpsaceContent refactor

## Diagnostic

The function to handle moving content use a `switch` and doesn't handle the case `status.code = 200` anymore so it execute the default code, and this was in case of errors.

## Expected

FlashMessage errors are displayed only if necessary

**Comment by gbonaspetti** [comment]
Verified on develop.
