### ISSUE TITLE
Bug: Standardize and factorize the behavior of messages related to TLM

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3238]
## Bug description & symptom

Need to standardize and factorize the behavior of messages intended for the user related to TLM.

## Expected

- [x] for **frontend**, **frontend_app_admin_workspace_user**, **frontend_app_gallery**, **frontend_app_workspace_advanced** and **timeline at appFeature** - all updates are made automatically,  i.e. without a warning message, more details for each action:

- workspace.created
    - update sidebar automatically
    - update workspaces list at admin account automatically
- workspace.modified
    - update sidebar automatically
    - update dashboard/gallery/workspace_advanced title and description automatically
    - update breadcrumbs automatically
    - update shared spaces and notifications list at user's account automatically
    - update workspaces list at admin account automatically
    - update optional functionalities at workspace_advanced automatically
- workspace.deleted
    - update sidebar automatically
    - update workspaces list at admin account automatically
- member.created
    - update members list at dashboard/workspace_advanced automatically
    - update shared spaces and notifications list at user's account automatically
    - update workspaces list at admin account automatically
- member.modified
    - update members list at dashboard/workspace_advanced automatically
    - update shared spaces and notifications list at user's account automatically
- member.deleted
    - update members list at dashboard/workspace_advanced automatically
    - update shared spaces and notifications list at user's account automatically
    - update workspaces list at admin account automatically
- content.created
    - update workspace content list automatically
    - update recent activities list at dashboard automatically
    - update share folder content list automatically if needed
    - update gallery automatically if needed
- content.comment.created
    - update recent activities list at dashboard automatically
    - add a comment on the timeline at appFeature automatically
- content.modified
    - update workspace content list automatically
    - update content at search result automatically
    - update recent activities list at dashboard automatically
    - create a revision on the timeline at appFeature automatically
    - update gallery automatically if needed
- content.deleted
    - update content's name at search result automatically
    - add a comment on the timeline at appFeature automatically
    - update gallery automatically if needed
- content.undeleted
    - update recent activities list at dashboard automatically
    - add a comment on the timeline at appFeature automatically
    - update gallery automatically if needed
- user.created
    - update users list at admin account automatically
- user.modified
    - update members list and user information at dashboard automatically
    - update accounts info at account and at adminAccount automatically
    - update dashboard and homepage automatically if public name is changed
    - update users list at admin account automatically
- user.deleted
    - update users list at admin account automatically

- [x] for **frontend_app_agenda**, **frontend_app_file**, **frontend_app_folder_advanced**, **frontend_app_html-document** and **frontend_app_thread** - all content updates, except timeline updates, should be followed by the message below and the interface should only be updated after the user clicks to refresh. For example, if the title of a content is changed, it should not be changed automatically, only after confirmation by the user.
For appFeature (file, folder_advanced, html-document, thread) the message must be located in the app header to the left of the status (to the left of the delete button for the folder_advanced, because it has no status) with a tooltip "_The content has been modified by {{author}}_" and for  appFullScreen (agenda): the message must be located on the right side of the page title to not move the frame with a tooltip "_Some information was modified by {{author}}_" .

![Screenshot from 2020-06-30 12-07-14](https://user-images.githubusercontent.com/35422692/86115371-28461e00-bacc-11ea-945f-a8ded5731b6b.png)

- [x] fix: all messages must have a responsive interface following the screenshot design below for the mobile version

![mobile](https://user-images.githubusercontent.com/35422692/86110676-27aa8900-bac6-11ea-8a21-b769135ee70d.png)

**Comment by lebouquetin** [comment]
> all updates are made automatically, i.e. without a warning message, more details for each action:

You mean "if the content of a html-content is modified, the shown content is automatically updated"? So... when does the refresh button appear?

> appFeature (file, folder_advanced, html-document, thread): the message must be located in the app header to the left of the status (to the left of the delete button for the folder_advanced, because it has no status)

We need a mobile version screenshot. I do not see how we'll show this message in the content header on a mobile phone

**Comment by lebouquetin** [comment]
By the way, there is no distinction between content in "read mode" and content in edition"

**Comment by gbonaspetti** [comment]
> > all updates are made automatically, i.e. without a warning message, more details for each action:
> 
> You mean "if the content of a html-content is modified, the shown content is automatically updated"? So... when does the refresh button appear?

No, this is just for the components **frontend**, **frontend_app_admin_workspace_user**, **frontend_app_gallery**, **frontend_app_workspace_advanced** and the **timeline at appFeature**, in the details of each action I put that, in these components if a content was modified (change the title of a content file for example) the changes that would happen automatically will be:
- update workspace content list automatically
- update this content at search result automatically
- update recent activities list at dashboard automatically
- create a revision on the timeline at appFeature automatically
- update gallery automatically if needed

> > appFeature (file, folder_advanced, html-document, thread): the message must be located in the app header to the left of the status (to the left of the delete button for the folder_advanced, because it has no status)
> 
> We need a mobile version screenshot. I do not see how we'll show this message in the content header on a mobile phone

Ok, I'll make an interface proposal for the mobile and add here.

**Comment by celiamgtt** [comment]
> appFeature (file, folder_advanced, html-document, thread): the message must be located in the app header to the left of the status (to the left of the delete button for the folder_advanced, because it has no status)

As I said to Côme, Philippe & Sebastien, I'm not sure that a warning message incorporate in the application is the best way to warn the user when someone else is editing the document. There are some problems if we're using toast notifications, but it could be more consistent for the user experience.

**Comment by gbonaspetti** [comment]
> > appFeature (file, folder_advanced, html-document, thread): the message must be located in the app header to the left of the status (to the left of the delete button for the folder_advanced, because it has no status)
> 
> As I said to Côme, Philippe & Sebastien, I'm not sure that a warning message incorporate in the application is the best way to warn the user when someone else is editing the document. There are some problems if we're using toast notifications, but it could be more consistent for the user experience.

I don't know if we have statistics of the type, but for me if there aren't normally many simultaneous changes in contents in Tracim, the toast messages would be great, otherwise they can be a bit disturbing.

**Comment by PhilippeAccorsi** [comment]
I think, missing information about changing background color of the update message. At present text message is black on white background. I think its more visible with yellow or orange color.

**Comment by gbonaspetti** [comment]
After talk with @PhilippeAccorsi and @lebouquetin we decided to stay in this design but add some color to highlight more the message.
Here are some colors option:

1. Info color
    - with a colored background:
![Screenshot from 2020-06-29 17-42-27](https://user-images.githubusercontent.com/35422692/86028212-e9638a00-ba31-11ea-8ee9-8e621bea07ca.png)
    - with a white background:
![Screenshot from 2020-06-29 17-42-18](https://user-images.githubusercontent.com/35422692/86028226-ef596b00-ba31-11ea-92bb-f313acea5d8c.png)

2. Warning color
    - with a colored background:
![Screenshot from 2020-06-29 17-31-24](https://user-images.githubusercontent.com/35422692/86028544-49f2c700-ba32-11ea-8933-df6571119517.png)
    - with a white background:
![Screenshot from 2020-06-29 17-39-44](https://user-images.githubusercontent.com/35422692/86028449-2fb8e900-ba32-11ea-8fa4-89ab85378318.png)
    - with a colored Refresh button:
![Screenshot from 2020-06-29 17-40-15](https://user-images.githubusercontent.com/35422692/86028532-452e1300-ba32-11ea-8a37-0ef90efd10ca.png)

3. A grey color
![Screenshot from 2020-06-29 17-36-45](https://user-images.githubusercontent.com/35422692/86028586-570fb600-ba32-11ea-871d-6079d9ac45a7.png)


So we need to choose between:
- color gray/warning/info
- background colored or not
- icon colored or not
- refresh button colored or not

**Comment by gbonaspetti** [comment]
For the mobile interface I have two options (the option chosen will have the same colors chosen for the browser version):
- with text
![Screenshot from 2020-06-29 17-45-55](https://user-images.githubusercontent.com/35422692/86028839-b372d580-ba32-11ea-9a32-57d86a7a94bc.png)

- just the icon
![Screenshot from 2020-06-29 17-46-35](https://user-images.githubusercontent.com/35422692/86028846-b53c9900-ba32-11ea-95db-f52cb0ff40b4.png)

Personally I think that just the icon will be better to be more coherent with the other buttons of the apps, as we can see in the screenshot below the app file mobile version
![Screenshot from 2020-06-29 18-04-38](https://user-images.githubusercontent.com/35422692/86029277-3e53d000-ba33-11ea-9ead-03042d070356.png)

**Comment by lebouquetin** [comment]
@gbonaspetti I'd prefer the orange color which will catch eye - in most case I think the user will want to refresh the content.

For the button, the icon should be always visible, with text in large screen and alone in small screen. Showing the icon in both case help the user to remind the feature.

**Comment by PhilippeAccorsi** [comment]
I prefer also orange color (Warning color and first example).
I think its better to have the some color on mobile version (just icon).

**Comment by inkhey** [comment]
Just 2 points that may need reflexions:
- This code allow to update content/add comment/etc… without refreshing when update is available. I do think it make sense to force refresh (with grey button) **before** because we can refresh status leading to error when updating content/comment. I do think it's a more advanced support so, we should probably fix this later (3.2.X maybe ?).
- Gallery app behavior is "live updating", This may be confusing, for some users depending on how they use the gallery.

**Comment by lebouquetin** [comment]
> This code allow to update content/add comment/etc… without refreshing when update is available. I do think it make sense to force refresh (with grey button) before because we can refresh status leading to error when updating content/comment. I do think it's a more advanced support so, we should probably fix this later (3.2.X maybe ?).

@inkhey you mean "disable buttons / write zone" until the refresh button has been clicked? If so, I agree this may be a good idea (and I agree this is an improvment)

> Gallery app behavior is "live updating", This may be confusing, for some users depending on how they use the gallery.

I'm pretty sure live update on gallery is not the expected behavior. This may be a usecase to test in our integration - and it may be something that @celiamgtt you test with users during a wrokshop"?

**Comment by Skylsmoi** [comment]
the first implementation of the TLM in the gallery did implement a live update.
After talking about it we chose to reduce the update perimeter (not adding content but still updating workspace name for example)

**Comment by inkhey** [comment]
> > This code allow to update content/add comment/etc… without refreshing when update is available. I do think it make sense to force refresh (with grey button) before because we can refresh status leading to error when updating content/comment. I do think it's a more advanced support so, we should probably fix this later (3.2.X maybe ?).
> 
> @inkhey you mean "disable buttons / write zone" until the refresh button has been clicked? If so, I agree this may be a good idea (and I agree this is an improvment)

Yes, more or less. but some case may be tricky if user has began to update content. i have created a specific issue : https://github.com/tracim/tracim/issues/3275

**Comment by raphj** [comment]
Tested on branch.

**Comment by gbonaspetti** [comment]
Verified on develop.
