### ISSUE TITLE
Bug: Revision number in timeline is wrong if comments are present

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3239]
## Bug description & symptom

When a new revision is added by handling a TLM, the revision's number is wrong if comments are already present in the timeline.

## Diagnostic

All timeline items are counted, only 'revision' items should be.

## Expected

Revision number should be `last revision number + 1`.

## Context and version information

N/A

## Prerequisites
None

## How to reproduce

*Optional - detail steps to reproduce the behavior:*

1. *Go to a content with comments*
1. *Create a new revision with another browser*

## Impacted components

- *frontend*

## Extra information

*Optional - add any useful information to understand and develop the feature*

**Comment by gbonaspetti** [comment]
Verified on develop.
