### ISSUE TITLE
Review PostgreSQL configuration documentation in doc/database.md 

### ISSUE THREAD

**Issue by algooapy** [tracim/tracim#324]
This especially concerns the ownership of `tracimuser` on `tracimdb`:
- update documentation itself,
- update `pgtool` as well ?

**Comment by lebouquetin** [comment]
What is expected to be done in this issue?
What do you mean by "update pgtool as well ?"

Remember that an issue should always define clearly: 
- the current status / the current behavior
- the expected behavior or the work expected to be done

**Comment by algooapy** [comment]
- Current:
  The `tracimdb` database may not be owned by the user `tracimuser`, leading to errors on database operations.
- Expected:
  Cause `tracimuser` to be the owner of `tracimdb`.
- Question:
  Do I update `pgtool` as well as the documentation ?

**Comment by lebouquetin** [comment]
Ok I understand your points.

For pgtool: if the documentation references it, then you must update. Otherwise, do not update `pgtool` (and remove it if not referenced in documentation anymore)

**Comment by algooapy** [comment]
Closing this issue solved by #347
