### ISSUE TITLE
Bug: TimeLine doesn't need to auto-scroll when the timline scroll is not at the bottom

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#3242]
## Bug description & symptom

For now when a new timeline item is created, the timeline will auto scroll to the bottom in order to see the new item
Now with TLM, The autoscroll is active even if the item was not created by the current user, so if the current user is reading some old comments it will scroll to bottom and this is not user-friendly

## Expected/Implementation

When the timeline is modified, it must check if the timeline scroll is already at the bottom (old bottom) to scroll to the new comment, and it need to scroll to the bottom when the new Timeline item added was created by the current user & current session (with Token_id)

**Comment by gbonaspetti** [comment]
The solution works well for large screens, but on smaller screens, since we are at the bottom of the document, it does not remain there, we need to scroll again each time. Check gif:
![scroll](https://user-images.githubusercontent.com/35422692/86231855-740fca80-bb93-11ea-9a57-1b7f13606bdd.gif)

**Comment by metzgegu** [comment]
Autoscroll is disabled when display `width < 1200px ` for now, but we could scroll to the bottom when a new item is added in the timeline and the scroll is already at the bottom when `width < 1200px`

**Comment by metzgegu** [comment]
The current implementation had an issue when the content was changed without close the app, 
I fixed it in the last commit
And I added the auto-scroll in small screen when the current User/TokenID added a comment (and only a comment) in order to have a more friendly behavior 
see :

![TimelineDemo2](https://user-images.githubusercontent.com/31687635/86344059-185c4480-bc5a-11ea-8da0-058f1be2cab9.gif)

**Comment by gbonaspetti** [comment]
Verified on develop.
