### ISSUE TITLE
Bug: WebDAV usage of Tracim generates too many events/TLMs

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3243]
## Bug description & symptom

Several TLMs/events are created for each user action when using webdav.

## Diagnostic

*Optional - explain what has been found and what is not clear yet. If unknown, write "unknown".*

## Expected

*Describe the expectations in order to consider the bug resolved**

## Context and version information

N/A

## Prerequisites

None.

## How to reproduce

*Optional - detail steps to reproduce the behavior:*

1. *Use tracim with webdav and edit a content*
1. *Visualize the content in a browser + its console open*
1. *Many TLMs are received for each modification*

## Impacted components

- *backend*
- *webdav*
- *...*

## Extra information

SQL Alchemy's sessions were re-used in webdav and the event code doesn't expect this. The associated PR makes the sessions behave as in pyramid : they are never re-used between two requests.

**Comment by gbonaspetti** [comment]
Verified on develop.
