### ISSUE TITLE
Bug: Moving a content in another Workspace doesn't update redux

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#3247]
## Bug description & symptom

After moving a content in another Workspace, the content is correctly moved but the WorkspaceContentList/workspaceShareContentList is not updated

## Diagnostic

TLM event for moving a content outside its workspace is `content.modified`, for now every TLM without the same `state.workspaceId` in WorkspaceContentList/workspaceShareContentList is ignored

## Expected/Implementation

When a `content.modified` TLM come to WorkspaceContentList/workspaceShareContentList it must remove contents which are in the `contentList` (if they exist in this workspace and `action.workspace !== state.workpsaceId`)

**Comment by gbonaspetti** [comment]
Verified on develop.
