### ISSUE TITLE
Bug: standardize the display of usernames

### ISSUE THREAD

**Issue by celiamgtt** [tracim/tracim#3250]
## Bug description & symptom

For now we have:

**fields**
- popup on the homepage: placeholder `@username`
- page My Account: placeholder `New username`
- page Admin User:
     - if you click on a user: `New username`
     - if you click on Create a user: `@username`
- login page and reset password page: placeholder `Email or username` and it's the only field that has a different design

**informations**
- page my account: `@username`
- page admin user
    - at the table: `username`
    - if you click at a user: `@username`
- autocomplete and members list (dashboard and dashboard advanced): `@username`

## Expected

- [x] Display the username with the `@` as a prefix for the information to clarify the interface, and to distinguish between email/public name/username. Update table at Admin User page.
- [x] Do not accept as username the input starting with `@`.
- [x] Display all placeholders without the `@` to be consistent with the input expected. Update homepage popup.

## Discussed

The username is display at several places in the interface, in popups or white pages for example. The current implemented solution matches to these different displays. If we set up a fixed icon, it could be weird regarding the other fields.

For exemple, we needed to have a cohesive design for the login page, and if we're fixing a prefix, it's not possible. Here, the @ icon can suggest the user to use his email address or his username.

<img width="566" alt="Capture d’écran 2020-06-30 à 09 56 51" src="https://user-images.githubusercontent.com/50453784/86102356-b7970580-babb-11ea-91ca-c7156e06261e.png">
 
Linked to https://github.com/tracim/tracim/issues/3056

**Comment by lebouquetin** [comment]
This may be a `@` in the text, not necessarely an icon.

Examples taken from twitter:

![image](https://user-images.githubusercontent.com/907161/86103483-1f9a1b80-babd-11ea-85f7-288db517be3f.png)
![image](https://user-images.githubusercontent.com/907161/86103641-4e17f680-babd-11ea-92eb-cd3042994281.png)

**Comment by lebouquetin** [comment]
In the login screenshot example, the icon may be a user and the placeholder somthing like `Adresse email ou @identifiant`

**Comment by gbonaspetti** [comment]
@lebouquetin @celiamgtt and for My Account style pages? Just putting the @ fixed will make the field different from the others on this page.

![Screenshot from 2020-07-01 15-23-14](https://user-images.githubusercontent.com/35422692/86249239-4afd3300-bbaf-11ea-8c64-c27cde199666.png)

**Comment by lebouquetin** [comment]
@gbonaspetti we must have coherent screens. My point of view is that it does not make sense to have a fixed `@` at left of the field. I would label the placeoholder: `new @username`.

**Comment by gbonaspetti** [comment]
> @gbonaspetti we must have coherent screens. My point of view is that it does not make sense to have a fixed `@` at left of the field. I would label the placeoholder: `new @username`.

Okay, I understand. One option, based on the screenshot you sent from twitter and the issue #3056, would be in **all fields** to put the label out and in this case we would have a label _New username_ and a field with the placeholder `@username`.

**Comment by gbonaspetti** [comment]
After discussion, it was decided not to accept the input with `@` for the username to remove possible ambiguity, so all placeholders should appear without the `@`. However, all information continues with `@`.
The issue description has been updated.

**Comment by raphj** [comment]
tested on branch

**Comment by raphj** [comment]
Reopening, actually we missed the `@` in the field of the user creation page.

**Comment by PhilippeAccorsi** [comment]
Issue fix in 3.0.0 but missing fix.

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Available in 3.0.2
