### ISSUE TITLE
Bug: Moving a content in a folder doesn't display all the folder's content

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#3255]
## Bug description & symptom

After moving a content inside a folder and opening the folder, it sometimes doesn't display every folder's content

## Diagnostic

It might be an issue in the reducer but I currently don't know.

## Expected

When opening a folder, every contents must be visible

## How to reproduce

1. Do a full reload of a content list (f5) (the folder must not have been opened to trigger the bug)
2. Move a content in a folder that already contains contents
3. Open that folder 

The folder only shows the moved content

## Impacted components

frontend

## Extra information

Check if it is possible to address the bug about content duplication on spam click on a folder with the same fix. If it's two too different issues, do nothing for the content duplication, it will be done in its own issue

**Comment by Skylsmoi** [comment]
The solution implemented is to filter the content list from duplicated contents.

This fix https://github.com/tracim/tracim/issues/2615

**Comment by Skylsmoi** [comment]
For tester:
For this issue, you can just test the "reproduction steps" in the description. Also do general test for nominal usage of folders.

Don't forget to also test the Share folder as it is handled by its own reducer.

Also check the issue #2615 and its reproduction step

**Comment by inkhey** [comment]
Tested on branch.

**Comment by gbonaspetti** [comment]
Verified on develop.
