### ISSUE TITLE
WebDAV + windows : ignore request when the submitted file is empty

### ISSUE THREAD

**Issue by algooapy** [tracim/tracim#326]
This is the following of issue #308.

Current status:
- with windows 10
- copying a file from Tracim WebDAV,
- pasting it locally,
- editing it locally,
- copying/pasting it back to Tracim WebDAV,
- leads to:
  - a new revision in the existing content of an empty file,
  - a new revision in the existing content of the actual edited file.

Expected behavior:
Ignoring request when the submitted file is empty.

**Comment by tracim** [comment]
Actually, I think the request should not be ignored but not shown in history of the file. The reason for that is that ignoring the request may result in an incompatibility with what windows explorer expects, while just not showing the revision make sure not to break the workflow and «make the job»

**Comment by inkhey** [comment]
Is it better to hide theses revision in the web ui or at a more deep level of tracim ?

**Comment by lebouquetin** [comment]
I believe you can hide it in the serialization so that web ui doesn't know about these particular revisions

**Comment by inkhey** [comment]
What about first and last revision ? 
As far i test, first revision can be drop if file is empty but we lost the "created" info, that's not so good, creating fake mixed revision with 2 first revision seems to me a bit tricky. 

I do think also, that last revision should be always visible, as it's the actual one.

**Comment by lebouquetin** [comment]
@inkhey good point. First and last revisions must be visible, always. If too complicated, simply close the bug as WONTFIX
