### ISSUE TITLE
Bug: Rethinking the username popup and info/error messages design

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3263]
## Bug description & symptom

If the user does not have a username yet, a popup suggesting that he set his username appears right after the login. Some bugs and feedback about this popup:
- The "Never ask me again" message linked to the "Confirm" button is not clear at all. In reality we are talking about not displaying the popup anymore. And the functioning in general of the "Never ask me again" is not clear.
- The text in parenthesis "you will still be able to set your login in your account preferences" is not clear. There is no "preference" part in _My account_ page, it should be more about the menu "My profile" available in "My account".
- The text "Allowed characters: azAZ09-_" is not very readable, especially the last allowed character (design common to other pages).
- Sentence not clear "Changing your username will not update the mentions using your current username.". We're talking about existing mentions, right? If we parse the comments and replace the `@billi` with #userid or something like that, this sentence is no longer correct. I see two possibilities: define now the behavior of the mentions remove this sentence for the moment?

### Current design
![Screenshot from 2020-07-01 16-14-09](https://user-images.githubusercontent.com/35422692/86254487-248ec600-bbb6-11ea-9337-fc7c8a34caa2.png)

## Expected
- [x] Text changes to: Don't show this popup again (you can set your username on page My Account)
    - Ne plus afficher cette fenêtre (vous pourrez définir votre identifiant depuis la page Mon Compte)
    - Não volte a mostrar este popup (você pode definir o seu identificador na página Minha Conta)
- [x] The text `Allowed characters: azAZ09-_`should be in black, in a smaller font size and in the right corner of the form.

![Screenshot from 2020-07-02 15-27-10](https://user-images.githubusercontent.com/35422692/86364560-9deeed00-bc78-11ea-91f5-4e568cdbf108.png)

- [x] Other messages that inform something about the field input, like the _Allowed characters_, should follow the same design: below and to the right of the field (in the respective colour). If necessary put in two lines.
- [x] The messages "Changing your username will not update the mentions using your current username." and "This edition requires your administrator password" should be deleted.

**Comment by celiamgtt** [comment]
Behavior: when the user starts to write an username, the "never ask me again" message should disappear.
For the allowed characters, and idea was to put them in black, but with a right alignment to avoid to confuse the users (too close to labels design).

**Comment by lebouquetin** [comment]
by the way, I think we should replace "never ask me again" (Ne jamais me redemander) by "do not ask me again" (ne pas me redemander). The information is stored in a cookie, so when the user will use another browser or device, the question will appear again. @gbonaspetti

**Comment by gbonaspetti** [comment]
> by the way, I think we should replace "never ask me again" (Ne jamais me redemander) by "do not ask me again" (ne pas me redemander). The information is stored in a cookie, so when the user will use another browser or device, the question will appear again. @gbonaspetti

@PhilippeAccorsi also suggested "Don't show this window/popup again" (Ne plus afficher cette fenêtre) or "Define later" (Définir plus tard) and the phrase in parenthesis "You can define your login from the page My Account" (Vous pourrez définir votre identifiant depuis la page Mon Compte).

**Comment by lebouquetin** [comment]
@gbonaspetti I let you decide with @celiamgtt and/or @PhilippeAccorsi or other. My point is precisely on the *never* / *jamais* word which is wrong and should not be used. I let you decide with others what is the best wording.

**Comment by grignards** [comment]
> Other messages like the Allowed characters should follow the same design (in the respective colour). If necessary put in two lines.

@gbonaspetti Do you mean that all "Allowed characters" should appear below the text input? Or is only the style (small font/black) to be shared?

**Comment by gbonaspetti** [comment]
> > Other messages like the Allowed characters should follow the same design (in the respective colour). If necessary put in two lines.
> 
> @gbonaspetti Do you mean that all "Allowed characters" should appear below the text input? Or is only the style (small font/black) to be shared?

All messages that inform something about the field input should appear below and to the right of the field. For example, the error message "Username must be at least 3 characters" that appears when the user is typing must follow this pattern.
The color remains the color the message already had (in the example, red). 
But all "Allowed characters" messages must now be black, according to second item "*The text Allowed characters: azAZ09-_should be in black, in a smaller font size and in the right corner of the form.*".

**Comment by gbonaspetti** [comment]
Verified on develop.
