### ISSUE TITLE
Bug: Wrong error message for long username

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3279]
## Bug description & symptom

If you set a 512 character username on the popup of the first connection and try to validate after entering the password, an error appears on the password length (which says that there must be more than 6 characters), with a 5 character username there is no error on the password length. 
Visible message: "Warning The password must be at least 6 characters long" 
Backend message: "Length must be between 3 and 255."

## Expected

- [x] The error message is linked to the username and not the password.
    - Username must have between 3 and 255 characters
    - L'identifiant doit avoir entre 3 et 255 caractères
    - O identificador deve ter entre 3 e 255 caracteres
- [x] Handle with the same message in all places that a user can change the username
    - frontend - Home.jsx
    - frontend - Account.jsx
    - frontend - AdminAccount.jsx
    - frontend_app_admin_workspace_user - AdminWorkspaceUser.jsx

**Comment by lebouquetin** [comment]
@gbonaspetti backend must be explicit about the origin of the error. If the error code is shared with other error cases, it may be impossible to understand the origin of the error.

**Comment by inkhey** [comment]
@lebouquetin This can be really tricky to have a specific error code for all different schema validation problems that can occured with marshmallow, but we should be able to find a way to customize code in a way that marshmallow validation error can return different error code.

**Comment by raphj** [comment]
tested on branch.
