### ISSUE TITLE
Bug: empty field auto-completion at Add Member if username is null

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3296]
## Bug description & symptom

If we click in the auto-complete when we add a member to a workspace, it fills the field with the username. If the user not have a username the auto-completion of field is no longer performed.

## Expected

- [x] Display the public name at the field auto-completion

**Comment by PhilippeAccorsi** [comment]
Tested on branch. Wait merge to close this issue (not necessary to test this fix specially on develop)
