### ISSUE TITLE
Reactivate reset password test

### ISSUE THREAD

**Issue by ghost** [tracim/tracim#330]
Solving ["no admin calendar"](https://github.com/tracim/tracim/issues/274) causes all tests to fail, after:
```
tracim/tracim/tests/library/test_resetpassword.py:TestResetPassword.test_unit__plain_send_mail__ok
```
Deactivating it solves this odd issue, probably due to improper individual test environment setup in tests sequence.

Investigate this in order to enable reset password test anew.

**Comment by PhilippeAccorsi** [comment]
@lebouquetin Cette issue fait déjà référence au même bug.
