### ISSUE TITLE
Feat: Define precise versions for pip/setuptools/wheel

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3307]
## Feature description

Use defined versions for `pip`/`setuptools`/`wheel` python packages in:
  - the docker image.
  - the backend setup script

## Context

The docker image is built using the last available versions of the `setuptools`/`pip`/`wheel` python packages. This means that the image build is not reproducible and this can lead to unexpected errors (like the one with `setuptools==48.0.0`).
This is also the case for the `setup_default_backend.sh` script.

## Prerequisites

None

## Impacted components

- *backend*
- *docker*

## Extra information

N/A.

**Comment by PhilippeAccorsi** [comment]
I think this is needed also without docker.

**Comment by inkhey** [comment]
this is probably related to https://github.com/tracim/tracim/issues/3191 , we need to figure how to deal with multiple requirements.txt files.

**Comment by inkhey** [comment]
As we will solve similar problem for extras, this issue will be fixed in https://github.com/tracim/tracim/issues/3191
