### ISSUE TITLE
Bug: It is possible to horizontal scroll on dashboard advanced

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3314]
## Bug description & symptom

It's possible to horizontally scroll on the dashboard advanced with a touchpad on screens bigger than 1200px.

## Expected

- [x] add a `overflow-x: hidden` on the CSS class `.workspace_advanced`

## How to reproduce

1. Open dashboard advanced
1. With a touchpad, horizontally scroll

## Screenshots

![scrollDashboardAdvanced](https://user-images.githubusercontent.com/35422692/87009795-f9176700-c1c5-11ea-9e8e-f08e7cb19287.gif)

## Linked branch
fix/3314__horizontal_scroll_at_dashboard_advanced

**Comment by PhilippeAccorsi** [comment]
Verified.
