### ISSUE TITLE
Bug: TLM user.modified is not handled in the dashboard nor advanced dashboard

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3316]
## Bug description & symptom

On the dashboard and the advanced dashboard, the TLM `user.modified` is not implemented. The member list is not updated with the new name/username when changed.

## Expected

- [x] Handle TLM `user.modified`.

## Linked branch
fix/3316__handle_user_tlm_at_dashboard_and_adv_dashboard

**Comment by PhilippeAccorsi** [comment]
Verified.
