### ISSUE TITLE
Feat: Allow saving of usernames from login page

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3317]
## Feature description

Ensure that the browser's autocomplete is active for usernames on login page.

## Context

The login page allows browser to save credentials, but this does not work with usernames for some browsers (Firefox).

## Prerequisites

None

## Impacted components

- *frontend*

## Extra information

None.

**Comment by raphj** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Tested with Fireifx and Chrome.
