### ISSUE TITLE
Bug: Connection problem message appears at login screen after disconnecting

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3318]
## Bug description & symptom

The connection problem popup introduced to show TLM connection error appears at the login page if the users disconnects.

## Diagnostic

The test for displaying the messages is `status !== OPENED`, it should be `status !== OPENED && status !== CLOSED`

## Expected

The connection popup shall not be displayed after disconnecting.

## Context and version information

Tracim v3.0 beta.

## Prerequisites

None.

## How to reproduce

*Optional - detail steps to reproduce the behavior:*

1. Login
1. Disconnect
1. Wait some seconds
1. The error appears

## Impacted components

- *frontend*

**Comment by gbonaspetti** [comment]
This issue was tested at preprod.
