### ISSUE TITLE
Feat: Allow marking all notification as read

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3322]
## Feature description

It should be possible to mark all notifications as read.

- [x] add a button `Mark all as read`
  - [x] on click: all the notifications are updated with the read status and it's design changes
  - [x] on click: the header's button should also be updated

## Translations

| English | French | Portuguese |
|--|--|--|
| Mark all as read | Tout marquer comme lu | Marcar tudo como lido |

## Prerequisites

#2840 
#3323 

## Interface

![allAsRead](https://user-images.githubusercontent.com/35422692/87935620-b55c1180-ca91-11ea-83c4-01b9753d3d78.jpg)

Envelope icon's size: `12px`
Envelope icon: `fa-envelope-open-o`

----
_13-07-2020 - Description edition: Added translations._
_16-07-2020 - Description edition: Added interface and its items._
_20-07-2020 - Description edition: Added sub-items at task list and update interface._

**Comment by gbonaspetti** [comment]
This issue was moved to In Progress because some interface development is in progress, but the label remains because it's yet `blocked by frontend` (see prerequisites). I can start the development, just not finish it.

**Comment by PhilippeAccorsi** [comment]
Verified.
