### ISSUE TITLE
Feat: Add a notification button in the header

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3323]
## Feature description

- [x] add a button Notifications at header
    - icon `fa-bell-o`
- [x] add the number of non-read notifications
- [x] on click should open notification wall

## Interface

Old mockup :
![header](https://user-images.githubusercontent.com/35422692/87164031-8216c700-c2c8-11ea-893f-e358d15235ef.png)
Actual Implementation :
![image](https://user-images.githubusercontent.com/31687635/88267182-c47cd280-ccd0-11ea-9423-1a10663c0ad6.png)

## Prerequisites

#2840 
#3374 (backend endpoint)

## Impacted components

frontend

## Branch

- `feat/3323__add_notification_button_header`

---
_13-07-2020 - Description edition: specified the icon_
_21-07-2020 - Specify the branch where the solution is implemented_
_22-07-2020 - Add backend prerequisites_
_23-07-2020 - Add the updated interface_

**Comment by metzgegu** [comment]
The number of non-read notifications displayed need to have a limit in order to have enough space in the bubble
I think we need to choose between `9+`:
![TestNotif](https://user-images.githubusercontent.com/31687635/88051556-1ac70580-cb59-11ea-8050-88774c605f88.png)
And `99+`
![testNotif2](https://user-images.githubusercontent.com/31687635/88053491-2e27a000-cb5c-11ea-967a-736108183ab2.png)

**Comment by lebouquetin** [comment]
I suggest 99+ in order to let users have an information a bit more complete (ie 15 notifications for example, which would be shown as 9+ in the first case)

**Comment by metzgegu** [comment]
In order to not use the same color as `errorRed`, we decide to use the new color `lightBlue` (`#3F9FF7`)
See :
![image](https://user-images.githubusercontent.com/31687635/88267087-97c8bb00-ccd0-11ea-8ffe-577c4ce03446.png)

**Comment by gbonaspetti** [comment]
By testing this ticket I found two main problems (coming from the same cause):
- The button appears even when the user is disconnected.
- The wall does not necessarily have the good amount of notifications. When the page is updated we can see that it changes (see gif).

Cause: notifications are loaded when the page loads, not when the user connects.

![mur](https://user-images.githubusercontent.com/35422692/89995776-40dc5300-dc8a-11ea-9e7f-bb2fdc3f325d.gif)

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Tested on develop.
Some notifications not have explicit description but its in spec because we need to define which notification is mandatory and which not (need to use this feature before define list mandatory value).
