### ISSUE TITLE
Feat: Highlight mentions

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3325]
## Feature description

Mentions should be highlighted in HTML documents and in the timeline. That is, if UserX is logged, all mentions for this user should be highlighted (see interface below) in a specific way and the other mentions should be highlighted in other way.

- [x] highlight mentions "for me" (including `all` (and its translations) group mentions)
- [x] highlight other mentions

### Implementation
- [x] To have always the same style for all mentions for the resolution of this issue a `Generic.styl` file should be created in `frontend_lib` and the implementation of the style should be done in this file.
- [x] the `mention-me` class will be added dynamically (and removed when the content is saved).

## Prerequisites

#2843 

## Interface

![notifs_highlight_mentions (1)](https://user-images.githubusercontent.com/50453784/88664813-eebdfe00-d0dd-11ea-88a3-3126fadc99b1.png)
![Capture du 2020-07-28 14-23-25](https://user-images.githubusercontent.com/50453784/88664809-ee256780-d0dd-11ea-9bd9-8785768ddfb0.png)

Others mentions: in bold
My mentions: in bold + highlighted (#FFEDA2)

----
_17-07-2020 - Description edition: Specified task list and added context at begging._
_22-07-2020 - Description edition: Add 'other mentions' at this issue._
_17-08-2020 - Add implementation help and design system tag (in rekation to the mention design)._

**Comment by celiamgtt** [comment]
Updated with the Interface Part :)

**Comment by grignards** [comment]
@gbonaspetti do you have an idea of how to do the "for me" mentions styling? I'm thinking of:
- generating classes for the mention spans:
```html
<span id="mention-foo" class="mention mention-user-1">@user</span>
```
where `1` is the id of the mentioned user.
- then have a dynamic css style for the mentioned user (generated when he logs in):
```css
.mention-user-1 {
 background-color: #FFEDA2
}
```
Would this approach appear sensible to you?

**Comment by raphj** [comment]
I'd go with a class name like mention-me without any dynamic CSS @grignards

**Comment by grignards** [comment]
> I'd go with a class name like `mention-me` without any dynamic CSS @grignards.
> 
> In HTML documents should we actually embed the span tags / the class or should we parse and add them on load?

Err… I do not see how this could work since the display must be different if the user is the one mentioned or not. Or would you rather modify the contents dynamically in order to add this `mention-me` class?

**Comment by raphj** [comment]
Mhm, to me it was probably easier to do something like `doc.getElementsByClassName("mention-xxx").map(el => el.classList.add("mention-me")` on load and then `doc.getElementsByClassName("mention-me").map(el => el.classList.remove("mention-me")` when saving, and cleaner too: the CSS remains static.

If loading a dynamic a CSS is way easier or feels cleaner, I am ok with this solution too.

**Comment by gbonaspetti** [comment]
@raphj @grignards initially, I was thinking of something more like what Raphael was proposing, but the two solutions are good for me.

**Comment by raphj** [comment]
it'd be a foreach instead of a map btw.

**Comment by inkhey** [comment]
Just begin test on branch, i have some remark:

1. First, i will expect to have some kind of popup about user when i put my mouse over the mention, like in both mattermost and github, Is there discussion about this somewhere ?
2. What about group mention and highlighting, it's curious that mentioning everyone doesn't mean highlight for everyone ?
3. Bold doesn't seems to work in html-document (not mention specific)

**Comment by grignards** [comment]
> Just begin test on branch, i have some remark:
> 
>     1. First, i will expect to have some kind of popup about user when i put my mouse over the mention, like in both mattermost and github, Is there discussion about this somewhere ?

I'm not aware of such a discussion (did a quick search in issues, nothing is related to this functionnality). Could you create an issue for this improvement ?

>     2. What about group mention and highlighting, it's curious that mentioning everyone doesn't mean highlight for everyone ?

For this you'll have to ask @celiamgtt. I don't know if this is a good idea.

> 
>     3. Bold doesn't seems to work in html-document (not mention specific) : maybe #2801 related ?

Do you mean it doesn't work when editing the html-document? Or always?

**Comment by inkhey** [comment]
> > ```
> > 3. Bold doesn't seems to work in html-document (not mention specific) : maybe #2801 related ?
> > ```
> 
> Do you mean it doesn't work when editing the html-document? Or always?

I recheck, it's seems #2801 related, the bold is not bold enough, especially in html-document. 
Maybe we should only pull develop with #2801 fix in this PR and retest in order to clearly see the difference.

**Comment by inkhey** [comment]
issue created about this mouseover popup: https://github.com/tracim/tracim/issues/3502

**Comment by celiamgtt** [comment]
Highlight is a quick indication for users to know where we are talking about them, so the group mentions to which they belong should be highlighted too (for them).

**Comment by grignards** [comment]
@inkhey I just added the highlighting for all/tous/todos, could you retest?

**Comment by inkhey** [comment]
@grignards 
Something goes wrong with this new implementation:
![Capture du 2020-09-04 10-24-47](https://user-images.githubusercontent.com/7851652/92218133-f15c0200-ee98-11ea-9621-3d08117342db.png)

**Comment by grignards** [comment]
@inkhey should be ok now.

**Comment by inkhey** [comment]
@grignards 
That's way better but i just found a very strange bug:
![strange_behavior](https://user-images.githubusercontent.com/7851652/92224385-06895e80-eea2-11ea-9ce8-c40cb816104a.gif)

**Comment by grignards** [comment]
I created an issue for this bug as it was already present in develop: https://github.com/tracim/tracim/issues/3507

**Comment by inkhey** [comment]
Tested on branch, as the bug found will be fixed somewhere else, we can merge this.

**Comment by PhilippeAccorsi** [comment]
Verified.
