### ISSUE TITLE
Feat: Change browser tab title and icon

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3326]
## Feature description
In the title of the page (which is shown in the title of the tab in most browsers, and also in the task list of most desktop environment):

- [x] Add the number of unread notifications
     - Produce this `CustomEvent` when a `TLM` notification was received. This `CustomEvent` will update the title with the current number of unread notifications.
     - Add a limit of 99+ like the header button
- [x] Modify of the favicon to indicate that there are notifications not read

## Interface

![onglet_notifs (1)](https://user-images.githubusercontent.com/50453784/88676042-e66cbf80-d0eb-11ea-9f4f-1ef5f80aa380.png)

## Prerequisites
- backend endpoint https://github.com/tracim/tracim/issues/3374

----
_28-07-2020 - Description updated: Add interface and backend prerequisites._

**Comment by metzgegu** [comment]
## Implemented solution :

### Head title
I put the head title in Redux, The head title will be set when its value or if the notification not read count has changed in Redux, so the Tracim.jsx will build the head title with these 2 parts `(${notificationPage.notificationNotReadCount}) ${system.headTitle}`
### Favicon
When the notificationNotReadCount > 0 the favicon will be re-draw with a blue circle, and when the notificationNotReadCount === 0 it will re-draw the favicon with its original `href`

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Verified.
