### ISSUE TITLE
Feat: Prevent users from setting their username with one of the group mentions

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3327]
## Feature description

A user must not be able to set their username with one of the words reserved for the group mentions (`@all` and its translations).

- [x] Add the error message (see translation table) following the same design that other live error messages like "This username is not available"
![Capture d'écran de 2020-08-10 15-29-42](https://user-images.githubusercontent.com/35422692/89787829-72d0a680-db1e-11ea-8369-505332e3686b.png)

## Translations

| English | French | Portuguese |
|--|--|--|
| This word is reserved for group mentions | Ce mot est réservé aux mentions de groupe | Esta palavra é reservada às menções de grupo |

## Prerequisites

backend https://github.com/tracim/tracim/issues/3328

## Impacted components

- frontend (Home.jsx, Account.jsx, AdminAccount.jsx)
- frontend_app_admin_workspace_user (AdminWorkspaceUser.jsx)

------
*2020-07-30 - Only keep `all` group mention.*
_2020-08-10 - Update translation, interface exemple and add label related to the prerequisite._

**Comment by raphj** [comment]
I don't find the displayed message explicit enough.  Should we display a message that explains that this reserved word collides with the group mentions? Something like "this word is reserved for group mentions"?

@celiamgtt @gbonaspetti

**Comment by PhilippeAccorsi** [comment]
> I don't find the displayed message explicit enough. Should we display a message that explains that this reserved word collides with the group mentions? Something like "this word is reserved for group mentions"?
> 
> @celiamgtt @gbonaspetti

@gbonaspetti can you reply here about what is done ?

**Comment by gbonaspetti** [comment]
> I don't find the displayed message explicit enough. Should we display a message that explains that this reserved word collides with the group mentions? Something like "this word is reserved for group mentions"?
> 
> @celiamgtt @gbonaspetti

I updated the message with your suggestion.

**Comment by PhilippeAccorsi** [comment]
Verified.
