### ISSUE TITLE
Feat: Ensure a username does not collide with group mentions names

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3328]
## Feature description

It mustn't be possible to create a username using predefined "groups":

- [x] When setting a username (`PUT
/api/users/{user_id:\d+}/username` endpoint), ensure that the given username does not collide with `@all` and its translations (as found in #3350). If it does this is a 400 error + an appropriate error code (and message).
- [x] Provide an endpoint (`GET /api/system/reserved-usernames`) giving the list of group mentions (and their translations) so that the frontend can display the appropriate message (see #3327).
- [x] Modify the  (`GET /api/system/username-availability`) endpoint so that it returns False for any group mention.

## Prerequisites

The list of translated group names should be available: #3350

## Impacted components

- *backend*

----
_20-07-2020 - Description edition: Add prerequiste's issue number, put the context at the beginning and specified the languages that should be handled._
_30-07-2020 - Description edition: Only keep `all` group mention, complete task list._

**Comment by lebouquetin** [comment]
@grignards another prerequisite is that a endpoint publish the list of forbidden usernames (for all languages): #3327 requires it.

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Verified.
