### ISSUE TITLE
Bug: The size of columns and the header on the admin user table isn't user friendly

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3331]
## Bug description & symptom

In the admin user page, the management of columns is weird, the user's email is not completely visible anymore. This makes it difficult to carry out administration tasks.

Some columns have a fixed width while there is little text in them (but wide size).

![Screenshot from 2020-07-15 10-26-10](https://user-images.githubusercontent.com/35422692/87522287-b6ea9b80-c685-11ea-94b8-6e4698a59199.png)

### Expected:

- [x] Redistribute column sizes with a better logic according its content

In addition to fixing the **table** size, i.e., do not vary according to the internal content. The strategy used for size redistribution was to assign 70px (size of avatar's profile) for the only column that maintains the same size regardless of the screen size (column `Profile`), and for the rest, from 100%, assign a percentage size for each column according to the size that normally has its contents. The `User` and `Email` are usually a little longer, so both are 18% the size of the table. After that, the `Active` column (especially when you are deactivated) and the  `Username` column, have a 17% size. And finally, the `Can create shared space` and `Administrator`
 columns are 15% of the table size.

Expected interface:
![Screenshot from 2020-07-27 17-21-00](https://user-images.githubusercontent.com/35422692/88559929-bced5e80-d02d-11ea-917f-68e10f3c9244.png)

- [x] Define a height size to table header (more details at comments https://github.com/tracim/tracim/issues/3331#issuecomment-672899817)

The size defined was 75px and the text was aligned in the middle.

## Diagnostic

The mail column doesn't have a minimum size so the others try to use the space, because they don't have the `...` to shrink, even if they don't have a minimum size either.

## Linked branch
fix/3331__redistribute_column_sizes

-----

_27-07-2020 - Description updated: Redistribution strategy and expected interface._
_13-08-2020 - Add a height size for table header task._

**Comment by lebouquetin** [comment]
@gbonaspetti what is the redistribution strategy you implemented? Could you add here some explanation + a screenshot?

**Comment by gbonaspetti** [comment]
> @gbonaspetti what is the redistribution strategy you implemented? Could you add here some explanation + a screenshot?

Yes, description updated.

**Comment by lebouquetin** [comment]
:+1:

**Comment by raphj** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
@gbonaspetti I have a question: is it not possible to have column title all the time visible on first line, also if one column title use two line ?

its not very freindly to see all column title moving when switching from english to other language:

![column_title_moving](https://user-images.githubusercontent.com/25848257/90026149-3d12f580-dcb7-11ea-8461-8621192cd80d.gif)

**Comment by gbonaspetti** [comment]
> @gbonaspetti I have a question: is it not possible to have column title all the time visible on first line, also if one column title use two line ?
> 
> its not very freindly to see all column title moving when switching from english to other language:
> 
> ...

@PhilippeAccorsi everything is possible :smile: for this problem I see two easy ways to fix (personally I prefer the first one):
1. Set the header (title's line) with a minimum fixed size of two lines
2. Set the size of this column bigger to do not have a two line title

What do you think?

**Comment by PhilippeAccorsi** [comment]
I think the first one is a good idea. I prefer if nothing change (just text) when user change language of Tracim.

**Comment by gbonaspetti** [comment]
> I think the first one is a good idea. I prefer if nothing change (just text) when user change language of Tracim.

And we make a new ticket for this change or I update this one?

**Comment by PhilippeAccorsi** [comment]
I thinks its more simple/quick to just update this ticket, and move ticket in to do.

**Comment by PhilippeAccorsi** [comment]
Verified.
