### ISSUE TITLE
Bug: AdminWorkspace is not updated after a user has been removed in a shared space

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#3335]
## Bug description & symptom

When a user is added and then removed from a workspace, the workspace members counter is not updated in the `AdminWorkspace` page.

Expected:
- [x] The workspace members counter is updated correctly

## Diagnostic

TLM handlers of `AdminWorkspace` don't handle the `SHAREDSPACE_MEMBER` events correctly.
The data received with the TLM wasn't correctly added in the handlers.

## Branch

`fix/3335__workspace_member_TLM_admin_workspace`

**Comment by gbonaspetti** [comment]
Tested on branch
