### ISSUE TITLE
Bug: The gallery is not always refreshed correctly with content.modified TLMs

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#3337]
## Bug description & symptom

When a user uploads a new version of a file, the gallery isn't always correctly updated.
The preview does not always updates.
Moving a content outside the folder doesn't update the gallery.

## Diagnostic and implementation 

Function `liveMessageNotRelevant()` doesn't work well because its assertion is not correct.
Indeed, if the `state.folderId` is `undefined` (gallery of the workspace root) it will always return `true`
Moving content is not handled with TLM handlers.

## Branch

- `fix/3337__gallery_preview_refresh`

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by raphj** [comment]
Further development on this issue: https://github.com/tracim/tracim/issues/3425 (it is probably necessary to cherry-pick that one, should this one be cherry-picked for Tracim 3.0.X)

**Comment by PhilippeAccorsi** [comment]
Verified.
