### ISSUE TITLE
Bug: Breadcrumbs and head title aren't always updated after content.modified

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#3342]
## Bug description & symptom

The breadcrumbs and the head title need to be updated with the new content name when a `content.modified` TLM arrives.

Expected: Add `this.breadcrumbs()` and `this.setHeadTitle()` in each app features :
- [x] App file
- [x] App Html doc
- [x] App Thread
- [x] App folder

## Diagnostic

Each content App need to dispatch a `CustomEvent` to set the head title and the breadcrumbs when its content has changed

**Comment by metzgegu** [comment]
### Implementation  

- Call buildBreadcrumbs() and setHeadTitle() when the current content has changed and if the token is the author
- Refactor the buildBreadcrumbs function in order to call it when loading the content with a content args (in order to avoid calling the function with a new state which was just set with a setState())

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Verified.
