### ISSUE TITLE
Feat: Generate event for new mentions in updated HTML documents and comments 

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3348]
## Feature description and goals

In order to generate TLMs for mentions (meta: #2838), we need to be able to find *new* mentions in updated:
- [ ] HTML documents
- [ ] comments

(for example, make a diff of the document/comment or parse mentions for the current and new revision then see which ones have been added)

## Prerequisites

- #3347 - handle the mention in created HTML documents and comments

**Comment by lebouquetin** [comment]
Mentions are not for HTML documents and comments but for all content descriptions.

**Comment by grignards** [comment]
Closing this issue in favor of the unified one: #3347.
