### ISSUE TITLE
Feat: Handle the translations of group mentions

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3350]
## Feature description and goals

- [ ] Handle the translation of group mentions (as part of meta: #2838).

As the group mention only has `all` currently and it is unsure we'll have other comparable special groups the translations won't be shared with the frontend programmatically.

## Prerequisites

- #3347

## Translations

| En | Fr | Pt |
|--|--|--|
| `@all` | `@tous` | `@todos` |

## See also

#3365

----

_20-07-2020 - Description edition: added task list and the discussion goal_
_20-07-2020 - Description edition: added see also_
_30-07-2020 - Only keep all group mention for now. Translation won't be shared for the time being.

**Comment by inkhey** [comment]
About translation in backend and frontend:
- Backend doesn't know which language it support
- Backend generate traduction from gettext file which are then converted to i18next json format
- Backend translation are all in same .json file backend.json
- Backend use backend.json file for translation
- It look like frontend does not use this file. It seems to me that in previous version frontend does use backend.json file but i don't see any code about this or about moving backend.json file.

**Comment by grignards** [comment]
Closing this issue as we decided to not share the translations between front and backend for now (only one word to translate, `all`).

**Comment by raphj** [comment]
Removed this from the project in consequence @PhilippeAccorsi
