### ISSUE TITLE
Bug: FlashMessage about password validity is not specific enough when adding user

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#3363]
## Description and expectations

When the notifications are enabled, adding a new user with a wrong password will display this message (`Error while saving new user`) which is not specific enough to be user friendly.
The password verification is only made if the notifications are disabled because when enabled, the password is not mandatory.
The condition need to be fixed in the handler.

### How to reproduce

Add a new user when the notifications are enabled with an invalid password.

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Verified.
