### ISSUE TITLE
Bug: wrong integration of pushpin in the docker image

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#3369]
## Description and expectations

- the log files of pushpin and redis are in `/var/log/pushpin/` and `/var/log/redis`.

Expected: log files in `/var/tracim/logs/`

**Comment by PhilippeAccorsi** [comment]
I add also zurl log in volume.

**Comment by PhilippeAccorsi** [comment]
- All log file are created when path folder not exist.
- new log file are added for tracim 3.0.0
- right access modification

**Comment by PhilippeAccorsi** [comment]
Manually tested by @inkhey (with new image from scratch and with migration from existing installation).

**Comment by PhilippeAccorsi** [comment]
Something wrong in common.sh file.

- if syntax not working
~~~
# Create Zurl log (necessary when migrate from Tracim < 3.0.0 )
if [ ]/var/tracim/logs/zurl.log ];then
    touch /var/tracim/logs/zurl.log
    chown www-data:www-data /var/tracim/logs/zurl.log
fi
~~~

- missing chmod
~~~
chmod 775 /var/tracim/logs/zurl.log
~~~

**Comment by PhilippeAccorsi** [comment]
Last fix tested on branch. Zurl log correctly created.
