### ISSUE TITLE
Bug: pushpin sometimes does not seem to start correctly with the docker image

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#3372]
## Description and expectations

I started Tracim 3.0.0_rc2 and saw that the pushpin service did not start correctly.
first try is rc2, second try is with rc1.

**Try rc2**

|UID|PID|PPID|C|STIME|TTY|TIME|CMD|
|--|--|--|--|--|--|--|--|
|root|3790|3772|0|16:49|?|00:00:00|/bin/bash /tracim/tools_docker/Debian_Uwsgi/entrypoint.sh|
|systemd+|3968|    3790|    0|16:50|   ?|00:00:00|/usr/bin/zurl --config=/etc/zurl.conf --logfile=/var/log/zurl.log|
|systemd+|3983|    3790|    0|16:50|   ?|00:00:00|/usr/bin/redis-server 127.0.0.1:6379|
|root|    4010|    3790|    0|16:50|   ?|00:00:00|/usr/sbin/apache2 -k start|
|www-data|4014|    4010|    0|16:50|   ?|00:00:00|/usr/sbin/apache2 -k start|
|www-data|4015|    4010|    0|16:50|   ?|00:00:00|/usr/sbin/apache2 -k start|
|root|    4089|    3790|    0|16:50|   ?|00:00:00|/usr/bin/python /usr/bin/supervisord -c /tracim/tools_docker/Debian_Uwsgi/supervisord_tracim.conf|
|root|    4092|    4089|    2|16:50|   ?|00:00:01|/usr/bin/python3 /usr/local/bin/rq worker -q -w tracim_backend.lib.rq.worker.DatabaseWorker event|
|root|    4093|    4089|    2|16:50|   ?|00:00:01|python3 /tracim/backend/daemons/mail_notifier.py|
|root|    4094|    4089|    2|16:50|   ?|00:00:01|python3 /tracim/backend/daemons/mail_fetcher.py|
|www-data|4332|    3790|    2|16:50|   ?|00:00:01|/usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/tracim_caldav.ini --daemonize /var/log/uwsgi/app/tracim_caldav.log|
|www-data|4453|    3790|    4|16:50|   ?|00:00:02|/usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/tracim_web.ini --daemonize /var/log/uwsgi/app/tracim_web.log|
|www-data|4564|    3790|    2|16:50|   ?|00:00:01|/usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/tracim_webdav.ini --daemonize /var/log/uwsgi/app/tracim_webdav.log|
|root|    4578|    4094|    0|16:50|   ?|00:00:00|git cat-file --batch-check|
|root|    4580|    4092|    0|16:50|   ?|00:00:00|git cat-file --batch-check|
|root|    4581|    4094|    0|16:50|   ?|00:00:00|git cat-file --batch|
|root|    4582|    4092|    0|16:50|   ?|00:00:00|git cat-file --batch|
|root|    4585|    4093|    0|16:50|   ?|00:00:00|git cat-file --batch-check|
|root|    4586|    4093|    0|16:50|   ?|00:00:00|git cat-file --batch|
|www-data|4626|    4332|    0|16:50|   ?|00:00:00|/usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/tracim_caldav.ini --daemonize /var/log/uwsgi/app/tracim_caldav.log|
|www-data|4634|    4332|    0|16:50|   ?|00:00:00|/usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/tracim_caldav.ini --daemonize /var/log/uwsgi/app/tracim_caldav.log|
|www-data|4642|    4453|    0|16:50|   ?|00:00:00|git cat-file --batch-check|
|www-data|4643|    4453|    0|16:50|   ?|00:00:00|git cat-file --batch|
|www-data|4645|    4564|    0|16:50|   ?|00:00:00|git cat-file --batch-check|
|www-data|4646|    4564|    0|16:50|   ?|00:00:00|git cat-file --batch|
|www-data|4648|    4564|    0|16:50|   ?|00:00:00|git cat-file --batch-check|
|www-data|4649|    4564|    0|16:50|   ?|00:00:00|git cat-file --batch|
|www-data|4651|    4564|    0|16:50|   ?|00:00:00|/usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/tracim_webdav.ini --daemonize /var/log/uwsgi/app/tracim_webdav.log|
|www-data|4655|    4453|    0|16:50|   ?|00:00:00|/usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/tracim_web.ini --daemonize /var/log/uwsgi/app/tracim_web.log|
|www-data|4659|    4453|    0|16:50|   ?|00:00:00|/usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/tracim_web.ini --daemonize /var/log/uwsgi/app/tracim_web.log|
|www-data|4663|    4453|    0|16:50|   ?|00:00:00|/usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/tracim_web.ini --daemonize /var/log/uwsgi/app/tracim_web.log|
|www-data|4667|    4453|    0|16:50|   ?|00:00:00|/usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/tracim_web.ini --daemonize /var/log/uwsgi/app/tracim_web.log|
|root|    4671|    3790|    0|16:50|   ?|00:00:00|tail -f /var/tracim/logs/tracim_web.log|

**Try rc1**

|UID|PID|PPID|C|STIME|TTY|TIME|CMD|
|--|--|--|--|--|--|--|--|
|root|    5077|    5058|    0|16:51|   ?|00:00:00|/bin/bash /tracim/tools_docker/Debian_Uwsgi/entrypoint.sh|
|Debian-+|5301|    5077|    0|16:51|   ?|00:00:00|/usr/bin/pushpin|
|systemd+|5312|    5077|    0|16:51|   ?|00:00:00|/usr/bin/zurl --config=/etc/zurl.conf --logfile=/var/log/zurl.log|
|systemd+|5329|    5077|    0|16:51|   ?|00:00:00|/usr/bin/redis-server 127.0.0.1:6379|
|root|    5364|    5077|    0|16:51|   ?|00:00:00|/usr/sbin/apache2 -k start|
|www-data|5367|    5364|    0|16:51|   ?|00:00:00|/usr/sbin/apache2 -k start|
|www-data|5368|    5364|    0|16:51|   ?|00:00:00|/usr/sbin/apache2 -k start|
|Debian-+|5427|    5301|    0|16:51|   ?|00:00:00|mongrel2 /var/run/pushpin/mongrel2.sqlite default_7999|
|Debian-+|5428|    5301|    0|16:51|   ?|00:00:00|m2adapter --config=/var/run/pushpin/m2adapter.conf --logfile=/var/log/pushpin/m2adapter.log|
|Debian-+|5429|    5301|    0|16:51|   ?|00:00:00|pushpin-proxy --config=/etc/pushpin/pushpin.conf --ipc-prefix=pushpin- --logfile=/var/log/pushpin/pushpin-proxy.log|
|Debian-+|5430|    5301|    0|16:51|   ?|00:00:00|pushpin-handler --config=/etc/pushpin/pushpin.conf --ipc-prefix=pushpin- --logfile=/var/log/pushpin/pushpin-handler.log|
|root|    5448|    5077|    0|16:51|   ?|00:00:00|/usr/bin/python /usr/bin/supervisord -c /tracim/tools_docker/Debian_Uwsgi/supervisord_tracim.conf|
|root|    5450|    5448|    0|16:51|   ?|00:00:00|Xvfb :99 -screen 0 1x1x16|
|root|    5451|    5448|    12|      16:51|   ?|00:00:01|/usr/bin/python3 /usr/local/bin/rq worker -q -w tracim_backend.lib.rq.worker.DatabaseWorker event|
|root|    5452|    5448|    12|      16:51|   ?|00:00:01|python3 /tracim/backend/daemons/mail_notifier.py|
|root|    5453|    5448|    12|      16:51|   ?|00:00:01|python3 /tracim/backend/daemons/mail_fetcher.py|
|www-data|5709|    5077|    14|      16:51|   ?|00:00:01|/usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/tracim_caldav.ini --daemonize /var/log/uwsgi/app/tracim_caldav.log|
|www-data|5819|    5077|    21|      16:51|   ?|00:00:02|/usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/tracim_web.ini --daemonize /var/log/uwsgi/app/tracim_web.log|
|www-data|5933|    5077|    14|      16:51|   ?|00:00:01|/usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/tracim_webdav.ini --daemonize /var/log/uwsgi/app/tracim_webdav.log|
|root|    5944|    5452|    0|16:51|   ?|00:00:00|git cat-file --batch-check|
|root|    5945|    5452|    0|16:51|   ?|00:00:00|git cat-file --batch|
|root|    5946|    5451|    0|16:51|   ?|00:00:00|git cat-file --batch-check|
|root|    5948|    5451|    0|16:51|   ?|00:00:00|git cat-file --batch|
|root|    5953|    5453|    0|16:51|   ?|00:00:00|git cat-file --batch-check|
|root|    5954|    5453|    0|16:51|   ?|00:00:00|git cat-file --batch|
|www-data|5992|    5709|    0|16:51|   ?|00:00:00|/usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/tracim_caldav.ini --daemonize /var/log/uwsgi/app/tracim_caldav.log|
|www-data|5993|    5709|    1|16:51|   ?|00:00:00|/usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/tracim_caldav.ini --daemonize /var/log/uwsgi/app/tracim_caldav.log|
|www-data|6011|    5819|    0|16:51|   ?|00:00:00|git cat-file --batch-check|
|www-data|6012|    5819|    0|16:51|   ?|00:00:00|git cat-file --batch|
|www-data|6014|    5933|    0|16:51|   ?|00:00:00|git cat-file --batch-check|
|www-data|6015|    5933|    0|16:51|   ?|00:00:00|git cat-file --batch|
|www-data|6017|    5933|    0|16:51|   ?|00:00:00|git cat-file --batch-check|
|www-data|6018|    5933|    0|16:51|   ?|00:00:00|git cat-file --batch|
|www-data|6020|    5933|    0|16:51|   ?|00:00:00|/usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/tracim_webdav.ini --daemonize /var/log/uwsgi/app/tracim_webdav.log|
|www-data|6022|    5819|    0|16:51|   ?|00:00:00|/usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/tracim_web.ini --daemonize /var/log/uwsgi/app/tracim_web.log|
|www-data|6026|    5819|    0|16:51|   ?|00:00:00|/usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/tracim_web.ini --daemonize /var/log/uwsgi/app/tracim_web.log|
|www-data|6030|    5819|    0|16:51|   ?|00:00:00|/usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/tracim_web.ini --daemonize /var/log/uwsgi/app/tracim_web.log|
|www-data|6046|    5819|    0|16:51|   ?|00:00:00|/usr/bin/uwsgi --ini /usr/share/uwsgi/conf/default.ini --ini /etc/uwsgi/apps-enabled/tracim_web.ini --daemonize /var/log/uwsgi/app/tracim_web.log|
|root|    6054|    5077|    0|16:51|   ?|00:00:00|tail -f /var/tracim/logs/tracim_web.log|

### How to reproduce

- Not easy to reproduce

### Version information

Tracim 3.0.0_rc1 and 2

________________________________________________
*The following sections are for the maintainers*

## Diagnostic

Explain what may cause the bug.

## Prerequisites

Optional - list the issues that must be solved or what needs to be done before handling this issue.

## Required sections, if relevant

 - To be discussed before development
 - Interface
 - Translations
 - Workaround
 - Extra information
 - Implemented solution

**Comment by PhilippeAccorsi** [comment]
After some test, I have reproduced the bug. Pushpin stretch package is in version 1.15 on us docker image.

Error visible in mongrel2_7999.log
~~~
Wed, 22 Jul 2020 15:04:41 GMT [ERROR] (src/unixy.c:158: errno: No such file or directory) Process 176 is still running, shut it down first.
Wed, 22 Jul 2020 15:04:41 GMT [ERROR] (src/mongrel2.c:180: errno: None) Failed to remove the dead PID file: /var/run/pushpin/mongrel2_7999.pid
Wed, 22 Jul 2020 15:04:41 GMT [ERROR] (src/mongrel2.c:419: errno: None) PID file failure, aborting rather than trying to start.
Wed, 22 Jul 2020 15:04:41 GMT [ERROR] (src/mongrel2.c:451: errno: None) Exiting due to error.
~~~

Same bug visible in this issue https://github.com/fanout/pushpin/issues/47638 and the solution is to update Pushpin to 1.18

**Comment by grignards** [comment]
It is possible to install the newer versions by using pushpin's repository: https://pushpin.org/docs/install/#packages

**Comment by PhilippeAccorsi** [comment]
This bug not appear on travis test, maybe because pushpin used on travis is not the same version like we have in Tracim Docker image.

**Comment by PhilippeAccorsi** [comment]
Tested.
