### ISSUE TITLE
Bug: Activating the remote authentication breaks cookie session authentication

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3373]
## Description and expectations

When the remote authentication is enabled in Tracim login using cookies/session becomes impossible.

### How to reproduce

Enable remote authentication on a tracim instance, try to login with a browser.

### Version information
- Tracim version: 3.0.x

## Diagnostic

A change in unauthenticated user id getter method of remote authentication is the reason for this regression.

## Prerequisites

None.

## Required sections, if relevant

 - To be discussed before development
 - Interface
 - Translations
 - Workaround
 - Extra information
 - Implemented solution

**Comment by grignards** [comment]
The problem was a change that make the remote authentication an empty string instead of a `None` value leading the cookie authentication to use the empty string as the user id.

**Comment by PhilippeAccorsi** [comment]
Manually tested on production.
