### ISSUE TITLE
Feat: Add an endpoint to get the number of unread TLMs

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#3374]
## Feature description and goals

We need to get the number of unread messages. We need to add a new endpoint to give this information.

To do:

- [x] Add this endpoint: GET `/users/${userId}/messages/summary` 
- [x] Add a `event_types` filter parram

Expected specifications:
```
GET /api/users/{user_id:\d+}/messages/summary
{
  "messages_count": 353,
  "read_messages_count": 112,
  "unread_messages_count": 241,
  "user": {
    "avatar_url": "/api/asset/avatars/john-doe.jpg",
    "public_name": "John Doe",
    "user_id": 3,
    "username": "My-Power_User99"
  },
  "user_id": 3,
}
```

## Implementation:

- message summary endpoint that return user and read/unread/total count of messages.
- This endpoint has a event_types query filter that can handle list of valid event_types separated by "," character

___
Edited 2020-07-24: changed the endpoint name according to @inkey's suggestion
Edited 2020-07-27: changed the endpoint name according to https://github.com/tracim/tracim/issues/3374#issuecomment-664426954
Edited 2020-07-29: clarify full specification of endpoint.
Edited 2020-07-30: ad Implementation detail

**Comment by inkhey** [comment]
1. As far i know, having exact number of unread content is nice but may be not mandatory. Frontend can give an estimation using endpoint to get unread messages and return "100+" instead of 241 for example.

2. Having exact number is a nice feature, so if we do need an endpoint for it, as we do not have really similar endpoint now, i do suggest to follow the `/api/users/{user_id:\d+}/disk_space` style.

so i suggest something like:


```
GET /api/users/{user_id:\d+}/messages/infos

{
  "messages_count": 353,
  "read_messages_count": 112,
  "unread_messages_count": 241,
  "avatar_url": "/api/asset/avatars/john-doe.jpg",
  "public_name": "John Doe",
  "user": {
    "avatar_url": "/api/asset/avatars/john-doe.jpg",
    "public_name": "John Doe",
    "user_id": 3,
    "username": "My-Power_User99"
  },
  "user_id": 3,
  "username": "My-Power_User99"
}

```

**Comment by metzgegu** [comment]
1. Yes in our `frontend`, it will display the number of notification not read up to `99`, but I think the `backend` should give the exact number of unread content

**Comment by metzgegu** [comment]
We need also add a `event_types` filter parram

**Comment by inkhey** [comment]
> We need also add a `event_types` filter parram

It's in ticket https://github.com/tracim/tracim/issues/3057

**Comment by raphj** [comment]
I like @inkey's suggested endpoint. The number of messages is redundant with the number of read + the number of unread messages. We might want to leave out the number of read messages, but I don't have a strong opinion on this.

**Comment by lebouquetin** [comment]
> The number of messages is redundant with the number of read + the number of unread messages

Someone has to compute the calculation. The most ready-to-use information you give, the easier it will be to use. If you return 2 numbers, this is not an effort to return 3 - and the API user has no question to ask: the answer is already there!

**Comment by metzgegu** [comment]
> > We need also add a `event_types` filter parram
> 
> It's in ticket #3057

Actually, this filter need also to be present in this new endpoint

**Comment by lebouquetin** [comment]
> ```
> GET /api/users/{user_id:\d+}/messages/infos
> {
>   "messages_count": 353,
>   "read_messages_count": 112,
>   "unread_messages_count": 241,
>   "avatar_url": "/api/asset/avatars/john-doe.jpg",
>   "public_name": "John Doe",
>   "user": {
>     "avatar_url": "/api/asset/avatars/john-doe.jpg",
>     "public_name": "John Doe",
>     "user_id": 3,
>     "username": "My-Power_User99"
>   },
>   "user_id": 3,
>   "username": "My-Power_User99"
> }
> ```

Why do you duplicate user information?

**Comment by lebouquetin** [comment]
by the way, @inkhey (and @grignards) what is the rule for query parameters? We do put them in plural form? singular? Where are the coding rules for REST APIs?

**Comment by raphj** [comment]
Oh by the way, information is always a singular noun in English, we should not put a plural ("infos") here I think. @inkhey

**Comment by inkhey** [comment]
> > ```
> > GET /api/users/{user_id:\d+}/messages/infos
> > {
> >   "messages_count": 353,
> >   "read_messages_count": 112,
> >   "unread_messages_count": 241,
> >   "avatar_url": "/api/asset/avatars/john-doe.jpg",
> >   "public_name": "John Doe",
> >   "user": {
> >     "avatar_url": "/api/asset/avatars/john-doe.jpg",
> >     "public_name": "John Doe",
> >     "user_id": 3,
> >     "username": "My-Power_User99"
> >   },
> >   "user_id": 3,
> >   "username": "My-Power_User99"
> > }
> > ```
> 
> Why do you duplicate user information?

This is based on the current return of UserDiskSchema, but you're right, something is uncorrect.
 As far i check, It Seems there is a bug with UserDiskSchema, which should not inherit UserDigestSchema.
We should create a specific bug about this one (don't know if frontend use the duplicated value).

So, the schema for message info we should have is:
```
GET /api/users/{user_id:\d+}/messages/info
{
  "messages_count": 353,
  "read_messages_count": 112,
  "unread_messages_count": 241,
  "user": {
    "avatar_url": "/api/asset/avatars/john-doe.jpg",
    "public_name": "John Doe",
    "user_id": 3,
    "username": "My-Power_User99"
  },
  "user_id": 3,
}

```
The duplication of user_id is expected here.

**Comment by raphj** [comment]
@inkhey would it be okay for every `/messages/` endpoint to not return the `user` field?

**Comment by inkhey** [comment]
> @inkhey would it be okay for every `/messages/` endpoint to not return the `user` field?

This will not be logical according to decision made for disk_usage endpoint : 
see https://github.com/tracim/tracim/issues/2518

**Comment by lebouquetin** [comment]
`GET /api/users/{user_id:\d+}/messages/infos` => `GET /api/users/{user_id:\d+}/messages/resume` ?

**Comment by raphj** [comment]
`info` looks good to me, I would prefer `summary` over `resume`. `resume` sounds like curriculum vitae to me but TIL résumé also means summary of details.

**Comment by lebouquetin** [comment]
you right @raphj `summary` is better.

**Comment by PhilippeAccorsi** [comment]
@inkhey you write `We should create a specific bug about this one (don't know if frontend use the duplicated value).` in your comment https://github.com/tracim/tracim/issues/3374#issuecomment-664394434

can you add here a link to the issue you have created ?

**Comment by inkhey** [comment]
> @inkhey you write `We should create a specific bug about this one (don't know if frontend use the duplicated value).` in your comment [#3374 (comment)](https://github.com/tracim/tracim/issues/3374#issuecomment-664394434)
> 
> can you add here a link to the issue you have created ?

https://github.com/tracim/tracim/issues/3381

**Comment by PhilippeAccorsi** [comment]
Verified.
