### ISSUE TITLE
Feat: Add endpoint to get/set user configuration

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#3380]
## Feature description and goals

This issue implements endpoint `/api/users/{user_id}/config` which lets the frontend get and set user configuration accessible across multiple devices. The endpoint shall be generic, so the frontend can store anything it wants here.

The current usage will be to store the status of the "username popup".
We are going to:
 - [x] create a new `user_config` table with rows `user_id`, `fields` where `fields` is a json string. The initial value of `fields` if `{}`.
 - [x] add an endpoint to get all the parameters
 - [x] add an endpoint to set several parameters

Examples:
```
GET /api/users/1/config
200 OK
{
    parameters: {
        "someparameter":"something"
    }
}


POST /api/users/1/config
{
    parameters : {
        "someparameter":"something"
    }
}
204 NO CONTENT
```

- `GET` returns all the parameters.
- `POST` only sets (or updates) the given parameters, without erasing other existing parameters

# Discussed

Should we simply add a column to the existing table for users instead of a creating a separate table? This would make the code easier. However, a separate table makes it easier to debug by not cluttering the output when printing the user table.

___
_2020-08-04 - edited : PUT becomes POST (because it takes a body)_, changed the table name, added the `parameters` field to the request / response body. Added the discussed section.

**Comment by inkhey** [comment]
some unclear points:
- 1. Should really the endpoint be generic, if so, it mean some kind of migration/old value support mecanism in frontend. This was discussed by @grignards and @gbonaspetti.
- 2. If the endpoint is generic, frontend should be able to handle the "empty" case. backend can't set default value.
- 3. Should we have a put (return all) or patch (set only some value) endpoint. Currently we do not have any patch endpoint so if we decide to have a patch, we do need clarification for handling "set to null" vs "do not set" case.

suggestion of specification:

```
GET /api/users/1/config
200 OK
{
 "someparameter":"something"
}


PUT /api/users/1/config
{
 "someparameter":"something"
}
204 NO CONTENT

```

Note: we need clarification about if it's possible/easy to have such generic endpoint mecanism with hapic, depending on the limitation of hapic, endpoint specification may change.

**Comment by PhilippeAccorsi** [comment]
Working on develop.
