### ISSUE TITLE
Bug: errors in HTTP requests when uwsgi has more than one thread/worker

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3383]
## Description and expectations

The standard Tracim docker uses uwsgi to host its web application. When using more than one thread/worker in uwsgi's configuration and stressing the server with concurrent requests, many requests are in error.

It should be possible to activate multiple workers/threads without getting more errors than with only one.

### How to reproduce

Detail steps to reproduce the bug:

1. start a 2.7.6 docker with

```shell
docker run -e START_WEBDAV=1 -e START_CALDAV=1 -e DATABASE_TYPE=sqlite -p 8080:80 algoo/tracim:2.7.6
```
2. tune uwsgi config (`/etc/tracim/tracim_web.ini` available in container):

```
workers = 4
threads = 4
```

3. use Apache's `ab` or [pewpew](https://github.com/bengadbois/pewpew) to stress the server

Example with pewpew:
```shell
pewpew stress -n 500 -c 10  http://localhost:8080
```

You then get a summary:
```
---Summary----


Timing
Mean query speed:     21 ms
Fastest query speed:  4 ms
Slowest query speed:  76 ms
Mean RPS:             407.63 req/sec
Total time:           973 ms

Data Transferred
Mean query:      4.4 kB
Largest query:   4.5 kB
Smallest query:  566 B
Total:           1.8 MB

Response Codes
200: 388 responses (97.73%)
502: 9 responses (2.27%)
```

where you can see several `502` errors, there are also many errors which do not even get an HTTP response (in the example the tools generated 500 requests of which 388+9 got an HTTP response).

### Version information

- Tracim 2.7.6 and also 3.0.0 rcX

## Screenshots

N/A

## Diagnostic

To be found.

## Prerequisites

None.

**Comment by grignards** [comment]
This doesn't give the cause but quick tests by using `mod_proxy_uwsgi` instead of http proxying do not show errors with the same tests.

**Comment by PhilippeAccorsi** [comment]
After discuss with @lebouquetin , we need to test this solution for 3.0.1 release (created on maintenance/3.0 when 3.0.0 stable release is available).

**Comment by grignards** [comment]
@PhilippeAccorsi I did the needed modifications on https://github.com/tracim/tracim/tree/fix/3383__uwsgi_errors_multiple_requests
Quick tests with web/webdav/agenda acces did not show problems.
The stress test of the issue is ok with this branch.

**Comment by PhilippeAccorsi** [comment]
Need test and if test is good, need some chnage in entrypoint.sh/common.sh to clean unnecessary command (like sed for caldav for example).

**Comment by PhilippeAccorsi** [comment]
In apache configuration its better to replace `<LocationMatch /api/users/[0-9]+/live_messages>` by `<LocationMatch ^/api/users/[0-9]+/live_messages$>`

**Comment by PhilippeAccorsi** [comment]
Tested with command `ab -k -n 500 -c 10  http://127.0.0.1:10018/` and no error visible.
Preprod-algoo is ready for testing.

**Comment by PhilippeAccorsi** [comment]
We can easly show stats of uwsgi by adding `stats = /tmp/stats.socket` in *.ini file.
We need also to install uwsgitop whis this command `pip3 install uwsgitop`.

After that you can seen stats of uwsgi with this command `uwsgitop /tmp/stats.socket`.

(information here https://github.com/xrmx/uwsgitop)

**Comment by PhilippeAccorsi** [comment]
Tested on preprod.
