### ISSUE TITLE
Bug: The Refresh button should be to the left

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3389]
## Description and expectations

- [x] The `Refresh?` button at all contents that have a warning when other change, should have this button at the left corner of header to be more visible and more coherent with the `Last version` button. 

### How to reproduce

1. Go to a document in a tab
2. Go to the same document in another tab
3. Do an update in one tab
4. See the refresh button in the other

### Version information

- Tracim version 3.0

## Screenshots

Current
![Capture d'écran de 2020-07-29 13-50-45](https://user-images.githubusercontent.com/35422692/88796845-a74d7580-d1a2-11ea-86d4-c557a746a294.png)

Expected
![Capture d'écran de 2020-07-29 13-52-52](https://user-images.githubusercontent.com/35422692/88796966-de238b80-d1a2-11ea-9ddd-24b483b4c5e2.png)

**Comment by PhilippeAccorsi** [comment]
@PhilippeAccorsi We need to create new 3.0.0_rc5 to add this fix.

**Comment by PhilippeAccorsi** [comment]
Dev note: For tests #3392

**Comment by PhilippeAccorsi** [comment]
Tested on branch.
