### ISSUE TITLE
Bug: wrong version number at html-documents

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3393]
## Description and expectations

Explain:

When the user is looking at a version N of an html-document and he receives a TLM of a new version, the document continues in the version he was looking at but the number that indicate the version (image bellow) is updated, so it is no longer consistent with the content shown.

![Capture d'écran de 2020-07-30 10-12-33](https://user-images.githubusercontent.com/35422692/88898633-4af36000-d24d-11ea-822e-1ad1b790dc86.png)

### Version information

- Tracim version: v3.0+

## Diagnostic

The number is linked with timeline size, not with the document shown.

One solution to this problem is to save new revision in the Timeline with a additional param which will tell if the `timelineItem` was added with TLM in order to compute the previous version number without these `timelineItem`, and when the user click to the `refresh` button, these `timelineItem` will be updated.

**Comment by PhilippeAccorsi** [comment]
Tested on branch. Wait merge to close issue.
