### ISSUE TITLE
API path /v2/ no more exist on tracim 3.x so old direct link to download file can't work

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#3395]
## Description and expectations

The public share feature give a direct link to download file, but this link use old api base path `/api/v2/public/`.
In Tracim 3.x the api base path is `/api/public/` so its necessary to create new specific rules to match old link on Tracim v3.

- [ ] ~~add directive in docker apache configuration~~ edit: this is not required
- [x] add documentation about this apache configuration
- [x] check if all information are available in changelog.md
________________________________________________
*The following sections are for the maintainers*

## Diagnostic

Explain what may cause the bug.

**Comment by PhilippeAccorsi** [comment]
I purpose to add this directive in apache configuration
~~~
    # Proxy old api path for direct guest download link
    ProxyPass /api/v2/public/guest-download http://127.0.0.1:8080/api/public/guest-download
~~~

Tested with Tracim docker image and its work good.
@lebouquetin @grignards what do you think about this solution ? Can you think we need to add this fix in 3.0.0 ? (with all documentation)

**Comment by grignards** [comment]
I agree with this solution, could we also have the problem with upload links?

**Comment by lebouquetin** [comment]
@PhilippeAccorsi I suggest:

- we do not update the docker image.
- we provide the apache config example for includign the rule for backward compatibility
- we add a point in changelog which explain that old share links may be broken and a "ready-to-add" apache config is available.

If we include the config in the docker image, it may result in we support this backward-compatibility for years (which is not a good idea)

**Comment by PhilippeAccorsi** [comment]
> If we include the config in the docker image, it may result in we support this backward-compatibility for years (which is not a good idea)

Ok.

**Comment by PhilippeAccorsi** [comment]
So I just need to create a merge request with just documentation about this issue.
Thanks.

**Comment by PhilippeAccorsi** [comment]
> I agree with this solution, could we also have the problem with upload links?

No link exist to access of Upload feature (I have checked this on Tracim 2.7.6). The mail received by user just give an url like this `https://sandbox.tracim.fr/ui/guest-upload/e1be8783-d782-401a-bc73-3935fff79742`

**Comment by PhilippeAccorsi** [comment]
Tested locally with docker image.
