### ISSUE TITLE
Feat: the pagination message endpoint need to return the parent_label of comments

### ISSUE THREAD

**Issue by metzgegu** [tracim/tracim#3406]
## Feature description and goals

To display the label of the content related to a notification in the notification wall of the frontend, we shall:
 - [x] add a `parent_label` field in the the paginated messages endpoint `/api/users/{userId}/messages` 

## Implemented solution

Added `parent_label` to `CommentSchema` to keep the same structure in messages and in HTTP API.

**Comment by grignards** [comment]
@metzgegu Can you confirm this is useful only for comments?

**Comment by metzgegu** [comment]
Yes because for now it is the only content which need to display a notification message with its parent content label.

**Comment by PhilippeAccorsi** [comment]
Verified.
