### ISSUE TITLE
Feat: Ensure missed TLMs are fetched when recovering connection

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3409]
## Feature description and goals

Starting with 3.0, the Tracim frontend has a persistent connection (through `EventSource`) to the backend. This connection can be interrupted (network failure, computer sleep, …). If TLMs are published during this interruption they are currently not received at all leading to missed user interface updates.

To avoid this we should:

- [x] Keep the event id of the last received message in the frontend
- [x] Add this id to the connection URL when reconnecting: `/api/users/2/live_messages?last_event_id=42`
- [x] When the backend has this option, it responds with all messages starting at id 43 (and still keeps the connection open).

We also:
 - [x] close all the live messages connections in the backend when a user logs out from somewhere.  
 - [x] check that the user is still logged in when re-establishing the connection to the live messages.
    - [x] If not, we redirect the user to the login page.
    - [x] otherwise, we re-establish the connection transparently.
 - [x] disable a few console.log that cause performance issues in the HTML doc: the whole state of the application was dumped on the console and this causes performance issues when there are images / a lot of comments / contents on a document. 

This issue won't address the potential issue of the number of TLMs to send, this will be handled later (see #3413).

## Extra information

We check that the user is still logged in in the frontend by fetching the /auth/whoami endpoint. A nicer solution would have been to check the status of the HTTP request sent by the EventSource object when an error is raised. Unfortunately, EventSource does not expose the HTTP status of requests…

**Comment by lebouquetin** [comment]
I'm not sure about the strategy and the cost in term of developments.

Currently the behavior is `on page load` :
  - get old TLM from REST API
  - connect to SSE/TLM in order to get live updates

What I thoug is
- `on page load` : do nothing
- `on SSE/TLM connect` : 
  - get old TLM from REST API
  - will get live updates from the SSE connection.

I understand using the pushpin feature is the right way to do what we want to, but in terms of refactoring, I'm not sure it's time for doing this. What will be the impact on TLM received from API vs TLM received from SSE? This is something which was clear in the original design (with some not-working cases) but this is not clear enoguh with the current issue

**Comment by grignards** [comment]
> Currently the behavior is `on page load` :
> 
>     * get old TLM from REST API
> 
>     * connect to SSE/TLM in order to get live updates

Not exactly: currently only the connection to SSE/TLM is done. The frontend will get the messages through the REST API only when opening the notification panel.

> What I thought is
> 
>     * `on page load` : do nothing
> 
>     * `on SSE/TLM connect` :
>       
>       * get old TLM from REST API
>       * will get live updates from the SSE connection.
The proposed implementation for this issue is almost this, apart from the fact that the missed messages will be sent through the SSE connection. The pushpin feature that I described is for paginating the returned messages, I put it here to decide if we take the time to make it now or not.
The main (good) functional difference I see is that this way we cannot have a race condition: if the frontend connects to SEE/TLMs then make the API request to get missed TLMs separately this could lead to get a TLM twice (as a TLM could be received while the API request is processed).

> I understand using the pushpin feature is the right way to do what we want to, but in terms of refactoring, I'm not sure it's time for doing this. What will be the impact on TLM received from API vs TLM received from SSE? This is something which was clear in the original design (with some not-working cases) but this is not clear enoguh with the current issue

**Comment by lebouquetin** [comment]
Thanks for the clarification. I did not understand that TLM are not stored on frontend side and are loaded on demand when showing the notification panel.

**Comment by raphj** [comment]
We will need to be careful with the interaction this issue could have with #3049.

**Comment by PhilippeAccorsi** [comment]
All final test done by @raphj and @grignards .

**Comment by PhilippeAccorsi** [comment]
Available in 3.0.3
