### ISSUE TITLE
Feat: Frontend must parse comments and content of html-doc to wrap mention by a span right before sending it to the API

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#3411]
## Feature description and goals

To allow backend to find the mention and to trigger messages from it, it needs something specific to find it.

From https://github.com/tracim/tracim/issues/2838, the specification of what the backend expects to find is:
``` html
<span id="mention-<uuid>">@all</span>
```

This behavior must be generic.
Since it is handled by comments, the Timeline components must handle it.
I have yet to find the proper way to implement it for app html.

- [x] add function to wrap the mention in a span
- [x] give an id to the newly generated span from a uuid following the spec above
- [x] this function must be used in app html-doc
- [x] the parsing happen after clicking on "Save" or "Send" button but before sending the content to the API
- [x] If something goes wrong during the parsing, display a flash message, a verbose console.log and block the api call

#### Interface
The highlight for a mention will be implemented at the issue https://github.com/tracim/tracim/issues/3325

**Comment by lebouquetin** [comment]
@Skylsmoi in the title `Frontend must parse comments and content of html-doc` its not clear when you plan to parse comments and contents. Is it on `save()` ? on `GET` from the API ?

**Comment by Skylsmoi** [comment]
This issue is in WIP but I can't work on it right now.
Someone can continue my work. It is on this branch: `feat/3411__add_span_wrapping_mention`

I'm assigning out of the issue and putting it back in TODO

**Comment by inkhey** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Verified.
