### ISSUE TITLE
Bug: TLMs aren't published when modifying a big html-document

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3415]
## Description and expectations

When modifying an html-document containing several images (amounting to around 1.7Mbytes) the corresponding `content.modified` TLMs are not published.

### How to reproduce

Create an html-document with several embedded images. Modify it (for example its status).

### Version information

- Tracim version: 3.0.0rc4
- Web browser: any

## Diagnostic

Publishing to pushpin is done with a HTTP request which has a maximum body size.

## Solution

Publishing through 0mq (PUB socket) doesn't show the problem.

**Comment by PhilippeAccorsi** [comment]
Tested on preprod.
