### ISSUE TITLE
Bug: docker image of version 3.0 does not build

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3418]
## Description and expectations

The build fails when apt tries to install the latest `zurl` package (`pushpin` dependency) and fails as it requires `libcurl4`.
Installing stretch's `zurl` works.

### How to reproduce

Build a docker image with the version 3.0.

### Version information

- Tracim version: 3.0

**Comment by PhilippeAccorsi** [comment]
Tested with docker image created from branch. TLM working good.
