### ISSUE TITLE
Add author's avatar in notification wall

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3429]
## Feature description and goals

To make it easier to identify the user who triggered a notification, and to be consistent with the rest of the UI (autocomplete, mentions, comments, etc), notifications should have the author's avatar on the left of their name in the Notification Wall.

## Implementation

In each notification text item, add the `Avatar` component from `frontend_lib` and use `display: flex` in the container `div` in order to display each elements in one line (the notification label and the author's avatar)

![image](https://user-images.githubusercontent.com/31687635/90728371-13fcf100-e2c5-11ea-9ffb-e5bfca56069e.png)

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Verified.
