### ISSUE TITLE
feat: add mouse over tooltip on notification wall

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#3430]
## Description and expectations
Related to #2840 

In the list of contents, we have a tooltip on mouse over on file name, but no tooltip visible in the notification wall. In the notification wall, the text size is smaller than text size visible in list of content.
Tooltips can increase readability of the file name.

To do:
- [x] tooltip on file name
- [x] tooltip on date (like we have in timeline)

## Screenshots

![Screenshot_2020-08-12 Tableau de bord · test1 · Tracim](https://user-images.githubusercontent.com/25848257/89999080-a2062580-dc8e-11ea-8a27-3557b10c5a6f.png)

![image](https://user-images.githubusercontent.com/3817365/91310997-d6abce00-e7b2-11ea-8b27-5b9f423d82da.png)
____
Log of this ticket:
- Added to do items about tooltip

**Comment by inkhey** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
@raphj why this fix is not merged ? something not good in the MR ?
@inkhey you says `tested on branch` but no message appear in the MR, checkbox not check in the MR, is it normal ?

**Comment by inkhey** [comment]
> @raphj why this fix is not merged ? something not good in the MR ?
> @inkhey you says `tested on branch` but no message appear in the MR, checkbox not check in the MR, is it normal ?

I've done a message in the MR, but you're right i forgot the checkbox:
https://github.com/tracim/tracim/pull/3469#issuecomment-687098551

**Comment by raphj** [comment]
I was waiting for the CI to pass the last fix, and forgot about it afterwards. It's now merged.

**Comment by PhilippeAccorsi** [comment]
Verified.
