### ISSUE TITLE
Bug: session validity in cookies is not updated. 

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#3431]
## Description and expectations

With new session mechanism, the backend update the session file when user is authenticated to make sure backend session expire after 7 days of inactivities.

In the frontend, the cookies is just set on login action and never updated. So after 7 days, the frontend cookies expire and you need to login again.

- [x] Cookies need to be updated to make sure the user is never disconnected if they use Tracim for a long time (several days).

### Version information

Tracim > 3.0.0

## Implemented solution

The cookie expiry date is renewed when its age exceeds 50% of its max age. The session is not recreated when renewing the expiry date (so no new session file is created).

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Available in 3.0.2
