### ISSUE TITLE
Bug: Incompatible version of packaging in requirements.txt vs. last wheel version

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3436]
## Description and expectations

The last version of `wheel` (0.35) package needs `packaging>=20` but it is locked to `18` in our requirements.txt file.
This is a problem as it causes the `setup_default_backend.sh` and docker image build to fail.

### How to reproduce

Clone the repository, launch `setup_default_backend.sh`/build the docker image.

### Version information

- Tracim version: 3.0 and develop

### Implemented solution

Update our requirements.txt file to `packaging==20.4`.

**Comment by PhilippeAccorsi** [comment]
What part of Tracim need to be tested after changing version of packaging ? to make sure no regression appear.

**Comment by grignards** [comment]
The `packaging` dependency seems unused by `preview_generator`, cannot confirm this by playing the tests as `pytest` itself depends on `packaging`.

**Comment by PhilippeAccorsi** [comment]
Available in 3.0.2
