### ISSUE TITLE
Feat: Enforce the type of key and values of the user configuration endpoint.

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3451]
## Feature description and goals

The endpoint added for storing the frontend configuration per user (see #3380) does not enforce the types of keys and values which are stored. To ensure an easier data migration when/if the stored data becomes big we should:

- [x] enforce that the keys are strings with simple characters `a-zA-Z0-9-_.`
- [x] enforce that the values are simple JSON values: string/number/bool/none, forbid lists and dictionaries.
- [x] add documentation in the endpoint explaining the key naming conventions (can be hierarchic using a `.` as delimiter, a bit like firefox `about:config`).

This will allow to split the single-JSON storage if need arises and also to provide filters based on the naming of the keys, eg. `starts_with=foo.` would only return keys (and values) starting with `foo.`.

Edit: (https://github.com/tracim/tracim/issues/3451#issuecomment-681729562)
We should also change a bit the original endpoint for setting user config:
- [X] switch from POST to PUT
- [X] document the "patch-like" behavior of this endpoint

some others thing should be fixed:
- [X] do not provide empty config for default admin user.
- [X] properly clean userconfig during user deletion process.
## Implemented solution:
https://github.com/tracim/tracim/pull/3465

- api level schema validation rule for allowing specific kind of json schema according to rule given in this tickets:
   - keys : string matching regex `^[0-9a-zA-Z-_.]+$`
  - value: type in str, int, float, null/NoneType
- add some tests on schema validation.
- Better documentation for api set_user_config endpoint (/api/users/{user_id:\d+}/config)
- set the set_user_config endpoint from POST to GET method.
- bugfix: update user delete command to handle the userconfig deletion case
- bugfix: provide config to default user on fixtures

____
Edited 2020-08-27: add implemented solution
Edited 2020-08-27: update implemented solution

**Comment by inkhey** [comment]
@grignards , @raphj 
When creation this, i got few question about the current user_config implementation:
- Why POST instead of PUT ?
- Is the "patch" behavior (allow to send partial part of the config) is wanted, this unallow the possibility to remove key.

**Comment by inkhey** [comment]
> @grignards , @raphj
> When creation this, i got few question about the current user_config implementation:
> 
>     * Why POST instead of PUT ?
> 
>     * Is the "patch" behavior (allow to send partial part of the config) is wanted, this unallow the possibility to remove key.

After discussion with @grignards, we decide to:
- Change POST to PUT
- Document the fact the PUT act more like a PATCH (partial update, no way to remove key)

**Comment by gbonaspetti** [comment]
There is an issue when I do a GET:

for
```
Request URL: http://{{apiUrl}}/api/users/{{userId}}/config
Request Method: GET
Status Code: 500 Internal Server Error
```

Where apiUrl is localhost:7999 and userId is 1, the response is
```
 {"message": "No row was found for one()", "code": null, "details": {"error_detail": {}}}
```

**Comment by inkhey** [comment]
> There is an issue when I do a GET:
> 
> for
> 
> ```
> Request URL: http://{{apiUrl}}/api/users/{{userId}}/config
> Request Method: GET
> Status Code: 500 Internal Server Error
> ```
> 
> Where apiUrl is localhost:7999 and userId is 1, the response is
> 
> ```
>  {"message": "No row was found for one()", "code": null, "details": {"error_detail": {}}}
> ```

Origin of the issue is that user created in fixture, does not use the same creation path as normal user creation, i made a quick fix :https://github.com/tracim/tracim/pull/3465/commits/0e21d3c819628b95d1a3fddb03d4f84b1bc32b7d
but we probably need to change the way we deal with fixture more deeply to avoid such case, see issue : https://github.com/tracim/tracim/issues/2120

**Comment by PhilippeAccorsi** [comment]
Verified.
