### ISSUE TITLE
Bug: TLM reconnection is not always functional when suspending/resuming computer

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3461]
## Description and expectations

When the computer is suspended then resumed while a tracim page is open, it can happen that the reconnection to the TLMs doesn't work, leading to display the connection error message eternally.
It also happens by disconnecting/reconnecting from the network.
The message is also misleading, reloading the page has little effect (see diagnostic below).

### How to reproduce

Detail steps to reproduce the bug:

1. Open a Tracim Page (after logging)
2. Suspend your computer
3. Resume it

With these instructions the bug occurs on around 50% of the tries.

### Version information

- Tracim version: 3.0.3
- Web browser: Firefox 79
- Device / System: PC
## Diagnostic

At least three problems:
- [x] the message is misleading: reloading the current tab does not necessarily reinitialize the TLM connection as it is shared between all tabs/windows (and managed by only one tab). Reloading has an action **only** if the current tab is the one managing the TLM connection

=> Change the message to the one below:

|English|French|Portuguese|
|---------|---------|--------------|
|Tracim has a connection problem, please wait or reload your browser if the problem persists|Tracim rencontre un souci de connexion, merci de patienter ou de redémarrer votre navigateur si le problème persiste|Tracim tem um problema de conexão, por favor aguarde ou recarregue o seu navegador se o problema persistir|

When reconnecting a fetch to `api/auth/whoami` is done to check if the disconnection is due to a user logout or not. This fetch:
  - [x] has no timeout: when resuming the computer it can happen that the request is not transmitted at all by the browser, in this case the re-connection logic stays blocked forever
  - [x] doesn't catch the exceptions: it can also happen that there is an error during the fetch (`err:NET_DISCONNECTED` for instance). in this case, as the exception is not caught the reconnection logic is stopped and never retried.

## Prerequisites

None

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Available in 3.0.4
