### ISSUE TITLE
Bug: It is possible to mention a user not part of the workspace

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3472]
## Description and expectations

The mentioning system allows mentioning a user which is not a member of the content's workspace. This should be restricted by the backend.

The backend should return a 400 error code in this case.

### How to reproduce

1. Create a workspace
2. Mention a user not member of this workspace
3. Log as this user and go to the notification panel
4. The mention is present but not usable as clicking on it returns an access error.

### Version information

- Tracim version: develop/soon-to-be 3.1

## Diagnostic

No check is done by the backend whether a user is part of the content's workspace before creating a mention.

**Comment by inkhey** [comment]
- Is there any risk of guessing which user exist with the 400 error code ?
- It's not just 400 error, it's also no applying the full update/creation of content/comment. We should be sure the case cannot happened in normal ui usage, or if it can happened in edge case we should think about a specific error code and a way to not lost the content created.
- Case that can be tricky may be related to frontend update sync issue, as an user can be removed from workspace when we create a comment/update a content. We should also ensure that previous mention doesn't cause any problem.

**Comment by raphj** [comment]
Maybe we should not issue a 400 error, but rather just not handle the mention if a user is not there.

We could also do fancy stuff like warn the user that they mentioned someone not here, but I'm not sure this should be done in Tracim 3.1.

**Comment by lebouquetin** [comment]
@inkhey I'm not sure we should forbid content update (especially if there is not message tellign which user causes the problem).

My feeling "à chaud" (et d'un point de vue "expérience utilisateur"):

- frontend should avoid not allowed mentions 
- backend should simply ignore forbidden mentions (without returning an error)

**Comment by lebouquetin** [comment]
> We could also do fancy stuff like warn the user that they mentioned someone not here, but I'm not sure this should be done in Tracim 3.1.

This is an improvment, not *required* for 3.1

**Comment by grignards** [comment]
I thought about ignoring mentions to non-member users, if we don't properly handle the error (meaning displaying a useful message to the user) I think we can do this. I specified an error as, from the user point-of-view it should be one.

>     * Is there any risk of guessing which user exist with the 400 error code ?

Perhaps, but we already have a better API to guess usernames : `/api/system/username-availability`. I'm not sure this is a problem…

>     * It's not just 400 error, it's also no applying the full update/creation of content/comment. We should be sure the case cannot happened in normal ui usage, or if it can happened in edge case we should think about a specific error code and a way to not lost the content created.

This is true, but is in every case (another error could happen). As long as the error is raised during the change's transaction nothing will be written in the DB. We would have to check that the frontend correctly handles this situation but I expect it should as it's got the localstorage save.

>     * Case that can be tricky may be related to frontend update sync issue, as an user can be removed from workspace when we create a comment/update a content. We should also ensure that previous mention doesn't cause any problem.

What do you mean ? The case of removing a user while a comment mentioning him is posted is handled by the db: either the removal will be done first or after, but we cannot post a comment in the middle of a user removal.

**Comment by inkhey** [comment]
> I thought about ignoring mentions to non-member users, if we don't properly handle the error (meaning displaying a useful message to the user) I think we can do this. I specified an error as, from the user point-of-view it should be one.
> 
> > ```
> > * Is there any risk of guessing which user exist with the 400 error code ?
> > ```
> 
> Perhaps, but we already have a better API to guess usernames : `/api/system/username-availability`. I'm not sure this is a problem…
> 
> > ```
> > * It's not just 400 error, it's also no applying the full update/creation of content/comment. We should be sure the case cannot happened in normal ui usage, or if it can happened in edge case we should think about a specific error code and a way to not lost the content created.
> > ```
> 
> This is true, but is in every case (another error could happen). As long as the error is raised during the change's transaction nothing will be written in the DB. We would have to check that the frontend correctly handles this situation but I expect it should as it's got the localstorage save.
> 
> > ```
> > * Case that can be tricky may be related to frontend update sync issue, as an user can be removed from workspace when we create a comment/update a content. We should also ensure that previous mention doesn't cause any problem.
> > ```
> 
> What do you mean ? The case of removing a user while a comment mentioning him is posted is handled by the db: either the removal will be done first or after, but we cannot post a comment in the middle of a user removal.

I think about the fact that the frontend can add mention at T+1 to a user which is removed at T+2 and the back-end receive the message at T+3 and return a 400 (if we decide to follow this mecanism).
Between frontend and backend, there is 2 time gap:
- time gap between creating the mention and sending by frontend.
- time gap between sending the mention and backend processing it.
As far i understood, the frontend convert text to true mention just during the sending, so it's possible that:
- frontend doesn't care about user has been removed and create an "invalid mention"
- frontend does care about it and leave mention do nothing, as this does not match valid workspace user.

**Comment by grignards** [comment]
> @inkhey I'm not sure we should forbid content update (especially if there is not message tellign which user causes the problem).
> 
> My feeling "à chaud" (et d'un point de vue "expérience utilisateur"):
> 
>     * frontend should avoid not allowed mentions

This should be the case, @metzgegu username completion is based on the known users.

>     * backend should simply ignore forbidden mentions (without returning an error)

From my point of view if a user mentions somebody who does not exist/is not part of the workspace it should be an error. Is the idea of silencing those "errors" more a question of development time or do you think this behavior is desirable (I fail to see why)?

**Comment by grignards** [comment]
>     * frontend doesn't care about user has been removed and create an "invalid mention"
> 
>     * frontend does care about it and leave mention do nothing, as this does not match valid workspace user.

The autocomplete feature does only propose users who are members of the current workspace at the time of writing the mention. When saving the frontend code wraps all text matching a mention (meaning a @ + string similar to a username). It does not validate that the mentioned username exists/is a member of the workspace at this point.

**Comment by grignards** [comment]
> From my point of view if a user mentions somebody who does not exist/is not part of the workspace it should be an error. Is the idea of silencing those "errors" more a question of development time or do you think the "silent" behavior is desirable (I fail to see why)? @lebouquetin

BTW I checked the backend/frontend, there is an error code and user message when a mention for a non-existing Tracim user is present in a saved comment/html-document. So adding a case for this new error isn't a behavior change. If we prefer a "quick'n dirty" implementation we could even use the same code as the user message is quite generic: "You are trying to mention an invalid user".

**Comment by inkhey** [comment]
> > ```
> > * frontend doesn't care about user has been removed and create an "invalid mention"
> > 
> > * frontend does care about it and leave mention do nothing, as this does not match valid workspace user.
> > ```
> 
> The autocomplete feature does only propose users who are members of the current workspace at the time of writing the mention. When saving the frontend code wraps all text matching a mention (meaning a @ + string similar to a username). It does not validate that the mentioned username exists/is a member of the workspace at this point.

Ok, i agree with this solution but we should have a frontend ticket about :
- handling the error case for all existing case: comment creation, html-document creation, html document update (these 2 are probably the same) to at least avoid "losing" the modification.

**Comment by grignards** [comment]
>     * handling the error case for all existing case: comment creation, html-document creation, html document update (these 2 are probably the same) to at least avoid "losing" the modification.

As far as I saw (both by reading the code and trying quickly) the frontend behavior is already ok regarding this (other errors are already possible and handled).

**Comment by inkhey** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Verified.
