### ISSUE TITLE
Feat: set version of Yarn to 2.1.1 when installing the frontend dependencies

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3473]
## Description and expectations
Later versions of Yarn dropped support for Node 10.16, which is the version of Node 10 that Travis currently provides. The CI broke on Friday, August, 28 with the release of Yarn 2.2. 

- [x] fix Yarn version at 2.1.1. 

The long term action to do is to upgrade to node 12 or 14. Node 10 stops being supported in April 2021. See #2953.

We are not upgrading Node for now because we need to coordinate and agree that we are ready to do it, and define the tests to conduct to be reasonably sure this won't break something.

**Comment by PhilippeAccorsi** [comment]
Verified.
