### ISSUE TITLE
Keep only chosen TLMs in notification panel

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3477]
## Feature description and goals

For now, every TLM is displayed as a notification in Tracim. After some integration tests, our goal is to keep only the notifications that we believe will be important for the user.

We didn't try filtering them sooner because we want to try this first to avoid writing unnecessary code.

TLM types/categories to remove from the notification display:

- [X] ~~TLMs whose author is the logged user~~ done in https://github.com/tracim/tracim/issues/3523
- [X] create i18n text for notifications that are not handled yet
- [x] check that the portuguese translation works well on small screens
- [X] add a .ini parameter which is the list of TLMs which won't generate a notification
- [X] add this parameter to the tracim config API so that frontend has access to it
- [X] choose an icon and add wording for all current notifications
- [X] implement in frontend the mechanism which ignores blacklisted TLMs
- [X] keep the current mechanism which shows unknown notifications as "raw notifications"
 - [x] Display an INFO flash message "Only an administrator can see this user's profile" will be displayed on a notification related to a user"
 - [x] Display a WARNING flash message "This notification does not have an associated content" will be displayed for the default "unhandled" notification if it does not have any content

Default blacklist (configuration web.notifications.excluded in development.ini):
- user.created
- user.modified
- user.deleted
- user.undeleted
- workspace.modified
- workspace.deleted
- workspace.undeleted
- workspace_member.modified
- content.modified

### Current TLMs that are processed notifications

- workspace_member.created
    - with a difference between "added you to" and "added {{user}} to"
- content.comment.created
- content.(file/html-document/thread/folder.)created
- content.(file/html-document/thread/folder.)modified
    - with a difference between status update and the other modification
- mention.created
    - with a difference between mention in a document and in a comment 

### Current TLMs that are notifications but not processed, i.e. don't have a specific text and icon

- user.created
- user.modified
- user.deleted
- user.undeleted
- workspace.created
- workspace.modified
- workspace.deleted
- workspace.undeleted
- workspace_member.modified
- workspace_member.deleted
- content.(file/html-document/thread/folder.)deleted
- content.(file/html-document/thread/folder.)undeleted

### Current TLMs that are not notifications

- TLMs whose author is the logged user
- content.comment.modified
- content.comment.deleted
- content.comment.undeleted

## Discussed

Which notifications should we filter out?
_18-09-2020_ Decision: https://github.com/tracim/tracim/issues/3477#issuecomment-694749770

## Translations

||English|French|Portuguese|
|-|-|-|-|
|**user.created**| {{author}} created {{user}}'s profile | {{author}} a créé le profil de {{user}} | {{author}} criou o perfil de {{user}} |
|**user.modified**| {{author}} updated {{user}}'s profile | {{author}} a mis à jour le profil de {{user}} | {{author}} actualizou o perfil de {{user}} |
|**user.deleted**| {{author}} deleted {{user}}'s profile | {{author}} a supprimé le profil de {{user}} | {{author}} eliminou o perfil de {{user}} |
|**user.undeleted**| {{author}} restored {{user}}'s profile | {{author}} a restauré le profil de {{user}} | {{author}} restaurou o perfil de {{user}} |
|**workspace.created**| {{author}} created the space {{space}} | {{author}} a créé l'espace {{space}} | {{author}} criou o espaço {{space}} |
|**workspace.modified**| {{author}} updated the space {{space}} | {{author}} a mis à jour l'espace {{space}} | {{author}} actualizou o espaço {{space}} |
|**workspace.deleted**| {{author}} deleted the space {{space}} | {{author}} a supprimé l'espace {{space}} | {{author}} eliminou o espaço {{space}} |
|**workspace.undeleted**| {{author}} restored the space {{space}} | {{author}} a restauré l'espace {{space}} | {{author}} restaurou o espaço {{space}} |
|**workspace_member.modified**| {{author}} updated member {{member}} in {{space}} | {{author}} a mis à jour le membre {{member}} dans {{space}} | {{author}} actualizou o membro {{member}} no espaço {{space}} |
|**workspace_member.deleted**| {{author}} deleted member {{member}} from {{space}} | {{author}} a supprimé le membre {{member}} de {{space}} | {{author}} eliminou o membro {{member}} de {{space}} |
|**content.deleted**| {{author}} deleted {{content}} from {{space}} | {{author}} a supprimé {{content}} de {{space}} | {{author}} eliminou {{content}} de {{space}} |
|**content.undeleted**| {{author}} restored {{content}} in {{space}} | {{author}} a restauré {{content}} dans {{space}} | {{author}} restaurou {{content}} no espaço {{space}} |

## Icons

||Icon|
|-|-|
|**user.created**|user-plus|
|**user.modified**|user + history (use ComposedIcon component)|
|**user.deleted**|user-times|
|**user.undeleted**|user + undo (use ComposedIcon component)|
|**workspace.created**|university + plus (use ComposedIcon component)|
|**workspace.modified**|university + history (use ComposedIcon component)|
|**workspace.deleted**|university + times (use ComposedIcon component)|
|**workspace.undeleted**|university + undo (use ComposedIcon component)|
|**workspace_member.modified**|user-o + history (use ComposedIcon component)|
|**workspace_member.deleted**|user-o + times (use ComposedIcon component)|
|**content.(file/html-document/thread/folder.)deleted**|file-o + times (use ComposedIcon component)|
|**content.(file/html-document/thread/folder.)undeleted**|file-o + undo (use ComposedIcon component)|

## Redirections

||Redirect to|
|-|-|
|**user.created**|if logged user is admin `/ui/admin/user/{{user_id}}` else `/ui`|
|**user.modified**|if logged user is admin `/ui/admin/user/{{user_id}}` else `/ui`|
|**user.deleted**|if logged user is admin `/ui/admin/user/{{user_id}}` else `/ui`|
|**user.undeleted**|if logged user is admin `/ui/admin/user/{{user_id}}` else `/ui`|
|**workspace.created**|`/ui/workspaces/{{workspace_id}}/dashboard`|
|**workspace.modified**|`/ui/workspaces/{{workspace_id}}/dashboard`|
|**workspace.deleted**|`/ui`|
|**workspace.undeleted**|`/ui/workspaces/{{workspace_id}}/dashboard`|
|**workspace_member.modified**|`/ui/workspaces/{{workspace_id}}/dashboard`|
|**workspace_member.deleted**|`/ui/workspaces/{{workspace_id}}/dashboard`|
|**content.deleted**|`/ui/workspaces/{{workspace_id}}/contents/{{content_type}}/{{content_id}}`|
|**content.undeleted**|`/ui/workspaces/{{workspace_id}}/contents/{{content_type}}/{{content_id}}`|
___
_2020-09-16: added the idem about text string to write_
_2020-09-21: added translations, icons and redirections_

**Comment by raphj** [comment]
@gbonaspetti can you clarify what you mean by tests (the two occurrences), and by "filtering [the TLMs] soon" (where, to achieve which purpose)?

"notifications from the logged user": is it a filter that removes the TLMs produced after an action from the user received by this same user?

**Comment by grignards** [comment]
@gbonaspetti I made some modifications to clarify a bit.

**Comment by raphj** [comment]
Should this be a 3.1 ticket?

**Comment by gbonaspetti** [comment]
> @gbonaspetti can you clarify what you mean by tests (the two occurrences), and by "filtering [the TLMs] soon" (where, to achieve which purpose)?
"notifications from the logged user": is it a filter that removes the TLMs produced after an action from the user received by this same user?

Updated.

> Should this be a 3.1 ticket?

Yes, it's not good that this version has a notification wall with "not treated" notifications (see description note at https://github.com/tracim/tracim/issues/2840)

**Comment by inkhey** [comment]
> > Should this be a 3.1 ticket?
> 
> Yes, it's not good that this version has a notification wall with "not treated" notifications (see description note at #2840)

So, the issue is also about creating some specific text and translation.

**Comment by PhilippeAccorsi** [comment]
For me:
- basic user account => not show notification about what is done by another user in his profile. But just show when user chnage his username (and show the new username)
-admin user account => not show notification about what is done by another user in his profile. But just show when user chnage his username (and show the new username), and if user change his public name and email.

Group notification about same content (multiple comment, or modification).

**Comment by raphj** [comment]
From the integration tests:

- Question: should we differentiate between  « mentioned you » and « mentioned all » ? [@raphj :+1: but maybe an improvement?]

Important notifications:
 - content edited
 - content created ?

NOT important notifications:
 - actions from the logged user [ #3523 ]
 - comments on a content
    - except threads?
 - modification of a username or a display name or auther user related data
 - content deleted?
 - content restored?
 - content renamed (but we cannot know if a rename is not an update (except status)
 - status set to approved? (@gbonaspetti says it should be important)

**Comment by raphj** [comment]
@PhilippeAccorsi grouping notifications would be neat, but this does not seems like a Tracim 3.1.X improvement. What do you think? (@lebouquetin, @gbonaspetti)

**Comment by PhilippeAccorsi** [comment]
> @PhilippeAccorsi grouping notifications would be neat, but this does not seems like a Tracim 3.1.X improvement. What do you think? (@lebouquetin, @gbonaspetti)

I don't know if its for 3.1.x or in futur version.
I think its a phase 2 improvement.

**Comment by grignards** [comment]
We should also make clear what is the role of notifications compared to the activities we'll get with 3.2 and 3.4. Especially 3.4 as it should bring an aggregation of space activities for each user.
For example I find the idea of grouping notifications cool, but am afraid that the user activities will provide a better solution for this (eg. be informed of changes without being overwhelmed).

**Comment by raphj** [comment]
indeed. It seems there will be some redundancy between the two features

**Comment by grignards** [comment]
I'm even wondering if the notification panel's main usage wouldn't become to access our mentions (mentions addressed to us) when the "user activities" feature become available.

**Comment by lebouquetin** [comment]
@gbonaspetti @grignards @inkhey could we have here the complete list of TLMs that currently generate a notification?

Is this activation/deactivation something to develop in the frontend or in the backend?

**Comment by raphj** [comment]
This should be a frontend feature in my opinion.

**Comment by gbonaspetti** [comment]
> @gbonaspetti @grignards @inkhey could we have here the complete list of TLMs that currently generate a notification?
> 
> Is this activation/deactivation something to develop in the frontend or in the backend?

I'll update the description with the list. The activation/deactivation something is done by frontend, if one exception: TLMs whose author is the logged user.

**Comment by lebouquetin** [comment]
After reflexion, here is what we will do:

- add a .ini parameter which is the list of TLMs which won't generate a notification (`tml2notification.blacklist`). Probably coma separated list (see other lists in order to have something consistant)
- add this parameter to the tracim config API so that frontend has access to it
- choose an icon and add wording for *all* current notifications
- implement in frontend the mechanism which ignores blacklisted TLMs
- keep the current mechanism which shows unknown notifications as "raw notifications"

Default blacklist:
```
user.created
user.modified
user.deleted
user.undeleted
workspace.modified
workspace.deleted
workspace.undeleted
workspace_member.modified
```

@gbonaspetti I suggest you start by writing the full list of sentences + propose an icon for each taken from fontawesome.

**Comment by mlopes21** [comment]
(optional) If the text don't break the interface, maybe it's better to explicit a little more in Portuguese the following translations : 
"{{author}} actualizou o membro {{member}} no espaço {{space}}"
and "{{author}} restaurou {{content}} no espaço {{space}}"

**Comment by gbonaspetti** [comment]
> (optional) If the text don't break the interface, maybe it's better to explicit a little more in Portuguese the following translations :
> "{{author}} actualizou o membro {{member}} no espaço {{space}}"
> and "{{author}} restaurou {{content}} no espaço {{space}}"

I updated the description with your suggestion.

**Comment by raphj** [comment]
There is a weird string, '{{author}} updated a new version of {{content}} in {{workspace}}'. I suggest changing this to: "'{{author}} updated {{content}} in {{workspace}}'".

There is also '{{author}} updated the status of {{content}} in {{workspace}}', I think '{{author}} changed the status of {{content}} in {{workspace}}' would be better. What do you think? @celiamgtt @gbonaspetti

**Comment by PhilippeAccorsi** [comment]
> There is a weird string, '{{author}} updated a new version of {{content}} in {{workspace}}'. I suggest changing this to: "'{{author}} edited {{content}} in {{workspace}}'".
> 
> There is also '{{author}} updated the status of {{content}} in {{workspace}}', I think '{{author}} changed the status of {{content}} in {{workspace}}' would be better.
> 


I think we need to show message like message visible in Timeline. So maybe its necessary to change everywhere and not just in wall.

**Comment by raphj** [comment]
The timeline shows "New revision", so it's okay. However, I'll keep '{{author}} updated {{content}} in {{workspace}}' because it works for both an upload and an edition.

**Comment by lebouquetin** [comment]
@raphj @gbonaspetti when modifying a content, we show a flash message for notifying users:

![image](https://user-images.githubusercontent.com/907161/93791557-b0077880-fc34-11ea-91d3-38114ec3040f.png)

So we do not need anymore to notify:

- when a content is created
- when the content of the content is modified

(actually, every time the message above is shown)

**Comment by raphj** [comment]
indeed. :+1: 

fewer notifications is quality notification.

**Comment by raphj** [comment]
After discussion with @gbonaspetti, we will no longer redirect to the home page for notifications that don't have an URL.
Instead:
 - an INFO flashmessage "Only an administrator can see this user's profile" will be displayed on a notification related to a user
 - a WARNING flashmessage "This notification does not have an associated content" will be displayed for the default "unhandled" notification... which should not happen in a production version anyway

**Comment by raphj** [comment]
we are not ready to disable notifications  when a content is created and post-poning this to a later version when we implement a prompt message to notify all members of the space when creating a document.

**Comment by PhilippeAccorsi** [comment]
Verified on preprod.
