### ISSUE TITLE
Feat: Use natural order in folders and shared spaces

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3481]
## Feature description and goals

Sometimes, it makes sense to prefix document titles by a number to order them (maybe these numbers are section numbers, like we do on [documentation.tracim.fr](https://documentation.tracim.fr)).

With the alphabetical order currently used, files `1`, `2`, `10` are sorted in this order: `1`, `10`, `2`.
With a natural sort,  the order is  `1`, `2`, `10`.

To do:
 - [x] implement natural sorting for contents in shared spaces and folder
 - [x] implement natural sorting in the sidebar (if the sort is already done in the frontend)

## Implementation
Sorting is currently already done in the frontend. We use [`String.localeCompare` with the option `numeric: true`](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/String/localeCompare#Tri_num%C3%A9rique) to implement this feature.

The sort also now takes the UI language in account, but since there is no difference in sorting between English, French and Portuguese as far as we know, we cannot test this.

## Extra information

 Dolphin or Nautilus, for instance, use natural order:

![image](https://user-images.githubusercontent.com/3817365/91826449-e194b180-ec3d-11ea-96a7-51410981492c.png)
![image](https://user-images.githubusercontent.com/3817365/91826427-d93c7680-ec3d-11ea-8a0f-dafef591bbf8.png)

## Screenshot

![image](https://user-images.githubusercontent.com/3817365/91865321-8f6d8380-ec71-11ea-8b74-ab2fbbaceae8.png)

**Comment by lebouquetin** [comment]
This would be a nice improvment on a user point of view. Do you know which JS library would help? Or do we sort on the backend?

**Comment by raphj** [comment]
We can use the builtin function `String.localeCompare` with the option `numeric: true`, no need for a particular library if we implement this in the frontend. And I think we should implement this in the frontend.

This would not be possible if the workspace content lists were paginated, but this is not the case. 
This would be useful to do it in the backend so every potential Tracim client could get the same order (consistency), but one could argue that this is also a design choice on the client and the client could as well implement a sort anyway. Currently, sorting is already done in the frontend in Tracim, so we would only have to add `{ numeric: true }` there to get the feature.

**Comment by lebouquetin** [comment]
OK. So if its only 1 code line I suggest to add it to 3.1. @celiamgtt what do you think on a UX point of view?

**Comment by celiamgtt** [comment]
Yes it's a really nice improvement!

**Comment by inkhey** [comment]
Can you clarify clearly where in the ui, you want this kind of order. As this order cannot be implemented the same way for search and other view where data are sorted only by backend, it should be clear where this improvment should be done.

Reading this issue, it seems to be applied  for content list in content view but the title seems to say that it can also be applied for shared spaces list in sidebar.

**Comment by raphj** [comment]
Only for content list. The sidebar is not involved.

**Comment by raphj** [comment]
I added a screenshot. It does not seems like a big problem for me if the search is not naturally sorted for now, but if desired, we could open another issue. @inkhey?

Sorting the shared spaces in the sidebar could also be nice but it does not seem as important.

**Comment by inkhey** [comment]
> I added a screenshot. It does not seems like a big problem for me if the search is not naturally sorted for now, but if desired, we could open another issue. @inkhey?

It's really unclear what natural sorting can mean for search, so i'm really not sure creating an issue yet make sense:
- elasticsearch based search currently sort element by a relevance algorithm.
- simple search result last modified content first as far i remember.

So, it's doesn't make sense yet, unless we decide to change the way the search engines (simple or elasticsearch) work, but that really more than just "use natural order".

**Comment by raphj** [comment]
Right, search should not be sorted at all actually. Are we okay with this issue?

**Comment by lebouquetin** [comment]
> Only for content list. The sidebar is not involved.

This is not coherent, I think.

> Right, search should not be sorted at all actually. Are we okay with this issue?

Search results are already sorted by relevance - this is part of the feature. When we would allow to sort differently we will have a "alphabetic order" which should be natural-sort, I think. This is a future improvment

**Comment by grignards** [comment]
> This is not coherent, I think.

I agree, if the sort for the sidebar is done by the frontend too, this issue should include the modifications for it too (as it wouldn't be much more work and we'd have a consistent behavior for alphabetically sorted lists).

**Comment by raphj** [comment]
Edited @grignards

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Verified.
