### ISSUE TITLE
Bug: Inputting several mentions in the same comment line changes the text of all but the last mention

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3507]
## Description and expectations

When inputting several mentions in the same comment line all mentions but the last one get an added character when saving the comment. The added character is the last of the mention, eg. `@plop` becomes `@plopp` when saved.

### How to reproduce

1. Go to a content
2. Add a comment with two or more mentions (of existing usernames), eg. `@TheAdmin @foo`

### Version information

- Tracim version: develop/future 3.1
- Web browser: not relevant
- Version: not relevant
- Device / System: not relevant

## Screenshots

![92224385-06895e80-eea2-11ea-9ce8-c40cb816104a](https://user-images.githubusercontent.com/51887114/92235996-e747fc80-eeb4-11ea-9b66-c2c51260abc7.gif)

________________________________________________

## Diagnostic

- Probably linked to the `<span>` wrap of mentions.

**Comment by inkhey** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Verified.
