### ISSUE TITLE
Bug: Message "Unknown shared space" is not translated

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3513]
## Diagnostic

The string  "Unknown shared space" is not passed to the translation function.

```
frontend/src/container/WorkspaceContent.jsx
241:        props.dispatch(newFlashMessage('Unknown shared space'))

frontend/src/container/Dashboard.jsx
158:        props.dispatch(newFlashMessage('Unknown shared space'))
```

## Translation strings

| English | French | Portuguese |
|:---------:|:----------:|:---------------:|
| Unknown shared space | Espace partagé inconnu | Espaço partilhado desconhecido |

## Extra information

URL to test: http://localhost:7999/ui/workspaces/1337/dashboard

**Comment by inkhey** [comment]
@raphj can you add the translation string result in the issue ?

**Comment by inkhey** [comment]
@raphj can you explicit in which context we can see this text, in order to be able to test it ?

**Comment by raphj** [comment]
Go to http://localhost:7999/ui/workspaces/1337/dashboard

**Comment by inkhey** [comment]
tested on branch.

**Comment by PhilippeAccorsi** [comment]
Verified.
