### ISSUE TITLE
Bug: the prompt to notify all users after an update does not hide when editing again

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3521]
## Description and expectations

The "to notify all users [...] click here" prompt remains open when re-editing the document. It shifts the UI elements towards the bottom of the app and can hide buttons on small screen.

- [x] The prompt must be hidden when editing a document.
- [x] The prompt must be hidden when viewing a previous revision.

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Verified.
