### ISSUE TITLE
Bug: Wrong link in the notification wall

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3522]
## Description and expectations

If we click on a "user commented in content X" notification instead of opening the content X, it tries to open an URL for the comment.

- [x] Notifications linked to a content should open its content

### Version information

- Tracim version: v.3.1

________________________________________________

## Diagnostic

When the URL is built the comment id is used instead of its parent id (the content).

## Extra information
This issue may solve the frontend part of https://github.com/tracim/tracim/issues/3525.

**Comment by inkhey** [comment]
i add information about a potential link with issue #3525

**Comment by raphj** [comment]
tested on branch.

**Comment by PhilippeAccorsi** [comment]
Verified.
