### ISSUE TITLE
Bug: mentions should appear in the notification wall but modifications of the logged user shoudn't

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3523]
## Feature description and goals

Notifications shown in the wall are going to be filtered. 
- Mentions should appear in the wall with the text and the icon showed here https://github.com/tracim/tracim/issues/2840.
- Updates made by the logged user shouldn't make a notification for itself 

### Expected

- [x] (front) Handle mention TLM in ReduxTlmDispatcher.jsx
- [x] (front) Filter TLM from the logged user in ReduxTlmDispatcher.jsx
- [x]  (front) Check if the notifications gotten from the API in Notification.jsx has a filter about the logged user.
- [x] (back) implement parameter `exclude_author_ids` for the `/messages` endpoint
- [x] (front) use parameter `exclude_author_ids`

## Diagnostic

- The mentions are already handled at NotificationWall.jsx component, but not its TLM in ReduxTlmDispatcher.jsx.

## Extra information

:warning: This fix bumps the documented minimal version of PostgreSQL from 9.3 to 9.6. It relies on a fix likely introduced in [version 9.4](https://www.postgresql.org/docs/9.4/release-9-4.html):

>    Corner cases in the JSON field/element/path extraction operators now return NULL rather than raising an error (Tom Lane)
 
We needed to extract a value from a JSON object which is sometimes NULL. We decided to match the PostgreSQL version that we battle-test Tracim against, which is also the one that is shipped in Debian Stretch, but Tracim likely still works on PostgreSQL 9.4+. Note however that PostgreSQL 9.4 and 9.5 have been unsupported by the PostgreSQL project for some time now.
 ________

2020-09-10 - exclude_author_id → exclude_author_ids
2020-09-14 - added the extra information section

**Comment by raphj** [comment]
tested on branch by @inkhey.

**Comment by PhilippeAccorsi** [comment]
Verified.
