### ISSUE TITLE
Bug: frequent (TLM) connection error after logging out and login again

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3524]
## Description and expectations

After logging out and then logging in again, the flash message saying that there are issues with the connection often appears.
Related issue: We are not redirected to the login page when we are disconnected from the API from the home page.

To do:
 - [X] do not show an error message in the login page
(Reported by @PhilippeAccorsi)
 - [X] redirect even from the home page.

## Diagnostic

The LiveMessageManager does not reset its timeout id after running the related callback in some cases. The connection to TLMs is therefore never restored. 

## Video

![tlm_error_after_disconnection](https://user-images.githubusercontent.com/3817365/93099634-871d3b80-f6a8-11ea-95f2-6d60afe8da4f.gif)

___
2020-09-17 - Diagnostic, information about redirections from the home page.

**Comment by PhilippeAccorsi** [comment]
My workflow:

- je suis connecté dans tracim, avec d'autre onglet ouvert (j'ai actuellement 60 onglet dans firefox et une partie qui corresponde à Tracim)
- je me déconnecte de tracim depuis mon onglet courant
- après quelques seconde (durée potentiellement aléatoire) le message d'erreur de connexion apparaît. Le message est visible sur la page de login.
- je renseigne mes identifiants puis je me connecte à Tracim
- le message reste visible à l'écran, pourtant tracim fonctionne correctement (pas vérifié les tlm mais le reste de l'interface fonctionne)

En cherchant dans mes autres onglets, je vois des onglets ouvert sur tracim avec le message d'erreur de visible.

**Comment by PhilippeAccorsi** [comment]
tab0 (leader)
![tab0-error-visible-after-disconnect-in-other-tab](https://user-images.githubusercontent.com/25848257/93097649-1f65f100-f6a6-11ea-9f21-fda5f35f2e8c.gif)

tab1
![tab1-error-visible-after-disconnect-in-other-tab](https://user-images.githubusercontent.com/25848257/93097721-36a4de80-f6a6-11ea-9326-e9edba945acf.gif)

**Comment by raphj** [comment]
I can reproduce, but with additional steps. Thanks. I'm going to shot a video.

**Comment by raphj** [comment]
On the login page:
- the frontend made a request to http://localhost:7999/api/auth/whoami that gives 401 (from LiveMessageManager).
- Status is then TLM Closed
- Then TLM Pending (?!?)
- Then TLM Connected
- Then TLM StreamOpen
- Then TLM Error
- Then a request to http://localhost:7999/api/users/3/live_messages gives a 401 error.

This could happen between login / logoff cycles. Maybe the request to whoami happens before logging off?

**Comment by PhilippeAccorsi** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Verified on preprod.
