### ISSUE TITLE
Bug: Using tracimcli to anonymize/delete users breaks the frontend

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3528]
## Description and expectations

`tracimcli` can be used to make modifications on users, it is especially used for anonymizing/deleting users.
After anonymizing a user all Tracim pages after login are not displayed, instead we get a blank page.

This should not happen, Tracim must stay functional.

For now, the backend send the following author object when a user is anonymized:
```
author: {
    lang: null,
    username: null
}
```
- [x] All author object should be null, i.e., should not have lang and username properties

- [x] Add a fictive author to TLMs when it has no author. The author should be:

```javascript
{
  user_id: 0,
  public_name: i18n.t('System Administrator'),
  username: '',
  avatar_url: null
}
```
- [x] Add a `is_from_system_admin` attribute to the TLM field in every case, its value will be `true` when a TLM has no author from the backend and `false` when it has one

The best place to do this would be `TracimComponent.execRegisteredLiveMessageHandler` as it is the only place where all messages arrive. `ReduxTlmDispatcher` could have been a candidate but it won't handle the case of direct TLM handlers (added with `registerLiveMessageHandlerList`).
- [x] The messages got through the `/api/users/<user_id>/messages` API must also be managed the same way (add the system admin author if no author in the message).

### How to reproduce

1. Anonymize a user using `tracimcli`: `tracimcli user anonymize -l <user_login>` in backend/configuration.ini folder.
2. Try to log on the same Tracim instance

### Version information

- Tracim version: develop/soon-to-be 3.1.0
- Web browser: Any
- Version: Not relevant
- Device / System: Not relevant

## Screenshots

________________________________________________

## Diagnostic

The events/TLMs created by the `tracimcli` command do not have an author, and the frontend code for the notification panel doesn't check that the author can be `null`.

## Discussed before development

There are 2 main ways to correct this:

- either the frontend code is changed (ideally everywhere a TLM author is used)
- OR the tracimcli actions do have an author.

If we go the second way we have several sub-questions to answer:

- which user can we use as an author for `tracimcli` (there is no authentication using this tool)
- if we have a reserved user, on which criteria can the command find it?
  - cannot be the id as we already have existing user ids (or we reserve an very big id to avoid collision?)
  - could be a username but we have to restrict its usage for normal users
  - could be a flag `is_cli_admin` (or a new profile?) on users: maybe the best solution, we'll need a migration script that can take care of inserting such a user. We also have to guarantee this user is unique.
- should this reserved user appear in the Tracim frontend/APIs? If yes should we restrict its `is_active`/`is_deleted` flags?

_09-09-2020 Decision: we went for the first option._

**Comment by gbonaspetti** [comment]
Personally I'm not a big fan of the front treatment because it means we can never be sure what comes from the back (public_name can be a string OR something else). But if it's simpler/cleaner, I'm not against it either, it's just necessary to make clear the possible values/types of each variable.

**Comment by lebouquetin** [comment]
@gbonaspetti the frontend receives a user structure, not username + userid + public_name, no?

**Comment by raphj** [comment]
For me, it is a reality that eventually, some events may not have an author and the front should check for it.

More generally, it seems to me that we are often discussing whether the front or the back should implement such or such check.
For me, stability can only be improved if checks are done in both the front and the back for things to be robust. This way, if one fails, the other can handle the case fine. It seems more reassuring to me.

For sure this may not be realistic for heavy checks, but checking whether an author is present and adjusting the notification display in consequence does not seem that heavy.

To me, the frontend should not trust that blindly that the backend has no bugs.

**Comment by gbonaspetti** [comment]
> @gbonaspetti the frontend receives a user structure, not username + userid + public_name, no?

Yes, sorry, I expressed myself badly in the example, what is defined are the variables that come in a TLM, and one of them is, for example, the author. If it's possible that the author doesn't exist, it has to be clear that it's an optional variable.

**Comment by grignards** [comment]
> For me, it is a reality that eventually, some events may not have an author and the front should check for it.

It is a reality as implemented now, but the truth is that even `tracimcli` events have an author: the human behind his keyboard. We just didn't bother to model him in Tracim until now.

> More generally, it seems to me that we are often discussing whether the front or the back should implement such or such check.
> For me, stability can only be improved if checks are done in both the front and the back for things to be robust. This way, if one fails, the other can handle the case fine. It seems more reassuring to me.

I agree for security related problems but here it is more a matter of API contract: it is not very productive to check that EVERY parameter you get from the backend can have ANY type/value… the documentation is here for that. Especially here as we develop the backend/frontend in the same team/company. If we were using a third-party backend it would make more sense.

> For sure this may not be realistic for heavy checks, but checking whether an author is present and adjusting the notification display in consequence does not seem that heavy.
> 
> To me, the frontend should not trust that blindly that the backend has no bugs.

Like I wrote above, this is not a backend bug, merely a mis-understanding on what is possible or not.

**Comment by inkhey** [comment]
tested on branch.

**Comment by PhilippeAccorsi** [comment]
Verified.
