### ISSUE TITLE
Bug: The foreign key constraint on messages created by the migration script is not the same as creating a DB from scratch

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3529]
## Description and expectations

The migration script (`backend/tracim_backend/migration/versions/3c92f57c52b2_added_events_and_messages_tables.py`) does not include the `ondelete="CASCADE"` parameter for the foreign key on `event_id` in the `messages` table.

- [X] add a new migration script that adds this parameter to the constraint.

### How to reproduce

1. Create a database with an older version
2. Upgrade to the last version using alembic

### Version information

- Tracim version: starting from 3.0

## Implemented solution

- Update database sqlalchemy schema to use ondelete cascade for message on event_id
- Update migration scripts with this ondelete cascade, in a way that work with all supported database

**Comment by PhilippeAccorsi** [comment]
Tested on branch by @inkhey 
Verified.
