### ISSUE TITLE
Feat: Add more command to really delete data in tracimcli

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#3530]
## Feature description and goals

It's currently possible to really delete user data through tracimcli which is great to deal with privacy issue with historical user which does not want to use the service anymore.

There are other case where it's needed for admin-sys to be able to trully delete data from tracim and where modifying directly database may be painful and time consuming : 
- creating a sub-set of data from a database from an existing database by only keeping some user/space. (useful for dev debugging, for demo, etc...) 
- Removing content that cause some issues (legal issue, confidentiality issue "mistake", etc...)

## Extra information

The method to delete workspace, content and revision already exists in the cleanup lib.
Branch: [feat/3530__add_new_delete_commands_to_tracimcli](https://github.com/tracim/tracim/tree/feat/3530__add_new_delete_commands_to_tracimcli)

## Linked PR
PR #5585

**Comment by inkhey** [comment]
@lebouquetin Don't you think, this issue should be in the backlog ? (at least the backend part)

**Comment by inkhey** [comment]
Note: we should probably add a comment to remove content revision too, may be useful for confidentiality issue.

**Comment by PhilippeAccorsi** [comment]
And solution maybe for TLM and reactions (load of recent activity can have some trouble, no ?)

**Comment by inkhey** [comment]
I created a first step here : https://github.com/tracim/tracim/pull/5585
It add command to delete:
- space
- content
- revision

@PhilippeAccorsi You suggested others command for TLM and reactions. Can you give us a use case ? Content reaction cleaning ? TLM cleaning ? Something else ?

In my PR, i also faced some ORM issue` to make TLM work properly during deletion, so i'm not sure all case does work as expected. I do think this kind of feature will need some heavy testing with real data to be sure it work as expected.

**Comment by PhilippeAccorsi** [comment]
Some comment added in the PR.
