### ISSUE TITLE
Feat: Add an access type parameter to spaces

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3536]
## Feature description and goals

Currently, the only way for a user to be a member of a Tracim space is for a space manager to add them to the space.
It can be useful to have other access methods for selected spaces in order to add "discoverability" to Tracim instances.

- [x] Add an `access_type` parameter to space APIs.
- [x] The access type parameter can be:
  - `CONFIDENTIAL`: the current space access type
  - `ON_REQUEST`: those spaces are visible to any user (but their contents are only accessible by their members). A user will be able to request access to those spaces. Access implementation is detailed in https://github.com/tracim/tracim/issues/3539 and is not part of this issue
  - `OPEN`: those spaces are accessible by any user of the Tracim instance. Access implementation is detailed in #3538 and is not part of this issue
- [x] Add a database migration script that will add the `access_type` to the `workspaces` table and set it to `CONFIDENTIAL` for all existing rows
- [x] The `access_type` must be given when creating the space through the API
- [x] We won't initially allow to modify the `access_type` of an existing space, so restrict it in the corresponding PUT API.

## Discussed before development

- is not allowing the modification of `access_type` after the space creation acceptable?

It is acceptable, see comments below.

## Extra information
Implemented solution here: https://github.com/tracim/tracim/pull/3585
Contain also frontend fix to force usage of access_type.

**Comment by raphj** [comment]
>   is not allowing the modification of access_type acceptable?

I guess it is acceptable, and we can always revert this decision later if needed.

**Comment by inkhey** [comment]
>     * is not allowing the modification of `access_type` acceptable?

What the goal of not allowing it ? We can keep the default value to CONFIDENTIAL and this way we can keep the current behaviour of frontend.

**Comment by grignards** [comment]
> > ```
> > * is not allowing the modification of `access_type` acceptable?
> > ```
> 
> What the goal of not allowing it ? We can keep the default value to CONFIDENTIAL and this way we can keep the current behaviour of frontend.

Changing the access type (OPEN -> (ON_REQUEST/CONFIDENTIAL)) after creation means that we'd potentially have to remove users from the space/do other things that administrators could expect. It also means that the frontend has to provide an interface for this change.
Nothing unfeasible, just takes time…

**Comment by lebouquetin** [comment]
I agree with @grignards : first iteration need to add this property at creation time. Allowing to update it will introduce side effects which are not necessarely usefull.

Example:

1. User XXX requested to join space YYY
2. space YYY become OPEN
3. How do the software manage this case?

Same example if the space become private. Do we just ignore requests? Do we drop them? Do we activate/disactive them?

This potentially involves email workflow, which is quite difficult to shortcut...

The easiest way to do things is to first allow creation (which is enough for ASF) and in the future (near future?) implement the possibility to modify it.

**Comment by inkhey** [comment]
ok i didn't understand correctly that we do not allow it for update only.

**Comment by inkhey** [comment]
@grignards created a PR here: https://github.com/tracim/tracim/pull/3585.
Only difference with specification now : access_type is currently optional, if not provided, default to confidential. I can do this fix, but this will directly broke the frontend until a fix is done for this.

**Comment by grignards** [comment]
OK, I'll push a frontend fix to add the CONFIDENTIAL parameter to creation.

**Comment by lebouquetin** [comment]
@grignards @inkhey is the parameter to be explicitly added? It looks not critical one or the other right now, *but* in terms of compatibility, it would break all API clients creating spaces. (this is something you must have in mind when changing API signatures/behaviors)

**Comment by lebouquetin** [comment]
what about adding a label for future developments `breaks CLI` or `breaks API` or something like this in order to  help writing release documentation?

**Comment by inkhey** [comment]
> @grignards @inkhey is the parameter to be explicitly added? It looks not critical one or the other right now, _but_ in terms of compatibility, it would break all API clients creating spaces. (this is something you must have in mind when changing API signatures/behaviors)

The specification say it "must", so yes. My current implementation say "use confidential by default" which is not conform.
It's a tradeoff between having a strict api with the minimum or unclear case and don't break the api.

**Comment by lebouquetin** [comment]
yes @inkhey both choices seems correct - my point is to clarify the behavior/choices to do in similar cases. At the moment backward compatibility does not seem to be so important (there are not plenty of users) but this is a case which will arrive and we will have to deal with it.

**Comment by grignards** [comment]
> At the moment backward compatibility does not seem to be so important (there are not plenty of users) but this is a case which will arrive and we will have to deal with it.

I admit I'm more in the "backwards-compatibility of APIs is not important right now" mindset so I didn't consider it here. As for dealing with breaking changes when the time comes:

- make it clear we have to support backward-compatibility (through an initial information + appropriate developer documentation/check-lists)
- for the HTTP API I would use the openapi documentation to ensure backwards-compatibility (or be informed when a breaking change occurs to documentate it)
- for other APIs (backend plugins? frontend apps?) we should first define what is public and what is not + make the split clear for everyone: Tracim developers and third-party developers. This probably would lead to maintain two sets of APIs: one private (that we can touch without fearing to break something) and one public (where every change is especially checked).

**Comment by inkhey** [comment]
@grignards @lebouquetin About this point we probably should create some technical debt ticket to clarify the idea here as our current marshmallow schema doesn't systematically use "required=True", there is probably some case where we are not strict but we should.

**Comment by inkhey** [comment]
To test this:
- update tracim (both backend and frontend) on branch.
- check if workspace creation is not broken.

**Comment by PhilippeAccorsi** [comment]
Done.
