### ISSUE TITLE
Feat: API for previewing OPEN and ON_REQUEST spaces

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3540]
## Feature description and goals

`OPEN` and `ON_REQUEST` spaces (see #3536 for details) can be previewed by any user so that they can become a member.

- [x] Add an API GET `/api/users/<user_id>/accessible_workspaces`:
  - accessible by the current user and administrators
  - returns the list of accessible spaces: every space the user is not member of and have access type `ON_REQUEST` or `OPEN`, see #3536).
  - the returned space object should only include:
```json
{
  "workspace_id": 42,
  "label": "My workspace",
  "description": "A short description",
  "access_type": "open",
  "slug": "my-workspace"
}
```
NOTE: added `slug` and `sidebar_entries` as they are part of every workspace object in the API. Using `description` instead of `public_description` until we choose whether to do #3551 or not.

## Prerequisites

- #3536
- #3551

## Design alternatives

Another design would be to modify the semantics of `/api/users/<user_id>/workspaces` in order to return every workspace the user is member of/has access to. And add a filter `is_member`.

@grignards I chose not to change the semantics as modifying the existing is generally more difficult than to create an new API. Also the usefulness of changing the semantics wasn't an evidence for me.

**Comment by inkhey** [comment]
Need probably some clarification about what informations we do provide to user about theses space.
Depending on the meaning we do have from "space descriptions", it should or shouldn't be publicly visible.
I do suggest to firstly do not leak description but a new "summary" public field may be a solution.

**Comment by lebouquetin** [comment]
I agree with @inkhey : we should have a short public description which is different from the space description (which may be large and rich text through HTML)

**Comment by inkhey** [comment]
issue created here about the public_description : https://github.com/tracim/tracim/issues/3551

**Comment by lebouquetin** [comment]
@grignards I suggest `s/can be viewed/can be previewed` (or discovered) to be clear that it is only a limited access

**Comment by raphj** [comment]
l like "discovered" (or "listed")?

**Comment by PhilippeAccorsi** [comment]
@grignards title of issue is `Feat: Allow API access to OPEN and ON_REQUEST spaces` but if I understand correctly, `ON_REQUEST``is done in another issue. This is right ?

If yes can you modify title or add comment about that ?

**Comment by grignards** [comment]
I think the `ON_REQUEST` in the title is OK: the goal of this issue was to provide an API for users to preview OPEN and ON_REQUEST spaces so that they can see some information about them before self-subscribing.
I edited access -> preview to make this clearer.

**Comment by PhilippeAccorsi** [comment]
Thanks.
Done.
