### ISSUE TITLE
Bug: no margin at end of a paragraph

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#3542]
## Description and expectations

When I type a comment splited into several paragraphs, the render of my comment does not show any margin between paragraphs, which makes text harder to read.

Same remark for bullet lists.

Expected: add a margin at bottom of paragraphs and end of bullet points

### How to reproduce

1. Type a comment composed of several paragraphs using TinyMCE.
2. Validate it.

### Version information

- Tracim version: 3.0.4
- Web browser: firefox
- Version:80.0.1
- Device / System: PC/Linux

## Screenshots

![image](https://user-images.githubusercontent.com/907161/92901517-d6513b00-f420-11ea-8a28-c68bc517cbcf.png)

## Diagnostic

Missing CSS rules. (note: these CSS rules must apply only to user defined content)

## Related issue

#3653, #3478

**Comment by PhilippeAccorsi** [comment]
This issu is added in this project but not visible in board. So I just have change label and put in `issue to review`.

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
