### ISSUE TITLE
Bug: Notification wall has inconsistent borders

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3543]
## Description and expectations

The notification wall has inconsistent borders, sometimes thinner, sometimes thicker, which is not pleasant for the user.

### Version information

- Tracim version: v3,1
- Web browser: any
- Device / System: any

## Screenshots

![Capture d’écran de 2020-09-11 10-54-02](https://user-images.githubusercontent.com/35422692/92897167-452c9500-f41d-11ea-8265-f4be1e986ff0.png)

________________________________________________

## Diagnostic

All elements have 1px borders, but when the element is "touching" other its border are sum and we have a 2px border.

## Prerequisites

None

**Comment by PhilippeAccorsi** [comment]
I move this issue in "in progress" because fix is not merge for the moment.

**Comment by PhilippeAccorsi** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
