### ISSUE TITLE
Feat: Enable child spaces

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3546]
## Feature description and goals

With the introduction of the new `OPEN` space type (see #3536), allowing a more fine-grained access (as access to contents is space-based in Tracim) while preserving a logical link between spaces on the same subject becomes useful.

A good way to do this is to allow a space to be created as a child of another.
One can easily imagine a parent space which is more "open" than one of its children spaces which is used for confidential information sharing.

- [x] Add a `parent_id` attribute to `workspaces` objects and APIs. This id will be a key to another workspace, thus a positive integer (see below).
- [x] Do not check maximum depth of the resulting tree (at creation)
- [x] This id must be given to the creation API. If a space is at root, `parent_id=null` should be used.
- [x] Add this id to the `PUT /api/workspaces/<workspace_id>` API.
- [x] Add a migration script that will add this column and set its value to `NULL` for all existing rows.
- [x] Add a `parent_ids` filter on GET `/api/workspaces` and GET `/api/users/<user_id>workspaces` to be able to restrict the results to space having a parent with the given ids. The list will be integers separated by commas: `1,2`. If the parameter is not given, all spaces will be returned, in this particular case 0 refer to no parent case.
- [x] ~~Modify the PUT `/api/workspaces/{workspace_id}/trashed` API to trash all children spaces if a space with children is trashed~~ Removed from spec see https://github.com/tracim/tracim/issues/3546#issuecomment-703464308
- [x] ~~Similarly, modify the `/api/workspaces/{workspace_id}/trashed/restore` API to restore all children spaces if a space with children is restored~~ Removed from spec see https://github.com/tracim/tracim/issues/3546#issuecomment-703464308
- [x] As parent_id is now mandatory for workspace creation, frontend should be adapted.

### Shall we allow child spaces to be moved to another parent/at root?

@grignards In my opinion this is not necessary right now and it will make the space members management more complicated so I would rather do it later.

**Decision** : the restriction will be done in the specific member management plugin implemented in #3572.

 ## Extra information 
Related issue:
- https://github.com/tracim/tracim/issues/3549 for webdav support
- https://github.com/tracim/tracim/issues/3549 for cleanapi support.

## Implemented solution
https://github.com/tracim/tracim/pull/3665
- add `parent_id` to `workspace` database table, referring to another `workspace_id` + migration script.
- add `parent_id` to `WorkspaceSchema`
- add `parent_id` as mandatory for  `PUT /api/workspaces/<workspace_id>`, does work only with known parent_id of authenticated user, instead return WorkspaceNotFound error.
- frontend fix to handle `parent_id` as mandatory
- add `parent_ids` filter to both  GET `/api/users/<user_id>workspaces`  and GET `/api/workspaces` 
- add method to get both direct and recursive children of workspace in an effective way (recursive cte).

**Comment by inkhey** [comment]
Some question:
- Why parent_id=0 and no parent_id = Null like for content ? note: we can accept 0 as same as None for query filter if needed.
- What should be the result for webdav view of such tree organization ?
- What should be the behavior for cleanapi command. We do have a method to remove workspace from database (hardly removed) that is used when removing user (we do remove workspace according to workspace owner), If owner of parent is A and owner of children is B, and we do remove A, The more logical behavior is refusing deleting A unless we force it. So we do need to fetch recursively the children workspaces before removing one.

**Comment by grignards** [comment]
> Some questions:
> 
>     * Why parent_id=0 and no parent_id = Null like for content ? note: we can accept 0 as same as None for query filter if needed.

A `NULL` value in SQL has the meaning "I don't know", here we want to model "this space has no parent". Having NULLs in columns make joins more difficult among many other things (see https://en.wikipedia.org/wiki/Null_(SQL)).

> 
>     * What should be the result for webdav view of such tree organization ?

I would say a folder within another folder, the main difference is that users won't be able to move the space folders (which is already the case I guess).

>     * What should be the behavior for cleanapi command. We do have a method to remove workspace from database (hardly removed) that is used when removing user (we do remove workspace according to workspace owner), If owner of parent is A and owner of children is B, and we do remove A, The more logical behavior is refusing deleting A unless we force it. So we do need to fetch recursively the children workspaces before removing one.

Good question… I think we can go this way: recursively remove workspaces (with a force option). But we have to be careful not to stop in a middle situation where some spaces/contents are removed and others not when the force option is not provided and a different owner is found in a child space.

**Comment by inkhey** [comment]
> ### Shall we allow child spaces to be moved to another parent/at root?
> 
> @grignards In my opinion this is not necessary right now and it will make the space members management more complicated so I would rather do it later.

For the frontend part: i do agree.
For the backend part: it depends. If this is just changing the id, it can be made. If we expect some recursive rules between parent and children, it will be really tricky. The other problem by allowing this through api is what the frontend will do when refreshing TLM with a content that have changed of parent.

**Comment by gbonaspetti** [comment]
> Shall we allow child spaces to be moved to another parent/at root?
@grignards In my opinion this is not necessary right now and it will make the space members management more complicated so I would rather do it later.

I agree, for me it's a future improvement

**Comment by grignards** [comment]
@inkhey Do you think the webdav part will need a separate development?

**Comment by inkhey** [comment]
> @inkhey Do you think the webdav part will need a separate development?

If we do want to support space hierarchy properly, yes. It will mean having space at same level as content which maybe tricky. Note that we do support renaming/deleting of space in webdav.

**Comment by inkhey** [comment]
Should we allow infinite parent/children workspace tree ?

**Comment by lebouquetin** [comment]
@grignards you wrote:

> In my opinion this is not necessary right now and it will make the space members management more complicated so I would rather do it later.

Why would it be more complicated for space members management ? I don't think its required to link sub-members to parent-members. If this is not related, I think moving a space would not create new problems.

What do you have in mind?

**Comment by grignards** [comment]
> @grignards you wrote:
> 
> > In my opinion this is not necessary right now and it will make the space members management more complicated so I would rather do it later.
> 
> Why would it be more complicated for space members management ? I don't think its required to link sub-members to parent-members. If this is not related, I think moving a space would not create new problems.
> 
> What do you have in mind?

@lebouquetin Even if we do not link them for the "general" Tracim development, for ASF needs we would have to take care of this move as having linked member lists between sub-spaces is one of their requirements. My comment was for this particular development.

**Comment by grignards** [comment]
> Should we allow infinite deep for parent/children workspace tree ?

This has been discussed, the backend will not enforce a maximum depth but the frontend will display a warning before creating a space if it could lead to a non-optimal display in the sidebar.

**Comment by inkhey** [comment]
> > Some questions:
> > ```
> > * Why parent_id=0 and no parent_id = Null like for content ? note: we can accept 0 as same as None for query filter if needed.
> > ```
> 
> A `NULL` value in SQL has the meaning "I don't know", here we want to model "this space has no parent". Having NULLs in columns make joins more difficult among many other things (see https://en.wikipedia.org/wiki/Null_(SQL)).

Ok, i understand this point but from a simple database point of view, as we should have foreign key on parent_id column, how can we deal to put a "0" value without any valid join ?

**Comment by grignards** [comment]
> > > Some questions:
> > > ```
> > > * Why parent_id=0 and no parent_id = Null like for content ? note: we can accept 0 as same as None for query filter if needed.
> > > ```
> > 
> > 
> > A `NULL` value in SQL has the meaning "I don't know", here we want to model "this space has no parent". Having NULLs in columns make joins more difficult among many other things (see https://en.wikipedia.org/wiki/Null_(SQL)).
> 
> Ok, i understand this point but from a simple database point of view, as we should have foreign key on parent_id column, how can we deal to put a "0" value without any valid related value ? With NULL dealing with this is straightforward, with 0, i don't know.

Fair point, I changed the description.

**Comment by lebouquetin** [comment]
@grignards I don't know if you detect that your last two checkboxes are not do/undo.

Imagine spaces B and C are children of A. With the behavior you suggest:

- You trash B. -> still available spaces: A and C
- Then you Trash A -> still available spaces: nothing
- Then you restore A -> still available spaces: A, B and C

It's not a problem (there is no easy-to-implement mechanism) but this is not like do/undo

**Comment by inkhey** [comment]
Just found one unclear points that may be solved later (in another ticket):
- How we handle the validation of parent_id ? 
  - If parent_id is not None and does not refer to an existing space : i do suggest to try to load parent and return a specific error if parent doesn't exist.
  -  if parent is not known for user: i do suggest we try loading parent from user known_space and return a specific error if parent doesn't refer to a space the user doesn't known .

**Comment by inkhey** [comment]
> @grignards I don't know if you detect that your last two checkboxes are not do/undo.
> 
> Imagine spaces B and C are children of A. With the behavior you suggest:
> 
>     * You trash B. -> still available spaces: A and C
> 
>     * Then you Trash A -> still available spaces: nothing
> 
>     * Then you restore A -> still available spaces: A, B and C
> 
> 
> It's not a problem (there is no easy-to-implement mechanism) but this is not like do/undo

Just discover some other edge case :+1: 
- User U1 as right to delete A but not B, what should happened if B child of A and U1 to delete A? (we do have the problem at N level)
- User U1 as right to undelete A but not B, what should happened if B child of A and B was deleted before by U2 ?

I currently suggest two solutions:

#### 1. Do not remove/restore recursively workspace at Api level
- Do not allow recursive delete/undelete outside of cleanapi managment scope.
- As frontend should take take of case where parent are not anymore valid, this will not cause to much issue to only delete parent and do not try delete children.

#### 2. Best effort recursive deletion
Another but  a bit more complex solution can be:
- remove all children known by user recursively, This should not be too much complicated but i'm not sure that a good idea.
- restore all children which should be known by user (as the workspace is deleted the user cannot access to it but we do not drop user 
It's seems to me not so complex to make it work but i'm not sure if this mechanism is not too much complex to explain to user.

**Comment by lebouquetin** [comment]
@inkhey I think the "do not delete recursively" option is ok. If a parent workspace is deleted, then children:

- do not change
- should become naturally root spaces (what I mean by "root" is on a user point of view, they should appear at root level - but their parent_space_id should not change)

**Comment by inkhey** [comment]
Another point:
- in current implementation `/api/workspaces` is sorted by workspace id whereas` /api/users/<user_id>workspace` is sorted by workspace label

@gbonaspetti @raphj did you know if there is any reasons behind this behavior ?

**Comment by raphj** [comment]
the frontend sorts workspaces using natural sort anyway. It does not rely on any sort done by the backend. I'd say, no need to sort them at all in the backend.

**Comment by lebouquetin** [comment]
@inkhey If a space "CHILD" is children of "PARENT" and I am a member of CHILD but not member of PARENT, then I MUST be able to access CHILD space. I also can be manager of CHILD and edit/update it (but not move it)

**Comment by inkhey** [comment]
Just recheck the code, in fact, 
- we can use any number for parent_ids as filter for both:
   - `GET /api/workspaces`
   -  `GET /api/users/<user_id>workspaces`
- we do need to be able to see a workspace to be able to set a new workspace with him as parent. for `POST /api/workspaces` endpoint. As we cannot set parent after, there is currently no issue with case where someone remove parent and can replace it.

**Comment by inkhey** [comment]
Just a last point about this PR:
This PR does not add Index on new field parent_id of workspace, which probably mean poor performance. As we currently doesn't have much need for performance here (real usage of recursive workspace will be done in another ticket for cleanapi), current PR should not cause much trouble.

So should we include index now or leave this performance issue for later (and probably check this with more accuracy using metric) ?

**Comment by lebouquetin** [comment]
As `parent_id` is a foreign key, the default choice is to add an index.

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
