### ISSUE TITLE
Bug: Contents received via TLMs sometimes appear doubled

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3547]
## Description and expectations

Sometimes, when several tabs are open everything is received twice or more. New comments and new revisions of document appear twice in the timeline:

![select_stay_active](https://user-images.githubusercontent.com/25848257/92930828-e0843100-f442-11ea-973e-025c96f1cdd9.gif)

To do:
 - [X] Ensure TLMs are not dispatched twice by checking that the event id of the TLM is greater than `afterEventId`
 - [X] When a leader detects that there is another leader, close the live message connection and restart the connection to the broadcast channel.

### How to reproduce

Difficult to reproduce "naturally". We think it can happen after resuming the computer from suspend. 

To artificially trigger the bug, run this in the web console of the tab that is connected to the live messages (the leader):

```js
d=Date.now(); while(Date.now() - 5000 - d < 0); 
```
You can see if a tab is a leader by the presence of the regular `.:. TLM KeepAlive:` or `.:. TLM received` messages in the console.

### Version information

- Tracim version: v.3.0+
- Web browser: Firefox
- Device / System: PC

### Diagnostic
Tabs use a [BroadcastChannel](https://github.com/pubkey/broadcast-channel) to communicate. A leader election happens between the tabs. The leader connects to the backend to receive TLMs and broadcasts them to the other tabs.
Problems arise when several pages, for some unknown reason, become leaders.
This probably happens because a timeout is not met because some tabs are busy or the computer has a slowdown.

### Discussed

@grignards thinks that it can happen because the leader election happen at startup, when the frontend is already very busy loading all its stuff. We settled on not changing the moment when the connection to the live messages is open for now.

A previously suggested idea (by @raphj) for this is as follows:
 - assign a unique id to each tab. Maybe some ever growing number (possibly stored in localStorage) or using uuids. better still, we may just use `Date.now()` (precise to the millisecond) + some random number to really reduce chances that two tabs get the same id to the minimun. `performance.now() + performance.timeOrigin` [would be experimental](https://developer.mozilla.org/en-US/docs/Web/API/Performance/timeOrigin). 
 - this id is transmitted with each message
 - whenever a tab is leader and receives a message from another tab with a bigger id, it stops being leader. 
 - any message that has already been handled should be dropped. We know which messages have already been handled: their ids are smaller than `lastEventId` in `src/util/LiveMessageManager.js`.

This idea mimics a poorly thought leader election so we settled on another way to do this: just restart everything when an inconsistency is detected, trusting that:

 - leaders either are screwed and do not communicate anyway, or will detect the situation too and restart the connection 
 - the leader election will eventually elect only one leader

_____
2020-09-14 - Added the Diagnostic, the discussed and the To do sections.

**Comment by inkhey** [comment]
tested on branch using`d=Date.now(); while(Date.now() - 5000 - d < 0); ` hack to trigger the issue.

**Comment by PhilippeAccorsi** [comment]
Verified.

**Comment by raphj** [comment]
I put this ticket from Done to To close for integration in the changelog for version 3.1.4. (cc @PhilippeAccorsi)

**Comment by PhilippeAccorsi** [comment]
Done in Tracim 3.1.4
