### ISSUE TITLE
Bug: mention auto-completion has various issues

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3548]
#### Auto-completion is not always triggered

- Auto-completion popup of mentions is not triggered with a document containing `<p>b@ar</p><p id="5">&nbsp;</p>`, by opening the document and directly starting a statement. It's us who insert this space, so it's done frequently if we want to insert a statement at the end of the document. _(Bug reported by @grignards )_

- Auto-completion is not triggered when a space is present before the `@`

#### Unable to close the mention autosuggestion popup

 - the escape key should close the popup

#### Mentions are sometimes deleted when validating the autosuggestion
https://github.com/tracim/tracim/pull/3603#issuecomment-694292150

![image](https://user-images.githubusercontent.com/35422692/93488326-8681e080-f906-11ea-8d94-67526ba14874.gif)

#### A generic message is shown when trying to send a document with an incorrect mention
https://github.com/tracim/tracim/pull/3603#issuecomment-694292150

#### There are HTML leftovers

https://github.com/tracim/tracim/issues/3581

#### Mentions are teleported in tables

https://github.com/tracim/tracim/issues/3568

![image](https://user-images.githubusercontent.com/35422692/93093800-69000d00-f6a1-11ea-9c3f-500f14d42f0e.gif)

**Comment by PhilippeAccorsi** [comment]
~~~
Unable to close the mention autosuggestion popup
- the escape key should close the popup
~~~

This is not working in simple text (comment in timeline).

**Comment by PhilippeAccorsi** [comment]
Verified.
