### ISSUE TITLE
Bug: Wrong highlight in a "not-mention"

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3550]
## Description and expectations

Even if they don't get the mention, every time we write `@something` we get a highlight as if it were a mention.
The behavior can be disturbing when someone who is not a member of space is "mentioned".

### How to reproduce

1. Open a content
2. Write `@...` (... = someone that is not a member of the space)
3. Validate

### Version information

- Tracim version:v.3.1.0
- Web browser: any
- Version: any
- Device / System: any

## Screenshots

![Capture d’écran de 2020-09-11 16-50-20](https://user-images.githubusercontent.com/35422692/92940193-16c7ad80-f44f-11ea-9724-a59ff6b5f8d5.png)

________________________________________________

**Comment by raphj** [comment]
Closing, as I think this is not an issue anymore. (cc @gbonaspetti)
