### ISSUE TITLE
Bug: No way to see the file extension when content file is very long

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#3557]
## Description and expectations

When you set a very long name to content, the file_extension is not visible anymore in the header bar. Please note also that the overlay info doesn't provide the file_extension.

### Version information

- Tracim version: build_033

## Screenshots

![Peek 14-09-2020 10-20](https://user-images.githubusercontent.com/7851652/93061998-9edacc80-f674-11ea-9f1f-7cfc3a13742c.gif)

________________________________________________

**Comment by raphj** [comment]
This should be fixed in #4230

**Comment by PhilippeAccorsi** [comment]
Done with this meta issue #4224
