### ISSUE TITLE
Bug: The autocompletion popup position is erroneous

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3559]
## Description and expectations

The autocompletion popup of mentions and links appears underneath even at the bottom of the document and systematically appears above if lines of text are present before the mention/link. Sometimes it's not even in the document, like we can see at the image below.

![Capture d’écran de 2020-09-08 09-52-50](https://user-images.githubusercontent.com/35422692/93083319-b45eef00-f692-11ea-8489-3ae384973773.png)

### Version information

- Tracim version: v3.1.0
- Web browser: at least Google Chrome
- Device / System: at least PC

________________________________________________

## Diagnostic
The position detection function didn't take into account the scroll that was performed. so the function was changed to getBoundingClientRect() that refers to the screen and not to the parent node. Besides that, some fixes were made regarding the popup being cut off when it was at the beginning of the detection zone and the comment edition popup that didn't take the specific style into account.

**Comment by raphj** [comment]
We noticed with @grignards that with a long HTML document, the mention suggestion popup is displayed far in the bottom of the app, so far that a scrollbar outside tinymce but in the app (at the left of the timeline) appears.

**Comment by raphj** [comment]
tested on branch
