### ISSUE TITLE
Bug: Wrong Portuguese translation

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3562]
## Description and expectations

The notification "status update" has a problem in its Portuguese translation, the author's public name isn't displayed (see screenshot). There is also a typo in an English sentence: "I know this user exist" should read "I know this user exists"

### Expected
- [x] Add a `{`in the Portuguese translation
- [x] Change "I know this user exist" to "I know this user exists"

### How to reproduce

1. Change your language to Portuguese
2. Ask someone to update the status of some content
3. See the notification received

### Version information

- Tracim version:v3.1.0

## Screenshots

![Capture d’écran de 2020-09-14 14-45-09](https://user-images.githubusercontent.com/35422692/93087676-32be8f80-f699-11ea-8217-e44794362caf.png)

___
2020-09-16 - mention "I know this user exist"

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Verified.
