### ISSUE TITLE
Bug: Responsive problem with "see more" button in the progressive web app

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3564]
## Description and expectations

The notification wall does not display the arrow to see more notifications in the progressive web app.

_(Bug reported by @PhilippeAccorsi )_

### Version information

- Tracim version: v3.1.0
- Web browser: at least Firefox
- Device / System: smartphone

________________________________________________

**Comment by raphj** [comment]
> the progressive web app

Did you mean responsive? (mobile view?)

**Comment by PhilippeAccorsi** [comment]
> > the progressive web app
> 
> Did you mean responsive? (mobile view?)

I mean progressive web app :) (cf https://fr.wikipedia.org/wiki/Progressive_web_app and/or https://developer.mozilla.org/fr/docs/Web/Progressive_web_apps )

**Comment by MariePrandstetter** [comment]
This problem bug doesn't show up in the 3.5 version either. It has probably been fixed indirectly
