### ISSUE TITLE
Bug: Table toolbar at TinyMCE is wrongly displayed

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3567]
## Description and expectations

The table toolbar at TinyMCE is wrongly displayed (see GIF at Screenshot session)

### How to reproduce

1. Go to a html-document
2. Create a table
3. Click at a cell

### Version information

- Tracim version: v3.1.0
- Web browser: any
- Device / System: at least PC

## Screenshots

![table](https://user-images.githubusercontent.com/35422692/93092297-8cc25380-f69f-11ea-8906-ae9b59cd17b6.gif)

________________________________________________

## Diagnostic

The following css rule causes the problem `.mce-tinymce:not(.mce-fullscreen), .mce-container-body { min-height: 100%; }`

_(Diagnostic by @raphj )_

## Implemented solution

Restrict the hack to set the tinymce height to things that are in the `#content` div, so it does not apply to tinymce's toolbars, that are added to the `<body>` tag (contrary to the editor).

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Verified on preprod.
