### ISSUE TITLE
Bug: Mentions have a weird behavior in tables

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3568]
## Description and expectations

When we start writing a mention in a table cell and then decide to write something in another cell, the mention "follows" the current cell.

_(Bug reported by @raphj )_

### How to reproduce

1. Go to a html-document
2. Create a table
3. Click at a cell and start to write a mention
4. Click at another cell and continues a write

### Version information

- Tracim version: v.3.1.0
- Web browser: any
- Device / System: at least PC

## Screenshots

![mentionAtTable](https://user-images.githubusercontent.com/35422692/93093800-69000d00-f6a1-11ea-9c3f-500f14d42f0e.gif)

________________________________________________

## Prerequisites

None

**Comment by raphj** [comment]
Duplicate of #3548
