### ISSUE TITLE
Bug: My Account and the dashboard are referring to notifications instead of email notifications

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3569]
## Description and expectations

The "My Account" page and the dashboard should make it clearer that they are referring to email notifications.

### Version information

- Tracim version: v3.1.0
- Web browser: any
- Version: any
- Device / System: any

## Screenshots

- My Account page

![Capture d’écran de 2020-09-14 15-51-31](https://user-images.githubusercontent.com/35422692/93095218-23444400-f6a3-11ea-90d0-640b7d4bd273.png)

- Dashboard

![Capture d’écran de 2020-09-14 15-54-28](https://user-images.githubusercontent.com/35422692/93095231-25a69e00-f6a3-11ea-9473-17dca8eb99c9.png)

________________________________________________

**Comment by MariePrandstetter** [comment]
This issue has been fixed in pr [#3726](https://github.com/tracim/tracim/pull/3726)

**Comment by PhilippeAccorsi** [comment]
Fix available since Tracim 3.2.1
