### ISSUE TITLE
Feat: Implement access rules for sub-spaces

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3572]
## Feature description and goals

Sub-spaces (see #3546) will allow to  create a hierarchy of spaces. By default the members of spaces in this hierarchy do not have any link between them (as it is currently the case).
Nevertheless having spaces where adding a member in a sub-space also add it in the ancestor space(s) can be useful for some use-cases.

In a separate "plugin" which is not activated by default, using event hooks:

- [x] add user in ancestor spaces when a member is added in a sub-space using event `on_user_role_in_workspace_created`
- [x] the user will be added with the default user role of the ancestor spaces

## Prerequisites

- #3601

### Are members of sub-spaces automatically added to "ancestor" spaces?

**Decision**: Yes, but not by default, this behavior is configurable per instance (through the activation or not of the corresponding plugin).

### Which role are members of sub-spaces given?

Could either be the default role of the space OR the role given in the sub-space.

@grignards I find the default role better as I think giving a privileged role (contributor/manager/...) to parent space just because this role is given in the sub-space is not secure/wanted.

**Decision**: we'll use the default role of the parent space(s).

### ~~if yes~~, does the opposite (removing the user from a sub-space) remove the user from "ancestor" spaces (if added automatically)?

@grignards I would say no for easier implementation and easier behavior.
If we would remove members from ancestor spaces we'd have to tag which members where added automatically and the case where a member was added automatically but its role has been modified after-wise would have a difficult-to-understand behavior.

**Decision**: we won't implement an automatic removal of users in child spaces for this first development.

## Implemented solution:
https://github.com/tracim/tracim/pull/3723

- add Parent Access Plugin with add new members into all parent of the workspace recursively with default role of each workspace
- add tests on this plugin.
- fix issue with empty user by setting user instead of user_id in role creation.

**Comment by inkhey** [comment]
I do see 3 potential behavior depending on how we want the process to work:
- independence: hierarchy is just here for more clarity.
- top-down : adding a user to a space, add it to all his children. idem for removing.
- bottom-up : adding a user to space add it to all his ancestor. removing here is unclear. maybe top-down removing ?

I'm not sure there is a good strategy here. I do suggest to leave the default to independance and add top-down and bottom-up strategy as backend plugin which trigger user membership event.

**Comment by inkhey** [comment]
for role added to workspace we do not explicitly give answers, we should use the default role we discussed in https://github.com/tracim/tracim/issues/3538, need some clarification if it's space specific or not, but that seems the more logical approach that deciding that if we are admin in a subspace we should be admin in parent too.

**Comment by grignards** [comment]
> I do see 3 potential behavior depending on how we want the process to work:
> 
>     * independence: hierarchy is just here for more clarity.
> 
>     * top-down : adding a user to a space, add it to all his children. idem for removing.
> 
>     * bottom-up : adding a user to space add it to all his ancestor. removing here is unclear. maybe top-down removing ?
> 
> 
> I'm not sure there is a good strategy here. I do suggest to leave the default to independance and add top-down and bottom-up strategy as backend plugin which trigger user membership event.

Yes these are the three main possibilities. Our current client likes/wants the third one.
I'm also for having the implementation of a access-rule behavior cleanly separated to allow other rules to be defined.
What I'm unsure of is which default rules should Tracim have.

**Comment by grignards** [comment]
After the discussion yesterday:
- by default there will be no link between members of sub-spaces
- a specific behavior will be implemented to handle the "bottom-up" behavior

This issue will become the issue for implementing this specific behavior.

**Comment by raphj** [comment]
If the "To be discussed before development" is still current, here is my take:
 - a member added to a space should always get the default roles set for this space regardless of how they were added, so things are simple to understand
 - removing a user's membership from a space should not remove this user from other spaces because this is complicated to reason about and might be unexpected (people can forget if a user was explicitly added to a space or if they joined by transitivity). It's also probably easier to implement this way. In a perfect world, we could also want a message that says "this users was automatically added to spaces X, Y, Z when they joined this space. Should they be removed from these spaces too?"

**Comment by lebouquetin** [comment]
This issue is not a Tracim developement but a client-specific one. To be postponed (we can deliver 3.2 without this)

**Comment by inkhey** [comment]
Some points: 

1. 
>  add user in ancestor spaces when a member is added in a sub-space

This should be a recursive mechanism.

2. Where these "internal plugins" which should not be activated by default be stored ? 
I do suggest to make things simple to:
- do not touch now to the current internal plugins mecanism at all
- put a directory of our internal plugins in tracim repository where we store these plugins, the plugin process does not check this dir (we do need to move plugin to make things work)
@grignards Do you suggest something else ? We can improve a bit the internal plugin mecanism for this but this mean a new ticket to be solve before both of the plugins code.

**Comment by inkhey** [comment]
added event to use in ticket.

**Comment by grignards** [comment]
>     1. Where these "internal plugins" which should not be activated by default be stored ?
>        I do suggest to make things simple for now:
> 
> 
>     * do not touch now to the current internal plugins mecanism at all
> 
>     * put a directory of our internal plugins in tracim repository where we store these plugins, the plugin process does not check this dir (we do need to move plugin to make things work)
>       @grignards Do you suggest something else ? We can improve a bit the internal plugin mecanism for this but this mean a new ticket to be solve before both of the plugins code.

I agree, I had the same idea to keep things as simple as possible for now.

**Comment by inkhey** [comment]
Which role are members of sub-spaces given?
-> i do agree with @grignards  to use default role

if yes, does the opposite (removing the user from a sub-space) remove the user from "ancestor" spaces (if added automatically)?
-> i do agree with @grignards  to be not recursive here for a first step.

**Comment by raphj** [comment]
We could store the info that a user has been added automatically in the database and not use this knowledge for now.

**Comment by lebouquetin** [comment]
After discussion our talk about recursivity... even if we decide to go for recursivity in remove member operation, I'd say this could be a frontend feature, not backend feature. This will "make the job" without to require both frontend and backend developments.

Anyway, as discussed today, we do not delete recursively at the moment.

**Comment by raphj** [comment]
tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
