### ISSUE TITLE
Bug: Missing tooltips in the Notification Wall buttons and icons

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3575]
## Description and expectations

Some buttons and icons on the notification wall may be hard to understand on small interfaces, it would be good to add a tooltip on them. Also, tooltips are a great way to improve Tracim accessibility.

Add tooltip at:
- [ ] See more button
- [ ] Close button
- [ ] Mark all as read button
- [ ] Notification type icons

### Version information

- Tracim version: v.3.1.0
- Web browser: any
- Device / System: PC

Icon example:
![Screenshot_2020-09-14 (17) Accueil · Algoo(1)](https://user-images.githubusercontent.com/25848257/93101081-255dd100-f6aa-11ea-8b78-fb7dedb98f7d.png)
________________________________________________

## To be discussed before development 
- Should we add required tooltips at the generic button components?

## Prerequisites
None

**Comment by lebouquetin** [comment]
@gbonaspetti In order to *never* miss a tooltip, I suggest to have a `Icon` component which requires a title description. Otherwise, we will keep on inserting new icons without title. Do you agree? If not, what do you suggest?

**Comment by gbonaspetti** [comment]
> @gbonaspetti In order to _never_ miss a tooltip, I suggest to have a `Icon` component which requires a title description. Otherwise, we will keep on inserting new icons without title. Do you agree? If not, what do you suggest?

I agree and I had put in the `To be discussed` of this ticket the same suggestion for the butons.

**Comment by PhilippeAccorsi** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
I move to "in progress" because fix is not merge yet.

**Comment by PhilippeAccorsi** [comment]
Done.
