### ISSUE TITLE
Feat: Add the access type, parent and default user role of space in the new space popup

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3577]
## Feature description and goals

The space access type (see #3536), parent space (see #3546) and default user role (see #3601) are new parameters needed for creating a space through the "Create shared space" button found in the sidebar and app admin_workspace_user.

- [x] The new popup will be in two steps and it shall have the following interface (with some different details, like the icons, and the public space will not be implemented now) :

<img width="278" alt="popup_new_space" src="https://user-images.githubusercontent.com/35422692/94658966-dc418a00-0303-11eb-91e7-9f4674d82fc3.png">

~- [x] In a confidential space, it can only be create confidential spaces, in a space on demand it can only be create confidential spaces and on demand.~

- [x] When the "Create" button is pressed, the additional parameters shall be given to the backend as described in #3536 and #3546.

- [x] If the selected parent leads to have more than 2 child levels (root-parent-child), display a warning to the user

- [x] The create space popup should filter its list with the values returned in `/api/system/workspace_access_types` (see https://github.com/tracim/tracim/issues/3602).

## Prerequisites

- #3536 (merged)
- #3546 (merged)

## Translations

|English|French|Portuguese|
|--|--|--|
|New space|Nouvel espace|Novo espaço|
|Space's name|Nom de l'espace|Nome do espaço|
|Space's type|Type de l'espace|Tipo do espaço|
|Open|Ouvert|Aberto|
|On Request|Sur demande|A pedido|
|Confidential|Confidentiel|Confidencial|
|Parent space|Espace parent|Espaço pai|
|None|Aucun|Nenhum|
|Default role|Rôle par défaut|Função predefinida|
|Any user will be able to see, join and open this space.|Tout utilisateur pourra voir, rejoindre et ouvrir cet espace.|Qualquer utilizador poderá ver, juntar-se e abrir este espaço.|
|Any user will be able to see and send a request to join this space, the space managers will be able to accept/reject requests.|Tout utilisateur pourra voir et envoyer une demande pour rejoindre cet espace, les responsables de l'espace pourront accepter/rejeter les demandes.|Qualquer utilizador poderá ver e enviar um pedido de acesso a este espaço, os gestores do espaço poderão aceitar/rejeitar pedidos.|
|Only invited users will be able to see and open this space, invitation is sent by space managers.|Seuls les utilisateurs invités pourront voir et ouvrir cet espace, l'invitation est envoyée par les responsables de l'espace.|Apenas os utilizadores convidados poderão ver e abrir este espaço, o convite é enviado por gestores de espaço.|
|Be careful, we do not recommend creating more than two levels of spaces because it makes the information much less accessible.|Attention, nous ne recommandons pas de créer plus de deux niveaux d'espaces car cela rend l'information beaucoup moins accessible.|Tenha cuidado, não recomendamos a criação de mais de dois níveis de espaços porque torna a informação muito menos acessível.|

### Find the right icons for the access types

_2020-09-29_ **Decision**: The second option in the table https://github.com/tracim/tracim/issues/3577#issuecomment-694736121

### Are there defaults for space type and default role? If yes which ones?

_2020-10-05_ **Decision**: No, the button  is disabled if the user doesn't choose a type.

### Which interface for the default user role? In other places roles are displayed as exclusive check boxes, is this advisable here?

_2020-09-30_ **Decision**: Radio buttons as in "Add member" interaction (see interface at description)

### Finalize descriptions of access types

Some suggestions:
- Open space: 
    - Visible and open space for any user to join/become a member.
    - Open space for any user to join/become a member.
    - Any user will be able to see, open and join this space.
- On request space:
    - Visible space for any user to request to join/become a member.
    - Any user will be able to see and send a request to join this space.
- Confidential space: 
    - Non-visible space that the user will join/be a member only if invited.
    - Space that the user will only join/be a member if invited.
    - Only invited users will be able to see and join this space.

_2020-09-30_ **Decision**: https://github.com/tracim/tracim/issues/3577#issuecomment-701308868

### Find warning text when too many child levels

Some suggestions: 
- Be careful, you may have interface problems if you make many levels of subspaces. We recommend a maximum of 2.
- Attention, this space will be too nested. We recommend a maximum nesting level of 2 too avoid display issues. To solve this problem, pick a parent space that is less nested.
- Warning, multiplying the number of levels makes the information much less accessible. We suggest not to exceed 2 levels of depth.
- Be careful, having many spaces inside is not very accessible. We recommend having at most one parent and one child space.
- Be careful, too many levels makes the information less accessible and can cause problems of visualization of this space in the sidebar. We recommend having at most one parent for each child space.
- Be careful, too many levels makes the information less accessible and can cause problems of visualization of this space in the sidebar. We recommend using simple parent-child tree without any grandson.
- We do not recommend creating more than two levels of spaces because it makes finding information more complex.

_2020-10-08_ **Decision**: :warning: Be careful, we do not recommend creating more than two levels of spaces because it makes the information much less accessible. (see https://github.com/tracim/tracim/issues/3577#issuecomment-705402964)

## Implementation details and decisions 
- Keep the existing popup icon of creating a space.
- Elements in first step: name and type.
- Elements in second step: parent and role.
- Add a "back" button (Back/Retour/Voltar).
- The size of the popup is a little bigger than before, because we have a lot more content and we didn't want a scroll.
- The popup is a 100% of the screen in extra-small screens.
- Add a icon at "next" button.

**Comment by raphj** [comment]
> Find warning text when too many child levels

Suggestion: grey out spaces which cannot be parent in the select box to avoid an error message.
In the select box, we should find a text that means "already at the maximum level of nesting".

Or would it be easier to allow creating child spaces from parent spaces instead of picking a parent space when creating a new space?

**Comment by gbonaspetti** [comment]
> > Find warning text when too many child levels
> 
> Suggestion: grey out spaces which cannot be parent in the select box to avoid an error message.
> In the select box, we should find a text that means "already at the maximum level of nesting".
> 
> Or would it be easier to allow creating child spaces from parent spaces instead of picking a parent space when creating a new space?

The idea is allow the creation but with a warning like "Attention: You are creating many levels within your space, this can make it illisible in the sidebar."

**Comment by gbonaspetti** [comment]
> Find the right icons for the access types

@lebouquetin @grignards Some ideas:

||1|2|3|4|
|-|-|-|-|-|
|**Confidential**|[user-secret](https://fontawesome.com/v4.7.0/icon/user-secret)|user-secret|[shield](https://fontawesome.com/v4.7.0/icon/shield)|[lock](https://fontawesome.com/v4.7.0/icon/lock)|
|**On request**|[home](https://fontawesome.com/v4.7.0/icon/home)|[handshake-o](https://fontawesome.com/v4.7.0/icon/handshake-o)|lock|[arrow-circle-right](https://fontawesome.com/v4.7.0/icon/arrow-circle-o-right)|
|**Open**|[building-o](https://fontawesome.com/v4.7.0/icon/building-o)|[sun-o](https://fontawesome.com/v4.7.0/icon/sun-o)|[unlock](https://fontawesome.com/v4.7.0/icon/unlock)|[hashtag](https://fontawesome.com/v4.7.0/icon/hashtag)|
|**Public**|[globe](https://fontawesome.com/v4.7.0/icon/globe)|globe|[key](https://fontawesome.com/v4.7.0/icon/key)|[circle-thin](https://fontawesome.com/v4.7.0/icon/circle-thin)|

The 1 is more a geographic grow (from people to world), the 2 I tried to think in a collaboration idea, the 3 is more linked to security and the 4 is based in the names/social networks. Of course this are just ideas and the icons can be mixed.

**Comment by inkhey** [comment]
> > Find the right icons for the access types
> 
> @lebouquetin @grignards Some ideas:
> 	1 	2 	3 	4
> **Confidential** 	[user-secret](https://fontawesome.com/v4.7.0/icon/user-secret) 	user-secret 	[shield](https://fontawesome.com/v4.7.0/icon/shield) 	[lock](https://fontawesome.com/v4.7.0/icon/lock)
> **On request** 	[home](https://fontawesome.com/v4.7.0/icon/home) 	[handshake-o](https://fontawesome.com/v4.7.0/icon/handshake-o) 	lock 	[arrow-circle-right](https://fontawesome.com/v4.7.0/icon/arrow-circle-o-right)
> **Open** 	[building-o](https://fontawesome.com/v4.7.0/icon/building-o) 	[sun-o](https://fontawesome.com/v4.7.0/icon/sun-o) 	[unlock](https://fontawesome.com/v4.7.0/icon/unlock) 	[hashtag](https://fontawesome.com/v4.7.0/icon/hashtag)
> **Public** 	[globe](https://fontawesome.com/v4.7.0/icon/globe) 	globe 	[key](https://fontawesome.com/v4.7.0/icon/key) 	[circle-thin](https://fontawesome.com/v4.7.0/icon/circle-thin)
> 
> The 1 is more a geographic grow (from people to world), the 2 I tried to think in a collaboration idea, the 3 is more linked to security and the 4 is based in the names/social networks. Of course this are just ideas and the icons can be mixed.

What is the difference between public and open ?

**Comment by gbonaspetti** [comment]
> > > Find the right icons for the access types
> > 
> > 
> > @lebouquetin @grignards Some ideas:
> > 1 	2 	3 	4
> > **Confidential** 	[user-secret](https://fontawesome.com/v4.7.0/icon/user-secret) 	user-secret 	[shield](https://fontawesome.com/v4.7.0/icon/shield) 	[lock](https://fontawesome.com/v4.7.0/icon/lock)
> > **On request** 	[home](https://fontawesome.com/v4.7.0/icon/home) 	[handshake-o](https://fontawesome.com/v4.7.0/icon/handshake-o) 	lock 	[arrow-circle-right](https://fontawesome.com/v4.7.0/icon/arrow-circle-o-right)
> > **Open** 	[building-o](https://fontawesome.com/v4.7.0/icon/building-o) 	[sun-o](https://fontawesome.com/v4.7.0/icon/sun-o) 	[unlock](https://fontawesome.com/v4.7.0/icon/unlock) 	[hashtag](https://fontawesome.com/v4.7.0/icon/hashtag)
> > **Public** 	[globe](https://fontawesome.com/v4.7.0/icon/globe) 	globe 	[key](https://fontawesome.com/v4.7.0/icon/key) 	[circle-thin](https://fontawesome.com/v4.7.0/icon/circle-thin)
> > The 1 is more a geographic grow (from people to world), the 2 I tried to think in a collaboration idea, the 3 is more linked to security and the 4 is based in the names/social networks. Of course this are just ideas and the icons can be mixed.
> 
> What is the difference between public and open ?

In a public space the content is accessible by people that don't have a Tracim account. It won't be implemented now, but I thought it was important to have this type in mind to make the decision.

**Comment by inkhey** [comment]
i do suggest:

| type         | icon                          |
|--------------|-------------------------------|
| confidential | user-secret                   |
| on_request   | arrow-circle-right  (no sure) |
| open         | circle-thin                   |
| public       | globe                         |

**Comment by lebouquetin** [comment]
@gbonaspetti I think the 2 is the most explicit about how it works

**Comment by celiamgtt** [comment]
@gbonaspetti 2 is interesting but I don't think the Open one (sun-o) is explicit enough.

**Comment by celiamgtt** [comment]
> Which interface for the default user role?
> In other places roles are displayed as exclusive check boxes, is this advisable here?

Proposal: 
![popup_new_space_default_role](https://user-images.githubusercontent.com/50453784/94153543-32827900-fe7d-11ea-87f4-b8cc88a1170e.png)

**Comment by gbonaspetti** [comment]
> @gbonaspetti 2 is interesting but I don't think the Open one (sun-o) is explicit enough.
> 
> I think the different type of locks were more explicit through the interface.
> 
> Solution 2:
> [...]
> 
> Current design:
> [...]

Yes, maybe the solution 3 that has the two locks...

**Comment by grignards** [comment]
> > Which interface for the default user role?
> > In other places roles are displayed as exclusive check boxes, is this advisable here?
> 
> Proposal:

I think the second one is better visually, even if different from other places where we set roles. Just a remark: the default value in this case should be `reader`.

**Comment by gbonaspetti** [comment]
> > > Which interface for the default user role?
> > > In other places roles are displayed as exclusive check boxes, is this advisable here?
> > 
> > 
> > Proposal:
> 
> I think the second one is better visually, even if different from other places where we set roles. Just a remark: the default value in this case should be `reader`.

We can use the same interface that we have at Dashboard Advanced.

**Comment by lebouquetin** [comment]
@celiamgtt when I talked to the client, it appears that different locks let him understand that they are related to differents state of the same space, which is not the case.

Could you make a screen of the [creation popup](https://user-images.githubusercontent.com/51887114/93103021-6525b800-f6ac-11ea-8e90-2267403cde82.png) with 4 icons proposed by @gbonaspetti in her proposal #2 (browser, sun-o, handshake and spy)?

In your proposal for default role through a select field (the second one), how will show the proposals when select is displayed? Will we have the description of the roles like we do in the first?

Could you also make the first popup with default role selection on a second column? (in order to have a popup designed on two columns?)

**Comment by celiamgtt** [comment]
Creation popup with prosonal n02 :
![popup_new_space (1)](https://user-images.githubusercontent.com/50453784/94431254-543d7200-0195-11eb-8e10-2b20db4ac91f.png)

Like @gbonaspetti said, we could use the same dropdown as advanced dashboard. I don't think the roles should be explain here.
![Capture du 2020-09-28 14-04-21](https://user-images.githubusercontent.com/50453784/94431353-7636f480-0195-11eb-8a92-10de29bb9cdc.png)

Popup with 2 columns (I don't think it's a good idea): 
![popup_new_space (2)](https://user-images.githubusercontent.com/50453784/94431485-a4b4cf80-0195-11eb-8af5-a1ae3b19154c.png)

**Comment by raphj** [comment]
I'd go with prosonal n02

**Comment by raphj** [comment]
Suggestions for the wordings:

Warning:

Attention: this space will be too nested. We recommend a maximum  nesting level of 3 too avoid display issues. To solve this issue, pick a parent space that is less nested"

- Open space: Any user will be able to see, open and join this space.
- On request space: Any user will be able to see and send a request to join this space
- Confidential space: Only invited users will be able to see and join this space

**Comment by gbonaspetti** [comment]
> Suggestions for the wordings:
> 
> Warning:
> 
> Attention: this space will be too nested. We recommend a maximum nesting level of 3 too avoid display issues. To solve this problem, pick a parent space that is less nested"
> 
> * Open space: Any user will be able to see, open and join this space.
> * On request space: Any user will be able to see and send a request to join this space
> * Confidential space: Only invited users will be able to see and join this space

I added your suggestions at the description.

**Comment by inkhey** [comment]
I'm not sure it a good idea to make both parent space and default role too much accessible, as these are "complex" feature.
It's just a suggestion, but what about a "change" button that allow us to change the value instead of directly showing a dropdown list ?

**Comment by lebouquetin** [comment]
@gbonaspetti 

My feeling is reading the description would make the creator dirtectly understand how the sapce will behave. So:

- **Open space**: 
    - Any user will be able to see, join and open this space.
- **On request space**:
    - Any user will be able to see and send a request to join this space, the space managers will be able to accept/reject requests.
- **Confidential space**: 
    - Only invited users will be able to see and open this space, invitation is sent by space managers.

**Comment by lebouquetin** [comment]
About the "too many space levels"' warning: the reason for suggesting not to create more than 3 levels is not about interface but about user experience.

I suggest: ⚠️ Attention : multiplier le nombre de niveaux rend l'information nettement moins accessible. Nous vous suggérons de ne pas dépasser 2 niveaux de profondeur.

(lets translate it in English).

Note : I think 2 levels is already enough for 99,9% cases, actually.

**Comment by celiamgtt** [comment]
> I'm not sure it a good idea to make ~both~ parent space ~and default role~ too much accessible, as ~these are~ this is a "complex" feature.
> It's just a suggestion, but what about a "change" button that allow us to change the value instead of directly showing a dropdown list ?

For me 'default role' is a complex feature, but it's interesting to create a sub-space directly at the right place

**Comment by gbonaspetti** [comment]
> About the "too many space levels"' warning: the reason for suggesting not to create more than 3 levels is not about interface but about user experience.
> 
> I suggest:  Attention : multiplier le nombre de niveaux rend l'information nettement moins accessible. Nous vous suggérons de ne pas dépasser 2 niveaux de profondeur.
> 
> (lets translate it in English).
> 
> Note : I think 2 levels is already enough for 99,9% cases, actually.

@lebouquetin in this idea I suggest "Be careful, having many spaces inside is not very accessible. We recommend having at most one parent and one child space." or "Be careful, having many spaces inside is not very accessible. We recommend having at most one grandparent, one parent and one child space."

**Comment by gbonaspetti** [comment]
> Find warning text when too many child levels

After getting in touch with some people of different ages and different levels of knowledge with technology, the two phrases that were clearer to the user were:

- Be careful, multiplying the number of levels makes the information much less accessible. We suggest not to exceed two levels of depth.
- We do not recommend creating more than two levels of spaces because it makes finding information more complex.

So, I decided to go with `Be careful, we do not recommend creating more than two levels of spaces because it makes the information much less accessible.`

Reasons:
- "Be careful" shows a care with the user.
- Having the recommendation right after that makes the user quickly understand the problem and don't need to read until the end of the sentence for that.
- And lastly we have the explanation, where I preferred to talk about accessibility than "finding the information" because it is a bit more extensive.

**Comment by PhilippeAccorsi** [comment]
Done.
