### ISSUE TITLE
Bug: mentions that are a suffix of a mention that should concern me are highlighted

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3580]
## Description and expectations

The highlighting of mentions for the connected user (including the group mentions) continues if there are characters after this mention. In other words, mentions that are a suffix of a mention that should concern the logged user are highlighted.

### Version information

- Tracim version: v3.1.0
- Web browser: any
- Device / System: at least PC

## Screenshots

![Capture d’écran de 2020-09-14 17-22-29](https://user-images.githubusercontent.com/35422692/93105500-72907180-f6af-11ea-9e52-91dd202f8385.png)

________________________________________________

**Comment by PhilippeAccorsi** [comment]
Manually tested on branch.
