### ISSUE TITLE
Feat: Change "shared space" to "space"

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3582]
## Feature description and goals

The idea of changing the name from **shared space** to **space** is that it is smaller, simpler and in the idea of Tracim we shouldn't have un-shared spaces, so the term shared space can even be considered redundant.

To do:
 - [x] change "workspace" and "shared space" to "space" everywhere in the UI (just the displayed interface, not the code)
 - [x] change "workspace" and "shared space" to "space" in the notification by email
## Translations

|English|French|Portuguese|
|--|--|--|
|Space|Espace|Espaço|

**Comment by grignards** [comment]
@gbonaspetti Do you mean "update all user-displayed string" do you imply to also modify the code (workspace is everywhere in it)?

**Comment by gbonaspetti** [comment]
> @gbonaspetti Do you mean "update all user-displayed string" do you imply to also modify the code (workspace is everywhere in it)?

Not the code, for now. I update the description to be clearer.

**Comment by raphj** [comment]
tested on branch.

**Comment by PhilippeAccorsi** [comment]
@gbonaspetti I can seen here that we change name shared space to space in frontend ui, but I can seen in code that warning/error messages is not change. Is it normal ? or its a mistake ?

In this file for example `frontend_app_folder_advanced/dist/app/agenda_en_translation.json`

**Comment by PhilippeAccorsi** [comment]
> @gbonaspetti I can seen here that we change name shared space to space in frontend ui, but I can seen in code that warning/error messages is not change. Is it normal ? or its a mistake ?
> 
> In this file for example `frontend_app_folder_advanced/dist/app/agenda_en_translation.json`

j'ai peur que les utilisateurs ne comprennent plus les messages d'erreur.

**Comment by PhilippeAccorsi** [comment]
Maybe an issue exist for a 3.2.1 or something like that ?

**Comment by PhilippeAccorsi** [comment]
Tested on unstable.tracim.fr

**Comment by PhilippeAccorsi** [comment]
Reopen and need more test when all other issue are merged.

**Comment by PhilippeAccorsi** [comment]
After discuss about release 3.2.0, will not do integration phase for this release.
Done.
