### ISSUE TITLE
Feat: Replace and filter the collapse menu with a dropdown menu at sidebar

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3584]
## Feature description and goals

Currently, the sidebar has a collapse menu with [Dashboard, All contents, Threads, Files, Text Documents, Agenda and Gallery]. To ease the implementation of the sidebar with child spaces (therefore a tree representation, see #3579), this menu should be turned into a drop-down menu (see interface example).
In addition we saw that the content type shortcuts are seldom used, so they should be removed from the menu as well as the Dashboard (see https://github.com/tracim/tracim/issues/3627).

## Expected
- [x] Replace collapse menu to a drop-down menu
- [x] The button to see this menu only shows when the space item is in hover
- [x] Updates all others drop-down menus to use the same React Component

## Interface example

![Capture d’écran de 2020-09-15 11-15-03](https://user-images.githubusercontent.com/35422692/93191778-3576be80-f745-11ea-8aab-32eb4480913b.png)
_Obs: this interface it's just a model. Things like "Create a subspace" and "Leave this space" will not be implemented at this issue._

##  Discussed before development

The drop-down menu should not be specific. Should it be a frontend_lib component that could be use in all Tracim or should we use Bootstrap dropdown-menu (as we do for the menus at header)?

_18-09-2020_ Decision: https://github.com/tracim/tracim/issues/3584#issuecomment-692611671 As we will create a specific component for the Dropdown menu, all other menus of the same type will use this component.

**Comment by grignards** [comment]
> Should it be a frontend_lib component that could be use in all Tracim or should we use Bootstrap dropdown-menu (as we do for the menus at header)?

My first thought would be to use the same thing as the header's menus, do you see cons to this approach?

**Comment by raphj** [comment]
> Should it be a frontend_lib component that could be use in all Tracim or should we use Bootstrap dropdown-menu (as we do for the menus at header)?

Is this exclusive?

**Comment by gbonaspetti** [comment]
> > Should it be a frontend_lib component that could be use in all Tracim or should we use Bootstrap dropdown-menu (as we do for the menus at header)?
> 
> My first thought would be to use the same thing as the header's menus, do you see cons to this approach?
> ...
> Is this mutually exclusive?

I don`t have any cons, we don`t use Bootstrap a lot, so I was wondering if it was not the time to have a menu of our own... But they are not mutually exclusive, we can make a frontend_lib component that use Bootstrap.

**Comment by inkhey** [comment]
> In addition we saw that the content type shortcuts are seldom used, so they should be removed from the menu as well as the Dashboard.

How do you expect to do this as this is the backend that return the list of sidebar endpoints ?

**Comment by lebouquetin** [comment]
@inkhey I think the backend must return the right list of items for the sidebar. I don't know if it should be hard-written or dynamically build or a mix of both but:

- the future is to make this shortcuts parametric
- the backend should return the right menu items list

**Comment by lebouquetin** [comment]
@gbonaspetti for the contextual menu I think what we should do is:

- a tracim component which is a list of items (icon + translatable label + associated url)
- make this component based on bootstrap

In the future, if we need specialized rendering, we'll "break" bootstrap design, but for now it's enough.

@grignards @raphj my point about that (we already had a chat with @gbonaspetti ) is to build a library of all tracim widgets in order to be able to reuse widgets with similar rendering and similar behavior

**Comment by lebouquetin** [comment]
in a pythonic view, the component would be something like:

```
class ContextualMenu(TracimWidget):
    def __init__(self, list_of_entries):
        [...]
```

where list_of_entries would be a list of MenuItem:

```
class MenuItem(TracimWidget):
    def __init__(self, label, target_url, font_awesome_icon_str="", image_path=""):
        # give font awesome string for example fa-user
        # or a png/jpeg asset path like flag/fr_fr.png
```

**Comment by gbonaspetti** [comment]
> > In addition we saw that the content type shortcuts are seldom used, so they should be removed from the menu as well as the Dashboard.
> 
> @gbonaspetti How do you expect to do this as this is the backend that return the list of sidebar endpoints ?
>
> @inkhey I think the backend must return the right list of items for the sidebar. I don't know if it should be hard-written or dynamically build or a mix of both but:
> 
> * the future is to make this shortcut list parametric (eg, it would be possible to include a raw link to something outside of tracim for example)
> * the backend should return the right menu items list (and the frontend does not "store" any kind of knowledge of what are the menu items)

I was thinking of making a `.filter` but your solution is better! @inkhey  can you create an issue for the backend part?

**Comment by lebouquetin** [comment]
(this snippet is *only* for illustrating my point)

**Comment by inkhey** [comment]
We do currently provided sidebar-entries to frontend (_WorkspaceMenuEntrySchema_) : 

description: | Entry element of a workspace menu
-- | --
fa_icon | string example: file-text-o CSS class of the icon. Example: file-o for using Fontawesome file-text-o icon
hexcolor | string example: #F0F9DC Hexadecimal color of the entry.
label | string example: Markdown Documents
route | string example: /workspace/{workspace_id}/contents/?type=mardown-page the  route is the frontend route. It may include workspace_id which must be  replaced on backend size (the route must be ready-to-use)
slug | string example: markdown-pages

**Comment by inkhey** [comment]
issue about backend change needed here : https://github.com/tracim/tracim/issues/3627

**Comment by inkhey** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
