### ISSUE TITLE
Feat: Allow user to join space

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3587]
## Feature description and goals

Users must have the option to join an **open** space and the option to ask to join an **on request** space. For this they will have a "join space" page that it's accessible by a button at the sidebar (see interface examples).

Some implementation/interface details:
- The style of the list is the same as in "All contents".

### Expected
- [x] All type icons have a tooltip with the type name
- [x] A big description should be chopped with ellipsis (...)

## Interfaces examples
_Obs: these interfaces are just a model. Things like the "Create space" button (that should have the same size of the Join button) will not be implemented in this issue._
- Sidebar button
![Capture d’écran de 2020-09-15 13-39-55](https://user-images.githubusercontent.com/35422692/93206442-b2139800-f759-11ea-9bd0-511191a85dbe.png)

- Join page
![ASF_join_space](https://user-images.githubusercontent.com/35422692/94577781-39dbc500-0277-11eb-8fb5-8cbddff986ed.png)

## Translations

|English|French|Portuguese|
|--|--|--|
|Join a space|Rejoindre un espace|Junte-se a um espaço|
|Title and description|Titre et description|Título e descrição|
|Access request|Demande d'accès|Pedido de acesso|
|Request access|Demander l'accès|Pedir acesso|
|Request sent|Demande envoyée|Pedido enviado|
|Join the space|Rejoindre l'espace|Junte-se ao espaço|
|Filter spaces|Filtrer les espaces|Filtrar espaços|
|You can join an existing space or create your first space|Vous pouvez rejoindre un espace existant ou créer votre premier espace|Você pode juntar-se a um espaço existente ou criar o seu primeiro espaço|
|You can create your first space|Vous pouvez créer votre premier espace|Você pode criar o seu primeiro espaço|
|You can join an existing space|Vous pouvez rejoindre un espace existant|Você pode juntar-se a um espaço já existente|
|Please ask access to your spaces to an administrator or space manager|Veuillez demander accès à vos espaces à un administrateur ou un gestionnaire d'espace|Por favor peça acesso aos seus espaços a um administrador ou gestor de espaço|

## Prerequisites
- https://github.com/tracim/tracim/issues/3538
- https://github.com/tracim/tracim/issues/3539

## Discussed before development 

1. The filter (search) should be done just for name or for the words in the description too?
Answer: The filtering should be on both and implemented in frontend only (https://github.com/tracim/tracim/issues/3587#issuecomment-692671610)

**Comment by lebouquetin** [comment]
@gbonaspetti note that the two buttons must have the same width for making a polished software.
The button "join a space" should be "join more spaces" or "discover more spaces" and it should allow to join:

- open spaces
- on demand spaces

And should be disabled (or disappear) if no extra space is available

**Comment by raphj** [comment]
I think spaces should be findable by searching keywords in their descriptions. Ideally, a filter should be present to search by name only, but without this feature, search on name + description seems better.

**Comment by lebouquetin** [comment]
> The filter (search) should be done just for name or for the words in the description too?

The filtering should be on both. We wont have thousands of spaces, so there won't be false positives, I think. By the way, this filtering should be implemented in frontend only for the first iteration - so changing the strategy will be easy

**Comment by gbonaspetti** [comment]
> @gbonaspetti note that the two buttons must have the same width for making a polished software.

Yes, I put a observations after interfaces title about the create button, but I'll update the description to live it more clear.

> The button "join a space" should be "join more spaces" or "discover more spaces" and it should allow to join:

"Discover spaces" maybe? I'm afraid that the button is too verbose with the _more_, but I'm open to try if you prefer. I had even proposed to let only "create" and "join" and leave the buttons on each other's side (for size reasons). 

> * open spaces
> * on demand spaces

Yes, it's at the description, but I'll try to make it clear

> And should be disabled (or disappear) if no extra space is available

I don't know if I love the idea of disable it if we are gonna show the status of the request ("demande envoyée"). Maybe add a phrase "There is no new space to discover" bellow the filter it's better in this case.

**Comment by celiamgtt** [comment]
Update with the interface wip mockup.

**Comment by celiamgtt** [comment]
```
The button "join a space" should be "join more spaces" or "discover more spaces" 
```
@lebouquetin "Join a space" is the common wording for this action, so the users are use to it. "Join more spaces" or "Discover more spaces" are too long. Some alternatives could be: "Browse spaces" like Slack (browse channels).

**Comment by raphj** [comment]
I'd go with "Join a space", or "Browse spaces" (which I like a bit less).

**Comment by lebouquetin** [comment]
"browse spaces" is more relevent with what the button give access to, but "join a space" in more the intention of the user, I think. The right wording would be "Browse and join spaces" ;)

More seriously, let's put "Join a space" and we'll change later if not clear to end-users.

**Comment by inkhey** [comment]
Just added https://github.com/tracim/tracim/issues/3662 need clarification in backend about the mecanism before working on the on_request part of this issue.

**Comment by grignards** [comment]
@gbonaspetti @celiamgtt While testing my developments I got a case we didn't think of: when a user is not part of any space the sidebar is hidden so he cannot explore/join spaces by himself.
I guess that the logical way would be to include the "Join a space" button in the default home, but what should be the text? I would propose "You aren't member of any space yet, you can join accessible spaces by yourself or refer to an administrator or a trusted user to get access". And this text/button should depend whether there are any accessible space or not (if there aren't any the button shouldn't be displayed and the text left to what it is currently).

**Comment by gbonaspetti** [comment]
> @gbonaspetti @celiamgtt While testing my developments I got a case we didn't think of: when a user is not part of any space the sidebar is hidden so he cannot explore/join spaces by himself.
> I guess that the logical way would be to include the "Join a space" button in the default home, but what should be the text? I would propose "You aren't member of any space yet, you can join accessible spaces by yourself or refer to an administrator or a trusted user to get access". And this text/button should depend whether there are any accessible space or not (if there aren't any the button shouldn't be displayed and the text left to what it is currently).

looks good for me!

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
