### ISSUE TITLE
Adapt the layout for a "main pages of the space" layout

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3589]
## Feature description and goals

We are adding an "activity feed" (issue https://github.com/tracim/tracim/issues/3600) in dashboards for spaces. The goal of this issue is to adapt the layout of the dashboard and all contents with this in mind, creating a "main page of the space" layout.

The main page of space layout will have tabs, initially with three options: all contents, activity feed and dashboard (see _Interface_ section).

### Expected

- [x] When active, the tab will have a border at the top with the primary color (see _Interface_ section) and the gray like the background color at displayed page (see _Interface_ section, _Activity feed_ item).
- [x] Tabs should be links, or at least focus-able.
- [x] The main title should be the name of the space and the icon should be the icon of its type (see #3577 to know more about the icons) with a tool-tip, since the title (implemented using the generic component frontend_lib > Layout > PageTitle) will change, all the components that use it will also change.
- [x] Add a border after the breadcrumbs
     - Implementation suggestion: a "Tabs" component that have this border, a title inside and a list of "SingleTab" components. The current layout container will accept sometimes just the title some times the "Tabs".
- [x] The All contents and Dashboard pages will not have their own title anymore and its background should be gray, the rest of the UI inside these pages should not change.
- [x] If the space is too big, it should have a Popover on click for mobile, on hover for others (see _Interface_ section, _Big title_ item)
- [x] The tab title, the breadcrumbs and the space type icon should be hidden on mobile (see _Interface_ section, _Mobile version_ item)

## Interface example
_Obs: These interface examples are only templates, not everything will be developed in this issue and some details can be changed according to the implementation._

- Dashboard
![ASF_tabs_line_dashboard](https://user-images.githubusercontent.com/35422692/98266005-0e40ae80-1f8a-11eb-854b-db51c0bfa3b9.png)

- All contents
![contents](https://user-images.githubusercontent.com/35422692/97164046-d9f71200-1781-11eb-9d1d-cc78b0090684.png)

- Activity feed
![feed](https://user-images.githubusercontent.com/35422692/97163650-3f96ce80-1781-11eb-9b0c-43c1f05f6f0b.png)

- Mobile version
![mobile_tabs_feed](https://user-images.githubusercontent.com/35422692/96267789-8984f500-0fc8-11eb-9f85-93dbf9383f44.png)

- Big title
![long_name](https://user-images.githubusercontent.com/35422692/96267890-a1f50f80-0fc8-11eb-90a0-1eea89660faf.png)

## Extra information

- In the first version, the order of the tabs will be [Dashboard, Activity Feed, All Contents] and the default page (i.e. the page activated when we click on the space name in sidebar) is the Dashboard. In the future this order/page by default will be an instance parameter.

- The Activity feed tab will not work in this issue, it'll be updated at #3600 

## Time Estimation

4 man.days

**Comment by grignards** [comment]
> Although I think it's more interesting to have the feed highlighted, I think it might be smart to put the other information first since they have a "fixed" size and the feed has a dynamic size.

I think that, from a user POV (and considering the usage on mobile phones to mainly be reading) we should put the activities first. But this raises several more questions so we could decide to postpone this to a later stage.

**Comment by raphj** [comment]
> What size should the activity feed have in relation to other information?

I think we should give it a fixed size in em (number of characters), or 100% if the screen is too small.
Maybe 85em, which seems to be almost the max width of a github comment on my screen:

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

**Comment by celiamgtt** [comment]
> What size should the activity feed have in relation to other information? Suggestion: 70-30% 
70-30% look fine for me, need to try it but I think it would be nice.

> How to adapt this screen to a mobile/small screens version?
>Although I think it's more interesting to have the feed highlighted, I think it might be smart to put the other information first since they have a "fixed" size and the feed has a dynamic size.
Yes, in this case the feed part is the most important. We could have a button opening a slider/drawer with the 'dashboard' section. Mobile mockup is in wip. I'm also working on a solution with a clear distinction between dashboard, activity feed and contents.

**Comment by raphj** [comment]
> Implementation suggestion: a "Tabs" component that have this border, a title inside and a list of "SingleTab" components. The current layout container will accept sometimes just the title some times the "Tabs".

I think we should avoid plurals in component or variable names in the tracim frontend: the convention is to use List instead.

I suggest TabBar / Tab or TabList / Tab. ("Single" seems unnecessary)

**Comment by gbonaspetti** [comment]
> > Implementation suggestion: a "Tabs" component that have this border, a title inside and a list of "SingleTab" components. The current layout container will accept sometimes just the title some times the "Tabs".
> 
> I think we should avoid plurals in component or variable names in the tracim frontend: the convention is to use List instead.
> 
> I suggest TabBar / Tab or TabList / Tab. ("Single" seems unnecessary)

Yes, sorry, the names aren't "to be followed", they were just to represented the main idea. I like "PageTab" to match "PageTitle" and maybe "PageTabNavigation". 
(I'm not too sure about the last one)

**Comment by grignards** [comment]
Tested on branch.

**Comment by lebouquetin** [comment]
> I think that, from a user POV (and considering the usage on mobile phones to mainly be reading) we should put the activities first. But this raises several more questions so we could decide to postpone this to a later stage.

I'm not sure about what has been implemented; on a conceptual point of view, the dashboard is the home of a space, so putting "activities" on the left is not coherent with the left to right way of reading (you start with a more specific content) 

In terms of "which tab should be open when clicking on a space", this must be configurable because activities is the expected entry point for a dynamic space while dashboard is the standard entry point for a "team" space and contents is the expected entry point for a knowledge management space.

**Comment by PhilippeAccorsi** [comment]
@gbonaspetti everything its ok with last comment write by @lebouquetin ?

**Comment by gbonaspetti** [comment]
> @gbonaspetti everything its ok with last comment write by @lebouquetin ?

Yes, he answered a comment regarding an old version, when there were no tabs yet. What is implemented is what is in the issue description.

**Comment by PhilippeAccorsi** [comment]
Thanks for your answer.
Done.
