### ISSUE TITLE
Calendar not working "out of the box"

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#359]
Current status: when installing tracim step by step, the installation succeeds. Unfortunately, after being logged in, a click to the "calendar" button results in a blank page (url is: http://localhost:8080/calendar)

Expected: the calendar must work out-of-the-box. It is probably a wrong default configuration.

**Comment by algooapy** [comment]
Does the error in JS console matches this one:
```
TypeError: localization[globalInterfaceLanguage] is undefined
main.js:109:29
```
This may be a front end issue impacting more than calendar page but also folder creation and logout dropdown button.

**Comment by xandercagexxx** [comment]
Test with new installation, is working good.
Verified.
