### ISSUE TITLE
Chore: Refactor functions used to talk to the API in the frontend 

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3596]
_Context: a fix for Tracim 3.1.1 (#3518) ended up as an unattended large refactor that should not be merged in Tracim 3.1.1. We are targeting this refactor to Tracim 3.2 instead._
   
A lot of duplication in the frontend related to the communication with the backend have been deduplicated :
 - Duplicated functions have been put in frontend lib instead of being copy pasted in each app
 - Duplicated functionality (header handling) in each of the function talking to the API have been put in a base function that handles the fetch

This may also allow handling errors in a single place in the code later.

Note: the refactor contains the fix for #3518.

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
