### ISSUE TITLE
Feat: Display subscription notifications

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3599]
## Feature description and goals

The `ON_REQUEST` spaces will allow a user to request membership by themself (see #3539). As the user and space managers will want to be informed of the new/changed subscriptions the backend will create and send TLMs for those events.

The TLMs have to be displayed in the notification panel:

### For the user who created the subscription

- [x]  `workspace_subscription.created` TLMs: are not displayed
- [x] `workspace_subscription.modified` TLMs: "{author name} granted access to {space name}", clicking on the subscription should go to the space if the subscription state in the TLM is `ACCEPTED`. Otherwise it should open the "My subscriptions" page.

### For other users who get the TLMs (content managers/administrators)

- [x] `workspace_subscription.created` TLMs: "{author name}" requested access to {space name}", clicking on the subscription should open the space advanced dashboard and display the space subscription tab.
- [x] `workspace_subscription.modified` TLMs when state is `ACCEPTED`: "{author name} granted access to {workspace name} for {user name}", clicking on the subscription should open the space advanced dashboard and display the space subscription tab. This notification is not displayed to its author.
- [x] `workspace_subscription.modified` TLMs when state is `REJECTED`: "{author name} rejected access to {workspace name} for {user name}", clicking on the subscription should open the space advanced dashboard and display the space subscription tab. This notification is not displayed to its author.

## Prerequisites

- #3539 

## Icons and translation strings

Icon |English|French|Portuguese|
|--|--|--|--|
| fa-check |{{author}} granted you access to {{space}}| {{author}} vous a permis l'accès à {{space}}|{{author}} concedeu-lhe acesso a {{space}}|
| fa-sign-in |{{author}} requested access to {{space}}|{{author}} a demandé l'accès à {{space}}|{{author}} solicitou acesso a {{space}}|
|fa-times|{{author}} rejected access to {{space}}|{{author}} a refusé l'accès à {{space}}|{{author}} rejeitou o acesso a {{space}}|

**Comment by raphj** [comment]
Should be display the "you requested access to {{space}}" though?

We are currently hiding actions from the user in the notification wall. I feel like we should avoid creating notifications when possible. For me, notification are here to notify users about actions they weren't aware of.

If we want to confirm to the user they requested an access, we could as well show a flash message.

**Comment by grignards** [comment]
> Should be display the "you requested access to {{space}}" though?
> 
> We are currently hiding actions from the user in the notification wall. I feel like we should avoid creating notifications when possible. For me, notification are here to notify users about actions they weren't aware of.
> 
> If we want to confirm to the user they requested an access, we could as well show a flash message.

You're right, I will remove this.

**Comment by raphj** [comment]
Which icons should we use?

**Comment by celiamgtt** [comment]
The 'log-in' icon ?
![image](https://user-images.githubusercontent.com/50453784/96266583-17f87700-0fc7-11eb-9fc2-3eac8432b8a3.png)

**Comment by gbonaspetti** [comment]
> Which icons should we use?

granted - fa-check
rejected - fa-times
requested - fa-sing-in

**Comment by raphj** [comment]
Should we use a ComposedIcon with the log-in icon suggested by @celiamgtt with the icons that @gbonaspetti suggests?

**Comment by celiamgtt** [comment]
I don't think that the composed icons are a good idea in general, it's too complicated to understand.

**Comment by raphj** [comment]
Okay :-)
Thanks

**Comment by gbonaspetti** [comment]
> Should we use a ComposedIcon with the log-in icon suggested by @celiamgtt with the icons that @gbonaspetti suggests?

Normally I like the idea, but it should be tested, I'm also think that in this case can be difficult to understand.

**Comment by celiamgtt** [comment]
We can go for the Giulia's proposal it's fine for me :)

**Comment by grignards** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
