### ISSUE TITLE
Feat: Add an activity feed by space

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3600]
## Feature description and goals

An activity feed will be added at the main pages of the space. The TLMs that will be activities, in a first time, will be the same as in the wall of notifications. The components made here will also be used in the personal activity feed.

### Expected

- [x] The contents will be ordered by last modification date, i. e. each time a content is updated it is shown at the top of the feed (comments included). The contents already displayed do not change order, unless the screen is refreshed, but the contents not displayed are added above in the thread.
- [x] We will have a "Update" button at the top of the feed to update the order of the page.
- [x] The last change type and date in right-top corner (see _Interface_ section, _Content details_ item) shall be updated when a change is made (real-time update).
- If the user clicks:
    - [x] on the content name, the "Comment" button or on the number+icon at its side, it must be redirected to the content app.
    - [x] on the breadcrumbs, it must be redirected to the right place (use the existing version, it will be improved in https://github.com/tracim/tracim/issues/3809)
- [x] If the content name is too big its overflow should be hidden with ellipsis (always with a tooltip).
- [x] Tooltips are required for the type of content, the date and all clickable zones.
- [x] The number of comments should be update for each new comment (real-time update).
- [x] The pagination behavior will stay the same (the last 15 new activities are displayed and at the bottom will have a "See more" button that show 15 more each time that the user clicks on it).
- [x] In the mobile view, the modification type and the breadcrumbs shall be hidden.
- [x] The date should be in friendly form ("2 days ago"), with a tooltip with the normal date (to be consistent with the rest of the Tracim UI). Make a `Date.jsx` component.
- [x] The public name of the last person who made the change is displayed.
- [x] The content type icon should have the type color and for member's and subscription request's activities it should be the user's avatar instead an icon.

**List of possible activities (and its modifications):**
- Activities about members :
     - New member (TLM workspace_member.created) 
     - Modified member (only for managers and specific member - TLM workspace_member.modified)
- Activities on contents (discussion / file / note / folder) :
     - Content created (TLM content. [file/html-document/thread/folder.]created)
     - Content modified (TLM content.[file/html-document/thread/folder.]modified)
     - Status modified (TLM content. [file/html-document/thread/folder.]modified) 
     - Commented content (TLM content.comment.created)
     - Mentioned (TLM mention.created) - "mention made ... by ..."
     - Reaction - "reaction made there ... by ..." (not implemented at this issue)
     - Content deleted (TLM content.[file/html-document/thread/folder.]deleted)
     - Content restored (TLM content.(file/html-document/thread/folder.)undeleted)
- Activities on requests to join space (only for managers) :
     - New request (TLM workspace_subscription.created)
     - Request denied (TLM workspace_subscription.deleted)

**Implementation details:**
- Make a component for the icons to force the tooltip (see https://github.com/tracim/tracim/issues/3600#issuecomment-701296939)
- The "Comment" button shall be a button (to be "tab key" accessible) and shall make a buttonLink component that uses the class `.buttonLink` (this class already exists, so the developer should put this class in the file .styl of this component)

## Interface
_Obs: These interface examples are only templates, not everything will be developed in this issue and some details can be changed according to the implementation._
- Content details 
(see #3657 for different types designs)
![content](https://user-images.githubusercontent.com/35422692/98219397-3f4ebe00-1f4d-11eb-962f-a8aa95a067bf.png)

- Folder activity
![template_folder_activity](https://user-images.githubusercontent.com/35422692/98007847-28e11f00-1df4-11eb-9dbc-eff99cc24944.png)

- Member activity
![template_member_activity](https://user-images.githubusercontent.com/35422692/98007978-4dd59200-1df4-11eb-94f2-cda6e70a2c12.png)

- Subscription request activity
![template_subscription_request](https://user-images.githubusercontent.com/35422692/98008022-5af28100-1df4-11eb-97d3-fb65c9ce4df8.png)

- Activity feed
![activity_feed_by_space](https://user-images.githubusercontent.com/35422692/98221214-a7060880-1f4f-11eb-8fb6-33b9e38a2d4b.png)

- Mobile view
![activity_feed_by_space_mobile](https://user-images.githubusercontent.com/35422692/98221236-aec5ad00-1f4f-11eb-85d4-9f1773a66122.png)

## Prerequisites
- #3589 

## Translations

|English|French|Portuguese|
|--|--|--|
|Activity feed|Fil d'actualités|Feed de atividades|
|Comment|Commenter|Comentar|
|{{user}} joined the space|{{user}} a rejoint l'espace|{{user}} juntou-se ao espaço|
|{{user}}'s role has been changed as {{role}}|Le rôle de {{user}} a été changé en {{role}}|O papel de {{user}} foi alterado como {{role}}|
|{{user}} wants to join the space|{{user}} souhaite rejoindre l'espace|{{user}} deseja juntar-se ao espaço|
|{{user}}'s request to join the space was rejected|La demande de {{user}} pour rejoindre l'espace a été réfusée|O pedido de {{user}} para se juntar ao espaço foi rejeitado|

## Discussed

1. Is the entire zone clickable and redirected to the content or just the content name?

_2020-09-29_ **Decision**: The white border is not clickable, but its elements are (e.g. the content's name redirects to the content). The whole preview is clickable and redirects to the element, with the exception of the black gradient in the bottom of the image. The entire black gradient area is clickable and expand/decrease the preview.

2. Will there be an action/contextual menu that can be done on the content through the feed (vertical ellipsis - three points)? If yes, what actions can be done?

_2020-09-29_ **Decision**: It will be a future improvement. It will not be developed in this issue.

3. Click on the feed preview of a file content display document preview in full screen?

_2020-09-30_ **Decision**: No, it will redirect to the content.

4. We will display all activities, Should we implement a [infinite scroll](https://scrollmagic.io/examples/advanced/infinite_scrolling.html) or a pagination?

_2020-09-30_ **Decision**: For now, we will have a pagination as in the rest of Tracim.

## Extra information
- _2020-09-28_: The emoji reactions will be developed at https://github.com/tracim/tracim/issues/3641
- _2020-09-30_: The content preview will be developed at https://github.com/tracim/tracim/issues/3657
- _2020-09-30_: The redirection to comment area in apps will be developed at https://github.com/tracim/tracim/issues/3658
- _2020-11-05_: As we do not have a public profile yet, member activities and subscription requests will not have the redirection in this issue.

### Time Estimation

5 man.days (3 man.days for the algorithm building the list and 2 man.days for the display).

**Comment by grignards** [comment]
@celiamgtt @lebouquetin How sould we represent a thread in this activity feed? A part of the thread comments?

**Comment by grignards** [comment]
@gbonaspetti In your mind, does this issue cover the implementation of the reactions/emojis?

**Comment by gbonaspetti** [comment]
> @gbonaspetti In your mind, does this issue cover the implementation of the reactions/emojis?
> I think reactions are a subject by themselves so I'd rather develop it separately.

I agree with you, I updated the description and add the issue #3641 to the project

**Comment by lebouquetin** [comment]
@gbonaspetti 

> The tooltips are required for the type of content, the date and all clickable zones.

Tooltips are *also* required for all icons (content type icon, menus, number of comments, etc)

**Comment by lebouquetin** [comment]
Note: I think we *must* use a react component like `FontawesomeIcon(fontawesome_id, translatable_label")` (we already talked about this, I dont know if its clear for all frontend developers)

Note2 : I think the link to comment zone is also another issue (it may require to touch timeline / content apps which is independant from the activity feed)

**Comment by gbonaspetti** [comment]
> Note: I think we _must_ use a react component like `FontawesomeIcon(fontawesome_id, translatable_label")` (we already talked about this, I dont know if its clear for all frontend developers)

Yes, I'm going to put this in the issue description, like that we make the component here and already start to use (even if we're not doing the refactor for that now)

> Note2 : I think the link to comment zone is also another issue (it may require to touch timeline / content apps which is independant from the activity feed)

Yes I agree! I'm gonna spit this issue. Thanks

**Comment by celiamgtt** [comment]
@grignards For the Threads, we'll display only the first message as "main content". For example:

<img width="1014" alt="Capture d’écran 2020-09-29 à 14 07 37" src="https://user-images.githubusercontent.com/50453784/94682356-1cfdcb00-0325-11eb-8781-c7113ee4a6a0.png">

**Comment by raphj** [comment]
>  The username of the last person who made the change is displayed.

What should we do if the user does not have a username?
Should we define a behavior once for all?

**Comment by gbonaspetti** [comment]
> > The username of the last person who made the change is displayed.
> 
> What should we do if the user does not have a username?
> Should we define a behavior once for all?

You are right, I chose the username because it's usually smaller, but let's use the Full name that is required, if the user has a big name we hide the overflow with `...` (always with a tooltip)

**Comment by inkhey** [comment]
A technical point to clarify here is how we generate the list of "activity" (which seems to actually be always content). There is no real problem for frontend to generate new items in the activity feed with TLM but obtain previous elements from the same source can be really tricky because:
- we can have a lot of event from the same content and we do need to show only one
- comment (and future reaction ?) mean obtaining the parent content instead of the comment itself.

One potential solution and not too costly solution may be storing in database the meaningful "last updated" value, the backend can return to frontend, a properly ordered and paginable list of truly last updated content.

**Comment by gbonaspetti** [comment]
> A technical point to clarify here is how we generate the list of "activity" (which seems to currently be always content ?). 

I updated the description: The TLMs that will be activities, in a first time, will be the same as in the wall of notifications. 

> There is no real problem for frontend to generate new items in the activity feed with TLM but obtain previous elements from the same source can be really tricky because:
> * we can have a lot of event from the same content and we do need to show only one
> * comment (and future reaction ?) mean obtaining the parent content instead of the comment itself.
> One potential solution and not too costly solution may be storing in database the meaningful "last updated" value which will be updated also when comment happened, the backend can return to frontend, a properly ordered and paginable list of truly last updated content.

I like the idea of "last updated", in a content the "modified" field does not take into account the comments made?

**Comment by grignards** [comment]
> I like the idea of "last updated", in a content the "modified" field does not take into account the comments made?

Nope, it doesn't.

This `last updated` field is an idea but there would be other ways to do part of the work in the back-end. It is feasible to write a front-end only algorithm with the default of having a non-fixed number of requests on `/api/users/<user_id>/messages` to be able to build a given number of entries in the feed.

We also have to discuss how the number of comments/reactions will be retrieved:
- two requests (`/api/contents/<content_id>/reactions` and `/api/contents/<content_id>/comments`)per feed entry (easy, restful but probably not good performance-wise)
- two requests (`/api/reactions?content_ids=x,y,z` and `/api/comments?content_ids=x,y,z`) for the whole feed
- …another solution

**Comment by grignards** [comment]
I'll start by working on the algorithm that will build the activities by requesting TLMs.

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
