### ISSUE TITLE
Feat: Add a `default_user_role` attribute to spaces

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3601]
## Feature description and goals

The `OPEN` spaces require a default role for users who become members of a space by themselves/are added automatically.
Furthermore having a default role allows the user interface to pre-select this role when a user is added.

- [x] add a `default_user_role` attribute to `Workspace`
- [x] return it in all `workspaces` APIs and make it mandatory
- [x] create a migration script that sets this column to `reader` in existing rows.
- [x] the role will be required at space creation
- [x] adapt frontend to always set default_user_role at workspace creation and update : (PUT
`/api/workspaces/{workspace_id}` and `POST /api/workspaces/)

## Implemented solution:
https://github.com/tracim/tracim/pull/3615
- `default_user_role` field as enum in workspace table, default database value to reader.
- migration script to add default_user_role field in workspace table
- `default_user_role` added to `WorkspaceSchema`
- `default_user_role` available in workspace update endpoint
- `default_user_role` mandatory in workspace creation endpoint
- adaptation of frontend to not break the ui (as `default_user_role` is mandatory)

**Comment by inkhey** [comment]
Is reader as default role for existing spaces OK?
- at database level, i do think yes, as existing workspace will be set to this, this seen to me both easier and logical.
- at api level, i don't know. should default_user_role being mandatory at workspace creation ? what should be the default in frontend ui ?

**Comment by grignards** [comment]
> > Is reader as default role for existing spaces OK?
> 
>     * at database level, i do think yes, as existing workspace will be set to this, this seem to me both easier and logical.
> 
>     * at api level, i don't know. should default_user_role being mandatory at workspace creation ? what should be the default in frontend ui ?

I added the ui point to the corresponding frontend issue #3577.
As for the API… it's a bit like the `access_type`: not having a default is "better" because the backend cannot really guess what is best, but breaks the compatibility.

**Comment by grignards** [comment]
> > > Is reader as default role for existing spaces OK?
> > 
> > 
> > ```
> > * at database level, i do think yes, as existing workspace will be set to this, this seem to me both easier and logical.
> > 
> > * at api level, i don't know. should default_user_role being mandatory at workspace creation ? what should be the default in frontend ui ?
> > ```
> 
> I added the ui point to the corresponding frontend issue #3577.
> As for the API… it's a bit like the `access_type`: not having a default is "better" because the backend cannot really guess what is best, but breaks the compatibility.

So I would propose to do the same: enforce it in the API + a quick fix in the frontend to avoid breaking it.

**Comment by inkhey** [comment]
> > > > Is reader as default role for existing spaces OK?
> > > 
> > > 
> > > ```
> > > * at database level, i do think yes, as existing workspace will be set to this, this seem to me both easier and logical.
> > > 
> > > * at api level, i don't know. should default_user_role being mandatory at workspace creation ? what should be the default in frontend ui ?
> > > ```
> > 
> > 
> > I added the ui point to the corresponding frontend issue #3577.
> > As for the API… it's a bit like the `access_type`: not having a default is "better" because the backend cannot really guess what is best, but breaks the compatibility.
> 
> So I would propose to do the same: enforce it in the API + a quick fix in the frontend to avoid breaking it.

i'm ok with that, i just updated the issue.

**Comment by inkhey** [comment]
2 Point to notice about implementation begin here:
- has the spec suggested i do set the column to "reader" by default in sql as an **Enum** in a similar way as for other feature. We have to remember that this not yet the way the role is set in current endpoint and there does exist a technical debt to fix it and convert int to Enum in current usage of role : https://github.com/tracim/tracim/issues/2666 . Note: fixing this should not change anything in current REST API as they do already use slug.
- I do add the field to `WorkspaceSchema`, not digest or minimal version, so this information is currently not available everywhere i can change this.

To validate this last change here are the current usage of different schema of Workspace:
```
WorkspaceMinimalSchema:
- GET /workspaces/{workspace_id}/disk_space as subitem
WorkspaceDigestSchema :
- GET /users/{user_id:\d+}/workspaces
- GET /workspaces/{workspace_id}/members as subitem
- GET /workspaces/{workspace_id}/members/{user_id} as subitem
- PUT /workspaces/{workspace_id}/members/{user_id} as subitem
WorkspaceSchema:
- GET /workspaces
- POST /workspaces
- PUT /workspaces/{workspace_id} 
- GET /workspaces/{workspace_id}
```

**Comment by grignards** [comment]
> 2 Point to notice about implementation begin here:
> 
>     * has the spec suggested i do set the column to "reader" by default in sql as an **Enum** in a similar way as for other feature. We have to remember that this not yet the way the role is set in current database for member and there does exist a technical debt to fix it and convert int to Enum in current usage of role : #2666 . Note: fixing this should not change anything in current REST API as they do already use slug.

No, keep it as it is implemented currently, I used "reader" as it is the name used in the API.

> 
>     * I do add the field to `WorkspaceSchema`, not digest or minimal version, so this information is currently not available everywhere in API, but where it make sense, i can change this if needed

Seems fine to me to only add it in `WorkspaceSchema`.

**Comment by inkhey** [comment]
> > 2 Point to notice about implementation begin here:
> > ```
> > * has the spec suggested i do set the column to "reader" by default in sql as an **Enum** in a similar way as for other feature. We have to remember that this not yet the way the role is set in current database for member and there does exist a technical debt to fix it and convert int to Enum in current usage of role : #2666 . Note: fixing this should not change anything in current REST API as they do already use slug.
> > ```
> 
> No, keep it as it is implemented currently, I used "reader" as it is the name used in the API.

I don't see the advantage to store int instead of Enum in future usage of storing role.  I do not suggest to fix the existing debt today but as we have to replace int to enum, it's seems simpler for me to use enum for new usage instead of int.

**Comment by inkhey** [comment]
> > > 2 Point to notice about implementation begin here:
> > > ```
> > > * has the spec suggested i do set the column to "reader" by default in sql as an **Enum** in a similar way as for other feature. We have to remember that this not yet the way the role is set in current database for member and there does exist a technical debt to fix it and convert int to Enum in current usage of role : #2666 . Note: fixing this should not change anything in current REST API as they do already use slug.
> > > ```
> > 
> > 
> > No, keep it as it is implemented currently, I used "reader" as it is the name used in the API.
> 
> I don't see the advantage to store int instead of Enum in future usage of storing role.  I do not suggest to fix the existing debt today but as we have to replace int to enum, it's seems simpler for me to use enum for new usage instead of int.

to summarize, in such case where technical debt is not yet fixed and do not concern the whole code but a part not so easy to change (database), should we prefer : 
- partial update with new change.
- use old storage method, making this a bit more consistent but leading to more technical debt for tomorrow.
time to do this is similar for both solution, but i've already done enum code here.

**Comment by grignards** [comment]
> > > > 2 Point to notice about implementation begin here:
> > > > ```
> > > > * has the spec suggested i do set the column to "reader" by default in sql as an **Enum** in a similar way as for other feature. We have to remember that this not yet the way the role is set in current database for member and there does exist a technical debt to fix it and convert int to Enum in current usage of role : #2666 . Note: fixing this should not change anything in current REST API as they do already use slug.
> > > > ```
> > > 
> > > 
> > > No, keep it as it is implemented currently, I used "reader" as it is the name used in the API.
> > 
> > 
> > I don't see the advantage to store int instead of Enum in future usage of storing role.  I do not suggest to fix the existing debt today but as we have to replace int to enum, it's seems simpler for me to use enum for new usage instead of int.
> 
> to summarize, in such case where technical debt is not yet fixed and do not concern the whole code (not workspace case) but a part not so easy to change (database), should we prefer :
> 
>     * add new feature with new storage method (enum).
> 
>     * use old storage method, making this a bit more consistent but leading to more technical debt for tomorrow.
> 
> 
> time to do is similar for both solution, but i've already done enum code here.

Personally I would have gone for the "consistency" approach but I do not think you have to change your implementation as it is already done. As for the advantage of role as int/enum… `int` allows direct comparison (`<`/`>`) in database queries, those comparisons are safe to changes as long as we do not change the order of roles. Storing it as an enum as the advantage of being easier to understand for a human as you already mentioned.

**Comment by raphj** [comment]
My uninformed opinion was requested so here it is: I should probably transition to a new way of doing things to avoid doing the work twice at the cost of breaking consistency a bit (you need to look things up when using them anyway so not sure consistency is fundamental here), but we need to have allocated dedicated time to handle technical tebt and restore consistency.

But since I lack experience here I'd go with @grignards's opinion here.

**Comment by inkhey** [comment]
To test this:
- update tracim (both backend and frontend) on branch.
 - check if workspace creation is not broken.

**Comment by raphj** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
