### ISSUE TITLE
Feat: Allow restrictions on created spaces access type

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3602]
## Feature description and goals

New space access types (`OPEN` and `ON_REQUEST`, see #3536) are not necessarily advisable for all Tracim instances.

- [x] add a backend configuration parameter (`workspace.allowed_access_types`). The value of this parameter shall be a list of strings corresponding to existing access types. Items will be separated by a comma.
- [x] the default value of this parameter shall be all existing access types
- [x] make the value of this parameter available through `/api/system/workspace_access_types` returning
`{"items": ["confidential", "on_request", "open"]}`
- [x] modify the POST `/api/workspaces` so that it forbids the creation of spaces with a type **not in** the list.

## Prerequisites

- #3536.

## Implemented solution:
https://github.com/tracim/tracim/pull/3626
- add `workspace.allowed_access_types`  config parameters with a list of string separated by ',' converted into workspace access_type
- add `/api/system/workspace_access_types` returning
`{"items": ["confidential", "on_request", "open"]}` style list of allowed access types.
- return error code  `UNALLOWED_WORKSPACE_ACCESS_TYPE = 2068` if trying to create a workspace from an unallowed access_type
- some tests
- some doc and small webdav error case fix.

**Comment by inkhey** [comment]
@grignards @raphj just re-read the proposed parameter name : `space.allowed_access_type`
Do we want to keep it like this. 
We currently do not have any `workspace.` or `space.*` parameters in config, and the only config with space in it is `limitation.workspace_size` . If we have some future idea about user space, it's ok to keep it, if we do not, maybe `limitation.allowed_space_access_types.` is better ?

**Comment by grignards** [comment]
> @grignards @raphj just re-read the proposed parameter name : `space.allowed_access_type`
> Do we want to keep it like this ?
> We currently do not have any `workspace.*` or `space.*` parameters in config, and the only config with space in it is `limitation.workspace_size` . If we have some future idea about user space, it's ok to keep it, if we do not, maybe `limitation.allowed_space_access_types` is better ?

For me it is not a limitation in the way the other values in `limitation.` are. I just used the same naming pattern as `app.enabled` since it's more or less the same thing. Just chosen `allowed` instead of `enabled` because `enabled` makes me think the value is a bool.

**Comment by inkhey** [comment]
> > @grignards @raphj just re-read the proposed parameter name : `space.allowed_access_type`
> > Do we want to keep it like this ?
> > We currently do not have any `workspace.*` or `space.*` parameters in config, and the only config with space in it is `limitation.workspace_size` . If we have some future idea about user space, it's ok to keep it, if we do not, maybe `limitation.allowed_space_access_types` is better ?
> 
> For me it is not a limitation in the way the other values in `limitation.` are. I just used the same naming pattern as `app.enabled` since it's more or less the same thing. Just chosen `allowed` instead of `enabled` because `enabled` makes me think the value is a bool, but I don't have a problem to use `enabled`.

The way this parameter work is also similar to `auth_types`

**Comment by raphj** [comment]
I missed `space.`

Well, so many things are called workspace in the backend, should we introduce `space` now?

**Comment by grignards** [comment]
> I missed `space.`
> 
> Well, so many things are called workspace in the backend, should we introduce `space` now?

We can also use `workspace.`, I didn't see there was the `limitation.workspace_size` parameter.

**Comment by lebouquetin** [comment]
I agree with @grignards : enabled would make sysadmin misunderstand the parameter.

**Comment by raphj** [comment]
> > I missed `space.`
> > Well, so many things are called workspace in the backend, should we introduce `space` now?
> 
> We can also use `workspace.`, I didn't see there was the `limitation.workspace_size` parameter when writing the issue.

another approach to make `workspace` an alias of `workspace` everywhere in the conf to initiate the transition from `workspace`  to space, what do you think?

**Comment by inkhey** [comment]
In this particular case:
- as space is less specific than workspace and may be more complicated to separate for other things in code ("whitespace" for example)
- as workspace is used everywhere in backend from database to api endpoint path.

I do suggest to keep workspace for both api endpoint and config parameter in backend for now and change the term everywhere in backend as soon as we decided to do in everywhere.

so : 
`workspace.allowed_access_type` config
and
`GET /api/system/workspace_access_types` endpoint

**Comment by grignards** [comment]
I modified workspace -> space.

**Comment by inkhey** [comment]
2 questions about this one:

## Endpoint specification

I see 2 ways to implement the endpoint (in a way hapic allow, it's not possible to provide direct list of string as far i know using schema).
1. the `/api/system/reserved-usernames` way : 
```json
{"items": ["all", "tous", "todos"]}
```
2. the `/api/system/timezones` way:
```json
[{"name": "Africa/Abidjan"}, {"name": "Africa/Accra"}, {"name": "Africa/Addis_Ababa"}, {"name": "Africa/Algiers"}, {"name": "Africa/Asmara"}, {"name": "Africa/Bamako"}, {"name": "Africa/Bangui"}, {"name": "Africa/Banjul"}, {"name": "Africa/Bissau"}, {"name": "Africa/Blantyre"}, {"name": "Africa/Brazzaville"}, {"name": "Africa/Bujumbura"}, {"name": "Africa/Cairo"}, {"name": "Africa/Casablanca"}, {"name": "Africa/Ceuta"}, {"name": "Africa/Conakry"}, {"name": "Africa/Dakar"}]

## Update ?

Is it a problem to not be able to update (without changing the access_type) a workspace with an unvalid access_type ? according to the way the update his done, i don't see a way to easily handle this case properly unless we move check from  workspace internal api to endpoint itself, which is less secure.

```

**Comment by raphj** [comment]
- `/api/system/reserved-usernames` looks better
- I'm okay to not be able to update a workspace with an invalid access_type because it should not happen. Should this happen, we will decide a proper way to solve the issue is a more correct way because we will have more information on which specific situation will cause this.

**Comment by grignards** [comment]
I also prefer the `items` approach for arrays.
For the update… I would rather allow to modify a workspace which has a disallowed `access_type`: the allowed access_types should only be enforced for created spaces (as long as we do not support updating the access_type of existing spaces). What makes you think it is difficult to do ?

**Comment by raphj** [comment]
It's okay for me if it is easy to do.

**Comment by inkhey** [comment]
After discussion with @grignards. i find a solution for the update (i didn't check correctly the code).

I just discovered a new problem with this restriction mechanism, which already exist but may be more visible now.
This problem is webdav related, and may be solve depending on the solution for #3549 : as we currently do accept to create workspace through webdav, there is no specification about what should be the access_type of these new workspace. According to code and test, it default to confidential and cause internal server error if confidential is not provided.

**Comment by inkhey** [comment]
> I just discovered a new problem with this restriction mechanism, which already exist but may be more visible now.
> This problem is webdav related, and may be solve depending on the solution for #3549 : as we currently do accept to create workspace through webdav, there is no specification about what should be the access_type of these new workspace. According to code and test, it default to confidential and cause internal server error if confidential is not allowed.

Will be solved by https://github.com/tracim/tracim/issues/3625

**Comment by PhilippeAccorsi** [comment]
Done.
