### ISSUE TITLE
Feat: Add a configurable way of automatically manage members of OPEN spaces

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3604]
## Feature description and goals

`OPEN` spaces (see #3536 and #3538 ) are freely accessible spaces: any user can become a member without validation.
In some cases it can be useful to have a feature that adds every user to `OPEN` spaces on user and `OPEN` space creation.

In a backend plugin, using the events for user and space creation:

- [x] add all existing users as members when an `OPEN` space is created with event `on_user_created`
- [x] make a new user member of all existing `OPEN`spaces when a user is created with event `on_workspace_created`
- [x] the plugin shall not be enabled by default
- [x] the user's role shall be the defined default role for the space (see #3601).

## Prerequisites

- #3536.
- #3601 

### Plugin activation method

@grignards To ease the development (and since this behavior could be needed by several instances) I would develop the plugin within tracim's repository. This means we should find a way to disable backend plugins without removing their `.py` file from the sources as it is too cumbersome in my opinion (plugins can be anywhere in tracim_backend folder/subfolders).

To do this we discussed and came to the conclusion that we can put the "official" plugins in a `official_plugins` folder. To activate one of those we'll use the current activation mechanism (move them to `plugins` in order to activate them).

### Implemented solution
PR: https://github.com/tracim/tracim/pull/3730
- add officials_plugin dir to backend dir
- adapt code to be able to test official plugin easily
- add  auto-Invite plugin which add all existing users as members when an `OPEN` space is created and make a new user member of all existing `OPEN`spaces when a user is created + tests

**Comment by raphj** [comment]
We could have a `plugins-available` folder and a `plugin-enabled` folder that has symbolic links if we go for the folder approach.
A configuration file listing the plugins is probably easier, though?

**Comment by inkhey** [comment]
not sure to understand this part:

> I would propose either:
> 
>     * to only try to load plugins from a defined folder (`tracim_backend/plugins`).

Plugin are loaded from a specific folder, configurable:
```
### Plugins ###
# if provided, this allow Tracim to load package from this dir and if package follow
# the convention "tracim_backend_{plugin_name}", hooks provided inside the package will
# be loaded, allowing to add new feature to an existing Tracim.
plugin.folder_path = %(here)s/plugins
```

**Comment by grignards** [comment]
I forgot this plugin folder. What I meant is that plugins are loaded from any path on the python path, not only from this plugin folder (like I propose to do).

**Comment by PhilippeAccorsi** [comment]
I not understand here if you purpose to change plugin (custom_toolbox) workflow or just to find a way to add some plugin.

If we change plugin workflow, its a breaking change, and for me its not possible to add breaking change for each new feature (. Why this feature is a plugin and not application for example ? If its an app, we can activate this feature by adding app in this list `app.enabled`.

At present we have this for backend:
~~~
### Plugins ###
# if provided, this allow Tracim to load package from this dir and if package follow
# the convention "tracim_backend_{plugin_name}", hooks provided inside the package will
# be loaded, allowing to add new feature to an existing Tracim.
; plugin.folder_path = %(here)s/plugins
~~~

and this for frontend:
~~~
# if you need to add custom javascript code into Tracim, you can use custom toolbox
# feature. You add your javascript in this folder, all content
# of this folder will be serve in /custom_toolbox-assets
# and all javascript ".js" file will be added to index.html file.
; frontend.custom_toolbox_folder_path =
# example:
# frontend.custom_toolbox_folder_path = /tmp/custom_toolbox
~~~

**Comment by PhilippeAccorsi** [comment]
Je vais mettre mes interrogations en français :
- quelle est la problématique actuel pour avoir besoin de changer de système de plugin ?
- la nouvelle mécanique pourra t elle garantir une meilleur pérénnité dans le temps ? La mécanique de plugin actuel n'a qu'1 an (sorti pour Mon Tracim), jai du mal à comprendre le besoin de changer complètement étant donnée qu'il y a eu pas mal de réflexion sur la mécanique des plugins (peut-être pas la bonne approche ? peut etre un mauvais choix technique ? etc).
- j'ai une inquiétude sur les breaking change qui me semble être considéré comme des fix normaux (dans le sens "cest pas grave"). Les breaking change nécessite souvent des modifications qui vont au dela de la simple modification d'un fichier du repo (script de déploiement, migration des process et procédure, changement d'infra).
Je voudrais être sur que l'on ne developpe pas le produit en mode "obsolescence programmé", cad qu'a chaque version ont doit repartir de zero, pour toutes les features. Comment migrer simplement les plugins déjà existant par exemple.
- la feature proposé ne peut-elle pas être considéré comme une app et donc être activable comme les autres app de tracim ? Ce type de feature me semblait être plus une app qu'un plugin.
- n'y a t'il aucun changement dans l'interface à propo de cette feature ? Il semble que l'on puisse créer différent type d'espace, cela sous-entend que les boutons de création d'espace seront multiple ou a choix multiple. Les modif en front seront-elle géré via le custom_toolbox ou via un nouveau mécanisme aussi en breaking change.

Je pense avoir mis mes interrogations/questions. Je n'est pas d'avis sur le bon choix technique à faire, mais plutôt sur le ressentie que l'on peut avoir si on "casse" chaque version de tracim dès que l'on a une nouvelle feature à mettre en place.

**Comment by lebouquetin** [comment]
@grignards there is already a plugin mechanism. The goal here is not to redefine what has already been defined but to use it.

There is a plugin folder because plugins are intended to be deployable with/without tracim. The goal of plugin folder is to allow specific distinct development from the product. This is why plugins must be found in a specific place: when deploying an upgrade, it must be easy to keep them without mixing core product source code and plugins code.

Writing plugins (in the mean of current Tracim version) is not "plugging any specific source code in the core" but implementing some features as a extra code / client-specific code out of the core tracim code.

The expected mechanism (which is already/partly implemented) is to be able to add source code in a specific folder and offering an easy-to-use interface for specific behavior/check implementations.

Examples:

- Send an email to someone when a user subscribes to a given space:

```
register_callback(Event.WorkspaceMemberAdded, membership, status):
    if status == Status.Error:
        return  # ignore membership error cases
    
    if member['workspace_id']==4:
        user = UserApi().get_user(member['user_id'])
        mailto(
            'admin@mycompany',
            subject='New user joined the space',
            body='New user: {}'.format(user.email_address)
         )
```

- Check content label structure for a given folder

```
register_callback([Event.BeforeContentCreated, Event.ContentUpdated], new_content):
    if new_content['workspace_id'] != 3:
        return  # we are only interested in content found in space #3
    if new_content['parent_id'] != 16:
        return  # we only want to check content structure in folder "standup"
  
    if new_content['label'] not like "YYYY-MM-DD | xxx":
        raise ValueError('Le standup de chacun doit être labelisé "YYYY-MM-DD | xxx"')
    if new_content['description'] contains less than 3 <h2>:
        raise ValueError('La structure du document doit être XXX')

    return new_content
```

- Auto invite new user to OPEN spaces:


```
register_callback([Event.OnUserCreated], user, status):
    ws_api = WorkspaceApi()
    open_spaces = ws_api.get_workspaces(status=OPEN)
    for space in open_spaces:
        ws_api.add_member(space, user, Role.READER)

    mail('admin@asf.be', subject='new user joined the plateform', body='his email is {}'.format(user.email_address)
```

- Update a PDF document on company website when the status of the given ODT document is validated on tracim


```
register_callback([Event.OnContentUpdated], content, status):
    if status == Status.ERROR:
        return
  
    if content.content_id != 234:
        return
  
    filepath = content.file_path  # file path on disk
    output_filepath = '/tmp/product_catalog.pdf' 
    if file.exists(output_filepath):
        os.remove(output_filepath)
  
    odt2pdf(filepath, output_filepath)
    with ftp.open('server', 'login', 'password' as ftp_handle:
        ftp_handle.write(output_filepath)
  
    mail(
        'admin@company',
        subject='updated product catalog',
        body='catalog updated according to last version {}'.format(content.user_friendly_url()
    )
```

Theses plugins are not intended to be developped by Tracim core team but by sys admins, algoo professional services or any algoo partner deploying tracim for their clients.

Plugins must be auto-detected, this is the reason for putting them in a given folder: this folder is processed at start time and will allow to activate some specific features.

Plugins must be stupidly simple to implement even for "not developers". It's not an advanced feature for developers, its an easy-to-use way to specialize tracim behavior for power-users and bidouilleurs. This will allow to adapt tracim behavior and to integrate easyly Tracim in information systems.

**Comment by lebouquetin** [comment]
I think we need to have a discussion about the goal of the plugin mechanism to implement *at the moment*.

**Comment by grignards** [comment]
I think I didn't make myself clear: the only thing I want to change is to load plugins **only** from the given plugins folder.
Currently plugins are loaded from **any** folder in the python's path (and the configured *plugins* folder is added to the path for this).
If we only load from the *plugins* folder we could then relax the naming (a plugin package's folder must currently begin with `tracim_backend`).

**Comment by PhilippeAccorsi** [comment]
> I think I didn't make myself clear: the only thing I want to change is to load plugins **only** from the configured _plugins_ folder.
> Currently plugins are loaded from **any** folder in the python's path (and the configured _plugins_ folder is added to the path for this).
> If we only load from the _plugins_ folder we could also relax the naming (currently a plugin package's folder must begin with `tracim_backend`).

Ok. So for this point I think its not a breaking change, and not need modification for Mon Tracim.

**Comment by grignards** [comment]
@lebouquetin I think we already talked about the backend plugins and their goals in the mid/long-term. I have no problem in creating the APIs for such plugins but  currently what is available in Tracim does not provide this type of plugins, only a basic way to hook code.
Making those "dumb-user" plugins a reality is a big task by itself that we won't achieve it just by doing it during other developments.
And I would base the "dumb-user" plugins on these current "advanced-user" plugins without replacing them: even if only used by Tracim developers the "advanced-user" plugins have their advantages of providing a way to split implementation of loosely linked features and a mechanism to easily enable/disable them (for example email notifications would benefit from being implemented as a "advanced-user" plugin I think).

**Comment by lebouquetin** [comment]
What I understand is you want to implement a plugin mechanism for this feature. This plugin is a dub-user plugin, so we need to implement the expected mechanism now, not in the middle/long term.

This mechanism is not part of tracim core but part of tracim backend ecosystem.

If we need to implement a plugin mechanism, then we need to write an issue, to discuss how it will be implemented, then implement it.

**Comment by grignards** [comment]
- events: before db insert, after and after commit
- equivalent to http api in terms of access.
- two plugins folders (from where tracim loads its plugins) : one official and one for third-party. Plugins enabled by configuration.
- documentation about plugins.

**Comment by inkhey** [comment]
Just added events needed for implementing the plugin in ticket.

for plugin activation, my suggestion is here: https://github.com/tracim/tracim/issues/3572#issuecomment-709958081 .

**Comment by inkhey** [comment]
Is this acceptable that the author of the automatic event is the author of the first action : create_user or create_workspace ? I'm ok with this, but i do need confirmation.

**Comment by inkhey** [comment]
To test this:
- move or create symlink to `official_plugins/tracim_backend_autoinvite` into backend plugin dir
- start tracim and check startup log message to verify plugin is correctly launched
- create  some users
- create a open space
- check all users are on open space with default role for all but the owner
- create somes new users
- check theses new user are automatically added to this open existing space.

**Comment by raphj** [comment]
tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
