### ISSUE TITLE
Feat: Change "Text document" to "Note"

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3621]
## Feature description and goals

The idea of changing the name from **text document** to **note** is that it is smaller, simpler and reduces ambiguity between the html-document and file type.

### Expected
- [x] change "text document" to "note" everywhere in the UI (just the displayed interface, not the code)
- [x] change "text document" to "note" in the backend translations (just the displayed interface, not the code)

## Prerequisites

None

## Translations

|English|French|Portuguese|
|--|--|--|
|Note|Note|Nota|

**Comment by lebouquetin** [comment]
the renaming to "note" is open to proposal for a better new naming.

**Comment by PhilippeAccorsi** [comment]
For me, Note (Notes ?) is a good idea. We have same feature on smartphone to write some text and add picture and different syntax.
I think we understand that is not a tool to make documentation like we can make with libreoffce.

**Comment by celiamgtt** [comment]
"text document" to "note" without s.

**Comment by PhilippeAccorsi** [comment]
> For me, Note (Notes ?) is a good idea. We have same feature on smartphone to write some text and add picture and different syntax.
> I think we understand that is not a tool to make documentation like we can make with libreoffice.

But if we add also markdown app, what is the solution to compare Note (html with tinymce) and Note (markdown with ???)

**Comment by PhilippeAccorsi** [comment]
Can we have something like 
- Note html (html visible with small font)
- Note markdown (markdown visible with small font)

**Comment by gbonaspetti** [comment]
> "text document" to "note" without s.

Personally I prefer with s, we make several notes in a document, but I do not have a very strong opinion about the subject. I like "text editor" too, but I think it can be kind of big in the translations.



> Can we have something like
> * Note html (html visible with small font)
> * Note markdown (markdown visible with small font)

I don't think "html" and "markdown" are very speaking for those who don't know much about informatics, but I confess that I don't have an idea to solve this case

**Comment by PhilippeAccorsi** [comment]
> I don't think "html" and "markdown" are very speaking for those who don't know much about informatics, but I confess that I don't have an idea to solve this case

Maybe show different text on tooltip and different icon for app.

**Comment by lebouquetin** [comment]
I suggest to follow the suggestion of @celiamgtt:

- `Note`, `write a note`
- For markdown I think it will be something like `Advanced Note` or `power user note` or `markdown`... or when clicking "note", we'll give the choice to the user... but we can decide this later (when implementing markdown support)

**Comment by inkhey** [comment]
tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
