### ISSUE TITLE
Feat: Remove space action from webdav and same name space view

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#3625]
## Feature description and goals

In order to support complex features through webdav like https://github.com/tracim/tracim/issues/3549, we should remove some space level actions from it.

- [x] remove the ability to create space from webdav view
- [x] remove the ability to rename space from webdav view
- [x] if a user belongs to identically named spaces, show the first one in the directory view (lower workspace_id), url to the workspace should go to this one too.
- [x] Add the information that we do not properly support identical names for spaces in webdav view in known issues.

## Prerequisites

None

##  Extra information

- Verify if some documentation exists for those features
- This should be documented in the changelog too.

## Implemented solution:
- remove ability to create workspace from webdav view
- remove the ability to rename space from webdav view
- if a user belongs to identically named spaces, show the first one in the directory view (lower workspace_id), url to the workspace should go to this one too + add explanation into known_issue doc.
- remove dead code about history, deleted or archived content.
- reorganise code to avoid having folder children of workspace (confusing).

**Comment by PhilippeAccorsi** [comment]
Please add some information about this breaking change in this issue https://github.com/tracim/tracim/issues/3650
Idea: one or two line to explain this kind of change.

**Comment by PhilippeAccorsi** [comment]
Manually tested:

- [ ] remove the ability to create space from webdav view
- [ ] remove the ability to rename space from webdav view
- [ ] if a user belongs to identically named spaces, show the first one in the directory view (lower workspace_id), url to the workspace should go to this one too.
- [ ] copy file
- [ ] move file
- [ ] replace file

**Comment by PhilippeAccorsi** [comment]
Done.
