### ISSUE TITLE
Feat: start showing members in the mention suggestions right away

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3630]
When a @ is written, the popup should open not only with the group mentions but also with the list of all space members immediately and not after two characters are typed.

- [x] When autocompleting mentions (that is, listing only members from the current workspace), start sending the list of members right away.
- [x] add a `limit` parameter to the known members endpoint
- [x] Limit the returned list to `limit` elements, if provided

## Discussed before development

- What should be the maximum number of returned members?
- Should this be a parameter the frontend sends? 

(taken from #3544)

___
2020-09-24: solved the discussions

**Comment by gbonaspetti** [comment]
> To be discussed before development
What should be the maximum number of returned members?
Should this be a parameter the frontend sends?

To have the same number of results everywhere I would say to use `NUMBER_RESULTS_BY_PAGE` constant (`frontend/src/util/helper.js`, for now)

**Comment by raphj** [comment]
ok :-) good idea
So since there is already a constant in the frontend, I'd say let's allow the frontend to set the maximum when doing the request to the backend.

**Comment by grignards** [comment]
Just a small remark for `max_count`: check if there is the same behavior in another API. If there is, you should use the same naming.

**Comment by raphj** [comment]
There is indeed a case where this parameter is named limit. I'm changing this.

**Comment by PhilippeAccorsi** [comment]
What is the default limit for `Limit the returned list to limit elements, if provided` ?

**Comment by raphj** [comment]
The limit provided by the frontend is 15

**Comment by PhilippeAccorsi** [comment]
Thanks.
Tested on preprod.
