### ISSUE TITLE
Feat: Allow to change a space's parent through tracimcli

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3636]
## Feature description and goals

Spaces will have the possibility to be created in another space with #3577.
In some cases (user error for instance) it can be useful to change a space's parent.
To minimize the development effort of this functionality which is not planned to be used frequently we'll first implement it in `tracimcli`:

- [X] add a `space move -s <space_id> -p <new_parent_id>` command in `tracimcli`
- [x] check plugin compatibility and discuss about behavior if needed
- [x] adjust the ui if needed.

## Prerequisites

- #3546 

## Interface

Where/how should this drop-down be added in the dashboard?

_2020-09-30_ **Decision**: https://github.com/tracim/tracim/issues/3636#issuecomment-698955451

**Comment by lebouquetin** [comment]
As we discussed on IM, it is acceptable to have this action only through CLI.

**Comment by grignards** [comment]
> As we discussed on IM, it is acceptable to have this action only through CLI.
> 
> Something like `tracimcli move-space --new-parent 45` where 45 is the id of the new parent space

I edited the issue.

**Comment by knodelle** [comment]
Warning: if you move a parent space and make it it's child's parent (let's say A is parent of B, and you make B parent of A), it may hide all your spaces. 
To fix this, bring all your spaces back to the root : 
```
tracimcli space move -s 1 -p 0
tracimcli space move -s 2 -p 0
tracimcli space move -s 3 -p 0
```
etc...

**Comment by knodelle** [comment]
tested on branch

**Comment by gbonaspetti** [comment]
Done
