### ISSUE TITLE
Feat: Add emoji reaction in the recent activities

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3641]
## Feature description and goals

- [x] Add reaction buttons to the activity feed

Reactions on comments and contents is done there: https://github.com/tracim/tracim/issues/4274

## Prerequisites

#3600 

## Interface

![emoji](https://user-images.githubusercontent.com/3817365/110488161-82cd5a80-80ee-11eb-949c-61ce434b0708.jpg)

## Translations

|English|French|Portuguese|
|--|--|--|
|React|Réagir|Reagir|

## Discussed 

1. Are the reactions by emoji specific to the feed or will it be possible to see them in the content (in the app)?

_2020-09-30_ **Decision**: The reactions will be displayed in the specific version at timeline.
NOTE: we back tracked on this decision: reactions are not attached to revisions anymore

2. Should we have a tooltip in the reactions that shows who did it?

_2020-09-30_ **Decision**: Ideally yes.

**Comment by raphj** [comment]
Should reactions also be clickable button to add/remove own's same reaction?

**Comment by PhilippeAccorsi** [comment]
Done.
