### ISSUE TITLE
Feat: Check opensearch compatibility

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#3642]
## Feature description and goals

Considering updating the elasticsearch version compatibility, we have raise a concern about the consequences of the new elasticsearch license which is not anymore opensource.

We should check opensearch compatibility and adapt documentation to explain which versions of both elasticsearch and opensearch, tracim do support.

previous description:
> 
> - At present, compatible Elasticsearch version with tracim is in version 7.0.0 (and ingest is based on this version).
> - Now elasticsearch 7.9.1 is available on [hub Docker](https://hub.docker.com/_/elasticsearch?tab=tags&page=1&ordering=last_updated) and we need to make sure this new version working good with Tracim.
> 

## Prerequisites
- need some local test on default and ingest version.

## Implemented solution

issue ref #3642 
PR ref #5596

- document how to use opensearch instead of elasticsearch
- add opensearch_ingest dockerfile

**Comment by inkhey** [comment]
Rapid check of 7.1->7.9 elasticsearch breakings changes without finding anything that seems to break current behavior.

**Comment by inkhey** [comment]
manually and automatically tested with 7.14.2.
No problem discovered for now. I suggest to test this more deeply in pre-production environnement.

**Comment by PhilippeAccorsi** [comment]
Great news \o/

**Comment by PhilippeAccorsi** [comment]
To use the new version on existing installation, is it necessary to update de `jvm.options` and `log4j2.properties` files, available in `/var/lib/docker/volumes/root_es-config/_data` (with `root_es-config` is the name of the docker volume for Elasticsearch).

The simple solution is to start new elasticsearch in another volume and copy this 2 new files in old volume.

**Comment by inkhey** [comment]
Due to the elasticsearch licence change making elasticsearch non-free software (as far i understood), some discussion are needed. There is a FOSS fork managed by amazon called opensearch, if we decided to use this one, we should do some tests to verify all is still working correctly (python lib, ingest mecanism, etc...). Until a decision has been made, we should probably stay officially on a old elasticsearch version.

**Comment by inkhey** [comment]
An other important point to note if we decide to be compatible with opensearch is that the current configuration and a part of the code is currently named as "elasticsearch".

**Comment by inkhey** [comment]
after discussion with the team, we decide to verify the opensearch compat and document both elasticsearch and opensearch version we do support.

**Comment by inkhey** [comment]
@gbonaspetti Just replace this PR in the current release has this development is pending, waiting for review/test . I added low priority as this is not required for now, be free to move it anywhere.
