### ISSUE TITLE
Feat: Add content preview in the activity feed

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3657]
## Feature description and goals

Each content should have a preview in the activity feed to make it more user friendly.

- [x] If the user clicks on the preview through the feed, they must be redirected to the content app.
- [x] In medium, large and extra-large screens, the preview should have a width/height ratio around 16/9.
- [x] If the element that will be previewed has a  greater height than the maximum height of the preview, it will be "cut" and the black gradient (see Interface section) will appear, for now this will be just a black gradient without the icon in the interface examples.
- The size should be defined by de development, it could be different for the different screen sizes (xs, sm, md, lg, xl) and should try to have a height that, if the previews got the maximum size, it shows around 1 activity and a half in the feed.

Implementation suggestions: 
- Have an `PreviewActivityFeed.jsx` component that will serve as the "wrapper" for the preview and determine the maximum size and what to do according to content's type.

## Prerequisites

#3600 

## Interface
_Obs: These interface examples are only templates, not everything will be developed in this issue and some details can be changed according to the implementation._

- Note
![template_actualite_note](https://user-images.githubusercontent.com/35422692/98222502-33fd9180-1f51-11eb-8c44-9d6f557e731b.png)

- Thread
<img width="800" alt="template_actualite_discussion" src="https://user-images.githubusercontent.com/35422692/94581480-6f82ad00-027b-11eb-823f-52ff8664903d.png">

- File
<img width="800" alt="template_actualite_odt" src="https://user-images.githubusercontent.com/35422692/94581500-76a9bb00-027b-11eb-825c-3430b235d75d.png">

- File without preview
![template_file_without_preview](https://user-images.githubusercontent.com/35422692/98257033-82298980-1f7f-11eb-815c-1389f2e1714f.jpg)

## Discussed

1. What will the preview of an html document look like? Should we display the first N lines?

_2020-09-30_ It will be displayed as a html text (see Interface section) inside a clickable zone and the size will be fixed for all previews.

2. What will the preview of an thread look like? Should we display the latest N messages?

_2020-09-30_ It will be displayed the first message as a html text (see Interface section) inside a clickable zone and the size will be fixed for all previews.

3. When the document is a big image, we have a max size to the preview? And if it's a very small image, we display it in its real size?

_2020-09-30_ Ideally the display will be different according to the size of the image. For now, we will do the same behavior for all images (the same of file preview) and then we will have an issue to improve this behavior.

## Extra information
The preview in a bigger size will be implemented at https://github.com/tracim/tracim/issues/3708
The distinction for videos will be implemented at https://github.com/tracim/tracim/issues/3709

## Time Estimation

3 man.days

**Comment by grignards** [comment]
@gbonaspetti Did you discuss how will the preview of html documents/threads be implemented? The logical way would be to implement this in backend but this is not necessarily the cheapest solution.

**Comment by grignards** [comment]
And I gather from the issue that the folder changes are not displayed in the feed?

**Comment by gbonaspetti** [comment]
> @gbonaspetti Did you discuss how will the preview of html documents/threads be implemented? The logical way would be to implement this in backend but this is not necessarily the cheapest solution.

Not discussed yet. If it's complexe to do it in the back, do you think is valid to have a first version with a frontend implementation and after we change for a backend one ?

> And I gather from the issue that the folder changes are not displayed in the feed?

For now, I don't think that it's necessary.

**Comment by lebouquetin** [comment]
@gbonaspetti @grignards I don't think its difficult to build preview in backend: this is a dev in preview-generator only. This could be "not as clean as expected" but there is a work "planned" about doing improved previews through preview-generator in order to include html preview which would be better for lots of file formats (text-based, libreoffice, html content, etc)

**Comment by lebouquetin** [comment]
for threads, what was discussed was to use the first comment as preview

**Comment by grignards** [comment]
> @gbonaspetti @grignards I don't think its difficult to build preview in backend: this is a dev in preview-generator only. This could be "not as clean as expected" but there is a work "planned" about doing improved previews through preview-generator in order to include html preview which would be better for lots of file formats (text-based, libreoffice, html content, etc)

It's not very difficult, but a bit different from the file previews as the content we want to preview is stored in the database (html documents and threads/comments are the same). `preview_generator` only supports previews through file paths which mean we have to store (even temporarily) the html as a file (or add support for memory buffers in preview_generator). We also have to duplicate/create API for threads and html documents as the preview HTTP APIs are specific to the `file` contents.

**Comment by grignards** [comment]
On front-end, converting html to image seems possible with [html2canvas](https://html2canvas.hertzen.com/documentation).

**Comment by gbonaspetti** [comment]
One option, if we do it in frontend, is to preview it in text html within a clickable div with the property `user-select: none`. This way we "imitate an image", the div will have the same border as an image and so on.

**Comment by inkhey** [comment]
> It's not very difficult, but a bit different from the file previews as the content we want to preview is stored in the database (html documents and threads/comments are the same). `preview_generator` only supports previews through file paths which mean we have to store (even temporarily) the html as a file (or add support for memory buffers in preview_generator).

As we previously have some kind of discussion about storing note/html-document as true file i do think this is acceptable to have some kind of hack which will return for any kind of tracim file a path with the content we do want. We may later remove the temporary file for note as we converted to a true file. The only case where i do not see any solution but to store a temporary file is the thread case because we do return not the content of the thread itself (a thread is some kind of "directory")


Note also that we already have a "dumb" content to html convertion in webdav for html-document and thread

 > We also have to duplicate/create API for threads and html documents as the preview HTTP APIs are specific to the `file` contents.

The other solution is to make the preview endpoint generic like move, etc... but this need discussion and is breaking change, this need also we do need to think about handling properly some edge case (preview of directory content, preview of comment content ?)

> 
> Another detail: if we do not care about the CSS to apply, the rendering will be "raw" and not using the styles/fonts used by the front-end.

**Comment by gbonaspetti** [comment]
After discussing with @grignards and @celiamgtt , it is logical to show the text directly and not make an image for the Note and Thread types. But we will add an endpoint in the backend to make the GET of the first comment of the thread.

**Comment by lebouquetin** [comment]
I do not agree with adding a specific endpoint for this. I suggest to implement a html preview endpoint for a content, which will implement the return of a html preview (which is first comment in the case of a thread). If you do not agree @grignards @gbonaspetti let me know and we'll have a chat about this

**Comment by grignards** [comment]
> I do not agree with adding a specific endpoint for this. I suggest to implement a html preview endpoint for a content, which will implement the return of a html preview (which is first comment in the case of a thread). If you do not agree @grignards @gbonaspetti let me know and we'll have a chat about this (this is related to the preview strategy and the products roadmap)

Do you want to make this endpoint work for any possible content or only for threads/html-documents?

**Comment by lebouquetin** [comment]
> Do you want to make this endpoint work for any possible content or only for threads/html-documents?

- In the (not so) near future, yes;
- In the near future, we only neet this endpoint to work for threads and html-documents
- In the long term future, this preview should also work for other content types.

Currently the API for preview are like `/api/workspaces/{workspace_id}/files/{content_id}/preview/pdf/{filename:[^/]*}`

My point is to make this more generic, possibly for all content types.

For example:

- JSON format preview should be available for all content types (this is about content metadata)
- HTML format preview should be available for lots of content types (htmldocument, thread, office files, all text-based files, etc)

The "brain" about preview should be implemented in the backend, I think (even if not processed using preview-generator). The goal behind this is about developing preview generator as a product.

**Comment by inkhey** [comment]
> The "brain" about preview should be implemented in the backend, I think (even if not processed using preview-generator). The goal behind this is about developing preview generator as a product.

Depending what we do mean by preview, as preview_generator rely on path and not having path will cause many trouble for previewing with external program, we can later simplify the problem with this: 

- The only specific code by content type is providing theses 3 information at ContentApi Level:
  - file path
  - file extension (already in database)
  - mimetype (already in database)

This way we can have generic endpoint like this:

/api/workspaces/{workspace_id}/{content_type_subpath}/{content_id}/preview/{preview_type}/{filename:[^/]*}

with:
- a checker that verify that content obtain with this content_id match the content_type related to content_type_subpath
-a checker that verify that preview_type is in a list of supported previews
- a pluggable process for `get_one_revision_filepath` of contentApi to do thing differently depending on the type of content (specific code per application).
- let preview_generator do the rest.

We will need to modify a bit schema to return mimetype and file_extension for all files. We can also go further and provide download endpoint for other content type if relevant.

**Comment by grignards** [comment]
@gbonaspetti I think you want a 16/9 ratio, isn't it (you wrote *6/9*)?

**Comment by gbonaspetti** [comment]
> @gbonaspetti I think you want a 16/9 ratio, isn't it (you wrote _6/9_)?

Yes, you are right, is 16/9, I'll update the description

**Comment by inkhey** [comment]
Is it relevant to get revision specific preview or the idea is to always show the last revision preview ?
(note: in the specific case of thread, first comment content will clearly not change).

**Comment by lebouquetin** [comment]
@inkhey I do not think we'll have cases where we show old revision of a content in the activity feed

**Comment by inkhey** [comment]
Tested on branch:
Preview are working correctly but we do need to find good rule to maximize useful information in file content.
This point need to be discussed, but that's should not block us to merge this first iteration of content preview.

**Comment by raphj** [comment]
Ok, after discussion with @inkey, we agreed to find this out during collective tests.

**Comment by PhilippeAccorsi** [comment]
Done.
