### ISSUE TITLE
Bug: error 500 for not found case and some specific case

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#3660]
## Description and expectations

Tracim 3.1 added a better mechanism to handle session when something goes wrong by "dooming" them, this works correctly most of the time but in some edge cases, it causes 500 errors instead of a more appropriate error.

These edge cases surfaced while fixing #3539. I decided to move this fix outside for this issue as:
- it's not really related to the issue but fixing this issue was necessary to troubleshoot the problem found in #3539 due to missing migration code
- we may want to backport this fix to 3.1.x

This issue was created in order to keep track of this problem.

### How to reproduce

1. Go to /api/this_endpoint_does_not_exist
3. Get error 500 instead of 404

### Version information

- Tracim version: local
- Web browser: httpie command line
- Version: 3.1.2
- Device / System: PC

## Diagnostic

The known edge cases are:
- PageNotFound case: in such case, pyramid does not start a transaction, so we can not doom the current transaction
- Database error about unique constraint occuring during sqalchemy trigger on saving on event table put us in a "non-doomable session case".

## Implemented solution 
Handle properly edge case with dooming of transaction.
- handle the PageNotFound if no Transaction case.
- handle the "non-doomable session" case which happened when session is not doomable at the time we try to doom it, for example if something has already got wrong during sqlalchemy trigger event.

**Comment by raphj** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
For me no more test necessary for this issue. I have also tested on unstable and this is not potentially impacted by other issue.
