### ISSUE TITLE
No way to restore deleted/archived file on workspace root when folder is "empty"

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#367]
When there is no visible folder in workspace root, there is no way to restore deleted/archived folders. The only way to do this is by creating an other folder and then the UI give access to those files.

**Comment by algooapy** [comment]
Strange... Should be fixed by now: see #277

**Comment by lebouquetin** [comment]
@inkhey where did you face the bug? On algoo.trac.im or on your local development environment. If dev environment, could you give us the last commit id (taken from master) of your repo?

**Comment by inkhey** [comment]
On dev environnement.
Last commit id : dec0113470784a37c6128de715f41561e6c14a8d
Happen only in workspace root, not in subdirectories.

**Comment by xandercagexxx** [comment]
Is working good with filter.

Verified.
