### ISSUE TITLE
Moving folder: destination folder choice is not clear

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#368]
Current status:
When trying to move folder, it's not clear if a destination folder has been selected (and if so, which one is selected). This is since the new treeview has been added, 

Expected: make something in the user interface which is clear for the user

**Comment by PhilippeAccorsi** [comment]
Actually, if you click not directly on folder name, you can't choose the new folder. But when you pass on a line, you see color line change.

It is possible to make the clickable area more bigger?

**Comment by PhilippeAccorsi** [comment]
Identique à #376
