### ISSUE TITLE
Bug: Cannot force-delete a user who owns a is_deleted=True space

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3685]
## Description and expectations

```sh
tracimcli delete user -f -l <login>
```
fails if the deleted user owns at least one workspace marked with `is_deleted=True`.

The command shall work in this case.

### How to reproduce

1. Create a user
2. Create a space with this user
3. Add a content in the space
4. Delete the space
5. Try to delete the user using the forementioned `tracimcli` command.

### Version information

- Tracim version: 3.1.4

## Screenshots

________________________________________________

## Diagnostic

Deleting the space content first modify it by setting its `cached_revision_id` to None. Thus a `content.modified` event is generated and this tries to access the space without the `show_deleted` option.

**Comment by grignards** [comment]
@PhilippeAccorsi I corrected the errors you had in your previous comment. But this requires to update tracim's code, there is no sql workaround this time.

**Comment by PhilippeAccorsi** [comment]
> @PhilippeAccorsi I corrected the errors you had in your previous comment. But this requires to update tracim's code, there is no sql workaround this time.

Ok. So to solve my problem before new release is done, can I work like this :
- create docker image from your branch and use this image on production ?
or
- it is more simple to just replace necessary file in my conteiner and restart uwsgi ?

**Comment by grignards** [comment]
You can replace the necessary files in the container. Restarting uwsgi is not necessary as `tracimcli` will read the updated files when launched.

**Comment by PhilippeAccorsi** [comment]
> You can replace the necessary files in the container. Restarting uwsgi is not necessary as `tracimcli` will read the updated files when launched.

Thanks for your reply. Replace file directly seem to be more simple on production ;)

**Comment by PhilippeAccorsi** [comment]
To use the fix on production: (like a hotfix)
- its just necessary to modify this files (necessary modification visble in https://github.com/tracim/tracim/pull/3686/files)
  -  backend/tracim_backend/command/cleanup.py
  -  backend/tracim_backend/lib/core/event.py
  - backend/tracim_backend/lib/core/mention.py
  - backend/tracim_backend/models/context_models.py

No restart/reload necessary to use tracimcli command.

**Comment by PhilippeAccorsi** [comment]
Done.
