### ISSUE TITLE
regression: to close sidebar you need to click on icon (before its work whis click on button area)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#3693]
## Description and expectations

- regression with button to close sidebar, after quick investiguate with @Skylsmoi we have find problem here: regression introduce when fix this issue https://github.com/tracim/tracim/pull/3638 and its here https://github.com/tracim/tracim/pull/3638/files#diff-80dab3c2de1deb73c7232c2f71514a8753dd649dcaa60c0a8ad75d212fb3ef67L40 (move `overflow hidden` create this regression)

### Version information

- Firefox 68.12.0esr (64 bits)
- Tracim 3.2.0

## Screenshots

![click_not_work](https://user-images.githubusercontent.com/25848257/96013531-a9d87680-0e45-11eb-8cc7-0b3fe8b8ee3b.gif)

________________________________________________

**Comment by gbonaspetti** [comment]
Fixed by #3768

**Comment by PhilippeAccorsi** [comment]
Done.
