### ISSUE TITLE
Bug/regression: scroll bar not integrated correctly in new sidebar

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#3694]
## Description and expectations

The scroll of sidebar is not correctly integrated.

### Version information

- Firefox 68.12.0esr (64 bits)
- Tracim 3.2.0

## Screenshots

Gif to show what is going on
![bug_side_bar](https://user-images.githubusercontent.com/25848257/96095185-90c7d800-0ece-11eb-98fa-b1931087245b.gif)

________________________________________________

**Comment by gbonaspetti** [comment]
This issue is fixed by https://github.com/tracim/tracim/issues/3725

**Comment by PhilippeAccorsi** [comment]
Done.
