### ISSUE TITLE
Bug: servdev feature is broken

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#3696]
## Description and expectations

The command `yarn run servdev` is broken.
It produces js error at runtime.
I have dig into it and there are 2 issue :
1. the frontend/dist/index.html file doesn't contain the new `GLOBAL_excludedNotifications` variable
 1.1. this is easy to fix
2. after fixing the above, another issue appears: the endpoint `/api/users/1/live_messages` returns http 401
  2.1. it appears the cookies aren't send with the request which would explain the the 401

### How to reproduce

1. just run `yarn run servdev`
2. add the line `GLOBAL_excludedNotifications = ''.replace(/\s/g, '')` in `frontend/dist/index.html` below `GLOBAL_primaryColor = '#7d4e24'`

### Version information

I have tested in 3.1.4 up to date with develop.
The issue was first reported the 2020-08-28, it was around version 3.0.3 and 3.0.4.

## Diagnostic

The 1. is only the fact that the new global variable wasn't added to the index file used by the servdev command
The 2. seems to come from the cookies not sent.

## Implementation

- [x] add the definition of `GLOBAL_excludedNotifications` in `frontend/dist/index.html`
- [x] move `LiveMessageManager` to `tracim_frontend_lib`
- [x] ensure `LiveMessageManager` is created in app servdevs by initializing it in their respective `index.dev.js`

**Comment by PhilippeAccorsi** [comment]
Done.
