### ISSUE TITLE
Bug: On developement build, React warns about the usage of the props "childrenKey"

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#3698]
## Description and expectations

When using development build of React, eg. using `servdev`, React warns about the usage of the props `childrenKey`

### How to reproduce

Run `yarn run servdev`.
For now, it doesn't work. See: https://github.com/tracim/tracim/issues/3696 for workaround.

## Diagnostic

Copying the warning here:
```
Warning: React does not recognize the `childrenKey` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `childrenkey` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

The `childrenKey` props is used by the `<DropdownMenu />` component that uses it to get the key to pass to its children.

- To get rid of the warning, the easy fix is to rename the props.

But I think this component implements a wrong patterns:
`<DropdownMenu />` expects its children to have a props `childrenKey` but this isn't documented anywhere. Neither in a comment nor in the PropTypes.
In the `<AdminLink />` component (in frontend), we can see that it forces to add the `childrenKey` property to a component `<Link />`. But this props isn't part of the `<Link />` component spec.

A better way of implementing `<DropdownMenu />` would be to make him expects only `<DropdownMenuItem />` has children. This can be done using PropTypes.
So it's the developer's role to wrap each children in a `<DropdownMenuItem />` to avoid doing it automatically in `<DropdownMenu />`

**Comment by raphj** [comment]
Closed, as this is fixed now.
