### ISSUE TITLE
Flash messahe HTML not deleted

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#37]
When flash message hide itself, html code still is in html:

![screenshot - 03142016 - 12 22 43 pm](https://cloud.githubusercontent.com/assets/1104637/13743010/95e1d7fa-e9df-11e5-80e7-82e38f6f310f.png)

**Comment by Skylsmoi** [comment]
see https://github.com/tracim/tracim/commit/8542e0f1e6d12218ee0320d4dba40999fbfc4a57
