### ISSUE TITLE
Feat: Allow user to leave space

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3706]
## Feature description and goals

Since the users have an option to join spaces (https://github.com/tracim/tracim/issues/3587) they should have the option to leave. 

- [x] This option will be in the My Account page in place of the red X of the mockup below:

![Capture d’écran de 2020-10-16 13-16-22](https://user-images.githubusercontent.com/35422692/96252230-ede88a00-0fb1-11eb-968e-95ea8243e9cf.png)

And it should be a (non primary) button with the icon `fa-sign-out` and the label "Leave space" with the normal font color.

- [x] When we clicking on this button, a confirmation popup should appear (like when we delete a space).
- [x] The option "Spaces and notifications" should be visible even if the notifications by email are deactivated, but the notification column should not be visible in this case.
- [x] It should be renamed "Spaces"

## Translations

|English|French|Portuguese|
|--|--|--|
|Leave space|Quitter l'espace|Deixar espaço|
|Are you sure you want to leave the space?|Voulez-vous vraiment quitter l'espace ?|Tem a certeza de que quer deixar o espaço?|

**Comment by grignards** [comment]
Should we have another column header *Leave Workspace* like we have for space/role/notification?

**Comment by raphj** [comment]
I'd like a column "Leave Space" yes, or even better I think, a button "Leave space" on each row. What do you think?

**Comment by gbonaspetti** [comment]
>  The option "Spaces and notifications" should be visible even if the notifications by email are deactivated, but the notification column should not be visible in this case.

Should we rename "Spaces and notifications" to "Spaces"?

**Comment by celiamgtt** [comment]
The icon should be the 'log out' icon ;) I like the idea to have a 'leave space button' (with the icon).
<img width="249" alt="Capture d’écran 2020-10-20 à 09 19 08" src="https://user-images.githubusercontent.com/50453784/96553385-5f2b8400-12b5-11eb-9803-daef95b319f2.png">

**Comment by lebouquetin** [comment]
> Should we rename "Spaces and notifications" to "Spaces"?

Looks logical

> Should we have another column header Leave Space like we have for space/role/notification?

I think a column header is not required, but a button on each line is the right solution (like sugested by @raphj )

Note: the leave feature must generate a waring like @celiamgtt suggested during last UI meetup

**Comment by raphj** [comment]
This branch requires commit f3f4971fa3e3f8e015626051fdd4eade5d6b79ba.
for manual tests, the branch to use is test_feat/3706__leave_spaces since this commit is not yet merged in develop.

**Comment by grignards** [comment]
A small comment: it is possible to click the "Leave space" button even if the user doing it is the last space manager of the selected space. It leads to a back-end error which is displayed as a rather generic message "An error ocurred…".

**Comment by raphj** [comment]
> A small comment: it is possible to click the "Leave space" button even if the user doing it is the last space manager of the selected space. It leads to a back-end error which is displayed as a rather generic message "An error ocurred…".

Indeed, thanks. @lebouquetin should we fix this now?

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
