### ISSUE TITLE
Feat: Implement HTML preview endpoints for contents

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3710]
## Feature description and goals

Previewing contents using HTML can be useful for many kinds of contents, and is needed for threads and html-documents to implement #3657.

- [x] Add a `GET /api/workspaces/{workspace_id}/threads/{content_id}/preview/html/{filename:[^/]*}` endpoint that will return the first comment of the thread as an HTML file
- [x] Add a `GET /api/workspaces/{workspace_id}/html-documents/{content_id}/preview/html/{filename:[^/]*}` endpoint that will return the entire content of the document as an HTML file

### `/api/workspaces/contents/{content_id}/preview` or specialized versions?

A generic endpoint seems simpler but requires knowledge of the different content types (threads/files/html documents) in the core Tracim code. Currently the core code does not have a knowledge of the existing content types as they are implemented in separate 'applications'.

We'll first implement this html preview as specialized enpoints as we must progress quickly, a technical debt issue has been created to address this: #3744

## Time Estimation

2 man.days.

## Implemented solution

- Return html preview  for both thread and html-document in a similar way as other preview (similar api) using ByteIO file Objet in order to be able to use similar mecanism as existing for other files. 
- use first comment content for thread and description/raw_content for html-content as html preview

**Comment by raphj** [comment]
What about `/api/workspaces/contents/{content_id}/preview?format=html` ?

**Comment by lebouquetin** [comment]
> Design choices

@grignards in order to allow a generic endpoint, the core should/would implement a delegate pattern to applications. I dont know the work required for doing this but this would be the right way, I think.

The preview endpoint already allow to preview a given revision id

**Comment by lebouquetin** [comment]
@raphj there are two subjects for a generic endpoint:

- content type
- preview type

**Comment by raphj** [comment]
I pretty much like the ability to add a filename at the end of the previews (`{filename:[^/]*}`), because if allows using wget to download the preview and have a cute filename. But how should it be used in the backend? just ignored?

**Comment by grignards** [comment]
> I pretty much like the ability to add a filename at the end of the previews (`{filename:[^/]*}`), because it allows using wget to download the preview and have a cute filename. But how should it be used in the backend? just ignored?

I think it is used with the `Content-Disposition` header.

**Comment by grignards** [comment]
> > Design choices
> 
> @grignards in order to allow a generic endpoint, the core should/would implement a delegate pattern to applications. I dont know the work required for doing this but this would be the right way, I think.

I'll check whether delegating to applications is easy or not.

**Comment by inkhey** [comment]
This seems a good first step to make things works.
This is what i suggest to make things consistent for later (using preview_generator):

- add a specific preview_generator builder and a specific mimetype for note and thread, that handle only html preview (at first) and adapt current code to use preview_generator instead of current code, this mean be able to pass a file path with the note/thread content.
- add "has_*_preview" for all types of content schema in endpoint, not only file or refactor this into something a bit more dynamic (list of preview type supported ? like ['jpeg','html','pdf'] )
-  add all preview endpoints available for all (or almost all, doesn't really make sense for folder) type of content, the only difference between note, thread and file is that for note and thread the path given to preview_generator is not stored the same way. We do rely on schema to know if the preview does exist ("has_*_preview" info).

**Comment by inkhey** [comment]
Current preview endpoints are: 

pdf
```
GET /api/workspaces/{workspace_id}/files/{content_id}/preview/jpg/allowed_dims
GET /api/workspaces/{workspace_id}/files/{content_id}/preview/jpg/{filename:[^/]*}
GET /api/workspaces/{workspace_id}/files/{content_id}/preview/jpg/{width}x{height}/{filename:[^/]*}
GET /api/workspaces/{workspace_id}/files/{content_id}/revisions/{revision_id}/preview/jpg/{width}x{height}/{filename:[^/]*}
```

jpg
```
GET /api/workspaces/{workspace_id}/files/{content_id}/preview/pdf/full/{filename:[^/]*}
GET /api/workspaces/{workspace_id}/files/{content_id}/preview/pdf/{filename:[^/]*}
GET /api/workspaces/{workspace_id}/files/{content_id}/revisions/{revision_id}/preview/pdf/full/{filename:[^/]*}
GET /api/workspaces/{workspace_id}/files/{content_id}/revisions/{revision_id}/preview/pdf/{filename:[^/]*}
```

To be consistent in api we do need, 4 endpoints (not just 2):
```
GET /api/workspaces/{workspace_id}/threads/{content_id}/preview/html/{filename:[^/]*}
GET /api/workspaces/{workspace_id}/threads/{content_id}/revisions/{revision_id}/preview/html/{filename:[^/]*}
```
```
GET /api/workspaces/{workspace_id}/html-documents/{content_id}/preview/html/{filename:[^/]*}
GET /api/workspaces/{workspace_id}/html-documents/{content_id}/revisions/{revision_id}/preview/html/{filename:[^/]*}
```

**Comment by inkhey** [comment]
@grignards i do suggest to put this issue in todo and make it work for activity feed, in a second time we can improve them to make this more consistent (revision specific preview, preview_generator integration, etc...)

**Comment by raphj** [comment]
This looks good to me

**Comment by grignards** [comment]
> @grignards i do suggest to put this issue in todo and make it work for activity feed, in a second time we can improve them to make this more consistent (revision specific preview, preview_generator integration, etc...)

I had a look to see if delegating the preview to backend apps from generic `contents` API seems feasible and I think it is without a major cost. But doing it now is longer as I would remove the content-type specific preview APIs if we delegate (so front-end changes too). So I agree to postpone those changes, I'll write an issue about this technical debt.

**Comment by PhilippeAccorsi** [comment]
@inkhey tests are be done in this issue ?

**Comment by inkhey** [comment]
> @inkhey tests are be done in this issue ?

No, it wasn't required. This is just a backend ticket and feature was already tested in a more complex case (with frontend), so, we can close this issue.

**Comment by PhilippeAccorsi** [comment]
Thanks for your answer.
Done.
