### ISSUE TITLE
Bug: sidebar's active space is not very readable for all users

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#3725]
## Description and expectations

- underlined text is hard to read for astigmat people
- without underline, bold text is not enough

## Expected:

- [x] remove underline of active space
- [x] add a primary color border of 5 pixels on the selected space
- [x] lighten the background to `#595959` (instead of `#333333`)
- [x] hide scroll bar in all browsers (see #3694)
- [x] fix dropdown menu that despawn on mouse out

## Examples

Currently on Tracim 3.2.0:

![image](https://user-images.githubusercontent.com/907161/96899968-d87fce00-1491-11eb-9c1c-0eefb089cf6e.png)

Proposal:

![image](https://user-images.githubusercontent.com/907161/96900012-e6355380-1491-11eb-97ad-a2eab2725199.png)

Activating a child space:

![image](https://user-images.githubusercontent.com/907161/96900928-eaae3c00-1492-11eb-8446-e2e259455aea.png)

**Comment by lebouquetin** [comment]
@gbonaspetti @raphj @grignards I'd like to have a chat about doing this in the 3.2.1 release

**Comment by Skylsmoi** [comment]
can this issue include the fixes for the visible scrollbar at the right and the outline property that spaces have in the sidebar when they are focused ?

**Comment by gbonaspetti** [comment]
> can this issue include the fixes for the visible scrollbar at the right and the outline property that spaces have in the sidebar when they are focused ?

I agree, we can, I think it will add +- 1/2h of development, @lebouquetin ok for you?

**Comment by raphj** [comment]
I think we should keep the outline, this is an accessibility feature (and allows navigating the sidebar with the keyboard)

**Comment by gbonaspetti** [comment]
> I think we should keep the outline, this is an accessibility feature (and allows navigating the sidebar with the keyboard)

I agree we should allows navigating the sidebar with the keyboard but for me the focus should be displayed with a change in the background, not with an outline, to keep the same behavior if we are navigating with the keyboard and the mouse.

**Comment by raphj** [comment]
This could be a lighter background :-)

**Comment by Skylsmoi** [comment]
there is also the issue about the dropdown menu that despawn on mouse out

**Comment by gbonaspetti** [comment]
> there is also the issue about the dropdown menu that despawn on mouse out

It seems also easy to fix, it adds at maximum 1h to dev

**Comment by lebouquetin** [comment]
> can this issue include the fixes for the visible scrollbar at the right and the outline property that spaces have in the sidebar when they are focused ?

:ok_hand: 

> I think we should keep ~~the outline, this is~~ an accessibility feature (and allows navigating the sidebar with the keyboard)
> (or keep a visible clue that tells which link is focused)

I agree; nevertheless the first target is "largest community" (not deficient) and also deficient people. underline is an issue for astigmatic people (based on direct experimentation), so this is not the right way to implement accessibility.

I'm not sure navigating by keyboard in tracim is enough for accesibility (I mean... there are probably plenty of things that do not work that I'm not sure allowing keyboard navigation in the sidebar is usefull).

Anyway, you can do something for this but first is to define what.

> there is also the issue about the dropdown menu that despawn on mouse out

:ok_hand:

**Comment by raphj** [comment]
tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
