### ISSUE TITLE
Bug: Join space button "Request access" becomes "Request sent" without any user interaction

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3748]
## Description and expectations

As an administrator it can happen that the "Request access" button changes to "Request sent" without clicking on it.

### How to reproduce

1. Log as a user
2. Create an ON_REQUEST space
3. Log as an administrator
4. Go to join space
5. In another browser session, log as another user, go to "join space" then request access for the newly created space
6. The "Request access" button in the administrator session becomes "Request sent"

Expected behavior: The "Request access" button in the administrator session shall not change.

### Version information

- Tracim version: 3.2.1 rc1

## Screenshots

________________________________________________

## Diagnostic

The space subscriptions are added to the user's subscription list without checking if their subject/author is the current user.
In `ReduxTlmDispatcher.js`.

## Prerequisites

None

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
