### ISSUE TITLE
Bug: Sidebar dropdown menu not visible all the time on the phone

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3749]
## Description and expectations

The dropdown menu doesn't work well when you are in a cell phone, it's not visible by default, but as soon as you click on the space it appears and it doesn't disappear anymore. It should be visible all the time.

### Version information

- Tracim version: v3.2.1
- Web browser: Google Chrome
- Device / System: Redmi Note8
________________________________________________

**Comment by grignards** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
