### ISSUE TITLE
Bug: Creating a user fails with OPEN spaces + autoinvite and parent_access plugins enabled

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3750]
## Description and expectations

Creating a user with OPEN spaces + autoinvite and parent_access plugins enabled, results in a 500 error from backend:

```
(psycopg2.errors.UniqueViolation) duplicate key value violates 
unique constraint "pk_user_workspace"↵DETAIL: Key (user_id, 
workspace_id)=(316, 134) already exists.↵↵[SQL: INSERT INTO 
user_workspace (user_id, workspace_id, role, do_notify) VALUES 
(%(user_id)s, %(workspace_id)s, %(role)s, %(do_notify)s)]↵[parameters: 
({'do_notify': True, 'user_id': 316, 'role': 8, 'workspace_id': 134}, 
{'do_notify': True, 'user_id': 316, 'role': 2, 'workspace_id': 137}, 
{'do_notify': True, 'user_id': 316, 'role': 8, 'workspace_id': 134}, 
{'do_notify': True, 'user_id': 316, 'role': 2, 'workspace_id': 135})]↵
(Background on this error at: http://sqlalche.me/e/13/gkpj)"
```

________________________________________________

## Diagnostic

Comes from an interaction between the 2 plugins, when autoinvite is disabled adding a user works.
Appears when there is a hierarchy of 3 spaces:

one parent space
  one OPEN child space
  another OPEN child space

In this case the parent access plugin tries to add twice the user in the parent space.
## Prerequisites

None

**Comment by raphj** [comment]
tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
