### ISSUE TITLE
Feat: Flash message when joining or requesting access to a space

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3751]
## Feature description and goals

- [x] When joining an OPEN space, a flash message should inform the user that they've successfully joined the space
- [x] When requesting access to an ON REQUEST space, a flash message should inform the user that their request will be managed by an space manager

## Translations

|English|French|Portuguese|
|--|--|--|
|You joined this space|Vous avez rejoint cet espace|Você juntou-se a este espaço|
|Your request to join {{space}} will be handled by a space manager. The result will be shown on the notification wall.|Votre demande pour rejoindre {{space}} sera traitée par un responsable. Le résultat sera affiché sur le mur de notification.|O seu pedido de acesso ao {{space}} será processado por um gestor do espaço. O resultado será mostrado no muro de notificação.|

**Comment by raphj** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
