### ISSUE TITLE
Bug: The add in ancestors plugin (parent_access) stops as soon as the user is already a member of an ancestor.

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3752]
## Description and expectations

The add in ancestors plugin (parent_access) stops as soon as the user is already a member of an ancestor and therefore the user is not added as a member of all ancestors in this case.

### How to reproduce

If we consider A → B → C → D → E as a tree: I am already a member of A and C and someone adds me to E, I will be added to E and D, but not to B.

________________________________________________

**Comment by raphj** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
