### ISSUE TITLE
Bug sur la treeview - pas claire dans l'utilisation pour déplacer des dossiers

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#376]
A voir avec moi quand tu l'attaques

**Comment by Skylsmoi** [comment]
it seems that the issue does not exists anymore:
We can clearly see which line is selected and which line is "mouse hovered"

**Comment by PhilippeAccorsi** [comment]
Actually, if you click not directly on folder name, you can't choose the new folder. But when you pass on a line, you see color line change.

It is possible to make the clickable area more bigger?

**Comment by tracim** [comment]
Closed with https://github.com/tracim/tracim/pull/382
