### ISSUE TITLE
Bug: The join space list does not have a hover effect

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3760]
## Description and expectations

The join space list items do not have a hover effect like the space list in the user settings, nor a gray background on odd items.

For better consistency and ease of use it should have them too.

### How to reproduce

1. Go to Join space
2. Move the mouse cursor over one space

### Version information

- Tracim version: 3.2.1 rc1

**Comment by grignards** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
