### ISSUE TITLE
Bug: All users are notified of the member changes of OPEN/ON_REQUEST spaces

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3763]
## Description and expectations

All users get the member added/removed notifications for OPEN and ON_REQUEST spaces.

The only users who should get them are the space members and instance administrators.

### How to reproduce

1. Create an OPEN/ON_REQUEST space
2. Add a user in it
3. Log as a user who is not member of the created space
4. Open the notification panel

### Version information

- Tracim version: 3.2.1 rc1

**Comment by raphj** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
