### ISSUE TITLE
Bug: "Leave space" buttons have no fixed height

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3765]
## Description and expectations

"Leave space" buttons have no fixed height and therefore bug in small height screens.

## Screenshots

![Screenshot from 2020-10-29 10-01-05](https://user-images.githubusercontent.com/35422692/97696959-a16b7700-1aa6-11eb-8f90-d89b254846e0.png)

**Comment by raphj** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
