### ISSUE TITLE
Bug: The button to close the sidebar is displaced

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3768]
![image](https://user-images.githubusercontent.com/3817365/97705258-12fdf200-1ab4-11eb-9b60-1d4dcf017a9d.png)

On a phone (Redmi Note 8T, chrome) :

![image](https://user-images.githubusercontent.com/3817365/97705216-0083b880-1ab4-11eb-853a-f8212cb40246.png)

This seems to happen while doing some actions like creating a space.

# Related and also fixes

https://github.com/tracim/tracim/issues/3693

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
