### ISSUE TITLE
Bug: The border of an active space moves the name of the space.

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3771]
## Description and expectations

The border of an active space moves the name of the space. Since the character shifts, it can be confused with a sub-space of lower rank (in the image below Sous⁵ and Sous⁵ child are on the same level, both children of Sous⁴ child).

![Screenshot from 2020-10-30 16-17-36](https://user-images.githubusercontent.com/35422692/97723967-a511f480-1acc-11eb-91f6-36eebb128297.png)

Related issue to fix: `<span>` elements are children of <ul> and parents of `<li>` elements in the sidebar.

To do:
 - [x] fix the margin
 - [x] remove the `<span>`

**Comment by grignards** [comment]
Tested on branch.

**Comment by gbonaspetti** [comment]
After testing, this issue was not completely fixed.

**Comment by raphj** [comment]
tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
