### ISSUE TITLE
Bug: space creation that triggers addition of the user to a parent space shows this space instead

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3772]
![Intégration 3 2 1_rc1 - bug pour rejoindre un espace](https://user-images.githubusercontent.com/3817365/97726298-5dd93300-1acf-11eb-9916-90e3bd075bab.gif)

## Implemented solution

The code assumed that when a  "created member role" TLM with both the new member the TLM's author being the connected user arrives, this TLM is a space that the user joined from the UI by clicking "Join space". It therefore set the current URL to the dashboard of the new space.

But this assumption is only true if not auto join plugins are enabled, which can add the user to several spaces at the same time.

The implemented solution is as follows:
 - The "created member role" TLM no longer redirects to the new space. This fixes the issue with the next point.
 - when the POST request to join a space X succeeds, the user is redirected to space X
 - when the URL changes and this URL is not in the same space as before, the item of the space in the sidebar is scrolled into view if it's not visible. As a side effect, this mechanism works everywhere else: if the user clicks on a notification of another space, the item of the space will also be scrolled into view

## Time Estimation

Remaining 1man.day.

**Comment by raphj** [comment]
Apparently not 100% reproductible.

I did see in firefox that joining space B child of space A opened A, then B, and then A again.

**Comment by raphj** [comment]
To test:
 - enable all the backend plugins (`cd backend; ln -s official_plugins plugins`)
 - create an open space, and a child open space of this space with an admin user
 - with a regular user:
    - create a lot of spaces so the sidebar is scrollable
    - join the child space with a regular user
    - the opened space should be the space and the corresponding item in the sidebar should be visible

**Comment by inkhey** [comment]
tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
