### ISSUE TITLE
Bug: Vendors are actually still bundled with apps

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3776]
## Description and expectations

Some late changes to the PR to group vendors (#3016)  actually introduced a regression. Vendors are actually still bundled with apps. The only thing this PR improved is not bundling the frontend lib with each frontend component. 

To do:
 - build a list of vendors when building the vendors
 - use this list in webpack configurations

**Comment by raphj** [comment]
To test:

not sure there is much to test: the CI passes and there's not much we could break beyond what is already checked in the CI.
Make sure building the frontend and running Tracim is okay.

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
