### ISSUE TITLE
Fix: Only show one notification when accepted in a space instead of two

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3785]
## Description and expectations

Only show one notification when accepted in a space instead of two:
- [x] Show only "X added you at Y"

### Version information

- Tracim version: v3.1.0
- Web browser: any
- Version: any
- Device / System: any

## Screenshots

![image](https://user-images.githubusercontent.com/3817365/97962635-e698ed00-1db5-11eb-92d1-990e0151e384.png)

________________________________________________

**Comment by Skylsmoi** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
