### ISSUE TITLE
Bug: The space description is HTML interpreted in the dashboard and not in the Join space and the admin space screens

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3786]
We should interpret the HTML code of description in the join space screen and the admin space screens. In these screens, we should probably only show the text of the description (something akin to `domParser.parseFromString(description).documentElement.textContent`), since the description is in one line.

___

edited to remove the suggestion of not interpreting the html. This is not an option as per the next comment, and also because we introducted a WYSIWYG editor in the advanced dashboard screen to edit the space description, to it always produces HTML code

**Comment by lebouquetin** [comment]
@raphj there is no question about interpreting the HTML code of the space description: we MUST interpret it. This issue is "the HTML description must be interpreted in the short description".

**Comment by lebouquetin** [comment]
@grignards If you work on this issue, it should be in the 3.6 board, otherwise it is impossible to know what is being worked on.

**Comment by lebouquetin** [comment]
By the way, It looks like the implementation you did is not in harmony with my last comment :

- I write HTML must be interpreted
- Your MR is "convert html to text".

I think this need some discussion or at very least a comment explaining why you do like this.

**Comment by grignards** [comment]
> I think this need some discussion or at very least a comment explaining why you do like this.

I did it like that because the join space screen is designed to present a list, and the description is already shortened with `…` when too long. If we display the HTML as it is it would possibly disturb the display of the list (for example including images, or even a text in `<h1></h1>` tags.

**Comment by MariePrandstetter** [comment]
Done
