### ISSUE TITLE
Bug: space names disappear when someone join them in the admin space screen

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3787]
## Description and expectations

Space names disappear when someone join them in the admin space screen (see screenshot), it returns if you refresh the page.

### How to reproduce

1. Click on `Administration -> Spaces` at header
2. Ask someone to join a space
3. See the space name in the list disappear

### Version information

- Tracim version: issue seen in Tracim v3.2.1, but probably present since the implementation of TLMs

## Screenshots

![image](https://user-images.githubusercontent.com/3817365/97965381-8c4e5b00-1dba-11eb-9644-52214b350aa9.png)
________________________________________________

**Comment by Skylsmoi** [comment]
still visible in 3.6.0_rc1

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
