### ISSUE TITLE
Bug: X added X to space Y notifications should read "X joined space Y"

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3790]
## Description and expectations

When a user joins a space it creates a "X added X to space Y" notification.

Expected:
- [x] If the user_id is the same, the message should be "X joined space Y".

### How to reproduce

1. Create a open space
2. Ask someone to join your space
3. See notification wall

### Version information

- Tracim version: 3.1
- Web browser: all
- Device / System: all

### Translations

|English|French|Portuguese|
|-|-|-|
|X joined space Y|X a rejoint l'espace Y|X juntou-se ao espaço Y|
|unkown|inconnu|desconhecido|

**Comment by PhilippeAccorsi** [comment]
Tested on branch
![Screenshot_2021-01-14 (1) Painel · issue 3790 · Tracim](https://user-images.githubusercontent.com/25848257/104566700-3ade0a00-564e-11eb-9b47-7036ca547cb3.png)
![Screenshot_2021-01-14 (1) Tableau de bord · issue 3790 · Tracim](https://user-images.githubusercontent.com/25848257/104566702-3b76a080-564e-11eb-955d-b0d1ccda4ede.png)
![Screenshot_2021-01-14 (1) Dashboard · issue 3790 · Tracim](https://user-images.githubusercontent.com/25848257/104566703-3b76a080-564e-11eb-8360-a50ff167aa72.png)

**Comment by PhilippeAccorsi** [comment]
Done
