### ISSUE TITLE
Feat: remove from child spaces when removed from parent

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3799]
## Feature description and goals

Tracim has currently the possibility to make users members of ancestor spaces when they are added to a child space (see #3572). A complement to this functionality would be to remove a user from child space when he is removed from a parent space.

- [x] The implementation should be done in the a separate "plugin" (`official_plugins/tracim_backend_child_removal`).
- [x] Document the fact that it is recommended to activate this plugin and the `parent_access` one together.

## Prerequisites

None.

**Comment by raphj** [comment]
tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
