### ISSUE TITLE
Feat: Allow the default member role of a space to be changed

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3805]
## Feature description and goals

- [x] It should be possible to change the default role on the advanced dashboard.
- [x] The interface must be the same as the creation space popup (see _Interface_ section).
- [x] It should have a tooltip explaining what is the default role (see _Interface_ section).
    - Use same translations as creation space popup.

## Interface

![App](https://user-images.githubusercontent.com/35422692/98567331-195c4d00-22b0-11eb-8f95-665fc3e89780.png)

**Comment by raphj** [comment]
tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
