### ISSUE TITLE
Bug: Breadcrumbs need to be improved

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3809]
## Description and expectations

Everywhere in Tracim, breadcrumbs currently do not show the full path. They show the space, the app and the content name.
Other problem is that they don't handle big words:

![98917562-d4f9c880-24cc-11eb-9e67-4f243119866e](https://user-images.githubusercontent.com/35422692/98924054-b26bad80-24d4-11eb-831d-138851efb740.png)

Expected (frontend):
Tracim has two types of breadcrumbs: page related and content related.

![breadcrumbs_page](https://user-images.githubusercontent.com/35422692/101490903-4eb59280-3963-11eb-9e54-45bfc02c7b80.png)

![breadcrumbs_content](https://user-images.githubusercontent.com/35422692/101491077-989e7880-3963-11eb-95ad-f7aea3f3138f.png)

 - [x] Page related breadcrumbs should always have Home page in it. In small and medium screens (xs, sm and md) and if we have more than 5 layers, we show only the icon `fa-home`.
 - [x] The current page at page related breadcrumbs should not be clickable.
 - [x] All clickable elements should have a tootltip.
 - [x] If the breadcrumbs have more than 5 layers (with the home page, 4 without) we put non-clickable ellipsis between the space and last element name, e.g. `home > space > ... > folder > sub-folder > content` and it should have a tooltip with the whole path in this ellipsis.
 - [x] Breadcrumbs should always be in one line only. It should handle big words with ellipsis.
 - [x] The breadcrumbs should include folders, if pertinent.

Expected (backend):
 - [x] New endpoint `GET /api/workspaces/{workspace_id}/contents/{content_id}/path` that returns a ordered array with the path to the content. Something like this _(this is just an example, it can be changed/adapted during development. please update this description if the implementation is different)_:
```
{
  "items": [
    {
      "content_id": 42,
      "content_type": "folder",
      "label": "A folder"
    },
   {
      "content_id": 44,
      "content_type": "folder",
      "label": "A sub-folder"
    },
   {
      "content_id": 46,
      "content_type": "file",
      "label": "A file"
    }
  ]
}
```
## Work branch

fix/3809__improve_breadcrumbs

## Extra information

- In the `frontend/src/container/SearchResult.jsx` component of frontend we have the `getPath` function that gets the pathname of a content.

### Should we still show the content app in the breadcrumb?

Decision: No, the breadcrumbs should not have elements there are not navigable.

### Should we also show the space hierarchy in the breadcrumb?

Decision: It's a good idea, but it won't be implemented in this version. It should be better planned.

### Should the breadcrumb be always in a single line?

Decision: Yes.

### Should we move the breadcrumbs into the app when a content is open?

Decision: It's a good idea, but it won't be implemented in this issue. Currently the app header has no space and is in Tracim's roadmap to redesign it. (see https://github.com/tracim/tracim/issues/2594)

### Does this require backend development?

@grignards Having an endpoint (or always include the path in contents?) for this would be faster and less requests, if we do not care about performance the front should be able to reconstruct the path by calling the contents API recursively (and eventually the space API if we decide to include the space hierarchy).
 
Decision: Yes. 

## See also
 - https://github.com/tracim/tracim/issues/1699 (esp. https://github.com/tracim/tracim/issues/1699#issuecomment-491762451)
 - https://github.com/tracim/tracim/issues/1637

## Implemented solution:
Frontend:
- add CSS rules to breadcrumbs__home
- add notALink at current pages
- add a tooltip at Breadcrumbs component
- add check in breadcrumbslist size to display all items or `...`
- add a tooltip with the whole path in this ellipsis
- add CSS rules at breadcrumbs to display in one line only and handle big words with ellipsis.
- add a function at frontend_lib for folders at pages and a function at ContentActivityHeader for contents

Backend:
- add "/api/workspaces/{}/contents/{}/path" endpoint that return the content path of the content, in order to be able to generate breadcrumb.
- add content property to retrieve all recursive parent and to retrieve content path.
- test for  "/api/workspaces/{}/contents/{}/path"

**Comment by raphj** [comment]
> Should we also show the space hierarchy in the breadcrumb?

Yes, I think so

**Comment by inkhey** [comment]
Is this feature required for tracim 3.3 ?

**Comment by gbonaspetti** [comment]
I added the _Extra informations_ section at the descrition and one other question to be discussed: I think we should also move the breadcrumbs into the app.

> Should we still show the app in the breadcrumb?

I don't understand, what app?

>> Should we also show the space hierarchy in the breadcrumb?
>
> Yes, I think so, good point. Or this could be hidden by default and unfolded on demand (when clicking on a small button, say)

That's a good idea, something like this that expands when you click at (...): ![Screenshot from 2020-11-09 16-42-32](https://user-images.githubusercontent.com/35422692/98562777-b4522880-22aa-11eb-949a-d68cb2e34ce8.png)

> Is this feature required for tracim 3.3 ?

Is a "nice to have" not a "must have".

**Comment by grignards** [comment]
Shouldn't the behavior be : display as many path components (including sub-spaces) as enough space is available, if not hide the upper-levels paths until we can display (with possibility to display the full path with a tooltip)? And then rely on ellipsis overflow if the name of the content is too long?
Because having a `…` button to unfold will cause the same problems (either multi-line display or overflowing the container)

**Comment by inkhey** [comment]
I do think, a first good step to know how to deal with it is clarifying which information are really needed in breadcrumb.
As far i know:
- Breadcrumb is not content specific, we do have breadcrumb for workspace (which are recursive with the parent/children mecanism), and also for specific feature.
- Current needed information seems :
  - type of "step" (content/workspace/other) 
  - item id (content or workspace id or nothing).
In some case, it can make sense to have more content/workspace/other data in breadcrumb, if we do want to get them, we do need to clarify what we do really want or may want, in order to not make a decision that will make the breadcrumb hard to improve.

**Comment by gbonaspetti** [comment]
Sorry, I miss click in close.

@inkhey we have breadcrumbs in two contexts, linked to the page and linked to the content (each activity feed content has its own breadcrumbs). 
I think the information we need from backend is:
- for contents, all the path up to space (folders, sub-folders, ...)
So we have a endpoint that receive the content id and returns this path.

I think we can make a first version just with the space, without the tree, and that stays in one line: 
- ellipsis (...) for big words
- if the breadcrumbs has many layers we make the ellipsis (...) not clickable in the middle `space > ... > parent-folder > title`

**Comment by inkhey** [comment]
> Sorry, I miss click in close.
> 
> @inkhey we have breadcrumbs in two contexts, linked to the page and linked to the content (each activity feed content has its own breadcrumbs).
> I think the information we need from backend is:
> 
>     * for contents, all the path up to space (folders, sub-folders, ...)
>       So we have a endpoint that receive the content id and returns this path.

@gbonaspetti 
1. You also need the workspace hierarchy.
2. I'm not sure content_ids is enough if you want to be efficient. It mean you have to get all content in path to get all the information you really need : content name and content_type (url used for content does contains the app to use).

**Comment by gbonaspetti** [comment]
> > Sorry, I miss click in close.
> > @inkhey we have breadcrumbs in two contexts, linked to the page and linked to the content (each activity feed content has its own breadcrumbs).
> > I think the information we need from backend is:
> > ```
> > * for contents, all the path up to space (folders, sub-folders, ...)
> >   So we have a endpoint that receive the content id and returns this path.
> > ```
> 
> @gbonaspetti
> 
> 1. You also need the workspace hierarchy.
> 2. I'm not sure content_ids is enough if you want to be efficient. It mean you have to get all content in path to get all the information you really need : content name and content_type (url used for content does contains the app to use).
> 
> edit: i'm not sure to have understood, i need to know "what is a path" , you not only need id or just text, you need many data to be able to generate the path, that's need specification, but as i'm not frontend dev, i need clarification about what the frontend really need.

For a path we need a list of elements, ordered, if the element is a content (like folders) we need `workspace_id`, `content_type` and `content_id`, for space we need only its id.

**Comment by grignards** [comment]
> For a path we need a list of elements, ordered, if the element is a content (like folders) we need workspace_id, content_type and content_id, for space we need only its id.

Er… I think the frontend needs the labels too. So the returned structure of a `path` would be something like:
```json
{
  "items.": [
    {
      workspace_id: 1,
      entity_type: 'workspace',
      label: "My space"
    },
    {
      workspace_id: 1,
      content_id: 42,
      entity_type: 'content',
      content_type: 'file'
  ]
}
```
The `workspace_id` in contents could be left out (as the response includes the space the contents are in), but it does simplify things and doesn't cost a lot to return.

**Comment by inkhey** [comment]
> > For a path we need a list of elements, ordered, if the element is a content (like folders) we need workspace_id, content_type and content_id, for space we need only its id.
> 
> Er… I think the frontend needs the labels too. So the returned structure of a `path` would be something like:
> 
> ```json
> {
>   "items": [
>     {
>       "workspace_id": 1,
>       "entity_type": "workspace",
>       "label": "My space"
>     },
>     {
>       "workspace_id": 1,
>       "content_id": 42,
>       "entity_type": "content",
>       "content_type": "file",
>       "label": "A file"
>     }
>   ]
> }
> ```
> 
> The `workspace_id` in contents could be left out (as the response includes the space the contents are in), but it does simplify things and doesn't cost a lot to return.

2 points : 
1. We do return different object type in this list, are we really sure we do want to do this. We don't follow this pattern at all in tracim unless for TLM as far i know ?
2. We probably do need to get "path" of workspace too, no ? We do need to be really careful about workspace tree as the tree returned is user specific… because some user may be unable to know the full workspace tree. The tree given should be logical with the sidebar result.

**Comment by gbonaspetti** [comment]
> > > For a path we need a list of elements, ordered, if the element is a content (like folders) we need workspace_id, content_type and content_id, for space we need only its id.
> > 
> > 
> > Er… I think the frontend needs the labels too. So the returned structure of a `path` would be something like:
> > ```json
> > {
> >   "items": [
> >     {
> >       "workspace_id": 1,
> >       "entity_type": "workspace",
> >       "label": "My space"
> >     },
> >     {
> >       "workspace_id": 1,
> >       "content_id": 42,
> >       "entity_type": "content",
> >       "content_type": "file",
> >       "label": "A file"
> >     }
> >   ]
> > }
> > ```
> > 
> > 
> > The `workspace_id` in contents could be left out (as the response includes the space the contents are in), but it does simplify things and doesn't cost a lot to return.
> 
> 2 points :
> 
> 1. We do return different object type in this list, are we really sure we do want to do this. We don't follow this pattern at all in tracim unless for TLM as far i know ?
> 2. We probably do need to get "path" of workspace too, no ? We do need to be really careful about workspace tree as the tree returned is user specific… because some user may be unable to know the full workspace tree. The tree given should be logical with the sidebar result.

1. We can return only contents if we don't include the space.
2. My suggestion was "not do the space tree for now" I don't think it is a problem for a first version

**Comment by grignards** [comment]
> > > For a path we need a list of elements, ordered, if the element is a content (like folders) we need workspace_id, content_type and content_id, for space we need only its id.
> > 
> > 
> > Er… I think the frontend needs the labels too. So the returned structure of a `path` would be something like:
> > ```json
> > {
> >   "items": [
> >     {
> >       "workspace_id": 1,
> >       "entity_type": "workspace",
> >       "label": "My space"
> >     },
> >     {
> >       "workspace_id": 1,
> >       "content_id": 42,
> >       "entity_type": "content",
> >       "content_type": "file",
> >       "label": "A file"
> >     }
> >   ]
> > }
> > ```
> > 
> > 
> > The `workspace_id` in contents could be left out (as the response includes the space the contents are in), but it does simplify things and doesn't cost a lot to return.
> 
> 2 points :
> 
>     1. We do return different object type in this list, are we really sure we do want to do this. We don't follow this pattern at all in tracim unless for TLM as far i know ?

Indeed. Either we return `"content_id": None` for spaces items or return two separate lists:

```json
{
  "spaces": [
    { "..." }
  ],
  "folders": [
  ]
}
```

>     2. We probably do need to get "path" of workspace too, no ? We do need to be really careful about workspace tree as the tree returned is user specific… because some user may be unable to know the full workspace tree. The tree given should be logical with the sidebar result.

Yes, as the logic of building the tree is inside the frontend currently I'd keep it this way. It has the default of "leaking" not accessible space names but as we already leak their ids I do not think it is a real problem.

**Comment by raphj** [comment]
When is a word / label considered big? what is the threshold, and should the ellipsis be at the end or at the middle of the label?

**Comment by inkhey** [comment]
I do suggest endpoint like these, if we go for backend endpoints:
```
GET /api/users/{user_id:\d+}/workspaces/{workspace_id}/tree
GET /api/users/{user_id:\d+}/workspaces/{workspace_id}/contents/{content_id}/tree
```
we probably need to find a proper name than tree.
As these endpoint should iterate through workspace parent, we should iterate from the workspace to the last parent visible by the user (using same filter) and then reverse the list to follow the logical tree organisation, this way we are able to properly limit the result according to current access limitation.

**Comment by gbonaspetti** [comment]
> When is a word / label considered big? what is the threshold, and should the ellipsis be at the end or at the middle of the label?

For the threshold: I think the developer should do some tests, the goal is to stay in one line. Maybe the threshold that should be defined is when to put the middle ellipsis. I would say that with more than 5 layers we already put ellipsis. Always showing the space name. `home > space > ... > folder > sub-folder > content`
For the ellipsis: Always in the end. Always with a tooltip. :smile:

**Comment by lebouquetin** [comment]
Breadcrumb is not about a *tree* but about a *path*. So the APIs should be named *path*, not *tree*.

My feeling is the space and app parts of the breadcrum may be build on the frontend side (all informations are there), so, I'm pretty sure there is no need to return other things that path of a content.

For contents, as soon as we already have space information (and potentially parent space information), the only breadcrumb required is about folders and subfolders.

The goal is to distinguish the path of the view data. In case of an application the path is always space > app, then for a content it is `space > contents > folder1 > folder 2 > [...] > content label`

**Comment by lebouquetin** [comment]
@inkhey what is the result of the following endpoint:

```
GET /api/users/{user_id:\d+}/workspaces/{workspace_id}/tree
```

?

I do not see the interest of it.

**Comment by raphj** [comment]
tested on branch
