### ISSUE TITLE
BUG : with workspace deleted

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#381]
**At present:**

When you go to /home, you can see also all recently activity. But if you have delete one workspace, file present in this workspace, is present in recently activity. You can try to click on one, and you have error 404.
You can seen file in "not read" and workspace deleted in "My workspaces" (in this page, if you click on one deleted workspace, this error appear: "sqlalchemy.orm.exc.NoResultFound: No row was found for one()")

~~When you delete some workspace, you can go to  /admin/workspaces and seen the name of existing workspace  (you seen also the number of the workspace, and this value is not updated).~~

~~If you go to /admin/user/1  , you can see the name of deleted workspace. You can try to click for more information but this error appear: "sqlalchemy.orm.exc.NoResultFound".~~

**Expected:**

You can't see deleted folder/files information about this workspace deleted.

~~The workspace number is change to correct number (if you have 3 workspace and you delete 2 of this, the number of last workspace its normaly "1")~~

**Comment by PhilippeAccorsi** [comment]
At present:

When you go to /home, you can see also all recently activity. But if you have delete one workspace, file present in this workspace, is present in recently activity. You can try to click on one, and you have error 404.

Expected:

when something is deleted, you can't see any information about this.

**Comment by tracim** [comment]
@algooapy this is probably a missing filter in lib/workspace.py (by default, deleted workspaces should be filtered using sqlalchemy)

**Comment by PhilippeAccorsi** [comment]
@algooapy bug is solved for  /admin/workspaces and /admin/user

But not in home page. you can seen information about this deleted workspace in "Recent Activity", "My workspaces" and I think in "Not read".

I have updated first comment.

**Comment by PhilippeAccorsi** [comment]
Merge #420
