### ISSUE TITLE
Bug: Need to click twice to insert a picture in a note or an advanced comment, the first time

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3811]
## Description and expectations

The first time after loading a Tracim page someone wants to insert a picture using the TinyMCE WYSIWYG editor (in an advanced comment or a note), they need to click twice on the Insert picture icon.

When done a first time, only one click suffices. 

### How to reproduce

1. Open a Tracim page
2. create a note or start the edition of an advanced comment
3. try to insert a picture using the "insert picture" button of TinyMCE

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
