### ISSUE TITLE
Bug: None is not translated in create space popup to select parent of space

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#3820]
## Description and expectations

Missing translation in French and Portuguese in placeholder of create space popup (the translation works fine in dropdown).

![Screenshot_2020-11-09 Accueil · Unstable](https://user-images.githubusercontent.com/25848257/98521494-cbc1ef00-2273-11eb-9ac3-99a912baeba2.png)

### How to reproduce

- Create a new space

### Version information

Tracim 3.2.1

**Comment by inkhey** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
