### ISSUE TITLE
Feat: Add a personal activity feed

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3825]
## Feature description and goals

- [x] Add to the top of the sidebar a button for the activity feed. The personal activity feed will be accessible via sidebar or URL `/ui/activity-feed`.
- [x] In this first version, the personal activity feed will not have any customization, i.e. it will have the same contents as the activity feed per space without the space filter.

## Interface
_Obs: This interface example is only a template, not everything will be developed in this issue and some details can be changed according to the implementation._

![personal_activity_feed](https://user-images.githubusercontent.com/35422692/98664304-7c9abd80-234a-11eb-8ee6-36ddc28e6d82.png)

## Prerequisites

- https://github.com/tracim/tracim/issues/3824

**Comment by raphj** [comment]
should we go for `/ui/activity-feed` instead, so it is similar to the activity feeds of spaces?

I'm okay with the rest

**Comment by inkhey** [comment]
For the first step, endpoints /messages (or combinaison of /messages and /events depending on the solution choosen) here https://github.com/tracim/tracim/issues/3824) should allow to retrieve all the activity regardless of the space.

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
