### ISSUE TITLE
Feat: Add an action dropdown menu in the activities

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3827]
## Feature description and goals

With the exception of member and requests activities, each activity will have a contextual menu. Below is the list of options present in the menu and the actions performed when clicking on each option:
  - [x] Copy content link
       - When clicking "Copy content link" the link to the content's app is copied to clipboard and a flash message appears with the phrase "The link has been copied to clipboard".
  - [x] Open content
        - The icon should be the type icon
        - When clicking "Open content" the user is redirected to the content's app.

### Expected

- [x] Add a vertical-ellipsis button with the tooltip "Actions"
- [x] On click, opens a dropdown menu with the options above
- [x] It should be hidden at mobile

## Interface
_Obs: This interface example is onlya  template, not everything will be developed in this issue and some details can be changed according to the implementation._

![file](https://user-images.githubusercontent.com/35422692/99513993-8ac08d80-298b-11eb-93e9-1cdc2421141d.png)

## Translations
|English|French|Portuguese|
|-|-|-|
|Actions|Actions|Ações|
|Copy content link|Copier le lien du contenu |Copiar ligação do conteúdo|
|The link has been copied to clipboard|Le lien a été copié dans le presse-papiers|A ligaçao foi copiada para a área de transferência|
|Open content|Ouvrir contenu|Abrir conteúdo|

## Prerequisites

https://github.com/tracim/tracim/issues/3600

## Extra information

- The option "Add to my favorites" will be added in the future when the functionality is available.

**Comment by raphj** [comment]
I suggest: "See timeline" -> "Open the timeline"

I changed "was" to "has been", I think is more correct like this. I'm okay with the rest.

**Comment by grignards** [comment]
Shouldn't `Edit` be `Open` instead? As we do not provide a direct edition through this link (for example images…). For me `Edit` would be to open the content directly in edition mode (but we can only do that for html-documents/threads and possibly office documents currently).
And is the `Show history` button needed as it performs the same action as `Edit`? Perhaps adding it when it performs a different action?

**Comment by grignards** [comment]
And we cannot totally implement `Add to favorites` as this functionality does not exist. Or does this issue implies that we should implement it now?

**Comment by gbonaspetti** [comment]
> Shouldn't `Edit` be `Open` instead? As we do not provide a direct edition through this link (for example images…). For me `Edit` would be to open the content directly in edition mode (but we can only do that for html-documents/threads and possibly office documents currently).
> And is the `Open timeline` button needed as it performs the same action as `Edit`? Perhaps only implement it when it performs a different action?

I think the initial idea was when the user clicks on open timeline, the focus is in the comment zone, but I agree that it is not necessary since we already have the "Comment" button on the activity. I'll merge both in "Open content".

**Comment by gbonaspetti** [comment]
> And we cannot totally implement `Add to favorites` as this functionality does not exist. Or does this issue implies that we should implement it now?

You are right. I got ahead of myself when writing the issue :sweat_smile: , I will update the description.

**Comment by PhilippeAccorsi** [comment]
Done.
