### ISSUE TITLE
Feat: Add history of the latest modifications to the activities

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3828]
## Feature description and goals

If the user clicks on the last modification, a dropdown menu opens with the last 5 modifications. The items are not clickable.

## Interface

![historique](https://user-images.githubusercontent.com/35422692/98702884-3c076800-237b-11eb-8d8e-9a5989397e80.png)

## Prerequisites

- #3600 
- #3846 (backend issue)

## Implementation

The will be built by querying the `/messages` API as it is the only one having all needed operations (especially mentions). Use the parameter defined in #3846 to filter the returned messages.

**Comment by raphj** [comment]
The user is redirected to the content in the specific revision, right?

**Comment by gbonaspetti** [comment]
> The user is redirected to the content in the specific revision, right?

Unfortunately we can't do this with the current Tracim structure, but it is certainly a desirable improvement.

**Comment by raphj** [comment]
I'd suggest not to allow clicking on revisions then. What do you think?

**Comment by gbonaspetti** [comment]
> I'd suggest not to allow clicking on revisions then. What do you think?

I find it strange that it is the only dropdown menu that does not allow clicking. But as neither solution is ideal, both have their pros and cons, either one is good for me.

**Comment by grignards** [comment]
How do you plan to implement this? Through the messages/tlms we aren't guaranteed to get 5 items for each activity (unless we perform an additional call to messages but then we need a `content_id` filter). Through the `comments`/`revisions` we'd need to rebuild an compatible history.

**Comment by raphj** [comment]
I fear that allowing this dropdown to exist (and be clickable) without the ability to open specific revisions, users will start to distrust this menu and never use it even in the future when the feature is complete.

Shouldn't we implement access to specific revisions in this ticket, or prior to this ticket?

**Comment by gbonaspetti** [comment]
> How do you plan to implement this? Through the messages/tlms we aren't guaranteed to get 5 items for each activity (unless we perform an additional call to messages but then we need a `content_id` filter). Through the `revisions` API and already present comment list we'd need to merge them to build the history (if we go this way it could be the occasion to paginate the revisions).

For the TLMs I thought of a simple "if less than 5 add at the top, else add at the top and remove the lowest", for the loading I thought of using the `${apiUrl}/workspaces/${workspaceId}/${type}/${contentId}/revisions` endpoint and taking the last 5, but I agree that this pagination can be done in the backend

**Comment by gbonaspetti** [comment]
> I fear that allowing this dropdown to exist (and be clickable) without the ability to open specific revisions, users could start to distrust this menu and never use it even in the future when the feature is complete.
> 
> Shouldn't we implement access to specific revisions in this ticket, or prior to this ticket?

I'm ok with doing a first version without the click (I'll update the description) and analyze the cost of time/development/priority of redirecting to a revision.

**Comment by grignards** [comment]
> > How do you plan to implement this? Through the messages/tlms we aren't guaranteed to get 5 items for each activity (unless we perform an additional call to messages but then we need a `content_id` filter). Through the `revisions` API and already present comment list we'd need to merge them to build the history (if we go this way it could be the occasion to paginate the revisions).
> 
> For the TLMs I thought of a simple "if less than 5 add at the top, else add at the top and remove the lowest", for the loading I thought of using the `${apiUrl}/workspaces/${workspaceId}/${type}/${contentId}/revisions` endpoint and taking the last 5, but I agree that this pagination can be done in the backend

In fact we must do the last 5 through the `/messages` API as neither `comments` nor `revisions` do return mention events.

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
