### ISSUE TITLE
Feat: Add public profile

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3829]
## Feature description and goals

- [x] The public profile will be accessible via URL `/ui/users/{{user_id}}/profile` or via the header menu (see _Interface_ section, item _Public profile of other user and menu details_))
- [x] While the data is loading, the screen must have the forms presented in the Interface session and the Loading text preceded by the spinner icon with the fa-spin class.
- [x] Add a new option in the header menu that will redirect to the public profile of the logged user.
    - it will be the first option
    - label: My profile
    - icon: user-o
- [x] The profile will have a cover image. The cover image will be the image at _Interface_ -> _Default cover image_.
- [x] The avatar will be the same that we currently have at Tracim.
    - [x] Size big for xl/lg/md screens
    - [x] Size medium for sm/xs screens
- [x] The profile header will only have the avatar, the public name, the username, the breadcrumbs. The number of followers and following, the follow state, the follow button and the chat button will not be implemented in this issue.
- [x] The content of the profile is divided into two parts: "Information" and "Personal Page". This issue will only make the space for the two parts:
    - The first part will be filled at #4038 
    - The second at #4039 
    - [x] For md/lg/xl screens the Information takes about 30% and Personal Page about 70% (not counting the margins between them).
    - [x] For xs/sm screens they have width 100% and Information is displayed first.

## Translations

|English|French|Portuguese|
|-|-|-|
|My profile|Mon profil|Meu perfil|
|Information|Informations|Informações|
|Personal Page|Page personnelle|Página pessoal|
|{{user}}'s profile|Profil de {{user}}|Perfil de {{user}}|
|Unknown user|Utilisateur inconnu|Utilizador desconhecido|
|Loading|Chargement|Carregando|

## Interface
_Obs: These interface examples are only templates, not everything will be developed in this issue and some details can be changed according to the implementation._

- Loading profile

![public_profile_loading](https://user-images.githubusercontent.com/35422692/100886303-f63e4b00-34b3-11eb-9ea2-998e1049efcb.png)

- Public profile of the logged user

![public_profile_before_edit](https://user-images.githubusercontent.com/35422692/100880595-33530f00-34ad-11eb-9d6a-a72a701e9ec8.jpg)

- Public profile of the logged user in edition mode

![public_profile_after_edit](https://user-images.githubusercontent.com/35422692/100776027-4fe73c80-3404-11eb-83ab-d37e8d3466ed.jpg)

- Public profile of other user and menu details

![public_profile](https://user-images.githubusercontent.com/35422692/100880616-3817c300-34ad-11eb-9753-42af8e06aafc.jpg)

- Mobile view

![public_profile_mobile (1)](https://user-images.githubusercontent.com/35422692/104181037-65418480-540e-11eb-94d4-34cea6a5069f.jpg)

- Default cover image

![default_image](https://user-images.githubusercontent.com/35422692/100726551-61f5ba80-33c5-11eb-870d-03ce89313cb7.jpg)

**Developer note**: After testing during the development some details are changed in the interface
- The background color is the same that other pages
- A border was added at each part to have the same design that activity feed
- Mobile version has normal text, not bold

## Prerequisites

- #2935
- #4004 
- #4027 
- #3842 

## Extra information 
- The number of followers and following  (https://github.com/tracim/tracim/issues/3915), the follow state (https://github.com/tracim/tracim/issues/3909), the follow button (https://github.com/tracim/tracim/issues/3910) and the chat button will not be implemented in this issue.
- The possibility of changing the cover image (https://github.com/tracim/tracim/issues/3833) and the avatar (https://github.com/tracim/tracim/issues/3905) will be implemented in another issue.

## Discussed
1. If you are viewing someone's profile and the person changes their profile, should the change be made in real time or should there be a "Refresh" button?

**Decision:** The change will not be made in real time, the user will only see the changes if they refresh the page.

## Time Estimation
5 man/day (using JSONSchema as CustomForms)

**Comment by inkhey** [comment]
For the backend part, we currently do not have the field required in database to handle such feature.
There is already a subject about allowing custom data to user:
https://github.com/tracim/tracim/issues/2935
We do need to clarify how we do handle this properly.

1. Which one of the field here are mandatory for any tracim instance, which one should be "dynamically" handled to allow custom user profile per instance ?
2. How do we get theses field (endpoint user or other one ?)
3. How do we get user statistics (specific endpoint), who can access to them ?

**Comment by inkhey** [comment]
as we will not cover in the first version:
- the subscriptions mecanism
- custom avatar and cover image
- chat
- subscription "state"

The data needed for a first versions are:

**Information Bar:**
- [X] public_name (already available)
- [X] username (already available)
- [X] breadcrumb (can be automatically generated from the username)
**Information Field**
- [ ] Custom instance field for profil : related to https://github.com/tracim/tracim/issues/2935
- [X] registration date : the `created` field of user is ok. :warning:  this is the creation of the user in tracim, so for ldap user it mean first connexion date.
- [ ] numbers of publications (number of content revision ? number of content creation ?)
- [ ] numbers of space of publication (need clarification if it mean user number of space or only the one the user has done publication).
**Personnal page.**
- [ ] personnal page field (html ?)

**Comment by inkhey** [comment]
Naïve first approach for endpoint : 

**New endpoints :** 

GET `/api/users/{user_id:\d+}/public_profile`
return 200 with this body:
```json
{
  "avatar_url": "/api/asset/avatars/john-doe.jpg",
  "created": "2020-11-16T13:43:22.089Z",
  "public_name": "John Doe",
  "user_id": 3,
  "username": "My-Power_User99",
  "statistics": {
    "publication_numbers": 12,
    "space_publication_numbers": 3
  },
  "infos": {
    "country": "England",
    "Organization": "Algoo Inc" 
  },
  "page": "<h1> my page ! </h1>"
}
```

PUT `/api/users/{user_id:\d+}/page`
```json
{
  "page": "<h1> my page ! </h1>"
}
```
-> Return 204
PUT `/api/users/{user_id:\d+}/infos` 
```json
  "infos": {
    "country": "England",
    "Organization": "Algoo Inc" 
  },
}
```
-> Return 204

PUT `/api/` 
```json
  "infos": {
    "country": "England",
    "Organization": "Algoo Inc" 
  },
}
```
-> Return 204

**updated endpoint:**
- added user_infos_fields, need clarification about how far we want to details validation of fields.

GET /api/system/config
```
{
  "collaborative_document_edition": {
    "software": "string",
    "supported_file_types": [
      {
        "associated_action": "edit",
        "extension": "odt",
        "mimetype": "application/vnd.oasis.opendocument.text",
        "url_source": "http://localhost:9980/loleaflet/305832f/loleaflet.html"
      }
    ]
  },
  "content_length_file_size_limit": 0,
  "email_notification_activated": true,
  "email_required": true,
  "instance_name": "string",
  "new_user_invitation_do_notify": true,
  "webdav_enabled": true,
  "webdav_url": "string",
  "workspace_size_limit": 0,
  "workspaces_number_per_user_limit": 0
  "user_infos_fields": {
    "country": { "type":"string"},
    "Organization": {"type":"string"} 
  },
}
```

**Comment by inkhey** [comment]
After thinking about this, i found a contradiction between the fact the user profile should be public and the how the  know_users endpoint work.

The known user endpoint does work in a way to avoid user to know the full list of user, if user have all public profile,this check is not really useful anymore. In some case, it can be voluntary, but in some other, it's not wanted, especially in case some user want to use different space with different people but without any link between them.

After reading theses two ticket about known_members:
- https://github.com/tracim/tracim/issues/2486
- https://github.com/tracim/tracim/issues/3635

The solution i do currently see, is :
- refactoring known_members code to be able to get all user known_members easily, splitted the autocomplete and filtering part outside (to always handle the current usage of known_members which are based on autocomplete mecanism).
- use the base known_members result as filter mecanism to make`/api/users/{user_id:\d+}/public_profile` visible only if current user has user_id in his known_members list.

This means:
1. if we want all public profile to be visible to any registered user (including simple user) we have to set `known_members.filter = false`
2. regardless of known_members filtering, if user profile (as profile level like admin, user, trusted-user) > user, user should be able to see all public profil (meaning anyone able to create a space can see all public profile)
3. If filtering is enabled, simple user can see public profil of only user who participate to a same space as him.

This is a bit better than the current proposal has this permit to handle case of simple user that should not be able to see other user (which is a potential typical B2B use case) if not in same workspace. 
Others interesting point that this does not solve:
- we may want user to decide if they active or not their public profile, and have some plugin for autoactivate or thing like that depending on usage.
- In a public instance logic, user profile is public because anyone is trusted-users, having possibility to find some user to invite to space doesn't mean you want to be able to see his user profile.

All this is a bit complex, so it's maybe the good moment to find a simpler logic around this.

**Comment by lebouquetin** [comment]
The public profile may be de-activable by the user itself. It would make thinks more clear without to overengineer the API

**Comment by grignards** [comment]
As I understand many of the profile settings (country/…) will be dynamic.
How will a user/administrator define the list of possible settings for his instance? Through a json file (a bit like color.json)?
How do we plan to handle the translation of the settings' labels in the frontend? Should we have a user configurable translation file? Or do not translate (at least for a first version)?

I also agree with the proposal of @inkhey to allow a user to block access to his profile and make configurable the fact that all users are known or not.
But what was the idea behind the plugin? If we have a `users_know_everybody`(bad name, but I think easy to understand) setting we can use its value to decide if the profiles are accessible by any user or not (and change the `known_users` API behavior accordingly).

**Comment by lebouquetin** [comment]
note : the default cover image is not tileable (it should)

**Comment by raphj** [comment]
Important: whatever endpoint we end up using for the public profile, we will need to add the follower count and following count to this endpoint, or create a specific endpoint.

**Comment by raphj** [comment]
Frontend URLs are like /ui/workspaces/30/dashboard for spaces: `/ui/workspaces/{WORKSPACE_ID}/{WORKSPACE_PAGE}`

For contents: `/ui/workspaces/30/contents/file/16676`: `/ui/workspaces/{WORKSPACE_ID}/contents/{FILE_TYPE}/{{FILE_ID}`

I think a more consistent URL for profiles would be one of those:
 - `/ui/users/{USER_ID}/`
 - `/ui/users/{USER_ID}/profile` (maybe this one is better)

**Comment by gbonaspetti** [comment]
> Frontend URLs are like /ui/workspaces/30/dashboard for spaces: `/ui/workspaces/{WORKSPACE_ID}/{WORKSPACE_PAGE}`
> 
> For contents: `/ui/workspaces/30/contents/file/16676`: `/ui/workspaces/{WORKSPACE_ID}/contents/{FILE_TYPE}/{{FILE_ID}`
> 
> I think a more consistent URL for profiles would be one of those:
> 
> * `/ui/users/{USER_ID}/`
> * `/ui/users/{USER_ID}/profile` (maybe this one is better)

The URL was based at the user account settings URL (`/ui/admin/user/{user_id}`), but I'm ok with `/ui/users/{user_od}/profile` if you prefer.

**Comment by raphj** [comment]
Good point. Any opinion @grignards?

**Comment by grignards** [comment]
I guess the `/ui/admin/user/{user_id}` URL comes from the fact that it is handled in a separate "app" (I do not know if having `/ui/users/{user_id}/account` would be possible in an app). But I also like @raphj naming for the URL.

**Comment by Skylsmoi** [comment]
During tests:
1. "Informations" doesn't exists in English, it's never plural
2. The "loading profile" doesn't seem to be fully implemented, only the component ProfileMainBar implements it
3. If there are multiple "personal page" parts, the design doesn't handle putting them on a new line
  3.1 It's not mandatory for the first version but will be required at some point

Points 2 and 3 might not be blocking to merge the PR since the PR is blocking other issues

**Comment by gbonaspetti** [comment]
> During tests:
> 
> 1. "Informations" doesn't exists in English, it's never plural
> 2. The "loading profile" doesn't seem to be fully implemented, only the component ProfileMainBar implements it
> 3. If there are multiple "personal page" parts, the design doesn't handle putting them on a new line
>    3.1 It's not mandatory for the first version but will be required at some point
> 4. On the mock ups, the mobile version seems to display the public name and username as bold
> 5. I don't see any edit cover button but I'm assuming it'll be added with the feature
> 
> Only point 1 might be a blocker to merge since this PR is blocking other issues

1. Fixed
2. I had implemented the loading for what information there was, I enriched a little but updated the #4038  and #4039 issues to update the screen if necessary.
3. To be discussed, but at first we won't do that in this version.
4. I updated the description with the changes made in comparison to the mockups
5. Yes, with the feature :smiley:

**Comment by PhilippeAccorsi** [comment]
Done.
