### ISSUE TITLE
Bug: Language translation not working on prod

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#383]
Actually:

On Tracim prod (algoo), its not possible to change language.
Check development.ini.base on prod.

**Comment by PhilippeAccorsi** [comment]
Translation
Compile translation binary files from available catalogs:

python setup.py compile_catalog


Check if file *.mo is present in language folder on "/tracim/tracim/i18n/ ".
If not, Tracim is not translate. 

Its necessary to have *.mo in all language folder.

**Comment by algooapy** [comment]
@buxx ran `python setup.py compile_catalog` this morning, this fixed the issue.
