### ISSUE TITLE
Bug: Automated tests fail randomly with pushpin docker 1.31

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3830]
## Description and expectations

The automated tests for TLMs use a pushpin docker image. Its version wasn't defined and the update to the 1.31 randomly breaks builds, see for example https://travis-ci.com/github/tracim/tracim/jobs/435134126

We should:
- [x] define the pushpin version as 1.30 for the tests
- [x] define the pushpin version as 1.30 for the official docker image
- ~~[ ] find the reason for those failures and correct them~~ postponed to #3911

### How to reproduce

1. `docker pull fanout/pushpin:1:31.0`
2. Run backend tests (following the documentation if needed)

Unfortunately the failures are not systematic. On my computer I didn't reproduce them, but noticed that `test_live_messages.py` execution is far longer (around 4 times longer).

### Version information

- Tracim version: develop, see the commit number of the travis job.

________________________________________________

## Diagnostic

Pushpin changed its default http server in 1.31: https://github.com/fanout/pushpin/blob/master/CHANGELOG.md
In the tests we have a config which starts the old http server, could it be the cause?

**Comment by inkhey** [comment]
Point to verify :
- is only `test_api__user_live_messages_endpoint_with_GRIP_proxy__ok__nominal_case` test that fail or `test_api__user_live_messages_endpoint_with_GRIP_proxy__ok__user_update` fail too sometime (they are very similar) ?
- i do suspect  the lack of `@pytest.mark.parametrize("config_section", [{"name": "functional_live_test"}], indirect=True)` in  `test_api__user_live_messages_endpoint_with_GRIP_proxy__ok__nominal_case` to have some side effect.

**Comment by PhilippeAccorsi** [comment]
@grignards one check box not check, can you explain in the issue why (if necessary) or check if its ok ?

**Comment by PhilippeAccorsi** [comment]
Also missing information about if some test is done or not.

**Comment by grignards** [comment]
> @grignards one check box not check, can you explain in the issue why (if necessary) or check if its ok ?

I put this in order to investigate the cause of those errors with pushpin 1.31, I just wrote an issue to handle this investigation as we didn't do it: #3911

> Also missing information about if some test is done or not.

Where? I explained in the PR description that manuel tests weren't necessary as the pushpin version that the PR defines is already the one used in official docker. I did test that the docker image builds properly.

**Comment by PhilippeAccorsi** [comment]
> > Also missing information about if some test is done or not.
> 
> Where? I explained in the PR description that manuel tests weren't necessary as the pushpin version that the PR defines is already the one used in official docker. I did test that the docker image builds properly.

Thanks for your answer. Question is just because we not have information in this issue about test :)

Done.
