### ISSUE TITLE
Feat: Profile cover image update

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3833]
## Feature description and goals

It should be possible for the user to change his profile cover image.

- [x] When the profile shown is the logged user's or the logged user is an administrator, a "change cover" button should appear in the lower right corner of the cover image.
- [x] On small screens the button label should be hidden.
- [x] When the user click on "change cover" an upload popup opens (same as when we upload a file). 
    - Only one file can be uploaded.
    - The recommended dimensions are 1300x150px
    - The maximum size is 1Mb
- [x] When confirmed the image is automatically updated.

Note: code for this feature should be largely shared with #3905 

## Translations

|English|French|Portuguese|
|-|-|-|
|Change cover|Changer la couverture|Mudar a capa|
|Upload image|Télécharger une image|Carregar imagem|
|Drag and drop your image here|Glisser déposer votre image ici|Arrastar e largar sua imagem aqui|
|You can also import your image by clicking here|Vous pouvez aussi sélectionner votre image en cliquant ici|Também pode importar sua imagem clicando aqui|
|Recommended dimensions:|Dimensions recommandées :|Dimensões recomendadas:|
|Maximum size:|Taille maximale :|Tamanho máximo:|
|You have not yet chosen any image to upload.|Vous n'avez pas encore sélectionné une image à téléverser.|Você ainda não escolheu nenhuma image para carregar.|
|Confirm|Valider|Confirmar|

## Prerequisites

#3829 
https://github.com/tracim/tracim/issues/3842

## Interface
_Obs: These interface examples are only templates, not everything will be developed in this issue and some details can be changed according to the implementation._

![public_profile_after_edit](https://user-images.githubusercontent.com/35422692/100776221-90df5100-3404-11eb-95e3-d3b6ad014179.jpg)

- Small screens

![public_profile_mobile (copy)](https://user-images.githubusercontent.com/35422692/100776378-bd936880-3404-11eb-8574-e365150a6c1c.jpg)

- Upload popup

![popup_new_image](https://user-images.githubusercontent.com/35422692/100776403-cbe18480-3404-11eb-906c-792b3c213ce6.png)

## Time estimation

3 man/day

**Comment by inkhey** [comment]
To limitate the upload to image only.
- You can use html5 to explictly accept only some kind of file : https://stackoverflow.com/questions/3828554/how-to-allow-input-type-file-to-accept-only-image-files.

For more safety, you should support the case the file cannot be processed properly as image for some reason (not an image ? broken file ?)

We should probably think of a backend check for this, but this is related to the problem of properly detecting mimetype for preview_generator, so i do suggest to wait for a proper mecanism to detect correct mimetype.

**Comment by lebouquetin** [comment]
> We should probably think of a backend check for this, but this is related to the problem of properly detecting mimetype for preview_generator, so i do suggest to wait for a proper mecanism to detect correct mimetype at file upload.

Hm... I'm not sure we have issues on image mimetype, do we? Supported mimetype for cover images will be classical jpeg, png (maybe gif)?

**Comment by lebouquetin** [comment]
By the way, what are the expected image dimensions? We must define this for functionnal purpose (the user must be informed of the expected image ratio / image dimensions).

**Comment by inkhey** [comment]
> > We should probably think of a backend check for this, but this is related to the problem of properly detecting mimetype for preview_generator, so i do suggest to wait for a proper mecanism to detect correct mimetype at file upload.
> 
> Hm... I'm not sure we have issues on image mimetype, do we? Supported mimetype for cover images will be classical jpeg, png (maybe gif)?

It's about mimetype check in backend. In most situation we can rely on mimetype given by the frontend but it's clearly better to have a check in backend to get the proper mimetype. As we don't properly deal with mimetype now, in both tracim and preview-generator, i do suggest to skip the backend check for a first step and wait to have a proper piece of software to guess mimetype. which will attach a proper mimetype to the content and this mimetype will be used by both tracim check and preview-generator.
We can of course decide to have another mimetype check at this level now but this will mean we will check mimetype 2 time: 
- in Tracim
- in Preview-Generator.
and the logic behind may be not the same, etc…

**Comment by inkhey** [comment]
Naïve api spec:

- we do consider we do not support preview of cover/avatar.

```
GET /api/users/{user_id}/avatar
```
-> available to all connected user
-> return always same size png or jpeg (should be always the same) avatar
```
GET /api/users/{user_id}/cover
```
-> available to all connected user
-> return always same size png or jpeg (should be always the same) avatar

```
PUT /api/users/{user_id}/avatar
```
-> put http file which should be a correctly sized image file
-> return 204
```
PUT /api/users/{user_id}/cover
```
-> put http file which should be a correctly sized image file
-> return 204

**Comment by lebouquetin** [comment]
@inkhey there is no need to build a different structure of API than for all files jpeg previews... this will be easier to manage and to understand if all image contents are offering similar APIs

**Comment by lebouquetin** [comment]
@inkhey you have to be inspired by what is done on almost any online service and by what we already done in our APIs:

- features are never limited to pixel-precise image files!
- we have API allowing to POST images and to get them resized - there is no reason for not reproducing them.

**Comment by raphj** [comment]
What about "Change cover" instead of "New image" for the button label?

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
