### ISSUE TITLE
Feat: Add avatar and cover image support for user

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#3842]
## Feature description and goals

The users' [public profile](https://github.com/tracim/tracim/issues/3833) will have avatars and cover images.

To do: implement avatars and cover images in the backend:
- [x] add `avatar`, `cropped_avatar` and `cover`, `cropped_cover` fields to user as UploadedFile (like `depot_file` for content)
- [x] migration script

### Avatar
- [X] ~~add proper avatar url (which one?) to user object (instead of none)~~ add has_avatar property
- add endpoints:
  - [x] available to all known users:

        GET /api/users/{user_id}/avatar/preview/jpg/{width}x{height}/{filename:[^/]*}
        GET /api/users/{user_id}/avatar/preview/jpg/{filename:[^/]*}
        GET /api/users/{user_id}/avatar/raw/{filename:[^/]*}
    - Only cropped image is used in the GETs.
  - [x] available to admins and the concerned user:
    - [x] should only allow one file
    - [x] should only allow the following types: `.gif` / `.jpeg` / `.png` / `.bmp` / `.webp`: Check is done with mimetype at http layer (no introspection).

             PUT /api/users/{user_id}/avatar/raw/{filename:[^/]*}
    - [x] the uploaded image is cropped (with static aspect ratios 1:1 for avatar with default size 100x100,  for cover 35/4 with default size 1300x150). Both the original and cropped versions are stored in depot.

### Cover Image

- [x] ~~add a proper cover URL (which one?) to user object (visible only on public profile endpoint?)~~ add has_cover property
- [x] add endpoints:
   - [x] available to  all known users:

         GET /api/users/{user_id}/cover/preview/jpg/{width}x{height}/{filename:[^/]*}
         GET /api/users/{user_id}/cover/preview/jpg/{filename:[^/]*}
         GET /api/users/{user_id}/cover/raw/{filename:[^/]*}

   - [x] available to admin/user itself
       - [x] should only allow 1 file
       - [x] should only allow the following types: `.gif` / `.jpeg` / `.jpg` / `.png` / `.bmp` / `.webp`

         `PUT /api/users/{user_id}/cover/raw/{filename:[^/]*}`

### To be discussed

- checking of content-type provided in backend? (i do suggest just check the mimetype given by frontend for a first step, no introspection)

> Decision:allowed file type should be gif / .jpeg / .png / .bmp / .webp .

In backend.

- size limitation (in bytes) of avatars?

In Apache configuration knowing it has the problem of getting an error only when uploading.

- default size of preview endpoint? (for content, it's the first value of preview.jpg.allowed_dims)

> Need clarification with frontend as avatar will have some default sizes.

## Time Estimation

2 man.day

## Implemented solution

see https://github.com/tracim/tracim/pull/4070
```
Add avatar and cover support of user in tracim backend.

 - Refactoring: Introduce StorageLib that encapsulate both DepotManager and PreviewManager usage (implemented almost everywhere)
 - add method `crop_image` to crop image to a given ratio.
 - add `avatar`, `cropped_avatar`, `cover`, `cropped_cover` fields to `users` table + migration script.
 - add 4 endpoints to PUT/GET raw/GET previews (with or without explicit size) for avatar.
 - add 4 endpoints to PUT/GET raw/GET previews (with or without explicit size) for cover.
 - remove `avatar_url` from user-schema and add `has_avatar` and `has_cover` boolean to user schema.
 
Refs: #3842
```

related issue : https://gitlab.algoo.fr/algoo/tracim-security/issues/29

**Comment by grignards** [comment]
A question about the type and size parameters of previews: I know this is the same as the preview on contents, but I'm curious to know what was the rationale to have the parameters as path parts instead of query parameters (we have `/api/users/{user_id}/cover/preview/jpg/{width}x{height}/{filename:[^/]*}` instead of `/api/users/{user_id}/cover/preview?type=jpg&width=width&height=height/{filename:[^/]*}`?
I understand the `filename` is here to ensure we can easily get any filename with any tool.

**Comment by grignards** [comment]
And do we need `avatar_url` in the end? AFAIK that would be the only time we'd allow a client/frontend to discover an url.

**Comment by grignards** [comment]
Also concerning the implementation: we should find a way to share as much code as reasonable between the contents previews and those ones (I didn't check if the contents previews are already factorized, otherwise we should do it in this issue).

**Comment by grignards** [comment]
And don't forget to generate TLMs in this case (It should be the case without needing a special case, but check).

**Comment by inkhey** [comment]
> A question about the type and size parameters of previews: I know this is the same as the preview on contents, but I'm curious to know what was the rationale to have the parameters as path parts instead of query parameters (we have `/api/users/{user_id}/cover/preview/jpg/{width}x{height}/{filename:[^/]*}` instead of `/api/users/{user_id}/cover/preview/{filename:[^/]*}?type=jpg&width=width&height=height`?

Unfortunately, i do not remembers the reason behind this.

> And do we need `avatar_url` in the end? AFAIK that would be the only time we'd allow a client/frontend to discover an url.

Good question, i do think, we do need the information about the availability of an avatar but i'm not sure url is pertinent here, it will make thing more complicated (and API more inconsistent). maybe something like "has_avatar" (like for preview availability of content) ?

> Also concerning the implementation: we should find a way to share as much code as reasonable between the contents previews and those ones (I didn't check if the contents previews are already factorized, otherwise we should do it in this issue).

i do agree. I don't think this code is fully factorized on this part.

**Comment by grignards** [comment]
> Good question, i do think, we do need the information about the availability of an avatar but i'm not sure url is pertinent here, it will make thing more complicated (and API more inconsistent). maybe something like "has_avatar" (like for preview availability of content) ?

Ideally we could generate an avatar on-demand (or when the user is created) in the back-end but this would probably take more time than leaving the frontend generation.
But isn't a 404 on the avatar's url enough? So that the front can make a request for the avatar and if not present use its generated one?

**Comment by inkhey** [comment]
> But isn't a 404 on the avatar's url enough? So that the front can make a request for the avatar and if not present use its generated one?

It's also a possibility. i think about the parameter "has_avatar"  to avoid doing too much url call, and this is logical according to the preview mecanism, but this may be not so useful. in fact, after thinking about this, if what we want here is avoid url call a kind of "hash" of the avatar is clearly a better solution, because if a user change his own avatar, there is no other solution that reload avatar (no way to know that avatar has changed in user object).

Maybe should we just do not return anything about avatar for a first step and optimize this later if needed. This point does exist also for cover image.

**Comment by grignards** [comment]
> Maybe should we just do not return anything about avatar for a first step and optimize this later if needed. This point does exist also for cover image.

Agreed, especially since all of these optimizations could/should (?) be solved by an standard HTTP caching mechanism.

**Comment by inkhey** [comment]
About file size, It has been decided to limit size to 1Mo for both avatar and cover.
This is ok but we need to clarify how to check this:
- frontend check is simpler has there is not problem to get fille file
- proper backend check will mean : 
  - store the file
  - check his size
which is dangerous.
- I do suggest a content_length check which will not exact match the size of the file but will allow to disable uploading more directly.

**Comment by inkhey** [comment]
>     * I do suggest a content_length check which will not exact match the size of the file but will allow to disable uploading more directly.

There is a similar problem with content_type check (but this is less a problem has storing temporary a small incorrect type file is acceptable). We should not accept a non image file.

**Comment by grignards** [comment]
> I do suggest a content_length check which will not exact match the size of the file but will allow to disable uploading more directly.

Yes it's probably enough. To be totally sure we could also check the behavior of pyramid in case of a bad content-size header (probably should reject the request by itself).

**Comment by inkhey** [comment]
> A question about the type and size parameters of previews: I know this is the same as the preview on contents, but I'm curious to know what was the rationale to have the parameters as path parts instead of query parameters (we have `/api/users/{user_id}/cover/preview/jpg/{width}x{height}/{filename:[^/]*}` instead of `/api/users/{user_id}/cover/preview/{filename:[^/]*}?type=jpg&width=width&height=height`?
> I understand the `filename` is here to ensure we can easily get any filename with any tool.

We should probably clarify the rule there as need for more advanced feature of preview_generator through api will soon be needed, see https://github.com/tracim/tracim/issues/3904

**Comment by raphj** [comment]
Should we return the file without scaling / croping / transformation if the size is not specified?

**Comment by inkhey** [comment]
> Should we return the file without scaling / cropping / transformation if the size is not specified?

I suggest we follow the same pattern as for normal stored file, same default size but not cropping/other transformation.

**Comment by Skylsmoi** [comment]
Image is cropped at upload (with static aspect ratios 1:1 for avatar,  x:y for cover ). The original and the cropped version are stored. Only cropped picture is used in the GETs.

**Comment by inkhey** [comment]
> > Maybe should we just do not return anything about avatar for a first step and optimize this later if needed. This point does exist also for cover image.
> 
> Agreed, especially since all of these optimizations could/should (?) be solved by a standard HTTP caching mechanism (relatively easy here as the avatar can only be modified through one endpoint).

So i suggest to remove avatar_url, is it used somewhere in frontend ? @raphj @Skylsmoi @grignards

**Comment by PhilippeAccorsi** [comment]
Done.
