### ISSUE TITLE
Bug: The dashboard icon and order is not the same in the tabs and in the sidebar menu.

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3847]
## Description and expectations

- [x] The dashboard icon should be `fa-tachometer` at both (sidebar and tab)
- [x] The elements order is also different at both (sidebar and tab) and it should be the same

### Version information

- Tracim version: v3.3.0

________________________________________________

**Comment by PhilippeAccorsi** [comment]
This is an important fix.

**Comment by PhilippeAccorsi** [comment]
Done.
