### ISSUE TITLE
Bug: Add a margin-bottom to the "Refresh" button in activity feed

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3848]
## Description and expectations

- [x] The button should have a margin-bottom of 10px (to match with the distance from the top)

### Version information

- Tracim version: v3.3

## Screenshots

![Screenshot from 2020-11-18 16-32-09](https://user-images.githubusercontent.com/35422692/99551031-ad6a9a80-29bb-11eb-9e07-ec69d8fb7ac8.png)
________________________________________________

**Comment by PhilippeAccorsi** [comment]
Done.
