### ISSUE TITLE
Bug: The phrase "by {{author}}" is not always right-aligned in activities

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3849]
## Description and expectations

The phrase "by {{author}}" should be right-aligned in activities.

### Version information

- Tracim version: v3.3
- Web browser: Google Chrome

## Screenshots

![Screenshot from 2020-11-18 16-53-07](https://user-images.githubusercontent.com/35422692/99553879-ea845c00-29be-11eb-8edc-7445d7f54ff4.png)

________________________________________________

**Comment by PhilippeAccorsi** [comment]
Done.
