### ISSUE TITLE
Bug: Translation in french for "read mode"

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#385]
Actually:

When Tracim in in French, the button for "read mode" is not translated. and when you push, you can see "undefined".

Expected:

"read mode" change to "mode lecture" (or something like that) and other text for "undefined".

**Comment by tracim** [comment]
@Skylsmoi could you fix the "undefined" part, then assign the issue to @algooapy for translation part of the bug?

**Comment by algooapy** [comment]
I translated "read mode" to "mode lecture" in the branch [fix/385/read_mode_translation](https://github.com/tracim/tracim/tree/fix/385/read_mode_translation)

**Comment by Skylsmoi** [comment]
the problem is that globalTracimLang can have many different values. It comes from i18n library that get the lang value from the browser's.

I have added in js the handling of some different language code (eg. 'fr', 'fr-fr', 'fr_Fr')

**Comment by PhilippeAccorsi** [comment]
at present:

When I go to tracim homepage, I see "Read mode". If I click, I see "Mode d'édition" and I click again, I see " Mode de lecture".

If I reload the page, "Read mode" appear again.
