### ISSUE TITLE
Bug: the text of the tabs move when switching between active and not active

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3850]
## Description and expectations

- [x] The text of the tabs should not move when switching between active and not active.

________________________________________________

## Diagnostic

There is a border-bottom of 1px when the tab is not active that does not exists when it's active, so the text move to bottom.

## Implemented solution

Add a transparent border-bottom at active tab.

**Comment by PhilippeAccorsi** [comment]
Done.
