### ISSUE TITLE
Bug: Comments are shown as activities in the activity feed

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3852]
## Description and expectations

Comments made on an unreachable content are displayed as activities by their own.
They shouldn't be displayed at all.

### How to reproduce

Difficult to reproduce as it has been spotted only for a now non-existing situation (a comment event without `parent_content_type`). Nevertheless the behavior if the GET content query fails should be fixed.

### Version information

- Tracim version: develop, future 3.3.

## Screenshots

________________________________________________

## Diagnostic
When a comment message is used to create an activity the real content is fetched from the API. If this fetch fails the content is set to the comment itself instead of raising an error.

**Comment by lebouquetin** [comment]
@grignards why do we get *a comment event without `parent_content_type`*  ? Is this related to non-coherent stored data?

**Comment by grignards** [comment]
Already answered privately but ultimately the cause is the absence of migrations for the fields of messages.

**Comment by PhilippeAccorsi** [comment]
@raphj @seb
I just seen this comment in MR
~~~
For testers

    [ ] Manual, quality tests have been done: as reproducing the error in a real situation is difficult I would test it directly on our pre-production (as we have a content triggering this error inside).
~~~

Can you add comment here to explain if all its ok ? (I think missing label about test and comment)

**Comment by grignards** [comment]
I just tested this with the preprod content which was behaving badly and all is OK (added label).

**Comment by PhilippeAccorsi** [comment]
Thanks for your answer.
Done.
