### ISSUE TITLE
Bug: The "refresh" button is always displayed in activity feed

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3861]
## Description and expectations

It should be hidden when pressing it does nothing.

### How to reproduce

1. Go to a space activity feed

### Version information

- Tracim version: develop (future 3.3)

## Screenshots

________________________________________________

## Diagnostic

The button is always displayed, its effect is to sort the current list so that the activities with the more recent update are displayed first.
To make it appear only when needed we need to:
- [x] have a `showRefresh` state which defaults to `false`
- [x] update the value of this state when a TLM is received and it updates an existing activity which is not the first.

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
