### ISSUE TITLE
Bug: Alignment of the tab icon

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3863]
## Description and expectations

The fact that icons of different shapes have equal alignments causes visual discomfort for some users. After some tests we found that the most comfortable was to align the dashboard icon a little above the others.

Current:
![Screenshot from 2020-11-20 10-29-56](https://user-images.githubusercontent.com/35422692/99784082-8e831a00-2b1b-11eb-91ab-a379fbe28760.png)

Expected:
![Screenshot from 2020-11-18 15-55-47](https://user-images.githubusercontent.com/35422692/99783843-44019d80-2b1b-11eb-9afa-5033e0c59606.png)

**Comment by raphj** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Done
