### ISSUE TITLE
Bug: In the dashboard, the square containing the name and the role changes size depending on the role

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3867]
## Description and expectations

In English, when I go from a space where I am contributor to a space where I am content manager, this square does not have the same size:

![image](https://user-images.githubusercontent.com/3817365/99951234-06507f00-2d7e-11eb-9431-06220e076946.png) ![image](https://user-images.githubusercontent.com/3817365/99951304-30a23c80-2d7e-11eb-8063-0a85e264efbf.png)

I expect this square to have the same size everywhere.

**Comment by gbonaspetti** [comment]
Fixed at #2594
