### ISSUE TITLE
Bug: Mention @all is not in the user language

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#3870]
## Description and expectations

When validating a new revision of a note, a flash message suggests to mention all users. This mention is expected to be done in the user language. This is not the case.

To do:
- [x] use the user's UI language for this message
- [x] also fix the translation of the description in the mention popup
- [x] an automatic test must be implemented in order to ensure this will not re-appear

### How to reproduce

1. Create a note.
2. Save it.
3. Modify it.
4. Click on the button "Pour notifier tous les membres de l'espace de votre modification, cliquez ici"

The mention appears in the timeline: `@all please notice that I did an important update on this content.`

### Version information

- Tracim version: 3.2.1
- Web browser: Firefox
- Version: 82.0.2 (64 bits)
- Device / System: PC Linux Debian

## Screenshots

![image](https://user-images.githubusercontent.com/907161/100016350-8eb03d80-2dd9-11eb-9822-6212a9ed509c.png)

**Comment by lebouquetin** [comment]
By the way, when looking for mentionning all in a comment, in french the mention is `tous` but the explanation is in english. French expected:

![image](https://user-images.githubusercontent.com/907161/100024010-4cd9c400-2de6-11eb-812d-a9fb2c44bffc.png)

**Comment by PhilippeAccorsi** [comment]
Done.
