### ISSUE TITLE
Bug: Change the background color of the previews

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3873]
## Description and expectations

Currently the background is offWhite, which causes the sensation of many white blocks. To solve this we will use the same color as the feed background, veryLightGrey, for the previews.

For html previews (notes and threads), it was decided to keep the offWhite background and add a margin between the gray area of the preview and the preview itself.

Note to the developer: test it with several html previews together and see if it doesn't get disturbing the many background changes (gray background, white background, gray background, white background). If it does, talk to the graphic person in charge.

### Version information

- Tracim version: v3.3.

## Interfaces
_Obs: These interface examples are only templates, not everything will be developed in this issue and some details can be changed according to the implementation._

![Image collée à 2020-11-23 17-09](https://user-images.githubusercontent.com/35422692/100204736-856fbf80-2f04-11eb-80aa-94743389fdad.png)
![Image collée à 2020-11-23 17-02](https://user-images.githubusercontent.com/35422692/100204737-86a0ec80-2f04-11eb-8de1-e595d7e0d878.png)

________________________________________________

**Comment by PhilippeAccorsi** [comment]
Done.
