### ISSUE TITLE
Bug: Improvements to HTML previews

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3874]
## Description and expectations

- [x] If a note or thread is empty, the preview must be "empty note/thread" with the same rendering and icon as "preview unavailable".
- [x] Add a padding (text is too close to the preview border).
- [x] Unify styles between the Preview and the Note app - style sheets that apply to notes should be applied to the preview for consistency. These styles should be factorized to a single location.
- [x] handle previews of files with a space in their names

### Version information

- Tracim version: v3.3.

## Translations
|English|French|Portuguese|
|-|-|-|
|Empty thread|Discussion vide|Discussão vazia|
|Empty note|Note vide|Nota vazia|

## Interface
_Obs: This interface examples is only a templates, not everything will be developed in this issue and some details can be changed according to the implementation._

![Screenshot from 2020-11-25 10-19-36](https://user-images.githubusercontent.com/35422692/100207427-daf99b80-2f07-11eb-9cd0-acd8c2e1dbc8.png)
________________________________________________

**Comment by inkhey** [comment]
Tested on branch,
All but Empty thread case is working . It's not working because, in this case, it's the backend that return a generic error which does not allow to see proper distinction between "preview unavailable" and "empty thread"
see issue https://github.com/tracim/tracim/issues/3898

**Comment by PhilippeAccorsi** [comment]
Done.
