### ISSUE TITLE
Bug: Font size too small in dropdown menu

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3877]
## Description and expectations

With the standardization of the dropdown menu component (done in https://github.com/tracim/tracim/issues/3584) the font of the elements became smaller than it was in some menus.

To do:
 - [x] restore the original font size

## Screenshots

- Current Tracim version
![Image collée à 2020-11-24 22-30](https://user-images.githubusercontent.com/35422692/100210820-b56e9100-2f0b-11eb-9f65-e5fc47577a80.png)

- Tracim v3.1.4.
![Image collée à 2020-11-24 22-31](https://user-images.githubusercontent.com/35422692/100210832-b7d0eb00-2f0b-11eb-84e4-deb9bbc58d4d.png)

________________________________________________

**Comment by inkhey** [comment]
tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
