### ISSUE TITLE
Bug: Pasting an image in TinyMCE does not work

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3899]
## How to reproduce

- take a screenshot
- copy it
- paste it in a note

## Expected

The image should be pasted

## Current behavior

The current line might be mangled and the image is not pasted 

## Diagnostic

None for now, I've not seen any error in the console message. Consider reviewing the code handling mention suggestions, it might block some events, though pasting text still works and pasting from the browsers' menu leads to the same effect.

In fact tinymce requires `paste_data_images: true` in `init()` to enable this feature.

## Versions

- Tracim 3.2, 3.3
- Firefox 82, Chromium 87

**Comment by grignards** [comment]
Corrected by 2663941348acb66aef5f8e1d966a32dbac03edc6 (pushed by error :-/ ).

**Comment by MariePrandstetter** [comment]
Done
