### ISSUE TITLE
Feat: Change wording with the arrival of the public profile

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3901]
## Feature description and goals

- [x] At "My Account" page:
    - the option "My profile" should be changed to "My Account".
    - and "Change my profile" to "Change my account settings"
- [x] At user's page (via Administration):
    - the option "Profile" should be changed to "Account".
    - and "Change the profile" to "Change the account settings"
- [x] The "My Account" option in the header menu will become "Account Settings".
    - icon: `fa-cogs`
- [x] In the user addition form, change all the uses from "profile" to " user type". 
    - For example "Choose the profile" will become "Choose the user type". 
    - Do not forget to update the error messages.
- [x] Change "All contents" to "Contents"
- [x] At create space popup and dashboard advanced, change "This is the role that members will have by default when they join your space." to "This is the role that members will have by default when they join your space (for open and on request spaces only)."
- [x] Change Tracim documentation
- [x] Change email templates, if necessary
- [x] Report changes made in the changelog.

## Translations

|English|French|Portuguese|
|-|-|-|
|Account Settings|Paramètres du compte|Definições de conta|
|My Account|Mon compte|Minha conta|
|Account|Compte|Conta|
|Change my account settings|Changer mes paramètres du compte|Mudar minhas definições de conta|
|Change the account settings|Changer les paramètres du compte|Mudar as definições de conta|
|user type|type d'utilisateur|tipo de utilizador|
|This is the role that members will have by default when they join your space (for open and on request spaces only).|C'est le rôle que les membres auront par défaut lorsqu'ils rejoignent votre espace (uniquement pour les espaces ouverts ou sur demande).|Esta é a função que os membros terão por pré-definição quando se juntarem ao seu espaço (apenas para espaços abertos ou a pedido).|
|Contents|Contenus|Conteúdos|

## Time Estimation

1 man/day

**Comment by raphj** [comment]
Why is the documentation label used here?

**Comment by gbonaspetti** [comment]
> Why is the documentation label used here?
There is the checkbox "Change Tracim documentation"

**Comment by raphj** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Done

**Comment by PhilippeAccorsi** [comment]
For `Change email templates, if necessary`: no change done in email template so not necessary to add comment in changelog.
