### ISSUE TITLE
Feat: Refactor Avatar to have fixed sizes

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3903]
## Feature description and goals

Currently we can put any value as avatar size. Therefore we have 8 different values, being them: 100px, 75px, 50px, 44px, 40px, 32px, 23px and 15px.

### Expected
- [x] Change the width prop to `size`. `size` can be a string between 'big', 'medium', 'small' and 'mini'.
- [x] At Avatar component associate the string 'big' to the size 100px, the string 'medium' to the size 50px, the string 'small' to the size 30px and the string 'mini' to the size '20px'.
- [x] Replace all Avatar calls with sizes 100px and 75px with a call of Avatar with the prop size set to 'big'.
- [x] Replace all Avatar calls with sizes 50px and 44px with a call of Avatar with the prop size set to 'medium'.
- [x] Replace all Avatar calls with sizes 40px and 32px with a call of Avatar with the prop size set to 'small'.
- [x] Replace all Avatar calls with sizes 23px and 15px with a call of Avatar with the prop size set to 'mini'.
- [x] This prop should be 'medium' by default.

Please check that it is not necessary to add css rules to other elements so that the display still works correctly. For example, it will be necessary to add the `align-items center` rule in `.autocomplete__item` class so that the autocompletion popup still has the same look.

Obs: The component's names are just examples and can be chosen by the developer.

## Time Estimation
1 man/day

**Comment by grignards** [comment]
Couldn't we keep `Avatar` and have a `size` (big|medium|small) parameter for it?

**Comment by gbonaspetti** [comment]
> Couldn't we keep `Avatar` and have a `size` (big|medium|small) parameter for it?

Yes, it's a good solution, I'm gonna update the description. However, I couldn't decrease it to only 3 values without having major interface changes. So we will have 4 size options (big, medium, small and mini).

**Comment by inkhey** [comment]
tested on branch
