### ISSUE TITLE
Feat: Add "crop mode" support for some preview 

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#3904]
## Feature description and goals

For user cover image, we do need cropped image :

- [ ] Add crop mode mechanism to _preview_generator_. It should allow to crop image to a defined ratio. We do need to support at least crop from upper-left corner but it will be better to have something more generic here (to handle multiple kind of cropping). see https://github.com/algoo/preview-generator/issues/206
- [ ] Adapt preview code to handle this kind of preview (find a generic way is cleary better, but it should at least work for cover image).

## To be discussed before development

- maximum upload size?

In Apache configuration but has the problem of getting an error only when uploading.

**Comment by grignards** [comment]
Which cropping facility do we plan to offer? I've seen several service UIs which have the user define the cropped area himself (see github avatars for an example). Do we plan to do the same here for cover images? If yes the parameters would be a `(x,y,width,height)` rectangle, and we have to store this rectangle.

**Comment by inkhey** [comment]
> Which cropping facility do we plan to offer? I've seen several service UIs which have the user define the cropped area himself (see github avatars for an example). Do we plan to do the same here for cover images? 

For a first step, decision taken are:
- crop mode is needed for cover image and should be implemented in preview-generator
- crop for cover image should be always top-left crop. So no need for specific UI.

for the parameters see https://github.com/algoo/preview-generator/issues/206#issuecomment-737213965

**Comment by raphj** [comment]
To allow genericity,  I suggest using a `sizing_method` parameter. Here, it seems we want to both resize and crop, so I suggest a value `resize_crop` for this parameter. This sizing method would:
 - resize such that the biggest proportion of the image is in the requested area
 - then, crop

We could have a second parameter, `crop_origin`, that says which part of the image we keep. I see three possible sets of values for `crop_origin`:
 - cardinal directions: n, ne, e, se, s, sw, w, nw
 - x,y percentage positions
 - x,y absolute pixel positions

This `crop_origin` parameter can be used with a `crop` sizing method, should we introduce it in the future.

**Comment by inkhey** [comment]
> To allow genericity, I suggest using a `sizing_method` parameter. Here, it seems we want to both resize and crop, so I suggest a value `resize_crop` for this parameter. This sizing method would:
> 
>     * resize such that the biggest proportion of the image is in the requested area
> 
>     * then, crop
> 
> 
> We could have a second parameter, `crop_origin`, that says which part of the image we keep. I see three possible sets of values for `crop_origin`:
> 
>     * cardinal directions: n, ne, e, se, s, sw, w, nw OR top, top-left, left, bottom-left, bottom, bottom-right, right, top-right
> 
>     * x,y percentage positions
> 
>     * x,y absolute pixel positions
> 
> 
> This `crop_origin` parameter can be used with a `crop` sizing method, should we introduce it in the future.

As we expect to generate preview, there will always been rezising, so i don't think it's important to name it "resize_crop", 
"crop" is enough.

I suggest to add a query parameters as this can be usable easily in previous preview endpoint without breaking anything:

If we do want a 180x360px cover, we could do something like this:
`GET /api/users/{user_id}/cover/preview/jpg/360x360/{filename:[^/]*}?post_action=crop, crop_box=0,0,360,180`

Implementation in preview_generator could be done using crop:
https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.crop

I do think we can avoid using fit method for the moment (we may add support for it later).
It's not to complete to add this to preview_generator, the only thing to consider is from preview_generator side:
- there is no "post-action" mecanism in preview-generator, so a refactor is needed if we do want to avoid  adding crop code in each preview generated. This has also some consequence on how we architecture preview_generator. I do add some preview_generator specific idea in the preview_generator issue:https://github.com/algoo/preview-generator/issues/206#issuecomment-756014942

**Comment by Skylsmoi** [comment]
Closing issue as this is un-needed for 3.5 (cropping done by tracim).
