### ISSUE TITLE
Feat: Profile avatar update

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3905]
## Feature description and goals

It should be possible for the user to change their avatar.

- [x] When the profile shown is the logged user's or the logged user is an administrator, a button should appear in the lower right corner of the avatar with a tooltip "Change avatar".
- [x] When the user click on "change avatar" button an upload popup opens (same as when we upload a file).
    - Only one file can be uploaded.
    - The recommended dimensions are 100x100px
    - The maximum size is 1Mb
- [x] When confirmed the image is automatically updated.

Note: the code for this feature should should be largely shared with #3833

## Translations

|English|French|Portuguese|
|-|-|-|
|Change avatar|Changer l'avatar|Mudar avatar|
|Upload image|Télécharger une image|Carregar imagem|
|Drag and drop your image here|Glisser déposer votre image ici|Arrastar e largar sua imagem aqui|
|You can also import your image by clicking here|Vous pouvez aussi sélectionner votre image en cliquant ici|Também pode importar sua imagem clicando aqui|
|Recommended dimensions:|Dimensions recommandées :|Dimensões recomendadas:|
|Maximum size:|Taille maximale :|Tamanho máximo:|
|You have not yet chosen any image to upload.|Vous n'avez pas encore sélectionné une image à téléverser.|Você ainda não escolheu nenhuma image para carregar.|
|Confirm|Valider|Confirmar|

## Prerequisites

#3829 
https://github.com/tracim/tracim/issues/3842

## Interface
_Obs: These interface examples are only templates, not everything will be developed in this issue and some details can be changed according to the implementation._

![public_profile_before_edit](https://user-images.githubusercontent.com/35422692/100733644-c5381a80-33ce-11eb-9858-4e4d4ca2bdca.jpg)

- Upload popup

![popup_new_image](https://user-images.githubusercontent.com/35422692/100776986-7fe30f80-3405-11eb-81a2-233fa3c3792c.png)

## Time estimation

3 man/day

**Comment by raphj** [comment]
I think this feature should be developed with #3833 at the same time.

**Comment by grignards** [comment]
Development notes:

|Upload files location|Multi-file|Popup|
|-|-|-|
|App File (creation)|Yes|Yes|
|App File (new version)|No|No|
|Frontend (guest upload)|Yes|No|
|*Frontend (public profile)*|No|Yes|

The uploading code (with xhr/progress) is currently copied-paste between the existing usages.

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
