### ISSUE TITLE
Feat: Allow S3 depot configuration in backend configuration file

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3908]
## Feature description and goals

Currently the backend configuration file only allows to set a directory for [depot](https://depot.readthedocs.io/en/latest/). It is then used to store all file contents.
Depot is able to use other storage than a local filesystem, for instance Amazon S3. Using a remote storage can be useful for several use cases: accessing Tracim contents without using Tracim itself, enhanced isolation/security/redudency.…
The S3 API is implemented by several open-source products ([min.io](https://min.io), [Open-Stack Swift](https://docs.openstack.org/swift/latest/)…) and available in several provider offers so using it do not enforce Amazon service usage.

- [x] allow setting [depot configuration keys](https://depot.readthedocs.io/en/latest/userguide.html#configuring-depotmanager) used for S3 in Tracim configuration
- [x] modify the preview generation to retrieve the file from depot instead of "cutting short" and directly giving the depot filename to preview generation.
- [x] make sure that the file used for preview generation is deleted just after finishing the preview
- [x] document the configuration keys

Note: two parameters will be deprecated (:warning:):

-  `depot_storage_name` will become `uploaded_files.storage_name`. New parameter has priority over the previous one.
-  `depot_storage_dir` will become `uploaded_files.storage_path`. New parameter has priority over the previous one.

Theses parameters will be removed from the sample config file.

### New parameters specifications
```
uploaded_files.storage.storage_name = tracim
uploaded_files.storage.storage_type = memory
```
or that:
```
uploaded_files.storage.storage_name = tracim
uploaded_files.storage.storage_type = local
uploaded_files.storage.local.storage_path = /tmp/mystoragepath
```
or that:
```
uploaded_files.storage.storage_name = tracim
uploaded_files.storage.storage_type = s3
uploaded_files.storage.s3.access_key_id = 0b9c2625dc21ef05f6ad4ddf47c5f203837aa32c
uploaded_files.storage.s3.secret_access_key = b728549201e1868e08bf85a7939a767ed02f9e82
uploaded_files.storage.s3.bucket = mybucker
uploaded_files.storage.s3.region_name = eu-west-2
uploaded_files.storage.s3.policy = private
uploaded_files.storage.s3.storage_class = STANDARD_IA
uploaded_files.storage.s3.endpoint_url = http://somehwere.it
uploaded_files.storage.s3.prefix = tracim_content/
```

## Prerequisites

- technical debt #3917 would be useful (but not required)

## Time Estimation

- 2 day/man for only S3 support
- 4 day/man for adding generic support and resolving technical debt related to config parameters, see issue #3917 and [discussion](https://github.com/tracim/tracim/issues/3908#issuecomment-737278279).

so either 2 or 6 man.day

## Implemented solution
https://github.com/tracim/tracim/pull/3942

-  config: `depot_storage_name` will become `uploaded_files.storage.storage_name`. New parameter has priority over the previous one.
-  config: `depot_storage_dir` will become `uploaded_files.storage.storage_path`. New parameter has priority over the previous one.
- config: big renaming of depot parameter naming to "uploaded_files.storage.*" 
- config: add support for both S3 and memory (ram) storage for uploaded_file + test file/preview on them too.
- adjust preview code in order to support all depot backend, current implementation is not efficient as it dropped the preview_generator cache mecanism and generate a new temporary file each time.
- use legacy mecanism for local file storage (currently more efficient but only work for this kind of storage) and new one for other storage in order to not "lose" functionnality.

**Comment by inkhey** [comment]
>     * [ ]  allow all [depot configuration keys](https://depot.readthedocs.io/en/latest/userguide.html#configuring-depotmanager) in Tracim configuration

This point may cause some trouble because we have the choice in tracim to either:
- support any config here like for `beaker` in config file but have a restricted support for this in en var
- be completely explicit about parameters config in tracim, so we do need to be aware of depot config.

@grignards Do you have any idea of how we can deal to solve those issues, we already have this problem for beaker but also webdav.* parameters ?

**Comment by inkhey** [comment]
>     * [ ]  modify the preview generation to retrieve the file from depot instead of "cutting short" and directly giving the depot filename to preview generation.

This mean : 
- create a "local" temporary copy of the file on disk (we do have builder that need a path), we may be careful if the file is huge.
- we can decide that the temporary copy of the file has the filename of the file we do want, so the standard file-extension. This mean all the trick about "handling file without explicit extension" in preview-generator is not anymore needed if we do this, which means less headache in builder and mimetype guessing because of this.

**Comment by grignards** [comment]
> @grignards Do you have any idea of how we can deal to solve those issues, we already have this problem for beaker but also webdav.* parameters ?

We could mimic the settings read: all environment variables starting by `TRACIM_DEPOT` are given to depot with their lowercase suffix as key. This means we won't ensure the validation of those options but rather rely on the underlying module (depot/beaker/…) though.

**Comment by inkhey** [comment]
> > @grignards Do you have any idea of how we can deal to solve those issues, we already have this problem for beaker but also webdav.* parameters ?
> 
> We could mimic the settings read: all environment variables starting by `TRACIM_DEPOT` are given to depot with their lowercase suffix as key. This means we won't ensure the validation of those options but rather rely on the underlying module (depot/beaker/…) though.

We do currently have validation on some of those field, but also default value. So, if we do want a good solution, we do need to : 
- Be able to set default value for some field we do decide.
- Be able to keep validation for some of those field if we decide to.

I do suggest to be able to do something like this in CFG:
```
self.generate_dynamic_parameters('depot') # will generate all depot parameters from both config and env variables as CFG parameters, these parameters will be visible at launch (we can add a specific note to show there are autogenerated) and maybe command that get parameters list (to clarify)
self.DEPOT_STORAGE_NAME = self.get_raw_config("depot_storage_name", "tracim") # depot_storage_name is already set if exist but by reenforcing it, we allow to have default value and some check)
self.check_mandatory_param("DEPOT_STORAGE_DIR", self.DEPOT_STORAGE_DIR)
self.check_directory_path_param("DEPOT_STORAGE_DIR", self.DEPOT_STORAGE_DIR, writable=True)
```
In my mind this problem of configuration, is more like a technical debt/improvement issue. It's not a blocking point. What is mandatory to be done in my mind for 3.4 is : 
- support both S3 backend for file depot in config.
- adapt usage of preview-generator to support both file and S3 backend.

**Comment by inkhey** [comment]
> 
>     * support both S3 backend for file depot in config.
> 
>     * adapt usage of preview-generator to support both file and S3 backend.

note : i say S3 but it can be another one, we do not need to support any kind of distant backend for now. Supporting all is nice but we do need a proper mecanism for config, and finding the good solution seems a bit tricky. The rest of the issue seems straightforward.

**Comment by inkhey** [comment]
Just re-read the depot source code and i do suggest something like this for config file:

```ini
depot.content.storage_name = tracim
depot.content.backend = depot.io.memory.MemoryFileStorage # (default value will be filestorage to ensure retrocompatibility)
depot.content.storage_path = /tmp/mystoragepath
```

storage_name is the name of the storage whereas other parameters refer to parameters name of depot:
https://depot.readthedocs.io/en/latest/api.html?highlight=backend#depot.manager.DepotManager.configure
The storage_name may be deprecated later as if we do decide to not rely anymore on DepotManager static list, this parameter
as not anymore reason to exist.

I do suggest `depot.content.` prefix in order to be future-proof in case we do want to use multiple depot for some reason.

previous parameter will stay functional for now but set as deprecated:
- `depot_storage_name` will become `depot.content.storage_name`. New parameter has priority over the previous one.
- `depot_storage_dir` will become `depot.content.storage_path`. New parameter has priority over the previous one.
Theses parameters will be remove from the sample config file.

All parameters needed for both File and S3 backend will be handled as real tracim parameter with similar mecanism as for webdav/beaker config allowing user to use full power of depot if needed but with real check and support for only S3/File/Memory case.

**Comment by inkhey** [comment]
> > ```
> > * [ ]  modify the preview generation to retrieve the file from depot instead of "cutting short" and directly giving the depot filename to preview generation.
> > ```
> 
> This mean :
> 
>     * create a "local" temporary copy of the file on disk (we do have builder that need a path), we may be careful if the file is huge.
> 
>     * we can decide that the temporary copy of the file has the filename of the file we do want, so the standard file-extension. This mean all the trick about "handling file without explicit extension" in preview-generator is not anymore needed if we do this, which means less headache in builder and mimetype guessing because of this.

Discovered an issue related to the preview-generator cache here.
Cache is done by creating a hash of the full path of the file. but if we do temporary copy of the file, path will be a temporary path, which is not reliable !
The solution i currently see is adapting preview-generator to do hash not on the full path but only on the end of the path (a relative path),
this will allow us to have path like` /my/depot/temp/dir/random/dir/content/depot_file_id-64x64.jpg` where only the `/content/depot_file_id-64x64.jpg` will be used for hash.

**Comment by grignards** [comment]
> Cache is done by creating a hash of the full path of the file. but if we do temporary copy of the file, path will be a temporary path, which is not reliable !

I see two other ways:

- use a reproducible temporary file (one where we can force its full path): is less secure
- compute the hash based on the contents of the file: slower but totally reliable, has the benefit of computing once a preview if the same file is uploaded several times

**Comment by PhilippeAccorsi** [comment]
> The storage_name may be deprecated later as if we do decide to not rely anymore on DepotManager static list, this parameter
> as not anymore reason to exist.

I'm not sure to understand why we need to change name of parameter about `depot_storage_name` and `depot_storage_dir`.

**Comment by PhilippeAccorsi** [comment]
Is it not possible to use two part of configuration, like this (idea) :
- `data_storage = local`  => nothing change in configuration file (like we have at present)
- `data_storage = remote` => need to configure S3 parameter. Is it necessary to reference to S3 or can we have generic parameter for other kind of storage?

If `data_storage = remote` we need to uncomment/modify parameters about this king of storage.

We also need to change/add configuration for docker (in common.sh and entrypoint. Maybe also documentation about proxy configuration, if proxy used).

And last point, add all necessary information in issue for the changelog (breaking change / important change).

**Comment by PhilippeAccorsi** [comment]
> Is it not possible to use two part of configuration, like this (idea) :
>     * `data_storage = local`  => nothing change in configuration file (like we have at present)
>     * `data_storage = remote` => need to configure S3 parameter. Is it necessary to reference to S3 or can we have generic parameter for other kind of storage?

I understand that this is a new parameter (one more) but I think its more explicit about where you store your files (maybe its not necessary for this advanced feature).

**Comment by inkhey** [comment]
> Just re-read the depot source code and i do suggest something like this for config file:
> 
> ```ini
> depot.content.storage_name = tracim
> depot.content.backend = depot.io.memory.MemoryFileStorage # (default value will be filestorage to ensure retrocompatibility)
> depot.content.storage_path = /tmp/mystoragepath
> ```
> 
> storage_name is the name of the storage whereas other parameters refer to parameters name of depot:
> https://depot.readthedocs.io/en/latest/api.html?highlight=backend#depot.manager.DepotManager.configure
> The storage_name may be deprecated later as if we do decide to not rely anymore on DepotManager static list, this parameter
> as not anymore reason to exist.
> 
> I do suggest `depot.content.` prefix in order to be future-proof in case we do want to use multiple depot for some reason.
> 
> previous parameter will stay functional for now but set as deprecated:
> 
>     * `depot_storage_name` will become `depot.content.storage_name`. New parameter has priority over the previous one.
> 
>     * `depot_storage_dir` will become `depot.content.storage_path`. New parameter has priority over the previous one.
>       Theses parameters will be remove from the sample config file.
> 
> 
> All parameters needed for both File and S3 backend will be handled as real tracim parameter with similar mecanism as for webdav/beaker config allowing user to use full power of depot if needed but with real check and support for only S3/File/Memory case.

`depot.content.` name may be changed to something more clear. idea here is just to allow in future multiple depot without pain.

**Comment by inkhey** [comment]
> > Is it not possible to use two part of configuration, like this (idea) :
> > * `data_storage = local`  => nothing change in configuration file (like we have at present)
> > * `data_storage = remote` => need to configure S3 parameter. Is it necessary to reference to S3 or can we have generic parameter for other kind of storage?
> 
> I understand that this is a new parameter (one more) but I think its more explicit about where you store your files (maybe its not necessary for this advanced feature).

It's already explain by : 
`depot.content.backend = depot.io.memory.MemoryFileStorage`
parameter. off course it's a bit less explicit but this allow us to both:
- Properly support some config (we can officially support both file and s3 storage type) with explicit error when we do file/ s3 storage config which seems uncorrect (unvalid file path for example)
- Support all the custom depot config possible, allowing us to have almost no work (we can do nothing but it's probably better to do some documentation and config check) to support other valid depot storage backend like memory or GridFS.

**Comment by grignards** [comment]
I think that `depot.content.backend` could be named `depot.content.storage_type` (or `depot_storage_type` if we keep the current parameters as they are).

**Comment by PhilippeAccorsi** [comment]
For me, `..._storage_type` is more explicit because `depot.io.memory.MemoryFileStorage` it's unknown to me (I have not seen something like this before).

**Comment by inkhey** [comment]
`.backend` parameter name was named this way because it was a parameter for depot itself, and i expect a mecanism that return the same parameters allowing us to support more usecase.

But after discussion with @grignards about the fact that depot want us to be strict about parameters name (we do have error if we give parameter that depot does not handle, it's seems better to be more strict.


So i suggest to have something like that:
```
depot.content.storage_name = tracim
depot.content.storage_type = memory
```
or that:
```
depot.content.storage_name = tracim
depot.content.storage_type = local
depot.content.local.storage_path = /tmp/mystoragepath
```
or that:
```
depot.content.storage_name = tracim
depot.content.storage_type = s3
depot.content.s3.access_key_id = 0b9c2625dc21ef05f6ad4ddf47c5f203837aa32c
depot.content.s3.secret_access_key = b728549201e1868e08bf85a7939a767ed02f9e82
depot.content.s3.bucket = mybucker
depot.content.s3.region_name = eu-west-2
depot.content.s3.policy = private
depot.content.s3.storage_class = STANDARD_IA
depot.content.s3.endpoint_url = http://somehwere.it
depot.content.s3.prefix = tracim_content/
```

**Comment by PhilippeAccorsi** [comment]
> depot.content.storage_type = memory

Memory is for ram ?

**Comment by inkhey** [comment]
> > depot.content.storage_type = memory
> 
> Memory is for ram ?

yes, it can be useful for test usage.

**Comment by raphj** [comment]
The "memory" naming would be consistent with SQLite's naming.

**Comment by PhilippeAccorsi** [comment]
I like what you suggest and naming used. For me that is explicit and the first check for admin is to verify this parameter `depot.content.storage_type`.
I think this parameter need to be visible in "BASIC SETUP" section.

**Comment by PhilippeAccorsi** [comment]
> > > depot.content.storage_type = memory
> > 
> > 
> > Memory is for ram ?
> 
> yes, it can be useful for test usage.

Can we have a more explicit wording ? example: ram 
(https://www.howtogeek.com/267415/tech-term-confusion-memory-means-ram-not-storage/)

**Comment by PhilippeAccorsi** [comment]
> I like what you suggest and naming used. For me that is explicit and the first check for admin is to verify this parameter `depot.content.storage_type`.
> I think this parameter need to be visible in "BASIC SETUP" section.

After some discuss, we need to find a better naming to replace `content.` if its possible.

**Comment by inkhey** [comment]
> > I like what you suggest and naming used. For me that is explicit and the first check for admin is to verify this parameter `depot.content.storage_type`.
> > I think this parameter need to be visible in "BASIC SETUP" section.
> 
> After some discuss, we need to find a better naming to replace `content.` if its possible.

We can also change the full prefix `depot.content.` if needed,
i do suggest:
`content_storage.`

**Comment by inkhey** [comment]
finally, after discussion with @PhilippeAccorsi , @raphj , @grignards , je decided to choose `uploaded_files.` prefix

**Comment by inkhey** [comment]
à tester:
- supprimer base de donnée et mettre la configuration de stockage en fichier local, vérifier que ça fonctionne.
- supprimer base de donnée et mettre la configuration de stockage en s3, vérifier que ça fonctionne.
- supprimer base de donnée et mettre la configuration de stockage en memoire, vérifier que ça fonctionne.

dans les point à vérifier:
- stockage ok (téléchargement possible)
- preview ok (preview bien généré)
- recherche dans le contenu des fichiers (nécessite un docker avec le mode ingest et une configuration spécifique), faire plusieurs tentative tout de même (le mécanisme d'indexation demande des mots stricte).

**Comment by PhilippeAccorsi** [comment]
Done
