### ISSUE TITLE
Bug: Fix errors with pushpin>1.30

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3911]
## Description and expectations

Using pushpin version 1.31 makes tests fail randomly, see for example https://travis-ci.com/github/tracim/tracim/jobs/435134126
#3830 fixed pushpin version to 1.30 but we should investigate the cause of those errors and correct them in order to not be blocked with 1.30.

### How to reproduce

1.   docker pull fanout/pushpin:1:31.0
 2. run backend tests (following the documentation if needed)

Unfortunately the failures are not systematic. On my computer I didn't reproduce them, but noticed that test_live_messages.py execution is far longer (around 4 times longer).

### Version information

- Tracim version: develop, see the commit number of the travis job.
________________________________________________

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by MariePrandstetter** [comment]
Done
