### ISSUE TITLE
Feat: Find and document a recommended S3 storage software

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3914]
## Feature description and goals

#3908 will allow to configure Tracim to use a [S3 API](https://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html) backend for storing the file contents.
The goal is *not* to promote the use of AWS but rather allow to use an alternative software/service that implements the S3 API, is open-source and deploy-able on-premises.
We should study the possibilities:

- [Swift](https://swift.openstack.org/)
- [min.io](https://min.io)
- [open.io](https://www.openio.io/)
- [Zenko](https://www.zenko.io/)
- [Ceph](https://ceph.com/)
- [SeaweedFS](https://github.com/chrislusf/seaweedfs)

Then choose one as our recommended remote storage solution for Tracim.

- [x] study the foreseen solutions: ease of installation, features (especially encryption), compatibility with [depot](https://depot.readthedocs.io/en/latest/), administration (backup/…), stability(?), performance(?)
- [x] document the recommended solution and explain how to use it/install it with a Tracim installation.

## Analysis matrix

|product|licence|technology|Installation means|encryption|depot compatibility|backup|
|-|-|-|-|-|-|-|
|Swift|Apache|Python|manual/pypi/in debian buster|Yes: SSE-S3|x|x|
|min.io|Apache|Go|docker/manual|Yes: SSE-C/SSE-S3/auto|Yes (one failed content-disposition test)|hot mirror|
|open.io|Apache, OpenCore|Python (based on swift)|docker/manual|Yes: SSE-C|Yes (one failed get_key test)|cold|
|Zenko|Apache|x|Kubernetes only|x|x|x|
|Ceph|LGPL+GPL|Python/C++|x|x|x|x|
|SeaweedFS|Apache|Go|docker/manual|Yes: auto with key(s) on master's metadata store|Yes (one failed content-disposition test)|hot mirror|

- `x` means no further investigation as product doesn't meet our needs.
- `SSE-S3`: encryption with a server-generated key, generally stored in a KMS (Key Management System like HashiCorp's Vault)
- `SSE-C`: encryption with a client-provided key (requires TLS communication)

### Swift

[Docs](https://docs.openstack.org/swift/latest/)

- [Encryption details](https://docs.openstack.org/swift/latest/overview_encryption.html), can store the key directly without a KMS
- Installation is quite complex, and requires many manual steps, so this doesn't match our goal of an "easy to setup" storage.

### min.io

[Docs](https://docs.min.io/)

- [hot mirroring for backup](https://github.com/minio/minio/issues/4398)
- [cannot mirror with SSE-C encryption](https://github.com/minio/minio/issues/9752)
- [Encryption details](https://docs.min.io/docs/minio-security-overview.html)
- SSE-S3 Encryption [requires an additional service](https://docs.min.io/docs/minio-kms-quickstart-guide.html)

### open.io

[Docs](https://docs.openio.io)

- [cold backup](https://docs.openio.io/latest/source/admin-guide/operations_backup_restore.html) properly documented
- [Encryption details](https://docs.openio.io/latest/source/admin-guide/configuration_encryption.html)

Is compatible with depot but only provides SSE-C (client encryption key) which depot does not support.

### Zenko

[Docs](https://zenko.readthedocs.io/en/latest/)

Only installable on a Kubernetes cluster, so not what we need right now.

### Ceph

Ceph is a distributed storage, not only object (as S3) but also block based. The installation is geared towards clusters and the whole software seems much too complex for Tracim needs.

### SeaweedFS

[Docs](https://github.com/chrislusf/seaweedfs/wiki)

- documentation is lacking in some areas (eg. encryption)
- encryption (when enabled) is done automatically with auto-generated keys. The keys are kept in the metadata store ([leveldb](https://github.com/google/leveldb) by default)
- [backup](https://github.com/chrislusf/seaweedfs/wiki/Data-Backup)

**Comment by PhilippeAccorsi** [comment]
Exemple of playbook to deploy Seaweedfs with ansible:
- https://github.com/egeneralov/seaweedfs
- https://github.com/iliul/seaweedfs-ansible

**Comment by PhilippeAccorsi** [comment]
Exemple of playbook to deploy Min.io with ansible:
- https://github.com/atosatto/ansible-minio

**Comment by PhilippeAccorsi** [comment]
Monitoring:
- minio => via prometheus et dashboard grafana https://docs.min.io/docs/how-to-monitor-minio-using-prometheus.html
- seaweedfs => via prometheus apparement avec rendu dans grafana https://github.com/chrislusf/seaweedfs/blob/master/other/metrics/grafana_seaweedfs.json

**Comment by PhilippeAccorsi** [comment]
Done
