### ISSUE TITLE
Feat: Branding - make it possible to choose the URL and name visible in footer 

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#3921]
## Feature description and goals

At present this is visible in tracim and can not be chnage easly
~~~
Copyright - 2013 - 2020 [tracim.fr](https://tracim.fr)
~~~

Some user want to change url or remove url and just show some text to have something like that :
~~~
Copyright - 2013 - 2020 powered by toto
~~~

**Comment by Millefeuille42** [comment]
won't fix
