### ISSUE TITLE
Feat: Branding - make it possible to change the email signatures

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#3922]
## Feature description and goals

At present, if user want to modify signature of all email send by tracim, its necessary to modify all *.mak template.

For exemple, I want to remove this from all email:
~~~
<p>${_("Suricat', your digital assistant")}</p>
${_("Suricat', the bot")}
 - <a href="https://www.tracim.fr">https://www.tracim.fr</a>
~~~

**Comment by Millefeuille42** [comment]
Fixed at the current date
