### ISSUE TITLE
Bug: HTML escaping is wrong in the activity feed

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3926]
## Description and expectations

There is a visible HTML entity in the activity feed, in a user public name.

![image](https://user-images.githubusercontent.com/3817365/101159163-40970780-362d-11eb-8420-27aef0cc0df4.png)

To do: fix this for any of these elements (if applicable):
 - public names
   - for both subjects and objects of actions
 - space names
 - folder names
 - file labels

Note: there is no need for escaping quotes at these places, it's only necessary in HTML attributes.

### How to reproduce

1. Create a user with a quote in its public name
2. make it join a space
3. notice the HTML entity in the join space entry that appears in your activity feed.

### Version information

- Tracim version: v3.3 on Firefox

**Comment by Millefeuille42** [comment]
Issue seems to be resolved at this date.
