### ISSUE TITLE
Bug: the translated group mention is not auto completed (@tous in French)

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3927]
## Description and expectations

If the user has set their UI language as French and attempts to use `@tous`, the mention will work when submitted but the auto completion never suggest it

### How to reproduce

1. Set the interface language to French
2. Try to mention `@tous`
3. Notice that `@tous` is never suggested

### Version information

- Tracim version: v3.3

### Diagnostic

Could be related to https://github.com/tracim/tracim/issues/3870

**Comment by raphj** [comment]
tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
