### ISSUE TITLE
Bug: Blocage du chargement du contenu mixte actif (mixed active content)

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#3928]
## Description and expectations

After migrate to 3.3.0, after login on web interface, i have a white page. Browser logs says:

    Blocage du chargement du contenu mixte actif (mixed active content) « http://tracim.bux.fr/api/users/1/workspaces?show_owned_workspace=0 »
    TypeError: NetworkError when attempting to fetch resource.

![2020-12-04_14-15](https://user-images.githubusercontent.com/1104637/101176843-5d403900-3647-11eb-80fe-f973f0836530.png)

### Version information

- Tracim version: 3.3.0

**Comment by buxx** [comment]
After investigation, the following line in my apache proxy config cause the bug:

    ProxyPreserveHost On

This line must be isolated for `/webdav` urls:

    # Proxying Webdav
    <Location /webdav>
        # Preserving host is needed for working move/copy in webdav
        ProxyPreserveHost On
    </Location>

**Comment by Millefeuille42** [comment]
Docker image's apache config file is properly done, closing.
