### ISSUE TITLE
Bug: messages from a space a user left should be removed from their personal activity feed

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3929]
## Description and expectations

Messages from a space a user left should be removed from their personal activity feed. Keeping them may cause security issues, because user have list of all old activity visible about this space.

## Chosen implementation

The messages (not events!) will be deleted from the database in this case (see the arguments [here](https://github.com/tracim/tracim/issues/3929#issuecomment-1035054659) ).

## Version

Tracim 3.3.0

# Implemented solution:

#5435
- remove message from left space in recent activity (only the deleted space event is keep)
- remove message from deleted space in recent activity (only the deleted space event is keep)

**Comment by PhilippeAccorsi** [comment]
Updated issue to add tracim version.

**Comment by inkhey** [comment]
This issue as some others drawbacks in 3.7+:
- obtaining content in activity feed but without all the information (missing preview for non note file, no reaction)
- obtaining a warning error message about reaction "Error while fetching a list of reactions"
- link returning to nowhere: as content an user linked are not anymore accessible  link does not work as expected and does unwanted redirection to recent-activity or default page (if no workspace)

**Comment by inkhey** [comment]
note: https://github.com/tracim/tracim/issues/4068 is a similar issue (cause similar problems) but for deleted workspace.

**Comment by inkhey** [comment]
Note: To do this dev, TLM for workspace undeleted seems to be missing in code, it should be added with hook `on_workspace_undeleted`

**Comment by inkhey** [comment]
Note: To do this dev, TLM for workspace undeleted seems to be missing in code, it should be added with hook `on_workspace_undeleted`

**Comment by knodelle** [comment]
done
