### ISSUE TITLE
Bug: the advanced workspace admin screen breaks on on-demand spaces when listing requests 

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3930]
## Description and expectations

Advanced workspace admin breaks on on-demand spaces when listing requests.

### How to reproduce

1. Go to an on demand space on which you are admin
2. Open the advanced workspace admin screen (space list)
3. Go to the list of requests
4. Notice the breakage

### Version information

- Tracim version: v3.3
- Web browser: Firefox

**Comment by Millefeuille42** [comment]
Issue seems to be solved at this date.
