### ISSUE TITLE
Bug: Poor performance on space list or user list in administration page where there are many items.

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#3933]
## Description and expectations

On big instance (many space, many users) showing the space/users list as administrator can take some time.
This is because the frontend does n+1 query to retrieve space or users infos.
### How to reproduce

1. Be administrator on an instance with many space and users (for example 1000+ users, 1000+ space)
2. Click on administration menu to get list of workspace/users

### Version information

- Tracim version: v3.1.5 - 3.3 - 4.0

## Diagnostic

There is multiple way to reduce these problem : 
- return more information in list endpoints for administrator in order to not force frontend to do query for each users/workspace
- make frontend more intelligent to not try to load too much query at the same time. 
- make list endpoint paginable in order to allow frontend to get easily data part by part.

This kind problem exist probably in other place of the software but administrator will probably be the first place where the bug is found as administrator is the only person that can have full list of users or workspace. Workspace with a very long list of members can exist and may cause similar issue but are less likely.

## Linked PR
#5120

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by knodelle** [comment]
done
