### ISSUE TITLE
Feat: Optional storage encryption for previews

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3944]
## Feature description and goals

Tracim can generate previews for its contents. Those previews are stored as files on the disk which could be used to retrieve information (for example backup leakage/…).
As the preview generation mechanism is very linked to writing/reading *files* a first step in the direction of securing the previews would be to store them encrypted.
Several file-based encryption solutions exists, a good candidate for it would be [gocryptfs](https://nuetzlich.net/gocryptfs/) as it is straightforward to use and make available in the official docker image.

- [x] integrate an option in the docker image which allows to encrypt the preview cache dir (`preview_cache_dir` )

## Implemented solution
- Add copy of docker image in `Debian_New_Uwsgi`
- Adapt `Debian_New_Uwsgi` to handle encrypting depot local storage and preview_cache_dir with gocryptfs.
- Add documentation about using new docker image image with encryption.

**Comment by inkhey** [comment]
note: basic_setup.preview_cache_dir is a shortcut, the real config parameter used is `preview_cache_dir`.

**Comment by inkhey** [comment]
To test:
- Debian_Uwsgi legacy: rapid check that the docker image always work (should not have changed at all)
- Debian_New_Uwsgi with encryption enabled : first launch + rerun (try creating files)

Other things interesting to test:
- Test Debian_New_Uwsgi with test_docker mecanism (some pytest test may failed as this is not currently tested)
- Test Debian_New_Uwsgi with encryption disabled.
- - Test Debian_New_Uwsgi with different configurations.

**Comment by raphj** [comment]
tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done
