### ISSUE TITLE
Chore: warning when building the frontend - Browserslist: caniuse-lite is outdated

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3967]
## Feature description and goals

Since a week ago or two, when building the frontend, there is this warning for each frontend component:

```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
```

## Diagnostic

If I understand correctly, we indirectly depend on `caniuse-lite`. The error does not go away by running `yarn up caniuse-list` and the given command does not fix the issue when run in the repository's root directory or in each component's directory: it fails with:

```
npx : 6 installé(s) en 2.114s
No lockfile found. Run "npm install", "yarn install" or "pnpm install"
```

~~We haven't yet figured out how to solve this issue. But caniuse-lite is likely used for web browser's feature detection and having an outdated version of this database is likely going to be an issue, so we'd probably better figure out a solution quickly.~~

## Solution

Update Babel.

**Comment by grignards** [comment]
This tool seems to be the one displayed this warning: https://github.com/browserslist/browserslist

**Comment by raphj** [comment]
tested on branch by @grignards.

**Comment by PhilippeAccorsi** [comment]
Done
