### ISSUE TITLE
Bug: Starting a new container fails

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3979]
## Description and expectations

Launching a new container with the 3.4.0 image exits quickly and does not run Tracim. Messages are:
```
Adding user `redis' to group `www-data' ...
Adding user redis to group www-data
Done.
Adding user `pushpin' to group `www-data' ...
Adding user pushpin to group www-data
Done.
Adding user `zurl' to group `www-data' ...
Adding user zurl to group www-data
Done.
```

### How to reproduce

1. `docker run --rm -e DATABASE_TYPE=sqlite algoo/tracim:3.4.0`

### Version information

- Tracim version: 3.4.0

## Screenshots

________________________________________________

## Diagnostic

Two errors:
- `development.ini.sample` has a syntax error (an unwanted carriage return in a sentence)
- the docker script `common.sh` has not been updated to use the new naming of depot storage dir (`basic_setup.basic_setup.depot_storage_dir` -> `basic_setup.uploaded_files_storage_path`)

**Comment by PhilippeAccorsi** [comment]
Hi @grignards 
I think its necessary to add some `breaking/important change` information in changelog about the new parameter. If user just use development.ini config, its necessary to modify the parameter name in config file.


(You can seen what we done on old release for this kind of change).

Have a nice day ;)

**Comment by grignards** [comment]
> Hi @grignards
> I think its necessary to add some `breaking/important change` information in changelog about the new parameter. If user just use development.ini config, its necessary to modify the parameter name in config file.
> 
> (You can seen what we done on old release for this kind of change).
> 
> Have a nice day ;)

You're right, I'll add this in the changelog for the 3.4.1.

**Comment by PhilippeAccorsi** [comment]
Done.
