### ISSUE TITLE
Prepare new release 3.5.0

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3987]
## Feature description and goals

- [x] update frontend version
- [x] update backend version
- [x] update changelog

**Comment by gbonaspetti** [comment]
Wording changes made at https://github.com/tracim/tracim/issues/3901:
- At "My Account" page:
    - from "My profile" to "My Account".
    - from "Change my profile" to "Change my account settings"
- At user's page (via Administration):
    - from "Profile" to "Account".
    - from "Change the profile" to "Change the account settings"
- The "My Account" option in the header menu was changed to "Account Settings".
- In the user addition form, change from "profile" to " user type".
- Change from "All contents" to "Contents"
- At create space popup and dashboard advanced, change "This is the role that members will have by default when they join your space." to "This is the role that members will have by default when they join your space if it is open or on request."

**Comment by grignards** [comment]
Add a known limitation with sqlite (re-used ids in some cases), the bug issue: https://github.com/tracim/tracim/issues/4016

**Comment by gbonaspetti** [comment]
Wording change at https://github.com/tracim/tracim/issues/4113:
- The notification "{{author}} created {{user}}'s profile" become "{{author}} created {{user}}'s account"

**Comment by PhilippeAccorsi** [comment]
> Wording change at #4113:
> 
>     * The notifications
>       
>       * "{{author}} created {{user}}'s profile" become "{{author}} created {{user}}'s account"
>       * "{{author}} modified {{user}}'s profile" become "{{author}} modified {{user}}'s account"
>       * "{{author}} deleted {{user}}'s profile" become "{{author}} deleted {{user}}'s account"
>       * "{{author}} restored {{user}}'s profile" become "{{author}} restored {{user}}'s account"

I add link to the issue in the chnagelog. Thanks.

**Comment by gbonaspetti** [comment]
At https://github.com/tracim/tracim/issues/4114:
 - Wording change in French: _Fil d'actualité_ becomes _Fild'activité_

**Comment by PhilippeAccorsi** [comment]
Please add this in the changelog
- https://github.com/tracim/tracim/issues/4109

**Comment by PhilippeAccorsi** [comment]
> At #4114:
> 
>     * Wording change in French: _Fil d'actualité_ becomes _Fild'activité_

and
>Please add this in the changelog
>
>    #4109
done in changelog

**Comment by PhilippeAccorsi** [comment]
> Add a known limitation with sqlite (re-used ids in some cases), the bug issue: #4016

Done in changelog

**Comment by PhilippeAccorsi** [comment]
If you use tracim with docker image, you need to update the development.ini file because new parameter is added for public profile (related to #4157 )
You need to set this three parameter in the file:
- `user.custom_properties.json_schema_file_path = /tracim/backend/tracim_backend/templates/user_custom_properties/default/schema.json`
- `user.custom_properties.ui_schema_file_path = /tracim/backend/tracim_backend/templates/user_custom_properties/default/ui.json`
- `user.custom_properties.translations_dir_path = /tracim/backend/tracim_backend/templates/user_custom_properties/default/locale`

**Comment by PhilippeAccorsi** [comment]
All comment in this issue are added in the changelog.

**Comment by PhilippeAccorsi** [comment]
Done.
