### ISSUE TITLE
Bug: missing documentation for new feature in tracim 3.4.1 about  session cleaning

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#3988]
## Description and expectations

- Missing documentation visible here https://github.com/tracim/tracim/pull/3972/commits/318bf970d72dc04f7a7406844f7ed3a8592675da (Cleanup existing sessions)
- ~~missing documentation about how configure https://github.com/tracim/tracim/blob/develop/backend/doc/setting.md#content-security-policy correctly for using tracim with collabora online (collabora-online used with https and other domaine name)~~ will be fixed by code, https://github.com/tracim/tracim/issues/3997

## Version

- Tracim 3.4.1 (3.4.0 also)

## Implemented solution:
- add documentation about cleanup all existing session for both file and redis storage + warning about session configuration change.

**Comment by inkhey** [comment]
For the first point, current documentation organisation has change, so we do need to adapt the doc:
https://github.com/tracim/tracim/blob/develop/backend/doc/setting.md#file-storage-configuration-default

**Comment by raphj** [comment]
For the second point, there is some dev to do (automatically add Collabora Online's URL to the CSPs. Cc @grignards.

**Comment by PhilippeAccorsi** [comment]
> For the second point, there is some dev to do (automatically add Collabora Online's URL to the CSPs). Cc @grignards.

If fix just done in 3.5.0, we need to add documentation in changelog about what we need to do, to run tracim with collabora (deactivate CSP feature).

**Comment by inkhey** [comment]
working on the first part of missing documentation, PR available here.
https://github.com/tracim/tracim/pull/4018

**Comment by inkhey** [comment]
> > For the second point, there is some dev to do (automatically add Collabora Online's URL to the CSPs). Cc @grignards.
> 
> If fix just done in 3.5.0, we need to add documentation in changelog about what we need to do, to run tracim with collabora (deactivate CSP feature).

@grignards @PhilippeAccorsi @raphj We do need a decision here:
- Do we create a fix for 3.4.2 that automatically add collabora url
- Do we document how to make collabora work in this context
- Do we do a mix of those two ?

**Comment by inkhey** [comment]
> > > For the second point, there is some dev to do (automatically add Collabora Online's URL to the CSPs). Cc @grignards.
> > 
> > 
> > If fix just done in 3.5.0, we need to add documentation in changelog about what we need to do, to run tracim with collabora (deactivate CSP feature).
> 
> @grignards @PhilippeAccorsi @raphj We do need a decision here:
> 
>     * Do we create a fix for 3.4.2 that automatically add collabora url to csp ?
> 
>     * Do we document how to make collabora work in this context for 3.4.2 ?
> 
>     * Do we do a mix of those two ?

After discussion with @grignards and @lebouquetin , this will be solved in code in https://github.com/tracim/tracim/issues/3997

**Comment by PhilippeAccorsi** [comment]
Done for 3.4.2
