### ISSUE TITLE
Chore: make frontend build (shell) scripts fail if the compilation fails

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#3989]
## Description and expectations

Frontend shell scripts hide compilation errors (exit with the 0 error code).

To do:
 - [x] exit 1 if there is an error, so the build process can "correctly fail" and an error does not go unnoticed.

**Comment by PhilippeAccorsi** [comment]
Tested when running build_full_frontend.sh manually (not tested on docker images).

@raphj do you know what is going on with docker images ?

**Comment by PhilippeAccorsi** [comment]
Tested with docker build command and build is stopped if build frontend app failed:
~~~
[13:20:16] $ Failed building /tracim/frontend_app_admin_workspace_user.
The command '/bin/sh -c cd /tracim/     && ./install_frontend_dependencies.sh root     && ./build_full_frontend.sh' returned a non-zero code: 1
~~~

**Comment by PhilippeAccorsi** [comment]
Done.
