### ISSUE TITLE
Front/back : Translation in french: User role definition

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#399]
At present (/admin/workspaces/1):

In "user role definition" popup, role are in french but in other view, user role are in english.

ex:
![capture d ecran de 2017-10-31 16-45-09](https://user-images.githubusercontent.com/25848257/32233572-f8c5c18c-be5a-11e7-86bb-cb24fdae5eed.png)

Expected:

User role are in french all the time.

**Comment by algooapy** [comment]
`tracim/tracim/lib/utils.py:_lazy_ugettext` `l.152`:
No translator context available to translate in user requested language.
see also #173
