### ISSUE TITLE
Feat: Add public profile documentation

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#3992]
## Feature description and goals

- [x] Add public profile documentation at "_Documentation Tracim_".
- [x] If relevant, add/update documentation of elements that have been changed (such as the avatar).

**Comment by Skylsmoi** [comment]
What has been done:
- new file `backend/doc/user_custom_properties` containing:
  - how to configure the `development.ini`
  - link to official doc of json schema
  - link to doc of react json schema form
  - tracim's specific property of ui schema (tracim:display_group) and how to use it
  - backend translation guide

What is might be lacking?:
- supported features
- unsupported features

see [here](https://github.com/tracim/tracim/issues/4039#issuecomment-766859816) for the list of supported and unsupported features

**Comment by inkhey** [comment]
We should explicitly tell that we do not supported required as explained here: https://github.com/tracim/tracim/issues/4121

**Comment by PhilippeAccorsi** [comment]
Need also modification about new icon visible with migration to font awesome 5 (if new one visible).

**Comment by Skylsmoi** [comment]
> Need also modification about new icon visible with migration to font awesome 5 (if new one visible).

There should not be any new icon with the refactor for font awesome 5.
The icons will be slightly different because it's a new font but their core design should not be different.
If any difference is found, it's a regression

**Comment by PhilippeAccorsi** [comment]
Some icon like calendar or paperclip have some small change.

**Comment by PhilippeAccorsi** [comment]
I work on Tracim documentation to add new icon

**Comment by PhilippeAccorsi** [comment]
I have added some documentation about public profile in https://documentation.tracim.fr

**Comment by PhilippeAccorsi** [comment]
Done.
