### ISSUE TITLE
Bug: Collabora edition is not possible by default with `content_security_policy.enabled = True`

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#3997]
## Description and expectations

The new content security policy header does not allow collabora edition without tweaking the `additional_directives` parameter.

### How to reproduce

1. Launch a Tracim instance with content security policy and collabora
2. Try to edit a file with collabora

### Version information

- Tracim version: 3.4.1

## Screenshots

________________________________________________

## Diagnostic

`frame-src` does not allow `collaborative_document_edition.collabora.base_url`.

**Comment by lebouquetin** [comment]
Is this bug avoidable by a specific .ini configuration (and the issue is about automatically authorize collabora) or is it a hard-coded issue requirering this bugfix in order to use the content policy security?

**Comment by lebouquetin** [comment]
Could you detail the description according to my previous comment ? Thanks

**Comment by grignards** [comment]
> Is this bug avoidable by a specific .ini configuration (and the issue is about automatically authorize collabora) or is it a hard-coded issue requirering this bugfix in order to use the content policy security?

Done. This fix is very quick (I'd say ~1h).

**Comment by PhilippeAccorsi** [comment]
Done for 3.4.2
