### ISSUE TITLE
Front/back : Translation in french for add content in workspace

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#400]
At present:

on workspace, when you want to add content, all proposition are in english.
Add : folder,  thread,  file

ex:
![capture d ecran de 2017-10-31 16-49-11](https://user-images.githubusercontent.com/25848257/32233799-8f54fa00-be5b-11e7-989d-18239220af8a.png)

Expected:

Folder, thread or file are translated

**Comment by algooapy** [comment]
`tracim/tracim/lib/utils.py:_lazy_ugettext` `l.152`:
No translator context available to translate in user requested language.
see also #173
