### ISSUE TITLE
Bug: S3 storage (minio) too many preview file created for one file uploaded in tracim

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#4000]
## Description and expectations

I have uploaded one file in my tracim instance and clean preview folder before uploaded this file (no other file exist in this test instance).
This is a odp file and his size is near 21Mo.

After uploading this file, app file is open and I can seen de preview. But if i look in preview folder I can seen many file and space used is 5 time bigger than file stored in tracim.

~~~
total 129M
-rw-rw-rw- 1 www-data www-data 16M déc.  30 10:00 2cbd2ed344591899e76bfd43a1cab403-500x500-page0
-rw-rw-rw- 1 www-data www-data 33K déc.  30 10:00 2cbd2ed344591899e76bfd43a1cab403-500x500-page0.jpeg
-rwxrwxrwx 1 www-data www-data   0 déc.  30 10:00 2cbd2ed344591899e76bfd43a1cab403.lock
-rw-rw-rw- 1 www-data www-data   2 déc.  30 10:00 2cbd2ed344591899e76bfd43a1cab403_page_nb
-rw-rw-rw- 1 www-data www-data 16M déc.  30 10:00 2cbd2ed344591899e76bfd43a1cab403.pdf
-rw-rw-rw- 1 www-data www-data   2 déc.  30 10:00 58870ca566246a789e3ff7998c026cfc_page_nb
-rw-rw-rw- 1 www-data www-data 16M déc.  30 10:00 58870ca566246a789e3ff7998c026cfc.pdf
-rw-rw-rw- 1 www-data www-data 16M déc.  30 10:06 59043e4cd2b1f9ba0596ebf7846c49e9-500x500-page0
-rw-rw-rw- 1 www-data www-data 33K déc.  30 10:06 59043e4cd2b1f9ba0596ebf7846c49e9-500x500-page0.jpeg
-rwxrwxrwx 1 www-data www-data   0 déc.  30 10:06 59043e4cd2b1f9ba0596ebf7846c49e9.lock
-rw-rw-rw- 1 www-data www-data   2 déc.  30 10:06 59043e4cd2b1f9ba0596ebf7846c49e9_page_nb
-rw-rw-rw- 1 www-data www-data 16M déc.  30 10:06 59043e4cd2b1f9ba0596ebf7846c49e9.pdf
-rw-rw-rw- 1 www-data www-data   2 déc.  30 09:59 7acd9736718ebe72199db0603ae2c739_page_nb
-rw-rw-rw- 1 www-data www-data 16M déc.  30 09:59 7acd9736718ebe72199db0603ae2c739.pdf
-rw-rw-rw- 1 www-data www-data   0 déc.  30 10:00 7de99d4620693e2bf273955d80c39f29.pdf_flag
-rw-rw-rw- 1 www-data www-data 21M déc.  30 10:00 7de99d4620693e2bf273955d80c39f29.pdf.odp
-rw-rw-rw- 1 www-data www-data   2 déc.  30 10:00 f2726df29616e2304e5f92e190224743_page_nb
-rw-rw-rw- 1 www-data www-data 16M déc.  30 10:00 f2726df29616e2304e5f92e190224743.pdf
-rwxrwxrwx 1 www-data www-data   0 déc.  30 10:06 libreoffice.lock
~~~

### How to reproduce

- Clean preview folder
- upload one big odp file in tracim and wait to see preview of file in app file
- look preview file created in preview folder
=> 18-19 file are created for one file uploaded (some file created is correctly used but why too much file).

### Version information

- Tracim version: 3.4.1
- Web browser: firefox
- Version: 78.6.0esr
- Device / System: Debian Stretch / Tracim on docker with S3 storage

## Screenshots

________________________________________________

## Implemented solution

https://github.com/tracim/tracim/pull/4005
- Force consistent path to rely on preview_generator cache, this avoid to create multiple preview of same original file on s3 storage unless we decide to change the system tempdir: https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir
- fix ci issue related to docker version of openldap test.

Note:
We may imagine another solution that use config parameter to set user specific tempdir for temporary s3 original file donwload (the original file is download before generated preview of it) but this is a bit more work and has this is a temporary fix, that don't look necesseray (s3 preview are not as efficient as they could because preview_generator is not optimized for it)

**Comment by PhilippeAccorsi** [comment]
When all preview are created, I tried to refresh my Tracim web page (with cleaning browser cache) and Tracim backend re-create all files.

So for each refresh and also for each client accessing file (same access like refresh with cleaning cache), we recreate all pdf preview and jpeg preview. **This is not possible to use Tracim like this**

**Comment by lebouquetin** [comment]
All previews are pre-generated?

**Comment by inkhey** [comment]
This issue is related to the fact that support for s3 has broke the preview_generator cache mecanism.
Preview_generator cache is based on filepath. Many improvement here need change from the preview_generator side.
One quick way to reduce issues related to the way we do deal with file with non-local storage is by giving consistent path for temporary file, see https://github.com/tracim/tracim/pull/4005

**Comment by inkhey** [comment]
to test this:
- run tracim with s3 as storage backend.
- go multiple time on same file content page (to retrieve multiple time the same preview)
- verify that previews dir doesn't grow up each time your are requesting preview.

**Comment by raphj** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done for 3.4.2
