### ISSUE TITLE
Feat: Redirect /api/doc to /api/doc/

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4007]
## Feature description and goals

Currently, going to /api/doc says "/api/doc is not a valid path", which is correct but a bit misleading. I think we should just redirect `/api/doc` to `/api/doc/`.

Tracim version: 3.4

## Implementation - solution
Pyramid got an option `append_slash` on `add_notfound_view` function. If there is no slash at the end of the url, and this url doesn't match with a view, this option add a slash at the end.

### PR Linked
#5002

**Comment by PhilippeAccorsi** [comment]
This is also existing on older version of tracim.

**Comment by charline-rageade** [comment]
@Haskaris @grignards what is status of this ticket ? Can I put this in board tracim 4.1 or it's for a maintenance version ?

**Comment by grignards** [comment]
It's been merged in develop => tracim 4.1, I just added it in the right column.

**Comment by knodelle** [comment]
done
