### ISSUE TITLE
Front/back : Translation in french in calendar

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#401]
At present (/calendar):

When you go to calendar, you can see on the left, the "0.1/user" and "0.1/workspace".

Expected:

In french, this two line need to be translate.

![capture d ecran de 2017-10-31 16-34-04](https://user-images.githubusercontent.com/25848257/32232943-7f19714a-be59-11e7-99ed-b4befe6547e2.png)

**Comment by Skylsmoi** [comment]
after a small investigation, this issue seems fairly complicated to solve

**Comment by tracim** [comment]
could you explain a bit more? what did you find / what did you not find? The goal: decide later if we try to fix or if we dont

**Comment by Skylsmoi** [comment]
I couldn't find where the text that is meant to be changed in the issue description is defined.

Finding the template is easy but finding where that template is parsed and compiled is not.
Especially the values of data that are inserted into the template

**Comment by Quiwy** [comment]
@PhilippeAccorsi : does this bug still exists?

I could not find in in  interface :

![image](https://user-images.githubusercontent.com/20048264/181012836-3c6e89c9-7d03-4a31-bcf3-cb9205b23542.png)

**Comment by PhilippeAccorsi** [comment]
"Espaces" and "Utilisateur" are be translated now ?

If yes, we can close this issue and removing label "to sort".

**Comment by Quiwy** [comment]
Yes they are :smile: 
![image](https://user-images.githubusercontent.com/20048264/181056592-46c864a1-c722-4446-b0fe-11ca88130953.png)
![image](https://user-images.githubusercontent.com/20048264/181056632-771105f5-af85-4283-b97a-6c62377db424.png)

I did not tried all languages though
