### ISSUE TITLE
Front/back : Translation in french for all search button name

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#402]
At present:

When you want to use filter for searching, the button name are in english.

Expected:

Button name are in french.

![capture d ecran de 2017-10-31 16-38-19](https://user-images.githubusercontent.com/25848257/32233159-0b25b3d8-be5a-11e7-962c-afd9cb93c1af.png)

**Comment by algooapy** [comment]
`tracim/tracim/lib/utils.py:_lazy_ugettext` `l.152`:
No translator context available to translate in user requested language.
see also #173

**Comment by algooapy** [comment]
Fixed by @lebouquetin in 3af2f58
