### ISSUE TITLE
Feat: easier test launch

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4020]
## Feature description and goals

The addition of several new components, optional or not (pushpin, minio) makes running the tests manually in all cases even more lengthy. Running tests should be easier, not needing more than 2/3 commands after the development environment installation.

## Implementation

Simplify test (and dev backend) launch by:
- moving all needed services into a docker compose file
- allow choosing the database used in backend tests by a `pytest` argument (`--database`)
- adding a script to launch a dev backend server and optionally the cypress tests (`run_dev_backend.sh`).

**Comment by PhilippeAccorsi** [comment]
Tested on branch.

Comment in PR about necessary documentation (but documentation can be done in futur).

**Comment by PhilippeAccorsi** [comment]
Issue created to add documentation.
Done.
