### ISSUE TITLE
Feat: Add about user endpoint

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4027]
## Feature description and goals

The public profile displays the public name and username which are currently available only through `members` endpoints. It also needs some dynamic information (number of contributions/number of spaces the user contributed to).
`/api/users/<user_id>` cannot be used as it also returns "private" information like the user's email.

## Implementation

- [x] Rename the `GET /api/users/<user_id>/public_profile` to `/api/users/<user_id>/about`
- [x] Add the `username` and `public_name` in it
- [x] Check the access rules: only users the given user knows can access this endpoint
- [x] Add `authored_content_revisions_count` field: returns the number of content revisions the given user is author of.
- [x] Add `authored_content_revisions_space_count` field: returns the number of spaces where the given user has authored at least one revision of a content.
- [x] Rename `following_count` to `leaders_count`
- [x] Add registration date property

```json
{
  "user_id": 1,
  "public_name": "John Doe",
  "username": "john",
  "created": "2020-07-31T15:18:37Z",
  "followers_count": 23,
  "leaders_count": 42,
  "authored_content_revisions_count": 223,
  "authored_content_revisions_space_count": 20
}
```

## Time Estimation

1 man.day

**Comment by inkhey** [comment]
All is ok, but created datetime format should be same as other datetime format used in tracim (example is wrong), ex of valid value:
`2020-07-31T15:18:37Z`

**Comment by raphj** [comment]
I wonder if we should rename following_count by leader_count to be consistent with the rest. I'm really not too happy with `/property`. There is a `GET /api/system/about` endpoint, what about `/api/users/<user_id>/about`?

**Comment by grignards** [comment]
> I wonder if we should rename following_count by leader_count to be consistent with the rest. I'm really not too happy with `/property`. There is a `GET /api/system/about` endpoint, what about `/api/users/<user_id>/about`?

I agree with both proposals, I'll edit the issue.

**Comment by Skylsmoi** [comment]
While working on the public profile page, I have a found a missing property: the subscription date.

As seen in https://github.com/tracim/tracim/issues/4038, frontend must display this information

**Comment by raphj** [comment]
I am taking this one.

**Comment by raphj** [comment]
It's merged @Skylsmoi

**Comment by PhilippeAccorsi** [comment]
Done.
