### ISSUE TITLE
Chore: class HomeHasWorkspace is not used anymore

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4028]
## Feature description and goals

Since we redirect users that are members of a workspace to their activity feed, class `HomeHasWorkspace` in the frontend is not used anymore. We should probably delete it. The decision to redirect the users to the activity feed could be reverted though, so we haven't gotten rid of it when setting up this redirection.

## Linked PR
PR #5943

**Comment by Millefeuille42** [comment]
Done
