### ISSUE TITLE
 Front/back : Translation in french for "status"

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#403]
At present:

All status are in english:

work in progress
closed — validated
closed — cancelled
deprecated
subject in progress
subject closed — resolved
subject closed — cancelled 

Ex
![capture d ecran de 2017-10-31 16-41-02](https://user-images.githubusercontent.com/25848257/32233354-746f4368-be5a-11e7-86d4-62ba68e6995f.png)

Expected:

All status are in french

**Comment by algooapy** [comment]
`tracim/tracim/lib/utils.py:_lazy_ugettext` `l.152`:
No translator context available to translate in user requested language.
see also #173
