### ISSUE TITLE
Bug: Web agendas are broken in 3.4.2

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4033]
## Description and expectations

Opening an agenda does not work: the iframe load is rejected because of CSP policies.

To do:
 - [X] write an issue to add tests to the app agenda: #4040 
 - [X] write an issue to use a nonce instead of 'self': #4041 
 - [X] add `'self'` to `frame-src` for app agenda 
### How to reproduce

1. Go to an agenda

### Version information

- Tracim version: 3.4.2

## Screenshots

________________________________________________

## Diagnostic

The fix for collabora added a specific `frame-src` directive, but `'self'` was forgotten…

**Comment by PhilippeAccorsi** [comment]
Done.
