### ISSUE TITLE
Feat: Add "informations" at public profile

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4038]
## Feature description and goals

- [x] Add fixed fields (which, if not filled in, should not appear in the profile) and the information about the user's subscription date, number of interventions and number of spaces that the user is member (which are generated automatically and cannot be changed by the user).
- [x] An administrator is allowed to edit the information of any user.
- [x] When the user/administrator clicks on edit, only the selected part switches to edit mode.
- [x] When the user/administrator clicks to confirm, the selected part returns to the view mode with the changes made.
- [x] Update loading screen if necessary

## Translations

|English|French|Portuguese|
|-|-|-|
|Information|Informations|Informações|
|Subscription date|Date d'inscription|Data de subscrição|
|{{interventions}} interventions in {{spaces}} spaces| {{interventions}} interventions dans {{spaces}} espaces | {{interventions}} intervenções em {{spaces}} espaços|
|Edit|Éditer|Editar|
|Confirm|Valider|Confirmar|

## Interface
_Obs: These interface examples are only templates, not everything will be developed in this issue and some details can be changed according to the implementation._

- Public profile of the logged user

![public_profile_before_edit](https://user-images.githubusercontent.com/35422692/100880595-33530f00-34ad-11eb-9d6a-a72a701e9ec8.jpg)

- Public profile of the logged user in edition mode

![public_profile_after_edit](https://user-images.githubusercontent.com/35422692/100776027-4fe73c80-3404-11eb-83ab-d37e8d3466ed.jpg)

- Public profile of other user and menu details

![public_profile](https://user-images.githubusercontent.com/35422692/100880616-3817c300-34ad-11eb-9753-42af8e06aafc.jpg)

## Prerequisites

- #3829 

## Discussed
1. How we handle translation for the Informations fields?

**Decision**: Have a user configurable translation file (https://github.com/tracim/tracim/issues/3829#issuecomment-729705064)

## Time Estimation
3 man/day (using JSONSchema as CustomForms)

**Comment by Skylsmoi** [comment]
see implementation information in https://github.com/tracim/tracim/issues/4039

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
