### ISSUE TITLE
Front/back : Translation in french for "Type"

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#404]
At present (/workspaces/3/folders/1):

When you are in one folder, you can see "Type", and all name in type are in english.

ex:
![capture d ecran de 2017-10-31 16-43-25](https://user-images.githubusercontent.com/25848257/32233470-bed1c336-be5a-11e7-9bc9-8e850b795c65.png)

Expected:

All type are in french.

**Comment by algooapy** [comment]
`tracim/tracim/lib/utils.py:_lazy_ugettext` `l.152`:
No translator context available to translate in user requested language.
see also #173
