### ISSUE TITLE
Feat: Add link to user's profile at Activity Feed

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4047]
## Feature description and goals

Add link to user's profile at Activity Feed. In the example image below "Laurent Nom" is a clickable component and redirect to Laurent's profile.
![actualité 2](https://user-images.githubusercontent.com/35422692/104310986-e2cfc800-54d4-11eb-8444-f01fd251a6b2.png)
This component should be abstract enough to be applied at all public names and evolve to show a popover before the redirection.

## Prerequisites

None

**Comment by Skylsmoi** [comment]
That said "component" should be a component to handle every display of a user's name ?

**Comment by Skylsmoi** [comment]
I mean, I don't imagine it to only handle the link, it can be the whole display which also handles the link

**Comment by Skylsmoi** [comment]
The difference would be:
``` jsx
<ProfileLink user={props.user}>
  <div className='profile__name'>{props.user.public_name}</div>
</ProfileLink>
```

or 
``` jsx
<DisplayPublicName user={props.user} />
```

**Comment by gbonaspetti** [comment]
> That said "component" should be a component to handle every display of a user's name ?

I had in mind a wrapper that generates the link, since we will have the same behavior for usernames and avatars (see https://github.com/tracim/tracim/issues/3991), and in the future it will evolve to something similar to the image below.

![public_profile_popover](https://user-images.githubusercontent.com/35422692/104470351-ea1cd180-55b9-11eb-83bf-26a3e50f0418.png)

**Comment by Skylsmoi** [comment]
I see, a wrapper seems better indeed

**Comment by gbonaspetti** [comment]
One possibility is to have both, 4 components, the profile link and one for each case that handles the display too:

``` jsx
<ProfileLink user={props.user}>
  <div className='profile__name'>{props.user.public_name}</div>
</ProfileLink>
```

``` jsx
<ProfileLink user={props.user}>
  <Avatar ... />
</ProfileLink>
```

``` jsx
<ProfileLink user={props.user}>
  <div className='profile__username'>{props.user.username}</div>
</ProfileLink>
```

But I'm not convinced that it is the best solution. What do you think @Skylsmoi?

**Comment by gbonaspetti** [comment]
After discussion irl, we decided to make a wrapper for this issue and go deeper into the subject/options when the refactor https://github.com/tracim/tracim/issues/3991 is made.

**Comment by PhilippeAccorsi** [comment]
> ![public_profile_popover](https://user-images.githubusercontent.com/35422692/104470351-ea1cd180-55b9-11eb-83bf-26a3e50f0418.png)

In this screenshot we seen something appear when mouseover avatar but nothing append in PR. Is it normal ?

**Comment by gbonaspetti** [comment]
> > ![public_profile_popover](https://user-images.githubusercontent.com/35422692/104470351-ea1cd180-55b9-11eb-83bf-26a3e50f0418.png)
> 
> In this screenshot we seen something appear when mouseover avatar but nothing append in PR. Is it normal ?

Yes, in this issue we added just a simple link to the profile. The popover with user information will be added at https://github.com/tracim/tracim/issues/3991

**Comment by PhilippeAccorsi** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
