### ISSUE TITLE
Front/back : Translation in french for "Page history"

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#405]
At present:

When you see "Page history", all name are in english.

Ex:
Item undeleted
Item deleted
New revision
Item created

Expected:

All name are in french.

![capture d ecran de 2017-10-31 16-36-47](https://user-images.githubusercontent.com/25848257/32233057-cef56d18-be59-11e7-8f66-7cd9ca6316a4.png)

**Comment by algooapy** [comment]
`tracim/tracim/lib/utils.py:_lazy_ugettext` `l.152`: no context.translator available to translate
