### ISSUE TITLE
Feat: Create translation endpoints for comments and html-documents APIs

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4057]
## Feature description and goals

Having an automated content translation feature in Tracim can be useful to some use-cases, e.g. international teams.
Add the endpoints needed for translating the notes and comments:

- [x] `GET /api/workspaces/{workspace_id}/html-documents/{content_id}/translated/{filename}`: returns the translated html-document/note directly as an html string.
- [x] `GET /api/workspaces/{workspace_id}/html-documents/{content_id}/revisions/{revision_id}`: for API coherency reasons, return the individual revision given in the query (**not related to translation**)
- [x] `GET /api/workspaces/{workspace_id}/html-documents/{content_id}/revisions/{revision_id}/translated/{filename}`: returns the translated html-document/note (from the given revision_id) directly as an html string.
- [x] `GET /api/workspaces/{workspace_id}/contents/{content_id}/comments/{comment_content_id}/translated/{filename}`: returns the comment directly as an html string.
- [x] `GET /api/workspaces/{workspace_id}/contents/{content_id}/comments/{comment_content_id}`: for API coherency reasons, returns the comment in the same structure as one element of the `comments` API. (**not related to translation**)

Both endpoints will have a common implementation called from Tracim core (for comments) and from html-documents backend application.
Both endpoints shall have the following query string parameters:

- [x] an optional `source_language_code` language, if not given the language of the current revision's author will be used.
- [x] a mandatory `target_language_code` language.

Both shall have the same access rights as their parent content.
Translation API errors shall be returned as:
- 400 error code in case of usage error
- 502/503/504 error codes in case of service processing error.

## Prerequisites

- #4054 

### Return type

The new endpoints directly return the translated content without embedding them in a JSON format. This choice has been done to have a unified return type between all translatable contents we'll have in the future (including files). This is also in line with the move to a file storage for html-documents (instead of the current database storage).

## Estimated development time

2 human.day

## Implemented solution:
https://github.com/tracim/tracim/pull/4219

```
- add 2 endpoints to get one revision of html-content and one comment by id.
- add 3 endpoints for html-content revision/ html-content and comment translation
- add "translation_service__enabled" parameter to /system/config endpoint.
- use is_translation_service_enabled checker as workaround to a limitation of hapic related to dynamically load part of controller.
- fix unrelated issue in test_api___elasticsearch_search_ok__wildcard__facet_only.

Refs: #4057
```

**Comment by inkhey** [comment]
>  a optional target_language_code language, if not given the language of request's user will be used.

This mean the endpoint result is user specific. We can do this (to avoid very long url GET /api/users/{user-id}/workspaces/{workspace_id}/html-documents/{content_id}/translated) but it should not be cached

**Comment by inkhey** [comment]
Another question: We should not been able to translated a previous revision of a comment ? 
I'm ok with that but that something to consider. (as we will allow to modify comment in future, we probably will give access to previous revision of comment).

**Comment by inkhey** [comment]
`GET /api/workspaces/{workspace_id}/html-documents/{content_id}/revisions/{revision_id}`
We agree that we implement this one for html-documents now but it make sense to have similar endpoint for others content type later (refactoring it may be interesting) ?

**Comment by grignards** [comment]
> > a optional target_language_code language, if not given the language of request's user will be used.
> 
> This mean the endpoint result is user specific. We can do this (to avoid very long url `GET /api/users/{user-id}/workspaces/{workspace_id}/html-documents/{content_id}/translated`) but it should not be cached

You're right, we should avoid that behavior, I'll make the target_language_code mandatory.

**Comment by grignards** [comment]
> `GET /api/workspaces/{workspace_id}/html-documents/{content_id}/revisions/{revision_id}`
> We agree that we implement this one for html-documents now but it make sense to have similar endpoint for others content type later (refactoring it may be interesting) ?

Yes, I wrote the minimum we currently need, do you see an increased cost if we add those endpoints for the other content types later?

**Comment by inkhey** [comment]
> > `GET /api/workspaces/{workspace_id}/html-documents/{content_id}/revisions/{revision_id}`
> > We agree that we implement this one for html-documents now but it make sense to have similar endpoint for others content type later (refactoring it may be interesting) ?
> 
> Yes, I wrote the minimum we currently need, do you see an increased cost if we add those endpoints for the other content types later?

not really, i just wanted to be sure. We should probably take some time later to think about a refactoring for this kind of endpoints where there is almost not change between content type.

**Comment by inkhey** [comment]
> Another question: We should not been able to translated a previous revision of a comment ?
> I'm ok with that but that something to consider. (as we will allow to modify comment in future, we probably will give access to previous revision of comment).

@grignards Seems like you don't see this question. Any idea about this (just to know, not mandatory for :rocket: ) ?

**Comment by lebouquetin** [comment]
I do not understand the choice not to publish an API for translating comments by revision. Even if this is not required at the moment, this is exactly the same behavior for comments and html documents, so implementing both is a question of a few lines of code. By the way it ensure the code is factorized.

What is really the reason for implementing specific behavior ?

By the way, translating the description of a file is not possible with your choice of implementation which has no technical reason.

A route like this: `GET /api/workspaces/{workspace_id}/html-documents/{content_id}/translated` would answer all cases if implemented as `GET /api/workspaces/{workspace_id}/content/{content_id}/translated`

**Comment by raphj** [comment]
I'd say 2 man.day for this issue.

**Comment by inkhey** [comment]
> I'd say 2 man.day for this issue.

I do agree.

**Comment by lebouquetin** [comment]
@grignards instead of implementing explict endpoints for each type of content we want to translate, why not sharing a generic endpoint? It would also allow to translate personal page, for example, without needing backend specific stuff.

**Comment by lebouquetin** [comment]
This will also allow to translate both description and raw_content without to require specific endpoints. Same thing for labels etc.

**Comment by lebouquetin** [comment]
(note: this does not answer to the async / file based translation needs - but for text - which would be short, this is a far way more generic way to get translation)

**Comment by inkhey** [comment]
> @grignards instead of implementing explict endpoints for each type of content we want to translate, why not sharing a generic endpoint? It would also allow to translate personal page, for example, without needing backend specific stuff.

You suggest something like this ?:
```json
POST /api/translate/text
{
  "text": "a cat",
  "source_language_code": "fr",
  "target_language_code": "en",
}
->
{
  "text": "un chat",
  "language_code": "en"
}
```
1. i'm not sure about POST vs GET, but we do an **action** here so GET doesn't make much sense.
2. as we do use json body to pass data, i don't see much reasons to use get or post param for source/target language.

**Comment by raphj** [comment]
It seems dangerous to publish a generic endpoint for translating texts. Couldn't it be abused?

**Comment by lebouquetin** [comment]
@inkhey yes this is what I mean.

> It seems dangerous to publish a generic endpoint for translating texts. Couldn't it be abused?

It can be abused by authenticated users.

But this can also be the case with editable content translation : 

- you create a content named "Translation sandbox
- you edit it, then translate the new text.
- edit again and translate it.
- ...

**Comment by Skylsmoi** [comment]
can you add to the description what type of paremeters `source_language_code` and `target_language_code` are please?
I'm assuming it's query though

**Comment by grignards** [comment]
> @grignards can you add to the description what type of paremeters `source_language_code` and `target_language_code` are please?
> I'm assuming it's query though

Done, your assumption was right.

**Comment by grignards** [comment]
> @grignards instead of implementing explict endpoints for each type of content we want to translate, why not sharing a generic endpoint? It would also allow to translate personal page, for example, without needing backend specific stuff.

To follow on our oral discussion yesterday: I was in the mindset of « creating APIs to translate Tracim contents », contents which do not have a defined maximum size. This is less true for notes/comments, but nothing prevents a user to create a very big note (especially with embedded images).
Should we decide to translate short texts (labels/…) providing a generic « short text translation » service is a solution to consider.

**Comment by PhilippeAccorsi** [comment]
Done.
