### ISSUE TITLE
Feat: Add content translation to timeline

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4063]
## Feature description and goals

It will be possible to translate comments automatically for instances that have a translation API. That is, if the configuration parameter is activated:
- [x] Add "See translation" button at the bottom of the comments
- [x] When this button is clicked the comment's text is replaced by its translation and the button's label becomes "Return to the original language" (see the gif in interface section)
- [x] The translated text should have the color `lightDarkGrey` and a left line in the primary color (see last suggestion at https://github.com/tracim/tracim/issues/4064#issuecomment-770960660)
- [x] When "Return to the original language" is clicked the text returns to the original language and format, i.e. without the line and  with `fontColor` color
- [x] The font size is the same for both texts and the button (`fontSizeSmall`)
- [x] The button should have the `lightDarkGrey` color, be underlined when hovered and should be aligned to the avatar with a distance around 10px from the text (to be confirmed with some tests during development)
- [x] The translation is not saved, i.e. if the user refreshes the page all translated comments return to the original language
- [x] If the translation endpoint returns an error, a flash message should be displayed and the text should stay at its original language.
    - Default: "Error while translating content"
- [x] Since the translation process can take time (if the comment is long for example), right after clicking on the translate button, turn it into a loader until the endpoint has responded

## Prerequisites

#4057 

## Translations

|English|French|Portuguese|
|-|-|-|
|See translation|Voir la traduction|Visualizar tradução|
|Restore the original language|Rétablir la langue d'origine|Restaurar a língua original|
|Error while translating content|Erreur lors de la traduction du contenu|Erro ao traduzir o conteúdo|

## Interface

_Obs: These interface examples are only templates, not everything will be developed in this issue and some details can be changed according to the implementation._
- interface
![content_translation](https://user-images.githubusercontent.com/35422692/105019653-9a6d5880-5a46-11eb-9fa4-78d3ad573c4e.png)
- gif
![GIF content_translation](https://user-images.githubusercontent.com/35422692/105019645-99d4c200-5a46-11eb-894d-d57eef442cfb.gif)

## Time estimation
1-2 man/day

**Comment by grignards** [comment]
What should happen if the translation endpoint returns an error? I guess a flash message display?

**Comment by gbonaspetti** [comment]
> What should happen if the translation endpoint returns an error? I guess a flash message display?

Yes, I'll added this at description

**Comment by raphj** [comment]
> The translated text should be in italic and have the color lightDarkGrey

Both things render the text less readable. What's more, it will hide parts that are already in italic in the original text for HTML comments. Could we show the fact that we are looking at a translated comment another way?

**Comment by lebouquetin** [comment]
@raphj please do not just say "it's not right" (If you think it's not a good idea, I expect you suggest sommething else)

**Comment by raphj** [comment]
We've discussed it at https://github.com/tracim/tracim/issues/4064#issuecomment-770850935

**Comment by inkhey** [comment]
tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
