### ISSUE TITLE
Feat: Add content translation to notes

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4064]
## Feature description and goals

It will be possible to translate contents automatically for instances that have a translation API. That is, when the configuration parameter is activated:
- [x] Add a "See translation" button at the top of the note
- [x] When this button is clicked the text shall be replaced by its translation and the button's label shall become "Return to the original language"
- [x] The translated text should have the color `lightDarkGrey` and a left line in the primary color (see last suggestion at https://github.com/tracim/tracim/issues/4064#issuecomment-770960660)
- [x] When "Return to the original language" is clicked the text returns to the original language and format, i.e. without the line and  with `fontColor` color
- [x] The font size is the same for both texts (`fontSize`) and the button has the size `fontSizeSmall`
- [x] The button should have the `mediumDarkGrey` color, be underlined when hovered and should be aligned to the note's content with a distance around 10px to the text (to be confirmed with some tests during development)
- [x] The translation is not saved, i.e. if the user refreshes the page the content returns to the original language
- [x] The original content shall be used when editing the note :warning: 
- [x] Since the translation process can take time (if the note is long for example), right after clicking on the translate button, turn it into a loader until the endpoint has responded

## Prerequisites

#4057 

## Translations

|English|French|Portuguese|
|-|-|-|
|See translation|Voir la traduction|Visualizar tradução|
|Restore the original language|Rétablir la langue d'origine|Restaurar a língua original|

## Interface

_Obs: These interface examples are only templates, not everything will be developed in this issue and some details can be changed according to the implementation._
![content_translation](https://user-images.githubusercontent.com/35422692/105019653-9a6d5880-5a46-11eb-9fa4-78d3ad573c4e.png)

## Time estimation
1-2 man/day

**Comment by grignards** [comment]
@gbonaspetti I added a warning for the edition mode. I also think that the translate button should be disabled during edition. Do you agree (in fact maybe in your mind it completely disappears)?

**Comment by grignards** [comment]
BTW shouldn't the english be "Show translation" rather than "See"?

**Comment by raphj** [comment]
> The translated text should be in italic and have the color lightDarkGrey

As I said in https://github.com/tracim/tracim/issues/4063#issuecomment-770840310, Both things render the text less readable and will hide parts that are already in italic in the original text.

The problem is bigger for HTML notes as they can be quite long.

Maybe we could add a colored border somewhere instead?

**Comment by lebouquetin** [comment]
colored border do not look like clear enough to me (or it will overload the page). What about the twitter way to show translations? What about mattermost/slack/any other tool?

@gbonaspetti do you have alternative ideas?

Note: the reason for translation is not to offer a fully ready-to-user translated version of a content but to help understanding the meaning of the content

**Comment by asf-algoo** [comment]
> colored border do not look like clear enough to me (or it will overload the page). What about the twitter way to show translations? What about mattermost/slack/any other tool?
> 
> @gbonaspetti do you have alternative ideas?
> 
> Note: the reason for translation is not to offer a fully ready-to-user translated version of a content but to help understanding the meaning of the content

Facebook: Grey left-border, displayed below for contents and replaced the original text for comments
Linkedin: Only change the text to grey, displayed below
Twitter: Same text design, displayed below

Some options:
![ASF_translation](https://user-images.githubusercontent.com/71391182/106483006-58b0c900-64ae-11eb-8db4-a92b28db5326.png)
![ASF_translation (1)](https://user-images.githubusercontent.com/71391182/106483022-5cdce680-64ae-11eb-85a0-a9f16fff96d3.png)
![ASF_translation (2)](https://user-images.githubusercontent.com/71391182/106483039-61090400-64ae-11eb-97f9-17358661286e.png)

**Comment by gbonaspetti** [comment]
> colored border do not look like clear enough to me (or it will overload the page). What about the twitter way to show translations? What about mattermost/slack/any other tool?
> 
> @gbonaspetti do you have alternative ideas?
> 
> Note: the reason for translation is not to offer a fully ready-to-user translated version of a content but to help understanding the meaning of the content

Facebook: Grey left-border, displayed below for contents and replaced the original text for comments
Linkedin: Only change the text to grey, displayed below
Twitter: Same text design, displayed below

Some options:
![ASF_translation](https://user-images.githubusercontent.com/71391182/106483006-58b0c900-64ae-11eb-8db4-a92b28db5326.png)
![ASF_translation (1)](https://user-images.githubusercontent.com/71391182/106483022-5cdce680-64ae-11eb-85a0-a9f16fff96d3.png)
![ASF_translation (2)](https://user-images.githubusercontent.com/71391182/106483039-61090400-64ae-11eb-97f9-17358661286e.png)

**Comment by raphj** [comment]
@gbonaspetti I think your last comment would rather go to the other issue. Otherwise these mockups look good to me. We might want to use `outline` instead of `border` or be careful to use transparent borders when the feature is not active so the box does not use more space when translated. We may want to go for the vertical (top+bottom) option to leave more horizontal space especially on mobile.

I'd argue that the "Restore the original language" link + borders already hints well about the feature being active and we could avoid graying the text, but as long as the contrast is accessible enough I am willing to compromise.

**Comment by lebouquetin** [comment]
> We may want to go for the vertical (top+bottom) option to leave more horizontal space especially on mobile.

I disagree with the vertical (top+bottom) option: on a computer (which is the major way to use tracim), there are plenty of space horizontally while we do not have enough space vertically (look at at a timeline and you will see that with multiple headers, there is only a few messages shown.

For me the third option is the one to choose at the moment

**Comment by gbonaspetti** [comment]
> > We may want to go for the vertical (top+bottom) option to leave more horizontal space especially on mobile.
> 
> I disagree with the vertical (top+bottom) option: on a computer (which is the major way to use tracim), there are plenty of space horizontally while we do not have enough space vertically (look at at a timeline and you will see that with multiple headers, there is only a few messages shown.
> 
> For me the third option is the one to choose at the moment

We can do the third one and test at mobile, if it's not enough space we leave only the text in grey.

**Comment by raphj** [comment]
good for me!

**Comment by raphj** [comment]
So for notes, should we use the same look than comments for consistency?

**Comment by gbonaspetti** [comment]
> So for notes, should we use the same look than comments for consistency?

Yes

**Comment by inkhey** [comment]
tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
