### ISSUE TITLE
Bug: link added in clipboard is not valid (from personal activity feed - tested with file, note, thread)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#4066]
## Description and expectations

Link available in clipboard since I clic on "copy content link" visible in personnal activity feed, is a wrong link. Link visible for a file:
~~~
http://192.168.1.150:7999/ui/workspaces/:idws/contents/file/1
~~~

Expected
- [ ] link created in clipboard have a good workspace_id

### How to reproduce

- create a space
- add one file
- open activity feed (personnal and not activity feed of space)
- clic on "..."
- clic on "copy content link"
- open a nex tab
- paste from clipboard
=> link have no workspace_id

### Version information

- Tracim version: >= 3.4.3
- Web browser: firefox
- Version: 78.6.0esr
- Device / System: Debian Buster

## Screenshots

________________________________________________

**Comment by MariePrandstetter** [comment]
I'm not reproducting

**Comment by charline-rageade** [comment]
I'm not reproducting

**Comment by charline-rageade** [comment]
Fixed at https://github.com/tracim/tracim/commit/869281885502049fafb825877f68b8fa50226952
