### ISSUE TITLE
Front/back : Translation in french for login page

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#408]
At present:

Many word need to be changed.

- _Login_  **to**  "Connexion" ou "Se connecter"

- _Default login: ''' (password: ''' )_ **to** Connexion par défaut: email: ''' (mot de passe: ''')

- _Collaboration, versionning and traceability_ **to** french translation

- _in case of problem, please contact the administrator._ **to** french translation

- _Login_ Button **to** "Connexion"

![capture d ecran de 2017-10-31 16-47-04](https://user-images.githubusercontent.com/25848257/32233685-41e3a28a-be5b-11e7-9ea3-bff8e95d38df.png)

**Comment by tracim** [comment]
Actually, most of these sentences are configured in development.ini file
