### ISSUE TITLE
Feat: Add search page interface for advanced search

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4083]
## Feature description and goals

The advanced search will be improved by adding some result filters and more results possibilities, for this we will add a new interface for advanced search.
This issue will not implement the filters menu (see https://github.com/tracim/tracim/issues/4097) nor the different types of results (see https://github.com/tracim/tracim/issues/4085). Just update the interface and some interactions for now.

- [x] Add search input at the search screen.
- [x] Update `N best results for "X"` message to `Showing N of M results` with lightDarkGrey color.
- [x] Update title adding the keyword.
- [x] After modifying a keyword the user must click on the search icon or press the Enter key to validate. After this validation, the title and both input are updated with the new keywords.
- [x] Allow the click at search icon even if there is no keyword
    - Tooltip: Search
    -  Hover: fontColor
    - Cursor: pointer
- [x] Add a filter button in the top-right corner
    - On click it'll open the filter menu
    - In sm and xs screens the label should be hidden
    - Icon: fas fa-sliders-h
    - Label: Filter
    - Tooltip: Search filters
- [x] Add a filter menu: 
    - For now just the rectangle, the title and the close option
        - Width: 300px to md, lg and xl screens and 100% to sm and xs screens
        - Background color: offWhite
        - Border color: grey
        - Icon: fas fa-sliders-h
        - Title: Search filters
- [x] By default the filter's menu is closed.
- [x] Update loader if needed

## Prerequisites

https://github.com/tracim/tracim/issues/4094 (see https://github.com/tracim/tracim/issues/4083#issuecomment-767553590)

## Translations

|English|French|Portuguese|
|-|-|-|
|Filter|Filtrer|Filtrar|
|Search filters|Filtres de recherche|Filtros de pesquisa|
|Search|Rechercher|Pesquisar|
|Showing {{number_display_results}} of {{number_total_results}} results|{{number_display_results}} résultats affichées sur {{number_total_results}}|Mostrando {{number_display_results}} de {{number_total_results}} resultados|
|Results for "{{keywords}}"|Résultats pour "{{keywords}}"|Resultados para "{{keywords}}"|

## Interface
_Obs: These interface examples are only templates, not everything will be developed in this issue and some details can be changed according to the implementation._

- Button view
    - md, lg, xl screens
    ![search_page](https://user-images.githubusercontent.com/35422692/105695965-fdf1fd00-5f02-11eb-86a7-c97ab9b8521e.png)
    - sm and xs screens
    ![search_mobile (1)](https://user-images.githubusercontent.com/35422692/105696053-17934480-5f03-11eb-9405-26ec185718cb.png)
- Filter menu view
    - md, lg, xl screens
    ![search_page (2)](https://user-images.githubusercontent.com/35422692/105696187-43aec580-5f03-11eb-86bd-a62b9a791da5.png)
    - sm and xs screens
    ![search_mobile (2)](https://user-images.githubusercontent.com/35422692/105696357-7fe22600-5f03-11eb-97c9-cdc369816557.png)

## Time Estimation
3 man/day

**Comment by grignards** [comment]
Tracim provides two search backends : one "simple" and one requiring elasticsearch as a third-party component.
This improved search page will only work with the elasticsearch backend so the work here is not to update the existing frontend search page but rather split it (while keeping common parts in common components).
Displaying one page or the other will be driven by a configuration available in `system/config`.

**Comment by raphj** [comment]
For icons, maybe we should start using FontAwesome 5?

**Comment by Skylsmoi** [comment]
> For icons, maybe we should start using FontAwesome 5?

yes, we must.
fontawesome 5 is part of 3.5.x

**Comment by gbonaspetti** [comment]
> > For icons, maybe we should start using FontAwesome 5?
> 
> yes, we must.
> fontawesome 5 is part of 3.5.x

yes, I updated the description

**Comment by Skylsmoi** [comment]
Test results:
- The filter pane height isn't fully handled
  - as we discussed @gbonaspetti , it will be handled in the issue for implementing facets in front
- The tooltip on the title isn't properly positioned in the search result page. It is correct on other pages

**Comment by gbonaspetti** [comment]
Fixed tooltip at https://github.com/tracim/tracim/pull/4165/commits/b1a2e9024b3bb72fffafc8d78b51fe33a5f64bcb and, as said, the height wil be handle at  https://github.com/tracim/tracim/issues/4097

**Comment by Skylsmoi** [comment]
verified
