### ISSUE TITLE
Feat: Add loader screen for search page

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4084]
## Feature description and goals

- [x] Add loader screen for advanced search page 

## Prerequisites

- #4083 

Try to make a quick review of the existing skeleton loaders solutions for React, see what are their main differences ("global/per-page" loader vs. "per-component" loader for example) then choose one (or build one ourselves if we really think none match our needs).
From what was seen during the public profile development, a "global/per-page" seems to be easier as it avoids propagating the loaded/not loaded state in every component so it eases their development. One drawback of this approach is the page layout which we'd have to do "twice": once for the real components and once for the skeleton. If we go the "per-page" way we should choose a solution that makes it easy to duplicate/create/modify a layout.

One of the existing solutions: https://skeletonreact.com/

## Interface
_Obs: This interface example is only a template, not everything will be developed in this issue and/or some details can be changed according to the implementation._
![search_loading_page](https://user-images.githubusercontent.com/35422692/106449430-415ce600-6484-11eb-8175-28f0c8411565.png)

## Translations

|English|French|Portuguese|
|-|-|-|
|Loading|Chargement|Carregando|

## Time Estimation
2 man/day

## Implemented solution
Loader per page using `<svg>` tags. To make it responsive the `<svg>` has a container with `position: relative` and its position as absolute with a width relative to the container and a fixed height (scroll if overflow). 
The svg version of mockups was used to do the base of the code and the text, the title and the responsive behavior were added after. As I made some attempts to automate the process as much as possible, I changed some things in the base code and the final code is "clean", but the behavior is the same and the svg file code could be used (modifying only the double quotes in single so there are no lint errors).

**Comment by grignards** [comment]
In this issue I would recommend to make a quick review of the existing skeleton loaders solutions for React, see what are their main differences ("global/per-page" loader vs. "per-component" loader for example) then choose one (or build one ourselves if we really think none match our needs).
From what I saw during the public profile development, a "global/per-page" seems to be easier as it avoids propagating the loaded/not loaded state in every component so it eases their development. The drawback of this approach is the page layout which we'd have to do "twice": once for the real components and once for the skeleton. If we go the "per-page" way we should choose a solution that makes it easy to duplicate a layout.

One of the existing solutions: https://skeletonreact.com/

**Comment by Skylsmoi** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
