### ISSUE TITLE
Feat: Update UI at content search

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4085]
## Feature description and goals

Now it will be possible to search not only for contents but also in spaces and users for advanced search. This issue will not implement the complete change for all three types, only for the content type.

- [x] By default the page should display the results of the content search
- With sm and xs screens:
    - [x] The breadcrumbs should be hidden
    - [x] The icon type should have fontSizeMedium
- With xl, lg and md screens:
    - [x] The icon type/avatar should have fontSizeTitle

### Contents list

- [x] Columns with xl, lg and md screens:
    - Type
    - Title and path
    - Last modified
    - Information (fontSizeSmall)
        - For folders: authorized types
        - For others: status and number of comments 
- [x] Columns with sm and xs screens:
    - Type and title
    - Last modified (the developer should test, if there's not enough space at xs screens, this column should also be hidden)
- Click on :
    - [x] the name of the user who did the last modification redirects to his profile (use the TimedEvent.jsx component)
    - [x] the breadcrumbs redirect to the right place
    - [x] the rest redirects to the content
- [x] Each type must have its name written under the icon on the lg and xl screens in fontSizeSmall size
- ~~The file path is not send by backend.~~ update:
  - the file path is always send by the backend and will be up to date regardless of using elastic search or not and regardless if the content has been renamed or moved
  - The only difference with current search endpoint will be the removal of the key `parent_id` which isn't used by the frontend
  - [x] remove the key `parent_id` for the content path list from the reducer searchResult.js
-  The folder's authorized content won't be displayed for the first version

## Prerequisites

- https://github.com/tracim/tracim/issues/4095

## Translations

|English|French|Portuguese|
|-|-|-|
|Contents|Contenus|Conteúdos|
|Users|Utilisateurs|Utilizadores|
|Spaces|Espaces|Espaços|
|Type|Type|Tipo|
|Title and Path|Titre et chemin|Título e caminho|
|Last modification|Dernière modification|Última modificação|
|Information|Informations|Informações|
|Avatar|Avatar|Avatar|
|Name|Nom|Nome|
|Full Name|Nom complet|Nome completo|
|and|et|e|

## Interface
_Obs: These interface examples are only templates, not everything will be developed in this issue and some details can be changed according to the implementation._

![search_page](https://user-images.githubusercontent.com/35422692/105707806-c63f8100-5f13-11eb-9973-ac3b16f08f4d.png)
![search_page (1)](https://user-images.githubusercontent.com/35422692/105707821-cc356200-5f13-11eb-86aa-9b12d62b51eb.png)
![search_page](https://user-images.githubusercontent.com/35422692/105819338-56cf9d00-5fb8-11eb-956a-aa0f4dfcde2e.png)
![search_mobile](https://user-images.githubusercontent.com/35422692/105707862-df483200-5f13-11eb-889a-fc29e6dc5315.png)

## Time Estimation
4 man/day

**Comment by inkhey** [comment]
https://user-images.githubusercontent.com/35422692/105707839-d48d9d00-5f13-11eb-8266-658541fda018.png
@gbonaspetti  Not sure to understood the idea of sidebar search for members here. It's a search bar on facet result ? if yes, is there a reason to do show the number of items related)

**Comment by inkhey** [comment]
These data could probably not been returned by search endpoint itself for performance reason, but the mecanism to get informations need some clarifications:
- numbers of comments is guessable the same way as in activity feed. I far i know there is no count endpoint.
- number of members of a workspace is guessable too. as far i know there is no count endpoint.
- numbers of content of a workspace is a tricky case: 
  - What should and what should not be included here (do we include public uploaded file ? dir ?)
  - as far i know there is no count endpoint.
- email is obtainable for admin user.

**Comment by inkhey** [comment]
@gbonaspetti the "Emplacement" Facet is really unclear. I don't think we could return faceted search not for fields values but for fields that match.
So the way i do see this one is that these box will always been visible and do just adjust the fields where the search is made. I will not being possible to have the "count".
@grignards what do think about this "facet "?

**Comment by gbonaspetti** [comment]
> https://user-images.githubusercontent.com/35422692/105707839-d48d9d00-5f13-11eb-8266-658541fda018.png
> @gbonaspetti Not sure to understood the idea of sidebar search for members here. It's a search bar on facet result ? if yes, is there a reason to do show the number of items related)

![membre](https://user-images.githubusercontent.com/35422692/105825151-91890380-5fbf-11eb-8aeb-d9fe7499bf64.gif)

The idea is have a text input with the auto completion popup, at the popup we have only the members that has a difference at search results, if you chose a member it is selected, the result are changed according to the member and you don't need the number of related items.

**Comment by gbonaspetti** [comment]
> These data will probably not been returned by search endpoint itself for performance reason, but the mecanism to get informations need some clarifications:
> 
> * numbers of comments is obtainable the same way as in activity feed. I far i know there is no count endpoint. this data may be stored in search as search will have to renew index for each comment, but we do way expect filtering on this ?
> * number of members of a workspace is guessable too. as far i know there is no count endpoint. it's possible to imagine index it but it does make much sense.
> * numbers of content of a workspace is a tricky case:
>   
>   * What should and what should not be included here (do we include public uploaded file ? dir ?)
>   * as far i know there is no count endpoint.
>   * for this one, it's really not a good  idea to index it, we may do this by accepting deprecated data on count.
> * email is obtainable for admin user, this cannot be returned by search without complex tweak.
> * i not sure about authorized types. It doesn't make much sense to index if we don't do search on it but we could.
> * avatar will, of course, be retrieved by frontend, backend search will not store raw data.

Authorized types and the number of comments, members and contents are not searchable fields for now, they are just some extra information to help to identify the result that you're looking for. they can always be deleted/changed if we see that they are not useful.

**Comment by gbonaspetti** [comment]
> @gbonaspetti the "Emplacement" Facet is really unclear. I don't think we could return faceted search not for fields values but for fields that match.
> So the way i do see this one is that these box will always been visible and do just adjust the fields where the search is made. I will not being possible to have the "count".
> @grignards what do think about this "facet "?

The filter "search only at ..." is required, if only the count is a problem we can remove for this one, but ideally it would be better to have the count

**Comment by inkhey** [comment]
> > https://user-images.githubusercontent.com/35422692/105707839-d48d9d00-5f13-11eb-8266-658541fda018.png
> > @gbonaspetti Not sure to understood the idea of sidebar search for members here. It's a search bar on facet result ? if yes, is there a reason to do show the number of items related)
> 
> ![membre](https://user-images.githubusercontent.com/35422692/105825151-91890380-5fbf-11eb-8aeb-d9fe7499bf64.gif)
> 
> The idea is have a text input with the auto completion popup, at the popup we have only the members that has a difference at search results, if you chose a member it is selected, the result are changed according to the member and you don't need the number of related items.

So, if backend return just  "user_id": number of match, it this enough for you ?

**Comment by gbonaspetti** [comment]
> > > https://user-images.githubusercontent.com/35422692/105707839-d48d9d00-5f13-11eb-8266-658541fda018.png
> > > @gbonaspetti Not sure to understood the idea of sidebar search for members here. It's a search bar on facet result ? if yes, is there a reason to do show the number of items related)
> > 
> > 
> > ![membre](https://user-images.githubusercontent.com/35422692/105825151-91890380-5fbf-11eb-8aeb-d9fe7499bf64.gif)
> > The idea is have a text input with the auto completion popup, at the popup we have only the members that has a difference at search results, if you chose a member it is selected, the result are changed according to the member and you don't need the number of related items.
> 
> So, if backend return just "user_id": number of match, it this enough for you ?

For the auto-completion I expected the same as `known_members` but only with the members that correspond to the possible results

**Comment by grignards** [comment]
Do we really want to display the emails in the user informations ? I ask the question because they are never displayed anywhere in the interface, I supposed for confidentiality reasons (for example we do not display the email in the public profile).

**Comment by raphj** [comment]
> The frontend must search for the 3 types in parallel so that there is no loading time each time the user changes the type.

Isn't this a premature optimization?

**Comment by lebouquetin** [comment]
> Isn't this a premature optimization that adds unnecessary complexity for a problem that might not exist?

It's not an optimization: this is the way a search tool must work. User do not want to search for a specific entity type but for some criteria.

> As a user, I would expect another request + waiting time to happen if I change anything related to my search query.

As a user I want to search for some criteria. Looking for users, workspaces or contents are filters of the search results

**Comment by gbonaspetti** [comment]
> Do we really want to display the emails in the user informations ? I ask the question because they are never displayed anywhere in the interface, I supposed for confidentiality reasons (for example we do not display the email in the public profile).

I updated the description.

**Comment by inkhey** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
