### ISSUE TITLE
Feat: allow to migrate a tracim instance from standard storage to minio

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#4087]
## Feature description and goals

We have instances using legacy storage (local disk). As we now have the possibility to store on s3/min.io, this would be very helpful to get a script that allow to migrate data.

## Implemented solution:
https://github.com/tracim/tracim/pull/4392
- add `tracimcli db migrate-storage` command permitting to copy file from one storage to another and switching database link too.

**Comment by grignards** [comment]
Tested on branch.
