### ISSUE TITLE
Front/back: default name for login page

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#409]
At present:

Default login: admin@admin.admin (password: admin@admin.admin)

Expected:

**I think its better to have** 
Default login: email: admin@admin.admin (password: admin@admin.admin)
or
Default login: (email: admin@admin.admin ; password: admin@admin.admin)

**Comment by tracim** [comment]
c'est de la configuration, ça aussi, non ?

**Comment by PhilippeAccorsi** [comment]
Information oui c'est dans development.ini.base

**Comment by tracim** [comment]
@PhilippeAccorsi corrige directement en mettant `Default login: email: admin@admin.admin (password: admin@admin.admin)`

**Comment by PhilippeAccorsi** [comment]
@lebouquetin  on laisse la parenthèse seulement sur le password?

**Comment by tracim** [comment]
oui

**Comment by PhilippeAccorsi** [comment]
commit #414
