### ISSUE TITLE
Feat: Add content search filters

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4097]
## Feature description and goals

We will have specific filters for the content  search. Those filters are predefined and sent by the backend (see https://github.com/tracim/tracim/issues/4094). The frontend should update the filters (new request) each time the user searches a new keyword or applies/removes a filter.

- [x] Each filter has a title with width 100%, background color `veryLightGrey` and with a label tooltip. If the user clicks at the arrow icon in the left, the options are hide/show, tooltip: show/hide {{filter_label}}.
     - Default state: show
     - This state is not saved, if the user refresh the page, all filters will be showed.

We have four types of filters for now:

### Checkbox
Each option is a simple checkbox with the label and the number of results that the search will have if this filter is applied. If the checkbox is selected the number disappears (just the label stays). To check/uncheck an option the user can click on any place at checkbox extension (box + label + number).

### Date
Two checkbox with a text input and a calendar (see the image below).
The first checkbox has the "before" label and the second "after". If the user selects the checkbox, clicks on the calendar icon or the text input, the calendar opens. If the user does not write a date and presses Enter or chooses a date in the calendar, the filter is not applied.
If the user writes and presses Enter or chooses a date in the calendar, the checkbox is automatically checked.
![Frame 12](https://user-images.githubusercontent.com/35422692/105839813-4debc500-5fd2-11eb-9b3c-8fd552e18542.png)

To select the date, since Safari doesn't support the input type="date", we will use an external library:
- https://github.com/Hacker0x01/react-datepicker/ is the most used
- https://github.com/gpbl/react-day-picker is a good alternative
After some tests we chose `react-day-picker` because it has fewer dependencies and the team already knows the library.

Dev note: At the moment it is not simple o open the date picker when the user clicks on the checkbox, so the first version will implement only a checkbox that active or not the filter a not clickanle label and the input (without the calendar).

### User
_Not implemented in this issue, not for 3.6.0._
A text input with auto-completion (use the same as mentions). 
To validate the user can click on one of the options (gif below) or press Enter after typing something. If the user does not use the auto-completion and tries to press Enter for an invalid user a flash message should appear with the message "Your filter does not match any known member".
Once the member is chosen, an already checked checkbox appears with his name. If the user unchecks this checkbox the filter is removed and the checkbox disappears.
![membre](https://user-images.githubusercontent.com/35422692/105838195-0feda180-5fd0-11eb-8591-4854529f89a5.gif)

### Slider
_Not implemented in this issue, not for 3.6.0._
Two checkbox with a slider (see image below).
The first checkbox has the "Smaller than" label and the second "Bigger than". 
If the user select a value in the slider the checkbox is automatically checked. If they check the checkbox the current value is used to filter.
![Frame 18](https://user-images.githubusercontent.com/35422692/105855041-e9d3fb80-5fe7-11eb-992d-0994f7d4fa41.png)

### List of possible filters for contents search
|Backend key|Type|Label|Options|Implemented in this issue|
|-|-|-|-|-|
|workspace_names|Checkbox|Space|space list|Yes|
|search_fields|Checkbox|Search at|title/content/comments/description|Yes (without number of results)|
|date_range_facets.modified|Date|Last Intervention|-|Yes|
|date_range_facets.created|Date|Creation|-|Yes|
|statuses|Checkbox|Status|opened/validated/cancelled/deprecated|Yes|
|content_types|Checkbox|Type|file/note/thread|Yes|
|file_extensions|Checkbox|File extension|pdf/docx/etc...|Yes|
|author__public_names|User|Author|known-user list|Yes (as checkbox, showing only the public name)|
|-|Slider|Size|minimal existing size - maximum existing size|No|
|-|Checkbox|Share|with shares/without shares|No|
|-|Checkbox|Categories|custom list|No|
|-|Checkbox|Location|space/folder|No|

## Prerequisites
https://github.com/tracim/tracim/issues/4094 (backend)
https://github.com/tracim/tracim/issues/4083 (search page interface)
https://github.com/tracim/tracim/issues/4085 (search types)

## Translations

:bulb: Since each facets are predetermined, the frontend will have the strings to generate the translations keys

|English|French|Portuguese|
|-|-|-|
|Only search in|Rechercher uniquement dans|Pesquisar somente em|
|Type|Type|Tipo|
|File extension|Extension de fichier|Extenção de ficheiro|
|Status|Statut|Status|
|Creation|Création|Criação|
|Author|Auteur|Autor|
|Space|Espace|Espaço|
|Member of|Membre de|Membro de|
|Last Intervention|Dernier intervention|Última intervenção|
|Member|Membre|Membro|
|Title|Titre|Título|
|Content|Contenu|Conteúdo|
|Comments|Commentaires|Comentários|
|Description|Description|Descrição|

## Interface
![search_page](https://user-images.githubusercontent.com/35422692/105836656-c7cd7f80-5fcd-11eb-9d55-01c7ac4fa7e2.jpg)

## Time Estimation

3 man/day

**Comment by grignards** [comment]
The file size sliders won't be implemented in this issue but I'm wondering if one double-ended slider (with its min/max=minimum/maximum sizes as returned by the backend and defaulting to the whole size range) wouldn't be easier to tune rather than 2 checkboxes + two sliders.

**Comment by gbonaspetti** [comment]
> The file size sliders won't be implemented in this issue but I'm wondering if one double-ended slider (with its min/max=minimum/maximum sizes as returned by the backend and defaulting to the whole size range) wouldn't be easier to tune rather than 2 checkboxes + two sliders.

The first idea was to have something simple to dev, and use the basic html tag (that has only one end) was quick. As this will not be dev now, we can rethink the design, Damien think an input can be better to, I'll have the time to test some interface options.

**Comment by raphj** [comment]
I'd refine to a slider as needed later too. I'm good with the inputs. Actually, I think I prefer inputs personally.

**Comment by raphj** [comment]
Should we move things that are not implemented in this issue out to another issue?

**Comment by gbonaspetti** [comment]
> Should we move things that are not implemented in this issue out to another issue?

I didn't remove them (just commented) to have the description when we start the "upgrade" since I don't know when we'll do, but if you prefer to have another issue, it's possible too.

**Comment by Skylsmoi** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
