### ISSUE TITLE
Bug: Cover and avatar file size limitation is too restrictive

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4101]
## Description and expectations

We should allow much more than 1MB, a reasonable value seems to be 10MB.

### How to reproduce

1. Go to your public profile page
2. Try to upload an image of more than 1MB

### Version information

- Tracim version: 3.5 - `build_37` tag

________________________________________________

**Comment by PhilippeAccorsi** [comment]
@grignards is its impacted by this parameters `limitation.content_length_file_size` (in development.ini) ?

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
