### ISSUE TITLE
Bug: Hide the profile edit button if the data json is empty

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4102]
## Description and expectations

By default, Tracim doesn't use custom properties and the endpoint related to that returns an empty json.
Frontend handle the empty json in the same way that others, so we have a "Edit" button at Information and/or Personal Page that gives the impression of doing nothing.

### Expected
- [x] Do not show the edit button if json is empty

### How to reproduce

1. Do not set any custom properties configuration
2. Go to your profile
3. Click at edit

### Version information

- Tracim version: v3.5
- Web browser: any
- Version: any
- Device / System: any

**Comment by raphj** [comment]
tested on branch, but the problem related to the required field of json schemas really needs to be addressed.

**Comment by inkhey** [comment]
tested on branch, does work correctly in all case:
- no json schema (get the `e.required is undefined` issue but this is unrelated to edit button.)
- json schema with no value in each session
- json schema with value in just one section
- json schema with value in just the other one section

**Comment by PhilippeAccorsi** [comment]
Done.
