### ISSUE TITLE
Bug: Trusted-user and admin don't have access to some user public profile

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#4103]
## Description and expectations

Admin user is able to see some user notifications for user he doesn't have related space with, which lead in ui to link to inaccessible public profile. This is not normal as admin user should have access to all users public profile.

### How to reproduce

1. Create a new user
2. Let him create a workspace
3. click on the tlm of the new created workspace.

### Version information

- Tracim version: 3.5 prerelease.

## Screenshots

________________________________________________

## Diagnostic

There is 2 implementation of the know user filtering:
- one for known user search
- one for filtering endpoints.

These are not doing the same user filtering which mean inconsistent behavior. The second one "KnowsCandidateUserChecker" is the one to fix, to allow admin and trusted_user user to access to all public profile.
+ check if possible to have only one implementation of known user filtering (to avoid inconsistency) and if not, add a comment on each known user part to tell "change this other part at the same time" to avoid future inconsistency.

## Implemented solution:
https://github.com/tracim/tracim/pull/4108

- consistent rule for known users : allow admin and trusted user to access to known users endpoints, which give similar filter result as get_known_users despite the way to do it is different.

**Comment by inkhey** [comment]
After reread known user endpoints, i see that trusted_user can find user through known_user endpoint, should their also have access to all user profile ?

**Comment by gbonaspetti** [comment]
> After reread known user endpoints, i see that trusted_user can find user through known_user endpoint, should their also have access to all user profile ?

Yes, I think they should have access. They will not be allowed to edit their profile, but they should be able to see.

**Comment by raphj** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
