### ISSUE TITLE
Bug: When editing the public profile, the form sometimes get reset during edition

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#4105]
## Description and expectations

When editing the public profile, the form sometime gets reset.

### How to reproduce

With user1 and user2 belonging to the same space1,
user1 is editing his public profile, so user type something in an input (without saving)
user2 create a content in space1 which trigger a TLM
user1 receives the TLM and the form is reset and the input is now empty

### Version information

- Tracim version: 3.5.0
- Web browser: any
- Version: any 
- Device / System: any

________________________________________________

## Diagnostic

It is in reaction to a TLM.

The TLM triggers a rerender and since the `<Form />` component of react json schema form is an uncontrolled component by default, it is reset

## Implemented solution
Turn the `<Form />` component to a controlled component

**Comment by inkhey** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
