### ISSUE TITLE
Bug: JS Error in the activity feed page

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4109]
## Description and expectations

When going we sometimes get the following JS error:

```
Uncaught (in promise) TypeError: activityParams is null    
activityIndex activity.js:183
addMessageToActivityList activity.js:183
_temp withActivity.jsx:90
```

### How to reproduce

1. Login as administrator
2. Visit the activity feed
3. in another browser login as another administrator
4. create a new user

## Diagnostic

TLM related to users are not handled by the activity feed component. The function handling TLMs, `getActivityParams`, therefore (correctly) returns null. We did not notice that the case was not explicitly handled because There are no exhaustive matches in Javascript.

`addMessageToActivityList` does not check for null when using `getActivityParams`. We did not notice because the language does not enfore checking for the presence of a result as TypeScript would.

The solution is to check for null there.

### Version information

- Tracim version: 3.5 before release

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
