### ISSUE TITLE
Back/front: bug with error if you want to add files (without files)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#411]
At present:

When you want to add files, you need to choice file. But if you validate without file, this error appear:

Error 500: 
"builtins.AttributeError
AttributeError: 'bytes' object has no attribute 'filename'
"

expected: 

Control if one file is selected. Show message about "no file selected", and stay in pop-up.

**Comment by Skylsmoi** [comment]
duplicate #207
