### ISSUE TITLE
Bug: Consistant naming for shortcut in config file

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#4110]
## Description and expectations

In new documentation , the fact that  `user_custom_properties_dir`  is a shortcut is unclear:
naming is also a bit strange (no point).

```ini
# See the Tracim settings documentation (available in source code, see "user_custom_properties.md") for more
# information about it. By default, Tracim doesn't use custom properties.
; user.custom_properties.json_schema_file_path =
; user.custom_properties.ui_schema_file_path =
; user.custom_properties.translations_dir_path =
## example:
# user_custom_properties_dir = %(here)s/examples/user_custom_properties/organization
# user.custom_properties.json_schema_file_path = %(user_custom_properties_dir)s/schema.json
# user.custom_properties.ui_schema_file_path = %(user_custom_properties_dir)s/ui.json
# user.custom_properties.translations_dir_path = %(user_custom_properties_dir)s/locale
```

see existing shortcut example:

```ini
# example with shortcut for template_dir path:
; email.template_dir =
# email.template_dir = %(here)s/tracim_backend/templates/mail
# email.notification.content_update.template.html = %(email.template_dir)s/content_update_body_html.mak
# email.notification.created_account.template.html = %(email.template_dir)s/created_account_body_html.mak
# email.notification.reset_password_request.template.html = %(email.template_dir)s/reset_password_body_html.mak
# ...
```

### Version information

- Tracim version: Tracim 3.5 pre-realase

### Solutions:

Best solution may be renaming with leading `@`  to make it explicit that just a shortcut: 
(+ add information at the start of the file about this rule)

- `email.template_dir ` ->  `@email.template_dir`
- `user_custom_properties_dir` -> `@user.custom_properties.dir`
- `basic_setup.website_title`  -> `@basic_setup.website_title`
-  etc

Changing existing naming for basic_setup is a big breaking change so i'm not sure we should do it now. 
We can for now just renaming only `user_custom_properties_dir` to `user.custom_properties.dir` and explain like email.template_dir that there is a shortcut, if doing breaking change now his too much.

Edit: the change with @ as been moved to https://github.com/tracim/tracim/issues/4117

## Implemented solution
https://github.com/tracim/tracim/pull/4116
- rename user_custom_properties_dir to user.custom_properties.dir + clarify about shortcut.

**Comment by PhilippeAccorsi** [comment]
> We can for now just renaming only user_custom_properties_dir to user.custom_properties.dir and explain like email.template_dir that there is a shortcut, if doing breaking change now his too much.

I'm ok for this solution and idea of `@` for future release.

**Comment by PhilippeAccorsi** [comment]
No test necessary.
