### ISSUE TITLE
Bug: Wrong wording for account notifications

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4113]
## Description and expectations

The notification wall mentions "profile" when it is not related. 

![Screenshot from 2021-01-28 15-01-03](https://user-images.githubusercontent.com/35422692/106148840-d35da980-6179-11eb-9323-525596209602.png)

### Expected
- [x] Change "profile" to "account" at
    - "{{author}} created {{user}}'s profile" that becomes "{{author}} created {{user}}'s account"
    - "{{author}} modified {{user}}'s profile" that becomes "{{author}} modified {{user}}'s account"
    - "{{author}} deleted {{user}}'s profile" that becomes "{{author}} deleted {{user}}'s account"
    - "{{author}} restored {{user}}'s profile" that becomes "{{author}} restored {{user}}'s account"

### How to reproduce

1. As admin, create a new user
2. See the notification wall

### Version information

- Tracim version: v3.5
- Web browser: any
- Version: any
- Device / System: any

**Comment by PhilippeAccorsi** [comment]
Done.
