### ISSUE TITLE
Bug: Some translation and wording issues

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4114]
## Description and expectations

- [x] in French "activity feed" should be "fil d'activité"
- [x] "interventions" and "spaces" are always in the plural form in the public profile page, they should be in singular when 1 intervention/space.
    - in Portuguese, the singular are "intervenção" and "espaço".
- [x] "Paramètre du compte" should be "Paramètres du compte" in French in the user's menu.

### Version information

- Tracim version: 3.5 build_37
- Web browser: [e.g. Google Chrome, Firefox, Safari]
- Version: [e.g. 22, latest]
- Device / System: [e.g. PC, iPhone 6]

## Screenshots

________________________________________________

**Comment by gbonaspetti** [comment]
Tested on branch by @grignards

**Comment by PhilippeAccorsi** [comment]
Done.
