### ISSUE TITLE
Misc: Improve Default JSONSchema/UISchema sample

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#4119]
## Description and expectations

Make it more easy for user to use JSONSchema by giving default sample that work and make sense.
We can decide to improve existing organization example of create other one.

## Extra information
see existing organization sample: https://github.com/tracim/tracim/tree/develop/backend/examples/user_custom_properties/organization
# Implemented solution
- add a new sample of jsonschema and make it default example in development.ini.sample.

**Comment by raphj** [comment]
tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
