### ISSUE TITLE
Bug: by editing the personal page, we see the name of the field personal_page

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4123]
## Description and expectations

As said in the "Mandatory things to do due to unsupported features" topic of this comment https://github.com/tracim/tracim/issues/4039#issuecomment-766859816, if the title that a property is empty or does not exist, its key is shown in place of the title. This is the case with the personal page. To not show any title we will create a title that exists but seems invisible to the user using an empty space as title. 

### Version information

- Tracim version: v3.5
- Web browser: any
- Version: any
- Device / System: any

## Screenshots

![Capture d’écran de 2021-01-29 11-43-20](https://user-images.githubusercontent.com/35422692/106265383-3e18ee80-6227-11eb-8d7a-0dd7176a6b49.png)

**Comment by raphj** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
