### ISSUE TITLE
Feat: Upgrade font awesome to version 5+

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#4124]
## Feature description and goals

Currently, we use font awesome v4.7.
The current version is 5 (and 6 is in alpha)
In version 3.5.0 we have introduced the usage of the library https://github.com/peterkelly/react-jsonschema-form-bs4 to handle json schema form.
This library expects font awesome 5+ and without it, some icons are missing

**Comment by Skylsmoi** [comment]
every icons have been updated to their font awesome 5+ equivalent (if changed)

There is a change in the icon management, previously, we only gave the icon name as props through components.
- eg: `users`

Now, there might be 2 versions of an icon differentiated by the other class `.fas` or `.far`. It use to only be one class `.fa`.
So we now give the full icon classes as props through components.
- eg: `fas fa-users`

**Comment by Skylsmoi** [comment]
Also note that the PR only adds the required css files for font awesome 5. See:
    frontend/dist/assets/font/fontawesome-free-5.15.2-web/

There are only the folders `css/` and `webfonts/`

**Comment by Skylsmoi** [comment]
For tester:
Navigate through Tracim pages and check the icons are still there and their design is equivalent to their previous version.

Since it's complicated to check each and every Tracim features, I suggest to put the issue in "Need test on develop" once the it is merged

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
I think this icon is better than the new one
![Screenshot_2021-02-03 Font Awesome](https://user-images.githubusercontent.com/25848257/106761260-ee766080-6634-11eb-9875-9b379238b086.png)

New one available in 3.5.0
![Screenshot_2021-02-03 Font Awesome(1)](https://user-images.githubusercontent.com/25848257/106761370-0a7a0200-6635-11eb-9293-f2893905ae43.png)

Old one in tracim 3.4.3
![Screenshot_2021-02-03 (34) Tableau de bord · Intranet · preprod-algoo](https://user-images.githubusercontent.com/25848257/106761446-1fef2c00-6635-11eb-9f62-d4ff731afbbc.png)

@lebouquetin I know new fontawesome 5.15 have some "pro" icon and the one I purpose seems to be free (not pro but something not clear in website), but I'm not sure this new icon is explicit.

**Comment by Skylsmoi** [comment]
the one you suggests is from the Regular font which is supposed to be free indeed

**Comment by lebouquetin** [comment]
I suggest to show icons in the following order:

1. Old
2. New
3. Suggested

**Comment by PhilippeAccorsi** [comment]
> I suggest to show icons in the following order:
> 
>     1. Old
> 
>     2. New
> 
>     3. Suggested

Done.

**Comment by PhilippeAccorsi** [comment]
Done.
