### ISSUE TITLE
Bug: Adding a member to a space where a member of this space who changed their username fails if they were mentioned under their former username

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4137]
### How to reproduce

When adding a member to a space in which a member has changed their username, and this member has been mentioned under their former username, the action fails. With plugins automatically adding users to spaces, this also prevents user creation.

A partial fix for this is to not fail if this case arises. A complete fix is described here: https://github.com/tracim/tracim/issues/4136

### Version information

- Tracim version: to-be-released tracim 3.5, probably previous versions with the activity feed as well.

### Implemented solution
#4139 
- try/catch user with username exist
- explicit warning log if such case happened

**Comment by PhilippeAccorsi** [comment]
Tested on preprod.

**Comment by PhilippeAccorsi** [comment]
Done.
