### ISSUE TITLE
Bug: CSPs block video integration with iframes in notes and advanced comments

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4142]
### How to reproduce

1. Create a note
2. click on "+", and then on the media button in TinyMCE
3. link a video from PeerTube, YouTube, Dailymotion, or whatever
4. Notice that the video does not load.

### Version information

- Tracim version: 3.4, soon to be released 3.5

### Diagnostic

Blocked by CSP's `frame-src` directive

### Solution

allow frames to everywhere (`*`)

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done
