### ISSUE TITLE
Feat: Update elasticsearch model for contents + clarify index rules

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4146]
## Feature description and goals

Update the indexed model to include all content fields as returned by the API in `ContentDigestSchema` plus:
  - [x] its `comments` (as a list)
  - [x] its `comments_count`
  - [x] its `raw_content` (be it in a file or directly stored in the database)
  - [x] `workspace` (as a `WorkspaceDigestSchema()`)
  - [x] `last_modifier` (last user who modified the content) as a `DigestUserSchema()`
  - [x] `author` (user who created the content) as a `DigestUserSchema()`
  - [x] its `content_size` (in bytes)
  - [x] its `path` as would be returned by `/api/workspaces/{workspace_id}/contents/{content_id}/path`

Refactor indexing rules to be consistent:
- full Indexing of content should occured when:
  -  [x] a content is created/modified (deletion included).
  -  [x] subcontent comment of the content is created/modified(deletion included)

- partial(or full ?) Indexing of content should occurred at least when:
  - [x] one of the parents filename has changed : update path
  - [x] one of the parents state has changed (active/archived/deleted): update deletion state
  - [x] workspace name has changed : update path
  - [x] workspace state has changed ? (Is deleted workspace case, working as expected?)
  - [x] author or last modifier username/public name has changed
  - [x] author or last_modifier state has changed (deleted user) ?

**Comment by inkhey** [comment]
We should add `number of comments` as parameter.

**Comment by inkhey** [comment]
Just added rules for reindexing content.

**Comment by lebouquetin** [comment]
According to

- the refactoring of `raw_content` vs `description`
- the search result user interface https://algoo.tracim.fr/ui/workspaces/124/contents/file/15544

The field `description` is missing in the issue description

**Comment by lebouquetin** [comment]
Note about `last_modifier`: I'm pretty sure the last modifier is historically the user who modified the content *or who commented the comment*.

**Comment by grignards** [comment]
> The field description is missing in the issue description

and many others because of this sentence:

> to include all content fields as returned by the API in ContentDigestSchema plus

> Note about `last_modifier`: I'm pretty sure the last modifier is historically the user who modified the content _or who commented the comment_ (it makes sense at least in the search context).

I'm afraid to say that this was not the case (or I really missed something). Could probably be added without too much difficulty.

**Comment by lebouquetin** [comment]
Thanks for the clarifications @grignards. I see two possible explanations for `last_modifier`:

- first hypothesis is my memory is mixed up between recent activities implementation (on the dashboard) and search results
- second hypothesis is this is only in my head that last_modifier is related to both content and comments.

The relevance of including comments in last_modifier is related to the UI rendering. What do you think @gbonaspetti?

**Comment by gbonaspetti** [comment]
> The relevance of including comments in last_modifier is related to the UI rendering. What do you think @gbonaspetti?

I agree, from a user point of vue, a comment is a intervention at a content.

**Comment by PhilippeAccorsi** [comment]
Manual test done in preprod instance.

**Comment by PhilippeAccorsi** [comment]
Done
