### ISSUE TITLE
Feat: Enable a default set of public profile properties by default 

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4157]
## Feature description and goals

The new public profile allows user to fill fields and a personal page. This works if a default set of public profile properties is enabled. This work consists in enabling a public profile by default.

**Comment by PhilippeAccorsi** [comment]
I think we need to move :
- examples/user_custom_properties/default/ to tracim_backend/templates/user_custom_properties/default/ or something like that
- set default path in backend code and add this default value in development.ini for this 3 parameters:
  - `; user.custom_properties.json_schema_file_path =`
  - `; user.custom_properties.ui_schema_file_path =`
  - `; user.custom_properties.translations_dir_path =`

**Comment by PhilippeAccorsi** [comment]
Done.
