### ISSUE TITLE
Bug: avatar/cover of other users broken when user has no avatar/cover.

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#4161]
## Description and expectations

When user has no avatar/cover, user cannot see avatar/cover of others users.
Reason is that we do use current user instead of the user we do need. during request, and fail to get the filename of an un-existing avatar.

### How to reproduce

1. Be admin without avatar
2. Add avatar to other user
3. Add cover to other user.
4. Check you can not see the new avatar/cover
5. Connect to the other user and see that the avatar/cover does work in this case.

You get error from backend :
`AttributeError: 'NoneType' object has no attribute 'filename'`
In this case

### Version information

- Tracim version: 3.5

## Implemented solution

- use correct user object

**Comment by PhilippeAccorsi** [comment]
Done.
