### ISSUE TITLE
Feat: Add a german translation

### ISSUE THREAD

**Issue by MariePrandstetter** [tracim/tracim#4171]
## Feature description

Add a German translation for Tracim.

To do:
 - [x] add `'de'` in the script that builds the translation files (`i18next.scanner.js`)
 - [x] add a translation file for each frontend component (frontend, apps, frontend_lib)
 - [x] adapt build scripts (`build_XXX.sh`) for each frontend component (copy the translation file to `frontend/`)  
 - [x] translate email templates
 - [x] translate custom_toolbox
 - [x] add a German flag on the language selection tool
 - [x] follow the steps in https://github.com/tracim/tracim/issues/3003#issuecomment-627157755
 - [x] edit `backend/development.ini.sample`, line: `# Available parameter: en, fr, pt`
 - [x] add a case for German in function `getTinyMceLang` , file `src/util/tinymceInit.js` https://github.com/tracim/tracim/issues/3011

See ticket [#3003](https://github.com/tracim/tracim/issues/3003) for additional information about the changes that need to be done when a new translation is added

**Comment by PhilippeAccorsi** [comment]
Need also a small add in the develoment.ini.sample file about default supported language, visible here:
~~~
### Lang ###
## default lang used in backend if user doesn't provided any lang.
# Available parameter: en, fr, pt
; default_lang = en
~~~

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by MariePrandstetter** [comment]
Done
