### ISSUE TITLE
Bug/regression: about font awesome icon

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#4177]
## Description and expectations

Todo:

- [X] Fix the missing fullscreen icon in agenda
- [X] Fix the Caldav's iframe  still trying to load the version 4.7.0 of font awesome
- [X] Use https://fontawesome.com/icons/expand-arrows-alt?style=solid for the full screen icon in the Gallery (same kind of icon visible in tinymce and collabora online)
- [X] some of class is not set correctly `class="fas fa-fw fas fa-history"`, check if this kind of syntax error exist ofr another icon
    - note(@raphj): I did not find any

### Version information

- Tracim version: 3.5.0

**Comment by MariePrandstetter** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
@raphj 
~~~
some of class is not set correctly class="fas fa-fw fas fa-history", check if this kind of syntax error exist ofr another icon
    note(@raphj): I did not find any
~~~

You not find this or not find more ? (I have seen this in existing instance)

**Comment by PhilippeAccorsi** [comment]
This is visible for exemple here https://branchdev.tracim.fr/ui/workspaces/2/contents/html-document/33?folder_open=&parent_id=null

Icon of history in menu of the Note.

**Comment by PhilippeAccorsi** [comment]
This is just visible in Note app (app-html) I think.

**Comment by inkhey** [comment]
work as expected.

**Comment by PhilippeAccorsi** [comment]
Done.
