### ISSUE TITLE
Feat: Add different types of search

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4180]
## Feature description and goals

Now it will be possible to search not only for contents but also in spaces and users for advanced search. Some development has already been done on problem #4085 and should be finished here.

- [x] Add radio buttons for the three different types of result.
- [x] The frontend must search for the 3 types in parallel so that there is no loading time each time the user changes the type.
    - Add three lists at Redux at root
- [x] By default the page should display the results of the content search
- With sm and xs screens:
    - [x] The breadcrumbs should be hidden
    - [x] The icon type/avatar should have fontSizeMedium/AVATAR_SIZE.MINI size
- With xl, lg and md screens:
    - [x] The icon type/avatar should have fontSizeTitle/AVATAR_SIZE.SMALL size
- [x] Add unit tests to advanced search (content type included), if needed
- [x] Deduplicate currentSearch ifs

### Users list

- [x] Columns at xl, lg, md and sm screens:
    - Avatar
    - Full Name
    - Information (fontSizeSmall)
        - Username
- [x] Columns at xs screens:
    - Avatar and Full Name
- [x] Clicking anywhere redirects to the user's profile
- [x] If and only if the logged user is an administrator, the frontend will have to get email for each result to display it. If user isn't an admin, the email is never displayed
    - Update: the e-mail will not be displayed, even for admin 
- The avatar is not send by backend
  - but the front will have all the required information to generate the component Avatar (id, public name ...)

### Spaces list

- [x] Columns at any screen:
    - Type 
    - Name (if there's not enough space at sm and/or xs screens type and name should be put in the same column)
    - Information (fontSizeSmall - and if there's not enough space at  xs screens this column should be hidden)
        - Number of contents
        - Number of members
- Click on :
    - [x] a space that the user is a member redirects to the home page of the space
    - [x] a space that the user is not a member redirects to the page to join the space with the same keyword entered in the search (compare with the list of spaces that the logged user is a member of)
- [x] Each type must have its name written under the icon on the lg and xl screens in fontSizeSmall size

## Prerequisites

- https://github.com/tracim/tracim/issues/4095

## Translations

|English|French|Portuguese|
|-|-|-|
|Contents|Contenus|Conteúdos|
|Users|Utilisateurs|Utilizadores|
|Spaces|Espaces|Espaços|
|Type|Type|Tipo|
|Title and Path|Titre et chemin|Título e caminho|
|Last modification|Dernière modification|Última modificação|
|Information|Informations|Informações|
|Avatar|Avatar|Avatar|
|Name|Nom|Nome|
|Full Name|Nom complet|Nome completo|
|and|et|e|

## Interface
_Obs: These interface examples are only templates, not everything will be developed in this issue and some details can be changed according to the implementation._

![search_page](https://user-images.githubusercontent.com/35422692/105707806-c63f8100-5f13-11eb-9973-ac3b16f08f4d.png)
![search_page (1)](https://user-images.githubusercontent.com/35422692/105707821-cc356200-5f13-11eb-86aa-9b12d62b51eb.png)
![search_page](https://user-images.githubusercontent.com/35422692/105819338-56cf9d00-5fb8-11eb-956a-aa0f4dfcde2e.png)
![search_mobile](https://user-images.githubusercontent.com/35422692/105707862-df483200-5f13-11eb-889a-fc29e6dc5315.png)

## Time Estimation
2 man/day

**Comment by inkhey** [comment]
Tested on branch, few minor remark:
- search allow wildcard but wildcard is not supported for workspace filtering (case where we use wildcard and click on an on_request workspace).
- "username @" syntax is weird as we do use "@username" almost everywhere

**Comment by gbonaspetti** [comment]
> * wildcard

I updated the description and the others issues are added to #4224

**Comment by PhilippeAccorsi** [comment]
Done.
