### ISSUE TITLE
Feat: Add user and space search filters

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4181]
## Feature description and goals

For each search type (see #4180) we will have specific filters. The content filters were implemented at https://github.com/tracim/tracim/issues/4097, this issue will implement the user and space filters. Those filters are predefined and sent by the backend (see https://github.com/tracim/tracim/issues/4094). The frontend should update the filters (new request) each time the user searches a new keyword or applies/removes a filter.

- [x] Each filter has a title with width 100%, background color `veryLightGrey` and with a label tooltip. If the user clicks at the arrow icon in the left, the options are hide/show, tooltip: show/hide {{filter_label}}.
     - Default state: show
     - This state is not saved, if the user refresh the page, all filters will be showed.

### List of possible filters for each type
**Users**
|Backend key|Type|Label|Options|Implemented in this issue|
|-|-|-|-|-|
||Checkbox|Search at|full name/username/profile(information/personal page)|Yes (without number of results)|
||Checkbox|Member of|space list|Yes|
||Date|Last Intervention|-|Yes|

**Spaces**
|Backend key|Type|Label|Options|Implemented in this issue|
|-|-|-|-|-|
||Checkbox|Search at|name/description|Yes (without number of results)|
||User|Author|known-user list|Yes (as checkbox, showing only the public name)|
||User|Member|known-user list|Yes (as checkbox, showing only the public name)|

## Prerequisites
https://github.com/tracim/tracim/issues/4094 (backend)
https://github.com/tracim/tracim/issues/4083 (search page interface)
https://github.com/tracim/tracim/issues/4085 (search types)

## Translations

:bulb: Since each facets are predetermined, the frontend will have the strings to generate the translations keys

|English|French|Portuguese|
|-|-|-|
|Search at|Recherchez sur|Pesquisar em|
|Type|Type|Tipo|
|File extension|Extension de fichier|Extenção de ficheiro|
|Status|Statut|Status|
|Creation|Création|Criação|
|Author|Auteur|Autor|
|Space|Espace|Espaço|
|Member of|Membre de|Membro de|
|Last Intervention|Dernier intervention|Última intervenção|
|Member|Membre|Membro|
|Title|Titre|Título|
|Content|Contenu|Conteúdo|
|Comments|Commentaires|Comentários|
|Description|Description|Descrição|

## Interface
![search_page](https://user-images.githubusercontent.com/35422692/105836656-c7cd7f80-5fcd-11eb-9d55-01c7ac4fa7e2.jpg)

## Time Estimation

2 man/day

**Comment by inkhey** [comment]
tested on branch.
