### ISSUE TITLE
Bug: responsive: search icon not stay in search input on small screen

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#4182]
## Description and expectations

If I resize my browser in width, I can seen the search icon between search input and administrative button

### How to reproduce

- Reduce the width of browser.

### Version information

- Tracim version: 3.5.0
- Web browser: firefox
- Version: Buster esr

## Screenshot

![Screenshot_2021-02-16 Global manager · Unstable(3)](https://user-images.githubusercontent.com/25848257/108069174-567c6c00-7063-11eb-8369-24c430b7177b.png)

## Video

https://user-images.githubusercontent.com/25848257/108069052-33ea5300-7063-11eb-9ad1-476d58fc64e8.mp4

________________________________________________

**Comment by PhilippeAccorsi** [comment]
I have added screenshot and video.

**Comment by gbonaspetti** [comment]
Fixed at https://github.com/tracim/tracim/commit/11468d779058ed50cb02d7aba53cb529ff1a8b1e
