### ISSUE TITLE
Bug: the CardPopup component can be closed by clicking anywhere in the line containing the close "×" button

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#4190]
## Description and expectations

I tried to create a new card, and try to move the popup. So I click on top of the popup and card disappear.

### How to reproduce

- try to add a new card
- click on top of the popup
=> the card is closed

### Version information

- Tracim version: 3.5.0+, and older versions too 
- Web browser: Firefox
- Version: 78.7.0esr
- Device / System: Buster

________________________________________________

## Diagnostic

The event to close the CardPopup component is put on the div containing the close icon.
@raph: I suggest implementing the close button using a button instead, inside this div.

**Comment by PhilippeAccorsi** [comment]
This is not exclusive to the kanban card. This is the same in all Tracim Popup

**Comment by PhilippeAccorsi** [comment]
If I select the div of the cross `<div class="cardPopup__close"><i class="fas fa-times"></i></div>` the size of this div is 512*26.
For me its just necessary to have a button with this size 2626 to protect wrong click in popup.

**Comment by raphj** [comment]
another example where CardPopup is used is the dialog to create a new space.

**Comment by PhilippeAccorsi** [comment]
Done.
