### ISSUE TITLE
Installation to match control panel config

### ISSUE THREAD

**Issue by Keepshango** [tracim/tracim#4194]
Hello,

Replies to both questions below would help better apprehend running and using TRACIM on my VPS

**Q1 : Installation matching control panel config**
Would you or not recommend installing TRACIM under a path that matches a control panel configuration (e.g.) ?

/var/www/clients/client1/web1/ web/ git clone https://github.com/tracim/tracim.git
/var/www/clients/client1/web1/ web/ cd tracim/

**Q2 : production vs development**
Can I run Tracim both for development and production without generating a conflict or a bug ?

Regards,

**Comment by buxx** [comment]
Hello @Keepshango 

Q1: I do not recommend installing Tracim like that. For two reasons: First is, Tracim source code can be unique on your system. After installing dependencies and building frontend you can deploy Tracim instances with web server like uwsgi, apache, etc. See https://github.com/tracim/tracim#run-tracim-for-production Second reason is Tracim have a lot of dependencies and it will be, maybe, in conflict with your control panel (Is that something like ISPConfig or Webmin ?). For your information, Tracim is ready for use with Docker.

Q2: Yes you can. Take care by use separated config with separated config values for persisted things (like database, file depot, etc).

**Comment by raphj** [comment]
Hi @Keepshango,

Depending on what you plan to do for development / production, I would not recommend sharing a Tracim instance for both development and production. It works though for reasons given by @buxx.

**Comment by Keepshango** [comment]
My Control panel is ISPConfig 3.2.2

 
 

Envoyé: jeudi 18 février 2021 à 16:51
De: "Bastien Sevajol" <notifications@github.com>
À: "tracim/tracim" <tracim@noreply.github.com>
Cc: "Keepshango" <keepshango@free.fr>, "Mention" <mention@noreply.github.com>
Objet: Re: [tracim/tracim] Installation to match control panel config (#4194)


 

Hello @Keepshango

Q1: I do not recommend installing Tracim like that. For two reasons: First is, Tracim source code can be unique on your system. After installing dependencies and building frontend you can deploy Tracim instances with web server like uwsgi, apache, etc. See https://github.com/tracim/tracim#run-tracim-for-production Second reason is Tracim have a lot of dependencies and it will be, maybe, in conflict with your control panel (Is that something like ISPConfig or Webmin ?). For your information, Tracim is ready for use with Docker.

Q2: Yes you can. Take care by use separated config with separated config values for persisted things (like database, file depot, etc).

**Comment by Keepshango** [comment]
Thank U
