### ISSUE TITLE
Docker install : other webapp already listening on port 8080

### ISSUE THREAD

**Issue by Keepshango** [tracim/tracim#4197]
Hello,

I wish to install TRACIM from docker, on a server that hosts a program (control panel) already listening on port 8080.
What then can I do to have TRACIM listening on a different port ?

Regards

**Comment by PhilippeAccorsi** [comment]
Hi Keepshango,

You can change port easly when you run tracim with docker. You just need to adapt this parameter `-p 8080:80` on your docker run command (same thing if you use docker-compose).

First value is the port on your host, so you can start docker image with port like that `-p 10000:80`. It is also better to add ip address in front of the port if you use a proxy in front of docker image. Example:
- `-p 127.0.0.1:10000:80` with that, all accepted request come from your host (from your proxy).

Regards,
Philippe

**Comment by Keepshango** [comment]
Thanks,
But I changed my mind and finally opted for Tracim installation from source code, rather than with docker
