### ISSUE TITLE
Confused with : default configuration suitable for local-test... !

### ISSUE THREAD

**Issue by Keepshango** [tracim/tracim#4204]
Hello,

I have read under **“Configuration“** in the **“Backend README“** page, the note below that's meaning is not clear enough to me :

_The provided default configuration is suitable for local-test. If you need to run Tracim over network, see “configuration file documentation“._

*** Q1 ***
Does “suitable for local-test“ means that team members can’t work on Tracim together if being away from each other (e.g. each one in a different state or country) ?

*** Q2 ***
Should those choosing option 2 to install Tracim backend  (Install backend: Automated script for easy setup) also care about this, or only those choosing to install it manually (option 1) ?

Regards,

**Comment by PhilippeAccorsi** [comment]
Hi Keepshango,

> *** Q1 ***
> Does “suitable for local-test“ means that team members can’t work on Tracim together if being away from each other (e.g. each one in a different state or country) ?
>

“suitable for local-test“ means test on your machine (localhost). The default configuration use localhost URL, so It is not possible to use Tracim from another network machine. If you want to use Tracim (and not just to test), you need to alter some parameter to permit connection from another network machine (local network or remote network).
 
> *** Q2 ***
> Should those choosing option 2 to install Tracim backend (Install backend: Automated script for easy setup) also care about this, or only those choosing to install it manually (option 1) ?
> 

This is the same if you use `Install backend: Automated script for easy setup`, you need to set the URL where other user can access to Tracim.

This is the parameter to explain where is the Tracim instance `basic_setup.website_base_url`.

**Comment by raphj** [comment]
Do not hesitate to take a look into parameters in `backend/develop.ini`, this file is widely commented. Dot hesitate to ask if you need further details. 

Also, please consider using the docker container to run Tracim in production.

**Comment by Keepshango** [comment]
Thanks
