### ISSUE TITLE
Bug: Search is not done in contents' descriptions

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4216]
## Description and expectations

The description of a content is used when searching with the advanced search.
The description should be used when searching.

### How to reproduce

To reproduce you need a Tracim instance with elasticsearch enabled.

1. Create a content with a description (for example a file)
2. search a word of the description

### Version information

- Tracim version: 3.5.0-build38

## Screenshots

________________________________________________

## Diagnostic

The description field is not indexed.

**Comment by PhilippeAccorsi** [comment]
Done.
