### ISSUE TITLE
Installation for production interrupted (without showing errors) ?

### ISSUE THREAD

**Issue by Keepshango** [tracim/tracim#4223]
Hello,

Firstly below, is the list of achieved installation steps.

Secondly is the list of command lines instructed **under subtitle “Run Tracim for production“** at section : **Tracim WSGI apps with pastedeploy (config in development.ini):**. This is where the **installation process was interrupted** (without showing errors) as explained in **output description below**.

**So I need guidance** on what I’m supposed to do to continue the installation, after such an interruption (I closed my terminal in the meantime…) :

**ACHIEVED STEPS**
- Get the source code
- Install the backend (option 2)
- Install the frontend

**INTERRUPTED STEP**
**Run Tracim for production** / Tracim WSGI apps with pastedeploy (config in development.ini):

**Command lines :**
cd backend/
source env/bin/activate
(# running web server)
pserve development.ini

**Output :**
The outputs for last command line **“pserve development.ini“** ended up without errors, but also **without rolling back to web root directory**. These below are the **two last output lines**, and nothing but the **terminal cursor** was shown afterward :  

Starting server in PID 26754.
Serving on http://localhost:6543

Regards,

**Comment by raphj** [comment]
Hello @Keepshango,

We need your complete logs to help you.

What do you mean by "without rolling back to web root directory"? Please note that there is not really such a thing in tracim: requests are handled by the backend tracim should be proxyfied by your web server.

> Serving on http://localhost:6543

Then Tracim seems to run. Make sure that you launch pushpin as per the documentation, and then Tracim will be reachable from port 7999.

Feel free to reach us at bonjour@tracim.fr so we can try and help you. If you happen to prefer French than English, do not hesitate to write us in French.

Also, give our issue template a try, it might help us help you :-)

**Comment by Keepshango** [comment]
Hello,

**/// TEST ENVIRONMENT ///**
Machine : remote VPS 2vCore
OS distro : Ubuntu 18.04 (bionic beaver)
User :  root with sudo permissions
Web server : apache 2.4
Cpanel : ISPConfig 3.2.2

No other webapp but Tracim installed on this fresh VPS
First connection as admin to my Tracim instance was successful, **but since, at any new connection** my browser displays a blank page with ERROR MESSAGE :

**“Error while proxying to origin“**

Please find **here below a link to the whole installation log file** (HTML) with each major installation command lines and output lines titled and numbered (git clone, backend, frontend, pushpin, connection, warnings…).
Text that follows contains numbers that indicates their corresponding numbered line in the log file, and this post ends with my questions.

> What do you mean by "without rolling back to web root directory"?
I wanted to mean that after connection to the server is established, **all command lines are preceded with web root directory string, e.g.** “root@vps-IP-ADDRESS:/var/www/clients/client1/web1/web#“ **(see log file)**,  and that **this string should normally also get displayed after each ended output**, as to allow next installation command line, or to allow the exit command line (prior to close the terminal window).

**This was not the case after command line “pserve development.ini“ (4229) ** whose output remained uncompleted **(4487, 4488)** during more than **20 minutes of terminal inactivity**. So that I could not know if the output was ended, neither I could pursue the installation or type exit to end the ssh connection to my server. 

**Reading what follows (log file)**, you may know what happened from then, as I left my **terminal opened until I had to force its closure** (unability to exit ssh) ! Doing so, I was alerted with this message : **Closing this window will terminate the ssh process running**. 

**/// INSTALLATION LOG FILE  ///**
On Pastebin : [https://pastebin.com/NVbRr8Ta](url)

Tracim git clone : 34
Backend : 44
Additional command lines : 3268 ; 3277 ;  3288
Frontend : 3302 ; 3353
………………………………………..
FOR DEVELOPMENT (squeezed)
………………………………………..
FOR PRODUCTION
Pushpin : 4130 ; 4164 ; 4224 ; 4226 
**Tracim WSGI apps with pastedeploy (config in development.ini):**
4228 ; 4229
4487 ; 4488 :
uncompleted output
unability to pursue or to type exit (terminal left open for next steps)
terminal inactivity until first connection to e.g. http://surname.domain-name.net:7999
………………………………………..
CONNECTION TO TRACIM INSTANCE
terminal activity relaunched : 4490
admin login / logout successfully : …. ….
terminal closure forced (unabilty to type exit) : 5358  

Afterward, at any new attempt to connect my TRACIM instance, browser now shows a blank page with ERROR MESSAGE  : **Error while proxying to origin**
………………………………………..
WARINGS
pip version : 3061
unknown : 3350
size limit : 3445
https URL : 4413 ; 4414 ; 4416

**/// QUESTIONS ///**
Should I, or not, pay attention to such uncompleted installation process in terminal ?
Any idea of what might have gone wrong, and what to do get rid of this issue ?

Regards,

**Comment by Keepshango** [comment]
Installation and connection issues are better exposed and detailed in this new post : 
[https://github.com/tracim/tracim/issues/4231](url)
