### ISSUE TITLE
First connection ok, all further ones fails (see install log file)

### ISSUE THREAD

**Issue by Keepshango** [tracim/tracim#4231]
Hello,

I chose to install Tracim from source (advanced), and to install its backend with the automated script.

**/////// BUG DESCRIPTION ///////**
**A first successful connection to my Tracim instance** allowed me to change default admin settings, and to logout without any issue. **Afterward (once the terminal was closed)**, at any attempt for a new connection, the browser displayed a blank page with ERROR MESSAGE : 

**Error while proxying to origin** 

**Since the day after, and until now,** any connection attempt ends up with browser displaying a CONNECTION FAILED page : 
[http://collabship.tameriberg.link:7999](url)

**/////// HELP REQUIRED ///////**
**To anyone that wish and may help**, I share in this post **elements allowing to investigate** upon what I observed during installation, that may potentially cause this failure. **As an introduction**, please note that I typed command line  **“pserve development.ini“** within this directory : /var/www/clients/client1/web1/web/**tracim/backend#**

**As resumed below,** all installation command lines outputs has started and ended  as expected, **except the “pserve development.ini“  command line** in backend directory, whose **output** left me no other choice than to **close my terminal window after more than 20 minutes of inactivity, without repositioning the ssh cursor at CD BACKEND /**.

**Numbers in the resume hereafter** refers to numbered **lines in the iINSTALLATION LOG FILE** whose access link is : [https://pastebin.com/NVbRr8Ta](url)

Tracim git clone : 34
Backend : 44
Additional command lines : 3268 ; 3277 ; 3288
Frontend : 3302 ; 3353
………………………………………..
FOR DEVELOPMENT (skipped)
………………………………………..
FOR PRODUCTION
Pushpin : 4130 ; 4164 ; 4224 ; 4226

FOR PRODUCTION
……….  **cd backend /** …………………..
Tracim WSGI apps with pastedeploy (config in development.ini):
command line **“pserve development.ini“** : 4228 ; 4229 ; 4487 ; 4488….
uncompleted output 
terminal inactivity until first connection to Tracim instance.
………………………………………..
CONNECTION TO TRACIM INSTANCE
[http://collabship.tameriberg.link:7999](url)
terminal activity relaunched : 4490
admin login / logout successfully : …. ….
**terminal closure forced** : 5358
………………………………………..
WARINGS
pip version : 3061 (upgrade done)
unknown : 3350
size limit : 3445
https URL : 4413 ; 4414 ; 4416

Regards,

**Comment by inkhey** [comment]
Hello,
In fact, pserve is a command that permit to run tracim, as this is a server process it does not stop, it's same for process like `tracimcli webdav start `. There is few way to convert a process as a "daemon" (software that keep running in the background).
We do use pserve for development only as we do prefer Uwsgi as server (pserve use waitress).

The documentation for this part is not completely clear, if you do want to deploy tracim, the backend documentation is a bit more clear and accurate, as we explain how to install this properly with both Uwsgi (for handling webservice) and supervisord (for handling other tracim daemon):
https://github.com/tracim/tracim/blob/develop/backend/README.md#deployment

I hope this can help you.

**Comment by Keepshango** [comment]
> if you do want to deploy tracim, the backend documentation is a bit more clear and accurate

Understood, thanks !
However, once the **Python Virtualenv** has been setup, as instructed in the **“Backend Readme“** page, **the command line prompt changes (e.g.) :**

From : root@vps-IP-ADDRESS:~#
To : **(env)** root@vps-IP-ADDRESS:~#

**/// Q1 ///**
- Should I or not remain in the **Virtual environment (env)** for **next steps like installing and building the frontend,** or installing **Pushpin** ?
- May you please reply the question with an **advice in regard of what should be install first and next** (pushpin, frontend, backend…) ?

**/// Q2 ///**
As I intent to use Tracim in production mode (not in development), am I right to skip command lines from chapter “Configuration“ in the “Backend Readme“ page ?

The same way that plugins allows the **add of functionalities for development usage**, does Tracim also have an optional **plugins store** that allows the of **add functionalities for production usage** ? 

Regards,

**Comment by raphj** [comment]
> Should I or not remain in the Virtual environment (env) for next steps like installing and building the frontend, or installing Pushpin ?

This does not matter. You can stay in the virtual environment or leave it.

> an advice in regard of what should be install first and next (pushpin, frontend, backend…) ?

It also does not matter: install them in the order you prefer. I usually build the frontend, and in another terminal install the backend and pushpin.

> am I right to skip command lines from chapter “Configuration“ in the “Backend Readme“ page?

Don't skip them. But cp commands create files, if they already exist you don't need to run them another time.

> does Tracim also have an optional plugins store that allows the of add functionalities for production usage ?

Yes, but it is experimental and prone to changes. We intend to build a more robust plugin system later. Do you need any particular custom behavior?

**Comment by Keepshango** [comment]
> We intend to build a more robust plugin system later. Do you need any particular custom behavior?

Not yet !
Thanks for your replies.

/// NOTE ///
In one of my other thread, you advised me to post any further issue in the same thread, but I observed that doing so, my questions are not replied (or are replied many days later…) !

Regards,
