### ISSUE TITLE
Backend Install with default SQLite database ?

### ISSUE THREAD

**Issue by Keepshango** [tracim/tracim#4241]
Hello,

These are questions to avoid any missing :

Although the SQLite database is bundled with python, is it automatically activated (this is not precised) ?
Any further step needed to get it activated ?

Regards

**Comment by raphj** [comment]
SQLite is the default database used in tracim, as you can see in the default configuration file, `backend/development.ini.sample` (parameter: basic_setup.sqlalchemy_url = sqlite:///%(here)s/tracim.sqlite).

It should work out of the box: in contrast to the other database engines, it does not require a dedicated deamon running on the server.

**Comment by Keepshango** [comment]
Thanks

**Comment by raphj** [comment]
Let us know when you manage to install and run tracim, we'd be glad to hear from you :-)
