### ISSUE TITLE
Backend install : output for pip install -e "." (see log file)

### ISSUE THREAD

**Issue by Keepshango** [tracim/tracim#4242]
**/// TEST ENVIRONMENT ///**
Machine : remote VPS 2vCore
OS distro : Ubuntu 18.04 (bionic beaver)
User :  root with sudo permissions
Web server : apache 2.4
Cpanel : ISPConfig 3.2.2

Hello,

Numbers below refers to numbered line in this **Backend installation log file :** [https://pastebin.com/XrrJxGkz](https://pastebin.com/XrrJxGkz)

Part of the output for command line **pip install -e "."** (from line n° **2909** to **2993**) was displayed in red, and I am also a beat worried to have read **“KeyError“** (line **2912**) and “**MemoryError“** (line **2993**).
May this prevent to access or use my Tracim instance ?

Further more, what may be the reason why NOT FOUND is the output for command line **“rq worker -q -w tracim_backend.lib.rq.worker.DatabaseWorker event elasticsearch_indexer & (line **3046**) ?

Regards

**Comment by raphj** [comment]
Hi again @Keepshango

Head's up on your memory usage when you log into your VPS: `Memory usage: 83%`. The install process most probably runs out of memory. You'll need to either lower you memory consumption by uninstalling stuff, or provide more ram.

There is also something else a bit fishy:

```
rq: command not found
```

It could be a consequence of the install process running our of memory though.

Could we keep your installation issues in a unique thread so it is easier to follow?

**Comment by raphj** [comment]
Another head's up: your links are systematically reversed (the markdown syntax is inverted).

**Comment by Keepshango** [comment]
Hello,

> Could we keep your installation issues in a unique thread so it is easier to follow?

Sure !

I can only get connected to my Tracim instance in  non secure HTTP mode (not in HTTPS), although **Tracim was installed in root directory of a website that was set from ISPConfig control panel**, with following **per check-box activation** services or parameters.

- SSL (activated)
- Let’s Encrypt (activated)
- Redirection from HTTP to HTTPS is activated (activated) 

I don’t know what setting(s) on Tracim or ISPConfig side should be modified, replaced, activated, or deactivated to avoid conflicts bugs, and perform a secured HTTPS connexion.

May you please help?

**Comment by Keepshango** [comment]
Thanks
