### ISSUE TITLE
Feat: Update components to handle new Publications feature

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4250]
## Feature description and goals

The new Publications feature will use the some of the same components as the activity feed and timeline.

- [x] The components below (at least) should be moved to a new folder `frontend/src/component/common/FeedItem` and renamed if needed
- `frontend/src/component/Activity/ContentWithPreviewActivity.jsx` renamed to `FeedItemWithPreview`
- `frontend/src/component/Activity/Preview.jsx` and its sylus
- `frontend/src/component/Activity/ContentActivityFooter.jsx`, its sylus and renamed to `FeedItemFooter`
- `frontend/src/component/Activity/ContentActivityHeader.jsx`, its sylus and renamed to `FeedItemHeader`
Note: the name is just a suggestion, can be changed. They can also be in `frontend_lib`instead `frontend`if it is more relevent.
- [x] The component `ContentWithPreviewActivity` should allow children to add the timeline on it
- [x] The components props should be generic for handle both cases
- [x] Update `frontend_lib/src/component/Timeline/Timeline.jsx` to extract the scroll behavior, like the example below

```jsx
Timeline.jsx
render (
    <ScrollWrapper>
        <TimelineList />
    </ScrollWrapper>
)

TimelineList.jsx
render (
    switch (content.timelineType) {
          case 'comment':
            return (
                <Comment />
            )
   ...
)

Publication.jsx
render (
    <ScrollWrapper>
      {props.publicationList.map(p => 
          <FeedItem />
      )}
    </ScrollWrapper>
)
```

## Prerequisites

None

**Comment by grignards** [comment]
> Update frontend_lib/src/component/Timeline/Timeline.jsx to allow publication type contents

After our discussion last friday I had in mind that we would extract the `Comment` and `PublishComment `components of the timeline to make them re-useable. Is this what you mean here?

**Comment by grignards** [comment]
> Comment is already a component maybe we can extract from the folder Timeline, but what I mean was use Timeline component to have the scroll behavior and update it to allow "FeedItemWithPreview" too

:thinking: Difficult to say without having a look at the code, but won't we end with a timeline component which first test which items types it has inside? If possible, extracting only the desired behavior (scroll) would be cleaner I think, instead of adding a new case to the `Timeline`.

**Comment by gbonaspetti** [comment]
> > Comment is already a component maybe we can extract from the folder Timeline, but what I mean was use Timeline component to have the scroll behavior and update it to allow "FeedItemWithPreview" too
> 
>  Difficult to say without having a look at the code, but won't we end with a timeline component which first test which items types it has inside? If possible, extracting only the desired behavior (scroll) would be cleaner I think, instead of adding a new case to the `Timeline`.

I haven't looked in detail yet, but from what I've seen to generate the scroll behavior the code uses three functions that can be passed to the helper, but uses componentDidMount and componentDidUpdate. This part of the code would end up being duplicated between the components (6 lines). Not a problem for me though, we can do like this.

Ps: I forgot to say, the PublishComment also has a component frontend_lib/src/component/Timeline/CommentTextArea.jsx

**Comment by grignards** [comment]
> I haven't looked in detail yet, but from what I've seen to generate the scroll behavior the code uses three functions that can be passed to the helper, but uses componentDidMount and componentDidUpdate. This part of the code would end up being duplicated between the components (6 lines). Not a problem for me though, we can do like this.

Or if we find it useful we could move the implementation in a HOC in order to be able to re-use them, eg:
```javascript
  componentDidUpdate (prevProps) {
    props.tryScrollToBottom()
  }
```

and something like this in the HOC:
```javascript
tryScrollToBottom = (list) => {
    if (this.props.timelineData && prevProps.timelineData) {
      this.scrollToBottom(prevProps.timelineData)
    }
    this.timelineContainerScrollHeight = this.timelineContainer.scrollHeight
}

**Comment by Skylsmoi** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
