### ISSUE TITLE
Feat: Update activity feed and add publications navigation

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4251]
## Feature description and goals

To add publication feature, we have to differentiate at most from activity feed, for this we will change a little the activity feed wording and add publications brand and navigation.

- [x] Add to `color.json.sample`: `publication: #661F98`
- [x] Change `Activity feed` to `Recent Activities` at
    - /frontend/src/component/Activity/ActivityList.jsx
    - frontend/src/component/TabBar/TabBar.jsx
    - /frontend/src/container/PersonalActivityFeed.jsx
    - /frontend/src/container/WorkspaceActivityFeed.jsx
    - /frontend/i18next.scanner/...
- [x] Add a new tab at spaces main pages for `Publications`
    - URL: .../ui/workspaces/{{workspaceId}}/publications
    - Icon: fas fa-stream
- [x] Update Sidebar to have `Publication` in place of `Activity Feed`
    -  /backend/tracim_backend/app_models/workspace_menu_entries.py
    - /frontend/src/container/Sidebar.jsx

## Translations

|English|French|Portuguese|
|--|--|--|
|Recent Activities|Activités récentes|Atividades recentes|
|Publications|Publications|Publicações|

## Prerequisites

None

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
