### ISSUE TITLE
Feat: Add publications in recent activities 

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4252]
## Feature description and goals

- [x] If a user post a content in Publications page, this content appears in the recent activities (as any content), excepted its icon and color which should be the publication brand (icon + color, see #4251).
- [x] If a user clicks on a content posted in publications in recent activities, he is redirected to Publications page instead of opening the content's app.

This issue is about handling the related TLM.

The TLM will be `content.created.[file, thread]` with the property `fields.content.content_namespace` set to `publication`.

## Prerequisites

#4251 
https://github.com/tracim/tracim/issues/4254

**Comment by raphj** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
