### ISSUE TITLE
Feat: Add reactions to publications page

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4253]
## Feature description and goals

- [x] Users will be able to react to the various comments, as well as to the publication. 
- [x] If a reaction is made on a publication composed of a file and a comment, the reaction is made on the content and not on the comment.

## Prerequisites

https://github.com/tracim/tracim/issues/4254

**Comment by raphj** [comment]
This has been automatically done in #4303

**Comment by raphj** [comment]
tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
