### ISSUE TITLE
Feat: Add publication page

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4254]
## Feature description and goals

The "publications" feature will be a feed where a user can publish a publication and react to the publications of others. Each space will have its own thread which will be accessible via a tab on the "main pages".

Two types of content are possible: threads and files. For this issue only the threads will be implemented.

- [x] Threads are created when the user posts a text message without any files.
- [x] Publications have a fixed width (as recent activities).
- [x] Handle changes in real time for comments and new publications (if a new publication is made, it will appear at the bottom of the feed). The order of the items in the publication feed will not change in real time (modifications at already displayed publications). The most recent items are at the bottom. As in the content history.
~~- [ ] The behavior of the page scroll will be the same as for the content history. As soon as the user enters the page, an automatic scroll will occur, sending the user to the end of the page. When it is at the end of the page, scrolling is maintained, but if it is not at the end, scrolling is not performed~~ (to be done in a second time)
- [x] In the publications page, if the user clicks on the publication input, it is focused with a border in the color of the feature + enable Publish button when the user start to write (the button is disabled if the entry is empty).
- [x] The publications should have the advanced edition option.

## Translations

|English|French|Portuguese|
|-|-|-|
|Publish|Publier|Publicar|
|Write your publication...|Écrivez votre publication ...|Escreva a sua publicação...|

## Prerequisites

#4250 
Backend endpoint to GET the content list: https://github.com/tracim/tracim/issues/4263 (see comment below for workaround during development)

## Interface
_Obs: These interface examples are only templates, not everything will be developed in this issue and some details can be changed according to the implementation._
![maquette_publications_finale](https://user-images.githubusercontent.com/35422692/110335316-feaea080-8023-11eb-9ef6-ecc624611903.png)

**Comment by raphj** [comment]
tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
