### ISSUE TITLE
Feat: Add file upload at publications

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4255]
## Feature description and goals

Two types of content are possible in publication page: threads and files. This issue will add the file type.

- [x] In the publications page, if the user clicks on the 'paperclip' icon next to 'publish' button, it opens the add file popup
- [x] The popup should allow the upload of a single file
- [x] If the user publishes a file with a text message, this message will be the first comment in the file.

## Prerequisites

#4254 
https://github.com/tracim/tracim/issues/4256

## Interface
_Obs: These interface examples are only templates, not everything will be developed in this issue and some details can be changed according to the implementation._
![maquette_publications_finale](https://user-images.githubusercontent.com/35422692/110335316-feaea080-8023-11eb-9ef6-ecc624611903.png)
![uploaded_file](https://user-images.githubusercontent.com/35422692/110340113-2f450900-8029-11eb-9c5f-4671ad92c396.png)

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
