### ISSUE TITLE
Feat: Add file upload at comments 

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4256]
## Feature description and goals

Just like on the publications page, it will be possible to add files in the comments.

- [x] If the user clicks on the 'paperclip' icon next to comment button, it opens the add file popup
- [x] The popup should allow the upload of a single file
- [x] When submitting the comment, it must save the comment and the files
- [x] When loading the timeline, it must load the files like it loads the revisions and comments
- [x] The Timeline must display the files
- [x] Handle TLM content created to add it to the timeline
- ~~[ ] If the user publishes a file with a text message, this message will be the first comment in the file.~~
  - This won't be implemented for first release

## Current implementation

User `u1` adds a comment with text `t1` and 2 files `f1` and `f2` to a content `c1`.
We will create t1 as a comment and then add the files f1 and f2 with a parent id equals to the content_id of c1.
This means we attach the files to the content, and not to the comment.

## Alternative implementation that won't be implemented

We initially plan on attaching the files to the comment (and not to the content).
This would imply a different design for comments containing a file. It would also imply getting from api the list of files possibly attached to each comments.
As this is more work, we won't do it fir now.

## Prerequisites

#4266 

## Interface

![uploaded file](https://user-images.githubusercontent.com/35422692/110344683-07a46f80-802e-11eb-8bfd-55ead39f43db.png)

**Comment by Skylsmoi** [comment]
new contents files will be created with the parent_id equal to the content on which we add a comment.

**Comment by Skylsmoi** [comment]
intelligence to send file to api will be added to the component CommentTextArea. It doesn't have to get this handler from its parent

**Comment by Skylsmoi** [comment]
When uploading multiple files display them as bellow:

![screen_display_multiple_files_as_comment](https://user-images.githubusercontent.com/11177014/111458547-d73d8f00-8719-11eb-90be-d2173cc39b1a.png)

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
