### ISSUE TITLE
Feat: Handle small screen display in publications page

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4258]
## Feature description and goals

In the mobile version (small screens), the following elements will be hidden :
- [ ] Type of the last modification
- [X] Advanced edition button
- [ ] Links description 
- [X] fit the publications in the screen

## Interface

![maquette_mobile_finale](https://user-images.githubusercontent.com/35422692/110347079-88fd0180-8030-11eb-8841-ae03b6880d15.png)

**Comment by raphj** [comment]
For now we can't handle the type of the last modification and the links description since they do not exist yet.

**Comment by PhilippeAccorsi** [comment]
@gbonaspetti some checkbox is empty, is it normal ?

**Comment by gbonaspetti** [comment]
> @gbonaspetti some checkbox is empty, is it normal ?

Yes, explained here https://github.com/tracim/tracim/issues/4258#issuecomment-805607545

**Comment by PhilippeAccorsi** [comment]
Done.
