### ISSUE TITLE
Feat: create a "publication" namespace for contents

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4263]
## Feature description and goals

A new feature of Tracim's interface will be [publications](https://github.com/tracim/tracim/issues/4254). Those publications will be  stored as standard contents (thread/file) in a special namespace (an existing feature currently used to differentiate guest file uploads and "standard" contents).

- [x] Add a new namespace `publication`
- [x] Allow `content_namespace` in `POST /api/workspaces/<workspace_id>/contents`, defaulting to `content`
- [x] Allow `content_namespace` in `POST /api/workspaces/{workspace_id}/files`, defaulting to `content`
- [x] Create the needed migration script (as content namespaces values are checked in the db)

**Comment by inkhey** [comment]
tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
