### ISSUE TITLE
Mail notification : enable implicit_ssl  (set to false or true) ?

### ISSUE THREAD

**Issue by Keepshango** [tracim/tracim#4265]
/// TEST ENVIRONMENT ///
Machine : remote VPS 2vCore
OS distro : Ubuntu 18.04 (bionic beaver)
User : root with sudo permissions
Web server : apache 2.4
Cpanel : ISPConfig 3.2.2

Hello,

As instructed in case of using implicit smtp with **encryption port like 465 (my use case)**, I want to **enable implicit_ssl** ([line 496 in INI file](https://pastebin.com/NZ81s0a9)), but the **parameter to be applied** in such a use case is **not precised :** should it be set to **false (default) or true ?**

Regards

**Comment by tracim** [comment]
@Keepshango when you create an issue, **please respect the template**

**Comment by PhilippeAccorsi** [comment]
> but the parameter to be applied in such a use case is not precised : should it be set to false (default) or true ?

This is visible in the beggining of the development.ini file:
~~~
## File Syntax
# Comments start by `;` or `#`.
# In the sample config file:
#  - `;` commented lines are used to indicate the default values used by Tracim;
...
~~~

An the text here explain how it's work by default
~~~
# enable implicit ssl if you are using implicit smtp with encryption port like 465
# by default, Tracim will try to use explicit smtp encryption using starttls, and unencrypted
# connection as fallback.
; email.notification.smtp.use_implicit_ssl = False
~~~

Regards,

**Comment by Keepshango** [comment]
> #  - `;` commented lines are used to indicate the default values used by Tracim;

Sorry, I probably misspoked… !

I know what commented lines are used for, and how to enable them (removing `;` or `#`), **so not the enabling but the parameter setting (false or true) was my question focused on.**

As this is not precised, **I still have a doubt about** how to set this command line parameter **(false or true)**, to have it matches **my use case** (using implicit **smtp with encryption port like 465**).

**/// Q ///**
In such my use case, should the **“implicit_ssl“** parameter be **left as default (set to false), or set to true ?**

Regards

**Comment by PhilippeAccorsi** [comment]
If you want to use implicit, you need to activate this parameter like this: `email.notification.smtp.use_implicit_ssl = True`.

**Comment by Keepshango** [comment]
OK !

**Comment by Keepshango** [comment]
Hello,

By the way,  I was told to respect the template when creating an issue !
As I am not so familiar to Github issue usages, can you please tell me how did I go wrong, or redirect me to some info page upon this matter.

Regard
