### ISSUE TITLE
Feat: Allow file children in html-documents and files

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4266]
## Feature description and goals

With the publication feature comes the possibility to link a file content in other contents (files/html-documents). When adding a new file it should be created as the child of the comment.

- [x] allow file children in all content types.
- [x] remove the `Event` content type
- [x] add a notice and explanation how to remove event contents from a database coming from v1.

## Additional change

Currently, the endpoints `/api/workspaces/{workspace_id}/{content_type}/{content_id}/revisions` have a specific property `comment_ids` that returns the list of comments for a revision.
This was a specific request from the frontend.
Since the timeline will now be generated from 3 sources (revision, comments and comments as file), this property will be outdated and won't be used anymore. The frontend will sort the timeline elements based on created date.

~~- [ ] remove the property `comment_ids` from endpoints returning revisions~~ => Will be done in #4256 PR.

## Behavior of related functionalities

- support in breadcrumb mechanism => gives the full path, including the parent content's name (as it would do for a folder)
- indexation behavior => child contents are searchable and found separately from their parents
- recent activity/read feature in dashboard => child contents are displayed in it, like contents in folder/root.

**Comment by inkhey** [comment]
some point to be careful of : 
- support in breadcrumb mecanism
- indexation behavior ?
- legacy ? Recent activity/read feature.

**Comment by PhilippeAccorsi** [comment]
@grignards one check box empty and is it tested ?

**Comment by grignards** [comment]
> @grignards one check box empty and is it tested ?

It has been tested with the corresponding frontend development, the missing checkbox is done, see https://github.com/tracim/tracim/issues/4282#issuecomment-801944438 in the changelog issue.

**Comment by PhilippeAccorsi** [comment]
Done.
