### ISSUE TITLE
Feat: Be able to activate/deactivate publications via advanced dashboard

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4270]
## Feature description and goals

The publications feature can be activated/deactivated by space via advanced dashboard.

- [x] Add a toggle option at Optional Functionalities
- [x] All ways to navigate to publications page should be related to this configuration

## Prerequisites

#4251

**Comment by grignards** [comment]
Does that mean that the backend should ensure this? Or is it only a frontend setting?

**Comment by raphj** [comment]
It is per space, not per user / per space, so I guess we will need an attribute attached to workspaces in the backend, and endpoints to handle this.

**Comment by grignards** [comment]
> It is per space, not per user / per space, so I guess we will need an attribute attached to workspaces in the backend, and endpoints to handle this.

Yes, what I meant is "should the backend refuse to create (list?) contents in the publication namespace if publications are disabled ?".

**Comment by inkhey** [comment]
> > It is per space, not per user / per space, so I guess we will need an attribute attached to workspaces in the backend, and endpoints to handle this.

Yes, like for public upload feature, i'm considering some kind of db refactor here, but we may decide to do it later and just add boolean field to workspace.

> 
> Yes, what I meant is "should the backend refuse to create (list?) contents in the publication namespace if publications are disabled for a workspace?".

Yes, like public upload is not anymore possible if we disable the feature. As this is the current behavior, existing publication will still exist, but we will not been available in ui. (may be available with recent change event or favorites), it's not really nice, but we could decide to make thing better later.
I suggest to deal with some kind of "fake app" for this, as this is a generic way to active/disable feature and will make more sense. This will need a bit more work from backend, but will make code more clear.

**Comment by inkhey** [comment]
this ticket is a kind of part of this: https://github.com/tracim/tracim/issues/4388

**Comment by grignards** [comment]
> > > It is per space, not per user / per space, so I guess we will need an attribute attached to workspaces in the backend, and endpoints to handle this.
> 
> Yes, like for public upload feature, i'm considering some kind of db refactor here, but we may decide to do it later and just add boolean field to workspace.
> 
> > Yes, what I meant is "should the backend refuse to create (list?) contents in the publication namespace if publications are disabled for a workspace?".
> 
> Yes, like public upload is not anymore possible if we disable the feature. As this is the current behavior, existing publication will still exist, but we will not been available in ui. (may be available with recent change event or favorites), it's not really nice, but we could decide to make thing better later.
> I suggest to deal with some kind of "fake backend app" for this, as this is a generic way to active/disable feature and will make more sense (similar active/disable approach as public upload). This will need a bit more work from backend, but will make code more clear.

I think you are confusing "totally disabling the publications in a Tracim instance" and "disabling the publications for selected workspaces in a Tracim instance". A backend app is not the solution for this issue which is "disabling publications for selected workspaces".

**Comment by grignards** [comment]
As the question of having optional features per workspace arises regularly (currently we have agenda, guest download, guest upload, and now publications) I think that having a generic but simple mechanism would be a good idea.
Such a mechanism could be to have a list of *features" per workspace:
```json
{
  "workspace_id": 1,
  "label": "Foo",
  "features": ["publications"]
}
```
Those features would be stored in a specific table with two columns (+ possibly created/author columns):
- workspace_id
- feature taken from an enumeration.

**Comment by raphj** [comment]
Tested on branch.
