### ISSUE TITLE
Feat: Have the possibility to "Reorder" the Publications

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4271]
## Feature description and goals

The order of the items in the publication feed will not change in real time, a "Reorder" button will appear if there have been changes in the order.

Order: most recent items at the bottom. As in the content timeline.

Icon: fas fa-redo-alt

## Translation

|English|French|Portuguese|
|-|-|-|
|Reorder|Réorganiser|Reordenar|

## Prerequisites

#4254 

## Interface
![maquette_publications_finale](https://user-images.githubusercontent.com/35422692/110462949-9f0ece80-80d1-11eb-9013-78d5d8d99cf4.png)

**Comment by raphj** [comment]
So, the orders of publications and of the activities in the recent activities are inverted?

**Comment by Skylsmoi** [comment]
Note that, in the PR https://github.com/tracim/tracim/pull/4315, I have updated the timeline sort function to be able to sort contents created at the same second by their content_id.
This is because backend sends created_at in iso format but without the milliseconds

**Comment by raphj** [comment]
already done, actually

**Comment by PhilippeAccorsi** [comment]
Done in another PR.
