### ISSUE TITLE
Feat: Add reactions element in backend

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#4272]
## Feature description and goals

Add reactions element to tracim, reactions are element which are not content but could be associated to a content (comment, file, folder, ...). Reaction are for now emoji.
more explanation here: https://algoo.tracim.fr/ui/workspaces/124/contents/html-document/15201?folder_open=14445 (internal doc)

`reaction` table:

fields | type | primary_key | other |
-- | -- | -- | -- |
reaction_id | int | yes |   |
content_id | int | no | unique(composite) |
owner_id | int | no | unique(composite) |
value | str | no | unique(composite) |
created | datetime | no | 

endpoints (4):

```http
GET /api/content/{{content_id}}/reactions/{{reaction_id}}
200
{
  "content_id": 41,
  "reaction_id": 241,
  "author": {
      "user_id": 23,
      "public_name": "John",
      "+ xxx UserDigestSchema": ""
   },
  "created": "2020-09-23T00:23:23",
  "value": "🐰"
}
###
GET /api/content/{{content_id}}/reactions
200
[{
  "reaction_id": 241,
  "content_id": 41,
  "author": {
  "user_id": 23,
  "public_name": "John",
    "+ xxx UserDigestSchema": ""
   },
   "created": "2020-09-23T00:23:23",
   "value": "🐰"
}]
###
POST /api/content/{{content_id}}/reactions
Content-Type: application/json

{
  "value": "🐰"
}

###
DELETE /api/content/{{content_id}}/reactions/{{reaction_id}}
204


```

to do:
- [x] add reaction table
- [x] add mixins between tables to avoid repetition 
- [x] migration script
- [x] add reactionlib
- [x] get/get/post/delete endpoints + related tests
- [x] add reaction tlm

TLM:
-
## Implemented solution:
https://github.com/tracim/tracim/pull/4278
```
- new entity: reaction with specific database table
- endpoints to get all content related reaction/get a specific reaction/add it/delete it
- set mysql/mariadb to utf8mb4 by default by adapting depot file fields (convert from varchar(4000) to text).
- add `tracimcli db migrate-mysql-charset` command permitting transition from old to new database format for mysql.
- support deletion of user reactions in cleanup command (tracimcli user delete).
Refs: #4272
```

**Comment by PhilippeAccorsi** [comment]
Done.
