### ISSUE TITLE
Feat: Add emoji reactions to contents and comments

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4274]
## Feature description and goals

Tracim is letting you react with emojis on contents and comments. To do:

 - [x] add the reaction buttons to comments
 - [x] add the reaction buttons to contents
 - [x] The main button should have a "React" tooltip
   - [x] use the emoji-mart picker
 - [x] use native fonts for emojis, and not images

Reaction buttons:
 - [x] are highlighted when the user has reacted with this reaction
     - border-color: primary color
     - background-color: primary color with 20% of opacity
 - [x] show the emoji reaction and the number of people who reacted
 - [x] have a title showing the list of people who reacted (public name) and ideally the name of the emoji
 - [x] clicking on the button adds / removes oneself to/from the list of people who reacted
    - [x] if the user was the only one who reacted with this reaction and remove themself, the button is removed too

![emoji](https://user-images.githubusercontent.com/3817365/110488161-82cd5a80-80ee-11eb-949c-61ce434b0708.jpg)

**Comment by PhilippeAccorsi** [comment]
Done.
