### ISSUE TITLE
Feat: Add file preview in comments

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4276]
## Feature description and goals

Add a file preview in the comments that have a file uploaded.

## Prerequisites

#4256 

## Interface

![maquette_app_finale](https://user-images.githubusercontent.com/35422692/110606694-b8278600-818a-11eb-95c5-bddaded95301.png)

**Comment by Skylsmoi** [comment]
This issue will follow this issue's progression https://github.com/tracim/tracim/issues/4256 since its development is included in the other issue's PR

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
