### ISSUE TITLE
Feat: prepare new release 3.7.0

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#4282]
## Feature description and goals

- [x] update frontend version
- [x] update backend version
- [x] update changelog

**Comment by Skylsmoi** [comment]
New color added to color.json.sample for 'publications'

**Comment by inkhey** [comment]
Reaction feature add big change to mysql/mariadb support:
https://github.com/tracim/tracim/pull/4278

This need a special modification in database to work, provided by a tracimcli command line (can be done after or before standard migration):
https://github.com/tracim/tracim/blob/2a6aae281046e7a10bf4c5b24dfc60f81214c709/backend/doc/cli.md#migrate-mysqlmariadb-database-to-utf8mb4-added-for-tracim-37

**Comment by grignards** [comment]
HTTP API change by: https://github.com/tracim/tracim/issues/4264
`/api/workspaces/<workspace_id>/contents` now returns an object containing the contents in "items" instead of a direct list. The object also contains pagination information when the `count`/`page_token` parameters are used.

**Comment by raphj** [comment]
The default of `web.notifications.excluded` changes from `user.created, user.modified, user.deleted, user.undeleted, workspace.modified, workspace.deleted, workspace.undeleted, workspace_member.modified, content.modified` to `user.*, workspace.modified, workspace.deleted, workspace.undeleted, workspace_member.modified, content.modified, reaction.*` in https://github.com/tracim/tracim/pull/4278

The recommended action should be to add `reaction.*` to any custom preference, to reactions do not show up in the notification wall.

**Comment by grignards** [comment]
Contents of type `event` become unsupported starting with #4266. It is recommended to remove them from databases which have been created with Tracim version 1.
We recommend to dump your database before executing the following command to keep your event data and protect against a miss-typing.
To erase the `event` contents:
```
delete from content where cached_revision_id in (select revision_id from content_revisions where type='event)'
```

**Comment by inkhey** [comment]
default value for
`web.notifications.excluded`
as changed to a reduced synonym + filtering for new type: reaction
https://github.com/tracim/tracim/pull/4278#discussion_r596959328

**Comment by PhilippeAccorsi** [comment]
> default value for
> `web.notifications.excluded`
> as changed to a reduced synonym for user (should not change anything technically) + filtering for new type: reaction
> [#4278 (comment)](https://github.com/tracim/tracim/pull/4278#discussion_r596959328)

duplicated modification information with https://github.com/tracim/tracim/issues/4282#issuecomment-801880866 but maybe good information in the two comment

**Comment by PhilippeAccorsi** [comment]
Done.
