### ISSUE TITLE
Bug: new ES Indices are created each time `tracimcli search index-create` is called

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4292]
### How to reproduce

1. Activate elasticssearch
2. Launch `tracimcli search index-create` twice
3. The indices are created twice

### Version information

- Tracim version: 3.6rc3

________________________________________________

## Diagnostic

A test of existence of the *alias name* was replaced by a test of existence of the *index name* during the implementation of multiple indices support.

**Comment by PhilippeAccorsi** [comment]
This bug is introduced by the refactor for advanced search. Not necessary to add in changelog.
