### ISSUE TITLE
Bug: Button "see more" in advanced search can fail to load more results

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#4299]
## Description and expectations

It is possible to make the "see more" button in the advanced search to not trigger a new search.

### How to reproduce

- have search using elasticsearch (advanced search)
- search a keyword that return more than one page of results
- click "see more" button
- open filters
- activate a filter that will return more than one page of results
- click "see more" button
- nothing happens

### Version information

- Tracim version: 3.6.0_rc5
- Web browser: any
- Version: any
- Device / System: any

________________________________________________

## Diagnostic

The issue is about the architecture of the advanced search that takes some parameters from the url and some from local variables (state or redux).
Two main issues:
- The page number is set in the url but is then duplicated in each search type objects in redux
- The filters aren't saved in the url

These 2 issues makes it complicated to properly set "see more" button search parameters:
When activating a filter, we set the page number back to one and we make an api call to do the search but we can't set the page number in the url or another search will be triggered without the filters (because filters aren't in the url).
We then have a mismatch between url and currentPage local variable (url is page 2 because of the first "see more" before activating filter (see "how to reproduce")) but the local currentPage is one.
Then, when clicking on "see more" button, it set the url page_number to 2, which already is. So the url doesn't change and components doesn't refresh and api search isn't triggered.

## Workaround

~~The current workaround that will be (or is) applied is to set the default search result number to a bigger number to reduce the chance to have more than one page of results after having applied a filter.~~
update: This issue has been properly worked around here: https://github.com/tracim/tracim/pull/4301/commits/6fe78e20430af1f43484acf4a4dfddc54b5a783f (added in 3.6.0)

**Comment by gbonaspetti** [comment]
Fixed at https://github.com/tracim/tracim/commit/6fe78e20430af1f43484acf4a4dfddc54b5a783f
