### ISSUE TITLE
Bug: Some date range in advanced search doesn't work

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#4300]
## Description and expectations

The date range content last modification and newest author doesn't work

### How to reproduce

The date sent to api doesn't have the proper format, visible with dev tools.

### Version information

- Tracim version: 3.6.0_rc4
- Web browser: any
- Version: any
- Device / System: any

________________________________________________

**Comment by PhilippeAccorsi** [comment]
Done
