### ISSUE TITLE
Bug: Emoji reaction buttons have some responsiveness issues and readers cannot see them

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4307]
## Description and expectations

To do:
 - [x] Make emoji reactions buttons available to readers
 - [x] Make emoji reactions buttons responsive
 - [x] Make emoji reactions buttons more square, by reducing the font-size of the count
 - [x] Fix the responsiveness of the status selection button too (this will allow more room for emoji reaction buttons) 

## Screenshots

![image](https://user-images.githubusercontent.com/3817365/111959908-60284200-8aef-11eb-8a27-0cdfc3f443e6.png)

**Comment by grignards** [comment]
Small remarks:

- In a content app the emojis are displayed on two lines when there are too many, but the second line is partly hidden and displays a scroll. Is this behavior expected?
- In the recent activities the two lines of emojis are not aligned when the connected user can add reactions:

![image](https://user-images.githubusercontent.com/51887114/112111205-2cfbb680-8bb4-11eb-9940-98fc4aab13d8.png)

**Comment by PhilippeAccorsi** [comment]
Done.
