### ISSUE TITLE
Bug: Database migration for reactions is incomplete

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4308]
## Description and expectations

It is not possible to add a reaction after migrating an existing database to develop (future Tracim 3.7, starting at commit 53ee8710079fbb297edcd4ded0c804c8474a9790).

### How to reproduce

1. Create a database with a version before 53ee8710079fbb297edcd4ded0c804c8474a9790
2. Upgrade it
3. Try to add a reaction.

### Version information

- Tracim version: develop (starting at commit 53ee8710079fbb297edcd4ded0c804c8474a9790)

## Screenshots

________________________________________________

## Diagnostic

The update of an integrity check on event/tlms entity type has been forgotten.

**Comment by PhilippeAccorsi** [comment]
Done.
