### ISSUE TITLE
Feat: Favorites content (backend part)

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#4309]
## Feature description and goals

Allow user to have a list of favorites content, permitting to easily retrieve some contents.

New database table `favorite_content` needed:

| column_name | type  | primary key ? |
|------------|--------------------------|---------------------|
| user_id    | foreign_key user.user_id | part of primary key |
| content_id | foreign_key ? content.id   | part of primary key |
| created | datetime not nullable ||
| original_label | varchar(sizelabel) not nullable ||
| original_type |  varchar(sizetype) not nullable ||

Future api:

```
GET /api/user/{user_id}/favorite-contents/{content_id}
200 favorite object


GET /api/user/{user_id}/favorite-contents
[
  {
    "content_id": 1,
    "user_id": 3,
    "original_label": "Intervention Report [WIP]",
    "original_type": "file",
    "content": {
        "actives_shares": 0,
        "author": {
          "has_avatar": true,
          "has_cover": true,
          "public_name": "John Doe",
          "user_id": 3,
          "username": "My-Power_User99"
        },
        "content_id": 6,
        "content_namespace": "content",
        "content_type": "file",
        "created": "2021-03-22T15:15:10.393Z",
        "current_revision_id": 12,
        "current_revision_type": "creation",
        "file_extension": ".txt",
        "filename": "Intervention Report 12.txt",
        "is_archived": false,
        "is_deleted": false,
        "is_editable": true,
        "label": "Intervention Report 12",
        "last_modifier": {
          "has_avatar": true,
          "has_cover": true,
          "public_name": "John Doe",
          "user_id": 3,
          "username": "My-Power_User99"
        },
        "modified": "2021-03-22T15:15:10.393Z",
        "parent_id": 34,
        "show_in_ui": true,
        "slug": "intervention-report-12",
        "status": "closed-deprecated",
        "sub_content_types": [
          "html-content"
        ],
        "workspace_id": 19
      }
  },
  {
    "content_id": 3,
    "user_id": 2,
    "original_label": "My new super content !",
    "original_type": "file",
    "content": null
  }
]

POST /api/user/{user_id}/favorite_contents
{
 "content_id": 
}
200
favorite object

DELETE /api/users/{user_id}/favorites_contents/{content_id}
204
```

- All endpoints are accessible by both admin and user itself.
- Access to content_id should be done at post (it should not being possible to add not accessible content as favorites).
- Contents returned should be filtered by user visible content, so content where user does not have anymore access should not being anymore visible (and deleted too ?) for now, something better may be done but it's complicated to find the good process. 
- copy of content (through webdav) should not copy the favorites contents (stay favorites for only original content, not the copy).
## Extra information 
This feature is for favorites content for user, it's different from :
- favorites content for a workspace defined here-- https://github.com/tracim/tracim/issues/547 which may be done in a slightly different way with customizable workspace home page (rich text in description/raw_content + link to content)
- https://github.com/tracim/tracim/issues/3775 which associate color to workspace, which is similar to some kind of "favorite workspace for user".

## Implemented feature:
https://github.com/tracim/tracim/pull/4317

```
- add table for favorites contents: favorite_contents and migration script
- add favorite related method to contentapi.
- add 4 endpoints to deal with favorites: get list, get one, set one a favorite, remove one from favorite
- adapt favorite object to allow a degraded state when content is not anymore visible.
```

**Comment by grignards** [comment]
May I suggest to add the `created` date to the table as we discussed friday? It doesn't cost much and could easily have a usage in a not so far future.

**Comment by grignards** [comment]
Also the `GET` api would benefit to be "pagination ready", i.e. return the results in an object containing an `items` list:
```
{
  "items": []
}
```
So that we do not introduce a breaking-change if/when pagination is becomes useful here.

**Comment by inkhey** [comment]
added PR:
https://github.com/tracim/tracim/pull/431,
some change:
- favorite-contents instead of favorite-contents
- "pagination ready" endpoint : very few change needed to have proper pagination.
- return 204 (with no content) instead of 200 for post : we do not really "create" a specific object, so returning a file here is somehow weird. maybe should we use 201 instead ?

**Comment by inkhey** [comment]
@lebouquetin can you confirm this behaviour is ok for you:

> Contents returned should be filtered by user visible content, so content where user does not have anymore access should not being anymore visible (and deleted too ?) for now, something better may be done but it's complicated to find the good process.

Note: in current WIP implementation, both deleted and non accessible are filtered.

**Comment by inkhey** [comment]
Proposal to be able to handle the not accessible case:

return of `GET /api/user/{user_id}/favorite-contents`
```json
  {
    "content_id": 1,
    "user_id": 3,
    "original_label": "Intervention Report [WIP]",
    "original_type": "file",
    "content": {
        "actives_shares": 0,
        "author": {
          "has_avatar": true,
          "has_cover": true,
          "public_name": "John Doe",
          "user_id": 3,
          "username": "My-Power_User99"
        },
        "content_id": 6,
        "content_namespace": "content",
        "content_type": "file",
        "created": "2021-03-22T15:15:10.393Z",
        "current_revision_id": 12,
        "current_revision_type": "creation",
        "file_extension": ".txt",
        "filename": "Intervention Report 12.txt",
        "is_archived": false,
        "is_deleted": false,
        "is_editable": true,
        "label": "Intervention Report 12",
        "last_modifier": {
          "has_avatar": true,
          "has_cover": true,
          "public_name": "John Doe",
          "user_id": 3,
          "username": "My-Power_User99"
        },
        "modified": "2021-03-22T15:15:10.393Z",
        "parent_id": 34,
        "show_in_ui": true,
        "slug": "intervention-report-12",
        "status": "closed-deprecated",
        "sub_content_types": [
          "html-content"
        ],
        "workspace_id": 19
      }
  },
  {
    "content_id": 3,
    "user_id": 2,
    "original_label": "My new super content !",
    "original_type": "file",
    "content": null
  }
]
```

note: original_label and original_type are the info needed to show a proper "broken" favorite. They should be saved as new field in  favorite table. Their goal is to be used as fallback for type/name if content is not anymore available. Another solution may be having some logic in a type/label field at favorite items root that use either original_label from database or existing label if content is available.

**Comment by lebouquetin** [comment]
@inkhey I like this :+1: Good job!

**Comment by inkhey** [comment]
> @inkhey I like this +1 Good job!

Some points to notice:
- There is always an edge case where favorite can disappear in current implementation: if someone fully delete a content, this may be solvable by not using foreign key for content_id but i'm not sure that a good idea to remove this constraint.
- null case happened because join doesn't match. there is no "null" for content_id in database.

**Comment by inkhey** [comment]
| column_name | type  | primary key ? |
|------------|--------------------------|---------------------|
| user_id    | foreign_key user.user_id | part of primary key |
| content_id | foreign_key ? content.id   | part of primary key |
| created | datetime not nullable ||
| original_label | varchar(sizelabel) not nullable ||
| original_type |  varchar(sizetype) not nullable ||

**Comment by gbonaspetti** [comment]
Tested during integration.

**Comment by PhilippeAccorsi** [comment]
Done.
