### ISSUE TITLE
Feat: Customizable login page

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#4310]
## Feature description and goals

Tracim's login page should be customizable per instance.
Two levels of customization are planned.

### Simple customization

The instance's administrator can:
  - edit a simple html file used as a rich-text format
  - copy a background image

### Advanced customization

In this case the whole html representing the custom login page part is written and maintained by the instance administrator (and possibly web designers for the page creation).

The customized content shall be available for search engine indexing so should be part of the `index.html/mak` which is downloaded when connecting to a Tracim instance.

## Technical implementation

- [x] include a "welcome.html" file in the `index.mak` template used to generate Tracim's index page. This file can also be a mako template.
- [x] the name of this file should be configurable through `development.ini`, for example `website.welcome_page = ...`
- [x] it must be placed in a folder made available outside our docker image, in `/etc/tracim/branding/` for example. The contents of this folder shall be available through HTTP requests, for example under `/assets/branding` so that images/css in this folder are accessible to "welcome.html". :warning: There are two docker folders now.
- [x] write a "simple-welcome.html" template that takes care of the needed styling for the simple customization and includes a "simple-welcome-text.html" file which can be edited to tune the welcome text in this case. The styling of this page should be responsive.
- [x] all the supplied welcome files should be copied from .sample by the docker container if they do not already exist.
- [x] the custom welcome page will be placed in a `<div>` of id `welcome` so that the frontend app can properly position it.
- [x] document the customization possibilities in `backend/doc/setting.md`.
- [x] in particular recommend to use a special prefix in custom css rules (for advanced customization), for example `tracimCustomWelcome`.
- [x] find a markdown -> html online service and document its possible usage to create `simple-welcome-text.html`.
- [x] by default the login page shall use the simple welcome with a default background image and a default text.
- [x] update the frontend's design (see the interface below)

## Interface

![login](https://user-images.githubusercontent.com/51887114/112471631-6b3bd600-8d6c-11eb-9d28-e5afbaa2a9a2.png)

## Translations

|English|French|Portuguese|
|-|-|-|
|Sign in|Se connecter||
|Login|Identifiant||

### Translations of the customized welcome pages

Not done for the moment, seen as useful but not essential currently. See #4324 for following/discussing this improvement.

### Markdown as language for simple-welcome-text

Not done for the moment, we'll only indicate the possibility of using an online tool to create the needed html file from a markdown. See #4325 for following/discussing this improvement.

### How migration work with this kind of feature, what should be shown for updated tracim to 3.8?

The user has nothing to do to update to Tracim 3.8, the feature will provide a default image and text if nothing is changed by the instance's administrator. When updating later on: the only changed files will be the `.sample` versions, so nothing is overwritten by accident. The simple customization text will never need change from our side. If incompatible changes are made in any welcome `.sample` file, this has to be documented through the changelog.

### What happened if we do not provided this file/default case?

See above.

### Because the feature is not translated, are we ok with a default non translated welcome page?

Currently yes (what remains to decide is the default text we want, and its language).

**Comment by inkhey** [comment]
some question : 
- How migration work with this kind of feature, what should be shown for updated tracim to 3.8 ?
- What happened if we do not provided this file ?

**Comment by Skylsmoi** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
