### ISSUE TITLE
Bug: Add a more user-friendly name to publications

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4318]
## Description and expectations

- [x] When a user publish a new publication it name should be "Publication of {{author}} at {{date}}"
- [x] This phrase should be in the author language 

## Translations

|English|French|Portuguese|
|-|-|-|
|Publication of {{author}} at {{date}}|Publication de {{author}} le {{date}}|Publicação de {{author}} em {{date}}|

### Version information

- Tracim version: v3.7

**Comment by raphj** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
