### ISSUE TITLE
Installation: size limit warnings on six items (critical) ?

### ISSUE THREAD

**Issue by Keepshango** [tracim/tracim#4321]
Hello, 

These below are **size limit WARNINGS** outputs copied from the **Tracim installation log**, and are part of output results of **command line “./build_full_frontend.sh“.**

**/// Qs ///**
- May these potentially leads to critical bugs if left unchanged ?
- If recommended, what parameter should be changed (increased or decreased), and where such changes may be done from ?
- Why is [another issue from 2019](https://github.com/tracim/tracim/issues/2284) on same subject is still open and not replied ?

**/// WARNINGS DETAILS ///**

**WARNING in asset size limit:** The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance. 
Assets:  
tracim_frontend_lib.lib.js (754 KiB) 
	
**WARNING in entrypoint size limit:** The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance. 
Entrypoints: 
lib (754 KiB) 
tracim_frontend_lib.lib.js 
	 
**WARNING in webpack performance recommendations:**
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application. 
For more info visit https://webpack.js.org/guides/code-splitting/ 
Script ended at 14:38:15 

**WARNING in asset size limit:** The following asset(s) exceed the recommended size limit (244 KiB). 
	This can impact web performance. 
	Assets:  
	tracim_frontend_lib.optimized.lib.js (504 KiB)

**WARNING in entrypoint size limit:** The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance. 
	Entrypoints: 
	lib (504 KiB) 
	tracim_frontend_lib.optimized.lib.js 
	  
**WARNING in webpack performance recommendations:**
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application. 
For more info visit https://webpack.js.org/guides/code-splitting/ 
Script ended at 14:38:48 
  
Regards,

**Comment by raphj** [comment]
These warnings are intended for the developers, you don't need to worry about them. They are known issues, and expected. They don't prevent Tracim to run correctly.

**Comment by Keepshango** [comment]
Thank U
