### ISSUE TITLE
Feat: Update space description display

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4333]
## Feature description and goals

The space title and description will change its display only at dashboard page.

- [x] Add "About Space" title
- [x] Add a _offWhite_ background with a _grey_ border
- [x] Put the "Open advanced Dashboard" button inside this block and change its label to "Space Settings"
- [x] The description should have _fontColor_ and should be 10px away from the other elements (borders, buttons)

## Interface
_Obs: This interface example is only a template, not everything will be developed in this issue and some details can be changed according to the implementation._
![Group 51](https://user-images.githubusercontent.com/35422692/112343638-9cac9700-8cc3-11eb-81bb-f049e911b833.png)

## Prerequisites

None

## Translations

|English|French|Portuguese|
|-|-|-|
|About Space|À propos de l'espace|Sobre o Espaço|
|Space Settings|Paramètres de l'espace|Definições do espaço|

**Comment by raphj** [comment]
tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
