### ISSUE TITLE
Feat: remove constant CONTENT_NAMESPACE from frontend and use the one from frontend_lib

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#4340]
## Feature description and goals

The constant CONTENT_NAMESPACE is declared twice:
- one in frontend/util/helper.js
- one in frontend_lib/helper.js

The one from frontend_lib has been added last but the refactor would be too much to be done at the time (was during 3.7 dev)

Every usage that needs to be refactored are in frontend/ and there should only be the imports that need to be changed.

## PR
#5931

**Comment by Millefeuille42** [comment]
Done
