### ISSUE TITLE
Bug: Title overflows from its container in the advanced search results

### ISSUE THREAD

**Issue by MariePrandstetter** [tracim/tracim#4341]
## Description and expectations

When a title is too long and has many words (separated by spaces), it overflows its container in the search results.

### How to reproduce

1. Make sure you have the advanced settings on for the search bar
2. Create or rename a content with many words **separated by spaces** (ex: "aaa aaa aaa aaa etc...")
3. Search for this content and see the results

### Version information

- Tracim version: v3.6.0_rc2
- Web browser: any
- Version: any
- Device / System: PC

## Screenshots

![overflow](https://user-images.githubusercontent.com/50776142/112486756-7696fd80-8d7c-11eb-9bfb-6f6b0068783e.png)
________________________________________________

**Comment by raphj** [comment]
tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
