### ISSUE TITLE
Feat: Update right menu on the dashboard

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4353]
## Feature description and goals

- [x] Update role interface to look like the mockup
- [x] Update "Click here to unsubscribe" button to "Email notifications" with a toggle button
- [x] Add request to join space number if pertinent (use subscription endpoint and do a .length())
- [x] Update call-to-action buttons style
- [x] Put member's list, agenda info and webdav info in the right menu

## Prerequisites

None

## Interface
_Obs: This interface example is only a template, not everything will be developed in this issue and some details can be changed according to the implementation._
![menu](https://user-images.githubusercontent.com/35422692/112970389-6dc47400-914e-11eb-9dd2-7b302295136c.png)

## Translations

|English|French|Portuguese|
|-|-|-|
|Your role|Votre rôle|Sua função|
|Email notifications|Notifications par email|Notificações por e-mail|
|{{number}} new requests|{{number}} nouvelles demandes|{{number}} novos pedidos|

**Comment by raphj** [comment]
tested on branch.

**Comment by Skylsmoi** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
