### ISSUE TITLE
Feat: Allow to edit and delete comment

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#4367]
## Feature description and goals

Allow to edit and delete comment.
- [X] verify delete endpoint and add put endpoint for comment in backend
- [x] Change access rules for edit/delete comment (and delete reactions ?)
- [x] adapt frontend to allow using these features
  - add dropdown menu at comments with both options
  - put all the logic in appContentFactory
  - open a popup to edit

```
DELETE /api/workspaces/{workspace_id}/contents/{content_id}/comments/{comment_id}
204
PUT /api/workspaces/{workspace_id}/contents/{content_id}/comments/{comment_id}
{
  "raw_content": "<p>This is just an html comment !</p>"
}
200 return content like POST
```
## Prerequisites

None

## Discussed 

:heavy_check_mark: Access rules for delete/update.
I suggest to keep the existing one for delete:
```
can_delete_comment = OrAuthorizationChecker(
    AndAuthorizationChecker(is_contributor, is_comment_owner), is_workspace_manager
)
```
validated see : https://github.com/tracim/tracim/issues/4367#issuecomment-810175311

## Implemented feature
https://github.com/tracim/tracim/pull/4374

```
Backend:
- add endpoint to edit existing comment
- add backend test for edit existing comment endpoint.
```

**Comment by inkhey** [comment]
after discussion with @gbonaspetti, we decide to keep same rules as existing (a reader can not edit/delete his own comment or reaction, case which happened if he was previously a contributor), if we decide to change it, we do need to think about consistency of readers rights (clear limit between what is allowed or not for reader).

**Comment by MariePrandstetter** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
