### ISSUE TITLE
Feat: Add an endpoint to preview links 

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4371]
## Feature description and goals

Add a `GET /api/url-preview?url=https://example.org/...` endpoint to provide an URL previewer.
 - [x] the `url` parameter will be URL-encoded
 - [x] output:
   ```json
   {
      "title": "Welcome to Example.org",
      "description": "This is an example website, suitable for... well, example URLs",
      "image": "https://example.org/favicon.png"
   }
   ```
 - [x] Possible errors:
   - timeout (suggestion: 502)
   - error from the previewed website: 502
   - ~~no preview (suggestion: 404)~~ (return object with null everywhere as webpreview lib return)
 - [x] Shall be accessible to authenticated users
 - [x] Integrate cache mecanism
 - [x] Add timeout config param

Suggested library: https://pypi.org/project/webpreview/

## Implemented solution:
https://github.com/tracim/tracim/pull/4378
```
Backend:
- `GET /api/url-preview?url=https://example.org/...` endpoint for url preview
- url preview generator using webpreview librairie.
- simple beaker memory 30min cache for url preview
- configurable timeout for fetching preview from external url.
- automated tests
```

**Comment by Skylsmoi** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
