### ISSUE TITLE
Feat: Improve some aspects of the new login page

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4375]
## Feature description and goals

The customizable login page (#4310) could be improved on some aspects:

- ~~[ ] default text which is a "lorem ipsum…": decide on a default text with links/Tracim presentation/… and replace it~~ => will be addressed in #4561
- [x] the docker image should export the whole `branding` folder instead of selected files.
- ~~[ ] responsive behavior: currently the welcome page is displayed after the login form on screens smaller than medium size and it has a white space in the end~~ => will be addressed in #4550
- ~~[ ] add the possibility to translate the welcome page.~~ => will be addressed in #4324

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
