### ISSUE TITLE
Feat: Add a user favorite contents page

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4376]
## Feature description and goals

Allowing a user to keep a favorite contents list is useful for him to keep track of some contents he is interested in.

- [x] Add a favorite icon in content apps: clicking on it will add/remove the content to/from the favorites list
- [x] Add a favorites page accessible through a link in the sidebar
- [x] Clicking on the favorite icon of a item of the favorites shall remove it from this list
- [x] The favorite filter will be implemented later, do not do it in this issue.

## Interface 

![my_favorites](https://user-images.githubusercontent.com/51887114/113003650-387e4d00-9173-11eb-8eec-37ef9d5a9203.png)

## Implementation

- [x] check whether re-using all or parts of the search result list item is possible
- [x] content apps will request the favorites list to know whether their opened content is a favorite or not
- [x] the frontend route will be `/ui/favorites`
- [x] the favorite icon is `fas fa-star` from font-awesome (and its variation `far fa-star` for "not favorite content")

**Comment by Skylsmoi** [comment]
Some added info
- Don't implement the filter from the mock up
- The star will be from font awesome icon
- The frontend route will be ui/favorites

**Comment by inkhey** [comment]
tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
