### ISSUE TITLE
Bug: "X's role has been changed to R" in the spaces' recent activities when X (un)subscribe from/to mail notifications

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4382]
## Description and expectations

When a user subscribes to / unsubscribes from mail notifications, an entry "X's role has been changed to R" incorrectly appears in the spaces' recent activities. refreshing the page makes it disappear.

### How to reproduce

1. As a space manager, go to the dashboard of a space
2. unsubscribe from / subscribe to the mail notifications
3. notice the new entry in the recent activities

### Version information

- Tracim version: 3.X, 3.7

## Diagnostic

The related TLMs should probably be filtered out if the role has not actually changed.

**Comment by gbonaspetti** [comment]
Fixed at #4423
