### ISSUE TITLE
config: 

### ISSUE THREAD

**Issue by Keepshango** [tracim/tracim#4383]
Hello,

Proceeding to configuration mostly from a file rather than from a UI remains to date a challenge to me (english not being my native language)…! Reasons why I have some **uncertainties upon what value is expected for Caldav setting**, particularly for uncommented **text in bold in below string**! Is it yes, no, a number, or a name ?

caldav.radicale_proxy.base_url = https://localhost:5232

// // // Radicale config // // //
// // those params are same as in config file of radicale but syntax
// // is different.
// // use syntax:
// // ```

**caldav.radicale.section.param_name = value**

// // ```
// // instead of radicale.ini syntax:
// // ```
// //    [section]
// //     param_name = value
// // ```

**I left as default all next settings in same Caldav config section….**

Regards,

**Comment by raphj** [comment]
https://github.com/tracim/tracim/issues/4384
