### ISSUE TITLE
config: help upon caldav settings

### ISSUE THREAD

**Issue by Keepshango** [tracim/tracim#4384]
Hello,

Proceeding to configuration mostly from a file rather than from a UI remains to date a challenge to me (english not being my native language)…! Reasons why I have some **uncertainties upon what value is expected for Caldav settings**, particularly for uncommented **text in bold in below string!** Is it yes, no, a number, or a name ?

caldav.radicale_proxy.base_url = https://localhost:5232

// // // Radicale config // // //
// // those params are same as in config file of radicale but syntax
// // is different.
// // use syntax:
// // ```

**caldav.radicale.section.param_name = value**

// // // // instead of radicale.ini syntax: // //
// // [section]
// // param_name = value
// // ```

**I left as default all next settings in same Caldav config section**….

Regards,

**Comment by raphj** [comment]
Hello @Keepshango

What are you trying to do? Do you have some specific requirements with respect to CalDAV/the calendar?

The section you are citing is an example of configuration format, not actual configuration parameters.

As a general rule, you only need to change settings / set parameters for things you which to configure. Do not set all the settings all by yourself for things you don't specifically want to configure: keep these parameters commented and only change what you need. 

You only need to configure and enable CalDAV if you care about agendas in Tracim.

**Comment by Keepshango** [comment]
To date, there is nothing that I especially want to configure for Caldav whose I wish it to run the standard way.
Does leaving above and  below settings as default match such expectation ?

caldav.radicale.server.host = localhost:5232
caldav.radicale.auth.type = None
caldav.radicale.rights.type = None
caldav.radicale.web.type = None
caldav.radicale.storage.type = multifilesystem
caldav.radicale.storage.filesystem_folder = %(basic_setup.caldav_storage_dir)s

**Comment by raphj** [comment]
Yes, but be sure to run the radicale service as per the documentation.

**Comment by Keepshango** [comment]
Understood, thanks.
