### ISSUE TITLE
Feat: Add a button to create publications in the dashboard

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4387]
## Feature description and goals

This button shall redirect the user to the publications.

## To discuss

- Where should the button go? (if it should go to the list of action buttons, in which order should it appear ?)

## Translations

- En: Publish some information
- Fr: Publier une information
- Pt: Publicar uma informação

**Comment by gbonaspetti** [comment]
Tested during integration.

**Comment by PhilippeAccorsi** [comment]
Done.
