### ISSUE TITLE
Feat: Allow to open file uploaded in a comment as a content

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4401]
## Feature description and goals

Have a "open as a content" option in the comment actions  menu.

![Capture d’écran de 2021-04-02 10-08-19](https://user-images.githubusercontent.com/35422692/113396244-7fe72200-939b-11eb-8fb6-a6055b182505.png)

## Prerequisites

#4367

**Comment by grignards** [comment]
- I'm unsure whether it comes from this PR, but the positioning of the text comment information in publication is not good:
![image](https://user-images.githubusercontent.com/51887114/113415278-2a247100-93bf-11eb-9627-a13778fc0d5b.png)
- The menu's entry text is the standard one whereas the menu entries of root published contents (not comments/children) are in small font size.
- The menu opens on the left side wheres the "same" menu opens on the right side for root published contents.

**Comment by gbonaspetti** [comment]
> * I'm unsure whether it comes from this PR, but the positioning of the text comment information in publication is not good:
>   ![image](https://user-images.githubusercontent.com/51887114/113415278-2a247100-93bf-11eb-9627-a13778fc0d5b.png)

Yes, a problem during the merge conflicts fix. Fixed.

> * The menu's entry text is the standard one whereas the menu entries of root published contents (not comments/children) are in small font size.

Yes, it was already like that, I just haven't changed

> * The menu opens on the left side wheres the "same" menu opens on the right side for root published contents.

Fixed

**Comment by grignards** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
