### ISSUE TITLE
Bug: tracimcli db init does not stamp head

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4404]
## Description and expectations

`tracimcli db init` creates a new database but does not stamp it, leading to failures when running migrations.

There are no cases where we need an unstamped database. We shall make tracimcli call alambic to avoid this.

### How to reproduce

1. `cd backend; rm tracim.sqlite; source env/bin/activate`
2. `tracimcli db init`
3. `./run_dev_backend.sh`

### Version information

- Tracim version: v3.X

## Implemented solution:
- add stamp head in tracimcli db init
- remove migrate versions table in tracimcli db delete

**Comment by grignards** [comment]
Tested on branch.

**Comment by inkhey** [comment]
need to be verified with preprod environnement (properly generated database).
