### ISSUE TITLE
Feat: Add Router to appFeature

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4406]
## Feature description and goals

For now, we can't use `<Link>` in the appFeatures because it doesn't have a Router.
As in the appFullscreen, we should wrap the component in index.js with a Router and a history props.
Example:

```jsx
<Router history={data.config.history}>
  <File data={data} />
</Router>
```

## Prerequisites

None

**Comment by raphj** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
