### ISSUE TITLE
Feat: display unavailable content as unavailable in the recent activities

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4415]
## Feature description and goals

For unavailable contents, the activity item shall:
 - [X] show "this content is unavailable" in italic
 - [X] hide the dropdown menu containing the copy link and open as content actions
 - [X] hide the reactions

**Comment by gbonaspetti** [comment]
Tested during integration.

**Comment by PhilippeAccorsi** [comment]
Done.
