### ISSUE TITLE
Bug: Members sometimes appear twice

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4430]
## Description and expectations
Members sometimes appear twice int the member list in the dashboard.

This is sporadic and we don't know how to reproduce yet. Probably by adding and removing members, possibly from another account.

![memberstwice](https://user-images.githubusercontent.com/3817365/114355558-e6c0c400-9b6f-11eb-85db-0c7e9de3e53c.png)

### Version information

- Tracim version: v3.X (starting before v3.6)

## Diagnostic and implemented solution

2021-05-19: The `workspace_member.created` TLM was handle two times in Redux (addWorkspaceMember) for the connected user:
- `handleTlmMemberCreated` function at `tracim/frontend/src/container/Sidebar.jsx`
- `handleMemberCreated` function at `tracim/frontend/src/container/ReduxTlmDispatcher.jsx`
I deleted `addWorkspaceMember` from `Sidebar.jsx` and to make sure that the list doesn't contain any duplicated members, I added a `uniqBy` function in the reducers `currentWorkspace.js` and `workspaceList.js`.

**Comment by MariePrandstetter** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
