### ISSUE TITLE
Bug: Missing max-width on translated comments

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4431]
## Description and expectations

![missingmaxwidth](https://user-images.githubusercontent.com/3817365/114359729-8f712280-9b74-11eb-9bc2-cc96d6ef38d2.gif)

### Version information

- Tracim version: v3.7

## Linked PR
PR #5287

**Comment by knodelle** [comment]
tested on branch

**Comment by knodelle** [comment]
done
