### ISSUE TITLE
Feat: Add emojis to comments and notes (advanced edition or not)

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4436]
## Feature description and goals
The same way we can react with an emoji, it would be nice to allow the user to add emojis in comments. 

We use Tinymce for advanced edition and there are plugins that exists that adds emojis in tinymce. 
Example: 
- https://jsfiddle.net/wpd2umt0/1/ (https://github.com/GeekJosh/tinymce-emoji)
- https://www.tiny.cloud/docs/plugins/opensource/emoticons/

Suggestion: reuse emoji-mart so we don't have to embed and manage two different emoji picker, and the experience is unified for the user.

## Prerequisites

None

**Comment by raphj** [comment]
Actually, I think we could also allow this in simple text edition and it should not be difficult to do, what do you think @gbonaspetti ?

**Comment by inkhey** [comment]
see also https://github.com/tracim/tracim/issues/2399

**Comment by raphj** [comment]
Be careful of the fonts used in Tracim when implementing this, this can be a bit tricky: https://github.com/tracim/tracim/issues/3479#issuecomment-747497120

See also https://github.com/tracim/tracim/issues/4517

**Comment by Haskaris** [comment]
Fixed in #6006 in advanced edition, #6058 will fix in simple edition.
