### ISSUE TITLE
Bug: New line added automatically when using advanced edition

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4437]
## Description and expectations

When the advanced edition is open, a new line is added in the end of the content. This line should be "strip()".

Please consider https://github.com/tracim/tracim/issues/4407 

### How to reproduce

1. Edit a note

### Version information

- Tracim version: v3.1
- Web browser: any
- Version: any
- Device / System: any

________________________________________________

## Diagnostic

See `frontend/src/util/tinymceInit.js` and https://github.com/tracim/tracim/pull/3445

## Related PR
PR #6058

**Comment by raphj** [comment]
See also https://github.com/tracim/tracim/issues/4407
