### ISSUE TITLE
Bug: Wrong modification type when delete or modify comment

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4441]
## Description and expectations

If I delete or modify a comment, the type of modification in recent activities is "commented X minutes ago".

### How to reproduce

1. Delete a comment
2. See this space recent activities

### Version information

- Tracim version: v3.8
- Web browser: any
- Version: any
- Device / System: any

________________________________________________

## Diagnostic

Better handle the TLMs `content.comment.modified` and `content.comment.deleted`

## Prerequisites

None

## Implemented solution

This modifications will be ignored, but they will appear on the "hidden" menu of the last modifications as "comment modified/deleted" (to have always 5, with a simple solution).

**Comment by raphj** [comment]
tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
