### ISSUE TITLE
Bug: Actions are not blocked on deprecated / closed publications

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4456]
## Description and expectations

Action lead to errors. They should be blocked. Beware not to block emoji reactions though.

### How to reproduce

1. Mark a publication as deprecated
2. do something in the publication, like comment or attach a file

Backend issue: https://github.com/tracim/tracim/issues/4511

### Version information

- Tracim version: v3.8

**Comment by Sarah-Pelle** [comment]
Fix, we keep reactions (emoji)
