### ISSUE TITLE
Feat: Error 500 in some cases when a link preview fails

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4459]
## Feature description and goals

- link: `https://news.google.com/articles/CAIiEPd184uy0Qsya4-i_jaLIfQqGQgEKhAIACoHCAow2_b2CjDm8NUCMMua2gY?hl=fr&gl=FR&ceid=FR%3Afr`
- Error 500: `('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check',))`
- This link works in Mattermost

Observed in a publication comment.

Related: https://github.com/tracim/tracim/issues/3898

**Comment by inkhey** [comment]
Try it locally, does work. don't know if fixed since or something else. Can not reproduce the issue.
@raphj can you check this ?

**Comment by raphj** [comment]
I confirm it works.
