### ISSUE TITLE
Bug: putting a table as a description of a space displays a large blank before

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4462]
## Description and expectations

Putting a table in a description of a space (advanced HTML edition) displays a large blank space before it.
See https://github.com/tracim/tracim/pull/4335#issuecomment-809452480

### How to reproduce

1. Go to a space that you are Space manager
2. Edit the description adding a table
3. Save the new description and see its display

### Version information

- Tracim version: at least 3,8
- Web browser: any
- Version: any
- Device / System: at least PC

## Screenshots

![Capture d’écran de 2021-04-12 16-20-02](https://user-images.githubusercontent.com/35422692/114409685-fc9faa80-9baa-11eb-9aa2-01b5d9e2a67b.png)

________________________________________________

## Prerequisites

None

**Comment by raphj** [comment]
:warning: the fix breaks existing workspace descriptions that have not been written with tinyMCE: new lines will disappear. A migration would be needed to keep them.

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
