### ISSUE TITLE
Bug: @all mention translation (to @tous in French) does not work without to change language

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#4463]
## Description and expectations

With the user interface is configured to be in Spanish, when I start a mention by typing a `@`, the mention proposed for group mention is `@all`; I expect `@todos`.

### Version information

- Tracim version: 4.3.0
- Web browser: Google Chrome
- Device / System: PC / Linux

-----
## Diagnostic
**Already implemented fixes:**

- frontend_lib doesn't have a set for i18n language (so it sets only when the language is changed or in frontend_app_* constructors, but nothing to frontend)
- frontend_app_* and frontend have a different wording for user object (technical debt issue: #749)

**Still existing problems:**

- It still has an asynchrony problem. When the function `getMatchingGroupMentionList` (frontend_lib/src/mentionOrLink.js) is called, i18n does the translation before it has the user language and then it uses fallbacks (browser language or English). We couldn't identify why the bug appeared the moment another language was added (#5777).

## Related PR
PR #6058

**Comment by MariePrandstetter** [comment]
I'm not able to reproduce, locally and in our instance

**Comment by PhilippeAccorsi** [comment]
I have sometime the same error. I need to choose @all instead of @tous.

**Comment by raphj** [comment]
I reproduce on our instance, but not locally. Some code must be run at a different order for some reason. I'll take a look

**Comment by PhilippeAccorsi** [comment]
I have seen this error in last 2min

![Screenshot 2021-08-19 at 15-14-48 Publications · 👯‍♀️ Equipe · Algoo](https://user-images.githubusercontent.com/25848257/130075104-7147a102-ef15-4f43-bdcb-063e691f2618.png)

**Comment by MariePrandstetter** [comment]
tested on branch

**Comment by gbonaspetti** [comment]
As pointed at https://github.com/tracim/tracim/issues/5777#issuecomment-1185475680 the bug come back when we add a new language. We need to refactor this code.

**Comment by lebouquetin** [comment]
What is the reason for this bug to appear again? Did you identify the source code responsible for it?

**Comment by gbonaspetti** [comment]
> What is the reason for this bug to appear again? Did you identify the source code responsible for it?

According to our diagnosis, it is an asynchrony problem. i18n does the translation before it has the user language and then it uses fallbacks (browser language or English). We couldn't identify why the bug appeared the moment another language was added, but we know in which part of the code it is happening. I'll update the description to add all this information.
