### ISSUE TITLE
Feat: Add link preview in publications

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4468]
## Feature description and goals

Maybe address this feature by using the Comment component there.

## Version

Tracim v3.8

**Comment by raphj** [comment]
Test:
 - if publication work
 - if comments in apps work

**Comment by lebouquetin** [comment]
Bruno asked a few days ago about Youtube preview not working. @raphj I'd like you to investigate this in the same issue.

**Comment by raphj** [comment]
> Bruno asked a few days ago about Youtube preview not working. @raphj I'd like you to investigate this in the same issue.

This has been fixed by @grignards in #4470

**Comment by lebouquetin** [comment]
I missed this. Perfect 👍

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by gbonaspetti** [comment]
> > Bruno asked a few days ago about Youtube preview not working. @raphj I'd like you to investigate this in the same issue.
> 
> This has been fixed by @grignards in #4470

@lebouquetin to be explicit, we have just an image preview, we can not play the video.

**Comment by PhilippeAccorsi** [comment]
Done.
