### ISSUE TITLE
Bug: Link preview does not work with Youtube and Google

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4470]
## Description and expectations

![image](https://user-images.githubusercontent.com/3817365/114519963-36bb8b80-9c41-11eb-9e3e-fe1c3fa938fd.png)

~~For YouTube, we might need an API key.~~

### Version information

- Tracim version: v3.8

## Diagnostic

The link previewer in the backend receives a cookie banner (since it's European).

A workaround is to include a value for the consent cookie used by youtube/google.

Reference: https://stackoverflow.com/questions/66934826/accept-cookies-consent-from-youtube

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
