### ISSUE TITLE
Feat: Handle dashboard display on small screens

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4473]
## Feature description and goals

For now, the dashboard on small screens looks like this:
![RMBYvg1](https://user-images.githubusercontent.com/35422692/114519051-4be3ea80-9c40-11eb-9dcf-13b9329c8e32.png)

And it should look more like this:
![space_homepage_mobile](https://user-images.githubusercontent.com/35422692/114523128-4ee0da00-9c44-11eb-80f9-98cc92ad7a85.png)

Note: the mockup it's just an exemple, the development will not handle all details right now.

### Version information
- Tracim version: 3.8.0 

## Prerequisites

None

## Implemented solution
Things there are different from the mockup:
- Still have the Space settings button
- Still have the text "Your role:" for the role
- Don't have the "next events"
- The action button icons are the same as on big screens (without the +)
- The order is: "about space", "recent activities" and the menu
- The titles, the member's list, the agenda information and the webdav information remains the same

**Comment by raphj** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
