### ISSUE TITLE
Bug: Can't remove a favorite if the related content is unavailable

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4483]
## Description and expectations

We get: `Content "17194" not found in database`

### How to reproduce

1. Favorite a content in a space
2. leave this space
3. try to remove the favorite

An alternative version exist if the space is deleted (#4444):

1. Favorite a content in a space
2. delete the space
3. try to remove the favorite

### Version information

- Tracim version: 3.8

## Implemented solution:
https://github.com/tracim/tracim/pull/5042
- delete by favorite by content_id instead of by content objet in order to work in all specific case (space deleted, content deleted) in internal lib
- add tests to check all the specific cases around deleting existing favorite link to a non accessible content.

**Comment by charline-rageade** [comment]
@inkhey what is the status of this development ? Can I put this ticket in Tracim 4.1 ?

**Comment by inkhey** [comment]
@charline-rageade yes. done.

**Comment by knodelle** [comment]
done
