### ISSUE TITLE
Bug: the WebP image formats seems to have broken previews.

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4494]
## Description and expectations

Some HTTP clients do upload webp image with an unexpected mimetype which leads to have a broken preview for the files which were uploaded.
This has been seen during avatar tests with the `httpie` client.

### How to reproduce

1. Go to…
2. Click on…
3. Scroll down to…

### Version information

- Tracim version: [e.g. v2.7, Mon Tracim]
- Web browser: [e.g. Google Chrome, Firefox, Safari]
- Version: [e.g. 22, latest]
- Device / System: [e.g. PC, iPhone 6]

## Screenshots

________________________________________________

## Implemented solution
#5121 
- update to preview-generator 0.28 + webp package add support for webp.

**Comment by gbonaspetti** [comment]
Done
