### ISSUE TITLE
Bug: E-mail not 100% translated (half French, half Portuguese)

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4502]
## Description and expectations

For portuguese as chosen language, I have the e-mail:
```
Olá X,

Vous avez invité 1 personne(s) à téléverser des fichiers dans cet espace Y :

    X nesse link: W

Esse upload é protegido por essa palavra-passe: "Z"

Aproveite o seu dia :)

Suricato, o seu assistente digital
```
that has a french part on it.

### Version information

- Tracim version: v3.8
- Web browser: Google Chrome
- Device / System: PC

## Translation
`Vous avez invité 1 personne(s) à téléverser des fichiers dans cet espace Y :` = `Convidou 1 pessoa(s) a carregar ficheiros no espaço Y:`

________________________________________________

## Prerequisites

None

**Comment by inkhey** [comment]
I don't reproduce the issue. i get this locally:

> Olá Global manager,
> 
> Você convidou 1 pessoas a carregar ficheiros neste espaço test_espace:
> 
>     toto@toto.toto nesse link: http://localhost:7999/ui/guest-upload/6b73adcb-69ce-438c-b10c-f469758b4a61
> 
> Aproveite o seu dia :)
> 
> Suricato, o seu assistente digital

I suspect a previously missing translation or simply the fact that backend translation were not properly updated.

**Comment by PhilippeAccorsi** [comment]
Can you check if it is a missing translation key in tracim 3.8 ?

**Comment by inkhey** [comment]
@gbonaspetti is this issue still relevant ?

**Comment by gbonaspetti** [comment]
Fixed
