### ISSUE TITLE
Bug: The "open as content" option in comments always opens in the same tab

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4508]
## Description and expectations

The "open as content" option in the action menu in comments always opens in the same tab, there is no way to open in a new tab or window.
It works for the same option in publications and recent activities.

### Version information

- Tracim version: v3.8
- Web browser: Google Chrome
- Device / System: PC

________________________________________________

## Prerequisites

None

**Comment by Sarah-Pelle** [comment]
Won't fix
