### ISSUE TITLE
Bug: No preview for thread when first comment is an image

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4510]
## Description and expectations

When the first comment of a thread is an image, on recent activities we have as preview "empty thread".

### How to reproduce

1. Create a thread
2. Comment with an image added on advanced edition
3. See recent activities feed

### Version information

- Tracim version: v3.8
- Web browser: Firefox
- Device / System: PC

## Screenshots

![6kUTne3](https://user-images.githubusercontent.com/35422692/114567567-a480ab00-9c73-11eb-8ca1-597d1e3ed4f4.png)

________________________________________________

## Prerequisites

None

**Comment by Sarah-Pelle** [comment]
fix
