### ISSUE TITLE
Bug: The prompt message "notify all" is displayed for contents in a non-editable state

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4512]
## Description and expectations

The prompt message "notify all" is displayed for contents in a non-editable state (obsolete/validated/...). We have a flash message "You must change the status or restore this content before any change" if we try to notify, the prompt message is closed and even if we change the status it does not reappear.

### How to reproduce

1. Go to a content
2. Modify it
3. Change it status on validated
4. Click to notify all

### Version information

- Tracim version: v3.8 (probably before)
- Web browser: Google Chrome, Firefox
- Device / System: PC

________________________________________________

## Prerequisites

None

**Comment by Sarah-Pelle** [comment]
Won't fix
