### ISSUE TITLE
Feat: "Sort by" favorites

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4513]
## Feature description and goals

Change the default order on backend to sort favorites by name.

### Version
Tracim 3.8

## Prerequisites

None

**Comment by grignards** [comment]
This also can be a change in the default sort order in the backend.

**Comment by gbonaspetti** [comment]
The frontend part was made at #6030

**Comment by Sarah-Pelle** [comment]
Closed in #6030 
The decision has been taken to do it in the frontend only
