### ISSUE TITLE
Bug: The public profile page does not handle very long public names

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4521]
## Description and expectations

The display of the name is not limited in length, leading to an horizontal overflow in the page.
The text should have a `…` overflow when it's too long.

### How to reproduce

1. Change a user display/public name to a very long one (~200 characters)
2. Go to his public profile page

### Version information

- Tracim version: 3.8 (build_41)

## Screenshots

________________________________________________

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by MariePrandstetter** [comment]
Done
