### ISSUE TITLE
Feat: Add box shadow around file content preview

### ISSUE THREAD

**Issue by MariePrandstetter** [tracim/tracim#4532]
## Feature description and goals

Add box shadow around file preview in recent activities 

![square](https://user-images.githubusercontent.com/50776142/114726477-b7f84880-9d3d-11eb-92f7-ed9dbf6a5d9a.png)

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
