### ISSUE TITLE
Feat: Be able to fold the subspaces in the sidebar

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4537]
## Feature description and goals

The subspaces in the sidebar are always shown (see image below). That can be a problem if you have a lot of spaces.
![Screenshot from 2021-04-15 10-49-24](https://user-images.githubusercontent.com/35422692/114841594-50dba200-9dd8-11eb-991d-6785d7522897.png)
To be able to fold the subspaces:
- [x] Update interface, only a space that has subspaces will have the [caret icon](https://fontawesome.com/icons/caret-down)
- [x] The [caret icon](https://fontawesome.com/icons/caret-right) should be clickable and it will hide/show the subspaces. It should have a tooltip 'Hide/show subspaces'
- [x] The other places should continue with the same functions, i.e. clicking on the name of the space should open it
- [x] For the first version, all spaces will be show by default, the state is not saved and it's relative to the current tab

## Interface
- Details of what will be changed in this issue
![Screenshot from 2021-04-15 10-58-27](https://user-images.githubusercontent.com/35422692/114842922-9b115300-9dd9-11eb-9611-7ee8f3eac1cc.png)
- Overall view (not everything will be implemented)
![Full sidebar](https://user-images.githubusercontent.com/35422692/114842915-99478f80-9dd9-11eb-9ba3-48c2f0d696b3.png)

## Prerequisites

None

**Comment by grignards** [comment]
A small remark after my tests: the whole sidebar item has a `cursor: pointer` rule, I think it could be removed as some zones in the item (under/over the folding button) are not clickable and the clickable zones (the button, the link and the popup menu) do already define `cursor: pointer` directly.

**Comment by grignards** [comment]
Tested on branch.

**Comment by PhilippeAccorsi** [comment]
Done.
