### ISSUE TITLE
Feat: Add terms and conditions validation

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4539]
## Feature description and goals

When a user signs in for the first time on the login page, he/she should have to click on a checkbox where he/she is informed about the general terms and conditions of use, which are also available at this location.

- [x] For the first time that the user tries to connect the "Sign in" area is replaced by a check list for each document that needs validation, if there is. Example:
![lgpage](https://user-images.githubusercontent.com/35422692/116211263-eb76a200-a743-11eb-827e-f14d33dd5ce7.png)
- [x] The cancel button cancels the login and stays in the login page
- [x] The validate button is enabled only if all options are checked
- [x] Clicking on the document name opens the document in another tab (:warning: see the comment https://github.com/tracim/tracim/issues/4539#issuecomment-823693996 for the right way to implement this issue)

## Translations

|English|French|Portuguese|
|-|-|-|
|In order to start using our platform, you must be aware of our conditions.|Afin de commencer à utiliser notre plateforme, vous devez prendre connaissance de nos conditions.|Para começar a utilizar a nossa plataforma, deve estar ciente das nossas condições.|

## Prerequisites

None

### Backend 
- Add a `website.usage_conditions` parameter in `development.ini`. This parameter will be a list of filenames separated by `,`. The filenames will be relative to the `frontend/dist/assets/branding` folder.
- Add a GET `/api/system/usage_conditions` API, only accessible to logged users which returns a list composed of the basename + website urls to the configured `website.usage_conditions` parameter:
```json
"items": [
  { "title": "My conditions", "url": "https://mytracim.fr/assets/branding/My%20conditions.pdf" }
]
```
The `title` attribute will be the `basename()` of the file without its extension.
:warning: do not forget to url-encode the file name in the `url` parameter.

### Frontend

Upon successful login via the API:
- retrieve the list of documents through `/api/system/usage_conditions`.
- retrieve the acceptance status in `/api/users/{user_id:\d+}/config`, the status will be stored in the `usage_conditions__status` key.
- if the list is not empty and the status not equal to `accepted`, display it as described in the functional section above.
- when the conditions are accepted, set the value of `usage_conditions__status` to `accepted` in `/api/users/{user_id:\d+}/config` before switching to the homepage.

**Comment by grignards** [comment]
Won't that make many popups when a user logs for the first time? First the terms and conditions, then the username setting?

**Comment by grignards** [comment]
"stays in the homepage": does that mean that Tracim will be usable after cancelling or not? BTW if it should not be possible to use Tracim without agreeing to those conditions, putting this page after the login is a weak protection.

**Comment by gbonaspetti** [comment]
> "stays in the homepage": does that mean that Tracim will be usable after cancelling or not? BTW if it should not be possible to use Tracim without agreeing to those conditions, putting this page after the login is a weak protection.

In this case, homepage = login page. I'll change the description to be more clear.

**Comment by gbonaspetti** [comment]
> Won't that make many popups when a user logs in for the first time? First the terms and conditions, then the username setting?

Another idea is to replace the "Sign in" area. What do you think @grignards @lebouquetin
![Capture d’écran de 2021-04-19 12-54-32](https://user-images.githubusercontent.com/35422692/115225663-a1236e80-a10e-11eb-957a-62ef4edb9a35.png)
 ?

**Comment by grignards** [comment]
Again some questions/remarks:
- how is defined the names "terms and conditions"/"privacy policy" in the interface? Should they be translatable?
- integrating the document in a Tracim popup limits the document formats possibilities: for example a pdf document wont' directly be possible I think. An alternative would be to have a link to a new tab/window.

**Comment by lebouquetin** [comment]
> how are defined the names "terms and conditions"/"privacy policy" in the interface? Should they be translatable?

This is the filename. No need to be translatable.

> integrating the document in a Tracim popup limits the document formats possibilities: for example a pdf document wont' directly be possible I think. An alternative would be to have a link to a new tab/window.

Good suggestion. This is what facebook does (open in new tab/window). But how would be encpasulated the terms and conditions?

I think allowing html, pdf, docx etc is very extensible and allows tracim managers to do "like they want". In another way, force to encapsulate terms and conditions in the design make the software more "professionnal"

**Comment by lebouquetin** [comment]
Actually, opening the document in another tab/window is similar to my last suggestion except that it allows to clearly stay on the page, which is better i think (do you agree?)

**Comment by grignards** [comment]
> > Won't that make many popups when a user logs in for the first time? First the terms and conditions, then the username setting?
> 
> Another idea is to replace the "Sign in" area. What do you think @grignards @lebouquetin

You mean to display the terms and conditions in the login page just after the login? Seems good to me, with the question of how to handle the case of "changed conditions to revalidate".

**Comment by lebouquetin** [comment]
> We cannot ensure PDFs will be handled correctly. A web browser does not necessarily handles them, and showing them in an iframe might not work, or not work uniformly, especially on mobile. Should we restrict supported formats to HTML for now and handle more formats later?

Why do you want to restrict by code something you are not sure it wont work for the user? This is over-engineering.

The right way to implement this is to allow the sysadmin (which is responsible to deploy tools that work) to do what he/she wants to do. You can add some warning in the documentation, but I do not see any reason to forbid this.

By the way this question makes the decision more clear: the right way to implement the link to terms and conditions is to put a link in new tab/window like @grignards suggested to the raw content (html, pdf or whatever).

:+1:

**Comment by raphj** [comment]
> Why do you want to restrict by code something you are not sure it wont work for the user? This is over-engineering.

To control the surface area of the features we provide. Handling PDFs is potentially more work, not handling this is the opposite of over-engineering to me. 

This has been discussed before about the fact we are not doing it now, but we'll probably need to ensure in a future development that the user cannot tamper the record that they have accepted the terms.

**Comment by lebouquetin** [comment]
> > Why do you want to restrict by code something you are not sure it wont work for the user? This is over-engineering.
> To control the surface area of the features we provide. Handling PDFs is potentially more work, not handling this is the opposite of over-engineering to me.

So this is more work in order to reduce features. This is a time-losing strategy at this point of development.

> This has been discussed before about the fact we are not doing it now, but we'll probably need to ensure in a future development that the user cannot tamper the record that they have accepted the terms.

At the moment there are no way to ensure terms validation are not tampered, pdf or html or other things.

**Comment by lebouquetin** [comment]
> To control the surface area of the features we provide. Handling PDFs is potentially more work, not handling this is the opposite of over-engineering to me.

Actually, this sentence worry me. We already add a talk about the development strategy which MUST NOT control what is not in the expected area. We MUST do an implementation as generic as possible which match the requested features. It does not implies to refuse other use cases - simply we do not guaranty it would work - we just dont care

**Comment by MariePrandstetter** [comment]
Done
