### ISSUE TITLE
Bug: Libreoffice previews can take forever

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4552]
## Description and expectations

Tracim uses preview generator to compute the previews of its documents. Preview generator in turn uses libreoffice to compute previews for many file formats (including but not limited to office documents).
The process launched by preview generator is not time-limited so it can happen that it takes several minutes to complete.
This, added to the fact that a limit of "one libreoffice process at a time" is implemented can result into blocking all Tracim/uwsgi worker threads to render previews, especially with the new publications and recent activities pages that display many previews.

### How to reproduce

1. Upload a file taking a long time to render in libreoffice (a very big spreadsheet for example).
2. Try to upload another office file
3. The preview of the second file is not done before the first finished.

### Version information

- Tracim version: 3.8-ASF
________________________________________________

## Implemented solutions

- preview-generator 0.16 will integrate a timeout for the libreoffice processes it launches. This is a quick fix until a more general solution can be found and implemented, see https://github.com/algoo/preview-generator/issues/186.
- preview-generator 0.20 fix issue with unkilled children process, see https://github.com/tracim/tracim/pull/4696
- spreadsheet preview are disabled in tracim, see https://github.com/tracim/tracim/pull/4704

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.

**Comment by inkhey** [comment]
In some case (big xlslx file 50mo), Libreoffice process stay alive despite timeout. Current temporary solution is disabling xlsx support by monkey-patching  `LO_MIMETYPES` static variable in` _init_.py` of tracim.
Code need to be reread to find why killing process is failing.

**Comment by inkhey** [comment]
After some research, i found the problem is related to children process which are not killed during sigkill and stay alive. The solution is doing SIGTERM and then SIGKILL if needed to the whole subtree, to ensure there is no children left.
