### ISSUE TITLE
Feat: add label in account setting form

### ISSUE THREAD

**Issue by charline-rageade** [tracim/tracim#4555]
## Feature description and goals

Currently user can change his informations (full name, username and email) in the account settings category. In order to improve readability of this input it would be interesting to : 

1. Add input label in order to specify and guide user for his new entry
2. Propose to user an example of input using the placeholder 

![labelinput](https://user-images.githubusercontent.com/82377347/115401053-419a9100-a1ea-11eb-935f-23ebc41ba629.png)

*Linked to https://github.com/tracim/tracim/issues/3287*

**Comment by charline-rageade** [comment]
WARNING : if the user is also an administrator, he can edit the profile of other users. We must modify also this form.

**Comment by charline-rageade** [comment]
Automatic tests do not seem necessary for this minor modification.

**Comment by MariePrandstetter** [comment]
tested on branch

**Comment by MariePrandstetter** [comment]
Done
