### ISSUE TITLE
Bug: space description included in TLMs, making feed very heavy

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#4557]
## Description and expectations

To do:
 - [x] remove descriptions from workspace objects in TLMs, other than workspace-related TLMs. 
---

A user has a space with pictures in the description. ALL TLMs include some workspace information including the description. It results in very wheighted recent activites feed.

### How to reproduce

1. Insert a picture in the space description
2. create lots of activity on the space (comments, new empty contents)
3. load the dashboard.

Tracim 3.8 dev 

Impacts t least backend, maybe frontend ?

**Comment by grignards** [comment]
In fact the description is also included in `/api/workspaces` response. This implies that the interface can take a very long time to display when loading Tracim as this API is used to display the sidebar. So I'd advocate to also remove `description` from this list (this change would probably have effects on the frontend).

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by MariePrandstetter** [comment]
Done
