### ISSUE TITLE
Feat: move the language dropdown menu into account settings page 

### ISSUE THREAD

**Issue by agile-marmot** [tracim/tracim#4562]
## Feature description and goals

Today, the navbar is too heavy with a lot of buttons. The language dropdown menu can be move to the account setting page in the section "My Account". 

Linked to #[3287](https://github.com/tracim/tracim/issues/3287#issue-651382114)

- [x] Step 1 : 

Remove the language dropdown menu to the navbar
![1](https://user-images.githubusercontent.com/82377347/115519727-c25c9a00-a289-11eb-9396-98085932862f.png)

- [x] Step 2 : 

Add the dropdown menu to the navbar
![img2_](https://user-images.githubusercontent.com/82377347/115519757-c8eb1180-a289-11eb-9adf-ac3c9b726097.png)

## Linked PR
#5458

**Comment by gbonaspetti** [comment]
Pay attention: the pages shown when the user is logged off (for example the login or the "forgot password" pages) must be translatable.

**Comment by knodelle** [comment]
tested on branch

**Comment by knodelle** [comment]
done
