### ISSUE TITLE
Bug: tooltip visible in publication not show the good message to the user (download but its not possible to download)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#4567]
## Description and expectations

On a existing publication, I tried to open link visible in a publication. When I mouseover description I can seen tooltip with wording `Download publication` but if I clic on description, the app thread is opened in a new tab.

### How to reproduce

- create a publication
- mouseover on description of the publication

### Version information

- Tracim version: 3.7.1
- Web browser: firefox
- Version: 
- Device / System: Debian 10

## Screenshots

https://user-images.githubusercontent.com/25848257/115681862-36b03f80-a355-11eb-9c87-2ac14cfee794.mp4

________________________________________________

**Comment by raphj** [comment]
Fixed in 07c9360b52758a5b34d64273de11747d10a71998 and 2e41a0a92255a7bd86590fbb1baa241a7ec661f6

**Comment by PhilippeAccorsi** [comment]
Done.
