### ISSUE TITLE
Feat: Better documentation for TLMs

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4578]
## Feature description and goals

The Tracim Live Message mechanism is another entry point to the Tracim API (through `/api/users/<user_id>/live_messages`). The endpoint is itself auto-documented but is missing:

- the TLM contents depending on the event/entity types (that we have documented internally for now).
- in which conditions a TLM of a given type is created/sent: most TLMs are relatively self-describing (content/…), but an explanation for some details could be useful (for example creating a comment/…).
- who are the recipients of the TLMs

## Implemented solution
https://github.com/tracim/tracim/pull/5388
- Add TLM documentation.
- Add link to this doc in autogenerated api documentation (swagger) for live_messages endpoint.

**Comment by inkhey** [comment]
I created a WIP documentation about TLM, feedback are welcome : https://github.com/tracim/tracim/pull/5388

**Comment by knodelle** [comment]
done
