### ISSUE TITLE
Bug: button "Open the gallery" is displayed even when the galeries are disabled

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#4586]
## Description and expectations

 The display of the button is not conditioned by the setting of the gallery app which can be disabled. So in this case when we click on we have a blank page with a JS console log loop: `gallery does not exist. Maybe it hasn't finished loading yet? Retrying in 500ms`

Expected:
- [x] Not show the button if functionality is disabled

---

  **Original description**
  
  Here is the original description of the issue (in French)
  
  Le bouton "open the gallerie" fait 46px de haut contre 42px pour le bouton create.
  
  ![image](https://user-images.githubusercontent.com/907161/116140325-77061980-a6d7-11eb-8241-718107e95be8.png)
  
  
  à noter que les boutons "create a space" et "join a space" dans la sidebar sont de 42 et 44px de haut
  
  ça serait bien de standardiser. Vous allez me dire "oui mais c'est la bordure", mais en fait je suis utilisateur et je m'attends à ce que tous les boutons aient la même hauteur que ce soit des boutons "call to action" ou "secondary". pour ça, il faut que la border soit intégrée dans le design de l'interface (donc un bouton plein = un bouton plein + bordure standard, et un bouton vide = bouton vide + bordure standard)
  
  aussi, d'après la MR, il me semble que l'affichage du bouton n'est pas conditionné par le paramétrage de l'app galerie qui peut être désactivée. d'après la MR l'affichage est systématique, ce qui est un problème
  
  j'ai voulu tester pour être sûr et réouvrir le ticket le cas échéant mais la procédure d'installation rapide de tracim ne fonctionne pas :
  
  ```
  damien@christophecolomb:~$ mkdir -p ~/tracim/etc
  damien@christophecolomb:~$ mkdir -p ~/tracim/var
  damien@christophecolomb:~$ docker run -e DATABASE_TYPE=sqlite -p 8080:80 -v ~/tracim/etc:/etc/tracim -v ~/tracim/var:/var/tracim algoo/tracim
  Unable to find image 'algoo/tracim:latest' locally
  docker: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
  See 'docker run --help'.
  ```
  (lié à pushpin ?)
  
  faut régler ce bug d'affichage systématique dans la 3.8.1 parce que sinon on ne peut pas mettre à jour l'instance Tracim de [client] qui justement nous a demandé de désactiver la galerie
  
  rappel pour tous les dev: les applications Tracim sont désactivables. L'interface doit avoir le fonctionnement approprié. (Marie a loupé le truc, Raphael aussi, et je pense que les autres n'y ont pas pensé non plus)
  
  -> cas de test auto à prévoir pour vérifier que si l'app n'est pas active le bouton est caché, sinon on va se retrouver probablement de nouveau avec cette régression vu que c'est un cas rare.
  
  C'est ce genre de détail qui va rendre l'équipe efficace ou non ; c'est ce qui fait que les utilisateurs vont avoir une sensation de confort avec l'application ou une impression désagréable mais indéfinissable.

**Comment by lebouquetin** [comment]
Note à propos de docker :

Philippe :

> Pour docker, tu n'est de toute façon pas sur la bonne branche (bonne version du code).
> Mais a priori le souci est pas là.

Moi : 

> j'ai copié l'explication depuis la doc pour lancer tracim
> c'est vrai que j'ai pas réfléchi à ça [que je ne suis pas sur la bonne branche]
> mais dans tous les cas ça ne marchait juste pas

Philippe :

> Oui. Vu l'erreur, cest docker sur ta machine qui semble avoir un souci car il reconnaît ne pas avoir l'image locallement. Cest ensuite docker qui doit faire un pull.

**Comment by lebouquetin** [comment]
I confirm that the behavior is broken:

1. deactivate the galery application
2. go to a workspace home page
3. click on the content tab
4. click on the open galery button
5. the scree keep on being white with a JS log loop: `gallery does not exist. Maybe it hasn't finished loading yet? Retrying in 500ms`
-

**Comment by lebouquetin** [comment]
By the way, in case a user is contributor or reader, the `...` menu of a folder is empty when galery is disabled.
Expected : the menu should not appear when there are no items to put inside.

**Comment by lebouquetin** [comment]
@gbonaspetti I suggesto you split this issue into several sub-issues or refactor it accordign to the understanding you have of the full investigation. We can have a chat about this

**Comment by gbonaspetti** [comment]
@lebouquetin  ok, you already have an issue for the style problems https://github.com/tracim/tracim/issues/4577 
I suggest to live this one only for the activation/deactivation issue and I'll do another for the `...` menu

**Comment by raphj** [comment]
> Vous allez me dire "oui mais c'est la bordure"

I wasn't personaly going to say this.

**Comment by MariePrandstetter** [comment]
Done
