### ISSUE TITLE
Bug: Preview generation is very slow

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#4587]
## Description and expectations

I already told preview generation was slow... I investiguate on my own. Here is the issue about office document preview process being slow - https://github.com/algoo/preview-generator/issues/222

The process does not use the pivot PDF anymore, so libreoffice is executed for every page on every size a preview is required.

I'd like you to investigate what has been done wrong and fix it.

Note: I identified where the issue is from (historicaly)

**Comment by inkhey** [comment]
fix in preview_generator 0.17 solve this issue: https://github.com/algoo/preview-generator/issues/222 .
Please note also, that there still lot of improving in this process:
The pdf to image preview builder using pypdf2 is not as improved as it can be, it does create unnecessary temporary one-page pdf
before creating jpeg preview. This can be solved either by tweaking to force using cached one page pdf (tricky !) or finding a way to use a pdf lib to make preview of only one page directly without making uneeded pdf. Anyway, pypdf2 should be replaced either by poppler or qpdf here (i do think poppler is probably the best choice as this is used in some big software like libreoffice).

**Comment by lebouquetin** [comment]
:warning: requires the 0.18 release of preview-generator - see https://github.com/algoo/preview-generator/issues/222#issuecomment-832729388

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by MariePrandstetter** [comment]
Done
