### ISSUE TITLE
Feat: Configure the color(s) of the sidebar in `color.json`

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4589]
## Feature description and goals

The color(s) used in Tracim's sidebar are not configurable which can disturb as other colors are configurable through entries in `color.json`.

### Backend

- [x] add a `sidebar` entry in `color.json`
- [x] its default value should be `#333`
- [x] make it available to the frontend  + a darken version (15% darken) like the primary color (which is transmitted through a css style defined in `index.mak`)

### Frontend

- [x] use the configured colors to style the sidebar

**Comment by raphj** [comment]
Tested on branch.

**Comment by MariePrandstetter** [comment]
Done
