### ISSUE TITLE
Bug: Recent activities display is too slow

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4590]
## Description and expectations

The display of the recent activities (personal and space) is too slow, we should improve it so that it doesn't take more than 2-3 seconds to display the activities in most cases.

### How to reproduce

1. Go a space's dashboard and look at the recent activities part

OR 

1. Go to the personal activities

### Version information

- Tracim version: 3.7.1
- Web browser: All
________________________________________________

## Diagnostic

There are several reasons to this:

- [x] activities are built using the `/api/users/<user_id>/messages` API. As several messages can all be part of one activity the API has to be called several times (2/3 times in general). To mitigate this we could increase the number of messages which are retrieved (currently 15) to 30/40.
- [x] the `messages` API is especially slow (~ 500ms delay) when filtering messages for the space activities. This is probably because the database lacks the appropriate index in this case (:warning: the data to index is *in* the JSON column of `events`).
~~- [ ] the comments of each content activity are retrieved, this is due to historical functionality where the number of comments where displayed in the activity. As this is not the case anymore, we could think of removing this API call.~~ => Comments (in fact only the first) are used in activities for threads.
- [x] contents needed for content activities are retrieved using the "generic" `/api/workspaces/<workspace_id>/contents/<content_id>` API which is implemented through a redirection which takes some dozens of ms (~30/40ms). As these requests are made several times (one for each content activity), directly calling the dedicated `/api/workspaces/<workspace_id>/<content_type>/<content_id>` API would remove those delays.
- [x] activities are built progressively by calling `messages`, but are displayed only when all required activities are ready. We could change this to add activities by small batches in order to quickly display the first batch.

**Comment by raphj** [comment]
We may also avoid http redirections to shave off a few milliseconds, this would reduce the number of requests (that are potentially queued because of the limit of 6 simultaneous connections)

**Comment by grignards** [comment]
Creating an index on `fields.workspace.workspace_id` in the `events` table greatly improves the `messages` API performance when it used by the space's recent activites. As noted in the issue the index would be created on JSON data (`fields`).
Which gives us two choices:

**Create a separate workspace_id column duplicating fields.workspace.workspace_id and index it*
- pros : the index creation code is shared between databases
- cons : values are duplicated, it is less "intuitive" to know which column to use when a query uses `workspace_id`

The cons would be amplified if we need other indexes on other JSON parts later on (a likely candidate is `content_id`).

**Directly indexing JSON data**
- pros : only one source of data => more intuitive, no risk of forgetting to use the indexed column.
- cons : the syntax to create an index on JSON data is specific to each database type, mysql version would need a small increase (8.0.1 currently, il [8.0.13 would be needed](https://dev.mysql.com/doc/refman/8.0/en/create-index.html#create-index-functional-key-parts), mariadb doesn't seem to support functional indexes so it would require a separate (potentially virtual) column…

**Comment by grignards** [comment]
We've settled with the first option (separate `workspace_id` column).

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by MariePrandstetter** [comment]
Done
