### ISSUE TITLE
Feat: public account creation

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#4594]
## Feature description and goals

The goal is to allow a user to publicly create an account.

- the feature must be deactivable
- the form should ask for email (required), username (optionnal) and password.
- an email is to be sent to the user with reminder of informations

## Graphical Design

https://user-images.githubusercontent.com/35422692/116865324-b23da680-ac09-11eb-83cb-8421c53b33ef.png
N.B. : the "créer mon compte" button shall be placed in the header.

https://user-images.githubusercontent.com/35422692/116858090-1e1a1200-abfe-11eb-93ba-b9f8e664ffa3.png

### Backend

- [x] add a `user.self_registration__enabled` configuration parameter in `development.ini`. The boolean value of this parameter shall enable/disable the following endpoint. This value shall be available in `/api/system/config` as the `user__self_registration__enabled` key.
- [x] add an endpoint `/api/users/register` with a `POST` method, accessible to anybody *without authentication*. The endpoint should have a body of this form:
```json
{
  "email": "hello@tracim.fr",
  "lang": "en",
  "password": "8QLa$<w",
  "public_name": "John Doe",
  "timezone": "Europe/Paris",
  "username": "My-Power_User99"
}
```
(`email`, `public_name` and `password` are required, the others optional with default values the same as `POST /api/users`).
The endpoint shall return a user structure like `POST /api/users`.
- [x] this endpoint shall create a new user with the given information, give it the `user.default_profile` profile from `development.ini`.
- [x] the creation shall send an invitation mail as does `POST /api/workspaces/{workspace_id}/members`
- [x] add an `creation_author_id` column in `users`, defaulting to NULL. Set its value to the created user id when `/api/users/register` is used, the currently authenticated user in other HTTP API creation endpoints.
  - [x] the `creation_author_id` value should be NULL for users created through ldap, command line and remote auth.
 - [x] Add a `creation_type` column that can be `admin`, `invitation`, `register`, `cli` depending on the HTTP API endpoint used to create the user. If the user was auto-created through ldap/remote auth, set its value to NULL.

### Frontend

- [x] the visibility of the "create account"  button shall be linked to `/api/system/config`'s `user__self_registration__enabled` value.
- [x] when the "create account" button is clicked the corresponding form shall be displayed (see the mockups)
- [x] use `/api/users/register` to create the account when the registration form is validated
- [x] when the create account form is validated, the user shall be directly logged in the system
- [x] if present the "terms and conditions" page shall be displayed accordingly

**Dev note**: work branch `feat/4594__add_account_creation`

### Endpoint to use for user creation

`/api/users` could have been used too, 2 reasons not to employ it:
- our authentication system is not able to handle an endpoint sometimes authenticated/sometimes not
- it would make more difficult to create rules for limiting abuse of public account creation (for example with fail2ban).

**Comment by grignards** [comment]
Should we check that the user has given a mail he has access to and activate his account when we have established the link?

**Comment by lebouquetin** [comment]
Not yet, I think

**Comment by lebouquetin** [comment]
This will be a welcome email with informations about where to find help, etc. I have a template for you.

**Comment by inkhey** [comment]
> This will be a welcome email with informations about where to find help, etc. I have a template for you.

This kind of stuff may be useful for new invited user too, so i do suggest that self-creation of account and invitation are similar process and return an almost similar email template (to avoid duplicate stuff).

also, should we consider sooner or later adding monitoring or "newsletter"  checkbox in this features ? (just to be sure we do not take a path that make this complicated).

**Comment by gbonaspetti** [comment]
Two questions:

- For the interface we stay with the interface below (adding username as optional)?
![Capture d’écran de 2021-05-03 10-55-00](https://user-images.githubusercontent.com/35422692/116858090-1e1a1200-abfe-11eb-93ba-b9f8e664ffa3.png)

- To access this page we add a simple button?
![Capture d’écran de 2021-05-03 11-03-45](https://user-images.githubusercontent.com/35422692/116865324-b23da680-ac09-11eb-83cb-8421c53b33ef.png)

**Comment by grignards** [comment]
In fact do we need to have the user do a full login just after subscribing? As the account creation is immediate the login form could be skipped, isn't it?

**Comment by lebouquetin** [comment]
The goal is to have something as soon as possible.

Ideally:

- creation of account should be as simple as possible. I suggesto to ask for public name (this name will be visible), email and password and optionnally *allow* to choose username.
- creating an account should rely on conditions acceptance as a second step
- the create account button should be more visible, probably on top of the screen ? (right to "connexion" title?)
- immediate login may be an option (it's not required but if it is fast to implement, then do it directly)

We will use this feature for the tracim community instance, which will include terms and conditions.

I agree with @inkhey suggestion to factorize email templates.

**Comment by lebouquetin** [comment]
> We need to validate the usage conditions in this page or just in the first login is enough?

My feeling is we should reuse the existing screen. The solution is probably to:

1. create account
2. auto-login like suggested by @grignards 
3. as a first login, show conditions and require to validate it

**Comment by inkhey** [comment]
Some point to clarify after working into implementing this in backend:
- (technical): not very clear how to add parameters in userlib, i did a new method to use after `create_user` for now as i do need flushing before to know the user id. This as some drawback as email are now send in `create_user` (not possible to have a different behaviour according to creation_type or creation_author_id in email).
- Should we prefer that endpoint is disabled (404) or return specific error (400 with specific error code), i go for the later for now as disabling endpoint in current architecture will mean a new controller for just one endpoint.
- What should be the behavior when email notification is disabled, as email are required, it make sense to not allow the have both email notification disabled and self registration enabled, but it can disable some edge case.
- Do we really need password to be required (for backend api) as password will be returned in email ? (we have a mecanism that generate one where no password is given).

**Comment by grignards** [comment]
- I think sqlalchemy has a way to have a row referencing itself: https://docs.sqlalchemy.org/en/14/orm/relationship_persistence.html Could you check whether this would be applicable?
- I would prefer 404 but can settle with a 400. Could you create an issue to solve this overhead to disable an endpoint conditionally? This is not the first time we have this situation.
- I would not check whether email is enabled or disabled: it is the duty of the administrator to properly configure Tracim, and the self-registration by itself works without mails.
- Not requiring the password would render my previous response invalid, so if you agree we should keep it required.

**Comment by MariePrandstetter** [comment]
Done
