### ISSUE TITLE
Feat: Allow selecting an alternative target language for content and comment translation 

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4596]
## Feature description and goals

To do:
 - add a select box to allow  selecting an alternative target language (in the TranslateButton component)
    - [x] in comments
    - [x] in publications
    - [x] in recent activities
    - [x] in app-html
 - [x] the default language is the one used in the UI, like today or the first defined language if the UI language is not found in the backend parameter.

## Discussed

- When should the select button be displayed?
  - always
  
- should the text of "See translation" ("Voir la traduction") be changed to "Translate" ("Traduire") to have more room for the select box?
  - New interface: when we click at the text we translate and when we click at the caret we open the menu
![ASF_translation (1)](https://user-images.githubusercontent.com/35422692/116247425-22ac7980-a76b-11eb-929e-3ef98097a2f8.png)

- where to get the list of target languages from? from an endpoint? hardcoded for now?
  - a setting in `development.ini` for the list of available translations

### Backend

- [x] add the `translation_service.target_languages` parameter in `development.ini`. Its value shall be a `,` separated list of ISO-639-1 codes + language string pairs. By default it shall be `fr:Français,en:English,pt:Português`.
- [x] provide this value in `/api/system/config` in the form of a JSON list named `translation_service__target_languages`:
```json
"translation_service__target_languages": [
  {
     "code": "en",
     "display": "English"
  },
  {
    "code": "fr",
    "display": "Français"
   }
]
```

## Frontend

- [x] use the backend-provided language list to display the languages in the select menu

**Comment by gbonaspetti** [comment]
For me, the answers are

> When should the select button be displayed?

always (if the feature is active)

> should the text of "See translation" ("Voir la traduction") be changed to "Translate" ("Traduire") to have more room for the select box?

I like your idea, maybe have sommething like that:
![ASF_translation](https://user-images.githubusercontent.com/35422692/116246728-88e4cc80-a76a-11eb-95b4-25e056b8bef9.png)
Advantage: simple to understand and does not require much space
Disadvantage: the user will always have to choose one language

Or when we click at the text we translate and when we click at the caret we open the menu, like that:
![ASF_translation (1)](https://user-images.githubusercontent.com/35422692/116247425-22ac7980-a76b-11eb-929e-3ef98097a2f8.png)
Advantage: still simple and allows the default language 
Disadvantage: small button to change the language, less simple to understand at the first time the difference between the clicks.

> where to get the list of target languages from? from an endpoint? hardcoded for now?

I think we had decided on a setting in development.ini but I am not sure. @grignards @lebouquetin do you remember?

**Comment by grignards** [comment]
Nope I don't remember we've decided this specific point. I would prefer having a setting in `development.ini` as it is more flexible (eg. when ASF asks for another language, this would only be a configuration change).

**Comment by lebouquetin** [comment]
I agree with the dev.ini config for the list of available translations.

The strategy is also ok for me.

👌

**Comment by raphj** [comment]
I like both of your mockups @gbonaspetti

**Comment by grignards** [comment]
There one detail: how does the frontend know which language string (*English*/*French*) to display? We could have a predefined list of languages but then we come back to have hard-coded values in the frontend…

**Comment by raphj** [comment]
I suggest to always show the name of the language in the language itself, since the person who wants a translation in this language is guaranteed to understand this one.

**Comment by MariePrandstetter** [comment]
Done
