### ISSUE TITLE
User workspaces

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#46]
For personal user calendar event, we create event Contents without parent workspace. Final goal is to build user personal workspace.

Theses personal workspaces should:
- Not be visible by admin user
- Not allow to add members into

**Comment by tracim** [comment]
The feature is:
- add a config parameter which will tell "every user has a personnal workspace"
- implement it and do not show these workspaces in workspace admin pages
- assign all events to this workspace if the option is activated
