### ISSUE TITLE
Misc: update pushpin's repository url

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4603]
## Feature description and goals

The online service that pushpin uses for distributing its debian packages will be closed on May 1st (see details [here](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)).
They have an issue and are working on this task, but we'll have to update the url used in our `Dockerfile` files so that Tracim's docker images can be built after May 1st.

## Prerequisites

- https://github.com/fanout/pushpin/issues/47695 : it is done, see the installation instruction [here](https://pushpin.org/docs/install/) to find the updated repository url.

## Implementation

Will be done with #3911 as the new repository only has the version 1.31.

**Comment by raphj** [comment]
Note the updates:

> UPDATE 4/27/2021: We listened to the community and will keep JCenter as a read-only repository indefinitely. Our customers and the community can continue to rely on JCenter as a reliable mirror for Java packages.
> 
> UPDATE 2/28/2021: To better support the community in this migration, JFrog has extended the JCenter new package versions submission deadline through March 31st 2021.

This gives some freedom as to when we decide to handle this.

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by MariePrandstetter** [comment]
Done
