### ISSUE TITLE
Misc: Move configurable images in the `branding` folder

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4606]
## Feature description and goals

Tracim's branding folder currently includes the welcome/login page customization and will soon include the terms and conditions documents.
There are other parts of Tracim that are configurable and moving them to this folder would ease the comprehension for instance administrators:

- [x] favicon images which are currently located in `frontend/assets/images/favicon/*` (links in `index.mak`)
- [x] progressive webapp images `frontend/assets/images/wa-*` (links in `frontend/dist/assets/manifest.json`)
- [x] main logo `frontend/assets/images/logo-tracim.png` (:warning: it is copied in the docker images script `common.sh`)
- [x] `color.json` (its path is a parameter in `development.ini`)
- [x] default favicon.ico image (`frontend/assets/favico.ico`)

**Comment by inkhey** [comment]
@grignards i do suggest to make this path configurable in backend but keep frontend path in /dist/assets as default value. Having an "harcoded" value here make testing theses features in backend complicated.

**Comment by inkhey** [comment]
we should probably adapt branding documentation according to these new features.

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
