### ISSUE TITLE
Feat: Change tracim's branding and graphic charter

### ISSUE THREAD

**Issue by charline-rageade** [tracim/tracim#4629]
## Feature description and goals

After working on the visual identity, Tracim changed its brand image. These changes need to be integrated into Tracim: 

- Replacement of the logos 
- Change of the font of the logos 
- Adaptation of colors

 **WARNING: All logos must be modified. It is important not to forget the favicon and the logo on the smartphone**.

_For more information on the different types of images and their location you can go to this ticket #4606_

## Graphic Charter : 

_Here is a description of the complete graphic design. We will only need the tracim logos and colours._ 

**Tracim's logo**:
![Capture d’écran du 2021-05-11 12-02-46](https://user-images.githubusercontent.com/82377347/117797873-d07e5480-b250-11eb-9b40-1fe7eb6397f2.png)
 : 

**Mon Tracim's logo** : 
![Capture d’écran du 2021-05-11 12-01-17](https://user-images.githubusercontent.com/82377347/117797794-b6447680-b250-11eb-8d92-0aec7f6bb834.png)

**Color palette**
![Capture d’écran du 2021-05-11 12-01-44](https://user-images.githubusercontent.com/82377347/117798017-f277d700-b250-11eb-9c7b-21299f370620.png)

**Fonts**:

Raleway Black Black italic
Raleway ExtraBold ExtraBold italic
Raleway Bold Bold italic
Raleway SemiBold SemiBold italic
Raleway Medium Medium italic
Raleway Regular Italic
Raleway Light Light italic
Raleway ExtraLight ExtraLight italic
Raleway Thin Thin italic

## Prerequisites
Make sure you have all the images in the appropriate format

## Comments

On  tracim application there is still an old logo (even older than the meerkats) in the background by transparency. This is an opportunity to replace it with the new one.

**Comment by lebouquetin** [comment]
@grignards I see at the moment that margins are not normalised. See:

![image](https://user-images.githubusercontent.com/907161/117933682-1c3d0680-b302-11eb-801a-3a2f3543d8d1.png)

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by MariePrandstetter** [comment]
Done

**Comment by PhilippeAccorsi** [comment]
Done.
