### ISSUE TITLE
Bug: Faulty migration with postgresql

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4632]
## Description and expectations

Upgrading the database to the build_044 version is not possible in postgresql:

```
E       sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) type "usercreationtype" does not exist
E       LINE 1: ALTER TABLE users ADD COLUMN creation_type usercreationtype
E                                                          ^
E       
E       [SQL: ALTER TABLE users ADD COLUMN creation_type usercreationtype]
E       (Background on this error at: http://sqlalche.me/e/13/f405)
```

### How to reproduce

1. Have a database < build_044 in postgresql
2. Try to upgrade it to build_044

### Version information

- Tracim version: 3.8.0_build_044

________________________________________________

## Diagnostic

The `create_enum()` command was forgotten and `test_migration.py` didn't fail because it starts with a newly created database, then downgrades it.

**Comment by MariePrandstetter** [comment]
Done
