### ISSUE TITLE
Bug: 500 on url preview

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#4637]
## Description and expectations

Error happens on Tracim page containing url preview.

**Expected**: Find a workaround to not show a 500 erreur when a preview does not work.

To do:
- [X] Don't double unquote urls
- [X] Handle the InvalidURL exception

## Screenshots

![2021-05-12_10-18](https://user-images.githubusercontent.com/1104637/117942538-72627780-b30b-11eb-910e-7be93a0c931a.png)

## Diagnostic

Bug is this XHR request:
    
`GET | https://algoo.tracim.fr/api/url-preview?url=https://github.com/LuckyDudeThakur/EBooks/blob/master/Accelerate%20-%20Building%20and%20Scaling%20High%20Performing%20Technology%20Organisations%20-%20Nicole%20Fergrson.pdf`

Response:

    {"code": null, "details": {"error_detail": {}}, "message": "The URL is invalid."}

- The link preview url is double unquoted
- The InvalidURL exception is unhandled

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
