### ISSUE TITLE
Bug: Multiple clicks are sometimes needed to close a publication, note or thread

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4646]
## Description and expectations

In some situations clicking on the close button of the note app is not enough to close it, the user has to click it several times before the app closes.

### How to reproduce

1. Open a thread
2. Write 3 comments then send them
3. Try to close the app.

### Version information

- Tracim version: 3.8.1
- Web browser: Firefox
- Version: 88
- System : Ubuntu 20.04

________________________________________________

## Diagnostic

Asynchronous unmount and render functions, more information at https://github.com/tracim/tracim/issues/4679

## Prerequisites

None

**Comment by MariePrandstetter** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Done
