### ISSUE TITLE
🐛 Bug: Creating a member take too long time when there is already a big history

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4652]
## Description and expectations

Creating a member (user that join a space) can take several seconds.
With the `autoinvite` plugin enabled and several open spaces (40+), creating a new user can take several minutes if every spaces contains 400+ members (or just a big history).
It should be quicker.

### How to reproduce

1. Create several open spaces and add content users in them
2. Enable `autoinvite` plugin
3. Create a new user

### Version information

- Tracim version: 3.8.1 ; 4.3.3

### 500 users join 50 spaces (time is in seconds)
![Graph500UserJoin500Spaces](https://user-images.githubusercontent.com/28917197/220056933-99e61eed-0de2-4668-b0f2-21757e20682f.png)
This tests was using a postgresql database

________________________________________________

## Diagnostic

Likely due to the creation of the history of messages for the new user. Could be mitigated by limiting the messages history (`workspace.join.max_messages_history_count` parameter).

Tests to see the influence of `workspace.join.max_messages_history_count` (16 spaces are joined automatically):

|value|creation time|total message count for new user|
|-------|-----------------|------|
|inf|11500ms|4098|
|100|3500ms|1181|
|2|500ms|50|

The time spent is mainly due to the multiple "useless" queries to know whether an message should be created for a given event: the mechanism was written to answer the question without prior knowledge of the user's membership. When creating historic messages the code has the prior knowledge that the user is member of the workspace.

## Implemented (chosen) solution:

Optimize the message creation speed by having a look at sqlalchemy caching.

### Optimize the message creation speed

**Pros**:  Does not change anything functionally, learning to cache with sqlalchemy could prove useful in other cases.
**Cons**: Either requires to have a more fragile code or to learn how to propely cache sqlachemy query results when creation historic messages.

### Add loaders to the user interface

**Pros**: The application would feel more interactive to the user
**Cons**: The time to wait can easily be too big even with a loader (>10s), two loader implementations would be needed (one for a button, the other for the member list)

### Limit the number of created messages

**Pros**: Very easy as the configuration parameter exists
**Cons**: The parameter limits the number of messages created for one workspace, not globally. This means it is not enough to ensure the waiting time will be ok (if there are many open spaces). The parameter is a message count which is good timewise, but for the user experience it can be problematic: if many messages only create one activity, there is the possibility that recent activities lists do not display many items.

### Asynchronous creation of historic messages

**Pros**: Quick to implement
**Cons**: Has functional impacts if the user logs in quickly after its creation: some recent activities could be missing in this case (refreshing the page after all messages have been created would display the expected activities). Does not help the CPU/database usage.

### Create the history on-access

The history (Tracim messages created from past events) could be created when accessing it through the backend, and only create the required history.
Messages usages are:
- notification panel (through HTTP API `/api/users/{user_id:\d+}/messages`)
- recent activities (through the HTTP API `/api/users/{user_id:\d+}/messages`)
- summary mails (through the python API `EventApi.get_messages_count()` and `EventApi.get_unread_messages_summary()`)

So it is feasible to implement a on-access creation in those functions.

**Pros**: as usages do only require part of the history, its creation should be relatively quick, minimal CPU usage and perfect responsiveness of member creation.
**Cons**: all methods accessing the history of messages **must** create the history on access. Could be fragile when future developments add future methods to access messages.

**Comment by lebouquetin** [comment]
> Could be mitigated by limiting the messages history (workspace.join.max_messages_history_count parameter).

I'm not sure there is a need for another solution for this. The autojoin plugin is based on community use case which does not necessary requires to get full history. Looking for an efficient way to "import event backlog for new users" may be useless
