### ISSUE TITLE
Bug: Recent activites can display less than 15 activities when loaded

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4654]
## Description and expectations

Even if there are many more activities (clicking on the `See more` button displays them).

### How to reproduce

1. Create a space
2. Add many members to it (15+)
3. Remove those members
4. Display the space recent activities

### Version information

- Tracim version: 3.8.1

## Screenshots

________________________________________________

## Diagnostic

The code filtering the activities to display is independent from the code fetching and constructing the activities. Filtering should occur during the fetching/creation of activities (`ActivityList.jsx`/`withActivity.js`).

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
