### ISSUE TITLE
Feat: Reformulate the terms and conditions message

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4656]
## Feature description and goals

The message displayed to the user when terms and conditions are enabled is a bit too assertive, a reformulation could help here: "In order to finish your log in, please read the following usage conditions and accept them".

## Translations

|en|fr|pt|de|
|--|--|--|--|
|In order to finish your sign in, please read the following usage conditions and accept them|Pour finaliser votre connexion, merci de prendre connaissance des conditions d'utilisation et de les valider|Para terminar a sua sessão, por favor leia as seguintes condições de utilização e aceite-as|Um Ihre Anmeldung abzuschließen, lesen Sie bitte die folgenden Nutzungsbedingungen und akzeptieren Sie diese|

## Steps

- [x] Step 1: asking my peers for different translations

- [x] Step 2: modify the code in the Conditions.jsx container with the reformulation of the new sentence

- [x] Step 3: copy the different translations into the translations.json of each language

**Comment by PhilippeAccorsi** [comment]
Done.
