### ISSUE TITLE
Feat: Prepare new release 3.8.2

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#4661]
## Feature description and goals

- [x] update frontend version
- [x] update backend version
- [x] update changelog

**Comment by grignards** [comment]
#4606 implies a breaking change for:
- manually installed instances where logos have been customized
- all docker instances with version >= 3.8.0 (updating needs first to copy new `branding` folder files to the already existing `branding` folder)

**Comment by gbonaspetti** [comment]
#4673 this issue introduces setting ui.spaces.creation.parent_space_choice.enabled (TRACIM_UI__SPACES__CREATION__PARENT_SPACE_CHOICE__ENABLED), which defaults to True.

**Comment by PhilippeAccorsi** [comment]
For this comment https://github.com/tracim/tracim/issues/4661#issuecomment-843261953

more information about process for this breaking change:
- on existing installation without branding folder (tracim < 3.8.0)
  - restart with new docker image
  - mv color.json and logo.png to the branding folder newly created
  - restart your docker image
 
If its not done, tracim not running with your customization.

**Comment by PhilippeAccorsi** [comment]
Done.
