### ISSUE TITLE
Feat: Add a configuration parameter to disable the space parent input when creating a space

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4673]
## Description and expectations

Allow disabling the space parent input when creating a space.

To do:
 - [x] backend : add a configuration parameter to disable the space parent input when creating a space (`ui.spaces.creation.parent_space_choice.enabled`)
 - [x] backend : reflect this value in the `/system/config` endpoint, field: `ui__spaces__creation__parent_space_choice__enabled`
 - [x] frontend : use this value to hide the parent space choice in the space creation popup

### Version information

- Tracim version: v3.8 (probably before)
- Web browser: any
- Version: any
- Device / System: PC

**Comment by gbonaspetti** [comment]
The space type was fixed at https://github.com/tracim/tracim/issues/3774 so I update the description to fix the parent space option.

**Comment by MariePrandstetter** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Done.
