### ISSUE TITLE
Misc: Duplicated code for activityDisplayFilter

### ISSUE THREAD

**Issue by knodelle** [tracim/tracim#4677]
## Description and expectations

The activity list filter activityDisplayFilter is used both in withActivity, and ActivityList. 
The filter in ActivityList is necessary for the recent activities, and the withActivity filter is used for the dashoard activity list. 

There is also a similar code at frontend/src/reducer/notificationPage.js

Also see https://github.com/tracim/tracim/pull/5947#discussion_r999211673

## Branch

~~[misc/4677__duplicated_code_activityDisplayFilter](https://github.com/tracim/tracim/tree/misc/4677__duplicated_code_activityDisplayFilter)~~ too old ; deleted

________________________________________________

**Comment by Haskaris** [comment]
Tracim 4.3.2
In `NotificationPage.js`, filter function, we are doing a map then a filter. The map doesn't change any notifications. We should move the code from the map to the filter.
