### ISSUE TITLE
Feat: add link to Tracim content using #'s

### ISSUE THREAD

**Issue by charline-rageade** [tracim/tracim#4680]
## Feature description and goals

This feature allows linking,  in contents and comments, contents to which members have access. This feature is based on the same principle as member mentions in content.

## Prerequisites

Here are the prerequisites to validate this ticket

- [x] autocompletion popup after # with id + content name
- [x] consistent proposal (autocomplete must propose only the files to which the member has access)
- [x] if the member does not have access to the content an alert message should notify them that they cannot access the content
- [x] an /users/me/known_content?acp enpoint runs ILIKE on content ids and labels

**Comment by gbonaspetti** [comment]
Done
