### ISSUE TITLE
Feat: Support content tags (backend)

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4685]
## Feature description and goals

We add tags to contents (#4681), which requires new endpoints.

To do:
 - [x] add a tag to a content: `POST /workspaces/XX/contents/YY/tags`: `{ tag_name: "TAGNAME" }` This endpoint adds a tag to a workspace if it doesn't exist, and attaches it to the given content
 - [x] add a tag to a content by id: `PUT /workspaces/XX/contents/YY/tags/ZZ`: This endpoint attaches a tag to the given content
 - [x] remove a tag from a content: `DELETE /workspaces/XX/contents/YY/tags/{TAG_ID}`. :warning: This endpoint does not remove the tag from the workspace.
 - [x] list tags of a content: `GET /workspaces/XX/contents/YY/tags`
 - [x] list tags of a workspace: `GET /workspaces/XX/tags`

We will also need these endpoints in a second phase (they don't require much more work):
- [x] get a tag: `GET /workspaces/XX/tags/YY`. This endpoint gets a tag in a workspace. It fails with a 400 error if the tag does not exist
 - [x] add a tag to a workspace: `PUT /workspaces/XX/tags`. This endpoint adds a tag to a workspace. It fails with a 400 error if the tag already exists
 - [x] remove a tag from a workspace: `DELETE /workspaces/XX/tags/{TAG_ID}`. This endpoint remove a tag from a workspace. It fails with a 400 error if the tag does not exist

To also do:
- [x] Readers cannot add or remove tags.
- [x] Tags are stored in a table `tag`: (tag_id, workspace_id, tag_name). We may add a description field later
- [x] Tags are mapped to content in a `content_tag` table (tag_id, content_id). We must be careful on what happens when moving a content from a workspace to another, or when deleting a content (don't forget ON CASCADE DELETE on tag_content elements)

:warning: Tags will not be copied across spaces when a content is moved / copied into another workspaces.

**Comment by inkhey** [comment]
1. for consistency with REST,  GET /workspaces/XX/contents/YY/tags/TAGNAME make sense, but this require TAGNAME to be unique in the workspace, so you need a unique constraint on TAGNAME, workspace_id.
2. if TAGNAME, workspace_id are unique, there is many no need for tag id. But this mean that workspace_id, tag name fields are directly in content_tag table.

**Comment by raphj** [comment]
okay, I updated endpoints so they are more consistent with other endpoints in tracim.

**Comment by raphj** [comment]
Tested on the corresponding frontend branch a while ago.
