### ISSUE TITLE
Feat: Create TagList component

### ISSUE THREAD

**Issue by MariePrandstetter** [tracim/tracim#4686]
## Feature description and goals
We add tags to contents (#4681), which requires a new component to render the tag list. 

This component will be rendered in the apps file and html-document, in a dedicated tab above the other ones.  

The goal of this feature is to let the user choose tags in the available tag list, or to create new ones in a form. 

The selected tags will be displayed in the left part of the app, on top of the "download" icon.

This component should look like MemberList

The chosen tags will be marked as "checked", and the other ones will be "unchecked". The checked tags will appear on top of the unchecked ones.

When a new tag is created in the app, it will be marked as "checked" and it will be rendered in the list. This tag will be available in every content in its space, and will be displayed as an "unchecked" tag.

To do : 

- [x] Create TagList component
- [x] Create NewTagForm component
- [x] Create Tag component
- [x] Render selected tags
- [x] Add translations
- [x] Link with backend endpoints

## Prerequisites

Backend endpoint to GET the tag list:  #4685

## Mockups

![TAGS](https://user-images.githubusercontent.com/50776142/120205581-65f67e00-c22a-11eb-9e4b-4d3f21fe5ba5.png)

**Comment by charline-rageade** [comment]
Just to complement, in a first time will be implemented a list of checkboxes and we can only check or uncheck the tags

**Comment by gbonaspetti** [comment]
> Just to complement, in a first time will be implemented a list of checkboxes and we can only check or uncheck the tags

See the list in CheckboxFilter (Advanced Search), it can be useful. (cc @MariePrandstetter @charline-rageade )

**Comment by Skylsmoi** [comment]
tested on branch
