### ISSUE TITLE
Feat: Display content title when link a internal content

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4692]
## Feature description and goals

For now, when a link to an internal content is made, its id is shown in the text. A nice feature is to show your title instead of the id. 

## Prerequisites

#4680 

## To be discussed before development

One possible problem is the detection of spaces in the title. A possible solution is to use the id during the text entry, but add the title after saving.

![Capture d’écran de 2021-06-04 17-05-12](https://user-images.githubusercontent.com/35422692/120822813-16c88a00-c557-11eb-9d0a-e460dac16ccd.png)

**Comment by lebouquetin** [comment]
My feeling is it will be complex because of spaces included in the label... in this case, it would be ok to fill with title only when tinymce is active (ie integer id by default in comments, and label for rich text comments and for notes)

**Comment by gbonaspetti** [comment]
Fixed at https://github.com/tracim/tracim/issues/4732
