### ISSUE TITLE
Radicale: Create ics files from zero

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#47]
Look at `tracim/tst_create_cal.py` for test script.

**Comment by tracim** [comment]
What is the issue ? To be investigated with @buxx

**Comment by algooapy** [comment]
Implemented in:
- `tracim/tracim/lib/calendar.py:create_then_remove_fake_event`

Useb by:
- `tracim/tracim/lib/workspace.py:ensure_calendar_exist`
- `tracim/tracim/lib/user.py:execute_created_user_actions`

Tested. Functional.
