### ISSUE TITLE
Feat: Handle TLMs for tags

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4700]
## Feature description and goals

To be able to see and interact with the tags in real time we need to add TLMs for it.

Expected:
- [x] Add TLMs for tags on backend
  - `tag.created`
  - `tag.modified`
  - `tag.deleted`
  - `content_tag.created`
  - `content_tag.deleted`
  - `tag.*` will have the following fields:
    - `tag` : (id + name)
    - `workspace`: (`WorkspaceWithoutDescriptionSchema`)
    - `author`
  -  `content_tag.*` will have the same fields plus:
    - `content`
- [x] Handle `tag.(created|deleted)` and `content_tag.(created|deleted)` in frontend for file and notes
- [x] Update TLM documentation
  - https://algoo.tracim.fr/ui/workspaces/49/contents/html-document/12987

## Prerequisites

None

**Comment by charline-rageade** [comment]
Tested on a branch
