### ISSUE TITLE
Misc: Give more importance to titles on links popup of autompletion

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4702]
## Feature description and goals

In the popup of autompletion of the links, remove the bold of the #id and put it to the titles, to give importance to the titles

![Capture d’écran de 2021-06-14 13-04-38](https://user-images.githubusercontent.com/35422692/121883269-d369da80-cd11-11eb-84cf-fc8cee4ce008.png)

## Prerequisites

None

**Comment by raphj** [comment]
tested on branch.
