### ISSUE TITLE
Feat: Handle delete for tags

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4709]
See issue #4767 for more details

## Feature description and goals

It should be possible to delete a tag from a space.

## Prerequisites

None

## Discussed before development

Two proposals:
- Have the list on a tab in space settings and only allow to delete from there
- Have a trash can icon on tag list (in each app) and when clicked a popup appears with the warning like "You will delete this tag from space and consequently from all content that uses it. Are you sure?"

We chose the first approach.

**Comment by charline-rageade** [comment]
tested on branch
