### ISSUE TITLE
Feat: Clarify use of tags 

### ISSUE THREAD

**Issue by charline-rageade** [tracim/tracim#4712]
#4767 
## Feature description and goals

Today the use of tags is not very clear. The user doesn't know if the tags are associated with the content or the space, nor how the latter are managed. 

## Prerequisites

N/A

## Proposals

*  Instead of making a checkbox, just make a label with a cross or a bin next to it to deselect it
*  Have only the list of tags already added and auto-completion for the list of all available tags
*  The space manager can add all the tags he wants, the contributor can only add pre-existing tags to the content

In the advanced dashboard have a tag management section

**Comment by gbonaspetti** [comment]
Fixed at https://github.com/tracim/tracim/issues/4709
