### ISSUE TITLE
Bug: I am a reader of a space and I have access to the button to add a tag

### ISSUE THREAD

**Issue by charline-rageade** [tracim/tracim#4716]
## Description and expectations

When we are a reader we go to the functionality concerning tags, it has the possibility to add tags. However, when he wants to add some he will encounter an error. This bug alters the user experience a bit. 

To solve this bug, it is necessary that ; 

- [ ] the reader does not see that it can add a tag

- [ ] the reader cannot interact with the checkboxes

### How to reproduce

1. Check that you are only a reader in a space
2. Go to a content of this space
3. Go to the tags tab
4. Click on add a tag
5. Type an example and validate

## Prerequisites
N/A

**Comment by gbonaspetti** [comment]
Fixed at #4767
