### ISSUE TITLE
Bug: The login screen is not fully responsive

### ISSUE THREAD

**Issue by charline-rageade** [tracim/tracim#4719]
## Description and expectations

The login screen is not responsive. The responsiveness should be reworked, especially for the connexion button.

### How to reproduce

1. If you are logged in, log out
2. Change the screen size with the development tool

## Screenshots

![xRch0nB](https://user-images.githubusercontent.com/82377347/122026053-3028cc00-cdca-11eb-845e-2647977b8c49.jpg)

## Prerequisites

N/A

**Comment by gbonaspetti** [comment]
Doubled with https://github.com/tracim/tracim/issues/4662
