### ISSUE TITLE
Bug: Ctrl+click doesn't open links to a tracim content in a new tab

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4731]
## Description and expectations

Ctrl+Click should open links in new tabs. However, when CTRL+clicking on a link to a Tracim content, no tab is opened and the Tracim content replaces what was displayed before.  

### How to reproduce

1. Link to a tracim content in a comment or a note
2. CTRL+Click on it

### Version information

- Tracim version: Tracim 3.8 after Sprint 01

## Diagnostic

The HTMLContent component waits for link clicks. If it detects that a tracim link was clicked, it prevents the default action to happen and push the url to the history of the current page.

## Suggested fixes
 - don't prevent default and don't push to history if a key is pressed (including Meta / the Window key / Cmd, Ctrl, Shift)
 - disable this behavior for now (and add it back, in a robust way, globally)

**Comment by wwalden** [comment]
It seems to work properly now
