### ISSUE TITLE
Feat: improve link management in advanced editing

### ISSUE THREAD

**Issue by charline-rageade** [tracim/tracim#4732]
## Feature description and goals

The aim of this ticket is to rework the links to the different contents (external as well as internal) to improve the user experience. The main points to achieve in this feature are :

- [x]  have an [icon](https://fontawesome.com/v5.15/icons/external-link-alt) to indicate that it is an external link

- [x] to have a visual element that differentiates an internal link from an external link. A first proposal would be to have the internal link highlighted (as for the embedded code on Mattermost)

## Prerequisites

Think about the implementation on the front-end (design phase). 

## Implementation
Not everything has been implemented. I am thinking in particular of the fact that the link becomes functional as soon as it is entered : 
~~to have an instant preview of the link in the advanced edition without going through the validate then modify path in order to be able to interact with it.~~ 

However, in link with this ticket #4692  it is no longer the id that is visible but the link

**Comment by raphj** [comment]
Tested on preprod.
