### ISSUE TITLE
Upgrade : Ubuntu 18.04 soon deprecated, need Tracim ready for Ubuntu 20.04

### ISSUE THREAD

**Issue by Keepshango** [tracim/tracim#4735]
Hi,

System **Ubuntu 18.04** will soon be deprecated, so I wish to backup-install TRACIM on **Ubuntu 20.04** asap !

Does making TRACIM compatible with distro **Ubuntu 20.04** is in your roadmap ?
If yes, at what dead line date can one expect this to be done ?

Regards

**Comment by PhilippeAccorsi** [comment]
Hi Keepshango,

Ubuntu 18.04 LTS are not really soon deprecated but this is an sys admin vision. You can seen support of 18.04 LTS [here](https://ubuntu.com/about/release-cycle).

We not have added support to Ubuntu 20.04 in the roadmap for the moment (this is not us priority). You can find some information to install/run Tracim with this release 20.04 [here](https://github.com/tracim/tracim/issues/3680)

For this kind of question, you can use https://community.tracim.fr (you need to create an account to acces on it)

Regards,
Philippe

**Comment by Quiwy** [comment]
Seems that's not relevant anymore, see https://github.com/tracim/tracim#advanced---install-tracim-from-source
