### ISSUE TITLE
Bug: @alle to mention all in German is missing

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4740]
## Description and expectations

The German translation landed without a way to mention all in German. We need to add `@alle`.

To do:
 - add it in `GROUP_MENTION_TRANSLATION_LIST` in file `frontend_lib/src/mentionOrLink.js`
 - add it in file `frontend_lib/test/apiMock.js`
 - add it to the reserved names (endpoint `/system/reserved-usernames`)
 - verify if there are other places to handle

### Version information

- Tracim version: 3.9

**Comment by gbonaspetti** [comment]
Fixed at #5470

**Comment by knodelle** [comment]
done
