### ISSUE TITLE
Bug: "TypeError: t.user is null" after deletion of an account in community.tracim.fr

### ISSUE THREAD

**Issue by charline-rageade** [tracim/tracim#4746]
## Description and expectations
When a user is deleted from the community space, after refresh web page, just a blank page is shown.

Web notification handling errors are displayed in web console devtool : 
"TypeError: t.user is null" and Uncaught (in promise) TypeError: t.user is null 

(this error appear in community.tracim.fr instance after deletion of an account) 

This bug impacts all installation of Tracim and members in common with the deleted member

**A temporary solution(hotfix) was applied by adding workspace_member.deleted to the list of web.notifications.excluded**

To do:
- [x] Use `updateTLMUser` function to handle in frontend (fixed at https://github.com/tracim/tracim/pull/4769)
- [x] The backend should not send null author in `/messages` endpoint

### How to reproduce

1. Delete using tracimcli an user's account whom is a member in a space shared with other users 
2. Log in with another user in the space

### Version information

- Tracim version: [3.8.2]

## Diagnostic

The diagnosis must be established and the most sustainable solution must be found. However, here are some guidelines: 
- The front-end could handle the "user":null
- In the back-end the tracimcli command could correctly modify the data in the database

Depending on the approach, keep in mind the database management.

## Implemented solution (backend):
- do a flush before user deletion.
- soft deletion of user before other action: renaming, real deletion for delete/anonymize command.

**Comment by grignards** [comment]
Tested on branch (frontend fix).

**Comment by gbonaspetti** [comment]
Tested on branch
