### ISSUE TITLE
Misc: Bump Preview-Generator to version 0.23

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#4751]
## Description and expectations

Latest version of preview-generator solve issue related to bad builder used. see https://github.com/algoo/preview-generator/issues/235
it contains also a change permitting to not required dependencies like vtk.

## Implemented solution:
- add new requirements for optionals preview-generator dependencies
- update preview-generator to 0.23

**Comment by inkhey** [comment]
To test this ticket: create preview of different types (image, video, 3d, office document, etc...) and verify all is ok.

**Comment by raphj** [comment]
tested on branch
