### ISSUE TITLE
Bug: "validity: 15 min" in mail to change password

### ISSUE THREAD

**Issue by charline-rageade** [tracim/tracim#4759]
## Description and expectations

When receiving the email to change the password, it is indicated that the validity period of the email is 15 minutes in this non-verbose form: (validity : 15 min). The correction of this bug should allow to have : 

- [x] Get the duration from the config file in the development.ini

- [x] Convert the data which is currently in seconds

- [x] Display the duration in the *.mak version

- [x] Make a more verbose sentence

- [x] Manage the translation in the 4 languages of my tracim

### How to reproduce

1. Go to the homepage of "Mon tracim!"
2. Click on forgotten password
3. Enter your email address and validate
4. Consult your e-mails

### Version information

- Tracim version: [3.8.2]

## Screenshots

![Capture d’écran du 2021-06-23 16-36-55](https://user-images.githubusercontent.com/82377347/123117749-5097fc80-d442-11eb-9226-f0e4a0c6aff6.png)

**Comment by raphj** [comment]
Tested on branch
