### ISSUE TITLE
Feat: Add "upload a new version" button in the file app

### ISSUE THREAD

**Issue by MariePrandstetter** [tracim/tracim#4766]
## Feature description and goals

In the file app:

If the file can be opened and edited with collabora:
-  keep the button "edit online"
- add an "upload a new version" button in the drop down menu of the app

If not:
- Add the "upload a new version" in the header instead of the "view online" and add "view online" in the drop down menu. 

Be careful: if collabora is disabled, it should always have the "upload a new version" button.

**Comment by grignards** [comment]
Tested on branch.
