### ISSUE TITLE
Feat: allow limiting the number of simultaneous active users

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4768]
## Feature description and goals

We need to be able to limit the number of active users at any given time. This number is different from:

- the number of currently logged-in (connected) users
- the number of connections to pushpin (a user can be simultaneously connected from several browsers or devices

Here's a course of implementation backend-wise:
 - [x] add a `connection_status` column to the users table (with possible values OFFLINE / ONLINE)
 - [x] a process (ran like mail_fetcher, for instance) monitors Pushpin and determines the list of connected users by listing the open connections to live messages and sets is_active=1 for these users
 - [x] for each user, after the last connection to live messages is closed + a configurable timeout, the process sets is_active=0 for this user
 - [x] when the frontend requests a live message connection, the active users are counted and an error is returned if there are more active users than the configured limit

Frontend-wise:
 - [x] a flash-message is displayed when this error is encountered (something like "There are too many active users. Please try again later or contact your administrator")

**Comment by grignards** [comment]
`is_active` already exists, maybe `is_connected`?

**Comment by raphj** [comment]
connection_state is good

**Comment by grignards** [comment]
or `connection_status` with `ONLINE|OFFLINE`.

**Comment by raphj** [comment]
Current state of the UI:
![limit-active-users-count](https://user-images.githubusercontent.com/3817365/124290696-0b677f00-db54-11eb-98c3-5fb7ba9c13b2.gif)

![image](https://user-images.githubusercontent.com/3817365/124290710-102c3300-db54-11eb-9fc2-d3c78075d2c5.png)

**Comment by raphj** [comment]
@PhilippeAccorsi This PR adds the following parameters with these default values:

```
; live_messages.stats_zmq_uri = ipc:///var/run/pushpin/pushpin-stats
; limitation.maximum_online_users = 0
; limitation.maximum_online_users_message =
; user.online_timeout = 10
```

These settings are optional and should be set only if we want to limit the number of users of an instance

**Comment by raphj** [comment]
This has been tested on preprod.
