### ISSUE TITLE
Feat: Update radicale to 3.*

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#4789]
## Feature description and goals

New radicale version 3.* change lot of things, it also change the way the configuration objet is handled. We do use these object for `tracimcli webdav start command`, so the compatibility is broken.
We should fix this to upgrade to the new radicale version

## Prerequisites
- #4785 (suppressed by #5010)

## Implemented solution:

- update radicale to 3.x
- fix code and default config to be compatible with radicale 3.x

PR ref: #5356 
Issue ref: #4789

**Comment by inkhey** [comment]
Tried to update to radicale 3.* in order to achieve https://github.com/tracim/tracim/issues/2099 (better to test this on latest radicale version):
https://github.com/tracim/tracim/commit/d7bf5504243ea508117492358cec80d19760e2d3
I do get multiple breaking change:
- some parameters names/valid values change and are not backward compatible.
- there is no more "none" right policy and with this:
  - we have to set basic auth for all query
  - it's no more possible to create tree hierarchy in radicale, which may be a problem if we want to keep url backward compatibility. This backward compatibility is not reached now.

**Comment by inkhey** [comment]
I tested with a custom right plugin and we can this way overcome the tree issue :

```python
from radicale import pathutils, rights

class Rights(rights.BaseRights):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._verify_user = self.configuration.get("auth", "type") != "none"

    def authorization(self, user, path):
        if self._verify_user and not user:
            return ""
        sane_path = pathutils.strip_path(path)
        if "/" not in sane_path:
            return "RW"
        if sane_path.count("/") >= 1:
            return "rw"
        return ""

```

**Comment by inkhey** [comment]
After launching, i discovered that the change to radicale 3 disallow some action directy on the root agenda directory itself which was allowed before.
This change doesn't look like a regression as this is not needed for event creation/deletion/agenda color change.

**Comment by inkhey** [comment]
To test this:
- update backend dependencies (with standard script) like for any PR.
- update development.ini according to the PR (instead it will failed)
- test caldav feature with all clients to seek potential regression.

**Comment by knodelle** [comment]
tested on branch with thunderbird 91.5.0 and tracim

**Comment by knodelle** [comment]
done
