### ISSUE TITLE
Feat: allow mentionning or linking after some punctuation marks

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4795]
## Feature description and goals

For now, mentions (or content links) will only work at the beginning of a text or before a white space character.
I'd really like to be able to create a mention without using a space before the `@`. For instance, after an opening parenthesis:

```
Some people complained about X being too FOO (@raphj for instance)
```

## Related PR
PR #6058

**Comment by Relf-Algoo** [comment]
This has been discussed on 2022/02/09, regarding punctuation marks at the end of mentions (example: `Thansk, @raphj.`) on the thread 53542 in our tracim instance.
This subject has been validated by several users and should be prioritised one way or another.
