### ISSUE TITLE
Bug: Sometimes we have a blank page in publications

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4805]
## Description and expectations

Sometimes we have a blank page in publications, error details:

> Uncaught (in promise) TypeError: URL constructor: is not a valid URL.

![Capture d’écran de 2021-07-16 09-25-30](https://user-images.githubusercontent.com/35422692/125909076-a4aa0d91-4784-430c-9357-4159310157b0.png)

### Version information

- Tracim version: at least 3.9
- Web browser: Google Chrome, Firefox
- Device / System: PC

________________________________________________

**Comment by charline-rageade** [comment]
Tested on branch

**Comment by PhilippeAccorsi** [comment]
Done in 3.9.1
