### ISSUE TITLE
Bug: autocomplete for link not working in tinymce with special caracters like `é`

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#4813]
## Description and expectations

I try to add a link to a document named `Procédure - ....` and the autocomplétion work when I'm in a simple text area but not working when I am in the rich text (with Tinymce).
Tinymce transform `#Procé` to `<p>#proc&eacute;</p>` (visible in source code) so Tracim can't find title with `&eacute;`.

### How to reproduce

- create a content with `é` in the title name
- open tinymce (in comment or note)
- try to add link by adding `#` (this is open link list)
- add `é`
=> now the list is closed automatically. You need to erase all letters to open link list again

### Version information

- Tracim version: 3.9.x
- Web browser: firefox
- Version: 78.7.0
- Device / System: Debian 10

## Screenshots

I can give gif if its necessary.

## Linked PR
PR #5571

**Comment by Skylsmoi** [comment]
tested on branch

**Comment by knodelle** [comment]
done
