### ISSUE TITLE
Bug: dependabot detects something wrong and this error creates a wrong config file

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#4814]
## Description and expectations

In the file `backend/setup.py` we have this line `"apispec-marshmallow-advanced>=0.4" "apispec==2.0.2",` (we seen missing `,`) and in `backend/tracim_backend.egg-info/requires.txt` we seen `apispec-marshmallow-advanced>=0.4apispec==2.0.2`.

### Version information

Wrong syntax exist since 06/08/2020

## Linked PR
PR #5691

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by gbonaspetti** [comment]
Done
