### ISSUE TITLE
Bug: File preview doesn't work well on mobile

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4824]
## Description and expectations

File preview doesn't work well on mobile. It should have a restricted area.

![mCoEk8p](https://user-images.githubusercontent.com/35422692/126755451-c6f2eec2-604b-49ec-b97b-8bb3390e01d7.jpg)

### How to reproduce

1. Open a content
2. Click on the first revision

### Version information

- Tracim version: v3.9
- Device / System: Mobile

________________________________________________

## PR

#5165

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by knodelle** [comment]
done
