### ISSUE TITLE
Misc: Find technical solution to return more than 10 items per facets in search

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#4829]
## Description

Find a solution to return more than 10 items per facets in backend search.
This issue is the first part of a change for search, the second part is #5380

Original issue text:
> ## At present
> 
> I have tried to search `Publication de Philippe` and in the search filter, I can't seen all space where I have some publication. I want to filter space `Stand up` but it is not possible because no facet exist with this name (in the results, I can seen some publication inside this space).
> 
> If I tried to search `"Publication de Philippe"` I can filter with facet `Stand up`.
> 
> After small investigation, we saw that all facets are limited to 10 items.
> 
> ## Expected
> 
> - [ ] Do not limit the results (maybe paginate them) 

## Implemented solution:
#5381
- add fixed value in code about number of item per facets

**Comment by inkhey** [comment]
After some search, it possible to set the limit from 10 to 65,536 keeping the same mecanism, if we do want to have not real limit, we do need to change the mecanism:
 https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-size

I do suggest to : 
- add pagination in frontend after some size
- have a different default than 10, it may be possible to make it a parameter either for the frontend or for the backend (add a config parameter in `development.ini`).

**Comment by inkhey** [comment]
To test this:
Just test elasticsearch search and verify you have at max 10 result (may be 7 for file extension as frontend does merge .something.html file extensions into .html).

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by knodelle** [comment]
done
