### ISSUE TITLE
Feat: Show mentions instead notifications in notification wall button

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4858]
## Feature description and goals

- [x] When the user has notifications that are not mentions, the notification wall button should show a blue circle without any text inside (see image below)
  - Background: lightBlue
  - Size: 15px. If pertinent, add three values at `Variable.styl` one for each circle size, something like :
    - notificationCircleSize = 15px
    - mentionCircleSize = 20px
    - wallCircleSize = 8px

![notificationBtn](https://user-images.githubusercontent.com/35422692/128892654-59d07cb9-5124-4155-a588-5806310a3c42.png)

- [x] When the user has at least one notification that is a mention, the notification wall button should show a orange circle with the number of mentions (see image below).
  - Background: warningOrange
  - Size: 20px

![mentionBtn](https://user-images.githubusercontent.com/35422692/128892829-7de053e2-f93e-4235-b4bf-9c38bbe53aa1.png)

- [x] Change warningOrange constant at `Variable.styl` from `#f2a027` to `#ff8a00`

## Prerequisites

None

**Comment by MariePrandstetter** [comment]
What you mean by wallCircleSize? For what CSS property is it meant to be?

**Comment by charline-rageade** [comment]
tested on branch
