### ISSUE TITLE
Feat: show the Tracim database version in the api /api/system/about

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#4862]
## Feature description and goals

We can seen the last commit id with `/api/system/about`. 
To create the changelog and permit simple rollback of the Tracim db, we need to know what is the db version for each new release. To do that we can create a new installation and look inside the db or use the command `alembic -c development.ini current` but this is not freindly user for the person who write the changelog.

If we add the db version in the `/api/system/about`, this person can seen version of db when he testing the last version of code. Whis that, it is very simple to add db version in the changelog and if necessary, its really easy to know what is the db version I need to put in command like that `alembic -c development.ini downgrade <database_revision>`.

## Implemented solution

#5377

- add database_version parameter to about config, which is null in case of missing table, with a warning log about a potential issue.

**Comment by inkhey** [comment]
To test this:
- Test endpoint with Postgresql and sqlite
- Test endpoint with missing migrate_versions table.

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by lebouquetin** [comment]
This is not a `database_version` actually but a data model version :-(

**Comment by knodelle** [comment]
done
