### ISSUE TITLE
Feat: Calibration of cover and avatar profile photos 

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4867]
## Feature description and goals

To improve the user experience, the platform should make it possible to calibrate the photo before saving it.
Below a user case to demonstrate the idea. The images are just to exemplify, they don't need to be take it literally.

User case - changing profile's cover (step by step):
- The user clicks on "Change cover"
- The upload popup opens
- The user chose their cover image and validate
![Capture d’écran de 2021-08-18 15-12-32](https://user-images.githubusercontent.com/35422692/129904439-a5642815-c876-42cd-830d-b1c19bf5dc01.png)
- The popup will be replaced by another one that contain the image with the original ratio and a cropper with the profile cover ratio
![crop](https://user-images.githubusercontent.com/35422692/129907525-cdbf665e-a31b-42ba-8896-b58221b703d1.png)
- When the user validates, the profile picture is changed.

- [x] Implement the second popup before validation
- [x] Use [react-cropper](https://github.com/react-cropper/react-cropper) for the cropper
- [x] The cropper ratio should be fixed with the cover/avatar ratio (the user can't change this ratio) 

## Prerequisites

None

**Comment by MariePrandstetter** [comment]
tested on branch

**Comment by knodelle** [comment]
done
