### ISSUE TITLE
Feat: Have the "Play" button on header for video files

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4873]
## Feature description and goals

Have the "Play" button always visible on header for video files.

![Capture d’écran de 2021-08-23 10-35-48](https://user-images.githubusercontent.com/35422692/130416813-3e517a4a-abcf-4c71-9b64-1adab2d38b2e.png)

## Prerequisites

None

## PR
https://github.com/tracim/tracim/pull/5852

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by Millefeuille42** [comment]
Done
