### ISSUE TITLE
Feat: Improve the frontend development and build system

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4894]
## Feature description and goals

We shall bring some improvements the frontend development and build system.

### Step 1: make React hooks work in development servers (a.k.a servdevs)

For hooks to work, we shall have only one copy of React in the web page

#### Substep 1.1 use optimized builds and externals in servdev

Optimized builds avoid having several copies of React in Tracim. We shall use this mechanism in servdev by
 - [x] including frontend vendors and tracim frontend lib in index.html files used in servdevs
 - [x] using webpack.optimized.config.js in servdev, to add vendors and tracim frontend lib in servdev

#### Substep 1.2 stop using tracim frontend lib in externals

- [ ] Substep 1.1 introduces a regression where recompiling tracim frontend lib does not refresh the page automatically anymore in servdev. To avoid this issue, we shall create a webpack.servdev.config.js for each frontend component and exclude tracim_frontend_lib from externals

### Step 2 

- [x] We shall unify script options to enable development mode (-dev versus -d, espace versus no space)
- [x] We shall provide a webpack.standalone.config.js to build standalone apps (which we don't use in the tracim project). Those will probably only be something like `export default require('./webpack.config.js').

### Step 3 and 4 (unordered)
 - React should be in the peerDependencies and devDependencies of React libraries and not in their dependencies. We probably should do this for frontend_lib, and for apps. This is arguable for standalone apps however.
 - We should find a way to live refresh the pages when editing a file in fontend_lib.

___
# PR
https://github.com/tracim/tracim/pull/5219

**Comment by Skylsmoi** [comment]
- [x] frontend dev should only use
  - `yarn run servdev`
  - `./build_app.sh` [-d]
  - `yarn run build:translation (the `-` is now a `:`)`
  - `yarn run test`
- [x] add README.md for each apps
- [x] debug.js is now git ignored. It is still created from debug.js.sample and created by ./build_app.sh
  - [x] but build_app.sh doesn't overrides it if it already exists, so now developers can modify it depending on their local database
- [x] apps unit tests don't rely on debug.js, they now rely on test/fixture/defaultProps.js which is also created by build_app.sh
- [x] harmonize yarn script naming using only `:` for modifiers
- [x] harmonize webpack scripts (now 3 scripts, one for standalone build, one for optimized build and one for servdev)

**Comment by Skylsmoi** [comment]
Since production only uses .sh scripts at the root the repository, there won't be any change for production.

**Comment by Skylsmoi** [comment]
For tester:
do
```
./install_frontend_dependencies.sh
./build_full_frontend.sh
./run_dev_backend.sh
```
and then check that tracim is running with pushpish and that apps are working

Also check that it works with frontend servdev

You can also check at least one app servdev by following its README.md information

**Comment by gbonaspetti** [comment]
Tested on branch.

**Comment by Skylsmoi** [comment]
following developments here: https://github.com/tracim/tracim/issues/5247

**Comment by Skylsmoi** [comment]
Putting here my cleanup.sh script that I used for development.

It removes every files that are generated by frontend scripts (yarn or shell)
It doesn't delete node_modules folders

``` bash
rm /home/come/repo/tracim/frontend/dist/app/*.js
rm /home/come/repo/tracim/frontend/dist/app/*.json
rm /home/come/repo/tracim/frontend/dist/assets/*.js
rm /home/come/repo/tracim/frontend/dist/assets/*.js

rm /home/come/repo/tracim/frontend_app_admin_workspace_user/dist/*.app.*
rm /home/come/repo/tracim/frontend_app_admin_workspace_user/src/debug.js
rm /home/come/repo/tracim/frontend_app_admin_workspace_user/test/fixture/defaultProps.js

rm /home/come/repo/tracim/frontend_app_agenda/dist/*.app.*
rm /home/come/repo/tracim/frontend_app_agenda/src/debug.js
rm /home/come/repo/tracim/frontend_app_agenda/test/fixture/defaultProps.js

rm /home/come/repo/tracim/frontend_app_collaborative_document_edition/dist/*.app.*
rm /home/come/repo/tracim/frontend_app_collaborative_document_edition/src/debug.js
rm /home/come/repo/tracim/frontend_app_collaborative_document_edition/test/fixture/defaultProps.js

rm /home/come/repo/tracim/frontend_app_custom-form/dist/*.app.*
rm /home/come/repo/tracim/frontend_app_custom/src/debug.js
rm /home/come/repo/tracim/frontend_app_custom/test/fixture/defaultProps.js

rm /home/come/repo/tracim/frontend_app_file/dist/*.app.*
rm /home/come/repo/tracim/frontend_app_file/src/debug.js
rm /home/come/repo/tracim/frontend_app_file/test/fixture/defaultProps.js

rm /home/come/repo/tracim/frontend_app_folder_advanced/dist/*.app.*
rm /home/come/repo/tracim/frontend_app_folder_advanced/src/debug.js
rm /home/come/repo/tracim/frontend_app_folder_advanced/test/fixture/defaultProps.js

rm /home/come/repo/tracim/frontend_app_gallery/dist/*.app.*
rm /home/come/repo/tracim/frontend_app_gallery/src/debug.js
rm /home/come/repo/tracim/frontend_app_gallery/test/fixture/defaultProps.js

rm /home/come/repo/tracim/frontend_app_html-document/dist/*.app.*
rm /home/come/repo/tracim/frontend_app_html/src/debug.js
rm /home/come/repo/tracim/frontend_app_html/test/fixture/defaultProps.js

rm /home/come/repo/tracim/frontend_app_share_folder_advanced/dist/*.app.*
rm /home/come/repo/tracim/frontend_app_share_folder_advanced/src/debug.js
rm /home/come/repo/tracim/frontend_app_share_folder_advanced/test/fixture/defaultProps.js

rm /home/come/repo/tracim/frontend_app_thread/dist/*.app.*
rm /home/come/repo/tracim/frontend_app_thread/src/debug.js
rm /home/come/repo/tracim/frontend_app_thread/test/fixture/defaultProps.js

rm /home/come/repo/tracim/frontend_app_workspace/dist/*.app.*
rm /home/come/repo/tracim/frontend_app_workspace/src/debug.js
rm /home/come/repo/tracim/frontend_app_workspace/test/fixture/defaultProps.js

rm /home/come/repo/tracim/frontend_app_workspace_advanced/dist/*.app.*
rm /home/come/repo/tracim/frontend_app_workspace_advanced/src/debug.js
rm /home/come/repo/tracim/frontend_app_workspace_advanced/test/fixture/defaultProps.js

rm /home/come/repo/tracim/frontend_app_kanban/dist/*.app.*
rm /home/come/repo/tracim/frontend_app_kanban/src/debug.js
rm /home/come/repo/tracim/frontend_app_kanban/test/fixture/defaultProps.js

rm /home/come/repo/tracim/frontend_lib/dist/*.js

rm /home/come/repo/tracim/frontend_vendors/dist/*.js
```

**Comment by knodelle** [comment]
done
