### ISSUE TITLE
Misc: write functional tests for the timeline after switching contents in the same app

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4898]
## Description and expectations

We had a bug during an integration where the timeline was not shown after switching contents in the same app, fixed by commit e99db73f59bcdf7304511edfaedd1ab0d5005e70.

We shall write functional tests which check that after a switch:
 - comments can be sent and are seen in the timeline
 - the right revisions are shown
 - the right comments are shown

PR: #5106

**Comment by lebouquetin** [comment]
As soon as the feature has been implemented, this issue is to be worked on after other features.

**Comment by knodelle** [comment]
done
