### ISSUE TITLE
Bug: The "created" revision is sometimes before the first comment on publications

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#4907]
## Description and expectations

Sometimes the first comment come before the "created" revision and we expecte that this revision come always first.

- [x] The algorithm should be a bit more clever by taking into account both created, revision_id and content_id properties. A content with a bigger content_id is necessarily younger. Same remark for a bigger revision_id.

### How to reproduce

1. send a publication

Note: not systematic.

### Version information

- Tracim version: v4.0

### Screenshot
![Capture d’écran du 2021-09-07 16-54-37](https://user-images.githubusercontent.com/82377347/132366329-8a19c85f-57e7-475a-a971-85b2e98b6693.png)

### Diagnostic

As said in https://github.com/tracim/tracim/issues/4907#issuecomment-949427264 the timeline is filled from 2 lists of objects that are merged. The algorithm implemented in frontend is very basic and don't differentiate revision from comment. So if both have the same creation time, there are no criteria for what we put first.

## Linked PR
https://github.com/tracim/tracim/pull/5151

**Comment by charline-rageade** [comment]
@lebouquetin what priority you give to this ticket ?
Should it be managed for 3.10 or just investigated first?

**Comment by lebouquetin** [comment]
light investigation may be done right now (only to identify if the problem comes from backend or frontend). Fixing it is for maintainance release after 3.10

**Comment by knodelle** [comment]
tested on branch

**Comment by knodelle** [comment]
done
