### ISSUE TITLE
Bug: Member mentions do not work all the time

### ISSUE THREAD

**Issue by agile-marmot** [tracim/tracim#4926]
### How to reproduce

1. Go to a content
2. Mention somebody

It doesn't work for all members

## Screenshots
![Capture d’écran du 2021-09-16 16-23-31](https://user-images.githubusercontent.com/82377347/133629634-525c5ed5-0e81-441f-a2d2-08b247636a83.png)

________________________________________________

## Linked PR
#6005

**Comment by charline-rageade** [comment]
This bug was detected in a particular space. It will be necessary to check during Sprint 6 that it is not reproduced on the internal instance.

**Comment by Millefeuille42** [comment]
Tested on branch

**Comment by gbonaspetti** [comment]
Done
