### ISSUE TITLE
Bug: on a small screen the dropdown-toggle text does not appear all the time

### ISSUE THREAD

**Issue by charline-rageade** [tracim/tracim#4928]
### How to reproduce

1. Use a smartphone or reduce your reduce the size of your screen with development tools
2. Click on the three small dots at the top right of the content

### Version information

- Tracim version: [4.0 Tracim]
- Device / System: [smartphone]

## Screenshots
![6iEx4qE](https://user-images.githubusercontent.com/82377347/133635042-2c6af5f2-c087-4c8b-88a7-a027c544d4b1.png)
![iuRNiAm](https://user-images.githubusercontent.com/82377347/133635047-14abed52-37a9-4850-8a7d-06654fdc55b6.png)
![fh9Q7At](https://user-images.githubusercontent.com/82377347/133635049-d3ccc053-c279-458f-a7fc-9847eca5edb7.png)]

________________________________________________

## Diagnostic
Add a text to textModile for every IconButtons 

## Linked PR
#5115

**Comment by lebouquetin** [comment]
I think this is not P0: there are plenty of other small-screen related bugs which make Tracim unusable

**Comment by charline-rageade** [comment]
@lebouquetin p3 or for the next release with work on responsive

**Comment by MariePrandstetter** [comment]
tested on branch

**Comment by knodelle** [comment]
done
