### ISSUE TITLE
Bug: Deleting a comment generates a "X has commented in Y" notification

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#4933]
## Description and expectations

Deleting a comment generates a "X has commented in Y" notification. It should not generates any or change the text for something like "X deleted a comment in Y".

### How to reproduce

1. Go to a thread
2. Comment something
3. Delete your comment
4. In another user account, see the notifications.

### Version information

- Tracim version: v3.9
- Web browser: Google Chrome
- Device / System: PC

________________________________________________

## Prerequisites

None

**Comment by Skylsmoi** [comment]
can't reproduce. Closing
