### ISSUE TITLE
Radical client_base_url config weakness

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#496]
When `radicale.client.base_url.host` config dont specify "http://" or "https://" in value, caldav javascript fail to parse url. Example:

If config is:

> radicale.client.base_url.host = myweb.site

Instead:

> radicale.client.base_url.host = http://myweb.site

An javascript error will be raise in `algoo_replace_regex` function because regular expression need "http" in url: `/^(https?:\/\/)(.*)/i`.

Expected: Javascript don't fail if "http://" or "https://" is missing in config value.

**Comment by lebouquetin** [comment]
suggestion: what about forcing the presence of `http://` or `https://` in the config, otherwise refuse to start ?

**Comment by buxx** [comment]
Can be a good solution but require to know if website is in httpS or not. I think we can guess it by looking website.base_url .
