### ISSUE TITLE
Feat: the reactions should be aligned with the reaction button

### ISSUE THREAD

**Issue by knodelle** [tracim/tracim#4975]
## Feature description and goals

The reaction button has been aligned with the comment button in the publications in this pr : https://github.com/tracim/tracim/pull/4956
But the reactions are not aligned with the button. 

- [ ] Fix this alignment
- [ ] Fix the position of the reaction button in the activities feed, it should have a 10px margin on the right

**Comment by wwalden** [comment]
This issue seems to be already solved
