### ISSUE TITLE
Bug: Loading a space content list usually does 3 api calls to get the read statuses

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#4985]
## Description and expectations

When loading a space content, we can see 3 calls to GET `http://localhost:7999/api/users/me/workspaces/:workspace_id/contents/read_status` while only one is required.

This is an issue because this endpoint takes time an consume backend resources so doing it 3 times increase the response time a lot.

### How to reproduce

Load a space's content list page.
You can see the 3 calls in network panel of dev tools.

### Version information

- Tracim version: v3.9.2 build 056
- Web browser: Firefox
- Version: latest
- Device / System: desktop

________________________________________________

## Diagnostic

The 3 calls are:
- 1 from frontend/src/container/WorkspaceContent.jsx in componentIdMount
- 2 from frontend/src/container/WorkspaceContent.jsx in componentDidUpdate
- 3 from frontend/src/container/WorkspaceContent.jsx in componentDidUpdate

The only call that should stay for that use case is the first one. The calls 2 and 3 should only happen for when the workspace has changed.
The calls 2 and 3 are because the variable `hasWorkspaceIdChanged` in the componentDidUpate is `true` while it should be `false`.
It is true because it compares the state `workspaceIdInUrl` with the workspace id from url.
And since setState is asyncrhonous while the id in url doesn't change, there are differences.

I think that the differences are because the state is undefined for a while (since the setState is asynchronous) and that makes the variable `hasWorkspaceIdChanged` to be true. I haven't confirmed this.

### Linked PR
#5108

**Comment by Skylsmoi** [comment]
related backend issue https://github.com/tracim/tracim/issues/2888

**Comment by raphj** [comment]
Thanks for the investigation. Shouldn't we keep a call in componentDidUpdate though? Don't we need the read status of the new space if the space changes?

**Comment by Skylsmoi** [comment]
Sure we need to
But the related `if` should not use the `workspaceIdInUrl` state

**Comment by Skylsmoi** [comment]
When I said "the calls 2 and 3 should be removed", I didn't mean to remove the code, just that these calls should not happen while loading the page

**Comment by Skylsmoi** [comment]
Yes we should.
I had created it at the very beginning of tracim v2 to have a shorthand to the props.match.params.idws
But using an asynchronous state for that purpose was a design flaw

**Comment by raphj** [comment]
Thanks for the explanation and the confirmation!

**Comment by PhilippeAccorsi** [comment]
I don't know if it is the same problem but when I open a small thread (2 comment, 3 version of document and 7 reaction) I can seen in console:
- 9 PUT of this `https://******/api/users/233/messages/read?content_ids=40209&parent_ids=40209`
- 1 PUT of this `https://******/api/users/233/workspaces/162/contents/40209/read`

@Skylsmoi @grignards

**Comment by raphj** [comment]
@PhilippeAccorsi This would be a separate issue I think. Probably works as intended, you probably had 9 notifications to mark as read, and we unconditionally mark any content as read. We would need to change the way things work to change this. Which is not to say we shouldn't.

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by grignards** [comment]
> @PhilippeAccorsi This would be a separate issue I think. Probably works as intended, you probably had 9 notifications to mark as read, and we unconditionally mark any content as read. We would need to change the way things work to change this. Which is not to say we shouldn't.

Whatever the number of notifications to mark as read there should only be one call to the API as its semantic is "mark all notifications related to the content" where "related to" means either the notification's content or parent content is the one provided to the API call.

**Comment by raphj** [comment]
Ok, so this is an issue. Should we fix this soon? @grignards @lebouquetin @charline-rageade

**Comment by lebouquetin** [comment]
> 9 PUT of this https://******/api/users/233/messages/read?content_ids=40209&parent_ids=40209

I do not understand why we have a parameter `content_ids` (in plural form) and we pop 9 HTTP requests instead of one (including 9 content_ids as a parameter). This is another issue, I think.

> Should we fix this soon? 

What is the impact on server load? At the moment it does not look like this is the origin of our problems, so this is not a  priority; but we can add it to Tracim 4.1 backlog @raphj

**Comment by knodelle** [comment]
done
