### ISSUE TITLE
Feat: Link to a specific comment

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#5000]
## Feature description and goals

I find myself often wanting to link to a specific Tracim comment.

Use case: link to a decision. Tracim is a platform where decisions within a team are made, and they are made in documents or comments (discussions). It could be a link in Tracim itself, or in a source code implementing a decision, so the reader who could be surprised  by a chunk of code can actually read the full context behind this code.

Current version: Tracim 3.10.

**Comment by Quiwy** [comment]
Duplicate of #2630.
