### ISSUE TITLE
Feat : have desktop/native notifications for the calls

### ISSUE THREAD

**Issue by knodelle** [tracim/tracim#5004]
## Feature description and goals

Show a desktop notification in the callee's browser when they receive a call. 
This popup window should display the same information than the tracim popup :
- [x] Display "XXX is calling you on Tracim"

## Prerequisites

PR: #5017

**Comment by lebouquetin** [comment]
@MariePrandstetter  instead of displaying "go to your tracim app" I'd like to display "XXX is calling you" (or the right sentence - I'm open to suggestions)

**Comment by lebouquetin** [comment]
Im aware in 10 minutes
