### ISSUE TITLE
Bug: RAW images preview is not possible anymore with the official docker image

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#5008]
## Description and expectations

It is not possible to preview RAW images from cameras with the official docker image starting with version 3.10.
RAW image support should be re-enabled.

### How to reproduce

1. Upload a RAW picture
2. Preview generation is not done

### Version information

- Tracim version: 3.10 using the official docker image
- Web browser: not relevant
- Version: not relevant
- Device / System: not relevant

## Screenshots

________________________________________________

## Diagnostic

The RAW image preview Tracim provides is based on the `ufraw-batch` utility. This utility is not available in Debian bullseye that is used as the official docker image base starting with version 3.10.
We need to find another way to preview RAW images, please see https://github.com/algoo/preview-generator/issues/249.

## Implemented solution 
#5121 
- update to preview-generator 0.28 with the new rawpy based raw builder

**Comment by gbonaspetti** [comment]
Done
