### ISSUE TITLE
Misc: display read status of contents asynchronously

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#5009]
## Feature description and goals

When I display a shared space, it can be long before I can see the contents. I can see the contents are displayed only when "read_status" api respond : 

![Capture d’écran de 2021-10-18 11-20-19](https://user-images.githubusercontent.com/1104637/137704789-659e9cde-8355-4362-9409-6135fdec6c55.png)

My suggestion is : display contents immediately and change their appearance according to read status when "read_status" api respond.

## Linked PR
#5024

**Comment by raphj** [comment]
We probably should not wait for the read status to load before displaying the space content.

See also #2888 and #4985

**Comment by buxx** [comment]
![2021-10-19_14-12](https://user-images.githubusercontent.com/1104637/137906953-5835c4aa-25f3-48b7-99ca-24cc46db7ba6.png)

![2021-10-19_14-13](https://user-images.githubusercontent.com/1104637/137906962-b829bf5e-a016-418b-a76f-62baf9d7db75.png)
