### ISSUE TITLE
Error while using webdav with windows 7 and 10

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#504]
**At present:**

When you tried to move, copy, put file with webdav, sometime, an error occured: Windows error "0x8007003A"

Here you can find log when copy (with same name) is working and create not working.

[copy_not_working.txt](https://github.com/tracim/tracim/files/1506751/copy_not_working.txt)
[copy_working.txt](https://github.com/tracim/tracim/files/1506753/copy_working.txt)

**philippe 4:46 PM**
Une requette sur 2 à un "401 Access not authorized", (les 2 requettes semble identique à chaque fois, la première erreur 401, la seconde code 200 OK. Cas de copy qui ne marche pas : dans l'ordre j'ai PROPFIND Request, PUT Request, LOCK Request , HEAD Request, PUT Request (1 fois qui plante) , HEAD Request, PUT Request.

**Comment by lebouquetin** [comment]
https://support.microsoft.com/fr-lu/help/2673544/windows-7-cannot-automatically-reconnect-a-dav-share-when-basic-authen

**Comment by lebouquetin** [comment]
Another link: https://support.microsoft.com/en-us/help/943280/prompt-for-credentials-when-you-access-webdav-based-fqdn-sites-in-wind

**Comment by lebouquetin** [comment]
@PhilippeAccorsi could you test webdav on windows using:

- cyberduck: https://cyberduck.io/
- webdrive: https://southrivertech.com/products/webdrive/ ?
- https://www.netdrive.net/download/

**Comment by lebouquetin** [comment]
Another interesting link : https://www.greenbytes.de/tech/webdav/webdav-redirector-list.html#issue-credentials-not-sent

**Comment by lebouquetin** [comment]
Another interesting subject : 
- https://stackoverflow.com/questions/23926497/custom-webdav-server-does-not-work-with-windows-7-mini-redirector/24129054#24129054
- http://dark9t.github.io/blog/2014/06/02/why-digest-authentication-fails-in-windows-7-mini-redirector/

**Comment by PhilippeAccorsi** [comment]
Its possible to work without problem if you use an other client for webdav:

Here you find windows client working without error:

- Cyberduck (you can use with same view like filezilla, its hard to use)

- WebDrive (you can use in windows explorer, very easy to use and very fast)

-WinSCP (you can use with view between Cyberduck and Webdrive, its not very difficult to use.  "Keep Remote Directory up to Date" not working good).

**Comment by buxx** [comment]
Need to be re-tested in controled and validaed environment but previous manual tests says: On algoo.trac.im prod, without nginx, bug not reproductible with windows 10 and 7.
