### ISSUE TITLE
Misc: Mysql and Mariadb are not officially supported anymore

### ISSUE THREAD

**Issue by knodelle** [tracim/tracim#5043]
## Description and expectations

Should anyone need support for those database systems, please create issues in the Tracim repository. If nobody needs this support, we'll remove MySQL and MariaDB in the next major release, 4.1.0

### Version information

- Tracim version: v4.0.0

### MySQL and MariaDB users

If you use those databases, please comment this issue if you need support.

**Comment by Quiwy** [comment]
4.1.0 is out since January and no issue since then.
