### ISSUE TITLE
Bug: 500 error instead of 404 for page not found error in tracim 4.0

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#5046]
## Description and expectations

With the introduction of debian bulleyes/python 3.9 support, we updated some python dependencies.
This does break an egde case error with 404 error that now return with no json return (the error case is not anymore catched by hapic).

Explain:

The problem is pyramid/pyramid-retry related. 
The pyramid-retry package which goal is to retry when some specific error with pyramid-tm (transaction manager), has some breaking change from 1.0 to 2.0 version. Thoses breaking changes are done to follow a new behavior in pyramid >2.0, as we stay in pyramid 1.10.8 because of compatibility issues, we stay in some in between case here.

A quick fix is downgrading  pyramid-retry to 1.0 . Some discussion may be needed because we may also decide to:
- reconsider the need of pyramid-retry (it was done because it was a component of pyramid-sqlalchemy cookiecutter)
- check how the upgrade to pyramid 2.0 impact this kind of issue. ()

see also:
https://github.com/Pylons/pyramid_retry/pull/17

### How to reproduce

- go to api url that doesn't exist like `http://localhost:7999/api/thisurldoesnotexist`

### Version information

- Tracim version: 4.0

## Implemented solution:
https://github.com/tracim/tracim/pull/5057
- downgrading to pyramid-retry=1.0
- splitting not found from frontend controller to have proper automated test for this error case.

**Comment by inkhey** [comment]
@gbonaspetti I added this issue in tracim v4.x backlog, but as this is a regression from v4 ,  we may want to put it in maintenance/4.0 instead of develop.

**Comment by gbonaspetti** [comment]
ok for me (cc @MariePrandstetter @grignards )

**Comment by MariePrandstetter** [comment]
done
