### ISSUE TITLE
Feat: Use Pyramid >=2.0 as python dependencies

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#5047]
## Feature description and goals

Update python dependencies for pyramid to support pyramid>=2.0
:warning: pyramid plugins may need to be updated too.

## Prerequisites

- https://github.com/tracim/tracim/issues/5046

## Implemented solution:

- remove pyramid-retry
- use compatibility layer (TracimSecurityPolicy) to keep current authentifications
- few fix in our custom authentifications to avoid infinite loop issue due to behavior change in pyramid 2.

PR ref: #5460

**Comment by inkhey** [comment]
When updating pyramid to version 2.0, some check should be done about pyramid-retry, as the not found error may be broken related to it, check : https://github.com/tracim/tracim/issues/5046

**Comment by grignards** [comment]
Could also be the time to rationalize the use of pyramid plugins (pyramid-retry usefulness is unclear) and authorization mechanism.

**Comment by knodelle** [comment]
done
