### ISSUE TITLE
Regression: preview of http link is brokend since tracim use bullseye on docker image

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#5048]
## Description and expectations

For all link visible in a comment, Tracim try to generate a preview of the link. Now, Tracim backend show an 500 error about this preview and a red flash message is visible in the frontend.

### How to reproduce

- add link in a comment, example `https://meet.jit.si/`
- validate the comment
=> error is directly visible

### Version information

- Tracim version: 4.0.0
- Web browser: Firefox
- Version: 93.0
- Device / System: Ubuntu 20.04

## Screenshots

![Screenshot 2021-11-02 at 09-58-42 (3) Activités récentes · Algoo](https://user-images.githubusercontent.com/25848257/139816377-3babadf8-7c80-4749-a65c-fc8206cc0201.png)

## Linked PR
#5053

**Comment by grignards** [comment]
In fact this bug seems to occur only with meet.jit.si: the preview image URL is relative, which is not authorized by the validation (and wouldn't work even if it is).

**Comment by grignards** [comment]
OK, I found the "culprit": https://github.com/tracim/tracim/blob/develop/backend/tracim_backend/views/processor.py has been introduced with 4.0.0. This changes the behavior of Tracim in case the backend response doesn't not match the schema which is defined for it.

**Comment by raphj** [comment]
> This behavior change explains the "new" 500 error (where previously the error was silenced)

Should we do something about this?

**Comment by PhilippeAccorsi** [comment]
I know test exist for this feature. Maybe the test is not correct if he not detect problem.

**Comment by grignards** [comment]
> > This behavior change explains the "new" 500 error (where previously the error was silenced)
> 
> Should we do something about this?

No, I think the new behavior is better: it is indeed an error when the schema validation fails.

**Comment by grignards** [comment]
> I know test exist for this feature. Maybe the test is not correct if he not detect problem.

There was several test cases, but not one with a relative preview image url. I added the test case in the related PR.

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by MariePrandstetter** [comment]
Done.
