### ISSUE TITLE
Bug: Local storage is keeping the previous text in the publications text area

### ISSUE THREAD

**Issue by MariePrandstetter** [tracim/tracim#5049]
### How to reproduce

1. Go to publications
2. Write a publication and post it
2. Refresh the page
3. The text of the previous publication is still in the text area

### Version information

- Tracim version: [e.g. v2.7, Mon Tracim]
- Web browser: [e.g. Google Chrome, Firefox, Safari]
- Version: [e.g. 22, latest]
- Device / System: [e.g. PC, iPhone 6]

## Linked PR
#5054
________________________________________________

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by MariePrandstetter** [comment]
Done.
