### ISSUE TITLE
Caldav: Calendar name replaced by "..."

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#505]
Calendar name replaced by "..." chars when no enough width. It could be great if name can be truncated instead replaced.

To reproduce: reduce width (tested under Firefox, Debian 9 by @lebouquetin)

**Comment by lebouquetin** [comment]
@Skylsmoi the bug is still there. Could you fix it totally? Let's see on the demo site page : https://demo.tracim.fr/calendar

**Comment by Quiwy** [comment]
@buxx : can't reproduce it, does it still a bug?

**Comment by buxx** [comment]
I think it is outdaded, I close :)
