### ISSUE TITLE
Bug: impossible to find user with search. Indexing user profil is broken when user add image in his profil or when profil is too big

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#5055]
## Description and expectations

We can not find user with Tracim search. 

I can see this error when indexing user with elasticsearch
~~~
2021-11-02 11:14:18 ERROR [tracim:54][MainThread] [ESUserIndexer] Exception while indexing user 233
Traceback (most recent call last):
  File "/tracim/backend/tracim_backend/lib/search/elasticsearch_search/elasticsearch_search.py", line 1146, in index_user
    search_api.index_user(user)
  File "/tracim/backend/tracim_backend/lib/search/elasticsearch_search/elasticsearch_search.py", line 351, in index_user
    indexed_user.save(
  File "/usr/local/lib/python3.9/dist-packages/elasticsearch_dsl/document.py", line 452, in save
    meta = es.index(
  File "/usr/local/lib/python3.9/dist-packages/elasticsearch/client/utils.py", line 168, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/elasticsearch/client/__init__.py", line 406, in index
    return self.transport.perform_request(
  File "/usr/local/lib/python3.9/dist-packages/elasticsearch/transport.py", line 415, in perform_request
    raise e
  File "/usr/local/lib/python3.9/dist-packages/elasticsearch/transport.py", line 381, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.9/dist-packages/elasticsearch/connection/http_urllib3.py", line 275, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.9/dist-packages/elasticsearch/connection/base.py", line 330, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'Document contains at least one immense term in field="custom_properties.personal_page.exact" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: \'[60, 112, 62, 77, 111, 110, 32, 105, 100, 111, 108, 101, 32, 40, 111, 117, 32, 112, 97, 115, 41, 60, 47, 112, 62, 10, 60, 112, 62, 60]...\', original message: bytes can be at most 32766 in length; got 297041')
~~~

### How to reproduce

- Add some images in user public profil
- Try to index user
=> error visible in log

### Version information

- Tracim version: since public profil is available in Tracim

## Implemented solution 
#5058

- add a maximum length for token for text in elasticsearch schema.
- add the "ignore_above" parameter to all keyword to avoid too big keyword case in elasticsearch schema.

**Comment by lebouquetin** [comment]
What is the amout of work in order to fix this? @inkhey @grignards

**Comment by grignards** [comment]
The problem comes from embedded images which are exceeding the maximum size for a single *term* (e.g. word) in the public page field.
A solution would be to filter-out the image tags before indexing the public page. Using beautifulsoup it shouldn't be much work I think.

**Comment by grignards** [comment]
BTW this bug not only affects users, but also:
- comments content
- notes content
- spaces description
provided that their field contain an image bigger than 32kB.

**Comment by inkhey** [comment]
> BTW this bug not only affects users, but also:
> 
>     * comments content
> 
>     * notes content
> 
>     * spaces description
>       provided that their field contain an image bigger than 32kB.

Is it possible that a note content without image/video/audio may be bigger than 32Kb without containing any base64 file ?

**Comment by lebouquetin** [comment]
Because it also affects comments and notes includign images (which may be common in a wiki-like usage), I suggest to fix it in a 4.0.x release.

**Comment by grignards** [comment]
After further investigations it appears that fields identified as html in search code (notes/comments/space descriptions) is not affected by this bug.
It can happen for custom properties if the schema doesn't set `format=html` to the html fields. It is properly set in the default custom properties schema.

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by MariePrandstetter** [comment]
done
