### ISSUE TITLE
Bug: on mobile, call popups are not displayed, nor call notifications

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5070]
## Description and expectations

pr #5267

- on iphone: ~the call popup does not work (except on the caller's side if he clicks on "open call")~ Resolved
- on android: the call pop up doesn't appear

### How to reproduce

1. Go to Tracim on your cellphone
2. Ask someone to call you

### Version information

- Tracim version: v4.0
- Web browser: Google Chrome, Safari
- Device / System: Huawei mate 20 pro, Redmi Netx8, iPhone 7

________________________________________________

**Comment by gbonaspetti** [comment]
Tested on branch (not on safari, but it will be tested during integration).

**Comment by Haskaris** [comment]
Tested on branch.
