### ISSUE TITLE
Bug: when editing a comment, the "Send" button is not disabled if the comment is empty

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5077]
## Description and expectations

Unlike other fields, when editing a comment, the "Send" button is not disabled if the comment is empty.
If I send I get "Error while saving the comment" (not translated).

### How to reproduce

1. Go to a content
2. Comment
3. Edit comment
4. Delete all text
5. Send

### Version information

- Tracim version: v3.9
- Web browser: Google Chrome
- Device / System: PC

________________________________________________

**Comment by ClmntBcqt** [comment]
The bug is fixed, closing the issue.
