### ISSUE TITLE
Misc: Add {{time}} to the popup message on "Call failed" popup (callee pressed X)

### ISSUE THREAD

**Issue by Haskaris** [tracim/tracim#5082]
Meta ticket: #4855

## Description and expectations
Add {{time}} to the popup message on "Call failed" popup

## Linked PR
#5085

**Comment by PhilippeAccorsi** [comment]
@Haskaris What is the date format visible in the popup ?

**Comment by Haskaris** [comment]
It's the local time for example in France: 20h30, in England: 8:30 pm
The previous sentence ``Call declined by {{username}}`` is now ``Call declined by {{username}} at {{time}}``
For example:
Call declined by Haskaris at 1:48 pm

**Comment by PhilippeAccorsi** [comment]
thanks

**Comment by MariePrandstetter** [comment]
tested on branch

**Comment by knodelle** [comment]
done
