### ISSUE TITLE
Misc: Add backend parameter for the call timeout

### ISSUE THREAD

**Issue by Haskaris** [tracim/tracim#5087]
Meta ticket: #4855

## Description and expectations
Add backend parameter for the call timeout
Do some researches about the default one (2 minutes seems a little bit long)

## Implementation
For the call timeout duration, after a quick research it appears to be between 15 and 30 seconds.
After a discussion with the team, the default value is going to be 30 seconds.

## Linked PR
#5089

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by knodelle** [comment]
done
