### ISSUE TITLE
Feat: Redirect to space settings on click to membership notifications

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5093]
## Feature description and goals

When we have a membership notification, it redirects to the space. But we have to go to space settings to approve or not the membership.

- [x] Add a Route to Space Settings (frontend_app_workspace_advanced)
- [x] Redirect the notification to the good space settings
  - member added
  - member request  

## Prerequisites

None

PR: #5123

**Comment by knodelle** [comment]
done
