### ISSUE TITLE
Bug Performance: one postgres request use too much cpu time and take long time to finish

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#5096]
## Description and expectations

I think it is related to #4870 (this is not the same request but the beginning of the request is the same).

This request take too much time to finish (near 20sec). More information in screenshot.

~~~
SELECT messages.receiver_id AS messages_receiver_id, messages.even
 _id AS messages_event_id, messages.sent AS messages_sent, messages.read AS messages_read FROM messages JOIN events ON events.event_id = messages.event_id WHERE (CAST(((events.fields -> 'content') ->> 'content_i
 ') AS INTEGER) IN (30064) OR CAST(((events.fields -> 'content') ->> 'parent_id') AS INTEGER) IN (30064)) AND messages.sent IS NOT NULL AND messages.receiver_id = 261 AND messages.read IS NULL
~~~

### How to reproduce

- open multiple News in different tab
=> tracim take too much time to open each News

### Version information

- Tracim version: 4.0.2
- Web browser: Firefox
- Version: [e.g. 22, latest]
- Device / System: Ubuntu 20.04

### Screenshots

![Capture d’écran du 2021-11-16 10-18-40](https://user-images.githubusercontent.com/25848257/141958391-4408a49f-f6cf-4ae8-a892-684f902ea004.png)

________________________________________________

## Implemented solution
https://github.com/tracim/tracim/pull/5100
- Use integer column when possible instead of json one to get better sql query performance dues to stats.

**Comment by inkhey** [comment]
The problem seems related to the fact we do use column in json whereas last patch for #4870 has added specific fields.

**Comment by grignards** [comment]
Related frontend bug which likely increases the number of requests: https://github.com/tracim/tracim/issues/4985

**Comment by inkhey** [comment]
@lebouquetin 
After some check, i discovered that only the PUT read endpoint does create such request which may take long time in some case.

I did some in situation test with @PhilippeAccorsi and we also discovered that the frontend (see #4985) has also a bug there with many unecessary request to this endpoint.

So the problem is both : 
- request is too long (backend)
- too many request (frontend)

I have a fix for the backend part, but we should consider fixing the frontend issue for the same maintenance release.

**Comment by lebouquetin** [comment]
Thanks @inkhey  . I do not see any reason not to deliver a maintaince release with this fix only.

I agree we must also fix the front-end #4985 in maintenance, but it can bé Done through another release (delivering both fixes does not need to be at the same time)

**Comment by lebouquetin** [comment]
Si the plan is:

- deliver a 4.0.x as soin as this issue is fixes
- fix #4985 as a maintainance fix
- deliver another 4.0.x as soin as possible

Also: both fixes must be reported to develop.

**Comment by PhilippeAccorsi** [comment]
What I can seen with `pg_stat_statements`

|name|result|
|--|--|
|query          | SELECT messages.receiver_id AS messages_receiver_id, messages.event_id AS messages_event_id, messages.sent AS messages_sent, messages.read AS messages_read FROM messages JOIN events ON events.event_id = messages.event_id WHERE (CAST(((events.fields -> 'content') ->> 'content_id') AS INTEGER) IN (40209) OR CAST(((events.fields -> 'content') ->> 'parent_id') AS INTEGER) IN (40209)) AND messages.sent IS NOT NULL AND messages.receiver_id = 233 AND messages.read IS NULL |
|calls          | 122|
|min_exec_time  | 35.871753|
|max_exec_time  | 18029.9901|
|mean_exec_time | 1622.193738352459|
|rows           | 85|
|hit_percent    | 84.0087108907789060|

**Comment by MariePrandstetter** [comment]
done
