### ISSUE TITLE
Feat: add validation for json shema to configurate public profile form

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#5104]
## Feature description and goals

As an admin, I have to configure the public profile json shema.

We use the json shema form available here https://rjsf-team.github.io/react-jsonschema-form/
But we add some specificity to it available here https://github.com/tracim/tracim/issues/4039#issuecomment-766859816

It is difficult and frustrating to have to put the schema live on a server to check its validity.

It would be better to have a validation feature of any sort.

It can be a form in a webpage or bash or python script.

One thing to know is that the schema for Tracim public profile **is** a valid json shema. But a valid json shema might not be valid for Tracim public profile.

The easiest way is:
- [x] create a python script that takes a json file in parameter
- [x] verify that the json schema validator validate that it is json valid. If not, call a json validator
- [x] call the json shema validator
- [x] if it is valid, call a custom parser that validate the "Mandatory things to do due to unsupported features" from the doc [here](https://github.com/tracim/tracim/issues/4039#issuecomment-766859816)
- [ ] [optional] if it is valid, check that the features put in the json are supported
  - "optional" because less priority

## Implemented solution
https://github.com/tracim/tracim/pull/5382

- refactor json schema file checking.
- add tracimcli command to check both ui and json schema file validity
- add tracim specific checks for json-schema validity.

**Comment by inkhey** [comment]
To test this:
- test invalid and invalid jsonschema and uischema file with the new command line.
- test launching tracim with valid and invalid jsonschema and uischema files (should failed if invalid)
- test briefly custom properties in frontend.

**Comment by gbonaspetti** [comment]
> test invalid and invalid jsonschema and uischema file with the new command line.

can you give an example of an invalid uischema file?

> test launching tracim with valid and invalid jsonschema and uischema files (should failed if invalid)

it works without a personal page at jsonschema

**Comment by inkhey** [comment]
> > test invalid and invalid jsonschema and uischema file with the new command line.
> 
> can you give an example of an invalid uischema file?

Currently there is no uischema specific check, what is checked for uischema is:
- json format
- is a file
- is readable by the user who run the command line.

**Comment by inkhey** [comment]
> it works without a personal page at jsonschema

There is no check of exisitng personal page, should this be mandatory ? (don't see anything about this in issue but i may have miss something).

**Comment by gbonaspetti** [comment]
> > it works without a personal page at jsonschema
> 
> There is no check of exisitng personal page, should this be mandatory ? (don't see anything about this in issue but i may have miss something).

Sorry, you are right, I mixed 'personal page' with 'properties'.

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by knodelle** [comment]
done
