### ISSUE TITLE
Feat: reactivate draw support for office document (collabora online)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#5113]
## Feature description and goals

Since Collabora Online 6.4.7 (https://www.collaboraoffice.com/collabora-online-6-4-release-notes/) it is now possible to use Draw feature for *.odg files.

In Tracim 2.4 we can seen popup with draw support on office document (https://github.com/tracim/tracim/issues/2115). We remove this feature when Collabora Online remove support of this kind of files.

## PR

#5163

**Comment by PhilippeAccorsi** [comment]
@lebouquetin @charline-rageade Do you know if we can add this before release 4.1 ?

**Comment by PhilippeAccorsi** [comment]
Maybe need information about which Collabora Online version used to know if we can show this button in popup or not (maybe it is possible to know that when tracim check config available on collaboraonline (which kind of file supported for modification).

**Comment by PhilippeAccorsi** [comment]
To activate Draw feature it is necessary to:

- Use Collabora Online 6.4.7 or newer
- Add default.odg template in `backend/tracim_backend/templates/open_documents` (With docker you can add this template directly in the container or use environment variable to use all templates outside Docker container).
  - You can use something like this with docker-compose.yml `- "TRACIM_COLLABORATIVE_DOCUMENT_EDITION__FILE_TEMPLATE_DIR=/etc/tracim/templates/open_documents"`
- add default.odg template in your personal folder if you use customize template

Example of default.odg file that you can use with Tracim:
[default.odg](https://github.com/tracim/tracim/files/7676199/default.odg)

**Comment by knodelle** [comment]
tested on branch

**Comment by knodelle** [comment]
done
