### ISSUE TITLE
MailFetcher mark new mails as read but don't retrieve them

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#512]
In some situation, after some time, MailFetcher continue seem to fetch news mail correctly (it mark them as read) but can't find new mail, so it can't add them into tracim.

`
2017-12-08T12:22:27|DEBUG|tracim|[MailFetcher] 
Connect IMAP mao993 using SSL|thread-139699700094720
2017-12-08T12:22:27|DEBUG|tracim|[MailFetcher]
 Login IMAP with login algoobetatest@trac.im|thread-139699700094720
2017-12-08T12:22:27|DEBUG|tracim|[MailFetcher]
 Fetch messages from folder INBOX|thread-139699700094720
2017-12-08T12:22:27|DEBUG|tracim|[MailFetcher] 
Response status OK|thread-139699700094720
2017-12-08T12:22:27|DEBUG|tracim|[MailFetcher]
 Fetch unseen messages|thread-139699700094720
2017-12-08T12:22:27|DEBUG|tracim|[MailFetcher]
Response status OK|thread-139699700094720
2017-12-08T12:22:27|DEBUG|tracim|[MailFetcher] 
Found 0 unseen mails|thread-139699700094720
2017-12-08T12:22:27|DEBUG|tracim|[MailFetcher] 
Notify tracim about 0 new responses|thread-139699700094720
2017-12-08T12:22:28|DEBUG|tracim|[MailFetcher]
 sleep for 60|thread-139699700094720
`

**Comment by lebouquetin** [comment]
@inkhey do you close/re-open the IMAP connexion every time ?

The situation is : 
- there are new emails in the inbox, they are in "not read status"
- email fetcher does not see them
- so the messages are not included in tracom

Could you confirm I understand the bug correctly ?

**Comment by inkhey** [comment]
Yes, the IMAP connexion is close every time, that's why this bug is really weird.
You are also right about the situation, but it's a bit more complicated because those mails are not
fully ignored, the fetch IMAP command set those mail as seen but at the same time don't find any unseen mail.

I'm thinking about a way to not rely on this weird behaviour of fetch IMAP command who does 2 differents things at the same time, not sure if it will fix this bug, but after that normally, no unprocessed mail will be flag as processed.

**Comment by lebouquetin** [comment]
ok, I understand. let's fix it as a priority task

**Comment by inkhey** [comment]
Normally fix with https://github.com/tracim/tracim/pull/525
