### ISSUE TITLE
Bug: content stays in bold in content list after reading

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5130]
## Description and expectations

The content stays in bold in content list after reading.

### How to reproduce

(systematically occurring)
1. Go to content list
2. Click on any content
3. Close the content

### Version information

- Tracim version: v.4.1
- Web browser: Google Chrome
- Device / System: PC

________________________________________________

## Diagnostic

Possibly linked to https://github.com/tracim/tracim/pull/5108
(@raphj: indeed)

**Comment by inkhey** [comment]
tested on branch

**Comment by knodelle** [comment]
done
