### ISSUE TITLE
Feat: have a loading indication for the space management popup

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5131]
## Feature description and goals

If there is a lot of spaces in an instance, the space management popup can take a little time to display the space list. We should have a loading screen or at least have a default text like "loading...".

Version 4.1

To access: as administrator, go to an user settings > spaces tab > manage user spaces button

## Prerequisites

None

## PR
https://github.com/tracim/tracim/pull/5671

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by gbonaspetti** [comment]
Done
