### ISSUE TITLE
Bug: Impossible to go to the administrator user after go to space settings

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5136]
## Description and expectations

Impossible to go to the administrator user after go to space settings. I click on the space administration button, I click on a space to modify it, I click on the user administration space, nothing happens.

### How to reproduce

(systematic)
1. Click on the space administration button
2. Click on a space to modify it
3. Click on the user administration space

### Version information

- Tracim version: v4.0.3
- Web browser: Google Chrome
- Device / System: PC

________________________________________________

## Diagnostic

Close popup button always redirects to space dashboard.
Implemented solution: have a route state if the popup was opened from admin page and in this case redirects to admin page. 

### Linked PR
#5162 

## Prerequisites

None

**Comment by knodelle** [comment]
tested on branch

**Comment by knodelle** [comment]
done
