### ISSUE TITLE
Bug: Access old revision of kanban and update it popups

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5156]
## Description and expectations

The two points below are priorities taken from #5153 

- [x] impossible to see the old revision of a kanban
- [x] have all Tracim popups (not alerts or prompts)

### How to reproduce
Revision bug:
1. Go to a Kanban
2. Click on a old revision

Popups bug:
1. Go to a Kanban
2. Click on a column title

### Version information

- Tracim version: v4.1
- Web browser: Google Chrome
- Device / System: PC

## Linked PR
https://github.com/tracim/tracim/pull/5159

**Comment by knodelle** [comment]
tested on branch

**Comment by knodelle** [comment]
done
