### ISSUE TITLE
Bug: no notifications if we comment a kanban

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5157]
## Description and expectations

We have no notifications if we comment a kanban. There is a 404 in the console.

Error:
- `/api/workspaces/{workspace_id}/kanbans/{content_id}/`
- Response: `{"message": "/api/workspaces/{workspace_id}/kanbans/{content_id}/ is not a valid path", "details": {"error_detail": {}}, "code": 9999}`

### How to reproduce

(systematically occurring)
1. Ask someone to comment a kanban

### Version information

- Tracim version: v4.1
- Web browser: Google Chrome, Firefox
- Device / System: PC

## Linked PR
#5180
________________________________________________

## Diagnostic

It seems like backend do a wrong redirection when `GET api/workspaces/{workspace_id}/contents/{content_id}`. Alternatively the frontend could use `/contents/{contentId}` (which does the right redirection) instead of `/workspaces/{workspaceId}/contents/{contentId}`.

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by gbonaspetti** [comment]
Done
