### ISSUE TITLE
Feat: new design for Kanban board

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5164]
## Feature description and goals

A new design was chose at #4962 for the kanban board.

![kanban + fullscreen colored columns background-1](https://user-images.githubusercontent.com/50776142/145569257-c48e4f55-00d0-4532-a6b6-c476993e06f1.png)

- [x] the column and card color by default should be the kanban color
- [x] column color: line ~+ background with transparency~ (not allowed by library, it will be an improvement)
- [x] card color: border
- [x] update fullscreen button
- [x] column menu: add card, edit column, delete column
- [x] card menu: edit card, delete card
~- [ ] add create card zone~ (not allowed by library, it will be an improvement)
- [x] update popup inputs

## PR

#5171 

## Prerequisites

None

**Comment by knodelle** [comment]
tested on branch

**Comment by gbonaspetti** [comment]
Done
