### ISSUE TITLE
Bug: On click to open a reaction/emojis on a content, the keyboard shows up

### ISSUE THREAD

**Issue by knodelle** [tracim/tracim#5166]
### How to reproduce

1. On mobile
2. Go to a content
2. Click on the emoji picker
3. The keyboard opens, instead of the emojis

### Version information

- Tracim version: v4.1
- Web browser: Google Chrome
- Device / System: Redmi Note 8

________________________________________________

## Diagnostic

Autofocus at research.

## PR
#5165

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by knodelle** [comment]
done
