### ISSUE TITLE
Misc: new tab not opened when receiving a call in Tracim

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#5168]
## Description and expectations

Lorsque j'appel ou que je reçois un appel via tracim, je n'ai pas de nouvel onglet qui s'ouvre avec la visio. La raison est quand fait je n'ai pas autorisé l'ouverture de fenêtre automatique via le javascript pour l'url de tracim.

Le souci c'est que le message d'autorisation ne s'ouvre que dans l'onglet maître et que si l'on se trouve dans un autre onglet on a aucun moyen simple de savoir qu'une action de l'utilisateur est requise.

Les pistes de réflexion sont les suivantes:
- le clic sur le bouton d'appel ouvre l'onglet via un `a` et fait en plus l'action javascript pour informer l'autre utilisateur
- un message s'affiche à l'utilisateur après le clic sur le bouton pour lui dire que si l'onglet ne c'est pas ouvert il peut cliquer sur le lien "Link" (comme dans la popup de l'appelant.

### How to reproduce

- Clean all firefox config (cookies, etc..)
- need 3-4 tab of Tracim
- receive a Tracim call from a non first tab opened on Tracim instance
- clic on accept call button
=> nothing append (and a popup is visible in parent tab to ask about autorize firefox popup

### Version information

- Tracim version: all tracim with call feature
- Web browser: Firefox
- Version: 95
- Device / System: Ubuntu 20.04

### Screenshots

________________________________________________

**Comment by knodelle** [comment]
This has been fixed in https://github.com/tracim/tracim/pull/5243

**Comment by knodelle** [comment]
@lebouquetin will test this issue to check if it has been fixed

**Comment by knodelle** [comment]
done
