### ISSUE TITLE
Bug: Scroll into another scroll in app content and the history

### ISSUE THREAD

**Issue by knodelle** [tracim/tracim#5169]
## Description and expectations

The separation with the app content and the history is disturbing, there is a scroll into another scroll and sometimes it even do some random stops.

### How to reproduce

1. Go to a note
2. Scroll the app
3. Scroll scroll the timeline

### Version information

- Tracim version: v4.1
- Web browser: Google Chrome
- Device / System: Redmi Note 8

________________________________________________

## PR

#5165

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by knodelle** [comment]
done
