### ISSUE TITLE
Bug: Frame the picture inside the personal page 

### ISSUE THREAD

**Issue by knodelle** [tracim/tracim#5170]
## Description and expectations

The picture inside the personal page is oversized and goes beyond the frame limit

### How to reproduce

1. Go to personal space
2. Add a  big image to the description
3. The image goes outside the frame

### Version information

- Tracim version: v4.1
- Web browser: Google Chrome
- Device / System: Redmi Note 8

### PR

#5165 
________________________________________________

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by knodelle** [comment]
done
