### ISSUE TITLE
Feat: Add a scroll per column on kanban

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5172]
## Feature description and goals

For now, we have a global scroll for the entire kanban board. To improve the experience, it would be nice to have a scroll per column.

## Prerequisites

#5171 

## PR and implementation 
https://github.com/tracim/tracim/pull/5178
### Workaround
The library does not allow to do our own column style, so I override some properties to have a scroll per column but the columns have all the same size.

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by gbonaspetti** [comment]
Done
