### ISSUE TITLE
Feat: Limit kanban card description

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5173]
## Feature description and goals

To have a maximum of cards in a kanban we can limit the card description.

- [x] If the card has more than 3 lines, the description is limited and a "see more" button appears
- [x] Click on "see more" display all description and the button label changes to "see less"
- [x] Click on "see less" hide the description overflow ant the button label changes to "see more"

## Prerequisites

#5171 

## PR
#5182

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by gbonaspetti** [comment]
Done
