### ISSUE TITLE
Bug: Send button disappears

### ISSUE THREAD

**Issue by Haskaris** [tracim/tracim#5175]
META: #5134 

## Description and expectations

Sometime, the send button in discussion disappear on mobile.

### How to reproduce

There is multiple way to reproduce:
- Create a discussion, click on the edit text to create text, and voilà!
- Open a discussion, change application, come back to Tracim, and voilà!
- Recent activities -> Actualities

### How to not reproduce
- Recent activities -> HTML document
- Wall notification -> File content commentary

### Version information

- Tracim version: v4.0.3 ; v4.1
- Web browser: reproduced on
  - android safari
  - android chrome
  - iphone safari
- Version: latest
- Device / System: Android 10 / iOS 14

### Screenshots

________________________________________________

## Diagnostic

My guess is that the button is hiding itself behind the browser overlay.

Update:
31/01/2022 - I was maybe wrong; The bug is reproductible on webapp -> there is no browser overlay in webapp

## Linked PR
PR: #5376

**Comment by Haskaris** [comment]
After a lot of searching, depending on the browser/smartphone you use the browser's navigation bar (which may be at the top or the bottom of your smartphone) sometimes hides when you reach the bottom of the website. However, sometimes the navigation bar does not hide and every elements behind the bar never appear.
A possible workaround is to change the position of the buttons
Here is a quick prototype:
![Screenshot_2021-12-21 · Tracim - Prototype](https://user-images.githubusercontent.com/28917197/146935973-294878ce-084f-4139-845d-971fdd7b5ba0.png)
Just for comparison, here is the current version:
![Screenshot_2021-12-21 · Tracim - Current](https://user-images.githubusercontent.com/28917197/146936142-8bf1b4d3-81ef-4f42-a9e0-1f2bf9ac07a1.png)

**Comment by Skylsmoi** [comment]
I changed the title to remove "[Discussion]" and I replaced it with the label "app-thread"

**Comment by lebouquetin** [comment]
What about adding a bottom margin @Haskaris ? (cc @gbonaspetti )

Another point to have in mind: We'll invert the order for news feed (currently : latest news are at the bottom, we will put them at the top)

**Comment by Skylsmoi** [comment]
@lebouquetin adding a margin bottom will fix the issue when it appears but it will also add an irrelevant margin when the issue doesn't occur
I wouldn't recommend it
We agree that changing the design might not be the best idea but it's a safe workaround for the global issue of the scrolling and header management on mobile (related to https://github.com/tracim/tracim/issues/5117)

**Comment by raphj** [comment]
Should we go for the first design depicted in @Haskaris' comment? https://github.com/tracim/tracim/issues/5175#issuecomment-998775477

It seems to both neatly solve the problem and optimize space for the user.

**Comment by lebouquetin** [comment]
@raphj @Haskaris I do not understand how putting buttons on the right will fix the fact that status bar goes sometime overt the content.

If the button are pulled up in the screen, then the part of the screen sometimes hidden by the status bar will be pulled up as well - so the problem will still appear (there will be a part of the textarea + the button hidden).

Am I missing something?

**Comment by raphj** [comment]
No, indeed, you are right @lebouquetin

**Comment by raphj** [comment]
We have to look into the topic. There are probably existing, hopefully clean, solutions for status or address bars hiding a part of the page.

**Comment by gbonaspetti** [comment]
Tested on branch (android and broswer)

**Comment by gbonaspetti** [comment]
Done
