### ISSUE TITLE
Bug: No clickable tooltip for space/content

### ISSUE THREAD

**Issue by knodelle** [tracim/tracim#5181]
## Description and expectations

[META]: #5134

### How to reproduce

1. Go to dashboard or a content
2. Click on the title
3. There should be a popover

### Version information

- Tracim version: v4.1
- Web browser: Google Chrome
- Device / System: Redmi Note 8

## PR
#5216 

________________________________________________

## Prerequisites

None

**Comment by grignards** [comment]
Tested on branch.

**Comment by knodelle** [comment]
done
