### ISSUE TITLE
Bug: docker images built after the 2021-12-19 are not functional

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#5183]
## Description and expectations

Images built after this date fail at startup with an error `tracimcli: command not found`.

### How to reproduce

1. Build an image (develop for instance) according to the official instructions
2. Start it with the official instructions

### Version information

- Tracim version: all official docker images built after 2021-12-19

### Screenshots

________________________________________________

## Diagnostic

Setuptools is used by the backend installation. A new version (60.0.0, see https://setuptools.pypa.io/en/latest/history.html) has been released the 2021-12-19 which changes the installation directory for develop/in-place installs (used by the docker image): `pip install -e "."`.
Setuptools version should be blocked by the installation process to the version 57.0, but the up-to-date version is still used during the installation for unclear reasons.

## Implemented solution

A quick fix has been found as setuptools provides a backward-compatibility through an environment variable: https://setuptools.pypa.io/en/latest/history.html#breaking-changes
The fix is to enable this variable in the `Dockerfile`.

**Comment by PhilippeAccorsi** [comment]
Manually tested with docker image.

**Comment by PhilippeAccorsi** [comment]
Done.
