### ISSUE TITLE
Bug: The screen returns to the left when I edit columns on the far right

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#5198]
## Description and expectations

The screen returns to the left when I edit columns on the far right

### How to reproduce

(random but easily reproductible)
1. Go to a kanban that have multiple columns (enough columns so that, when scrolling all the way to the right, the first one is "hidden")
2. Change a card from the second-last to the last
3. Wait the save "refresh"

### Version information

- Tracim version: v4.1
- Web browser: Firefox
- Device / System: PC

### Screenshots

![kanban](https://user-images.githubusercontent.com/35422692/147458235-456babf1-fff7-4442-b137-6b35d14fe4b1.gif)

________________________________________________

## Diagnostic

The bug occur when the component goes in the `LOADING` state. In this state the board is not rendered, and rendering it anew when the states become `LOADED` resets the scroll position.
The fix avoids this by only hiding (with a CSS style) the board when the state is not `LOADED`.

## PR

#5200

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by gbonaspetti** [comment]
Done
