### ISSUE TITLE
Feat: Allow the user to scroll by/during drag

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5199]
## Feature description and goals

For now, the only way of scroll horizontally is using scroll bar. The required feature is scroll horizontally when dragging a card.

### Diagnostic and solution
Since we have a scroll by column, the cards try to drag inside the column, not between columns. So to fix it we handle the scroll by column only on hover.

### PR
#5201 

## Prerequisites

None

**Comment by grignards** [comment]
Tested on branch.

**Comment by gbonaspetti** [comment]
Done
