### ISSUE TITLE
Bug: Better handle kanban search and popup

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5202]
## Description and expectations

 - [x] when creating a new card, the focus is in the 'description' field rather than the 'title' field
 - [x] add kanban translation for search filter
 
![Capture d’écran de 2021-12-27 15-25-13](https://user-images.githubusercontent.com/35422692/147480732-99109d9b-7ef4-4d4f-94b0-5d23af269df5.png)

### Version information

- Tracim version: v4.0.3
- Web browser: Google Chrome
- Device / System: PC

________________________________________________

## Diagnostic

- Tinymce init function put the auto focus on tinymce, I added a flag to know if it should auto focus or not.
- Missing translation.

## PR
#5204 

## Prerequisites

None

**Comment by grignards** [comment]
Tested on branch.

**Comment by gbonaspetti** [comment]
Done
