### ISSUE TITLE
Bug: no scroll in kanban creation/edition card pop-up in small screens

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5205]
## Description and expectations

There is no scroll in creation/edition card pop-up in small screens (the pop-up goes out of the screen) so we can not validate.

### How to reproduce

(sistematic)
1. Go to a kanban using a small device
2. Click on create a card

### Version information

- Tracim version: v4.1
- Web browser: Google Chrome
- Device / System: Redmi Note 8

________________________________________________

## PR

#5208 

## Prerequisites

None

**Comment by grignards** [comment]
Tested on branch.

**Comment by gbonaspetti** [comment]
Done
