### ISSUE TITLE
fix cypess test error `{"message": "No row was found for one()", "details": {"error_detail": {}}, "code": null}`

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#5209]
- [x]  `{"message": "No row was found for one()", "details": {"error_detail": {}}, "code": null}` in `kanban_columns_spec.js`
- [x] error `TypeError: cannot read property content_id of undefined` in all kanban test files
- [x] Double addition of a revision when creating a kanban board.

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by knodelle** [comment]
done
