### ISSUE TITLE
Misc: fix test docker image for pushpin

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#5212]
## Description and expectations

CI builds fail randomly when building the pushpin image used for tests (both backend and end-to-end).
The displayed error is:

```
E: Failed to fetch https://fanout.jfrog.io/artifactory/debian/pool/mongrel2-core_1.12.2-3~bionic1_amd64.deb  Connection failed [IP: 34.192.115.181 443]

E: Failed to fetch https://fanout.jfrog.io/artifactory/debian/pool/pushpin_1.31.0-1~bionic1_amd64.deb  Connection failed [IP: 34.200.165.67 443]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

The reason behind those `Connection failed` is unclear: JFrog does not mention any service failure.

## Implemented solution

Use bullseye for the base of the image (as the official Tracim image) and install pushpin from the official debian packages.

**Comment by knodelle** [comment]
done
