### ISSUE TITLE
bug: Having `&é"'(-è_çà)=$^*ù!:;,` as title of the kanban broke the kanban

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#5220]
## Description and expectations

All characters should be possible in the title.

## Version Information

- Tracim Version 4.0.4 build 63
- Browser: Chrome (the bug does **not** occur with Firefox)

## Diagnostic
The filename wasn't URL encoded by the frontend, after encoding it it still fails.
This is due to the combination of `"` and `;` characters which aren't handled properly by the backend to write the `Content-Disposition` header. Firefox seems to be lenient when parsing this header whereas Chrome isn't and fails with `ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION`.
This bug likely also affects all file contents.

In fact it seems that a standard way to handle `"` in the `filename` parameter of `Content-Disposition` does **not** exist: see https://stackoverflow.com/questions/93551/how-to-encode-the-filename-parameter-of-content-disposition-header-in-http and https://httpwg.org/specs/rfc6266.html#header.field.definition for a reference

## Branch
[fix/5220__kanban_title](https://github.com/tracim/tracim/tree/fix/5220__kanban_title)

**Comment by grignards** [comment]
This bug is related to this: https://github.com/algoo/hapic/issues/214 hapic issue.

**Comment by lebouquetin** [comment]
@grignards what is the strategy of the fix you suggest for not breaking the kanban? We already have some logic for file name resilience in the webdab context, I'd suggest to use it as is or improve them both - My feeling is there is no consistenty here between webadv & kanban cases
