### ISSUE TITLE
Bug: miss positioning of the button "change description"

### ISSUE THREAD

**Issue by knodelle** [tracim/tracim#5224]
Linked to : #5134

### How to reproduce

1. Go to a file content, on mobile
2. Click in the information tab
3. The "change description" has too much margin on the right

### Version information

- Tracim version: [e.g. v2.7, Mon Tracim]
- Web browser: [e.g. Google Chrome, Firefox, Safari]
- Version: [e.g. 22, latest]
- Device / System: [e.g. PC, iPhone 6]

### Screenshots

________________________________________________

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by knodelle** [comment]
done
