### ISSUE TITLE
Bug: The main header doesn't close itself once we clicked on the notification wall, we have to close it manually

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5227]
## Description 
On mobile, the main header doesn't close itself once we clicked on the notification wall, we have to close it manually.

### Expected
- [x] the header close when we click on any button on it (on mobile)

### Version information
- Tracim version: v4.1

### PR
#5231

**Comment by knodelle** [comment]
tested on branch

**Comment by knodelle** [comment]
done
