### ISSUE TITLE
Bug: Fix width issues on cards

### ISSUE THREAD

**Issue by knodelle** [tracim/tracim#5229]
## Description and expectations

- Reading the title of a card (and a file too) can be hard depending on the width of the device.
- Cards are too long and tiny, like squeezed vertically. Reducing/removing the margins between the smartphone borders and the card could be nice. 
- The text in a card sometimes exceed the card.

### How to reproduce

1. Go to the activity feed
2. Check the width of the cards and the authors name width (it is overflowing)

### Version information

- Tracim version: v4.1
- Web browser: Brave
- Device / System: Huawei Mate 20 Pro

### Screenshots

________________________________________________

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by knodelle** [comment]
done
