### ISSUE TITLE
Bug: UX improvement of some buttons

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5234]
## Description and expectations

- [x] The button to open/close the menu `...` is too small
- [x] For notes content modification is a plus sign, title modification is pen sign, quite confusing. I was expecting to be able to edit the text right away.

### Version information

- Tracim version: v4.1
- Web browser: Brave
- Device / System: Huawei Mate 20 Pro

________________________________________________

## PR

https://github.com/tracim/tracim/pull/5235

**Comment by knodelle** [comment]
tested on branch

**Comment by gbonaspetti** [comment]
Done
