### ISSUE TITLE
Feat: After selecting a Space, the left bar should close automatically on mobile

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5236]
## Feature description and goals

- [x] After selecting a Space, the left bar should close automatically on mobile.
    - Other items updated too

## PR

https://github.com/tracim/tracim/pull/5237

**Comment by Skylsmoi** [comment]
@gbonaspetti 
everything works fine but the button to create a space. The sidebar doesn't close when clicking on it.
I'm not sure it should though

**Comment by Skylsmoi** [comment]
I'm adding that it doesn't work either for the button "join space"

**Comment by knodelle** [comment]
done
