### ISSUE TITLE
Bug: admin page improvements on mobile

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5238]
## Description and expectations

- [x] smaller toggle/switch buttons
- [x] hide toggle/switch buttons label
- [x] smaller font for space and user type
- [x]  join the user and username columns

### Version information

- Tracim version: v3.8
- Web browser: Google Chrome
- Device / System: Redmi Note 8

### Screenshots

![Capture d’écran de 2022-01-04 16-24-31](https://user-images.githubusercontent.com/35422692/148082137-fb59dbf4-e693-434d-889c-c0e7fec67322.png)

________________________________________________

## Prerequisites

None

## PR
https://github.com/tracim/tracim/pull/5240

**Comment by knodelle** [comment]
tested on branch

**Comment by knodelle** [comment]
done
