### ISSUE TITLE
Bug: Allow to resize images in tinyMCE

### ISSUE THREAD

**Issue by agile-marmot** [tracim/tracim#5257]
### How to reproduce

1. Go to…
2. Click on…
3. Scroll down to…

### Version information

- Tracim version: [e.g. v2.7, Mon Tracim]
- Web browser: [e.g. Google Chrome, Firefox, Safari]
- Version: [e.g. 22, latest]
- Device / System: [e.g. PC, iPhone 6]

### Screenshots

________________________________________________

**Comment by raphj** [comment]
We can't reproduce this bug on any computer, on our preprod, locally or on our production instance, on @knodelle, @charline-rageade or my computer, on Chrome like Firefox.
