### ISSUE TITLE
Bug: Activation/Deactivation of agenda is not properly handled.

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#5263]
## Description and expectations

Currently switching the button for activation or disabling of workspace agenda does not have any consequences for the user calendars list.
To make things work, we do need to add/delete symlink during workspace_modification if the agenda enabled/disabled state as changed.

The fix doesn't need to fix existing incorrect case for existing agenda as switching two time the state, will restore the correct state.

### Version information

- Tracim version: v4.0.5 build 067

## Diagnostic

change should be made in this event handler:
https://github.com/tracim/tracim/blob/a0e9746fde5a4c45b4e0f0bfa2caf9522b8c4e21/backend/tracim_backend/applications/agenda/lib.py#L599

## Implemented solution
https://github.com/tracim/tracim/pull/5323

- handle properly the activation/deactivation case of agenda in hooks.
- refactor caldav sync code to work more in a "set to this state" logic than "do this" logic.
- fix issues during usage of tracimcli user delete command (agenda not properly deleted) 
- correct error code when calendar is disabled for better support of DAVx⁵.

**Comment by inkhey** [comment]
About this issue, there is probably something wrong in both 
_on_user_role_in_workspace_created_ and _on_user_role_in_workspace_deleted_ 
as there is no proper check of activation of agenda before adding/removing symlinks. This can cause issue because this behaviour is inconsistent with symlink creation when workspace is created/modified that doesn't create symlink is agenda feature is disabled.

**Comment by inkhey** [comment]
A workaround to unblock all situations where user cannot been removed from a space because symlinks doesn't exist:
- active agenda feature in the workspace if not enabled.
- modify the workspace description or run `tracimcli caldav sync`.

**Comment by knodelle** [comment]
I added this to the changelog as a known issue

**Comment by inkhey** [comment]
To test this: 
- add/remove agenda feature of workspace does add/remove the agenda/addressbook for all members list. the content should NOT be deleted during removing then reenabling the feature. Test this with thunderbird/ davx5.
- check if possible to remove user from workspace if user is added to a workspace without agenda enabled (so no symlinks)
- create inconsistency cases : 
  - save symlink of workspace W user for user A before removing user A from the workspace W and replace it after, do` tracimcli caldav sync` and verify the symlinks is properly synced (dropped).
  - remove valid symlink and do` tracimcli caldav sync` and verify the symlinks is properly synced (added).
- check user deletion (`tracimcli user delete`) does proper deletion of user calendar, addressbook but also user symlink. Also, when the `tracimcli user delete` does imply workspace deletion, the user agenda and all symlink to it (from workspace members), should be removed)

**Comment by raphj** [comment]
The missing bullet point of the previous comment is described in https://github.com/tracim/tracim/issues/5345

This is not problematic for this issue.

**Comment by raphj** [comment]
Noticed https://github.com/tracim/tracim/issues/5346

Tested on branch, we are good to go.
