### ISSUE TITLE
Bug: Unable to close the call popup using the X button - HTTP 400 | 2074 Cannot change the state of a call if it is not in progress

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#5265]
## Description and expectations

I was using Chromium and the close popup could not be closed. The path to get there was a bit contrived, see the "How to reproduce section"

### How to reproduce

1. Open Tracim in both Firefox and Chromium (important: a fresh profile where you haven't allowed browser notifications yet)
2. Receive a call
3. answer on firefox
4. close the call on both ends (caller / callee)
3. allow notifications on Chrome
4. the call popup appears on Chome
5. try to close it

### Version information

- Tracim version: 4.1
- Web browser: Chromium 97.0.4692.71 (official Build) for Linux Mint (64 bits)
- Device / System: Ubuntu 20.04

## Diagnostic

This is probably an unhandled API error, as when I click on the close button, I see this error in the debugger

```
PUT https://algoo.tracim.fr/api/users/290/incoming_calls/263/state 400 (Bad Request)
{"message": "Cannot change the state of a call if it is not in progress", "details": {"error_detail": {}}, "code": 2074}
```

**Comment by Skylsmoi** [comment]
fixed by https://github.com/tracim/tracim/pull/6529
