### ISSUE TITLE
Bug: loading is not handled in user workspace admin app

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#5273]
### How to reproduce

1. Go to…
2. Click on…
3. Scroll down to…

### Version information

- Tracim version: [e.g. v2.7, Mon Tracim]
- Web browser: [e.g. Google Chrome, Firefox, Safari]
- Version: [e.g. 22, latest]
- Device / System: [e.g. PC, iPhone 6]

### Screenshots

________________________________________________

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by knodelle** [comment]
done
