### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [tracim/tracim#5283]
https://hosted.weblate.org/projects/tracim/frontend-app-agenda/#information says GPLv3+, but 
https://github.com/tracim/tracim/blob/develop/LICENSE.md says AGPLv3+ for frontend_app_agenda

It can be fixed in https://hosted.weblate.org/settings/tracim/frontend-app-agenda

How it doesn't make everything AGPLv3+ is anyone's guess, but I imagine that is OK.

**Comment by raphj** [comment]
Thanks for the head's up! @grignards can you look into this please?

**Comment by grignards** [comment]
License for app agenda is now set to AGPLv3+.
BTW: no PR for this issues as the fix is a weblate configuration change.

**Comment by knodelle** [comment]
done
