### ISSUE TITLE
Misc: disable ringing on mobile

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#5285]
## Description and expectations

Mobile currently lacks functionality for calls to be usable enough. Specifically, the ringing can be disturbing as it seems to come from nowhere if the user does not recognize the Tracim's ring tune.

Let's disable ringing for now.

### Version information

- Tracim version: 4.1
- Web browser: mobile

PR: #5316

**Comment by gbonaspetti** [comment]
Tested on branch
