### ISSUE TITLE
Feat: Introduce arabic language selection

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#5288]
## Feature description and goals

The arabic language support needs several developments, but first the language itself should be selectable in the interface:

- [x] Add arabic in the user interface (precise steps are in #3003)
- [x] Ensure that the direction of the page is set to `rtl` when arabic is chosen.

**Comment by grignards** [comment]
I had a look for collabora online RTL display, it seems that the support is pending: https://github.com/CollaboraOnline/online/pull/3968 but not already available (the linked PR was merged the 11th of January 2022).

**Comment by knodelle** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
@grignards collobora online support RTL with version 21.11 but i don't know if its available on LibreOffice Online.
.

**Comment by knodelle** [comment]
done
