### ISSUE TITLE
Feat: Support right to left with the sidebar 

### ISSUE THREAD

**Issue by Haskaris** [tracim/tracim#5289]
## Feature description and goals

With the arabic support, we need the sidebar to be right to left.

## Linked PR
PR #5291

**Comment by Haskaris** [comment]
The PR implement the uniformity of Z-index of the sidebar (10 and 15 to 10) and increase the Z-index of wsContent from 9 to 15.
Uniformity of the sidebar: if we merge the sidebar extension plus the "core" of the sidebar, we need them to got the same Z-index.
Increase the Z-index of wsContent to go above the sidebar when the application is in fullscreen mode.

**Comment by knodelle** [comment]
done
