### ISSUE TITLE
Bug: Link previews of text files are spammy and have wrong whitespaces (including no line breaks)

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#5294]
## Description and expectations

![image](https://user-images.githubusercontent.com/3817365/150995758-432d62b4-30d3-48e0-a7e9-31cc47165764.png)

For instance, with this link: https://github.com/jitsi/jitsi-meet/releases/download/stable%2Fjitsi-meet_6826/jitsi-meet_1.0.5764_CHANGELOG.txt

The text should be presented better, or shortened, or both, or link previews for such files should be disabled.

### Version information

- Tracim version: 3.X, 4.1

**Comment by gbonaspetti** [comment]
Fixed https://github.com/tracim/tracim/pull/5439
