### ISSUE TITLE
sharp (#) at the end of the calendar url broke radicale file structure

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#53]
See server log (tested with "Intranet")

**Comment by tracim** [comment]
Renamed as the issue is due to the "user-friendly" calendar url. Need to remove the user friendly part (#intranet in the example)

**Comment by tracim** [comment]
Is it fixed or not ?

**Comment by algooapy** [comment]
- Issue not reproduced.
- Seems to have been fixed by buxx@68b7c40 in:
`tracim/tracim/model/data.py:Workspace.calendar_url`
