### ISSUE TITLE
Docker: Which Debian release is used to build images

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#530]
At present:

when you want to build a new image docker, its not possible to know exactly which release of debian is used. Docker use "latest" but if you have one file "latest" locally, docker don't download  the new "latest" of Debian image.

Expected: 

We need explicit information about Debian release is used.

**Comment by PhilippeAccorsi** [comment]
If you want to make sure, that docker used Debian "latest", you need to remove cache images in local.

**Comment by lebouquetin** [comment]
I believe this bug is already fixed, isn't it ? @buxx

**Comment by buxx** [comment]
@lebouquetin Yes it is. This issue is a deplicate of https://github.com/tracim/docker_tracim/issues/10 . I close it.
