### ISSUE TITLE
Feat: Support RTL interface on public profile

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5312]
## Feature description and goals

- [x] Fix cover image button position
- [x] Fix popup for cover image
- [x] Fix popup for avatar
- [x] Fix personal page edition and validation button
- [x] Fix informations edition and validation button

## Prerequisites

None

## PR
https://github.com/tracim/tracim/pull/5325

**Comment by inkhey** [comment]
@gbonaspetti 
Manually tested, i confirm that:
- cover image button is ok
- personal information and information button are ok.

I'm not sure what are the improvement for:
- cover-image popup
- avatar popup

Also, is there any reason that avatar button placement doesn't change ? If we follow a mirror logic it should be on the left side of the avatar.

**Comment by knodelle** [comment]
tested on branch

**Comment by knodelle** [comment]
done
