### ISSUE TITLE
Bug: Folder triangles are not displayed correctly in RTL

### ISSUE THREAD

**Issue by Haskaris** [tracim/tracim#5313]
## Description and expectations

Here is the display of the triangle in LTR:
![image](https://user-images.githubusercontent.com/28917197/151567104-a32bf001-55eb-4ec6-a49f-5e1d0caab9b7.png)

Here is how it looks like now in RTL:
![image](https://user-images.githubusercontent.com/28917197/151567333-c5e6e75c-15e4-4457-a228-297430a04e3c.png)

Here is how it should be in RTL:
![image](https://user-images.githubusercontent.com/28917197/151567434-a2d45c7c-114e-4bd7-9dad-3eaf9253f0be.png)

### Version information

- Tracim version: 4.1

## Linked PR
PR #5314

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by knodelle** [comment]
done
