### ISSUE TITLE
Bug: the "connection problem" pop-up persists after refresh

### ISSUE THREAD

**Issue by charline-rageade** [tracim/tracim#5315]
## Description and expectations

Pop up with "Tracim has a connection problem, please wait or restart your browser if the problem persists" persists after refresh on mobile and PC

### How to reproduce

randomly

### Version information

- Tracim version: [4.1, probably before]
- Web browser: [Firefox]
- Version: [unidentified]
- Device / System: [PC, smartphone]

### Screenshots

________________________________________________

## Diagnostic

*This diagnostic is for the cases where the popup appears soon after opening a new browser tab/window with an already existing tab/window on the same Tracim instance*.

When opening a new tab it can happen (seen in the browser's console logs) that its TLM connection status always stays to `PENDING`. This triggers the popup display.
As the behavior is random it is likely linked to a race condition when creating the broadcast channel: when creating a new tab the broadcast channel is used to get the current connection status of the "leader" tab and this status is never received (the leader tab's status in this case is `OPENED`).
In particular the dependency which is used has a filed fix for this case: https://github.com/pubkey/broadcast-channel/blob/master/CHANGELOG.md#490-23-december-2021 (Tracim is currently using version 3.1).

## Implemented solution
 - upgrade broadcast-channel to benefit from its possibly related last December fix
 - detect the situation where the state is pending and we receive a TLM and try to recover from that

**Comment by PhilippeAccorsi** [comment]
Sometime when I seen this, in console I can seen that TLM seems to be "broken". Status on TLM is not refreshed.
I have seen this same error when the message is charged before all other content of the page.

Maybe a async problem.

**Comment by charline-rageade** [comment]
@grignards Did you see Philippe's message? Does this give you any information about this bug?

**Comment by grignards** [comment]
@PhilippeAccorsi Do you have the console logs? Or remember the `xxx` in the last line which contained `TLM STATUS: xxx`?

**Comment by PhilippeAccorsi** [comment]
I don't have for the moment :(

**Comment by grignards** [comment]
@raphj If you have some time, could you have a look? I added some diagnostic information in the issue.

**Comment by raphj** [comment]
all right :-)

**Comment by raphj** [comment]
As a first measure because we don't have time to fully investigate and fix the problem at the end of the sprint, we are going to update the dependency in the hope that it will fix the issue. If we still notice the issue after the upgrade, we shall implement a more comprehensive fix, including, possibly : a broadcast message from tabs that have been in a pending state for more than X seconds to request the state to the main tab.

I'll also switch from pending to connected as soon as we receive a normal TLM since this means we are connected.

cc @grignards
