### ISSUE TITLE
Feat: Add RTL support to composed icons

### ISSUE THREAD

**Issue by Haskaris** [tracim/tracim#5319]
## Feature description and goals

When the page is in RTL, composed icons should be reversed.

### Update
The linked PR also do some minor fixes related to margin/padding (left/right to start/end)

## Linked PR
(done) PR #5322 merged in build_068
(to review/test) PR #5362 fix the incompatibility with #5292

**Comment by inkhey** [comment]
composed icon are use in : 
- search filter
- member creation
- share content/upload creation
- content list
- user admin 
- ...

**Comment by inkhey** [comment]
@Haskaris I briefly tested this, but the fix here is not enough clear for me to validate this.

**Comment by knodelle** [comment]
tested on branch

**Comment by Haskaris** [comment]
After testing on build_068, found out the development isn't working with #5292
I'll do a second PR with a fix to that since this ticket isn't in the changelog yet

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by knodelle** [comment]
done
