### ISSUE TITLE
Documentation about Webdav with Apache and uwsgi

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#532]
We need new doc to use Webdav.

**Comment by lebouquetin** [comment]
@inkhey le but de ce ticket est de s'assurer qu'on a une doc proposant une configuration apache/uwsgi de base qui est opérationnelle.

si c'est déjà le cas y'a rien à faire, si la doc (et donc la config d'exemple) qu'on a mise n'est pas celle qu'on utilise nous même, il faut la mettre à jour (sauf si les différences sont complètement liées aux spécificité du déploiement en prod)

**Comment by lebouquetin** [comment]
donc le boulot à faire est :

- une fois que webdav est 100% opérationnel pour nous, vérifier la doc par rapport à notre config
- reporter les différences de config si il y a lieu
