### ISSUE TITLE
Bug: notification wall is mispositioned when the interface is in rtl

### ISSUE THREAD

**Issue by knodelle** [tracim/tracim#5320]
### How to reproduce

1. Put the interface in arabic
2. Click on the notification button
3. The notification wall should open on the left

### Version information

- Tracim version: [e.g. v2.7, Mon Tracim]
- Web browser: [e.g. Google Chrome, Firefox, Safari]
- Version: [e.g. 22, latest]
- Device / System: [e.g. PC, iPhone 6]

### Screenshots

________________________________________________

## Prerequisites

PR: #5321

**Comment by inkhey** [comment]
@knodelle Manually tested:
- the notification wall at the right in french and in the left in arabic
- no left or right for phone-sized device.
is there any known special case to check ?

**Comment by knodelle** [comment]
@inkhey that's all that needs to be tested, thanks ! 
Is there anything that didn't seem right about this pr?

**Comment by inkhey** [comment]
@knodelle  no, it's ok

**Comment by knodelle** [comment]
done
