### ISSUE TITLE
Bug: Mention aren't well displayed in RTL

### ISSUE THREAD

**Issue by Haskaris** [tracim/tracim#5324]
## Description and expectations
 Here is how mention are supported in LTR (and latin keyboards) `@all`.
 Here is how mention is currently displayed in RTL `all@`. Furthermore, if the mention is the first thing of the text, the mention will be split with the text in between: `all here is some text@`

Also:
- [x] update auto completion mention popup
- [x] check if works when we edit a content and we "click here to notify all"

### Screenshots

Here is an example
![image](https://user-images.githubusercontent.com/28917197/151809408-27d6b9f3-33b2-4610-a583-5f457d26f699.png)

## Linked PR
PR #5361

**Comment by gbonaspetti** [comment]
Tested on branch (see https://github.com/tracim/tracim/pull/5361#issuecomment-1036338799)
