### ISSUE TITLE
Bug: File upload "round" progress bar is broken for RTL languages

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#5326]
The progress bar should have the same appearance in LTR and RTL languages:
https://marvelapp.com/blog/mirroring-designing-for-arab-users/

> As you can see even though you read the whole sentence from right to left you read the numbers themselves from left to right. It is 29 and not 92 and 1951, not 1591
>
> The same happens with clocks for time. When you display the time on a clock it will still turn clockwise for RTL languages. A clock icon, a circular refresh or progress indicator with an arrow pointing clockwise should not be mirrored.

### How to reproduce

1.Upload a file

### Version information

- Tracim version: v4.2 (unreleased)
- Web browser: any

## Diagnostic

transform origins and positions need to be fixed.

**Comment by knodelle** [comment]
tested on branch

**Comment by knodelle** [comment]
done
