### ISSUE TITLE
Bug: The notification order (short date) isn't correct when grouping notification

### ISSUE THREAD

**Issue by agile-marmot** [tracim/tracim#5333]
## Description and expectations

In certain circumstances, the first notification in the notification wall may not be the most recent.

### How to reproduce

1. With account A create an actuality a1
2. With account B create an actuality a2
3. With B comment a2
4. With A comment a1

### Version information

- Tracim version: 4.1.2.build-069

### Screenshots

![image](https://user-images.githubusercontent.com/28917197/155094499-23f3f223-3948-47cf-99b8-7b4a456d6894.png)

## Linked PR
PR #5456

**Comment by Haskaris** [comment]
It appears that the group timestamp isn't updated too

**Comment by inkhey** [comment]
tested on branch

**Comment by Relf-Algoo** [comment]
Is this still in progress ? Hasn't it been fixed ?

**Comment by knodelle** [comment]
done
