### ISSUE TITLE
Bug: comments sent while not connected to Tracim (browser closed) aren't recieved after a connexion if the browser cache isn't empty

### ISSUE THREAD

**Issue by agile-marmot** [tracim/tracim#5334]
## Description and expectations

I'm in a discussion content, open in two tabs.
I reboot my computer, meanwhile someone added several comments to the discussion.
After having my computer rebooted, I open Firefox and I don't see any of their comments. Neither in the discussion or in the notification wall.

I have Firefox that will open every tabs I previously had on start.

### How to reproduce

1. Open a discussion in several tabs (I believe you can reproduce it with only one tab, but I always have three or more tabs - one with the discussion, one on the profile of someone, one in a content, plus two others to be sure to load the browser)
2. Close your browser
3. Send a comment into the discussion with another browser and another account (maybe you can use the same account)
4. Open Firefox again
5. The comment isn't there

### Version information

- Tracim version: 4.1.2 build_69

### Linked issue
#3413

## Linked PR
~PR #5459~ https://github.com/tracim/tracim/pull/5473

________________________________________________

## Diagnostic

Edit 1.
- We tried to get some information about old tabs that aren't used

Edit 2.
- We can see that the tab makes a `GET` request to get the comment list, with a `200` response that takes 0ms (doesn't seems to be sent to the server).
- In comparison, the same request takes ~150ms when reloading the page.

Edit 3.
- The bug is due to the tab using an outdated cache
The client should ask for the events that they missed with a `GET` on `api/users/{user_id}/live_messages?last_event_id={last_event_id}` but in this case, it calls a `GET` `api/users/{user_id}/live_messages`

Edit 4.
- As suspected, the request is wrong into the code, now I still have to figure how to fetch the `last_event_id`.

Final edit.
- This bug only appears on Firefox and it seems to be a Firefox bug/behavior when no `Cache-Control` header is present, the solution is to force no cache through the HTTP headers (`Cache-Control: no-store`).
- It has nothing to do with TLMs,

**Comment by Haskaris** [comment]
Tested on banch.

**Comment by knodelle** [comment]
done
