### ISSUE TITLE
Bug: breadcrumbs are incoherent when you delete content in the favourites space

### ISSUE THREAD

**Issue by agile-marmot** [tracim/tracim#5336]
## Description and expectations

when I tried to delete a lot of content in my bookmarks, I noticed that the breadcrumbs did not match the deleted content

### How to reproduce

1. Go to…
2. Click on…
3. Scroll down to…

### Version information

- Tracim version: [e.g. v2.7, Mon Tracim]
- Web browser: [e.g. Google Chrome, Firefox, Safari]
- Version: [e.g. 22, latest]
- Device / System: [e.g. PC, iPhone 6]

### Screenshots

________________________________________________

**Comment by gbonaspetti** [comment]
Fixed at #6030
