### ISSUE TITLE
Bug: when I call someone on tracim, sometimes two windows open 

### ISSUE THREAD

**Issue by agile-marmot** [tracim/tracim#5337]
### How to reproduce

1. Go to…
2. Click on…
3. Scroll down to…

### Version information

- Tracim version: [e.g. v2.7, Mon Tracim]
- Web browser: [e.g. Google Chrome, Firefox, Safari]
- Version: [e.g. 22, latest]
- Device / System: [e.g. PC, iPhone 6]

### Screenshots

________________________________________________

**Comment by Relf-Algoo** [comment]
@PhilippeAccorsi Do you know if this still exists ?

**Comment by PhilippeAccorsi** [comment]
I don't know.

**Comment by Skylsmoi** [comment]
could not reproduce, might be fixed by https://github.com/tracim/tracim/pull/6529
