### ISSUE TITLE
Misc: put the expand part of the sidebar outside the sidebar

### ISSUE THREAD

**Issue by Haskaris** [tracim/tracim#5348]
## Description and expectations

The commit 22abe8e015daf2645376df476ea33046bd007730 introduced few bugs: no background on the sidebar, reducing the space on responsive.

After a discussion, we have chosen to revert this commit and keep the ``expand`` part of the sidebar outside the sidebar.

## Linked PR
PR #5349

**Comment by inkhey** [comment]
tested on branch

**Comment by knodelle** [comment]
done
