### ISSUE TITLE
Bug: sometimes translations are not coherent

### ISSUE THREAD

**Issue by agile-marmot** [tracim/tracim#5358]
## Description and expectations

- [x] french/german translation on frontend_lib while interface on arabic
- [x] german translation on frontend_app_gallery while interface on arabic
 
### How to reproduce

random

### Version information

- Tracim version: v4.1.1 build_068
- Web browser: Google Chrome, Firefox
- Device / System: PC

### Screenshots

![AkKtJel](https://user-images.githubusercontent.com/35422692/152813873-68bde42b-34eb-45d2-88fe-a1fb793d5195.png)
![Ny11P6o](https://user-images.githubusercontent.com/35422692/152813877-a4f71c4a-9f00-4089-a39c-61bdf12df003.png)

________________________________________________

## Diagnostic

Missing link to translation at frontend_lib and wrong link for gallery.

## PR
https://github.com/tracim/tracim/pull/5365

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by knodelle** [comment]
done
