### ISSUE TITLE
Feat: add a default text for agenda event descriptions

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#5359]
## Feature description and goals

We shall add the possibility to create templates for agenda events. In particular, we shall have a default description text for event when creating them.

## Linked PR
PR #5367

**Comment by raphj** [comment]
@PhilippeAccorsi and whoever will write the changelog: this development introduces a new parameter: agenda.pre_filled_event.description_file_path` (might be renamed after review)

**Comment by PhilippeAccorsi** [comment]
I have done a review.

**Comment by inkhey** [comment]
tested on branch

**Comment by knodelle** [comment]
done
