### ISSUE TITLE
Bug: The profile dropdown menu and its items are broken on rtl

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5368]
## Description and expectations

The profile dropdown menu and its items are broken on rtl

![Capture d’écran de 2022-02-08 16-44-29](https://user-images.githubusercontent.com/35422692/153022675-7dbe91ed-9491-444a-8425-df72c76301ee.png)

### Version information

- Tracim version: v4.1.1_build_068
- Web browser: Google Chrome, Firefox

________________________________________________

## PR

#5369

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by knodelle** [comment]
done
