### ISSUE TITLE
Bug: The popup falsely indicating a connection problem is still there 

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#5370]
## Description and expectations

This issue is a sequel to #5315. ~~Upgrading the BroadcastChannel library didn't fix the issue~~ we forgot to upgrade the BroadcastChannel library (the upgrade somehow didn't ship with the commit). The workaround detecting the wrong state when a TLM arrives is working (the right state is restored in the secondary tab and the hack message shows up in the console). ~~Now, we need to understand the root cause and fix the issue or reliably work around it.~~

Let's upgrade the BroadcastChannel library and see.

### Version information

- Tracim version: Tracim 4.2 to be released
- Web browser: Firefox
- Version: latest
- Device / System: Ubuntu 20.04

**Comment by gbonaspetti** [comment]
Tested on branch (tested on Google Chrome and Firefox, I did not reproduce the initial bug during testing)

**Comment by gbonaspetti** [comment]
Done
