### ISSUE TITLE
Bug: Gallery not working on rtl

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5373]
## Description and expectations

Gallery not working on rtl

### Version information

- Tracim version: v4.1.1_build_068

### Screenshots
![Capture d’écran de 2022-02-09 13-26-05](https://user-images.githubusercontent.com/35422692/153200778-2587c210-fe91-45e9-986f-db551548ae30.png)

________________________________________________

**Comment by inkhey** [comment]
@grignards switching the language between french and arabic change the currently showed image in gallery. i don't see other issue with the PR.

**Comment by grignards** [comment]
This should be corrected now @gbonaspetti @raphj maybe a small review again as I changed some aspects to fix @inkhey bug.

**Comment by inkhey** [comment]
tested on branch

**Comment by knodelle** [comment]
done
