### ISSUE TITLE
Bug: Elasticsearch docker use too much memory during dev

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#5378]
## Description and expectations

The elasticsearch configuration used with docker-compose up in dev, doesn't have memory limitation which lead to freezing computer in some specific case

### Screenshots

________________________________________________

## Implemented solution 

https://github.com/tracim/tracim/pull/5379

- add a 4go limit for elasticsearch in docker-compose for dev.

**Comment by knodelle** [comment]
done
