### ISSUE TITLE
Support de https dans wsgidav

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#538]
Erreur: Webdav est en erreur lorsque l'on renomme document.
Objectif: Ne plus avoir d'erreur quand on renomme un document. Voir avec Damien les autres erreur qu'il a pu rencontrer pour vérifier si elles sont corrigé également avec le guide ci-dessous:

Lorsque `cherrypy.wsgiserver.wsgiserver3.WSGIGateway_10` construit le dict `environ` dans la méthode `get_environ`, la partie:

`'wsgi.url_scheme': req.scheme.decode('ISO-8859-1'),`

récupère `http` dans `req.scheme` car en effet, wsgidav tourne en http et non en https. L'idée est donc de venir modifier la valeur derrière clé `wsgi.url_scheme` dans ce dict selon le contexte.

Cela peut se faire de cette manière: Ajouter un Middlware dans `tracim.lib.daemons.WsgiDavDaemon#_initConfig`:

> config['middleware_stack'] = [
>     WsgiDavDirBrowser,
>     TracimHTTPAuthenticator,
>     ErrorPrinter,
>     TracimWsgiDavDebugFilter,
> ]

Middlware qui dans sa méthode `__call__` à accès au dict `environ`. L'info qui dit que l'on est en réalité en https peut être obtenu de deux façons:

* On regarde dans la config Tracim
* On ajoute un header/variable d'environnement depuis apache lorsque l'on est en https, et on la regarde

**Comment by buxx** [comment]
Note: Pour la mise en prod de ce correctif, si cela est effectué sur algoo.trac.im il faut bien penser qu'actuellement on fait tourner la version http et la version https en parallèle. Ce qui rendra hors d'usage webdav en http si il à été utilisé l'option "On regarde dans la config Tracim"

**Comment by inkhey** [comment]
Windows 10 ne semble pas concerné par le problème. Il ne doit probablement pas passer par l'instruction MOVE pour faire des déplacement.

**Comment by inkhey** [comment]
Already merge.
