### ISSUE TITLE
Bug: Clicking on the new folder creation notification does not link to the folder

### ISSUE THREAD

**Issue by agile-marmot** [tracim/tracim#5395]
## Description and expectations

When we click on a notification of "A has created folder X" we are taken to a page that tells us the type of content allowed for this folder instead of the content of said folder.

As a user I expect that when I click on a folder in the breadcrumbs or when I click on a folder creation notification, I expect that I will be redirected to the list of contents with the scroll positioned in that folder and that it is open. 

### How to reproduce

1. Ask someone to create a folder
2. Open your notification wall
3. Click on the folder creation notification

Or

1. Create a folder
2. Create a content X inside your folder
3. Go to recent activities
4. Click on the folder on the breadcrumbs of the content X activity

Systematically occurring expect for breadcrumbs inside an app content.

### Version information

- Tracim version: v4.1
- Web browser: Google Chrome
- Device / System: PC

________________________________________________

## PR

#5695

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by gbonaspetti** [comment]
Done
