### ISSUE TITLE
Champ avec URL calendrier perso: disabled

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#54]
Empêche le clic droit sous certain navigateurs

**Comment by tracim** [comment]
Remove the "disabled" in order to be able to copy/paste

**Comment by Skylsmoi** [comment]
Thoses fields are not "disabled", they are "readonly".
I have removed the input tag and switched it to a div (with same display) so there wont be any copast issues anymore.
merge requesting soon

**Comment by tracim** [comment]
fixed with https://github.com/tracim/tracim/pull/379
