### ISSUE TITLE
"COPY" method not implemented in webdav -> file copy not working on some webdav clients.

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#540]
COPY method for webdav is now not implemented in tracim webdav feature.
 The consequence is that file copy (copying a file from webdav to webdav into the same or a different folder) doesn't work on some client like nautilus 3.22. (Problem appear somewhere after nautilus 3.14.1)
Some other client like thunar are working because they don't rely on COPY to copy file, they do a PUT like for creating a new file.

Solution to fix this bug: 
-  implement "copy" method into content API, like the "move" one
- Create copyMoveSingle method in File (lib/webdav/sql_ressource.py) and  check move_file method.

**Comment by lebouquetin** [comment]
I do not understand this bug. This feature has been working in the past.

**Comment by inkhey** [comment]
Log of the issue :
```
<139851785565952> 127.0.0.1 - admin@admin.admin - [2018-03-07 15:18:47] "PROPFIND /Test_windows/test.png" length=235, depth=0, elap=0.072sec -> 207 Multi-Status
<139851785565952> 127.0.0.1 - admin@admin.admin - [2018-03-07 15:18:47] "PROPFIND /Test_windows" length=235, depth=0, elap=0.026sec -> 207 Multi-Status
<139851785565952> 127.0.0.1 - admin@admin.admin - [2018-03-07 15:18:47] "PROPFIND /Test_windows" length=155, depth=0, elap=0.026sec -> 207 Multi-Status
<139851785565952> 127.0.0.1 - admin@admin.admin - [2018-03-07 15:18:47] "PROPFIND /Test_windows/test.png" length=235, depth=0, elap=0.054sec -> 207 Multi-Status
<139851785565952> 127.0.0.1 - admin@admin.admin - [2018-03-07 15:18:47] "PROPFIND /Test_windows/test.png" length=235, depth=0, elap=0.054sec -> 207 Multi-Status
<139851785565952> 127.0.0.1 - admin@admin.admin - [2018-03-07 15:18:47] "PROPFIND /Test_windows/test.png" length=235, depth=0, elap=0.053sec -> 207 Multi-Status
<139851785565952> 127.0.0.1 - admin@admin.admin - [2018-03-07 15:18:47] "PROPFIND /Test_windows/test.png" length=146, depth=0, elap=0.064sec -> 207 Multi-Status
<139851785565952> 127.0.0.1 - admin@admin.admin - [2018-03-07 15:18:47] "PROPFIND /Test_windows/test (copie).png" length=146, depth=0, elap=0.027sec -> 404 Not Found
Traceback (most recent call last):
  File "/usr/share/tracim/test_webdav_patch/venv3.5/lib/python3.5/site-packages/wsgidav/request_server.py", line 1046, in _copyOrMove
    sRes.copyMoveSingle(dPath, isMove)
  File "/usr/share/tracim/test_webdav_patch/venv3.5/lib/python3.5/site-packages/wsgidav/dav_provider.py", line 1011, in copyMoveSingle
    raise NotImplementedError()
NotImplementedError
<139851785565952> 127.0.0.1 - admin@admin.admin - [2018-03-07 15:18:47] "COPY /Test_windows/test.png" dest="https://caribou/webdav/Test_windows/test%20%28copie%29.png", depth=0, overwrite=F, elap=0.095sec -> 500 Internal Server Error
<139851785565952> 127.0.0.1 - admin@admin.admin - [2018-03-07 15:18:47] "PROPFIND /Test_windows/test.png" length=235, depth=0, elap=0.053sec -> 207 Multi-Status
```

**Comment by buxx** [comment]
> I do not understand this bug. This feature has been working in the past.

In the past we have had to correct copy related problems. But these copying problems were produced in a context where customers were doing a simple PUT (or I'm misinformed).

In this case, the customer uses the webdav COPY statement, which we understand is simply not implemented. Certainly because at the time of writing the code, no client was using this instruction. The developer's judging it to be low-priority.

**Comment by inkhey** [comment]
Windows 10 seems to not be affected by this bug. It probably don't rely on "COPY" statement .
