### ISSUE TITLE
Bug: pages take a long time to load for the least efficient connections

### ISSUE THREAD

**Issue by agile-marmot** [tracim/tracim#5403]
## Description and expectations

- Make an evaluation of what is causing the lag.
  - One point already noticed is the revision endpoint when a content is very big. 
- List all the points found citing their importance for the problem and the difficulty of solving it. 
- Discuss with the team which points should be solved in this sprint.

### Version information

- Tracim version: v4.1.3

________________________________________________

**Comment by lebouquetin** [comment]
> > One point already noticed is the revision endpoint when a content is very big.

Another point already noticed is the number of API calls, some being executed several times.

**Comment by lebouquetin** [comment]
The use case to have in mind is a very slow mobile connection - which make tracim totally unusable at the moment

**Comment by PhilippeAccorsi** [comment]
Maybe another information is to check what is going on with connection with very slow response time (ping near 500-1000ms).

**Comment by gbonaspetti** [comment]
Done
