### ISSUE TITLE
Bug: content is still displayed in the activity feed even after deletion

### ISSUE THREAD

**Issue by agile-marmot** [tracim/tracim#5404]
## Description and expectations

When a content is deleted, it's preview is still visible on activity feed. As a user I don't want other person to see the content that I deleted, but as a manager I don't want to loose the summary of changes.

To do:
- [x] do not show the preview of deleted contents

### How to reproduce

1. Go to a content
2. Delete it
3. Go to dashboard of space's content  

### Version information

- Tracim version: v4.1.3
- Web browser: Google Chrome
- Device / System: PC

________________________________________________

## Implemented

Add condition based on TLM informations.
For notification wall we have a configuration to disable if the clients want it.

### PR
#5657

**Comment by Relf-Algoo** [comment]
Check internally regarding the notification wall too

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by gbonaspetti** [comment]
Done
