### ISSUE TITLE
Bug: Sidebar menu does not collapse when editing html notes in full screen

### ISSUE THREAD

**Issue by agile-marmot** [tracim/tracim#5407]
### How to reproduce

1. Go to HTML note
2. Click on Fullscreen icon

### Version information

- Tracim version: [e.g. v2.7, Mon Tracim]
- Web browser: [e.g. Google Chrome, Firefox, Safari]
- Version: [e.g. 22, latest]
- Device / System: [e.g. PC, iPhone 6]

## Related PR
PR #6058

**Comment by Relf-Algoo** [comment]
tried tro recreate the problem. Didn't work on our tracim 4.1.3 build 047.
