### ISSUE TITLE
Feat: Use TinyMCE 5.10 (migrate from version 4.7)

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#5409]
## Feature description and goals

TinyMCE 4.7 reached EOL support last December. What's more, TinyMCE 5 fixes problems related to switches between  RTL and LTR languages. 

Included in this development:
 - keep the custom buttons
 - use the custom mechanism to insert image in the context menu
 - add select all, copy, paste entries in the context menu so people who don't know the keyboard shortcuts can be helped
 - remove some TinyMCE 5 toolbar borders, as we did for the previous version of TinyMCE
 - remove two deprecated plugins which functionalities are in the core of TinyMCE anyway
 - fixes for mentions in fullscreen in the timeline (comment) and the publications.

## PR
https://github.com/tracim/tracim/pull/5411

**Comment by raphj** [comment]
This needs to be tested quite intensively (everywhere TinyMCE is used, also check things like mentions).
There are bugs that were already present before the migration. If you run into bugs while testing this, be sure to check those are new.

**Comment by knodelle** [comment]
done
