### ISSUE TITLE
Misc: the wrong debouncedCheckUsername function is used in frontend/src/container/Home.jsx

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#5414]
## Feature description and goals

While investigating #3483, I noticed the wrong debouncedCheckUsername function is used in frontend/src/container/Home.jsx. A PR shall fix this.

**Comment by inkhey** [comment]
@raphj is there anything to test here ? and if yes,  how ?

**Comment by raphj** [comment]
@inkhey yes, you need to create a user without a username. Log in with this new user and check that:
 - you can still set a valid username
 - attempts to use an invalid username are blocked

**Comment by inkhey** [comment]
tested on branch

**Comment by knodelle** [comment]
done
