### ISSUE TITLE
Copy comments when using copy feature of contentAPI

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#543]
New copy feature of content (see https://github.com/tracim/tracim/pull/542 ) doesn't copy comments related to the content. They should be added to copy file.

**Comment by inkhey** [comment]
Feature added to #542 . 
Up to now, comments are created the same way content is created, that's why : 
- Creation date is almost same to new copied file creation.
- User who did comment is the creator of the copy of the file.

Should we save user/creation_date :
- for all copied files .
- only for comments. 
- not at all (current behaviour).

**Comment by lebouquetin** [comment]
when copied, information must stay the same : creation datetime, author, etc must be copy of the original information (not owned by the copy author)
