### ISSUE TITLE
Misc: Make TinyMCE's height adapt to its container's height 

### ISSUE THREAD

**Issue by raphj** [tracim/tracim#5442]
## Feature description and goals

Since migrating to TinyMCE 5, the `height: 100%` style that is applied to it does not work (anymore?).
To avoid custom styles and workarounds and arbitrary sizes wherever TinyMCE is embedded, find a way to make it adjust to its container automatically.

## Related PR
PR #6058

**Comment by raphj** [comment]
We shall decide rules to size TinyMCE appropriately, including on small and mobile screens

**Comment by Quiwy** [comment]
I guess I'm facing the same issue here.

I want to edit a "large" discussion (more than 25 words) and it's quite annoying to have to scroll a lot, even more if you have images on the discussion :

![image](https://user-images.githubusercontent.com/20048264/166455249-b13ea6bf-45ba-4e01-a697-b7d8812b49fa.png)

**Comment by raphj** [comment]
@Quiwy This issue is a technical debt (only an issue for developers). Your issue is more that you find the TinyMCE component too small. You should file a new issue for this, something like "The tinyMCE component is too small when editing a comment".

As a workaround, I suggest you to use the full screen feature of TinyMCE (which corresponds to the last icon in your screenshot. That should allow you to comfortably write a long comment with big images.

See also: https://github.com/tracim/tracim/issues/4583
