### ISSUE TITLE
Bug: The position of two authors avatar (grouped) is wrong in RTL

### ISSUE THREAD

**Issue by Haskaris** [tracim/tracim#5444]
## Description
Here is how a multi author notification is in LTR:
![image](https://user-images.githubusercontent.com/28917197/154510643-7c61d77c-02fa-4a0d-8eb8-1cedf5400b3c.png)
Here is how it currently is in RTL:
![image](https://user-images.githubusercontent.com/28917197/154510764-7e6a89e9-7f01-4648-80e5-9cb8f1d3fa68.png)
Here is how it should be in RTL:
![image](https://user-images.githubusercontent.com/28917197/154511004-6dc17175-5a43-49b6-8377-576c1f664db4.png)

## How to reproduce
Manage to get a multi author notification, then change the interface in RTL.

### How to get a multi author notification
You need 3 differents accounts.
With account A create a discussion/document and start a conversation with account B in the same thread.
Check notification with account C.

## Linked PR
PR #5445

**Comment by inkhey** [comment]
@Haskaris don't forget to complete this issue later.

**Comment by inkhey** [comment]
@Haskaris Can you explain how to reproduce the issue ?

**Comment by Haskaris** [comment]
@inkhey issue completed, plus with some "how to" :)

**Comment by inkhey** [comment]
tested on branch

**Comment by knodelle** [comment]
done
