### ISSUE TITLE
Bug: 16th sprint integration fixes

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#5446]
## Description and expectations

This issue is here to document commits done during the integration phase (quick fixes):

- [x] sidebar's folded icon of parent spaces has the wrong orientation in RTL (9dd9a1711)
- [x] kanban's "exit fullscreen" button is still on the right side in RTL (and is hidden by the sidebar) (8068c650b)
- [x] fix typo at API (https://github.com/tracim/tracim/commit/d006e779b9d0569e05e9ddc4d5845964da1f4bbe)
- [x] the mentions in the notes do not work and make the notification point to `/api/contents/null` (https://github.com/tracim/tracim/commit/ca4f074575616ccea2162620fa451effbd4194ee)
- [x] Unable to close the "Tags" filter in the advanced filters (https://github.com/tracim/tracim/commit/8f7e84bdbcd9342f2bb05198e211e59ce7a8944e)

**Comment by knodelle** [comment]
done
