### ISSUE TITLE
 Bug: Entries of the action menu of the app file aren't suppressed when we change the interface direction from RTL to LTR

### ISSUE THREAD

**Issue by Haskaris** [tracim/tracim#5452]
## Description and expectations

When changing the language from Arabic to English, the entries of the action menu of the app file aren't suppressed.
The expected behavior is to be the same as English to Arabic.

### How to reproduce

1. Go to app file
2. Change language from Arabic to English

### Version information

- Tracim version: 4.1.2.build-069

### Screenshots

![image](https://user-images.githubusercontent.com/28917197/154915331-9bd49ffc-4f46-45d2-8c18-15dc3ec41096.png)

## Linked PR
#5458

**Comment by knodelle** [comment]
tested on branch

**Comment by knodelle** [comment]
done
