### ISSUE TITLE
Bug: the bottom of notes sometimes is hidden 

### ISSUE THREAD

**Issue by charline-rageade** [tracim/tracim#5453]
## Description and expectations

![6p23dDN](https://user-images.githubusercontent.com/35422692/155511531-1174d13d-9f9f-49c6-9071-b576b1b0fc01.png)

### Version information

- Tracim version: v4.1
- Web browser: Brave
- Device / System: PC

________________________________________________

## PR
https://github.com/tracim/tracim/pull/5462

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by gbonaspetti** [comment]
Done
