### ISSUE TITLE
Feat: Highlight spaces and add number of notifications 

### ISSUE THREAD

**Issue by agile-marmot** [tracim/tracim#5454]
## Feature description and goals

- [x] If notification (not mention), bold title
- [x] If mention, red circle with number
- [x] Space click, read notification (not mention)

## Linked PR
PR #5505

## Branch
[feat/5454__highlight_space_and_add_mentions](https://github.com/tracim/tracim/tree/feat/5454__highlight_space_and_add_mentions)

**Comment by knodelle** [comment]
tested on branch

**Comment by knodelle** [comment]
done
