### ISSUE TITLE
[META] Bug: add Arabic translation at welcome page and better integrate kanban

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5466]
## Description and expectations

- [x] On the Welcome page, we list the available languages. We need to remove the flags and include Arabic. https://github.com/tracim/tracim/pull/5480
- [x] The title (columns and cards) and description on a kanban are not `unicode-bidi: plaintext`. And scroll doesn't works in rtl. https://github.com/tracim/tracim/pull/5481

### Version information

- Tracim version: 4.1.2
- Web browser: Google Chrome
- Device / System: PC

________________________________________________

**Comment by gbonaspetti** [comment]
https://github.com/tracim/tracim/pull/5480 was tested on branch

**Comment by knodelle** [comment]
#5481 was tested on branch

**Comment by knodelle** [comment]
done
