### ISSUE TITLE
"Pin to workspace" feature

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#547]
Use case : imagine your development workspace. Documents like coding rules, good habits are very important for this workspace. It would be helpfull for developers to have access to these documents straight from workspace home page. A button "pin to workspace" would put the document on home page.

This feature is similar to "favorites", except that favorites are for the user himself and "pin this" is for all workspace members.

**Comment by buxx** [comment]
Maybe this feature can be developed as a plugin ?

**Comment by Quiwy** [comment]
Closed in favor of #5833
