### ISSUE TITLE
Bug: The pagination disappeared from the preview of files 

### ISSUE THREAD

**Issue by Relf-Algoo** [tracim/tracim#5471]
## Description and expectations

when opening a file content, the pagination disappeared from the interface. Previously, in 4.0.2, there was a line at the bottom right saying page 1 of 6.
In version 4.1.1 the line is no more present.

### How to reproduce

1. Go to a file with 2 pages or more

### Version information

- Tracim version: 4.1.1
- Web browser: Firefox
- Version: latest
- Device / System: work laptop, ubuntu 20.04

### Screenshots

________________________________________________

## Linked PR
https://github.com/tracim/tracim/pull/5583

**Comment by knodelle** [comment]
done
