### ISSUE TITLE
📝 Documentation: upgrade to 4.2.0

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#5479]
:warning:  this is necessary since build_070

Several changes have been introduced in version 4.2.0: 

## Configuration update (`development.ini`)

Radicale has been updated to 3.*, you will need to update developement.ini. You can either : 
- For Docker : Remove the `developement.ini` from docker volume placed in `/etc/tracim` in the official docker image which will automatically regenerate the development.ini configuration.
- For Non-Docker install: replace `development.ini` by `development.ini.sample` placed in backend directory.
- Both Docker and Non-Docker install : if you want to keep your settings, change theses variables from development.ini :
    - `caldav.radicale.server.host` renamed to `caldav.radicale.server.hosts` (see the trailing s)
    - `caldav.radicale.auth.type` valid value change from `None` to `none`
    - `caldav.radicale.rights.type`  valid value change from `None` to `tracim_backend.radicale_plugins.allow_all_access_rights `
    - `caldav.radicale.web.type` valid value change from `None` to `none`
    - the `listen` value in ` [server:caldav]` should be adapted accordingly : 
      -  `listen = %(caldav.radicale.server.host)s` replaced to `listen = %(caldav.radicale.server.hosts)s`

:warning: these parameters are not settable through env var, these changes are required to run Tracim. The Caldav process can not run without them.

## Re-index advanced search

Advanced Search (Elasticsearch) has been improved. If you use it, You need to you will need to rebuild the index using tracimcli command lines. 

The process for the official docker image is this one:

```bash
docker exec -it -u www-data -w /etc/tracim {CONTAINER ID} tracimcli
search index-drop -d
search index-create -d
search index-populate -d
```

If you use Tracim in another context, the process is similar, simply run `tracimcli` from:
- the directory where `development.ini` is placed.
- make sure you are in the correct python environment.
- run theses command lines:

```bash
tracimcli
search index-drop -d
search index-create -d
search index-populate -d
```

## API BREAKING CHANGE

If you are using the Tracim API for script, there is some breaking change you need to be careful of.

- properties `page_nb`, `has_pdf_preview`, `has_jpeg_preview` from  `GET /api/workspaces/{workspace_id}/files/{content_id}` have been moved to new endpoint `GET /api/workspaces/{workspace_id}/files/{content_id}/preview_info`, see below:

```
GET /api/workspaces/{workspace_id}/files/{content_id}/preview_info
{
  "content_id": 6,
  "has_jpeg_preview": true,
  "has_pdf_preview": true,
  "page_nb": 1,
  "revision_id": 12
}
```

- properties  `page_nb`, `has_pdf_preview`, `has_jpeg_preview`  from  /`api/workspaces/{workspace_id}/files/{content_id}/revisions/{revision_id}` has been moved to new endpoint `GET /api/workspaces/{workspace_id}/files/{content_id}/revisions/{revision_id}/preview_info`, see below:

```
GET /api/workspaces/{workspace_id}/files/{content_id}/revisions/{revision_id}/preview_info
{
  "content_id": 6,
  "has_jpeg_preview": true,
  "has_pdf_preview": true,
  "page_nb": 1,
  "revision_id": 12
}
```

**Comment by grignards** [comment]
I'm unsure whether this is the right place to inform about an HTTP API breaking change: #5495 moved the fields (`page_nb`, `has_pdf_preview`, `has_jpeg_preview`) attributes from `/api/workspaces/{workspace_id}/files/{content_id}` and `/api/workspaces/{workspace_id}/files/{content_id}/revisions/{revision_id}` to `/api/workspaces/{workspace_id}/files/{content_id}/preview_info`/`/api/workspaces/{workspace_id}/files/{content_id}/revisions/{revision_id}/preview_info`.
@knodelle @PhilippeAccorsi Any opinion? This breaking change information is useful for people directly using the HTTP apis (so developers, not directly sysadmins).

**Comment by PhilippeAccorsi** [comment]
I think the breaking change need to be visible directly in the changelog to make sure user/admin/dev see this information (we have done some breaking change for api in the past, maybe look in changelog to see what we done).

All existing user make script to use this feature are impacted.

**Comment by PhilippeAccorsi** [comment]
Old release. We can close.
