### ISSUE TITLE
Feat: Put caldav and webdav links at space settings

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5482]
## Feature description and goals

For a better UX and a cleaner interface, we should change caldav and webdav links from dashboard. 
These links are not used in a daily base.

- [x] Put caldav link at space settings (on the left part)
- [x] Put webdav link at account settings with the personal agenda 
- [x] Change the "agenda" tab name to "configuration links" at account settings

Follow up issue: https://github.com/tracim/tracim/issues/5501

## Prerequisites

None

## PR
https://github.com/tracim/tracim/pull/5486

**Comment by PhilippeAccorsi** [comment]
I'm not sure about added this two part in space setting.

2 idea:
- add this two information in account setting space menu
- add a link to a popup in dashboard, and show all information in the popup

**Comment by gbonaspetti** [comment]
Description updated and issue about centralize agenda's information created: https://github.com/tracim/tracim/issues/5484

**Comment by knodelle** [comment]
tested on branch

**Comment by knodelle** [comment]
done
