### ISSUE TITLE
Feat: add caldavzap translation on Weblate

### ISSUE THREAD

**Issue by agile-marmot** [tracim/tracim#5491]
## Feature description and goals

- [x] Create a caldav_translation folder on frontend_lib 
- Add all caldav translation keys for at least : 
  - [x] French
  - [x] English
  - [x] Arabic
  - [x] German
- [x] Add a new component on Weblate that whats changes on the folder above
- [x] Add the translations that we already have for the languages above (copy paste)
- [x] Add an Github settings for link Weblate and this folder
- [x] Update documentation

## Linked PRs

Documentation: https://github.com/tracim/tracim/pull/5519
Add folder and files: https://github.com/tracim/tracim/pull/5514

**Comment by knodelle** [comment]
Can I move this to "need test on develop"?

**Comment by gbonaspetti** [comment]
> Can I move this to "need test on develop"?

Someone has tested?

**Comment by knodelle** [comment]
done
