### ISSUE TITLE
Bug: Sometimes the `الكل@` does not work

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5493]
## Description and expectations

It seems to be related to the fact that there is another mention in the comment and that the Arabic `@all` is at the beginning

### How to reproduce

1. Go to a file
2. Comment "`@الكل` jsdiqojdiojdqs `@another_member`"

### Version information

- Tracim version: v4.1
- Web browser: Google Chrome
- Device / System: PC

________________________________________________

## Diagnostic and implementation solution

The detection of a mention used to be done using two regex but as soon as it found a mention from the first regex it didn't go back to check if it had a previous mention from the second. to avoid this the current algorithm looks at both and starts wrapping the mention closer to the beginning of the sentence.

PR #5522

**Comment by knodelle** [comment]
tested on branch

**Comment by knodelle** [comment]
done
