### ISSUE TITLE
Bug: simple text entry box overrides the 'publish' button

### ISSUE THREAD

**Issue by agile-marmot** [tracim/tracim#5494]
### How to reproduce

1. Go to a news
2. Click on text box for overrides

### Version information

- Tracim version: [e.g. v2.7, Mon Tracim]
- Web browser: [e.g. Google Chrome, Firefox, Safari]
- Version: [e.g. 22, latest]
- Device / System: [e.g. PC, iPhone 6]

### Screenshots

![index](https://user-images.githubusercontent.com/82377347/157004261-3b5f0c8d-a51d-4700-94f6-044fc0261ca0.png)
________________________________________________

## PR

https://github.com/tracim/tracim/pull/5524 (also fix the autocomplete position)

**Comment by knodelle** [comment]
tested on branch

**Comment by knodelle** [comment]
done
