### ISSUE TITLE
Bug: Add loader when downloading files on comments

### ISSUE THREAD

**Issue by knodelle** [tracim/tracim#5496]
## Description and expectations

Add loaders to the timelines of : 

- [x] Threads
- [x] Files
- [x] Kanban
- [x] Notes

On comments, when the user uploads a file, the download loader is not showing, so the user has no information about whether the file is loading or not.

### Version information

- Tracim version: [e.g. v2.7, Mon Tracim]
- Web browser: [e.g. Google Chrome, Firefox, Safari]
- Version: [e.g. 22, latest]
- Device / System: [e.g. PC, iPhone 6]

### Screenshots

________________________________________________

## Prerequisites

PR: #https://github.com/tracim/tracim/pull/5664

**Comment by PhilippeAccorsi** [comment]
Is it a regression ? (if yes I think its a good idea to indicate that in title.

**Comment by gbonaspetti** [comment]
> Is it a regression ? (if yes I think its a good idea to indicate that in title. And add a specific test for that)

No, it's not a regression. I updated the title to be more understandable.

**Comment by PhilippeAccorsi** [comment]
> On comments, when the user uploads a file, the download popup is not showing,

I think something not clear in the description. Is it a loader when uploading file in comment or when downoding file from app file ?
I think is it a good idea to add "comment" in issue title.

:)

**Comment by inkhey** [comment]
tested on branch

**Comment by gbonaspetti** [comment]
Done
