### ISSUE TITLE
Feat: Notification refactor

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5497]
## Feature description and goals
The current notification system (with redux) use an arborescent list.
Groups notification are done in redux, which leads to list of list.
This was originialy done for the notification wall.
However this logic should be done in the wall notification component.
The notification system should be generic, and use a flat list of notification.

## Prerequisite
~~#5505 (issue #5497)~~ (done)

## Linked PR
PR #5521

**Comment by knodelle** [comment]
tested on branch

**Comment by knodelle** [comment]
done
