### ISSUE TITLE
Bug: comment editing not possible in responsive

### ISSUE THREAD

**Issue by agile-marmot** [tracim/tracim#5506]
## Description and expectations

When a user wants to edit a comment that has already been posted, they are unable to do so. The popup is too wide and the submit button is not visible. 

### How to reproduce
With your mobile

1. Go to a comment
2. Click on Edit

### Version information

- Tracim version: [Tracim 4.1.3_build70]
- Web browser: [Google Chrome, Firefox]
- Device / System: [Smartphone]

### Screenshots
![Capture d’écran du 2022-03-09 11-37-25](https://user-images.githubusercontent.com/82377347/157425045-ee96d341-def8-4d98-9bd5-f14432cc31ae.png)

________________________________________________

## To testers
Somehow this bug only appears on mobile devices (ie: smartphone), you will have to try it on your smartphone.

## Linked PR
PR #5584

**Comment by PhilippeAccorsi** [comment]
In oldest version of tracim, we can use all popup correctly.
Maybe wrong choice of the minimal resolution for responsive.

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by knodelle** [comment]
done
