### ISSUE TITLE
Bug: Dashboard", "News", "Contents" tabs are misplaced on mobile phones and also on desktop if news not activated

### ISSUE THREAD

**Issue by agile-marmot** [tracim/tracim#5507]
## Description and expectations
The three tabs Dashboard", "News", "Contents" are positioned on the left side of the screen in the main screen of the space whereas before they were positioned on the left. 

### How to reproduce

1. Go to a space
2. Look at the tabs

### Version information

- Tracim version: [4.1.3_build070]
- Web browser: [Opera, google Chrome]
- Device / System: [smartphone]

### Screenshots

![Capture d’écran du 2022-03-09 11-48-50](https://user-images.githubusercontent.com/82377347/157426981-24eb0e10-7951-4446-b9b1-3cf5667f442b.png)

________________________________________________

## Diagnostic

Surely a regression

## Prerequisites

N/A

**Comment by PhilippeAccorsi** [comment]
this is not just on mobile. On desktop if News is not activated, all tab is not on the good position.

![Screenshot 2022-03-17 at 17-26-47 Tableau de bord · Z1 👥 Discussions privées · Algoo](https://user-images.githubusercontent.com/25848257/158847517-02a64180-f213-42b0-8dcd-cb949657fee3.png)

**Comment by knodelle** [comment]
done
