### ISSUE TITLE
Bug: create news with file transform news to a file with comment

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#5510]
## Description and expectations

I create a **News** with some comment and I want to join file to this news. So I click in input form `Share a news…` to write some text and I click on button `attach file` to join also a screenshot.
When I click on `Publish`, Tracim create something like a **News** (color of icon is the good one) but it still a file with some comment, and not a news with comment and attached file.

So by default, in the news tab, I not seen something like `Publication of Philippe on 4/21/2021, 4:56:45 PM` but something like that `25848257 (13/08/2021 à 16:32:38).jpeg`.

I can't also `Open as content` with thread app. Tracim just open file and all comment are added to this file.

### How to reproduce

- open news tab
- create a news and add file directly
- click on publish button

### Version information

- Tracim version: 4.1.3 build_070
- Web browser: Firefox
- Version: 97.0.2
- Device / System: Ubuntu 20.04

### Screenshots

https://user-images.githubusercontent.com/25848257/157454386-59598d56-d625-49e1-8f52-bcd818637ffd.mp4

________________________________________________

**Comment by gbonaspetti** [comment]
Fixed at #5799
