### ISSUE TITLE
Bug: list of modifications is not displayed any more

### ISSUE THREAD

**Issue by Relf-Algoo** [tracim/tracim#5513]
## Description and expectations

In th eliste of recent activities, each item has a last modification frame. this frame is supposed to show the list of modifications when clicked on. The click works, but the list is hidden. One can see it appear, but it is hidden by other things.
In the same way, when the path to the content is too long, the las modification is not completely displayed.

Might be related to Z-index

### How to reproduce

1. Go to Recent Activities
2. Click on the last modification of one content

### Version information

- Tracim version: prod 4.1.3 build 070 and preprod
- Web browser: firefox
- Version: latest
- Device / System: work laptop and personnal computer

### Screenshots
![Capture d’écran de 2022-03-18 14-12-16](https://user-images.githubusercontent.com/28917197/159009068-5f663642-0f41-4851-a782-6473a8ad6e2d.png)

________________________________________________

**Comment by knodelle** [comment]
done
