### ISSUE TITLE
Bug: Can't mark a group of notification as read

### ISSUE THREAD

**Issue by Haskaris** [tracim/tracim#5526]
## Description and expectations

#5497 bring a regression. With the refactoring of notifications, the possibility of marking a group as read by clicking on the little dot has disappeared.

### How to reproduce

1. Make a notification group
2. Click on the blue dot

## Linked PR
PR #5903

## Implemented solution
I've modified the `read every messages` endpoint to accept a list of messages to read. If there is no list then it will read every messages.
Also put `read one message` as deprecated since we are not using it anymore.

**Comment by Haskaris** [comment]
This was started during integration phase of Tracim 4.3.2 build_91
Since it has some _major_ change I decided to create a dedicated PR (#5903).

**Comment by Haskaris** [comment]
I've created a ticket for deprecated code #5941

**Comment by Quiwy** [comment]
Tested on branch

**Comment by Millefeuille42** [comment]
Done
