### ISSUE TITLE
Feat: with Tracim in Arabic the first day of a week should be the Saturday

### ISSUE THREAD

**Issue by Haskaris** [tracim/tracim#5532]
## Feature description and goals

The Arabic calendar start the week on Saturday, we have to change it to start on Saturday.

As an Arabic user, I expect to see the first day of a week to be Saturday.

- [x] Update Agendas app
- [x] Update date filter (if needed)

PR https://github.com/tracim/tracim/pull/5551

**Comment by gbonaspetti** [comment]
Update to Saturday, not Sunday

**Comment by knodelle** [comment]
tested on branch

**Comment by knodelle** [comment]
done
