### ISSUE TITLE
Bug: We can only see the end of the content title if too big in rtl

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5533]
## Description and expectations

We can only see the end of the content title if too big in rtl.

![Capture d’écran de 2022-03-21 10-26-44](https://user-images.githubusercontent.com/35422692/159234356-e25f3353-566e-4727-a612-6c176cc40697.png)

Note: it works for file type.

### Version information

- Tracim version: v4.1.3_build_073
- Web browser: Google Chrome, Firefox
- Device / System: PC

## Linked PR
PR #5548

**Comment by knodelle** [comment]
tested on branch

**Comment by knodelle** [comment]
done
