### ISSUE TITLE
Bug: List are aligned to the right even with LTR input when Arabic is the user language

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#5534]
## Description and expectations

When a user who selected Arabic as language displays a note written in a LTR language, the lists are aligned to the right.

As the language is LTR they should be aligned to the left instead.

## Screenshots

![image](https://user-images.githubusercontent.com/51887114/159235284-e6914dbc-5c16-4394-b297-02e698a30d9d.png)

**Comment by Skylsmoi** [comment]
Solution is to add html attribute dir='auto' on the <ul> and <ol> tags.
To do so, I override tincyMCE `InsertUnorderedList` and `InsertOrderedList` commands to customize the parameter `value` to add the key `dir: 'auto'` to the value.['list-attributes'] object.

**Comment by Skylsmoi** [comment]
I couldn't understand why there is the need to manually add the `dir='auto'` on each `<ul>` and `<ol>` though

My solution is kind of a workaround

**Comment by inkhey** [comment]
tested on branch,

Just 2 points:

1. as far i see to decide which alignment, it's based on the first list element which is important to known in case of mixed content
2. the behavior is a bit strange with sub list which can have a different alignemen than the parent, don't know if this is a real issue.

**Comment by knodelle** [comment]
done
