### ISSUE TITLE
Bug: Preview is always showing the first page

### ISSUE THREAD

**Issue by knodelle** [tracim/tracim#5536]
## Description and expectations

On full screen, the preview of a document is always showing the first page of a document, even when you switch page on the preview. 

Check if this still happens in the current version 4.1.3_build_73

### How to reproduce

1. Go to…
2. Click on…
3. Scroll down to…

### Version information

- Tracim version: [e.g. v2.7, Mon Tracim]
- Web browser: [e.g. Google Chrome, Firefox, Safari]
- Version: [e.g. 22, latest]
- Device / System: [e.g. PC, iPhone 6]

### Screenshots

________________________________________________

**Comment by grignards** [comment]
I checked with the content where the bug occured with build 73: the fullscreen preview page is properly changed.
So I think we can close this issue/move it to done.

**Comment by gbonaspetti** [comment]
Duplicated of #5529
