### ISSUE TITLE
Meta: What should be the model of a content in Tracim?

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#5538]
## Feature description and goals

This issue is here to list questions and ideas on the modeling of contents in Tracim.
The model has mainly three views/aspects: for a frontend user, for an API user, for a Tracim backend developer (more or less the database modeling).

- provide a definition of a content's metadata: where is the limit (e.g. the mimetype of a content is clearly metadata, but what of its label?)
- the current HTTP API (as of tracim v4.1) has several differences between content types (mainly notes/thread/file): are those still useful, would a unified API be functional?
- What should be the status of comments (as of tracim v4.1 they are contents in the db, but not in the API)?
- …

**Comment by Skylsmoi** [comment]
feature model is live, closing this issue
