### ISSUE TITLE
Bug: regression: download links (pdf, file) give an undefined filename

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#5539]
## Description and expectations

Downloading a file gives an `undefined` filename.

### How to reproduce

1. Try do download a file
2. 
3. 

### Version information

Tracim 4.1.3_build73.

### Screenshots

________________________________________________

## Implemented solution

Properly extract the filename from the state.

**Comment by TheFenrisLycaon** [comment]
I would like to work on this one.

**Comment by charline-rageade** [comment]
Hi @TheFenrisLycaon ! It makes us super happy that you want to contribute! However, this issue had to be quickly corrected! If you want to contribute on other tissues, share your preferences with us, and we'll guide you to tickets you might like!

**Comment by TheFenrisLycaon** [comment]
I'm relatively new to open source so I'd liek so simple tickets. Have any suggestions?

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by TheFenrisLycaon** [comment]
Thanks @gbonaspetti , I'll get started.

**Comment by knodelle** [comment]
done
