### ISSUE TITLE
Feat: mail addresses not checked when input in Tracim fields

### ISSUE THREAD

**Issue by Relf-Algoo** [tracim/tracim#5558]
## Feature description and goals

Administrator and/or user that want to invite other users do so whit mail addresses. But there is no check done on the appropriate fields. So when users make mistakes, the account is not created, or the invitee receives no mail and there is no error messages.

2 types of mistakes have been reported : 
- [x]  spaces in front or after the address
- [x] address copied from thunderbird or outlook include First name + Last name + Address. For example : `"Barbara Kamar <barbara@barbara.barbara>"`

The relevant checks and potential error messages must be applied on all fields destined to receive mail addresses.

## Linked PRS
PR #5581  (for the first point)
PR #5592 (for the second point)

**Comment by inkhey** [comment]
Not check need to be made in both frontend and backend to list the distinct place with email and how each one react.

**Comment by gbonaspetti** [comment]
First element tested

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by knodelle** [comment]
done
