### ISSUE TITLE
Bug: Test test_unit__submit_job__OK_nominal_case stuck in some edge case

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#5560]
## Description and expectations

the test `test_unit__submit_job__OK_nominal_case`  set a 2 sec timeout for rq jobs, in case this timeout is not enough , the test is keep stuck in an infinite loop.

## Implemented solution:
https://github.com/tracim/tracim/pull/5561

- set rq jobs timeout to 30 s
- set global test timeout to 45s.

**Comment by knodelle** [comment]
done
