### ISSUE TITLE
Bug: horizontal scroll appear in upload file popup with long name

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#5566]
## Description and expectations

When I choose a file with a long label like this `Screenshot 2022-02-07 at 11-20-32 Password Strength Meters – more harm than good .png`, an horizontal scroll bar appear but all information are shown correctly in the popup. I can move the scroll bar but no more information are visible.

### How to reproduce

- Add a file with this name in upload new file popup
=> scroll bar appear directly

### Version information

- Tracim version: 4.1.3 build_074 on "build_version": "a3ab051da0"
- Web browser: Firefox
- Version: 98.0.2
- Device / System: Ubuntu 20.04

### Screenshots

![Screenshot 2022-03-30 at 18-26-44 Nouveau fichier · test · Unstable](https://user-images.githubusercontent.com/25848257/160885575-079c748a-a309-488c-a54a-9efa5d434c9e.png)

________________________________________________

**Comment by Haskaris** [comment]
Can't reproduce.
