### ISSUE TITLE
Bug: the deadline and value of a kanban card are not visible in the card

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5569]
## Description and expectations

The deadline and duration of a kanban card are not visible in the card, the information is visible in edition mode

### How to reproduce

1. Go to a kanban
2. Click on create a card
3. Add a deadline and/or a value
4. Validate. The values are visible on edition mode but not on Kanban view mode

### Version information

- Tracim version: v4.1
- Web browser: Google Chrome
- Device / System: PC

### Screenshots

![Capture d’écran de 2022-04-01 17-36-44](https://user-images.githubusercontent.com/35422692/161296095-501d1f82-addd-4a50-897b-f3c9db5f0185.png)
![Capture d’écran de 2022-04-01 17-36-33](https://user-images.githubusercontent.com/35422692/161296099-2276b60c-fc06-4b83-a5b2-f8e7c15f988e.png)

________________________________________________

## Prerequisites

PR: #5572

**Comment by knodelle** [comment]
Here are a few suggestions for the additional information that will be added on the card, let me know what you think

![Group 7](https://user-images.githubusercontent.com/50776142/161728469-5e4299f1-ea39-48a1-9848-bc3d3976136d.png)

**Comment by agile-marmot** [comment]
Thanks @knodelle i prefer the third but can we imagine the date at the bottom right? and both value and date info on the same line?

**Comment by gbonaspetti** [comment]
I like the third one (last mockup from first line).
I don't know if the background it's just to have a little contrast on github, but I think the white background is better.

**Comment by Relf-Algoo** [comment]
I like the second and fifth one.
Order of preference is : 
5
2
3
1
4

**Comment by Skylsmoi** [comment]
I like the third one (on the first line) ; it's the most simple but it does things well : readability and cleanness.
I would only align everything vertically (title, text, date, extra)

**Comment by Skylsmoi** [comment]
> Thanks @knodelle i prefer the third but can we imagine the date at the bottom right? and both value and date info on the same line?

Problem is, we don't know the length of what you call "value" (which I called "extra" in my comment). It's a free text that can potentially be long

**Comment by knodelle** [comment]
This is what I ended up choosing, with the feedback I got. Let me know what you think

![calendar](https://user-images.githubusercontent.com/50776142/162197514-a9fe7b7d-17aa-454e-a3f2-c6841f86f984.png)

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by knodelle** [comment]
done
