### ISSUE TITLE
Feat: Consider underscore as token separator for elastisearch-based search

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#5574]
## Feature description and goals

Currently the tokenizer used for search does not split token on "_" but does it on "-" this as some consequence when trying to find file like: just_a_boat.txt which will not match with "boat" whereas "just-a-boat.txt" will match.

To make the search a bit easier we decide to consider underscore as token separator too.

## Implemented solution

PR ref: #5576 
Issue ref: #5574 

- better search result by forcing token split on "_" by replacing them by "-" at char filter.

**Comment by lebouquetin** [comment]
@inkhey It would be interesting to explain here why the way to configure token for word spit is ton "convert _ into -" (and not, for example, to define a list of char to be considered as word split token.

Maybe a link to the elastic search documentation would help to understand your implementation, otherwise there are no way to understand why you do so

**Comment by inkhey** [comment]
> @inkhey It would be interesting to explain here why the way to configure token for word spit is ton "convert _ into -" (and not, for example, to define a list of char to be considered as word split token.
> 
> Maybe a link to the elastic search documentation would help to understand your implementation, otherwise there are no way to understand why you do so

i will add a comment in the code

**Comment by inkhey** [comment]
After a test in preproduction, i discovered that i forgot to check for the ingested content case. 

In case, ingested content is detected by Elasticsearch as french, english, portuguese or deutsch, the process use existing language analyzer so don't use the char_filter i do add. After rapid search, it's not straightforward to reintroduce custom language analyzer as we have to convert from elasticsearch syntax to elasticsearch dsl one : see https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-lang-analyzer.html#_reimplementing_language_analyzers for the existing Elasticsearch language analyzer.

**Comment by knodelle** [comment]
done
