### ISSUE TITLE
Bug: Bottom of the advanced edition disappears in full screen

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5575]
## Description and expectations

As a user, I expect to see the bottom of my editor.

### How to reproduce

(systematically occurring)
1. Go to a note
2. Click on Edit
3. Write multiple lines
4. Click on fullscreen mode

### Version information

- Tracim version: v4.1.3
- Web browser: Google Chrome, Firefox
- Device / System: PC

### Linked PR
PR #5582

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by knodelle** [comment]
done
