### ISSUE TITLE
Feat: Add a filter to the notification wall

### ISSUE THREAD

**Issue by Relf-Algoo** [tracim/tracim#5590]
## Feature description and goals

The user should be able to filter the notification on their wall, in order to manage them more easily, especially when the notifications ar too numerous.

**Comment by Quiwy** [comment]
I agree, at least we should be able to filter read vs unread notifications in order to find "old" unread notifications

**Comment by grignards** [comment]
Related to: https://github.com/tracim/tracim/issues/3324, maybe event duplicate?

**Comment by Haskaris** [comment]
Closing since duplicate of #3324
