### ISSUE TITLE
Bug: Tinymce (advanced edition) doesn't work well on small screens

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5593]
## Description and expectations

If you enable advanced editing on a comment and reduce the screen size, the text editor looks like the image below.

![Capture d’écran de 2022-04-12 11-46-13](https://user-images.githubusercontent.com/35422692/162937985-eba59157-8614-43c9-9fb0-af64f61ac143.png)

As a user, I expect to be able to see the text I am writing without having to go full screen.

### Version information

- Tracim version: v4.1
- Web browser: Google Chrome
- Device / System: PC

________________________________________________

## Diagnostic

Tinymce's height is thought for two header lines, when the screen is too small the last element goes to the line below and we find ourselves with 4 lines instead of 2.

### Implemented solution

Have a min-height for edition area, not the container.

### PR 
#5594

**Comment by inkhey** [comment]
tested on branch

**Comment by knodelle** [comment]
done
