### ISSUE TITLE
Bug: breadcrumbs alignment should be changed in RTL

### ISSUE THREAD

**Issue by Relf-Algoo** [tracim/tracim#5603]
## Description and expectations

When the interface is in RTL, the parts of the breadcrumbs are aligned on the right, including the name of each part. Which means that only the last letters of each name are displayed.
The user wants the alignment to stay on the right, but the name of each part of the breadcrumb should be aligned on the left, which means that the first letter of each name is displayed.

![Capture d’écran 2022-04-14 144531 (14⧸04⧸2022, 14 45 58)](https://user-images.githubusercontent.com/50776142/164456205-58d442e6-52f5-48ba-82de-856babf42191.png)

________________________________________________

## PR 
#5613

**Comment by Relf-Algoo** [comment]
Update done.

**Comment by knodelle** [comment]
tested on branch

**Comment by knodelle** [comment]
done
