### ISSUE TITLE
Bug: Public upload will fail if we are logged to the instance and are not member of the space

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#5604]
## Description and expectations

If I'm logged to an instance and I try to upload a file though a public upload link, if I'm not a member of the space from which the upload link has been generated, an error appear and I can't upload the file.

### How to reproduce

1. create a public upload link for a space A
2. log in to another user that is NOT member of the space A
3. load the public upload link generated in 1.
4. try to upload a file
5. an error appear

### Version information

- Tracim version: v4.1.3 build_075
- Web browser: firefox
- Version: latest
- Device / System: ubuntu 20

### Screenshots

________________________________________________

## Diagnostic

The POST to /api/public/guest-upload/:id fail with a http 400 with code 1002 saying "workspace 119 does not exist or not visible for user"

Since the space exists, it means that api tells us we cannot create a file in a space we are not member from.

This happens because, since we are logged in, the session cookie is sent with the request.

Solution would be either frontend make that api call without the credentials or the backend ignores it.

## Implemented solution

Issue ref : #5604
PR ref: #5758

- add a force_anonymous_context to tracimcontext allowing to force current_user to be anonymous.

**Comment by Skylsmoi** [comment]
After discussing with @grignards , the best solution is to make the change in backend.
This endpoint is supposed to be public and it should not require frontend to specifically NOT send the credentials.

Though, not sending credentials is one line to remove in frontend:
in frontend/src/container/GuestUpload.jsx, remove `xhr.withCredentials = true` l199.

The backend change will be a bit more complex. So the frontend fix could be a quick fix if required.

Removing the frontend tag anyway.

**Comment by Haskaris** [comment]
Tested on branch.
