### ISSUE TITLE
Feat: Currently, the kanban feature cannot be easily activated by docker

### ISSUE THREAD

**Issue by Relf-Algoo** [tracim/tracim#5607]
## Feature description and goals
The kanban feature, when needed to be activated, cannot be activated easily via docker. There needs to be a discussion regarding the differents ways to activate apps in Tracim, especially the kanban.
@inkhey already has thought about it and can explain the different evolution.

## Implemented solution

issue ref : #5607 
PR ref: #5618
- add kanban app to default app list in docker images.

**Comment by Relf-Algoo** [comment]
I've assigned people to this issue so that they can discuss it and choose how it needs to be done.

**Comment by inkhey** [comment]
Currently the kanban app is not added by default in tracim. The use case we have is to be easily been able to have tracim with and without kanban.  Currently this need to set the explicit list of all app, which mean it's not possible to say "i want the default app but not the kanban" or "i want the default app and collabora".

A solution may be having 3 parameters:
- a base list with app that don't require specific configuration which are always enabled by default.
- an extra list to add extra app like collabora (which doesn't work without specific configuration).
- an exclusion list allowing to blacklist app previously added.

**Comment by PhilippeAccorsi** [comment]
I think in the first row, we can add kanban in default app list in docker images.

**Comment by knodelle** [comment]
done
