### ISSUE TITLE
Feat: underscore as token separator for elastisearch ingested content search

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#5608]
## Feature description and goals

According to https://github.com/tracim/tracim/issues/5574#issuecomment-1098105079, the underscore is not considered as separator for language analyzer for ingested content. This issue is about fixing this by creating custom language analyzer.

## Implemented solution:

https://github.com/tracim/tracim/pull/5609

- add language analyzer for arabic
- use custom language analyzer with "_" as separator instead of default one.

**Comment by lebouquetin** [comment]
@inkhey I do not understand the strategy behind hard coded language specific stuff. It does not scale

**Comment by lebouquetin** [comment]
Is there a reason to work with hard coded french_yyy, english_yyy vars instead of using lists which would allow to add easily new languages?

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by knodelle** [comment]
done
