### ISSUE TITLE
Bug: Integration fixes from v4.2

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5621]
## Fix list

- [always have breadcrumbs on one line](https://github.com/tracim/tracim/commit/ecefa273d53a08c97af0e62424af37b07bbe019a)
- [fix missing ellipsis on firefox](https://github.com/tracim/tracim/commit/436012f888c3811db6f170088c49e56369b6e8e5)
- [fix latin space name on rtl](https://github.com/tracim/tracim/commit/df46196dfd05a7cc28f607c6b01a4c595b71acf1)
- [better handle text layout on rtl](https://github.com/tracim/tracim/commit/9b016ce32f1d804c5645fa51f49101d9f91802cc)
- [fix Information plural for Arabic translation](https://github.com/tracim/tracim/commit/423b4d5fdcd57bd8f6e3b80eb3e6b00dd5efb158)

**Comment by inkhey** [comment]
Done
