### ISSUE TITLE
Bug: Wrong message during the loading of a list of spaces

### ISSUE THREAD

**Issue by Relf-Algoo** [tracim/tracim#5624]
## Description and expectations

When asked for a list of spaces, there is a message displayed during the loading. This message says "no space" although there are spaces, but they are still loading. This message needs to be changed.
Example : in the user settings.

As a user I want a loading message during loading and a "no space" message only when there is no space.

### How to reproduce

Systematically occurring.
1. Login with an user that is member of multiple spaces
2. Go to Account Settings
3. Click on Spaces

![noSpace](https://user-images.githubusercontent.com/35422692/165923645-4046e625-5c23-4659-9f07-35947f6434d7.gif)

### Version information

- Tracim version: v4.1.3
- Web browser: Google Chrome
- Device / System: PC

## Linked PR
PR #5628

**Comment by knodelle** [comment]
tested on branc

**Comment by gbonaspetti** [comment]
Done
