### ISSUE TITLE
Bug: content creation popups are a bit cut off on a mobile phone

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5625]
## Description and expectations

As a user I want all popups centered. 

### How to reproduce

Systematically occurring on **mobile**

1. Go to Contents
2. Click on Create...
3. Click on Write a note

### Version information

- Tracim version: v4.2
- Device / System: 
    - Redmi Note 8, google chrome
    - Fairphone4, fennec, /e/ os

### Screenshots
![JdHvzOA](https://user-images.githubusercontent.com/35422692/165720651-5886fbcc-c98f-4142-935b-d93815c1b4c6.jpg)
![HzR1onE](https://user-images.githubusercontent.com/35422692/165720657-e0dfc248-f166-4ffa-8c88-d39551d6e37c.jpg)

________________________________________________

## PR

#5881

**Comment by Millefeuille42** [comment]
Done
