### ISSUE TITLE
Feat: change labels in the Account Settings

### ISSUE THREAD

**Issue by Relf-Algoo** [tracim/tracim#5629]
## Feature description and goals

The menu labels in the Account settings should be unified to include "my" at the beginning of each label
![Capture d’écran de 2022-05-02 11-23-23](https://user-images.githubusercontent.com/92590810/166213085-4bb2c427-6e37-41c8-ba66-97644263b4d3.png)

The labels are already different when seen by an administrator. "My account" becomes "Account". Would it be a good idea to add possessive determiners in this screen too ?
For example : Their account, Their spaces, etc.

## PR
#5980

**Comment by PhilippeAccorsi** [comment]
This need to be done for all language (maybe just need to use weblate @gbonaspetti ?)
who can change this if it is validated ? Can I help dev to fix this for example ?

**Comment by gbonaspetti** [comment]
> This need to be done for all language (maybe just need to use weblate @gbonaspetti ?) who can change this if it is validated ? Can I help dev to fix this for example ?

Yes, we update the translation key on the code and the real translations are made on Weblate. Anyone can help with the translation, but we need a dev (or someone who want to touch the code) for change the translation key before.

**Comment by Haskaris** [comment]
Tested on branch.
