### ISSUE TITLE
Bug: wrong place for the password request block in "My account" of Account Settings

### ISSUE THREAD

**Issue by Relf-Algoo** [tracim/tracim#5631]
## Description and expectations

When changing the username or the email address, there is a new block displayed, requesting the password. this bloc is always under the "new email" block, which is not logic. It should either stay just above the "validate" button or move under each block being changed.

### Version information

- Tracim version: 4.2.0
- Web browser: Firefox
- Version:  latest
- Device / System: work laptop

### Screenshots

![image](https://user-images.githubusercontent.com/28917197/169006595-70b5c325-dbe7-4cb1-beac-d0f1b970838d.png)

## Linked PR
PR #5661

**Comment by gbonaspetti** [comment]
Done
