### ISSUE TITLE
Bug: The default login page does not list the arabian language

### ISSUE THREAD

**Issue by Relf-Algoo** [tracim/tracim#5641]
## Description and expectations

The defzult login page displays a frame with a text. In this frame, the languages of tracim are listed. This list does not contain the arabian language and still displays the flags

### How to reproduce

1. Go to…
2. Click on…
3. Scroll down to…

### Version information

- Tracim version: 4.0.2
- Web browser: [e.g. Google Chrome, Firefox, Safari]
- Version: [e.g. 22, latest]
- Device / System: [e.g. PC, iPhone 6]

### Screenshots

________________________________________________

**Comment by Quiwy** [comment]
Not sure this is relevant anymore since a859390f77967c92346b3516b8cd4f888c1b36e7

**Comment by PhilippeAccorsi** [comment]
You're right quiwy :)
This is done since `tracim 4.1.3_build_070` :)
