### ISSUE TITLE
Bug: blank screen when loading a page with someone that has notification

### ISSUE THREAD

**Issue by Haskaris** [tracim/tracim#5642]
## Description and expectations

When I am loading a page that have notifications, I got a blank screen.

Error displayed into the console:
`document.getElementsByClassName(...).forEach is not a function`

### How to reproduce

1. Go to a page with an account that have notification

### Version information

- Tracim version: 4.2.1
- Web browser: Google Chrome/Firefox
- Device / System: Any

________________________________________________

## Diagnostic

As shown in the console, we are doing a `forEach` on an HTMLCollection, however HTMLCollection prototype doesn't have a `forEach` function (see [documentation](https://developer.mozilla.org/fr/docs/Web/API/HTMLCollection)).
Somehow we had this function added by a dependancy (if we look at the prototype of an element returned by `document.getElementsByClassName` in Tracim 4.2.0, we got the `forEach` function)

The solution is simply to remove this `forEach` and loop through it with a basic `for` loop.

## Linked PR
PR #5643

**Comment by knodelle** [comment]
tested on branch

**Comment by Haskaris** [comment]
Done.
