### ISSUE TITLE
Problem with the view of WorkspaceList

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#565]
At present:

When you have multiple workspace(for exemple 40), you can go down to seen one of them (exemple: number 30). When you choose to see a file, you click on file name, the page is reloaded to show you the page of the file.
In the same time, the left bar is reloaded and you see again the begining of the list. So you need to scroll down to show again workspace number 30.

Expected:

When you are in one workspace, its necessary to show all the time this workspace in left bar.

**Comment by PhilippeAccorsi** [comment]
@inkhey this bug is it still present in the last Tracim version ?

**Comment by inkhey** [comment]
i don't remember this well but as i don't see any reloading in the last Tracim version, i don't success to reproduce the issue, so i suggest to close it.

**Comment by PhilippeAccorsi** [comment]
Ok. Thanks. 
I close this issue.
