### ISSUE TITLE
Bug: 22nd sprint integration fixes

### ISSUE THREAD

**Issue by knodelle** [tracim/tracim#5653]
fix(frontend): add simple search loader - [78d9c60](https://github.com/tracim/tracim/commit/78d9c600137ba74eba7c0e12d72e09227a0d36da)

fix(frontend): fix notification by mail button - [9c69e21](https://github.com/tracim/tracim/commit/9c69e21a3af2ad5e462ec0ff1318f1121da7881d)

fix(frontend): blank page - [cfaa908](https://github.com/tracim/tracim/commit/cfaa908a48a7f09bda08ec03366ef84956f474f2)

**Comment by gbonaspetti** [comment]
Done
