### ISSUE TITLE
Feat: Reduce the weight of notifications

### ISSUE THREAD

**Issue by Haskaris** [tracim/tracim#5655]
## Feature description and goals

Currently, for every notifications, we download:
- [x] The full content (`raw-content` included). 

In order to optimize performances (and to anticipate the mobile version) we might want to not download everything.

The first step would be to not download the `raw-content` of the content.

Be careful after removing the `raw-content` we might use this data to calculate the preview in recent activities.

Issue from audit https://algoo.tracim.fr/ui/workspaces/165/contents/html-document/64275

## Linked PR 
https://github.com/tracim/tracim/pull/5660

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by gbonaspetti** [comment]
Done
