### ISSUE TITLE
Solve "504 Gateway Time-out" with nginx proxy on large file upload

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#567]
When tracim running behind nginx (like in tracim official docker), error "504 Gateway Time-out" can appear when upload a big file. This error happen because upload time is to long for default config of nginx.

Current nginx config is:

```
    [...]
    location / {
        uwsgi_pass  unix:/var/run/uwsgi/app/tracim/socket;
        include uwsgi_params;
        uwsgi_param  SCRIPT_NAME        '';
    }
}
```

It must be replaced by (ex for 12 hours maximum request):

```
    [...]
    location / {
        client_body_timeout 43200s;
        uwsgi_read_timeout 43200s;
        uwsgi_pass  unix:/var/run/uwsgi/app/tracim/socket;
        include uwsgi_params;
        uwsgi_param  SCRIPT_NAME        '';
    }
}
```

*Note*: When make tests on local, an other error can happen: 

> OSError: timeout during read(65536) on wsgi.input

This error happen when client stop communicate whith server. It can happen when client is overloaded. I experienced that uploading local to local and overuse my local hard drive.

**Warning**: An other error can happen: When upload big files on tracim logically use disk spaces. When use tracim in docker, be sure to use volume on partition with enough disk space.

**Comment by buxx** [comment]
Note: Think to check apache2 config about this problematic.

**Comment by Quiwy** [comment]
@PhilippeAccorsi : have you heard about the same kind of problems with containers in production?

**Comment by PhilippeAccorsi** [comment]
No.
But this kind of problem need to be addressed manually. The limit depend of what we want to do on Tracim instance.
Exemple, if you want to sent file bigger than 5-10-100Go, you need maybe to adapt proxy configuration.
 
If I rememeber correctly, the actual default value is 2Gb per file.
