### ISSUE TITLE
Bug: it's possible to get loader without font loaded

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#5676]
## Description and expectations

In some case (low connection) we can get weird result on loader because font is missing.

### Version information

- Tracim version: build 079
- Web browser: firefox
- Version: 100.0.2
- Device / System: ubuntu 18.04

### Screenshots

![LkYpBsC](https://user-images.githubusercontent.com/7851652/170290699-f6335b36-428b-4ac3-8e47-98a912ac4c62.png)

________________________________________________

## Related PR
https://github.com/tracim/tracim/pull/6121

**Comment by Skylsmoi** [comment]
reopened because issue isn't validated yet, it's now in "To close" on board 4.7.0
