### ISSUE TITLE
Bug: Wrong link on notification with mentions

### ISSUE THREAD

**Issue by Relf-Algoo** [tracim/tracim#5679]
## Description and expectations

Problem in the notification wall, with notification that link to a mention (not only `@all`). The link is https://algoo.tracim.fr/ui/contents/:idcts instead of a link to the content. then, when clicking on the link, there is an error message about unknown content. And then the recent activities are displayed.
When the page is refreshed, in one way or another, the problem disappears.

### Version information

- Tracim version: v4.2.2 build_079
- Web browser: firefox
- Version: latest
- Device / System: algoo laptop

________________________________________________

## Diagnostic

We are still using the raw content from some TLMs. Fixing this we fix the undefined when modifying a document.

## PR

#5680 
https://github.com/tracim/tracim/pull/5682

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by gbonaspetti** [comment]
Done
