### ISSUE TITLE
Bug - Regression: As a new user, I don't have set my username but I never see the popup asking for it

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#5685]
## Description and expectations

As a **new** user, I want to be notified that I need to set my username.
There should be a popup that asks for it when I login to Tracim.
But I never see that popup.

### How to reproduce

1. User 1 (admin) create a new user User 2
2. User 1 add User 2 to a space
3. Login to User 2
4. User 2 is on the recent activities page and is not prompted by the popup asking for a username

### Version information

- Tracim version: v4.2.2 build_080
- Web browser: any
- Version: latest
- Device / System: any

### Screenshots

________________________________________________

## Diagnostic

The issue comes from the fact that the popup to set a username is displayed by the Home.jsx component (frontend/). But, if the user already is member of a space, the component Home.jsx is never displayed, we show the recent activities page instead.

The popup should not only be in the component Home.jsx. I would advise to put it higher in the architecture.

## Prerequisites

None

## Linked PR
PR #5737

**Comment by PhilippeAccorsi** [comment]
@gbonaspetti do you know if fix can be done in this sprint?

**Comment by gbonaspetti** [comment]
> @gbonaspetti do you know if fix can be done in this sprint?

This will not be solved in the current sprint (which ends on Thursday the 9th) and on the 10th I will know if it will be in the next sprint.

**Comment by gbonaspetti** [comment]
Tested on branch (see https://github.com/tracim/tracim/pull/5737#issuecomment-1169790126 )

**Comment by gbonaspetti** [comment]
Done
