### ISSUE TITLE
Orthographe et image non affichée

### ISSUE THREAD

**Issue by d-stephane** [tracim/tracim#57]
- Petite inversion de lettre dans la traduction française :
_"Vous consultez une ancienne version de al page courante."_
Ce texte est affiché quand on visualise une version précédente d'une page

- Quand on est sur un fichier, le bouton de téléchargement montre qu'il manque une image. Vu avec Firefox. L'image est pourtant bien présente dans le répertoire **tracim/tracim/public/assets/img**
![selection_006](https://cloud.githubusercontent.com/assets/10093837/16335452/ff6e0dca-3a06-11e6-96cf-2142619cfb1f.png)

Voilà, c'est pas grand chose mais c'est signalé :-)

**Comment by tracim** [comment]
Egalement un "double quote" traîne à la fin de l'affichage de l'URL du calendrier CalDav. Il faut nettoyer ce texte dans la foulée
