### ISSUE TITLE
Bug: In the parameter application of a space the button "mark template" appears

### ISSUE THREAD

**Issue by Haskaris** [tracim/tracim#5705]
## Description and expectations

The button `mark template` appears when it should not. For example it appears in the parameter application of a space.

### How to reproduce

1. Go to parameter application, click on the `...`

### Version information

- Tracim version: 4.2.2_082
- Web browser: Firefox

## PR
https://github.com/tracim/tracim/pull/5753

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by gbonaspetti** [comment]
Done
