### ISSUE TITLE
Feat: [todo] Add an progress indication on To Dos tab

### ISSUE THREAD

**Issue by Haskaris** [tracim/tracim#5706]
## Feature description and goals

With the addition of To Dos, we should have more visibilities on To Dos.
![Screenshot from 2022-06-10 10-42-18](https://user-images.githubusercontent.com/28917197/173027283-7f73bb94-314f-480c-b6fb-469dfcee78a8.png)

## Prerequisites

#5698

## Linked PR
PR #5759

**Comment by wwalden** [comment]
**implemented solution:** _progress bar_ and _number status_ as in screenshot above, for Notes, Files and Kanbans

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by gbonaspetti** [comment]
Done
