### ISSUE TITLE
📝 Documentation: upgrade to 4.3.0

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#5711]
## Configuration update (development.ini)

- The variable `TRACIM_APP__ENABLED` has a new app by default (`contents/todo`). If you have changed this variable and you would like to add the functionality, you will need to add it to your list.

## Re-index advanced search

Advanced Search (Elasticsearch) has been improved. If you use it, You need to you will need to rebuild the index using tracimcli command lines. 

The process for the official docker image is this one:

```bash
docker exec -it -u www-data -w /etc/tracim {CONTAINER ID} tracimcli
search index-drop -d
search index-create -d
search index-populate -d
```

If you use Tracim in another context, the process is similar, simply run `tracimcli` from:
- the directory where `development.ini` is placed.
- make sure you are in the correct python environment.
- run theses command lines:

```bash
tracimcli
search index-drop -d
search index-create -d
search index-populate -d
```

**Comment by PhilippeAccorsi** [comment]
Old release. We can close.
