### ISSUE TITLE
Bug: Add member button / user list of space not loading

### ISSUE THREAD

**Issue by Quiwy** [tracim/tracim#5722]
## Description and expectations

When adding a new user to a space without a role, we have a message telling us we need to add a role. Then the space user list has a loader which does nothing without reloading the page.

### How to reproduce

1. Go to a space
2. Click on "Add user"
3. Select a user
4. Don't select a role
5. Validate
6.  You have the warning popup
7.  User list is not loading anymore

### Version information

- Tracim version: v4.2.2 build_082
- Web browser: Firefox
- Version: 103
- Device / System: PC

### Screenshots
![add_user](https://user-images.githubusercontent.com/20048264/174541504-667fa76d-4155-4132-ac39-17fb33c757d4.gif)

**Comment by gbonaspetti** [comment]
@Quiwy do you still have this bug or we can close the issue?

**Comment by Quiwy** [comment]
We can close the issue, I can't reproduce on build 89 :smile:
