### ISSUE TITLE
Update docker processus to copy branding files

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#5723]
## Feature description and goals

This ticket is about improving https://github.com/tracim/tracim/issues/1354 :
- [x] find a solution to branding check: see https://github.com/tracim/tracim/pull/5710#discussion_r898888484 , a good solution seems to make the feature optional, this is a bit more work but avoid trouble for migration. Another solution is finding a generic way to fallback branding.

## Prerequisites

https://github.com/tracim/tracim/issues/1354

## Implemented solution

PR ref: https://github.com/tracim/tracim/pull/5796
Issue ref: https://github.com/tracim/tracim/issues/5723

- Add fallback for all branding file in setup_default_backend script and dockerfile entrypoint.

----------------

Deprecated implemented solution:
> 
> PR ref: https://github.com/tracim/tracim/pull/5736
> Issue ref: https://github.com/tracim/tracim/issues/5723
> 
> - make export to pdf feature optional (disabled by default)

**Comment by lebouquetin** [comment]
@Haskaris imm'm not sûre to understand thé goal of this issue.

You implémentés something in ordre to make thé feature optionnal?

**Comment by lebouquetin** [comment]
If si, what is the use case?

**Comment by lebouquetin** [comment]
I see this:

> This make 2 new files from branding mandatory for all installations: https://github.com/tracim/tracim/issues/5711 I don't really like the fact we have such breaking change forcing sys-administrator to do manual fix but i don't see better solution for now, this feature doesn't make much sense to be optional and having tracim in a partially working state is not a good solution.
> 
> @PhilippeAccorsi What do you think about this kind of breaking change ?

And The talk we had was about make feature work "out of the box". Why did you not implement something that copy template export files when they do not exist instead of creating a useless activable feature? @inkhey ?

**Comment by Haskaris** [comment]
Indeed, the goal of this issue is to make this feature optionnal.
The user case would be:

> As an administrator user, I would like to disable the `Download as PDF` since I don't want my users to get lost/confused with the convert HTML-Document to PDF option.

Or

> As an administrator user, I would like to enable the `Download as PDF` because I use the HTML-Document for a lot of things such as contracts and I need them on paper.

**Comment by lebouquetin** [comment]
@Haskaris where did you see this use case? I did not see it in the issues.

The use case I spoke about to @inkhey was: "As an administrator, I want to be able to upgrade my instance and tyo benefit from this new feature without to have configuration requested" - this is not in a ticket, it's what I told to @inkhey "out loud" (de vive voix)

**Comment by lebouquetin** [comment]
related question: is there some behavior in order to setup default files for exportation in case of migration? Can I upgrade an instance and benefit from the feature without to copy/paste files "by hand"? (this is what was expected, actually)

**Comment by Haskaris** [comment]
Indeed there is no use case written in this issue nor the merge request. What I answered was a use case of what I thought after the development.

I don't think there is such a behaviour right now (but I might be wrong)

**Comment by inkhey** [comment]
> I see this:
> 
> > This make 2 new files from branding mandatory for all installations: #5711 I don't really like the fact we have such breaking change forcing sys-administrator to do manual fix but i don't see better solution for now, this feature doesn't make much sense to be optional and having tracim in a partially working state is not a good solution.
> > @PhilippeAccorsi What do you think about this kind of breaking change ?
> 
> The talk we had was about make feature work "out of the box". Why didn't you implement something that copy template export files when they do not exist instead of creating a useless activation/deacivation feature? @inkhey ?

The problem is that there are some unclear point about solving the original ticket and after discussion with the team, it's seems easier for a first step to make the feature optional and disabled by default. 

This is not "useless" has this feature ensure that the feature is correctly working (the activation feature is related to file existence check), so it's seems to me less ugly than having a "broken" feature without manual change.

**Comment by Haskaris** [comment]
Tested on branch.
