### ISSUE TITLE
Feat: Be able to create several tasks to do at once

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5729]
## Feature description and goals

As a user I would like to be able to create several tasks to do at once. Each task will still be associated to one person.

## Linked PR
PR #5750

**Comment by wwalden** [comment]
tested on branch

**Comment by Haskaris** [comment]
Update after discussion:
The current multiple creation have to be the mechanism for the unique creation
The multiple creation should be like an import. It should have a text area where one line is a todo

**Comment by wwalden** [comment]
tested on branch

**Comment by gbonaspetti** [comment]
Done
