### ISSUE TITLE
add user and add member: show profile and role description directly in same screen

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#573]
Dans les nouvelles maquettes, le choix du rôle est une select ; donc l'utilisateur est obligé de cliquer dessus pour savoir quel rôle donner à l'utilisateur.

Il faudrait qu'il puisse de base savoir quel rôle attribuer, comme sur tracim actuel (liste de radiobutton).

Avantages en terme d'ergonomie :

- on a la liste des différents rôles possible sous les yeux
- on peut en avoir un choisi par défaut
- si besoin de mettre une aide, on peut l'associer immédiatement

**Comment by lebouquetin** [comment]
@PhilippeAccorsi à confirmer que c'est bien déjà le cas comme on vient de le voir avec @AlexiCauvin

**Comment by PhilippeAccorsi** [comment]
@lebouquetin C'est fonctionnel. Il manque juste une bulle par exemple, avec le détaille du rôle si on laisse la souris au dessus du texte. Ou alors un bouton qui donne accès au détaille des rôle.

**Comment by AlexiCauvin** [comment]
Is it important for v2.0 output to display help on the function of the proposed roles ?

this function on tracim v1 : 
![capture3](https://user-images.githubusercontent.com/16293214/43525220-7b18baf4-95a1-11e8-8820-1ef37e9135c9.PNG)

**Comment by PhilippeAccorsi** [comment]
write explicit text of user role on right of role (text in grey)

**Comment by gbonaspetti** [comment]
One idea of how to do that in the dashboard without *visual pollution* is with tooltips.
![ToolTips](https://user-images.githubusercontent.com/35422692/58407484-28275380-806c-11e9-942c-e3a0fa6981c1.png)

**Comment by lebouquetin** [comment]
another way to do this is to add a question mark which will show the explanation for each role

**Comment by PhilippeAccorsi** [comment]
After some discussion with @lebouquetin :

- add description about profil and role after each title (in grey like we have about mail description)

**Comment by Skylsmoi** [comment]
What are the theses descriptions ?
It might be necessary to be quite short to avoid breaking the design

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi You can find information directly in tracim v1 repo `/home/algoo/repo/tracim_v1-old_software/tracim/tracim/i18n/fr/LC_MESSAGES/tracim.po`

**Comment by lebouquetin** [comment]
@Skylsmoi the first thing is to be clear ; then we will consider not breaking the design.

My suggestion is to have a line (or two?) of description below the role, in grey like suggested by @PhilippeAccorsi

**Comment by PhilippeAccorsi** [comment]
This is what we have in tracim_v1. We need to make description smaller in v2 (but idea of profile and role is here):

Roles:
- Workspace Manager | Same as content manager + workspace management rights: edit workspace, invite users, revoke them.
- Content Manager | Same as contributor + content management rights: move content, folders management, delete archive operations.
- Contributor | Same as reader + contribution rights: edit, comments, status update.
- Reader | This role gives read-only access to workspace resources.

Profile:
- This user is an administrator 
- This user can create workspaces 
- This user a standard user.

@metzgegu when you are ready to add text we can try together to find the maximum words we can add for description

**Comment by PhilippeAccorsi** [comment]
I think we can use text like this:
role:
- Sharedspace Manager: Content manager + add member and edit shared space
- Content Manager: contributor + create folder and manage content
- Contributor:  reader + create/modify content
- Reader: Just read content
profile:
- Administrator: Create user, create shared space, administration of instance
- Trusted user: Create shared space, add member in shared space
- User: Access to shared space where user is member

(cf https://github.com/tracim/tracim/blob/develop/backend/doc/roles.md)

**Comment by metzgegu** [comment]
### Here is a first preview how it could look

Profile :

![Profile](https://user-images.githubusercontent.com/31687635/61941533-fbbe8380-af97-11e9-8aaa-719c3b11c482.png)

Role : 

![Role](https://user-images.githubusercontent.com/31687635/61941545-00833780-af98-11e9-874a-f2504d035455.png)

**Comment by PhilippeAccorsi** [comment]
Can you align all icon and just leave check box alone in left?

**Comment by metzgegu** [comment]
Yes @PhilippeAccorsi 

Profile : 

![Profile](https://user-images.githubusercontent.com/31687635/62056171-5e748100-b21d-11e9-89c2-6765b95acd57.png)

Role : 

![Role](https://user-images.githubusercontent.com/31687635/62056189-67fde900-b21d-11e9-9004-769f58773606.png)

**Comment by lebouquetin** [comment]
Do not put bulb icon + align text like below:

![image](https://user-images.githubusercontent.com/907161/62059897-6a177600-b224-11e9-92da-d313e52ffcb4.png)

**Comment by metzgegu** [comment]
I created a Draft PR with this design : 

![exemple](https://user-images.githubusercontent.com/31687635/62363560-e6110700-b51f-11e9-96e8-9feb6347d7e0.png)

We need to define final descriptions texts with their translations.

**Comment by PhilippeAccorsi** [comment]
> I think we can use text like this:
> role:
> 
>     * Sharedspace Manager: Content manager + add member and edit shared space
> 
>     * Content Manager: contributor + create folder and manage content
> 
>     * Contributor:  reader + create/modify content
> 
>     * Reader: Just read content
>       profile:
> 
>     * Administrator: Create user, create shared space, administration of instance
> 
>     * Trusted user: Create shared space, add member in shared space
> 
>     * User: Access to shared space where user is member
> 
> 
> (cf https://github.com/tracim/tracim/blob/develop/backend/doc/roles.md)

@lebouquetin @Skylsmoi is it ok for you? Maybe we need to add plural on some words

**Comment by Skylsmoi** [comment]
@PhilippeAccorsi @metzgegu I have edited a bit the roles and profile description

**Comment by PhilippeAccorsi** [comment]
@metzgegu I think we need to add plural for each description:

Role:
~~~
- Content manager + add members and edit shared spaces <=> Gestionnaire de contenu + ajouter des membres et modifiers les espaces partagés
- Contributor + create folders and manage contents <=> Contributeur + crééer des dossiers et gérer les contenus
- Reader + create/modify content <=> Lecteur + créer/modifier les contenus
- Read contents <=> Lire les contenus
~~~

Profile:
~~~
- Create users, create shared spaces, administration of instance <=> Créer des utilisateurs, créer des espaces partagés, administration d'instance
- Create shared spaces, add members in shared spaces <=> Créer des espaces partagés, ajouter des membres dans les espaces partagés
- Access to shared spaces where user is member <=> Accès aux espaces partagés où l'utilisateur est membre
~~~

For profile: what do you think about adding profil + description like we have with role? ex: "user + tatata", "Trusted user + tatata".

**Comment by metzgegu** [comment]
Yes I agree with adding the profile + description in profiles descriptions like roles descriptions, and I will also add plural :ok_hand:

**Comment by PhilippeAccorsi** [comment]
Verified.
