### ISSUE TITLE
Bug: content generated from template have always strict allowed_content properties

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#5731]
## Description and expectations

When copying content from template, the properties fields has strict allowed_content set in all cases.
This can make sense if a strict value as been set but when it's not the case, this will cause compatibility issue between new and old contents

The issue has been reproduced with copied content from template from a database with a codebase before the add of the todo feature, adding later the todo feature, make these copied content to be unable to have todo (todo unallowed).

## Implemented solution
- convert properties as json column
- refactor properties code to be explicit between stored value and read-only value.
- add migration script to remove all non-folder content with content restriction to avoid "broken content".

issue ref: #5731 
pr ref: #5732

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by gbonaspetti** [comment]
Done
