### ISSUE TITLE
Bug: Video size when playing video

### ISSUE THREAD

**Issue by Quiwy** [tracim/tracim#5747]
## Description and expectations

When playing a video which is too large for the screen, without putting it in fullscreen, we can not have control and see everything in the video .

### How to reproduce

1. Go to https://algoo.tracim.fr/ui/workspaces/163/contents/file/70892
2. Click on "Play video"

### Version information

- Tracim version:  v4.2.2 build_082
- Web browser: Firefox

### Screenshots
![pain](https://user-images.githubusercontent.com/20048264/176371794-6e16a447-4be4-420a-994c-9b77d632be47.gif)

### PR
#5851

**Comment by lebouquetin** [comment]
@Skylsmoi is this an issue you already knows? Do you know how to fix / what is the origin?

**Comment by Skylsmoi** [comment]
It is a known issue. Though I couldn't find an existing issue through a quick look.
The origin is that we implemented the video player for a very specific use case and we haven't took the time to implement it for a general use.
As far as I remember, we never set ratio, width and/or height when playing a video. So the player take the original width and height. So if the video is in high definition, the issue happen.

I'm adding the workaround to the issue's description

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by Millefeuille42** [comment]
Done
