### ISSUE TITLE
Bug: Kanban card creation not fine depending on screen size

### ISSUE THREAD

**Issue by Quiwy** [tracim/tracim#5748]
## Description and expectations

On my laptop, it's not possible for me to have all fields of kanban creation card without have a <= 80% zoom

### How to reproduce
1. Create a kanban card

### Version information
- Tracim version: v4.2.2 build_084
- Web browser: Firefox
- Screen : 1920x1080 16:9

### Screenshots
![kanban_create_card](https://user-images.githubusercontent.com/20048264/176377515-6b84ab24-a3ec-4516-8354-97526e408853.gif)

### Workaround
Press enter to create card

## PR
#5945

**Comment by Relf-Algoo** [comment]
The same problem seems to happen during edition of cards, not only creation. See discussion on https://algoo.tracim.fr/ui/workspaces/296/contents/thread/80014

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by Millefeuille42** [comment]
Done
