### ISSUE TITLE
full size screen on tracim v2 apps

### ISSUE THREAD

**Issue by AlexiCauvin** [tracim/tracim#576]
TODO : - add a full size screen buttons
             -  manage the content width according to the app

**Comment by lebouquetin** [comment]
Proposer un bouton "fullscreen" pour le wysywig de saisie.

**Comment by AlexiCauvin** [comment]
A fix is push on the branch fix-tiny, but we need to verify the method used before the merge

**Comment by lebouquetin** [comment]
What is the status if this issue? @AlexiCauvin @PhilippeAccorsi

**Comment by AlexiCauvin** [comment]
fix is on an other branch. I need to know with @Skylsmoi if the fix is good

**Comment by PhilippeAccorsi** [comment]
Verified.
