### ISSUE TITLE
Bug: escape from tag sugestion

### ISSUE THREAD

**Issue by Quiwy** [tracim/tracim#5760]
## Description and expectations

When adding a tag to a content, it's not possible to click outside of suggestion box to disable suggestion. This is a problem because we can't click on "Add" button to add the tag.

### How to reproduce

1. Go to a tag tab of any content
2. Add a tag
3. If another present tag contains the string, you can not click outside to not show suggestions anymore

### Version information

- Tracim version: v4.2.2 build_082
- Web browser: Firefox 104.0a1

### Screenshots
![image](https://user-images.githubusercontent.com/20048264/177098440-e6e40809-eb03-42f4-b784-20caf8be57cb.png)

### Workaround 
press escape key on keyboard

##  PR
#5929

**Comment by Millefeuille42** [comment]
Done
