### ISSUE TITLE
Bug: 26nd sprint integration fixes

### ISSUE THREAD

**Issue by Haskaris** [tracim/tracim#5765]
fix(frontend): username popup fix - 30936e58e676842c8e567c0ae005f3c42e600222
fix(frontend): flash message unknown content appears when CUD ToDo - 570b7432ab6be7f1ce30f4423c4df3f66b63edbb
fix(frontend): several fix concerning todos - 38a66f40a22a0719f45bed0531cc1706220bd896
feat(frontend): to do progress bar on my tasks page - 296211b356b43ba73f50f6a5b69867ef423df534
feat(frontend): quick fix - 1b717849ea0c1db4694b235fede6bffb04792f7a
fix(frontend): correction on todo notifications - 866011a1c104a666fcdff062ba83e4bfa1eaf3e7

**Comment by gbonaspetti** [comment]
Done
