### ISSUE TITLE
Feat: Be able to disable by instance to dos on frontend 

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5770]
## Feature description and goals

At this point, the backend allows you to disable the to do functionality in the configuration of the instance, but the frontend does not manage this case. As the instance manager, I would like to be able to disable the functionality in the Tracim interface.

## Prerequisites

None

## PR

https://github.com/tracim/tracim/pull/5774

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by gbonaspetti** [comment]
Done
