### ISSUE TITLE
Bug: templates from files doesn't work and give white screen/white application

### ISSUE THREAD

**Issue by Haskaris** [tracim/tracim#5775]
## Description and expectations
When I want to create a file based on a collabora template, I get a white screen/white application.

### How to reproduce

1. Create a collaborative file
2. Mark this file as a template
3. Create a file with this template

### Version information

- Tracim version: 4.2.2_build_085

## Linked PR
PR  #5776

**Comment by gbonaspetti** [comment]
Done
