### ISSUE TITLE
Feat: Add Spanish interface 

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5777]
## Feature description and goals

Since Spanish language has more than 50% of translations on Weblate. 
As a user that speaks Spanish, I would like to have the Spanish interface if there is the translations.

## Prerequisites

None

## PR
https://github.com/tracim/tracim/pull/5780

**Comment by Haskaris** [comment]
Tested on branch.
There is still a bug about mentioning everyone in Spanish. However we have to refactor the mention system so this is acceptable.

**Comment by gbonaspetti** [comment]
Done
