### ISSUE TITLE
Bug: contributor cannot check/uncheck/delete a todo that he has create

### ISSUE THREAD

**Issue by Haskaris** [tracim/tracim#5781]
## Description and expectations

I'm contributor in a space. I create a to do assigned to X (not me), I can't check/uncheck/delete his to do.

After some searches, a reader assignee cannot check/uncheck his todo

### How to reproduce

1. Create a todo for a contributor
2. Ask the contributor to check the todo

### Version information

- Tracim version: 4.2.2_build_085

## Linked PR 
#5782

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by gbonaspetti** [comment]
Done
