### ISSUE TITLE
Bug: wrong text when creating N tasks on one content

### ISSUE THREAD

**Issue by Haskaris** [tracim/tracim#5785]
## Description and expectations

When a user U1 creates 6 tasks, other users will see a notification in the notification well: `U1 created a task on 6 contents`.
We should excpect the notification to see `U1 created 6 tasks on <content label>`

### How to reproduce

1. Create several tasks (3+) on a content
2. See notifications on the notification wall 

### Version information

- Tracim version: 4.2.2_build_085

## Linked PR
PR #5786

**Comment by gbonaspetti** [comment]
Done
