### ISSUE TITLE
Bug: the todo page creation is displayed even if there is some todos

### ISSUE THREAD

**Issue by Haskaris** [tracim/tracim#5790]
## Description and expectations

The todo page creation should be displayed only if there is no todo. However in the current state of the application, if the todos aren't loaded, it displays the todo page even if after the loading, there is some todos.

### How to reproduce

1. Create some todos
2. Change space
3. Go see your todos quickly (you have to do it a bit fast so the todos doesn't have the time to load)

### Version information

- Tracim version: 4.2.2_build_085

## Linked PR
PR #5791

**Comment by gbonaspetti** [comment]
Tested on branch

**Comment by gbonaspetti** [comment]
Done
