### ISSUE TITLE
Feat: Allow right-click or mouse wheel-click on Edit button

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5800]
## Feature description and goals

As a user I would like to be able to open the edition of an Office document in another tab using the right click or mouse wheel click. This would facilitate my day-to-day use as I could continue my navigation from where I was and edit the document in parallel.

## Prerequisites

None

## PR and implemented solution
**PR**: https://github.com/tracim/tracim/pull/5839

Since the only way to be able to open in another tab is using a Link, a workaround was made to have this feature using a link that has the same style that a button.

**Comment by wwalden** [comment]
tested on branch

**Comment by PhilippeAccorsi** [comment]
Can we add this fix also in content list with this button?

![button_in_content_list](https://user-images.githubusercontent.com/25848257/185349707-7f381464-c96a-4827-a0db-64602ddab1d5.gif)
