### ISSUE TITLE
Bug: No more padding in the favorites list

### ISSUE THREAD

**Issue by Relf-Algoo** [tracim/tracim#5802]
## Description and expectations

When there are too many favourites in the list, the padding disappears. See topic https://algoo.tracim.fr/ui/workspaces/49/contents/thread/73848 for more informations

### How to reproduce

1. Go to…
2. Click on…
3. Scroll down to…

### Version information

- Tracim version: 4.3.0, our tracim
- Web browser: Firefox 
- Version: 102
- Device / System: work laptop

### Screenshots

________________________________________________

## PR
#5984

**Comment by Millefeuille42** [comment]
Done
