### ISSUE TITLE
Bug: content of folder is not displayed when clicking on the folder.

### ISSUE THREAD

**Issue by Relf-Algoo** [tracim/tracim#5803]
## Description and expectations

When opening folders in the content of a space, the contents of this folders are not displayed or displayed at the bottom of the list of folders (if the list is short).
This has been reproduced on some web browser, but not all.
See discussion https://algoo.tracim.fr/ui/workspaces/296/contents/thread/74022

### How to reproduce

1. Go to the content of a space
2. Click on the name of a folder
3. Scroll down or not

### Version information

- Tracim version: 4.3.0
- Web browser: Firefox ESR
- Version: latest, aka 91.1.0
- Device / System: Debian

________________________________________________

## PR
https://github.com/tracim/tracim/pull/5804

## Diagnostic

fit-content is not supported by Fireffox ESR, so we added the -moz-fit-content for this case

**Comment by wwalden** [comment]
tested on branch (Ubuntu 20.04 + Firefox & Chrome)

**Comment by gbonaspetti** [comment]
Done
