### ISSUE TITLE
Feat: Borderless design

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5818]
## Feature description and goals

As a user, I consider a borderless design to be modern and clean.

## Prerequisites

None

## PR

https://github.com/tracim/tracim/pull/5963

Some colors had to be changed to ensure contrast and to help with this change, an update was made to the nomenclature, making it easier to understand.

**Comment by Millefeuille42** [comment]
Tested on branch

**Comment by Millefeuille42** [comment]
Done
