### ISSUE TITLE
Bug: when receiving a call, the sound is here but no popup to accept or reject the call

### ISSUE THREAD

**Issue by Relf-Algoo** [tracim/tracim#5821]
## Description and expectations

Sometimes, when a call is made between tracim users, the audio ring is heard, but there is no popup to accept or reject the call. The only way to stop the ring is to close all tracim tabs in the browser. Refreshing tabs can help by displaying the popup, but it doesn't always work.
This has been detected to happen when the user's session is locked. Not reproduced yett, but this can be explored.

### How to reproduce

1. Go to…
2. Click on…
3. Scroll down to…

### Version information

- Tracim version: v4.3.1 build_087
- Web browser: Firefox
- Version: 103
- Device / System: [e.g. PC, iPhone 6]

### Screenshots

________________________________________________

**Comment by Skylsmoi** [comment]
fixed in https://github.com/tracim/tracim/pull/6529
