### ISSUE TITLE
Bug: better handle collabora, kanban and custom button with new sidebar

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5822]
## Description and expectations

After sidebar update, we found the following bugs:

- [x] The app collabora doesn't take advantage of all the available height
- [x] The horizontal scroll on kanban disappears on some workstations (firefox 103 ubuntu 20) - when you have a lot of cards, in fact you can't even scroll vertically, so access the horizontal scroll at the bottom
- [x] The kanban full screen is broken, the first column is partially hidden by the sidebar
- [x] Add custom button in the sidebar

### Version information

- Tracim version: build_087
- Web browser: Google Chrome, Firefox
- Device / System: PC

________________________________________________

## PR

https://github.com/tracim/tracim/pull/5823

**Comment by wwalden** [comment]
tested on branch, except for the custom button add

**Comment by Millefeuille42** [comment]
Done
