### ISSUE TITLE
Feat: Improve spaces zone on sidebar

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5836]
## Feature description and goals

- [x] Put creation and join space button in the title "spaces"
- [x] Click on spaces icon when sidebar is closed should always open spaces list
- [x] Add a message when user is not a member of any space and better handle icon and action on click
- [x] Better align and add a different background for titles
- [x] Use primary color as background for current item
- [x] Add an icon to highlight confidential spaces

## Prerequisites

None

## PR
https://github.com/tracim/tracim/pull/5838

**Comment by wwalden** [comment]
tested on branch

**Comment by Millefeuille42** [comment]
Done
