### ISSUE TITLE
Feat: Show discussion on activity feed

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5843]
## Feature description and goals

- [x] If there is comments on content timeline, display a show discussion button
- [x] When clicking on this button, the comments are displayed (like on the news page) et the button label become "hide discussion" (et vice-versa)
- [x] On the bottom of the discussion, we will have a "Participate" button that redirects to the app
- [x] If the content has no comment, add a "Participate" button that opens app
- [x] Do not duplicate first comment for theads

~- [ ] When the app is opened, add a focus on comment zone~

   - The autofocus is not working. Since the other developments have a bigger priority, this point was added on integration document

## Prerequisites

None

##  PR
https://github.com/tracim/tracim/pull/5848

**Comment by wwalden** [comment]
tested on branch

**Comment by Millefeuille42** [comment]
Done
