### ISSUE TITLE
Bug: API documentation for todo must indicate to pass "Null" value to create a todo assigned to nobody

### ISSUE THREAD

**Issue by Quiwy** [tracim/tracim#5844]
## Description and expectations

For now, the API documentations doen't explain how to create a todo assigned to nobody. I thought at first I only had to remove "assignee_id" parameter.

After talking with @Haskaris , the solution is to put a "null" value, it's not really explicit.

 
![image](https://user-images.githubusercontent.com/20048264/185639939-f104a443-2759-48c0-bc26-20a4fd6e0a84.png)

# Expected
An explanation on how to assign nobody when creating a todo

**Comment by Millefeuille42** [comment]
Done
