### ISSUE TITLE
Feat: Add curl example on documentation for using API

### ISSUE THREAD

**Issue by Quiwy** [tracim/tracim#5845]
I had some issue using curl (which is often installed by default) instead of httpie.

It can help other people to have an example with curl.

## PR
https://github.com/tracim/tracim/pull/5847

**Comment by PhilippeAccorsi** [comment]
@Quiwy process exist about issue. Do not close issue like this.

Please ask dev to understand process and why we need to not close issue.

**Comment by Quiwy** [comment]
> @Quiwy process exist about issue. Do not close issue like this.

Sorry, I guess I missed some automation on github as I did not closed it manually. Will double check next time.

**Comment by Millefeuille42** [comment]
Done
