### ISSUE TITLE
Feat: Display video player when clicking on preview

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5849]
## Feature description and goals

As a user, when I click on a video preview, I don't expect a carousel of some video images, I expect that it opens the video player.

- [x] Don't show carousel, only one image
- [x] When clicking on the image, open the video player

## Prerequisites

None

## PR
https://github.com/tracim/tracim/pull/5853

**Comment by Haskaris** [comment]
Tested on branch.

**Comment by Millefeuille42** [comment]
Done
