### ISSUE TITLE
Don't associate the apps color to the icons class (tracim v2)

### ISSUE THREAD

**Issue by AlexiCauvin** [tracim/tracim#585]
Don't associate the apps color to the icons class but manage the color at the parent level

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi do you know if its necessary to save this issue?

**Comment by Skylsmoi** [comment]
@PhilippeAccorsi You can close it. It's outdated

**Comment by PhilippeAccorsi** [comment]
I close this issue.
