### ISSUE TITLE
Feat: Improve sidebar when fullscreen mode and some visual cleaning

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5854]
## Feature description and goals

- [x] Have the actions of admin, account settings and profile in the three small dots
- [x] Right align confidential space icons
- [x] We need to have the sidebar visible when we are in fullscreen mode (collabora, tinymce, kanban)
- [x] Click on user name opens profile (same behavior that spaces title)

## Prerequisites

None

## PR
https://github.com/tracim/tracim/pull/5855

**Comment by wwalden** [comment]
tested on branch. When in kanban fullscreen mode, the button to exit the full screen doesn't exist

**Comment by Quiwy** [comment]
- When sidebar is opened, and I open a note in fullscreen, I can't have all tinymce menu:

![image](https://user-images.githubusercontent.com/20048264/186663471-e269d750-0267-4379-bd04-16834a9e45ec.png)

- I have no button to come back from fullscreen on kanban application.

- Space icon is moving when mouse is over it. It's quite disturbing when you have a lot of confidential spaces, and you are looking for one particular space.

![space_bar](https://user-images.githubusercontent.com/20048264/186664108-8104048c-e8c6-4abf-bb9d-3580663a3676.gif)

Maybe something like this is better?
![image](https://user-images.githubusercontent.com/20048264/186664868-df2281bc-1bd8-4d7e-a256-a64c8f68ab71.png)

**Comment by gbonaspetti** [comment]
I fixed the kanban button and added the others feedback at #5814 
Thanks!

**Comment by wwalden** [comment]
fix tested, looks great!

**Comment by Millefeuille42** [comment]
Done
