### ISSUE TITLE
Feat: Update sidebar colors

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5856]
## Feature description and goals

- [x] Change of sidebar color
- [x] Make sidebar font color custom by instance
- [x] Add custom color for logo background
- [x] Review icons colors
- [x] Add hover for icon on title even if we hover at the text
- [x] Add a little shadow around search input

## Prerequisites

None

## PR
#5861

**Comment by Quiwy** [comment]
Tested on branch

**Comment by Millefeuille42** [comment]
Done
