### ISSUE TITLE
Bug: Content doesn't go up on activity feed if an attached file or a to do is added

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5858]
## Description and expectations

Differently than when I add a comment, the content doesn't go up on activity feed if an attached file (or a to do) is added. As a user I expect the same behavior for both since attached files are shown as comments.  

### How to reproduce

1. Go to the content X
2. Make a comment
3. Go to the activity feed, content X should be on top
4. Make other activities
5. Go to content X again
6. Attach a file
7. Go to the activity feed

### Version information

- Tracim version: at least 4.3
- Web browser: Google Chrome, Firefox
- Device / System: PC

________________________________________________

## PR
https://github.com/tracim/tracim/pull/5859

If the parent id is not null, an endpoint is used to get its type and if it's not a folder it means that it's an attached file and it have the same behavior that a comment.
Also, to do schema is different from others contents, everything linked to it was update to follow its schema (e.g. `content.parent.id` instead `content.parent_id`).

**Comment by Millefeuille42** [comment]
Done
