### ISSUE TITLE
📝 Documentation: upgrade to 4.4.0

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5860]
## Sidebar colors

- :warning: Two new colors (`sidebar/font` and `sidebar/logo`) were added in `branding/color.json`: this requires all existing instances to update their `frontend/dist/assets/branding/color.json` files to add these new colors. Otherwise the backend won't start at all. You can see an example at `frontend/dist/assets/branding.sample/color.json`.
- The default colors (`sidebar` and `agenda`) were updated too and they are visible at `frontend/dist/assets/branding.sample/color.json`. `sidebar` changed from `#333333` to `#f3f3f3` and `agenda` changed from `#ff4b3a` to `#0b166a`.

After both updates, we have:
- Before (second and eighth line, `sidebar` and `agenda`)
```
{
  "primary": "#2f7d30",
  "sidebar": "#333",
  "contents/html-document": "#00CC00",
  "contents/thread": "#428BCA",
  "contents/file": "#ffa500",
  "contents/folder": "#414548",
  "contents/kanban": "#197474",
  "agenda": "#ff4b3a",
  "gallery": "#999999"
}
```
- After (second, third, fourth and tenth lines, `sidebar`, `sidebar/logo`, `sidebar/font` and `agenda`)
```
{
  "primary": "#2f7d30",
  "sidebar": "#f3f3f3",
  "sidebar/logo": "#f3f3f3",
  "sidebar/font": "#252525",
  "contents/html-document": "#00CC00",
  "contents/thread": "#428BCA",
  "contents/file": "#ffa500",
  "contents/folder": "#414548",
  "contents/kanban": "#197474",
  "agenda": "#0b166a",
  "gallery": "#999999"
}
```

## New interface language

- Norwegian has been added as a possible interface language. If you have Custom Properties specific to your instance, you will need to make specific translations as well. See the documentation at `backend/doc/user_custom_properties.md`

## Configuration update (development.ini)

A new variable was added `ui.notes.code_sample_languages` (`TRACIM_UI__NOTES__CODE_SAMPLE_LANGUAGES`) that defines the list of languages available to create code samples in the notes. By default it's value is 
```
ui.notes.code_sample_languages = markup:Markup,css:CSS,clike:C-like,javascript:JavaScript,apacheconf:Apache Configuration,arduino:Arduino,aspnet:ASP.NET,bash:Bash,batch:Batch,bbcode:BBcode,c:C,csharp:C#,cpp:C++,cobol:COBOL,css-extras:CSS Extras,csv:CSV,diff:Diff,django:Django/Jinja2,docker:Docker,erlang:Erlang,excel-formula:Excel Formula,fortran:Fortran,git:Git,haskell:Haskell,ignore:.ignore,ini:Ini,java:Java,jq:JQ,json:JSON,json5:JSON5,jsonp:JSONP,latex:LaTeX,lisp:Lisp,lua:Lua,makefile:Makefile,markdown:Markdown,matlab:MATLAB,nginx:nginx,objectivec:Objective-C,ocaml:OCaml,pascal:Pascal,perl:Perl,php:PHP,phpdoc:PHPDoc,php-extras:PHP Extras,powershell:PowerShell,properties:.properties,python:Python,r:R,jsx:React JSX,tsx:React TSX,regex:Regex,ruby:Ruby,rust:Rust,sql:SQL,vbnet:VB.Net,vim:vim,visual-basic:Visual Basic,yaml:YAML,wiki:Wiki markup
```

### API

API URL deprecated (with https://github.com/tracim/tracim/pull/5903):
- `/api/users/{user_id:\d+}/messages/{event_id:\d+}/read` in favor of `/api/users/{user_id:\d+}/messages/read` which accept a list of `event_id`
- `/api/users/{user_id:\d+}/messages/{event_id:\d+}/unread` in favor of `/api/users/{user_id:\d+}/messages/unread` which accept a list of `event_id`

**Comment by Haskaris** [comment]
API URL deprecated (with #5903):
- `/api/users/{user_id:\d+}/messages/{event_id:\d+}/read` in favor of `/api/users/{user_id:\d+}/messages/read` which accept a list of `event_id`
- `/api/users/{user_id:\d+}/messages/{event_id:\d+}/unread` in favor of `/api/users/{user_id:\d+}/messages/unread` which accept a list of `event_id`

**Comment by gbonaspetti** [comment]
:warning: If you are upgrading from build_92 to build_093, the sidebar color has changed. 
From:
```
  "sidebar": "#f6f6f6",
  "sidebar/logo": "#f6f6f6",
```
To:
```
  "sidebar": "#f3f3f3",
  "sidebar/logo": "#f3f3f3",
```

**Comment by PhilippeAccorsi** [comment]
Old release. We can close.
