### ISSUE TITLE
Feat: Improve new UI (new sidebar) on small screens

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5865]
## Feature description and goals

Better support of the small screens:

- [x] The sidebar should have full width on mobile and stay full height even when closed
- [x] If the user clicks on a redirection, it should close the sidebar (e.g. Click on "My tasks" open the page and close the sidebar)
- [x] Search filters should be closed by default
- [x] The app should not be hide by closed sidebar
- [x] The sidebar should open/close when clicking at empty zone

## PR

https://github.com/tracim/tracim/pull/5870

**Comment by Millefeuille42** [comment]
Done
