### ISSUE TITLE
Feat: Integrate Norwegian translation

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5866]
## Feature description and goals

Considering that the translations to the Norwegian Bokmål language were at 50%+ on Weblate, the language needs to be integrated into the interface.

It's an LTR language.

## To do

- [x] Add option as language by default (`backend/development.ini.sample` + `backend/tracim_backend/config.py`
- [x] Add language on pipeline langs for advanced search (`backend/tracim_backend/lib/search/elasticsearch_search/elasticsearch_search.py`)
- [x] Add language on tests (`backend/tracim_backend/tests/functional/test_system.py`)
- [x] Add caldav translations (`frontend/dist/assets/_caldavzap/config.tracim.js` + `frontend/dist/assets/_caldavzap/localization.js`)
- [x] Add language on default welcome page (`frontend/dist/assets/branding.sample/welcome-simple-text.html`)
- [x] Add language for Tinymce (`frontend/dist/assets/tinymce-5.10.3/js/tinymce/langs/nb_NO.js`)
- [x] Add language on redux (`frontend/src/reducer/lang.js`)
- [x] Add configuration to access translation files (`frontend/src/util/i18n.js` + `frontend_lib/src/index.js`)
- [x] Add dateFns configuration (`frontend_lib/src/helper.js`)
- [x] Add fallback option ffor browser language (`frontend_lib/src/i18n.js`)
- [x] Add information at #5860 about custom translations

## PR

https://github.com/tracim/tracim/pull/5876

**Comment by gbonaspetti** [comment]
Tracim has a new policy about its translations! From this version on, translations that have more than 50% of the keys translated in Weblate, will be integrated in the interface.

Thanks @comradekingu for the Norwegian translations! Currently we are at 48%, but as we were at more than 50% before, we will add the Norwegian interface. Your collaboration is very much appreciated, feel free to continue. :smiling_face_with_three_hearts:

**Comment by gbonaspetti** [comment]
Hi @comradekingu 

Ideally, it would be great not to need the cutoff, but since our team is small and interface integration is still manual, we have to prioritize :disappointed:. I hope that in the not too distant future we can automate things from our side and change that.

Wow, thank you so much. I added you to our project!

**Comment by Millefeuille42** [comment]
Done
