### ISSUE TITLE
Misc: update Caldavzap translations

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5867]
## Feature description and goals

Some translations were added or updated on Weblate and, since we don't have an automation yet (https://github.com/tracim/tracim/issues/5518), they need to be change on Caldavzap.

### To do 
- [x] Add Portuguese language (be sure that the "Fullscreen" translation is added)
- [x] Update Spanish, French and English translations

## Prerequisites

None

## PR

https://github.com/tracim/tracim/pull/5876

**Comment by Millefeuille42** [comment]
Done
