### ISSUE TITLE
Bug: Spamming the "create workspace" button results in too many workspaces

### ISSUE THREAD

**Issue by Quiwy** [tracim/tracim#5882]
## Description and expectations

Spamming the button to create a workspace results in multiples workspaces with the same name created.

### How to reproduce

(almost systematical)
1. Create a workspace
2. Click multiple times and fast on "create"
3. See how many workspaces you have created

### Version information

- Tracim version: build_089
- Web browser: Firefox 106

### Screenshots
![multiple_workspace_creation](https://user-images.githubusercontent.com/20048264/189074482-74618e39-7b1e-4b85-80ee-645223b18e6a.gif)

________________________________________________

## Diagnostic
Related to #5192 ?

## Prerequisites

None

**Comment by lebouquetin** [comment]
I believe this bug is larger - I mean there is a mechanism to implement on every submit button

**Comment by Quiwy** [comment]
Closing in favor of #5192 after internal discussion.
