### ISSUE TITLE
Bug: edit from recent activities doesn't seem to work 

### ISSUE THREAD

**Issue by Haskaris** [tracim/tracim#5884]
## Description and expectations
When I want to edit a comment from recent activities, it doesn't work

By "it doesn't work" I mean, I don't see my modification. This bug appears with other modifications too.
However, when I reload the page the modifications/edits are here.

### How to reproduce
1. Comment through an application a file or something
2. Go to an recent activity
3. Show comments
4. Edit comments
5. Voilà

### Version information

- Tracim version: 4.3.2 build_090 and 4.3.2 build_089
- Web browser: Not relevant
- Version: Not relevant
- Device / System: Not relevant

### Screenshots

Not relevant

## Linked PR
PR #5846

________________________________________________

**Comment by Relf-Algoo** [comment]
Seen with me, ticket creation validated.

**Comment by Haskaris** [comment]
After lot of digging, we had a (very old) mechanism to not update commentaries when receiving a TLM to _probably_ save some computing. However, since we now need to display commentaries, I updated this mechanism to not bypass the processing of the TLM when it's an updated commentary.
See the specific commit d08ec319d74a13c46f38d74e94711fb3606efe91 in the file `activity.js`
