### ISSUE TITLE
Feat: add line numbering in code/preformatted blocks in TinyMCE

### ISSUE THREAD

**Issue by Relf-Algoo** [tracim/tracim#5890]
## Feature description and goals

The user wants the preformatted blocks in the notes to contain line numbering

## PR and implemented solution

[Prismjs](https://prismjs.com/) was added to display code samples. Prism management is done through a plugin babel, where we can add the plugins we want to use and the languages supported. The styles of all languages are supported in this first version (an improvement would be to support only the styles of the languages proposed by TinyMce). Also a css file has been added, using the same logic. 
Some css classes have exactly the same name in Prismjs and Tracim, so some extra styles were added to the code blocks. To avoid this the classes were renamed (`content` => `contentItem` and `comment` => `timeline__comment`).
 
For the line numbering it was used the Prismjs plugin https://prismjs.com/plugins/line-numbers/

For the edit mode we added the [codesample](https://www.tiny.cloud/docs/tinymce/6/codesample/) plugin in TinyMce and a new variable in development.ini. This variable contains the list of languages that will be proposed in the editor, using the format `alias:display name` which is converted to the format requested by TyniMce, an `{ value: 'alias', text: 'display name }` object. The list is passed to TinyMce at initialization time.

One possible issue see at https://github.com/tracim/tracim/pull/5889/files#r993256371 is that reduxStore.system.config.ui__notes__code_sample_languages could not be initialized in time, i.e. TinyMce is initialized before Redux. A solution would be to add an await to this.loadAppConfig() in Tracim.jsx, but the software performance could degrade a little bit.

PR: #5889

**Comment by Millefeuille42** [comment]
Done
