### ISSUE TITLE
Ne pas montrer tous les utilisateurs à tout le monde

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#59]
Si l'utiIisateur est lecteur : 
- afficher uniquement les responsables

Si contributeur : 
- afficher les responsables + gestionnaires + contributeurs (mais pas lecteur)

Si l'utilisateur est responsable : 
- afficher tout le monde

Note : en profiter pour vérifier qu'on n'affiche pas les espaces de travail aux utilisateurs non concernés (visiblement c'est le cas sur l'instance du client "microlight")

**Comment by buxx** [comment]
A propos de 

> Note : en profiter pour vérifier qu'on n'affiche pas les espaces de travail aux utilisateurs non concernés (visiblement c'est le cas sur l'instance du client "microlight")

A tu un cas pour reproduire ? Mes essais de base me laisse penser que l'on ne peux pas afficher un workspace si on n'y à pas accès. Ou j'ai mal compris la note ?
