### ISSUE TITLE
User role definition is not clear (v1)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#590]
**At present**

When you see user role definition, you can't see information about create files.

**Expected**

Better role information is needed.

**Comment by PhilippeAccorsi** [comment]
With this description its ok.

**Comment by inkhey** [comment]
Comments are a special case of content, so right should be different there. (allow any contributor to modify other user content seems a bad idea.

How content modification , managment (deletion/archive), etc... should be integrated with workspace_role ?  I first was thinking about only admin or owner should be allowed to modify comments, but as i see there, admin is not a workspace_related concept, so should we consider content-manager as a kind of "admin" of workspace. If this is ok, we should just change content modification for comments from contributor to content_manager + grant to owner to modify them (only if he has a  contributor+ role ?)

**Comment by inkhey** [comment]
Another special case is user specific data, like user workspace endpoint. That's not a big problem as we can allow only specific user (and global admin) to watch is own data

**Comment by lebouquetin** [comment]
- There is a workspace manager which is the "admin of a workspace". Content manager is not.
- You're right about making things more clear - but some simplifications are already "the common use case" for example on gitlab, every user can modify any comment. Not sure we should do the same (it may appear to be strange for common users)
- did not understand your last point about user specific data

Please put your table here in order everybody to see it easily

**Comment by inkhey** [comment]
My proposition about right with actual endpoint in mind.

## Global profile


|                               | Normal User | Managers    | Admin   |
|-------------------------------|-------------|-------------|---------|
| participate to workspaces     |  yes        | yes         | yes     |
| access to tracim apps         |  yes        | yes         | yes     |
|-------------------------------|-------------|-------------|---------|
| create workspace              |  no         | yes         | yes     |
| invite user to tracim         |  no         | yes         | yes     |
|-------------------------------|-------------|-------------|---------|
| set user global profile rights|  no         | no          | yes     |
| deactivate user               |  no         | no          | yes     |
|-------------------------------|-------------|-------------|---------|
| access to all user data (/users/{user_id} endpoints) |personal-only|personal-only| yes     |


## Workspace Roles


|                              | Reader | Contributor | Content Manager | Workspace Manager |
|------------------------------|--------|-------------|-----------------|-------------------|
| read content                 |  yes   | yes         | yes             | yes               |
|------------------------------|--------|-------------|-----------------|-------------------|
| create content               |  no    | yes         | yes             | yes               |
| edit content                 |  no    | yes         | yes             | yes               |
| copy content                 |  no    | yes         | yes             | yes               |
| comments content             |  no    | yes         | yes             | yes               |
| update content status        |  no    | yes         | yes             | yes               |
-------------------------------|--------|-------------|-----------------|-------------------|         
| move content                 |  no    | no          | yes             | yes               |
| archive content              |  no    | no          | yes             | yes               |
| delete content               |  no    | no          | yes             | yes               |
|------------------------------|--------|-------------|-----------------|-------------------|
| edit workspace               |  no    | no          | no              | yes               |
| invite users (to workspace)  |  no    | no          | no              | yes               |
| set user workspace role      |  no    | no          | no              | yes               |
| revoke users (from workspace)|  no    | no          | no              | yes               |
|------------------------------|--------|-------------|-----------------|-------------------|
| modify comments              |  no    | owner       | owner             | yes             |
| delete comments (probably useful in the future)             |  no    | owner       | owner             | yes             |

**Comment by inkhey** [comment]
user role/profile mecanism is now specify in /backend/doc/roles.md.
