### ISSUE TITLE
Bug: error when using webdav if a space contains a kanban

### ISSUE THREAD

**Issue by Relf-Algoo** [tracim/tracim#5917]
## Description and expectations

When connecting to a tracim through webdaw on windows, spaces containing a kanban are displayed as empty although they contain files and notes and kanbans.

This has been reproduced on the Windows 11 of a client and on our own windows 10 VM. The problem did not appear on our Ubuntu 20.04
This has been reproduced on mon.tracim.fr (V4.3.2) and demo.tracim.fr (v4.3.2 build_090)

See Thread https://algoo.tracim.fr/ui/workspaces/296/contents/thread/82850 for investigation done on 2022-10-06. 

### How to reproduce

1. Go to mon.tracim.fr
2. create a space
3. create a note and a kanban in this space
4. launch the windows VM
5. Connect to montracim with webdav
6. try to open the space created.
7. Optionnal : remove the kanban through the web interface
8. Optionnal : refresh the explorer in the windows VM

### Version information

- Tracim version: All version since kanban available
- Web browser: [e.g. Google Chrome, Firefox, Safari]
- Version: [e.g. 22, latest]
- Device / System: Windows 10, 11

### Screenshots

________________________________________________

**Comment by Relf-Algoo** [comment]
According to @PhilippeAccorsi and @grignards, the problem now appears with linux OS too.

**Comment by Millefeuille42** [comment]
Tested on branch

**Comment by gbonaspetti** [comment]
Done
