### ISSUE TITLE
Bad naming in endpoints + wrong http codes

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#592]
Rename properties in all endpoints : 

- `content_type_slug` => "content_type"
- `sub_content_type_slug` => `sub_content_types` (in plural form as it's a list of values)
- `display_name` => `public_name`
- `"profile": { "slug": "managers" }` => `"profile": "managers"`
- `"global_status": "Open"` => values are always lowercase (so the example must be lowercase too)
- `id` => `workspace_id` pour les workspace, `content_id` pour les contenus
- `status_slug` => `status`
- `role_slug` => `role`

Wrong HTTP code and content : 

`/archive`, `/delete`, `/unarchive`, `/undelete` => return 204 with no body

Wrong datetime format : 

documented : "2018-06-18T21:11:16.876Z"
expected : "2018-06-18T21:11:16Z"

**Comment by lebouquetin** [comment]
This bug must be fixed before to implement new endpoints

**Comment by inkhey** [comment]
Datetime format is returned as ISO8601 format. Both value are accepted by this format.
So we can :
- Try to force acceptation of only "2018-06-18T21:11:16Z" format. Seems possibly tricky.
- Use specific datetime exemple instead of precise default exemple value.
