### ISSUE TITLE
wrong `/move` structure

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#593]
Current API is the following one : 

```
PUT
{
  "new_parent_id": 42
}
```

returning an empty result

Expected : 

```
PUT
{
  "parent_id": 42,
  "workspace_id": 23
}
```

returning the content object with up-to-date information.

The reason for these renaming : 

- the body with parent_id/workspace_id is "apply-able" on a content object (same property names)
- the returned structure should always include updated data.

**Comment by lebouquetin** [comment]
This bug must be fixed before to implement new endpoints

**Comment by inkhey** [comment]
return part bug is #596
