### ISSUE TITLE
Feat: Do not send notifications for task that do not concerns user

### ISSUE THREAD

**Issue by Millefeuille42** [tracim/tracim#5940]
## Feature description and goals

Do not send notifications for task that do not concerns user

## Linked PR
PR #5947
PR #5959

## Implementation
Since we display notification in two different ways, we have to filter both of them.
I've added a filter in `ReduxTlmDispatcher` and `NotificationPage`.
Furthermore an issue (#5946) has been created to handle filters in one place.

**Comment by Haskaris** [comment]
I've removed the backend label since we are using `Todo` as `Content`. I've created an issue to handle a "filtering" in backend #5946 which seems more complex than this feat/fix since it have to deal with more notifications.

**Comment by Quiwy** [comment]
Tested on branch

**Comment by Millefeuille42** [comment]
Done
