### ISSUE TITLE
📝 Doc: File run_development_server.sh doesn't exists

### ISSUE THREAD

**Issue by Quiwy** [tracim/tracim#5949]
### What content on github.com/tracim/tracim is affected?

https://github.com/tracim/tracim/blob/develop/doc/BUILD.md

### What part(s) of the content would you like to see updated?

Part `Run development server` tell user to run script `run_development_server.sh` .

I guess the script to run is instead `run_dev_backend.sh`

### Related PR(s)

#5950

**Comment by Millefeuille42** [comment]
Done
