### ISSUE TITLE
Update "requirement.txt" of tracim_backend.

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#595]
Some dependency are missing in requirement.txt of tracim_backend. Update them.

**Comment by inkhey** [comment]
copy from https://github.com/tracim/tracim_backend/issues/32

> we now have a requirement.txt (useful for security check) file (not used automatically, you need to explicitly say you want to use those versions).

**Comment by PhilippeAccorsi** [comment]
Verified.
