### ISSUE TITLE
✨ Feat: export useLifecycle hook when it's usage will be appropriate

### ISSUE THREAD

**Issue by Millefeuille42** [tracim/tracim#5954]
## Feature description and goals
This hook is designed to bring a better syntax to the useEffect hook when it is used to replace class component's componentDidMount and componentWillUnmount (passing [] as deps).

It will find it's usage when refactoring class components or creating function components.

## Prerequisites
This hook will be added in the solution of #5951

**Comment by lp-algoo** [comment]
this issue has been solved in #5955
