### ISSUE TITLE
✨ Feat: Display Kanban in activities

### ISSUE THREAD

**Issue by Haskaris** [tracim/tracim#5957]
## Feature description and goals

When a kanban is modified it's not displayed in the activities.
We also have a 404 error in the console.

## Linked PR
#5958

## Implementation
Since kanban are file, when calling the api related to space content, I've changed the type from kanban to files.
Another solution was to duplicate endpoints for kanbans.

**Comment by Quiwy** [comment]
Tested on branch

**Comment by Millefeuille42** [comment]
Done
