### ISSUE TITLE
🐛 Bug: Comments with code/pre blocs are overflowing

### ISSUE THREAD

**Issue by Relf-Algoo** [tracim/tracim#5960]
## Description and expectations

When the text from a pre bloc or a code bloc goes  beyond the size of the screen, the whole interface is sent to the end of the text, meaning out of the screen.
See thread https://algoo.tracim.fr/ui/workspaces/296/contents/thread/85674 

## Linked PR
PR #5961

**Comment by Relf-Algoo** [comment]
This happens not for the whole thread, only for the message(s) containing the bloc.

**Comment by Millefeuille42** [comment]
Done
