### ISSUE TITLE
✨ Feat: Normalize the lists on Tracim interface

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5964]
## Feature description and goals

Currently the Tracim interface has several different lists. As a user, I don't understand why list X is displayed one way and list Y another.
As far as the code goes, it would be ideal to have components dedicated to the list.

## Screenshots

Some lists examples, we can see that background color, size, borders, etc are very different between lists.

![Screenshot from 2022-10-22 17-19-06](https://user-images.githubusercontent.com/35422692/197347210-eb272554-8448-47df-aab3-97791e2fb472.png)

![Screenshot from 2022-10-22 17-18-55](https://user-images.githubusercontent.com/35422692/197347211-70c1abbc-a469-4713-8a3d-5f153e64139a.png)

![Screenshot from 2022-10-22 17-19-22](https://user-images.githubusercontent.com/35422692/197347209-20944282-9d7d-4124-be14-bb3ba805ee4e.png)

## Working branch
feat/5964__normalize_lists (with #5818 as prerequisite)

**Comment by Haskaris** [comment]
This one should be done using #6034

Plus working on this should also fix the displacement in the content list:
![Screenshot from 2023-04-27 09-09-12](https://user-images.githubusercontent.com/28917197/234786518-5c9ade4e-ae8e-422a-aa9e-25f352731d6e.png)

**Comment by lp-algoo** [comment]
this issue has been resolved #6034
