### ISSUE TITLE
🐛 Bug: Elements are not aligned well on sidebar

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#5966]
## Description and expectations

As we can see on the screenshot, we have two alignements (pink and purple). The elements that have an icon are aligned between them (purple) and the The elements that fold/unfold are aligned between them (pink).

- The alignment of the sub-items should be more marked.
- The left title icon is not aligned with the pages icons nor the "open subspace" icons.
- The space title has not the same alignement when it has children or not (in the same level).

![Screenshot from 2022-10-23 18-37-08](https://user-images.githubusercontent.com/35422692/197404915-2e1fdfc4-bd9a-44bc-899e-62db95bd3d86.png)

As an user, I expected that all "external" elements (titles and the two first items) are aligned between them and the "internal" items (spaces, my tasks item, my favorites item and my agendas item) are aligned between them.

### Version information

- Tracim version: v4.4

### PR
#6022

**Comment by Millefeuille42** [comment]
Tested on branch.
