### ISSUE TITLE
✨ Feat: enlarge preview of images in comments instead of downloading them

### ISSUE THREAD

**Issue by Relf-Algoo** [tracim/tracim#5974]
## Feature description and goals

Currently, clicking on images in comment downloads the image on the disk.
We would like the click to only enlarge the picture (like the previews of contents or the gallery) so that the image can be seen in just one click.
Discussion needed on whether the download can be done through a menu next to the enlarged display or through the classic right-click.

## Prerequisites

To be discussed before development 
Interface : see aboce

**Comment by gbonaspetti** [comment]
Duplicated #5997
