### ISSUE TITLE
Add generic get content endpoint with 302 redirection to correct content type get endpoint

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#599]

**Comment by inkhey** [comment]
2 problems with this issues: 
- Endpoint with workspace_id is ok, but shoudl we have endpoint without workspace_id ? something like : 
`/api/v2/contents/{content_id}` ?
- How redirect result should be return ? Should we return empty json or something else ? Is using pyramid redirect ok (it return html result but http status code are ok, and result is correct json if redirection is followed ?)

**Comment by PhilippeAccorsi** [comment]
Verified.
