### ISSUE TITLE
🐛 Bug: Large button to join spaces

### ISSUE THREAD

**Issue by Relf-Algoo** [tracim/tracim#5994]
## Description and expectations

the mobile app (iOS and Android) displays very large button to join spaces, hiding the names of the spaces in the list
See thread https://algoo.tracim.fr/ui/workspaces/296/contents/thread/86623

### How to reproduce

1. Go to…
2. Click on…
3. Scroll down to…

### Version information

- Tracim version: [e.g. v2.7, Mon Tracim]
- Web browser: [e.g. Google Chrome, Firefox, Safari]
- Version: [e.g. 22, latest]
- Device / System: [e.g. PC, iPhone 6]

### Screenshots

________________________________________________

**Comment by gbonaspetti** [comment]
Fixed at #6030
