### ISSUE TITLE
✨ Feat: Add emoji button in rich text (tinymce) editor

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#6006]
## Feature description and goals

Inserting an emoji into a note or comment can be difficult depending on the user's technical knowledge. Having a button to select emojis would lower the entry level of using emojis.

## Implementation

#6010 
- use the official [emoticons plugin](https://www.tiny.cloud/docs/plugins/opensource/emoticons)
- add a button in the toolbar, it displays tinymce's emoji picker
- add a keyboard shortcut *Ctrl+e*, it displays tinymce's emoji picker
- add emoji library using the cache token and the csp #6021

**Comment by Haskaris** [comment]
Fix #4436 in advanced edition, #6058 will fix in simple edition.
