### ISSUE TITLE
Allow to attach comment to a specified revision + fix "Comments_ids" param in revision

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#601]
Actually comments are link to a content, there is no direct way to clarify the revision about what the comments is referring

**Comment by lebouquetin** [comment]
TODO : 

- dynamically map comments to revisions according to creation datetime
- add a technical debt ticket for :  
    - adding a field reference_revision_id to comments
    - write a sqla migration for associating old comments to revisions
    - add a specific endpoint for commenting an old revision

**Comment by inkhey** [comment]
dynamic mapping is done with https://github.com/tracim/tracim_backend/pull/91/commits/aa7730cf756b2451a4831a02d8ac585ea69100f4
technical debt_ticket is available here #607
