### ISSUE TITLE
✨ Feat: Refactor listings

### ISSUE THREAD

**Issue by Millefeuille42** [tracim/tracim#6034]
## Feature description and goals

Current listings are a bit messy and sometime it's hard to align everything in it when content varies.

## Proposed solutions

~~Using grids could be a solution.~~

Using [react-tables](https://github.com/TanStack/table).

## Prerequisites

~~Needs discussion.~~

- [x] Need to define what features from react-tables should be used.
- [x] Need to define properties of a new and generic 'listing component'.
- [ ] Need to think about how nested content will be handled (example: folders in Workspace content)

## Specs

- Optional columns headers (example: TODOs)
- Dynamic columns numbers
- Difference in number of columns and number of headers
- Optional 'sort by' upon clicking on header columns (as brought by #6030)
- Optional filter using a filter bar (as brought by #6028)
- For the table contents
  - Using a normalized generic container which will manage the content alignment and display
  - for each cell, using 'slots' for content display, one for main content and one for sub content (example: filename and breadcrumbs in Favorites)

### Expected results

Making the most generic and dynamic component as possible will provide the ability to have an unified set of listings whether it is in the code or in the UI.

## PR 
#6067

**Comment by gbonaspetti** [comment]
Linked to #5964
