### ISSUE TITLE
🐛 Bug: On advanced edition, the autocompletion popup is hidden behind the sidebar menu

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#6035]
## Description and expectations

On advanced edition, when I'm in full screen and I want to enter a mention, the autocompletion popup is hidden behind the sidebar menu.

### How to reproduce

1. Go to a content
2. Click on comment advanced edition
3. Click on fullscreen
4. Type ` @`

### Version information

- Tracim version: v4.4
- Web browser: Firefox
- Device / System: PC

### Screenshots

![Capture d’écran de 2022-11-16 16-41-05](https://user-images.githubusercontent.com/35422692/202225803-9d5f8a54-a7fb-4f65-888e-2309bd7e4a56.png)

________________________________________________

## Diagnostic and implemented solution

The moment we make Tinymce fullscreen mode, we overwrite its css to take into account the sidebar. This operation is done in frontend/src/css/Generic.styl.
However, the auto-completion popup does not take this into account, so we have to do the same for it.
We use the sibling selector, since they are on the same level, but with it it is only possible to change later elements. So if the autocompletion component is used with advanced editing, it must be placed AFTER the textarea.
This solution is not ideal, but the component is going to be deprecated on https://github.com/tracim/tracim/issues/6007, so it's just a workaround until that.

## PR

#6036

**Comment by Millefeuille42** [comment]
Tested on branch.
