### ISSUE TITLE
🐛 Bug: In notification email, wrong link to content when editing a comment of a thread

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#6037]
## Description and expectations

When you edit a comment of a thread, other members receive an email notification (if activated).

At the bottom of that mail there is a link to the content that points to the comment but that url isn't handled by tracim frontend.
The url should point to the parent content of the comment.

### How to reproduce

You need 2 users, here called U1 and U2:
1. U1 Create a Thread in a Space where U1 and U2 are members
2. U1 Create a comment in that thread
3. U1 Edit that comment
4. U2 Should have receive a mail about the edition of the comment. That mail have the wrong link at the bottom "check on Tracim"

### Version information

- Tracim version: v4.4.2 build_095
- Web browser: FF
- Version: Latest
- Device / System: Ubuntu 20

### Screenshots

________________________________________________

**Comment by PhilippeAccorsi** [comment]
Related to this issue https://github.com/tracim/tracim/issues/1691 @Skylsmoi  ?

If yes, some information maybe need to be added here or old issue need to be updated.

:)

**Comment by Skylsmoi** [comment]
indeed it's the same problem
I'm closing this issue since the other has some history
