### ISSUE TITLE
"owner" should be different from "last_modifier"

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#606]
For API endpoint, we need "last_modifier" and "owner". 
Owner should probably be the person who create the content when last_modifiers is the person who create the last revision of the content.
There is actually no such thing as a distinct owner from last_modifier in Tracim.
In fact, actually, "owner" of a tracim content is owner of the last revision. It the same as what "last modifier" should be.

We should find a way to provide a "owner" distinct from owner of last revision.
Possible solutions:
- Add a true "owner" field in database related to content distinct from actual owner field.
- Same but add a last_revision field and modify a bit the behaviour of content.
- Consider owner of first revision as eternal owner of content.

**Comment by lebouquetin** [comment]
Same issue as https://github.com/tracim/tracim/issues/202 which should have fixed the bug. Probably, the issue has been fixed in serialization.

Add a TODO in the code for renaming `owner` to `author`.

**Comment by inkhey** [comment]
renaming in API is done in tracim/tracim_backend#91.
renamin is model and core api should be done later (see #608).
