### ISSUE TITLE
🐛 Bug: Wrong tag button color

### ISSUE THREAD

**Issue by gbonaspetti** [tracim/tracim#6088]
### Tracim version

3.9.0

### Issue description

In an app all buttons have the color of the app, except the create/add tag button. This button has the color of the instance, making the interface less coherent.

### How to reproduce

1. Go to an app
2. Click on tag tab
3. See the button

### Screenshots

- App color: orange
- Button color: green

![Screenshot from 2023-01-11 11-40-52](https://user-images.githubusercontent.com/35422692/211786396-769f0244-767a-48ca-8fc9-ed4edf054935.png)

### What browsers are you seeing the problem on?

Any

### What devices are you seeing the problem on?

Any

### Related PR

#6089

**Comment by gbonaspetti** [comment]
Hello @tracim/algoo
I proposed a PR for this issue, should I add the issue in some specific project (maybe in the current version project with the backlog tag)?
Another thing, I added the team as reviewer, but don't hesitate to change if you prefer specific people.

**Comment by Haskaris** [comment]
Hello,
Since the project (from github) is destined to Algoo (sprint related) there is no need to add it.
We'll manage your fix/PR as an external contribution.

For the reviewer, selectionning the team is fine for now. We are planning to improve the experience in the near future, sorry for the inconvenience.

**Comment by gbonaspetti** [comment]
Hey, no problem, it's not an inconvenience, it's just a doubt that I had while contributing to make sure it's not a contribution in vain (that would just be forgotten and never merged).
Thx for your answer! :slightly_smiling_face:
