### ISSUE TITLE
📝 Please review first ever services config (bridge network) and edition of docker run cl 

### ISSUE THREAD

**Issue by Keepshango** [tracim/tracim#6095]
### Which file(s) on Tracim is affected?

Docker image

### Which part(s) of the file would you like to see updated?

Hello,

What follows consider such a **services configuration of choice** that allows Tracim app container to connect non-containerrized MariaDB server (both services on same host) **using the docker default bridge network**. 

I am about to execute following **“docker run“ command line**, but being newbie to docker, I’d like someone to review it and tell if it is correctly edited and functional to run Tracim app container, depending external database through connection over default bridge network : 

**docker run --env-file /tracim/.env_named -p 8080:80 - p 3306:3306 -v ~/tracim/etc:/etc/tracim -v ~/tracim/var:/var/tracim algoo/tracim**

So to allow whoever wishing to help, the above “docker run“ command line may be reviewed based on **here below 5 steps** (each one showing how it renders the “docker run“ command line getting build),  to configure both services, **Tracim app container** and the **MariaDB server** (on same host).

I’ll be thankful too, to get replies to simple questions ending this post.

**SERVICES CONFIGURATION** 

**STEP 1 : I did successfully install docker via shell**
• sub-step : verify that docker is running - **OK**
• sub-step : connect and disconnect to docker via terminal using my docker hub account credentials - **OK**
• sub-step : get my host’s docker IP ADRESS to allow its remote access from container with docker default bridge mode : 172.17.0.1 (next on step 3)
**°°° editing cl °°°**
_docker run -p 8080:80_
**°°° source °°°°°°°**
[https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-22-04](url)
[https://www.howtogeek.com/devops/how-to-connect-to-localhost-within-a-docker-container/](url)

**STEP 2 : I did install tracim volumes and pull algoo/tracim image via shell, as non-root user (su -)**
• sub-step : locate created volumes in Ubuntu OS file system  - **OK**
**°°° editing cl °°°**
_docker run -p 8080:80 ……. -v ~/tracim/etc:/etc/tracim -v ~/tracim/var:/var/tracim algoo/tracim_
**°°° source °°°°°°°**
[https://hub.docker.com/r/algoo/tracim ](url)

**STEP 3 : I did create and setup database and user on my host (VPS)** 
• sub-step : grant all privileges to new user on new database, with remote access from any host (%) - **OK**
• sub-step : change MariaDB server bind-address to host’s docker IP ADDRESS “172.17.0.1“ - **OK**
**°°° editing cl °°°**
_docker run ……. - p 3306:3306 -p 8080:80 -v ~/tracim/etc:/etc/tracim -v ~/tracim/var:/var/tracim algoo/tracim_
**°°° source °°°°°°°**
[https://phoenixnap.com/kb/mysql-remote-connection](url)
[https://linuxize.com/post/mysql-remote-access/](url)

**STEP 4 : I did create .env file in tracim container root directory**
• sub-step : extend the .env with a specific name : # sudo nano ./tracim/.env_named - **OK**
• sub-step : set the .env_named file with the above created MariaDB database environment variable, such as 
MYSQL_ROOT_PASSWORD=password
MYSQL_DATABASE=name
MYSQL_USER=user
MYSQL_PASSWORD=password
**°°° editing cl °°°**
**docker run --env-file /tracim/.env_named -p 8080:80 - p 3306:3306 -v ~/tracim/etc:/etc/tracim -v ~/tracim/var:/var/tracim algoo/tracim**
**°°° source °°°°°°°**
[https://www.systranbox.com/how-to-setup-env-file-linux/](url)

**STEP 5 : set firewall (ufw) to allow container’s IP ADRESS to listen on port 3306**
• sub-step : verify from cpanel that port 3306 is allowed in firewall - **OK**
• sub-step : allow traffic and matching between container’s IP ADDRESS and MariaDB server port 3306 **(MISSING)** 
(the container’s IP ADDRESS may only be collected after that the container was run at least once)
**°°° source °°°°°°°**

**QUESTIIONS**
Q1 : does final “docker run“ command line (step 4)  miss configuration parameters, e.g host’s docker IP ?
Q2 : does final “docker run“ command line (step 4) contains parameters that are unnecessary ?
Q3 : is .env_named file (step 4) is correctly configured with on host database environment variable (MariaBD)?
Q4 : may execution of above “docker run“ command line fails because of step 5 (ufw) being unachieved ? 

Regards

**Comment by Quiwy** [comment]
Hi @Keepshango ,
Since [Tracim version 4.0.0 ](https://github.com/tracim/tracim/releases/tag/release_04.00.00)released in October 2021, mysql/mariadb support is not provided anymore.



So, you're on your own on this ticket.
Best regards.
