### ISSUE TITLE
Method 'extract_links_from_content' always return empty list

### ISSUE THREAD

**Issue by Nonolost** [tracim/tracim#61]
In 'tracim/model/data.py' in class 'Content', method 'extract_links_from_content'; the function always return an empty list
```
lists = []
return lists
# the rest of the function's code; not reached
...
```

Can be found here : https://github.com/tracim/tracim/blob/master/tracim/tracim/model/data.py#L1018

**Comment by tracim** [comment]
This part is a hotfix (you can blame me as I did not comment it in the source) because of random hanging cause (probably) by BeautifulSoup.

The code shoulb be better commented ; I'm pretty the feature "extract_links" can be removed as it is not used anymore in the UI

**Comment by tracim** [comment]
The fix is to remove this method and all calls to it
