### ISSUE TITLE
Refactor NewContentType and ContentTypeLegacy and same thing with contentStatus 

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#610]
file in tracim/models/contents.py

We need to not rely on old "ContentType" object of tracim v1, we should have one ContentType object and one "ContentTypeList" object . There should
 be one ContentTypeList object acessible anywhere as a global var (we should think later about to to make this not global, but that's not easy)

Same for ContentStatus.

**Comment by PhilippeAccorsi** [comment]
Verified.
