### ISSUE TITLE
✨ Feat: Reduce mail notification by grouping them in one daily email

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#6106]
### Feature description

To reduce the number of email sent, add the possibility to set mail notification as "daily" per spaces.
The mail will recap the unread mentions and the unread notifications in the last 24h.

#### Backend
- [x] add a tracimcli command to generate and send the emails
  - [x] and documentation on how to create a cron for this command
- [x] a python script that will fetch the data from database and send the mail
- [x] migration in the db to store the new 3 state value of mail notification
- [x] change api to allow new "daily notification" option
- [x] make the cron file in the volum to allow to change it on different instances
- [x] fix docker images build (solution was found on develop branch)
- [x] fix the "noreply+{user_id}@..." as the from email
- [x] complete translation process (add lang parameter to _send_mail())
- [x] add the new parameter email.summary.template.html to breaking changes info

#### Frontend
- [x] add the new mail template
  - [x] and the design
  - [x] have the template give url for instance logo
- [x] change the mail notification button on space dashboard to allow "daily notification" and the related api
  - [x] and account page and admin account page

#### Questions
- [x] upon migration should we set every members to "daily" or keep them on "individual" (for members with email notifications activated)
- [x] at what hour should we send the email ?
  - This might require some mail template adjustments regarding "today" or "yesterday" for example
- [x] Should we have delays between instances to mitigate the number of mail sent at the same time
- [ ] Naming of the parameters - keep in mind there might be added temporality later:
  - Current: individual, summary, none
  - Proposed: atomic, daily-digest, none (and later weekly-digest)
 
#### Known issues
- We cannot differentiate a message workspace_member.modified changing a role or a email_notification_type. The impact is that each email_subscription_change will be displayed in recent activities which we would not want. Current implementation hide both, role change and email_subscription_type change
- Due to the notification wall and the recent activities list filtering some irrelevant messages and the summary mail process not doing exactly the same, the number of activities in the mail might differ from the recent activities for a given space and differ from the notification wall.
  - To fix this, the summary mail must filter the same messages as recent activities and notification wall

### Related PR

 #6108

**Comment by Haskaris** [comment]
# API Change

## Removed (`PUT`)

- /api/users/{user_id:\d+}/workspaces/{workspace_id}/notifications/activate
- /api/users/{user_id:\d+}/workspaces/{workspace_id}/notifications/deactivate

## Added (`PUT`)

- /api/users/{user_id:\d+}/workspaces/{workspace_id}/notifications/email_notification_type

Takes a body with `email_notification_type`

**Comment by PhilippeAccorsi** [comment]
Do not miss to make documentation about this breaking change.

It is possible to add deprecated information and maybe save this parameter available in code, and remove parameter definitly in futur release ?

**Comment by PhilippeAccorsi** [comment]
`EMAIL__NOTIFICATION__ENABLED_ON_INVITATION` this is not exist in development.ini upper case is just value used in env variable.

**Comment by Haskaris** [comment]
Since the code is completely different, it'd require a lot of changes to keep both of the parameters (we'd have `do_notify` = `true`/`false` and the new state)
Sadly we can't have a deprecated information here... We could have if we had predicted that we'd change this parameter. But it's definitely not backward compatible :/

**Comment by Haskaris** [comment]
You're right, my mistake it's `email.notification.enabled_on_invitation` ; editing my comment

**Comment by PhilippeAccorsi** [comment]
You can find information here https://github.com/tracim/tracim/blob/develop/doc/backend/env_settings.md

Value in development.ini `email.notification.enabled_on_invitation`

**Comment by PhilippeAccorsi** [comment]
@Haskaris `NB: new users will not being notified until they login to Tracim a first time` this is saved with the new parameter, right ?

**Comment by lebouquetin** [comment]
Instead of 'individual', 'summary', 'none', i suggest 'atomic', 'daily-diggest', 'none' @Haskaris @Skylsmoi

**Comment by PhilippeAccorsi** [comment]
Last question :

Why solution not save 2 parameters ?
- first one with value true/false
- second one with periodicity 

(I don't know if two parameter is good or not but not sure one parameter is better)

**Comment by PhilippeAccorsi** [comment]
last comment (again ^^ )

```

    email.notification.type_on_invitation

Possible values are SUMMARY, INDIVIDUAL, NONE
Default value is SUMMARY.
```
It can be a good idea to explain in documentation (for this breaking change) what we have in the past and what we have now.
- With value at `true` by default, user receive email for each notification 
- Now with `summary` by default, user recevive just email with summary of notification (question : `summary` is for day, week, month ?)

**Comment by Skylsmoi** [comment]
@lebouquetin 
about your naming proposition, regarding "daily", we discussed it and since the feature is how to send mails related to messages, we thought that "daily" is only a specific configuration of the cron that uses the feature. So for the backend context, the mail sent is either for an individual message or a summary of messages. That's why we chose "individual" and "summary"
We will show "daily" in frontend though.

regarding "atomic" instead of "individual", I'm ok with the renaming

**Comment by lebouquetin** [comment]
I think we will require daily & weekly at a moment, si we need to do a distinction (and thé diggest would bé built differently, I think, non?)

By thé way, if tout show daily in thé front-end, why IS it a problem to get it un thé configuration ?

**Comment by lebouquetin** [comment]
Anyway, at least I think the right way to name this IS diggest, non?

**Comment by PhilippeAccorsi** [comment]
After discussion with skylsmoi we need to add some fix to use this new feature: add cron job in docker volume to make possibility to change default send hour, add cron job installation in install default backend (without docker), check if task executed by cron is done or not if notification is disabled or if notification is just individual, and some other thing. 

We need a small discuss @lebouquetin about the default hour set in the cron job (actually is set at 0h00, so user receive email near this time and it is maybe not a good idea (ex: if email subject is like this : "what you miss today").

Question also about SaaS impact if summary is send to all users in same time (same hour).

**Comment by Skylsmoi** [comment]
I agree that if we choose a naming with "daily" or "weekly", "digest" (with only one -d)  is a good suffix

**Comment by Skylsmoi** [comment]
### Issue related to environment variables:

The cron job that sends summary mail cannot access the environment variable because it isn't bash that's running the process.

To workaround that, the cron job run a script that load a file containing all the environment variable (`send_summary_mail.sh.sample`). That file is created in the `entrypoint.sh` with `printenv |grep TRACIM > /var/tracim/data/tracim_env_variables`. This file is used by uwsgi.

The issue is that `printenv` displays the values unescaped. A value with a quote `'` break the cron.
Uwsgi loads the variable with `env = %(_)` (`uwsgi.ini.sample`) and manage to use the properly escaped version

But we currently don't have proper way for making cron to use an escaped version.

**Comment by PhilippeAccorsi** [comment]
We can use command like this `declare -x |grep TRACIM |cut -c12-` to create another file usable by cron task.
