### ISSUE TITLE
Workspace create/update + invite user to workspace + set user role endpoints

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#611]
- Create new workspace
- Update workspace description/name
- invite user to workspace
- set user role in workspace

**Comment by inkhey** [comment]
after merging https://github.com/tracim/tracim_backend/pull/95

- [X]  Endpoint to create workspace
- [X]  Endpoint to modify workspace
- [X]  Endpoint to modify user role in workspace

WIP: Add/Invite user to workspace :
- [X] Endpoint to add user to workspace
- [X]  Create new tracim user when email is provided but user do not exist ?
- [X] Better output schema for add user to workspace endpoint (return info about new user creation)
- [ ] Reenable user mail notification for new created account

**Comment by PhilippeAccorsi** [comment]
Verified.
