### ISSUE TITLE
user account endpoint

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#612]
- change user password
- change email
- change other user informations (timezone,public_name, avatar)
- active/disable account
- change global profile (user, manager, admin)
- GET /api/v2/users/{user_id}/known_members/?acp=text

**Comment by inkhey** [comment]
after merging tracim/tracim_backend
**endpoints :**
- [X] create user endpoint
- [X] update user email,password, user info
- [X] get user endpoint
- [ ] get all user for admin endpoint
- [ ] get known user endpoint
- [ ] delete user endpoint

**others/bugs/etc.. :**
- [ ] Check need of "transaction.commit() for password modification
- [X] Fix tracim/tracim#680 issue with is_active

**Comment by PhilippeAccorsi** [comment]
Verified.
