### ISSUE TITLE
Restore File content type

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#614]
endpoint:
- create file (post http upload)
- update file (2 PUT endpoint : JSON and http-upload)
- get revisions of file
- get file (2 GET endpoint : json + file)
- get previews (many endpoints)
- set status of file.

Other:
- need preview_generator (tracim/tracim_backend#42)

For manual tests :  
- go to swagger autogendoc and tests endpoints.

**Comment by PhilippeAccorsi** [comment]
Verified.
