### ISSUE TITLE
📝 Documentation: upgrade to 4.5.0

### ISSUE THREAD

**Issue by Haskaris** [tracim/tracim#6161]
# Breaking/Important changes

### development.ini

We've renamed _email.notification.enabled_on_invitation_ to __email.notification.type_on_invitation__.
The new possible values are:

  - `none`: doesn't send any mail
  - `individual`: send a mail for every notification receive
  - `summary`: send a daily mail containing notification summary

The default value is `summary`.
If you had `email.notification.enabled_on_invitation` as `true`, the equivalent is now `individual`.

On an already existing installation, it's necessary to update `development.ini`.
If you haven't changed this file, you can delete it and start Tracim. If you have any doubt or if you use the `api_key` it is better to backup this file.

This file is in:
- On default install, `backend/`
- On docker install, `/{docker-volume}/etc/`

You can also update this file manually before starting Tracim. 

### Endpoint

If you use theses endpoints you might want to change your scripts. We removed two endpoints in favor of one. Unfortunately, we couldn't set them to deprecated...

#### ✨ Added

- [`PUT`] /api/users/{user_id:\d+}/workspaces/{workspace_id}/email_notification_type
  - Body:
    - `email_notification_type`: `none`, `individual`, `summary`

#### 🔥 Removed

- [`PUT`] /api/users/{user_id:\d+}/workspaces/{workspace_id}/notifications/activate
- [`PUT`] /api/users/{user_id:\d+}/workspaces/{workspace_id}/notifications/deactivate

#### Updated

We had to update `RoleAPI.create_role` function. Therefore if you use this function in your custom script, here is what you need to know.

Parameters:

- `with_notif` is removed in favor of `email_notification_type`.  

That means you will have to change `with_notif=True` to `email_notification_type=EmailNotificationType.SUMMARY` or `email_notification_type=EmailNotificationType.ALL` in your plugins.  
`with_notif=False` is now `email_notification_type=EmailNotificationType.NONE`

Possible values for `email_notification_type` are:

- `EmailNotificationType.NONE`
- `EmailNotificationType.INDIVIDUAL`
- `EmailNotificationType.SUMMARY`

**Comment by PhilippeAccorsi** [comment]
This two plugin `tracim_backend_auto_invite` and `tracim_backend_parent_access` need also to be replaced by the new one available in the repository (cf https://github.com/tracim/tracim/tree/release_04.05.00/backend/official_plugins )

**Comment by lebouquetin** [comment]
@PhilippeAccorsi can we close this issue?

**Comment by PhilippeAccorsi** [comment]
I think we can now close documentation about upgrade, for all old release.
