### ISSUE TITLE
Reorganise backend code to make him more modular, with "applications"

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#617]
This issues is about reorganising code to make code use "application" who have:
- controllers
- schema
- models
- metadata (name, color, ...)
- associated content_type
- config
- etc

Todo:

- [ ] put specific application code in specific dir in applications dir.
- [ ] make load/unload of app dynamic (https://github.com/tracim/tracim/issues/2555)
- [ ] clarify enable/disable of app in config (see https://github.com/tracim/tracim/issues/2215)
- [ ] Upgrade docker file

### Original issue:

> # Reorganise schema/models/controllers for app with plugin architecture in mind
> 
> > (from le bouquetin) You will probably have a folder named /plugins/html-document where you will find models, controllers, etc.
> 
> folder app pluginification of :
> - [ ] controllers
> - [ ] marshmallow_schema
> - [ ] models related
> - [ ] others ?

**Comment by inkhey** [comment]
As we do have example for share and upload permission app, we can follow the same folder organization.

**Comment by inkhey** [comment]
@PhilippeAccorsi :
- This PR convert CALDAV_ENABLED and COLLABORATIVE_DOCUMENT_EDITION__ACTIVATED deprecated as deprecated parameters.
- To activate/disable any app including agenda and collaborative document edition, you need to set app.enabled.
- app.enabled order change ordering in ui currently, we should use order of app available in development.ini.sample for docker configuration.

**Comment by PhilippeAccorsi** [comment]
> @PhilippeAccorsi :
> 
>     * This PR convert CALDAV_ENABLED and COLLABORATIVE_DOCUMENT_EDITION__ACTIVATED deprecated as deprecated parameters.
> 
>     * To activate/disable any app including agenda and collaborative document edition, you need to set app.enabled.
> 
>     * app slug order in app.enabled change ordering in ui currently, we should use order of app available in development.ini.sample for docker configuration.

Ok. So for docker I need to make some change, and change documentation about how to use feature.

**Comment by inkhey** [comment]
Some frontend bug are found related to this new architecture:
- if app `gallery` is disabled, folder edit should not propose `gallery`.
- if app `share_content` app is disabled and `public_download_enabled` is true in workspace, frontend should not propose enabled/disable public download and should not load/display share for content.
- if app `upload_permission` app is disabled and `public_upload_enabled` is true in workspace, frontend should not propose enabled/disable public upload and should not show "Received files" dir.

**Comment by metzgegu** [comment]
I just commit frontend fix for these bugs into the branch : `fix/617__reorganise_apps_frontend_fix`

**Comment by inkhey** [comment]
:heavy_check_mark:  verfied on branch

**Comment by PhilippeAccorsi** [comment]
- [x] Tested and verified on develop branch with pserve
- [ ] Tested and verified on develop branch with docker
