### ISSUE TITLE
✨ Feat: Fields in Tracim that can be linked to an ldap should not be modified via the tracim interface

### ISSUE THREAD

**Issue by Relf-Algoo** [tracim/tracim#6172]
### Feature description

Frontend : 
Currently, when linking tracim to an ldap, changes in some fields in tracim are still able to be modified by users, although they shouldn't. For exemple, if a user changes his username, There might be a creation in tracim of a new account with the username from the ldap.
This should not be allowed. In order to signify this, all fields in tracim linked to the ldap should be deactivated and greyed in the user interface 

### How it works

Deactive fields in the user interface when they are linked to a ldap

**Comment by Skylsmoi** [comment]
the fix disable the fields display name, username email email when the auth type is not "internal"

**Comment by PhilippeAccorsi** [comment]
I close issue. Fix done in 4.5.1
