### ISSUE TITLE
✨ Feat: command to transform news from a space into threads

### ISSUE THREAD

**Issue by Relf-Algoo** [tracim/tracim#6189]
### Feature description

Some user tend to forget that news are not thread and create news in order to discuss profound / interesting subjects. The problem is that news do not appear in the results of the search tool, so many data can be not easily found.
It is possible to deactivate the news functionnality in each space, however the existing news are then hidden from the interface.

The need is to transform news from a space into threads so that the news functionnality can then be deactivated and the users can use the right tool.

### How it works

I'm sure it would be nice to have it as button in the interface, but as it does not exist right now, a command would be a nice first step.
I don't know if we should have a way to select some news to be transformed, in order not to pollute the threads with uninteresting news. As above, this would be a nice evolution but is not needed at first.

### Related PR

https://github.com/tracim/tracim/pull/6229

**Comment by lebouquetin** [comment]
De philippe (à traduire) : Il faudrait pouvoir transformer toutes les actualités de cet espace en discussion pour pouvoir les traiter correctement (classé) et enlever les actualités de cet espace.

**Comment by lebouquetin** [comment]
Améliorations associées : (à traduire)

Remplacer les actus c'est pas forcément la solution car tu ne sais pas toujours d'avance si tu vas vouloir garder. Une solution intermédiaire est :
- nommer explicitement (j'ai mis dans la liste des améliorations Tracim à venir le fait de pouvoir nommer facilement les actualités)
- pouvoir "transformer" une actu en fil de discussion. Je ne sais pas encore comment appeler ça mais je pense que qqchose comme "déplacer vers la bibliothèque" me semble approprié (j'ai mis dans la liste des améliorations Tracim à venir cette action qui est facile à implémenter)
- permettre de définir une description sur une discussion (comme l'a maquetté Giulia il y a quelques mois)
