### ISSUE TITLE
Renames endpoints tag constants

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#620]
example:
 HTML_DOCUMENT_ENDPOINTS_TAG -> SWAGGER_TAG__HTML_DOCUMENT_ENDPOINTS

do the same for all controllers

**Comment by inkhey** [comment]
done here : https://github.com/tracim/tracim_v2/commit/8c9feae41ed5725ca4dcfba3af90a415f97fae53

**Comment by PhilippeAccorsi** [comment]
Verified.
