### ISSUE TITLE
Local testing environment for SAML authentication

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#6206]
### Feature description

SAML is an authentication mechanism which uses an external provider for identities.
Integrating SAML into Tracim requires to write automated tests which in turn requires a reproducible test environment.

### How it works

- The test environment should be based on [Shibboleth IdP](https://shibboleth.atlassian.net/wiki/spaces/IDP4/overview).
- Take care about metadata and certificates needed for this testing environment
- Add tests including the test environnement

### Related PR

https://github.com/tracim/tracim/pull/6230
https://github.com/tracim/tracim/pull/6232

**Comment by Millefeuille42** [comment]
Got something to work with Shibboleth IdP and a OpenLDAP server, It works but I do not understand *everything*. Currently creating a script to set up the testing environment, since it's not as easy as starting a docker container.

**Comment by Skylsmoi** [comment]
see tools_docker/shibboleth_idp/README.md
