### ISSUE TITLE
Check RemoteAuthentificationPolicy and LDAP authentication behaviors

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#6207]
### Feature description

The global user management mechanism of RemoteAuthenticationPolicy and LDAP are the same: 
  - check if user exists
  - create it if not
  - update its attributes if they are provided by the auth mechanism (only LDAP).

### How it works

This behavior should be the same for SAML authentication, so checking the common behavior could be useful to share this common behavior later on.

**Comment by grignards** [comment]
I think the documentation in `development.ini.sample` is wrong:
> ## Auth type list (internal or ldap), can be a list of item separated by ','
> ## and ordered by priority

But the order of authentication policies in code is independent of the order in `development.ini`.

**Comment by grignards** [comment]
BTW the current Tracim authentication mechanism use policies which have been deprecated in Pyramid 2.0 (they are still available but could be removed in a future version): https://docs.pylonsproject.org/projects/pyramid/en/latest/whatsnew-2.0.html#upgrading-authentication-authorization

**Comment by grignards** [comment]
The SAML auth needs a session but it cannot be implemented in the same way as LDAP since the authentication is not synchronous (the backend cannot do saml.authenticate()…).

**Comment by grignards** [comment]
In fact Tracim authentication have 3 set of properties:
- session or not session
- create user / expects user
- controls the authentication/relies on external authentication

|Type|Session?|User creation?|Control Auth?|
|--|--|--|--|
|internal|yes|no|yes|
|ldap|yes|yes|yes|
|remote|no|yes|no|
|apitoken|no|no|yes|
|querytoken|no|no|yes|
|basic auth|no|no|yes|

**Comment by grignards** [comment]
@Millefeuille42 could you review this issue and my comments?

**Comment by Millefeuille42** [comment]
Seems good to me, this gives valuable information for implementing a new auth.

I think too that the saml auth should use the session mechanism, perhaps by linking a session token to the "auth file" provided by the POST request and sorting out it's validity through a specifically designed mechanism (I don't know if Pyramid has available interfaces for this).

**Comment by grignards** [comment]
Pyramid has a concept of a session which, when enabled, is available in each request. From what I read of pyramid_saml, it makes use of the pyramid's session.
In Tracim the session is implemented with [beaker](beaker.readthedocs.io/).
