### ISSUE TITLE
Feasibility of using Pyramid security policies for SAML authentication

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#6208]
### Feature description

Pyramid 2.0 (which Tracim uses) has deprecated authentication policies in favor of security policies: https://docs.pylonsproject.org/projects/pyramid/en/latest/whatsnew-2.0.html#upgrading-authentication-authorization

But Tracim still uses the "old" mechanism for its authentication policies.

### How it works

Since authentication policies could be removed in a future Pyramid version the SAML authentication should use the new mechanism, but first we have to check whether the new mechanism of security policies is usable with old Tracim policies.

### Related PR

https://github.com/tracim/tracim/pull/6214

**Comment by grignards** [comment]
Tracim currently uses an adapter for authentication policies `TracimSecurityPolicy` and an authentication policy `MultiAuthenticationPolicy` which tries several authentication policies (remote/basic/…, depending on configuration).

It should be possible to use `TracimSecurityPolicy` for each (remote/basic/…) policy instead, this way SAML authentication could be written using a security policy. This way will require to write a `MultiSecurityPolicy` class which will have the same behavior as the existing `MultiAuthenticationPolicy`.

**Comment by grignards** [comment]
Seems that other projects already implemented a `MultiSecurityPolicy`: https://github.com/pypi/warehouse/pull/11218/files#diff-60b1172fcc3ed0f44469ecfff8ba1b5021c2fca3686eb4837522291a722ef624

**Comment by lebouquetin** [comment]
@Millefeuille42 we must keep assignment for issues which have been processed. Code associated to an issue in "To Close" should have been merged. So, there are 2 possibilities:

- you create a new issue "refactor" and associate the branch with this issue (this is the cleaner way to fix the process)
- you re-move the issue in To/Under review and rename it to feasibility + refactor

**Comment by Millefeuille42** [comment]
@lebouquetin done, I created a new issue dedicated to the refactor, see https://github.com/tracim/tracim/issues/6233
