### ISSUE TITLE
✨ Feat: Configuration for mapping SAML attributes to user properties

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#6209]
### Feature description

SAML IdP provide attributes which give information about the logged user. This can include direct mappings like the user's name, its email/… but also indirect mapping, e.g. an attribute with value `staff` will give the Tracim's user a profile of `trusted-user`.

### How it works

It murt be possible to configure Tracim to map SAML attributes to user properties:

- [x] The mapping must be defined by IdP (see #6210)
  - attribute_map in settings_saml2.json
- [x] Tracim will need a new property in `User` to map its internal (Tracim) id with the SAML user id: `external_id`.
- [x] The possible properties must include `email`, `username`, `display_name`, `profile`, `lang` and `external_id`.
  - missing lang 
- [x] It must be possible to combine several SAML attributes to form one user property.
- [x] It must be possible to provide a map of SAML attribute values => user property values for `profile` and `lang`. The map keys (SAML attributes) should be matched with a regex.
  - profile_map for profile
  - lang is NYI
- [x] The configuration must include a way to mark a SAML attributes as required.
  - works natively, must be documented
- [x] When the SAML attributes needed to build a user property is not defined, use the default value for this property
  - Implemented: empty string is set
- [x] If no profile is matched by the saml attributes, the user mustn't be created and the login should fail.
  - For now, user is created with a profile User, which is the lowest profile

For example (INI format is not required):
:warning: Implementation is made on a json file, see comment about settings_saml2.json in this thread
```ini
[ORION_IDP]
# The mapping syntax is tracim_user.<tracim user property> = ${<SAML attribute>}
# SAML attributes can be combined to form a user property (see display_name below).
# Possible tracim user properties are:
# - email: e-mail address of the user
# - username: username (used in mainly for mentions, can only contain [a-zA-Z0-9-_) characters)
# - display_name: The full name of the user
# - external_id: ID from SAML, must be unique
# - lang: two-letter language code (ISO-639-1)
# - profile: profile to set, can be computed from regular expressions on a SAML attribute
tracim_user.email.attribute = ${mail}
tracim_user.username.attribute = ${commonName}
tracim_user.display_name.attribute = ${surName} ${givenName}
tracim_user.external_id.attribute = ${eduPersonUniqueId}

# profile attribute can be computed from a SAML attribute matching a regular expression
# Here the 'users' profile will be defined for SAML users having an 'eduPersonPrimaryAffiliation'
# attribute with either 'student' or 'affiliate' value.
# Possible profiles are 'users', 'trusted-users' and 'administrators'.
# If the configuration matching several profiles the first one in the order of their definition is chosen.
tracim_user.profile.users.attribute = ${eduPersonPrimaryAffiliation}
tracim_user.profile.users.regex = ^(student|affiliate)$

tracim_user.profile.trusted-users.attribute = ${eduPersonPrimaryAffiliation}
tracim_user.profile.trusted-users.regex = ^staff$
```
the `${}` allows to interpolate SAML attributes to combine them (like for `display_name`). Again this syntax is only an example.

Then, when a user logs in with SAML, Tracim should create/update its internal user's attributes by using this configuration.

### Related PR

https://github.com/tracim/tracim/pull/6234
https://github.com/tracim/tracim/pull/6232

**Comment by lebouquetin** [comment]
@Millefeuille42 you are currently working on making IdP configurable, aren't you?

The mapping is potentially distinct for each IdP?

I suggest we put all SAML / shibbolet related stuff in a distinct `.ini` (or `.json`) file in order to be able keep tracim config file "not to complex". My suggestion is we have a parameter in tracim config file which points to the saml related config file

**Comment by Millefeuille42** [comment]
@lebouquetin I am indeed working on this atm, I'm planning to permit a separate configuration per IdP (otherwise it gives huge limitations pretty quickly, and does not costs that much additional workload). The actual implementation is not defined yet, I was thinking about a separate JSON file containing all configs per IdP, or having a config folder with 1 file per IdP (even though a single file might be easier for a standard user idk :/)

**Comment by Millefeuille42** [comment]
I was thinking of something like this (and currently working with this)

```
        "virtual_organization": {
            "https://samltest.id/saml/idp": {
                "common_identifier": "saml_test",
                "logo_url": "url_of_logo",
                "displayed_name": "Test Saml",
                "attribute_map": {
                  "user_id": "${mail}",
                  "email": "${eduPersonUniqueId}",
                  "username": "${commonName}",
                  "display_name": "${surName} ${givenName}"
                }
            },
            "https://idp.ssocircle.com": {
                "common_identifier": "sso_circle",
                "logo_url": "url_of_logo",
                "displayed_name": "Test Saml",
                "attribute_map": {
                  "user_id": "${mail}",
                  "email": "${eduPersonUniqueId}",
                  "username": "${commonName}",
                  "display_name": "${surName} ${givenName}"
                }
            }
        }
```

This blends in pysaml2 configuration making a single JSON file required for all of SAML configuration, the caveat is that I can get pretty big overtime when adding multiple IdPs, but I guess it's enough for now ?

**Comment by Skylsmoi** [comment]
See file backend/settings_saml2.json file for example and naming

currently (2023-11-08): https://github.com/tracim/tracim/blob/feat/6231__implement_saml_authentication_flow/backend/settings_saml2.json

**Comment by Skylsmoi** [comment]
the external_id property is a dedicated branch: feat/6258__add_external_id_field_to_user_accounts
