### ISSUE TITLE
✨ Feat: Configure SAML IdP(s)

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#6210]
### Feature description

SAML authentication uses external services (Identity Providers) to authenticate users.
Tracim should support several IdP and propose a choice to the user so that he can choose his IdP/organism to use for authenticating himself.

### How it works

- [x] Tracim configuration must include a list of IdPs with a title, an optional logo image (url), its `entityID` (url)
  - title: displayed_name ; logo: logo_url ; entityID: clé de l'objet
- [x] When SAML authentication is active and a request not authenticated, Tracim must display the list of configured IdPs in a form which will redirect to the chosen IdP when submitted.
- [x] The displayed list must include custom names and logo of the IdP (integrated in #6231)
  - displays logo_url and displayed_name

Example configuration (INI format not required, but keeps tracim configuration file format, in this case use 

Implemented in a json file. See backend/settings_saml2.json

[configparser](https://docs.python.org/3/library/configparser.html) to do the job):
```ini
# The DEFAULT section can contain default configuration values
# They are overwritten by a specific IdP value if present.
[DEFAULT]
metadata_url = https://mdq.federation.renater.fr/test/entities/%(entity_id)s

# Each section contains an IdP configuration
[ORION_IDP]
# SAML entity id of this IdP
entity_id = https://idp.orion-univ.or
# title which will be displayed in the IdP selection form
title = University of Orion
# logo which will be displayed in the Idp selection form
logo_url = https://orion-univ.or/logo.png

[MARS_IDP]
entity_id = https://mars-univ.ma/idp
title = University of Mars
logo_url = https://mars-univ.ma/logo.png
```

### Related PR

https://github.com/tracim/tracim/pull/6234
https://github.com/tracim/tracim/pull/6232

**Comment by Millefeuille42** [comment]
@grignards 

> Tracim configuration must include a list of IdPs with a title, an optional logo image (url), its entityID (url)

This task seems to be covered (at least partially) in https://github.com/tracim/tracim/pull/6214 unless it's a mistake.
Is it ok that I start working on the implementation of the config and the SAML login mechanism ? (disabling login page + showing the list of IdPs)

**Comment by grignards** [comment]
> @grignards
> 
> > Tracim configuration must include a list of IdPs with a title, an optional logo image (url), its entityID (url)
> 
> This task seems to be covered (at least partially) in #6214 unless it's a mistake. Is it ok that I start working on the implementation of the config and the SAML login mechanism ? (disabling login page + showing the list of IdPs)

Yes, I would propose to first work on integrating the SAML login mechanism within Tracim (with a static configuration) then on the configuration file itself. This way you'll start by the most challenging and uncertain task (externalizing the configuration will take time, but has much less surprise potential).

**Comment by lebouquetin** [comment]
@Millefeuille42 you are currently working on making IdP configurables. Are you planning to keep 1 section per IdP for both UI config (logo url, label, etc) + users mapping?

**Comment by Millefeuille42** [comment]
@lebouquetin I am indeed working on this atm, I'm planning to permit a separate configuration per IdP (otherwise it gives huge limitations pretty quickly). The actual implementation is not defined yet, I was thinking about a separate JSON file containing all configs per IdP, or having a config folder with 1 file per IdP (even though a single file might be easier for a standard user idk :/)

**Comment by lebouquetin** [comment]
Do you plan to allow *both* multiple files *and* multiple IdP in every file? If so, I'm ok with it.

I think the right way to do this is:

- add a saml_config_path parameter in tracim config file
- if path is a folder: 
  - read every json in the folder
- if path is a file:
  - process it as a json file

**Comment by lebouquetin** [comment]
If I misunderstand, let explain it again (or a different way;)

**Comment by Millefeuille42** [comment]
Yeah we could do that, at the moment I am split between having a single file or several files in a folder. For now I am working with a single file, but I can add a folder mechanism as you described !
