### ISSUE TITLE
✨ Feat: Allow SAML Single Logout

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#6211]
### Feature description

SAML Single Logout is a technique which allows to disconnect from an IdP coming from a SP (Tracim here).

To support this logout mechanism Tracim must be able to redirect to the IdP's SLO url when the user clicks on the logout button.

### How it works

- [x] when auth_type is `SAML`, the logout button should be a link to a backend url.
- [x] when this url is reached the backend should redirect to the user's IdP SLO url.
- [x] when a `<LogoutResquest> from the IdP is received, the backend should end its user's session.

### Open questions

- Should this logout method the only one when SAML is used? Or should local logout AND Single Logout coexist?

### Related PR

#6237
https://github.com/tracim/tracim/pull/6232

**Comment by Millefeuille42** [comment]
@lebouquetin

I believe that implementing the described approach may not be the most effective way. Instead, the logout method should be dynamically selected based on the user's login method when they access the logout endpoint.

In this particular scenario, the preferred action is to redirect the user to the Identity Provider's Single Log Out (SLO) page. Moreover, a dedicated route will be created to support the SAML SLO endpoint, ensuring compliance with standards. This route will handle logout requests from the Identity Provider. By combining both mechanisms, it results in no to little additional workload compared to using either approach exclusively, and in fact, it might even reduce the complexity.

This implementation is expected to be straightforward and is well-suited for long-term use, seamlessly integrating into the existing system while leaving room for potential integration of other logout mechanisms in the future.

**Comment by lebouquetin** [comment]
I'm not sure of what you mean. Here is what I understand being the best way to implement logout:

- identify the logout method based on login method (are you able to identify it? how?)
- in case of "classical login" the logout keep being "classical"
- in case of SAML, the logout process is the one described by @grignards in the description (redirect to IdP logout process)

Is this hat you have in mind? @Millefeuille42

**Comment by Millefeuille42** [comment]
Yeah this is somewhat what I was thinking, the changes are all done in backend on the logout route.

Considering that the `auth_typ`e for each user is stored in the DB, we could guess based on that (this or add per session `auth_type` in the user's session data)

![image](https://github.com/tracim/tracim/assets/42064302/655b528a-8907-4a6c-ae7a-0be5e52cbc35)

This would then permit the selection of a logout method depending on the `auth_type`, just like we're already doing for login.

```
        for auth_type in self._config.AUTH_TYPES:
            try:
                return self._authenticate(
                    login=login,
                    password=password,
                    ldap_connector=ldap_connector,
                    auth_type=auth_type,
                    saml_name=saml_name,
                    saml_mail=saml_mail,
                )
            except AuthenticationFailed as exc:
                raise exc
            except WrongAuthTypeForUser:
                pass
```

Here this is the auth mechanism already in place in tracim, we would then just have to mimic this behavior for deauth

**Comment by Millefeuille42** [comment]
After investigation, I have two solution in mind.

The first would be to add a `read_only` field in the `user_configs` table's JSON.
This field will have a boolean value. This value will be set upon creation and will be evaluated when trying to modify the user. 

If the user doing the request is not an admin and the target user is in read-only, block any modification besides the language. 

This `read-only` property could also be evaluated in the frontend to prevent the user from modifying their data (currently the check is only done against the user's authentication type)

The second option is similar in most points, it would add a `read-only` field in the same spot, but this field will instead be a list of user attributes (`username`, `email`...).

Upon modification of the user, if the user doing the request is not an admin, if any of the modified fields are deemed `read-only` the request will be blocked.

In the frontend, the list of `read-only` attributes will be evaluated, and associated UI form fields will be disabled.

---

This logic is made to be evolutive. This will permits to evolve the first solution into the second one quite easily.

The first solution lacks granularity but is faster to implement, and still do not block evolution to the second solution (most of the code will be reused and no DB migration will be required). The second one is completed but slower to implement.

I'll let the decision up to you @lebouquetin

**Comment by lebouquetin** [comment]
We are waiting the client answer in order to decide if this is enough

**Comment by Skylsmoi** [comment]
TODO: @lebouquetin validate solution related to this issue

**Comment by lebouquetin** [comment]
The simple logout PR is enough - https://github.com/tracim/tracim/pull/6237 so we can consider this bug ok
