### ISSUE TITLE
📝 Doc: Document SAML authentication configuration

### ISSUE THREAD

**Issue by grignards** [tracim/tracim#6212]
### Which file(s) on Tracim is affected?

backend doc

### Which part(s) of the file would you like to see updated?

SAML authentication support comes with new configuration possibilities which should be properly documented:

- [x] #6210 
- [x] #6209 

Also, a developer documentation should be integrated, even if not properly designed. For example, schemas like  the one in #6231 is interesting to be integrated.

Documentation ust be available in:

- [x] `development.ini.sample`
- [x] `doc/backend/setting.md`

3 things bellow are left to be done. They will be implemented in another issue, see comments
- #6206
- add doc
  - `doc/TESTING.md`
  - `/tools_docker/test_docker/README.md`

### Related PR

https://github.com/tracim/tracim/pull/6234
https://github.com/tracim/tracim/pull/6232

**Comment by lebouquetin** [comment]
I moved back the issue to TODO in order @Skylsmoi test to deploy the service and validate/invalidate the documentation

The expected process is:
- @Skylsmoi tries to install/configure
- @Millefeuille42 is available for help (but no intervention)
- @Skylsmoi updates the documentation according to what @Millefeuille42 says.

**Comment by Millefeuille42** [comment]
Documentation can be found in `doc/backend/setting.md` from line 169

**Comment by Skylsmoi** [comment]
PR for improving doc: https://github.com/tracim/tracim/pull/6260

Note that documentation about tests isn't made yet
