### ISSUE TITLE
✨ Feat: Transform publication into content

### ISSUE THREAD

**Issue by floreal15** [tracim/tracim#6228]
### Feature description

Enable the possibility to transform a publication into a content

### How it works

-On the dropdown menu of publication an option the change into content will appear
-Using this option will send a validation pop up 
-If validate the publication will be transformed into a content in the same workspace and at the root folder

use the new end point : PUT "api/workspaces/{workspace_id}/threads/{content_id}/namespace" to change the namespace

### Related PR

https://github.com/tracim/tracim/pull/6229

**Comment by floreal15** [comment]
to do for the PR : 
- [ ] change api end point to be the same as the one from televersement 
- [ ] add in the popup the new title of the content or/and the new place wanted
- [ ] fix the bug in the general rencent activities where the icon became the one of publication again

**Comment by Skylsmoi** [comment]
related https://github.com/tracim/tracim/issues/6189

**Comment by lebouquetin** [comment]
@floreal15 the description of this issue shows this:

```
Related PR

No response
```

This is wrong. It's important to keep information up-to-date. Could you link the PR there?

**Comment by Skylsmoi** [comment]
that's because this issue is a duplicate, the original one is https://github.com/tracim/tracim/issues/6189
