### ISSUE TITLE
🐛 Bug: Implement encryption on shibbolet/saml test server

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#6246]
### Tracim version

4.6.2

### Issue description

Currently : SAML/shibb communication is plain
Expected: activate encryption (and make it work)

### How to reproduce

go to terminal and check config

### Related PR

https://github.com/tracim/tracim/pull/6232

**Comment by Skylsmoi** [comment]
TODO: move issue to 4.7.x

also, need validation from client

**Comment by Skylsmoi** [comment]
we made the encryption works with an IDP.

We are testing with another one. Waiting for response

**Comment by Skylsmoi** [comment]
no further implementation required.
Can close the issue
