### ISSUE TITLE
🐛 Bug: associate user type (shibb property) to tracim user profile

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#6248]
### Tracim version

4.6.2

### Issue description

Expected: 
- define the mapping between saml property about user type (student, researcher, etc) with tracim profil (super admin, trusted user, user)
- test it

### How to reproduce

test on branchdev

### Related PR

https://github.com/tracim/tracim/pull/6253
https://github.com/tracim/tracim/pull/6232

https://github.com/tracim/tracim/pull/6302

**Comment by Skylsmoi** [comment]
not mandatory for 4.7.0

**Comment by Skylsmoi** [comment]
- [x] move to 4.7.x

require validation from client

**Comment by Millefeuille42** [comment]
We should not create a profile for users that don't match any pattern. Currently we are attributing the lowest profile grade instead.

This is in standby for the moment.

**Comment by lebouquetin** [comment]
@Millefeuille42 is it difficult to fix? If it's easy, I'd like to be able to have it for 4.7.1
