### ISSUE TITLE
Tracimv2 - App Thread - CSS fix 

### ISSUE THREAD

**Issue by AlexiCauvin** [tracim/tracim#625]
CSS fix on App Thread and it's CreationPopup

**Comment by PhilippeAccorsi** [comment]
@AlexiCauvin tu te rappel a quoi sa correspond exactement?

**Comment by AlexiCauvin** [comment]
@PhilippeAccorsi Hum, c'était après que @Skylsmoi ai branché le react, il y avait des problèmes de CSS à régler

**Comment by PhilippeAccorsi** [comment]
Ok je clos.
