### ISSUE TITLE
✨ Feat: Add an external_id field to user accounts

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#6258]
### Feature description

Currently:

When using a remote auth mechanism (HTTP_AUTH, LDAP or SAML), we need to map internal username or email address with remote field.

- this is the only way we can provision new accounts on the fly.
- this may result in duplicated user account if the remote username or email address change
- our username constraints may be different from remote ones, and in this case we can't map user accounts with efficiency

Expected:

**AT LEAST FOR SAML AUTHENTICATION** 

- Add an `external_id` free string field associated to tracim user account. This field should be varchar (1024) in order to allow virtually any id - we don't know the rules of remote user management system.
- fill this field with remote value (use the mapping mechanism for this, the one used for email, display_name, etc)
- when auto-provisionning an account for a given username or email address, check if the user is already existing (with this external_id):
  - if not -> create the new account
  - if the external_id already exist -> update the account with all new values (display_name, username, email_address)

bonus:
- add a documentation with a SQL query allowing sysadmin to identify the case where an external_id appears several times in the database (do not force uniqueness for now, but allow to identify a potential problem

Extra-work:

- create an issue for integration of the external_id in the APIs + admin screens
- create an issue in order to share the mechanism with LDAP & REMOTE HTTP authentication protocols

Fixes:

- [x] Remove obsolete TODOs
- [x] Change display_name to public_name
- [x] Change user_id to username

### How it works

The explanation seems enough for me

### Related PR
https://github.com/tracim/tracim/pull/6232
https://github.com/tracim/tracim/pull/6259

**Comment by lebouquetin** [comment]
@Millefeuille42 there are some explanation about external_id here: https://github.com/tracim/tracim/issues/6209 . Can you check the cases of what is implemented and what is not ? It looks like you missed some fields like external_id, lang, (see: The possible properties must include email, username, display_name, profile, lang and external_id.)

**Comment by lebouquetin** [comment]
@Millefeuille42 you told me there is a downgrade issue with the current state of development. Could you give the error traceback here?

**Comment by Millefeuille42** [comment]
@lebouquetin here is the traceback from the CI

```
self = <alembic.operations.batch.ApplyBatchImpl object at 0x7fd820492d90>, const = UniqueConstraint()


    def drop_constraint(self, const):

        if not const.name:

            raise ValueError("Constraint must have a name")

        try:

            if const.name in self.col_named_constraints:

                col, const = self.col_named_constraints.pop(const.name)

    

                for col_const in list(self.columns[col.name].constraints):

                    if col_const.name == const.name:

                        self.columns[col.name].constraints.remove(col_const)

            else:

                const = self.named_constraints.pop(const.name)

        except KeyError:

            if _is_type_bound(const):

                # type-bound constraints are only included in the new

                # table via their type object in any case, so ignore the

                # drop_constraint() that comes here via the

                # Operations.implementation_for(alter_column)

                return

>           raise ValueError("No such constraint: '%s'" % const.name)

E           ValueError: No such constraint: 'uq__users__external_id'

```

**Comment by lebouquetin** [comment]
Did you run the test on your own? Do you know how to do it?

**Comment by Millefeuille42** [comment]
I did not. But I know how to do it. For now in order to test quickly I am just upgrading and downgrading to trigger the downgrading function.

**Comment by lebouquetin** [comment]
@Millefeuille42 the model does not explicitly says the column is unique:

`    external_id = Column(Unicode(MAX_PUBLIC_NAME_LENGTH), nullable=True)`

Maybe it's the reason for this:

- when upgrading an existing model, the inex is created
- when creating from scratch, the model is created without the uniqueness (and no associated index)

**Comment by lebouquetin** [comment]
If you upgrade/downgrade, migrations are symetric. But if you create the model from scratch, then downgrade, it's not

**Comment by lebouquetin** [comment]
> As well as setting a default value for existing rows

I do not like this as it may conflict with real external id: external id could be an integer. Why do you want to put a default value? Is it in order to ensure unicity?

**Comment by Millefeuille42** [comment]
@lebouquetin Is it because we have to make it unique. And unique columns can't have null value do they ?

**Comment by Millefeuille42** [comment]
This must be fixed later
https://github.com/tracim/tracim/issues/6266

**Comment by Millefeuille42** [comment]
Since the first client that requested SAML auth could not guarentee that the username will fit our username policy, We added a piece of code that will process and format the username to fit the policy.
