### ISSUE TITLE
🐛 Bug: deleted workspaces appear in the list

### ISSUE THREAD

**Issue by Millefeuille42** [tracim/tracim#6271]
### Tracim version

v4.7.0__build_119

### Issue description

Deleted workspaces appear in the workspaces list.

### How to reproduce

Anywhere on tracim, deleted workspaces are visible.

### Related PR

#6274

**Comment by floreal15** [comment]
to fix, use a _roles property with get_roles(include_workspace_deleted) function in the backend core, with will be called from the controller

**Comment by lebouquetin** [comment]
@floreal15 please renae `include_workspace_deleted` to `with_deleted_workspaces`

**Comment by floreal15** [comment]
Actually, the development of this function is useless because user already have a function get_active_roles and we just need to use it for the fix.

**Comment by Millefeuille42** [comment]
tested on branch
