### ISSUE TITLE
Tracimv2- Account - Fix content Account 

### ISSUE THREAD

**Issue by AlexiCauvin** [tracim/tracim#628]
Fix content Account  : 

- No description on "Mon Profil" ,"Mot de passe", "Espace de travail & Notifications", "Fuseau Horaire" and "Calendrier Personnel" => add one or remove NYI
- No content on "Espace de Travail & Notifications"  =>  add content
- No content on Timezone => add the timezone
- No url on "Calendrier Personnel" => add one

Need to add content in DB

**Comment by AlexiCauvin** [comment]
when the user click on "Espace de travail & Notifications" a blank page appear

**Comment by PhilippeAccorsi** [comment]
Closed. Issue outdated.
