### ISSUE TITLE
🐛 Bug: deactivated members are listed on the 'add a member' section of the workspace dashboard

### ISSUE THREAD

**Issue by Millefeuille42** [tracim/tracim#6289]
### Tracim version

v4.7.0__build_119

### Issue description

deactivated members are listed on the 'add a member' section of the workspace dashboard

### How to reproduce

No response

### Related PR

#6290

**Comment by Skylsmoi** [comment]
closing this issue since deactivated users are not listed and known members, when logged used is trusted user or more, are from every users
