### ISSUE TITLE
✨ Feat: sort space in the side bar and contents in content list without considering emojis

### ISSUE THREAD

**Issue by floreal15** [tracim/tracim#6357]
### Feature description

The sidebar with the workspace should be sorted by alphabetical order without considering the emojis. Considering how the fix is made (by modifying the 'byLabel' sorting), content sorting is also affected.

Since the sort algorithm is global, it'll also affect contents sort in the content list. Which is good.

### How it works

the sidebar should be sorted by alphabetical order without the emojis but will still display them for the user, only the order got to change

See: https://stackoverflow.com/questions/28023682/how-do-i-remove-emoji-characters-from-a-string

### Related PR

#6391

**Comment by Skylsmoi** [comment]
Indeed, I think it will impact the sort of contents too. I missed that.
I agree that it's not an issue and might even be beneficial as long as it is documented

**Comment by Millefeuille42** [comment]
Updated title and desc to fit the actual changes
