### ISSUE TITLE
✨ Feat: Allows more email notification summary period choice

### ISSUE THREAD

**Issue by floreal15** [tracim/tracim#6359]
### Feature description

Allows the user to choose more period for the email summary notification,
- every hour
- every day (already implemented) 
- every week

### How it works

Create 2 more cron to send email summary every hour and another one for every week.
Add frontend interface to choose between each setup.
Can improve responsiveness of the form to setup email notification

### Back
- [x] remove tracimcli parameter --since
- [x] create new parameter email_notification_type in tracimcli with 3 possible values: hourly, daily, weekly
- [x] create 3 new EmailNotificationType hourly, daily, weekly and remove summary
- [x] update the files related to cron jobs in docker `cron_task_tracim_send_summary_mails` and `send_summary_mails.sh.sample`
- [x] create a migration or a script to update every users in existing db to switch from SUMMARY to DAILY
- [x] change period.py::take_app_action variable created_after to depend on user.email_notif_type
- [x] update summary mail html content to make timing dynamic (the "24h")

### Front
- [x] update const EMAIL_NOTIFICATION_TYPE (helper.js) with new options
- [x] update form to show a drop down (EmailNotificationTypeButton.jsx)
- [x] improve responsivness
- [x] update api endpoint if required (might not be)
- [x] update content of helper popin
- ~~[ ] (optional) increase width of popin helper. No props available, might require override~~ Wont because text in popin will be reduced

### Possible improvement  📖 👀
Create config variable with cron timing definition.
So that there will be env var with these info and we'll be able to recreate the cron config with docker without needing manual intervention during server upgrade.

### Related PR

https://github.com/tracim/tracim/pull/6429

## Breaking change 💥
api of tracimcli will change
- removed argument `--since`
- new argument `--email_notification_type`
  - possible values: `HOURLY`, `DAILY`, `WEEKLY`

## Tracim upgrade info
- file `tools_docker/Debian_Uwsgi/send_summary_mails.sh.sample` has been modified. You need to update your `send_summary_mails.sh` manually
- file `summary_body_html.mak` now uses a new variable `email_notification_type_string`. If your banding overrides it, you need to update your mail template

**Comment by Skylsmoi** [comment]
To update DB, you need to update the contraint emailnotificationtype on table user_workspace.
SQLite doesn't allow to update constraint.

Current script:
```sql
CREATE TABLE user_workspace_bu (
  user_id INTEGER NOT NULL, 
  workspace_id INTEGER NOT NULL, 
  role INTEGER NOT NULL, 
  email_notification_type VARCHAR(10) DEFAULT 'SUMMARY' NOT NULL, 
  CONSTRAINT pk_user_workspace PRIMARY KEY (user_id, workspace_id), 
  CONSTRAINT fk_user_workspace_user_id_users FOREIGN KEY(user_id) REFERENCES users (user_id), 
  CONSTRAINT fk_user_workspace_workspace_id_workspaces FOREIGN KEY(workspace_id) REFERENCES workspaces (workspace_id), 
  CONSTRAINT emailnotificationtype CHECK (email_notification_type IN ('INDIVIDUAL', 'NONE', 'SUMMARY'))
);

INSERT INTO user_workspace_bu SELECT * FROM user_workspace;

DROP TABLE user_workspace;

CREATE TABLE user_workspace (
  user_id INTEGER NOT NULL, 
  workspace_id INTEGER NOT NULL, 
  role INTEGER NOT NULL, 
  email_notification_type VARCHAR(10) DEFAULT 'DAILY' NOT NULL, 
  CONSTRAINT pk_user_workspace PRIMARY KEY (user_id, workspace_id), 
  CONSTRAINT fk_user_workspace_user_id_users FOREIGN KEY(user_id) REFERENCES users (user_id), 
  CONSTRAINT fk_user_workspace_workspace_id_workspaces FOREIGN KEY(workspace_id) REFERENCES workspaces (workspace_id), 
  CONSTRAINT emailnotificationtype CHECK (email_notification_type IN ('INDIVIDUAL', 'HOURLY', 'DAILY', 'HOURLY', 'NONE'))
);

INSERT INTO user_workspace SELECT
  user_id,
  workspace_id,
  role,
  CASE
    WHEN email_notification_type = 'SUMMARY' THEN 'DAILY'
    ELSE email_notification_type
  END AS email_notification_type
FROM user_workspace_bu;

DROP TABLE user_workspace_bu;
```

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi can we rename `user_workspace_bu` to something more explicit ?

ex: `user_workspace_migration_process` or `user_workspace_sqlite_migration`

Just to make sure if something not work correctly, we can seen quickly if something wrong in the database.

**Comment by Skylsmoi** [comment]
sure, I edit my comment

**Comment by Skylsmoi** [comment]
Current helper text for summary timing:

### Individual

One mail will be sent for each event of the space.
Use this setting for spaces where you need to be kept informed of everything that happens.
Be careful: this might result in a lot of e-mails. We advise you to pair this feature with filters and/or folders in your mailbox.

### Weekly

Todo

### Daily 

One mail will be sent every 24 hours with a daily digest of all actions in this space.
No matter how many spaces are set to 'Daily', only one mail will be sent. This daily mail will include all notifications (including mentions) you haven't read in the last 24h for each space set to 'Daily'.

### Hourly

Todo

### None

No notification for this space will be sent by mail. You will have to rely solely on Tracim's notifications wall.

**Comment by Skylsmoi** [comment]
@lebouquetin You can update the existing text and set the new ones

**Comment by lebouquetin** [comment]
@Skylsmoi here are the versions. Keep the space separators and the formated (italic, bold) parts.

**Individual**

You will receive an email for each event.

Use this setting when you need to be informed of *everything that happens*.

Warning: this might result in a lot of e-mails.

**Weekly**

You'll *receive a weekly e-mail* summarizing everything you haven't already read.

There will be a single email for all spaces configured as "Weekly".

**Daily**

You'll *receive a daily e-mail* summarizing everything you haven't already read.

There will be a single email for all spaces configured as "Daily".

**None**

You'll receive no e-mail notifications, even if you are mentionned. 

You'll need to rely on recent activities and the notification wall to stay up to date.

**Comment by Skylsmoi** [comment]
@lebouquetin missing "Hourly"
