### ISSUE TITLE
✨ Feat: Save the state of the sidebar

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#6362]
### Feature description

The sidebar state should be save between different tracim tabs and when opening and closing it.

The "state" includes:
- Whether the submenu favorite, task, agenda is opened or closed
- Whether each parent spaces are opened or closed

### How it works

This information can be stored in a cookie or in local storage.

We don't need to save it in db, at least for a first version.

Having it in a cookie or local storage prevent from sharing the config between multiple devices but allows to have different config on different devices which can be useful depending on the screen size

### Related PR

#6371

**Comment by Skylsmoi** [comment]
implemented as description state using a cookie named `sidebarState`

**Comment by Millefeuille42** [comment]
added reference to PR
