### ISSUE TITLE
✨ Feat: Logbooks

### ISSUE THREAD

**Issue by Millefeuille42** [tracim/tracim#6370]
### Feature description

A **logbook** is a type of content that features **logbook entries**. It displays these entries chronogically as a timeline, with an emphasis on the time and the order.

Unlike current tracim timeline, it is more focused on event base logging, and less on discussions.

It should look like that ~~https://jsfiddle.net/zqwp6kLo/1/~~ https://jsfiddle.net/13dptxv5/

![Capture d’écran du 2024-02-26 10-02-38](https://github.com/tracim/tracim/assets/907161/b4f7e032-112b-45d1-9d4d-1647087a42aa)

### How it works

Event management screen identical to kanban card creation screen
use a free field explicitly (as in kanban) and clearly visible
Date field: Date and time

### Related PR

#6378

**Comment by lebouquetin** [comment]
@Skylsmoi @Millefeuille42 I added a screenshot + updated the link to last revision of the jsfiddle

**Comment by Millefeuille42** [comment]
#6378 will bring a first rudimentary version of the logbook.

What is left to do and should be done afterward:
- Write tests
- Fix the design implementation (which is currently hacky and not that good looking)
- Remove unused code
- Readjust code terminology and design to better fit the logbook app (currently, most of the code is unmodified from kanban code)

> Readjust code terminology [...]

by this I mean readjusting minor elements, for example, the date is called "deadline", which is valid for kanbans but not for logbooks.

We should also check what #6363 fixes, since I took the code of the Kanban before these fixes were merged.

**Comment by Millefeuille42** [comment]
Current icon is `fa-newspaper` but it could/should be replace in the future.

A proper candidate would be `fa-sort-numeric-up`

**Comment by Millefeuille42** [comment]
@lebouquetin We changed the icon since it is already used elsewhere in tracim. I also set the color to pink, which is one of the colors that is not close to any other one already used in tracim

<img width="218" alt="image" src="https://github.com/tracim/tracim/assets/42064302/693d5775-2a97-4530-8009-e3145add115a">

Is it ok for you, at least for a v1 ?

**Comment by lebouquetin** [comment]
Color is ok for the v1; I'm not happy with the icon, newspaper is better, I think.

Where is the icon `fa-newspaper` already used in tracim?

**Comment by Millefeuille42** [comment]
How about a book instead ?

**Comment by lebouquetin** [comment]
yes, let's try the book

**Comment by Millefeuille42** [comment]
<img width="300" alt="image" src="https://github.com/tracim/tracim/assets/42064302/6b097b1a-37f1-4f53-9dc8-96e1f10a63a6">
Here is how it looks like with the book
