### ISSUE TITLE
color management for tracim and apps

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#638]
process:
- backend:
  - a JSON file that contains all the colors in hexa:
    - 1 primary color for tracim frontend
    - 1 color for each app
  - ~~on page load, backend insert in index.html a <style> tag that contains (replace #### by it's associated value from the JSON file):~~
    - ~~`.primaryColorFont { color: #### }`~~
    - ~~`.primaryColorBg { background-color: #### }`~~
    - ~~`.primaryColorBorder { border-color: #### }`~~
    - ~~2 classes darken and lighten for each above colors. Theses classes will generate a 15% (parametrable) darken and lighten. Use library to calculate~~
  - ~~endpoint `/api/v2/system/content_type` returns the hexcolor of each apps~~
  

- frontend:
  - tracim_frontend uses the classes generated from backend
  - apps uses the hexcolor they get from tracim_frontend (which tracim_frontend get from api)
    - apps set styles in html attributes `style={{color: config.hexcolor }}` in jsx

**Comment by Skylsmoi** [comment]
snippet I will use for development:
```
<style>
      /* code bellow will be generated by backend */
      .primaryColorFont { color: #985f2c; }
      .primaryColorFont.darken { color: #723906; }
      .primaryColorFont.lighten { color: #be8552; }
      .primaryColorBg { background-color: #985f2c; }
      .primaryColorBg.darken { background-color: #723906; }
      .primaryColorBg.lighten { background-color: #be8552; }
      .primaryColorBorder { border-color: #985f2c; }
      .primaryColorBorder.darken { border-color: #723906; }
      .primaryColorBorder.lighten { border-color: #be8552; }
    </style>
```

**Comment by Skylsmoi** [comment]
process:
- create a color.json that will contains a key "primary_color", "html-document", "thread" ...
  - in root or in backend folder ?
- generate (by backend) a <style> tag in index.html like the exemple above
  - it means having a library able to do a darken and lighten on primary_color
- set endpoint api/system/content_types and api/system/applications to returns in the property "hexcolor" the color from color.json
  - apps will handle their own darken and lighten

**Comment by PhilippeAccorsi** [comment]
Verified.
