### ISSUE TITLE
📝 Doc: Add kanban to development.ini notification filter documentation

### ISSUE THREAD

**Issue by Millefeuille42** [tracim/tracim#6399]
### Tracim version

v4.8.0+build_125

### Issue description

Kanban in not featured in the list of notification filter options.

### How to reproduce

It should be as this diff shows: 

```diff
@@ -532,7 +532,7 @@ website.usage_conditions =
# Possible events are in the form ENTITY_TYPE.EVENT_TYPE or ENTITY_TYPE.EVENT_TYPE.CONTENT_TYPE where:
# ENTITY_TYPE  = user_call | user | workspace | content | mention | workspace_member
# EVENT_TYPE   = created | modified | deleted | undeleted
-# CONTENT_TYPE = html-document | file | thread | folder | comment | logbook
+# CONTENT_TYPE = html-document | file | thread | folder | comment | kanban | logbook
```

### Related PR

https://github.com/tracim/tracim/pull/6512

**Comment by lebouquetin** [comment]
@Millefeuille42 could you explain why you closed this issue? I'm not sure and there is no explicit comment about the WHY.

One point is, the history tells there is a reference in the PR #6394 but there are no findable reference

**Comment by Millefeuille42** [comment]
Mixed up this issue with another one about logbooks, my bad
