### ISSUE TITLE
🐛 Bug: When receiving a call, the sound effect is present but the popin is not

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#6402]
### Tracim version

4.8.0

### Issue description

When receiving a call, sometimes, we can hear the music but the popin to open the call doesn't appear.
It makes users unable to answer the call.

A workaround is to refresh the page.

### How to reproduce

We currently don't have a clear reproduction way.

It appears that the issue might be related to browser tabs running tracim that have been active for a long time.

Waking a session up from a sleep state appears to help reproducing the issue.

### Related PR

https://github.com/tracim/tracim/pull/6529

**Comment by Skylsmoi** [comment]
issue already created since version 4.3.1 here: https://github.com/tracim/tracim/issues/5821

**Comment by lebouquetin** [comment]
@floreal15 actually, I expect from this issue to fix most of the issues related to call sound:

- popin not there but sound here
- sound that can't be stopped
- ...

One of the tasks is to ask @PhilippeAccorsi (and others) about the recurring bugs related to jitsi calls + sound + popin

**Comment by Skylsmoi** [comment]
Issues related to calls found:
- https://github.com/tracim/tracim/issues/5821
- https://github.com/tracim/tracim/issues/5472
- https://github.com/tracim/tracim/issues/5337
- https://github.com/tracim/tracim/issues/5265
- https://github.com/tracim/tracim/issues/5133
- https://github.com/tracim/tracim/issues/5079
- https://github.com/tracim/tracim/issues/5056
- https://github.com/tracim/tracim/issues/5044
- https://github.com/tracim/tracim/issues/5022
- https://github.com/tracim/tracim/issues/4998
- https://github.com/tracim/tracim/issues/4993
- https://github.com/tracim/tracim/issues/4877
- https://github.com/tracim/tracim/issues/4855

**Comment by Skylsmoi** [comment]
Since we are working on the call feature, I would add to move all the call related code to a specific frontend component instead of having everything in tracim.jsx

**Comment by Skylsmoi** [comment]
PR https://github.com/tracim/tracim/pull/6529 moved all the Call related code from Tracim.jsx to a new specific component Call.jsx

The previous implementation, related to the current issue was:
On receive TLM call created
  if user logged is the calee
    setState with information from TLM
    update title
    play audio
Then, the component redraw and displays the popin


The new implementation from the refactor is:
On receive TLM call created
  if user logged is the callee 
    setState with information from TLM
Then, the component redraw, plays the audio and displays the popin


So we won't have desynchronization between audio and popin
