### ISSUE TITLE
Workspace: problem with delete   (create, modify, => ok)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#643]
Some problem with delete:

At present

When we try to delete workspace, the app_workspace_advanced is open and popup also to confirm or not this delete.
If I confirm, the workspace is deleted but the app_workspace_advanced stay open. Its also possible to make modification in this app.

![capture d ecran de 2018-09-11 16-06-49](https://user-images.githubusercontent.com/25848257/45365612-336d4880-b5dd-11e8-89bd-e770c0c0f141.png)

Expected

If I confirm delete, everything about this workspace are close.

**Comment by PhilippeAccorsi** [comment]
if end points exists, set to frontend and assign alexicauvin to make the template

**Comment by inkhey** [comment]
backend part is #611

**Comment by inkhey** [comment]
@PhilippeAccorsi All endpoint but deletion exist in backend, we should decide what's really mean delete if we add such feature.

**Comment by PhilippeAccorsi** [comment]
@lebouquetin Pour le moment il n'y a pas de gestion de suppression ou d'archivage de workspace.

La solution est-elle de supprimer les utilisateurs d'un workspace pour qu'il ne soit plus visible? Dans ce cas, l'admin lui verra tjrs la liste complète des workspace, ou pourrait-il lui aussi ce retirer des utilisateurs du workspace (afin de ne plus voir le workspace dans sa liste).

**Comment by tracim** [comment]
On supprime comme actuellement. Je crois que ça correspond à un flag «deleted» dans la base

**Comment by tracim** [comment]
On laisse les membres associés ; mais lapi ne devrait plus remonter le workspace dans les réponses

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi I have updated this issue.

**Comment by PhilippeAccorsi** [comment]
Verified.
