### ISSUE TITLE
🐛 Bug: Design of emojis in the title of a content is broken

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#6432]
### Tracim version

4.8.0+build_127

### Issue description

Regression due to the latest build "build_127".

It is relate to the fix of responsive design of the title edition input.

Now, when adding multiple emojis, they stack vertically instead of horizontally.

### How to reproduce

Open a content app
Add multiple emojis to the content (not in the timeline)

### Related PR

https://github.com/tracim/tracim/pull/6433

**Comment by Skylsmoi** [comment]
It appears to not be possible, or at least very complicated, to do what is expected: the title of the content taking as many space available to the right with the emoji space increasing their required spaces to the right.
It also makes it impossible if the the title is long and the content has a lot of emoji.
Solution is to move the emoji list on the list bellow the header, where there is the version and the status

**Comment by lebouquetin** [comment]
@Skylsmoi could you add screenshots before / after of the position - otherwise users (and collaborators) can't understand what is your proposal

**Comment by Skylsmoi** [comment]
Before
![Sélection_028](https://github.com/tracim/tracim/assets/11177014/29874d99-4e13-43db-931f-d331d4dfb87f)

After
![Sélection_029](https://github.com/tracim/tracim/assets/11177014/5c6b9884-9c2c-44b6-bab9-d471efac012c)
