### ISSUE TITLE
🐛 Bug: Summary mail doesn't check the state of email_notification_type

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#6441]
### Tracim version

4.8.0+build_129

### Issue description

The process that sends summary email doesn't check the email_notification_type value.

So, when the process exec, it sends mails for spaces that have email_notification_type in value hourly, daily or weekly whatever the parameter `email_notification_type` from the `tracimcli periodic send-summary-mails` calls

### How to reproduce

have a space1 with email_notification_type to hourly
have a space2 with email_notification_type to daily
create unread notification on both spaces
the summary mail for the hourly config will show notifications from both spaces

### Related PR

https://github.com/tracim/tracim/pull/6442

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi this line can be added in shell script juste before executing tracimcli command:
`echo "Cron task send-summary-email: $1"`
