### ISSUE TITLE
🐛 Bug: Crash on emoji strip if string is undefined

### ISSUE THREAD

**Issue by Millefeuille42** [tracim/tracim#6445]
### Tracim version

v4.8.0+build_129

### Issue description

Crash on emoji strip if string is undefined, not sure of when this could occur, but this occured and got fixed by a refresh.

### How to reproduce

unknown

### Related PR

https://github.com/tracim/tracim/pull/6446

**Comment by Skylsmoi** [comment]
fixed buy https://github.com/tracim/tracim/pull/6446
