### ISSUE TITLE
🐛 Bug: icon for restore and for delete content are identical

### ISSUE THREAD

**Issue by Millefeuille42** [tracim/tracim#6475]
### Tracim version

v4.9.0

### Issue description

In the timeline, icons for delete and restore content are the same.

### Related PR
#6476

**Comment by Millefeuille42** [comment]
Proposition for the icon:

![image](https://github.com/tracim/tracim/assets/42064302/51f6a1f8-6705-4b53-9de3-5e0e0675f834)

This development will require us to change the `PromptMessage` component so it can display different icon for message and button. Making it look like this:

![image](https://github.com/tracim/tracim/assets/42064302/26302717-2128-499a-9a3b-9c3da2621dea)

**Comment by lebouquetin** [comment]
> This development will require us to change the PromptMessage component so it can display different icon for message and button. Making it look like this:

I do not understand the relationship between the usage of 2 distinct icons and the refactot of a component which allow to sho message and/or button. Could you explain it @Millefeuille42 ?

Your icon suggestion is good :+1:

**Comment by Millefeuille42** [comment]
@lebouquetin At the moment, a single icon is passed to the component. I added an optional (which defaults to the original icon if empty) icon named `btnIcon` to add the possibility to set a different icon on the button and the text.

I designed it so it supports "legacy" way of using the component. So no change is needed elsewhere

**Comment by lebouquetin** [comment]
Thanks for the explanation @Millefeuille42
