### ISSUE TITLE
User manual: French version

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#648]

**Comment by lebouquetin** [comment]
End-user documentation for using Tracim. What about letting Luc do the job?

**Comment by PhilippeAccorsi** [comment]
Luc work on it.

**Comment by PhilippeAccorsi** [comment]
in progress => https://algoo.trac.im/workspaces/49/folders/7689/pages/7690

**Comment by PhilippeAccorsi** [comment]
in progress:
- version pdf => https://algoo.trac.im/workspaces/49/folders/7689/files/7889
- version markdown => https://algoo.trac.im/workspaces/49/folders/7689/files/7888

**Comment by tracim** [comment]
TODO

- [ ] add webdav and folder documentation @PhilippeAccorsi 
- [ ] read doc and reorganize @lebouquetin

**Comment by Quiwy** [comment]
@PhilippeAccorsi : does this still relevant as we have documentation on [public-community](https://public-community.tracim.fr/ui/workspaces/166/dashboard) ?

ping @Relf-Algoo

**Comment by PhilippeAccorsi** [comment]
I close this issue. Documentation accessible in french directly on your link.
