### ISSUE TITLE
✨ Feat: allow to skip preview for given file types

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#6500]
### Feature description

Currently, tracim tries to preview every file when file app is open.

Some very-heavy text-based files will be previewed through a quite long process, which is useless in some case. For example, BIM-related `.ifc` files.

Expected: allow to skip preview for some files according to a `development.ini` skiplist parameter, something like:

```
preview.ext_skiplist='ifc,iges'
```

This would/should be implemented in `tracim/backend/tracim_backend/applications/content_file/controller.py`:

```
    @hapic.with_api_doc(tags=[SWAGGER_TAG__CONTENT_FILE_ENDPOINTS])
    @check_right(is_reader)
    @check_right(is_file_content)
    @hapic.handle_exception(UnavailablePreview, HTTPStatus.BAD_REQUEST)
    @hapic.handle_exception(PageOfPreviewNotFound, HTTPStatus.BAD_REQUEST)
    @hapic.input_path(FilePathSchema())
    @hapic.input_query(PageQuerySchema())
    @hapic.output_file([])
    def preview_jpg(self, context, request: TracimRequest, hapic_data=None):
        [...]
        content = api.get_one(hapic_data.path.content_id, content_type=ContentTypeSlug.ANY.value)
        if content.file_ext in CONFIG.preview.skiplist:
            raise UnavailablePreview
        [...]
```

### How it works

It would/should simply be a pre-condition that raise error on preview API + management of the given error code in the frontend (this will raise a HTTP 400 with a specific tracim error code)

Another way to implement this is to add a skip list to the app config loaded by frontend and to avoid the query in case the file extension is in the list. It may be better engineered like this.

@Millefeuille42 let's give your feeling about the best implementation on your point of view (I'm ok with both)

### Related PR

https://github.com/tracim/tracim/pull/6517

**Comment by floreal15** [comment]
The frontend use the end point PreviewInfoSchema to know if a preview is available for the file, in order to stop the front from asking the preview, updating the has_jpeg_preview field seems better since it's this field main use
