### ISSUE TITLE
login: use case missing password

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#651]
todo:
- a form in the login page to input the backup email. On another url ?
- something in backend (end point ?) to get the email sent by frontend
- a mail template

**Comment by inkhey** [comment]
backend part done.

**Comment by Skylsmoi** [comment]
@inkhey I got this issue while testing:
```
{"message": "cant reset password with notification disabled", "code": null, "details": {"error_detail": {}}}
```
It seems that when email are deactivated, it returns the error above

**Comment by Skylsmoi** [comment]
@inkhey 
the url to point to in the email is this: /reset_password

**Comment by PhilippeAccorsi** [comment]
Verified.
