### ISSUE TITLE
✨ Feat: Have a possibility to reduce scrolling necessary on logbook with big cards

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#6539]
### Feature description

The exact feature isn't defined yet.
It needs to:
- allow to scroll faster in the logbook entries when there are long cards with many lines
- allow to see enough of the card to be able to identify that it is the card we are looking for
- allow to see most entries completely and only "collapse" the longest ones

It might not be possible to satisfy all of them properly.

Some ideas are:
- a "show more" button on each cards
- two buttons "collapse" all and "expand" always visible
- saving in local storage the state "collapse" or not, for each card or for the entire logbook

### How it works

see feature description

### Related PR

A WIP PR exists: https://github.com/tracim/tracim/pull/6536

https://github.com/tracim/tracim/pull/6553

**Comment by Skylsmoi** [comment]
Current implementation set a max line number to define whether to collapse the card or not.

Here are some examples:

~10 lines displayed
![440px](https://github.com/tracim/tracim/assets/11177014/5425f486-86df-47e3-bc4d-504dc323b740)

~5 lines displayed
![240px](https://github.com/tracim/tracim/assets/11177014/7e153765-b87b-4470-a99e-de02f2afda5a)

0 lines displayed
![0px](https://github.com/tracim/tracim/assets/11177014/abc0aff4-8583-4b7b-8eac-dca931e215b4)

**Comment by floreal15** [comment]
Adding buttons to expand all event and collapse all event description:
![Capture d’écran du 2024-07-09 14-07-09](https://github.com/tracim/tracim/assets/118758647/e7a3f24d-0405-4cf7-a386-fdee6000e0ce)

**Comment by lebouquetin** [comment]
I suggest to make the expand/collapse buttons less visibile in order to keep a hierachy between different actions. Something like `btn-link` class style in bootstrap is ok for those two actions.

When talking about this feature, I expected a unqieu expand/collapse button but having two buttons looks easier to understand, I think.

Cases for showing buttons: when there is something to show/hide (so if there is at lease a large card show the buttons, if not, show nothing)

are my answers clear? @floreal15  (tell me if you need more clarification)

**Comment by floreal15** [comment]
Yes thanks I will do as you ask; no change for the default length of the description preview then ?

**Comment by lebouquetin** [comment]
> no change for the default length of the description preview then ?

No. Let's keep current strategy, we'll see with experience if this is too small.

**Comment by floreal15** [comment]
@lebouquetin 
Is that button ok ? I use the btn-link class in tracim and change the font color to be less visible; should I remove the button background ? Change the text ? Or is it fine as it is ?

![image](https://github.com/tracim/tracim/assets/118758647/d0865517-23cf-45c1-9bb1-aee8e6163a29)

**Comment by floreal15** [comment]
@lebouquetin 
Is that button fine, I use the btn-link class and change the font color the make it less visible; should I change the button, maybe removing the backgroud or change the text ?

![image](https://github.com/tracim/tracim/assets/118758647/5d4c34c7-f480-43df-94ea-aea352c31a0d)

**Comment by floreal15** [comment]
After discussing: there should be no background, a smaller text maybe and the text should just be "Expand all"; the rest can be a title of the element

**Comment by floreal15** [comment]
There is no emoji in the expand all and reduce all button, we have talked about it but no clear answer about if we need one or not was found
