### ISSUE TITLE
✨ Feat: Improve the wording related to web notification

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#6543]
### Feature description

The new feature to disable web notification isn't intuitive.

We need to improve the wording for it to be more user friendly.
It should allow to understand the difference between web notif and email notif.
Also, it should allow to understand that we subscribe/unsubscribe to a space.

~~An idea would also be to add an icon in the sidebar to tell which spaces are unsubscribed (or subscribed)~~ See https://github.com/tracim/tracim/issues/6561

### How it works

This needs to be defined

### Related PR

Commit https://github.com/tracim/tracim/commit/66a1b6f3c25072a43af6df33c3e9dd1e7e980a60

**Comment by Millefeuille42** [comment]
Seems like the wording has been adjusted in https://github.com/tracim/tracim/commit/66a1b6f3c25072a43af6df33c3e9dd1e7e980a60 (commit is not linked to a PR, it was done right before release).
What seems to be left is the icon next to the spaces.

**Comment by Millefeuille42** [comment]
![image](https://github.com/user-attachments/assets/bc16b6af-4cee-4050-8cc0-ec8a8226ced1)
@lebouquetin This is how it could look like

**Comment by lebouquetin** [comment]
> What seems to be left is the icon next to the spaces.

What is the current wordin @Millefeuille42

**Comment by Millefeuille42** [comment]
@lebouquetin 

We use "Notification" and "Email notifications" for respectively Web and Email notifications.
![image](https://github.com/user-attachments/assets/2aa72c35-92cf-4192-997d-4d4e29505000)

It is also made clear in the web notification helper popin that it only affects notifications in the notification wall.

> Activer / Désactiver les notifications pour cet espace.
Si les notifications web sont désactivées, elles n'apparaîtront plus sur votre mur de notifications.
Ce paramètre affecte toutes les notifications sauf les mentions individuel.

**Comment by lebouquetin** [comment]
The design you suggested is ok for me.

- do not forget to add a title to the icon in order to make icon understandable.
- also, I invite you to update the label and description of the issue in order to make clear what will be implemented in association with this issue

**Comment by Millefeuille42** [comment]
Might as well create a new issue dedicated to the Icon and mark this one as resolved by the aforementioned commit

**Comment by Millefeuille42** [comment]
See https://github.com/tracim/tracim/issues/6561
