### ISSUE TITLE
🐛 Bug: No supression and restoration notification in the history of a content

### ISSUE THREAD

**Issue by floreal15** [tracim/tracim#6557]
### Tracim version

4.10.0

### Issue description

when a content is deleted, the history didn't update itself with the tlm to show that the content has been deleted, we need to reload to have it; same with the restoration 

### How to reproduce

1. go to a content 
2. delete it
3. the history didn't display the suppression 

### Related PR

https://github.com/tracim/tracim/pull/6574

**Comment by Skylsmoi** [comment]
https://github.com/tracim/tracim/pull/6574
