### ISSUE TITLE
✨ Feat: add an icon in the space list for spaces with disabled web notifications

### ISSUE THREAD

**Issue by Millefeuille42** [tracim/tracim#6561]
### Feature description

Add an icon in the sidebar to tell which spaces are unsubscribed (or subscribed)

### How it works

When unsubbed from webnotifications of a space, an icon should appear near the space name to inform that the space is "muted"

### Related PR

https://github.com/tracim/tracim/pull/6562

**Comment by Millefeuille42** [comment]
![image](https://github.com/user-attachments/assets/3b2159d6-ca3e-4a04-9cd6-835b628793bf)

**Comment by Millefeuille42** [comment]
![padding](https://github.com/user-attachments/assets/293a3464-9e2a-4354-8009-e88e3d873246)
We should maybe reduce the padding of the three dots, since it takes a lot of space

**Comment by Skylsmoi** [comment]
Since the PR is merged, I move this issue in Done
