### ISSUE TITLE
📝 Doc: Invalid elements in the env settings documentation

### ISSUE THREAD

**Issue by Millefeuille42** [tracim/tracim#6567]
### Which file(s) on Tracim is affected?

doc/backend/env_settings.md

### Which part(s) of the file would you like to see updated?

In the table, some entries, such as `TRACIM__APP_CUSTOM_ACTION__CONFIG_FILE_PATH` are invalid. It is required to fix it using the command.

### Related PR

https://github.com/tracim/tracim/pull/6568

**Comment by Skylsmoi** [comment]
Since the related PR is merged, I move this issue in Done
