### ISSUE TITLE
✨ Feat: Add border to images inserted in notes, comments and other places edited from wysiwyg text editor

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#6614]
### Feature description

Add a light border around images to create a delimitation around them.

### How it works

The border is automatically added during edition and read

### Related PR

https://github.com/tracim/tracim/pull/6616

**Comment by lebouquetin** [comment]
@Skylsmoi I would appreciate you include before / after screenshots in the issue, so that visitors can see the evolution.

**Comment by Skylsmoi** [comment]
Read:
![Sélection_034](https://github.com/user-attachments/assets/682a330e-6a0f-430a-926f-2863fcbcc061)


Write:
![Sélection_035](https://github.com/user-attachments/assets/2c3d0daa-3da2-43cc-83f0-1e2b7b4047cd)

**Comment by lebouquetin** [comment]
As discussed at the moment:

- we should add the border everywhere we edit text and insert images. 
- creating a frontend / react component seems to be the right way to fix this: it will allow a common/standard behavior everywhere a user can edit a content in tracim

Let's share your 3-to-5 alternatives with different border/shadow sizes and color so we can decide together the right values

**Comment by Skylsmoi** [comment]
1) The shadow that already exists on image for files attached to a comment. It has a slight gap to right right and bottom.
![1px 1px 6px 2px](https://github.com/user-attachments/assets/851dc1e9-5c7d-4aa2-97db-4cb397a7ed9b)

2) Visible shadow
![0px 0px 4px 1px](https://github.com/user-attachments/assets/763203a3-a2a6-4977-9bdf-40c7b400d423)

3) Light shadow
![0px 0px 4px -1px](https://github.com/user-attachments/assets/9c8aae03-093d-4b95-8e02-9cac017a0dc7)

4) Very light shadow
![0px 0px 1px 0px](https://github.com/user-attachments/assets/6e31b075-ce3a-4a53-acdc-ca11788b2658)

**Comment by Skylsmoi** [comment]
as discussed, the validated shadow is the existing one on the attached files in comments
