### ISSUE TITLE
✨ Feat: Improve design for pdf export of notes

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#6620]
### Feature description

the notes exported as pdf have design flaws.

**Comment by Skylsmoi** [comment]
Todo:
- better font embeding during pdf generation using weasyprint instead of font on the system

**Comment by Skylsmoi** [comment]
First PR #6625 merged.

Merged without CI backed green because backend CI has issue that will be resolved in another PR.

PDF fixes included in build_148.

Issues to fix related to PDF in build_148:
- [ ] image max width
- [ ] transparent color
- [ ] light grey color on some titles and code block
- [ ] summary numbers > might need to add documentation

**Comment by floreal15** [comment]
I am not sure if removing the possibility to change the size of images is a good thing, even if it prevents some case where the image size was too big for the PDF, it can break the design wanted by the author of the note if he were to use images, and it's not really possible for him to fix that.
