### ISSUE TITLE
Search box is visible in home page (v2)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#668]
At present:

The searchbox is visible in home page when you are not connected.

Expected:

Don't show this search box when you are not connected.

**Comment by lebouquetin** [comment]
the search box will have to be available in not connected context as soon as workspaces can be public

**Comment by PhilippeAccorsi** [comment]
This search box need to search only in public workspace?
This is not the same searchbox  when you are connected?

**Comment by PhilippeAccorsi** [comment]
see #679
