### ISSUE TITLE
Restore breadcrumb in header

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#669]
At present:

In the top of home page => "Dev Tracim - liste des contenus"

Expected:

- Show the breadcrumb corresponding to current screen.

The breadcrumb should be of the form `<workspace name> > <current app> > <extra breadcrumb items>`

Examples:

- Intranet > Agenda
- Intranet > Files
- Intranet > All documents > Documentation générale > Configuration de l'imprimante

- On small screens, breadcrumb must be hidden by default and an icon should allow to view it
- Every item should be clickable.
- If too long, end of breadcrumb should be hidden with "..." in place.
- on mouseover, the full breadcrumb must be shown.

**Comment by PhilippeAccorsi** [comment]
link to #681

**Comment by Skylsmoi** [comment]
The breadcrumbs mechanism is done. 
It doesn't handle folder for now, it'll be a bit more complicated.

We need to define a place to put them properly

**Comment by Skylsmoi** [comment]
missing:
- some plural translations
- extension for type file

**Comment by PhilippeAccorsi** [comment]
The name `Administrer` in this breadcrumbs "Accueil > Administrer >Utilisateurs" is not explicit about where we are. I think we need to find a word more explicit about we are in `Administration` like we have in header button.



"

**Comment by gbonaspetti** [comment]
Changing the "Manage" names for the more explicit word "Administration".

**Comment by PhilippeAccorsi** [comment]
Verified.
