### ISSUE TITLE
view of document Timeline is not intuitive (v2)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#670]
At present:

You can close (don't show) timeline if you click on Timeline title, but its not intuitive to show again timeline.

Exemple when its close:

![capture d ecran de 2018-07-17 16-01-28](https://user-images.githubusercontent.com/25848257/42822281-f0922892-89da-11e8-81cb-440b9e1c9b71.png)

Expected:

We need a direction arrox to know its possible to show timeline again. Or other idea.

**Comment by AlexiCauvin** [comment]
commit https://github.com/tracim/tracim_v2/commit/0e03339cfad6e97da61541bafba24ea72614c3fc

**Comment by PhilippeAccorsi** [comment]
Verified.
