### ISSUE TITLE
read/not read content API

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#671]
Add API endpoint to:
- set content as read/unread
- get last actives contents
- get read_status of contents
related to #641

**Comment by inkhey** [comment]
after merging tracim/tracim_backend#100

- [X] Set read content, set read workspace, set unread content endpoints + simple tests
- [X] recently_updated content endpoint + simple test
- [X] read_status content endpoint + simple test

Bug/To Do:
- [ ] content_ids for read_status endpoint issue: Lists into path params with hapic ?
- [ ] better sql request for read_status.
- [ ] fix issue related to datetime lack of precision in read_status +repair test (remove sleep)
- [ ] Error case tests for theses endpoints

**Comment by PhilippeAccorsi** [comment]
Verified.
