### ISSUE TITLE
Timeline: improve view of Information about version (v2)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#672]
**At present:**

Text information is too close to blue button.

Here with 19" screen:

![capture d ecran de 2018-07-17 16-13-11](https://user-images.githubusercontent.com/25848257/42822966-a5151a9e-89dc-11e8-83a5-ded23cd0f2ce.png)

Here with 24" screen:

![capture d ecran de 2018-07-17 16-19-41](https://user-images.githubusercontent.com/25848257/42823220-4ec7d694-89dd-11e8-96c6-e29c4c61ce61.png)

**Expected:**

Make a bigger space between button and text. Maybe we can have text to right of time line and button on left.

**Comment by lebouquetin** [comment]
@AlexiCauvin when fixing this kind of bug, you must use margin / padding for this kind of fix, not justify and other css3 features.

**Comment by AlexiCauvin** [comment]
Should we only space the button of the text or keep the content on a single line ?

**Comment by AlexiCauvin** [comment]
commit https://github.com/tracim/tracim_v2/commit/0e03339cfad6e97da61541bafba24ea72614c3fc

**Comment by PhilippeAccorsi** [comment]
Verified.
