### ISSUE TITLE
Tmeline: default text in textarea for comment

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#673]
**At present:**

The default text is "Taper votre commentaire ici".

Expected:

"Votre message ..."

Other idea if necessary: "Commentaire...." or "Ecrire un commentaire"

**Comment by AlexiCauvin** [comment]
commit https://github.com/tracim/tracim_v2/commit/0e03339cfad6e97da61541bafba24ea72614c3fc

**Comment by PhilippeAccorsi** [comment]
Verified.
