### ISSUE TITLE
Dashboard: problem with size of "start new thread" (v2)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#674]
At present:

The size of this button is too big, and responsive is not really working.

Expected:

All button have same size or find a better way to show all button.
On 19" screen we have this view:

![capture d ecran de 2018-07-17 17-17-51](https://user-images.githubusercontent.com/25848257/42826735-6f853f36-89e5-11e8-907f-e9509420ab53.png)

**Comment by AlexiCauvin** [comment]
commit https://github.com/tracim/tracim_v2/commit/a6e60fe6601bb42da425177a17d1da4a335e18d9

**Comment by PhilippeAccorsi** [comment]
Verified.
