### ISSUE TITLE
Refresh Problem when you want to disconnect from your account

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#677]
At present:

When you click on "Se déconnecter" the page go to blanck page, just top of home page is visible. You can't see brown page and login popup.

Expected:

When you click on "Se déconnecter" the home page is refresh and you can login again.

**Comment by Skylsmoi** [comment]
@PhilippeAccorsi this issue has been resolved. I wont look for the exact commit since it might has been a little while.

**Comment by PhilippeAccorsi** [comment]
Ok. Thats true.

**Comment by PhilippeAccorsi** [comment]
Verified.
