### ISSUE TITLE
Login page: don't show breadcrumb on top before login successfull

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#681]
At present:

breadcrumb is visible on top of login page.

Expected:

don't show breadcrumb on top before login successfull

**Comment by AlexiCauvin** [comment]
@lebouquetin should we implement this feature in tracim v2.0 ?

**Comment by PhilippeAccorsi** [comment]
@AlexiCauvin  breadcrumb is visible all the time in Tracim V2.0 except on login page.

**Comment by Skylsmoi** [comment]
@lebouquetin we need to talk a about what we exactly need about that. I plan a meeting on the calendar for tomorrow, update it as you will

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi for the moment in login page we don't show breadcrumb.
when you are logged => show #669

**Comment by PhilippeAccorsi** [comment]
Breadcrumb is active in tracim_v2.1

**Comment by Skylsmoi** [comment]
test this issue again when https://github.com/tracim/tracim/issues/669 is closed
I think this issue is outdated

**Comment by PhilippeAccorsi** [comment]
Thats ok for this. No breadcrumbs available in login page.
I close this issue directly.
Verified.
