### ISSUE TITLE
Login page: connexion button alignment problem

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#682]
at present:

The connexion button is in the center of the page.

Expected:

The button is on the right of the page.

**Comment by AlexiCauvin** [comment]
commit https://github.com/tracim/tracim_v2/commit/a6e60fe6601bb42da425177a17d1da4a335e18d9

**Comment by PhilippeAccorsi** [comment]
We really need to have "connexion" button on right of the login box.

Look in Tracim_V1 connexion page.

**Comment by PhilippeAccorsi** [comment]
@AlexiCauvin Après une modification il faut ajouter le label Fix - a tester et le mettre dans la partie du board correspondante. 

La colonne Done, c'est pour les issue qui ont été testé et valider.

**Comment by PhilippeAccorsi** [comment]
verifed.
