### ISSUE TITLE
Login page: fix size of box for login

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#683]
at present:

If we use small screen (19") or big screen (24"), the size of login box change.

Expected:

Fix the size of this box. Smaller is better.

**Comment by PhilippeAccorsi** [comment]
A revalider avec damien

**Comment by PhilippeAccorsi** [comment]
@AlexiCauvin j'ai compris le soucis avec cette fenetre.

Il faut le même fonctionnement et le même aspect que sur la v1. C'est a dire avoir beaucoup moins d'espace entre le bord de la fenetre et les champs à remplir. Là c'est pas très beau sur le V2.

![capture d ecran de 2018-07-27 10-42-20](https://user-images.githubusercontent.com/25848257/43311173-e88ac97c-9189-11e8-92e3-7b1985db1007.png)

**Comment by AlexiCauvin** [comment]
ok, je modifie ça .

**Comment by PhilippeAccorsi** [comment]
Verified.
