### ISSUE TITLE
Workspace: editing : integrate in app

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#686]
édition workspace (dashbord avancé) voir https://algoo.trac.im/workspaces/49/folders/6679/files/6680 ==à intégrer (Alexi)==

**Comment by AlexiCauvin** [comment]
This app is already integrated but is not connected in react. The repository is located at this url : https://github.com/tracim/tracim_frontend_app_workspace_dashboard/tree/develop

**Comment by PhilippeAccorsi** [comment]
@AlexiCauvin Comment je fait pour tester sa?

un git clone de ce repos ne me donne rien .

**Comment by PhilippeAccorsi** [comment]
Related to #746

**Comment by PhilippeAccorsi** [comment]
Verified.
