### ISSUE TITLE
User account: title or element is not all the time in same position

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#687]
**At present**

look in profil, password, timezone, calendar. 
Title moving, sometime is in bold, sometime no title. Sometime ":" is present.

**Expected**

standardize information in different view

**Comment by AlexiCauvin** [comment]
commit https://github.com/tracim/tracim_v2/commit/a6e60fe6601bb42da425177a17d1da4a335e18d9

**Comment by PhilippeAccorsi** [comment]
Verified.
