### ISSUE TITLE
Generic naming of class: 

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#690]
**At present:**

We have some class with naming name are the same. The problem is: if i need to write test or for debug, if I see `error in 'calendar__title'` in account section, by default I'm going to menu Calendar. But this class name is also used in menu timezone.

**Expected:**

The class name need to specify exactly where we are in the DOM.
For generic class names, its impossible to re-use class name from one specific part. 

**Ex: Wrong choice**:
- ~~in calendar => calendar__title~~
- ~~in timezone => calendar__title~~

**Ex: Good choice**: 
- ~~in calendar => calendar__title ; calendar__subtitle ; calendar__text~~
- ~~in timezone => timezone__title ; timezone__subtitle ; timezone__text~~

------------------------------------------------------------------------------------------------------------------
-

List of change needed:
- ~~account > profile: `personaldata__sectiontitle` (and other name in this section )~~
- ~~account > password: `personaldata__sectiontitle` (and other name in this section)~~
- ~~account > timezone: `calendar__title` (and other name in this section )~~
- ~~account > personal calendar: `calendar__title` (and other name in this section)~~

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi @AlexiCauvin Je propose que l'on garde cette issue ouverte all the time. On y ajoutera au fur et a mesure les soucis de nommage (suffit de barrer ce qui est déjà fait).
On ajoute un commentaire pour informer de la mise à jour de la liste du sujet (et on joue avec les label pour le suivi).
Sa vous conviens?

**Comment by AlexiCauvin** [comment]
Check by @AlexiCauvin

**Comment by PhilippeAccorsi** [comment]
Thanks @AlexiCauvin .
