### ISSUE TITLE
user account: don't show personal calendar in menu

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#693]
At present:

In account menu, we can see personnal calendar option.

Expected:

Don't show this option. Calendar appear in V2.1

**Comment by AlexiCauvin** [comment]
commit https://github.com/tracim/tracim_v2/commit/a6e60fe6601bb42da425177a17d1da4a335e18d9

**Comment by PhilippeAccorsi** [comment]
Verified.
