### ISSUE TITLE
Remove the calendar filter from the sidebar 

### ISSUE THREAD

**Issue by AlexiCauvin** [tracim/tracim#694]
Remove the calendar filter from the sidebar. This is not implemented at the moment.

**Comment by inkhey** [comment]
Done in https://github.com/tracim/tracim_v2/pull/9 : https://github.com/tracim/tracim_v2/pull/9/commits/55422eec6858a7e9f993b6ccc36ddea1296f7af9

**Comment by PhilippeAccorsi** [comment]
Verified.
