### ISSUE TITLE
Optimize Tracim Backend SQL requests

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#697]
## Feature description

Some endpoint expectially, read status endpoint are not optimal, we do need to optimize them in order to reduce:
- the time to wait for receiving information
- the number of query (less work on database)

### Previous issue content:

**Currently:**
SQL request used by read_status endpoint, see https://github.com/tracim/tracim/blob/413085f49d1ae5930b6251fb6022fbde8b16a7f6/backend/tracim_backend/lib/core/content.py#L1291
is not optimal.

**Expected:**
Convert this database query in order to be more effective.

## Implementation
- not implemented yet
- see https://github.com/tracim/tracim/issues/697#issuecomment-611929405 for implementation proposal

**Comment by lebouquetin** [comment]
@inkhey this issue is not clear, please complete the description

**Comment by Skylsmoi** [comment]
front related issue: https://github.com/tracim/tracim/issues/1443

If the resolution of this issue is long/complicated, prioritize the frontend one

**Comment by inkhey** [comment]
Some thought about fixing this :
- Try in raw sql first.
- Thing about using CTE query.

**Comment by inkhey** [comment]
#2803 propose many database optimization, that don't directly change specific read_status part, but make read_status and many other query must faster.

**Comment by inkhey** [comment]
About database support : 

Simple table of support of  recursive CTE + Debian and django 3.0 (decembre 2019) support for these database, in order to make decision on which database to retain:

| Database   | Version    | Official Debian support (debian official repos)                                   | Support recursive CTE | official support Django 3\.0 |
|------------|------------|------------------------------------------------------------|-----------------------|------------------------------|
| sqlite     | \>=3\.8\.3  | since Jessie/8                                            | yes                   | yes                         |
| postgresql | \>=9\.4     | since Jessie/8                                            | yes                   | \>=9\.5                      |
| mysql(old) | \>=5\.5     | 5\.5 in Jessie/8, dropped in Stretch/9 in favor of mariadb| no                    | \>=5\.6                      |
| mysql(new) | \>= 8\.0\.1 | No                                                        | yes                   | unclear                     |
| mariadb(old)| \>=10\.0    | Yes                                                      | no                    | \>=1\.1                      |
| mariadb(new)   | \>=10\.2\.2 | since Buster/10                                       | yes                   | yes                         |

EDIT: Mysql 5,7 and 8+ are available in official Ubuntu repositories.

| Database     |  Version |  Specificity                                                       |
|--------------|----------|--------------------------------------------------------------------|
| sqlite       | >=3.8.3  | Limited support for alter table(1)                                 |
| postgresql   | >=9.4    | True Enum type, True sequence type (2)                             |
| mysql(old)   | >=5.5    |  No CTE, No Constraint, Type in alter column, Create automatic index on Foreign Keys (3) |
| mysql(new)   | >=8.0.1  | Constraint migration Issue(4) , Type in alter column, Create automatic index on Foreign Keys (3)                         |
| mariadb(old) | >=10.0   | No CTE, No Constraint, Type in alter column, Create automatic index on Foreign Keys (3)  |
| mariadb(new) | >=10.2.2 | Constraint migration Issue(4), Type in alter column, Create automatic index on Foreign Keys (3)                         |

1. need to use batch operations  : https://github.com/tracim/tracim/blob/41e7671a503ed9fec566f105d0dba85dd0a975ab/backend/doc/migration.md#sqlite-support-of-alter-table-is-limited-use-always-batch_op-

2. need **specific migration code** to handle migration modification of enum:  https://github.com/tracim/tracim/blob/41e7671a503ed9fec566f105d0dba85dd0a975ab/backend/doc/migration.md#postgresql-support-real-enum-type

3. Cannot easily add/remove index in migration, **need specific migration code** (see https://github.com/tracim/tracim/blob/41e7671a503ed9fec566f105d0dba85dd0a975ab/backend/doc/migration.md#mysql-does-already-add-index-to-foreign-keys) + Type needed in alter column (https://github.com/tracim/tracim/blob/41e7671a503ed9fec566f105d0dba85dd0a975ab/backend/doc/migration.md#mysql-require-always-type-to-be-defined-when-altering-column)
4. migration of type with constraint cause some trouble in recent mariadb/mysql version, **need specific migration code** ( see https://github.com/tracim/tracim/blob/41e7671a503ed9fec566f105d0dba85dd0a975ab/backend/doc/migration.md#mysql-require-always-type-to-be-defined-when-altering-column)

**Comment by PhilippeAccorsi** [comment]
Tested and verified on branch. Wait merge to close.

Need to add information in next chnagelog. I dont know what is the good solution for that. If no new version exist before 3.0.0 I think thats ok to just add information in this changelog version.
