### ISSUE TITLE
Backend Plugin mecanism based on hooks and pluggy

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#706]
This issue is now about new plugin hook mecanism allowing to add custom plugin which will use provided hooks.

After discussion with @lebouquetin, we decided to add a plugin mecanism using config parameter allowing to include "tracim_backend_" prefixed module in this dir. All "tracim_backend_" prefixed module are considered as tracim plugin.
Plugin mecanism is based on pluggy hooks mecanism.
Pluggy will load all hook implementation from theses modules.

see https://github.com/tracim/tracim/issues/2555 for pluginify of app.

-----------------
Original message:

> 
>  Todo :
> - [ ] folder organisation https://github.com/tracim/tracim/issues/617
> - [ ] plugin mecanism itself
> 
> Plugin should allow to set many things :
>  - add application to 
>  - add or not workspace menu entry according to workspace and installed apps.
>  - etc...

**Comment by inkhey** [comment]
We should clarify what we want about plugin in Tracim :

We need some kind plugin mecanism to : 
1. add/remove application in tracim in a more easy way.
2. add external code in tracim easily, it's unclear if this code should be app.
3. have an event mecanism. see issue https://github.com/tracim/tracim/issues/1487.

These 3 goal are different, so it may mean different plugin mecanism.
I do think 1 and 2 are similar and may be done with same plugin mecanism whereas 3 is probably too specific. So should be plugin mecanism same for both integrated app and external code add ? Goal are similar and adding external code is almost like adding app.

There multiple approach to add plugin code in python:
- directory based:  we have one directory with plugin and we load them into a module. That how builder mecanism of preview_generator work (https://github.com/algoo/preview-generator/blob/3b2f9024552dcbe616082023a9907e6b07d318bd/preview_generator/preview/builder_factory.py#L86)
-  package based plugin, see https://packaging.python.org/guides/creating-and-discovering-plugins/
- ?

**Comment by inkhey** [comment]
@lebouquetin Did you confirm external code plugin for backend, should be done with a directory based approach ? Should it be same plugin mecanism as application one ?

**Comment by lebouquetin** [comment]
@inkhey your question are good ones. There are two ways we will implement plugin mechanisms in tracim:

- a real plugin mechanism like for applications. The goal of this mechanism is to have a small-core software with modules for all features. This is not the mechanism to implement here
- an `adminsys-ready` mechanism for injecting python code in tracim - this is what I expect you to implement here.

The idea of this mechanism is to allow administrator of a tracim instance to inject specific code easily.

For example, as soon as we have events/signals in our backend, an admin should be interested in implementing some custom callbacks, eg : "when a file statut is put `validated`, then the file is pushed to public folder of a given website". This kind of feature should be easy to implement without to understand how tracim works (the only thing you have to understand is "where to put the code and how to write it").

Example of code:

```python push_validated_file.py

from tracim.event import handler

def publish_file(event, data):
    """publish file on website when status becomes validated"""
    assert event.type == "status_changed"
    if data.type == "file":
        if data.status == "closed-validated":
            exec("cp {} /var/www/files/".format(data.file))

handler.register("on_status_changed",  publish_file)
```

**Comment by PhilippeAccorsi** [comment]
@inkhey documentation is it ready? I not see documentation to use plugin or to generate documentation. Is it normal for 2.5.1 ?

**Comment by inkhey** [comment]
@PhilippeAccorsi 
Documentation generation for plugin (using generate_doc.sh script) was added but is not "production" ready, that's why generation of this one is not documented (to use it effectively, we may need to change script source code). see https://github.com/tracim/tracim/issues/2564 . 

That happened because we decide to push plugin feature with current state of documentation without solving issue related to "how we should properly add sphinx documentation into tracim". 

We can add a micro-documentation about how to use current script.

**Comment by PhilippeAccorsi** [comment]
Can you make a small documentation here ? to know what is necessary to use plugin (path and develoment.ini config).
When its done, we can close this issue (plugin working good).

**Comment by inkhey** [comment]
> Can you make a small documentation here ? to know what is necessary to use plugin (path and develoment.ini config).
> When its done, we can close this issue (plugin working good).

parameter in development.ini is : 
`plugin.folder_path`
It should be an absolute path where administrator put plugins, plugins are python modules (either dir or .py file) beginning with `tracim_backend_` naming convention.

**Comment by inkhey** [comment]
verified
