### ISSUE TITLE
pluged the flash messages

### ISSUE THREAD

**Issue by AlexiCauvin** [tracim/tracim#718]

**Comment by AlexiCauvin** [comment]
it seems to be already pluged. It be verified.

**Comment by PhilippeAccorsi** [comment]
@AlexiCauvin quel test je peux faire pour contrôler sa?

**Comment by Skylsmoi** [comment]
right now, not much.
flash messages are implemented but since error management in still not really implemented, there isn't any of them displayed

**Comment by PhilippeAccorsi** [comment]
ok. So i close this issue and open an other to test all flash message (when error management is implemented).

**Comment by PhilippeAccorsi** [comment]
Verified.
