### ISSUE TITLE
Remove the p tag when publishing a timeline comment via wysiwyg 

### ISSUE THREAD

**Issue by AlexiCauvin** [tracim/tracim#719]
Investigate the fact of being able to remove the p tag when publishing a comment from the timeline and if possible make the modification

**Comment by AlexiCauvin** [comment]
@PhilippeAccorsi  Pour tester : clic-droit sur un commentaire publié par tinyMCE, et regarder si le texte est dans une balise p.

**Comment by PhilippeAccorsi** [comment]
Verified.
