### ISSUE TITLE
Admin: add workspace admin view

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#726]
Exemple here =>https://algoo.trac.im/admin/workspaces

**Comment by AlexiCauvin** [comment]
To access the page put this ur l: 
localhost:8090/admin_temp/workspace

**Comment by PhilippeAccorsi** [comment]
@AlexiCauvin 
Ok.
Do you have finish this page? If not, please save this in work in progress.

**Comment by PhilippeAccorsi** [comment]
- utilité du bouton "Create a workspace" vu qu'il y en a déjà un autre dans la sidebar?
  - le bouton n'est pas fonctionnel
- la ligne marron de séparation est pas très propre: 
    => il faudrait au moins la centrer (mais est-elle utile?)
    => si elle reste, ne pas la coller au bouton

- Remplacer "Users" par "Users nb" (comme sur la v1, sa semble plus explicite).
- Faire disparaître "Calendar"
- voir si "ID" ne serait pas mieux que "# ID" (demander aux autres).
- laisser la page vide ou indiquer dans les lignes que c'est une vue "non contractuelle"
    => n'est-il pas possible de déjà récupérer les nom des workspace de façon automatique?

**Comment by AlexiCauvin** [comment]
- Laisser le bouton "create a workspace"  permet à l'utilisateur de créer un espace de travail alors que la sidebar est fermé.

- La ligne marron n'est pas vraiment utile ce n'est qu'un composant graphique ayant pour but de délimiter la partie haute du contenu de la partie basse
    
- @PhilippeAccorsi Pourrais-tu me fournir un screenshoot de ton écran que je puisse voir l'affichage de la page ? merci

- @Skylsmoi doit effectuer les branchement react de la page pour avoir du contenu dynamique

**Comment by PhilippeAccorsi** [comment]
![capture d ecran de 2018-08-06 16-03-15](https://user-images.githubusercontent.com/25848257/43721170-62e301de-9992-11e8-8a30-d2ade177c26c.png)

**Comment by AlexiCauvin** [comment]
@PhilippeAccorsi pourra tu regarder dans le fichier CSS de la page si cette ligne apparaît, merci.

&__delimiter
    margin 25px auto 65px auto

**Comment by PhilippeAccorsi** [comment]
Aucune des 2 lignes de trouvées.

**Comment by PhilippeAccorsi** [comment]
@AlexiCauvin 
PLEASE: look properly all job needed.

THIS issue is not ready for testing.

**Comment by AlexiCauvin** [comment]
see : https://github.com/tracim/tracim/issues/779

**Comment by AlexiCauvin** [comment]
this issue only takes into account the design and integration of the workspace admin page (for the plug part refer to https://github.com/tracim/tracim/issues/779). The content is therefore not dynamic but is intended to serve as an example. No links and buttons work.

**Comment by PhilippeAccorsi** [comment]
Verified.
