### ISSUE TITLE
workspace: problem refresh status in app (html-doc, file, thread, etc.....) 

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#730]
At present:

When you change status, new version is create but when you close your app, you can't see status changed in all content view. You need to refresh web page.

Expected:

If you change status, when you close your app, the status is automaticaly changed.

**Comment by Skylsmoi** [comment]
@PhilippeAccorsi I can't reproduce. The status is changed when I close the app.
Issue might be outdated, if you can't reproduce either, then it might have been fixed

**Comment by PhilippeAccorsi** [comment]
Ok. 
I close this issue because the bug not exist actually.
