### ISSUE TITLE
Workspace: delete "Create collection of any documents"

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#731]
At present:

We can see this function "Create collection of any documents" in create button. 

Expected:

This function not exist in Tracim. Delete "Create collection of any documents" everywhere in Tracim.

**Comment by AlexiCauvin** [comment]
This function is used to create a folder, we need to change it's text and it's icons.

**Comment by inkhey** [comment]
Need more information about final creation_label value and fa_icon value.

**Comment by PhilippeAccorsi** [comment]
Verified.
