### ISSUE TITLE
Remove subdropdown header from dropdown status

### ISSUE THREAD

**Issue by AlexiCauvin** [tracim/tracim#740]
change this :
![capture2](https://user-images.githubusercontent.com/16293214/43397693-02497344-9406-11e8-8489-2cfa3e0dce7c.PNG)

for this : 
![status-1](https://user-images.githubusercontent.com/16293214/43397733-1f07a8f2-9406-11e8-800e-41abd4cbf6f2.PNG)

**Comment by PhilippeAccorsi** [comment]
Verified.
