### ISSUE TITLE
backend should generate the index.html

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#742]
for now, the index.html that host the react app is handled by frontend. It should be handled by backend so that the backend can generate it with the color classes from the JSON file.

backend must generate the index.html for any route handled by react app.
It must have a <script> tag that get all the apps activated on the instance. Also add the mandatory apps like admin_workspace_user (nyi)
It must includes the appInterface.js and tinymceInit.js.
It also must handle all the colors for frontend and apps.

**Comment by PhilippeAccorsi** [comment]
Verified.
