### ISSUE TITLE
plug dashboard

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#745]
make dashboard get data from api and dynamic display

**Comment by Skylsmoi** [comment]
https://github.com/tracim/tracim_v2/commit/c54e260a612c1e1bf6dc48aba23c014d1a421758

**Comment by Skylsmoi** [comment]
I set this issue for testing even if there are 2 missing features.
@PhilippeAccorsi keep me in touch when you have successfully tested it, I'll modify it for the missing feature (labels and stuff)

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi 

For testing recently activity, I need an another account, no?

missing feature:
- dashboard__calltoaction__button => not connected

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi test ok with two users. Mark as read working.

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi avatar is not plugged in dashboard member list.

**Comment by Skylsmoi** [comment]
@PhilippeAccorsi
- the btns of apps now works
- the btn 'see more' for recent activity now works
- added avatar of members
- reworked the recent activity process: it now displays recent activity regardless of whether it has been read by user or not. The difference is now a bold font for read content

**Comment by PhilippeAccorsi** [comment]
Verified.
