### ISSUE TITLE
plug app advanced dashboard

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#746]
in a feature app to edit workspace.
todo:
- edit title
- edit description
- edit members ROLE + add/remove members (note: add and remove member is also in dashboard)
- __later__: manage calendar, visio conf ...

**Comment by Skylsmoi** [comment]
https://github.com/tracim/tracim_v2/commit/03663b195dce9dbb2358b5b75be39de5e58d8f33

**Comment by PhilippeAccorsi** [comment]
Verified.

**Comment by lebouquetin** [comment]
@Skylsmoi in the advanced app, we should be able to done same as directly in dashboard + advanced stuff. If we can change role but are not able to add/remove users, it's not "advanced app"...
