### ISSUE TITLE
Language: add the user language preferences in a cookie

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#747]
At present:

You can choose the language in Tracim (French), but if you logout then login again, langage is back to english.

Expected:

- save language in Tracim.
- set login page language to the same (based on browser cookie).

**Comment by Skylsmoi** [comment]
this is a backend issue
frontend actually expect API to return the language of the user but, right now, database doesn't save it.

So the frontend always use the default language which is english

**Comment by tracim** [comment]
@Skylsmoi, could you store choosen language in a cookie? This cookie, if existing, should be used for Ui + login screen

**Comment by Skylsmoi** [comment]
mmh that's possible indeed.
I'll do the necessary

**Comment by inkhey** [comment]
Should langage already been save in backend, see https://github.com/tracim/tracim/issues/747 if we use the cookie strategy ?

**Comment by Skylsmoi** [comment]
you just linked to the very same issue

**Comment by inkhey** [comment]
@Skylsmoi you're right, correct issue is https://github.com/tracim/tracim/issues/734

**Comment by Skylsmoi** [comment]
@lebouquetin wouldn't it be better to auto select language for not logged user with their browser preferences ? there is the `navigator.language` variable that returns the code of the active browser language.
If it contains "fr", set Tracim to french. Set to english otherwise

**Comment by lebouquetin** [comment]
@Skylsmoi what I understand is that the backend already stores the user language.

So the algorithm to choose language should be: 

- if user is authenticated:
    - set langage according to value stored in backend
    - when getting language from backend, store it in a cookie
    - if user change language in the UI, save it to backend and update the cookie
2. if user is not authenticated:
   - if the user has the tracim lang cookie, then use it
   - otherwise, use the navigator.language variable

Is it ok for you? the resumé is: priority to value stored in backend, use cookie as a "local cache" also available when user not logged in, use navigator.language as fallback

**Comment by Skylsmoi** [comment]
after discussing with lebouquetin:  
we only use the browser language for default tracim language  

we will implement the cookie version later

see https://github.com/tracim/tracim/issues/1012

**Comment by Skylsmoi** [comment]
see lebouquetin's previous comment for implementation spec

**Comment by Skylsmoi** [comment]
cookie for default language has been added
cookies usage has been refactored with constants

**Comment by Quiwy** [comment]
@Skylsmoi : does this issue still exists?
