### ISSUE TITLE
Translation of tracim v2 components

### ISSUE THREAD

**Issue by ghost** [tracim/tracim#748]
First commit : 
commit https://github.com/tracim/tracim_v2/commit/3c47fa6fe7d1a624987bacb622be635ed9e2f5bc

**At present**

"search__input form-control" => not translate
"dashboard__moreinfo__calendar__information__text genericBtnInfoDashboard__info__text" => not translate
"dashboard__moreinfo__webdav__information__text genericBtnInfoDashboard__info__text" => not translate

~~"card-header connection__header text-center" => not translate~~
~~"connection__form__pwforgot" => not translate~~
~~"connection__form__btnsubmit" => not translate~~
~~Button "Change your status"~~
~~"dashboard__userstatut__role__msg" => not translate~~
~~"dashboard__userstatut__notification__text" => not translate~~
~~"account__title" => note translate
~~"account__userpreference__menu__list__item__link" => not translate (4 lign)~~
~~"#dropdownCreateBtn" => not translate~~
~~"#dropdownMenuButton" => not translate~~
~~"#dropdownMenuButton.extandedaction__button" => "change"~~
~~All title in sidebar => not translate~~

**Expected**

"search__input form-control" => french/english translation
"dashboard__moreinfo__calendar__information__text genericBtnInfoDashboard__info__text" => french/english translation
"dashboard__moreinfo__webdav__information__text genericBtnInfoDashboard__info__text" => french/english translation

~~"card-header connection__header text-center" => french/english translation~~
~~"connection__form__pwforgot" => french/english translation~~
~~"account__title" => french/english translation~~
~~"account__userpreference__menu__list__item__link" => french/english translation (4 lign)~~
~~"#dropdownCreateBtn" => french/english translation~~
~~"#dropdownMenuButton" => french/english translation~~
~~"#dropdownMenuButton.extandedaction__button" => "Modify"~~ 
~~All title in sidebar => french/english translation~~
~~"connection__form__btnsubmit" => french/english translation~~
~~"Button "Change your status" => "Changer de statut"~~
~~"dashboard__userstatut__role__msg" => french/english translation~~
~~"dashboard__userstatut__notification__text" => french/english translation~~

**Comment by PhilippeAccorsi** [comment]
**At present**

"card-header connection__header text-center" => not translate
"connection__form__pwforgot" => not translate
"connection__form__btnsubmit" => not translate
Button "Change your status"
"dashboard__userstatut__role__msg" => not translate
"dashboard__userstatut__notification__text" => not translate
"search__input form-control" => not translate
"dashboard__moreinfo__calendar__information__text genericBtnInfoDashboard__info__text" => not translate
"dashboard__moreinfo__webdav__information__text genericBtnInfoDashboard__info__text" => not translate
"account__title" => note translate
"account__userpreference__menu__list__item__link" => not translate (4 lign)


All title in sidebar => not translate



**Expected**

"card-header connection__header text-center" => french/english translation
"connection__form__pwforgot" => french/english translation
"connection__form__btnsubmit" => french/english translation
Button "Change your status" => "Changer de statut"
"dashboard__userstatut__role__msg" => french/english translation
"dashboard__userstatut__notification__text" => french/english translation
"search__input form-control" => french/english translation
"dashboard__moreinfo__calendar__information__text genericBtnInfoDashboard__info__text" => french/english translation
"dashboard__moreinfo__webdav__information__text genericBtnInfoDashboard__info__text" => french/english translation
"account__title" => french/english translation
"account__userpreference__menu__list__item__link" => french/english translation (4 lign)

All title in sidebar => french/english translation

**Comment by AlexiCauvin** [comment]
@PhilippeAccorsi  "#dropdownMenuButton.extandedaction__button" => "Modify"
Currently the translation is "Change", and this is also correct. Do we still have to change the translation ?

**Comment by PhilippeAccorsi** [comment]
I think change is not too explicit, maybe "Edit" its better. 
This function is to change title? If you write "change", i think user understand "replace by another".

**Comment by AlexiCauvin** [comment]
@Skylsmoi @PhilippeAccorsi 

Some translations do not work: 
- button create content on all content page
- the side menu in the account page
- the status on the apps and the all content page 

The create button and statuses are generated by the backend

**Comment by lebouquetin** [comment]
We discussed this morning: *a priori* @Skylsmoi will manage the translation mechanismin pure frontend - @inkhey wait for the GO before cleaning the API.

**Comment by Quiwy** [comment]
@tracim/algoo  : is this issue still present/relevant ?

**Comment by PhilippeAccorsi** [comment]
I close this issue because this is no more relevant.
