### ISSUE TITLE
Sidebar - Workspace: sidebir closes and opens again on page change

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#755]
At present:

If you show all content and you go to dashboard, the sidebar closing and open again. 

Expected:

No automatic movement in sidebar.

**Comment by Skylsmoi** [comment]
this issue now only happens if switch from account page, admin pages and workspace pages.
The reason is in Routes declaration, if `<Sidebar>` is unmounted an remounted, the animation occurs

**Comment by lebouquetin** [comment]
@Skylsmoi is it easy to fix?

**Comment by Skylsmoi** [comment]
there is the bad fix which is really quick and means removing the animation on the sidebar. Fixes all the issues.
And there is the good fix which will be hard, I dont have any solution right now to handle it

**Comment by Skylsmoi** [comment]
fixed in https://github.com/tracim/tracim_v2/commit/02e433e2d84c13996abe83ad6af834bd61d0df05

**Comment by PhilippeAccorsi** [comment]
Verified.
