### ISSUE TITLE
Alert Message:  if you want create something and you are on "modify"

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#758]
Expected:

**IMPORTANT:** If one app is open on "modify", make pop-up to explain if you create new something (workspace, folder, content, etc....), you are redirect to this feature and you loose your modification.

**Comment by Skylsmoi** [comment]
possible solution:
use the componentWillUnmount to block the unmounting of the app

**Comment by Skylsmoi** [comment]
handle the click on the close btn of an app is easy.
  
handle the click on another content of a workspace is way more complicated

**Comment by lebouquetin** [comment]
Stratégie à suive : 

- webworker + cache local
- ouvrir l'app avec un contenu venant du cache si l'id y est trouvé
- purger le cache au moment du clic sur "valider/sauvegarder"

**Comment by Skylsmoi** [comment]
I assume you are talking about localStorage instead of webworker

**Comment by tracim** [comment]
I assume too.

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi its not working for new html-document if you not have save the first time.

**Comment by PhilippeAccorsi** [comment]
Verified.

FI: if you want to find your modification on localstorage you just need to edit your html-document.
