### ISSUE TITLE
add 'content' to routes that are contents related

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#759]
for react router

**Comment by Skylsmoi** [comment]
For testing:
Check that all urls about workspaces contents contains the word 'contents' in url.
Theses urls are:
- list of all contents of a workspace
- url of an opened content

Info: dashboard should NOT contains the word 'contents' since it is not related to 'contents', only to workspace

**Comment by PhilippeAccorsi** [comment]
Verified.
