### ISSUE TITLE
How "daemon" should be runned in tracimv2 ?

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#762]
In tracimv2, there is uwsgi process but also possibility non-web daemon like email_fetcher.
How should those daemon be runned ?

**Comment by PhilippeAccorsi** [comment]
Maybe used supervisord.

**Comment by lebouquetin** [comment]
@inkhey, some resources for integration with supervisord:

- http://supervisord.org/
- https://blog.nicolargo.com/2013/10/gerer-ces-processusdemons-python-supervisor.html
- https://www.raspberrypi.org/forums/viewtopic.php?t=134332

In development, I think the way to run services is simply to run the processes "by hand"

**Comment by PhilippeAccorsi** [comment]
Verified.
