### ISSUE TITLE
Re-open text content editor after closed it break wysiwyg editor

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#763]
**Describe the bug**
Wysiwyg editor is broken when Re-opening text content editor after closing it.

**To Reproduce**
1. Open a html-document
2. Click on "Modify"
3. Close html-document
4. Open this same document

**Expected behavior**
Wysiwyg editor should not be broke, or html-document should appear like "closed".

**Screenshots**
![selection_007](https://user-images.githubusercontent.com/1104637/43645962-cdbce9cc-9733-11e8-9f09-30709eb1a97a.png)

**Comment by lebouquetin** [comment]
@buxx , do you reproduce?

**Comment by buxx** [comment]
I don't reproduce anymore. I close !
