### ISSUE TITLE
Docker file for tracim

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#77]
Créer des images docker de Tracim:
- Tracim+MySQL
- Tracim+PostgreSQL
- Tracim+SQLite

Ecrire des scénarios Jenkins pour construire ces images et exécuter les tests à l'intérieur. Afin de valider les processus d'install et de tests.

**Comment by buxx** [comment]
Dévs on https://github.com/tracim/tracim/tree/77/dev/beta_1.0/docker.
TODO: Solves entrypoint.sh TODOs.

**Comment by buxx** [comment]
TODO restants:

* Transformer l'image de production en une image qui embarque nginx avec les proxies (radicale, webdav et siteweb) qui vont bien. Le daemon sera un tail (tail -f -n +1 pour commencer au début du fichier) du log uwsgi.

* Créer un dépôt dédié a docker (tracim_docker)

**Comment by tracim** [comment]
@lebouquetin Une réflexion: On as actuellement deux images docker, une pour les tests et une pour la prod/dév. En fait je me demande si il ne vaudrait mieux pas les fusionner pour que notre process de test de déploiement soit plus sûr: si on fait les tests avec l'image de test, on ne teste que l'image de test et pas l'image de dev/prod. Ou on teste les deux.

**Comment by buxx** [comment]
Note: Faire hériter l'image de test de l'image "base/prod", faire un .sh commun dans base/prod qu'utilise l'image de test.

Les noms des images seront (envoyé sur hub docker public):
* tracim:latest
* tracim_tests:latest
