### ISSUE TITLE
Sidebar: problem with size of button to add workspace

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#774]
At present

The button is to big:

![capture d ecran de 2018-08-07 14-25-53](https://user-images.githubusercontent.com/25848257/43775774-211b3958-9a4e-11e8-9de9-2f72d6a11ff1.png)

Expected

Make a smaller button.

**Comment by AlexiCauvin** [comment]
@PhilippeAccorsi This issue will be corrected with the commit of the sidebar fix

**Comment by PhilippeAccorsi** [comment]
Verified.
