### ISSUE TITLE
login_page: change view of login box 

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#778]
**At present**

![capture d ecran de 2018-08-08 11-56-14](https://user-images.githubusercontent.com/25848257/43830677-2a553816-9b02-11e8-8938-bca374356b7f.png)

**Expected**

Position of link like this (just "connexion" button on right)

![capture d ecran de 2018-08-08 11-53-05](https://user-images.githubusercontent.com/25848257/43830584-eb88ae10-9b01-11e8-9bdc-791506a54427.png)

**Comment by AlexiCauvin** [comment]
@PhilippeAccorsi @Skylsmoi  should we add the "Remember me " too ?

**Comment by PhilippeAccorsi** [comment]
I think yes.

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi you say's "remember me" is not develop for Tracim_V2.0, but for an another version of tracim, right?

**Comment by Skylsmoi** [comment]
I did but I might have got wrong
I think we must do it for 2.0

**Comment by PhilippeAccorsi** [comment]
Issue about Remember me => #792

**Comment by PhilippeAccorsi** [comment]
Verified.
