### ISSUE TITLE
Cannot get content from api when it is archived

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#780]
- I have archived a html-document (workspaces/{workspace_id}/contents/{content_id}/archive)
- now I want to get that document (workspaces/{workspace_id}/html-documents/{content_id}) it returns an error 400:
  - {"code": null, "message": "Content \"68\" not found in database", "details": {"error_detail": {}}}
- same issue with workspaces/1/html-documents/68/revisions, error 400:
  - {"code": null, "message": "Content \"68\" not found in database", "details": {"error_detail": {}}}

**Comment by Skylsmoi** [comment]
same issue for Thread

**Comment by PhilippeAccorsi** [comment]
Verified.
