### ISSUE TITLE
Workspace: impossible to create workspace with sidebar button if you are on /admin/workspace_page (

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#783]
**At present:**

If you look /admin/workspace_page, you can't open pop-up to create new workspace.

**Expected:**

Everywhere you see button with option, its possible to use this button.

**Comment by Skylsmoi** [comment]
https://github.com/tracim/tracim_v2/commit/94b08ae413285024a83e9722014f3dd0911027d0

**Comment by Skylsmoi** [comment]
duplicate : https://github.com/tracim/tracim/issues/757

**Comment by PhilippeAccorsi** [comment]
Verified.
