### ISSUE TITLE
Webdav: problem with url to use webdav 

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#784]
At present:

Url is static, and its not the good one.

![capture d ecran de 2018-08-09 10-54-20](https://user-images.githubusercontent.com/25848257/43888724-a51fe9d6-9bc2-11e8-8a90-6dc165ac81db.png)

Expected:

url is from config file (from /backend/development.ini ? )

**Comment by inkhey** [comment]
Backend should probably serve this endpoint with this url (and other stuff ?)

**Comment by PhilippeAccorsi** [comment]
This is done in tracim 2.2

Frontend show value of this parameter `webdav.base_url` and if you use one proxy, the value of this parameter `webdav.root_path` is added at end of url (parameters are in backend/development.ini )

I close this issue.
