### ISSUE TITLE
pull `git pull` command out of `build_full_frontend.sh`

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#785]
Currently : 

If I start ./build_full_frontend.sh, `git pull origin develop` is executed.

Expected : 

the git pull command must be outside of scripts.

**Comment by Skylsmoi** [comment]
We should add a parameter to do the git pull or not

**Comment by PhilippeAccorsi** [comment]
At present you need to git pull manually before used ./build_full_frontend.sh
Its not good to use git pull just for this script because sometime after git pull you need also to run install_frontend and setup_backend.
