### ISSUE TITLE
All content: option "Change" for title about content

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#788]
**At present**

For all content, we have small button "..." with 4 option. One option is to change title of this content but if I choice "Change", nothing append.

![capture d ecran de 2018-08-09 13-01-31](https://user-images.githubusercontent.com/25848257/43898529-69ae1c16-9bdf-11e8-8450-b8224a90dbf7.png)

**Expected**

If I choice "Change" option, its possible to modify title of this content.

Maybe modify also the name of this option from "Change" **to** "Modify"

**Comment by lebouquetin** [comment]
The issue is : the `Modify` button must open the app.

**Comment by PhilippeAccorsi** [comment]
After discuss with @Skylsmoi and @lebouquetin we have choice: edit just open app.

**Comment by PhilippeAccorsi** [comment]
Verified.
