### ISSUE TITLE
sqlite3.InterfaceError

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#79]
`sqlalchemy.exc.InterfaceError
sqlalchemy.exc.InterfaceError: (sqlite3.InterfaceError) Error binding parameter 8 - probably unsupported type. [SQL: 'SELECT content.id AS content_id \nFROM content JOIN content_revisions ON content.id = content_revisions.content_id AND content_revisions.revision_id = (SELECT content_revisions.revision_id AS content_revisions_revision_id \nFROM content_revisions \nWHERE content_revisions.content_id = content.id ORDER BY content_revisions.revision_id DESC\n LIMIT ? OFFSET ?) \nWHERE content_revisions.type IN (?, ?, ?, ?, ?) AND content_revisions.workspace_id IN (?) AND content_revisions.is_deleted = 0 AND content_revisions.is_archived = 0 AND content_revisions.content_id IN (?, ?, ?, ?, ?, ?) AND content_revisions.type != ? ORDER BY content_revisions.updated DESC'] [parameters: (1, 0, 'folder', 'file', 'comment', 'thread', 'page', 1, (1,), (2,), (3,), (4,), (5,), (6,), 'folder')]`

**Comment by buxx** [comment]
Je ne reproduit pas. La pauvreté de l'issue n'aide pas ...
Les tests auto en sqlite fonctionnes. Je clos l'issue

**Comment by tracim** [comment]
"La pauvreté de l'issue n'aide pas ..." => enseignement à tirer pour les prochains rapports de bug (même destinés à soi-même)
