### ISSUE TITLE
Better code to be able to handle dynamically App and content_type

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#791]
Actually, app and content_type are both distinct thing and hard-coded in tracim code, we should adapt code in order to have content-type related to loaded app and to have capability to load app through config. 

If we want to support color management https://github.com/tracim/tracim/issues/638, we need to first read color.json file and then load app with hexcolor automatically setup from theses info.

**Comment by PhilippeAccorsi** [comment]
Verified.
