### ISSUE TITLE
login_page: 'remember me' is missing (not developed)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#792]
At present

Check box "remember me" is not present (not developed)

Expected

Its possible to check "remember me"

**Comment by PhilippeAccorsi** [comment]
See issue #778 for detail about integration.

**Comment by Skylsmoi** [comment]
when checkbox is checked, the login will be keep for 1 year

expect if the cookie is deleted

**Comment by PhilippeAccorsi** [comment]
Verified.
