### ISSUE TITLE
Remove width management from dashboard jsx file and account page 

### ISSUE THREAD

**Issue by AlexiCauvin** [tracim/tracim#794]
remove the width management from the jsx file and manage it in the stylus file

**Comment by AlexiCauvin** [comment]
@PhilippeAccorsi pour le test de cette issue, il faut regarder si la page fait bien 100% de la largeur de l'écran et vérifier dans le fichier jsx qu'il n'y ait pas de "style={{width: 100%}}

**Comment by PhilippeAccorsi** [comment]
Verified.
