### ISSUE TITLE
Fix admin button css on header

### ISSUE THREAD

**Issue by AlexiCauvin** [tracim/tracim#798]
The button is not linked to any css, we need to design it. 

Now : ![image](https://user-images.githubusercontent.com/16293214/44033864-f8fb1016-9f0b-11e8-869e-bd9f40198778.png)

Expected : 

- Add a border
- fix the subdropdown menu

**Comment by PhilippeAccorsi** [comment]
@AlexiCauvin Its ok for this issue.

**Comment by PhilippeAccorsi** [comment]
Verified.
