### ISSUE TITLE
Fix the width of the profil button subdropdown on the header

### ISSUE THREAD

**Issue by AlexiCauvin** [tracim/tracim#799]
Now : 
![image](https://user-images.githubusercontent.com/16293214/44034237-e5d86cd0-9f0c-11e8-9753-dad5cf8f86c3.png)

Expected : 
![image](https://user-images.githubusercontent.com/16293214/44034259-f5df67f0-9f0c-11e8-9622-dfbddd2ca4e3.png)

**Comment by PhilippeAccorsi** [comment]
Verified.
