### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by xylle** [tracim/tracim#80]
Hello,

my server timezone is set to America/Guadeloupe, same for my client.
When i add something, i have 4 hour difference in Activity.
When i comment or modify i have the correct difference time.

**Comment by tracim** [comment]
xylle, do you mean that for the same comment you have different times shown ?

**Comment by xylle** [comment]
No, when i create a document, it's older than 4 hours.

**Comment by tracim** [comment]
I'm not sure to understand.

I may understand two distincts usecase : 

1. files, pages and discussions are created with a wrong time, but comments are created with the right one.

or 

2. times are right on file/page/discussion view but are wrong on activity view (the homepage)

Which one is your case ?

**Comment by xylle** [comment]
En français c'est possible ?
Answer in french good ?

**Comment by tracim** [comment]
Oui :)

**Comment by buxx** [comment]
Ce que je constate c'est que les date de création/modifications sont enregistré sur le serveur avec la date UTC et dont également affichés en UTC. Je vais effectuer les modifications afin d'afficher les dates en fonction de la timezone du client web.

**Comment by buxx** [comment]
Autant pour moi, on ne peut avoir cette information (timezone du client), ce devra donc être une configuration du profil utilisateur.

**Comment by tracim** [comment]
Buxx, le pb n'est pas le décalage entre client et serveur (cf message original où les 2 sont dans la même zone), mais un décalage pris en compte entre création et modification. (genre on s'appuie pas sur la même TZ dans les deux cas)

**Comment by buxx** [comment]
Si je comprend bien dans cette exemple (ou la modification à été faite immédiatement après la création):

![selection_008](https://cloud.githubusercontent.com/assets/1104637/20100831/7e71cc96-a5bf-11e6-8933-671eb95200e1.png)

Il est affiché 1h, ce qui est incorrect. J'ai juste ?
