### ISSUE TITLE
html-document: bug: Its possible to create many document with same title

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#800]
At present

Its possible to create many documents with same title

Expected

Its just possible to create one file for one title. If title is used, inform user about this problem.

**Comment by Skylsmoi** [comment]
I need a endpoint to do a search based on a string (the content name) and a content type

**Comment by inkhey** [comment]
I do think backend should probably handle this case, because 2 content in same folder with same name is not pratical and should probably be unauthorized.

**Comment by PhilippeAccorsi** [comment]
Verified.
