### ISSUE TITLE
Dashbord: bug: margin is too small on left and all white space are not equal size

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#803]
At present

If you look here you can see different space value (white part)

![capture d ecran de 2018-08-13 16-32-21](https://user-images.githubusercontent.com/25848257/44038338-deb82738-9f16-11e8-978d-0e27f451d524.png)

Expected

Make bigger margin in left and make equal space beetween each view.

**Comment by PhilippeAccorsi** [comment]
Find a good solution for margin. maybe make a bigger margin in left and right.

**Comment by AlexiCauvin** [comment]
issue fix with responsive commit : 
https://github.com/tracim/tracim_v2/commit/75fb0208478face1cec2b1b00faec0ddd7fdc3fa

**Comment by PhilippeAccorsi** [comment]
Verified.
