### ISSUE TITLE
Workspace: filter document in backend before frontend

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#806]
At present

All document is sorted by frontend. The backend send content with last modification on end of list.

Expected

By default, the backend filter content by "type" and "title".

Frontend can adjust the result if necessary.

**Comment by PhilippeAccorsi** [comment]
@inkhey when your work is done, please Assign to @Skylsmoi .

**Comment by PhilippeAccorsi** [comment]
@inkhey Add filter in backend to make filter by title directly in alphabetical.
This is not for research function. 

The good view off all content is: filter by type => and for each type filter by title in alphabetical. The filter for title need to be apply directly by backend.

**Comment by Skylsmoi** [comment]
to test:  
just check that content are properly sorted alphabetically

**Comment by PhilippeAccorsi** [comment]
Verified.
