### ISSUE TITLE
Content / Files / Documents view: the title of the screen does not change (always show Content list)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#807]
At present

If you filter page by content (in sidebar), the name of header is all the time the same.

Expected

Adjust title by name of sidebar filter. Ex:

- Text Documents
- Files
- Threads

**Comment by Skylsmoi** [comment]
need translation for backend key

**Comment by Skylsmoi** [comment]
todo: add frontend mecanism for theses translations then add tag "blocked by backend"

**Comment by PhilippeAccorsi** [comment]
Fix today by Skylsmoi.

**Comment by PhilippeAccorsi** [comment]
Verified.
