### ISSUE TITLE
Archive

### ISSUE THREAD

**Issue by xylle** [tracim/tracim#81]
Hello,

i have archived a file, where i find it ?

**Comment by tracim** [comment]
Hello xylle, currently, the only way to find the archived files is going into the database. In the v1.0 beta (expected on next september) you'll be able to find them through webdav.

In the future, it is planned to give access to them through the web interface, but it's not yet implemented

**Comment by xylle** [comment]
Ok, thanks. it's possible to remove the button ?
If the end user see this button, he click on it and whine because he lost the document

**Comment by tracim** [comment]
The buttons are now hidden. This feature will be restored with 1.0 beta (september 2016)
