### ISSUE TITLE
Tiny MCE: Bug with rich text

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#810]
At present

If you want to use rich text, for exemple with paragraph value, we can't change just one line, all line change in same time.

Expected:

Find a good solution to use rich text with tiny mce or with an another tool.

Good link => http://network.ubotstudio.com/forum/index.php/topic/3335-solved-tinymce-iframe-javascript-need-to-fill-it-with-a-blog-post/

**Comment by lebouquetin** [comment]
Fixed and verified.
