### ISSUE TITLE
Button: make sure all button is not visible if member can't show option of this button

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#813]
Expected

Member can only show button about it's own role.

Exemple: if user is just reader, he can't show "create workspace", archive, delete , move, modify, etc.....

**Comment by Skylsmoi** [comment]
little info: I have hidden the btn create workspace in sidebar for basic users in a random commit

**Comment by PhilippeAccorsi** [comment]
info for role reader:
its possible: 
**dashboard**
- click on each app
- click on "add member"

**app file**
- click in "change description" in app file

**Comment by PhilippeAccorsi** [comment]
Better issue for this problem => #959
