### ISSUE TITLE
workspace: bug: create content button

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#818]
## Currently

when you scroll in page all content, you can see option for button create  is going on top of header:

![capture d ecran de 2018-08-14 14-20-23](https://user-images.githubusercontent.com/25848257/44091362-81607fc4-9fcd-11e8-84f9-6f664c26c0ae.png)

## Expected

- menu must have a z-index which make it pass below headbar

**Comment by Skylsmoi** [comment]
It wont with the new layout with separated scrolls

I think this issue can be closed.

I put it in need tests

**Comment by PhilippeAccorsi** [comment]
Thats ok with the new layout.
Thanks.
