### ISSUE TITLE
Alternative content for the home page 

### ISSUE THREAD

**Issue by AlexiCauvin** [tracim/tracim#820]
**At present**

When you are connected to tracim, if you are not member of any workspace you can't see anything (blanck page)
When you are connected to tracim and you are member of some workspace, you see the dashboard of the first workspace.

**Expected**

- If you don't have any workspace, use this page =>  frontend/src/container/home.jsx

- If the user has already created a workspace, it is necessary to display the home page with the following content : 
-le texte : "veuillez sélectionner un workspace présent sur la sidebar en cliquant simplement dessus" par "démarrez en sélectionnant un espace collaboratif dans le menu latéral"
- le logo tracim en pied de "popin" par un message : "bonne journée :)"
- transformer le cadre marron figé par une ombre diffuse (voire rien du tout).

- If user (reader) is not member of any workspace, show specific message about that.

**Comment by lebouquetin** [comment]
@AlexiCauvin did you integrate the screens?

**Comment by AlexiCauvin** [comment]
@lebouquetin I integrated the homepage, not the alternative content

**Comment by AlexiCauvin** [comment]
I have integrated the homepage, the reactjs connection of the page is missing. For alternative content, I need more precision in relation to the method to be used

**Comment by AlexiCauvin** [comment]
Curently we have two prototypes : 

the user can create a workspace : 
![page 1er wks 2](https://user-images.githubusercontent.com/16293214/46022886-c204be00-c0e3-11e8-83fb-752117ba2993.png)

And the user cannot create a workspace : 

![homepage_alternative](https://user-images.githubusercontent.com/16293214/46023359-c1b8f280-c0e4-11e8-9f2c-73a5996e2b61.png)

**Comment by AlexiCauvin** [comment]
@lebouquetin @PhilippeAccorsi 
There is another use case, where the user is already linked to a workspace and the workspace reconnects to tracim, it should fall on this display: 
(these models date from 23/08/2018, to be revalidated for 2.0) 

![accueil-wks-texte](https://user-images.githubusercontent.com/16293214/46065044-5b2de600-c171-11e8-8329-f405a63e9642.png)

ou celui-ci : 

![accueil-wks-btn](https://user-images.githubusercontent.com/16293214/46065061-64b74e00-c171-11e8-9a3f-617f21577193.png)

**Comment by PhilippeAccorsi** [comment]
@AlexiCauvin can you change this => le logo tracim en pied de "popin" par un message : "bonne journée :)"

**Comment by PhilippeAccorsi** [comment]
Verified.
