### ISSUE TITLE
html-document: bug js with tiny mce (test Cypress)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#823]
At present:

When I run test with cypress /functionnal_tests/app_html-document/operation_create_html-document.js  to create new html-document with button accessible in page contents, I have strange bug. The html app open and close sudently after Validate and create.

When test run from dashbord, everything working correctly.

Error I can see:

![capture d ecran de 2018-08-16 16-44-25](https://user-images.githubusercontent.com/25848257/44217153-19c01900-a177-11e8-9713-91d7cfabba69.png)

Expected

Find a solution to make normal test.
Test on my PC.

**Comment by lebouquetin** [comment]
@PhilippeAccorsi @Skylsmoi it looks similar to the issue detected in comments of the following article: https://medium.com/@nickdenardis/getting-cypress-js-to-interact-with-ckeditor-f46eec01132f

By the way, this medium article point to a direction for cypress testing including the use of tinymce.

**Comment by lebouquetin** [comment]
This issue is more generalized through https://github.com/tracim/tracim/issues/844. This is a duplicate
