### ISSUE TITLE
Impossible to access Tracim with another machine

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#825]
**at present**

Its impossible to access to Tracim_v2 from an another machine

Error in tracim.app.entry.js:

~~~
Object.defineProperty(exports, "__esModule", {
  value: true
});
var FETCH_CONFIG = exports.FETCH_CONFIG = {
  headers: {
    'Accept': 'application/json',
    'Content-Type': 'application/json'
  },
  apiUrl: 'http://localhost:6543/api/v2',
  mockApiUrl: 'http://localhost:3001' // @todo: better to use one url only and use proxy on mock api to point to real api (if implemented)
};
~~~

Value 'localhost' is static

**Expected**

It's possible to access from different ip adress.

**Comment by Skylsmoi** [comment]
@PhilippeAccorsi  I have added a fontend/configEnv.js.sample file that holds the apiUrl.
You need to create a configEnv.js file (from the .sample) and change the apiUrl in it.

**Comment by PhilippeAccorsi** [comment]
Verified.

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi you want to make a json.

**Comment by PhilippeAccorsi** [comment]
Verified.
