### ISSUE TITLE
html-document and thread: a reader can fill textarea but he is not allowed to save. textarea should be disabled

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#826]
At present

Reader account can write text in many form. ex: comment thread, comment html-file, etc...

Expected

Its not possible for reader account to write text in form. Reader just can read.

**Comment by Skylsmoi** [comment]
I can't reproduce.
now, a reader see neither the form to add a comment nor the btn edit

**Comment by PhilippeAccorsi** [comment]
Verified.
