### ISSUE TITLE
open content in new tab with shortcut

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#827]
**At present**

Its not really easy to open content in new tab (html-doc, thread, file, folder, etc. )

**Expected**

I can open content in new tab with all keyboard/mouse shortcut:

ctrl + "click"
ctrl + "click mouse wheel"
etc..

**Comment by lebouquetin** [comment]
@Skylsmoi lets discuss about it

**Comment by Skylsmoi** [comment]
duplicated here https://github.com/tracim/tracim/issues/1518

**Comment by lebouquetin** [comment]
note: this issue must be fix for all screens. there is the problem for contents but also for workspaces and users (in admin screens) ; and we should always be able to ctrl+click a link

**Comment by lebouquetin** [comment]
by the way, being able to right click + copy link is also required. @Skylsmoi lets discuss if you do not see how to do this easily

**Comment by Skylsmoi** [comment]
I have found way yesterday that looks promising.
I'll test it further and implement it everywhere

**Comment by Skylsmoi** [comment]
@lebouquetin What do you expect to happen when ctrl+clicking a workspace from admin page ?

**Comment by Skylsmoi** [comment]
a commit and a PR has been added.
It fixes workspace content list + admin user list
It lacks admin workspace list because the change is too big to do it right now

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi its not working for "admin user list", you say yes but in console I can see this message: `ReferenceError: "appAdminWorkspaceUser is not defined"`after ctrl+click on button administration => users

**Comment by Skylsmoi** [comment]
indeed, appInterface.js should be loaded after each and every apps.
I'll do the changes in index.html and index.mak

**Comment by lebouquetin** [comment]
@Skylsmoi you should have a "onDocumentLoaded" or something like this? or its not possible?

**Comment by lebouquetin** [comment]
(I mean, loading external .js file may finished in whatever order, even if the html tags are in the right order)

**Comment by Skylsmoi** [comment]
of course there is
the error philippe is talking about doesn't appear every time.
I'm assuming it's because of an asynchronous issue bu I haven't debugged it yet.

**Comment by Skylsmoi** [comment]
After some tests: the `appAdminWorkspaceUser is not defined` is unrelated to the ctrl+click.

The issue is when we load urls like `http://192.168.1.153:6543/ui/admin/user`, it sometimes fails to load because the appAdminWorkspaceUser seems not yet loaded when the script executes

I have created a specific issue here https://github.com/tracim/tracim/issues/1615

**Comment by Skylsmoi** [comment]
@PhilippeAccorsi If this is the only problem about the resolution of this issue, I think we can close it since it's an unrelated problem

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi Ok.

**Comment by PhilippeAccorsi** [comment]
Verified.
