### ISSUE TITLE
Thread: margin is too big before first comment

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#828]
At present

The margin before first comment is too big

Expected

Have same margin before first comment and last comment.

**Comment by Skylsmoi** [comment]
@AlexiCauvin dont use absolute. Absolute positioning should only be used to make element overlaps each others.
use flex positioning and a position relative for the avatar

**Comment by lebouquetin** [comment]
@Skylsmoi take a look to the html with @AlexiCauvin :

There is something like that:

```
<div>
    <!-- this div is the margin between messages -->
   <img src="avatar">
<div>
<div>
    <!-- this div represents the message -->
    <div><!-- message header --></div>
    <div><!-- message body --></div>
</div>
```

Instead we should have something like this:

```
<div>
    <!-- this div is the margin between messages -->
<div>
<div>
    <!-- this div represents the message -->
    <div>
        <!-- message header -->
        <img src="avatar">
    </div>
    <div><!-- message body --></div>
</div>
```

The avatar related node must be in the div representing the message, not the div representing the margin between messages

**Comment by Skylsmoi** [comment]
I agree with that.
We can even remove the div that handles the margins, and put margins around the div of the message
```
<div><!-- this div represents the message containing the margins -->
    <div><!-- message header -->
        <div><!-- this div will holds the user name and date -->
          <div /><!-- username -->
          <div /><!-- date -->
        </div>
        <img src="avatar">
    </div>
    <div><!-- message body --></div>
</div>
```

**Comment by Skylsmoi** [comment]
I did the refactor, @AlexiCauvin I let you check that it's fine and if it is, put the issue in "need test"

**Comment by PhilippeAccorsi** [comment]
Verified.
