### ISSUE TITLE
How to obtain timezone list for frontend ?

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#833]

**Comment by Skylsmoi** [comment]
I'd say it depends on the list size. If reasonably small, we can save it in js code. If large, backend will save it and returns it through a system end point /api/v2/system/timezone

**Comment by lebouquetin** [comment]
@inkhey @Skylsmoi this is already in v1 code. You should do the same (if done in python => backend + api, if done in js => frontend)

**Comment by PhilippeAccorsi** [comment]
@inkhey this function can be implemented in frontend?
If yes, can you remove "backend" and inform Skylsmoi and put this issue in todo.

**Comment by inkhey** [comment]
@PhilippeAccorsi Technically, that's possible but solution in tracimv1 was in backend, and it need some js code who charge a very long list of timezones.

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi do you have all what you need to connect this in frontend?

**Comment by Skylsmoi** [comment]
Update:
The date saved in database seems ton contains the gmt difference in it.
Js libraries automatically displays date regarding the timezone of the browser that runs it.

So, by only using the date from db, I can automatically display the date in the correct Timezone of the browser.

For that, I use 2 functions:
- `distanceInWords(new Date(), dateFromApi)` from date-fns ([doc](https://date-fns.org/docs/distanceInWords)) for dates like "x minutes ago"
- `(new Date(dateFromApi)).toLocaleString()` from default js date library ([doc](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Date/toLocaleString)) for dates like "26/09/2018 at 15:48:02"

both of them automatically translate themselves

**Comment by Skylsmoi** [comment]
Conclusion, right now, we dont need to format date with the saved user's timezone.

It might an evolution though

**Comment by Skylsmoi** [comment]
Todo:
- remove menu entry to set timezone from myaccount page and admin account

**Comment by PhilippeAccorsi** [comment]
Verified.
