### ISSUE TITLE
How to avoid tricky case who could happen with admin right ?

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#836]
some tricky case possible with admin right:
- remove all role from a workspace -> empty workspace (unusable)
- remove all workspace_manager from workspace -> no more manager.
- remove self role, lower self role in workspace.
- lower self global profile.

...

**Comment by lebouquetin** [comment]
@inkhey

> remove all role from a workspace -> empty workspace (unusable)

Not a problem as soon as the super admin user can add again some roles.

> remove all workspace_manager from workspace -> no more manager.

Not a problem as soon as the super admin user can add again some roles.

> remove self role, lower self role in workspace.

The API should prevent this case: an admin user can't remove himself from being admin.

> lower self global profile.

What do you mean ? Describe an action.

**Comment by inkhey** [comment]
@lebouquetin 

> What do you mean ? Describe an action.

It the same case as remove role but globally. An admin can remove itself admin role of tracim. But if i understood what you are saying both workspace_admin and global_admin should not be able to remove themself admin role.

**Comment by PhilippeAccorsi** [comment]
need to verify if its done in v2.0

This issue is not visible in project.

**Comment by PhilippeAccorsi** [comment]
@inkhey @lebouquetin I don't know why this issue is not in project.

**Comment by tracim** [comment]
we consider this being ok. Let's open a specific issue if some of the problems appear again.
