### ISSUE TITLE
Support for date according to user timezone

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#841]

**Comment by inkhey** [comment]
- All date in database are correctly store in UTC format
- frontend is able to handle properly those date to adapt to user timezone.

-> There is no need to adapt anything.

**Comment by inkhey** [comment]
Frontend should use user timezone if provided instead of system/browser timezone.

**Comment by PhilippeAccorsi** [comment]
@inkhey you have reopened this issue, fronted need to work for this issue?
It is just for information?

This issue is in "Done" list so nobody look here.

**Comment by inkhey** [comment]
@PhilippeAccorsi Yes frontend need to work on this. Frontend need to use user timezone for datetime if provided, actually it use probably default user time of computer or something like that.

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi @inkhey do you know if its fix in v2.0 ?

This issue is not visible in project, I dont know why (maybe because reopen not move issue frome "Done".

**Comment by Skylsmoi** [comment]
@PhilippeAccorsi this is fixed yes

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi thanks.
I close this issue.
