### ISSUE TITLE
Cypress tests including rich text editable widgets not working

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#844]
Currently, it's not possible to test tinymce rich text widgets with cypress. this is because of using iframes.

It looks like there are ways to warkaround this.

You should have a look at the following issue : https://github.com/cypress-io/cypress/issues/136
This is a common problem, and for what we want to do it looks like its possible. Look especially to the following comments : 

- https://github.com/cypress-io/cypress/issues/136#issuecomment-390026390
- https://github.com/cypress-io/cypress/issues/136#issuecomment-406908638
- https://github.com/cypress-io/cypress/issues/136#issuecomment-417057086

There is also an article on medium about this issue - maybe interesting too : https://medium.com/@nickdenardis/getting-cypress-js-to-interact-with-ckeditor-f46eec01132f

Au retour de Philippe il faut que vous regardiez ensemble pour débloquer Philippe dans ses tests automatiques.

Damien 

https://github.com/cypress-io/cypress/issues/136#issuecomment-417057086

**Comment by PhilippeAccorsi** [comment]
Roadmap cypress, **You cannot target elements or interact with anything in an iframe** :

https://docs.cypress.io/guides/references/known-issues.html#

**Comment by raphj** [comment]
We do test TinyMCE now, so let's close this.
