### ISSUE TITLE
restore archive buttons + allow to show archive content in folders

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#85]
We disabled archive button according to bug #81. These buttons will be restored as soon as archives are available through webdav.

This need to uncomment code in templates (search for SHOW_ARCHIVE_BUTTON__BUG_#81 in code)

By the way, the idea is to allow to show archives in folder view

**Comment by buxx** [comment]
TODO:

* Restore Folder, File, Page and Thread "Archive" button
* Permit to view workspace archived folders
* Permit to view folder archived contents

**Comment by buxx** [comment]
@lebouquetin See archived contents/folder will be available. Should we permit to view deleted content/folders to ?

**Comment by tracim** [comment]
@buxx yes we must have the option to view deleted contents too.

**Comment by tracim** [comment]
Note : 
- on threads, the button is not available
- on files the button is available but the label (in french) is "Archivertest" instead of "Archiver"
- on pages, the button is ok
- on folders, the button is not available

**Comment by buxx** [comment]
Note: Assigne rensuite à Come pour design (notamment colorer les lignes de contenu lorsque il y a la classe archivde ou deleted)

**Comment by buxx** [comment]
Note: Click on deleted/archived folder are broken (because they are not available, so 404). Disable direct link, and add "restore" button.

**Comment by buxx** [comment]
@Skylsmoi Le développement est disponible sur la branche 85/dev/beta_1.0/archived_deleted_shown . Tes dévs devront être poussé sur cette branche, j'attends une relecture de Damien.

@lebouquetin Je vais créer un Merge request pour discuter des changements.

**Comment by buxx** [comment]
@bux Bug: affichage d'un répertoire supprimé: Les boutons archiver, supprimer s'affichent quand même ... ?
(vu sur http://127.0.0.1:8080/workspaces/43/folders/2483)

**Comment by buxx** [comment]
Feature: La barre d'affichage se transforme en:

* active
* deleted
* archived

Par défaut, affiche les actives. Les clics active ou désactives les affichages (pour pouvoir faire des combinaisons). Si ils sont tous désactivé, revenir à la vue "active".

**Comment by buxx** [comment]
Affichage d'un contenu archivé/supprimé: ajouter la classe en plus de not-editable. Ajouter un message en haut de la page (comme le message lorsque l'on consulte une version antérieure).

**Comment by buxx** [comment]
Les trois points cités ci-dessus après réunion avec Damien ont été réalisé et poussés sur 85/dev/beta_1.0/archived_deleted_shown . @Skylsmoi Tu peux attaquer le design cité dans le message du 13 décembre.
