### ISSUE TITLE
How downloaded file should be handled ?

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#854]
To force download of a file there is 2 solutions : 
- Specific header 'Content-Disposition'
- Specific html '[download](https://caniuse.com/#search=download)' attribute

**Comment by lebouquetin** [comment]
First, the API should not force to download : this is to the API user to decide.
Second, you told me that the html download attribute may or may not work => do not use this.

Conclusion : you should add a parameter to the API, something like "force-download=1" in the URI and transform it to a `Content-Disposition` Header.

Is it ok for you @inkhey ?

**Comment by PhilippeAccorsi** [comment]
Verified.
