### ISSUE TITLE
fix color of top left logo

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#858]
the image has it's text in the default Tracim color.
It should has a background color equals to the background color of the header and the text should back transparent so that when changing the .primaryBgColor, it will automatically change the color of the top left header logo

**Comment by AlexiCauvin** [comment]
@lebouquetin @Skylsmoi  
Do I have to change the logo in the header to be able to change the color when the theme changes? 
Should the user be able to change the tracim logo to his own logo?

**Comment by Skylsmoi** [comment]
Indeed, users should be able to change it. But right now, we dont have any solutions to do it apart from changing the source file.
Having the logo transparent will at least allow users to have it in the same color of the primary color they chose

**Comment by PhilippeAccorsi** [comment]
@lebouquetin Since we have changed default logo, I think it's no more necessary to add primary-color relation for logo. If you not use one specific logo and don't use tracim logo, you just see header color.

Can we close this issue?

**Comment by Skylsmoi** [comment]
@PhilippeAccorsi I agree, we can close it

**Comment by PhilippeAccorsi** [comment]
I close this issue.
