### ISSUE TITLE
Responsive : adapt or disable the timeline opening in responsive apps 

### ISSUE THREAD

**Issue by AlexiCauvin** [tracim/tracim#861]
solutions :
- disable the timeline mechanism in responsive

**Comment by PhilippeAccorsi** [comment]
@AlexiCauvin @Skylsmoi please explain what you think about that.

**Comment by PhilippeAccorsi** [comment]
@lebouquetin this is what you want for responsive?

**Comment by lebouquetin** [comment]
@AlexiCauvin @Skylsmoi the goal is not to disable the timeline but to show the timeline below and not allowing to hide it

**Comment by PhilippeAccorsi** [comment]
Le clic sur la timeline doit être désactivé en responsive. Actuellement avec un test sur la tablette en mode portrait, la zone de texte est réduite en taille si l'on clic sur la time line. Cette zone d'affichage doit rester fix.

**Comment by PhilippeAccorsi** [comment]
Verified.
