### ISSUE TITLE
Preview_page_nb should start at 1 instead of 0 when calling API

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#866]

**Comment by tracim** [comment]
What's wring? I do not understand this issue...

**Comment by Skylsmoi** [comment]
@tracim @lebouquetin It is for coherence is endpoints:
E.g: if `file/:id/content` returns page_nb: 3, it makes sens to call `/file/:id/content/preview/pdf?page=[1..3]` instead of `/file/:id/content/preview/pdf?page=[0..2]`

Moreover, it's cleaner for the frontend to do this way

**Comment by PhilippeAccorsi** [comment]
Verified.
