### ISSUE TITLE
string key "{{nb}} days ago" (app file) does not update on language change

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#867]
On app file, in the timeline, every revisions have the string "x [days, hours, minutes, seconds] ago".

This string does not update on language change in frontend.

It works for app html document.

**Comment by lebouquetin** [comment]
@Skylsmoi this feature is visible? What I see is the date and time of modification, not "x time ago" (which would be better)

**Comment by Quiwy** [comment]
Not relevant anymore
![image](https://user-images.githubusercontent.com/20048264/185613874-9fdaa94e-4e50-4a39-8298-f2bd20cac96b.png)
