### ISSUE TITLE
Timeline: its impossible to know who is the author of a revision

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#869]
at present :

in app you can see date and hour about new version. Name of the author is not visible.

Expected

- [x] show also member name and avatar.
- [x] also add the user name as title of the avatar

**Comment by lebouquetin** [comment]
not sure it will be quick to fix, but would be nice

**Comment by Skylsmoi** [comment]
It shouldn't be very long but not quick enough to allow the "quick" tag I guess ^^

**Comment by basilelegal** [comment]
@lebouquetin Design proposition:

![screenshot at 2019-02-26 05-04-25](https://user-images.githubusercontent.com/7879232/53404628-0ee70c00-3984-11e9-84bd-a7832e31c0c4.png)

**Comment by basilelegal** [comment]
@lebouquetin I used github timeline as an example for the wording

> lebouquetin removed this from the TracimV2 - V2.2 milestone 6 days ago

**Comment by basilelegal** [comment]
second proposition:
![screenshot at 2019-02-27 10-28-34](https://user-images.githubusercontent.com/7879232/53504990-00324f00-3a81-11e9-87be-43cd9e8c8044.png)

third proposition:
![screenshot at 2019-02-27 10-57-03](https://user-images.githubusercontent.com/7879232/53505003-07f1f380-3a81-11e9-83a2-8f04d12c478a.png)

**Comment by tracim** [comment]
@basilelegal, keep first proposal, but change text to only : «status changed to *validated*» for example.

Name of the user can be only as title of the avatar. And datetimeshould stay right aligned

**Comment by basilelegal** [comment]
@lebouquetin 
New proposal after your comments
![screenshot at 2019-03-04 10-11-38](https://user-images.githubusercontent.com/7879232/53722833-64179780-3e34-11e9-8224-3fd0e85b8d65.png)

**Comment by lebouquetin** [comment]
@basilelegal perfect

**Comment by basilelegal** [comment]
MR #1526 WIP

**Comment by PhilippeAccorsi** [comment]
Verified.
