### ISSUE TITLE
Radicale caldavzap client: don't list never used calendars

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#87]
Lorsque l'on liste des calendriers accessible (par exemple, sur caldavzap), les calendirer qui n'ont jamais été "manipulés" ne sont pas listés:

Les règles permettant de créer/modifier ces calendrier existe, mais comme personne les à encore requêté auprès de radicale, ils n'existe pas "physiquement". Lorsque un client comme caldavzap demande la liste des calendrier, ceux-ci ne sont donc pas retournés.

**Comment by tracim** [comment]
Bux, vois-tu une solution ? Une idée : créer un évènement au moment de la première activation de l'agenda associé au workspace (soit à la création si la coche est activée, soit au moment où la coche est activée durant l'édition)

**Comment by buxx** [comment]
Je vais faire ça oui: Créer puis supprimer un événement à la volée.
