### ISSUE TITLE
copyright: show copyright all the time

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#872]
at present

in many case, copyright is not visible.

expected

copyright is visible all the time with correct/good view.

**Comment by lebouquetin** [comment]
@PhilippeAccorsi add a screenshot explaining how to do

**Comment by PhilippeAccorsi** [comment]
After some idea, copyright is just visible in end of sidebar. All the time at end of sidebar.
This is available in release_2.2.0_rc5.
I close this issue.
