### ISSUE TITLE
admin user : synthesis problem

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#874]
at present

we have this view:

![capture d ecran de 2018-09-07 15-20-56](https://user-images.githubusercontent.com/25848257/45221560-16213d00-b2b2-11e8-8e44-b8df3938c102.png)

expected

- member not in bold (if necessary explain why)
- ~~when mouse is over button change the color of this button (like with other button in tracim)~~

**In Active column:**
- If user is "active" => don't show text "active"
- If user is "inactive" => show text in lightgrey "This user is desactivate"

**For all button:**
- if button is in position "active" => button is green
- if button is in position "inactive" => button don't have color

**Comment by Skylsmoi** [comment]
I havent done it, your integration did. I didn't changed it

@PhilippeAccorsi I'm not sure what you implies by "change the color of this button " theses buttons changes in design when they switch values (on or off)

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi @AlexiCauvin 
After discuss with @lebouquetin:

**In Active column:**
- If user is "active" => don't show text "active"
- If user is "inactive" => show text in lightgrey "This user is desactivate"

**For all button:**
- if button is in position "active" => button is green
- if button is in position "inactive" => button don't have color

**Comment by PhilippeAccorsi** [comment]
This is fixed now.

**Comment by PhilippeAccorsi** [comment]
Verified.
