### ISSUE TITLE
create content: autofocus directly on text input

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#875]
at present

when you create content you need to clic in text zone to write title of content.

expected

when you create content its possible to write directly the text (autofocus on placeholder)

**Comment by lebouquetin** [comment]
@Skylsmoi this issue must be resolved for 2.0 except if its more than half a day of work

**Comment by PhilippeAccorsi** [comment]
Fix today by Skylsmoi.

**Comment by PhilippeAccorsi** [comment]
Verified.
