### ISSUE TITLE
app file: change icon about pdf export

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#877]
at present

we can show this order

![capture d ecran de 2018-09-07 15-50-33](https://user-images.githubusercontent.com/25848257/45222931-1d4a4a00-b2b6-11e8-8e56-ed64c98d9ded.png)

expected

find a good icon for each function.
inverse 2 last icon. 
Maybe find good icon to download just one page in pdf (present page). @lebouquetin do you have an idea for this icon?

**Comment by lebouquetin** [comment]
Icons in this order : 

1. (left) icon of an empty page which allow to download the current page
2. (middle) icon of a pdf which allow to download the document in pdf form
3. (right) icon "download" which allow to download the original document

**Comment by AlexiCauvin** [comment]
@Skylsmoi The download links do not seem to correspond to the correct function according to @lebouquetin

**Comment by Skylsmoi** [comment]
@AlexiCauvin is there another thing do to in this issue ? If not, put it to need test

**Comment by PhilippeAccorsi** [comment]
@AlexiCauvin can you change also de small title html when you stay with mouse on icon?
Inverse first and second small title.

**Comment by PhilippeAccorsi** [comment]
Verified.
