### ISSUE TITLE
Dashboard : remove the minimum size on recent activity and members list

### ISSUE THREAD

**Issue by ghost** [tracim/tracim#879]
Improve the view of recent activity and members list

![image](https://user-images.githubusercontent.com/16293214/45225438-d01da680-b2bc-11e8-8a54-df7df50963c3.png)

**Comment by PhilippeAccorsi** [comment]
@gbonaspetti this is done since we have done modification in the dashboard, right ?

**Comment by gbonaspetti** [comment]
> @gbonaspetti this is done since we have done modification in the dashboard, right ?

yes it's deprecated (https://github.com/tracim/tracim/issues/4330)

**Comment by PhilippeAccorsi** [comment]
I close this issue.
