### ISSUE TITLE
CaldavZap cache system

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#88]
Caldavzap possède un système disant au client (web browser) de ré-effectuer la demande des fichiers de config de caldavzap. D'après la doc cela est nécessaire pour que le client (web browser) soit à jour et liste bien tous les calendriers.

Je ne sais pas à ce stade quel est l'impact, mais comme on ne passe pas directement par un serveur web apache (caldavzap fournis un .htaccess dédié à cela) les règles de "cache" ne sont pas correctement appliqué.

Il faut re-faire un tour d'horizon pour:
- Estimer l'impact
- Si besoin donc, apporter ce fonctionnement à travers tracim.

**Comment by Skylsmoi** [comment]
Dans la situation actuelle, caldavzap ne peut pas utiliser son système de cache (avec cache.manifest), celui du navigateur est donc utilisé. Or, le navigateur n'utilisant pas le fichier cache.manifest, il ne détecte pas les mises à jour de fichiers et charge toujours tout depuis son propre cache.

Pour que le cache.manifest soit correctement utilisé, il faut rajouter des config dans le serveur web.
Ces configs sont dans _caldavzap/.htaccess
pb : ces config ne sont dispo que pour apache2

**Comment by buxx** [comment]
Après discussion avec Damien, on retire l'utilisation de ce manifeste pour le moment. Les navigateurs eb chargent au besoin les ressources.
