### ISSUE TITLE
Remove useless tracim logo on home page

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#881]
Here is my login screen on a 1366x768 screen.

![espace de travail 3_084](https://user-images.githubusercontent.com/907161/45228348-3f969480-b2c3-11e8-9c56-894cf101318d.png)

Expected : 
- remove the tracim logo above the login form

the goal is to see the full login screen on page

**Comment by PhilippeAccorsi** [comment]
@Philippe
I think its ok but need more verification with small screen.
With 10" pad, whis horizontaly view => not really good.
Whis verticaly view => ok.

Try with @lebouquetin to make sure is working good on small PC (with small resolution).

**Comment by PhilippeAccorsi** [comment]
Verified.
