### ISSUE TITLE
add member: error 400 when you try to add member 

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#884]
At present

When I tried to add member to one workspace (new user) I have  POST error 400 with this message:

~~~
message | Validation error of input data
-- | --
details | {…}
user_id | […]
0 | Not a valid integer.
code | null
~~~
~~~
role | reader
user_email_or_public_name | [my_email]
user_id |  
~~~

 Expected

When we try the POST request directly with "user_id ": null , the member is correctly added.
command => `# http -a admin@admin.admin:admin@admin.admin POST http://192.168.1.250:6543/api/v2/workspaces/2/members < test1.json`

with this value:
~~~
"user_id": null,
"user_email_or_public_name": "[my_email]"
"role": "reader"
~~~

**Comment by Skylsmoi** [comment]
issue already fixed but I added a tiny fix to be extra sure

**Comment by PhilippeAccorsi** [comment]
Verified.
