### ISSUE TITLE
folder: don't show any option/text about folder

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#885]
At present

Folder are finaly not implemented in V2.0

Expected

Don't show any option/text about folder.

**Comment by PhilippeAccorsi** [comment]
@inkhey in backend its necessary to deactivate folder for frontend (remove folder in list of app available).

**Comment by AlexiCauvin** [comment]
@inkhey We cannot disable folders via the front (presence of javascript error), you must disable it via the backend.

**Comment by lebouquetin** [comment]
@AlexiCauvin could you copy/paste the JS error here?

**Comment by AlexiCauvin** [comment]
Image of the error : 
![image](https://user-images.githubusercontent.com/16293214/45628232-efbe8700-ba93-11e8-9037-604a05dae95e.png)

**Comment by PhilippeAccorsi** [comment]
Verified.
