### ISSUE TITLE
wrong import in frontend_app_admin_workspace_user

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#887]
the file frontend_app_admin_workspace_user/helper.js import i18n from frontend.
It should import it's own i18n.
The problem:
frontend_app_admin_workspace_user requires all app to have built their translation files (e.g running npm run build-translation)
but since we import i18n from frontend, it fails because frontend/i18n.js fails to require some translation files.

**Comment by Skylsmoi** [comment]
@PhilippeAccorsi To test this:
check that the translations of the app admin workspace user are working properly

**Comment by Skylsmoi** [comment]
spoiler: they dont

**Comment by Skylsmoi** [comment]
they do now

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi the translation about active/inactive don't work (all the time in english)

In `/tracim_v2/frontend_app_admin_workspace_user/i18next.scanner` translation.json (en or fr) I can't find line about inactive

**Comment by Skylsmoi** [comment]
I have pushed a fixed.
I didn't wait for you to put this issue back in ToDo because this problem is spread across all apps that are using the component BtnSwitch.
It is fixed now (require rebuild of frontend_lib, and then every apps)

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi "actif" et "inactif" its not better trad? If we see the column title.
Or maybe, we don't need name for this column.
@lebouquetin what do you think about that?

![capture d ecran de 2018-09-11 18-12-07](https://user-images.githubusercontent.com/25848257/45372888-49373980-b5ee-11e8-83b8-6bc5cde2e7d1.png)

**Comment by Skylsmoi** [comment]
I'd say we should improve the design and remove the word.
The design should be enough. But it's sometimes hard to be clear with theses on/off btn with only design

**Comment by PhilippeAccorsi** [comment]
Verified.
