### ISSUE TITLE
Upload image box size and place is strange.

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#888]
**Describe the bug**

Upload image box size and place is strange.

**To Reproduce**

Put this [image](https://user-images.githubusercontent.com/1104637/45345471-af986980-b5a6-11e8-93df-97785396a52a.png) in upload file input:

**Expected behavior**

1. Image should not exceed the box.
2. Upload popin should not exceed the screen.

**Screenshots**

![tracim - mozilla firefox_001](https://user-images.githubusercontent.com/1104637/45345560-fbe3a980-b5a6-11e8-9175-388f8928b4f8.png)

**Desktop (if applicable, please complete the following information):**
 - OS: Debian 9
 - Browser Firefox
 - Version 60.2.0esr (64 bits)

**Comment by lebouquetin** [comment]
Currently : in case of a large image, the preview hide buttons. 
Expected : define a max size for the preview in order to prevent this case.

**Comment by Skylsmoi** [comment]
https://github.com/tracim/tracim_v2/commit/dcc06d68028868155627bf09e48a4aa481effeaa

**Comment by PhilippeAccorsi** [comment]
Verified.
