### ISSUE TITLE
Create a content after apply a filter disable the filter

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#891]
**Describe the bug**

When content creation popin open, applied filter is cancel. EDIT: Same behaviour when i open a content.

**To Reproduce**

1. Open a workspace
2. Click on "Files" filter
3. Click on Create the upload a file

**Expected behavior**

File list should not be updated with non files documents.

**Screenshots**

![tracim - mozilla firefox_003](https://user-images.githubusercontent.com/1104637/45346225-e3748e80-b5a8-11e8-90e0-9368ad2380a3.png)

**Comment by lebouquetin** [comment]
An interesting  answer from @AlexiCauvin was that the create menu is a shortcut so you can create a document without leaving threads view.

Another solution would be to add a real-shortcut button on the left of the menu for current type of content.

Anyway, to be discussed after 2.0

**Comment by PhilippeAccorsi** [comment]
Verified.
