### ISSUE TITLE
Downloaded file is called "raw" / Naming strategy ?

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#892]
**Describe the bug**

When download a file, the downloaded file filename is "raw". I guess backend response header is missing Content-disposition "filename" http header. See [rfc](https://tools.ietf.org/html/rfc6266#section-4) or [here](https://stackoverflow.com/a/1741508/801924).

**To Reproduce**

1. Download uploaded file with "Download file" button.

**Expected behavior**

Downloaded file should have origin filename filename.

**Screenshots**

![tracim - mozilla firefox_004](https://user-images.githubusercontent.com/1104637/45346468-93e29280-b5a9-11e8-9eb9-8df3900c4dbe.png)

**Comment by inkhey** [comment]
naming strategy : 
- for normal file and revision: use file_name param of revision/content.
- for preview ?


Preview naming file In tracim v1 : 
 - pdf full version have same label but pdf extension (ex : test_file.md -> test.file.pdf)
 - pdf 1 page version don't seems to work correctly (can't test)
 - jpeg preview doesn't really have naming because there are just showed, same case as "raw" , naming refer to endpoint, so it is something like "high_quality" ...

**Comment by lebouquetin** [comment]
> pdf 1 page version don't seems to work correctly (can't test)

@inkhey your are a DEVELOPER. So at least you must READ THE CODE.

> jpeg preview doesn't really have naming because there are just showed, same case as "raw" , naming refer to endpoint, so it is something like "high_quality" ...

This is a naming. Maybe wrong, but it's a naming. By the way, if you right click on a small preview, you can get its name and its `0.jpeg`, `1.jpeg`, etc.

Now, the software module in charge of generating previews is preview-generator. Preview files are stored on disk. Could you add the naming rules associated to stored files, please?

**Comment by inkhey** [comment]
`
This is a naming. Maybe wrong, but it's a naming. By the way, if you right click on a small preview, you can get its name and its 0.jpeg, 1.jpeg, etc.
`

This is a default naming choosen probably by the browser. The backend server doesn't explain here what the naming should be.

**Comment by lebouquetin** [comment]
> This is a default naming choosen probably by the browser.

Ok. So there is a naming.

> This is a default naming choosen probably by the browser.

The v1 naming has to be *improved* because it relies on the browser - so it is not under control. Good point.

What about the naming of files stored by preview-generator. I know there are names including page and image dimensions. Could you complete with this?

**Comment by inkhey** [comment]
@lebouquetin 
some example of preview_generator created file (i will check the code to understood better):

```
0aacbe4ee2ed6c4c3d6d2059427ba969-256x256-page0.jpeg
0cdf9d46244c964287546306922fe087.pdf
00d4c4b359f620e94bc71151a4a6a0a2-page0.pdf
```

**Comment by lebouquetin** [comment]
c'est un md5sum du path, je crois.

**Comment by lebouquetin** [comment]
At least:

- files to upload must have the file_name as filename (note: by default, label must be updated with new file_name value in case of update of a file)
- full pdf version must be named with same name except extension

**Comment by inkhey** [comment]
@lebouquetin In case of getting file or preview of an old revision, file-name must be old file-name or current-one?

**Comment by inkhey** [comment]
Technicall handling of this issue will be done at the same time as  #892.
This issue will be left opened until naming strategy is not decided.

**Comment by PhilippeAccorsi** [comment]
For the moment when you try to download file, the name have mimetype replicated at end of file name.

Ex: 
file name => test.pdf
File name when download => test.pdf.pdf

**Comment by inkhey** [comment]
@PhilippeAccorsi this will be fix by fixing both https://github.com/tracim/tracim/issues/880, https://github.com/tracim/tracim/issues/957.

**Comment by PhilippeAccorsi** [comment]
I have tested with different mimetype and its working good.

**Comment by PhilippeAccorsi** [comment]
Verified.
