### ISSUE TITLE
Errors displayed when i am disconnected

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#894]
**Describe the bug**

When disconnected, action on frontend produce error messages.

**To Reproduce**

1. Login into tracim
2. Open new tab with tracim
3. Disconnect with one of tabs
4. Try to use Tracim with opened tab

**Expected behavior**

Tracim should say we are disconnected and redirect (or make proposition) to go to login page.

**Comment by PhilippeAccorsi** [comment]
Fix by @Skylsmoi 

@Skylsmoi can you modiy this message:
~~~
Information
You have been disconnected, please login
~~~
by 
~~~
Information
You have been disconnected, please login again
~~~

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi Its not working if you try to use admin workspace or admin user.
You don't see anything but you are not disconnected.

**Comment by PhilippeAccorsi** [comment]
We have seen with @Skylsmoi that code not working for admin workspace and admin user. need debug.

**Comment by Skylsmoi** [comment]
I already added a redirection to login with the error msg whenever a endpoint return 401.
Since it seems to work well, I have reproduced that process for apps

**Comment by PhilippeAccorsi** [comment]
Verified.
