### ISSUE TITLE
Upload popin hidden by bottom of window

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#896]
**Describe the bug**

When screen size is little, upload popin is hidden.

**To Reproduce**

1. Open upload popin
2. Resize window

**Expected behavior**

Popin should be centered.

**Screenshots**

![selection_006](https://user-images.githubusercontent.com/1104637/45349323-381c0780-b5b1-11e8-9a61-b8ac9d81f4db.png)

**Comment by lebouquetin** [comment]
@Skylsmoi the issue is for every popup

**Comment by PhilippeAccorsi** [comment]
Fix today by Skylsmoi.

**Comment by PhilippeAccorsi** [comment]
Verified.
