### ISSUE TITLE
various bugfix in app_workdpace_advanced

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#900]
todo:
- ~~color. use .primary classes from frontend~~
- ~~edit workspace title sometimes doesn't display the previous title in the input~~
- ~~description doesn't allow line break~~
- ~~placeholder stay in french~~
- ~~btn "delete workspace" in admin/workspace, need to preventdefault and stop propagation~~

**Comment by lebouquetin** [comment]
@PhilippeAccorsi workspace description is rich text or simple text?

**Comment by PhilippeAccorsi** [comment]
@lebouquetin description is simple text.

**Comment by PhilippeAccorsi** [comment]
Verified.
