### ISSUE TITLE
Menu button hidden by scrolling

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#901]
**Describe the bug**

The open/close menu button is hidden when scroll the page.

**To Reproduce**

1. Hide menu
2. Scroll down

**Expected behavior**

Open menu button should be always visible.

**Screenshots**

![tracim - mozilla firefox_010](https://user-images.githubusercontent.com/1104637/45409394-4e889880-b66f-11e8-832a-e730929e068e.png)
![tracim - mozilla firefox_011](https://user-images.githubusercontent.com/1104637/45409398-50525c00-b66f-11e8-8f7a-8c25ebb09757.png)

**Comment by PhilippeAccorsi** [comment]
This is fix in release_2.2.0_rc2
I close this issue.
