### ISSUE TITLE
Refresh issue in app file

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#902]
At present

when switching among 2 different content file without closing the app popup, there is a refresh issue.

Workspace_advanced:
- When you change role or delete member, the list in dashbord not change

Many time when you use tracim, we can seen refresh problem: with title, with role, etc...

Expected

Its possible to use tracim without any error of refresh, or blank page.

Work in mode extreme programming with @PhilippeAccorsi to find all problem and solved it directly.

**Comment by PhilippeAccorsi** [comment]
Verified.
