### ISSUE TITLE
Don't manage response in request object code, use Hapic file support instead

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#903]
## Currently

The current `TracimRequest` class contain code about response building:

* `response_content_disposition` attribute
* `_set_responses_headers` method
* `response_download_mode` method

This code exist because Hapic don't permit access to request data in response building code. See this [issue](https://github.com/algoo/hapic/issues/82) for the change.

## To do

* Use new response file support of hapic 0.52 (see algoo/hapic#86) instead of custom pyramid Request object.
* Add explicit filename info for all endpoint according to https://github.com/tracim/tracim/issues/892  .
* ~~Make pull request on hapic about the [need](https://github.com/algoo/hapic/issues/82)~~
* Remove concerned code in `TracimRequest`
* ~~Add needed header (`Content-Disposition`) in response construction code (request object is now accessible)~~
* Filename can be found in controller returned object itself

**Comment by lebouquetin** [comment]
@inkhey this issue is better to be fixed for 2.0... BUT its low priority. Do it at the full end of 2.0 bugfixes

**Comment by inkhey** [comment]
Finally this may be handled by new response file support of hapic (see https://github.com/algoo/hapic/issues/86) in hapic 0.52.
https://github.com/algoo/hapic/issues/82 is not anymore a requirement for this.

**Comment by PhilippeAccorsi** [comment]
Verified.
