### ISSUE TITLE
Rename routes for notification activation/deactivation

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#904]
**Describe the bug**
Endpoints for activating and deactivating notifications are the following ones:

- `PUT /api/v2/users/{user_id}/workspaces/{workspace_id}/notify`
- `PUT /api/v2/users/{user_id}/workspaces/{workspace_id}/unnotify`

**Expected behavior**

Rename routes to : 

- `PUT /api/v2/users/{user_id}/workspaces/{workspace_id}/notifications/activate`
- `PUT /api/v2/users/{user_id}/workspaces/{workspace_id}/notifications/deactivate`

or to : 

- `POST /api/v2/users/{user_id}/workspaces/{workspace_id}/notifications`
- `DEL /api/v2/users/{user_id}/workspaces/{workspace_id}/notifications`

**Comment by lebouquetin** [comment]
@inkhey @Skylsmoi what do you think?

**Comment by PhilippeAccorsi** [comment]
Verified.
