### ISSUE TITLE
Refresh of page: in some many case the refresh not working

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#909]
at present:

after first connexion in tracim (after one CTRL + F5 in login page) I go in admin_user after that I go in admin_workspace, the page is blanck.

Too many time the admin_workspace or admin_user show just blanck page. 

Expected

No blanck page is show in tracim.

**Comment by Skylsmoi** [comment]
https://github.com/tracim/tracim_v2/commit/d62b924c9c25e00a451ff57b148ef69deb38cf21

**Comment by Skylsmoi** [comment]
If this issue is only about admin pages (user, workspace) it is fixed now.
There is another issue about app file that might not refresh properly here : https://github.com/tracim/tracim/issues/902

**Comment by PhilippeAccorsi** [comment]
Verified.
