### ISSUE TITLE
Password: Problem: max value not working

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#910]
At present

I change password for my account with just type "old password". I validate directly the form. The new password is accepted but its a blanck password.

Expected

Make different kind of control:
- send button is not activate if new password is not defined.
- make control of complexity or/with minimum of lenght.

the good idea is to make minimum of necessary caractere and maximum not under for exemple 30 caractere. With this solution is possible to use passphrase. its better than for exemple "4 caratere minimum and 10 maximum"

**Comment by Skylsmoi** [comment]
@lebouquetin Are you ok with this password length restriction 6..50 ?

**Comment by tracim** [comment]
Why 6 ? Why limit length to a max?! At least remove the max value.

**Comment by PhilippeAccorsi** [comment]
@lebouquetin if you not make max value, you can make a very big value and I think, you can make a ddos of service.

**Comment by Skylsmoi** [comment]
Philippe, that's right
6 because it sets a minimum value that isn't too restrictive

**Comment by tracim** [comment]
Ok. So put maxvalue to 512

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi max value not working, its possible to use password with 513, 513 or for exemple 1028 character

**Comment by PhilippeAccorsi** [comment]
Verified.
