### ISSUE TITLE
Set password size limitation in backend

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#911]
At present :

~~We don't know the limit of the password lenght and we don't know if its working good~~
There is no password limitation (no min and no max limitation).

Expected :

~~Know what is the limit of password length.~~

Set password limitation in backend with min at 6 char and max at 512 char

**Comment by PhilippeAccorsi** [comment]
@inkhey No limitation in frontend.
I think its important to have limitation in frontend or backend to be sure no DDOS is possible whis a very very long password.

**Comment by inkhey** [comment]
Password limitation should be between 6 and 512 char according to https://github.com/tracim/tracim/issues/910.

**Comment by inkhey** [comment]
same issue as #1050
