### ISSUE TITLE
Color: the color of sidebar is too dark

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#912]
At present

Caplogiciel => color: #fd912c

The color in sidebar is too dark:
![capture d ecran de 2018-09-12 18-13-16](https://user-images.githubusercontent.com/25848257/45438495-9b905d00-b6b7-11e8-8bd7-1b36761178a9.png)

the image in background is also too dark
![applat](https://user-images.githubusercontent.com/25848257/45438594-d397a000-b6b7-11e8-84dd-7d729911ff17.png)

Expected

Make background image more light and try with darken or not darken for color of the sidebar.

**Comment by Skylsmoi** [comment]
@AlexiCauvin Your part of the task is to edit the background image.
It should be really transparent, right now, it darken the color it behind by a lot.
It also should be smaller. Since it is used as a background-repeat, the size of it should be 1 iteration. Ask me for more details, it's hard to explain here

**Comment by AlexiCauvin** [comment]
@lebouquetin i think the pattern is a too flashy
![image](https://user-images.githubusercontent.com/16293214/45612704-2381b880-ba64-11e8-8256-1d435552e125.png)

**Comment by PhilippeAccorsi** [comment]
@AlexiCauvin 
Sreenshot sidebar caplogiciel:

![capture d ecran de 2018-09-17 10-38-48](https://user-images.githubusercontent.com/25848257/45613276-0fd75180-ba66-11e8-9222-ccb729a1e12c.png)

**Comment by AlexiCauvin** [comment]
Color of the sidebar after modification of the theme and pattern :

![marron](https://user-images.githubusercontent.com/16293214/45615565-2c2abc80-ba6d-11e8-9daf-60ef01ce55ff.png)
![jaune](https://user-images.githubusercontent.com/16293214/45615574-33ea6100-ba6d-11e8-84d4-1e39ef0eb7aa.PNG)

**Comment by AlexiCauvin** [comment]
![image](https://user-images.githubusercontent.com/16293214/45618254-68621b00-ba75-11e8-965f-e2d83f63033c.png)

**Comment by AlexiCauvin** [comment]
![image](https://user-images.githubusercontent.com/16293214/45618381-bd059600-ba75-11e8-9114-3d0bf5ec541b.png)

**Comment by AlexiCauvin** [comment]
the button to create a workspace has also been modified. Its background-color is primaryColorBgLighten and its font color is dark grey

**Comment by PhilippeAccorsi** [comment]
Verified.
