### ISSUE TITLE
Improve avatar design

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#913]
**Currently**

The avatar is a `<img/>` including an auto-generated SVG file.
The SVG is a circle with a border, the background is computed according to user name.
The `<img/>` is square and the avatar is circle

**Expected**
- [x] ~The avatar should be a rounded `<div/>` with a border with primary color of the theme~
- [ ] The content of the div are the 2 first letters of the user name, in white, taken from all parts of the name (separated by `-` or `.` or ` ` (space)
- [x] The background color of the div is the color computed according to the user name

Example:

```
<div style="width:128px; height: 128px; border-radius: 64px; border: 2px solid #FD912C; text-align: center; vertical-align: middle; overflow: hidden;">
    <div style="width: 120px; height: 120px; margin: 4px; background-color: #709; overflow: hidden; border-radius: 58px; color: #FFF; font-weight: bold; font-size: 64px; line-height: 128px; ">
   CO
    </div>
</div>


<div style="width:64px; height: 64px; border-radius: 32px; border: 1px solid #FD912C; text-align: center; vertical-align: middle; overflow: hidden;">
    <div style="width: 60px; height: 60px; margin: 2px; background-color: #C09; overflow: hidden; border-radius: 60px; color: #FFF; font-weight: bold; font-size: 32px; line-height: 64px; ">
   DA
    </div>
</div>
```

Examples of names : 

- if user is *Damien Accorsi*, the avatar is DA
- if user is *Côme Huguiès*, the avatar is CH
- if user is *Pierre-Henry Dupond*, the avatar is PH
- if user is *Some.Dummy.PublicName*, the avatar is SD

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi just to remember: its impossible to access to account of user from admin user.
Bug with avatar.

**Comment by PhilippeAccorsi** [comment]
Verified.
