### ISSUE TITLE
Workspace advanced edition

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#914]
**Describe the bug**
Several bugs on the application : 

- Title edition:
     - ~~if I click edit, the field is empty. expected: have the current title in edit field~~
     - if I hit escape key, I expect the form to go out of edition => specific issue for this: #956 
- Description edition:
    - ~~when editing the description, if I hit "save" button, a popup tell me that the edition succeeded... but the app is not closed and the dashboard is not refreshed.~~
- Member management
    - ~~operations seems to work but nothing is refreshed, no flash message saying "ok".~~

**Comment by PhilippeAccorsi** [comment]
Hit escape key nyi.

**Comment by PhilippeAccorsi** [comment]
Verified.
