### ISSUE TITLE
error when importing a file docx or odt from popup create content

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#917]
If I create a new content type file, if I upload a file type docx or odt, the upload success (returns 200 or 204) but the end point workspaces/:id/files/:id returns error 500 [Errno 2] No such file or directory: '/tmp/tracim/preview/96a8a7df482a08c59b9c464e00cfd2c5.pdf'

If I edit an existing file and import the same file docx or odt, it works fine.

**Comment by PhilippeAccorsi** [comment]
[programme2018_web.pdf](https://github.com/tracim/tracim/files/2389281/programme2018_web.pdf)

**Comment by inkhey** [comment]
Similar issue using last preview_generator version https://github.com/algoo/preview-generator/commit/b979040b94c5845d8c8b9179a8ea72c46f359bb5 , for tracim api test.
All test based on simple text file now failed, like "_test_api__get_file__ok_200__nominal_case_"

```
       b'File \\"/home/user/Public/preview-generator/preview_generator/manager.py\\", line 80, in get_page_nb\\n   ' \
        b' self.cache_path\\n  File \\"/home/user/Public/preview-generator/preview_generator/preview/builder/office__libreoffice.py\\", ' \
        b'line 116, in get_page_number\\n    cache_path=cache_path\\n ' \
        b' File \\"/home/user/Public/preview-generator/preview_generator/preview/builder/office__libreoffice.py\\", line 170, in build_pdf_preview\\n   ' \
        b' output_filepath=intermediate_pdf_file_path\\n  File \\"/home/user/Public/preview-generator/preview_generator/preview/builder/office__libreoffice.py\\",' \
        b' line 249, in convert_office_document_to_pdf\\n    ' \
        b'os.rename(output_filepath+\'.pdf\', output_filepath)\\n' \
        b'FileNotFoundError: [Errno 2] No such file or directory: \'/tmp/test/preview_cache/86f21218ccf1e735b0ecc9e105d2b3f5.pdf.pdf\' -> \'/tmp/test/preview_cache/86f21218ccf1e735b0ecc9e105d2b3f5.pdf\'\\n"
```

File who does not work are simple text file, generated in test, for example like in "_test_api__get_file__ok_200__nominal_case_" . 

```
       content_api.update_file_data(
            test_file,
            'Test_file.txt',
            new_mimetype='plain/text',
            new_content=b'Test file',
        )
        with new_revision(
            session=dbsession,
            tm=transaction.manager,
            content=test_file,
        ):
            content_api.update_content(test_file, 'Test_file', '<p>description</p>')  # nopep8
            dbsession.flush()
        transaction.commit()
```

**Comment by inkhey** [comment]
Bug with text file in test in last preview_generator may be fixed by this commit : https://github.com/algoo/preview-generator/commit/170f0c516d272e5c15ab09cbbe98217adc26db6c .Need to be checked.

For doc file 500 error when creating content like doc, a weird concurrency problem has been found. It seems that frontend is trying to run many endpoint at the same time when loading app and has intermediate pdf preview is not created yet, it fail. Using only one endpoint at the same time does not create this issue.
An easy workaround is to directly ask for creating intermediate pdf preview if needed when uploading file by directly asking for page_number of new file before database commit.

**Comment by inkhey** [comment]
@PhilippeAccorsi This need to be tested now as we have updated preview_generator versioN.

**Comment by PhilippeAccorsi** [comment]
@inkhey I have tested with one docx file and everything its working good.

Do you have one another docx file for test?

**Comment by PhilippeAccorsi** [comment]
I close this issue.
Pass to Done not close issue automatically.
