### ISSUE TITLE
Include traceback in logs in case of exception

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#920]
**In case of exception, no traceback available even in debug mode**
In case of exception - lets try for example to preview an odt document, the API returns a JSON with error structure but traceback is not available.

**Expected:**

- The `is_debug` option of hapic pyramid context seems not to be setup correctly (I forced True in the code and the traceback was included in the JSON response)
- The traceback should be included in logs.

**Comment by PhilippeAccorsi** [comment]
Verified.
