### ISSUE TITLE
Riche text editor : improve view + make insert an image more easily 

### ISSUE THREAD

**Issue by lebouquetin** [tracim/tracim#921]
**Currently**

In tracim v1

- we added an image button in the tinymce toolbar which opens the file selector. this button allow to insert an image taken from local drive of the user.
- it is also possible to drag and drop an image taken from local drive

In tracim v2

- it's possible to drag and drop an image
- the image button is missing

**Expected**

- [x] insert again the image button
- [x] move the button "+" (top left of the toolbar) to the top right
- [x] add the special char button (visible in "+" button) directly in the toolbar
- [x] Translate in all tinymce

**Comment by Skylsmoi** [comment]
also add translations for tinymce

**Comment by PhilippeAccorsi** [comment]
Verified.
