### ISSUE TITLE
Support correctly unsupported preview mimetype file in file endpoints

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#928]
**Describe the bug**
Many endpoints for file using unsupported mimetype return 500 error due to UnsupportedMimetype exception.

**Expected behavior**

Return 200 for endpoint who return json info, 400 for endpoints who should return Preview (which cannot be available).
Content where preview is not supported yet should return only normal error, and not return at all error using get content/get revisions standard endpoints.

**Comment by PhilippeAccorsi** [comment]
Verified.
