### ISSUE TITLE
impossible de supprimer un folder (Workspace) à la racine après l'avoir crée

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#93]
J'ai crée un folder à la racine par l'explorateur de fichier et quand j'essai de le supprimer, toujours via l'explorateur, il me dit que c'est impossible car le folder est non vide.

**Comment by buxx** [comment]
cf.

    def delete(self):
        """For now, it is not possible to delete a workspace through the webdav client."""
        raise DAVError(HTTP_FORBIDDEN)

C'est pas encore implémenté, je place le label enhancement.

**Comment by buxx** [comment]
@lebouquetin Il me semble que tu as évoqué la possibilité que nous ne proposions pas la suppression de workspace à travers webdav. Quand à faire passer un message dans le genre "Vous ne pouvez pas supprimer un workspace"  je ne vois pas comment on pourrais faire à ce stade.

Dois-je fermer l'issue ?

**Comment by tracim** [comment]
We should not be able to delete workspaces from webdav. Please verify (and fix if required), then close

**Comment by algooapy** [comment]
Verification done: we are not be able to delete workspaces from WebDAV.

**Comment by PhilippeAccorsi** [comment]
@Philippe merci de tester aussi.
