### ISSUE TITLE
Wrong end point for app admin workspace

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#931]
in app admin workspace, when getting all workspace, end point used it /users/:id/workspaces
It only returns workspace of the user
It should be /workspaces

**Comment by Skylsmoi** [comment]
I did not set "sort" label to this issue since fixing it is obviously required

**Comment by Skylsmoi** [comment]
Right now, endpoint /workspaces/:id/members does not allow users out of the workspace to see who is in.
The problem is that I have to be able to get that information to display the number of members in the worksapce (on the admin/workspace page)

solution to review: allow the superadmin users to access this endpoint for any workspace

**Comment by Skylsmoi** [comment]
@inkhey will dev the solution to allow the superadmin users to access this endpoint for any workspace

**Comment by tracim** [comment]
The superadmin has access to advanced worspace app? Lets talk about tjis this morning

**Comment by Skylsmoi** [comment]
right now, yes, he does

**Comment by PhilippeAccorsi** [comment]
Verified.
