### ISSUE TITLE
Refactor Group system in a better way.

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#941]
**Describe the bug**

Currently Tracim database model use a complex system for profile, with 3 tables (2 really used) : 
- group_permission (not really used , deprecated ?)
- groups (list of groups, name/slug, and display_name)
- users_groups (groups related to user)

The role system which is the system the most similar to groups, work itself only with one table:
- user_workspace (store only role level int, all other information like slug are store only in tracim code)

There are few issue with the group system : 

- groups slug info and id are stored in 2 differents places : in database and in code (check Group.TIM_USER_GROUPNAME for example). This mean that's a bit complex to change properly profiles name, because it need to modify both database internal data (not database schema) and stored var in code (see https://github.com/tracim/tracim/issues/937 for example).
It seems more convenient, like for role, to not store anything else than id/level in database and to have slug and associated information in code which allow easily to make code related to specific profile level, to return slug of a specific group, etc...

- Groups models allow users to be part of multiple group. This doesn't make any sense related to profiles system which choose always the "max" id group and profile checking, which rely on id value to know if Admin profile means also  manager and user right (other user-group junction than max are useless).

**(not yet) Implemented solution :**
proposition here : see https://github.com/tracim/tracim/pull/2668)
- Convert profile as Enum in users table. Remove completely "group" mecanism.
- table permission and group_permission are dropped.

**Comment by lebouquetin** [comment]
@inkhey we had a chat with a major client who was interested in being able to define which features are available for each profile. Fixing this issue (ie remove the "technical debt") may be in conflict with implementing the definition of features available per profile

**Comment by lebouquetin** [comment]
@PhilippeAccorsi @inkhey I'd like to have a chat together before we remove this

**Comment by inkhey** [comment]
after discussion with @lebouquetin, we decide to merge the fix for this and we do need to clarify how to implement a more customizable mecanism later: https://github.com/tracim/tracim/issues/2879

**Comment by buxx** [comment]
I approve the [pull request](https://github.com/tracim/tracim/pull/2668)

**Comment by buxx** [comment]
Manuel tests done on branch: User (admin, trusted and user) can still been created and use their account.
