### ISSUE TITLE
App Workspace Advanced : Improve the visual design

### ISSUE THREAD

**Issue by AlexiCauvin** [tracim/tracim#942]
We need to improve the visual design of the workspace advanced app 

At present : 

![image](https://user-images.githubusercontent.com/16293214/45820559-52f42780-bce7-11e8-872e-1a914680a04f.png)

Expected : 

![workspace_advanced](https://user-images.githubusercontent.com/16293214/45820589-6bfcd880-bce7-11e8-9b9e-57559ce6f278.PNG)

or 

![image collee a 2018-9-19 15-32](https://user-images.githubusercontent.com/16293214/45820600-728b5000-bce7-11e8-9f51-c64004c05a27.png)

**Comment by PhilippeAccorsi** [comment]
@AlexiCauvin please make more information.
ex:

At present
What is not a good design: ex: title, color, etc...

Expected
ex: title in bold
text in yellow color
