### ISSUE TITLE
z-index conflict between header and tinymce full screen

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#943]
Property: the z-index of an element cannot be higher than the z-index of its parents.

Header z-index is 6
Sidebar z-index is 5
PopinFixed z-index is 7
Fullscreen tinymce z-index 1500

The problems are the dropdown in the header when an app is opened
![selection_012](https://user-images.githubusercontent.com/11177014/45806108-82436e00-bcc0-11e8-8313-22dfc5a26dc8.png)
even if the z-index of the dropdown is 1000+, it cannot exceed the z-index of it's parent which is 6.

If I increase the z-index of the header to fix the dropdown issue, then it is the tinymce full screen that will be behind the Header. Even if the full screen tinymce is 1500, it's parent (popin fixed) is 7

**Comment by Skylsmoi** [comment]
Right now, I only have 2 possibles solutions:
- the Header goes back to static, it isn't fixed anymore and doesn't have z-index. It solves the issue but it now disappear when scrolling
- The tinymce full screen is not a real full screen, I can reduce it's size to be always bellow the Header 
![selection_012](https://user-images.githubusercontent.com/11177014/45806495-7efcb200-bcc1-11e8-92d7-4dddfa2c557a.png)

**Comment by Skylsmoi** [comment]
@lebouquetin waiting for intel

**Comment by lebouquetin** [comment]
the second solution looks fine to me. The goal of the fullscreen is to maximize edit zone, if we have "fullscreen - headbar" it should be ok - and allow the user to keep an eye on the context of the screen.

BUT... will it be sticked to headbar? What if you resize the screen, etc? In these cases, I expect the result to keep on being "professionnal" (you know what I mean? A perfect rendering)

**Comment by Skylsmoi** [comment]
What do you mean by "headbar" ? the header of tracim or the head of tinymce ?

**Comment by lebouquetin** [comment]
the header of tracim.

**Comment by Skylsmoi** [comment]
regarding responsive, in mobile, the header can expand to show the btns. So the problem remains.
But I wonder if it's a good idea to keep the header fixed on mobile

**Comment by lebouquetin** [comment]
@Skylsmoi 

- in mobile view full screen edit with tinymce is not required
- in tablet view, full screen may be interesting.

For the header behavior (fixed/static) : 

- look at dropbox header behavior
- look at basecamp header behavior
- look at gitlab header behavior

Is there a common way to manager the header?

**Comment by lebouquetin** [comment]
also look at mattermost and slack

**Comment by lebouquetin** [comment]
By the way, the header is twice the required height... maybe scrolling it with the rest of the content is a good idea.

**Comment by tracim** [comment]
I should not have deleted lebouquetin comment /o\
Look at the way this is managed in mattermost or slack

**Comment by tracim** [comment]
I do not understand your comment. On september 20 you told "the problem remains (on mobile/tablet). And now, you tell there are no problem. So... we close it?

**Comment by Skylsmoi** [comment]
I was responding about the mattermost and slack way to handle their header

**Comment by PhilippeAccorsi** [comment]
This is fixed in release_2.2.0_rc5
I close this issue.
