### ISSUE TITLE
Admin user: when you want to change name or email for one user, text inputs is not empty after modification success

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#947]
At present

If you change name or email when you validate, the text inputs is not clean.

Expected

When you validate with success, clean all text inputs.

**Comment by Skylsmoi** [comment]
theses are text inputs (only one line), textareas are multi-lines

**Comment by Skylsmoi** [comment]
see this issue : https://github.com/tracim/tracim/issues/953

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi I don't understand: in this issue we spok about cleaning text input after successfull validation.

If I just change name, the validation working but the text in text input stay. And the name is changed near the avatar.
If I just change email, its working also.

I speak about : change name or email for one user with admin account.

**Comment by Skylsmoi** [comment]
personal notes:
I have added the returns for the handler of submit for Acountjsx, not for AdminAccount.jsx.

I need to get the result http code of the submit to reset the form if success (after the await)

**Comment by inkhey** [comment]
#953 fixed in backend.

**Comment by Skylsmoi** [comment]
there is still the user name that isn't updated when changed by an admin

**Comment by PhilippeAccorsi** [comment]
Verified.
