### ISSUE TITLE
all app: if filtered in sidebar when you close app the filtered is disabled 

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#948]
At present

You have filtered by files and you look one file. When you close app you return to list off all content.

Expected

If filter is activated, after closing app you stay in filter.

**Comment by Skylsmoi** [comment]
event appClosed handled by WorkspaceContent should keep the filters in it's history.push

**Comment by PhilippeAccorsi** [comment]
Verified.
