### ISSUE TITLE
Add simple test for serve frontend to prevent broken index.mak file.

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#949]
**Describe the bug**

https://github.com/tracim/tracim/issues/945 happened probably due to a bad merge in index.mak.
Actually index.mak is untested. We should have at least a very simple test to prevent it from being broken.

**Expected behavior**

A test should check if root endpoint return http response 200  if serving frontend is enabled.

**Comment by PhilippeAccorsi** [comment]
Verified.
