### ISSUE TITLE
add user: not good workflow if email activated or not

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#950]
**at present:**

If smtp for email not activated:

Its possible to create account by all people have rights but just administators can change password for this new users.

If smtp for email is activated:

If you try to create account, if email not working this account is not create.

**Expected**

Its possible to create account all the time. If notification is not activated, just admin can create account.

~~~
After discuss with @lebouquetin 
if email is not activated in backend, make message in header to inform users "email notification not activated".
In this case, just admin can create account but all users with privilege can add member if user exist.

When email is activated:
when users want to add member, if user not exist make better workflow when you type name/email of this futur user.
the good workflow is to select in list "create this user" and when you have clicked, its not possible to modify email and you just change the role and validate.
~~~ 

reminder after discuss with @lebouquetin and @inkhey 
Backend make possibility to easly inform frontend that "email notification not activated".

**Comment by PhilippeAccorsi** [comment]
After discuss with @lebouquetin 
if email is not activated in backend, make message in header to inform users.
In this case, just admin can create account but all users with privilege can add member if user exist.

When email is activated:
when users want to add member, if user not exist make better workflow when you type name/email of this futur user.
the good workflow is to select in list "create this user" and when you have clicked, its not possible to modify email and you just change the role and validate.

**Comment by PhilippeAccorsi** [comment]
@inkhey assign @Skylsmoi when you have find and push solution to inform frontend.

**Comment by PhilippeAccorsi** [comment]
@inkhey for backend everything its ok?
if yes, can you assign skylsmoi and change label and put this issue in to do.
Thanks.

**Comment by inkhey** [comment]
@PhilippeAccorsi Yes.

**Comment by Skylsmoi** [comment]
https://github.com/tracim/tracim_v2/commit/dc9b6105cdf1509d3c4284ccd5f5dc091ab5478d

**Comment by PhilippeAccorsi** [comment]
Verified.
