### ISSUE TITLE
admin workspace: problem: size of column change if text is long

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#951]
At present

if you have workspace name or description with long text, the size of column change.

Expected

If workspace or description ihave long text, don't change column size but make same view like we have in sidebar. If we want to see all text we just need to mouseover.

**Comment by gbonaspetti** [comment]
Liked with https://github.com/tracim/tracim/issues/1781

**Comment by Skylsmoi** [comment]
Can't reproduced
Admin space page now has a overflow hidden
