### ISSUE TITLE
Endpoint /users/:id/email break cookie validity

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#953]
When changing the email, the api must return the new cookie to the frontend. Currently, at the next api call, the frontend will send an outdated one and get a 403 that will disconnect the user

**Comment by inkhey** [comment]
Problem is not outdated cookie, it's unusable cookie because cookie give access to "user_id" which is an old invalid email.

Because first auth was basic_auth, id info to get user objet in backend was always email.
That's probably a bad choice, so some refactoring is needed in backend.

**Comment by lebouquetin** [comment]
A backend test for this fix is required

**Comment by PhilippeAccorsi** [comment]
Verified.
