### ISSUE TITLE
Change the color on btnswitch

### ISSUE THREAD

**Issue by AlexiCauvin** [tracim/tracim#954]
**Now:** 

The swtich button has no color when it's active 
![image](https://user-images.githubusercontent.com/16293214/45882067-4df9ab80-bdad-11e8-94b7-c5f1b9c97485.png)

**Expected:** 

- [x] replace "inactive" - "désactivé" by "account deactivated" - "compte désactivé" (just for the first column).
- [x] Apply the theme color on the swtich button when it's active  and disabled the entire line when it's disabled

Also

- [x] remove "active" - "activé" near button

**Comment by AlexiCauvin** [comment]
Problem encountered during the resolution of this issue 

Until now, the operation of the color change on the background of the switch button was managed by the CSS. A background color was defined when the button was in the active position and another in the initial position. The problem being that the background color must be managed by the jsx (theming principle) or the jsx cannot manage the different states of the button. What solution should be adopted?

Currently, if you change the translation of the switch button in the admin users page it also changes the translation of the switch button in the account page, so the translations of the switch button on the admin users page must be specific to it.

**Comment by Skylsmoi** [comment]
fixed here https://github.com/tracim/tracim_v2/commit/bb48bdef1b54dfe99296ea044df509455bcef5c2

**Comment by PhilippeAccorsi** [comment]
Missing translation about Account deactivated

**Comment by Skylsmoi** [comment]
fixed here https://github.com/tracim/tracim_v2/commit/bb48bdef1b54dfe99296ea044df509455bcef5c2

**Comment by PhilippeAccorsi** [comment]
Verified.
