### ISSUE TITLE
add html-document: impossible because same name for one thread but no error message

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#955]
**At present**

I create thread with name "test pour reader", I try to create html-document with same name.
I have this error in console:

~~~
Unhandled promise rejection 
Response { type: "basic", url: "http://localhost:6543/api/v2/workspaces/1/contents", redirected: false, status: 400, ok: false, statusText: "Bad Request", headers: Headers, bodyUsed: false }
tracim.vendor.bundle.js:11:212572
N/</t<
http://localhost:6543/asset/tracim.vendor.bundle.js:11:212572
e.exports
http://localhost:6543/asset/tracim.vendor.bundle.js:6:95637
N/<
http://localhost:6543/asset/tracim.vendor.bundle.js:11:212449
e.exports
http://localhost:6543/asset/tracim.vendor.bundle.js:6:93434
<anonyme>
http://localhost:6543/asset/tracim.vendor.bundle.js:6:49819
g
http://localhost:6543/asset/tracim.vendor.bundle.js:6:49677
b
http://localhost:6543/asset/tracim.vendor.bundle.js:6:49697
~~~ 

**Expected**

Its impossible to create content with same name but just for one type of content.

If mimetype is same, show specific message about title.

**Comment by PhilippeAccorsi** [comment]
@inkhey @Skylsmoi I dont know if its backend or frontend problem. maybe backend first?

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi in this case, the html-doc and thread have same mimetype so its normal that I can't create 2 content with same name, but We don't see any error about this problem.

Do you think this issue solve this information problem?  https://github.com/tracim/tracim/issues/864

**Comment by Skylsmoi** [comment]
waiting for backend to be able to return specific error code because, in frontend, I can't know if the label is truly unique because of the archived and deleted contents

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi normally all error code are available.

**Comment by lebouquetin** [comment]
A retester par @PhilippeAccorsi

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi no flashmessage at present

- [ ] add flash message about error content already exist

- [ ] add french translation for flash message

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi the flash message is when you try to create new content with same label (that an another content already have)

**Comment by PhilippeAccorsi** [comment]
Verified.
