### ISSUE TITLE
shortcut key are not correctly used

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#956]
At present:
shortcut key is not used.

Expected:

- [x] If I hit enter key, I expect the validate button is activate.
- [x] if I hit escape key, it closes the app's creation popup

**Comment by Skylsmoi** [comment]
added handling for Enter key on all popup create content here: https://github.com/tracim/tracim_v2/commit/bb48bdef1b54dfe99296ea044df509455bcef5c2

**Comment by PhilippeAccorsi** [comment]
Its ok for app thread and html-document.

**Comment by PhilippeAccorsi** [comment]
Verified.
