### ISSUE TITLE
Do not send file extension in label when creating new file

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#957]
**Describe the bug**
File label is not a filename who should content file-extension as file-extension is already automatically handled by update file content endpoint. Actually extension is send during file creation.

**Expected behavior**

Do not send any file extension in label param through POST /api/v2/workspace/{workspace_id}/contents . Label should be either filename without extension part or a string given explicitly by user.

**Comment by Skylsmoi** [comment]
I need to check what I append to formData, try to remove the extension from the filename

**Comment by lebouquetin** [comment]
You MUST not remove the extension from the filename. The user upload a file myfile.extension, we MUST keep this information in the API.

**Comment by lebouquetin** [comment]
the API should use one attribute which is filename, not label

**Comment by lebouquetin** [comment]
this is a backend task to split and to manager both label + extension

**Comment by inkhey** [comment]
@lebouquetin So, we need to have both filename and label attribute in POST /api/v2/workspace/{workspace_id}/contents ?

**Comment by Skylsmoi** [comment]
see https://github.com/tracim/tracim/issues/977

**Comment by PhilippeAccorsi** [comment]
@inkhey for you, everything is done in backend?

**Comment by inkhey** [comment]
@PhilippeAccorsi yes.

**Comment by Skylsmoi** [comment]
frontend now uses the specific endpoint to post new content file
this issue is ready for testing

**Comment by PhilippeAccorsi** [comment]
Verified.
