### ISSUE TITLE
Check if profil and role is correctly applicate

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#959]
At present

Some role is not correctly applicate for user

Expected:

Respect strictly this => https://github.com/tracim/tracim_v2/blob/develop/backend/doc/roles.md

**Comment by PhilippeAccorsi** [comment]
info for role reader:
its possible: 
**dashboard**
- click on each app
- click on "add member"

**app file**
- click in "change description" in app file

**Comment by Skylsmoi** [comment]
has been fixed:
- dashboard: add member btn
- dashboard: remove user from workspace
- dashboard: btn create content
- app file: change description

**Comment by PhilippeAccorsi** [comment]
verified.
