### ISSUE TITLE
Integration new dashboard design 

### ISSUE THREAD

**Issue by AlexiCauvin** [tracim/tracim#960]
Currently we have this dashboard : 

![image](https://user-images.githubusercontent.com/16293214/45947502-c9996980-bff4-11e8-8541-080254021d3a.png)

Expected : 

![dashboard new design v2 0 final prototype](https://user-images.githubusercontent.com/16293214/45947522-df0e9380-bff4-11e8-8a29-79b11522c716.png)

**Comment by AlexiCauvin** [comment]
The new dashboard with description  : 
![dashboard_description](https://user-images.githubusercontent.com/16293214/46021239-80264880-c0e0-11e8-834e-85d0e0471133.PNG)

The new dashboard without description : 
![dashboard_sans_description](https://user-images.githubusercontent.com/16293214/46021260-8ddbce00-c0e0-11e8-991c-9125f9e7cc1e.PNG)

**Comment by PhilippeAccorsi** [comment]
Verified.
