### ISSUE TITLE
app_advanced_workspace: translation not working in option list of role

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#963]
At present

If you show list of role about one member you can see text all the time in english

Expected

Translation of this list is working.

**Comment by Skylsmoi** [comment]
fixed here https://github.com/tracim/tracim_v2/commit/bb48bdef1b54dfe99296ea044df509455bcef5c2

**Comment by PhilippeAccorsi** [comment]
Verified.
