### ISSUE TITLE
Reactivate "same file content" check 

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#964]
**Describe the bug**
"Same file content" check is broken due to pyramid behaviour (return specific buffered object instead of bytes directly). It was disabled in https://github.com/tracim/tracim_v2/pull/47/commits/6c0020966f52b2086acf9e1346a8cf5c951e2f45 waiting for a solution to https://github.com/tracim/tracim/issues/566.

**Expected behavior**
Reenabled same file content check with better file check mecanism.

**Comment by tracim** [comment]
At the moment, My feeling is that not comparing bytes is fine.

**Comment by Skylsmoi** [comment]
It has never been an issue
We won't reactivate this check
closing the issue
