### ISSUE TITLE
login page: flash message about disconnect is visible all the time

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#966]
At present

When you go on http://localhost:6543/ you are directly redirect to  http://localhost:6543/login?dc=1  with flash message:

~~~
Information
You have been disconnected, please login again
~~~

Expected

If you don't have use tracim before, you are not redirected to http://localhost:6543/login?dc=1  and you have normal login page without any flashmessage.

**Comment by Skylsmoi** [comment]
https://github.com/tracim/tracim_v2/commit/9e158960cc66f934ec4fd7b3ea1dbe157ef44b24

**Comment by PhilippeAccorsi** [comment]
Verified.
