### ISSUE TITLE
mouseover not working for date and time

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#969]
At present

If you mouseover text about date and time you don't see anything.

Expected

If you mouseover you see exact date and time.

**Comment by Skylsmoi** [comment]
this has been fixed for the timeline in a recent commit

**Comment by PhilippeAccorsi** [comment]
b3f11026c6f2a9bc55a3cb40fcc20a88238cc592

**Comment by PhilippeAccorsi** [comment]
Verified.
