### ISSUE TITLE
new dashboard: some modification needed

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#974]
- [x] (rôle et notifications) :
il y a 2 polices différentes utilisées (ou en tout cas ça n'est pas la même taille) => à corriger
- [x] il faudrait mettre une bulle au survol du rôle avec comme texte : "votre rôle dans l'espace partagé" - "your role in the shared space")
- [x] il faudrait remplacer le texte "abonné" par "abonné aux notifications". Ca s'écrira sur 2 lignes mais c'est très bien
- [x] test not ok
- [x] il faudrait mettre une bulle au survol de "abonné aux notifications" indiquant "vous pouvez changer votre statut de notification en cliquant ici"
- [x] il faudrait un "hover" avec une couleur différente sur le "bouton" "abonné aux notifications" (actuellement, ça n'est pas immédiat qu'on peut changer le statut d'abonnement)
- [x] autre point sur le dashboard (pas lié au nouveau design) : "discuter d'un sujet" en français ça se dit plutôt "lancer une discussion"

**Comment by PhilippeAccorsi** [comment]
@lebouquetin what do you think about this 2 versions:

**Tracim_v1 (with mouse over in admin/workspace)**
Vous êtes abonné(e) aux notifications par email <=> Vous n'êtes pas abonné(e) aux notifications par email
Email notifications subscribed <=> Email notifications desactivated

**Tracim_v2 (visible directly in dashboard)**
Subscribed to the notifications <=> Unsubscribed to the notifications
Abonné(e) aux notifications <=> Désabonné(e) aux notifications ("aux" replaced by "des" tomorrow)

Do you prefer

**Comment by Skylsmoi** [comment]
"desactivated" actually doesn't exists, it's "deactivated"

**Comment by PhilippeAccorsi** [comment]
Verified.
