### ISSUE TITLE
create a endpoint to create content type file

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#977]
Usually, we use the endpoint POST /workspaces/{workspace_id}/contents to create the content ; then the specific one to edit the content.
For file it is /workspaces/{workspace_id}/files/{content_id}/raw

But it generate some issues regarding the filename.

Solution: create a specific endpoint to create content type file

Proposition:
POST /workspace/{workspace_id}/files

it should return the same object as the endpoint POST /workspaces/{workspace_id}/contents

**Comment by PhilippeAccorsi** [comment]
Verified.
