### ISSUE TITLE
Sidebar bug in responsive mode 

### ISSUE THREAD

**Issue by AlexiCauvin** [tracim/tracim#979]
the correction of a bug on the dashboard caused a modification on the sidebar. However, the problem is that this fix creates another more important bug on the sidebar

the following image is the original bug (a blank margin at the bottom of the page)  :  
![image](https://user-images.githubusercontent.com/16293214/46292489-51511c00-c591-11e8-951a-6d0b6828c6e8.png)

The following image is the new bug that appeared with the fix : 
![image](https://user-images.githubusercontent.com/16293214/46293208-164fe800-c593-11e8-9511-2f2757006e93.png)

**Comment by PhilippeAccorsi** [comment]
Verified.
