### ISSUE TITLE
Responsive on SmartPhone

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#980]
At present

On smartphone you cn't change title of content because button is not visible.

Expected

Its possible to change title of content with button.

**Comment by PhilippeAccorsi** [comment]
@AlexiCauvin I think its a good Idea to check together directly on smartphone and pad if all function is accessible or not.

**Comment by AlexiCauvin** [comment]
https://github.com/tracim/tracim_v2/commit/bb7581d60327411037a970df043d51a7a35607c6

**Comment by PhilippeAccorsi** [comment]
Verified.
