### ISSUE TITLE
Clarify production and dev build for frontend build script

### ISSUE THREAD

**Issue by inkhey** [tracim/tracim#985]
**Describe the bug**
i get  "is_production = True " during building of frontend by node.

**Expected behavior**
Allow to easily set build mode and add clear doc about how to select between production and dev mode.

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi is it still active?
It is for tracim_v2.0 ?

**Comment by Skylsmoi** [comment]
yes this is still valid
I don't if we should include it in 2.0

**Comment by raphj** [comment]
It is being fixed in #3017:
 - the `-d` flag allows enabling the development mode
 - the development mode enables source maps
 - `isProduction: true` is not printed anymore during the compilation (this print was breaking some Webpack tools)

**Comment by Skylsmoi** [comment]
@raphj what was it breaking ? I'm curious

**Comment by raphj** [comment]
@Skylsmoi it broke `webpack --json`. Witch is useful with https://github.com/robertknight/webpack-bundle-size-analyzer for instance:

```
yarn run webpack --json | webpack-bundle-size-analyzer
```

**Comment by Skylsmoi** [comment]
docs are:
- https://github.com/tracim/tracim/blob/develop/doc/frontend/app_building.md
- https://github.com/tracim/tracim/blob/develop/doc/frontend/yarn_scripts.md

closing the issue
