### ISSUE TITLE
Update password lost url in email

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#986]
Actual url is something like `http://localhost:6543/reset-password-request/34109079-c706-4bf0-8d03-b5ac28640220`.

We want url like: /reset_password

**Comment by Skylsmoi** [comment]
I also need the email in the url

**Comment by buxx** [comment]
PR: https://github.com/tracim/tracim_v2/pull/83

**Comment by PhilippeAccorsi** [comment]
Verified.
