### ISSUE TITLE
backend config parameter email.notification.activated is used for other things than notifications

### ISSUE THREAD

**Issue by Skylsmoi** [tracim/tracim#987]
When developing the forget password feature, when trying the email, I got a 400 error staging that email cannot be sent because email notifications are disabled.

To reproduce, set email.notification.activated to false and try the forgot password feature (not yet pushed)

**Comment by Skylsmoi** [comment]
frontend is already aware of whether mails are activated or not

so we only need to hide the "forget password" button when emails are deactivated. Maybe we should replace it by an information to help users that actually forgot their password, something like:
`<button>Forgot password<button>` => redirect to a page that says: `Please contact an admin to get a new password`

**Comment by lebouquetin** [comment]
This issue is already fixed in tracim 2.1.0
