### ISSUE TITLE
app file: if you edit a file you are not redirected to the file preview

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#989]
at present

if i edit file, after validate the page stay in edit.

Expected

after validate you are redirect to preview of file.

**Comment by Skylsmoi** [comment]
@PhilippeAccorsi I can't reproduce neither on local nor on lastest. Can you test that issue again and close it if you can't reproduce either ?

**Comment by PhilippeAccorsi** [comment]
i can't reproduce this Issue.

**Comment by PhilippeAccorsi** [comment]
issue.
