### ISSUE TITLE
impossible de supprimer un folder après l'avoir crée

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#99]
Le navigateur répond "Folder non vide"

**Comment by buxx** [comment]
Lorsque l'on demande à son client de fichier de supprimer le répertoire en question, il demande d'abord  quels sont les fichiers à l'interieur. Puis demande la suppression de ceux-ci.

Après ces demandes de suppressions, il re-demande la liste des fichiers contenus, comme l'api répond toujours qu'il reste les répertoires .archived .deleted etc, il ne demande pas la suppression du répertoire puisqu'il n'est pas vide.

Le problème c'est que les requêtes où il demande quels sont les fichiers à l'interieur est indépendante, on ne peux pas la relier au fait qu'elle est au sein d'une demande de suppression.

Une solution qui m’apparaît c'est de stocker en base la date de la dernière demande de suppression des .archived, .deleted, etc de façon à ne pas les retourner pendant X secondes. L'explorateur de fichier pourra considéré le dossier comme vide et fera la demande de suppression.

**Comment by lebouquetin** [comment]
Il me semble qu'Arnaud avait géré ce genre de problème, non ? Il faut aussi distinguer les dossiers à la racine (qui sont des espaces de travail dans tracim) et les sous-dossiers (qui sont des dossiers). Le comportement n'est pas le même ; je pense qu'il y a une distinction à faire en terme d'ergonomie.

Vous avez une idée de comment faire cette distinction ?

**Comment by Nonolost** [comment]
Par rapport au problème du dossier non-vide, c'était un problème qui restait effectivement et est normal car je n'avais pas de fix 'propre'. On avait parlé de garder en mémoire la date de demande de suppression du sous-dossier pour s'en servir mais comme c'était pas forcément très propre je n'avais pas appliqué cette solution.

Pour la distinction espace de travail / dossier 'normaux', il n'y a pas de problèmes de distinction. Lorsqu'une requête est appelé sur un chemin, il va récupérer la ressourcé liée. Si j'appelle avec '/workspace' je vais avoir un item 'workspace', donc je le traite comme tel (et les fonctions delete etc... sont spécifiques à cette ressource dans le code) et si j'appelle avec '/workspace/dossier' il va avoir un item 'dossier' et donc il a accès aux méthodes spécifiques de la ressource.

**Comment by buxx** [comment]
En effet cette discussion me revient. On fera certainement un mécanisme dans ce genre. Pour le distinction entre workspace et dossier oui en effet ça fonctionne bien.

**Comment by buxx** [comment]
@lebouquetin Comme nous avons désactivé les dossiers .archived, .deleted de manière temporaire (pour la beta 1.0), la suppression de répertoire est désormais possible. Puis-je enlever la milestone beta 1.0 de cette issue ?

**Comment by algooapy** [comment]
Verification done: we are able to delete a folder from WebDAV just after creating it.

**Comment by PhilippeAccorsi** [comment]
@philippe à tester.
