### ISSUE TITLE
How does the auth mechanism work ?

### ISSUE THREAD

**Issue by buxx** [tracim/tracim#993]
I was reading auto generated tracim v2 backend documentation and i asked myself: How give auth information during api discussions ?

I think it is missing in documentation. It should be added in (possible locations):

* backend README.md
* backend auto generated doc in global description
* backend auto generated doc in each api path request headers + returned headers in `/api/v2/sessions/login`.

**Comment by tracim** [comment]
This documentation must be part of the basic documentation "Howto interact with tracim API"

**Comment by inkhey** [comment]
@buxx @lebouquetin can I've done a documentation about using api. Not sure if this is enough, not sure about what the meaning of the issue (more technical stuff about auth mecanism, a figure ?)

Also this documentation do not explain setup of auth mecanism, but another PR add some doc about it, see here : https://github.com/tracim/tracim/pull/1338.

**Comment by buxx** [comment]
The goal of issue is to enhance documentation about auth mechanisms. Wrote documentation about api is ok for me. Additional: 

We can add a link to this documentation into generated api doc.

**Comment by PhilippeAccorsi** [comment]
Verified.
