### ISSUE TITLE
member list: don't show the deactivated members.

### ISSUE THREAD

**Issue by PhilippeAccorsi** [tracim/tracim#997]
At present

If you deactivate one user, you can't use tracim with this account but in workspace you can seen this user.

Expected:

in member list, just show active users.

**Comment by Skylsmoi** [comment]
@lebouquetin @inkhey Shouldn't this be a backend issue ? Like adding a query parameter to the endpoint to display or not deactivated members ?

**Comment by Skylsmoi** [comment]
or not, there is already the "is_active" property.
I guess frontend should filter on it

**Comment by Skylsmoi** [comment]
@inkhey form to add user should not autocomplete deactivated users.
This is a backend issue.
Endpoint /users/:id/known_members

**Comment by PhilippeAccorsi** [comment]
@Skylsmoi its merged.

**Comment by PhilippeAccorsi** [comment]
Verified.
