### ISSUE TITLE
Contents in validated status can be updated

### ISSUE THREAD

**Issue by tracim** [tracim/tracim#999]
Currently : 

- when a content is in validated status the edit button is still active.
- a new revision can be uploaded
- the behavior is also viewed in documents and threads.

Expected :

- [x]  disable edit button if the status is not editable (ie not "work in progress")

- [x]  check the status in API before to accept a modification (this is also the case for updating the title)

Todo:

- [X] [backend] add `is_editable` property in content APIs: `/files/{id}`,`/threads/{id}`, `/html-documents/{id}`
- [x] [frontend] use this property to activate or deactivate write access to : label modification, content modification, comment access

**Comment by inkhey** [comment]
à propos des contenu éditable ou non (de @lebouquetin): 
>  un contenu "readonly", intuitivement je me dis que c'est une propriété du contenu et donc que ça n'a pas vraiment de raison de bouger editable / not éditable, ça laisse penser que c'est un état (et donc que ça peut changer)

> 
> à terme j'imagine bien des documents ReadOnly (donc toujours not editable) et des documents "normaux" qui peuvent être editables ou non éditable en fonction de leur statut, du fait qu'ils sont supprimés, archivés, etc
> 
> en fait du coup il y a bien une différence ; et c'est editable/not editable qui nous intéresse, là
> 

> (editable / not editable n'est pas une propriété du contenu mais un état lié au contexte -> le code doit être intégré ailleurs que dans la classe content)

**Comment by Skylsmoi** [comment]
@lebouquetin nothing has been implemented about status  
Are we sure want to add custom intelligence about status ?  
If I fix this issue, should I also do the same for any content type ?

**Comment by PhilippeAccorsi** [comment]
@lebouquetin we have add custom intelligence to archive and delete button (in frontend) but do you think we need to add this also in backend?

Do we need to make control in backend all the time for all app with status and archive and delete?

**Comment by PhilippeAccorsi** [comment]
@inkhey @Skylsmoi After discuss with @lebouquetin 

Backend need to check status or if content is archive or delete before accept modification when its possible.
Frontend block some functionnality for better user experiance but if we not use frontend, API apply this rules.

All rules need to be apply first in backend.

**Comment by inkhey** [comment]
this issue fix in backend created bug with contentApi, is_editable was not able with deleted/archived content to get is_editable value.

**Comment by PhilippeAccorsi** [comment]
Verified.
